### ISSUE TITLE
pillar targeting using pillar with git_pillar backend

### ISSUE THREAD

**Issue by vquiering** [saltstack/salt#52567] opened 2019-04-16 21:16 UTC
### Description of Issue/Question
Whenever I try to target minions using pillar in pillar top.sls with `git_pillar` as backend I get the following error message.

```
2019-04-16 22:58:51,680 [salt.pillar      :984 ][ERROR   ][17607] Exception caught loading ext_pillar 'git':
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 974, in ext_pillar
    key)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 902, in _external_pillar_data
    *val)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/git_pillar.py", line 474, in ext_pillar
    local_pillar.compile_pillar(ext=False),
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 1018, in compile_pillar
    matches = self.top_matches(top)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 675, in top_matches
    self.opts.get('nodegroups', {}),
  File "/usr/lib/python2.7/dist-packages/salt/matchers/confirm_top.py", line 36, in confirm_top
    return m(match)
  File "/usr/lib/python2.7/dist-packages/salt/matchers/compound_match.py", line 97, in match
    six.text_type(matchers['{0}_match.match'.format(engine)](*engine_args, **engine_kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/matchers/pillar_match.py", line 26, in match
    __opts__['pillar'], tgt, delimiter=delimiter

2019-04-16 22:58:51,682 [salt.pillar      :1036][CRITICAL][17607] Pillar render error: Failed to load ext_pillar git: u'pillar'
```
In `salt/matchers/pillar_match.py` I edited the corresponding line as following since I couldn‘t find `'pillar'` in `__opts__`.
```
diff --git a/salt/matchers/pillar_match.py b/salt/matchers/pillar_match.py
index 5bb9cc8ae2..37aeb643f3 100644
--- a/salt/matchers/pillar_match.py
+++ b/salt/matchers/pillar_match.py
@@ -21,5 +21,5 @@ def match(tgt, delimiter=DEFAULT_TARGET_DELIM):
                   'statement from master')
         return False
     return salt.utils.data.subdict_match(
-        __opts__['pillar'], tgt, delimiter=delimiter
+        __opts__['ext_pillar'], tgt, delimiter=delimiter
     )
```

I know this can't be the solution. 😄
Is this related to #52122, #51934 and #52266?
Is this fixed in the next release?

### Setup
master config, no pillar_roots
```
ext_pillar:
  - gitstack:
    - master git@gitlab.example.com:group/pillar-gitstack.git:
      - stack:
        - minions.cfg # This is where I define roles per minion
        - stack.cfg
  - git:
    - master git@gitlab.example.com:group/pillar-gitstack.git:
      - privkey: "/root/.ssh/id_rsa"
      - pubkey: "/root/.ssh/id_rsa.pub"
  - git:
    - master git@gitlab.example.com:group/pillar.git:
      - privkey: "/root/.ssh/id_rsa"
      - pubkey: "/root/.ssh/id_rsa.pub"
```

pillar top.sls
```
base:
  '*':
    - foo
  'I@roles:web':
    - match: compound
    - bar
  'roles:web':
    - match: pillar # works neither way
    - bar
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.5 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-7-amd64
         system: Linux
        version: debian 9.5 
```

**Comment by Ch3LL** [comment] 2019-04-26 14:53
this seems to be a duplicate of https://github.com/saltstack/salt/issues/52122

if you try the head of 2019.2 does this resolve the issue for you?

**Comment by Ch3LL** [comment] 2019-04-26 14:54
actually if you could test the head of 2019.2.1 as that is what will be released for 2.1

**Comment by vquiering** [comment] 2019-10-26 19:32
@Ch3LL, sorry for the late reply. Tested with 2019.2.1 and 2019.2.2. Still the same issue.

**Comment by Ch3LL** [comment] 2019-12-03 15:30
thanks for trying that. What is the exact command you are using to target the minions?

**Comment by vquiering** [comment] 2019-12-03 20:03
@Ch3LL 
What I actually do is `salt-call pillar.items` on the minion. I get all pillar data from the gitstack part but not from `top.sls`.

    local:
        ----------
        _errors:
            - Failed to load ext_pillar git: u'pillar'
        gitstack:
          foo: bar

Editing `salt/matchers/pillar_match.py` as stated above still works perfectly.

**Comment by vquiering** [comment] 2019-12-12 17:23
@Ch3LL 
I just created #55624 which fixes my issue. Can you please check?

**Comment by Ch3LL** [comment] 2019-12-18 16:03
one thing i noticed in this issue when re-reviewing is i never asked if you have `ext_pillar_first` set? pillar would not be available to the pillar top file as it hasn't been rendered yet, except for in the case when we ensure  ext pillar is rendered first with `ext_pillar_first` set. This PR https://github.com/saltstack/salt/pull/52851 ensures this works correctly.

**Comment by vquiering** [comment] 2019-12-18 19:59
@Ch3LL 
`ext_pillar_first` has always been set with every test command. `__opts__['pillar']` just doesn't exist.

**Comment by Ch3LL** [comment] 2019-12-19 15:21
hmmm this PR https://github.com/saltstack/salt/pull/52851 was what fixed it for me in 2019.2.1

i believe you said that you verified with 2.1 but any chance you can verify with just that PR? sorry for the one more ask.

**Comment by vquiering** [comment] 2019-12-19 19:57
I just tested the PR. Nothing has changed.

**Comment by waynew** [comment] 2020-01-16 02:15
closing since your PR was merged

**Closed** 2020-01-16 02:14 UTC
Labels: Info Needed
