### ISSUE TITLE
sudo_password Doesnt work in Salt-Cloud (saltify)

### ISSUE THREAD

**Issue by FeatherKing** [saltstack/salt#14258] opened 2014-07-15 21:59 UTC
I am trying to boostrap a few hundred vms via salt-cloud's saltify provider. I have a password similar to q4BKSNi>(<2q. 
When I put this in my cloud profile like so
```
sudo_password: q4BKSNi>(<2q
```

According to debug, the initial login via ssh works using this password but when elevating for any tasks using sudo the password does not work. I have tried removing all special characters from the password and it still fails to bootstrap (or create any folders or anything).

If i set `sudo: False` and comment remove the `sudo_password`, the bootstrap makes it much further including creating a few folders before failing because it needs permissions.

**Comment by rallytime** [comment] 2015-10-19 19:57
@FeatherKing I have tested this functionality on our latest 2015.8.1 release and I was able to get this to work very well. I also tested this on 2015.5.6 and 2014.7.7 which were also recently tagged and it worked there as well. I am thinking something might have been fixed in the mean time since you were attempting this on the 2014.1 branch.

Can you test this on a newer version of Salt and let us know if you're running into any problems still?

**Comment by rallytime** [comment] 2015-12-08 00:16
Since we didn't receive a response here, and I am unable to reproduce the issue on newer versions of Salt, I am closing this issue. Please let us know if this remains a problem and we'll be glad to reopen.

**Closed by rallytime** 2015-12-08 00:16 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P4, RIoT, Salt-Cloud

**Comment by NdK73** [comment] 2023-08-23 07:44
Testing on 3005.2 and it hangs at sudo password prompt.
Might it be a language issue? If I change system language to 'C', it starts working.
