### ISSUE TITLE
[BUG] state.apply fails in some combinations on 3006

### ISSUE THREAD

**Issue by mmulqueen** [saltstack/salt#64241] opened 2023-05-05 14:56 UTC
**Description**

When calling state.apply SLS rendering fails with a cryptic error message, but only if I try to apply the state file along with at least one more state file.

The bug here probably isn't state.apply itself, but that the error message is pretty useless or that an earlier error isn't properly cleaned up after.

**Setup**

Minion:
OS: Ubuntu 22.04, fully upgraded.
Salt minion: Onedir installed today with salt-bootstrap. 3006.0
On prem hardware. AMD64

Master: Mature installation, running 3005.1

I don't think the SLS files are actually relevant, they render fine elsewhere, see my comments about reproducing.

**Steps to Reproduce the behavior**

I believe that the error occurs in another state (state_a) but for some reason only occurs when trying to render this state (state_b). The order of the states doesn't seem to matter. Combinations without errors seem to work (e.g. state_b,state_c)

I suspect, but I can't be sure that this is related to #64118 occurring in state_a and perhaps it's not getting cleaned up properly after the error. If applied alone, the SLS for state_a will render, but a state inside it will fail because of the bug I mentioned. If state_a and state_b are applied together, the SLS for state_b will fail to render.

```bash
salt-call state.apply  # Error
salt-call state.apply state_b # OK
salt-call state.apply state_a,state_b # Error
salt-call state.apply state_b,state_a # Error
salt-call state.apply state_b,state_c # OK
salt-call state.apply state_a,state_c # OK
```

This is the kind of error I'm seeing

```


    Data failed to compile:
----------
    Rendering SLS 'base:state_b' failed: Jinja error: 'NoneType' object has no attribute 'done'
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/templates.py", line 471, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/jinja.py", line 185, in get_source
    self.check_cache(_template)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/jinja.py", line 138, in check_cache
    ret = self.cache_file(template)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/jinja.py", line 131, in cache_file
    return fcl.get_file(saltpath, "", True, self.saltenv)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1167, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1414, in hash_and_stat_file
    hash_result = self.hash_file(path, saltenv)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1407, in hash_file
    return self.__hash_and_stat_file(path, saltenv)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1399, in __hash_and_stat_file
    return self.channel.send(load)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/asynchronous.py", line 125, in wrap
    raise exc_info[1].with_traceback(exc_info[2])
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/asynchronous.py", line 131, in _target
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/ioloop.py", line 457, in run_sync
    if not future_cell[0].done():
AttributeError: 'NoneType' object has no attribute 'done'

; line 1

---
{% from "state_b/map.jinja" import xyz with context %}    <======================

[...]
```

**Expected behavior**
The SLS should render.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0
 
Python Version:
        Python: 3.10.11 (main, Apr 14 2023, 05:57:16) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.11.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.19.0-41-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
 

```
</details>

**Additional context**
Works fine on other minions, but this may be the only minion running 3006, everything else is still on 3005.

**Comment by s0undt3ch** [comment] 2023-05-05 18:01
This is a duplicate of https://github.com/saltstack/salt/issues/64111 and is fixed in the upcoming 3006.1 release.

**Closed by s0undt3ch** 2023-05-05 18:01 UTC
Labels: Bug, needs-triage
