### ISSUE TITLE
salt-cloud fails intermittently because it can't create a directory or set perms

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#13341] opened 2014-06-09 21:01 UTC
I'm getting 2 intermittent errors with salt-cloud

```
root@dockmaster:~# salt-cloud -m /etc/salt/docker.do.map -P
[INFO    ] salt-cloud starting
[INFO    ] Applying map from '/etc/salt/docker.do.map'.
<-- snip -->
[INFO    ] Rendering deploy script: /etc/salt/cloud.deploy.d/bootstrap-salt.sh
[ERROR   ] Failed to deploy 'docker09'. Error: Cant create temporary directory in /tmp/.saltcloud !
Traceback (most recent call last):
  File "/root/salt/salt/cloud/__init__.py", line 2086, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/root/salt/salt/cloud/__init__.py", line 1162, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/digital_ocean.py", line 445, in create
    deployed = salt.utils.cloud.deploy_script(**deploy_kwargs)
  File "/root/salt/salt/utils/cloud.py", line 999, in deploy_script
    'directory in {0} !'.format(tmp_dir)
SaltCloudSystemExit: Cant create temporary directory in /tmp/.saltcloud !
[ERROR   ] Failed to deploy 'docker18'. Error: Cant create temporary directory in /tmp/.saltcloud !
Traceback (most recent call last):
  File "/root/salt/salt/cloud/__init__.py", line 2086, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/root/salt/salt/cloud/__init__.py", line 1162, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/digital_ocean.py", line 445, in create
    deployed = salt.utils.cloud.deploy_script(**deploy_kwargs)
  File "/root/salt/salt/utils/cloud.py", line 999, in deploy_script
    'directory in {0} !'.format(tmp_dir)
SaltCloudSystemExit: Cant create temporary directory in /tmp/.saltcloud !
[ERROR   ] Failed to deploy 'docker20'. Error: Cant create temporary directory in /tmp/.saltcloud !
Traceback (most recent call last):
  File "/root/salt/salt/cloud/__init__.py", line 2086, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/root/salt/salt/cloud/__init__.py", line 1162, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/digital_ocean.py", line 445, in create
    deployed = salt.utils.cloud.deploy_script(**deploy_kwargs)
  File "/root/salt/salt/utils/cloud.py", line 999, in deploy_script
    'directory in {0} !'.format(tmp_dir)
SaltCloudSystemExit: Cant create temporary directory in /tmp/.saltcloud !
[ERROR   ] Failed to deploy 'docker01'. Error: Cant set perms on /tmp/.saltcloud/minion.pem
Traceback (most recent call last):
  File "/root/salt/salt/cloud/__init__.py", line 2086, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/root/salt/salt/cloud/__init__.py", line 1162, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/digital_ocean.py", line 445, in create
    deployed = salt.utils.cloud.deploy_script(**deploy_kwargs)
  File "/root/salt/salt/utils/cloud.py", line 1021, in deploy_script
    'Cant set perms on {0}/minion.pem'.format(tmp_dir))
SaltCloudSystemExit: Cant set perms on /tmp/.saltcloud/minion.pem
[ERROR   ] Failed to deploy 'docker13'. Error: Cant set perms on /tmp/.saltcloud/minion.pem
Traceback (most recent call last):
  File "/root/salt/salt/cloud/__init__.py", line 2086, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/root/salt/salt/cloud/__init__.py", line 1162, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/digital_ocean.py", line 445, in create
    deployed = salt.utils.cloud.deploy_script(**deploy_kwargs)
  File "/root/salt/salt/utils/cloud.py", line 1021, in deploy_script
    'Cant set perms on {0}/minion.pem'.format(tmp_dir))
SaltCloudSystemExit: Cant set perms on /tmp/.saltcloud/minion.pem
[INFO    ] Salt installed on haproxy01
[INFO    ] Created Cloud VM 'haproxy01'
[INFO    ] Salt installed on docker07
<-- snip -->
```

I have to destroy the vms and try to rebuild them.
I've had this happen on Rackspace and DigitalOcean. The snippet above is from an attempt to build them on DigitalOcean on Ubuntu 12.04.

Here's the output of test.versions_report on one of the successfully deployed vms:
```
docker10:
               Salt: 2014.1.0-7237-gb017cab
             Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
             Jinja2: 2.6
           M2Crypto: 0.21.1
     msgpack-python: 0.1.10
       msgpack-pure: Not Installed
           pycrypto: 2.4.1
             PyYAML: 3.10
              PyZMQ: 13.0.0
                ZMQ: 3.2.2
```
Here's the versions report for the Salt Master:
```
root@dockmaster:/etc/salt# salt-master --versions-report
           Salt: 2014.1.0-7233-gf74febd
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

I wonder if there's a race condition here.

**Comment by rallytime** [comment] 2015-06-02 21:19
@UtahDave or @marnovdm Are either of you still seeing this on newer versions of Salt? I know numerous fixes have gone into salt-cloud since this was filed and I can't reproduce the failure. (Though I know that is difficult since it's a race condition, but I think this may be fixed.)

**Comment by rallytime** [comment] 2015-06-02 21:20
Oh, also note that I was testing this on digital ocean, using the new API. I also could get this to trigger on Rackspace either....

**Comment by rallytime** [comment] 2015-06-16 23:21
Since I can't reproduce this and I didn't hear back, I am going to close this. If it pops up again, please leave a comment and we can re-open the issue and address any concerns.

**Closed by rallytime** 2015-06-16 23:21 UTC
Labels: Bug, Fixed Pending Verification, High Severity, Integrations, P2, Salt-Cloud
