### ISSUE TITLE
systemd version check failing on debian testing

### ISSUE THREAD

**Issue by shish** [saltstack/salt#52782] opened 2019-05-01 19:49 UTC
### Setup
Be using latest debian testing (aka buster, due to become stable in a couple of months IIRC)

### Steps to Reproduce Issue
salt-call state.highstate

As far as I can tell, the code to parse "systemctl --version" doesn't like the new format:

```
# systemctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

### Versions Report
```
# salt-call --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Apr  6 2019, 01:42:57)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1

System Versions:
           dist: debian buster/sid
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-2-amd64
         system: Linux
        version: debian buster/sid
```

**Comment by shish** [comment] 2019-05-01 19:56
(Just realised that I'd somehow lost /etc/apt/sources.list.d/salt-stack.list so I'd been stuck on 2018.3, but it seems 2019.2 has a very similar issue)

**Comment by waynew** [comment] 2019-05-03 20:43
Do you need any particular state file or is just calling `state.highstate` enough?

**Comment by waynew** [comment] 2019-05-31 22:01
@shish I'm going to close this as a dupe of #51745. If that fix doesn't solve your problem, let me know and I'll re-open this.

**Closed by waynew** 2019-05-31 22:01 UTC
Labels: Bug, Pending Discussion
