### ISSUE TITLE
[BUG] contextvars depenendecy for Python < 3.7 only

### ISSUE THREAD

**Issue by mtelka** [saltstack/salt#64972] opened 2023-08-13 07:10 UTC
`contextvars` was added to Python 3.7 (see https://docs.python.org/3/library/contextvars.html), but `salt` still needs the standalone [contextvars](https://pypi.org/project/contextvars/) even for Python >= 3.7 (see https://github.com/saltstack/salt/blob/master/requirements/base.txt#L12).

I suggest to change the dependency to something like
```
contextvars ; python_version < '3.7'
```
in the [requirements/base.txt](https://github.com/saltstack/salt/blob/master/requirements/base.txt) file.

**Comment by s0undt3ch** [comment] 2023-08-13 17:06
Closing as duplicate of https://github.com/saltstack/salt/issues/64493

**Closed by s0undt3ch** 2023-08-13 17:06 UTC
Labels: Bug, needs-triage
