### ISSUE TITLE
salt-minion is stuck in a restart loop with not much info:

### ISSUE THREAD

**Issue by esn89** [saltstack/salt#32472] opened 2016-04-11 09:04 UTC
### Description of Issue/Question
salt-minion daemon is stuck in a restart loop

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
- no sls files as minion doesn't even start.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
- I just run `salt-minion -l debug` and that happens
- `salt-minion -l debug` log:
https://paste.debian.net/432104/

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
(I only installed the salt-minion and salt-common package on this server as it is a minion machine)
- `salt-minion --versions-report` log:
https://paste.debian.net/432105/
- `strace salt-minion -l debug 2> log`:
warning, 9000 lines file:  http://ix.io/vSv/#n-LINENO

**Comment by lewandom** [comment] 2016-04-11 14:23
I just found out the same with the exact same minion version on RHEL 6.7.

**Comment by esn89** [comment] 2016-04-11 18:12
So I'm not alone here?

**Comment by jfindlay** [comment] 2016-04-11 20:37
@esn89, @lewandom, thanks for reporting.  How did you install salt-minion.  Did you set any config files?  What is the strace during the restart loop?  I only see one (re)start in the provided strace.  Can you reproduce the issue on another system or is there any other information you suspect may help us to reproduce this?

**Comment by esn89** [comment] 2016-04-12 06:24
@jfindlay, 

- I installed this via the repo.saltstack.com
- The config files I set are found here:  https://paste.debian.net/432311/
- The strace seems to just repeat itself if it's a restart loop, no?
- I have not been able to reproduce this with my vagrant + Ubuntu 12.04 box.  It seems to work fine there.  To be fair, with the vagrant set up, the minions and masters are all on local host.

- To trouble shoot the master host resolution, I did:   `nc -vz <hostname>` on the minions and the port and ip connected successfully, so it isn't a connection issue.

**Comment by lewandom** [comment] 2016-04-12 06:53
I did the installation with the bootstrap script, without any args (we have the master at "salt"). After installing all the prereqs, in the end:
```
Installed:
  salt-minion.noarch 0:2015.8.8-2.el6                                           

Dependency Installed:
  pciutils.x86_64 0:3.1.10-4.el6           python-futures.noarch 0:3.0.3-1.el6  
  python-markupsafe.x86_64 0:0.11-10.el6   python-tornado.x86_64 0:4.2.1-1.el6  
  salt.noarch 0:2015.8.8-2.el6            

Complete!
 *  INFO: Running install_red_hat_enterprise_linux_stable_post()
 *  INFO: Running install_red_hat_enterprise_linux_restart_daemons()
Starting salt-minion daemon: 
```
and then it goes hang.
I'm able to reproduce this continuously using the same virtual image (OpenStack/KVM).
What's weird about this issue is I think the "Minion failed to start" message should be followed by a traceback indicating the exact failure cause, but here it is not.
nc works okay so it's not a connectivity problem, definitely.

**Comment by jfindlay** [comment] 2016-04-12 15:59
@esn89, what is not clear to me is what portion of the strace is included in the repeat, even though it seems that it would not be conclusive in this case.

**Comment by esn89** [comment] 2016-04-13 06:38
@jfindlay 
Here is the log with a more lines:
http://ix.io/wuY/#n-LINENO

**Comment by esn89** [comment] 2016-04-14 08:25
if it helps your debugging process, i installed salt-minion 5.3 (Lithium) and it works.

**Comment by cachedout** [comment] 2016-04-29 17:34
@esn89 The config files you posted are no longer in the pastebin. Could you repaste them here, please?

**Comment by michaelgibson** [comment] 2016-04-29 20:32
Also experiencing this issue on el7 using community yum repos but only if I try to use the raet transport.
Using zeromq seems to work fine.

salt-minion --versions-report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 21 2015, 00:39:04)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.8
        libgit2: Not Installed
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

**Comment by Timandes** [comment] 2016-04-29 21:22
I have some machines using el6 who also were upgraded to 2015.8.8.2, but they work fine. Only el5s stuck.

**Comment by esn89** [comment] 2016-05-02 07:06
@cachedout 

I have lost that config since I have moved to an older version of salt-minion.

**Comment by Timandes** [comment] 2016-05-02 10:09
```
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "t.erm1"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] The Salt Minion is starting up
[INFO    ] The Salt Minion is shut down
[ERROR   ] Minion failed to start
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 10 seconds
[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 9129
--- SIGCHLD (Child exited) @ 0 (0) ---
select(4, [3], NULL, NULL, {0, 0})      = 1 (in [3], left {0, 0})
read(3, "\0\0\0\5", 4)                  = 4
read(3, "\200\2K\n.", 5)                = 5
select(0, NULL, NULL, NULL, {10, 0})    = 0 (Timeout)
pipe([6, 7])                            = 0
lstat("/dev/shm/sem.GykQSF", 0x7fff878d9f70) = -1 ENOENT (No such file or directory)
open("/dev/shm/sem.GykQSF", O_RDWR|O_CREAT|O_EXCL, 0600) = 8
write(8, "\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 8, 0) = 0x2af0cd1de000
link("/dev/shm/sem.GykQSF", "/dev/shm/sem.mp9124-3") = 0
fstat(8, {st_mode=S_IFREG|0600, st_size=32, ...}) = 0
unlink("/dev/shm/sem.GykQSF")           = 0
close(8)                                = 0
unlink("/dev/shm/sem.mp9124-3")         = 0
lstat("/dev/shm/sem.Bsn9hH", 0x7fff878d9f70) = -1 ENOENT (No such file or directory)
open("/dev/shm/sem.Bsn9hH", O_RDWR|O_CREAT|O_EXCL, 0600) = 8
write(8, "\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 8, 0) = 0x2af0cd1df000
link("/dev/shm/sem.Bsn9hH", "/dev/shm/sem.mp9124-4") = 0
fstat(8, {st_mode=S_IFREG|0600, st_size=32, ...}) = 0
unlink("/dev/shm/sem.Bsn9hH")           = 0
close(8)                                = 0
unlink("/dev/shm/sem.mp9124-4")         = 0
lstat("/dev/shm/sem.mBQAHI", 0x7fff878d9f70) = -1 ENOENT (No such file or directory)
open("/dev/shm/sem.mBQAHI", O_RDWR|O_CREAT|O_EXCL, 0600) = 8
write(8, "\377\377\377\177\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 8, 0) = 0x2af0cd1e0000
link("/dev/shm/sem.mBQAHI", "/dev/shm/sem.mp9124-5") = 0
fstat(8, {st_mode=S_IFREG|0600, st_size=32, ...}) = 0
unlink("/dev/shm/sem.mBQAHI")           = 0
close(8)                                = 0
unlink("/dev/shm/sem.mp9124-5")         = 0
munmap(0x2af0cd1dd000, 32)              = 0
close(4)                                = 0
munmap(0x2af0cd1db000, 32)              = 0
close(3)                                = 0
munmap(0x2af0cd1dc000, 32)              = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x2af0c26c0020) = 9157
wait4(9157, [DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "t.erm1"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] The Salt Minion is starting up
[INFO    ] The Salt Minion is shut down
[ERROR   ] Minion failed to start
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 1 seconds
[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 9157
--- SIGCHLD (Child exited) @ 0 (0) ---
select(7, [6], NULL, NULL, {0, 0})      = 1 (in [6], left {0, 0})
read(6, "\0\0\0\5", 4)                  = 4
read(6, "\200\2K\1.", 5)                = 5
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
pipe([3, 4])                            = 0
lstat("/dev/shm/sem.aQoWiN", 0x7fff878d9f70) = -1 ENOENT (No such file or directory)
open("/dev/shm/sem.aQoWiN", O_RDWR|O_CREAT|O_EXCL, 0600) = 8
write(8, "\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 8, 0) = 0x2af0cd1db000
link("/dev/shm/sem.aQoWiN", "/dev/shm/sem.mp9124-6") = 0
fstat(8, {st_mode=S_IFREG|0600, st_size=32, ...}) = 0
unlink("/dev/shm/sem.aQoWiN")           = 0
close(8)                                = 0
unlink("/dev/shm/sem.mp9124-6")         = 0
lstat("/dev/shm/sem.GFVpUR", 0x7fff878d9f70) = -1 ENOENT (No such file or directory)
open("/dev/shm/sem.GFVpUR", O_RDWR|O_CREAT|O_EXCL, 0600) = 8
write(8, "\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 8, 0) = 0x2af0cd1dc000
link("/dev/shm/sem.GFVpUR", "/dev/shm/sem.mp9124-7") = 0
fstat(8, {st_mode=S_IFREG|0600, st_size=32, ...}) = 0
unlink("/dev/shm/sem.GFVpUR")           = 0
close(8)                                = 0
unlink("/dev/shm/sem.mp9124-7")         = 0
lstat("/dev/shm/sem.cbZZvW", 0x7fff878d9f70) = -1 ENOENT (No such file or directory)
open("/dev/shm/sem.cbZZvW", O_RDWR|O_CREAT|O_EXCL, 0600) = 8
write(8, "\377\377\377\177\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 8, 0) = 0x2af0cd1dd000
link("/dev/shm/sem.cbZZvW", "/dev/shm/sem.mp9124-8") = 0
fstat(8, {st_mode=S_IFREG|0600, st_size=32, ...}) = 0
unlink("/dev/shm/sem.cbZZvW")           = 0
close(8)                                = 0
unlink("/dev/shm/sem.mp9124-8")         = 0
munmap(0x2af0cd1e0000, 32)              = 0
close(7)                                = 0
munmap(0x2af0cd1de000, 32)              = 0
close(6)                                = 0
munmap(0x2af0cd1df000, 32)              = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x2af0c26c0020) = 9164
wait4(9164, DEBUG:salt.utils.parsers:SYSPATHS setup as: /etc/salt
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "t.erm1"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] The Salt Minion is starting up
[INFO    ] The Salt Minion is shut down
[ERROR   ] Minion failed to start
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 8 seconds
[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 9164
--- SIGCHLD (Child exited) @ 0 (0) ---
select(4, [3], NULL, NULL, {0, 0})      = 1 (in [3], left {0, 0})
read(3, "\0\0\0\5", 4)                  = 4
read(3, "\200\2K\10.", 5)               = 5
select(0, NULL, NULL, NULL, {8, 0} <unfinished ...>
```

**Comment by ssgward** [comment] 2016-05-02 17:51
@esn89 - were are needing the OS and salt version you were running when this issue was originally logged so we can narrow down the problem area.

**Comment by thatch45** [comment] 2016-05-03 21:33
@esn89 @lewandom @Timandes @michaelgibson can you all try this with `--disable-keepalive`?

```
salt-minion --disable-keepalive
```

And let me know what you see? That will bypass the attempt to restart the minion and should show us the offending stack trace

**Comment by michaelgibson** [comment] 2016-05-03 22:23
Ok,
Here is what I get:

[DEBUG   ] schedule.clean_proc_dir: checking job {'fun': 'mine.update', 'jid': '20160427093151862622', 'pid': 797, 'id': 'XXXX', 'schedule': '__mine_interval'} for process existence
[DEBUG   ] schedule.clean_proc_dir: Cleaning proc dir, pid 797 still exists.
[INFO    ] The Salt Minion is shut down
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
StackError: StackError: Stack 'event531f77db40fad9bb6e': Failed opening server at '/var/run/salt/minion/XXXX_minion.event531f77db40fad9bb6e.uxd'
.

Traceback (most recent call last):
  File "/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 123, in salt_minion
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 320, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/site-packages/salt/daemons/flo/__init__.py", line 146, in tune_in
    consolepath=consolepath,
  File "/usr/lib/python2.7/site-packages/ioflo/app/run.py", line 137, in run
    skedder.run()
  File "/usr/lib/python2.7/site-packages/ioflo/base/skedding.py", line 273, in run
    status = tasker.runner.send(tasker.desire)
  File "/usr/lib/python2.7/site-packages/ioflo/base/framing.py", line 630, in makeRunner
    self.enterAll() #activates, resets .done state also .desire may change here
  File "/usr/lib/python2.7/site-packages/ioflo/base/framing.py", line 411, in enterAll
    self.enter(self.actives)
  File "/usr/lib/python2.7/site-packages/ioflo/base/framing.py", line 423, in enter
    frame.enter()
  File "/usr/lib/python2.7/site-packages/ioflo/base/framing.py", line 1244, in enter
    act() #call entryAction
  File "/usr/lib/python2.7/site-packages/ioflo/base/acting.py", line 99, in __call__
    return (self.actor(**self.parms))
  File "/usr/lib/python2.7/site-packages/ioflo/base/acting.py", line 524, in __call__
    return self.action(**kwa)
  File "/usr/lib/python2.7/site-packages/salt/daemons/flo/core.py", line 292, in action
    stackname=name)
  File "/usr/lib/python2.7/site-packages/salt/daemons/salting.py", line 62, in __init__
    self.saltRaetKey = RaetKey(opts)
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 965, in __init__
    Key.__init__(self, opts)
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 522, in __init__
    listen=False)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 134, in get_event
    opts=opts)
  File "/usr/lib/python2.7/site-packages/salt/utils/raetevent.py", line 49, in __init__
    self.__prep_stack(listen)
  File "/usr/lib/python2.7/site-packages/salt/utils/raetevent.py", line 59, in __prep_stack
    self.stack = transport.jobber_stack = self._setup_stack(ryn=self.ryn)
  File "/usr/lib/python2.7/site-packages/salt/utils/raetevent.py", line 103, in _setup_stack
    sockdirpath=self.sock_dir)
  File "/usr/lib/python2.7/site-packages/raet/lane/stacking.py", line 77, in __init__
    **kwa)
  File "/usr/lib/python2.7/site-packages/raet/stacking.py", line 94, in __init__
    " '{1}'\n".format(self.name, self.server.ha))
StackError: StackError: Stack 'event531f77db40fad9bb6e': Failed opening server at '/var/run/salt/minion/XXXX_minion.event531f77db40fad9bb6e.uxd'
.
Traceback (most recent call last):
  File "/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 123, in salt_minion
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 320, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/site-packages/salt/daemons/flo/__init__.py", line 146, in tune_in
    consolepath=consolepath,
  File "/usr/lib/python2.7/site-packages/ioflo/app/run.py", line 137, in run
    skedder.run()
  File "/usr/lib/python2.7/site-packages/ioflo/base/skedding.py", line 273, in run
    status = tasker.runner.send(tasker.desire)
  File "/usr/lib/python2.7/site-packages/ioflo/base/framing.py", line 630, in makeRunner
    self.enterAll() #activates, resets .done state also .desire may change here
  File "/usr/lib/python2.7/site-packages/ioflo/base/framing.py", line 411, in enterAll
    self.enter(self.actives)
  File "/usr/lib/python2.7/site-packages/ioflo/base/framing.py", line 423, in enter
    frame.enter()
  File "/usr/lib/python2.7/site-packages/ioflo/base/framing.py", line 1244, in enter
    act() #call entryAction
  File "/usr/lib/python2.7/site-packages/ioflo/base/acting.py", line 99, in __call__
    return (self.actor(**self.parms))
  File "/usr/lib/python2.7/site-packages/ioflo/base/acting.py", line 524, in __call__
    return self.action(**kwa)
  File "/usr/lib/python2.7/site-packages/salt/daemons/flo/core.py", line 292, in action
    stackname=name)
  File "/usr/lib/python2.7/site-packages/salt/daemons/salting.py", line 62, in __init__
    self.saltRaetKey = RaetKey(opts)
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 965, in __init__
    Key.__init__(self, opts)
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 522, in __init__
    listen=False)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 134, in get_event
    opts=opts)
  File "/usr/lib/python2.7/site-packages/salt/utils/raetevent.py", line 49, in __init__
    self.__prep_stack(listen)
  File "/usr/lib/python2.7/site-packages/salt/utils/raetevent.py", line 59, in __prep_stack
    self.stack = transport.jobber_stack = self._setup_stack(ryn=self.ryn)
  File "/usr/lib/python2.7/site-packages/salt/utils/raetevent.py", line 103, in _setup_stack
    sockdirpath=self.sock_dir)
  File "/usr/lib/python2.7/site-packages/raet/lane/stacking.py", line 77, in __init__
    **kwa)
  File "/usr/lib/python2.7/site-packages/raet/stacking.py", line 94, in __init__
    " '{1}'\n".format(self.name, self.server.ha))
raet.raeting.StackError: StackError: Stack 'event531f77db40fad9bb6e': Failed opening server at '/var/run/salt/minion/XXXX_minion.event531f77db40fad9bb6e.uxd'

**Comment by thatch45** [comment] 2016-05-03 22:34
Awesome @michaelgibson ! Thanks!
The hard thing with the minion reset is that this is a last ditch fallback just in case the minion stops talking to the master or crashed for an odd reason. I am almost sure that everyone will have a different stack trace, because this will expose some strange nuances that would only exist in specific environment where we otherwise had not tested things.

My first reaction to your stack trace is to ask 2 things:
1. is the /var/run/salt/minion directory present?
2. It looks like you have blacked out your minion id. which is understandable, can you at least let me know how many characters long the minion id is? If it is really long that can cause a unix socket connection to fail.
Also, what OS are you running? MacOSX in particular is more prone to long name unix socket errors because they have a path limit of (I think) 107 chars

**Comment by thatch45** [comment] 2016-05-03 22:36
assuming it is the socket length issue, I might be able to fix it by changing the default socket paths in raet to be hashes of the id

**Comment by michaelgibson** [comment] 2016-05-03 22:40
1. Yup, Directory exists:

ls -lart /var/run/salt/minion/
total 0
drwxr-xr-x. 3 root root  60 Apr 28 19:45 ..
srw-------. 1 root root   0 Apr 28 19:45 minion_event_0977a90cf0_pull.ipc
srw-------. 1 root root   0 Apr 28 19:45 minion_event_0977a90cf0_pub.ipc
srw-------. 1 root root   0 May  3 22:26 minion_event_60aaad4a8b_pub.ipc
srw-------. 1 root root   0 May  3 22:26 minion_event_60aaad4a8b_pull.ipc
drwxr-xr-x. 2 root root 120 May  3 22:26 .

2. The full minion ID is 55 characters and the OS is a RHEL7 flavor.

**Comment by michaelgibson** [comment] 2016-05-03 22:42
Actually 62 characters with _minion appended

**Comment by thatch45** [comment] 2016-05-03 22:43
yep, that puts it up to 111 chars, and if I am not mistaken it has a limit of 108 on the default Linux kernel, just to verify, can you rename the minion to something short and try again? Then we will know for sure

**Comment by thatch45** [comment] 2016-05-03 22:48
Can you also please give me a

```
salt --versions-report
```

So I can see what version of raet you are on? This might be fixed in a newer version (at least I remember it being an issue and fixing it...)

**Comment by thatch45** [comment] 2016-05-03 22:50
@michaelgibson Also, for the record, I would only suggest raet if you are in a situation where you specifically need UDP, otherwise if there are issues with zeromq (licence etc.) then you can use the tcp transport which there are no known issues with in the 2016.3 rc.

**Comment by michaelgibson** [comment] 2016-05-03 22:59
This thread is too long! :)
https://github.com/saltstack/salt/issues/32472#issuecomment-215873437

Looks like that was the fix.
shortened the minion id and no more stacktracing.

Yeah, zeromq license was too murky so we wanted to test out raet.
I'll check out TCP and see if that is sufficient for us.

Thanks for the help!

**Comment by thatch45** [comment] 2016-05-03 23:12
Sure thing, and yes this is a long one!

**Comment by thatch45** [comment] 2016-05-03 23:14
oh! yes, sorry I missed the version report!

**Comment by Timandes** [comment] 2016-05-04 00:42
@thatch45 
This is what I got:
```
# salt-minion --disable-keepalive
[DEBUG   ] Configuration file path: /etc/salt/minion
[TRACE   ] Trying pysss.getgrouplist for 'root'
[TRACE   ] Trying generic group list for 'root'
[TRACE   ] Group list for user 'root': ['adm', 'bin', 'daemon', 'disk', 'sys', 'wheel']
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "t.erm1"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] The Salt Minion is starting up
[INFO    ] The Salt Minion is shut down
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'IOLoop' object has no attribute 'spawn_callback'
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 123, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 320, in start
    self.minion.tune_in()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 686, in tune_in
    self.minions = self._spawn_minions()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 646, in _spawn_minions
    self.io_loop.spawn_callback(self._connect_minion, s_opts)
AttributeError: 'IOLoop' object has no attribute 'spawn_callback'
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 123, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 320, in start
    self.minion.tune_in()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 686, in tune_in
    self.minions = self._spawn_minions()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 646, in _spawn_minions
    self.io_loop.spawn_callback(self._connect_minion, s_opts)
AttributeError: 'IOLoop' object has no attribute 'spawn_callback'

```
Other informations:
```
# salt-minion --versions
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.08
          PyZMQ: 2.1.9
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 2.1.9
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 5.4 Final
        machine: x86_64
        release: 2.6.18-164.el5
         system: CentOS 5.4 Final
```
```
# uname -a
Linux erm1.xxx 2.6.18-164.el5 #1 SMP Thu Sep 3 03:28:30 EDT 2009 x86_64 x86_64 x86_64 GNU/Linux
```

BTW, It's a little strange that I can not find binary `salt` in anywhere:
```
# which salt
/usr/bin/which: no salt in (/sbin:/usr/sbin:/usr/local/sbin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin:/root/bin)
# ls /usr/bin/salt*
/usr/bin/salt-call  /usr/bin/salt-minion  /usr/bin/salt-proxy
```

But I'm quite sure I have installed the package `salt`:
```
# rpm -qa|grep salt
salt-2015.8.8-2.el5
salt-minion-2015.8.8-2.el5
# cat /etc/yum.repos.d/saltstack.repo
[saltstack-repo]
name=SaltStack repo for RHEL/CentOS $releasever
baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
enabled=1
gpgcheck=1
gpgkey=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/SALTSTACK-EL5-GPG-KEY.pub
```

**Comment by thatch45** [comment] 2016-05-04 03:50
The salt command is part of the salt-master package, also, where did you install from? our repo should have installed tornado 4.3, salt 2015.8 needs tornado 4.3, I think that might be the problem, although that stack trace is from an attribute that was introduced in tornado 4.0, so I would not think that it would stack trace there.
Try upgrading tornado

**Comment by Timandes** [comment] 2016-05-04 03:54
@thatch45 
From `https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest`.

And:
```
# rpm -qa|grep tornado
python26-tornado-4.2.1-1.el5
```

**Comment by thatch45** [comment] 2016-05-04 03:59
Thanks for the heads up
@dmurphy18 are we aware of any issues like @Timandes is seeing with the RHEL5 repo?

**Comment by Timandes** [comment] 2016-05-04 04:05
@thatch45 Thanks for your time.

I can not upgrade python26-tornado higher than 4.2.1-1.el5:
```
# yum install python26-tornado
Setting up Install Process
Package python26-tornado-4.2.1-1.el5.x86_64 already installed and latest version
Nothing to do
```

And in SaltStack repo `http://repo.saltstack.com/yum/redhat/5/x86_64/latest/`, I can only find same version of python26-tornado:
* python26-tornado-4.2.1-1.el5.x86_64.rpm
* python26-tornado-doc-4.2.1-1.el5.x86_64.rpm

**Comment by thatch45** [comment] 2016-05-04 04:07
Thanks, @dmurphy18 should know on this one, he will likely be back online in the morning (10-12 hours)

**Comment by Timandes** [comment] 2016-05-04 04:30
Oh, I see.
You all in U.S.
: )
Thanks.

**Comment by Timandes** [comment] 2016-05-04 09:45
@thatch45 
I think I solved the issue on my servers...

I found that on the server which has no this issue, the version of package `PyZMQ` is `14.x.x`:
```
# rpm -qa|grep zmq
python-zmq-14.3.1-1.el6.x86_64
```
But on the servers with issue, the version is `2.x.x`:
```
# rpm -qa|grep zmq
python26-zmq-2.1.9-3.el5
```

After upgrading this package:
```
# yum -y install python26-zmq
# rpm -qa|grep zmq
python26-zmq-14.5.0-2.el5
```
The `salt-minion` works as usual.

Thank you very much and hope this information useful.

**Comment by thatch45** [comment] 2016-05-04 15:58
Ahh! yes! epel STILL distributes the old, broken zeromq 2! We only see this issue on rhel5, that platform keeps getting harder to maintain! Thanks!

**Comment by thatch45** [comment] 2016-05-04 16:00
I am going to close this issue out, since #33030 will display the actual error when this is encountered and this has been shown to be references to other bugs.

**Closed by thatch45** 2016-05-04 16:00 UTC
Labels: Core, Critical, P3, Regression
