### ISSUE TITLE
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.   --- How to solve

### ISSUE THREAD

**Issue by zhulh200868** [saltstack/salt#38432] opened 2016-12-24 08:13 UTC
### Description of Issue/Question
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.

**Comment by gtmanfred** [comment] 2016-12-27 14:33
This is a duplicate of https://github.com/saltstack/salt/issues/37267

Have you reached out to the community for help with this?  you can try #salt on freenode, or the salt-users mailing list.

There are a lot of reasons that this could be happening.  It could be that your master just doesn't have enough memory or cpu to handle all those connections, or it could be that network is saturated to the master that the minions cannot send their data.

You should also consider running your salt command with `--async` and then checking the jobs database afterwards to see if they all return.

You could also run your command with `--batch` and run smaller batch commands against the whole list of minions instead of running them all at once.

**Closed by gtmanfred** 2016-12-27 14:33 UTC
Labels: Duplicate
