### ISSUE TITLE
salt-ssh ignores cachedir in master configuration

### ISSUE THREAD

**Issue by pirogoeth** [saltstack/salt#27279] opened 2015-09-21 15:47 UTC
Using a Saltfile with a private configuration, `salt-ssh` seems to ignore the cachedir that I set in my $config_dir/master. I followed the instructions [here](https://docs.saltstack.com/en/2015.5/topics/ssh/index.html#running-salt-ssh-as-non-root-user).

`Saltfile`:
```yaml
salt-ssh:
  max_procs: 30
  wipe_ssh: True
  roster_file: .salt-secret/roster
  config_dir: .salt-secret/conf
  ssh_priv: .salt-secret/pki/salt_rsa
```

`.salt-secret/conf/master`:
```yaml
pki_dir: "/home/pirogoeth/maiome-saltstates/.salt-secret/local/pki"
cachedir: "/home/pirogoeth/maiome-saltstates/.salt-secret/local/cache"
log_file: "/home/pirogoeth/maiome-saltstates/.salt-secret/local/log/master"

state_verbose: False
state_output: mixed

file_roots:
  base:
    - base
    - base/states
    - base/files
  staging:
    - staging
    - staging/states
    - staging/files
  prod:
    - prod
    - prod/states
    - prod/files

pillar_roots:
  base:
    - base/pillars
  staging:
    - staging/pillars
  prod:
    - prod/pillars
```

Example from `salt-ssh 'omega.maio.me' state.highstate`:
```
[CRITICAL] Rendering SLS 'base:core' failed: Jinja error: [Errno 13] Permission denied: '/var/cache/salt/minion/roots/mtime_map'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
  File "/usr/local/lib/python2.7/site-packages/salt/utils/jinja.py", line 113, in get_source
    self.check_cache(template)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/jinja.py", line 101, in check_cache
    self.cache_file(template)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/jinja.py", line 94, in cache_file
    self.file_client().get_file(saltpath, '', True, self.saltenv)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/jinja.py", line 86, in file_client
    self.opts, self.pillar_rend)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 53, in get_file_client
    }.get(client, RemoteClient)(opts)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 1290, in __init__
    self.channel = salt.fileserver.FSChan(opts)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 663, in __init__
    self.fs.update()
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 412, in update
    self.servers[fstr]()
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 154, in update
    with salt.utils.fopen(mtime_map_path, 'w') as fp_:
  File "/usr/local/lib/python2.7/site-packages/salt/utils/__init__.py", line 1208, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 13] Permission denied: '/var/cache/salt/minion/roots/mtime_map'
```

Annoyingly enough, it works when run as root:
```
→ pirogoeth@epsilon | ~/maiome-saltstates | branch: master * | load: 0.56
λ sudo salt-ssh 'omega.maio.me' state.highstate
[ERROR   ] Template was specified incorrectly: False
[ERROR   ] Template was specified incorrectly: False
omega.maio.me:
  Name: /etc/sudoers - Function: file.managed - Result: Changed

Summary for omega.maio.me
-------------
Succeeded: 12 (changed=1)
Failed:     0
-------------
Total states run:     12
Total run time:   10.362 s
```

Environment:
```
→ pirogoeth@epsilon | ~ | load: 0.21
λ uname -a
FreeBSD epsilon.maio.me 10.1-RELEASE-p10 FreeBSD 10.1-RELEASE-p10 #3: Sat May 30 02:06:42 CDT 2015     root@epsilon.maio.me:/usr/obj/usr/src/sys/MAIOME-XEN  amd64

→ pirogoeth@epsilon | ~ | load: 0.18
λ salt --versions-report
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Sep  4 2015, 18:58:11)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: 1.1.1
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: amd64
        release: 10.1-RELEASE-p10
```

**Comment by jfindlay** [comment] 2015-09-21 17:36
@pirogoeth, thanks for the report.

**Comment by pirogoeth** [comment] 2015-09-21 18:57
@jfindlay No problem. I may see if this is just somehow a FreeBSD-specific issue or if this occurs on other OSes as well.

**Comment by basepi** [comment] 2015-11-17 22:23
@pirogoeth Just wanted you to know this is still on our radar, we need to get this fixed.

**Comment by pirogoeth** [comment] 2015-11-18 04:15
@basepi Thanks for the note!

**Comment by DmitryKuzmenko** [comment] 2015-12-04 16:23
@pirogoeth can't reproduce the issue on my FreeBSD VM. Reviewed the related code and found nothing interesting.
Probably it would be helpful if you'll share your configuration, i.e. your file_roots and pillar_roots content.

**Comment by pirogoeth** [comment] 2015-12-04 17:51
@DmitryKuzmenko Just curious, but how are the contents of `file_roots` and `pillar_roots` relevant? This purely seems to be something weird with salt ignoring my cachedir setting...

You can see my `file_roots` and `pillar_roots` content [here](https://phabricator.ramcloud.io/diffusion/MSLS/repository/master/), though.

**Comment by DmitryKuzmenko** [comment] 2015-12-07 12:47
I thought maybe it depends on a specific module loading procedure. LazyLoader works really strange sometimes.
Still can't reproduce the issue. @pirogoeth could you please reproduce this with ```--log-level=trace``` and public the full log?

**Comment by basepi** [comment] 2015-12-07 23:05
(Make sure you gist.github.com the log, don't paste it in here, it gets unwieldy)

**Comment by pirogoeth** [comment] 2015-12-07 23:05
@DmitryKuzmenko doing so now.

**Comment by pirogoeth** [comment] 2015-12-07 23:12
@DmitryKuzmenko https://gist.github.com/pirogoeth/76ffa69cd6b514248882

**Comment by DmitryKuzmenko** [comment] 2015-12-09 15:30
@pirogoeth using the trace log I've extracted the script that is executed on the remote site with it's contiguration and reproduced the issue on my Arch dev box. The issue is not in the cachedir Saltfile option. It's in the yaml dump/load procedure.
Tomorrow I'll continue work on this and will provide more details.

**Comment by pirogoeth** [comment] 2015-12-09 17:18
@DmitryKuzmenko alright, cool!

**Comment by DmitryKuzmenko** [comment] 2015-12-10 07:54
Finally got it. The issue is already fixed by 0785438b that was merged in scope of #27573 into develop and released since v2015.8.1.
@pirogoeth you can either update to salt>=2015.8.1 or apply the commit manually to 2015.8.0. It's safe.

**Comment by DmitryKuzmenko** [comment] 2015-12-10 08:09
BTW, salt-ssh lacks the ability to set salt-call log-level on the remote side. It would be helpful to analyze such issues. I'm going to create a feature request for this.

**Comment by DmitryKuzmenko** [comment] 2015-12-10 10:11
Created a new issue #29591.
This one will be closed after confirmation from @pirogoeth.

**Comment by pirogoeth** [comment] 2015-12-11 16:20
@DmitryKuzmenko Yep, we're good.

**Closed** 2015-12-14 13:50 UTC
Labels: Boron, Bug, Confirmed, Core, Critical, P4, Salt-SSH, TEAM Core
