### ISSUE TITLE
__virtual__() doesn't work without __virtualname__

### ISSUE THREAD

**Issue by robkinyon** [saltstack/salt#26673] opened 2015-08-26 18:26 UTC
The following does not work under 2015.5.3 (Lithium) / Ubuntu 14.04:
```python
def __virtual__():
    return 'mytest'

def echo(text):
    return 'X:' + text
```
It claims "Module 'mytest' is not available."

If, however, you set `__virtualname__ = 'mytest'` as well, then everything works as expected. This requirement to set `__virtualname__` is missing from the docs at http://docs.saltstack.com/en/stage/ref/modules/index.html

This may be related to #25142

**Comment by jfindlay** [comment] 2015-08-26 18:51
@robkinyon, thanks for the report.  This may be caused by some recent changes to the loader.  Defining a `__virtialname__` may be good practice, but I don't see why it is necessary (perhaps it should be?).

**Comment by robkinyon** [comment] 2015-08-26 19:09
@jfindlay My thought would be that you should do one-and-only-one of:
* define `__virtualname__` if you have a virtualname you can know at compiletime.
* define `__virtual__()` which would then set `__virtualname__` to the return value. This is for virtualnames that can only be known at runtime.

If you define a `__virtual__()`, then also setting a `__virtualname__` should be an error.
Having to (or being able to) set both violates DRY and leads to situations like this where doc, code, and intention are all out of sync.

**Comment by s0undt3ch** [comment] 2015-08-26 19:16
The point of `__virtualname__` is to future proof documenting several modules under the same virtual name without running the `__virtual__` function. Unfortunately, creating the sphinx extension for that takes time and is not high priority, hence, not yet being implemented.

**Comment by s0undt3ch** [comment] 2015-08-27 00:04
I'd also like to add that the virtual function does not serve the sole purpose of (re)naming the module, a way to block a module from loading. It can also be used for some additional "pre-flight" checks.
I agree about the DRY, but runing the virtual function with all those possible checks just to build documentation is also not right.

**Comment by cachedout** [comment] 2015-09-03 22:33
We have had no reply here for over a week. I'm going to close this. If you would like to continue the discussion here, that's still fine. We can re-open it if necessary.

**Comment by robkinyon** [comment] 2015-09-03 22:34
I didn't think I needed to reply to an accepted documentation bug.

**Comment by cachedout** [comment] 2015-09-03 22:37
The documentation tag was removed a week ago so I didn't see it.  I've re-opened and we'll address the documentation. Thanks for the reply.

**Comment by jacobhammons** [comment] 2015-10-06 23:28
Hi @robkinyon, would you take a look at the commit I made ^ and let me know if the changes correctly describe the current behavior? Thanks!

**Comment by robkinyon** [comment] 2015-10-08 18:03
@jacobhammons: Perfect. The key sentence is `Modules that return a string from the __virtual__ function must also set the __virtualname__ variable.` Thank you for addressing this.

**Closed** 2015-10-08 23:32 UTC
Labels: Bug, Documentation, High Severity, P3
