### ISSUE TITLE
Windows pkg.list_pkgs and grain encoding issue

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#53340] opened 2019-06-02 17:46 UTC
### `®` of death

Somewhere deep in Salt an output of `pkg.list_pkgs` is not decoded properly and passed as a binary string (not unicode)

This binary string gets stored in grain

When Salt tries to read the grain, it expects it to be stored as unicode, and fails miserably while trying to decode it, because the characters are from CP437

### Setup

1. Windows 10
2. Install the Intel driver (msi) https://downloadmirror.intel.com/28688/a08/WiFi_21.0.0_PROSet64.zip (link to the page: https://downloadcenter.intel.com/download/28688/Intel-PROSet-Wireless-Software-and-Drivers-for-IT-Admins)  This also happens with MS Office localization package names that contain diacritics, but this Intel driver is the simplest way to reproduce the problem.

### Steps to Reproduce Issue

1. Apply the following state:

```
{% set pkgs = salt['pkg.list_pkgs']() %}

windows_packages:
   grains.present:
     - value : {{ pkgs }}
     - force: True
```

The output should look like this

```
local:
----------
          ID: windows_packages
    Function: grains.present
...
Intel\xc2\xae PROSet/Wireless WiFi Software:
                      21.0.0.2990

...
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   8.316 ms
```

2. Apply the same state second time. It should fail like this:

```
[WARNING ] Bad syntax in grains file! Skipping.
[ERROR   ] Unable to read existing grains file: unacceptable character #x00ae: invalid start byte
  in "c:\salt\conf\grains", position 548
local:
----------
          ID: windows_packages
    Function: grains.present
      Result: False
     Comment: Unable to read existing grains file: unacceptable character #x00ae: invalid start byte
                in "c:\salt\conf\grains", position 548
     Started: 00:39:02.515980
    Duration: 7.801 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   7.801 ms
```

```
c:\salt>chcp
Active code page: 437
```

### Versions Report

<details><summary>c:\salt>salt-call --versions-report</summary>

```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```
</details>

**Comment by cmcmarrow** [comment] 2019-06-03 14:06
last change: https://github.com/saltstack/salt/pull/50534

**Comment by cmcmarrow** [comment] 2019-06-03 14:08
This test error might be related to this too. https://github.com/saltstack/salt/issues/53214

**Comment by damon-atkins** [comment] 2019-06-03 14:45
Hi @max-arnold  why do you feel the need to have the list of packages as a grain, this is something you might do in other configuration management tools, not Salt. What are you trying to solve?

**Comment by damon-atkins** [comment] 2019-06-03 14:47
You must use python 3 version of salt-minion to work with Unicode. Python 2 WIN API interface is too limiting.

**Comment by max-arnold** [comment] 2019-06-03 19:49
@damon-atkins 

> You must use python 3.6 version of salt-minion

I used Python 3.5.3 (see the attached versions-report) that is shipped with Salt 2018.3.4. 

> why do you feel the need to have the list of packages as a grain, this is something you might do in other configuration management tools, not Salt. What are you trying to solve?

I need this for state tracking and reporting purposes. What is not shown in the example is a custom event I send when the grain changes (using the `onchanges` requisite). Without a grain the event would be sent each time the state is run.

**Comment by max-arnold** [comment] 2019-06-03 19:55
My guess is that the grain is not a problem. The problem is that something in salt (`pkg.list_pkgs` maybe?) returns a CP437-encoded binary string and not an unicode one.

**Comment by damon-atkins** [comment] 2019-06-04 16:45
There are lots of issues with python on windows and Unicode. Which were not fixed until python 3.6
For example a command can work from the salt master on linux and not work on the cmd.exe window.

The software should only change if you have set the version to latest,

The only thing I can think of, is if you wanted to track when someone by hand had changed the software.

**Comment by max-arnold** [comment] 2019-06-04 18:41
> You must use python 3.6 version of salt-minion

Are there official Salt builds that ship with Python 3.6?  Below is the output of versions-report using the latest `2019.2.0` build:

```
c:\salt>salt-call --local --versions-report
Salt Version:
           Salt: 2019.2.0
...
Dependency Versions:
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
...
System Versions:
        machine: AMD64
        release: 10
         system: Windows
```

I also successfully reproduced the encoding problem with Salt 2019.2.0.

**Comment by max-arnold** [comment] 2019-06-04 19:50
Upon closer examination, the encoding problem seems to be caused by grains.  See the following code: https://github.com/saltstack/salt/blob/develop/salt/modules/grains.py#L273-L290

Static grains (that are stored in C:\salt\conf\grains) are read first as binary file:

```
        with salt.utils.files.fopen(gfn, 'rb') as fp_:
```

and then saved a few lines later as text file:

```
        with salt.utils.files.fopen(gfn, 'w+') as fp_:
```

So far this is my understanding of what is happening here:

1. `pkg.list_pkgs` is fine and returns an unicode dictionary (both keys and values). I verified this in a debugger
2. When the dictionary gets stored in a grain, it is saved as text (`w+`), so Python uses system encoding (`cp1252` as reported by `salt --versions-report`)
3. When it later gets read, the file is treated as binary, and YAML loader fails to decode it in `grains = salt.utils.yaml.safe_load(fp_)`, producing the `Unable to read existing grains file` message

As far as I can see, it is always been this way:

https://github.com/saltstack/salt/commit/830324898a622c7648bc4c86fbfc6c9d4260586e
https://github.com/saltstack/salt/commit/36e39aead2b628a294fdb057d786ad350bb44d81

```
> print(sys.getdefaultencoding(), sys.getfilesystemencoding(), sys.stdout.encoding)
utf-8 mbcs cp437
```

**Comment by twangboy** [comment] 2019-06-04 22:29
@saltstack/team-core  What do you think about making grains Unicode-safe?

**Comment by twangboy** [comment] 2019-06-04 22:32
Could the fix be as simple as changing the `fopen` command on line 290 to `wb`?

https://github.com/saltstack/salt/blob/develop/salt/modules/grains.py#L290

**Comment by twangboy** [comment] 2019-06-04 23:17
Actually, I applied the following state:
```
z_grain:
  grains.present:
    - value: some text
    - force: True

z_grain_unicode:
  grains.present:
    - value: trademark®
    - force: True
```
with the following result:
```
----------
          ID: z_grain
    Function: grains.present
      Result: True
     Comment: Set grain z_grain to some text
     Started: 16:45:10.097000
    Duration: 27.0 ms
     Changes:
              ----------
              z_grain:
                  some text
----------
          ID: z_grain_unicode
    Function: grains.present
      Result: True
     Comment: Set grain z_grain_unicode to trademark┬«
     Started: 16:45:10.124000
    Duration: 16.0 ms
     Changes:
              ----------
              z_grain_unicode:
                  trademark┬«
```
Looks weird, probably fixed in Python 3.6...

But the `grains` file was created properly, with the trademark symbol inside:
```
z_grain: some text
z_grain_unicode: trademark®
```
`grains.items` returned the following:
```
    z_grain:
        some text
    z_grain_unicode:
        trademark┬«
```
Applying the state a second time:
```
----------
          ID: z_grain
    Function: grains.present
      Result: True
     Comment: Grain is already set
     Started: 16:50:27.963000
    Duration: 16.0 ms
     Changes:
----------
          ID: z_grain_unicode
    Function: grains.present
      Result: True
     Comment: Grain is already set
     Started: 16:50:27.979000
    Duration: 0.0 ms
     Changes:
```
So, then I added a registry entry for software containing the `®` and verified that it showed up in `pkg.list_pkgs`:
```
    Salt┬« Unicode Test:
        2019.2.1
```
Then added your code to my custom grains state and get the following:
```
                  u'Salt\xae Unicode Test':
                      u'2019.2.1'
```
But, I'm noticing that my unicode character (`\xae`) is different from yours (`\xc2\xae`).

**Comment by twangboy** [comment] 2019-06-04 23:20
This was all on 2019.2 branch...

**Comment by max-arnold** [comment] 2019-06-05 04:27
Your super minimal reproducible test case successfully triggers the problem for me (Py 3.5.4, Salt 2019.2.0):

```
z_grain_unicode:
  grains.present:
     - value : trademark®
     - force: True
```

Please note that the state above should be encoded as `utf-8` file. And the resulting grains file seems to be encoded as `cp1252`.  I attached the files here to preserve their encoding.

[encoding.zip](https://github.com/saltstack/salt/files/3255468/encoding.zip)

```
salt-call --local state.apply encoding2
[WARNING ] Bad syntax in grains file! Skipping.
[ERROR   ] Unable to read existing grains file: unacceptable character #x00ae: invalid leading UTF-8 octet
  in "c:\salt\conf\grains", position 26
local:
----------
          ID: z_grain_unicode
    Function: grains.present
      Result: False
     Comment: Unable to read existing grains file: unacceptable character #x00ae: invalid leading UTF-8 octet
                in "c:\salt\conf\grains", position 26
     Started: 11:02:03.976061
    Duration: 15.334 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  15.334 ms
```

One of the ways to fix the issue is to apply the following patch (and add a couple of tests):

```
diff --git a/salt/modules/grains.py b/salt/modules/grains.py
index b8474006d4..65f80af336 100644
--- a/salt/modules/grains.py
+++ b/salt/modules/grains.py
@@ -270,7 +270,7 @@ def setvals(grains, destructive=False):
             )

     if os.path.isfile(gfn):
-        with salt.utils.files.fopen(gfn, 'rb') as fp_:
+        with salt.utils.files.fopen(gfn, 'rb', encoding='utf-8') as fp_:
             try:
                 grains = salt.utils.yaml.safe_load(fp_)
             except salt.utils.yaml.YAMLError as exc:
@@ -287,7 +287,7 @@ def setvals(grains, destructive=False):
             grains[key] = val
             __grains__[key] = val
     try:
-        with salt.utils.files.fopen(gfn, 'w+') as fp_:
+        with salt.utils.files.fopen(gfn, 'w+', encoding='utf-8') as fp_:
             salt.utils.yaml.safe_dump(grains, fp_, default_flow_style=False)
     except (IOError, OSError):
         log.error(
```

The `encoding` keyword is available only on Python3, but `salt.utils.files.fopen` has a compatibility layer to handle it. I haven't tested this on Py2 though.

With this patch the state applies successfully:

```
c:\salt>salt-call --local state.apply encoding2
b'local:\n----------\n          ID: z_grain_unicode\n    Function: grains.present\n      Result: True\n     Comment: Set grain z_grain_unicode to trademark\xc2\xae\n     Started:
 11:11:17.835143\n    Duration: 14.853 ms\n     Changes:   \n              ----------\n              z_grain_unicode:\n                  trademark\xc2\xae\n\nSummary for local\n-
-----------\nSucceeded: 1 (changed=1)\nFailed:    0\n------------\nTotal states run:     1\nTotal run time:  14.853 ms'

c:\salt>salt-call --local state.apply encoding2
local:
----------
          ID: z_grain_unicode
    Function: grains.present
      Result: True
     Comment: Grain is already set
     Started: 11:11:26.897816
    Duration: 0.0 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.000 ms
```

I do not know if it is ok that the command output is printed on the console as binary b'local:\n----------\n ...`

**Comment by damon-atkins** [comment] 2019-06-06 16:45
@max-arnold Good fine.
Internal salt needs to be utf-8.  The question comes down to, if all salt configurations files are also consider to be utf-8 even if the OS is set to another language.  Maybe salt sort of already does this. I assume for languages like Japaneses ASCII is still available in the code page???

**Comment by max-arnold** [comment] 2019-06-06 17:09
I’d say that at least state files should use utf-8, because they are distributed to different systems with potentially different encodings, but should be read identically. Probably it also makes sense to do the same for config files

**Comment by max-arnold** [comment] 2019-06-07 09:22
@twangboy 

> Could the fix be as simple as changing the `fopen` command on line 290 to `w+b`?
> 
> https://github.com/saltstack/salt/blob/develop/salt/modules/grains.py#L290

This fix fails on Python 3 with the following error:

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1919, in call
    **cdata['kwargs'])
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\states\grains.py", line 120, in present
    ret = __salt__['grains.set'](name, value, force=force)
  File "c:\salt\bin\lib\site-packages\salt\modules\grains.py", line 781, in set
    _setval_ret = setval(key, _value, destructive=destructive)
  File "c:\salt\bin\lib\site-packages\salt\modules\grains.py", line 334, in setval
    return setvals({key: val}, destructive)
  File "c:\salt\bin\lib\site-packages\salt\modules\grains.py", line 291, in setvals
    salt.utils.yaml.safe_dump(grains, fp_, default_flow_style=False)
  File "c:\salt\bin\lib\site-packages\salt\utils\yamldumper.py", line 129, in safe_dump
    return yaml.dump(data, stream, Dumper=SafeOrderedDumper, **kwargs)
  File "c:\salt\bin\lib\site-packages\yaml\__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "c:\salt\bin\lib\site-packages\yaml\__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "c:\salt\bin\lib\site-packages\yaml\representer.py", line 27, in represent
    self.serialize(node)
  File "ext\_yaml.pyx", line 1350, in _yaml.CEmitter.serialize (ext\_yaml.c:18773)
  File "ext\_yaml.pyx", line 1525, in _yaml.output_handler (ext\_yaml.c:21549)
TypeError: a bytes-like object is required, not 'str'
```

But the following fix works, should be backwards-compatible, and does not require an immediate decision to switch to `utf-8` (although I still think it is a good idea):

https://github.com/saltstack/salt/blob/develop/salt/modules/grains.py#L273 (change from `rb` to `r`):

```
        with salt.utils.files.fopen(gfn, 'r') as fp_:
```

This way the `C:\salt\conf\grains` file should be stored and read in a system encoding.

**Comment by waynew** [comment] 2019-06-15 00:06
I think that we could benefit from a higher level discussion about bytes vs text in Salt in general. There are many places where we sort of inherit the Python2 conflation of bytes and text, and it causes occasional weirdness like this.

It's been something that I've been kicking around in my head for a while, due to the number of times I've seen issues like this, and been frustrated by the occasional lack of text/bytes coherence. I think then what I will do is let this idea percolate over the weekend and create a [SEP](https://github.com/saltstack/salt-enhancement-proposals) early next week about it.

Meanwhile, hopefully this issue can get resolved :)

**Comment by yur4enko** [comment] 2019-10-04 19:22
any news about it? 2019.2.1 - all the same

**Comment by waynew** [comment] 2019-10-07 17:22
I don't think there's been any progress. @yur4enko do you have any time to devote to this issue?

**Comment by cmcmarrow** [comment] 2019-10-17 19:34
I tried to reproduce this in 2019.2.2. I have Office 16 installed. I did not get any errors. 
```
DESKTOP-XXXXXXXXXXXX:
    ----------
    GNU Privacy Guard:
        2.2.17
    Git version 2.23.0.windows.1:
        2.23.0.windows.1
    Google Chrome:
        77.0.3865.120
    Google Update Helper:
        1.3.35.301
    Gpg4win (3.1.10):
        3.1.10
    JetBrains PyCharm 2019.2.3:
        192.6817.19
    JetBrains PyCharm Community Edition 2019.2.3:
        192.6817.19
    Microsoft Build Tools 14.0 (amd64):
        14.0.25420
    Microsoft Build Tools 14.0 (x86):
        14.0.25420
    Microsoft Build Tools Language Resources 14.0 (amd64):
        14.0.25420
    Microsoft Build Tools Language Resources 14.0 (x86):
        14.0.25420
    Microsoft Office 365 ProPlus - en-us:
        16.0.11328.20438
    Microsoft OneDrive:
        19.152.0927.0012
    Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24210:
        14.0.24210.0
    Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24210:
        14.0.24210.0
    Microsoft Visual C++ 2015 x64 Additional Runtime - 14.0.24210:
        14.0.24210
    Microsoft Visual C++ 2015 x64 Debug Runtime - 14.0.24210:
        14.0.24210
    Microsoft Visual C++ 2015 x64 Minimum Runtime - 14.0.24210:
        14.0.24210
    Microsoft Visual C++ 2015 x86 Additional Runtime - 14.0.24210:
        14.0.24210
    Microsoft Visual C++ 2015 x86 Debug Runtime - 14.0.24210:
        14.0.24210
    Microsoft Visual C++ 2015 x86 Minimum Runtime - 14.0.24210:
        14.0.24210
    Microsoft Visual C++ Build Tools:
        14.0.25420.1
    Nullsoft Install System:
        3.03
    Office 16 Click-to-Run Extensibility Component:
        16.0.11328.20438
    Office 16 Click-to-Run Licensing Component:
        16.0.11328.20438
    Office 16 Click-to-Run Localization Component:
        16.0.11328.20438
    Oracle VM VirtualBox Guest Additions 6.0.8:
        6.0.8.0
    Python 3.5.4 (64-bit):
        3.5.4150.0
    Python 3.5.4 Add to Path (64-bit):
        3.5.4150.0
    Python 3.5.4 Core Interpreter (64-bit):
        3.5.4150.0
    Python 3.5.4 Development Libraries (64-bit):
        3.5.4150.0
    Python 3.5.4 Executables (64-bit):
        3.5.4150.0
    Python 3.5.4 Standard Library (64-bit):
        3.5.4150.0
    Python 3.5.4 Utility Scripts (64-bit):
        3.5.4150.0
    Python 3.5.4 pip Bootstrap (64-bit):
        3.5.4150.0
    Python Launcher:
        3.5.6063.0
    Slack:
        4.1.0
    Teams Machine-Wide Installer:
        1.2.0.24753
    Universal CRT Extension SDK:
        10.0.26624
    Universal CRT Headers Libraries and Sources:
        10.0.26624
    Visual C++ CRT Headers Package:
        14.0.24210
    Visual C++ Compiler/Tools X64 ARM Cross Package:
        14.0.24210
    Visual C++ Compiler/Tools X64 ARM Cross Resource Package:
        14.0.24210
    Visual C++ Compiler/Tools X64 Base Package:
        14.0.24210
    Visual C++ Compiler/Tools X64 Base Resource Package:
        14.0.24210
    Visual C++ Compiler/Tools X64 Native Package:
        14.0.24210
    Visual C++ Compiler/Tools X64 Native Resource Package:
        14.0.24210
    Visual C++ Compiler/Tools X64 X86 Cross Package:
        14.0.24210
    Visual C++ Compiler/Tools X64 X86 Cross Resource Package:
        14.0.24210
    Visual C++ Compiler/Tools X86 ARM Cross Package:
        14.0.24210
    Visual C++ Compiler/Tools X86 ARM Cross Resource Package:
        14.0.24210
    Visual C++ Compiler/Tools X86 Base Package:
        14.0.24210
    Visual C++ Compiler/Tools X86 Base Resource Package:
        14.0.24210
    Visual C++ Compiler/Tools X86 Native Package:
        14.0.24210
    Visual C++ Compiler/Tools X86 Native Resource Package:
        14.0.24210
    Visual C++ Compiler/Tools X86 X64 Cross Package:
        14.0.24210
    Visual C++ Compiler/Tools X86 X64 Cross Resource Package:
        14.0.24210
    Visual C++ Core Build Toolset:
        14.0.25420
    Visual C++ Library CRT ARM Desktop Package:
        14.0.24210
    Visual C++ Library CRT ARM Redist Package:
        14.0.24210
    Visual C++ Library CRT ARM Store Package:
        14.0.24210
    Visual C++ Library CRT Source Package:
        14.0.24210
    Visual C++ Library CRT X64 Desktop Package:
        14.0.24210
    Visual C++ Library CRT X64 Redist Package:
        14.0.24210
    Visual C++ Library CRT X64 Store Package:
        14.0.24210
    Visual C++ Library CRT X86 Desktop Package:
        14.0.24210
    Visual C++ Library CRT X86 Redist Package:
        14.0.24210
    Visual C++ Library CRT X86 Store Package:
        14.0.24210
    Visual C++ MSBuild ARM Package:
        14.0.25420
    Visual C++ MSBuild Base Package:
        14.0.25420
    Visual C++ MSBuild Base Resource Package:
        14.0.25420
    Visual C++ MSBuild X64 Package:
        14.0.25420
    Visual C++ MSBuild X86 Package:
        14.0.25420
    Windows App Certification Kit Native Components:
        8.100.26629
    Windows App Certification Kit x64:
        8.100.26795
    Windows Runtime Intellisense Content - en-us:
        8.100.25984
    Windows Software Development Kit:
        8.100.26936
    Windows Software Development Kit DirectX x64 Remote:
        8.100.25984
    Windows Software Development Kit DirectX x86 Remote:
        8.100.25984
    Windows Software Development Kit for Windows Store Apps:
        8.100.26936
    Windows Software Development Kit for Windows Store Apps DirectX x64 Remote:
        8.100.26936
    Windows Software Development Kit for Windows Store Apps DirectX x86 Remote:
        8.100.26936
```

**Comment by max-arnold** [comment] 2019-10-17 20:58
@cmcmarrow Try to install the Intel PROSet Wireless Software.

Or even a simpler test case described here https://github.com/saltstack/salt/issues/53340#issuecomment-498933940

**Comment by max-arnold** [comment] 2020-01-07 13:43
Still valid

**Comment by cmcmarrow** [comment] 2020-02-03 21:38
@damon-atkins we are dropping python2 in Sodium.

**Comment by doesitblend** [comment] 2020-02-27 20:24
ZD-4232

**Comment by cmcmarrow** [comment] 2020-05-04 20:52
This fix does the trick^

**Closed** 2020-05-12 00:32 UTC
Labels: Bug, Confirmed, Fixed Pending Verification, Sodium, Windows, Windows track, ZD
