### ISSUE TITLE
[BUG] Packaging - RHEL8 salt-minion script contains explicit reference to /usr/bin/python3.6

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#61345] opened 2021-12-10 02:09 UTC
**Description**
Installation (or extraction) of the RHEL8 RPM package from the official Salt Project repo results in a `/usr/bin/salt-minion` file with this she-bang:

```bash
#!/usr/bin/python3.6
```

Both 3003 and 3004 are exhibiting this behavior. This is problematic on systems where a newer Python version is installed and is desired to be used.

The issue seems to be coming from line 228 in the `salt.spec` file:

```
CFLAGS="${CFLAGS:-${RPM_OPT_FLAGS}}" LDFLAGS="${LDFLAGS:-${RPM_LD_FLAGS}}" %{__python3} %{py_setup} %{?py_setup_args} build --executable="%{__python3}" %{?*}
```

The `__python3` macro is being used to determine the executable. The macro is determining something about the configuration of the build system which is causing the explicit executable reference.

This does not seem to be an issue with the RHEL7 package.

**Setup**
This can be checked without install using the following commands:

```bash
tmpdir="$(mktemp -d)"
cd "${tmpdir}"
curl -sL https://repo.saltproject.io/py3/redhat/8/x86_64/3004/salt-minion-3004-1.el8.noarch.rpm | rpm2cpio | cpio -idm --quiet
head -n1 usr/bin/salt-minion 
cd -
rm -rf "${tmpdir}"
```
  
**Expected behavior**
Ideally, the she-bang would point to `/usr/bin/python3`... which would allow swapping the symlink using `alternatives`.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
N/A
```
</details>

**Additional context**

**Comment by dmurphy18** [comment] 2021-12-10 18:02
@nicholasmhughes FYI I don't handle the packaging any more, that responsibility has passed to the SRE Team, however I shall follow up to see about getting this addressed.

RHEL 8 did use Python 3.6, but guessing Python 3.8 is now available as part of a stream. Also wondering if RedHat/Centos are messing around with the python3 macros similar to what occurred with RedHat/Centos 7, first Py 3.4, then Py 3.6 and plenty of messing about with swapping of which one was prime and which was alternative, etc.  It is probable that the RHEL 8 spec carried over some of the RHEL 7 spec where Py 3.6 was specifically called out to work-around the RHEL 7 Python version issues described above.  Especially since RHEL 8 when it was release had very few packages and didn't even have EPEL 8 support for months after.

Python 3.6.8 is still the default version of Python for RedHat / Centos 8, hence this is not so much a bug as an enhancement to allow for use of later versions of Python on RedHat / Centos 8, thus marking it such.

Understand the desire to use later versions of Python and will have to allow for them soon with Py 3.6 not long this world, doesn't even make to Christmas, but RedHat has support for ancient stuff on their releases long after their EOL, hence the additional flags concerning this.

**Comment by nicholasmhughes** [comment] 2021-12-10 18:19
@dmurphy18 apologies for the ping. Does mean I can bug the heck out of @bryceml instead?  :wink: 

AFAIK, [RHEL 8 doesn't have a "default" version of Python](https://developers.redhat.com/blog/2019/05/07/what-no-python-in-red-hat-enterprise-linux-8). It seems like it's being installed as part of the [Salt packaging process](https://github.com/saltstack/salt-pack-py3/blob/develop/file_roots/setup/redhat/rhel8/rhel8_setup.sls#L36).

I put in #61346 as well, which addresses the increase in versions as a feature... although it should be addressed sooner rather than later considering the limited time before security patches cease.

This issue is really meant to point out that the explicit version should not be set, which I believe should be tracked separately to avoid having the same problem in a while when 3.8 or 3.9 go EOL.

**Comment by dmurphy18** [comment] 2021-12-10 19:41
@nicholasmhughes No problem, don't expect you to be aware of internal re-assignments and unfortunately we lost @bryceml to the Great Resignation :( .  I believe you are mistaken about Python 3.6 not being the default for RHEL 8 (unless that changed recently), just tried uninstalling salt-minion and salt and no mention of Python 3 being an unused dependency..  Also been awhile, so memory may be faulty, but don't recall having to build Python 3.6 for RHEL 8 so it could be used by Salt.

And a 'dnf list python36' shows it coming from 'appstream'
When I do a clean install of RHEL 8 as a VM, I get Python 3.6

But yes, discussing the issue of handling Py 3.6's demise internally, same applies for other OS's which are still alive with dead components, for example: Debian 9 and Py 3.5.

**Comment by nicholasmhughes** [comment] 2021-12-10 20:38
Correct, Python 3.6 is absolutely available from AppStream. So is 3.8 and 3.9. I stood up a test machine yesterday that didn't have Python by default... but ultimately, the logistics don't matter. Requesting a more generic Python executable is perfectly reasonable any way you slice it. We shouldn't be pointing at any OS having an old version of Python as a reason to *mandate* that version of Python.

**Comment by dmurphy18** [comment] 2022-01-12 01:22
@nicholasmhughes The problem is how do we know which version of Python 3 the user will have installed and wants to function with.  I count 3 versions Py 3.6, Py 3.8 and Py 3.9 and Py 3.10 is probably soon on its way.

The she-bang problem is tied to the output line, as originally stated above
```
225 CFLAGS="${CFLAGS:-${RPM_OPT_FLAGS}}" LDFLAGS="${LDFLAGS:-${RPM_LD_FLAGS}}" /usr/libexec/platform-python setup.py  build --executable="/usr/libexec/platform-python"
```
that is generated by the /usr/libexec/platform-python but I will dig in deeper to ensure I am correct.
This still leaves the issue of /usr/lib/python3.6/site-packages to be cleared up, but perhaps there is something I can try there too, just had a thought to try as typing, will let you know.
This may be out of Salt's control given rpm building output has 
```
Bytecompiling .py files below /home/david/rpmbuild/BUILDROOT/salt-3004-1.el8.x86_64/usr/lib/python3.6 using /usr/libexec/platform-python
+ /usr/lib/rpm/brp-python-hardlink
+ PYTHON3=/usr/libexec/platform-python
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
mangling shebang in /usr/lib/python3.6/site-packages/salt/templates/git/ssh-id-wrapper from /usr/bin/env sh to #!/usr/bin/sh
```

but perhaps there is a way to update the scripts before they are packaged into the rpm and srpm.
It requires overriding regular rpm building tools from RedHat, as that is what is putting it there.

Noting the actual script in Salt has
```
#!/usr/bin/env python3
```

**Comment by dmurphy18** [comment] 2022-01-13 22:36
From private builds of Centos 8, with updated tools keep getting the following she-bang for /usr/bin/salt-minion
```
#!/usr/libexec/platform-python
```
same applies for other utilities.

The Centos / RedHat 8 build of rpms is done by production which I have no rights to hence adding @krionbsd as assignee.  Think the version of Centos 8 used to build packages is an early Centos 8 AMI and hence using earlier tools to provide '/usr/bin/python3.6' rather than the later '/usr/libexec/platform-python'.

Given Centos 8 is now EOL, perhaps should check that using final release Centos 8.5.211 for the build machine.  Playing around with platform-python and alternatives --config python3
```
[root@Unknown tmp]# /usr/libexec/platform-python -V
Python 3.6.8
[root@Unknown tmp]# alternatives --config python3

There are 2 programs which provide 'python3'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/bin/python3.6
   2           /usr/bin/python3.9

Enter to keep the current selection[+], or type selection number: 2
[root@Unknown tmp]# /usr/libexec/platform-python -V
Python 3.6.8
[root@Unknown tmp]# python3 --version
Python 3.9.6
[root@Unknown tmp]#
```
However changing the she-bang still has the issue of dealing with '/usr/lib/python3.6' which is generated by building rpm using macro python3_sitelib.  But given https://fedoraproject.org/wiki/Changes/Platform_Python_Stack , one would think it really should be '/usr/lib/platform-python3.6/'

Inconsistency in RPM tools.

@nicholasmhughes Not sure this is going to be changeable, but still searching to see if there is a way to adjust the default platform-python to recognize using Py 3.9 as in the example above.

Perhaps to only way to work this is altering the she-bang for the /usr/bin utilities doing the more correct method as follows which is the original she-bang in Salt for the scripts
```
[root@Unknown tmp]# cat t1
#!/usr/bin/env python3
import sys
print(sys.version)
[root@Unknown tmp]# ./t1
3.9.6 (default, Aug 25 2021, 16:22:38) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
[root@Unknown tmp]# 
```

but that still leaves '/usr/lib/python3.6' issues

**Comment by dmurphy18** [comment] 2022-02-02 21:34
Closing this as a won't fix, since the solution is to utilize Tiamat based packages with pip install capabilities which should be released in the next major version of Salt, Phosphorous.

The problem is really the rpm tools provided by RedHat, for example: use of the rpm supplied macro **_python3_sitelib_** in the spec file, and currently most RHEL / Centos 8 installations will install Python 3.6.  
This issue is more than merely changing a she-bang given that the macro translates to /usr/lib/python3.6 if Python 3.6 is installed, /usr/lib/python3.8 if Python 3.8 is installed.

If you have other suggestions as to how to resolve this issue, please feel free to re-open.

**Closed by dmurphy18** 2022-02-02 21:34 UTC
Labels: won't-fix, Packaging, python3, package-repo, enhancement
