### ISSUE TITLE
salt-ssh 2015.5.0 does not work on pristine installation

### ISSUE THREAD

**Issue by Mstaaravin** [saltstack/salt#23618] opened 2015-05-12 20:49 UTC
I'm testing salt-ssh on my local laboratory (notebook to virtualized guest)

This is my /etc/salt/roster
```ShellSession
root@lwork:~# cat /etc/salt/roster 
ol601:
 host: 192.168.122.6
 user: oracle
 priv: /home/cmiranda/.ssh/id_rsa
```

This is my salt-ssh version
```ShellSession
root@lwork:~# salt-ssh --versions-report
                  Salt: 2015.5.0
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: 0.1.3
              pycrypto: 2.6.1
               libnacl: 1.4.2
                PyYAML: 3.11
                 ioflo: 1.2.1
                 PyZMQ: 14.4.0
                  RAET: 0.6.3
                   ZMQ: 4.0.5
                  Mako: 1.0.0
 Debian source package: 2015.5.0+ds-1~bpo8+1
```

I can join over ssh to host without any problem, but salt-ssh doesn't work.

```ShellSession
root@lwork:~# salt-ssh 'ol601' test.ping
Permission denied for host ol601, do you want to deploy the salt-ssh key? (password required):
[Y/n] Y
Password for oracle@ol601: 
ol601:
    Traceback (most recent call last):
      File "/tmp/.oracle_440328__salt/salt-call", line 4, in <module>
        salt_call()
      File "/tmp/.oracle_440328__salt/salt/scripts.py", line 227, in salt_call
        client.run()
      File "/tmp/.oracle_440328__salt/salt/cli/call.py", line 59, in run
        caller = salt.cli.caller.Caller.factory(self.config)
      File "/tmp/.oracle_440328__salt/salt/cli/caller.py", line 69, in factory
        return ZeroMQCaller(opts, **kwargs)
      File "/tmp/.oracle_440328__salt/salt/cli/caller.py", line 92, in __init__
        self.minion = salt.minion.SMinion(opts)
      File "/tmp/.oracle_440328__salt/salt/minion.py", line 298, in __init__
        opts['grains'] = salt.loader.grains(opts)
      File "/tmp/.oracle_440328__salt/salt/loader.py", line 508, in grains
        ret = fun()
      File "/tmp/.oracle_440328__salt/salt/grains/core.py", line 1169, in os_data
        grains.update(_linux_gpu_data())
      File "/tmp/.oracle_440328__salt/salt/grains/core.py", line 164, in _linux_gpu_data
        lspci_out = __salt__['cmd.run']('lspci -vmm')
      File "/tmp/.oracle_440328__salt/salt/modules/cmdmod.py", line 524, in _run_quiet
        saltenv=saltenv)['stdout']
      File "/tmp/.oracle_440328__salt/salt/modules/cmdmod.py", line 391, in _run
        .format(cmd, kwargs, exc)
    salt.exceptions.CommandExecutionError: Unable to run command ['lspci', '-vmm'] with the context {'with_communicate': True, 'shell': False, 'env': {'LC_NUMERIC': 'en_US.UTF-8', 'WLS_HOME': '/opt/oracle/Middleware/wlserver_10.3', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'SSH_CLIENT': '192.168.122.1 42233 22', 'SELINUX_USE_CURRENT_RANGE': '', 'LOGNAME': 'oracle', 'USER': 'oracle', 'QTDIR': '/usr/lib64/qt-3.3', 'LC_PAPER': 'en_US.UTF-8', 'PATH': '/opt/oracle/jrockit/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin', 'LANG': 'en_US.UTF-8', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'SHELL': '/bin/bash', 'LC_MEASUREMENT': 'en_US.UTF-8', 'G_BROKEN_FILENAMES': '1', 'JAVA_HOME': '/opt/oracle/jrockit', 'HOME': '/home/oracle', 'LC_MONETARY': 'en_US.UTF-8', 'MW_HOME': '/opt/oracle/Middleware', 'LC_ADDRESS': 'en_US.UTF-8', 'WL_HOME': '/opt/oracle/Middleware/wlserver_10.3', 'SELINUX_ROLE_REQUESTED': '', 'LC_ALL': 'C', 'QTINC': '/usr/lib64/qt-3.3/include', 'LC_IDENTIFICATION': 'en_US.UTF-8', 'LC_TELEPHONE': 'en_US.UTF-8', 'SELINUX_LEVEL_REQUESTED': '', 'SHLVL': '1', 'PWD': '/home/oracle', 'CVS_RSH': 'ssh', 'LC_NAME': 'en_US.UTF-8', 'MAIL': '/var/mail/oracle', 'LC_TIME': 'en_US.UTF-8', 'SSH_CONNECTION': '192.168.122.1 42233 192.168.122.6 22'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -2, 'cwd': '/home/oracle'}, reason: [Errno 2] No such file or directory
```

**Comment by cachedout** [comment] 2015-05-13 06:52
Thanks for the report here. This is a duplicate of issue #23342. Since there is already a long-running discussion there on this issue, I'm going to close yours in favour of keeping the data all in one place. Please subscribe to #23342 for further information and add any details there that might be helpful.

Apologies for the breakage here. From the sounds of things, they thought they had this one fixed but it sounds like that's not the case. :-/

**Closed by cachedout** 2015-05-13 06:52 UTC
