### ISSUE TITLE
make pkg.upgrade work with individual packages or an alternate command

### ISSUE THREAD

**Issue by briffle** [saltstack/salt#7179] opened 2013-09-11 16:19 UTC
There is no simple way to upgrade a single package with salt-stack that I have found. (I use RHEL based distributions, not sure if this happens with debian based)  
For example, in yum, to upgrade the package salt-minion, I would run "yum update salt-minion"

However inside salt, using:
salt 'server1' pkg.upgrade salt-minion
to update the salt-minion package rather unintuitively upgrades all packages on the server.  This could be very bad, as many of them might not be 'approved' for production, for example. 

I see in the documentation (http://docs.saltstack.com/ref/modules/all/salt.modules.yumpkg.html) that I can find the newest version, and install a particular version, but there is no simple way to just upgrade a single package like yum does.

**Comment by pille** [comment] 2015-01-28 13:57
just to bring this topic up again: this would be really useful for security updates.
it's sad to workaround this using ```cmd.run``` in the meantime...

**Comment by basepi** [comment] 2015-01-28 23:20
Thanks for the bump, @pille. This would be awesome to have.

**Comment by pille** [comment] 2015-01-29 00:09
implemented #16293 with 13f7fe1d8e9e66b04773249b6a86e32b99598848 via #20148

**Comment by robgil** [comment] 2015-01-29 04:18
Only upgrade is handy, but rolling back with downgrade would be handy. Also upgrading a package to newer versions.

**Comment by racooper** [comment] 2015-01-29 14:29
nice work @pille. now just need to get the RHEL/yum side take care of! (I'd look at it, but I'm not much of a code writer...)

**Comment by stardust85** [comment] 2015-08-05 10:51
Implemented this for yum-based systems in PR #26022

**Comment by cstockton** [comment] 2016-02-02 22:35
In december I made the mistake of running "pkg.upgrade <somepkg>" .. I didn't notice until the consequence of it arose this week. That said **was completely my fault** for not RTFM'ing carefuly or being cautious with execution on 1 host manually but I think that full system upgrades should be more heavilly guarded.

I understand if maybe the project has a higher design philosophy behind the decisions for this interface to deviate from the distros.. but at the very least when an extra argument to pkg*.upgrade is detected it should notify the user that "extraneous argument to pkg.upgrade, this command is for upgrading the entire system".. Just my two cents.

**Comment by dadrian** [comment] 2017-08-17 13:52
I just made the exact same mistake as @cstockton. While obviously I should have been more careful, this is a ridiculous and anti-user default.

**Comment by stardust85** [comment] 2017-08-18 10:16
It is also discussed here: https://github.com/saltstack/salt/issues/26202

**Comment by cstockton** [comment] 2017-08-18 17:00
@dadrian Ah yes, the day I did a full system upgrade on a live 30 machine elasticsearch cluster. By some miracle java wasn't upgraded, thank goodness! Hope you had a little luck too.

**Comment by racooper** [comment] 2017-08-18 17:10
someone needs to mark #26202 as a duplicate of this ticket and close it.

**Comment by stardust85** [comment] 2017-08-21 08:20
What about renaming pkg.update to pkg.update_all? This would be explicit enough :) And pkg.update would require an argument of course

**Comment by dadrian** [comment] 2017-08-21 13:27
@cstockton That's exactly what I did.

**Comment by timwsuqld** [comment] 2019-01-18 04:41
This issue is still valid.

**Comment by dmurphy18** [comment] 2023-09-25 20:37
@briffle Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.3 and if still an issue, please open a new issue, which will have metrics in tracking issues.

This looks more like a feature request, if still interested, can you open a feature request using the new template, this allows for matrices from the template to track issues and allows for more information as to what problems are encountered or requested.

**Closed by dmurphy18** 2023-09-25 20:37 UTC
Labels: Feature
