### ISSUE TITLE
Exception when setting up development environment

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#19485] opened 2015-01-07 21:35 UTC
I'm following http://docs.saltstack.com/en/latest/topics/development/hacking.html#running-a-self-contained-development-version and I'm running into an exception:

```bash
$ salt-key -c ./etc/salt -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
Exception TypeError: 'an integer is required' in <bound method MasterEvent.__del__ of <salt.utils.event.MasterEvent object at 0x106331310>> ignored
```

I have 242d4d49068f6cab702496e23554eebdb9586247 checked out.

**Comment by rallytime** [comment] 2015-01-08 18:52
I've seen this one as well. Thanks for the report!

**Comment by rallytime** [comment] 2015-01-09 22:40
This is actually a duplicate of #19216. I'm going to close this one in favor of the other one. Thanks!

**Closed by rallytime** 2015-01-09 22:40 UTC
Labels: Bug, Duplicate, Medium Severity
