### ISSUE TITLE
firewalld state function unexpected behavior

### ISSUE THREAD

**Issue by reyescameron17** [saltstack/salt#43291] opened 2017-08-31 19:48 UTC
### Description of Issue/Question
Using firewalld.present with a single port, the salt output shows multiple unnamed services being removed permanently from firewalld rules, most importantly removing ssh from the rules.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```yaml
#jenkins.sls
create_jenkins_user:
  group.present:
    - name: jenkins
  user.present:
    - fullname: jenkins
    - name: jenkins
    - shell: /bin/bash
    - home: /home/jenkins
    - groups:
      - wheel
      - jenkins

install_openjdk:
  pkg.installed:
    - name: java-1.8.0-openjdk
    - refresh: True

# Put nfs mount here to point jenkins_home to the mount instead of storing config locally

artifactory:
  pkgrepo.managed:
    - humanname: jenkins-artifactory
    - name: Artifactory
    - enable: True
    - baseurl: some_url

install_jenkins:
  cmd.run:
    - name: mkdir -p /data/jenkins_home
    - unless: ls -lrt /data/jenkins_home
  environ.setenv:
    - name: JENKINS_HOME
    - value: /data/jenkins_home
    - update_minion: True
  pkg.installed:
    - name:  jenkins-2.76-1.1

firewall_configuration:
  firewalld.present:
    - name: external
    - ports:
      - 8081/tcp
```

### Steps to Reproduce Issue
I simply ran salt-call --local -l info state.apply jenkins and the output for firewalld shows it removing ssh.

```
...
[INFO    ] Running state [external] at time 15:09:39.103425
[INFO    ] Executing state firewalld.present for [external]
[INFO    ] Executing command '/bin/firewall-cmd --get-zones --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --get-icmptypes --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --list-icmp-blocks --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --list-all --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --remove-masquerade --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --list-ports --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --list-all --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --add-masquerade --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --add-port=8081/tcp --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --list-forward-ports --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --list-services --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --remove-service=ssh --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --list-interfaces --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --list-sources --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --zone=external --list-rich-rules --permanent' in directory '/root'
[INFO    ] Executing command '/bin/firewall-cmd --reload' in directory '/root'
[INFO    ] Made the following changes:
'masquerade' changed from 'absent' to 'Masquerading successfully disabled.'

[INFO    ] Completed state [external] at time 15:09:42.491801 duration_in_ms=3388.376
...
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
~]# salt-call --version
salt-call 2017.7.1 (Nitrogen)

**Comment by reyescameron17** [comment] 2017-08-31 21:15
Forgot to mention:
```
~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

**Comment by gtmanfred** [comment] 2017-08-31 22:44
This is a duplicate of this issue

https://github.com/saltstack/salt/issues/41075

**Closed by gtmanfred** 2017-08-31 22:44 UTC
