### ISSUE TITLE
Unable to target minions via ipcidr in 2015.8

### ISSUE THREAD

**Issue by bergemalm** [saltstack/salt#29188] opened 2015-11-25 13:59 UTC
Targeting minions via cidr/ip doesn't work. (ok in 2015.5.3).

    Salt Version:
               Salt: 2015.8.1
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.7.0
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: centos 7.0.1406 Core
            machine: x86_64
            release: 3.10.0-123.9.3.el7.x86_64
             system: CentOS Linux 7.0.1406 Core

--
    [root@saltmaster]# salt 'test01*' test.ping
    test01:
       True
    [root@saltmaster]# salt 'test01*' grains.item ipv4
    test01:
      ----------
      ipv4:
          - 10.3.139.1
          - 127.0.0.1
    [root@saltmaster]# salt -S '10.3.139.1' test.ping
    No minions matched the target. No command was sent, no jid was assigned.
    ERROR: No return received
    [root@saltmaster]# salt -C 'S@10.3.139.1' test.ping
    No minions matched the target. No command was sent, no jid was assigned.
    ERROR: No return received

**Comment by jfindlay** [comment] 2015-11-25 21:22
@bergemalm, thanks for the report.  I am able to reproduce this with the exception that for me it only fails sometimes.

```console
# salt -S '10.210.201.55' test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```
```console
# salt -S '10.210.201.55' grains.item id
jmoney-main:
    ----------
    id:
        jmoney-main
```
```console
# salt -S '10.210.201.55' test.ping
jmoney-main:
    True
```
```console
# salt -S '10.210.201.55' grains.item id
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```
```console
# salt -S '10.210.201.55' test.versions
jmoney-main:
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: debian 8.2
            machine: x86_64
            release: 3.16.0-4-amd64
             system: debian 8.2
```

**Comment by bergemalm** [comment] 2015-11-25 21:40
@jfindlay, yes I've noticed that it may work very occasionally but haven't found any pattern. Also this works fine:

    # salt 'test01' match.compound 'S@10.3.139.1'
    test01:
      True

**Comment by gladiatr72** [comment] 2016-01-23 02:58
Alas, not so.  It works, technically, but if you have a group of minions on 10.64.0.0/16  and another group on 172.34.0.0/16

```
salt -C 'S@10.64.0.0/8' test.ping
```

returns

```
minion1-10-64
      True
minion2-10-64
      True
minion3-10-64
      True
```
long timeout pause while waiting for...

```
minion1-172-31
    Minion did not return. [No response]
minion2-172-31
    Minion did not return. [No response]
etc...
```

s'broke!

**Comment by hgfischer** [comment] 2016-01-28 15:47
Same issue here. It's not working anymore.

**Comment by rallytime** [comment] 2016-02-12 23:12
Thank you for all of the feedback on this issue. This regression looks to be caused by the changes in #24282.

**Comment by The-Loeki** [comment] 2016-02-13 21:52
@fantasy88 was correct in #30962 about the `self.opts['grains']` making no sense in the master-side matching context ;) 
The other thing he notes is that '10.0.0.1/32' wouldn't match because it'd be handled as a net rather as an IP; I can't reproduce this, it matches nicely over here?

There's a few different described behaviours in the various issues here:
* No matches at all: I had this happen to me when I started debugging. Updated the salt master to the latest git 2015.8 code and that was suddenly gone. My guess is therefore unrelated & fixed, at least in git.
* Non-matching minions 'not responding': Should be fixed in PR. 

It's quite likely some of the erratic behaviour described here is related to #17204, since it induces pretty much the same behaviour patterns.

Anyway, first shot at fixxing, see how it goes.

**Comment by fantasy86** [comment] 2016-02-14 03:39
I don't know if IP address 'xx.xx.xx.xx' handled as subnet 'xx.xx.xx.xx/32' affects the matching, only noticed that the single ip address specific code can not be reached as expected, because all ip/subnet will be handled by the subnet matching logic.

**Comment by The-Loeki** [comment] 2016-02-14 16:03
@fantasy86 you're right & it should be fixed with the new commit. I probably hadn't noticed at the time because (semi-accidentally) the in_subnet does actually match (while the actual address matching didn't work, <duh>). 

I've refactored somewhat to improve performance master-side as well, casting only once instead of casting over & over again.

**Comment by rallytime** [comment] 2016-02-16 17:24
@The-Loeki Thank you for submitting that fix. I ran some quick tests on your PR, and the breakage I was seeing has been resolved.

@bergemalm Can you confirm this issue is fixed for you, too?

**Comment by bergemalm** [comment] 2016-02-16 20:12
@rallytime Yup, problem solved! :)

**Comment by rallytime** [comment] 2016-02-16 20:22
@bergemalm Awesome! We've already started the tagging/testing release process for 2015.8.7, so this particular fix didn't make it into that release. However, this fix should make it into the release after that, which will come out sometime in March. 

We can either keep this bug open until then, or we can close it now since it's confirmed fixed. What do you think?

**Comment by bergemalm** [comment] 2016-02-17 06:22
@rallytime You can close this, fine with me.

**Comment by rallytime** [comment] 2016-02-17 15:42
Thanks everyone!

**Closed by rallytime** 2016-02-17 15:42 UTC
Labels: Bug, Confirmed, Core, Fixed Pending Verification, High Severity, P2, Regression
