### ISSUE TITLE
Question about the online documentation for salt commands

### ISSUE THREAD

**Issue by erwindon** [saltstack/salt#49271] opened 2018-08-22 23:11 UTC
### Description of Issue/Question
The online documentation for Salt commands is easier to use than issuing salt `sys.doc` commands.
The online documentation is in https://docs.saltstack.com/en/latest/ref/modules/all/index.html.
However, some modules are listed under a different name.
e.g. module `cmd` is not present in the list.
One has to know that its documentation is actually named `cmdmod`.
Note that the examples in that documentation properly use e.g. `cmd.run`.
This happens for several modules.
How can one predict the alternative names based on the salt command?

### Setup
the current website

### Steps to Reproduce Issue
Go to https://docs.saltstack.com/en/latest/ref/modules/all/index.html.
Try to find the documentation for `cmd.run`

### Versions Report
N/A

**Comment by gtmanfred** [comment] 2018-08-23 13:28
Yup, that is one of the problems with the way that this documentation is loaded.

We use `sphinx` autodoc, so we have a .rst file for each one of the automod documents.

https://github.com/saltstack/salt/blob/2018.3/doc/ref/modules/all/salt.modules.cmdmod.rst

The problem is with automod, you have to specify the specific file to load from, so in this case, `salt/modules/cmdmod.py`  while we build in a way to overload module names, https://github.com/saltstack/salt/blob/2018.3/salt/modules/cmdmod.py#L64

We would be open to a way to not have to do this, and be able to use the virtualname for the documentation, but as of the last time i looked, it was not possible.

Here is the doc for the autosummary that is from sphinx https://github.com/saltstack/salt/blob/develop/doc/ref/modules/all/index.rst

**Comment by erwindon** [comment] 2018-08-23 15:28
I found it.
Calling `test.providers` first to see where things are.

**Comment by gtmanfred** [comment] 2018-08-23 15:44
:+1: cool, yeah that would work.

I am going to close this issue then.

**Closed by gtmanfred** 2018-08-23 15:44 UTC
Labels: Pending Discussion
