### ISSUE TITLE
unpack(b) received extra data

### ISSUE THREAD

**Issue by yermulnik** [saltstack/salt#24892] opened 2015-06-23 11:07 UTC
```python
(jail) [root#jail_salt][w:0][j:0][.../salt/states]> salt-run jobs.list_jobs
[CRITICAL] Could not deserialize msgpack message: ��fun_args��20150623072103827288�jid�20150623072108848695�return��tgt_type�compound�jid�20150623072103827288�tgt�&( G@roles:balancer and G@cluster:red )�pid��`�ret��user�sudo_yz�arg��nginx�fun�state.sls�retcode�successуcmd�_return�_stamp�2015-06-23T07:21:08.874430�fun�saltutil.find_job�id�dt-bal0403This often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/runners/jobs.py", line 211, in list_jobs
    ret = mminion.returners['{0}.get_jids'.format(returner)]()
  File "/usr/local/lib/python2.7/site-packages/salt/returners/local_cache.py", line 282, in get_jids
    for jid, job, _, _ in _walk_through(_job_dir()):
  File "/usr/local/lib/python2.7/site-packages/salt/returners/local_cache.py", line 67, in _walk_through
    job = serial.load(salt.utils.fopen(load_path, 'rb'))
  File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
(jail) [root#jail_salt][w:0][j:0][.../salt/states]>
```

**Comment by alf** [comment] 2015-06-24 08:00
This is a duplicate of #22734

**Comment by rallytime** [comment] 2015-06-24 13:17
Thanks for this report @yermulnik and for the link to the duplicate, @alf. Since we have more information/discussion on the earlier bug, I am going to close this one in favor of the other. Thanks!

**Closed by rallytime** 2015-06-24 13:17 UTC
Labels: Duplicate
