### ISSUE TITLE
salt cp.push return False

### ISSUE THREAD

**Issue by honghuizheng** [saltstack/salt#36860] opened 2016-10-08 10:42 UTC
I want to sync files from minions,but master return False，and sometimes，minions had a log “Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master. ”. But my configure is right.
### Setup

saltmaster configure file：
interface: 0.0.0.0
file_roots:
  base:
    - /data/services/salt

pillar_roots:
  base:
    - /data/services/pillar

grains_roots:
  base:
    - /data/services/_grains

file_recv: True
log_level: debug
keep_jobs: 24
worker_threads: 20
nodegroups:
### Steps to Reproduce Issue

[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/a.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/a.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ubuntu
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ubuntu_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/1b/663a572149aee5a9819899d85f76f6/.minions.p
[DEBUG   ] get_iter_returns for jid 20161008183739386188 sent to set(['myip']) will timeout at 18:37:44.391872
[DEBUG   ] Checking whether jid 20161008183739386188 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ubuntu_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
[DEBUG   ] jid 20161008183739386188 return from myip
[DEBUG   ] LazyLoaded nested.output
myip:
    False
[DEBUG   ] jid 20161008183739386188 found all minions set(['myip'])
### Versions Report

salt-master：salt 2016.3.3 (Boron)
salt-minion 2014.7.0 (Helium)

**Comment by gtmanfred** [comment] 2016-10-10 15:16
Unfortunately I am unable to reproduce this.

Can you verify that you have restarted the salt master after adding the file_recv: True?

Also, salt 2014.7 is no longer supported and has been End of Lifed, can you update to a newer version of the minion if restarting the master still does not work?

Thanks,
Daniel

**Comment by gtmanfred** [comment] 2016-12-29 18:15
I am closing this in favor of #37133

**Closed by gtmanfred** 2016-12-29 18:15 UTC
Labels: Pending Discussion
