### ISSUE TITLE
salt-run manage.status command on master can't get down minions status under syndic

### ISSUE THREAD

**Issue by shenjh369** [saltstack/salt#25028] opened 2015-06-29 08:18 UTC
In my vm environment, I have one master(snail-linux), one syndic(syndic-B) and three minions(client-B1,minion_win2003,client-B2) under the syndic. The minion process on the syndic connect directly to the upper master. 
On the master, the manage.status shows the following output:

<pre><code>[root@snail-linux ~]# salt-run manage.status 
down:
up:
    - client-B1
    - minion_win2003
    - syndic-B
</code></pre>

Master result shows no down minion in the list.

On the syndic, the manage.status shows the following output:

<pre><code>[root@syndic-B ~]# salt-run manage.status
down:
    - client-B2
up:
    - client-B1
    - minion_win2003
</code></pre>

Syndic result shows the down minion(client-B2) is in the down list.

My linux version is Centos 6.6, below is the versions report in my environment on both master and minions:

<pre><code>[root@snail-linux ~]# salt-run --versions-report
           Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.2
   msgpack-pure: 0.1.3
       pycrypto: 2.0.1
        libnacl: 1.4.3
         PyYAML: 3.10
          ioflo: 1.3.6
          PyZMQ: 14.3.1
           RAET: 0.6.3
            ZMQ: 3.2.5
           Mako: 0.3.4
</code></pre>

 It seems that the manage.status command on master can get all up minions but failed to get down minions under the syndic,  could this be a problem?

**Comment by jtand** [comment] 2015-07-01 19:29
@shenjh369 Thanks for this bug report, I was able to reproduce this as well. It looks like a bug to me.

**Comment by nikatjef** [comment] 2015-11-11 16:38
Greetings,

 We first spotted this issue back in 2014.1.10, and are still seeing it in 2015.8.0.  To give an idea of what we are seeing, I have attached two graphs;
![count_from_mom](https://cloud.githubusercontent.com/assets/1252723/11094648/ad666496-8845-11e5-8dab-9e2e7f0e4bfe.png)
This graph shows the total number of minions, as reported by 'salt-run manage.status', averaged over three hours for the past 3 months.  Those massive downward spikes are after the averaging.

In this configuration, we have;
  - 1 x Salt M-O-M
  - 5 x Salt Syndic / Master (one for each data center)
  - ~750 x Salt Minions (Across 5 data centers)

![count_from_primary_syndic](https://cloud.githubusercontent.com/assets/1252723/11094647/ad628fb0-8845-11e5-8d37-a4276e7b625e.png)
This graph shows the same time period from the perspective of our prime syndic, but here the values are taken every hour.  As you can see, we do occasionally remove a few minions, but never 500+ at a time.

Here are the versions;

    jwells@saltmom:~$ sudo salt-run --versions-report
               Salt: 2014.1.10
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
                ZMQ: 4.0.4

    jwells@saltsyndic:~$ sudo salt-run --versions-report
               Salt: 2014.1.10
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
                ZMQ: 4.0.4

We are also in the process of doing an upgrade to Salt 2015.8.x and we are noticing the same thing in our early deployments as seen here;
![count_from_new_mom](https://cloud.githubusercontent.com/assets/1252723/11095113/4a7985e0-8848-11e5-8def-c63d037b8750.png)
We have made no changes to the over the last 12 hours (instrumentation was just added to this environment yesterday.

This new environment is also a bit different in structure as we have not pushed it to the other data centers yet and we have learned from some previous issues.  We have;
  - 2 x Salt Master / Minion : Peers using Gluster to share /etc/salt/pki/master
  - 2x2 x Salt Syndic / Master / Minion : Two sets of two peers using Gluster
  - 5 x Salt Minions

I should also point out that all of the servers in the new environment, are on the same network and in the same rack even.

And here are the versions;

    jwells@saltmom:~$ sudo salt-run --versions-report
    Salt Version:
                 Salt: 2015.8.0
 
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: Not Installed
          pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
 
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-66-generic
             system: Ubuntu 14.04 trusty

    jwells@saltsyndic:~$ sudo salt-run --versions-report
    Salt Version:
                 Salt: 2015.8.0
 
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: Not Installed
          pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
 
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-66-generic
             system: Ubuntu 14.04 trusty

One final note.  From what I can tell, salt commands are getting to the minions, but the  grains cache ( see: https://github.com/saltstack/salt/issues/28676 ) and various salt returns are not making it back from the minions to the Salt M-O-Ms.

**Comment by tsaridas** [comment] 2016-10-10 21:26
@nikatjef does the issue persist with newer version ?

**Comment by nikatjef** [comment] 2016-10-10 21:59
We have upgraded to 2016.3.X and this appears to be working correctly.

**Comment by rallytime** [comment] 2016-10-10 22:56
Thanks again @nikatjef for letting us know!

@shenjh369  I am not sure if you have been able to upgrade to 2016.3.x yet, but I wanted to ping you on this issue to get your feedback before closing. Marking as `Fixed Pending Verification`.

**Comment by rallytime** [comment] 2016-11-01 22:14
Since we haven't gotten a response for the OP here, I am going to close this. Let us know if this pops up again and we can take another look. Thanks!

**Closed by rallytime** 2016-11-01 22:14 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P3, Runners

**Comment by jlrcontegix** [comment] 2022-11-16 18:53
We are seeing this as a regression in 3005.1.  When running 'salt-run manage.status' on the MoM it reports no down minions, but when we run it on our Syndic we see multiple down minions.
