### ISSUE TITLE
pkg.latest fails on Lithium on arch linux

### ISSUE THREAD

**Issue by Investocat** [saltstack/salt#23667] opened 2015-05-13 16:09 UTC
This used to work just fine with salt 2014.7.5

    ----------
              ID: linux
        Function: pkg.latest
          Result: False
         Comment: An error was encountered while checking the newest available version of package(s): Unable to run command ['LANG=C', 'pacman', '-Sy'] with the context {'with_communicate': True, 'shell': False, 'env': {'LANG': 'en_US.UTF-8', 'TERM': 'xterm-color', 'SHELL': '/bin/bash', 'SHLVL': '2', 'SSH_TTY': '/dev/pts/0', 'SSH_AUTH_SOCK': '/tmp/ssh-1DkyMchlrJ/agent.32092', 'SSH_CLIENT': '10.0.0.2 53802 22', 'PWD': '/root', 'LOGNAME': 'root', 'USER': 'root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl', 'MAIL': '/var/mail/root', 'PYTHONUNBUFFERED': 'true', 'SSH_CONNECTION': '10.0.0.2 53802 10.0.0.14 22', 'HOME': '/root', 'LC_ALL': 'C', '_': '/usr/bin/salt-call'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -1, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
         Started: 09:05:50.674616
        Duration: 4.302 ms
         Changes:  

Pacman exists:

    # which pacman
    /usr/bin/pacman

And as you can see, /usr/bin/ is listed in the PATH being used for the command.

**Comment by rallytime** [comment] 2015-05-13 22:07
Thanks for this report @Investocat. We discovered this bug recently as well as an artifact of the change documented [here - see the warning](http://docs.saltstack.com/en/latest/topics/releases/2015.5.0.html). It was fixed with #23424, and then I have back-ported this change to 2015.5 right now with #23690. This will be fixed in 2015.5.1.

The quick workaround for now would just be to add `python_shell=True` to your affected state, or you can also see the other workarounds in the link above.

**Comment by codekoala** [comment] 2015-05-16 04:07
Perhaps I don't understand what's supposed to be handled by the referenced issues, but this only worked for me when I removed the ``LANG=C`` before ``pacman -Sy``. It becomes obvious that this is the problem because it's the first item in the command list (which must be an executable, not an environment variable). Python's ``subprocess.Popen`` has an ``env`` parameter for environment variables.

**Comment by codekoala** [comment] 2015-05-16 04:10
Nevermind. I see it now. I thought the file I edited already included the ``python_shell=True``.

**Comment by murdegern** [comment] 2015-06-09 07:49
This doesn't seem fixed in 2015.5.1, or I have another error. For me, it says

          ID: pkg_uptodate
    Function: pkg.uptodate
      Result: False
     Comment: error: target not found: |
              error: target not found: egrep
              error: target not found: ^\s|^:Root      : /
              Conf File : /etc/pacman.conf
              DB Path   : /var/lib/pacman/
              Cache Dirs: /var/cache/pacman/pkg/  
              Lock File : /var/lib/pacman/db.lck
              Log File  : /var/log/pacman.log
              GPG Dir   : /etc/pacman.d/gnupg/
              Targets   : |  egrep  ^\s|^:
              :: Synchronizing package databases...
              downloading core.db...
              downloading extra.db...
              downloading community.db...
              downloading alarm.db...
               aur is up to date
               enda is up to date
     Started: 09:44:16.213174
    Duration: 4817.127 ms
     Changes:  

which I think is the same problem - the pipes and egrep are interpreted as parameters to pacman.

As for the quick fix: How do I add python_shell=True to a YAML state file?

**Comment by rallytime** [comment] 2015-06-09 15:19
@murdegern I think I may have misspoken above about adding python_shell to the state file. So you can either do one of the options in the [release notes warning](http://docs.saltstack.com/en/latest/topics/releases/2015.5.0.html) or you could also download the latest `salt/modules/pacman.py` files from the 2015.5 branch that now includes the fix from @aneeshusa (#24490) and put it in your _modules directory and deploy it to your minions. That will override your current file from 2015.5.1 with the pacman.py file with the fix.

Or, the fix will be available in 2015.5.3.

**Comment by thatch45** [comment] 2015-06-09 15:21
@gtmanfred you may consider adding #24490 as a patch to the Arch package

**Comment by rallytime** [comment] 2015-06-09 15:24
Also, I was able to reproduce the failure from @murdegern and then tested the fix from @aneeshusa and it fixed the errors seen above. Since the original bug report was fixed some time ago, and the secondary problem has also been fixed, I am going to close this issue.

If this pops up again after applying the fixes from above, please leave a comment and we will be happy to reopen. Thanks!

**Closed by rallytime** 2015-06-09 15:24 UTC
Labels: Bug, Execution Module, Fixed Pending Verification, High Severity, P1, Platform Mgmt

**Comment by gtmanfred** [comment] 2015-06-09 17:20
@thatch45 I will add it now.

**Comment by gtmanfred** [comment] 2015-06-09 17:30
fixed

https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/salt&id=9ea25cd5dbc8f1a054caeff5da1ea6634e27e384
