### ISSUE TITLE
Unicode decode issue using vault read secret

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#47103] opened 2018-04-16 16:03 UTC
### Description of Issue/Question
Getting Attribute Error for a unicode object with 2018.3.0 when reading a secret from the Vault.
The same code works fine with 2017.7.5 and earlier

### Setup
```
root@c7master:/srv/salt# cat test.sls 
{% set secret_path = 'secret/saltstack/automation' %}
{% set bld_release_public_key = 'bld_release_public_key' %}
{% set pub_key_b64 = salt['vault'].read_secret(secret_path, bld_test_public_key) %}

debug_cmd:
  cmd.run:
    - name: |
        echo "this is a test for read secret from vault"

Need to have vault active on the Master and Minion, both on the same node.

/etc/salt/master.d/vault.conf
vault:
    url: http://A.B.C.D:PPPP
    auth:
      method: token
      token: xxxxxxxxxxxxx
    policies:
      - my-dev-policy

/etc/salt/master.d/peer_run.conf
peer_run:
  .*:
    - vault.generate_token

root@c7master:/etc/salt/master.d# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

### Steps to Reproduce Issue
m7m minion id for salt-minion co-located on the master

salt m7m state.show_sls test

/var/log/salt/minion log.
```
  1 
  2 2018-04-10 15:10:59,132 [salt.loaded.int.utils.vault:81  ][ERROR   ][869] Failed to get token from master! Response is not a dict: Exception occurred in runner vault.generate    _token: Traceback (most recent call last):
  3   File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
  4     data['return'] = self.functions[fun](*args, **kwargs)
  5   File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
  6     'Token generation request for %s (impersonated by master: %s)'.
  7 AttributeError: 'unicode' object has no attribute 'minion_id'
  8 
  9 2018-04-10 15:10:59,132 [salt.loaded.int.module.vault:148 ][ERROR   ][869] Failed to read secret! CommandExecutionError: Exception occurred in runner vault.generate_token: Tr    aceback (most recent call last):
 10   File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
 11     data['return'] = self.functions[fun](*args, **kwargs)
 12   File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
 13     'Token generation request for %s (impersonated by master: %s)'.
 14 AttributeError: 'unicode' object has no attribute 'minion_id'
 15 
 16 2018-04-10 15:10:59,133 [salt.utils.templates:180 ][ERROR   ][869] Rendering exception occurred
 17 Traceback (most recent call last):
 18   File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
 19     output = render_str(tmplstr, context, tmplpath)
 20   File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 410, in render_jinja_tmpl
 21     tmplstr)
 22 SaltRenderError: Problem running salt function in Jinja template: Exception occurred in runner vault.generate_token: Traceback (most recent call last):
 23   File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
 24     data['return'] = self.functions[fun](*args, **kwargs)
 25   File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
 26     'Token generation request for %s (impersonated by master: %s)'.
 27 AttributeError: 'unicode' object has no attribute 'minion_id'
 28 ; line 5
 29 
 30 ---
 31 
 32 {% set secret_path = 'secret/saltstack/automation' %}
 33 
 34 {% set bld_release_public_key = 'bld_release_public_key' %}
 35 {% set pub_key_b64 = salt['vault'].read_secret(secret_path, bld_test_public_key) %}    <======================
 36 
 37 debug_cmd:
 38   cmd.run:
 39     - name: |
 40         echo "this is a test for read secret from vault"
 41 [...]
 42 ---
```

### Versions Report
```
root@c7master:/etc/salt/master.d# salt-run --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by terminalmage** [comment] 2018-04-16 17:32
Duplicate of https://github.com/saltstack/salt/issues/46864, already fixed in 01a5b88.

**Closed by terminalmage** 2018-04-16 17:32 UTC
Labels: 2018.3.1, Bug, Has Testcase
