### ISSUE TITLE
unit.utils.test_vmware.DisconnectTestCase.test_disconnect_raise_vim_fault

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52820] opened 2019-05-02 22:13 UTC
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.utils.test_vmware/DisconnectTestCase/test_disconnect_raise_vim_fault)
---

<module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'Disconnect'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 2005, in test_disconnect_raise_vim_fault
    with patch('salt.utils.vmware.Disconnect', MagicMock(side_effect=exc)):
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1393, in __enter__
    original, local = self.get_original()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1367, in get_original
    "{} does not have the attribute {!r}".format(target, name)
AttributeError: <module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'Disconnect'
		
```

**Comment by waynew** [comment] 2019-05-02 22:14
- unit.utils.test_vmware.DisconnectTestCase.test_disconnect_raise_no_permission
- unit.utils.test_vmware.DisconnectTestCase.test_disconnect_raise_runtime_fault
- unit.utils.test_vmware.DisconnectTestCase.test_disconnect

Also fails on the above

**Comment by Ch3LL** [comment] 2019-05-03 13:46
duplicate of https://github.com/saltstack/salt/issues/51886

**Closed by Ch3LL** 2019-05-03 13:46 UTC
Labels: 2019.2.1, Test Failure
