### ISSUE TITLE
Errors in rabbitmq_user.present when user already exists

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#25125] opened 2015-07-02 13:26 UTC
I'm currently upgrading my environments from `2015.5.0` to `2015.5.2` using the Ubuntu packages. After upgrading I am seeing an error with the `rabbitmq_user.present` state when the user already exists in rabbit. 

My state definition:

```saltstack
rabbit-ensure-cinder-user-present:
  rabbitmq_user.present:
    - name: {{ pillar.get('rabbit_cinder_user','cinder') }}
    - password: {{ pillar.get('rabbit_cinder_password','CINDER-RABBIT-PASSWORD') }}
    - force: True
    - perms:
      - '/':
        - '.*'
        - '.*'
        - '.*'
    - require:
      - pkg: rabbitmq-server
      - service: service-rabbitmq-server
```

Here's the output from a highstate on my systems with `2015.5.0` installed:

              ID: rabbit-ensure-cinder-user-present
        Function: rabbitmq_user.present
            Name: cinder
          Result: True
         Comment: Changing password for user "cinder" ...
         Started: 13:16:13.908094
        Duration: 1718.377 ms
         Changes:   
                  ----------
                  new:
                      Set password.
                      Set permissions ['.*', '.*', '.*'] for vhost /
                  old:

After upgrading to `2015.5.2` I now get this:

              ID: rabbit-ensure-cinder-user-present
        Function: rabbitmq_user.present
            Name: cinder
          Result: False
         Comment: Creating user "cinder" ...
                  Error: user_already_exists: cinder
         Started: 13:11:34.165086
        Duration: 1999.851 ms
         Changes:

**Comment by marek-obuchowicz** [comment] 2015-07-02 20:41
This is fixed by this commit in develop: https://github.com/saltstack/salt/commit/a154280b34c58d3d3e5f02ffa7450a2495dc7cbd

**Comment by jtand** [comment] 2015-07-06 19:42
@corywright This should be fixed in 2015.5.3, but @marek-obuchowicz has great workaround in the mean time!  Thanks!

**Comment by multani** [comment] 2015-07-15 11:28
The fix proposed by @marek-obuchowicz in https://github.com/saltstack/salt/commit/a154280b34c58d3d3e5f02ffa7450a2495dc7cbd doesn't work (anymore?) for me.

This is the output of ``rabbitmqctl list_users`` here (running RabbitMQ 3.3.5-1.1 on Debian Jessie):

```
Listing users ...
administrator	[administrator]
guest	[administrator]
...done.
```

Notice that the ```...done.``` last line ends up with a period, whereas the fix aforementioned doesn't check that, hence it fails with the following error:

```
          ID: rabbitmq_user_administrator
    Function: rabbitmq_user.present
        Name: administrator
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/rabbitmq_user.py", line 101, in present
                  user_exists = __salt__['rabbitmq.user_exists'](name, runas=runas)
                File "/var/cache/salt/minion/extmods/modules/rabbitmq.py", line 150, in user_exists
                  user_list = list_users(runas=runas)
                File "/var/cache/salt/minion/extmods/modules/rabbitmq.py", line 116, in list_users
                  return _output_to_dict(res, func)
                File "/var/cache/salt/minion/extmods/modules/rabbitmq.py", line 94, in _output_to_dict
                  key, values = row.split('\t', 1)
              ValueError: need more than 1 value to unpack
     Started: 13:27:19.051816
    Duration: 14
```

Fixing this is "easy", as it involves adding a period at the end of the ``...done`` check in the ``_strip_listing_to_done`` function, but this still makes the parsing of rabbitmqctl very fragile...

**Comment by multani** [comment] 2015-07-15 11:35
Isn't making a more parsing-friendly ``rabbitmqctl``, in this case, something that should be reported upstream?
It's a bit of a pain to have bugs due to such problems and I'm pretty sure that would be useful for other projects as well.

**Comment by multani** [comment] 2015-07-15 11:43
I believe the ``...done.`` was changed [in this commit](https://github.com/rabbitmq/rabbitmq-server/commit/a6c97140182effe407e483ff1287225d26058b36), which would be RabbitMQ 3.4.0+.

**Comment by mlavin** [comment] 2015-07-15 20:41
`rabbitmqctl` has a "quiet" mode where the header and trailing lines are not printed in the output https://www.rabbitmq.com/man/rabbitmqctl.1.man.html

> Quiet output mode is selected with the "-q" flag. Informational messages are suppressed when quiet mode is in effect.

```
$ sudo rabbitmqctl list_users -q
guest   [administrator]
````

vs

```
$ sudo rabbitmqctl list_users
Listing users ...
guest   [administrator]
```

This is with RabbitMQ 3.5.3 which you will note does not have a `...done` with or without the period.

**Comment by msummers42** [comment] 2015-07-16 01:17
Related, the same failure behavior occurs for vhosts when using rabbitmq_vhost.present.

**Comment by mlavin** [comment] 2015-07-16 20:20
Yes I can confirm this does not work on Salt 2015.5.3 with RabbitMQ 3.5.3. https://github.com/saltstack/salt/commit/a154280b34c58d3d3e5f02ffa7450a2495dc7cbd#diff-30812e41e68a99b6000203ffabdeada6R74 removes the last line which in this version of RabbitMQ contains meaningful output. The end result is that it cannot detect if a user/vhost has already been added/removed if it appears last in the list.

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo salt --version
salt 2015.5.3 (Lithium)
vagrant@vagrant-ubuntu-trusty-64:~$ sudo rabbitmqctl status
Status of node 'rabbit@vagrant-ubuntu-trusty-64' ...
[{pid,12403},
 {running_applications,[{rabbit,"RabbitMQ","3.5.3"},
                        {os_mon,"CPO  CXC 138 46","2.2.14"},
                        {xmerl,"XML parser","1.3.5"},
                        {mnesia,"MNESIA  CXC 138 12","4.11"},
                        {sasl,"SASL  CXC 138 11","2.3.4"},
                        {stdlib,"ERTS  CXC 138 10","1.19.4"},
                        {kernel,"ERTS  CXC 138 10","2.16.4"}]},
 {os,{unix,linux}},
 {erlang_version,"Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:30] [kernel-poll:true]\n"},
 {memory,[{total,34551072},
          {connection_readers,0},
          {connection_writers,0},
          {connection_channels,0},
          {connection_other,2632},
          {queue_procs,2632},
          {queue_slave_procs,0},
          {plugins,0},
          {other_proc,13324584},
          {mnesia,61440},
          {mgmt_db,0},
          {msg_index,45136},
          {other_ets,748624},
          {binary,13592},
          {code,16365700},
          {atom,561761},
          {other_system,3424971}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,0.25},
 {vm_memory_limit,260563968},
 {disk_free_limit,50000000},
 {disk_free,38869303296},
 {file_descriptors,[{total_limit,924},
                    {total_used,3},
                    {sockets_limit,829},
                    {sockets_used,1}]},
 {processes,[{limit,1048576},{used,123}]},
 {run_queue,0},
 {uptime,164}]
vagrant@vagrant-ubuntu-trusty-64:~$ sudo rabbitmqctl list_users
Listing users ...
example_local   []
guest   [administrator]
vagrant@vagrant-ubuntu-trusty-64:~$ sudo salt '*' rabbitmq.user_exists guest
vagrant-ubuntu-trusty-64:
    False
vagrant@vagrant-ubuntu-trusty-64:~$ sudo salt '*' rabbitmq.add_user guest
vagrant-ubuntu-trusty-64:
    ----------
    Error:
        Creating user "guest" ...
        Error: user_already_exists: guest
```

It would appear that this has been fixed in https://github.com/saltstack/salt/commit/a154280b34c58d3d3e5f02ffa7450a2495dc7cbd and https://github.com/saltstack/salt/commit/3c3d99fd569fd7961ba64a0bd350303b2a4a7305. The first appears to be backported to the 2015.5 branch but the second was not. This module and the related states remain unusable in the released versions of Lithium.

**Comment by ngrennan-inflection** [comment] 2015-07-19 23:18
I found that the second hash, 3c3d99f, doesn't backport. I did find replacing the whole file from v2015.8.0rc1 works just fine.

**Comment by jquast** [comment] 2015-08-13 17:07
@mlavin i proposed backporting 3c3d99fd569fd7961ba64a0bd350303b2a4a7305 to 2015.5 in https://github.com/saltstack/salt/pull/26292

**Comment by rallytime** [comment] 2015-10-23 16:25
This bug fix is present in the 2015.5 and 2015.8 branches (as well as develop) and is in our recent releases (2015.5.6 and 2015.8.1). Are you guys still seeing this after upgrading? Or is this issue resolved?

**Comment by multani** [comment] 2015-10-23 16:42
I upgraded to 2015.8.1 a few days a ago and removed my custom patch and it seems to be working OK now.

**Closed** 2016-01-06 23:26 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P3, Platform, State Module

**Comment by gibsonje** [comment] 2016-01-08 19:55
I'm seeing this in 2015.8.3 currently. I don't have a solution just yet.

**Comment by patrickpierson** [comment] 2016-01-12 14:57
same at @gibsonje salt-minion 2015.8.3

```
          ID: rabbitmq_user_user1
    Function: rabbitmq_user.present
        Name: user1
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/rabbitmq_user.py", line 111, in present
                  user = __salt__['rabbitmq.user_exists'](name, runas=runas)
                File "/usr/lib/python2.7/dist-packages/salt/modules/rabbitmq.py", line 150, in user_exists
                  user_list = list_users(runas=runas)
                File "/usr/lib/python2.7/dist-packages/salt/modules/rabbitmq.py", line 118, in list_users
                  return _output_to_dict(res, func)
                File "/usr/lib/python2.7/dist-packages/salt/modules/rabbitmq.py", line 96, in _output_to_dict
                  key, values = row.split('\t', 1)
              ValueError: need more than 1 value to unpack
     Started: 09:55:30.495392
    Duration: 206.249 ms
     Changes:   
```

**Comment by gibsonje** [comment] 2016-01-12 15:40
@patrickpierson I was able to solve this by using the rabbitmq module from a past version (sorry, I'm not positive which version it came from, coworker did it). The rabbitmq module in 2015.8.3 is not working for me.

**Comment by multani** [comment] 2016-01-12 16:19
For those who are still experiencing the issue (@gibsonje and @patrickpierson ?) running 2015.8.3, you should probably report the output of the following commands:
* ``python -c "import subprocess; print repr(subprocess.check_output(['rabbitmqctl', 'list_users']))"``
* ``rabbitmqctl status``

I'm currently running 2015.8.3 and RabbitMQ 3.5.6 and I don't have the problem.

**Comment by patrickpierson** [comment] 2016-01-12 17:30
@multani 

```root@salt-minion:~# python -c "import subprocess; print repr(subprocess.check_output(['rabbitmqctl', 'list_users']))"
'Listing users ...\nsensu\t[administrator]\nuser1\t[]\nguest\t[administrator]\n'

root@salt-minion:~# rabbitmqctl status
Status of node 'rabbit@salt-minion' ...
[{pid,32674},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.6.0"},
      {amqp_client,"RabbitMQ AMQP Client","3.6.0"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.0"},
      {rabbit,"RabbitMQ","3.6.0"},
      {rabbit_common,[],"3.6.0"},
      {os_mon,"CPO  CXC 138 46","2.4"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.0"},
      {webmachine,"webmachine","git"},
      {mochiweb,"MochiMedia Web Server","2.13.0"},
      {ssl,"Erlang/OTP SSL application","7.2"},
      {public_key,"Public key infrastructure","1.1"},
      {asn1,"The Erlang ASN1 compiler version 4.0.1","4.0.1"},
      {inets,"INETS  CXC 138 49","6.1"},
      {syntax_tools,"Syntax tools","1.7"},
      {crypto,"CRYPTO","3.6.2"},
      {mnesia,"MNESIA  CXC 138 12","4.13.2"},
      {compiler,"ERTS  CXC 138 10","6.0.2"},
      {xmerl,"XML parser","1.3.9"},
      {sasl,"SASL  CXC 138 11","2.6.1"},
      {stdlib,"ERTS  CXC 138 10","2.7"},
      {kernel,"ERTS  CXC 138 10","4.1.1"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 18 [erts-7.2] [source] [64-bit] [async-threads:64] [kernel-poll:true]\n"},
 {memory,
     [{total,61009440},
      {connection_readers,31744},
      {connection_writers,7992},
      {connection_channels,22512},
      {connection_other,93144},
      {queue_procs,38280},
      {queue_slave_procs,0},
      {plugins,105984},
      {other_proc,18427856},
      {mnesia,79376},
      {mgmt_db,324080},
      {msg_index,45312},
      {other_ets,1356152},
      {binary,7913024},
      {code,27312205},
      {atom,992409},
      {other_system,4259370}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,945066803},
 {disk_free_limit,50000000},
 {disk_free,27352551424},
 {file_descriptors,
     [{total_limit,924},{total_used,5},{sockets_limit,829},{sockets_used,3}]},
 {processes,[{limit,1048576},{used,227}]},
 {run_queue,0},
 {uptime,8706},
 {kernel,{net_ticktime,60}}]
```

**Comment by multani** [comment] 2016-01-15 10:08
@patrickpierson That weird, because we I try to parse the content of your ``subprocess.check_output()`` result with the function that is raising the exception as you posted before, it parses everything alright. I assume that running the ``rabbitmq.list_users`` Salt command on the related minion also gives you the same traceback?

**Comment by erikpar** [comment] 2016-01-28 14:31
i have the same issue
i am running rabbitmq 3.6.0-1 and salt salt 2015.8.3 (Beryllium)
running rabbitmq.list_users in the minion log i see its run ok but from the master i get 
Minion did not return. [No response]

**Comment by patrickpierson** [comment] 2016-03-03 19:18
@multani sorry for the long wait.

When I run rabbitmq.list_users on that host from the master I get the same as @erikpar no response but in the logs the command is ran and results are shown in the debug log output.
