### ISSUE TITLE
14.04 / salt '*' test.ping Failed to authenticate, is this user permitted to execute commands?

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#12248] opened 2014-04-24 00:19 UTC
Since my upgrade to 14.04 and sync of @makinacorpus fork to last develop, something is weird.

I get intermittent total unfunctionnality of the saltmaster , on a period of 1 at 2 minutes, i cant ping any minion, and the next 2 minutes ping is working, and 2 minutes after this does not work.
```
 mastersalt '*' test.ping
Failed to authenticate, is this user permitted to execute commands?

```

I rebuilded all the eggs locally installed to be sure of the linking, but this seems not to be sufficient.

Ill check tomorow to double check if this is one of our maintainance crons, but i would suspect yet another regression.

**Comment by kitplummer** [comment] 2015-01-05 21:24
I'm seeing this message:

[root@ip-172-31-6-75 master]# salt '*' test.ping
[ERROR   ] Salt request timed out. If this error persists, worker_threads may need to be increased.
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

This is with CentOS 7 for both the Master and salt-cloud provisioned instances in EC2.

**Comment by basepi** [comment] 2015-01-05 23:22
@kitplummer `salt --versions-report` please?

**Comment by cachedout** [comment] 2015-01-08 23:34
Are there any cases currently where people can reliably reproduce the error ```Failed to authenticate, is this user permitted to execute commands?```. I would *love* to have something I can look at, if anybody can point me in that direction.

**Comment by saltuser** [comment] 2015-01-13 08:31
Hi!

We hit this message yesterday. The reason seems to be that restarting salt master somehow left one process hanging.
After killing the hung/leftover process manually (and cruelly) the message disappeared.

salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0

It's not much, but i hope it helps (and keeps the conversation going) :)

**Comment by basepi** [comment] 2015-01-13 21:07
Interesting, thanks for the update @saltuser. I'm sure the extra process didn't suffer. ;)

**Comment by nacengineer** [comment] 2015-02-17 17:43
I can confirm this behavior happens when you change the number of CPUs on a Virtual Machine. 

Basically I bumped the Procs to 2 sockets / 4 cores/socket  when I bumped it back to the original 1/2 it worked again. 

LSB Release
~~~sh
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
~~~

Uname Info
~~~sh
3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
~~~

~~~sh
           Salt: 2014.1.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
~~~

running on VMware ESXi, 5.0.0, 623860

**Comment by s0undt3ch** [comment] 2015-03-09 13:31
Sorry for the slow response. As @rallytime pointed out, https://bootstrap.saltstack.com uses the stable branch of the repository. I try to merge the develop branch as often as possible with the new fixes. If you want to use the development version of the bootstrap script, please use https://bootstrap.saltstack.com/develop

**Comment by cachedout** [comment] 2015-06-12 22:03
This is a loooong issue. :]

At this point, I think we've more or less at the point where the issue as it was originally reported was traced back to lingering salt-master procs during an incomplete restart. Since it looks like that issue has been addressed via bootstrap and (hopefully) packaging changes, I am going to finally go ahead and close this.

If people have lingering issues that are reproduceable, please open them in separate issues and we will track them individually going forward instead of having this monolithic issue. Thanks.

**Closed by cachedout** 2015-06-12 22:03 UTC
Labels: Bug, Medium Severity

**Comment by Pratik-Patil** [comment] 2016-06-09 16:39
I have restarted the salt-master and it worked !!
restart salt-master;
