### ISSUE TITLE
Thousands of defunct Proxy Minion processes when multiprocessing = True

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#49221] opened 2018-08-21 08:46 UTC
### Description of Issue/Question

While SSH-based Proxy Minions have the constraint to configure `multiprocessing: false`, non-SSH based Proxies should normally replicate the behaviour of the regular Minion and execute each task in a separate process fork.

It appears that it doesn't actually clean up after itself:

```
mircea   23712  0.0  0.0  12732  2016 pts/21   S+   08:34   0:00              \_ grep salt-proxy
root     32704  0.0  0.0 122264 53540 ?        Ss   Aug18   0:00      |   \_ /usr/bin/python /usr/bin/salt-proxy --proxyid router1 -l warning
root     32824  0.3  0.0 656808 130420 ?       Sl   Aug18  13:28      |       \_ /usr/bin/python /usr/bin/salt-proxy --proxyid router1 -l warning
root     37881  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37882  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37884  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37885  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37887  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37890  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37894  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37895  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37899  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37900  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37923  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     37924  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     38876  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     38877  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     39939  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     39940  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     40779  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     40780  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     40958  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     40959  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     42042  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     42043  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     42829  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     42830  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     42964  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     42965  0.0  0.0      0     0 ?        Z    Aug18   0:00      |       \_ [salt-proxy] <defunct>
root     42967  0.0  0.0      0     0 ?        Zs   Aug18   0:00      |       \_ [salt-proxy] <defunct>
...
... ~~~ snip ~~~
...
```

(many more defunct processes)

Probably worth mentioning that this Proxy process runs inside a Docker container. I'm not sure where I should start tracing this from

**Comment by Ch3LL** [comment] 2018-08-21 13:36
ping @saltstack/team-network any thoughts here?

**Comment by gtmanfred** [comment] 2018-08-21 14:16
Yeah, that should never happen, we need to get that fixed, for 2018.3.4

@mirceaulinic can you replicate this with the rest_example proxy minion?

**Comment by mirceaulinic** [comment] 2018-08-22 12:36
Yes, I'm seeing the same with any proxy type setting `multiprocessing: true` (or leaving the default value).
Once I set `multiprocessing: false` there are no longer defunct processes. They seem to be defunct processes from the highstate.

**Comment by rallytime** [comment] 2018-08-31 15:17
@garethgreenaway Can you look at this one for 2018.3.4?

**Comment by garethgreenaway** [comment] 2018-09-06 17:49
@mirceaulinic To confirm, you're seeing this behavior with the rest_example proxy minion as well?  Are there any particular Salt functions that result in you seeing defunct processes?  So far I haven't been able to duplicate.

**Comment by mirceaulinic** [comment] 2018-09-12 08:47
Yes, @garethgreenaway I have noticed the same with the ``rest_example`` proxy minion as well. Please note that this occurred when running the Proxy Minion process as Docker container. It appears that the defunct processes are caused by scheduled `state.highstate` or `state.apply`.

**Comment by garethgreenaway** [comment] 2018-09-12 13:11
@mirceaulinic thanks!  This is more to go on. I'll see if I can reproduce it. :grinning:

**Comment by cro** [comment] 2018-09-12 19:33
@garethgreenaway Is this fixed in the head of 2018.3?  I'm wondering if this is the issue @terminalmage is working on where `os.exit()` doesn't seem to return the value we need.  You might ask him in case this is a further clue.

**Comment by garethgreenaway** [comment] 2018-09-12 19:36
@cro I wasn't able to duplicate it outside of Docker. That's the next step.

**Comment by garethgreenaway** [comment] 2018-09-28 19:55
So far I haven't been able to duplicate this particular issue inside a Docker container, it's possible it was fixed at the head of 2018.3 as @cro mentioned or could be related to this fix (https://github.com/saltstack/salt/pull/49019) that was added in August.  @mirceaulinic can you confirm what version of 2018.3 you're using?  If you're able to, can you run the salt-proxy in debug mode and report back any logged errors that stand out?  Thanks!

**Comment by Ch3LL** [comment] 2019-01-18 14:44
@mirceaulinic bump on this issue for the questions above

**Comment by Ch3LL** [comment] 2019-01-29 16:23
closing due to lack of response but please let us know if we need to re-open

**Closed by Ch3LL** 2019-01-29 16:23 UTC
Labels: 2018.3.4, Bug, Critical, P2
