### ISSUE TITLE
{{ grains['host'] }} is not giving hostname instead giving IP address in xx-xx-xx-xx format.

### ISSUE THREAD

**Issue by hemantaltair** [saltstack/salt#56277] opened 2020-03-01 06:30 UTC
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Nov  7 2019, 10:07:09)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-1025-azure
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by hemantaltair** [comment] 2020-03-01 06:30
Ideally it shoud give hostname but not giving

**Comment by garethgreenaway** [comment] 2020-03-02 22:01
@hemantaltair Thanks for the report.  I haven't been able to reproduce this.  On the minion in question  are you able to do simple things such as looking up the hostname using ping?

**Comment by hemantaltair** [comment] 2020-03-31 09:46
Hi, yes I was able to ping hostname

**Comment by garethgreenaway** [comment] 2020-10-22 21:14
@hemantaltair Apologies for the delay on this one.  The `host` grains is based on the fully qualified domain name for the minion, the information is based on the available IP addresses and what host names they resolve to.  If your grain entry is ending up as an IP address then it's most likely because the IP address that Salt is using doesn't resolve to a name.

**Comment by garethgreenaway** [comment] 2023-08-28 18:30
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.

**Closed by garethgreenaway** 2023-08-28 18:30 UTC
Labels: info-needed, Pending-Discussion
