### ISSUE TITLE
unit.utils.test_vmware.GetClusterTestCase.test_get_service_instance_from_managed_object

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52813] opened 2019-05-02 21:47 UTC
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.utils.test_vmware/GetClusterTestCase/test_get_service_instance_from_managed_object)
---

name 'vmodl' is not defined

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 112, in test_get_service_instance_from_managed_object
    salt.utils.vmware.get_cluster(self.mock_dc, 'fake_cluster')
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 1827, in get_cluster
    traversal_spec = vmodl.query.PropertyCollector.TraversalSpec(
NameError: name 'vmodl' is not defined
		
```

**Comment by waynew** [comment] 2019-05-02 21:49
Also these failures:

- unit.utils.test_vmware.GetClusterTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.GetClusterTestCase.test_cluster_found
- unit.utils.test_vmware.GetClusterTestCase.test_get_mors_with_properties_returns_empty_array
- unit.utils.test_vmware.GetPropertiesOfManagedObjectTestCase.test_managed_object_no_name_property
- unit.utils.test_vmware.GetClusterTestCase.test_cluster_not_found

**Comment by Ch3LL** [comment] 2019-05-03 13:24
duplicate of https://github.com/saltstack/salt/issues/51886

**Closed by Ch3LL** 2019-05-03 13:24 UTC
Labels: 2019.2.1, Test Failure
