### ISSUE TITLE
unable to use repo.saltstack.com

### ISSUE THREAD

**Issue by sceptiq** [saltstack/salt#52847] opened 2019-05-06 17:32 UTC
### Description of Issue/Question

trying to install https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ on ubuntu 14.04 minion with salt-ssh 2019.2.0 (Fluorine)

### Setup

this:
```
salt-repo:
  pkgrepo.managed:
    - humanname: saltstack
    - name: deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main
    - key_url: https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub
    - file: /etc/apt/sources.list.d/saltstack.list
```

results in:
```
           ID: salt-repo                                                                                                                                                      [0/1885]
    Function: pkgrepo.managed
        Name: deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main
      Result: False
     Comment: Failed to configure repo 'deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main': [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER
_HELLO:sslv3 alert handshake failure
     Started: 19:30:04.245210
    Duration: 175.437 ms
     Changes:
```

a `openssl s_client -connect repo.saltstack.com:443` on the 14.04 minion results in:

```
CONNECTED(00000003)
140555418023584:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:770:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 295 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
``` 

### Versions Report
salt-ssh 2019.2.0 (Fluorine)

**Comment by bryceml** [comment] 2019-05-07 05:38
This is caused by cloudfront requiring sni.  Apt can handle it fine.  The openssl command needs the server name added, possibly in the salt code as well.

```bash
openssl s_client -connect repo.saltstack.crepo.saltstack.com:443 -servername repo.saltstack.com
```

**Comment by sceptiq** [comment] 2019-05-07 08:46
what is it I am missing? 

my apt seems not to be able to handle it?

**Comment by bryceml** [comment] 2019-05-07 14:54
Do you have apt-transport-https installed?

```bash
root@ubuntu:/home/bryceml# curl https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub|apt-key --keyring /etc/apt/trusted.gpg.d/saltstack.gpg add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1727  100  1727    0     0   8846      0 --:--:-- --:--:-- --:--:--  8811
OK
root@ubuntu:/home/bryceml# echo "deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main" > /etc/apt/sources.list.d/saltstack.list
root@ubuntu:/home/bryceml# sudo apt update
Hit http://security.ubuntu.com trusty-security InRelease
Ign http://archive.ubuntu.com trusty InRelease
Hit http://archive.ubuntu.com trusty-updates InRelease
Get:1 https://repo.saltstack.com trusty InRelease                      
Hit http://security.ubuntu.com trusty-security/main Sources                    
Hit http://archive.ubuntu.com trusty-backports InRelease        
Get:2 https://repo.saltstack.com trusty/main amd64 Packages              
Hit http://security.ubuntu.com trusty-security/restricted Sources              
Get:3 https://repo.saltstack.com trusty/main i386 Packages        
Hit http://archive.ubuntu.com trusty Release.gpg                      
Hit http://security.ubuntu.com trusty-security/universe Sources
Get:4 https://repo.saltstack.com trusty/main Translation-en_US   
Hit http://archive.ubuntu.com trusty-updates/main Sources                 
Hit http://security.ubuntu.com trusty-security/multiverse Sources         
Hit http://archive.ubuntu.com trusty-updates/restricted Sources   
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe Sources       
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/multiverse Sources   
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages    
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Ign https://repo.saltstack.com trusty/main Translation-en_US        
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Ign https://repo.saltstack.com trusty/main Translation-en           
Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit http://archive.ubuntu.com trusty-updates/main i386 Packages     
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en  
Hit http://archive.ubuntu.com trusty-updates/universe i386 Packages      
Hit http://archive.ubuntu.com trusty-updates/multiverse i386 Packages    
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://archive.ubuntu.com trusty-updates/main Translation-en         
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://archive.ubuntu.com trusty-backports/main Sources
Hit http://archive.ubuntu.com trusty-backports/restricted Sources
Hit http://archive.ubuntu.com trusty-backports/universe Sources
Hit http://archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages         
Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages       
Hit http://archive.ubuntu.com trusty-backports/main i386 Packages              
Hit http://archive.ubuntu.com trusty-backports/restricted i386 Packages        
Hit http://archive.ubuntu.com trusty-backports/universe i386 Packages          
Hit http://archive.ubuntu.com trusty-backports/multiverse i386 Packages        
Hit http://archive.ubuntu.com trusty-backports/main Translation-en             
Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en       
Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en       
Hit http://archive.ubuntu.com trusty-backports/universe Translation-en         
Hit http://archive.ubuntu.com trusty Release                                   
Hit http://archive.ubuntu.com trusty/main Sources                              
Hit http://archive.ubuntu.com trusty/restricted Sources                        
Hit http://archive.ubuntu.com trusty/universe Sources                          
Hit http://archive.ubuntu.com trusty/multiverse Sources                        
Hit http://archive.ubuntu.com trusty/main amd64 Packages                       
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages                 
Hit http://archive.ubuntu.com trusty/universe amd64 Packages                   
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages                 
Hit http://archive.ubuntu.com trusty/main i386 Packages                        
Hit http://archive.ubuntu.com trusty/restricted i386 Packages                  
Hit http://archive.ubuntu.com trusty/universe i386 Packages                    
Hit http://archive.ubuntu.com trusty/multiverse i386 Packages                  
Hit http://archive.ubuntu.com trusty/main Translation-en                       
Hit http://archive.ubuntu.com trusty/multiverse Translation-en                 
Hit http://archive.ubuntu.com trusty/restricted Translation-en                 
Hit http://archive.ubuntu.com trusty/universe Translation-en                   
Ign http://archive.ubuntu.com trusty/main Translation-en_US                    
Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US              
Ign http://archive.ubuntu.com trusty/restricted Translation-en_US              
Ign http://archive.ubuntu.com trusty/universe Translation-en_US                
Fetched 17.3 kB in 21s (808 B/s)                                               
Reading package lists... Done
root@ubuntu:/home/bryceml# apt install salt-minion
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  dctrl-tools debconf-utils libgmp10 libjs-jquery libjs-sphinxdoc
  libjs-underscore libmysqlclient18 libpgm-5.1-0 libsodium13 libyaml-0-2
  libzmq3 mysql-common python-concurrent.futures python-crypto python-dateutil
  python-jinja2 python-mako python-markupsafe python-msgpack python-mysqldb
  python-pkg-resources python-psutil python-pycurl python-tornado python-yaml
  python-zmq salt-common
Suggested packages:
  debtags javascript-common python-crypto-dbg python-crypto-doc
  python-jinja2-doc python-beaker python-mako-doc python-egenix-mxdatetime
  mysql-server-5.1 mysql-server python-mysqldb-dbg python-distribute
  python-distribute-doc libcurl4-gnutls-dev python-pycurl-dbg python-augeas
The following NEW packages will be installed:
  dctrl-tools debconf-utils libgmp10 libjs-jquery libjs-sphinxdoc
  libjs-underscore libmysqlclient18 libpgm-5.1-0 libsodium13 libyaml-0-2
  libzmq3 mysql-common python-concurrent.futures python-crypto python-dateutil
  python-jinja2 python-mako python-markupsafe python-msgpack python-mysqldb
  python-pkg-resources python-psutil python-pycurl python-tornado python-yaml
  python-zmq salt-common salt-minion
0 upgraded, 28 newly installed, 0 to remove and 0 not upgraded.
Need to get 9,352 kB of archives.
After this operation, 42.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libgmp10 amd64 2:5.1.3+dfsg-1ubuntu1 [218 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main mysql-common all 5.5.62-0ubuntu0.14.04.1 [12.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libmysqlclient18 amd64 5.5.62-0ubuntu0.14.04.1 [598 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/universe libpgm-5.1-0 amd64 5.1.118-1~dfsg-0.1ubuntu3 [156 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libyaml-0-2 amd64 0.1.4-3ubuntu3.1 [48.1 kB]
Get:6 https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main python-msgpack amd64 0.4.6-1build1 [55.0 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty/main dctrl-tools amd64 2.23ubuntu1 [101 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty/main debconf-utils all 1.5.51ubuntu2 [57.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu/ trusty/main libjs-jquery all 1.7.2+dfsg-2ubuntu1 [78.8 kB]
Get:10 http://archive.ubuntu.com/ubuntu/ trusty/main libjs-underscore all 1.4.4-2ubuntu1 [45.6 kB]
Get:11 https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main python-tornado amd64 4.2.1-1~ds+1 [274 kB]
Get:12 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libjs-sphinxdoc all 1.2.2+dfsg-1ubuntu1.1 [41.4 kB]
Get:13 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-crypto amd64 2.6.1-4ubuntu0.3 [239 kB]
Get:14 http://archive.ubuntu.com/ubuntu/ trusty/main python-dateutil all 1.5+dfsg-1ubuntu1 [48.9 kB]
Get:15 http://archive.ubuntu.com/ubuntu/ trusty/main python-markupsafe amd64 0.18-1build2 [14.3 kB]
Get:16 http://archive.ubuntu.com/ubuntu/ trusty/main python-jinja2 all 2.7.2-2 [161 kB]
Get:17 http://archive.ubuntu.com/ubuntu/ trusty/main python-mako all 0.9.1-1 [59.6 kB]
Get:18 http://archive.ubuntu.com/ubuntu/ trusty/main python-mysqldb amd64 1.2.3-2ubuntu1 [55.4 kB]
Get:19 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-pkg-resources all 3.3-1ubuntu2 [61.9 kB]
Get:20 http://archive.ubuntu.com/ubuntu/ trusty/main python-psutil amd64 1.2.1-1ubuntu2 [50.2 kB]
Get:21 http://archive.ubuntu.com/ubuntu/ trusty/main python-pycurl amd64 7.19.3-0ubuntu3 [47.9 kB]
Get:22 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-yaml amd64 3.10-4ubuntu0.1 [102 kB]
Get:23 http://archive.ubuntu.com/ubuntu/ trusty/universe python-zmq amd64 14.0.1-1build2 [175 kB]
Fetched 9,352 kB in 3s (3,037 kB/s)
Selecting previously unselected package libgmp10:amd64.
(Reading database ... 55029 files and directories currently installed.)
Preparing to unpack .../libgmp10_2%3a5.1.3+dfsg-1ubuntu1_amd64.deb ...
Unpacking libgmp10:amd64 (2:5.1.3+dfsg-1ubuntu1) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../mysql-common_5.5.62-0ubuntu0.14.04.1_all.deb ...
Unpacking mysql-common (5.5.62-0ubuntu0.14.04.1) ...
Selecting previously unselected package libmysqlclient18:amd64.
Preparing to unpack .../libmysqlclient18_5.5.62-0ubuntu0.14.04.1_amd64.deb ...
Unpacking libmysqlclient18:amd64 (5.5.62-0ubuntu0.14.04.1) ...
Selecting previously unselected package libpgm-5.1-0:amd64.
Preparing to unpack .../libpgm-5.1-0_5.1.118-1~dfsg-0.1ubuntu3_amd64.deb ...
Unpacking libpgm-5.1-0:amd64 (5.1.118-1~dfsg-0.1ubuntu3) ...
Selecting previously unselected package libsodium13:amd64.
Preparing to unpack .../libsodium13_1.0.3-1_amd64.deb ...
Unpacking libsodium13:amd64 (1.0.3-1) ...
Selecting previously unselected package libyaml-0-2:amd64.
Preparing to unpack .../libyaml-0-2_0.1.4-3ubuntu3.1_amd64.deb ...
Unpacking libyaml-0-2:amd64 (0.1.4-3ubuntu3.1) ...
Selecting previously unselected package libzmq3:amd64.
Preparing to unpack .../libzmq3_4.0.5+dfsg-3_amd64.deb ...
Unpacking libzmq3:amd64 (4.0.5+dfsg-3) ...
Selecting previously unselected package dctrl-tools.
Preparing to unpack .../dctrl-tools_2.23ubuntu1_amd64.deb ...
Unpacking dctrl-tools (2.23ubuntu1) ...
Selecting previously unselected package debconf-utils.
Preparing to unpack .../debconf-utils_1.5.51ubuntu2_all.deb ...
Unpacking debconf-utils (1.5.51ubuntu2) ...
Selecting previously unselected package libjs-jquery.
Preparing to unpack .../libjs-jquery_1.7.2+dfsg-2ubuntu1_all.deb ...
Unpacking libjs-jquery (1.7.2+dfsg-2ubuntu1) ...
Selecting previously unselected package libjs-underscore.
Preparing to unpack .../libjs-underscore_1.4.4-2ubuntu1_all.deb ...
Unpacking libjs-underscore (1.4.4-2ubuntu1) ...
Selecting previously unselected package libjs-sphinxdoc.
Preparing to unpack .../libjs-sphinxdoc_1.2.2+dfsg-1ubuntu1.1_all.deb ...
Unpacking libjs-sphinxdoc (1.2.2+dfsg-1ubuntu1.1) ...
Selecting previously unselected package python-concurrent.futures.
Preparing to unpack .../python-concurrent.futures_3.0.3-1_all.deb ...
Unpacking python-concurrent.futures (3.0.3-1) ...
Selecting previously unselected package python-crypto.
Preparing to unpack .../python-crypto_2.6.1-4ubuntu0.3_amd64.deb ...
Unpacking python-crypto (2.6.1-4ubuntu0.3) ...
Selecting previously unselected package python-dateutil.
Preparing to unpack .../python-dateutil_1.5+dfsg-1ubuntu1_all.deb ...
Unpacking python-dateutil (1.5+dfsg-1ubuntu1) ...
Selecting previously unselected package python-markupsafe.
Preparing to unpack .../python-markupsafe_0.18-1build2_amd64.deb ...
Unpacking python-markupsafe (0.18-1build2) ...
Selecting previously unselected package python-jinja2.
Preparing to unpack .../python-jinja2_2.7.2-2_all.deb ...
Unpacking python-jinja2 (2.7.2-2) ...
Selecting previously unselected package python-mako.
Preparing to unpack .../python-mako_0.9.1-1_all.deb ...
Unpacking python-mako (0.9.1-1) ...
Selecting previously unselected package python-msgpack.
Preparing to unpack .../python-msgpack_0.4.6-1build1_amd64.deb ...
Unpacking python-msgpack (0.4.6-1build1) ...
Selecting previously unselected package python-mysqldb.
Preparing to unpack .../python-mysqldb_1.2.3-2ubuntu1_amd64.deb ...
Unpacking python-mysqldb (1.2.3-2ubuntu1) ...
Selecting previously unselected package python-pkg-resources.
Preparing to unpack .../python-pkg-resources_3.3-1ubuntu2_all.deb ...
Unpacking python-pkg-resources (3.3-1ubuntu2) ...
Selecting previously unselected package python-psutil.
Preparing to unpack .../python-psutil_1.2.1-1ubuntu2_amd64.deb ...
Unpacking python-psutil (1.2.1-1ubuntu2) ...
Selecting previously unselected package python-pycurl.
Preparing to unpack .../python-pycurl_7.19.3-0ubuntu3_amd64.deb ...
Unpacking python-pycurl (7.19.3-0ubuntu3) ...
Selecting previously unselected package python-tornado.
Preparing to unpack .../python-tornado_4.2.1-1~ds+1_amd64.deb ...
Unpacking python-tornado (4.2.1-1~ds+1) ...
Selecting previously unselected package python-yaml.
Preparing to unpack .../python-yaml_3.10-4ubuntu0.1_amd64.deb ...
Unpacking python-yaml (3.10-4ubuntu0.1) ...
Selecting previously unselected package python-zmq.
Preparing to unpack .../python-zmq_14.0.1-1build2_amd64.deb ...
Unpacking python-zmq (14.0.1-1build2) ...
Selecting previously unselected package salt-common.
Preparing to unpack .../salt-common_2019.2.0+ds-1_all.deb ...
Unpacking salt-common (2019.2.0+ds-1) ...
Selecting previously unselected package salt-minion.
Preparing to unpack .../salt-minion_2019.2.0+ds-1_all.deb ...
Unpacking salt-minion (2019.2.0+ds-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
Setting up libgmp10:amd64 (2:5.1.3+dfsg-1ubuntu1) ...
Setting up mysql-common (5.5.62-0ubuntu0.14.04.1) ...
Setting up libmysqlclient18:amd64 (5.5.62-0ubuntu0.14.04.1) ...
Setting up libpgm-5.1-0:amd64 (5.1.118-1~dfsg-0.1ubuntu3) ...
Setting up libsodium13:amd64 (1.0.3-1) ...
Setting up libyaml-0-2:amd64 (0.1.4-3ubuntu3.1) ...
Setting up libzmq3:amd64 (4.0.5+dfsg-3) ...
Setting up dctrl-tools (2.23ubuntu1) ...
Setting up debconf-utils (1.5.51ubuntu2) ...
Setting up libjs-jquery (1.7.2+dfsg-2ubuntu1) ...
Setting up libjs-underscore (1.4.4-2ubuntu1) ...
Setting up libjs-sphinxdoc (1.2.2+dfsg-1ubuntu1.1) ...
Setting up python-concurrent.futures (3.0.3-1) ...
Setting up python-crypto (2.6.1-4ubuntu0.3) ...
Setting up python-dateutil (1.5+dfsg-1ubuntu1) ...
Setting up python-markupsafe (0.18-1build2) ...
Setting up python-jinja2 (2.7.2-2) ...
Setting up python-mako (0.9.1-1) ...
Setting up python-msgpack (0.4.6-1build1) ...
Setting up python-mysqldb (1.2.3-2ubuntu1) ...
Setting up python-pkg-resources (3.3-1ubuntu2) ...
Setting up python-psutil (1.2.1-1ubuntu2) ...
Setting up python-pycurl (7.19.3-0ubuntu3) ...
Setting up python-tornado (4.2.1-1~ds+1) ...
Setting up python-yaml (3.10-4ubuntu0.1) ...
Setting up python-zmq (14.0.1-1build2) ...
Setting up salt-common (2019.2.0+ds-1) ...
Setting up salt-minion (2019.2.0+ds-1) ...
salt-minion start/running, process 2311
Processing triggers for libc-bin (2.19-0ubuntu6.15) ...
Processing triggers for ureadahead (0.100.0-16) ...
root@ubuntu:/home/bryceml# apt-cache policy apt-transport-https
apt-transport-https:
  Installed: 1.0.1ubuntu2.23
  Candidate: 1.0.1ubuntu2.23
  Version table:
 *** 1.0.1ubuntu2.23 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1ubuntu2.19 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     1.0.1ubuntu2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

```

It does seem like there is a bug in salt itself:
```bash
root@ubuntu:/srv/salt# salt-call --local --file-root=/srv/salt state.apply test -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ubuntu
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] key: test, ret: _|-
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Returning file list from cache: age=19 cache_time=20 /var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'test.sls' to resolve 'salt://test.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/test.sls' to resolve 'salt://test.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/test.sls
[DEBUG   ] Jinja search path: [u'/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'jinja' renderer: 0.0111751556396
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/test.sls:
salt-repo:
  pkgrepo.managed:
    - humanname: saltstack
    - name: deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main
    - key_url: https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub
    - file: /etc/apt/sources.list.d/saltstack.list

[DEBUG   ] Results of YAML rendering: 
OrderedDict([(u'salt-repo', OrderedDict([(u'pkgrepo.managed', [OrderedDict([(u'humanname', u'saltstack')]), OrderedDict([(u'name', u'deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main')]), OrderedDict([(u'key_url', u'https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub')]), OrderedDict([(u'file', u'/etc/apt/sources.list.d/saltstack.list')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'yaml' renderer: 0.000674962997437
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded pkg.mod_repo
[DEBUG   ] LazyLoaded pkgrepo.managed
[INFO    ] Running state [deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main] at time 08:53:14.166940
[INFO    ] Executing state pkgrepo.managed for [deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main]
[DEBUG   ] LazyLoaded cp.cache_file
[DEBUG   ] Requesting URL https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub using GET method
[DEBUG   ] Using backend: tornado
[WARNING ] SSL Error on 8 ('143.204.158.64', 443): [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[ERROR   ] Failed to configure repo 'deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main': [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[INFO    ] Completed state [deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main] at time 08:53:14.351556 (duration_in_ms=184.613)
[DEBUG   ] File /var/cache/salt/minion/accumulator/140278293436880 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: salt-repo
    Function: pkgrepo.managed
        Name: deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main
      Result: False
     Comment: Failed to configure repo 'deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main': [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
     Started: 08:53:14.166943
    Duration: 184.613 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 184.613 ms
root@ubuntu:/srv/salt# cat test.sls 
salt-repo:
  pkgrepo.managed:
    - humanname: saltstack
    - name: deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main
    - key_url: https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub
    - file: /etc/apt/sources.list.d/saltstack.list
```

**Comment by bryceml** [comment] 2019-05-07 15:32
Discussion of this issue is here: https://github.com/saltstack/salt/issues/33782

**Comment by bryceml** [comment] 2019-05-07 15:57
https://github.com/saltstack/salt/issues/16409#issuecomment-245741588 you will probably need python 2.7.9 or newer.

Closing issue as ubuntu 14.04 is EOL and no longer supported.

**Closed by bryceml** 2019-05-07 15:57 UTC
