### ISSUE TITLE
unit.utils.test_vmware.GetClusterTestCase.test_traversal_spec_init test failure

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52812] opened 2019-05-02 21:45 UTC
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.utils.test_vmware/GetClusterTestCase/test_traversal_spec_init)
---

No module named 'salt.utils.vmware.vmodl'; 'salt.utils.vmware' is not a package

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 124, in test_traversal_spec_init
    with patch(patch_traversal_spec_str, mock_traversal_spec_ini):
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1377, in __enter__
    self.target = self.getter()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1547, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1234, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1223, in _dot_lookup
    __import__(import_path)
ModuleNotFoundError: No module named 'salt.utils.vmware.vmodl'; 'salt.utils.vmware' is not a package
		
```

**Comment by waynew** [comment] 2019-05-02 21:55
This one also has a tremendous # of failures:

- unit.utils.test_vmware.GetContentTestCase.test_external_traversal_spec
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_filtered_pgs
- unit.utils.test_vmware.GetContentTestCase.test_create_container_view_raise_vim_fault
- unit.utils.test_vmware.GetContentTestCase.test_retrieve_contents_raise_no_permission
- unit.utils.test_vmware.GetServiceInstanceFromManagedObjectTestCase.test_name_parameter_passed_in
- unit.utils.test_vmware.GetContentTestCase.test_empty_container_ref
- unit.utils.test_vmware.GetDvssTestCase.test_get_no_dvss
- unit.utils.test_vmware.AddLicenseTestCase.test_label_settings
- unit.utils.test_vmware.GetDvssTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.GetContentTestCase.test_property_obj_filter_specs_and_contents
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_mount_info_call
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_get_new_stub
- unit.utils.test_vmware.AddLicenseTestCase.test_add_license_raises_runtime_fault
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_datastores_filtered_by_both_name_and_backing_disk
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.GetDatastoresTestCase.test_root_folder_traversal_spec
- unit.utils.test_vmware.GetContentTestCase.test_defined_container_ref
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_traversal_spec
- unit.utils.test_vmware.AddLicenseTestCase.test_add_license_raises_vim_fault
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_get_new_stub_2_7_8_python
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_session_cookie_in_context
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_storage_system_call
- unit.utils.test_vmware.GetContentTestCase.test_destroy_raise_runtime_fault
- unit.utils.test_vmware.GetContentTestCase.test_create_container_view_raise_runtime_fault
- unit.utils.test_vmware.GetDvssTestCase.test_get_all_dvss
- unit.utils.test_vmware.GetStorageSystemTestCase.test_valid_mors_result
- unit.utils.test_vmware.GetDatastoresTestCase.test_datacenter_traversal_spec
- unit.utils.test_vmware.GetContentTestCase.test_destroy_raise_no_permission
- unit.utils.test_vmware.GetServiceInstanceFromManagedObjectTestCase.test_default_name_parameter
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.AddLicenseTestCase.test_license_manager_passed_in
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_unsupported_parrent
- unit.utils.test_vmware.GetDatastoresTestCase.test_backing_disks_no_mount_info
- unit.utils.test_vmware.GetDvssTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_traversal_spec_dvs_parent
- unit.utils.test_vmware.AddLicenseTestCase.test_no_license_manager_passed_in
- unit.utils.test_vmware.GetContentTestCase.test_local_properties_set
- unit.utils.test_vmware.AddLicenseTestCase.test_add_license_arguments
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_get_all_pgs
- unit.utils.test_vmware.GetStorageSystemTestCase.test_empty_mors_result
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_reference_name_call
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_get_uplink_pg
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_ssl_default_context_loaded
- unit.utils.test_vmware.GetStorageSystemTestCase.test_hostname_argument
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_no_datastores
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_get_no_uplink_pg
- unit.utils.test_vmware.AddLicenseTestCase.test_valid_license_added
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_get_no_pgs
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_new_stub_returned
- unit.utils.test_vmware.CreateDvsTestCase.test_no_dvs_create_spec
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_traversal_spec
- unit.utils.test_vmware.GetContentTestCase.test_local_traversal_spec
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_get_no_network_folder
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_datastores_filtered_by_name
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_traversal_spec_datacenter_parent
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_datastores_filtered_by_backing_disk
- unit.utils.test_vmware.GetDvssTestCase.test_filtered_all_dvss
- unit.utils.test_vmware.GetServiceInstanceFromManagedObjectTestCase.test_si_return_and_stub_assignment
- unit.utils.test_vmware.GetContentTestCase.test_retrieve_contents_raise_runtime_fault
- unit.utils.test_vmware.GetDatastoresTestCase.test_host_traversal_spec
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_all_datastores
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetDatastoresTestCase.test_unsupported_reference_type
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetStorageSystemTestCase.test_no_hostname_argument
- unit.utils.test_vmware.GetDvssTestCase.test_traversal_spec
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_get_network_folder
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetDatastoresTestCase.test_cluster_traversal_spec
- unit.utils.test_vmware.AddLicenseTestCase.test_add_license_raises_no_permission
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetContentTestCase.test_retrieve_contents_raise_vim_fault
- unit.utils.test_vmware.GetClusterTestCase.test_get_mors_with_properties_call
- unit.utils.test_vmware.GetContentTestCase.test_create_container_view_raise_no_permission
- unit.utils.test_vmware.GetContentTestCase.test_destroy_raise_vim_fault
- unit.utils.test_vmware.GetStorageSystemTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetServiceInstanceFromManagedObjectTestCase.test_service_instance_instantiation
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_ssl_default_context_not_loaded
- unit.utils.test_vmware.GetStorageSystemTestCase.test_traversal_spec

**Comment by Ch3LL** [comment] 2019-05-03 13:23
duplicate of https://github.com/saltstack/salt/issues/51886

**Closed by Ch3LL** 2019-05-03 13:23 UTC
Labels: 2019.2.1, Test Failure
