### ISSUE TITLE
Minions respond after repeated commands and not initially (even when specifying large timeout)

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#16518] opened 2014-10-09 18:01 UTC
I've been using salt for a very long time now. One problem i noticed is that sometimes minions don't respond initially and start responding after repeated ``test.ping``. If after a day or some duration i login to my master and issue a high state, it does not get applied to certain servers in the first attempt. I have tried setting a timeout as well and tried with it but the issue persists. See the following repeated commands:
```
[root@nitin-saltmaster ~]# salt '*' test.ping
nitin-saltmaster:
    True
nitin-salt-primecoin:
    True
nitin-salt-sumologic:
    Minion did not return. [No response]
nitin-jenkins-test:
    Minion did not return. [No response]
nitin-saltminion1:
    Minion did not return. [No response]
nitin-saltminion2:
    Minion did not return. [No response]
[root@nitin-saltmaster ~]# salt '*' test.ping
nitin-salt-primecoin:
    True
nitin-saltmaster:
    True
nitin-salt-sumologic:
    Minion did not return. [No response]
nitin-jenkins-test:
    Minion did not return. [No response]
nitin-saltminion1:
    Minion did not return. [No response]
nitin-saltminion2:
    Minion did not return. [No response]
[root@nitin-saltmaster ~]# salt '*' test.ping
nitin-salt-primecoin:
    True
nitin-salt-sumologic:
    True
nitin-saltmaster:
    True
nitin-saltminion1:
    True
nitin-jenkins-test:
    Minion did not return. [No response]
nitin-saltminion2:
    Minion did not return. [No response]
[root@nitin-saltmaster ~]# salt '*' test.ping
nitin-salt-primecoin:
    True
nitin-salt-sumologic:
    True
nitin-saltminion2:
    True
nitin-saltminion1:
    True
nitin-saltmaster:
    True
nitin-jenkins-test:
    Minion did not return. [No response]
[root@nitin-saltmaster ~]# salt '*' test.ping
nitin-salt-primecoin:
    True
nitin-salt-sumologic:
    True
nitin-saltminion2:
    True
nitin-jenkins-test:
    True
nitin-saltminion1:
    True
nitin-saltmaster:
    True
[root@nitin-saltmaster ~]#
```

Here's salt-versions:
```
[root@nitin-saltmaster ~]# salt '*' test.versions_report
nitin-salt-primecoin:
               Salt: 2014.1.10
             Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
             PyYAML: 3.10
              PyZMQ: 2.2.0.1
                ZMQ: 3.2.4
nitin-saltminion2:
               Salt: 2014.1.10
             Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
             PyYAML: 3.10
              PyZMQ: 2.2.0.1
                ZMQ: 3.2.4
nitin-salt-sumologic:
               Salt: 2014.1.10
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.10
              PyZMQ: 13.0.2
                ZMQ: 3.2.4
nitin-jenkins-test:
               Salt: 2014.7.0rc1
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 13.0.2
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed
nitin-saltminion1:
               Salt: 2014.7.0rc1
             Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed
nitin-saltmaster:
               Salt: 2014.7.0rc3-2159-g07f9246
             Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed
[root@nitin-saltmaster ~]#
```

I'm sure there may be other related issues and this has been brought to the teams attention, but why does the issue exist at all? Can it be fixed?

**Comment by obestwalter** [comment] 2015-08-12 10:52
@drawsmcgraw is this is still a problem in 2015.5.3? I would say that this situation has much improved with this release.

**Comment by drawsmcgraw** [comment] 2015-08-12 11:15
@obestwalter thanks for the follow up. I'm currently running 2015.5.0 with `ping_on_rotate: True` in the master config and things have been running great for a long while (coming up on 6 months).

If you're looking for a data point, I can try upgrading to 2015.5.3 (assuming it's in EPEL?) and removing that option to see how things perform?

**Comment by obestwalter** [comment] 2015-08-12 12:25
@drawsmcgraw no worries. I am just asking, because I had similar problems with Minion connections and 2015.5.3 made a big step forward for me there.

**Comment by basepi** [comment] 2015-08-18 16:53
Based on this discussion, I think I'm going to close this for the moment. Please keep us posted if there are problems here with future upgrades.

**Closed by basepi** 2015-08-18 16:53 UTC
Labels: Bug, Core, High Severity, P3

**Comment by kracekumar** [comment] 2015-09-09 16:20
I am facing similar issue.

```
ubuntu@ip-172-31-25-111:/opt/switch/provisioner$ sudo salt 'worker-stage-*' state.highstate -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /home/ubuntu/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /home/ubuntu/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-09-09T16:16:57.004662'}
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] get_iter_returns for jid 20150909161657011758 sent to set(['worker-stage-1']) will timeout at 16:17:02.014466
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-09-09T16:17:02.022585'}
[DEBUG   ] Checking whether jid 20150909161657011758 is still running
[DEBUG   ] LazyLoaded no_return.output
worker-stage-1:
    Minion did not return. [No response]
ubuntu@ip-172-31-25-111:/opt/switch/provisioner$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

I faced this problem 4-5 times rerunning the command. I was on Google Hangout and my bandwidth usage was high, does that have any connection ?

**Comment by basepi** [comment] 2015-09-15 22:52
That certainly seems like it could be a source of problems. Please keep us posted if you can reproduce this on a more standard setup.

**Comment by judeaugustinej** [comment] 2016-02-04 12:54
![ubuntu_install](https://cloud.githubusercontent.com/assets/3624858/12815464/7fc85840-cb6c-11e5-9e79-439e1258bba5.png)
