### ISSUE TITLE
Yum pkg.installed false error

### ISSUE THREAD

**Issue by moali87** [saltstack/salt#43076] opened 2017-08-21 03:20 UTC
### Setup
salt with kitchen-salt running 2017.7.1
### Steps to Reproduce Issue
Run a state like the following:
```yaml
download_java8:
  cmd.run:
    - name: 'wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm'
    - cwd: /tmp
    - unless: java -version

install_java8:
  pkg.installed:
    - name: /tmp/jdk-8u131-linux-x64.rpm
    - unless: java -version
```
### Versions Report
```yaml
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

### Log from minion
```shell
2017-08-21 03:14:08,716 [salt.state       ][ERROR   ][3696] Made the following changes:
'jdk1.8.0_131' changed from 'absent' to '2000:1.8.0_131-fcs'
```

### Log from salt run
```yaml
       ----------
                 ID: install_java8
           Function: pkg.installed
               Name: /tmp/jdk-8u131-linux-x64.rpm
             Result: False
            Comment: The following packages failed to install/update: /tmp/jdk-8u131-linux-x64.rpm
            Started: 03:13:45.461228
           Duration: 23416.124 ms
            Changes:
              ----------
              jdk1.8.0_131:
                  ----------
                  new:
                      2000:1.8.0_131-fcs
                  old:

       Summary for local
       -------------
       Succeeded: 10 (changed=11)
       Failed:     1
       -------------
       Total states run:     11
       Total run time:  144.193 s

```

**Comment by garethgreenaway** [comment] 2017-08-21 18:57
@AkhterAli Thanks for the report.  We'll get someone to take a look at this.

**Comment by Giandom** [comment] 2018-08-02 19:41
Hi have the same issue. Has anyone solved that problem?

Thanks,
Giandomenico

**Comment by isaachui** [comment] 2018-10-30 22:29
Hello,

I'm also having the same issue. Would love an update on this.

**Comment by 36below** [comment] 2019-07-08 03:48
Not sure if I have the same issue:

### Steps to reproduce
Create a state file and apply to a minion

### State file to test
`getpagespeed:
  pkg.installed:
    - sources:
      - getpagespeed: https://extras.getpagespeed.com/release-el7-latest.rpm`

### Debug output
`2019-07-08 15:35:08,095 [salt.minion      :1783][DEBUG   ][8861] minion return: {u'fun_args': [u'test'], u'jid': u'20190708153456821848', u'return': {u'pkg_|-getpagespeed_|-getpagespeed_|-installed': {u'comment': u'The following packages failed to install/update: getpagespeed', u'name': u'getpagespeed', u'start_time': '15:35:00.130482', u'result': False, u'duration': 7890.674, u'__run_num__': 0, u'__sls__': u'test', u'changes': {u'epel-release': {u'new': u'7-11', u'old': u''}, u'getpagespeed-extras-release': {u'new': u'7-3.el7.gps', u'old': u''}}, u'__id__': u'getpagespeed'}}, u'retcode': 2, u'success': False, u'fun': u'state.apply'}
2019-07-08 15:35:08,546 [salt.utils.lazy  :104 ][DEBUG   ][8706] LazyLoaded config.merge
2019-07-08 15:35:08,547 [salt.utils.lazy  :104 ][DEBUG   ][8706] LazyLoaded mine.update
2019-07-08 15:35:23,615 [salt.utils.parsers:1071][WARNING ][8706] Minion received a SIGTERM. Exiting.
2019-07-08 15:35:23,615 [salt.cli.daemons :85  ][INFO    ][8706] Shutting down the Salt Minion
2019-07-08 15:35:23,616 [salt.log.setup   :1035][DEBUG   ][8706] Stopping the multiprocessing logging queue listener
2019-07-08 15:35:24,119 [salt.log.setup   :1041][DEBUG   ][8706] closing multiprocessing queue
2019-07-08 15:35:24,119 [salt.log.setup   :1043][DEBUG   ][8706] joining multiprocessing queue thread
2019-07-08 15:35:24,120 [salt.log.setup   :1057][DEBUG   ][8706] Stopped the multiprocessing logging queue listener
2019-07-08 15:42:54,989 [salt.state       :322 ][ERROR   ][9506] Made the following changes:
'epel-release' changed from 'absent' to '7-11'
'getpagespeed-extras-release' changed from 'absent' to '7-3.el7.gps'
`
### Versions
Master:
`Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
`
Minion:
`Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
`

**Comment by 36below** [comment] 2019-07-08 03:50
(Sorry ... new to this and can't get the formatting correct)

**Comment by MartinEmrich** [comment] 2020-01-08 11:12
Same issue here:

Salt state:

```
jre1.8:
  pkg.installed:
    - version: 1.8.0_161
```

the package is already installed, but salt tries to install it anyways:

```
# salt-call state.sls la.packages.oraclejre
[ERROR   ] The following packages failed to install/update: jre1.8=1.8.0_161
local:
----------
          ID: jre1.8
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: jre1.8=1.8.0_161
     Started: 11:10:16.126604
    Duration: 4411.396 ms
     Changes:   

```

The `ignore_epoch` option did not help.

**Comment by whytewolf** [comment] 2023-08-30 19:49
so the original case here is not a bug. name is not supposed to be used for installing from anything but a repository. this is because a repository actually will find the proper name of the package. sources is meant to be used for direct installs because you have to label each package with the name that yum will report, this is what allows pkg.installed to detect that a package is actually installed. 

@MartinEmrich what distro has a package named jre1.8? I can't find that package in centos or ubuntu. I know it is supposed to be java jre. however i think the thing you are running into which is a different problem than the original issue. is that what you are trying to install is a virtual package which salt does not support. 

I'm going to go ahead and close this issue. @MartinEmrich if you are still having problems with packages please create a new ticket. as the problem you are running into would be scope creep into this one. and please include as much detail as you can.

**Closed by whytewolf** 2023-08-30 19:49 UTC
Labels: Bug, severity-medium

**Comment by MartinEmrich** [comment] 2023-08-31 06:47
@whytewolf it's been a long time. IIRC these were the official Oracle JRE packages. After all that Oracle/Java/JRE licensing mumbojumbo, we moved to Open alternatives (OpenJDK/Corretto/etc.) long ago, so I cannot reproduce anymore.

So at least I/we are no longer affected by this.
