### ISSUE TITLE
 KeyError with schedule

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30472] opened 2016-01-20 13:14 UTC
```yaml
minion_highstate_schedule:  ## schedule highstate
  schedule.present:
    - function: state.highstate
    - seconds: 900 
    - splay: 10

```

I get this in my log;
```
[ERROR   ] Unhandled exception running state.highstate
Traceback (most recent call last):
  File "salt/utils/schedule.py", line 740, in handle_func
  File "salt/utils/context.py", line 187, in __getitem__
```

I grab the content of ret which is hit on line 740
```
{'jid': '20160120131113245095', 'return': {'service_|-minion_service_|-salt-minion_|-running': {'comment': 'The service salt-minion is already running', 'name': 'salt-minion', 'start_time': '13:11:16.597962', 'result': True, 'duration': 710.222, '__run_num__': 1, 'changes': {}, '__id__': 'minion_service'}, 'schedule_|-minion_highstate_schedule_|-minion_highstate_schedule_|-present': {'comment': 'Job minion_highstate_schedule in correct state', 'name': 'minion_highstate_schedule', 'start_time': '13:11:17.313496', 'result': True, 'duration': 37.082, '__run_num__': 2, 'changes': {}, '__id__': 'minion_highstate_schedule'}, 'file_|-minion_config_|-/srv/salt/config/minion_|-managed': {'comment': u'File /srv/salt/config/minion is in the correct state', 'pchanges': {}, 'name': '/srv/salt/config/minion', 'start_time': '13:11:13.923841', 'result': True, 'duration': 126.12, '__run_num__': 0, 'changes': {}, '__id__': 'minion_config'}}, 'schedule': 'minion_highstate_schedule', 'pid': 22118, 'fun': 'state.highstate', 'id': 'cronos'}
```

platform: SmartOS 
version: develop branch

**Comment by sjorge** [comment] 2016-01-20 13:26
```python
            ret['retcode'] = self.functions.pack['__context__']['retcode']
```
Line 740 from schedule.py

I added the following above:
```python
            log.debug(ret)
            log.debug(self.functions.pack['__context__'])
```

Output of ret is above, self.functions.pack['__context__'] is empty :/

**Comment by sjorge** [comment] 2016-01-20 13:52
On the positive note, the error seems to be non fatal.

**Comment by jfindlay** [comment] 2016-01-21 17:19
@sjorge, thanks for reporting.

**Comment by jfindlay** [comment] 2016-01-21 17:27
@sjorge, I'm getting a similar error with the default scheduled mine update on the HEAD of 2015.8.
```
[INFO    ] Running scheduled job: __mine_interval
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 2
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun': 'mine.update', 'jid': '20160121082433672210', 'pid': 31956, 'id': 'jmoney-main', 'schedule': '__mine_interval'}
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20160121082433672210
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20160121082433672210
[DEBUG   ] MinionEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_3f1c9a06f3_pub.ipc
[DEBUG   ] MinionEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_3f1c9a06f3_pull.ipc
[DEBUG   ] Sending event - data = {'clear': False, 'cmd': '_mine', 'data': {}, 'id': 'jmoney-main', '_stamp': '2016-01-21T15:24:33.690295'}
[DEBUG   ] Handling event '_minion_mine\n\n\x85\xa5clear\xc2\xa3cmd\xa5_mine\xa4data\x80\xa2id\xabjmoney-main\xa6_stamp\xba2016-01-21T15:24:33.690295'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[ERROR   ] Unhandled exception running mine.update
Traceback (most recent call last):
  File "/root/salt/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
```
@garethgreenaway, do you have any ideas on this one?

**Comment by sjorge** [comment] 2016-01-21 17:31
Good to know it is not the SmartOS freezing that is the issue.

**Comment by m4z** [comment] 2016-02-02 12:37
I'm seeing the same problem (I think) on `openSUSE 13.2` with `2015.8.3`:

```
[INFO    ] User sudo_checkmk Executing command test.ping with jid 20160202132127746242
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20160202132127746242', 'tgt': '*', 'ret': '', 'user': 'sudo_checkmk', 'arg': [], 'fun': 'test.ping', 'master_id': 'salt-master-machine.mydomain.tld'}
[INFO    ] Starting a new job with PID 13169
[DEBUG   ] LazyLoaded test.ping
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)

[DEBUG   ] MinionEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_dc25ac5f97_pull.ipc
[DEBUG   ] Sending event - data = {'clear': False, 'cmd': '_mine', 'data': {'networkname': '', 'hostname': 'salt-minion-machine', 'os': 'openSUSE', 'backup.set_mine_data': {'xfs_partitions': '', 'root': 'vda1', 'fs': 'ext4', 'partitions': 'vda1 drbd0'}, 'roles': {'syslog-client': True, 'fe-group-server': True, 'monitoring-client': True, 'ntp-client': True, 'backup-client': True}}, 'id': 'salt-minion-machine.mydomain.tld', '_stamp': '2016-02-02T12:25:56.960443'}
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20160202122556931856
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20160202122556931856
[DEBUG   ] Handling event '_minion_mine\n\n\x85\xa5clear\xc2\xa3cmd\xa5_mine\xa4data\x85\xabnetworkname\xa0\xa8hostname\xa4salt-minion-machine\xa2os\xa8openSUSE\xb4backup.set_mine_data\x84\xaexfs_partitions\xa0\xa4root\xa4vda1\xa2fs\xa4ext4\xaapartitions\xaavda1 drbd0\xa5roles\x85\xadsyslog-client\xc3\xaffe-group-server\xc3\xb1monitoring-client\xc3\xaantp-client\xc3\xadbackup-client\xc3\xa2id\xb6salt-minion-machine.mydomain.tld\xa6_stamp\xba2016-02-02T12:25:56.960443'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'salt-minion-machine.mydomain.tld', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'salt-minion-machine.mydomain.tld', 'tcp://127.0.0.1:4506')
[ERROR   ] Unhandled exception running mine.update
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 703, in handle_func
ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'salt-minion-machine.mydomain.tld', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'salt-minion-machine.mydomain.tld', 'tcp://127.0.0.1:4506')
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20160202122556931856
```

```
salt-minion-machine:~ # salt --versions
-bash: salt: command not found
salt-minion-machine:~ # salt-minion --versions
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.0
         Python: 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.0
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: SuSE 13.2 x86_64
        machine: x86_64
        release: 3.16.7-29-default
         system: openSUSE  13.2 x86_64
 
```

**Comment by anlutro** [comment] 2016-02-05 12:24
I'm getting this as well, but completely unrelated to custom schedulers/mine:

```
2016-02-05 13:20:47,642 [salt.utils.schedule][ERROR   ][9772] Unhandled exception running status.master
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
```

Similar errors have also popped up with "event.fire" instead of "status.master".

**Comment by sjorge** [comment] 2016-02-05 13:13
I'll update the title, I'm actually getting on all schedule runs.

**Comment by garethgreenaway** [comment] 2016-02-06 21:38
Looking to the cause on this one.

**Comment by garethgreenaway** [comment] 2016-02-06 23:15
I think I see the issue and it seems related to the fact that you're running a highstate.  The first run of a highstate from the scheduler runs and has a retcode in the __context_ dictionary, subsequent runs do not.  Investigating why this is the case.

**Comment by garethgreenaway** [comment] 2016-02-06 23:39
The plot thickens, running a highstate manually never includes the retcode in __context__, same for a regular state run, eg. state.sls.

**Comment by danlsgiga** [comment] 2016-02-09 16:58
I'm having the same issue running on CentOS 7 + Salt 2015.8.5

**Comment by garethgreenaway** [comment] 2016-02-09 17:37
@danlsgiga Assuming this is related to running state functions from the scheduler, the change in that PR will fix the issue.

**Comment by danlsgiga** [comment] 2016-02-09 18:12
@garethgreenaway Ah ok! Thanks.... I'm assuming this fix comes out in the next point release since it was merged to 2015.8.

**Comment by garethgreenaway** [comment] 2016-02-09 18:17
@danlsgiga That is the plan.

**Comment by hgfischer** [comment] 2016-02-16 14:05
when there will be the next point release?

**Comment by jfindlay** [comment] 2016-02-16 21:43
@hgfischer, it should be coming out this or next week.

**Comment by sakateka** [comment] 2016-02-18 16:57
> Similar errors have also popped up with "event.fire" instead of "status.master". 


@anlutro I think this bug will be corrected here https://github.com/saltstack/salt/pull/31196
lsof always returns 1 when there no active tcp session to master,  and it caused an exception

**Comment by anlutro** [comment] 2016-02-19 09:33
Upgraded to 2015.8.7 today and am still seeing the error.

**Comment by sakateka** [comment] 2016-02-19 19:42
This PR#31196  is not included in the release 2015.8.7

**Comment by cachedout** [comment] 2016-02-23 20:18
@anlutro That fix was merged one day after the release of 2015.8.7, unfortunately.

**Comment by favoretti** [comment] 2016-03-30 20:05
Seems also not in 2015.8.8?

**Comment by sjorge** [comment] 2016-04-18 20:32
This is fixed, atleast in 2016.3rc2

**Comment by warden** [comment] 2016-05-23 02:55
2015.8.9 and 2015.8.10 were released although I can't see this issue referenced in the release notes..

**Comment by jfindlay** [comment] 2016-05-23 15:15
@warden, the [fix](https://github.com/saltstack/salt/pull/30978) is in the release notes for [2015.8.8](https://docs.saltstack.com/en/latest/topics/releases/2015.8.8.html).

**Closed** 2016-05-23 21:52 UTC
Labels: Bug, Core, Fixed Pending Verification, Medium Severity, Needs Testcase, P1, Regression

**Comment by rukender** [comment] 2017-01-04 16:43
@jfindlay, I have upgraded salt-minions to the latest version i.e. 2016.11.1 and I'm still seeing this error. 
Do we have any permanent fix for this?

Not sure, if anyone else is also getting the same issue with the salt latest version.
