### ISSUE TITLE
build fails on unit.pydsl_test.PyDSLRendererTestCase

### ISSUE THREAD

**Issue by cmeisinger** [saltstack/salt#20504] opened 2015-02-08 06:19 UTC
While building RPMs against the 2014.7.1 sources downloaded from pypi, the build fails on the following unit test.  This is on a CentOS 6.6 host.

```
ERROR: test_rendering_includes (unit.pydsl_test.PyDSLRendererTestCase)
[CPU:0.0%|MEM:51.3%|Z:1] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rpmbuild/rpmbuild/BUILD/salt-2014.7.1/salt-2014.7.1/tests/unit/pydsl_test.py", line 388, in test_rendering_includes
    with salt.utils.fopen(output, 'r') as f:
  File "/home/rpmbuild/rpmbuild/BUILD/salt-2014.7.1/salt-2014.7.1/salt/utils/__init__.py", line 1066, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/tmp/tmpR_3fhY/output'

----------------------------------------------------------------------
```

**Comment by jfindlay** [comment] 2015-02-09 18:54
@cmeisinger, the pydsl tests are known to have intermittent failures.  We've resolved most of these since v2014.7.1.  If you're still experiencing errors on later versions, please feel free to respond here.

**Comment by cmeisinger** [comment] 2015-02-10 15:28
I'd be more than happy to try a new build.   Any idea when pypi will get updated as I'd prefer not to move my infrastructure to developmental builds.

**Comment by jfindlay** [comment] 2015-02-10 17:13
2014.7.2 should be coming out this week.

**Comment by Whissi** [comment] 2015-02-18 16:07
Test is failing on Gentoo with salt-2014.7.2 (same error):
```
======================================================================
ERROR: test_rendering_includes (unit.pydsl_test.PyDSLRendererTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2014.7.2/work/salt-2014.7.2-python2_7/tests/unit/pydsl_test.py", line 388, in test_rendering_includes
    with salt.utils.fopen(output, 'r') as f:
  File "/var/tmp/portage/app-admin/salt-2014.7.2/work/salt-2014.7.2-python2_7/build/lib/salt/utils/__init__.py", line 1078, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/tmp/tmps8Ojqh/output'

----------------------------------------------------------------------
```

**Comment by Whissi** [comment] 2015-02-18 20:33
Uhm, this is a funny timing issue, if I apply the following patch, the test will pass on my systems:
```DIFF
diff -rupN old/salt-2014.7.2/tests/unit/pydsl_test.py new/salt-2014.7.2/tests/unit/pydsl_test.py
--- old/salt-2014.7.2/tests/unit/pydsl_test.py  2015-02-12 18:55:39.000000000 +0100
+++ new/salt-2014.7.2/tests/unit/pydsl_test.py  2015-02-18 21:27:06.120387894 +0100
@@ -372,6 +372,8 @@ class PyDSLRendererTestCase(TestCase):
                     state(color).cmd.run('echo hello '+color+' '+str(number)+' >> {3}', cwd='/')
                 '''.format(output, output, output, output)))

+            import time
+            time.sleep(30)
             state_highstate({'base': ['aaa']}, dirpath)
             expected = textwrap.dedent('''\
                 X1
```

Without this "patch", when the test reaches
```
salt/state.py(2728)render_highstate()
-> statefiles = fnmatch.filter(self.avail[saltenv], sls_match)
```
`self.avail[saltenv]` is empty
```
(Pdb) p self.avail[saltenv]
[]
```
but it should be
```
(Pdb) p self.avail[saltenv]
['aaa', 'xxx', 'yyy']
```

**Comment by Whissi** [comment] 2015-02-18 21:45
OK, `sleep(30)` helps because `check_file_list_cache` from `salt/fileserver/_init_.py` caches for 30 seconds. If I lower *fileserver_list_cache_time* value in the file we don't need to wait 30 seconds.

So the question is how to force a cache refresh... and is this something the test should do or are we missing a forced cache refresh somewhere else.

**Comment by jfindlay** [comment] 2015-02-18 22:38
We've fixed most of these failed tests over the past few weeks but were mainly concentrating on one branch (develop) in order to try to get sanity restored.  It is possible that not all of the fixes have been backported, which may be why you're still seeing this race condition.

**Comment by Whissi** [comment] 2015-02-18 23:12
I just tried develop and the test (which was renamed to *PyDSLRendererIncludeTestCase.test_rendering_includes*) is still failing with the same problem.

The problem is, that the test's `setUp()` will create the HighState which populates the available files first and caches the result.
When `test_rendering_includes()` runs later, the cache is still valid so the state files the test creates aren't seen.

If you only run `test_rendering_includes()` removing `setUp()` for this test would be enough. But if you run this test twice within 30 seconds, the second test would fail again, because the file cache, populated by the first run, would be still valid (and if another test running before this test populates the cache, too, you would have the same problem).

So we need a way to invalidate the cache or a way to manually add the created files to the cache. Not sure if we can use `cache_local_file()` from *salt/fileclient.py* or `update()` from *salt/fileserver/roots.py*.


Or if you say that's an edge case, adding `time.sleep(30)` to the test would workaround the problem. But that's hack ;)

**Comment by jfindlay** [comment] 2015-02-18 23:21
@Whissi, thanks for looking at this.  @cachedout would have better responses to the points you've made than I.

**Comment by cachedout** [comment] 2015-11-30 23:34
I have fixed this by migrating this to integraiton tests and removing the hacks that were in place. Since then, I have not seen a single test failure. Therefore, I'm going to close this issue.

**Closed by cachedout** 2015-11-30 23:34 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P3, Platform
