### ISSUE TITLE
When onlyif and unless are used together in a state definition, just onlyif gets executed

### ISSUE THREAD

**Issue by cruatta** [saltstack/salt#30161] opened 2016-01-05 22:20 UTC
It appears that when you use both unless and onlyif in a state definition, onlyif takes precedence over unless and the unless statement is ignored. I would expect both onlyif and unless to be run to verify whether or not a state should be run. Here is an example.

```
[root@server1 test]# pwd
/vagrant/salt/test

[root@server1 test]# cat init.sls
test:
  file.managed:
    - name: /test.txt
    - contents: test
    - unless: echo 1
    - onlyif: echo 0

[root@server1 test]# salt-call state.sls test --state-output=verbose
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://test/init.sls'
[INFO    ] Running state [/test.txt] at time 14:16:34.662395
[INFO    ] Executing state file.managed for /test.txt
[ERROR   ] Exception raised when processing __virtual__ function for nova. Module will not be loaded global name 'novaclient' is not defined
[WARNING ] salt.loaded.int.module.nova.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'nova', please fix this.
[INFO    ] Executing command 'echo 0' in directory '/root'
[INFO    ] File /test.txt is in the correct state
[INFO    ] Completed state [/test.txt] at time 14:16:35.194239
local:
----------
          ID: test
    Function: file.managed
        Name: /test.txt
      Result: True
     Comment: File /test.txt is in the correct state
     Started: 14:16:34.662395
    Duration: 531.844 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 531.844 ms
```

When I remove the onlyif, the unless gets executed.

```
[root@server1 test]# cat init.sls
test:
  file.managed:
    - name: /test.txt
    - contents: test
    - unless: echo 1
[root@server1 test]# salt-call state.sls test --state-output=verbose
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** u'test/init.sls'
[INFO    ] Running state [/test.txt] at time 14:18:12.025800
[INFO    ] Executing state file.managed for /test.txt
[ERROR   ] Exception raised when processing __virtual__ function for nova. Module will not be loaded global name 'novaclient' is not defined
[WARNING ] salt.loaded.int.module.nova.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'nova', please fix this.
[INFO    ] Executing command 'echo 1' in directory '/root'
[INFO    ] unless execution succeeded
[INFO    ] Completed state [/test.txt] at time 14:18:12.587728
local:
----------
          ID: test
    Function: file.managed
        Name: /test.txt
      Result: True
     Comment: unless execution succeeded
     Started: 14:18:12.025800
    Duration: 561.928 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 561.928 ms
```

Debug info

```
[root@server1 test]# salt-minion --versions-report
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: CentOS 6.5 Final
```

**Comment by basepi** [comment] 2016-01-07 16:53
This sounds reasonable. At the very least it should be warning you that the `unless` will be ignored, and maybe error out if we don't support both of those at the same time. But I think we can support both. Thanks for the report.

**Comment by cruatta** [comment] 2016-01-08 00:37
Thanks basepi! Definitely would like to see them both supported.

**Comment by wuxxin** [comment] 2016-11-29 15:44
still present in salt-call 2016.3.4 (Boron) and salt-call 2016.11.0 (Carbon)
please run both or report an error or document this pitfall

**Comment by marco-m** [comment] 2017-08-29 10:58
hello, any news?

**Comment by lsh-0** [comment] 2017-12-05 06:12
+1

**Comment by basepi** [comment] 2017-12-06 23:12
@rallytime Mentioning you here so at least we have a current employee subscribed to this issue. :)

**Comment by rallytime** [comment] 2017-12-07 21:16
Thanks @basepi 👍 

I'll have @garethgreenaway take a look at this issue. :)

**Comment by garethgreenaway** [comment] 2018-03-13 17:09
The fix for this has been merged and will be in the Oxygen release.  Going to close this one out.  If the problem persists, please feel free to reopen the issue.  Thanks!

**Closed by garethgreenaway** 2018-03-13 17:09 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P2, State Compiler

**Comment by UniIsland** [comment] 2018-11-11 06:56
I'm using 2018.3.3 (Oxygen).

With `module.run`, it seems this problem still exists that `unless` is ignored when used in combination with `onlyif`.

Below is my state file that reproduce this issue.

```
extract_ruby_binary:
  module.run:
    - archive.tar:
      - options: xjf
      - tarfile: {{ ruby_precompiled }}
      - cwd: {{ ruby_install_dir }}
      - dest: "./"
    - onlyif:
      - test -f {{ ruby_precompiled }}
    - unless:
      - test -d {{ ruby_install_dir ~ '/' ~ version }}
```

**Comment by wuxxin** [comment] 2018-11-16 13:52
thanks for reporting, it helped me debugging my states, because i did not think about the bug in other cases (module.run) after it was fixed.

**Comment by UniIsland** [comment] 2018-11-19 00:38
could someone reopen this issue?

**Comment by kiddom-kq** [comment] 2021-03-03 23:16
Still getting hit by this:

```sls
install_aws_cli:
  archive.extracted:
    - name: /tmp/aws-cli
    - source: /tmp/aws-cli.zip
    # We'll do our own verificaiton in a second....
    - skip_verify: True
    - onlyif:
    # Salt stack does not support verification of PGP signed hashes; we do it ourselves
    # See: https://github.com/saltstack/salt/issues/42237
    ##
      - gpg --verify /tmp/aws-cli.zip.sig /tmp/aws-cli.zip

  # If the archive was verified, it was extracted
  cmd.run:
    - name: /tmp/aws-cli/aws/install
    # cmd will be run only if all tests in the list return TRUE ($? == 0)
    - onlyif:
      # We need the extraction to have worked
      - test -f /tmp/aws-cli/aws/install

      # AND we need the awscli tools to *not* already be installed
    - unless: test -f /usr/local/aws-cli/v2/current

    # Also does not work
    # See: https://github.com/saltstack/salt/issues/57336
    # - unless:
    #   - fun: file.file_exists
    #     path: /usr/local/aws-cli/v2/current

```

**Comment by rallytime** [comment] 2021-03-04 13:50
@sagetherage Can you take a look at this one and reopen? I am tagging you here so some current folks at salt can get some 👀 on it. :)
