### ISSUE TITLE
corrupt keys in Helium

### ISSUE THREAD

**Issue by smithjm** [saltstack/salt#19061] opened 2014-12-17 19:04 UTC
I am seeing corrupt keys in helium for lots of minions, as evidenced in the salt-master log file:

[ERROR   ] Corrupt public key "/etc/salt/pki/master/minions/somehost.somedomain.com": no start line

```
           Salt: 2014.7.0
         Python: 2.7.8 (default, Nov 25 2014, 07:25:02)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.0
         PyYAML: 3.11
          ioflo: 1.0.2
          PyZMQ: 14.4.1
           RAET: 0.3.8
            ZMQ: 4.0.4
           Mako: 1.0.0
```

Running master in open mode and attempting to delete all the corrupt keys on the minions and recreate them via the below commands to see if this clears it up.  Anyone know if this is an artefact of old hydrogen keys not playing nice with helium, or a bug with helium key handling in general?  In at least one case this appears to have crashed the master daemon.

grep Corrupt /var/log/salt/master.badkeys | awk '{print $9}' | cut -d '"' -f 2 | cut -d '/' -f 7 | sort |uniq > /tmp/corrupt-keys.txt

for n in `cat /tmp/corrupt-keys.txt`; do ssh -o BatchMode=yes  $n "/etc/init.d/salt-minion stop; rm -rf /etc/salt/minion?* /etc/salt/pki; /etc/init.d/salt-minion restart"; done

**Comment by rvora** [comment] 2015-01-02 23:35
I am also seeing this issue (both master and minions are at 2014.7.0 and have always been at this version).

We have a different use case which may be easier to debug as it is reproduced daily in Continuous Deployment job.

We have a baked image (qcow2) and we rm -rf /etc/salt/pki/ before we save the image. When we boot that image, we again rm -rf /etc/salt/pki just to be safe and then start the minion (through cloud-init script).

In the Continuous Deployment job, we first create a new Salt master in Open Mode and then start multiple VMs using the baked image and we are seeing multiple VMs show "Corrupt public key" issue - say 2 to 3 VMs out of 10. VMs are started sequentially. Reactor is used to trigger highstate on the minion on minion start event. Master and all minions are in debug mode so there are lots of logs but no smoking gun that I can identify.

Salt master log shows:
2015-01-02 10:58:57,642 [salt.master                                         ][INFO    ] Clear payload received with command _auth
2015-01-02 10:58:57,643 [salt.master                                         ][INFO    ] Authentication request from hostname-redacted
2015-01-02 10:58:57,644 [salt.master                                         ][INFO    ] Clear payload received with command _auth
2015-01-02 10:58:57,644 [salt.master                                         ][INFO    ] Authentication request from hostname-redacted
2015-01-02 10:58:57,645 [salt.master                                         ][INFO    ] Authentication accepted from hostname-redacted
2015-01-02 10:58:57,643 [salt.master                                         ][INFO    ] Authentication accepted from hostname-redacted
2015-01-02 10:58:57,646 [salt.master                                         ][ERROR   ] Corrupt public key "/etc/salt/pki/master/minions/hostname-redacted": no start line
2015-01-02 10:58:57,696 [salt.master                                         ][INFO    ] Clear payload received with command _auth

Corresponding minion on "hostname-redacted" log shows:
2015-01-02 10:58:57,141 [salt.crypt                                  ][CRITICAL] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.


Remediation: Sometimes we have to just restart salt-minion. In this case, CRITICAL error shown above is the only event in minion log, even the minion start lines - like "Setting up the Salt Minion" - are absent. 

Sometimes, it seems, the problem is auto-corrected through subsequent salt-minion -> salt-master auth requests (both master and minion logs show continuous log events related to auth). Only thing we have to do then is to issue state.highstate as the Reactor fired state.highstate event never happened. In this case, minion logs look normal starting with "Setting up the Salt Minion" chatter followed by CRITICAL line and then immediately (same second or next second) followed by lines like "Decrypting the current master AES key"

Let me know if you need more information.

**Comment by iggy** [comment] 2015-01-03 03:19
Some similarities I see to our setup... Open mode and reactor triggered highstate.

**Comment by smithjm** [comment] 2015-01-03 16:47
We are also running in open mode, to handle key changes through the upgrade
from Hydrogen to Helium.  I am currently on vacation but can check this out
later next week when I'm back at work, but in the meantime, is anyone
seeing this issue who ISN'T running in open mode?

**Comment by smithjm** [comment] 2015-01-05 18:44
I have been running several hours with open mode set to false and have not seen this issue since making this change, so this particular bug appears related to open mode.  HOWEVER, I am now seeing issue #18322, so I wonder if the two aren't related at a deeper level.

**Comment by cachedout** [comment] 2015-01-08 22:14
@smithjm or @iggy Can either of you test that fix to see if it resolves the problem for you?

**Comment by iggy** [comment] 2015-01-08 23:33
I had to roll back to 2014.1.x. If I get some time this weekend (and nobody beats me to it), I'll try to test it.

**Comment by cachedout** [comment] 2015-01-08 23:56
@iggy Many thanks!

**Comment by iggy** [comment] 2015-01-14 20:57
I tested this briefly the other day. Not long enough to say the bug is definitely fixed (it wasn't super easy to reproduce in the first place), but long enough that I didn't see it crop up and I didn't see any other issues.

**Comment by cachedout** [comment] 2015-01-14 21:01
@iggy Sounds good. If you don't mind, I'm going to go ahead and close this issue then. If it crops back up, please drop a note here and we'll definitely re-open it. Thanks!

**Closed by cachedout** 2015-01-14 21:01 UTC
Labels: Bug, Fixed Pending Verification, High Severity

**Comment by evilNullPointer** [comment] 2015-01-29 16:53
In which version the fix is available? It's not mentioned in http://docs.saltstack.com/en/latest/topics/releases/2014.7.1.html

**Comment by rallytime** [comment] 2015-01-29 17:13
This fix should be available in 2014.7.1. Our release notes did not contain an exhaustive list of fixes. If this is still causing a problem for you, let us know and we can take another look.

**Comment by spo0nman** [comment] 2015-02-17 15:29
Hello!

I see the same bug with 2014.7.1, I can provide more debug info if needed.

`
salt-call --versions
           Salt: 2014.7.1
         Python: 2.7.9 (default, Dec 30 2014, 13:07:54)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
`

**Comment by iggy** [comment] 2015-02-17 19:04
Is that master? minion? Are you using open_mode?

**Comment by spo0nman** [comment] 2015-02-18 12:11
Hi,

Figured what the problem could be, I'm using puppet and salt together and sharing the keys with each other. all the keys that are creating an issue look like 
"-----BEGIN RSA PUBLIC KEY-----" 

vs, the ones that work look like 

"-----BEGIN PUBLIC KEY-----"

So it could be that the puppet master for the affected hosts is generating keys wrongly.
