### ISSUE TITLE
Misleading error message when an include'd file is not found in init.sls

### ISSUE THREAD

**Issue by chrish42** [saltstack/salt#19360] opened 2015-01-05 21:46 UTC
I'm running Salt 2014.1, and I have an init.sls file in a directory foo (say) that contains only a bunch of includes, like this:

    include:
      - other.stuff
      - .localstuff1
      - .localstuff2

One of these includes (say the first one here) was pointing to a file that didn't exist (because of a typo, etc.). That sls file is referenced in my top file, etc. Here's the error message I got when running state.highstate, etc.

    local:
        Data failed to compile:
    ----
        No matching sls found for 'foo' in env 'base'.

This is a... rather poor description of the cause of the problem, to say the least. I wasted a bunch of time asking myself why Salt wasn't finding `foo/init.sls`, until trial and error led me to the real cause.

It'd have saved me a bunch of time if the error message actually mentioned that Salt was trying to include the sls for `other.stuff` and not finding it. That "no matching sls found" message for `foo` when the problem is a syntax problem, failed include, etc. is *really* misleading.

**Comment by basepi** [comment] 2015-01-06 17:48
I'm going to close this as a duplicate of #13236. We definitely do need to get this fixed, sorry for the frustration it caused.

**Closed by basepi** 2015-01-06 17:48 UTC
