### ISSUE TITLE
Pillar not updating on some minions

### ISSUE THREAD

**Issue by H20-17** [saltstack/salt#56677] opened 2020-04-17 00:40 UTC
**Description**
I am sorry. This description may not be all that clear. I have no idea how to triangulate this. On some minions. The pillar will not refresh (barring a minion restart).  _saltutil.refresh_pillar_ will return _True_ but the result of _pillar.raw_ will not be updated.

Another problem is that on these minions, pillar based scheduling mostly stops. Supposing that _job_name_ is a job scheduled in the pillar dictionary, when I do
```
schedule.show_next_fire_time job_name
```
I'll often see the fire times as being in the past!

**Setup**
I don't really know how to set this up. It appears to be happening on laptops, which leads me to believe that it may be related to suspend/resume. When the laptop sleeps and wakes up there is something salt doesn't like about it.

**Steps to Reproduce the behavior**
I don't have a solid idea of how to do this

**Expected behavior**
I expect pillar data to be always refreshable.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 3.0.2
         Jinja2: 2.10.1
        libgit2: 0.28.2
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.6 (default, Jan 30 2020, 09:44:41)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 31 Thirty One
         locale: UTF-8
        machine: x86_64
        release: 5.5.13-200.fc31.x86_64
         system: Linux
        version: Fedora 31 Thirty One

</details>
Please note that the minions are all windows 3000 py3

**Additional context**

**Comment by Akm0d** [comment] 2020-04-17 19:25
Duplicate of https://github.com/saltstack/salt/issues/31907

**Closed by Akm0d** 2020-04-17 19:25 UTC
Labels: Duplicate

**Comment by H20-17** [comment] 2020-04-17 20:00
Even if it is a duplicate why are both of these issues closed?

**Comment by H20-17** [comment] 2020-04-18 11:49
Sorry I see the other one is open. My bad. I'll never get used to github.
