### ISSUE TITLE
Error in HTTP MODULES tutorial: status must not contain quotes

### ISSUE THREAD

**Issue by flassman** [saltstack/salt#53863] opened 2019-07-16 10:05 UTC
### Description of Issue
The HTTP MODULES tutorial contains an example at the end, which contains the line:
    - status: '200'
but if you use quotes around the number, it will not match. It should be like written in the SALT.STATES.HTTP documentation:
    - status: 200

### Setup
no setup. its a documentation (tutorial) issue

### Steps to Reproduce Issue
n/a

### Versions Report
at least in 2019.2.0 and Develop the tutorial is wrong

**Comment by waynew** [comment] 2019-07-18 20:09
I can't reproduce this. Can you provide the exact state that you're working with to get this error? I'm using 2019.2.0, and both of these work for me:

```
https://www.waynewerner.com: 
  http.query:                
    - status: '200'          
``` 

```
https://www.waynewerner.com: 
  http.query:                
    - status: 200     
``` 

Are you seeing something different?

**Comment by flassman** [comment] 2019-07-25 07:59
Hi Wayne,

I'm using 2018.3.4 - so apparently it has been fixed with 2019.2.0

Anyway I suggest to make that little correction in the tutorial and
remove the quotes. It is not much work and in the docs there are no
quotes as well.

           ID: BackupService1_check_selftest
     Function: http.query
         Name: http://10.121.6.51/selftest
       Result: False
      Comment: Status 200 was not found, as specified.
         body: ...
         text: ...
         status: 200
      Started: 09:53:38.858072
     Duration: 10.953 ms
      Changes:

Best Regards,
Friedmund



Am 18.07.19 um 22:10 schrieb Wayne Werner:

**Comment by waynew** [comment] 2019-07-25 16:39
https://docs.saltstack.com/en/2018.3/topics/tutorials/http.html#tutorial-http does have an incorrect example (and is the only place I could find it). Everywhere else is sans quotes, even on 2018.3.4.

**Comment by waynew** [comment] 2019-07-25 16:44
Changed the docs (and searched for `status: '\d+'` among the entire codebase) without finding any other offenses. I'm going to go ahead and close this issue unless there's some other issue with this that I've missed.

**Closed by waynew** 2019-07-25 16:44 UTC
Labels: Cannot Reproduce, Info Needed
