### ISSUE TITLE
Add a configuration option for EC2 termination protection

### ISSUE THREAD

**Issue by stepkirk** [saltstack/salt#12573] opened 2014-05-06 20:21 UTC
The documentation shows that EC2 termination protection can be enabled/disabled using the salt-cloud command:

salt-cloud -a enable_term_protect mymachine
salt-cloud -a disable_term_protect my machine

Could we have a corresponding configuration line that could be added to the cloud profile or provider file?

**Comment by tbaker57** [comment] 2015-06-14 02:47
This looks like a duplicate of #10207. 

cheers,
Tim

**Comment by techhat** [comment] 2015-06-14 03:31
Agreed.

**Closed by techhat** 2015-06-14 03:31 UTC
Labels: Feature, Integrations, Salt-Cloud
