### ISSUE TITLE
env_vars not properly validated/casted to strings w/ virtualenv.manage/pip.install

### ISSUE THREAD

**Issue by b1naryth1ef** [saltstack/salt#36644] opened 2016-09-28 18:46 UTC
### Description of Issue/Question

Any env_vars passed into virtualenv.manage and pip.install are not validated/casted as strings, and therefore throw an exception when added to the `os.environ`. The expected behavior is for all the keys/values in the env_vars dict to be converted/casted as strings before passing to `environ.update` AND/OR to return a more reasonable error.
#### Error Case

``` yaml
/tmp/test:
  virtualenv.manage:
    - requirements: /tmp/requirements.txt
    - env_vars:
        CASS_DRIVER_BUILD_CONCURRENCY: {{ (grains.num_cpus - 1) or 1 }}
```
#### Working Case

``` yaml
/tmp/test:
  virtualenv.manage:
    - requirements: /tmp/requirements.txt
    - env_vars:
        CASS_DRIVER_BUILD_CONCURRENCY: '{{ (grains.num_cpus - 1) or 1 }}'
```
#### Example Traceback

```
 Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/virtualenv_mod.py", line 273, in managed
                  env_vars=env_vars
                File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 830, in install
                  os.environ.update(env_vars)
                File "/usr/lib/python2.7/os.py", line 486, in update
                  self[k] = dict[k]
                File "/usr/lib/python2.7/os.py", line 471, in __setitem__
                  putenv(key, item)
              TypeError: must be string, not int
```
### Steps to Reproduce Issue

Update state w/ the above sls
### Versions Report

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-33-generic
         system: Ubuntu 14.04 trusty
```

(old version, but scanning the code suggests this happens on latest master as well)

**Comment by Ch3LL** [comment] 2016-09-29 17:00
@b1naryth1ef i was able to replicate this on 2016.3.3 as well. Looks like we need to do some better validation here. Thanks!

For anyone who wants to quickly replicate this here is a docker container:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:36644 /bin/bash` (where /home/ch3ll/git/salt/ is a local git checkout of salt)
2. `salt-call --local state.apply test`

**Comment by siccrusher** [comment] 2016-09-30 09:52
Fixed in https://github.com/saltstack/salt/pull/36706

**Comment by Ch3LL** [comment] 2016-10-03 19:57
@b1naryth1ef would you mind giving that fix a try and reporting back whether it works for you? I confirmed it works for me

Thanks @siccrusher !!

**Closed** 2016-11-01 22:41 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P4, Platform, State Module
