### ISSUE TITLE
Unnecessary python2 packages in python3 CentOS repository

### ISSUE THREAD

**Issue by pacaj2am** [saltstack/salt#48914] opened 2018-08-03 11:28 UTC
### Description of Issue/Question
SaltStack ptython3 CentOS/RedHat repository includes a lot of python2 unnecessary libraries, that are in interference with other older epel python2 libraries, even stopping some other important services from starting.

The packages in https://repo.saltstack.com/py3/redhat/7/x86_64/2018.3/ starting python2 should not be in the repository at all.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Install Cnetos and IPA server. 
Instal saltstack minion with python3. 
python2-urllib3 library is overwritten from saltstack repository
IPA fails starting again

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
see above

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2018.03

**Comment by Ch3LL** [comment] 2018-08-03 14:37
ping @dmurphy18

**Comment by Poil** [comment] 2018-08-24 07:29
Also EPEL provide a newer version of python-msgpack, and conflict with Salt's one.

https://bugzilla.redhat.com/show_bug.cgi?id=1599068
Next Epel package : https://koji.fedoraproject.org/koji/buildinfo?buildID=1136121

**Comment by Poil** [comment] 2018-08-24 07:36
And another conflict:

```
Transaction check error:
  file /usr/share/doc/python-libcloud/demos/secrets.py from install of python34-libcloud-2.0.0-4.el7.noarch conflicts with file from package python2-libcloud-2.0.0rc2-1.el7.noarch
  file /usr/share/doc/python-libcloud/demos/secrets.py-dist from install of python34-libcloud-2.0.0-4.el7.noarch conflicts with file from package python2-libcloud-2.0.0rc2-1.el7.noarch
```

**Comment by Poil** [comment] 2018-08-24 07:45
Also it should be nice to provide python34-pygit2==0.26.4

**Comment by Poil** [comment] 2018-08-24 08:00
I think the best way should be to use python packages from SCL or to provide a full python environment that have no dependency with the OS packages

**Comment by Poil** [comment] 2018-08-24 08:08
But I can confirm that with Python34 I have not this problem : #40673

**Comment by Poil** [comment] 2018-08-24 08:16
Also, I'll try to package Salt with SCL Python 3.7, I haven't made RPM packages for years but we'll see

**Comment by Ch3LL** [comment] 2018-08-27 13:42
ping @dmurphy18 can you take a look here?

**Comment by dmurphy18** [comment] 2019-04-08 19:41
@pacaj2am @Poil Note with RHEL 7  (EPEL) now having Py3.6, will begin the move to building with Python 3 base salt-minions in a pure Python 3 environment. Currently Python 2 salt-minion's have been used to build Python 3 Salt for the various platforms.

The correct place to track this issue is https://github.com/saltstack/salt-pack-py3/issues/123
hence closing this since this is a packaging issue.

**Closed by dmurphy18** 2019-04-08 19:41 UTC
Labels: Pending Discussion
