### ISSUE TITLE
SALT.BEACONS.PKG don't send alerts

### ISSUE THREAD

**Issue by yorlov-ledger** [saltstack/salt#63501] opened 2023-01-17 12:10 UTC
Hello.
I have a minion configured with the following /etc/salt/minion.d/beacon.conf:
```
beacons:
  ps:
    - processes:
        haproxy: stopped
    - interval: 300
    - disable_during_state_run: True
  pkg:
    - pkgs:
        - haproxy
    - refresh: True
```
My minion has new versions of **haproxy**, but I don't see any events being sent by the beacon related to **pkg** when i run **salt-run state.event pretty=True** on my master. I've restarted salt-minion a bunch of times, and see no activity for these beacons in /var/log/salt/minion. I'm not finding activity in the debug log on my salt-master either, but maybe I'm missing something since I'm not familiar w/the log data yet for this. I can provide an excerpt of our debug log if useful.
```
salt-master --versions-report
Salt Version:
          Salt: 3005.1
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:50:07)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-57-generic
        system: Linux
       version: Ubuntu 22.04 jammy
```
```
salt-minion --versions-report
Salt Version:
          Salt: 3005.1
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:50:07)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-57-generic
        system: Linux
       version: Ubuntu 22.04 jammy

```
```
apt-show-versions  | grep haproxy
haproxy:amd64/jammy 2.4.14-1ubuntu1 upgradeable to 2.4.18-0ubuntu1
```
```
salt-call pkg.upgrade_available haproxy
local:
    True

salt-call pkg.version haproxy
local:
    2.4.14-1ubuntu1

salt-call pkg.latest_version haproxy
local:
    2.4.18-0ubuntu1
```

**Comment by OrangeDog** [comment] 2023-01-17 12:17
Is it not the case that you only get a single event when the update is first seen?
I would not expect beacons to be resending duplicate events.

**Comment by yorlov-ledger** [comment] 2023-01-17 13:42
@OrangeDog hi, i dont have any events in when i run salt-run state.event pretty=True on my master, absolutly nothing related to SALT.BEACONS.PKG or HAPROXY. It is not a problem with resending.

**Comment by OrangeDog** [comment] 2023-01-17 13:55
It only shows events since you started watching them. If you already missed the "upgrade available" event for haproxy (which you certainly have by now) you aren't going to see another one until you upgrade it and then another update is released.

**Comment by whytewolf** [comment] 2023-01-18 16:23
so, it is up to each individual beacon on if it sends every beacon tick. i will say though. pkg without an interval and refresh being true can not be good on your package manager. you're refreshing your packages every second at that point. 

to debug beacons on the minion level you have to go to the trace logging not debug. beacons are way more noisy than standard debug stuff. 

that being said what @OrangeDog said is true. although it is more than that. each beacon can choose when it sends events. but they can use `__context__` to save the last run of the beacon to compare against.

in this case the pkg beacon sets a status item that is used for tracking if the beacon should fire.
at the start of the minion the minion stores the `__context__` as none and then sets status to that same None. if status is none when it gets to the end of the beacon it doesn't fire an event. on the next run of the beacon it will set status to the value stored in `__context__`. so when it gets to the end it will check status find that the status is not none, but find that the status == the `__context__` status and not fire. so the only way to get the beacon to fire is if there is a change in the status of the pkg WHILE the minion is already running. a startup will not fire the beacon.

**Comment by whytewolf** [comment] 2023-01-18 16:41
closing this as it looks to be expected behavior. that the beacon will only fire the event once. and not on startup. only if the status of the pkg changes WHILE the minion is running.

**Closed by whytewolf** 2023-01-18 16:41 UTC
Labels: expected-behavior, Beacon
