### ISSUE TITLE
Apt 'could not get lock' only via salt

### ISSUE THREAD

**Issue by rasathus** [saltstack/salt#28817] opened 2015-11-12 12:11 UTC
Im experiencing some very strange behaviour provisioning new Ubuntu 14.04 machines.  Im using the latest vagrant box image "v20151110.0.0", to which I am adding the salt repository "http://repo.saltstack.com/apt/ubuntu/ubuntu14/latest trusty main" and have installed salt version '2015.8.1+ds-1'.

The logs from running highstate are riddled with errors, but they seem to be focused mainly around failing calls to apt ...

```
2015-11-12 11:00:21,281 [salt.loaded.int.module.cmdmod][ERROR   ][15040] Command 'apt-get -q update' failed with return code: 100
2015-11-12 11:00:21,282 [salt.loaded.int.module.cmdmod][ERROR   ][15043] Command 'apt-get -q update' failed with return code: 100
2015-11-12 11:00:21,281 [salt.loaded.int.module.cmdmod][ERROR   ][15040] stderr: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
2015-11-12 11:00:21,282 [salt.loaded.int.module.cmdmod][ERROR   ][15043] stderr: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
2015-11-12 11:00:21,282 [salt.loaded.int.module.cmdmod][ERROR   ][15040] retcode: 100
2015-11-12 11:00:21,282 [salt.loaded.int.module.cmdmod][ERROR   ][15043] retcode: 100
2015-11-12 11:00:21,282 [salt.state       ][ERROR   ][15040] An error was encountered while installing package(s): E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
2015-11-12 11:00:21,282 [salt.state       ][ERROR   ][15043] An error was encountered while installing package(s): E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
```

As shown below any call from salt is failing to get a lock, but when that command is run by the vagrant user via sudo, all is well ...

```
vagrant@node0:~$ sudo salt '*' cmd.run "apt-get update"
node0:
    E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
    E: Unable to lock directory /var/lib/apt/lists/
node0:
    E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
    E: Unable to lock directory /var/lib/apt/lists/
ERROR: Minions returned with non-zero exit code
vagrant@node0:~$ sudo apt-get update
Hit http://ppa.launchpad.net trusty InRelease
Ign http://archive.ubuntu.com trusty InRelease                                 
Hit http://deployment.eu.evertz.tv trusty InRelease                            
Hit http://mirrors.coreix.net trusty InRelease                                 
Hit http://archive.ubuntu.com trusty-updates InRelease                         
Hit http://archive.ubuntu.com trusty-backports InRelease                       
Hit http://deployment.eu.evertz.tv trusty/main amd64 Packages                  
Hit http://archive.ubuntu.com trusty Release.gpg                               
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://archive.ubuntu.com trusty Release 
```

Im at a bit of a loss as to how to debug this problem.  Any suggestions would be most welcome.

Thanks

aptitude package output :
```
vagrant@node0:~$ sudo aptitude show salt-common
Package: salt-common                     
State: installed
Automatically installed: yes
Version: 2015.8.1+ds-1
Priority: extra
Section: admin
Maintainer: Debian Salt Team <pkg-salt-team@lists.alioth.debian.org>
Architecture: all
Uncompressed Size: 13.9 M
Depends: python:any (>= 2.7.5-5~), python, python:any (< 2.8), python-dateutil, python-jinja2, python-apt, python-yaml,
         python-pkg-resources, python-requests (>= 1.0.0), python-tornado (>= 4.2.1)
Recommends: lsb-release, python-mako
Breaks: python-mako (< 0.7.0)
...
```

**Comment by rasathus** [comment] 2015-11-12 12:17
The duplicate output from the cmd.run intrigued me, so I had a look through the master logs and found something odd...

```
2015-11-12 12:10:22,931 [salt.utils.job   ][INFO    ][13050] Got return from node0 for job 20151112121022794667
2015-11-12 12:10:22,936 [salt.utils.job   ][INFO    ][13057] Got return from node0 for job 20151112121022794667
2015-11-12 12:10:22,936 [salt.loaded.int.returner.local_cache][ERROR   ][13057] An extra return was detected from minion node0, please verify the minion, this could be a replay attack
```

Even when running  the command in a targeted fashion I get a duplicate response ...

```
vagrant@node0:~$ sudo salt 'node0' cmd.run "apt-get update"
node0:
    E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
    E: Unable to lock directory /var/lib/apt/lists/
node0:
    E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
    E: Unable to lock directory /var/lib/apt/lists/
ERROR: Minions returned with non-zero exit code
```

**Comment by cachedout** [comment] 2015-11-13 17:12
@rasathus Are you positive you aren't running multiple copies of the salt-minion daemons at the same time?

**Comment by jfindlay** [comment] 2015-11-14 01:09
@rasathus, thanks for the report.  This is most likely a duplicate of #19317.  Also see #13869.  If there is any differences from #19317 that ought to be addresses, then we can reopen this issue.

**Closed by jfindlay** 2015-11-14 01:09 UTC
Labels: Bug, Duplicate, High Severity, P2, Pending Discussion, Platform
