### ISSUE TITLE
salt-ssh 2019.2.0 does not display file diff with state_output: changes on test run

### ISSUE THREAD

**Issue by PauloGDPeixoto** [saltstack/salt#52454] opened 2019-04-09 10:17 UTC
I'm using salt-ssh 2019.2.0 and running a state, with test=T, that modifies a file only gives me the output that the file is set to be changed, but not the actual diff.
I've tried adding --state-output=full --state-verbose=True, but there is no difference. I can only see the actual diff when the state is ran without test=T.

**Comment by max-arnold** [comment] 2019-04-09 15:25
Duplicate of #51932

**Closed** 2019-04-09 15:30 UTC
