### ISSUE TITLE
changing git_pillar with -name and using same -name not updating repo.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#45422] opened 2018-01-12 20:47 UTC
### Description of Issue/Question
Starting with a git_pillar repo with one - name setting and then changing the repo but not the - name can cause different erroneous situations.  

### Setup
```
ext_pillar:
  - git:
    - master https://github.com/whytewolf/test_repo1.git:
      - root: pillar/base
      - name: base
      - env: base
    - master https://github.com/whytewolf/test_repo1.git:
      - root: pillar/env1
      - name: env1
      - env: env1
```
push those pillars live to the minions.

then move to a new repo but keep the same name
```
ext_pillar:
  - git:
    - master https://github.com/whytewolf/test_repo2.git:
      - root: pillar/subbase
      - name: base
      - env: base
    - master https://github.com/whytewolf/test_repo2.git:
      - root: pillar/env1
      - name: env1
      - env: env1
```
in this example. the error `2018-01-12 19:28:02,242 [salt.utils.gitfs ][ERROR   ][11438] Root path '<bound method Pygit2._getconf of <salt.utils.gitfs.Pygit2 object at 0x2e3f090>>' not present in git_pillar remote 'master https://github.com/whytewolf/test_repo2.git', skipping.` will happen for the first repo. 

For the second repo. The test pillar will not change from env1 to env2. 

* both repos listed here are public so can be used for testing.

running `salt-run pillar.update` does not update the repo. 

so far only clearing out the git_pillar cache seems to fix the issue. 

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by whytewolf** [comment] 2018-01-12 20:48
ZD-2137

**Comment by gtmanfred** [comment] 2018-01-16 17:11
@terminalmage is there any way to solve this without deleting the git bare checkout?

Thanks,
Daniel

**Comment by terminalmage** [comment] 2018-01-31 17:18
@gtmanfred not at present. The `update()` func in salt.utils.gitfs runs a function called `clear_old_remotes()` which removes cachedirs for removed/renamed repos. But the way it detects an "old" remote is by listing all the directories in `/var/cache/salt/master/git_pillar` and then iterating over the configured remotes and removing the cachedirs for each git_pillar repo from that list, then removing the directories which remain. The reason we don't detect it as one which needs to be removed is because the directory name hasn't changed (since it was hardcoded and not derived via hashing the branch and repo).

This could be solved by checking during the `init_remote()` that the URL matches the desired one, and removing and reinit-ing the repo if it doesn't match.

**Comment by terminalmage** [comment] 2018-01-31 17:45
@gtmanfred You could probably tackle this if you want to get some experience working with salt.utils.gitfs. Because of the (mostly) shared codebase, this fix would work the same for both gitfs and git_pillar. I took the liberty of doing the legwork of playing around in a Python shell and figuring out how to get the fetch URL from the git remote in both GitPython and Pygit2:

```python
>>> import git
>>> repo = git.Repo('/var/cache/salt/minion/gitfs/a32591700a115f5cbbadd6c7006e8276bb627121306022baed0af4866aed12d3')
>>> dir(repo.remotes[0])
['__class__', '__delattr__', '__doc__', '__eq__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_assert_refspec', '_clear_cache', '_config_reader', '_config_section_name', '_get_fetch_info_from_stderr', '_get_push_info', '_id_attribute_', '_set_cache_', 'add', 'add_url', 'config_reader', 'config_writer', 'create', 'delete_url', 'exists', 'fetch', 'iter_items', 'list_items', 'name', 'pull', 'push', 'refs', 'remove', 'rename', 'repo', 'rm', 'set_url', 'stale_refs', 'update', 'urls']
>>> repo.remotes[0].urls
<generator object urls at 0x1397640>
>>> list(repo.remotes[0].urls)
[u'https://github.com/terminalmage/gitfs-test1']
>>> list(repo.remotes[0].urls)[0]
u'https://github.com/terminalmage/gitfs-test1'
>>>
>>>
>>> import pygit2
>>> repo = pygit2.Repository('/var/cache/salt/minion/gitfs/a32591700a115f5cbbadd6c7006e8276bb627121306022baed0af4866aed12d3')
>>> dir(repo.remotes[0])
['__class__', '__del__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_remote', '_repo', '_stored_exception', 'fetch', 'fetch_refspecs', 'get_refspec', 'name', 'push', 'push_refspecs', 'push_url', 'refspec_count', 'save', 'url']
>>> repo.remotes[0].url
u'https://github.com/terminalmage/gitfs-test1'
>>>
```

The fix here would simply be to edit both `init_remote()` functions, abstracting all of the code above the `self.gitdir = ....` line into a private helper within `init_remote()` which returns a tuple containing the repo object and the `new` value, which is what tells the function that called `init_remote()` whether or not a repo dir was init'ed there. Then you'd just be able to do something like:

```python
self.repo, new = _init()
if list(self.repo.remotes[0].urls)[0] != self.url:
    # URL does not match, the repo URL has changed. Remove and re-init.
    shutil.rmtree(self.cachedir)
    self.repo, new = _init()
```

The Pygit2 version of the code above would just use `self.repo.remotes[0].url` instead of `list(self.repo.remotes[0].urls)[0]`.

**Comment by terminalmage** [comment] 2018-01-31 17:49
Actually, the helper doesn't have to return a repo object, since it's a private function it'd have access to `self`, so the helper would literally be as simple as indenting that code and returning the value of `new`, and then doing:

```python
new = _init()
if list(self.repo.remotes[0].urls)[0] != self.url:
    # URL does not match, the repo URL has changed. Remove and re-init.
    shutil.rmtree(self.cachedir)
    new = _init()
```

**Comment by whytewolf** [comment] 2019-05-16 18:45
This is not a stale issue

**Comment by wwalker** [comment] 2019-09-14 01:06
+1 for fixing.  It is very hard for an end user, without the knowledge of a dev, to be able to figure out why git changes are not seen.

**Comment by whytewolf** [comment] 2020-01-07 22:07
This is still a problem

**Comment by sagetherage** [comment] 2020-01-31 20:11
this shouldn't get picked up again by the bot - last week we merged an update to the config

**Comment by garethgreenaway** [comment] 2020-10-13 17:38
Wasn't able to reproduce this one and confirmed with @whytewolf that previously it was easily reproducible.  Closing this one out.

**Closed by garethgreenaway** 2020-10-13 17:38 UTC
Labels: Bug, CS-R2, CS-S2, Core, Magnesium, Severity: Medium, ZD, team-core
