### ISSUE TITLE
Apt pkg does not include provides

### ISSUE THREAD

**Issue by AstraLuma** [saltstack/salt#53583] opened 2019-06-24 17:56 UTC
### Description of Issue
`pkg.installed` does not seem to consider packages that are provided but not directly installed.

Concretely, the `containerd.io` package (from `https://download.docker.com/linux/debian`) says it Provides and Conflicts with the `runc` package (which is available from the Debian repos).

### Setup
On a debian buster minion:
```
docker-repo:
  pkgrepo.managed:
    - name: 'deb [arch=amd64] https://download.docker.com/linux/debian {{grains['oscodename']}} stable'
    - file: /etc/apt/sources.list.d/docker.list
    - key_url: https://download.docker.com/linux/debian/gpg

containerd.io: pkg.installed
```
```
runc: pkg.installed
```

This will produce flapping states, where `containerd.io` uninstalls `runc` and `runc` uninstalls `containerd.io` (even though `containerd.io` claims it Provides `runc`).

### Steps to Reproduce Issue
1. Set up a minion running Debian Buster (testing)
2. Apply the above states

### Versions Report
Master:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9 
```

Minion:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.0 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-5-amd64
         system: Linux
        version: debian 10.0 
```

**Comment by astronouth7303** [comment] 2019-06-24 17:59
It's easy to argue that `pkg.installed` is roughly equivalent to just running `apt install`, and this is the correct behavior.

I would say that you rarely want to just "install this package, exactly", but you more abstractly need this service, and if another package Provides it, that satisfies the requirement. (There are, of course, situations where a Provides won't cut it, but again, my argument is that they're not the norm.)

**Comment by merichar** [comment] 2021-04-19 18:33
I am running into a similar issue (Debian 10.28-1) with salt (3002.5) not recognizing libgcc-s1 as Providing/Replacing libgcc1 as a dependency for minecraft-launcher. @AstraLuma, I'm tacking on to this issue based on your comment:
> I would say that you rarely want to just "install this package, exactly", but you more abstractly need this service, and if another package Provides it, that satisfies the requirement.

But if you don't feel they are sufficiently related I'll go open a new issue.

### Package details
Package: minecraft-launcher
Depends: [...] libgcc1 (>= 1:4.1.1) [...]

Package: libgcc-s1
Replaces: libgcc1 (<< 1:10)
Provides: libgcc1 (= 1:10.2.1-6)

### Investigation
In my case, I found that it was only a problem when salt was using the python3 interface to apt (Package: python3-apt, 1.8.4.3). Salt's fallback use of the shell successfully resolved libgcc-s1 as a libgcc1 replacement. 

When `HAS_APT = True` (in modules/aptpkg.py):
```
Function: pkg.installed
Result: False
Comment: An error was encountered while installing package(s): Error: unable to resolve dependencies for: None
```

When `HAS_APT = False` (in modules/aptpkg.py):
```
Function: pkg.installed
Result: True
Comment: The following packages were installed/updated: minecraft-launcher
[...]
Changes:   
----------
              minecraft-launcher:
                  ----------
                  new:
                      921
                  old:
----------
```

Next step in my case will probably be to investigate if the issue is in python-apt or (I suspect) just salt's invocation of it.

**Comment by whytewolf** [comment] 2022-02-16 19:55
can someone test against 3004? want to see if this is still an issue with the most recent version.

**Comment by whytewolf** [comment] 2022-03-08 17:58
I'm going to close this since no one responded. If someone is still running into this in 3004 please create a new ticket at this point.

**Closed by whytewolf** 2022-03-08 17:58 UTC
Labels: Bug, severity-high, Confirmed, Linux
