### ISSUE TITLE
Py3 - Nitrogen - Salt-cloud error when creating amazon vm

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#41410] opened 2017-05-24 16:22 UTC
### Description of Issue/Question
Trying to create a amazon vm using salt-cloud fails on py3 in Nitrogen.
I get this error:
```
[ERROR   ] There was a profile error: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/root/salt/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/root/salt/salt/cloud/__init__.py", line 1449, in run_profile
    ret[name] = self.create(vm_)
  File "/root/salt/salt/cloud/__init__.py", line 1279, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/ec2.py", line 2558, in create
    vm_['name'], vm_['profile'], 'ec2', vm_['driver']
  File "/root/salt/salt/utils/cloud.py", line 2540, in cachedir_index_add
    index = msgpack.load(fh_)
  File "msgpack/_unpacker.pyx", line 164, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:2622)
  File "msgpack/_unpacker.pyx", line 124, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:1918)
TypeError: a bytes-like object is required, not 'str'
```

### Setup
`providers.d`
```
amazon:
  driver: ec2
  id: xxxxx
  key: xxxxx
  securitygroup: default
  private_key: xxxxx
  keyname: xxxxx
  ssh_interface: public_ips
  ssh_username: c2-user
```

`profiles.d`
```
ec2_ubuntu_12:
  image: ami-3acc7a52
  size: m3.medium
  provider: amazon
  script_args: '-g https://github.com/saltstack/salt.git -M -P git db109a3707ae8bbabd2041b24454775906015556'
```

### Steps to Reproduce Issue
Try to create a vm using salt-cloud.
I get this error:
```
[ERROR   ] There was a profile error: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/root/salt/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/root/salt/salt/cloud/__init__.py", line 1449, in run_profile
    ret[name] = self.create(vm_)
  File "/root/salt/salt/cloud/__init__.py", line 1279, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/ec2.py", line 2558, in create
    vm_['name'], vm_['profile'], 'ec2', vm_['driver']
  File "/root/salt/salt/utils/cloud.py", line 2540, in cachedir_index_add
    index = msgpack.load(fh_)
  File "msgpack/_unpacker.pyx", line 164, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:2622)
  File "msgpack/_unpacker.pyx", line 124, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:1918)
TypeError: a bytes-like object is required, not 'str'
```
I also see this traceback in the logs:
```
[DEBUG   ] Failed to execute 'ec2.list_nodes()' while querying for running nodes: Unicode-objects must be encoded before hashing
Traceback (most recent call last):
  File "/root/salt/salt/cloud/__init__.py", line 2388, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/root/salt/salt/cloud/clouds/ec2.py", line 3582, in list_nodes
    nodes = list_nodes_full(get_location())
  File "/root/salt/salt/cloud/clouds/ec2.py", line 3437, in list_nodes_full
    return _list_nodes_full(location)
  File "/root/salt/salt/cloud/clouds/ec2.py", line 3518, in _list_nodes_full
    sigver='4')
  File "/root/salt/salt/utils/aws.py", line 434, in query
    method, endpoint, params, prov_dict, aws_api_version, location, product, requesturl=requesturl
  File "/root/salt/salt/utils/aws.py", line 247, in sig4
    payload_hash = hashlib.sha256(data).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

### Versions Report
```
Salt Version:
           Salt: 2017.5.0-97-gdb109a3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 17 2016, 17:05:23)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.9.15-x86_64-linode81
         system: Linux
        version: Ubuntu 16.04 xenial
 ```

**Comment by frogunder** [comment] 2017-05-24 16:25
Creating a Linode vm using salt-cloud is working fine. https://github.com/saltstack/salt/issues/40437

**Comment by rallytime** [comment] 2017-05-31 00:39
@frogunder Please give #41514 a try. That should fix this up for you. I think I got all of the logging stacktraces as well, but let me know if you see others.

**Comment by frogunder** [comment] 2017-05-31 17:18
@rallytime I see another error/warning.
```
[WARNING ] Unable to obtain lock for /var/cache/salt/cloud/index.p
[ERROR   ] There was a profile error: Unpack failed: error = 0
Traceback (most recent call last):
  File "/root/salt/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/root/salt/salt/cloud/__init__.py", line 1449, in run_profile
    ret[name] = self.create(vm_)
  File "/root/salt/salt/cloud/__init__.py", line 1279, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/ec2.py", line 2559, in create
    vm_['name'], vm_['profile'], 'ec2', vm_['driver']
  File "/root/salt/salt/utils/cloud.py", line 2541, in cachedir_index_add
    index = msgpack.load(fh_)
  File "msgpack/_unpacker.pyx", line 164, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:2622)
  File "msgpack/_unpacker.pyx", line 146, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2231)
msgpack.exceptions.UnpackValueError: Unpack failed: error = 0
```

**Comment by rallytime** [comment] 2017-05-31 18:49
Oh, I was hitting that error when I was debugging and fixing this issue as well. Basically what is happening is that when you ran the original `salt-cloud -p ...` call, the cache file got locked, then the stacktrace occurred and the process exited. When you ran the `salt-cloud` command again, the file is still locked and it causes the stack trace. If you remove the cached `index.p` file, it will work just fine.

Just to be sure, I tried testing this with my PR switching back and forth between py2 and py3 with the salt-cloud command and it was fine. So this bug is only caused by that locked file issue caused by the previous run.

**Comment by frogunder** [comment] 2017-05-31 21:01
It is working fine, thank you for tips and for fixing it.

**Comment by cachedout** [comment] 2017-05-31 22:35
@rallytime I am going to go ahead and close this. Let me know if that's incorrect.

**Closed** 2017-05-31 22:36 UTC
Labels: Blocker, Bug, Critical, Fixed Pending Verification, Nitrogen, P2, RIoT, Salt-Cloud
