### ISSUE TITLE
salt.function succeds even though it calls cmd.script with a non-existant script

### ISSUE THREAD

**Issue by ealphonse** [saltstack/salt#30728] opened 2016-01-29 07:22 UTC
Given:
```
init patch integration:
  salt.function:
    - tgt: 'sarje-infra'
    - name: cmd.script
    - arg:
      - salt://non_existant_file
```

`salt.function` will succeed:
```
/usr/bin/salt-run state.orchestrate Sarje.init-patch-integration
sarje-infra:
    ----------
    salt_|-init patch integration_|-cmd.script_|-function:
        ----------
        __run_num__:
            0
        changes:
            ----------
            out:
                highstate
            ret:
                ----------
                sarje-infra:
                    ----------
                    cache_error:
                        True
                    pid:
                        0
                    retcode:
                        1
                    stderr:
                    stdout:
        comment:
            Function ran successfully. Function cmd.script ran on sarje-infra.
        duration:
            132.676
        name:
            cmd.script
        result:
            True
        start_time:
            15:02:29.966378
```

`salt.function` should fail or clearly indicate that there is a problem.

Best,

Erick
```
---------------
# salt-master --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-24-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment] 2016-01-29 21:03
@ealphonse, thanks for the report.  This is a duplicate of #30367.

**Closed** 2016-01-29 21:03 UTC
Labels: Duplicate

**Comment by ealphonse** [comment] 2016-01-30 16:51
Thank you @jfindlay
