### ISSUE TITLE
state.network.system is not idempotent on ubuntu due to search value. 

### ISSUE THREAD

**Issue by leonkatz** [saltstack/salt#40759] opened 2017-04-18 23:16 UTC
```
test:
  network.system:
    - enabled: True
    - hostname: test.example.com 
    - apply_hostname: True



/usr/lib/python2.7/dist-packages/salt/states/network.py
  
        old = __salt__['ip.get_network_settings']()
        new = __salt__['ip.build_network_settings'](**kwargs)
```
old never returns SEARCH
and new always returns SEARCH.

So search is always shown as changing.

Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-34-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment] 2017-04-19 15:26
Thanks for reporting this.

If you wouldn't mind submitting a PR, we would greatly appreciate it.  Otherwise I have added this to the list of bugs for our Platform Team.

Thanks,
Daniel

**Comment by cmclaughlin** [comment] 2017-08-01 05:35
I think this duplicates issue #39151 (I have the same problem).

**Comment by cmclaughlin** [comment] 2017-08-01 05:40
And I didn't have the problem on 2016.3.6, but I do have the problem on 2017.7.0... both on Ubuntu 14.04.

**Comment by gtmanfred** [comment] 2017-08-01 14:28
It is.  Thanks for letting us know.

I am going to mark this as a duplicate of #39151

**Closed by gtmanfred** 2017-08-01 14:28 UTC
Labels: Bug, Medium Severity, P3, Platform, State Module
