### ISSUE TITLE
[BUG] Brute Force Attempt: ssh_exchange_identification: read: Connection reset by peer

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#57960] opened 2020-07-16 15:20 UTC
**Description**
Using salt-ssh, while rendering of SLS files, this can happen:
```
[TRACE   ] ssh_exchange_identification: read: Connection reset by peer
```

**Setup**
salt/_modules/ssh_failure.py
```
def test():
    return 'Test Module Function'
```

salt/tmp/ssh_failure.py
```
{% for i in range(30) %}

testcmd{{ i }}:
  cmd.run:
    - name: echo Test Output {{ salt['ssh_failure.test']() }}

{% endfor %}
```

**Steps to Reproduce the behavior**
```
salt-ssh host state.sls tmp.ssh_failure
```

**Expected behavior**

1. not opening so many ssh sessions (seems we have a host within special firewall settings right now)
2. a way to run master-only modules (seems like this here: #45450) - would also be performance booster
3. always display rendering errors (few lines of context + linenumbers to see the error easily + jinja context variables)

The way we see it, rendering errors are irrecoverable and needs thorough investigation. So, jinja variables are usually needed to get a complete picture. There is not need to hide anything. Right now, the output is:
```
salt:/srv # salt-ssh host state.sls tmp.ssh_failure
[CRITICAL] Rendering SLS 'base:tmp.ssh_failure' failed: mapping values are not allowed in this context
oml-archiv:
    - Rendering SLS 'base:tmp.ssh_failure' failed: mapping values are not allowed in this context

```

**Versions Report**
<details>
salt:/srv # salt-ssh --versions-report
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.10
        libgit2: 0.22.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.22.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: SuSE 12.3 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.114-42.1-default
         system: Linux
        version: openSUSE  12.3 x86_64
</details> 

**DEBUG OUTPUT**
```
[DEBUG   ] Rendered data from file: /var/cache/salt/master/files/base/tmp/ssh_failure.sls:


testcmd0:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd1:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd2:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd3:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd4:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd5:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd6:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd7:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd8:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd9:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd10:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd11:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd12:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd13:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd14:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd15:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd16:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd17:
  cmd.run:
    - name: echo Test Output Test Module Function



testcmd18:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd19:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd20:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd21:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd22:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd23:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd24:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd25:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd26:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd27:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd28:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}



testcmd29:
  cmd.run:
    - name: echo Test Output {'retcode': 255, '_error': 'Failed to return clean data', 'stderr': u'ssh_exchange_identification: read: Connection reset by peer\r\n', 'stdout': u''}
```

![image](https://user-images.githubusercontent.com/1389648/87690087-4a58c500-c789-11ea-94b7-34d9f9fd3931.png)

**Comment by sagetherage** [comment] 2021-03-24 00:38
The Core Team will not be able to get this in this release cycle and moving this back into planning.

**Comment by Ch3LL** [comment] 2022-01-26 17:28
> 1. not opening so many ssh sessions (seems we have a host within special firewall settings right now)

Salt-SSH renders the SLS files on the master, that is why you are seeing the multiple SSH connections. This is expected behavior. Do you need to run `ssh_failure.test` 30 times in the loop? Can you run it outside of the jinja loop?

**Comment by Ch3LL** [comment] 2023-08-02 18:37
Closing due to inactivity. Please feel free to open a new issue with further details requested

**Closed by Ch3LL** 2023-08-02 18:37 UTC
Labels: Pending-Discussion
