### ISSUE TITLE
Starting salt-minion: ImportError: No module named Random

### ISSUE THREAD

**Issue by lrhazi** [saltstack/salt#23526] opened 2015-05-11 02:57 UTC
```
# salt --versions-report
Salt Version:
           Salt: 2015.5.0-5091-gccb186b
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
           RAET: Not Installed
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.0.1
 
System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.8.1.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago
```

```
# salt-minion 
[ERROR   ] Minion failed to start: 
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 269, in start
    self.minion.tune_in()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1561, in tune_in
    self.sync_connect_master()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 579, in sync_connect_master
    raise self._connect_master_future.exception()
ImportError: No module named Random
[WARNING ] ** Restarting minion **
```

**Comment by thatch45** [comment] 2015-05-11 15:17
Looks like we may need to provide a backport of pycrypto to rhel 5 and 6...

**Comment by cachedout** [comment] 2015-05-13 07:15
Ouch! So if I'm reading this right, 2015.5 is currently non-functional on both RHEL5 and 6?!

**Comment by DmitryKuzmenko** [comment] 2015-06-08 17:40
@thatch45 @cachedout I reproduced it on CentOS 6.6 and reviewed salt code changes. The problem with lack support of pycrypto 2.0.1 initiated by work on removing M2Crypto: 21b52fa810968c42330e77cabcb874230244d99d and merged into develop here a7e417cfd9d8b73eca7b8d393f59f15ed4ad01af. Both this work and the salt revision used by @lrhazi  ccb186b aren't included in any release yet. It's in the develop branch only. So we didn't broken anything (yet). I've checked all v2015.5.0-2, all of them use M2Crypto and work on CentOS 6.6 with  pycrypto 2.0.1 installed with yum from system repositories.

What about develop branch, is see the following options here:
* Most clean and correct way is to make salt depend on pycrypto>=2.5.0
* Keep support of M2Crypto for pycrypto < 2.5.0. I looked up the changes removed M2Crypto, it looks possible to keep both. The work on M2Crypto removal was done by @msteed, maybe he will shatter my confidence about it.
* As @thatch45 proposed backport pycrypto 2.6 features. Do we really need to do it?

**Comment by msteed** [comment] 2015-06-08 21:34
M2Crypto is definitely being removed as a dependency, and we need pycrypto >= 2.6 in order to replace it. So we will need updated pycrypto packages for rhel 5 and 6.

I think @rallytime can provide details about what we are doing on the build executors to work around this for now.

**Comment by rallytime** [comment] 2015-06-08 22:40
Yes, the test VMs that are running on Jenkins ran into a similar problem. First, you must remove any pycrypto previously installed. Then install 2.6.1 via pip. (You first have to remove any older versions of pycrypto because if you don't remove them first, there is a path conflict between the new pip installed version and the old system-installed version.)

**Comment by tbaker57** [comment] 2015-06-09 00:04
@msteed python-crypto2.6-2.6.1-2.el6 is definitely in epel6-stable now (https://bugzilla.redhat.com/show_bug.cgi?id=1103566). But not so much for epel5 :-(

cheers,
Tim

**Comment by DmitryKuzmenko** [comment] 2015-06-09 12:23
Is there anything more that I can do for this issue?

**Comment by drawsmcgraw** [comment] 2015-07-31 19:50
@lrhazi Thank you for filing this issue. I've been wrestling with broken pycrypto installs for several days now and didn't realize this was the issue. 

For posterity, my stacktrace is a little different and `versions-report` shows that pycrypto is *not* installed. Regardless, the workaround mentioned by rallytime works for me.

```
[root@host-10 nagios-plugins]# salt-call test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
NameError: global name 'AES' is not defined
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 59, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 69, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 92, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 322, in __init__
    self.gen_modules(initial_load=True)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 334, in gen_modules
    self.opts['environment']
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 83, in compile_pillar
    dictkey='pillar',
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 271, in crypted_transfer_decode_dictentry
    ret = self.sreq.send('aes', self.auth.crypticle.dumps(load), tries, timeout)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 834, in dumps
    return self.encrypt(self.PICKLE_PAD + self.serial.dumps(obj))
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 802, in encrypt
    cypher = AES.new(aes_key, AES.MODE_CBC, iv_bytes)
NameError: global name 'AES' is not defined
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 59, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 69, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 92, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 322, in __init__
    self.gen_modules(initial_load=True)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 334, in gen_modules
    self.opts['environment']
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 83, in compile_pillar
    dictkey='pillar',
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 271, in crypted_transfer_decode_dictentry
    ret = self.sreq.send('aes', self.auth.crypticle.dumps(load), tries, timeout)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 834, in dumps
    return self.encrypt(self.PICKLE_PAD + self.serial.dumps(obj))
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 802, in encrypt
    cypher = AES.new(aes_key, AES.MODE_CBC, iv_bytes)
NameError: global name 'AES' is not defined

[root@host-10 nagios-plugins]# salt-call --versions-report
           Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: Not Installed
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

```

Thanks @rallytime for the workaround. It works perfectly. 

Oddly, though, installing `python-crypto2.6` via Yum (on CentOS 6.4) does *not* fix the problem. That's after removing both the pip-installed and the yum-installed versions.

**Comment by tbaker57** [comment] 2015-08-02 02:44
@drawsmcgraw - yes, there is something slightly broken with the python-crypto2.6 in epel. It doesn't create the 'Crypto' symlink in the python site-packages directory. See #25502 for a similar scenario

**Comment by DmitryKuzmenko** [comment] 2015-10-28 17:00
@rallytime @jfindlay @cachedout 
Is it a core issue? Maybe we should reassign to somebody else?

**Comment by cachedout** [comment] 2015-10-29 19:32
This looks like it was filed prior to the saltstack repo going online. With our repo, this issue should not be occuring. Therefore, I'm going to close this. If anybody can reproduce this using Saltstack packages from repo.saltstack.com, please leave a comment and we'll re-open this. Thanks.

**Closed by cachedout** 2015-10-29 19:32 UTC
Labels: Bug, Core, Critical, P3

**Comment by DmitryKuzmenko** [comment] 2015-10-29 20:34
Thanks, Mike!
