### ISSUE TITLE
OEL - statick routes

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#30387] opened 2016-01-15 14:16 UTC
hello

the network module on OEL can't set the static routes properly.
this is my network settings:
```
routes:
  network.routes:
    - name: eth0
    - routes:
      - name: internal networks 172.0.0.0
        ipaddr: 172.0.0.0
        netmask: 255.0.0.0
        gateway: {{ route_sec }}
    - routes:
      - name: internal networks 10.3.0.0
        ipaddr: 10.3.0.0
        netmask: 255.255.0.0
        gateway: {{ route_sec }}
```
and when I run it I got the 10.3.0.0 network into the route-eth0 file. Plus the network was restarted therefore the salt lost the connection with the minion because the master is in the 172 network.

I got this when I run the network command:
```
      ID: routes
    Function: network.routes
        Name: eth0
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/network.py", line 457, in routes
                  __salt__['ip.apply_network_settings'](**kwargs)
                File "/usr/lib/python2.6/site-packages/salt/modules/rh_ip.py", line 1129, in apply_network_settings
                  res = __salt__['service.restart']('network')
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 900, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.6/site-packages/salt/utils/lazy.py", line 93, in __getitem__
                  raise KeyError(key)
              KeyError: 'service.restart'
     Started: 14:03:14.746843
    Duration: 650.304 ms
```

**Comment by jfindlay** [comment] 2016-01-15 18:00
@BalintSzigeti, thanks for the report.  As @sjorge indicates, the core problem is the same as #30386, which is that the service execution module is not loading, so I am going to close this as a duplicate of that.

**Closed by jfindlay** 2016-01-15 18:00 UTC
Labels: Duplicate
