### ISSUE TITLE
unit.utils.test_vmware.RenameDatastoreTestCase.test_rename_datastore_raise_vim_fault

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52810] opened 2019-05-02 21:25 UTC
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.utils.test_vmware/RenameDatastoreTestCase/test_rename_datastore_raise_vim_fault)
---

name 'vim' is not defined

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 2131, in rename_datastore
    datastore_ref.RenameDatastore(new_datastore_name)
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1091, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1142, in _mock_call
    raise effect
pyVmomi.VmomiSupport.vim.fault.VimFault: (vim.fault.VimFault) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'vim_fault',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 4304, in test_rename_datastore_raise_vim_fault
    'fake_new_name')
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 2132, in rename_datastore
    except vim.fault.NoPermission as exc:
NameError: name 'vim' is not defined
		
```

**Comment by waynew** [comment] 2019-05-02 21:28
several other `RenameDatastoreTestCase` errors failed with this `vim is not defined`

**Comment by waynew** [comment] 2019-05-02 21:43
And by several, I mean like... over 100. So fixing this vim not defined thing should help a lot:

- unit.utils.test_vmware.GetLicensesTestCase.test_raise_vim_fault
- unit.modules.test_vsphere.CreateDatacenterTestCase.test_returned_value
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_get_disks
- unit.utils.test_vmware.UnregisterVirtualMachineTestCase.test_unregister_vm_raise_vim_fault
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_supported_proxes
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_invalid_schema_validation
- unit.utils.test_vmware.GetDatacentersTestCase.test_get_mors_with_properties_returns_empty_array
- unit.utils.test_vmware.AssignLicenseTestCase.test_update_assigned_licenses_raises_runtime_fault
- unit.utils.test_vmware.RemoveDvportgroupTestCase.test_destroy_task_raises_no_permission
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_validate
- unit.modules.test_vsphere.CreateDatacenterTestCase.test_supported_proxies
- unit.modules.test_vsphere.ListClusterTestCase.test_supported_proxies
- unit.utils.test_vmware.GetServiceInfoTestCase.test_about_raises_runtime_fault
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test__get_proxy_target_call
- unit.utils.test_vmware.WaitForTaskTestCase.test_first_task_info_raise_vim_fault
- unit.utils.test_vmware.SetDvsNetworkResourceManagementEnabledTestCase.test_enable_network_resource_management_raises_no_permission
- unit.utils.test_vmware.UnregisterVirtualMachineTestCase.test_unregister_vm_raise_runtime_fault
- unit.utils.test_vmware.CreateDvportgroupTestCase.test_create_dvporgroup_task_raises_no_permission
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test__get_proxy_target_call
- unit.utils.test_vmware.DeleteVirtualMachineTestCase.test_destroy_vm_raise_runtime_fault
- unit.utils.test_vmware.AssignLicenseTestCase.test_instance_uuid_raises_runtime_fault
- unit.utils.test_vmware.RegisterVirtualMachineTestCase.test_register_vm_raise_runtime_fault
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test__get_proxy_target_call
- unit.utils.test_vmware.WaitForTaskTestCase.test_inner_loop_task_info_raise_no_permission
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_remove_capacity_from_diskgroup
- unit.utils.test_vmware.AssignLicenseTestCase.test_instance_uuid_raises_no_permission
- unit.utils.test_vmware.UpdateClusterTestCase.test_reconfigure_compute_resource_raise_no_permission
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_erase_disk_partitions
- unit.utils.test_vmware.GetHostsTestCase.test_no_hosts
- unit.utils.test_vmware.CreateVirtualMachineTestCase.test_create_vm_host_task_call
- unit.utils.test_vmware.GetLicensesTestCase.test_raise_runtime_fault
- unit.utils.test_vmware.GetRootFolderTestCase.test_raise_runtime_fault
- unit.modules.test_vsphere.ListClusterTestCase.test_default_service_instance
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_disk_not_found_safety_checks_set
- unit.utils.test_vmware.GetDatacentersTestCase.test_datastore_not_found
- unit.utils.test_vmware.UpdateDvsTestCase.test_reconfigure_dvs_task_raises_no_permission
- unit.utils.test_vmware.GetHostsTestCase.test_filter_cluster
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_multiple_datastores_found
- unit.utils.test_vmware.WaitForTaskTestCase.test_first_task_info_raise_no_permission
- unit.utils.test_vmware.DeleteVirtualMachineTestCase.test_destroy_vm_raise_vim_fault
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_instance_uuid_raises_runtime_fault
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_success_output
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_no_disk_id_or_scsi_address
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_get_datastore_call
- unit.utils.test_vmware.UpdateDvportgroupTestCase.test_reconfigure_dvporgroup_task_raises_runtime_fault
- unit.utils.test_vmware.SetDvsNetworkResourceManagementEnabledTestCase.test_enable_network_resource_management_raises_vim_fault
- unit.utils.test_vmware.GetHostsTestCase.test_get_si_datacenter_name_no_cluster_name
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_disk_group_not_found_safety_checks_set
- unit.utils.test_vmware.RemoveDvportgroupTestCase.test_destroy_treconfigure_dvporgroup_task_raises_vim_fault
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_get_diskgroups
- unit.utils.test_vmware.CreateClusterTestCase.test_create_cluster_raise_no_permission
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_get_no_datastores
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_exception
- unit.utils.test_vmware.GetLicenseManagerTestCase.test_raise_runtime_fault
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_default_params
- unit.utils.test_vmware.RegisterVirtualMachineTestCase.test_register_vm_raise_vim_fault
- unit.utils.test_vmware.UpdateDvsTestCase.test_reconfigure_dvs_task_raises_runtime_fault
- unit.utils.test_vmware.GetDatacentersTestCase.test_get_all_datastores
- unit.utils.test_vmware.GetLicenseManagerTestCase.test_raise_vim_fault
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_datastore_not_found
- unit.utils.test_vmware.UpdateVirtualMachineTestCase.test_update_vm_raise_runtime_fault
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_get_datastores_call
- unit.utils.test_vmware.CreateDvsTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_invalid_argument_no_fault_message
- unit.utils.test_vmware.CreateVirtualMachineTestCase.test_create_vm_raise_vim_fault
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_diskgroup_not_found
- unit.utils.test_vmware.IsConnectionToAVCenterTestCase.test_api_type_raise_runtime_fault
- unit.utils.test_vmware.CreateClusterTestCase.test_create_cluster_raise_vim_fault
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_remove_capacity_from_diskgroup_data_evacuation_false
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_get_disk_groups
- unit.utils.test_vmware.GetLicenseAssignmentManagerTestCase.test_raise_runtime_fault
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_supported_proxies
- unit.utils.test_vmware.IsConnectionToAVCenterTestCase.test_api_type_raise_no_permission
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_defined_datacenter_names
- unit.utils.test_vmware.GetDatacentersTestCase.test_datastore_found
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_supported_proxes
- unit.utils.test_vmware.UpdateDvsTestCase.test_reconfigure_dvs_task_raises_vim_fault
- unit.utils.test_vmware.UpdateVirtualMachineTestCase.test_update_vm_raise_vim_fault
- unit.utils.test_vmware.GetLicenseManagerTestCase.test_raise_no_permission
- unit.utils.test_vmware.GetHostsTestCase.test_get_si_datacenter_name_and_cluster_name
- unit.utils.test_vmware.RemoveDvportgroupTestCase.test_destroy_treconfigure_dvporgroup_task_raises_runtime_fault
- unit.utils.test_vmware.GetLicenseAssignmentManagerTestCase.test_raise_vim_fault
- unit.utils.test_vmware.GetHostsTestCase.test_get_si_no_datacenter_no_cluster
- unit.modules.test_vsphere.ListClusterTestCase.test_no_cluster_raises_argument_value_error
- unit.utils.test_vmware.UpdateClusterTestCase.test_reconfigure_compute_resource_raise_vim_fault
- unit.utils.test_vmware.WaitForTaskTestCase.test_inner_loop_task_info_raise_vim_fault
- unit.modules.test_vsphere.CreateDatacenterTestCase.test_default_service_instance
- unit.utils.test_vmware.GetDatacentersTestCase.test_no_parameters
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_supported_proxes
- unit.utils.test_vmware.GetServiceInfoTestCase.test_about_raises_vim_fault
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_scsi_address_not_found
- unit.utils.test_vmware.GetHostsTestCase.test_host_get_all_hosts
- unit.utils.test_vmware.GetLicensesTestCase.test_raise_no_permission
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_get_proxy_target
- unit.utils.test_vmware.CreateDvsTestCase.test_create_dvs_task_raises_vim_fault
- unit.utils.test_vmware.CreateDvsTestCase.test_get_network_folder
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_success_output
- unit.utils.test_vmware.WaitForTaskTestCase.test_inner_loop_task_info_raise_runtime_fault
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_rename_datastore_call
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_vim_fault
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_instance_uuid_raises_vim_fault
- unit.utils.test_vmware.CreateDvsTestCase.test_create_dvs_task_raises_runtime_fault
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_no_permission
- unit.utils.test_vmware.GetRootFolderTestCase.test_raise_no_permission
- unit.modules.test_vsphere.ListClusterTestCase.test_get_cluster_call
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_get_managed_object_name_calls
- unit.utils.test_vmware.GetDatacentersTestCase.test_get_mors_with_properties_call
- unit.utils.test_vmware.CreateDvsTestCase.test_create_dvs_task_raises_no_permission
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_success_output
- unit.utils.test_vmware.GetHostsTestCase.test_one_host_returned
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_remove_disk_group
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_query_assigned_licenses_raises_vim_fault
- unit.utils.test_vmware.RegisterVirtualMachineTestCase.test_register_vm_raise_no_permission
- unit.utils.test_vmware.IsConnectionToAVCenterTestCase.test_api_type_raise_vim_fault
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_scsi_address_to_disk_id_map
- unit.utils.test_vmware.UpdateDvportgroupTestCase.test_reconfigure_dvporgroup_task_raises_no_permission
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_instance_uuid_raises_no_permission
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_supported_proxies
- unit.utils.test_vmware.WaitForTaskTestCase.test_first_task_info_raise_runtime_fault
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_default_service_instance
- unit.utils.test_vmware.AssignLicenseTestCase.test_update_assigned_licenses_raises_no_permission
- unit.utils.test_vmware.AssignLicenseTestCase.test_update_assigned_licenses_raises_vim_fault
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_system_fault
- unit.utils.test_vmware.GetServiceInfoTestCase.test_about_raises_no_permission
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_supported_proxes
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_returned_array
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_query_assigned_licenses_raises_no_permission
- unit.utils.test_vmware.UpdateDvportgroupTestCase.test_reconfigure_dvporgroup_task_raises_vim_fault
- unit.utils.test_vmware.SetDvsNetworkResourceManagementEnabledTestCase.test_enable_network_resource_management_raises_runtime_fault
- unit.utils.test_vmware.UpdateClusterTestCase.test_reconfigure_compute_resource_raise_runtime_fault
- unit.modules.test_vsphere.ListClusterTestCase.test__get_cluster_dict_call
- unit.utils.test_vmware.CreateDvportgroupTestCase.test_create_dvporgroup_task_raises_runtime_fault
- unit.utils.test_vmware.GetHostsTestCase.test_filter_hostname
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_remove_disk_group_data_accessibility_false
- unit.utils.test_vmware.CreateVirtualMachineTestCase.test_create_vm_raise_no_permission
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_remove_datastore_call
- unit.utils.test_vmware.CreateDvportgroupTestCase.test_create_dvporgroup_task_raises_vim_fault
- unit.utils.test_vmware.GetRootFolderTestCase.test_raise_vim_fault
- unit.utils.test_vmware.GetLicenseAssignmentManagerTestCase.test_raise_no_permission
- unit.utils.test_vmware.CreateClusterTestCase.test_create_cluster_raise_runtime_fault
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_invalid_argument_with_fault_message
- unit.utils.test_vmware.AssignLicenseTestCase.test_instance_uuid_raises_vim_fault
- unit.utils.test_vmware.CreateVirtualMachineTestCase.test_create_vm_raise_runtime_fault
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_query_assigned_licenses_raises_runtime_fault
- unit.utils.test_vmware.GetHostsTestCase.test_get_all_host_flag_not_set_and_no_host_names

**Comment by Ch3LL** [comment] 2019-05-03 13:22
duplicate of https://github.com/saltstack/salt/issues/51886

**Closed by Ch3LL** 2019-05-03 13:22 UTC
Labels: 2019.2.1, Test Failure
