### ISSUE TITLE
Add option for ssh_auth state to allow something like this_key_only=true

### ISSUE THREAD

**Issue by lloesche** [saltstack/salt#18252] opened 2014-11-19 15:58 UTC
We're using the ssh_auth state in our formulas for setting ssh pubkeys for our user accounts.
There's currently a present and an absent option which allow to add and remove keys. However our use case would be to set a single ssh key for a user and remove any others. Basically an update function.

Our keys are stored in an external pillar. When a user updates his ssh key it replaces the previously stored key in the pillar. At that point we have no chance to call the 'absent' function on the old key anymore.
Of course we could implement some elaborate functionality like a key versioning or history but that seems like a very complicated solution to a rather simple problem.

For some users we would like to say "this is the user's ssh key and his account should only have this one key set - please remove any other keys for this user". I assume this would be fairly easy to implement inside of Salt and would be super helpful.

**Comment by pirxthepilot** [comment] 2016-06-24 17:12
Hello, just checking where we are with this? This feature is badly needed in our environment where users periodically refresh or reset their ssh keys.

Hoping for a flag similar to ansible's "exclusive" option:
http://docs.ansible.com/ansible/authorized_key_module.html

Thanks!

**Comment by pirxthepilot** [comment] 2016-06-24 17:53
Possibly similar to #13340

**Comment by darkpixel** [comment] 2018-05-25 20:29
I'd say this is a dupe of #13340

**Comment by mchugh19** [comment] 2019-03-15 23:02
With the merge of #50141, I think this can be closed.

**Closed** 2019-03-21 00:23 UTC
Labels: Feature
