### ISSUE TITLE
Windows saltutil.kill_job

### ISSUE THREAD

**Issue by freimer** [saltstack/salt#21057] opened 2015-02-26 04:19 UTC
When running a `salt '*' saltutil.kill_job` Windows hosts fail with the following:
```
dc2.redacted:
    The minion function caused an exception: Traceback (most recent call last):
      File "salt/minion.py", line 1022, in _thread_return
      File "salt/modules/saltutil.py", line 581, in kill_job
    AttributeError: 'module' object has no attribute 'SIGKILL'
```
Windows hosts should fail gracefully, not with an exception.  Although this job was not active on the hosts, this brings up the question whether kill_job is even supported or functional on Windows hosts...
See internal issue 197.

**Comment by jfindlay** [comment] 2015-02-26 17:52
Thanks for the report, @freimer.

**Comment by freimer** [comment] 2015-03-03 00:52
This is a dup of issue #14150, fixing now.

**Comment by rallytime** [comment] 2015-03-03 16:56
Thanks for following up here, @freimer! Since your pull request was merged, should this issue be closed?

**Comment by rallytime** [comment] 2015-03-03 16:59
Actually since this is a duplicate of #14150, it probably should be. @freimer Thanks very much for your work here and do leave a comment if I have closed this prematurely. We can re-open as needed.

**Closed by rallytime** 2015-03-03 16:59 UTC
Labels: Bug, Fixed Pending Verification, High Severity, Windows

**Comment by twangboy** [comment] 2015-05-11 21:44
Multi-Processing currently works on the develop branch. I have verified that turning on Multi-Processing does fix this problem. You can turn on Multi-Processing in earlier branches, but there is a stack trace when the minion starts. The minion, however, seems to continue to function correctly in the tests I did. There are no plans to fix the stack trace in the earlier branches.
