### ISSUE TITLE
Exit code is 0 when the minion is not response

### ISSUE THREAD

**Issue by jason-tian** [saltstack/salt#42636] opened 2017-07-31 05:49 UTC
### Description of Issue/Question
Our all servers are managed by saltstack, we often write scripts to call salt state.apply or highstate for automation. But it confusing us that the exit code is still 0 when the minion is not response. Maybe the minion is broken, but the script can't tell me it. 
Is there any ways or suggestion to catch the correct exit code?
### Setup
The script is wrote by python. I use subprocess.CalledProcessError to catch the exception if the exit is not zero.
Sample:

    try:
        dm.start()
        cmd_r = "salt '{}' state.apply test.test".format(hostname)
        return_roll = subprocess.check_call(cmd_r, shell=True)
        dm.successful()
    except subprocess.CalledProcessError as e:
        print e.output
        dm.failed_dataloader()
        sys.exit(2)

### Steps to Reproduce Issue
    root@jt:~/tmp# salt 'testserver' state.apply test.test
    testserver:
        Minion did not return. [No response]
    root@jt:~/tmp# echo $?
    0

### Versions Report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.1.2
       cherrypy: 3.5.0
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.22.1
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.8 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.8

**Comment by mchugh19** [comment] 2017-07-31 06:45
Seems this might be looked at for the next release: #18510

**Comment by gtmanfred** [comment] 2017-07-31 15:00
This will be fixed in the next release, and is a duplicate of #18510

**Closed by gtmanfred** 2017-07-31 15:00 UTC
