### ISSUE TITLE
multi-syndic & multi-master documentation request

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#25150] opened 2015-07-04 00:50 UTC
Hi, @jacksontj , I want to change to use Multi-Syndic & Multi-Master in my prod, and it will be better if you can offer me some documentation about ``` How to setup it & How to optimize it etc.. ```

Many Thanks.

**Comment by jfindlay** [comment] 2015-07-07 19:45
@Colstuwjx, the multimaster and syndic documentation are here:
http://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html
http://docs.saltstack.com/en/latest/topics/topology/syndic.html

Do you have a specific question about them?

**Comment by Colstuwjx** [comment] 2015-07-08 01:30
Hi, @jfindlay , I means Multi-Syndic Architecture, not Syndic. As it was introduced by @jacksontj , I hope there will be some document.

**Comment by jfindlay** [comment] 2015-07-08 17:09
@Colstuwjx, this is actually a duplicate of #18751.  If you have any further comments, you are welcome to add them there, thanks.

**Closed by jfindlay** 2015-07-08 17:09 UTC
Labels: Core, Documentation, Duplicate, Feature, P2
