### ISSUE TITLE
Broken pkg.installed with sources

### ISSUE THREAD

**Issue by Azidburn** [saltstack/salt#40219] opened 2017-03-22 11:57 UTC
### Description of Issue/Question
When i installed a packet from source, salt response with an error.
I check with the example from documentation from [https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed)

state_aggregate is enabled.

I think the Problem is a combination from [https://github.com/saltstack/salt/blob/2016.11/salt/states/pkg.py#L2665-L2667](https://github.com/saltstack/salt/blob/2016.11/salt/states/pkg.py#L2665-L2667) and [https://github.com/saltstack/salt/blob/2016.11/salt/states/pkg.py#L315-L319](https://github.com/saltstack/salt/blob/2016.11/salt/states/pkg.py#L315-L319). In mod_aggregate function the pkgs list append the name value, so pkgs parameter has a value. _find_install_targets function check if sources parameter and pkgs parameter exist and throw an error.

### Steps to Reproduce Issue
test.sls
```
mypkgs:
  pkg.installed:
    - sources:
      - foo: salt://rpms/foo.rpm
      - bar: http://somesite.org/bar.rpm
      - baz: ftp://someothersite.org/baz.rpm
      - qux: /minion/path/to/qux.rpm
```

response
```
salt example.minion state.apply test test=false
example.minion:
----------
          ID: mypkgs
    Function: pkg.installed
      Result: False
     Comment: Only one of "pkgs" and "sources" is permitted.
     Started: 09:56:56.605352
    Duration: 10.872 ms
     Changes:   

Summary for example.minion
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  10.872 ms
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.4.6
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.4.4
       M2Crypto: 0.21.1
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.12 (default, Jun 28 2016, 06:57:42) [GCC]
   python-gnupg: 0.3.7
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.4
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1
 
System Versions:
           dist: SuSE 42.2 x86_64
        machine: x86_64
        release: 4.4.49-16-default
         system: Linux
        version: openSUSE  42.2 x86_64
```
It is also broken in 2016.3

**Comment by gtmanfred** [comment] 2017-03-22 15:21
Thanks for reporting this, I have been able to replicate this with the following docker container `gtmanfred/issues:40219`

```
$ docker run -ti gtmanfred/issues:40219 salt-call state.apply test
[ERROR   ] org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[ERROR   ] Only one of "pkgs" and "sources" is permitted.
local:
----------
          ID: install nginx
    Function: pkg.installed
      Result: False
     Comment: Only one of "pkgs" and "sources" is permitted.
     Started: 15:19:25.548815
    Duration: 0.574 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.574 ms
```

@terminalmage you might be interested in this.

In the end if you use state_aggregate with the pkg states, you will need to use only sources: or only pkgs:, because it would otherwise combine the two, which is not allowed.  But right now, it is not possible to use all sources: with this state.

Thanks,
Daniel

**Comment by terminalmage** [comment] 2017-03-23 18:13
This is fixed in #40265. The issue is that mod_aggregate wasn't considering ``sources`` _at all_. It first looks at ``pkgs`` and then at ``name``. Since ``pkgs`` is not present, it adds the ``name`` value (which in this case is the ID declaration, ``install nginx``) as the ``pkgs`` parameter. The result is that mod_aggregate rewrites the low data for that state such that it contains both ``pkgs`` and ``sources``.

The solution is to aggregate ``name``/``pkgs`` and ``sources`` separately.

The PR also fixes a separate issue with aggregation that I identified in the course of my troubleshooting.

**Comment by Azidburn** [comment] 2017-03-29 13:43
I've tested the PR in 2016.11. Looks OK for me.

**Comment by terminalmage** [comment] 2017-03-29 13:51
Thanks for following up! I'll go ahead and close this.

Thank you for bringing this to our attention and helping us get it fixed.

**Closed by terminalmage** 2017-03-29 13:51 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P2, Platform, State Module, TEAM Platform
