### ISSUE TITLE
Question: Compile SLS file externally

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#21662] opened 2015-03-14 14:58 UTC
I have a question. according to saltstack documentation, there is alot of its functions which have "name" parameter. like cmd.run or pkg.installed for example.
lets say i wrote a state , it may have yaml only , or jinja and yaml.

What if i wanted to ensure that my state is following some of standards (as a start). like all functions must use "name:" parameter.

I guess the sls file should be parsed to json to be able to check the keys and values to search for my desired parameter which is "name" in this case, am i right ?

Now how i could parse an sls file if it contains jinja to yaml in order to parse the yaml result into json ?? is there some method provided by saltstack api makes me able to get yaml from sls ?

I am trying some lint for my own standards in writing formulas along with saltstack standards.

**Comment by cachedout** [comment] 2015-03-14 18:16
The functions in ``salt.template`` should get you started. Take a look at ``salt.template.compile_template()``

https://github.com/saltstack/salt/blob/develop/salt/template.py#L29

**Comment by Code-Vortex** [comment] 2015-03-14 19:01
thanks  for your replay, in order to get started could you tell me what params should be pass ?

```
from salt.template import compile_template

compile_template("sls","jinja",sls="file.sls")
```
but its not working i got empty {}


another question about saltenv='base', should the base be /srv/salt ? or if i use my script inside /home/usrname/test, so this will be the saltenv in this case ?

**Comment by Code-Vortex** [comment] 2015-03-15 00:53
I have tried the following 

```python
 import salt.renderers
from salt.template import *

print compile_template("/srv/salt/test.sls", salt.renderers, "yaml_jinja")
```
I am getting an error

```
Traceback (most recent call last):
  File "syntax-checker.py", line 6, in <module>
    print compile_template("/srv/salt/test.sls", salt.renderers, "yaml_jinja")
  File "/usr/lib64/python2.6/site-packages/salt/template.py", line 65, in compile_template
    render_pipe = template_shebang(template, renderers, default)
  File "/usr/lib64/python2.6/site-packages/salt/template.py", line 143, in template_shebang
    render_pipe = check_render_pipe_str(default, renderers)
  File "/usr/lib64/python2.6/site-packages/salt/template.py", line 185, in check_render_pipe_str
    results.append((renderers[name], argline.strip()))
TypeError: 'module' object is unsubscriptable
```

**Comment by Code-Vortex** [comment] 2015-03-15 03:28
@cachedout finally I made it work with sls files which contains yaml only, for some reason if there is any jinja syntax and I don't know what I should do in order to make it compile jinja if any jinja syntax are there like import or set or if conditions and so on....
Here is my current progress 

```python
# -*- coding: utf-8 -*-
import salt.template as t
import salt.renderers
import salt.loader
import salt.config
import json
import sys
state = sys.argv[1]
opts = salt.config.master_config('whatever, just load the defaults!')
r = salt.loader.render(opts, {})

result = t.compile_template(state, r,"yaml_jinja")

print json.dumps(result, sort_keys=True, indent=4)
```

**Comment by Code-Vortex** [comment] 2015-03-16 18:13
@jfindlay am i facing an issue with salt which will be fixed or there is a way to compile an sls file which have jinja syntax to json like i did with yaml ? 

i tried to figure it out but i couldn't help appreciated. thanks

**Comment by jfindlay** [comment] 2015-03-16 18:22
@Code-Vortex, I haven't had time to learn all of salt's features yet, so I can't say for sure.  Either @cachedout or @basepi would know, or would be able to figure out what the expected behavior here is.

**Comment by basepi** [comment] 2015-03-17 22:18
Hey @Code-Vortex, you might consider trying `salt 'myminion' state.show_sls myslsfile`. This will compile the specified sls file (leave off the `.sls` extension when you run this), and it will show you the compiled highstate data. It does a little more work than just converting the jinja/yaml to a data structure, but since this is the actual data that salt looks at and executes, it could be very useful for your linting.

**Closed** 2016-07-16 19:49 UTC
Labels: Pending Discussion, Question
