### ISSUE TITLE
Salt-call return code 0 when minions key is rejected

### ISSUE THREAD

**Issue by jyurdal** [saltstack/salt#45706] opened 2018-01-26 09:25 UTC
Hej,
The salt-call  on linux returns 0 (both with and without --retcode-passthrough) when the master reject minions key. Error message is printed but the call itself does not print any error neither does it return errorcode. This makes it difficult to verify from the script whether command was successful or not. Is there something I am missing in here. I would imagine that passing --retcode-passthrough would return value other then 0 if the command was not successful for any reason (satlt-call failure, connection failure, keys rejected, sls error).
It does return False on Windows but it returns 0 on Centos.

I am running salt-minion 2017.7.2 (Nitrogen) on Centos.
Greetings
/Joanna

**Comment by gtmanfred** [comment] 2018-01-26 17:10
This is a duplicate of https://github.com/saltstack/salt/issues/18562

which is a duplicate of https://github.com/saltstack/salt/issues/18510

`--retcode-passthrough` only passes through the retcode from all the cmd.run stuff in salt-call if there are retcode errors in a state run. 
```
--retcode-passthrough
Exit with the salt call retcode and not the salt binary retcode
```

**Closed by gtmanfred** 2018-01-26 17:10 UTC
