### ISSUE TITLE
pkg.installed rpm-package from salt-source wrongly reports as failed

### ISSUE THREAD

**Issue by mninform** [saltstack/salt#29978] opened 2015-12-23 15:45 UTC
Hi,

on a Centos  7.1.1503, using salt-master 2015.8.1 on server and salt-minion 2015.8.0, we apply this state to the minion:

    [root@deploy oracle]# cat instantclient12102.sls
    instantclient12102:
        pkg.installed:
          - sources:
            - basic: salt://oracle/oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
Package is being installed, all files present:

     [root@SALTSTACK-CE7 ~]# yum list installed
     oracle-instantclient12.1-basic.x86_64
                                     12.1.0.2.0-1                     @/oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64

The message returned on salt-master is, *however*:
    
    SALTSTACK-CE7:
    ----------
              ID: instantclient12102
        Function: pkg.installed
          Result: False
         Comment: The following packages failed to install/update: sqlplus, basic
         Started: 18:16:19.376263
        Duration: 9577.44 ms
         Changes:
                  ----------
                  oracle-instantclient12.1-basic:
                      ----------
                      new:
                          12.1.0.2.0-1
                      old:
                  oracle-instantclient12.1-sqlplus:
                      ----------
                      new:
                          12.1.0.2.0-1
                      old:
    
    Summary for SALTSTACK-CE7
    ------------
    Succeeded: 0 (changed=1)
    Failed:    1
    ------------

A second run returns the failed state also.

    [root@gs3-deploy-ict ~]# salt 'GS3-SALT*' state.apply oracle.instantclient12102salt
    GS3-SALTSTACK-CE7.:
    ----------
              ID: instantclient12102salt
        Function: pkg.installed
          Result: False
         Comment: The following packages failed to install/update: basic
         Started: 16:35:40.939307
        Duration: 4959.903 ms
         Changes:
    
    Summary for GS3-SALTSTACK-CE7.
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1
    Total run time:   4.960 s

Any local installation on the client using yum or rpm is working flawless. Something wrong?
### Minion's test.versions_report
     [root@gs3-deploy-ict salt]# salt GS3-SALTSTACK-CE7 test.versions_report
     GS3-SALTSTACK-CE7:
        Salt Version:
                   Salt: 2015.8.0
    
        Dependency Versions:
                 Jinja2: 2.7.3
               M2Crypto: Not Installed
                   Mako: Not Installed
                 PyYAML: 3.11
                  PyZMQ: 14.7.0
                 Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
                   RAET: Not Installed
                Tornado: 4.2.1
                    ZMQ: 4.0.5
                   cffi: Not Installed
               cherrypy: Not Installed
               dateutil: Not Installed
                  gitdb: Not Installed
              gitpython: Not Installed
                  ioflo: Not Installed
                libnacl: Not Installed
           msgpack-pure: Not Installed
         msgpack-python: 0.4.6
           mysql-python: Not Installed
              pycparser: Not Installed
               pycrypto: 2.6.1
                 pygit2: Not Installed
           python-gnupg: Not Installed
                  smmap: Not Installed
                timelib: Not Installed
    
        System Versions:
                   dist: centos 7.1.1503 Core
                machine: x86_64
                release: 3.10.0-229.14.1.el7.x86_64
                 system: CentOS Linux 7.1.1503 Core

Attached see also the debug output from the minion.

[debug-output-initial-install.txt](https://github.com/saltstack/salt/files/70951/debug-output-initial-install.txt)
[debug-output-run2.txt](https://github.com/saltstack/salt/files/70952/debug-output-run2.txt)

**Comment by cachedout** [comment] 2015-12-23 16:26
Hmm, this is interesting. It would be nice if there were timestamps in the logs but even with them, I'm not sure what is going on here.

@terminalmage Do you have any insight on this one?

**Comment by whytewolf** [comment] 2015-12-23 19:20
this doesn't look like a bug but a failure in document reading. in sources the package is referred to as basic. but the yum package name is oracle-instantclient12.1-basic. and as part of the document for sources says "refer to the name of the package, as it would appear in the output of the pkg.version or pkg.list_pkgs salt CLI commands"

**Comment by terminalmage** [comment] 2015-12-28 04:07
@whytewolf is correct, this is simply incorrect usage. The following SLS should allow the state to complete successfully:

```
instantclient12102:
    pkg.installed:
      - sources:
        - oracle-instantclient12.1-basic: salt://oracle/oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
```

**Comment by cachedout** [comment] 2015-12-30 19:43
Looks like this is expected behavior so I'm closing this issue. If further discussion is needed, feel free to leave a comment and we will re-open it. Thanks.

**Closed by cachedout** 2015-12-30 19:43 UTC
Labels: Expected Behavior, Platform

**Comment by zksfyz** [comment] 2016-06-19 07:16
good!
