### ISSUE TITLE
States that may cause changes treated as failing when failhard=True and test=True

### ISSUE THREAD

**Issue by moloney** [saltstack/salt#34801] opened 2016-07-20 01:17 UTC
If you set `failhard: True` on a state, and then try to test a highstate run with `test=True` it will failhard if that state may cause changes. 

As a simple example add this state to your config:

```refresh_pillars:
  module.run:
    - name: saltutil.refresh_pillar
    - order: 1
    - failhard: True
```
Then try to do a highstate with `test=True`. Only this first state will be tested because it seems to treat any changes as a failure.

```
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-22-generic
         system: Ubuntu 16.04 xenial
```

**Comment by morganwillcock** [comment] 2016-07-20 15:58
I have the same issue and found it already discussed here #13635. I'm currently using template rendering to work around it (to ensure valid YAML you have to make use of Jinja whitespace stripping).
<pre>pkg.refresh_db:
{%- if opts['test'] %}
  module.run
{%- else %}
  module.run:
    - failhard: True
{%- endif %}</pre>
It would be nice to not have to do this.

**Comment by rallytime** [comment] 2016-07-20 16:26
@morganwillcock Thanks for finding the other issue and for posting your work around! I'm going to add it to the other issue.

@moloney Since this is a duplicate of #13635, I am going to close this one. Please use the earlier issue to track the progress of this bug. I am going to change the labels on the other issue from `feature` to `bug` and hopefully we can get some more eyes on it.

**Closed by rallytime** 2016-07-20 16:26 UTC
Labels: Duplicate
