### ISSUE TITLE
SaltMinion service startup fails in RHEL 7.9 with CIS benchmark enabled host

### ISSUE THREAD

**Issue by vtotappanava** [saltstack/salt#61611] opened 2022-02-09 14:46 UTC
### SaltMinion service startup fails in RHEL 7.9 with CIS benchmark enabled host
We had a customer issue where salt minion startup was abruptly stopping without any error message in log file as one of the system files did not have read permission. Customers environment is RHEL 7.9 with CIS benchmark standards was applied on it. Though the regular RHEL does not have this file, thinking should be created because of CIS patch (yet to get confirmation from customer on this).
 
File in question was “/etc/machine-id”.
After giving read permission to this file, everything worked perfectly fine.
 
This is the error seen when trying to start salt minion manually.
PermissionError: [Error 13] Permission denied: '/etc/machine-id'
<img width="1064" alt="image001" src="https://user-images.githubusercontent.com/79497530/153224862-6d299f2c-3610-4ae7-9949-1e054f39b9d5.png">
 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
 3002.5 (Opensource Salt)

**Comment by dmurphy18** [comment] 2022-02-09 17:27
@vtotappanava By default the permissions on that file in RHEL 7 / Centos 7 has read permissions, for example:
```
david@tc7:~$ ls -alh /etc/machine-id 
-r--r--r--. 1 root root 33 Aug 18  2020 /etc/machine-id
david@tc7:~$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
david@tc7:~$ 
```
This raises the question: what did they do to the file on the machine previously to change the default permissions.

Note checked with Centos 9 and the defaults are the same, read-only permissions.

**Comment by dmurphy18** [comment] 2022-02-09 22:15
@vtotappanava RHEL 7.9 Server
```
david@Unknown:~$ ls -alh /etc/machine-id 
-r--r--r--. 1 root root 33 Feb  9 10:55 /etc/machine-id
david@Unknown:~$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
david@Unknown:~$ 
```
on RHEL 7.9 without Salt
```
[root@Unknown david]# ls -alh /etc/machine-id 
-r--r--r--. 1 root root 33 Feb  9 13:41 /etc/machine-id
[root@Unknown david]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)
[root@Unknown david]#
```

After installing Salt 3002.5
```
[root@Unknown david]# salt-call --local test.version
local:
    3002.5
[root@Unknown david]# ls -alh /etc/machine-id 
-r--r--r--. 1 root root 33 Feb  9 13:41 /etc/machine-id
[root@Unknown david]# 
```

With the latest Salt  3004 installed, no difference
```RHEL 7.9 Server
```
david@Unknown:~$ ls -alh /etc/machine-id 
-r--r--r--. 1 root root 33 Feb  9 10:55 /etc/machine-id
david@Unknown:~$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
david@Unknown:~$ 
```
on RHEL 7.9 without Salt
```
[root@Unknown david]# ls -alh /etc/machine-id 
-r--r--r--. 1 root root 33 Feb  9 13:41 /etc/machine-id
[root@Unknown david]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)
[root@Unknown david]#
```

After installing Salt 3002.5
```
[root@Unknown david]# salt-call --local test.version
local:
    3002.5
[root@Unknown david]# ls -alh /etc/machine-id 
-r--r--r--. 1 root root 33 Feb  9 13:41 /etc/machine-id
[root@Unknown david]# 
```

With the latest Salt  3004 installed, no difference
```
[root@Unknown david]# ls -alh /etc/machine-id 
-r--r--r--. 1 root root 33 Feb  9 13:41 /etc/machine-id
[root@Unknown david]# salt-call --local test.versions
local:
    Salt Version:
              Salt: 3004
     
    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: Not Installed
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.1
           libgit2: Not Installed
          M2Crypto: 0.35.2
              Mako: Not Installed
           msgpack: 1.0.3
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: Not Installed
            pygit2: Not Installed
            Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
      python-gnupg: Not Installed
            PyYAML: 3.13
             PyZMQ: 17.0.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.1.4
     
    System Versions:
              dist: rhel 7.9 Maipo
            locale: UTF-8
           machine: x86_64
           release: 3.10.0-1160.53.1.el7.x86_64
            system: Linux
           version: Red Hat Enterprise Linux Server 7.9 Maipo
     
[root@Unknown david]# 
```
Note the correct way to provide the version of Salt that is running, as it provides more than just the version of Salt which is important.  This can be provided by running salt-run --versions-report on the Master, or salt <minion_id> test.versions, or as above with salt-call.

I want to close this issue since the problem is in the customer's environment where someone or something changed the permissions on /etc/machine-id, but it was not open Salt.

BTW: Salt 3002.5 is no longer supported and would advise to upgrade to a later version of Salt, which contains the most recent CVE fixes.

**Comment by vtotappanava** [comment] 2022-02-10 04:29
This is not an issue with RHEL 7.9. The customer had CIS Benchmark changes done on top of the regular RHEL and that is when the file permission may have got changed.
In any case the reason for me raising bug is that Salt Minion before crashing should have dumped some error message saying that the issue is because of machine-id file not having read permission than abruptly stopping. I dont know what is this file used for but in my case salt minion works even if this file is not present. So you may need to handle this in your code.

https://srviewer.vmware.com/sfdc-scripts/4/022/298/092/901/
This is the vmdk file that I got from customer. If you can access it, create a vm from this and you will hit the issue.

**Comment by dmurphy18** [comment] 2022-02-10 16:43
I think we have the wrong team handling this.  I was showing that Salt on RHEL 7.9 / Centos 7 does not manipulate the permissions on /etc/machine-id, did not imply there was anything wrong with RHEL 7.9, but stating that in the customers environment something changed the permissions on that file but it was not Open Salt.

The Open Salt Team only accesses the contents of /etc/machine-id to report the value in grains, item _**machine_id**_ .  The only other time that value is utilized is with use of Vagrant, reboot management control, or first boot parameters with systemD, these would all be set by the customer's use of Salt states/execution modules, and from what you have presented, this is not the case here (and the use is in the contents of the file).

Open Salt does not make use of CIS, that is another team on the SSC / vRA side of things, and perhaps the best thing to do is move it to that team which is familiar with use of CIS.

**Comment by dmurphy18** [comment] 2022-02-10 23:29
@vtotappanava @dstoliker Thank you Del missed that, so re-looked at original comment
```
Though the regular RHEL does not have this file, thinking should be created because of CIS patch (yet to get confirmation from customer on this).

File in question was “/etc/machine-id”.
```

Centos and RHEL **DO** have /etc/machine-id by default.  Hopefully this is due to a mis-spoke, otherwise someone/something removed this file from the system, and it is highly unlikely to be CIS or Salt.  That is, highly suspect someone messed up their system.

**Comment by dmurphy18** [comment] 2022-04-14 20:28
@joechainz I see no movement on this and I'd like to close it out as not reproducible, or have it moved out of Salt area and into Content Teams bug handling, since this is not related to Salt.

**Comment by dmurphy18** [comment] 2022-04-14 20:58
Closing since no further information after consulting with Content Team

**Closed by dmurphy18** 2022-04-14 20:58 UTC
Labels: cannot-reproduce, info-needed, Phosphorus v3005.0
