### ISSUE TITLE
TemplateNotFound/Unable to cache file

### ISSUE THREAD

**Issue by Ashald** [saltstack/salt#36121] opened 2016-09-07 17:51 UTC
### Description of Issue

While running Salt we noticed master becoming "broken" after some period of time - it starts failing on every single operation. While looking into this issue we noticed that at some point Salt master processes log an error like:

```
Exception trying to compile reactions: 'bool' object has no attribute 'rfind'
Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/reactor.py", line 180, in reactions
    high.update(self.render_reaction(fn_, tag, data))
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/reactor.py", line 63, in render_reaction
    for fn_ in glob.glob(glob_ref):
  File "/opt/python-2.7env/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/opt/python-2.7env/lib/python2.7/glob.py", line 38, in iglob
    dirname, basename = os.path.split(pathname)
  File "/opt/salt/lib/python2.7/posixpath.py", line 85, in split
    i = p.rfind('/') + 1
AttributeError: 'bool' object has no attribute 'rfind'
```

or

```
Rendering exception occurred: Jinja error: service/generic/macros/fleet.jinja
Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/templates.py", line 366, in render_jinja_tmpl
    output = template.render(**decoded_context)
      File "/opt/salt/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
        return self.environment.handle_exception(exc_info, True)
      File "/opt/salt/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "<template>", line 1, in top-level template code
      File "/opt/salt/lib/python2.7/site-packages/salt/utils/jinja.py", line 144, in get_source
        raise TemplateNotFound(template)
        TemplateNotFound: service/generic/macros/fleet.jinja

    ; line 1

    ---
    {%- from 'service/generic/macros/fleet.jinja' import fleet_path %}    <======================

    [...]
    ---
Failed to render "/var/cache/salt/master/files/base/service/generic/reactor/scale.sls": 
Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/reactor.py", line 68, in render_reaction
    data=data)
  File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 304, in render_template
    template, self.rend, self.opts['renderer'], **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/renderers/jinja.py", line 69, in render
    **kws)
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/templates.py", line 413, in render_jinja_tmpl
    trace=tracestr)
    SaltRenderError: Jinja error: service/generic/macros/fleet.jinja
Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/templates.py", line 366, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/opt/salt/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/salt/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/jinja.py", line 144, in get_source
    raise TemplateNotFound(template)
    TemplateNotFound: service/generic/macros/fleet.jinja

; line 1

---
{%- from 'service/generic/macros/fleet.jinja' import fleet_path %}    <======================


[...]

---
```

It looks like that after some event the process becomes "broken" and once it's broken it cannot render any template and fails with similar error each time.

After some debugging we noticed that those failures occur when `salt.utils.jinja.SaltCacheLoader` is given such `opts` that `opts['file_roots'] == opts['pillar_roots']` while it's sued to render a Jinja formula rather than pillar (we using only external pillars - no file system pillars at all).

That's all we sure about. From here - only guesses.
Our theory is that at some point some kind of failure occurs while reactor executes compiled reactions (every now and then we see `tcp stream to 192.168.2.15:4506 closed, unable to recv` in minion logs - maybe that's the reason for those failures?) and since then master becomes "broken". Maybe there are some modules that patch `file_roots` and do not restore the correct value in case of failure?... But that's only a guess.
### Setup

Master config:

```
transport: tcp

worker_threads: 30
timeout: 120

file_roots:
  base:
    - /etc/salt/files/sys
    - /etc/salt/files/v2
```
### Steps to Reproduce Issue

Out "sure" way to reproduce the issue is to restart many minions at once - once they're connected to master it uses reactor to enforce some states on them.
### Versions Report

We witnessed the issue on all `2016.3.*` versions.

```
$ ./salt-master --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 5.4.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Apr  5 2016, 13:41:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment] 2016-09-08 16:36
@Ashald i'm wondering if this is related to #29670 It looks like in that issue the user just had the wrong name for a reactor file and had to update to the path to the correct reactor file name. Can you ensure these are all correct? Also it looks like that jinja error is essentially stating that `service/generic/macros/fleet.jinja` does not exist. Can you also make sure this does exist?

Now if this indeed seems to be the resolution we still will want to add  a more useful error and not cause the master to turn into an unusable state. Or maybe you will correct me and this is not the reason. Thanks

**Comment by Ashald** [comment] 2016-09-08 16:48
@Ch3LL not, the file does exist for sure and the path is correct. We starting a master and everything works just fine. But after some time (our sure way to reproduce - restart few dozens of minions so they start talking to master more or less simultaneously) this error appears and once it appeared for the 1st time all subsequent reactor-based actions (that involve Jinja formulas) are failing. As I mentioned in original description we were able to track that down to the fact that error appears when `salt.utils.jinja.SaltCacheLoader` is initialized with wrong `opts` - such where `opts['file_roots']` is set to a copy of `opts['pillar_roots']` when trying to render non-pillar Jinja sls.

**Comment by Ashald** [comment] 2016-09-08 16:52
My guess is that we need to look for a reason why `salt.utils.jinja.SaltCacheLoader` could be initialized with "broken `opts`" within reactor process. Maybe something patches `opts` (I saw something similar within code related to Pillar rendering - it was assigning `opts['file_roots'] = opts['pillar_roots']`) but fails to un-patch that? Or, if multi-threading involved, maybe the issue in sharing` __opts__` between multiple threads while modifying it.

**Comment by kmt** [comment] 2016-09-08 23:32
This was marked as `Info needed` prior to @Ashald 's answers.  @Ch3LL do you need more info?

**Comment by Ch3LL** [comment] 2016-09-09 19:39
Thanks for the additional information @Ashald and i don't think we need more info at this point. I believe the line you are referring to concerning where file_roots does become pillar roots is [here](https://github.com/saltstack/salt/blob/develop/salt/pillar/__init__.py#L321) which I'm assuming is where the Pillar class is called when looking up pillar values. I want to get @terminalmage 's input here since he is more knowledgeable in this area. @terminalmage it looks like you have done a lot of the code in the SaltCacheLoader where it compares the opts do you see why they might be running into this issue or any follow questions? Thanks

**Comment by terminalmage** [comment] 2016-09-09 20:17
@Ashald The assignment you are referring to is performed on a deepcopy of the opts, as seen [here](https://github.com/saltstack/salt/blob/98767d5/salt/pillar/__init__.py#L343-L344).

**Comment by kmt** [comment] 2016-10-18 15:38
Would this be assigned and looked into sometime soon?  It's still a problem for us and it's not something we can address ourselves at this point.

**Comment by chrismcmacken** [comment] 2017-01-04 18:30
We are also seeing this issue on the latest stable, version `2016.11.1`, rendering reactor states via the salt file system seems to cause the issue. If I put absolute paths in the reactor configuration instead of using the salt file system it seems to work fine.

**Comment by terminalmage** [comment] 2017-01-04 20:52
Thus far no one has provided an example reactor configuration that can be used to reproduce this, and I've not been able to reproduce it on my own.

@chrismcmacken when you say "rendering reactor states via the salt file system", what exactly do you mean by that? Do you mean that the paths to the reactor SLS files are salt fileserver paths? Something like this:

```
reactor:
  - 'some_tag':
    - salt://path/to/reactor.sls
```

**Comment by chrismcmacken** [comment] 2017-01-04 20:59
@terminalmage Yes, exactly that. The reactor files work correctly for some amount of time after the salt-master initially starts up but eventually they start to fail with the unable to cache / find file error posted above. 

I will try to take some time to post simple configurations that reproduce the issue in the next couple of days.

**Comment by terminalmage** [comment] 2017-01-04 21:22
OK, I configured a test environment with a reactor configuration pulling from a ``salt://`` URL, and still can't reproduce. I don't disbelieve you, I just need to get a reproducible case so that I can see what is going wrong.

**Comment by chrismcmacken** [comment] 2017-01-18 19:34
@terminalmage I've spent a few hours configuring basic test environments with reactors / beacons and haven't been able to reproduce the issue outside of our actual salt instances. We run salt-master as a non-root user and have a large number of states / pillars so I'm guessing it has something to do with that but haven't found a concrete way to reproduce it yet.

**Comment by terminalmage** [comment] 2017-01-23 04:20
I took a look at the potential code paths that may have caused this and I think that, even though I haven't been able to reproduce it, I have found the likely cause of the traceback. See pull request #38875.

**Comment by chrismcmacken** [comment] 2017-01-23 15:44
That does look like it could cause the issue. Thanks for taking a look at it. I will post back if I see the issue again after upgrading to the fixed version

**Closed** 2017-02-06 23:32 UTC
Labels: Bug, Core, Critical, Fixed Pending Verification, P3, Reactor
