### ISSUE TITLE
File_tree ext_pillar doesn't work with nodegroup YAML list or N@ compound

### ISSUE THREAD

**Issue by akrus** [saltstack/salt#44437] opened 2017-11-08 09:41 UTC
### Description of Issue/Question
File_tree ext_pillar allows per-nodegroup directory, but this doesn't work if you have nodegroup specified as YAML list or N@ compound. Likely the problem is here:
https://github.com/saltstack/salt/blob/5bbbd106570918e82462c930de072a674d4219a8/salt/pillar/file_tree.py#L339-L341
Workaround is to add 'or' word between all the hosts in group, although it's still a bug.
For N@ there is no known workaround.

### Setup
With YAML list:
/etc/salt/master:
```
nodegroups:
  group1:
    - host1
    - host2
```
With N@:

/etc/salt/master:
```
nodegroups:
  group2: 'N@group1'
```
Both:
```
ext_pillar:
  - file_tree:
      root_dir: /srv/storage
      keep_newline: True
```
/srv/storage/nodegroups/group1/test.file

### Steps to Reproduce Issue
Execute salt 'host1' pillar.items, you'll see this error:
(with list):
[salt.utils.minions][ERROR   ][28360] Invalid compound target: ['host1', 'host2']
(with N@):
[salt.utils.minions][ERROR   ][16001] Detected nodegroup expansion failure of "group2"

salt -N group1 test.ping and salt -N group2 test.ping work fine.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-97-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment] 2017-11-08 15:05
I believe that the nested node group is known to not work for certain use cases

I believe that this issue is a duplicate of https://github.com/saltstack/salt/issues/42735 ?

Thanks,
Daniel

**Comment by akrus** [comment] 2017-11-08 15:13
@gtmanfred,
#42735 only described nested groups and not sure if it's exactly the same.
Here I have simple YAML list in first case which is not working as expected, but should according to docs.

**Comment by gtmanfred** [comment] 2017-11-08 15:43
Right, but I think that it is the same issue.  That the nodegroup list doesn't actually render correctly.

If you switch the first nodegroup to `L@host1,host2` The whole thing works correctly.

**Closed** 2017-11-08 15:43 UTC
Labels: Duplicate
