### ISSUE TITLE
pkgrepo.managed cannot download the gpg key

### ISSUE THREAD

**Issue by mochrul** [saltstack/salt#44264] opened 2017-10-24 19:57 UTC
### Description of Issue/Question

I have some servers controlled by salt. One of the state file controls the salt repository. It has been worked well until I added a new host (with the newest version of salt) and on this host, it is not able to download the gpg key related to the repository. This setup was working for the other hosts (installed earlier) but not for this host. Also I can download the gpg key with wget from the same host. And also I can see the communication with tcpdump, so it is not a connection issue.

### Setup
The state file contains the following:
```
saltstack:
  pkgrepo.managed:
    - humanname: SaltStack Repo
{% if grains['oscodename'] == 'trusty' %}
    - name: deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main
    - key_url:  https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub
{% elif grains['oscodename'] == 'xenial' %}
    - name: deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main
    - key_url:  https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
{% elif grains['oscodename'] == 'jessie' %}
    - name: deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main
    - key_url: https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub
{% endif %}
    - file: /etc/apt/sources.list.d/saltstack.list
    - gpgcheck: 1
```
### Steps to Reproduce Issue
Run salt-call state-highstate is the easiest way to reproduce it.

This can be found in the debug log:
```
[DEBUG   ] Requesting URL https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub using GET method
[INFO    ] Executing command ['apt-key', 'add', '/var/cache/salt/minion/extrn_files/base/repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub'] in directory '/root'
[ERROR   ] Command '['apt-key', 'add', '/var/cache/salt/minion/extrn_files/base/repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub']' failed with return code: 2
[ERROR   ] stderr: gpg: no valid OpenPGP data found.
[ERROR   ] retcode: 2
```

And the size of the cache file is 0:
```shell
# ls -l /var/cache/salt/minion/extrn_files/base/repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub
-rw-r--r-- 1 root root 0 Oct 24 21:41 /var/cache/salt/minion/extrn_files/base/repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub
```

Interestingly, if I strace the salt processes, I can see that the salt connect to the server, download the content but then do not save it to anywhere:
```
10360 open("/var/cache/salt/minion/extrn_files/base/repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub.part", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 93
[...]
10360 stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=230, ...}) = 0
10360 socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 96
10360 connect(96, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.2.1.12")}, 16) = 0
[...]
10360 socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 96
10360 fcntl(96, F_GETFL)                = 0x2 (flags O_RDWR)
10360 fcntl(96, F_SETFL, O_RDWR|O_NONBLOCK) = 0
10360 connect(96, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("198.199.77.106")}, 16) = -1 EINPROGRESS (Operation now in progress)
[...]
10360 poll([{fd=94, events=POLLIN}, {fd=96, events=POLLOUT}], 2, 299 <unfinished ...>
10360 <... poll resumed> )              = 1 ([{fd=96, revents=POLLOUT}])
10360 getsockopt(96, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
10360 getsockopt(96, SOL_SOCKET, SO_TYPE, [1], [4]) = 0
10360 getpeername(96, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("198.199.77.106")}, [16]) = 0
[...]
10360 write(96, "\26\3\1[...]
10360 read(96, 0x3cce000, 7)            = -1 EAGAIN (Resource temporarily unavailable)
10360 poll([{fd=94, events=POLLIN}, {fd=96, events=POLLIN}], 2, 0) = 0 (Timeout)
10360 poll([{fd=94, events=POLLIN}, {fd=96, events=POLLIN}], 2, 19869) = 1 ([{fd=96, revents=POLLIN}])
10360 read(96, "\26\3\3\0B\2\0", 7)     = 7
10360 read(96, "\0>\3\3Y\357\230\27\210?x\316`\332\244\315;\200\36\234\207\376H\231E\21\221b\6Aqr\215w=\257\0\300/\0\0\26\377\1\0\1\0\0\v\0\4\3\0\1\2\0#\0\0\0\17\0\1\1", 64) = 64
10360 read(96, "\26\3\3\r{", 5)         = 5
10360 read(96, "\v\0\rw\0\rt\0\5 0[...]
[...]
10360 write(96, "\27\3\3\0\262 \322\223\260]x\307\320J\252\231\315/\3667\323I\216a\24\\7h\303PI_\274\3\325\243\224\33\10{nk\201\201u\342\16>\246\243\3066\234\273\23\321\200\314\31\r\335\2k\257\367kT\270\240w\03105\266*@MB\365\371\24\225 \307\202\344>\216c\221\365\331\302\2Z\6\224\231m_G\233\336&L\242\344\347\4\227\316\7>O\37/\245\270r\317\377\257\31\36I\342\203!\274\334\226\177)x\323l\357\3060\277\260\272D\375\274\23\271\2250PU\346\313\215E\222\3344\352\314\316\215\31X\233\353-A\7\177\3\34(=\310 \221%\245M\\\2\203", 183) = 183
10360 setsockopt(96, SOL_TCP, TCP_NODELAY, [1], 4) = 0
10360 setsockopt(96, SOL_TCP, TCP_NODELAY, [0], 4) = 0
10360 brk(0x3d13000)                    = 0x3d13000
10360 read(96, 0x3cce003, 5)            = -1 EAGAIN (Resource temporarily unavailable)
10360 poll([{fd=94, events=POLLIN}, {fd=96, events=POLLIN}], 2, 0) = 0 (Timeout)
10360 poll([{fd=94, events=POLLIN}, {fd=96, events=POLLIN}], 2, 19615) = 1 ([{fd=96, revents=POLLIN}])
10360 read(96, "\27\3\3\7\312", 5)      = 5
10360 read(96, "J\2241\207\203GO\200\33r\207\3355&\234\250%,\206g\301\271\10\372\311\323\276I\225\2009fE\275Mw\316\341\266\312h\227|u\345qp\27\373\200\316\237\f\263y\303I\344\21\211\342\255,\277\244\271U\206\320\207\6\323\343\31\26\274y\3[...]
10360 stat("/usr/lib/python2.7/encodings/latin_1", 0x7ffdc8aa6de0) = -1 ENOENT (No such file or directory)
10360 open("/usr/lib/python2.7/encodings/latin_1.x86_64-linux-gnu.so", O_RDONLY) = -1 ENOENT (No such file or directory)
10360 open("/usr/lib/python2.7/encodings/latin_1.so", O_RDONLY) = -1 ENOENT (No such file or directory)
10360 open("/usr/lib/python2.7/encodings/latin_1module.so", O_RDONLY) = -1 ENOENT (No such file or directory)
10360 open("/usr/lib/python2.7/encodings/latin_1.py", O_RDONLY) = 97
10360 fstat(97, {st_mode=S_IFREG|0644, st_size=1264, ...}) = 0
10360 open("/usr/lib/python2.7/encodings/latin_1.pyc", O_RDONLY) = 98
10360 fstat(98, {st_mode=S_IFREG|0644, st_size=2291, ...}) = 0
10360 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4fd2238000
10360 read(98, "\3\363\r\n[...]
10360 fstat(98, {st_mode=S_IFREG|0644, st_size=2291, ...}) = 0
10360 read(98, "", 4096)                = 0
10360 close(98)                         = 0
10360 munmap(0x7f4fd2238000, 4096)      = 0
10360 close(97)                         = 0
10360 close(96)                         = 0
10360 poll([{fd=94, events=POLLIN}], 1, 0) = 0 (Timeout)
10360 poll([{fd=94, events=POLLIN}], 1, 0) = 0 (Timeout)
10360 write(95, "x", 1)                 = 1
10360 close(94)                         = 0
10360 close(95)                         = 0
10360 close(93)                         = 0
10360 rename("/var/cache/salt/minion/extrn_files/base/repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub.part", "/var/cache/salt/minion/extrn_files/base/repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub") = 0
```

### Versions Report
```shell
# salt-call --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-133-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment] 2017-10-25 18:57
This appears to be a duplicate of https://github.com/saltstack/salt/issues/44013

Daniel

**Closed by gtmanfred** 2017-10-25 18:57 UTC
