### ISSUE TITLE
salt-cloud tries to use $SHELL when proxying through aws cloud driver, this fails on Arch linux

### ISSUE THREAD

**Issue by cinterloper** [saltstack/salt#29347] opened 2015-12-02 22:26 UTC
in salt-cloud -ldebug when provisioning a aws machine:
[DEBUG   ] bash: No such file or directory

setting SHELL=/bin/bash solves the issue

**Comment by jtand** [comment] 2015-12-04 16:58
@cinterloper Are you provisioning an Arch Linux vm on AWS or using Arch Linux as your master?

**Comment by cinterloper** [comment] 2015-12-04 17:22
Both

**Comment by techhat** [comment] 2015-12-04 17:28
@cinterloper are you using the old `aws` driver or the new `ec2` driver? The `aws` driver should not be used.

**Comment by cinterloper** [comment] 2015-12-04 22:29
[ cloud.providers.d]$ cat /etc/issue
Arch Linux \r (\l)

[ cloud.providers.d]$ cat aws.conf | grep driver
  # driver for something other than Amazon EC2, change it here:
  driver: ec2

**Comment by pass-by-value** [comment] 2015-12-08 20:28
I tried with a public AMI and didn't get that specific error. I got a different error during bootstrap (shown below) which was resolved after doing a `pacman -Syu`

```shell
libx32-glibc: /libx32 exists in filesystem
Errors occurred, no packages were upgraded.
 * ERROR: Failed to run install_arch_linux_stable()!!!
```

I'm wondering if the AMI you are using is publicly available so I can test with it?

**Comment by pass-by-value** [comment] 2015-12-08 20:29
@cinterloper Please see my above comment, I forgot to tag you in that one.

**Comment by pass-by-value** [comment] 2015-12-17 16:36
@cinterloper Any luck with this?

**Comment by pass-by-value** [comment] 2016-01-11 16:53
Hi @cinterloper were you able to move forward with this? I am not able to reproduce this particular bug. Please let me know, would love to get this working for you.

**Comment by pass-by-value** [comment] 2016-01-19 20:45
Closing this for now. Pleas re-open if it is still an issue.

**Closed by pass-by-value** 2016-01-19 20:45 UTC
Labels: Bug, Cannot Reproduce, High Severity, P3, RIoT, Salt-Cloud, TEAM RIoT
