### ISSUE TITLE
salt.modules.cmdmod broken

### ISSUE THREAD

**Issue by antifob** [saltstack/salt#48480] opened 2018-07-08 02:15 UTC
### Description of Issue/Question

`cmdmod` is broken.

A bisect shows commit eaddf737f3a777fba34a2c213fc932ebd68caa21 introduced the problem.

### Setup

Same result in a virtualenv using pip-installed salt and current `develop` branch.

### Steps to Reproduce Issue
```
python -c 'import salt.modules.cmdmod'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "salt/modules/cmdmod.py", line 34, in <module>
    import salt.utils.templates
  File "salt/utils/templates.py", line 24, in <module>
    import salt.utils.http
  File "salt/utils/http.py", line 41, in <module>
    import salt.loader
  File "salt/loader.py", line 25, in <module>
    import salt.utils.event
  File "salt/utils/event.py", line 72, in <module>
    import salt.config
  File "salt/config/__init__.py", line 97, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "salt/config/__init__.py", line 87, in _gather_buffer_space
    import salt.grains.core
  File "salt/grains/core.py", line 46, in <module>
    import salt.utils.dns
  File "salt/utils/dns.py", line 47, in <module>
    'cmd.run_all': salt.modules.cmdmod.run_all
AttributeError: 'module' object has no attribute 'cmdmod'
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment] 2018-07-09 13:56
I am able to replicate this, but it also appears to happen in 2017.7.4, which was before that commit was merged.

```
[root@ebffcaaf40b9 /]# history
    1  yum install -y epel-release
    2  yum install -y python2-pip python-devel gcc git
    3  pip2 install -e git+git://github.com/saltstack/salt.git@develop#egg=salt
    4  history
[root@ebffcaaf40b9 /]# python -c 'import salt.modules.cmdmod'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/salt/salt/modules/cmdmod.py", line 34, in <module>
    import salt.utils.templates
  File "/src/salt/salt/utils/templates.py", line 32, in <module>
    import salt.utils.http
  File "/src/salt/salt/utils/http.py", line 40, in <module>
    import salt.config
  File "/src/salt/salt/config/__init__.py", line 97, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/src/salt/salt/config/__init__.py", line 87, in _gather_buffer_space
    import salt.grains.core
  File "/src/salt/salt/grains/core.py", line 51, in <module>
    import salt.utils.dns
  File "/src/salt/salt/utils/dns.py", line 58, in <module>
    'cmd.run_all': salt.modules.cmdmod.run_all
AttributeError: 'module' object has no attribute 'cmdmod'
```

None of the salt modules are meant to be imported outside of salt itself, but only loaded by the loader.

As a workaround, you can still load the cmdmod module using the loader.

```
>>> import salt.loader
>>> import salt.config
>>> opts = salt.config.minion_config('/etc/salt/minion')
>>> mods = salt.loader.minion_mods(opts, None, None, whitelist=['cmd'])
>>> mods['cmd.run_all']('ls')
{u'pid': 1284, u'retcode': 0, u'stderr': u'', u'stdout': u'anaconda-ks.cfg'}
```

Thanks,
Daniel

**Comment by gtmanfred** [comment] 2018-07-09 13:58
Also, if you do 

```
import salt.loader
import salt.modules.cmdmod
```
it works.

```
[root@ebffcaaf40b9 salt]# python -c 'import salt.loader, salt.modules.cmdmod'
[root@ebffcaaf40b9 salt]#
```
Because it doesn't have the circular dependency.

**Comment by gtmanfred** [comment] 2018-07-09 15:05
This is the expected behavior, you should be loading the cmdmod module using the loader, not directly importing it.

Thanks!
Daniel

**Closed by gtmanfred** 2018-07-09 15:05 UTC
Labels: Expected Behavior, Pending Discussion

**Comment by gerardjp** [comment] 2019-11-09 07:46
@gtmanfred Please explain how one ...

>  should be loading the cmdmod module using the loader

instead of importing. Thanks! :)

**Comment by gtmanfred** [comment] 2019-11-09 14:40
https://docs.saltstack.com/en/latest/ref/clients/#salt-s-loader-interface
