### ISSUE TITLE
Regarding Proxy process memory and CPU usage

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38990] opened 2017-01-27 12:56 UTC
### Description of Issue/Question

I'm afraid the proxy process consumes more than expected (I recall @cro said they would need ~40M of memory), but this is what I constantly see (in the `top`):

```yaml
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20134 root      20   0 1189492  85628  13764 S   0.3  0.1   2:03.23 salt-proxy
20224 root      20   0 1119728  89104  14256 S   0.3  0.1   2:15.44 salt-proxy
20241 root      20   0 1261148 103232  14044 S   0.3  0.1   2:25.58 salt-proxy
20413 root      20   0 1203788 111008  13676 S   0.3  0.1   2:36.26 salt-proxy
20419 root      20   0 1126996  83564  14108 S   0.3  0.1   2:10.13 salt-proxy
20434 root      20   0 1475828 142124  13676 S   0.3  0.1   4:21.18 salt-proxy
20479 root      20   0 1258680  92728  13980 S   0.3  0.1   2:13.64 salt-proxy
20480 root      20   0 1127228  85156  13812 S   0.3  0.1   2:03.96 salt-proxy
20523 root      20   0 1393708  95884  13932 S   0.3  0.1   2:48.58 salt-proxy
```

When doing a `sync_all`, the CPU usage spikes:

```yaml
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20704 root      20   0 1275184 102724  13848 S 108.3  0.1   4:29.43 salt-proxy
20950 root      20   0 1602884 216072  13888 S 105.7  0.2   8:01.68 salt-proxy
21039 root      20   0 1198564 149368  13956 S 103.7  0.1   9:59.86 salt-proxy
20954 root      20   0 1421144 132168  13968 S 103.1  0.1   5:53.28 salt-proxy
21044 root      20   0 1532552 169760  14052 S 103.1  0.1   7:46.55 salt-proxy
21648 root      20   0 1635956 154768  13924 S 103.1  0.1   7:05.68 salt-proxy
20643 root      20   0 1418324 154004  13812 S 102.7  0.1   5:20.54 salt-proxy
```

And the master:

```yaml
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
31491 root      20   0  430928  85244   8976 R  99.7  0.1   0:30.05 salt-master
 9231 root      20   0  431676  86072   8976 R  99.4  0.1   1:00.48 salt-master
```

I'm wondering if this could be a cause of https://github.com/saltstack/salt/issues/35443.

In a separate lab environment having 50 proxy processes started, I managed to replicate the modules disappearing:

```
[DEBUG   ] LazyLoaded localfs.contains
[DEBUG   ] LazyLoaded no_return.output
animal21:
    Minion did not return. [No response]
```

And the proxy is unable to start:

```python
2017-01-27 12:54:30,691 [salt.scripts     ][ERROR   ][7293] Proxy Minion failed to start:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 249, in proxy_minion_process
    proxyminion.start()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 515, in start
    super(ProxyMinion, self).start()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 948, in start
    self.prepare()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 481, in prepare
    if self.check_running():
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 925, in check_running
    pid = self.get_pidfile()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 897, in get_pidfile
    return get_pidfile(self.config['pidfile'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 134, in get_pidfile
    return int(pid)
ValueError: invalid literal for int() with base 10: ''
2017-01-27 12:54:30,692 [salt.scripts     ][WARNING ][7293] ** Restarting proxy minion **
```

Although there's still enough memory:

```yaml
top - 12:55:21 up  2:05,  2 users,  load average: 0.63, 0.78, 3.82
Tasks: 184 total,   1 running, 183 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.9 us,  0.5 sy,  0.0 ni, 95.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.2 st
KiB Mem:   4057568 total,  3022492 used,  1035076 free,    16348 buffers
KiB Swap:        0 total,        0 used,        0 free.   148144 cached Mem
```

Also, the `sync_all` in 2016.11 is much slower than in 2016.3.

### Salt Version

- production:

```yaml
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 10.0.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```

- lab:

```yaml
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Dec 18 2016, 20:19:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

**Comment by cro** [comment] 2017-02-02 15:51
@mirceaulinic I've been profiling the proxy minion today with the rest_sample proxy.  I see this memory consumption after a little activity:

```
root@ba941b7c693e:/# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/6562/smaps) | bc
64127
root@ba941b7c693e:/# echo 0 $(awk '/Rss/ {print "+", $2}' /proc/6562/smaps) | bc
72444
root@ba941b7c693e:/# echo 0 $(awk '/Shared/ {print "+", $2}' /proc/6562/smaps) | bc
9704
```

So essentially 64 MB per proxy minion, which is indeed an increase.  I suspect this is because we are now injecting `__utils__` and some other dunder dictionaries into the proxies--would those changes have been present in your copy?

Your proxy minions will likely take more memory because of the napalm functionality.

Re: time to sync_all, I don't see an appreciable difference between 2016.3, 2016.11, & develop, but I likely have far fewer modules in my file_roots than you.

I can profile this but I'm not sure if we can do anything about it, if indeed the extra memory is from `__utils__` and the other dunders.

**Comment by mirceaulinic** [comment] 2017-02-02 16:01
Hi @cro  - thanks very much for looking into this.

> I suspect this is because we are now injecting __utils__ and some other dunder dictionaries into the proxies--would those changes have been present in your copy?

No, the above was taken from the production box still running 2016.11.0 (which does not have the changes from https://github.com/saltstack/salt/pull/38900, if I understand you correctly).
My proxies are SSH-based.. some using ncclient on top of paramiko. I'm wondering if this could add the extra overhead at all.

> Your proxy minions will likely take more memory because of the napalm functionality.

Yes, I have thought about that too.

> I can profile this but I'm not sure if we can do anything about it

No problem at all, even 150MB would not be that detrimental. I am more concerned about the CPU usage, is it acceptable the usage spike when refreshing the grains or doing `sync_all`? I know there are are many things to be refreshed in the cache during `sync_all`, but is it that heavy?
Please note that I am also seeing this spike every 5 minutes when the mines are refreshed in background (as specified in the `mine_interval`).

**Comment by mirceaulinic** [comment] 2017-03-09 02:14
I did the same as above and the proxies consume much more (again this might be related to napalm):

```
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/15798/smaps) | bc
140681
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/15798/smaps) | bc
140681
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/15798/smaps) | bc
140681
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/15798/smaps) | bc
140681
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/15798/smaps) | bc
140681
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/30343/smaps) | bc
235727
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/30343/smaps) | bc
235727
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/30343/smaps) | bc
235727
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/30343/smaps) | bc
235727
root@salt-master:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/30343/smaps) | bc
235727
root@salt-master:~#
```

15798 and 30343 are the child processes of two proxies started some time ago (a couple of weeks maybe).

At the same time, in a lab, a fresh napalm proxy process (running the code from develop tho):

```
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
59820
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
59824
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
59824
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
59824
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
59824
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
59824
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
59824
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
60676
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
60676
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
60676
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
61556
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
61556
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
61800
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
61800
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
```

 I will leave them running and see if indeed the consumption goes up -- at a glance it would suggest so.

**Comment by mirceaulinic** [comment] 2017-03-09 10:58
I let the lab running overnight (without having jobs scheduler etc. - just the process being up):

```
root@ip-172-31-13-136:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
70160
root@ip-172-31-13-136:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
70160
root@ip-172-31-13-136:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
70161
root@ip-172-31-13-136:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
70160
root@ip-172-31-13-136:~# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/24870/smaps) | bc
70160
root@ip-172-31-13-136:~#
```

Which shows an increase of 10MB over several hours. At this point I am still not sure if it's because of the proxy itself, or the connection to the network device.

**Comment by mirceaulinic** [comment] 2017-03-09 11:02
For the sake of testing, I am running now the code from https://github.com/saltstack/salt/pull/39896 specifying the `always_alive: false` option which spawns a new connection when a CLI command is executed (somehow similar to the regular minion), but the process itself is always up. This perhaps will give us some more input. For the beginning, these are the values:

```
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/27850/smaps) | bc
59758
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/27850/smaps) | bc
59758
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/27850/smaps) | bc
59758
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/27850/smaps) | bc
59758
root@ip-172-31-13-136:/etc/salt/pillar# echo 0 $(awk '/Pss/ {print "+", $2}' /proc/27850/smaps) | bc
59758
root@ip-172-31-13-136:/etc/salt/pillar#
```

**Comment by cro** [comment] 2017-03-09 21:16
Good data to have.  Thank you.

**Comment by aplanas** [comment] 2019-08-13 16:59
I want to check this a bit. Do you have an easy way to reproduce the issue?

**Comment by mirceaulinic** [comment] 2019-08-13 17:20
Yes, start any SSH-based proxy minion (either [junos](https://docs.saltstack.com/en/latest/ref/proxy/all/salt.proxy.junos.html), [napalm](https://docs.saltstack.com/en/latest/ref/proxy/all/salt.proxy.napalm.html) or [netmiko](https://docs.saltstack.com/en/latest/ref/proxy/all/salt.proxy.netmiko_px.html), etc.) and execute 100 commands, 1000 commands and so on while checking the memory footprint. I've seen it growing to absurd values.

**Comment by TheBirdsNest** [comment] 2021-06-07 13:44
Hi,

Has there been any movement on this bug? I am running 1500 proxy minions on my hosts and there seems to be some form of memory leak or something. Multiprocessing is disabled and the proxy is not persistent (keep_alive: False).

@mirceaulinic would you say this is the same as what you are seeing?

![image](https://user-images.githubusercontent.com/31070227/121027446-deb38800-c79e-11eb-94a3-422f162af899.png)
![image](https://user-images.githubusercontent.com/31070227/121027507-ebd07700-c79e-11eb-9668-5ce90aa7d348.png)

**Comment by mirceaulinic** [comment] 2021-06-07 21:18
Yes, the memory leak in the Proxy Minions has never been resolved. It _seems_ a little better in the most recent Salt versions (I'm running 3002.5), especially if you disable anything using `schedule` (that is, disable mines, disable keep alive, everything). We ended up writing an internal tool that restarts the PMs gracefully when they're about to hit a certain mem usage (like a PM manager) but that's definitely not the way it should be.
For some specific parts of the network (such as OOB, or console servers) we're now using [salt-sproxy](https://github.com/mirceaulinic/salt-sproxy) (in case you didn't see it already) as we don't necessarily need to have always running PMs for those, rather on-demand execution (and no memory leak :stuck_out_tongue:). HTH!

**Comment by dmurphy18** [comment] 2023-09-05 21:50
@mirceaulinic Closing this due to age, the old version of Salt and Python 2 that the issue was originally run on.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.

There have been a number of memory leak fixes recently.

**Closed by dmurphy18** 2023-09-05 21:50 UTC
Labels: Bug, severity-medium, Confirmed, RIoT, Proxy-Minion, Performance
