### ISSUE TITLE
docker_image.present fails first time when python3-docker module is installed

### ISSUE THREAD

**Issue by golpa** [saltstack/salt#54449] opened 2019-09-10 20:53 UTC
### Description of Issue
I'm trying to use `docker_image.present` but salt fails to detect the module on first `state.apply` because the required python modules are installed in that run. On second `state.apply` the module is detected and used. This is even the case with `reload_modules: true` set.

On the first run I see:
```
----------
          ID: Docker
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: python3-docker
              The following packages were already installed: docker-ce
     Started: 16:12:02.098635
    Duration: 1403.352 ms
     Changes:   
              ----------
              python3-docker:
                  ----------
                  new:
                      1.9.0-1
                  old:
              python3-websocket:
                  ----------
                  new:
                      0.37.0-2
                  old:
----------
          ID: Kubernetes Dependency Image k8s.gcr.io/pause
    Function: docker_image.present
        Name: k8s.gcr.io/pause
      Result: False
     Comment: State 'docker_image.present' was not found in SLS 'kube-minion'
              Reason: 'docker_image' __virtual__ returned False: 'docker.version' is not available.
     Changes:
```

On the minion itself the `salt-minion` logs have this error:
```
salt-minion[138912]: [ERROR   ] State 'docker_image.present' was not found in SLS 'kube-minion'
salt-minion[138912]: Reason: 'docker_image' __virtual__ returned False: 'docker.version' is not available.
```

However, it works on second run:
```
----------
          ID: Docker
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed and are at the desired version
     Started: 16:29:44.739748
    Duration: 26.875 ms
     Changes:  
----------
          ID: Kubernetes Dependency Image k8s.gcr.io/pause
    Function: docker_image.present
        Name: k8s.gcr.io/pause
      Result: True
     Comment: Image 'k8s.gcr.io/pause:3.1' was pulled
     Started: 16:29:44.859688
    Duration: 1079.729 ms
     Changes:   
              ----------
              Layers:
                  ----------
                  Pulled:
                      - 67ddbfb20a22
              Status:
                  Downloaded newer image for k8s.gcr.io/pause:3.1
              Time_Elapsed:
                  0.4564225673675537
              retcode:
                  0
```
### Setup
I have two state files. docker.sls:
```
Docker:
  pkg.installed:
    - pkgs:
        - docker-ce: 18.06.1~ce~3-0~debian
        - python3-docker
    - install_recommends: False
    - reload_modules: true
```

and kube.sls:
```
include:
  - docker

Kubernetes Dependency Image k8s.gcr.io/pause:
  docker_image.present:
    - name: k8s.gcr.io/pause
    - tag: 3.1
    - reload_modules: True
    - require:
      - pkg: Docker
      - service: Docker
      - pkg: Kubernetes Dependencies
```

This may be related to #54332 but in that case `pip` is the installation method and the error message is different. 

### Steps to Reproduce Issue
1) Run `salt <minion> state.apply`
2) Get Failure
3) Run `salt <minion> state.apply`
Success!

### Versions Report
On Master:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9 
```

On the Minion (after `python3-docker` has been installed):
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 1.9.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9 
```

**Comment by xeacott** [comment] 2019-10-30 18:52
I'm not reproducing this entirely, getting a different error but may be with my sls file...
```
linux:
----------
          ID: Docker
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed and are at the desired version
     Started: 18:51:18.833487
    Duration: 95.318 ms
     Changes:
----------
          ID: Kubernetes Dependency Image k8s.gcr.io/pause
    Function: docker_image.present
        Name: k8s.gcr.io/pause
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     service: Docker
                                     pkg: Kubernetes Dependencies
     Started: 18:51:18.950491
    Duration: 0.179 ms
     Changes:

Summary for linux
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:  95.497 ms
```
I did use the provided states above

**Comment by xeacott** [comment] 2019-10-30 18:54
I probably am missing some kubernetes package

**Comment by xpicio** [comment] 2019-11-29 14:26
Hello i'm reporting the same issue using [docker formula](https://github.com/saltstack-formulas/docker-formula) (it seems that in docker formula they use `reload_modules: true`)

Here a snippet of my sls file:
```
include:
  - docker

internal_network:
  docker_network.present:
    - subnet: 172.20.0.0/16

redis service:
  docker_container.running:
    - name: redis
    - image: registry.***.***/***/redis:v1
    - binds:
      - /opt/redis/data:/data
    - ports:
      - 6379
    - networks:
      - internal_network
      - bridge
    - restart_policy: on-failure:3
    - log_driver: syslog
    - log_opt:
      - syslog-facility: daemon
```

The error on first run:
```
----------
          ID: internal_network
    Function: docker_network.present
      Result: False
     Comment: State 'docker_network.present' was not found in SLS 'init-gtw'
              Reason: 'docker_network' __virtual__ returned False: 'docker.version' is not available.
     Changes:
----------
          ID: redis service
    Function: docker_container.running
        Name: redis
      Result: False
     Comment: State 'docker_container.running' was not found in SLS 'init-gtw'
              Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.
     Changes:
----------
```

The result on second run:
```
----------
          ID: internal_network
    Function: docker_network.present
      Result: True
     Comment: Network 'internal_network' created
     Started: 01:48:06.168053
    Duration: 157.235 ms
     Changes:
              ----------
              created:
                  True
----------
          ID: redis service
    Function: docker_container.running
        Name: redis
      Result: True
     Comment: Created container 'redis'
     Started: 01:48:06.453425
    Duration: 12383.978 ms
     Changes:
              ----------
              container:
                  ----------
                  Networks:
                      ----------
                      internal_network:
                          ----------
                          Gateway:
                              ----------
                              new:
                                  172.20.0.1
                              old:
                                  None
                          IPAddress:
                              ----------
                              new:
                                  172.20.0.2
                              old:
                                  None
              container_id:
                  ----------
                  added:
                      128201edd8beb49da5321278b2ae5cf01dd8e36577357a09c0f474cb6936a800
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - e42672a2ca6a
                          - 823e4275fef6
                          - 327e62bcfef7
                          - be5997a801f5
                          - dc62338c8c74
                          - 6c40cc604d8e
                          - 79ed9185c842
                          - c2ad7a3b6c3f
                  Status:
                      Downloaded newer image for registry.***.***/***/redis:v1
                  Time_Elapsed:
                      3.1893012523651123
                  retcode:
                      0
              state:
                  ----------
                  new:
                      running
                  old:
                      None
```

Versions on server:
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: 0.28.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.9.4
         pygit2: 0.28.2
         Python: 3.7.5 (default, Oct 17 2019, 12:25:15)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.138+
         system: Linux
        version: Not Installed
```

Versions on minion:
```
root@ubuntu-18:/tmp# salt-call --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by lsh-0** [comment] 2020-01-20 05:13
I'm getting this too on Salt `2018.3`

```
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 4.1.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-72-generic
         system: Linux
        version: Ubuntu 18.04 bionic
 
```

**Comment by lsh-0** [comment] 2020-01-20 06:38
FWIW, ensuring the `docker` python library is installed prior to calling `highstate` seems to work. The `python-mysqldb` dependency doesn't seem to fail like this but historically we had problems with upgrading python using salt states as well (`reload_modules: true` never seemed to work for us either) so I think it's just safest to call the Python `docker` a hard prerequisite before running Salt.

**Comment by darkn3rd** [comment] 2020-02-06 21:48
I run into the same issue with `salt-minion 2019.2.3 (Fluorine)` when running:
```bash
salt-call state.highstate --retcode-passthrough --local --log-level=debug --force-color
```

I install the docker module, but then run  `docker_container.running`, which does a Traceback.

**Comment by supfors** [comment] 2020-02-21 09:43
Running into the same issue using salt 3000 on ubuntu 18.04. Installing `python3-docker` in advance is working for me. Any chance for a fix in 3000.1 ?

**Comment by 234d** [comment] 2020-03-06 09:38
Same issue here on `Amazon Linux 2` and `salt-minion 3000`.
Tired setting both `reload_modules` and `force_reinstall` to `True` without sucess.

**Comment by max-arnold** [comment] 2020-04-17 10:27
This looks like a potential cause: https://github.com/saltstack/salt/issues/56669#issuecomment-614863977

**Comment by richardsimko** [comment] 2020-05-14 10:18
@max-arnold That seems to be specifically linked to Pip, looking at the PR which is later referenced as a fix (#56867) this only changed so that Pip triggers a reload, however even when installing using `pkg.installed` the Docker state fails.

**Comment by gecube** [comment] 2020-05-23 17:17
I used the `reload_modules` and it looks like it worked for me. OK. Could you all make more thoroughly tests? I will try to repeat too :-)

**Comment by richardsimko** [comment] 2020-05-24 07:26
@gecube Are you installing docker using `pkg.installed` or `pip.installed`?

**Comment by b-a-t** [comment] 2020-09-24 10:06
> @gecube Are you installing docker using `pkg.installed` or `pip.installed`?

I have it with pip.installed.

Even that construction doesn't fix the problem on Salt 3000.3:

```yaml
salt-python-dependencies:
  pip.installed:
    - bin_env: /usr/bin/pip3
    - names:
      - elasticsearch == 7.5.1
      - docker
    - reload_modules: True
    - watch_in:
      - service: salt-minion_svc
```

**Comment by richardsimko** [comment] 2020-09-24 12:24
I changed to using `pkg.installed` and that seems to have fixed the issue for me. It's slightly more inconvenient since the Docker repo needs to be added first but it works.

**Comment by hartwork** [comment] 2020-10-12 16:55
This seems to affect `docker_network` the same way.

**Comment by streambinder** [comment] 2020-11-26 17:13
I actually am experiencing a very similar problem, while configuring Docker + running a container straight away.
Basically if I install _any_ module (regardless it is related or not with `docker`; in this example only the `nox` module was installed via `pip`, all the rest using the `pkg` state) via `pip` state, the `highstate` is gonna fail with:
```
    Function: docker_container.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/urllib3/util/timeout.py", line 124, in _validate_timeout
                  float(value)
              TypeError: float() argument must be a string or a number, not 'Timeout'

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/docker/api/client.py", line 175, in _retrieve_server_version
                  return self.version(api_version=False)["ApiVersion"]
                File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
                  return self._result(self._get(url), json=True)
                File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
                  return f(self, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/docker/api/client.py", line 198, in _get
                  return self.get(url, **self._set_request_timeout(kwargs))
                File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
                  return self.request('GET', url, **kwargs)
                File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
                  resp = self.send(prep, **send_kwargs)
                File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
                  r = adapter.send(request, **kwargs)
                File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
                  timeout=timeout
                File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 587, in urlopen
                  timeout_obj = self._get_timeout(timeout)
                File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 300, in _get_timeout
                  return Timeout.from_float(timeout)
                File "/usr/lib/python3/dist-packages/urllib3/util/timeout.py", line 154, in from_float
                  return Timeout(read=timeout, connect=timeout)
                File "/usr/lib/python3/dist-packages/urllib3/util/timeout.py", line 94, in __init__
                  self._connect = self._validate_timeout(connect, 'connect')
                File "/usr/lib/python3/dist-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
                  "int, float or None." % (name, value))
              ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int, float or None.

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/docker_container.py", line 1687, in running
                  image_id = _resolve_image(ret, image, client_timeout)
                File "/usr/lib/python3/dist-packages/salt/states/docker_container.py", line 187, in _resolve_image
                  image_id = __salt__["docker.resolve_image_id"](image)
                File "/usr/lib/python3/dist-packages/salt/modules/dockermod.py", line 2057, in resolve_image_id
                  inspect_result = inspect_image(name)
                File "/usr/lib/python3/dist-packages/salt/modules/dockermod.py", line 1989, in inspect_image
                  ret = _client_wrapper("inspect_image", name)
                File "/usr/lib/python3/dist-packages/salt/modules/dockermod.py", line 451, in wrapper
                  __context__["docker.client"] = _get_client(timeout=timeout, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/dockermod.py", line 411, in _get_client
                  ret = docker.APIClient(**client_kwargs)
                File "/usr/lib/python3/dist-packages/docker/api/client.py", line 158, in __init__
                  self._version = self._retrieve_server_version()
                File "/usr/lib/python3/dist-packages/docker/api/client.py", line 183, in _retrieve_server_version
                  'Error while fetching server API version: {0}'.format(e)
              docker.errors.DockerException: Error while fetching server API version: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int, float or None.
     Started: 16:53:52.451899
    Duration: 19.067 ms
     Changes:
```
If I run the very same `highstate` once more, it'll work.
On the other hand, if I strip any `pip` state out of the `highstate` (e.g., temporarily exclude `nox` from being installed), it'll work at the first try.
Obviously, that can't be a viable solution, as even the simplest states usually include `pip` dependencies.

**Comment by md-magenta** [comment] 2021-02-17 12:52
I have the same issue as streambinder, but with `docker_network.present`.

**Comment by mattiasr** [comment] 2021-05-11 17:43
I installed `python3-docker`, no change, then I started a python3 shell and imported docker and got error `No module named 'distutils.spawn'`

Installed `python3-distutils` and now the steps works.

Running:  3003+ds-1 on Ubuntu 20.04

**Comment by luvncoco** [comment] 2021-05-21 10:01
still getting this issue with 
      - python3-distutils
      - python3-docker
```
    googlecompute:           ID: Configure Networks
    googlecompute:     Function: docker_network.present
    googlecompute:         Name: traefik_web
    googlecompute:       Result: False
    googlecompute:      Comment: State 'docker_network.present' was not found in SLS 'docker'
    googlecompute:               Reason: 'docker_network' __virtual__ returned False: 'docker.version' is not available.
    googlecompute:      Changes:
```

**Comment by mattiasr** [comment] 2021-05-28 14:11
> still getting this issue with
> - python3-distutils
> - python3-docker
> 
> ```
>     googlecompute:           ID: Configure Networks
>     googlecompute:     Function: docker_network.present
>     googlecompute:         Name: traefik_web
>     googlecompute:       Result: False
>     googlecompute:      Comment: State 'docker_network.present' was not found in SLS 'docker'
>     googlecompute:               Reason: 'docker_network' __virtual__ returned False: 'docker.version' is not available.
>     googlecompute:      Changes:
> ```

Dump question, but did you restart the service?

**Comment by DaAwesomeP** [comment] 2021-08-29 21:54
I am in nearly the exact same environment as @rhbvkleef and have the same issue. I have tried both `python3-docker` via apt and `docker==4.4.4`, `urllib3==1.26.6`, and `requests==2.26.0` via pip.

Another issue mentions installing `docker`, `urllib3`, and `requests` via pip, but I think this might not work because the salt apt packages depend on `python3-requests`, etc.

**Comment by DaAwesomeP** [comment] 2021-09-03 18:38
I think some of the problem may be in that salt is installed via the system package repository and relies on packages like `python3-requests` and `python3-urllib3` of whichever version the OS repo provides. However, the Python docker library is installed via pip and and brings its own versions of `requests` and `urllib3` which salt may not actually use. Docker no longer offers `docker-py` as an system package; it can only be installed as a pip package.

The solution to isolate these would be to either
  1. Reinstall salt from pip (not ideal)
  2. Move `docker-py` to a virtualenv and run some other salt connector process in that virtualenv (proper separation, most ideal)
  3. Somehow force salt to use the pip versions of urllib3 and requests

**Comment by rhbvkleef** [comment] 2021-09-04 20:21
@DaAwesomeP, if you read my previous comment, you'll see that `requests` and `urllib3` are only installed once each, so there is no such conflict, although somehow the stacktrace looks like that's the only option. Is my find not complete somehow? Where else could these packages be installed?

**Comment by DaAwesomeP** [comment] 2021-09-04 20:36
Saltstack depends on `python3-requests` at the OS level (i.e. this is install by APT on Debian as it is a dependency of salt-common). These are installed to `/usr/lib/python3/dist-packages/` .You will also notice a `urllib3` and `requests` here if you run `apt-get install python3-urllib3 python3-requests` (though requests should already be there if salt is installed).

However, pip is able to provide newer dependencies when it installs packages. These are stored in `/usr/local/lib/python3.7/dist-packages/` on Debian 10. This is where the `docker` library is installed from pip. You will also notice a `urllib3` and `requests` here if you run `pip3 install urllib3 requests`.

So I think what may be happening, and maybe I am very wrong here, but `salt-common` installed via APT may be preferring the `python3-requests` library over the pip-installed `requests` library. But the `docker` library installed via pip expects the newer version that pip installed (as a dependency for `docker`) and so is generating this error.

There is always a danger in mixing and matching pip and os-provided Python libraries for this reason: there is no version matching between the two systems (apt and pip). I think this may not have used to be an issue because Docker used to ship a `docker-py` OS/apt package (which would properly depend on the right version of `python3-requstests`), but now they have moved to pip only (probably for greater system/OS compatibility and newer dependency versions).

Typically for CLI tools and individual applications the solution would be to isolate `docker` into a virtualenv/venv, but since it needs to be accessed programmatically via Python, that may not be possible.

The best solution I can think of would be to introduce a `salt-docker-connector` package to pip/Pypi. This package would depend on `docker` on Pypi. It would provide a connection between the `docker` package and `salt` via non-Python programmatic means (i.e. socket, bus, CLI, etc.). This way `docker` and `salt-docker-connector` could live in their own in a separate virtualenv and not mix with the `salt` or other system dependencies.

**Comment by dmurphy18** [comment] 2022-01-14 00:52
There is no response to the issue for some months, if none is received soon, the issue will be closed as considered dormant, and no longer relevant.

**Comment by DaAwesomeP** [comment] 2022-02-02 20:24
@whytewolf where did you install the python3-docker module from? Did you install the Debian-provided Docker or the one from the Docker APT repo?

**Comment by whytewolf** [comment] 2022-02-02 20:48
docker apt doesn't supply python3-docker https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/ that can only come from the docker repos.

**Comment by whytewolf** [comment] 2022-02-14 18:14
Closing this issue since no one has been able to give a test case that fails, and I have tried the suggested test cases. as well as some things not suggested in an attempt to get it to fail. If you are still having this issue with a 3004 or later version then please open a new ticket.

**Closed by whytewolf** 2022-02-14 18:14 UTC
Labels: Bug, severity-medium, Phosphorus v3005.0

**Comment by markdueck1** [comment] 2022-10-12 01:18
I have recently run into this on raspbian bullseye, with the latest salt (3005.1).  This time the pip docker version 6 is the issue, downgrading it to 5.0.3 fixes the issue for me.

**Comment by whytewolf** [comment] 2022-10-12 01:39
> I have recently run into this on raspbian bullseye, with the latest salt (3005.1). This time the pip docker version 6 is the issue, downgrading it to 5.0.3 fixes the issue for me.

the issue with docker 6 is not related to this issue. docker 6.0.0 broke how they handle versioning which is how salt determines if a proper docker python module is installed. that is much different than what was causing this issue which is loader issues and python path based.
