### ISSUE TITLE
[BUG] status.uptime will fail if uptime less than 24 hours (AIX minions only)

### ISSUE THREAD

**Issue by jose1711** [saltstack/salt#61557] opened 2022-02-01 09:32 UTC
**Description**
If uptime on AIX minion is less than 24 hours call to `status.uptime` will generate `IndexError`.

**Setup**
AIX 7.2 minion with `uptime` less than 24 hours.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Issue `salt AIX_MINION status.uptime` from salt master.

**Expected behavior**
Information regarding uptime appears on stdout.

**Actual behaviour**
No information is returned, instead an error appears:
``` 
    The minion function caused an exception: Traceback (most recent call last):
      File "/opt/salt/lib/python2.7/site-packages/salt/minion.py", line 1606, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/opt/salt/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/opt/salt/lib/python2.7/site-packages/salt/modules/status.py", line 243, in uptime
        seconds = _get_boot_time_aix()
      File "/opt/salt/lib/python2.7/site-packages/salt/modules/status.py", line 92, in _get_boot_time_aix
        hms = days[1].split(':')
    IndexError: list index out of range
``` 

**Versions Report**
Salt master running at version 3002.6, minion running at version 2018.3.2.

**Additional context**
If uptime of AIX system is less than 24 hours the output of `ps -o etime= -p 1` is as follows:
``` 
$ ps -o etime= -p 1
   11:10:06
``` 
This is how the output looks on a host with 96+ days of uptime (for comparison):
``` 
$ ps -o etime= -p 1
96-20:58:27
```

**Comment by OrangeDog** [comment] 2022-02-01 12:02
2018.3.2 is EOL and missing several critical security patches.

Please upgrade and see if the issue is fixed.
The `ps` command has the same behavior on Linux, and there is no issue there.

**Comment by jose1711** [comment] 2022-02-01 12:13
Testing with the latest version is irrelevant. The code is the (almost - only cosmetics) same for 2018.3.2 and current master = the issue is still present even in yet-to-be-released version. `ps` command is only used on AIX inside `_get_boot_time_aix()` function (https://github.com/saltstack/salt/blob/master/salt/modules/status.py).

If Linux was using the same method it would fail too. Here's a test case (my home system, uptime ~4 hours):
```
import subprocess
bt_time = subprocess.getoutput('ps -o etime= -p 1')
days = bt_time.split('-')  # ['   04:35:07']
hms = days[1].split(':')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

And the same thing on my VPS with uptime of 266 days.
```
import subprocess
bt_time = subprocess.getoutput('ps -o etime= -p 1')
days = bt_time.split('-')  # ['266', '15:40:50']
hms = days[1].split(':')  # ['15', '41', '05']
```

**Comment by OrangeDog** [comment] 2022-02-01 12:28
It's relevant if you ever want it fixed for you. No more releases of 2018.3 are going to be made.
You are correct that AIX is the only platform that attempts to parse command output instead of reading the uptime directly.

The fix looks easy enough, I might do it shortly if the testing isn't too painful.
You can patch it yourself, or upgrade to a future release.

**Comment by OrangeDog** [comment] 2022-02-01 13:48
Worth noting that there are unit tests for every platform except AIX for the status module.

**Comment by dmurphy18** [comment] 2022-02-01 17:28
@OrangeDog Actually in the master branch there is now, tests/pytests/unit/modules/test_aix_status.py. Been working through a number of AIX issues, where there were a few missed Py 2 -> Py 3 issues which have now been fixed.

**Comment by dmurphy18** [comment] 2022-02-01 18:54
Problem exists with current Salt 3004, need to try on machine just rebooted to ensure uptime is less than 24 hours.
```
[TRACE   ] Loaded cmdmod as virtual cmd
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command 'ps' in directory '/'
[DEBUG   ] stdout:       13:43
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "salt-aix", line 70, in <module>
  File "salt-aix", line 55, in redirect
  File "salt/scripts.py", line 432, in salt_call
    client.run()
  File "salt/cli/call.py", line 55, in run
    caller.run()
  File "salt/cli/caller.py", line 111, in run
    ret = self.call()
  File "salt/cli/caller.py", line 219, in call
    self.opts, data, func, args, kwargs
  File "salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/run/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/run/salt/modules/status.py", line 245, in uptime
    seconds = _get_boot_time_aix()
  File "/opt/saltstack/salt/run/salt/modules/status.py", line 79, in _get_boot_time_aix
    hms = days[1].split(":")
IndexError: list index out of range
[7471492] Failed to execute script salt-aix
Traceback (most recent call last):
  File "salt-aix", line 70, in <module>
  File "salt-aix", line 55, in redirect
  File "salt/scripts.py", line 432, in salt_call
  File "salt/cli/call.py", line 55, in run
  File "salt/cli/caller.py", line 111, in run
  File "salt/cli/caller.py", line 219, in call
  File "salt/loader/lazy.py", line 149, in __call__
  File "salt/loader/lazy.py", line 1201, in run
  File "salt/loader/lazy.py", line 1216, in _run_as
  File "/opt/saltstack/salt/run/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "salt/loader/lazy.py", line 149, in __call__
  File "salt/loader/lazy.py", line 1201, in run
  File "salt/loader/lazy.py", line 1216, in _run_as
  File "/opt/saltstack/salt/run/salt/modules/status.py", line 245, in uptime
    seconds = _get_boot_time_aix()
  File "/opt/saltstack/salt/run/salt/modules/status.py", line 79, in _get_boot_time_aix
    hms = days[1].split(":")
IndexError: list index out of range
root@p1272-pvm3:/home/cecuser# 
```

**Comment by dmurphy18** [comment] 2022-02-01 20:07
PR https://github.com/saltstack/salt/pull/61563 has a proposed fix for this

**Closed** 2022-02-03 01:30 UTC
Labels: Bug, severity-medium, Confirmed, effort-small, AIX
