### ISSUE TITLE
2015.8.0rc4_TheBigBear git rel. 'gcb9fddd' [ERROR   ] Failed to import log_handlers sentry_mod, this is due most likely to a syntax error:

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26739] opened 2015-08-28 16:25 UTC
@UtahDave ^^^ @twangboy I have done a test install of the new 2015.8 right after your winrepo chnages were merged in.

I admittedly used an inappropriate cmd. ```salt-call --local winrepo.genrepo``` that has actually been removed from the masterless minion on >=  2015.8 

But it looks like it tried calling in the logging and failed. ;-(

```
C:\salt>salt-call --local pkg.winrepo.genrepo
[ERROR   ] Failed to import log_handlers sentry_mod, this is due most likely to
a syntax error:
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\loader.py", line 1105, in _load_module
    ), fn_, fpath, desc)
  File "c:\salt-dev\salt\salt\log\handlers\sentry_mod.py", line 96, in <module>
    __grains__ = salt.loader.grains(__opts__)
NameError: name '__opts__' is not defined
'pkg.winrepo.genrepo' is not available.
```

my ```salt-call --local --versions``` is:
```
C:\salt>salt-call --versions
Salt Version:
           Salt: 2015.8.0rc3-147-gcb9fddd

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD6
4)]
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.2.1
       cherrypy: 3.8.0
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: 1.3.8
        libnacl: 1.4.3
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.3
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist:
        machine: AMD64
        release: 8
         system: 8 6.2.9200  Multiprocessor Free
```

**Comment by rallytime** [comment] 2015-08-28 17:26
This should be fixed by #26744 and is a duplicate of #26717. I'm going to close this so we can track it in the other issue. If you still see problems after the fix is merged, definitely let us know and we can take another look, but I pulled the fix down just now and it has fixed the issue nicely.

**Closed by rallytime** 2015-08-28 17:26 UTC
Labels: Core, Duplicate
