### ISSUE TITLE
unit.test_auth.AuthACLTestCase.test_acl_simple_allow transport test failure

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53282] opened 2019-05-28 18:39 UTC
The test `unit.test_auth.AuthACLTestCase.test_acl_simple_allow` is failing on transport tests:

https://jenkinsci.saltstack.com/job/2019.2.1/view/Transport/job/salt-centos-7-py2-tcp/4/testReport/junit/unit.test_auth/AuthACLTestCase/test_acl_simple_allow/

```
Lists differ: [] != [{u'alpha_minion': [u'test.pin...  Second list contains 1 additional elements. First extra element 0: {u'alpha_minion': [u'test.ping']}  - [] + [{u'alpha_minion': [u'test.ping']}]

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/test_auth.py", line 589, in test_acl_simple_allow
    [{'alpha_minion': ['test.ping']}])
AssertionError: Lists differ: [] != [{u'alpha_minion': [u'test.pin...

Second list contains 1 additional elements.
First extra element 0:
{u'alpha_minion': [u'test.ping']}

- []
+ [{u'alpha_minion': [u'test.ping']}]
```

**Comment by DmitryKuzmenko** [comment] 2019-06-10 14:25
In the `auth/pam.py` module either `HAS_PAM` or `HAS_LIBC` is calculated to `False`. 
The test passes running alone with the same Jenkins configuration.
I'm waiting results of the full test suite running with the additional logging on CI.

**Comment by DmitryKuzmenko** [comment] 2019-06-11 14:43
Here's the error message from pam module:
```
01:30:53,850 [salt.loaded.int.auth.pam                                  :71  ][DEBUG   ] Failed to load libc using ctypes
Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/auth/pam.py", line 55, in <module>
    LIBC = CDLL(find_library('c'))
  File "/usr/lib64/python2.7/ctypes/util.py", line 244, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/lib64/python2.7/ctypes/util.py", line 233, in _findSoname_ldconfig
    f = os.popen('/sbin/ldconfig -p 2>/dev/null')
OSError: [Errno 12] Cannot allocate memory
01:30:53,850 [salt.loaded.int.auth.pam                                  :173 ][DEBUG   ] Failed to load pam using ctypes
Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/auth/pam.py", line 141, in <module>
    LIBPAM = CDLL(find_library('pam'))
  File "/usr/lib64/python2.7/ctypes/util.py", line 244, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/lib64/python2.7/ctypes/util.py", line 233, in _findSoname_ldconfig
    f = os.popen('/sbin/ldconfig -p 2>/dev/null')
OSError: [Errno 12] Cannot allocate memory
```

So I'm marking this as a duplicate of the memory issue #53284.

**Comment by Akm0d** [comment] 2019-07-09 23:40
This needs to be fixed in Neon

**Closed** 2019-07-10 17:22 UTC
Labels: 2019.2.1, Duplicate, Neon, Test Failure
