### ISSUE TITLE
Error installing salt-minion on RHEL 8 beta

### ISSUE THREAD

**Issue by schultmc** [saltstack/salt#50643] opened 2018-11-26 20:24 UTC
### Description of Issue/Question

Unable to install salt-minion on RHEL 8 beta.

### Setup

We are testing out RHEL 8 beta in our environment and would like to salt our test machines to match the rest of our environment. RHEL 8 does not have any packages that provide /usr/bin/python. Python 2.7 is available via the python2 package and python 3.6 is available via the python3 package. Depending on a package rather than an absolute filepath would resolve this issue.

### Steps to Reproduce Issue

1. Install a RHEL 8 beta instance.
2. Add saltstack repository per https://repo.saltstack.com/#rhel
3. Attempt to install salt-minion

Results:

Error: 
 Problem: conflicting requests
  - nothing provides /usr/bin/python needed by salt-minion-2018.3.3-1.el7.noarch

### Versions Report
N/A (Unable to install minion). Master is 2018.3.3 and target minion version is 2018.3.3

**Comment by garethgreenaway** [comment] 2018-11-27 16:50
@dmurphy18 Thoughts on this one?

**Comment by mikeadamz** [comment] 2018-12-05 23:32
The issue is this: https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/ You need to make the salt-minion package depend on the appropriate python package as RHEL 8 no longer ships with a default /bin/python.

**Comment by dmurphy18** [comment] 2019-04-02 16:52
@schultmc This issue can be tracked in salt-pack-py3, the correct location for Salt packaging issues with Python 3, see https://github.com/saltstack/salt-pack-py3/issues/120

At the moment Salt has issues working with python3-tornado > v5, however there is a fix that is under initial test at the moment but there are no timelines as to when it will be available, but there is pressure to have it available as soon as possible (Buster, Fedora, etc.)

Closing this issue since the above issue is the correct place to track this issue.

**Closed by dmurphy18** 2019-04-02 16:52 UTC
Labels: Duplicate, Pending Discussion
