### ISSUE TITLE
[BUG] Function grains.items in mine.update failed to execute

### ISSUE THREAD

**Issue by MyIgel** [saltstack/salt#57055] opened 2020-05-02 21:47 UTC
**Description**
When setting `mine_functions` to run `grains.items` it fails to execute after upgrade to `3000.2` (from before `3000` where it worked).

**Setup**
_/etc/salt/minion.d/50-mine.conf_
```
mine_functions:
  grains.items: [host]
```

**Steps to Reproduce the behavior**
Restart the minion

```
May 02 21:12:14 prometheus salt-minion[5753]: [ERROR   ] Function grains.items in mine.update failed to execute
May 02 21:12:14 prometheus salt-minion[5753]: [DEBUG   ] Error: Traceback (most recent call last):                                                                                            
May 02 21:12:14 prometheus salt-minion[5753]:   File "/usr/lib/python2.7/dist-packages/salt/modules/mine.py", line 192, in update
May 02 21:12:14 prometheus salt-minion[5753]:     **function_kwargs
May 02 21:12:14 prometheus salt-minion[5753]:   File "/usr/lib/python2.7/dist-packages/salt/utils/functools.py", line 147, in call_function
May 02 21:12:14 prometheus salt-minion[5753]:     return salt_function(*function_args, **function_kwargs)
```
(lines may be inaccurate as i added more debug messages to the code, see Additional context)

**Expected behavior**
The `grains.items` to be collected

**Versions Report**
<details><summary>salt-call --versions-report</summary>
The same problem occurs on minions running python 3 on a new debian vm

```
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 1.9.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.12
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-12-amd64
         system: Linux
        version: debian 9.12
```
</details>

**Additional context**
The value of `function_args` is `[u'host']` and the value of `function_kwargs` is `{'sanitize': False}`, where the sanitize part seems to cause the problem. Where does it come from?

Removing the `**function_kwargs` parameter from `return salt_function(*function_args, **function_kwargs)` solves the problem but that can not be the solution ;)

What would be the expected value here?

**Comment by MyIgel** [comment] 2020-05-02 21:56
Interestingly when using `grains.items: []` it works somehow but why?

**Comment by rossengeorgiev** [comment] 2020-05-02 23:07
Hi @MyIgel whats your salt master log saying? Do you see any errors, or `Requested method not exposed: .....` ?

**Comment by MyIgel** [comment] 2020-05-03 10:27
I can't see that message in the master debug log (but as i have more minions its not that easy to find anything in it ;))

But i don't think its that master related (and only affects minions)?

**Comment by OrangeDog** [comment] 2020-05-04 10:47
Duplicate of #56496

**Comment by waynew** [comment] 2020-05-06 22:33
Closing this as duplicate

**Closed by waynew** 2020-05-06 22:33 UTC
Labels: Bug, Duplicate
