### ISSUE TITLE
if the user exists, but has no permissions, rabbitmq_user.list_user_permissions() blows

### ISSUE THREAD

**Issue by belt-ascendlearning** [saltstack/salt#28971] opened 2015-11-17 20:51 UTC
To recreate: try defining the permissions as: `{'/': ["","",""]}`
Then try doing anything else e.g. re-running the recipe.

**Comment by jfindlay** [comment] 2015-11-18 16:21
@belt-ascendlearning, is this on 2015.8.1?

**Comment by belt-ascendlearning** [comment] 2015-11-18 16:22
Yes.

**Comment by rallytime** [comment] 2016-01-25 20:49
@belt-ascendlearning Can you be a little more specific about the error you're seeing and what you're expecting to happen? I have set up the following state, ran it, and then used `rabbitmq.list_user_permissions` and everything appears to work:
```
root@rallytime:~# cat /srv/salt/rabbitmq_user.sls
test_user:
  rabbitmq_user.present:
    - password: secret
    - perms:
      - '/':
        - ''
        - ''
        - ''
root@rallytime:~# salt-call --local state.sls rabbitmq_user
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://rabbitmq_user.sls'
[INFO    ] Running state [test_user] at time 20:46:50.015895
[INFO    ] Executing state rabbitmq_user.present for test_user
[INFO    ] Executing command 'rabbitmqctl list_users' as user 'root' in directory '/root'
[INFO    ] Executing command 'rabbitmqctl list_user_permissions test_user' as user 'root' in directory '/root'
[INFO    ] Executing command 'rabbitmqctl set_permissions -p / test_user "" "" ""' as user 'root' in directory '/root'
[INFO    ] Made the following changes:
'perms' changed from 'absent' to {'/': ['', '', '']}
'user' changed from 'absent' to 'test_user'
[INFO    ] Completed state [test_user] at time 20:46:51.138011
local:
----------
          ID: test_user
    Function: rabbitmq_user.present
      Result: True
     Comment: 'test_user' was configured.
     Started: 20:46:50.015895
    Duration: 1122.116 ms
     Changes:
              ----------
              perms:
                  ----------
                  new:
                      ----------
                      /:
                  old:
                      ----------
              user:
                  ----------
                  new:
                      test_user
                  old:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
root@rallytime:~# salt-call --local rabbitmq.list_user_permissions test_user
[INFO    ] Executing command 'rabbitmqctl list_user_permissions test_user' as user 'root' in directory '/root'
local:
    ----------
    /:
root@rallytime:~# salt --versions
Salt Version:
           Salt: 2015.8.3-253-gb1e604a

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-x86_64-linode63
         system: Ubuntu 14.04 trusty
```
Note: the output above is from the current HEAD of the 2015.8 branch, but I also tested this same progression with 2015.8.1 with the same results.

**Comment by rallytime** [comment] 2016-01-25 21:05
@belt-ascendlearning Actually, I think I was just building this example incorrectly and what you're reporting on is likely the same bug as reported in #28661. When I tried the sample state in that issue, which was:
```
rabbitmq_user_tmpchq_user:
  rabbitmq_user.present:
    - name: tmpchq_user1
    - password: 'yup'
    - perms:
      - 'tmpchq':
      - ".*"
      - ".*"
      - ".*"
```
I get the following stacktrace:
```
local:
----------
          ID: rabbitmq_user_tmpchq_user
    Function: rabbitmq_user.present
        Name: tmpchq_user1
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/root/SaltStack/salt/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/root/SaltStack/salt/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/root/SaltStack/salt/salt/states/rabbitmq_user.py", line 179, in present
                  if _check_perms_changes(name, perms, runas=runas, existing=existing_perms):
                File "/root/SaltStack/salt/salt/states/rabbitmq_user.py", line 60, in _check_perms_changes
                  for vhost, perms in vhost_perms.iteritems():
              AttributeError: 'str' object has no attribute 'iteritems'
     Started: 20:58:01.606120
    Duration: 604.493 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
And after looking through the code, we're not checking to see if the new user has perms correctly, as you stated in the title:
```
# salt-call --local rabbitmq.list_user_permissions tmpchq_user1
[INFO    ] Executing command 'rabbitmqctl list_user_permissions tmpchq_user1' as user 'root' in directory '/root'
local:
    ----------
```
Is this the error you are seeing? If so, can we close this issue as a duplicate of #28661, and track the progress of that fix over there?

**Comment by rallytime** [comment] 2016-01-25 21:30
Also note, after even more experimentation, the sample state provided in the other issue had some incorrect yaml syntax, resulting in the stacktrace. As outlined in [this comment](https://github.com/saltstack/salt/issues/28661#issuecomment-174670916), using the correct syntax results in a more reasonable error. Let me know if either of these errors are what you were seeing. If it is something different, then we'll need to get that fixed up.

**Comment by belt-ascendlearning** [comment] 2016-02-01 16:25
salt-2015.8.3

<code>
RabbitmqUser.present(
  'bug', password='test', force=True, tags='administrator',
  perms=[{'/': ['', '', '']}])
</code>

<pre>
[INFO    ] Executing command 'rabbitmqctl list_user_permissions bug' as user 'root' in directory '/root'
[DEBUG   ] output: Listing permissions for user "bug" ...
/
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/rabbitmq_user.py", line 174, in present
    existing_perms = __salt__['rabbitmq.list_user_permissions'](name, runas=runas)
  File "/usr/lib/python2.7/dist-packages/salt/modules/rabbitmq.py", line 371, in list_user_permissions
    return _output_to_dict(res)
  File "/usr/lib/python2.7/dist-packages/salt/modules/rabbitmq.py", line 96, in _output_to_dict
    key, values = row.split('\t', 1)
ValueError: need more than 1 value to unpack
</pre>

**Comment by belt-ascendlearning** [comment] 2016-02-01 16:29
<pre>
$ sudo rabbitmqctl list_user_permissions bug
Listing permissions for user "bug" ...
/
</pre>

**Comment by belt-ascendlearning** [comment] 2016-02-01 16:33
This is not a yaml syntax error as I'm using pyobjects. This is a parsing error of rabbitctl output as the parser assumes there will be data where there is none.

**Comment by rallytime** [comment] 2016-02-01 19:19
@belt-ascendlearning Thank you for providing that additional information. I am still unable to reproduce your exact error using the pyobjects state you provided above.

However, I was able to produce a different error in the state output regarding setting the `administrator` tag, because the renderer couldn't the parse the `set` of the new tags coming from the `rabbitmq_user` state:
```
# git diff
diff --git a/salt/states/rabbitmq_user.py b/salt/states/rabbitmq_user.py
index 689afee..8a291d0 100644
--- a/salt/states/rabbitmq_user.py
+++ b/salt/states/rabbitmq_user.py
@@ -79,7 +79,7 @@ def _check_tags_changes(name, new_tags, runas=None):
         except CommandExecutionError as err:
             log.error('Error: {0}'.format(err))
             return []
-        return users
+        return list(users)
     else:
         return []
```

With that change applied to either version `2015.8.3` or the HEAD of the `2015.8` branch, I have the following successful state run:
```
root@rallytime:~# cat /srv/salt/rabbitmq_pyobjects.sls
#!pyobjects

RabbitmqUser.present( 'bug', password='test', force=True, tags='administrator', perms=[{'/': ['', '', '']}])

root@rallytime:~# salt-call --local state.sls rabbitmq_pyobjects
<snipped>
[INFO    ] Running state [bug] at time 19:02:35.094674
[INFO    ] Executing state rabbitmq_user.present for bug
[INFO    ] Executing command 'rabbitmqctl list_users' as user 'root' in directory '/root'
[INFO    ] Executing command 'rabbitmqctl list_users' as user 'root' in directory '/root'
[INFO    ] Executing command 'rabbitmqctl set_user_tags bug administrator' as user 'root' in directory '/root'
[INFO    ] Executing command 'rabbitmqctl list_user_permissions bug' as user 'root' in directory '/root'
[INFO    ] Executing command 'rabbitmqctl set_permissions -p / bug "" "" ""' as user 'root' in directory '/root'
[INFO    ] Made the following changes:
'perms' changed from 'absent' to {'/': ['', '', '']}
'user' changed from 'absent' to 'bug'
'tags' changed from 'administrator' to ['']

[INFO    ] Completed state [bug] at time 19:02:36.897727
local:
----------
          ID: bug
    Function: rabbitmq_user.present
      Result: True
     Comment: 'bug' was configured.
     Started: 19:02:35.094674
    Duration: 1803.053 ms
     Changes:
              ----------
              perms:
                  ----------
                  new:
                      ----------
                      /:
                  old:
                      ----------
              tags:
                  ----------
                  new:
                  old:
                      administrator
              user:
                  ----------
                  new:
                      bug
                  old:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.803 s
root@rallytime:~# rabbitmqctl list_user_permissions bug
Listing permissions for user "bug" ...
/
...done.
root@rallytime:~# salt --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-x86_64-linode63
         system: Ubuntu 14.04 trusty
```
What version of rabbitmq are you using? Perhaps something related to the version is causing the discrepancy.

**Comment by belt-ascendlearning** [comment] 2016-02-01 19:54
Stated in https://github.com/saltstack/salt/issues/28971#issuecomment-178055166
salt-2015.8.3

**Comment by belt-ascendlearning** [comment] 2016-02-01 19:56
Does it make a difference if the rabbitmq-account exists before you try setting the permissions? In my example(s), it does not.

**Comment by rallytime** [comment] 2016-02-01 20:20
@belt-ascendlearning Sorry, I meant the version of `rabbitmqctl` you have installed. I have `3.2.4`. Also, can you clarify what you mean by the `rabbitmq-account`? The `bug` user that you listed in your state was not present when I ran the state. I only had the `guest` user:
```
# rabbitmqctl list_users
Listing users ...
guest	[administrator]
...done.
```

**Comment by rallytime** [comment] 2016-02-01 20:22
If the `bug` user is already there, then I get the following, expected, state output:
```
local:
----------
          ID: bug
    Function: rabbitmq_user.present
      Result: True
     Comment: 'bug' was configured.
     Started: 20:21:33.330874
    Duration: 1170.577 ms
     Changes:
              ----------
              password:
                  ----------
                  new:
                      Set password.
                  old:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.171 s
```

**Comment by belt-ascendlearning** [comment] 2016-02-01 20:26
rabbitmq-server-3.6.0

**Comment by belt-ascendlearning** [comment] 2016-02-01 20:28
In my opinion, acount is a friendlier term than user. User dehumanizes people. Name an industry, other than narcotics, that call their customers users.

**Comment by rallytime** [comment] 2016-02-01 21:25
Hrm...I upgraded to version `3.6.0-1` of rabbitmq-server and I unfortunately still can't reproduce this error. Can you think of anything that I might be missing here to reproduce?

**Comment by belt-ascendlearning** [comment] 2016-02-01 21:40
The only differential I see is that I'm running it as `sudo salt-call` and you are running as root via `salt-call --local` ... so unless that difference sets (or not) the value of runas, AND that effects how __salt__['cmd.run'] yields results... I'm not understanding how _output_to_dict() seems to be trying to split a null-response in list_user_permissions() for me, but not you.

**Comment by rallytime** [comment] 2016-02-01 21:43
Oh! @belt-ascendlearning I figured it out. I get that error when I don't have the fix applied that I mentioned above. The difference in rabbitmq versions manifests the error differently, but with 3.6.0 and 2015.8.3, I am getting your same error:
```
[INFO    ] Executing command 'rabbitmqctl list_user_permissions bug' as user 'root' in directory '/root'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/root/SaltStack/salt/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/root/SaltStack/salt/salt/states/rabbitmq_user.py", line 174, in present
    existing_perms = __salt__['rabbitmq.list_user_permissions'](name, runas=runas)
  File "/root/SaltStack/salt/salt/modules/rabbitmq.py", line 371, in list_user_permissions
    return _output_to_dict(res)
  File "/root/SaltStack/salt/salt/modules/rabbitmq.py", line 96, in _output_to_dict
    key, values = row.split('\t', 1)
ValueError: need more than 1 value to unpack
```
With my fix applied, it works. A PR is incoming shortly.

**Comment by rallytime** [comment] 2016-02-02 18:47
@belt-ascendlearning Thanks for providing all of the useful information here to help track this one down. I've submitted #30822 to fix this issue.

**Closed** 2016-02-15 16:35 UTC
Labels: Bug, Execution Module, Fixed Pending Verification, High Severity, P3, Platform, TEAM RIoT
