### ISSUE TITLE
Minion sometimes fails during startup, hangs silently with no errors reported

### ISSUE THREAD

**Issue by adam12b1** [saltstack/salt#53319] opened 2019-05-30 18:46 UTC
### Description of Issue

On FreeBSD 11, ever since updating to the Python 3.6 version of Salt, we sporadically see (perhaps 1 out of 10 times) the salt-minion fail to fully start up, though there is no explicit indication of any trouble. The start command exits after appearing to succeed, the salt-minion process is running, and there are no errors reported on command line or in logs, even at DEBUG level, but the minion is unreachable and the process will not go down without a `kill -9`.

### Setup

The only non-default settings in our minion config are these:
```
log_file: file:///var/run/log/LOG_LOCAL5
log_fmt_console: '%(colorlevel)s %(colormsg)s'
log_level_logfile: debug
master_finger: '[OUR MASTER FINGERPRINT HERE]'
```
and in the master config:
```
nodegroups:
  [OUR LOCALLY DEFINED NODEGROUPS HERE]
log_file: file:///var/run/log/LOG_LOCAL5
log_fmt_console: '%(colorlevel)s %(colormsg)s'
log_level_logfile: debug
timeout: 5
```
We have no non-default runtime variables set for Salt.

### Steps to Reproduce Issue

Logs show the startup getting to the same point every time, before it ceases further activity: on the minion, the final item is always `Closing AsyncZeroMQReqChannel instance`, while on the master the final action is sending the public key. Here are the final few lines from the minion:
```
May 16 15:36:36 virt-web 2019-05-16 15:36:36,484 [salt.crypt  :797 ][DEBUG   ][622] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
May 16 15:36:36 virt-web 2019-05-16 15:36:36,583 [salt.crypt  :207 ][DEBUG   ][622] salt.crypt.get_rsa_pub_key: Loading public key
May 16 15:36:36 virt-web 2019-05-16 15:36:36,587 [salt.transport.zeromq :227 ][DEBUG   ][622] Closing AsyncZeroMQReqChannel instance
```
and from the master:
```
May 16 15:36:36 saltmaster 2019-05-16 15:36:36,177 [salt.transport.mixins.auth :407 ][INFO    ][62549] Authentication accepted from virt-web
May 16 15:36:36 saltmaster 2019-05-16 15:36:36,177 [salt.crypt :207 ][DEBUG   ][62549] salt.crypt.get_rsa_pub_key: Loading public key
May 16 15:36:36 saltmaster 2019-05-16 15:36:36,186 [salt.utils.event :742 ][DEBUG   ][62549] Sending event: tag = salt/auth; data = {'result': True, 'act': 'accept', 'id': 'virt-web', 'pub': '-----BEGIN PUBLIC KEY----- [OUR PUBLIC KEY HERE...]-----END PUBLIC KEY-----', '_stamp': '2019-05-16T22:36:36.186534'}
```

### Versions Report

We run the same 2019.2.0 version of Salt on minions and master.
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2019, 01:15:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 11.2-RELEASE-p10
         system: FreeBSD
        version: Not Installed
```

**Comment by dmurphy18** [comment] 2019-05-31 20:55
Wonder if experiencing something similar to what is described in https://github.com/saltstack/salt/issues/44848

**Comment by adam12b1** [comment] 2019-05-31 22:04
@dmurphy18 Thanks much for the reference... and I'm not sure, but I _think_ this would be a separate issue with a different solution because it's about starting up the salt-minion itself, not about restarting other daemons via Salt?

But maybe I'm making too much of that distinction; I'm afraid Salt, Jinja, and even Python are new and mysterious to me (one uncomfortable visitor from the Perlverse here), so my analysis may be off. Perhaps we should try the rc.d fix mentioned in one comment there (`run_rc_command "$1" 2>/dev/null`), although silencing error output is not real appealing as a solution....

**Comment by adam12b1** [comment] 2019-06-03 20:38
Okay, FWIW we've tried that test of redirecting stderr to /dev/null in the salt_minion startup script, and no luck - still (after a number of repetitions) got a minion hung during startup, just after exchanging keys with the master.

Also, since there's talk of zombie procs in that other issue, we're now looking for that - but not finding it. Our hung process is (according to `ps` and `top`) not in any weird state, not marked as zombie, just sitting there idle after apparently using 21.72 seconds of CPU time.
```
# ps auwwx | grep salt
root     2294  0.0  8.1  77788 60484  -  IJ   13:29   0:21.72 /usr/local/bin/python3.6 /usr/local/bin/salt-minion -c /usr/local/etc/salt -d
```

**Comment by sagetherage** [comment] 2020-04-21 18:20
@dmurphy18 can you follow up here?

**Comment by defanator** [comment] 2020-07-22 15:14
Just for the reference, we are experiencing very similar issue here with:

```
# salt -V
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 1.0.3
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-1020-aws
         system: Linux
        version: Ubuntu 20.04 focal
 
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

It is happening while applying a number of different states using `salt-call`. Regardless of state execution result (ok or fail), salt just hangs until Ctrl+C is pressed.

For the reference, here are last lines of debug log, minion:

```
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded highstate.output
local:

Summary for local
------------
Succeeded: 7
Failed:    0
------------
Total states run:     7
Total run time:   2.056 s
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
^C
```

Master:

```
2020-07-22 15:11:30,636 [salt.loaded.int.returner.local_cache:252 ][DEBUG   ][127791] Adding minions for job 20200722151130635594: ['salt-delegate-20200722']
2020-07-22 15:11:30,637 [salt.utils.job   :88  ][INFO    ][127791] Got return from salt-delegate-20200722 for job 20200722151130635594
2020-07-22 15:11:30,637 [salt.utils.event :757 ][DEBUG   ][127791] Sending event: tag = salt/job/20200722151130635594/ret/salt-delegate-20200722; data = {'cmd': '_return', 'id': 'salt-delegate-20200722', 'jid': '20200722151130635594', 'return': {'pkg_|-resolvconf package_|-resolvconf_|-installed': {'name': 'resolvconf', 'changes': {}, 'result': True, 'comment': 'All specified packages are already installed', '__sls__': 'unbound-svc', '__run_num__': 0, 'start_time': '15:11:28.563629', 'duration': 30.673, '__id__': 'resolvconf package'}, 'pkg_|-unbound package_|-unbound_|-latest': {'name': 'unbound', 'changes': {}, 'result': True, 'comment': 'Package unbound is already up-to-date', '__sls__': 'unbound-svc', '__run_num__': 1, 'start_time': '15:11:28.595026', 'duration': 1645.127, '__id__': 'unbound package'}, 'file_|-unbound configuration_|-/etc/unbound/unbound.conf_|-managed': {'changes': {}, 'comment': 'File /etc/unbound/unbound.conf is in the correct state', 'name': '/etc/unbound/unbound.conf', 'result': True, '__sls__': 'unbound-svc', '__run_num__': 2, 'start_time': '15:11:30.244176', 'duration': 10.101, '__id__': 'unbound configuration'}, 'file_|-unbound qname-minimisation.conf_|-/etc/unbound/unbound.conf.d/qname-minimisation.conf_|-managed': {'changes': {}, 'comment': 'File /etc/unbound/unbound.conf.d/qname-minimisation.conf is in the correct state', 'name': '/etc/unbound/unbound.conf.d/qname-minimisation.conf', 'result': True, '__sls__': 'unbound-svc', '__run_num__': 3, 'start_time': '15:11:30.254496', 'duration': 1.621, '__id__': 'unbound qname-minimisation.conf'}, 'service_|-unbound service_|-unbound_|-running': {'name': 'unbound', 'changes': {}, 'result': True, 'comment': 'The service unbound is already running', '__sls__': 'unbound-svc', '__run_num__': 4, 'start_time': '15:11:30.257367', 'duration': 307.432, '__id__': 'unbound service'}, 'service_|-Stop systemd-resolved_|-systemd-resolved_|-dead': {'name': 'systemd-resolved', 'changes': {}, 'result': True, 'comment': 'The service systemd-resolved is already dead', '__sls__': 'unbound-svc', '__run_num__': 5, 'start_time': '15:11:30.565820', 'duration': 43.844, '__id__': 'Stop systemd-resolved'}, 'service_|-Disable systemd-resolved_|-systemd-resolved_|-disabled': {'name': 'systemd-resolved', 'changes': {}, 'result': True, 'comment': 'Service systemd-resolved is already disabled, and is in the desired state', '__sls__': 'unbound-svc', '__run_num__': 6, 'start_time': '15:11:30.610091', 'duration': 16.965, '__id__': 'Disable systemd-resolved'}}, 'retcode': 0, 'out': 'highstate', 'fun': 'state.apply', 'fun_args': ['unbound-svc'], 'arg': ['unbound-svc'], 'tgt_type': 'glob', 'tgt': 'salt-delegate-20200722', '_stamp': '2020-07-22T15:11:30.637361'}
```

This is 100% reproducible here, so please let me know if there's anything else I could obtain from that system in order to help nail down a root cause of the issue.

**Comment by cmcmarrow** [comment] 2020-09-28 23:22
@adam12b1 can you see if this PR https://github.com/saltstack/salt/pull/58364 fixes your hang?

**Comment by adam12b1** [comment] 2020-10-01 22:29
> @adam12b1 can you see if this PR #58364 fixes your hang?

I'm sorry, I'm afraid we had to put our Salt-ification project on the back burner, no longer even installed anywhere, and don't know when we'll be able to get back to it. So I cannot confirm or deny - but appreciate the attention to bug reports!

**Comment by sagetherage** [comment] 2020-10-02 14:49
@adam12b1 we will close this for now as fix with the above mentioned PR, please mention me if you need this reopened in the future. Thank you!

**Closed by sagetherage** 2020-10-02 14:49 UTC
Labels: Bug, Fixed Pending Verification, Linux, Magnesium, Severity: High, ZMQ, salt-call

**Comment by jakehilton** [comment] 2020-11-06 17:07
I recently upgraded to 2019.2.7 from 2019.2.4 for the latest CVE fixes. I am now seeing this hang issue as well. I'm on Ubuntu 18.04.
