### ISSUE TITLE
Infinite loop when providing pki_dir on Windows minion

### ISSUE THREAD

**Issue by vdav** [saltstack/salt#42742] opened 2017-08-04 12:30 UTC
### Description of Issue/Question

When providing a pki_dir in the minion configuration that does not contain a directory call 'salt' in the path, then the minion gets stuck in an infinite loop at startup.

Providing a pki_dir is important when seeding a minion through a different disk.

Problem is from `utils/verify.py` in function `win_verify_env`. The first loop. It is not hard to miss.

### Setup

Have a windows minion with the following configuration.

```
master: your_master
minion: some_name
pki_dir: c:/mypki/minion
```

And create directory "c:/mypki/minion". Add a key pair and master public key.

### Steps to Reproduce Issue

Start the minion, it does not go very far.

### Versions Report

Fails with 2016.11.2, 2016.11.6 and 2017.7.0

Works with 2016.3.1

**Comment by gtmanfred** [comment] 2017-08-04 13:08
Yup that would be a problem, thanks for reporting.

@twangboy can you take a look at this?  It looks like it was added as part of https://github.com/saltstack/salt/commit/2dc45dc97ea

Thanks,
Daniel

**Comment by tsaridas** [comment] 2017-08-07 11:18
connected with 

https://github.com/saltstack/salt/issues/41199

**Comment by gtmanfred** [comment] 2017-08-07 12:29
yup, thanks @tsaridas 

This is a duplicate of #41199

Thanks,
Daniel

**Closed by gtmanfred** 2017-08-07 12:29 UTC
Labels: Bug, Critical, P3, Platform, Windows
