### ISSUE TITLE
'I/O operation on closed file

### ISSUE THREAD

**Issue by jerob** [saltstack/salt#27844] opened 2015-10-10 03:20 UTC
Command :
```console
salt 'web1' state.sls test
```
Error :
```
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f758ee06490>> ignored
```
```yaml
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Debian 8 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Debian 8 
```

**Comment by ogabrielsantos** [comment] 2015-10-11 03:53
@jerob have you defined 'transport' option inside master settings?

**Comment by jerob** [comment] 2015-10-12 09:44
I don't have defined 'transport' option inside master setting.

**Comment by jfindlay** [comment] 2015-10-13 18:18
@jerob, thanks for the report.  Do you have anything in your master config?  Did you upgrade or install a new master?

**Comment by cachedout** [comment] 2015-10-15 15:11
I believe this is fixed at the head of the 2015.8 branch. Is there any chance you could try and reproduce this error with that code?

**Comment by cachedout** [comment] 2015-10-29 22:13
Closed for lack of response. If this is truly not fixed, please comment and we will be glad to re-open.

**Comment by nigelsim** [comment] 2015-12-08 02:35
After upgrading from 2015.5.3 to 2015.8.3 I get the above error. I've not updated any of the config files.

This occurs both with:
salt-call test.version
and
salt '*' test.version

**Comment by cachedout** [comment] 2015-12-23 21:39
If this is solved by upgrading ZeroMQ, I am not sure why this was re-opened since it's not clear what else we can do. Re-closing.

**Closed by cachedout** 2015-12-23 21:39 UTC
Labels: Bug, Core, Fixed Pending Verification, Medium Severity, P3
