### ISSUE TITLE
os: centos6.8 ,salt-minion init scripts run hang, return nothing

### ISSUE THREAD

**Issue by edwin--zhao** [saltstack/salt#39588] opened 2017-02-23 08:43 UTC
### Description of Issue/Question
running service salt-minion start , command return nothing
running /usr/bin/salt-minion -l debug , salt-minion running normally
### Setup
omit

### Steps to Reproduce Issue
# sh -x /etc/init.d/salt-minion status
+ : /usr/bin
+ : /etc
+ : root
+ SALTMINION=/usr/bin/salt-minion
+ SALTCALL=/usr/bin/salt-call
+ : '
root /etc/salt
'
+ SALTMINION_ARGS=
+ SALTMINION_TIMEOUT=30
+ SALTMINION_TICK=1
+ SERVICE=salt-minion
+ '[' -f /etc/default/salt ']'
+ '[' -f /etc/sysconfig/salt ']'
+ RETVAL=0
+ NS_NOTRIM=--notrim
+ ERROR_TO_DEVNULL=/dev/null
+ '[' 1 = 0 ']'
+ main status
+ '[' -n '' ']'
+ netstat --notrim
+ grep -q unrecognized
^C

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by gtmanfred** [comment] 2017-02-23 17:43
I believe this is a duplicate of https://github.com/saltstack/salt/issues/39052 and is solved by the following pull request.

https://github.com/saltstack/salt/pull/39104

This change should be in 2016.11.3 which was just tagged and should have packages soon.

Can you verify?

Thanks,
Daniel

**Comment by edwin--zhao** [comment] 2017-02-24 01:32
@gtmanfred I close the first, 2016.11.3 RPM package updated I will install test again

**Comment by edwin--zhao** [comment] 2017-03-02 03:33
@gtmanfred  test 2016.11.3 the problem is still

# rpm -qf /etc/init.d/salt-minion
salt-minion-2016.11.3-1.el6.noarch

# salt-minion --versions
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

# md5sum /etc/init.d/salt-minion
45a4786cb8d549e3bd936c0a79c5d20a  /etc/init.d/salt-minion

# sh -x /etc/init.d/salt-minion
+ : /usr/bin
+ : /etc
+ : root
+ SALTMINION=/usr/bin/salt-minion
+ SALTCALL=/usr/bin/salt-call
+ : '
root /etc/salt
'
+ SALTMINION_ARGS=
+ SALTMINION_TIMEOUT=30
+ SALTMINION_TICK=1
+ SERVICE=salt-minion
+ '[' -f /etc/default/salt ']'
+ '[' -f /etc/sysconfig/salt ']'
+ RETVAL=0
+ NS_NOTRIM=--notrim
+ ERROR_TO_DEVNULL=/dev/null
+ '[' 0 = 0 ']'
+ main
+ '[' -n '' ']'
+ netstat --notrim
+ grep -q unrecognized

Stuck here

**Comment by gtmanfred** [comment] 2017-03-02 04:03
My apologies, this PR needs to be backported, i didn't realize it was only on develop.

If you add a -n to the netstat command, does this fix the problem?

I have marked that PR to be backported.

**Comment by gtmanfred** [comment] 2017-03-02 04:04
This is most certainly a duplicate of https://github.com/saltstack/salt/issues/39119

So I am going to close this issue.

**Closed by gtmanfred** 2017-03-02 04:04 UTC
Labels: Duplicate

**Comment by edwin--zhao** [comment] 2017-03-02 05:55
@gtmanfred  add a -n to the netstat command fix the problem
Want to update to the RPM package, convenient mass minion updates
