### ISSUE TITLE
Mount.mounted is incompatible with devices that can be mounted multiple times

### ISSUE THREAD

**Issue by dpedu** [saltstack/salt#48280] opened 2018-06-24 04:37 UTC
### Description of Issue/Question

I use glusterfs, which is a network filesystem. Sometimes I mount a glusterfs volume read/write at one mountpoint, and read-only at another mountpoint. But the `mount.mounted` state doesn't let me do this.

When this state is used, the application of the second mountpoint removes the first one. I can't find a way through the other options of `mount.mounted` to have both coexist. 

### Setup

Sls state file:

```
/mnt/realm:
  mount.mounted:
    - device: core00:/realm2
    - fstype: glusterfs
    - mkmnt: True
    - require:
      - pkg: glusterfs-client

/mnt/realmro:
  mount.mounted:
    - device: core00:/realm2
    - fstype: glusterfs
    - mkmnt: True
    - opts: ro
    - require:
      - pkg: glusterfs-client
```

### Steps to Reproduce Issue

1) Apply the above state
2) Observe that only one mount is created, and each time they overwrite eachother

### Versions Report

```Salt Version:
           Salt: 2018.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-23-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

No difference in master/minion version.

**Comment by garethgreenaway** [comment] 2018-06-25 19:31
@dpedu Thanks for the report.  Marking this as a future feature since it would be adding functionality.

**Comment by n-rodriguez** [comment] 2019-05-22 21:44
the same here with nfs mounts.
IMHO this is not a feature but more a bug. It seems that salt use the device as unique key instead of using mount target. Using device as a key is a mistake since the device can be repeated multiple times.
Example with nfs:

```sh
filer1.example.priv:/data/storage/foo/docs_pdf   /data/www/foo/shared/docs_pdf nfs vers=4.0,proto=tcp  0 0
filer1.example.priv:/data/storage/foo/docs_pdf   /data/www/bar/shared/docs_pdf_foo nfs vers=4.0,proto=tcp  0 0
filer1.example.priv:/data/storage/bar/docs_pdf   /data/www/bar/shared/docs_pdf_bar nfs vers=4.0,proto=tcp  0 0
```
Salt should use the destination as unique key because the destination is supposed to be unique. (mount over mount, wtf?)

**Comment by n-rodriguez** [comment] 2019-05-22 21:57
https://github.com/saltstack/salt/blob/b050ccf78f4b2744afaf4670bf947566ad9a6431/salt/states/mount.py#L126

**Comment by n-rodriguez** [comment] 2019-05-22 22:01
> It seems that salt use the device as unique key instead of using mount target.

nope. `salt '*' mount.active`

**Comment by garethgreenaway** [comment] 2019-08-29 22:25
@dpedu @n-rodriguez Apologies for the delay in circling back to this one. @n-rodriguez You're absolutely right, this is a bug in how we're handling mounts for filesystems that support multiple mount points.  I believe I've identified the issue and have a fix, but just wanted to confirm the behavior you're both seeing.  Are the shares being mounted and the issue is when it comes to persisting the entry in /etc/fstab or are the shares not being mounted at all?  Thanks!

**Comment by n-rodriguez** [comment] 2019-08-29 22:38
>  Are the shares being mounted and the issue is when it comes to persisting the entry in /etc/fstab or are the shares not being mounted at all?

If I remember it's when it comes to persisting

**Comment by garethgreenaway** [comment] 2019-08-29 22:49
@n-rodriguez Perfect  The issue is in the mount module when it's setting the fstab in the `set_fstab` function and is matching on the device instead of the name.  If you wouldn't find trying the following patch:
```

**Comment by n-rodriguez** [comment] 2019-08-30 00:21
@garethgreenaway awesome :+1:

**Comment by n-rodriguez** [comment] 2020-02-11 14:04
@garethgreenaway Hi! I think this issue can be closed. Thank you!

**Closed** 2020-03-23 03:21 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P2
