### ISSUE TITLE
[BUG] 06.11.2020 -- salt-ssh -- salt doesn't properly recognize appropriate python versions

### ISSUE THREAD

**Issue by paralllax** [saltstack/salt#57647] opened 2020-06-12 00:42 UTC
**Description**

I have a Centos 7 master and an Centos 7 client. salt-ssh exits with the following error:

```
ERROR: Python version error. Recommendation(s) follow:
- Install Python 2.6/2.7 Salt dependencies on the Salt SSH 
  master to interact with Python 2.6/2.7 targets
- Install Python 3 on the target machine(s)
```

Centos 7 Client has python versions: 2.6 & 2.7.5. 

Centos 7 Host, where I run salt-ssh from, has python 2.6, 2.7.5, and python 3.6.8. 

I believe this may be a bug as I recently ran this from a manjaro box, identical setup, and there were 0 issues. I had to rekick the manjaro box to centos over the weekend, arrived at this issue, and have been unable to find a solution.

**Setup**

Here is the roster file:

```
<REDACTED>:
  host: <REDACTED>
  user: <REDACTED>
  passwd: <REDACTED>
  sudo_user: <REDACTED>
  thin_dir: /home/<REDACTED>/.salt_auto
```

**Steps to Reproduce the behavior**
Here is what I ran, followed by the trace log output. It is confusing to me, as it looks like it searches and eventually finds python2.7, and successfully runs, then returns that it couldn't find it. Uncertain if it is relevant, but running with `-r` for raw ssh commands will succeed without issues. The error mentioned occurs regardless of whether I try to apply states, or run other execution modules.

```[~]$ salt-ssh -c ~/.salt '*' 'uptime'
[...]
ERROR: Python version error. Recommendation(s) follow:
- Install Python 2.6/2.7 Salt dependencies on the Salt SSH 
  master to interact with Python 2.6/2.7 targets
- Install Python 3 on the target machine(s)

--------------------------------------------------------------------------------
echo "ERROR: Unable to locate appropriate python command" >&2
exit $EX_PYTHON_INVALID
EOF
[TRACE   ] <REDACTED>'s password:
[TRACE   ] + SUDO=
+ '[' -n '' ']'
+ SUDO_USER=<REDACTED>
+ '[' '' ']'
+ '[' '' ']'
+ EX_PYTHON_INVALID=10
+ PYTHON_CMDS='python3 python27 python2.7 python26 python2.6 python2 python'
[TRACE   ] + for py_cmd in '$PYTHON_CMDS'
+ command -v python3
+ continue
+ for py_cmd in '$PYTHON_CMDS'
+ command -v python27
+ continue
+ for py_cmd in '$PYTHON_CMDS'
+ command -v python2.7
+ python2.7 -c 'import sys; sys.exit(not (sys.version_info >= (2, 6)));'
[TRACE   ] ++ python2.7 -c 'from __future__ import print_function;import sys; print(sys.executable);'
[TRACE   ] + py_cmd_path=/usr/bin/python2.7
++ command -v python2.7
[TRACE   ] + cmdpath=/usr/bin/python2.7
+ grep 'shell script'
+ file /usr/bin/python2.7
[TRACE   ] + exec /usr/bin/python2.7 -c 'import base64;
[...]
[TRACE   ] "").decode("utf-8"))'
[DEBUG   ] End of file(EOL). Brain-dead platform.
[TRACE   ] STDOUT <REDACTED>
<REDACTED>'s password: 
/usr/bin/scp

[TRACE   ] STDERR <REDACTED>
+ SUDO=
+ '[' -n '' ']'
+ SUDO_USER=<REDACTED>
+ '[' '' ']'
+ '[' '' ']'
+ EX_PYTHON_INVALID=10
+ PYTHON_CMDS='python3 python27 python2.7 python26 python2.6 python2 python'
+ for py_cmd in '$PYTHON_CMDS'
+ command -v python3
+ continue
+ for py_cmd in '$PYTHON_CMDS'
+ command -v python27
+ continue
+ for py_cmd in '$PYTHON_CMDS'
+ command -v python2.7
+ python2.7 -c 'import sys; sys.exit(not (sys.version_info >= (2, 6)));'
++ python2.7 -c 'from __future__ import print_function;import sys; print(sys.executable);'
+ py_cmd_path=/usr/bin/python2.7
++ command -v python2.7
+ cmdpath=/usr/bin/python2.7
+ grep 'shell script'
+ file /usr/bin/python2.7
+ exec /usr/bin/python2.7 -c 'import base64;
[...]
[DEBUG   ] RETCODE <REDACTED>: 10
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'<REDACTED>': {'stdout': 'ERROR: Python version error. Recommendation(s) follow:\n- Install Python 2.6/2.7 Sa
lt dependencies on the...
```
If I remove the thin directory on the client, and run without using raw ssh commands, it returns there was an issue dpeloying the thin, however on the client, it looks like it deployed successfully.

Master:
```
[~]$ time salt-ssh -c ~/.salt '*' 'uptime'
[ERROR   ] ERROR: Failure deploying thin, retrying:
STDOUT:
<REACTED>'s password: 

STDERR:

RETCODE: 10
<REACTED>:
    ----------
    retcode:
        10
    stderr:
    stdout:
        ERROR: Python version error. Recommendation(s) follow:
        - Install Python 2.6/2.7 Salt dependencies on the Salt SSH 
          master to interact with Python 2.6/2.7 targets
        - Install Python 3 on the target machine(s)
```

Client during and after install of thin:

```
[~]# ls /home/<REACTED>/.salt_auto/
salt-thin.tgz
[~]# ls /home/<REACTED>/.salt_auto/
code-checksum  minion  py3  pyall  salt-call  supported-versions  version
```

**Expected behavior**
salt-ssh runs execution modules, or anything really that isn't raw ssh, without an error. 

**Versions Report**

```
[~]$ salt --versions-report

Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core
```
From the thin client:

```
[ ~]# cat /home/<REACTED>/.salt_auto/version 
3000.3
```

**Additional context**

I am brand new to salt! Started learning a few weeks ago, apologies if I missed something simple, or haven't got all the lingo down yet.

**Comment by paralllax** [comment] 2020-06-12 01:14
Reading back, I just realized it references dependencies specifically for python2.6/2.7... so I installed those on the master just to be certain with:

```
yum install python2-libs python2-pip python2-setuptools python2-pyyaml python2-crypto python2-idna python2-jinja2 m2crypto python2-msgpack python2-psutil python2-pysocks python2-requests python2-six python2-urllib3 python2-zmq
```

The other 3 were already satisfied:

```
$ pip install chardet markupsafe pycurl
Requirement already satisfied (use --upgrade to upgrade): chardet in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib64/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pycurl in /usr/lib64/python2.7/site-packages
```

Here is the version report again

```
[~]$ salt --versions-report 
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 
```

Unfortunately the same error is returned as before:

```
<REDACTED>:
    ----------
    retcode:
        10
    stderr:
    stdout:
        ERROR: Python version error. Recommendation(s) follow:
        - Install Python 2.6/2.7 Salt dependencies on the Salt SSH 
          master to interact with Python 2.6/2.7 targets
        - Install Python 3 on the target machine(s)
```

**Comment by xeacott** [comment] 2020-06-16 23:13
Thanks for the report @paralllax someone on @saltstack/team-ssh ; any insight on this one? 😄

**Comment by paralllax** [comment] 2020-06-25 22:04
Thank you @xeacott 

As a note, I updated to the latest version today, and the same issue persists

```
$ time salt-ssh -c ~/.salt '*' 'uptime'
[ERROR   ] ERROR: Failure deploying thin, retrying:
STDOUT:
<REDACTED>@<REDACTED>'s password: 

STDERR:

RETCODE: 10
<REDACTED>:
    ----------
    retcode:
        10
    stderr:
    stdout:
        ERROR: Python version error. Recommendation(s) follow:
        - Install Python 2.6/2.7 Salt dependencies on the Salt SSH 
          master to interact with Python 2.6/2.7 targets
        - Install Python 3 on the target machine(s)
```

Note that similar to before, it still deploys the thin client despite the error:

```
# ls /home/rack/.salt_auto/
code-checksum  minion  py3  pyall  salt-call  supported-versions  version
```

I hadn't noticed, it seems to deploy the py3 thin client instead of py2 . I don't know python super well, but it seems like the error happens somewhere around here in salt/utils/thin.py.

On the thin client:

```
[ .salt_auto]# cat supported-versions 
py3:3:0
[ .salt_auto]# ls py3
backports_abc.py  markupsafe             tornado
distro.py         ssl_match_hostname.py  yaml
```

From the most recent clone of the salt repo under salt/utils/thin.py:

```
    for py_ver, tops in _six.iteritems(copy.deepcopy(tops)):
        py_ver = int(py_ver)
        if py_ver == 2:
            pymap.append("py2:2:7")
        elif py_ver == 3:
            pymap.append("py3:3:0")
```

```
$ salt --versions-report
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```

**Comment by paralllax** [comment] 2020-06-25 22:06
Thank you @xeacott 

As a note, I updated to the latest version today, and the same issue persists

```
$ time salt-ssh -c ~/.salt '*' 'uptime'
[ERROR   ] ERROR: Failure deploying thin, retrying:
STDOUT:
<REDACTED>@<REDACTED>'s password: 

STDERR:

RETCODE: 10
<REDACTED>:
    ----------
    retcode:
        10
    stderr:
    stdout:
        ERROR: Python version error. Recommendation(s) follow:
        - Install Python 2.6/2.7 Salt dependencies on the Salt SSH 
          master to interact with Python 2.6/2.7 targets
        - Install Python 3 on the target machine(s)
```

Note that similar to before, it still deploys the thin client despite the error:

```
# ls /home/<REDACTED>/.salt_auto/
code-checksum  minion  py3  pyall  salt-call  supported-versions  version
```

I hadn't noticed, it seems to deploy the py3 thin client instead of py2 . I don't know python super well, but it seems like the error happens somewhere around here in salt/utils/thin.py.

On the thin client:

```
[ .salt_auto]# cat supported-versions 
py3:3:0
[ .salt_auto]# ls py3
backports_abc.py  markupsafe             tornado
distro.py         ssl_match_hostname.py  yaml
```

From the most recent clone of the salt repo under salt/utils/thin.py:

```
    for py_ver, tops in _six.iteritems(copy.deepcopy(tops)):
        py_ver = int(py_ver)
        if py_ver == 2:
            pymap.append("py2:2:7")
        elif py_ver == 3:
            pymap.append("py3:3:0")
```

```
$ salt --versions-report
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```

**Comment by isbm** [comment] 2020-06-25 22:49
I don't get it. I fixed that myself two years ago. Broken again?? 🤦

**Comment by paralllax** [comment] 2020-07-15 02:49
Sadly it seems so :/ Though it was quite a while back, would you happen to know the pull request? I don't know python all too well, but I could try and check it out.

**Comment by Ch3LL** [comment] 2020-09-01 14:10
I just tested on 3000.3 and this is working. Can you make sure to remove your thin from /var/cache/salt/master/thin/ and run the command again. 

And if you could look at the debug output and look for where it says `Adding module to the tops: "salt"` for example and `Packing "salt" to "pyall" destination`. Want to make sure you arent running into any errors, for example if it was not able to add a certain module or it cant find python

now what i did discover is this is actually broken on the head of master. We dropped python2 support and do not allow any python2 code to run, i'll look into how we can work around this.

**Comment by Ch3LL** [comment] 2020-09-01 15:49
okay I don't think we can still allow python2 modules to be put into the tar, because we do not allow python2 code to run throughout salt, so even if python2 is included in the tar ball a user could not run salt commands on the target host anyways.I think the best thing to do here is remove the python2 code here and update the documentation/error reporting. Then a user will have two options- to use the `ssh_pre_flight` option (https://docs.saltstack.com/en/latest/topics/ssh/roster.html#ssh-pre-flight) to install python3 on the target host before salt-call runs or they will be able to use this feature https://github.com/saltstack/salt/issues/56944 which will be added in Magnesium.

To make things clear for your use case @paralllax tho it should still be working on versions <3001

**Comment by paralllax** [comment] 2020-09-01 21:32
Thank you so much! That makes sense, much appreciated. 

I moved back to version 3000.3 and I purged the thin client from the cache and on the minion as well. I tested once more. Looking at the section requested in the debug logs, it looks like there is an error there. 

```
[DEBUG   ] Adding module to the tops: "salt.ext.backports_abc"                                                                              [544/1883]
[DEBUG   ] Failed collecting tops for Python binary python2.
[DEBUG   ] b'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nImportError: No module named salt.utils.thin\n'
[DEBUG   ] Packing default libraries based on current Salt version
```

I am uncertain why is can't find that module, but am looking to get more information. If you have any ideas, let me know! Thank you again.

**Comment by Ch3LL** [comment] 2020-09-03 14:13
`salt.utils.thin` is a part of salt. If you try to import that with your python 2 binary what happens? `python2 -c "import salt.utils.thin"`

**Comment by paralllax** [comment] 2020-09-03 20:40
It seems it works with python3 but not with python2. python2 is the default version which I suppose is why it errors out. 

```
$ python2 -c 'import salt.utils.thin'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named salt.utils.thin
```

```
$ python3 -c 'import salt.utils.thin'
$
```

I have salt-3000.3 installed

```
$ rpm -qa salt*
salt-syndic-3000.3-1.el7.noarch
salt-master-3000.3-1.el7.noarch
salt-cloud-3000.3-1.el7.noarch
salt-3000.3-1.el7.noarch
salt-ssh-3000.3-1.el7.noarch
salt-api-3000.3-1.el7.noarch
salt-minion-3000.3-1.el7.noarch
```

it looks like salt isn't installed for python2

```
$ ls /usr/lib/python3.6/site-packages/salt/
acl      client      daemons        ext            key.py     matchers   output      __pycache__  runner.py    spm          templates  utils
auth     cloud       defaults       fileclient.py  loader.py  metaproxy  payload.py  queues       runners      state.py     thorium    _version.py
beacons  _compat.py  engines        fileserver     log        minion.py  pillar      renderers    scripts.py   states       tokens     version.py
cache    config      exceptions.py  grains         _logging   modules    platform    returners    sdb          syspaths.py  tops       wheel
cli      crypt.py    executors      __init__.py    master.py  netapi     proxy       roster       serializers  template.py  transport
$ ls /usr/lib/python2.7/site-packages/*salt*
ls: cannot access /usr/lib/python2.7/site-packages/*salt*: No such file or directory
```

I installed it, and it looks like it can import the module now

```
$ pip2 install salt==3000.3 salt-ssh=3000.3
[...]
$ python2 -c 'import salt.utils.thin'
$
```

However it seems to still fail with the same error from previously when attempting to run salt-ssh

```
    stdout:
        ERROR: Python version error. Recommendation(s) follow:
        - Install Python 2.6/2.7 Salt dependencies on the Salt SSH 
          master to interact with Python 2.6/2.7 targets
        - Install Python 3 on the target machine(s)
```

I checked the trace level log, and it returns the same errors when checking each python version. It seems like it works with python2.7, but still fails regardless. 

```
echo "ERROR: Unable to locate appropriate python command" >&2
[...]
echo "ERROR: Unable to locate appropriate python command" >&2
[...]
+ PYTHON_CMDS='python3 python27 python2.7 python26 python2.6 python2 python'
+ for py_cmd in '$PYTHON_CMDS'
+ command -v python3
+ continue
+ for py_cmd in '$PYTHON_CMDS'
+ command -v python27
+ continue
+ for py_cmd in '$PYTHON_CMDS'
+ command -v python2.7
+ python2.7 -c 'import sys; sys.exit(not (sys.version_info >= (2, 6)));'
++ python2.7 -c 'from __future__ import print_function;import sys; print(sys.executable);'
+ py_cmd_path=/usr/bin/python2.7
++ command -v python2.7
+ cmdpath=/usr/bin/python2.7
+ grep 'shell script'
+ file /usr/bin/python2.7
+ exec /usr/bin/python2.7 -c 'import base64;
[...]
        ERROR: Python version error. Recommendation(s) follow:...
```

**Comment by Ch3LL** [comment] 2020-09-04 10:34
something must not be getting added to the tarball correctly to interact with python2.

on the host you are targeting you should see a py2 directory similar to this: 

```
[root@localhost ~]# ls /var/tmp/.root_e5ce0d_salt/py2/
backports_abc.py   concurrent  singledispatch_helpers.py   singledispatch.py   yaml
backports_abc.pyc  markupsafe  singledispatch_helpers.pyc  singledispatch.pyc
```

the `.root` directory will be different for you - (`/var/tmp/<user>_<FQDNUUID>_salt`)

**Comment by paralllax** [comment] 2020-09-08 23:04
It looks like the behavior of the thin_dir on the minion has remained the same as before unfortunately where it only recognizes python3 as the supported version, and doesn't seem to include py2. I am uncertain why as the client doesn't have python3 installed. The below commands are run on the client.

```
# find / -type d -name py2
# updatedb
# locate salt | grep py2
# 
```
```
# ls -a /home/<redacted>/.salt_auto/
.  ..  code-checksum  minion  py3  pyall  salt-call  supported-versions  .thin-gen-py-version  version
```

**Comment by Ch3LL** [comment] 2020-09-09 19:33
can you include the debug output when the thin is generated? particularly the log statements i refereed to above for python2.

**Comment by paralllax** [comment] 2020-09-09 20:08
Hmmm well, miraculously, it seems to have worked this time. I removed the thin_dir on the client and the cache on the master (`~/.salt/cache/master` for me) for probably the 15th time, and it seems to have worked. I am not sure why it didn't previously as I didn't do anything different that I can remember... I tried it again, removing the cache and thin dir and all remains well. py2 is copied over and salt-ssh works! 

A bit anti-climatic but I guess we can close this one out! Thank you again for all the help.

**Comment by isbm** [comment] 2020-09-09 20:31
Yeah, the Salt SSH has by a design has this weakness that not just cache should be flushed on a client but also on a master and each Salt update needs to regenerate the thin.

@Ch3LL time to think of attaching Salt version to a generated thin and at least check that on each master start-up, so once updated, it force-regenerate it? And check if client has newest thin too, because whilst it supposed to work already, it may be different from the updated one.

**Comment by paralllax** [comment] 2020-09-09 21:38
I see, understandable. Sounds like a good idea. 

Sorry as well, I may have prematurely closed the issue, I'll leave it opened.

**Comment by Ch3LL** [comment] 2020-09-10 19:23
`on each master start-up` i'm not quit following here, salt-ssh does not require a master, also the thin does have versioning added to it. @paralllax 's use case is not related to a Salt upgrade, but related to python 2 not having all the required dependencies when the thin was initially generated. I'm not following the request clearly enough.

**Comment by isbm** [comment] 2020-09-10 23:00
Oh well. Ok. Salt SSH takes thin from where?.. After cache was flushed, things started to work. Conclusions obvious.

**Comment by Ch3LL** [comment] 2020-09-11 11:58
The cache needed to be flushed to ensure a new thin was generated with the python 2 dependencies after they were installed correctly. I do not see how this is tied to a Salt upgrade, which was not included in this use case. We could improve things so a new thin is generated after all the python 2 dependencies are installed but my PR removes that part of the code going forward.

**Comment by isbm** [comment] 2020-09-11 12:10
@Ch3LL well, that's what you've just confirmed in different words: "after they were installed correctly". That is, if ecosystem of Salt was changed, thin should be immediately obsoleted and regenerated. I do agree it is not that easy due to Salt SSH design choices. I still not sure if current design makes any sense in terms of keeping stuff in `/tmp/` rather then install it in `/opt` permanently into a self-contained environment and have a passive client there instead. So you could do a simple SSH call and invoke fully done client, rather then sending limited thin back and forth. Salt SSH is anyway not client-less technically, it just feels so.

**Comment by Ch3LL** [comment] 2020-09-11 12:25
I'm going to close this issue then, because yes it would have been great if the thin was generated after the python2 dependencies were installed correctly, but my PR removes this part of the code since python 2 is no longer supported. As you stated @isbm things can be improved here in general though and we are currently working on heist (https://gitlab.com/saltstack/pop/heist) which does improve on some of the flaws of Salt-SSH and runs a full salt minion and does not use the thin concept anymore.

**Closed by Ch3LL** 2020-09-11 12:25 UTC
Labels: Bug, Magnesium, Regression, Salt-SSH, Severity: Critical
