### ISSUE TITLE
test=test functionality for state.sls_id

### ISSUE THREAD

**Issue by wes-novack** [saltstack/salt#25847] opened 2015-07-29 22:03 UTC
When running state.sls_id , if you append test=test to the command, it executes the command and makes changes, without actually running a test, showing diffs, etc. Please add test=test functionality to state.sls_id !

**Comment by UtahDave** [comment] 2015-07-30 20:25
What versions of Salt are you seeing this in?

**Comment by wes-novack** [comment] 2015-07-30 22:44
Master: 
salt 2015.5.2 (Lithium)

Minions:
salt-call 2015.5.2 (Lithium)
salt-call.exe 2014.7.2 (Helium)

**Comment by jfindlay** [comment] 2015-07-31 23:50
@wes-novack, thanks for the report.

**Comment by thatch45** [comment] 2015-09-08 21:03
I am closing this out, sorry @wes-novack but if we add this functionality in then we would logically need to broaden how we evaluate command line booleans to be less than predictable. Please stick with test=True

**Comment by wes-novack** [comment] 2015-09-08 21:19
Howdy @thatch45 I think there was a misunderstanding here. Whether you use test=test or test=true doesn't matter, neither are currently respected when calling state.sls_id

**Comment by thatch45** [comment] 2015-09-08 21:20
Oh, THAT is a critical bug! We will get on that right away, reopened!

**Comment by thatch45** [comment] 2015-09-08 21:25
hmm, I can't replicate this, looks like the code to add the test=True check was added when the function was written:
https://github.com/saltstack/salt/commit/3b20382505056bc47545fe2665d0ff3bf1e01572

**Comment by cachedout** [comment] 2015-09-08 21:25
@wes-novack Coud you please show us a reproduceable test case? I don't see this happening:

```
 % sudo salt-call --local  state.sls_id test_it test_it test=true                                              (git)-[v2015.5.2] 
15:24:59,491 [salt.state                               ][INFO    ] Loading fresh modules for state activity
15:24:59,498 [salt.fileclient                          ][INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test_it.sls'
15:24:59,603 [gnupg                                      ][INFO    ] Log opened: Tue Sep  8 21:24:59 2015 UTC
15:24:59,675 [salt.loaded.int.module.cmdmod              ][INFO    ] Executing command 'npm --version' in directory '/home/mp'
15:24:59,935 [salt.state                                          ][INFO    ] Running state [test_it] at time 15:24:59.934581
15:24:59,935 [salt.state                                          ][INFO    ] Executing state test.succeed_without_changes for test_it
15:24:59,935 [salt.state                                          ][INFO    ] If we weren't testing, this would be a success!
15:24:59,935 [salt.state                                          ][INFO    ] Completed state [test_it] at time 15:24:59.935161
local:
----------
          ID: test_it
    Function: test.succeed_without_changes
      Result: True
     Comment: If we weren't testing, this would be a success!
     Started: 15:24:59.934581
    Duration: 0.58 ms
     Changes:   

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
mp@silver ~/devel/salt/salt/modules
```

**Comment by thatch45** [comment] 2015-09-08 21:28
I wonder if this is a case of a rouge state module that made changes regardless of the test argument. A case where it does not work would shed light on this if it is the case

**Comment by wes-novack** [comment] 2015-09-08 21:33
It's definitely happened in the past when attempting to execute an ID that uses file.managed. I'll do some testing again and report back.

**Comment by wes-novack** [comment] 2015-09-08 21:46
Okay, I was mistaken. 

test=True does seem to work for state.sls_id
test=test does NOT work with state.sls_id

In contrast, both test=True AND test=test works when calling state.sls. So why would test=test work for one and not the other? I had always used test=test rather than test=True.

**Comment by basepi** [comment] 2015-11-19 17:24
I'm guessing the check against that test value in state.sls is just checking for truthiness rather than True. In any case, test=test is not supported, please use test=True.

**Closed by basepi** 2015-11-19 17:24 UTC
Labels: Bug, Confirmed, Core, Critical, P4

**Comment by wes-novack** [comment] 2015-11-19 17:26
Will do, thank you.
