### ISSUE TITLE
multi-syndic environment the master use list tgt_type return many a time 

### ISSUE THREAD

**Issue by slhu91** [saltstack/salt#48084] opened 2018-06-13 09:04 UTC
### Description of Issue/Question
Salt-master has multiple syndics and when I use list to manipulate minions on the master, it returns one success and multiple failures。

### Setup
![image](https://user-images.githubusercontent.com/14175152/41341264-e294f8e2-6f2b-11e8-9157-2f33c33daa7a.png)

### Versions Report
![image](https://user-images.githubusercontent.com/14175152/41341049-576caf3a-6f2b-11e8-950c-c2cc6f115764.png)

**Comment by Ch3LL** [comment] 2018-06-13 20:08
duplicate of https://github.com/saltstack/salt/issues/47199  can you try 2018.3.1 should be fixed there.

**Closed** 2018-06-14 01:34 UTC
Labels: Duplicate, Fixed Pending Verification
