### ISSUE TITLE
salt-runner: RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by schasi** [saltstack/salt#43668] opened 2017-09-21 11:10 UTC
### Description of Issue/Question
When trying to use "parallel: True" with salt.runner and salt.state, I get a "RuntimeError: maximum recursion depth exceeded" error.

### Setup
orch.sls:
```
test-vm:
  salt.runner:
    - name: cloud.profile
    - prof: FreeBSD-2C-2G
    - provider: ovirt
    - instances:
      - Prod-Test-1.ocn.sh
    - opts:
        minion:
          master: Prod-Saltmaster-1.ocn.sh
    - parallel: True

test-setup:
  salt.state:
    - tgt: "Prod-Test-1.ocn.sh"
    - highstate: True
    - require:
      - salt: test-vm
```

### Steps to Reproduce Issue

Run the following command:
`salt-run -l debug state.orch orch.test saltenv=prod`

The following exception occurs:
```
[DEBUG   ] Runner return: Exception occurred in runner state.orch: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 392, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/runners/state.py", line 82, in orchestrate
    orchestration_jid=orchestration_jid)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 1109, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2515, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2008, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2245, in call_chunk
    status, reqs = self.check_requisite(low, running, chunks, pre=True)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2148, in check_requisite
    return self.check_requisite(low, running, chunks, pre)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2148, in check_requisite
    return self.check_requisite(low, running, chunks, pre)
...
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2148, in check_requisite
    return self.check_requisite(low, running, chunks, pre)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2148, in check_requisite
    return self.check_requisite(low, running, chunks, pre)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2088, in check_requisite
    self.reconcile_procs(running)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 2040, in reconcile_procs
    if not proc.is_alive():
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 158, in is_alive
    self._popen.poll()
RuntimeError: maximum recursion depth exceeded
```

### Versions Report
master:
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Aug 25 2017, 23:46:22)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE
         system: FreeBSD
        version: Not Installed

minion:
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Aug 15 2017, 01:13:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE
         system: FreeBSD
        version: Not Installed

**Comment by gtmanfred** [comment] 2017-09-22 14:59
Does this happen if you remove the required?

Thanks,
Daniel

**Comment by schasi** [comment] 2017-09-22 15:12
It gives me a different exception if I do that:
```
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/utils/process.py", line 647, in _run
    return self._original_run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1696, in _call_parallel_target
    troot = os.path.join(self.opts['cachedir'], self.jid)
  File "/usr/local/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/site-packages/salt/utils/process.py", line 647, in _run
    return self._original_run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1696, in _call_parallel_target
    troot = os.path.join(self.opts['cachedir'], self.jid)
  File "/usr/local/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by gtmanfred** [comment] 2017-09-22 15:14
Hrm, it looks like parallel doesn't work for orchestrate states right now.  I am marking this as bug.

We will work on getting it fixed,

Thanks for reporting,
Daniel

**Comment by gtmanfred** [comment] 2017-09-22 15:28
This second one is caused by the fact that there is no jid set on the orchestration jobs, and even if you pass in an orchestration_jid on the state.orch call, it never gets set for `self.jid` State class, so the os.path.join fails.

As for the recursion error, it sounds like this may be caused by recursion being used to check requirements.

Thanks for reporting.
Daniel

**Comment by angeloudy** [comment] 2018-05-07 04:25
having the same issue here. Only happens when I enable parallel

**Comment by gtmanfred** [comment] 2018-05-07 12:49
This should be fixed in the next releases

https://github.com/saltstack/salt/pull/46023

**Closed by gtmanfred** 2018-05-07 12:49 UTC
Labels: Bug, Core, High Severity, P2, Runners, team-core
