### ISSUE TITLE
[BUG] salt.state.file.managed handles ignores parameter skip_verify when parameter source is a list

### ISSUE THREAD

**Issue by olafurj** [saltstack/salt#60472] opened 2021-06-30 18:56 UTC
**Description**

salt.state.file.managed handles ignores parameter skip_verify when parameter source is a list 

**Setup**
test.sls
```
/tmp/file:
  file.managed:
    - source:
      - https://example.com/somefile
    - skip_verify: True
    - replace: True
    - keep_source: False
    - makedirs: True
```

**Steps to Reproduce the behavior**
salt '*' state.apply test

**Expected behavior**
Download the file from https://example.com/somefile without verifing hash (no HTTP HEAD request) and store as /tmp/file on the minions

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: 1.1.0
      M2Crypto: 0.36.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: 3.10.1
  pycryptodome: Not Installed
        pygit2: 1.4.0
        Python: 3.8.10 (default, Jun 14 2021, 10:46:13)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: openbsd 6.9 
        locale: utf-8
       machine: amd64
       release: 6.9
        system: OpenBSD
       version: OpenBSD 6.9 

```
</details>

Same thing works correctly if source is changed to a single string

```
/tmp/file:
  file.managed:
    - source: https://example.com/somefile
    - skip_verify: True
    - replace: True
    - keep_source: False
    - makedirs: True
```

**Comment by garethgreenaway** [comment] 2021-07-15 22:44
@olafurj Thanks for the report.  So far I haven't been able to reproduce this one.  When specifying multiple sources Salt will check each one and make sure it's a valid source and if not, skip to the next one.  When I specify one valid source and one invalid source then it works as expected, when I specify one invalid source then I receive the expected message, `Unable to manage file: none of the specified sources were found`.  Can you share the output that you're seeing?

**Comment by garethgreenaway** [comment] 2021-07-27 16:56
@olafurj Following on this one and seeing if you're able to provide the output that you're seeing when this doesn't work as you expected it to.  Thanks!

**Comment by garethgreenaway** [comment] 2023-08-28 18:29
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.

**Closed by garethgreenaway** 2023-08-28 18:29 UTC
Labels: Bug, info-needed, Pending-Discussion
