### ISSUE TITLE
rabbitmq_user.present Errors if user exists.

### ISSUE THREAD

**Issue by rtaft** [saltstack/salt#56258] opened 2020-02-26 21:19 UTC
### Description of Issue
When using rabbitmq_user.present, the user is created the first time around.  After that, the salt function errors with 
```
Error: RabbitMQ command failed: Error:
              {:undef, [{:rabbit_auth_backend_internal, :check_user_login, ["USERNAME", [password: "PASSWORD"]], []}, {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 680]}, {:rpc, :"-handle_call_call/6-fun-0-", 5, [file: 'rpc.erl', line: 197]}]}
```
### Setup
```
rabbitmq_add_myuser_user:
  rabbitmq_user.present:
    - name: USERNAME
    - password: PASSWORD
    - tags:
      - administrator
    - runas: rabbitmq
    - perms:
      - 'vhost1':
        - '.*'
        - '.*'
        - '.*'
      - 'vhost2':
        - '.*'
        - '.*'
        - '.*'
```

### Steps to Reproduce Issue
```
2020-02-26 15:52:57,531 [salt.template    :30  ][PROFILE ][4855] Time (in seconds) to render '/var/cache/salt/minion/files/base/rabbitmq/state.sls' using 'yaml' renderer: 0.00201606750488
2020-02-26 15:52:57,532 [salt.utils.lazy  :104 ][DEBUG   ][4855] LazyLoaded config.get
2020-02-26 15:52:57,532 [salt.loaded.int.module.config:483 ][DEBUG   ][4855] key: gpg_keydir, ret: _|-
2020-02-26 15:52:57,532 [salt.loaded.int.render.gpg:355 ][DEBUG   ][4855] Reading GPG keys from: /etc/salt/gpgkeys
2020-02-26 15:52:57,533 [salt.template    :30  ][PROFILE ][4855] Time (in seconds) to render '/var/cache/salt/minion/files/base/rabbitmq/state.sls' using 'gpg' renderer: 0.00186109542847
2020-02-26 15:52:57,535 [salt.utils.lazy  :104 ][DEBUG   ][4855] LazyLoaded rabbitmq_user.present
2020-02-26 15:52:57,535 [salt.state       :1867][INFO    ][4855] Running state [USERNAME] at time 15:52:57.535303
2020-02-26 15:52:57,535 [salt.state       :1900][INFO    ][4855] Executing state rabbitmq_user.present for [USERNAME]
2020-02-26 15:52:57,538 [salt.utils.lazy  :104 ][DEBUG   ][4855] LazyLoaded rabbitmq.user_exists
2020-02-26 15:52:57,540 [salt.utils.lazy  :104 ][DEBUG   ][4855] LazyLoaded cmd.run_all
2020-02-26 15:52:57,540 [salt.loaded.int.module.cmdmod:397 ][INFO    ][4855] Executing command [u'/usr/sbin/rabbitmqctl', u'list_users', u'-q'] as user 'rabbitmq' in directory '/var/lib/rabbitmq'
2020-02-26 15:52:57,541 [salt.loaded.int.module.cmdmod:501 ][DEBUG   ][4855] env command: (u'su', u'-s', u'/bin/sh', u'-', u'rabbitmq', u'-c', '/usr/bin/python2')
2020-02-26 15:52:58,307 [salt.loaded.int.module.cmdmod:840 ][DEBUG   ][4855] stdout: user	tags USERNAME	[administrator]
2020-02-26 15:52:58,308 [salt.loaded.int.module.cmdmod:397 ][INFO    ][4855] Executing command [u'/usr/sbin/rabbitmqctl', u'status'] as user 'rabbitmq' in directory '/var/lib/rabbitmq'
2020-02-26 15:52:58,308 [salt.loaded.int.module.cmdmod:501 ][DEBUG   ][4855] env command: (u'su', u'-s', u'/bin/sh', u'-', u'rabbitmq', u'-c', '/usr/bin/python2')
2020-02-26 15:52:59,070 [salt.loaded.int.module.cmdmod:840 ][DEBUG   ][4855] stdout: Status of node rabbit@rabbitmqqa-mm ...
Runtime

OS PID: 19193
OS: Linux
Uptime (seconds): 4015
RabbitMQ version: 3.8.2
Node name: rabbit@rabbitmqqa-mm
Erlang configuration: Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:64]
Erlang processes: 434 used, 1048576 limit
Scheduler run queue: 1
Cluster heartbeat timeout (net_ticktime): 60

Plugins

Enabled plugin file: /etc/rabbitmq/enabled_plugins
Enabled plugins:

 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
 * cowboy
 * cowlib
 * amqp_client

Data directory

Node data directory: /var/lib/rabbitmq/mnesia/rabbit@rabbitmqqa-mm

Config files


Log file(s)

 * /var/log/rabbitmq/rabbit@rabbitmqqa-mm.log
 * /var/log/rabbitmq/rabbit@rabbitmqqa-mm_upgrade.log

Alarms

(none)

Memory

Calculation strategy: rss
Memory high watermark setting: 0.4 of available memory, computed to: 3.3458 gb
other_proc: 0.0343 gb (35.13 %)
code: 0.0303 gb (30.99 %)
other_system: 0.0124 gb (12.67 %)
allocated_unused: 0.0088 gb (9.05 %)
reserved_unallocated: 0.0053 gb (5.39 %)
other_ets: 0.0031 gb (3.13 %)
atom: 0.0015 gb (1.55 %)
plugins: 0.0011 gb (1.15 %)
mgmt_db: 0.0003 gb (0.27 %)
binary: 0.0002 gb (0.25 %)
metrics: 0.0002 gb (0.21 %)
mnesia: 0.0001 gb (0.08 %)
msg_index: 0.0001 gb (0.06 %)
quorum_ets: 0.0 gb (0.04 %)
connection_other: 0.0 gb (0.04 %)
connection_channels: 0.0 gb (0.0 %)
connection_readers: 0.0 gb (0.0 %)
connection_writers: 0.0 gb (0.0 %)
queue_procs: 0.0 gb (0.0 %)
queue_slave_procs: 0.0 gb (0.0 %)
quorum_queue_procs: 0.0 gb (0.0 %)

File Descriptors

Total: 4, limit: 32671
Sockets: 0, limit: 29401

Free Disk Space

Low free disk space watermark: 0.05 gb
Free disk space: 3.3728 gb

Totals

Connection count: 0
Queue count: 0
Virtual host count: 2

Listeners

Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: [::], port: 15672, protocol: http, purpose: HTTP API
2020-02-26 15:52:59,071 [salt.loaded.int.module.cmdmod:1199][DEBUG   ][4855] output: Status of node rabbit@rabbitmqqa-mm ...
Runtime

OS PID: 19193
OS: Linux
Uptime (seconds): 4015
RabbitMQ version: 3.8.2
Node name: rabbit@rabbitmqqa-mm
Erlang configuration: Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:64]
Erlang processes: 434 used, 1048576 limit
Scheduler run queue: 1
Cluster heartbeat timeout (net_ticktime): 60

Plugins

Enabled plugin file: /etc/rabbitmq/enabled_plugins
Enabled plugins:

 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
 * cowboy
 * cowlib
 * amqp_client

Data directory

Node data directory: /var/lib/rabbitmq/mnesia/rabbit@rabbitmqqa-mm

Config files


Log file(s)

 * /var/log/rabbitmq/rabbit@rabbitmqqa-mm.log
 * /var/log/rabbitmq/rabbit@rabbitmqqa-mm_upgrade.log

Alarms

(none)

Memory

Calculation strategy: rss
Memory high watermark setting: 0.4 of available memory, computed to: 3.3458 gb
other_proc: 0.0343 gb (35.13 %)
code: 0.0303 gb (30.99 %)
other_system: 0.0124 gb (12.67 %)
allocated_unused: 0.0088 gb (9.05 %)
reserved_unallocated: 0.0053 gb (5.39 %)
other_ets: 0.0031 gb (3.13 %)
atom: 0.0015 gb (1.55 %)
plugins: 0.0011 gb (1.15 %)
mgmt_db: 0.0003 gb (0.27 %)
binary: 0.0002 gb (0.25 %)
metrics: 0.0002 gb (0.21 %)
mnesia: 0.0001 gb (0.08 %)
msg_index: 0.0001 gb (0.06 %)
quorum_ets: 0.0 gb (0.04 %)
connection_other: 0.0 gb (0.04 %)
connection_channels: 0.0 gb (0.0 %)
connection_readers: 0.0 gb (0.0 %)
connection_writers: 0.0 gb (0.0 %)
queue_procs: 0.0 gb (0.0 %)
queue_slave_procs: 0.0 gb (0.0 %)
quorum_queue_procs: 0.0 gb (0.0 %)

File Descriptors

Total: 4, limit: 32671
Sockets: 0, limit: 29401

Free Disk Space

Low free disk space watermark: 0.05 gb
Free disk space: 3.3728 gb

Totals

Connection count: 0
Queue count: 0
Virtual host count: 2

Listeners

Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: [::], port: 15672, protocol: http, purpose: HTTP API
2020-02-26 15:52:59,072 [salt.loaded.int.module.cmdmod:501 ][DEBUG   ][4855] env command: (u'su', u'-s', u'/bin/sh', u'-', u'rabbitmq', u'-c', '/usr/bin/python2')
2020-02-26 15:52:59,692 [salt.state       :322 ][ERROR   ][4855] Error: RabbitMQ command failed: Error:
{:undef, [{:rabbit_auth_backend_internal, :check_user_login, ["USERNAME", [password: "PASSWORD"]], []}, {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 680]}, {:rpc, :"-handle_call_call/6-fun-0-", 5, [file: 'rpc.erl', line: 197]}]}
2020-02-26 15:52:59,693 [salt.state       :2045][INFO    ][4855] Completed state [USERNAME] at time 15:52:59.693352 (duration_in_ms=2158.046)
```

### Versions Report
Salt Master: 3000
Salt Minion: 3000
Rabbitmq-server: 3.8.2

```
# salt --versions-report
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-88-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by 11chrisadams11** [comment] 2020-03-09 16:25
This is caused by a new output from the status call for newer versions of RabbitMQ. It is checking for a version number, and can't find it because the format has changed.
I have submitted this pull request (#56193) that will check both output versions for the version number. It has fixed the user errors, and allows changing passwords again.

**Comment by sagetherage** [comment] 2020-04-15 02:18
closing as merged and will be released with Sodium

**Closed by sagetherage** 2020-04-15 02:18 UTC
Labels: Bug, State Module, team-state

**Comment by rtaft** [comment] 2020-05-18 17:43
I'm still seeing this error in 3000.3

Salt Master is 3000.3
Salt Minion is 3000.3
Rabbitmq 3.8.3
