### ISSUE TITLE
Salt-Cloud multiple providers prevents minion destroy from functioning

### ISSUE THREAD

**Issue by kdecoteauCS** [saltstack/salt#39178] opened 2017-02-04 14:04 UTC
### Description of Issue/Question

We are experiencing an issue where having multiple provider credentials using the AWS ec2 driver cause salt-cloud -d to fail as it detects multiple copies of a single target instance. Changing from "provider" to "driver" makes no difference. 

Prior to 2015.05.05, this behavior was not observed.  

### Setup
Example Setup: 
1. Create two VPC's in AWS region us-east-1 on the same AWS account. Call them "Test" and "Dev"
2. Create two AWS providers with the ec2 driver with different credentials and iam roles. In our case, these IAM roles only have the ability to act in the specific VPC for which they are intended. 
3. Create a profile for a simple instance using "Test" provider

### Steps to Reproduce Issue
1. Use salt-cloud to create an instance in the Test VPC using the Test iam credentials
2. Instance will create successfully. 
3. Now attempt to delete the instance using salt-cloud -d $instancename from test salt master. The following will happen: 

```
[root@gateway.test.aws TEST]
 # salt-cloud -m test.conf -d  # (or salt-cloud -d my-sample-instance-services08.test.aws ) 
[INFO    ] salt-cloud starting
[INFO    ] Applying map from 'test.conf'.
The following virtual machines are set to be destroyed:
   TEST:
    ec2:
      my-sample-instance-services08.test.aws
  DEV:
    ec2:
      my-sample-instance-services08.test.aws

Proceed? [N/y] n
```

Further: the instance CAN be deleted, however, it does not fully remove itself from salt. The renamed instance has to be removed manually from salt-key. Most of the time, the instance deletion is successful, but the cleanup can not be completed. 

```
Proceed? [N/y] y
... proceeding
[INFO    ] Destroying in non-parallel mode.
[INFO    ] Renaming my-example-services08.test.aws to my-example-services08.test.aws-DEL6657e73b9c2d4e42bba8c27651e2f276
[INFO    ] Machine will be identified as my-example-services08.test.aws-DEL6657e73b9c2d4e42bba8c27651e2f276 until it has been cleaned up.
[INFO    ] [{'instanceId': 'i-05d3d27d5d483de45', 'currentState': {'code': '32', 'name': 'shutting-down'}, 'previousState': {'code': '16', 'name': 'running'}}]
[ERROR   ] There was an error destroying machines: 'instanceId'
```

```
 # salt-key -L | grep "services08"
my-sample-instance-services08.test.aws-DEL3f2b3001af3542abb6adf2cada3a0bd2
my-sample-instance-services08.test.aws-DEL6657e73b9c2d4e42bba8c27651e2f276
[root@gateway.test.aws providers]
```

Our IAM roles do allow for viewing instances outside the VPC, however this was unintended behavior for salt to check outside the VPC and fail to delete. (It worked in 2014.7.5) 

### Versions Report
 # salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-573.3.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by Ch3LL** [comment] 2017-02-06 20:10
@kdecoteauCS This is a duplicate of https://github.com/saltstack/salt/issues/33439. I will close this issue so we can track the issue there.

**Closed by Ch3LL** 2017-02-06 20:10 UTC
