### ISSUE TITLE
Infoblox state fails if record_type=host and ran a second time

### ISSUE THREAD

**Issue by jagojkov** [saltstack/salt#38465] opened 2016-12-28 16:28 UTC
### Description of Issue/Question
The infoblox state module fails after the initial run if record_type=host.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
{%- set fqdn = [] %}
{%- set hostname = grains['host'] %}
{%- set domain = "domain.test" %}
{%- set fqdn = hostname + '.' + domain %}
{%- set ipv4 = grains['ip_interfaces']['eth0'][0] %}

info-blox-present-a:
    infoblox.present:
      - name: {{ fqdn }}
      - value: {{ ipv4 }}
      - record_type: host
      - dns_view: default
      - sslVerify: False
      - infoblox_server: {{ salt['pillar.get']('infoblox:server') }}
      - infoblox_user: {{ salt['pillar.get']('infoblox:user') }}
      - infoblox_password: {{ salt['pillar.get']('infoblox:password') }}
      - infoblox_api_version: v2.3

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

[root@dc01test1 opt]# salt-call state.sls infoblox.present
[WARNING ] /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

local:
----------
          ID: info-blox-present-a
    Function: infoblox.present
        Name: dc01test1.domain.test
      Result: True
     Comment:
     Started: 08:24:57.373574
    Duration: 247.935 ms
     Changes:
              ----------
              new:
                  |_
                    ----------
                    DNS View:
                        default
                    IP Addresses:
                        - 172.24.36.119
                    Name:
                        dc01test1.domain.test
                    Record ID:
                        record:host/ZG5zLmhvc3QkLl9kZWZhdWx0Lm1oYy5tb2xpbmEuZGMwMXRlc3Qx:dc01test1.domain.test/default
              old:
                  None

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 247.935 ms

[root@dc01test1 opt]# salt-call state.sls infoblox.present
[WARNING ] /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/infoblox.py", line 110, in present
    sslVerify=sslVerify)
  File "/usr/lib/python2.7/site-packages/salt/modules/infoblox.py", line 231, in update_record
    raise CommandExecutionError(msg)
CommandExecutionError: Unsuccessful status code 400 returned.

local:
----------
          ID: info-blox-present-a
    Function: infoblox.present
        Name: dc01test1.domain.test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/infoblox.py", line 110, in present
                  sslVerify=sslVerify)
                File "/usr/lib/python2.7/site-packages/salt/modules/infoblox.py", line 231, in update_record
                  raise CommandExecutionError(msg)
              CommandExecutionError: Unsuccessful status code 400 returned.
     Started: 08:25:00.222066
    Duration: 171.266 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 171.266 ms

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
# salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.3.1
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.16.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.6 Santiago

**Comment by bl4ckcontact** [comment] 2016-12-28 22:51
I've discovered the cause of this issue has to do with the `value` variable not being converted to unicode before being compared to the jsonified return for `IP Address(es)`. This actually causes issues with every `record_type`, not just host records, causing every value to be considered a mismatch, as it will always compare a string against a unicode value.

See the gist I've put up here for the changes that allow this to work: 
https://gist.github.com/bl4ckcontact/dd930f3cb6f1e1411e3f7bdbdeb92d64

Specifically on line [72](https://gist.github.com/bl4ckcontact/dd930f3cb6f1e1411e3f7bdbdeb92d64#file-infoblox-py-L72), [90](https://gist.github.com/bl4ckcontact/dd930f3cb6f1e1411e3f7bdbdeb92d64#file-infoblox-py-L90), [93](https://gist.github.com/bl4ckcontact/dd930f3cb6f1e1411e3f7bdbdeb92d64#file-infoblox-py-L93) and [94](https://gist.github.com/bl4ckcontact/dd930f3cb6f1e1411e3f7bdbdeb92d64#file-infoblox-py-L72)

**Comment by rallytime** [comment] 2017-02-21 22:36
@jagojkov Do the changes in #38475 fix the issue here for you?

**Comment by jagojkov** [comment] 2017-02-21 22:54
I certainly does.

**Comment by rallytime** [comment] 2017-02-21 23:03
Great! I'll go ahead and close this then. Thanks for confirming!

**Closed by rallytime** 2017-02-21 23:03 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity
