### ISSUE TITLE
state-output does not have precedence over master config

### ISSUE THREAD

**Issue by javicacheiro** [saltstack/salt#30862] opened 2016-02-03 16:28 UTC
In version 2015.8.4 the state-full option of the CLI does not override the option state_output of the salt master config.

For example if state_output is changed in the master config to 'terse' then:
```
salt --state-output=full node state.apply
```
will give terse output.

**Comment by jfindlay** [comment] 2016-02-04 00:38
@javicacheiro, thanks for reporting.  This is a duplicate of #29795.  If you have any more info, please report there.

**Closed by jfindlay** 2016-02-04 00:38 UTC
Labels: Duplicate
