### ISSUE TITLE
sdb.get not returning the value and minion executing to none value

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#59204] opened 2020-12-29 12:54 UTC
I have integrated vault with saltstack using the document https://help.saltstack.com/hc/en-us/articles/360041140451-Quick-Guide-to-Vault-Integration

everything was good enough, but am not getting the value with `salt-run sdb.get 'sdb://myvault/salt/data/user1' -l debug`
getting error
```
ImportError: bad magic number in 'salt.loaded.int.log_handlers.fluent_mod.cpython-35': b'\x17\r\r\n'
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:8200/v1/salt/data
```

I strictly followed the document and used the same vault policies.

Still while executing in minions  getting none value

Could anyone help on this issue??

Salt version

3000.3

**Comment by sooraj2589** [comment] 2021-01-06 10:01
@s0undt3ch,can you please help on this?

**Comment by s0undt3ch** [comment] 2021-01-06 13:09
Could you please include the full debug logs?
Thanks!

**Comment by sagetherage** [comment] 2021-04-06 17:08
@sooraj2589 can you provide the sanitized logs, please?

**Comment by sagetherage** [comment] 2021-04-30 01:27
closing since we have received info enough to triage this issue or reproduce it.

**Closed by sagetherage** 2021-04-30 01:27 UTC
Labels: Bug, info-needed, needs-triage
