### ISSUE TITLE
salt-ssh and gpg pillar renderer

### ISSUE THREAD

**Issue by pykler** [saltstack/salt#19114] opened 2014-12-19 05:45 UTC
Pillar data that is gpg encrypted does not decrypt with salt-ssh. Any idea why?

**Comment by slafs** [comment] 2015-01-16 16:06
hey! 

@basepi  I took a closer look on this, since I also bumped into this issue.
I found that states also don't work and forked @pykler's repo to show this. See https://github.com/slafs/salt-gpg-test.

After some fiddling in salt I think I found a fix to make gpg renderer work with states in ``salt-ssh``. PR coming.

**Comment by slafs** [comment] 2015-01-16 16:27
OK. So #19787 should fix the thing with states. Also it's worth noting that a shebang (``#!yaml|gpg``) is required on top of ``sample.sls`` pillar as stated in docs and in 22ebbe5cb207e448.

The issue with ``pillar.get`` still remains. What I noticed is that in ``render`` function from ``salt.renderers.gpg`` the ``__salt__`` object is sometimes a ``dict`` (when running ``pillar.get``) and sometimes an instance of ``salt.client.ssh.wrapper.FunctionWrapper`` (when running ``state.show_sls``). 

From this point I'm stuck since I find whole salt-ssh invoking nearly magical. BTW, are there any internal docs about what is the idea behind running ``salt-ssh``. I mean the workflow and general rationale for the copied modules (i.e. grains, state, pillar) in ``salt.client.ssh.wrapper`` package?

**Comment by pykler** [comment] 2015-01-16 17:52
Does adding the `#!yaml|gpg` fix anything in your tests?

**Comment by slafs** [comment] 2015-01-19 11:16
@pykler no it doesn't. The fix is required for this to work somehow. But, as @thatch45 stated in #19787, that fix breaks ``salt-ssh`` in other places. So I guess there must be a different way for fixing this.

**Comment by basepi** [comment] 2015-01-21 18:09
@slafs I think #19912 will fix your issue and shouldn't break anything else. Keep me posted.

**Comment by slafs** [comment] 2015-01-21 23:05
I think it's even worse now. Trying to test my case as well as @pykler's (both linked in earlier comments) seems to fail. Now I get:
```
  File "/home/slafs/.virtualenvs/salt-ssh-gpg-deleteme/src/salt/salt/renderers/gpg.py", line 137, in render
    homedir = __salt__['config.get']('gpg_keydir', DEFAULT_GPG_KEYDIR)
KeyError: 'config.get'
```
I think we can assume the presence of ``__salt__`` dict, but (and I saw this one earlier in my fiddling)   ``__salt__`` dict in render function is empty. ``__opts__`` however is full of stuff :). 

Before #19912 I saw that the ``render`` function from ``gpg`` renderer was called twice (while running ``salt-ssh -i local pillar.get password``).
For the first time it used ``__opts__.get`` and the second time it used ``__salt__['config.get']``. 
This is probably involves the way salt-ssh invokes itself, which again I don't fully understand ;).

BTW it's a bit harder to test this (e.g. compare to ``salt-call``) since the patch was merged only in ``2014.7`` branch and not in ``develop``.

**Comment by basepi** [comment] 2015-01-23 23:35
@slafs It has since been merged forward to develop. We merge forward from 2014.7 to 2015.2, and from 2015.2 to develop. Just takes a day or two.

I'm mystified as to why `config.get` isn't in `__salt__`. It doesn't have a `__virtual__` function and so should always be loaded. At least it's a dict, which was the main conditional I needed to remove. I should be able to add back in the `config.get` conditional as a quick fix and then look into why that's required later.

**Comment by basepi** [comment] 2015-01-23 23:43
I submitted the partial reversion in #20023. Keep me posted if that doesn't work. (It's *possible* it might fail because of the FunctionWrapper -- but if it does, we need to get that fixed *in* the FunctionWrapper, because we need to be able to check for membership in `__salt__` in salt-ssh.)

**Comment by slafs** [comment] 2015-01-24 13:54
Not quite there yet. I changed some gpg renderer code, to see the problem, like this:
```diff
diff --git a/salt/renderers/gpg.py b/salt/renderers/gpg.py
index 6ab89f7..fe85b00 100644
--- a/salt/renderers/gpg.py
+++ b/salt/renderers/gpg.py
@@ -134,9 +134,11 @@ def render(data, saltenv='base', sls='', argline='', **kwargs):
     if not HAS_GPG:
         raise SaltRenderError('GPG unavailable')
     if 'config.get' in __salt__:
+        log.warning('getting gpg homedir from "__salt__" config.get')
         homedir = __salt__['config.get']('gpg_keydir', DEFAULT_GPG_KEYDIR)
     else:
+        log.warning('getting gpg homedir from "__opts__" get')
         homedir = __opts__.get('gpg_keydir', DEFAULT_GPG_KEYDIR)
-    log.debug('Reading GPG keys from: {0}'.format(homedir))
+    log.warning('Reading GPG keys from: {0}'.format(homedir))
     gpg = gnupg.GPG(gnupghome=homedir)
     return decrypt_object(data, gpg)
```

And then:
``salt-call -c . -l warning --local pillar.get password`` (notice ``-c .`` and ``-l warning``)
gives:
```
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: ./gpgkeys
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: ./gpgkeys
local:
    supersecret
```
which is OK. But: 
``salt-ssh -c . -l warning -i  local pillar.get password`` (again, notice ``-c .`` and ``-l warning``)
gives:
```
[WARNING ] getting gpg homedir from "__opts__" get
[WARNING ] Reading GPG keys from: ./gpgkeys
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: /etc/salt/gpgkeys
[CRITICAL] Rendering SLS 'sample' failed, render error:
[Errno 13] Permission denied: '/etc/salt/gpgkeys'
[CRITICAL] Pillar render error: Rendering SLS 'sample' failed. Please see master log for details.
local:
```

---

Now. Removing the shebang from ``pillars/sample.sls`` results with:
```
salt-ssh -c . -l warning -i  local pillar.get password                  
[WARNING ] getting gpg homedir from "__opts__" get
[WARNING ] Reading GPG keys from: ./gpgkeys
local:
    -----BEGIN PGP MESSAGE-----
    Version: GnuPG v1
    
    hQEMA5Sfae08wQwjAQf+I+OHBUMtU9cn8dlYM+7CvtrKpHK/tgfoOm2vp8Xt+tpS
    FtYva+kCVrDRBrj3sGtzjYUncHwSQDZwECddNPb4y4FuUhRVrLhw3CqJ6JHzNZ7Z
    gVzD4S0dfEm3qdBYAgZHgbtyv1Myt4srza5ow4N9VOOe/SRlANdAiSPkFgjakGJt
    5Bw7wBuQ5cOHlK1aIW2QQLRO7cPf25w5Ws5+GlKL/TjPuinnfrxTWsByXsJsKERo
    TZTCAbN4XTjA4rTVhGERMWgQ1mLh58BfKKibkFQCEqKyuRcthD+DxGENSkVNWKlJ
    suapPHSm5pmwrtyd4fxummsuxYkN0RM4NvnxNzn+nNJGASgEW4MA92qmp4MTtM7u
    ZgiA49bPmN5WW7+trwS5PNddhHobehRTSgZ9c4NiHiosnRFJYFLgA4D3q4XulFqb
    0NBTP1XAZw==
    =1IBo
    -----END PGP MESSAGE-----
    
```

The example is here: https://github.com/slafs/salt-gpg-test

DEBUG log with shebang: http://pastebin.com/2FktfnpR
DEBUG log without shebang: http://pastebin.com/TN2PiAp1

**Comment by slafs** [comment] 2015-01-24 14:00
Similar issue with states:

``salt-call -c . -l warning --local state.show_sls sample``
```
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: ./gpgkeys
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: ./gpgkeys
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: ./gpgkeys
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: ./gpgkeys
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: ./gpgkeys
local:
    ----------
    test-salt-ssh-gpg:
        ----------
        __env__:
            base
        __sls__:
            sample
        cmd:
            - run
            |_
              ----------
              name:
                  supersecret
            |_
              ----------
              order:
                  10001
    test-salt-ssh-gpg-frompillar:
        ----------
        __env__:
            base
        __sls__:
            sample
        cmd:
            - run
            |_
              ----------
              name:
                  supersecret
            |_
              ----------
              order:
                  10000
```

But:
``salt-ssh -c . -l warning -i  local state.show_sls sample``
```
[WARNING ] getting gpg homedir from "__opts__" get
[WARNING ] Reading GPG keys from: ./gpgkeys
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: /etc/salt/gpgkeys
[CRITICAL] Rendering SLS 'sample' failed, render error:
[Errno 13] Permission denied: '/etc/salt/gpgkeys'
[CRITICAL] Pillar render error: Rendering SLS 'sample' failed. Please see master log for details.
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: ./gpgkeys
[WARNING ] getting gpg homedir from "__salt__" config.get
[WARNING ] Reading GPG keys from: ./gpgkeys
[CRITICAL] Rendering SLS sample failed, render error: argument of type 'int' is not iterable
local:
    - Rendering SLS sample failed, render error: argument of type 'int' is not iterable
    - Traceback (most recent call last):
    -   File "/home/slafs/.virtualenvs/salt-ssh-gpg-deleteme/src/salt/salt/state.py", line 2425, in render_state
    -     sls, rendered_sls=mods
    -   File "/home/slafs/.virtualenvs/salt-ssh-gpg-deleteme/src/salt/salt/template.py", line 84, in compile_template
    -     ret = render(input_data, saltenv, sls, **render_kwargs)
    -   File "/home/slafs/.virtualenvs/salt-ssh-gpg-deleteme/src/salt/salt/renderers/gpg.py", line 136, in render
    -     if 'config.get' in __salt__:
    -   File "/home/slafs/.virtualenvs/salt-ssh-gpg-deleteme/src/salt/salt/client/ssh/wrapper/__init__.py", line 47, in __getitem__
    -     if '.' not in cmd and not self.cmd_prefix:
    - TypeError: argument of type 'int' is not iterable
    - 
```

**Comment by basepi** [comment] 2015-01-27 23:47
Thanks for the new logs, I'll find some time to dive into this. Still something weird going on with the function wrapper there.

**Comment by slafs** [comment] 2015-03-06 10:09
Hi! Any update on this?

**Comment by basepi** [comment] 2015-03-10 22:27
Nope. SaltConf decimated my available time. Once I'm caught up I hope to get back to this. =)

**Comment by basepi** [comment] 2015-04-29 21:30
So now that I'm actually looking into this, it's probably not an issue with the functionwrapper at all. (I was only looking at the states example) Rather, I think it's probably an issue with the config directory. I noticed that in your pillar.get example it was trying to look in /etc/salt/gpgkeys.

Anyway, still investigating.

**Comment by basepi** [comment] 2015-04-29 21:38
(You made this clear, by the way, I just didn't read closely enough and fixated on that stacktrace at the end. =P)

**Comment by basepi** [comment] 2015-05-01 18:58
Making progress here. The root cause of the pillar issue was the fact that we weren't passing any minion opts to the target, so it didn't have gpg_keydir defined. #23188 was a workaround. #23272 fixed the root issue and reverted the workaround.

The state.sls call is still stacktracing. Probably a completely different issue.

**Comment by basepi** [comment] 2015-05-04 20:43
A bit of a change to how this will work. You must either define `ssh_minion_opts` in the master config to override minion opts, or define `minion_opts` in the roster on a per-minion basis. It will not take any keys from the local minion config, because that may be unwanted. (salt-ssh could be coexisting with a real minion)

**Comment by basepi** [comment] 2015-05-04 22:42
Alright, have the state issue fixed as well with #23347. Once #23272 and #23347 are both merged, this will be fixed!

**Comment by slafs** [comment] 2015-05-05 09:58
Great! Thank you! I will try to verify this with my use cases. 

One question though. If I understood you correctly there's currently no way to have a GPG key on a machine where I'm invoking ``salt-ssh`` (like in the example repo I linked earlier), right? Or am I missing something?

**Comment by basepi** [comment] 2015-05-05 21:23
Your example repo works. The interesting interaction is the minion opts. Basically, when we compile pillar or states, we're using the minion opts in the renderers. So the gpg_keydir wasn't making it down to that set of opts, even though the actual rendering was happening on the master.

So I think your example should work fine, you just need to make sure the `gpg_keydir` is specified under the `ssh_minion_opts` in the master config, or in the roster under `minion_opts` for the host.

**Closed** 2015-05-06 21:52 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P4, Salt-SSH

**Comment by slafs** [comment] 2015-05-07 11:29
Yes, you're right. My example now works :). Great! Thank you again for your stunning work!

**Comment by basepi** [comment] 2015-05-11 18:01
No problem! Glad we got it resolved. This issue managed to uncover a few core issues with salt-ssh, so it was great!
