### ISSUE TITLE
[BUG] state.sls_exists does not work for saltenv other than base

### ISSUE THREAD

**Issue by wwdillingham** [saltstack/salt#61343] opened 2021-12-09 17:00 UTC
**Description**
I have attempted to create a meta state "node/init.sls":

```
{% set sls_file = "node." ~ grains.get('host') %}

{% if salt['state.sls_exists'](sls_file, saltenv=saltenv) -%}
include:
  - {{ sls_file }}
{%- endif %}
```

The idea here is i can setup a state file for minions at the root of the fileserver in "node/hostname.sls" where hostname is the short hostname of a minion.

so for instance {{ sls_file }} would be rendered as "node.foo" for foo.example.com

and my fileserver has: "node/foo.sls" in both my testing saltenv and in base

this works in base, bot not in any other saltenv. state.show_states does not list any states further included from node/foo.sls and state.apply node does not show any of the state code in node/foo.sls being executed when specifying saltenv=

It works entirely when not specifying saltenv (in base)

**Expected behavior**
node.foo (node/foo.sls) would be included in the state run and
`salt 'foo.example.com' state.sls_exists node.foo saltenv=test`
would return "True" not "False"

**Versions Report**
```
Salt Version:
           Salt: 3001.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1160.45.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```

**Comment by OrangeDog** [comment] 2021-12-09 17:04
3001 will soon be EOL. Can you reproduce with 3004?

**Comment by wwdillingham** [comment] 2021-12-09 17:07
@OrangeDog I am not in a position to quickly test with 3004 however @whytewolf indicated to me he had reproduced the issue in 3004. I will attempt to setup a dev environment to test the issue and get back to you.

**Comment by whytewolf** [comment] 2021-12-10 20:26
well to be fair my testing of sls_exists in 3004 wasn't complete and was very rudimentary. and also pointed to sls_exists not working in my environment at all for anything that does exist. however, after further testing, it turns out my issue was that the state I was referencing wasn't rendering properly. once I used a properly referenced state it worked fine in 3004.

**Comment by OrangeDog** [comment] 2021-12-10 20:44
I believe it uses `show_sls` internally and returns `False` on any error.

**Comment by wwdillingham** [comment] 2021-12-13 21:40
I am no longer able to reproduce this issue, I am sorry for the distraction, If I encounter it again I will circle back.

**Comment by wwdillingham** [comment] 2021-12-14 21:37
Okay, so I think I may have re-encountered it and found out more information. It seems that the state.sls_exists returns false for sls files introduced newly in the saltenv but not for states which existed previously.

**Comment by whytewolf** [comment] 2021-12-14 21:45
"newly" in the saltenv kind of points to it not being a part of the fileserver yet. in which case it should return false. if you are using gitfs, please make sure the fileserver is updated for all saltenvs. using fileserver.update if you are using gitfs you will have to force the remotes to update as well. see https://docs.saltproject.io/en/latest/ref/runners/all/salt.runners.fileserver.html#salt.runners.fileserver.update for more info.

**Comment by wwdillingham** [comment] 2021-12-14 21:58
I am using gitfs, and when I make a new branch I can use new state files in state.apply when specifying saltenv etc, but the sls_exists function does not work (returns false) is that consistent with the fileserver needing updating?

**Comment by whytewolf** [comment] 2021-12-14 22:06
it can be. as @OrangeDog eluded to earlier. sls_exists is a very simplistic function. it literally is one line of executed code. 

```
return isinstance(show_sls(mods, test=test, queue=queue, **kwargs), dict)
```

as such before you try `sls_exists`. try to see what the output of `state.show_sls` with the same options is.

**Comment by wwdillingham** [comment] 2021-12-14 22:17
Okay getting a further understanding now, thanks for the help. I think this summarizes the issue I saw: It appears the issue is not newly created states but rather my newly created states were including a state that I had also deleted within my branch. Despite state foo.bar existing in the fileserver it was foo.bar is including foo.baz which doesnt exist and that causes sls_exists foo.bar to return false.

**Comment by whytewolf** [comment] 2021-12-14 22:23
right, that would actually fit into the working as expected. as the states do need to render, and the missing include causes that not to happen. I think this does fall into realm of it is the expected result. but we should maybe do something to capture the failure of rendering, as @OrangeDog suggested. I'm just not sure how we would mark that back to the end user ... without it breaking all rendering. unless it just gets marked in a log file somewhere since ... everyone checks log files after all right?

**Comment by OrangeDog** [comment] 2021-12-14 23:53
When I said it should be logged, I observed it being logged.
@wwdillingham the rendering failure was in the minion log when `sls_exists` returned false?

**Comment by whytewolf** [comment] 2022-02-07 17:57
@OrangeDog Thank you, I"ll go ahead and close this case. since the logging already happens.

**Closed by whytewolf** 2022-02-07 17:57 UTC
Labels: Bug, cannot-reproduce, needs-triage
