### ISSUE TITLE
onlyif requisite triggers stack trace if python3-pip is missing on salt 3000

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#56157] opened 2020-02-13 17:48 UTC
### Description of Issue
The ``onlyif`` requisite (and possibly others) triggers a stack trace if python(3)-pip is not installed.  I can paste the stack trace if it's needed.  We should decide if python(3)-pip should be a package dependency so it doesn't matter (as it's not installed by default), or if this is a bug and should be fixed.

Dave Boucha confirmed that it happens on python2 as well on centos.

### Setup
```bash
docker run --rm -it ubuntu:bionic
apt update ; apt -y install curl
curl -L https://bootstrap.saltstack.com|bash -s -- -x python3
salt-call --local state.single test.nop name=hi onlyif=true
```
note that it does not occur on 2019.2.3:
```bash
docker run --rm -it ubuntu:bionic
apt update ; apt -y install curl
curl -L https://bootstrap.saltstack.com|bash -s -- -x python3 stable 2019.2.3
salt-call --local state.single test.nop name=hi onlyif=true
```
it also does not occur if python3-pip is installed:
```bash
docker run --rm -it ubuntu:bionic
apt update ; apt -y install curl python3-pip
curl -L https://bootstrap.saltstack.com|bash -s -- -x python3
salt-call --local state.single test.nop name=hi onlyif=true
```

### Versions Report
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 5.5.3-2-MANJARO
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by bryceml** [comment] 2020-02-13 18:07
see also https://github.com/saltstack/salt/issues/56131

**Comment by DmitryKuzmenko** [comment] 2020-02-14 17:18
@dwoz I've assigned this one to you because you're already assigned to the similar issue #56131. I'm just not sure is it the same or not so leaving this opened for now.

**Comment by dwoz** [comment] 2020-02-21 07:23
Duplicate of #56131

**Closed by dwoz** 2020-02-21 07:23 UTC
Labels: 3000.1, Bug, Confirmed, Core, Duplicate, High Severity, P3, State Compiler
