### ISSUE TITLE
user.present fails to remove extra groups when gid_from_name==True (FreeBSD)

### ISSUE THREAD

**Issue by backerman** [saltstack/salt#23819] opened 2015-05-17 02:06 UTC
On FreeBSD, when:
* gid_from_name is set
* no further groups are required by the state
* the user is a member of at least group other than the default,

salt/modules/pw_user.py errors out:

`[ERROR   ] These values could not be changed: {'groups': []}`

because it's calling `pw usermod -G -n (username)` and -G obviously has no arguments. A single comma should suffice for the null set of groups, but there's also a nifty regression ([FreeBSD bug 185666][1]) which causes that to not actually work in 10.0 or 10.1&mdash;the user is added to groups listed, but not removed from groups that aren't listed. (A patch was applied to HEAD that was never merged into a release.) So the workaround will probably involve `pw groupmod`.

[1]: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=185666

**Comment by jfindlay** [comment] 2015-05-20 18:16
@backerman, would you consider this a duplicate of #21902?

**Comment by backerman** [comment] 2015-05-21 00:03
Looks like it is. There's an extra complication here where the -G option doesn't get an argument, but that shouldn't matter because of the `pw usermod` bug.

**Comment by jfindlay** [comment] 2015-05-21 03:54
@backerman, thanks for the confirmation.  I'll close this in favor of the other.

**Closed by jfindlay** 2015-05-21 03:54 UTC
Labels: Duplicate
