### ISSUE TITLE
salt.states.grains.list_present appends a full list when some elements are already defined

### ISSUE THREAD

**Issue by dereckson** [saltstack/salt#41716] opened 2017-06-13 12:22 UTC
### Description of Issue/Question

The salt.states.grains.list_present ensures a list is present.

When some entries of the list are already present, but not the full list, it appends the full list.

That creates duplicate entries.

### Setup
A saltmaster, a minion (repro also with salt-call --local)

### Steps to Reproduce Issue

Apply twice the following state for the two following lists:

```
salt_roles:
  grains.list_present:
    - name: roles
    - value: {{ pillar.get('roles')[grains['id']] }}
```

```
roles:
  someminionid:
     - role1
```

```
roles:
  someminionid:
     - role2
     - role1
```

### Expected and actual result

Expected in /etc/salt/grains:
```
roles:
   - role1
   - role2
```

Actual:
```
roles:
   - role1
   - role2
   - role1
```

### Versions Report
Salt Version:
           Salt: 2016.11.4

**Comment by Ch3LL** [comment] 2017-06-13 15:08
@dereckson this is a duplicate of https://github.com/saltstack/salt/issues/31427. Please feel free to add comments in this issue since we will track this issue there.

**Closed by Ch3LL** 2017-06-13 15:08 UTC
