### ISSUE TITLE
Top SLS compilation does not behave the same as Docs describe

### ISSUE THREAD

**Issue by driskell** [saltstack/salt#12483] opened 2014-05-02 09:44 UTC
Hi

(This is taken from my comments on closed issue #5440 - @basepi recommended a new issue so here it is! Thanks.)

I have 4 environments, "base", "qa", "dev", "master", in that order defined in file_roots. These are branches in a git and I have my own deployment of this to the salt server (I do not use gitfs).

Each has a version of the top.sls file containing all environments (as you'd expect since it same file, just different revisions different branches)

The documentation describes that if an environment has info in top.sls in "base", it will always override all other top.sls. This is not the case - and checking the code there is no distinction between "base" and any other name, and no specific decision on ordering (and it seems alphabetical) - so in my case, even though in the top.sls and file_roots, "qa" is second down, because it is last alphabetically, that overrides all other top.sls files in all other environments.

Based on the docs, it seems to give the idea that "base" is a special name and is always authoritative. It also explicitly says that if an environment is defined in multiple top.sls files - the definition in the top.sls for that environment will be preferred. But the code seems to say otherwise.

The code seems to simply merge and overwrite, in alphabetical order. Which contradicts entirely the documentation.

For reference, from http://docs.saltstack.com/en/latest/ref/states/top.html:

The following is what lead me to think "base" was a special name (it doesn't say the FIRST environment wins, it says the "base" environment wins.)
> 21.24.15.3. HOW TOP FILES ARE COMPILED
> ...
> 1 . The base environment's top file is processed first. Any environment which is defined in the base top.sls as well as another environment's top file, will use the instance of the environment configured in base and ignore all other instances. In other words, the base top file is authoritative when defining environments.

The following is the bit saying a top.sls in an environment is authoritative for that environment if it contains config for it:
> 3 . For environments other than base, the top file in a given environment will be checked for a section matching the environment's name. If one is found, then it is used. Otherwise, the remaining (non-base) environments will be checked in alphabetical order. In the below example, the qa section in /srv/salt/dev/top.sls will be ignored, but if /srv/salt/qa/top.sls were cleared or removed, then the states configured for the qa environment in /srv/salt/dev/top.sls will be applied.

Although if I'm honest, point 3 does seem to contradict point 2 (below) - I would've expected point 2 to at least make an exception for point 3 - or point 3 come first
> 2 . If, for some reason, the base environment is not configured in the base environment's top file, then the other environments will be checked in alphabetical order. The first top file found to contain a section for the base environment wins, and the other top files' base sections are ignored. So, provided there is no base section in the base top file, with the below two top files the dev environment would win out, and the common.centos SLS would not be applied to CentOS hosts.

=====

@basepi:
>@driskell Could I convince you to open a new issue and insert all of this awesome information and detective work into that new issue? I think what we will want to do is bring the code in line with the documentation (I still haven't tested this myself, so I haven't verified that I see the same thing you do) if possible. I think the documentation's way is a good way, but we definitely need to get them in line with each other one way or another.

I agree the documentation is (mostly) a good way, and the behaviour should match. Assuming I haven't read the doc wrong though, and "base" is meant to be special and authoritative and overriding, then I think that should be configurable so I can call it something else, so maybe a "main_env: base" option with that as default.

Thanks guys!

**Comment by clinta** [comment] 2015-01-27 21:20
Count me among those who found this too late after painfully discovering that these don't work they way I'd expect.

I think a simpler scheme would be that an environments definition must be in that environments top file, and all other environments in that top file are ignored. So in the base top.sls, the contents of the base environment is read, and everything else is ignored. In the dev environment's top.sls the dev environment is read and everything else is ignored.

This would make the merging of top files much simpler and intuitive, while still allowing them to be version controlled and merged with a normal git workflow.

**Comment by basepi** [comment] 2015-01-28 21:22
I actually do like this idea, I'll have to think on it. It would obviously have to be config-gated, as plenty of people are using a single topfile in the `base` environment these days, but I think this would be good to add.

**Comment by alf** [comment] 2015-02-05 21:13
Just had a fight with #17261 and I see that this is related so I figured I'd point this out. The fix I'm proposing for that issue would probably help out a lot for this issue as well.

The logical fix for this problem would be to *not* use an unordered set in [BaseHighState.get_envs](https://github.com/saltstack/salt/blob/v2014.1.13/salt/state.py#L1883) but rather use an OrderedDict and then return it as a list.

**Comment by driskell** [comment] 2015-02-05 21:31
@alf Not sure I understand. The get_tops returns an OrderedDict so it doesn't look like the get_envs matters at all. The main issue reported here is the top compilation is purely alphabetical order, and nothing else, which is completely other than the seemingly complex process described in the documentation.

> The code seems to simply merge and overwrite, in alphabetical order. Which contradicts entirely the documentation.

The entire logic for this issue is within get_tops (used to be) and I did put forward the correct fix to make everything function exactly as described in the documentation (see #12483) - however, because it was such a substantial behaviour change it couldn't be accepted at the time.

Although, @basepi I don't mind refactoring and testing a new patch fenced by config if it helps speed things along? Just need some thought on what the process SHOULD be and I can implement it I think.

Not sure how much this will all impact GitFS backend but I presume it will be the same as I guess it uses the same compilation process?

**Comment by alf** [comment] 2015-02-05 22:03
According to the python stdlib [documentation](https://docs.python.org/2/library/collections.html):

```An OrderedDict is a dict that remembers the order that keys were first inserted. If a new entry overwrites an existing entry, the original insertion position is left unchanged.
```


Since we iterate over the result from `get_envs` and add to the OrderedDict returned from `get_tops`, it is `get_envs` that decides the order.

Since a set in python is unordered, the order is not decided. It might appear to be alphabetical but that is unspecified behaviour. 

At least that's how I read the code.

**Comment by alf** [comment] 2015-02-05 22:14
I also get the impression that by making this simple change the code will do what the original author intended and documented.

**Comment by driskell** [comment] 2015-02-05 22:42
Ah I see! Sorry. It's odd that when I tested originally I always had it alphabetical... maybe random chance of the unordered set.

Though I think fixing that would only ensure it was alphabetical then, with the env list having base first and the rest alphabetical (rather than unordered). Ultimately, merge_tops still merges everything though, and I can see the merging will be more orderly but I think ultimately, the output will be identical.

I think based on your analysis then my #12537 was insufficient - but both combined it would work exactly to the docs I bet (since my patch assumed alphabetical environment list)

So I think if we keep existing behaviour, and allow for better arrangement, we're looking at max 3 options:

1. Option for "ordered_top_files" - default false.
2. Option for "top_file_method" - default "merge". Available: "merge", "same", "preferred"
3. Option for "preferred_top" - default "base".

So then we have the following:

1. Default is the same as now. Unordered merging of top files if you mix them up (maybe a major release can API change and change defaults... and remove the ordered_top_files...)

2. With top_file_method "same", we prefer the current env's top file, and then if current env doesn't exist in its own top file, we look for it like normal either unordered or ordered

3. With top_file_method "preferred" we can say, if current env is listed in the "preferred_top" env's top file, use it, otherwise fall back to "same"

So essentially here, with "ordered_top_files" and "top_file_method" set to "preferred" - we're then doing exactly what documentation says.

I think this all works in theory - the only confusing bit is the ordered_top_files. It's just a case of - are we happy to enforce the ordering? Bearing in mind someone somewhere is bound to be relying on it. Maybe it is considered worthwhile though.

What are people's thoughts?

**Comment by driskell** [comment] 2015-02-05 22:52
Just to add - I did like the documentations way, thus why I'm still wanting to discuss it. If simplification is desired, maybe the fallbacks on the top_file_methods proposal can be removed though, so "same" is ONLY the same, and "preferred" is ONLY the preferred (only that top file is used). I'd be happy to go with the "same" option then and the top file within an env only affects that env.

**Comment by alf** [comment] 2015-02-05 23:34
I agree that fixing the bug in `get_envs` is not sufficient to get the behaviour specified in the documentation.

**Comment by alf** [comment] 2015-02-06 08:31
Looking a bit more at the code, I see that [Pillars.get_top](https://github.com/saltstack/salt/blob/v2014.1.13/salt/pillar/__init__.py#L2415) behaves similar but different from [BaseHighState.get_top](https://github.com/saltstack/salt/blob/v2014.1.13/salt/state.py#L2041). Does anyone know whether the behaviour in `Pillars.get_top` is specified anywhere? Are they different by design or by accident?

**Comment by bechtoldt** [comment] 2015-02-23 16:47
Could someone please sum up what's currently working differently from the behavior described in the docs?
I see a mighty wall of text in this ticket and would need some time to understand and verify what's the actual problem.

**Comment by driskell** [comment] 2015-02-23 17:35
@bechtoldt In the docs, HOW TOP FILES ARE COMPILED, is not how it currently works.
( http://docs.saltstack.com/en/latest/ref/states/top.html )

The code seems to simply merge and overwrite, in arbitrary order. Which contradicts entirely the documentation.

(In my experience it is merge and overwrite alphabetical - but others here have reported arbitrary.)

**Comment by driskell** [comment] 2015-02-23 17:36
I would rather have it behave like the docs say (or almost like they say) than just updating the docs. Current behaviour is awkward with git branches.

Hope this quickly gives you enough insight. I am known for my essays (sorry).

**Comment by alf** [comment] 2015-02-23 17:43
In short, the docs specify the order to be used when merging the tops from different environments. See [How Top Files are Compiled](http://docs.saltstack.com/en/latest/ref/states/top.html). We experience and see from the source that the documentation is wrong and the actual result seems to be unspecified. There is already a warning in the documentation saying as much. We were hoping it could be solved. :)

**Comment by alf** [comment] 2015-02-24 17:57
Issue #19802 might be related.

**Comment by samart** [comment] 2015-03-29 15:43
we might be running into this while trying to get svnfs and envs working.    this implies environment functionality is pretty much broken?

**Comment by basepi** [comment] 2015-03-31 21:55
It implies that the best way to handle environments currently is to not have topfiles with conflicts top level keys. Only define an environment once, in a single topfile, because the merging is not currently happening as described in the docs.

**Comment by iigorkarpov** [comment] 2015-04-05 08:54
Since this problem has been around for almost a year, is not it better to change the documentation so that it reflects the current state of affairs? I mean not only a reference to the issue #12483, added to http://docs.saltstack.com/en/latest/ref/states/top.html, but also recommendations on the management of the multiple environments.

I wonder if ongoing release candidate treats top files differently...

**Comment by basepi** [comment] 2015-04-06 16:21
I don't expect the topfile compilation to have changed recently, but you're right, I still don't think it matches the docs and it should. However, we'll probably just fix the functionality, rather than taking the time to test the current state of things sufficiently to document it.

**Comment by BIAndrews** [comment] 2015-04-23 18:15
This is a pretty big problem for us as well. We aren't able to implement a multi environment setup tracked in git by branches because of this.

**Comment by BIAndrews** [comment] 2015-04-24 16:54
It seems to me a simplified solution would be to enable the salt-master to specify a default environment for all minions that do not specify an environment in the minion client config. Then we can be assured which directory top.sls will be used and the process would be git repo friendly. This is how puppet enterprise does it and it works very well. Compiling a top file from multiple environments and alphanumeric issues just seem like the whole process is very over complicated.

**Comment by packeteer** [comment] 2015-04-27 07:31
well this problem just took Salt out of the running here. We're going with Puppet

**Comment by ajmath** [comment] 2015-05-05 04:46
+1 to this.  Just spent the last 2 hours tracking this down and working around it.  It's a crapshoot if any of my highstates will succeed.

**Comment by tehmaspc** [comment] 2015-05-05 12:03
FWIW, here is what my team does to pull out env from git branches but equally importantly to keep us from having to change our top.sls env files:

We have a template file ('env_top.sls') in our salt master formula that looks like the following:

env_top.sls:
```
{%- raw %}
{% set roles = salt['grains.get']('roles', '') %}
{%- if roles %}
{%- endraw %}
{{ env }}:
  'env:{{ env }}':
{%- raw %}
    - match: grain
    {%- for role in roles %}
    - {{ role }}
    {%- endfor %}
{% endif %}
{%- endraw %}
```

base_top.sls:
```
base:

  '*':
    - core
```

This file gets layed down for every env we desire with the following state code in this same salt master formula - you can see how many envs we have:

```
...

# Setup our environment top.sls files
/srv/salt/base/top.sls:
  file.managed:
    - source: salt://salt/files/base_top.sls
    - makedirs: True

{% set envs = ['dev', 'stg', 'prd', 'inf'] %}
{% for env in envs %}
/srv/salt/{{ env }}/top.sls:
  file.managed:
    - source: salt://salt/templates/env_top.sls
    - template: jinja
    - makedirs: True
    - context:
        env: {{ env }}
{% endfor %}

...
```

Thus, on our Salt master server we get the following env directory structure:
/srv/salt/base/top.sls
/srv/salt/dev/top.sls
/srv/salt/stg/top.sls
/srv/salt/prd/top.sls
/srv/salt/inf/top.sls

Notice, we never have to change these top.sls files BUT we are completely grain backed. So we keep important grains on all our Salt servers that allow the following approach to work. Each server per it's env has a 'roles' grain list for figuring out what state files it should have applied. Additionally, since we do not have to update these files and because of the issues in this thread I decided to serve these top.sls files above from the FS directly instead of keeping them in separate Git branches.

Our main idea for matching grains and using a template file like above came from this section of the Salt docs: http://docs.saltstack.com/en/latest/topics/targeting/grains.html#matching-grains-in-the-top-file

If our strategy above works for you - you might want to take our approach to Salt envs. Just wanted to share back our strategy.

BTW - we do pillars similarly - via template pillar top.sls files - but we keep a separate git repo to manage all our pillar data / etc.

Cheers,
Tehmasp

**Comment by thatch45** [comment] 2015-05-05 22:11
Some crazy lie somehow got into the docs a while back and it has cause many issues. We will fix the docs.

**Comment by garo** [comment] 2015-05-06 10:29
This is also problematic for us: What we want is to have base environment to follow the master branch and then a separated production branch. The idea is that every change goes first to the master branch where it's tested against few servers. If it works it's then rebased to production which the majority of our severs follow.

Note that all our virtual machines / servers described here are getting production traffic. The two branches (master/production) exists just to ensure that for example autoscaling servers will always be able to start because we guarantee that the production branch will work in all cases (by peer reviewing etc).

**Comment by jamiemoore** [comment] 2015-05-20 13:26
+1 @BIAndrews .  Don't compile the top file at all.  Just specify the environment on the minion.  Puppet has this right.

**Comment by jmelfi** [comment] 2015-06-04 21:29
+1 @BIAndrews @jamiemoore 

We use puppet currently to deploy changing values from our code checked out of git branches (single repo).  Puppet determines from the node itself what env it should be.  We have two repos for puppet and hiera with branches and this works well.

It would be beneficial to be able to have something similar for salt where the salt repo can logically define the envs and pillars can provide the abstracted data.  Really hoping for a change and update here since we are beginning our evaluation of continuing with puppet or another solution.  This feature problem removes salt for us for now.

**Comment by cachedout** [comment] 2015-06-11 19:57
Whew, this issue took a long time to read! ;]

There are a lot of solid suggestions here and good feedback. The use cases surrounding version-controlled SLS files in multiple environments are especially compelling and make me feel like we need to add additional behavior to Salt to facilitate workflows where it makes sense to have per-environment top files.

Here is what I would like to propose:

1) We adopt a merge strategy configuration option similar to the pillar merge strategy that's currently controlled by `pillar_source_merging_strategy`. For the interested, this code is fairly straightforward to follow. The default merging strategy would *not* change. Somebody would have to really come up with a compelling reason to do so, since it would break many existing installations, in my opinion.

2) Like @basepi, I like this suggestion from @clinta of being able to allow each environment to only use high data for its own environment defined in the top file present in that environment, disregarding all others. I propose making this an additional merge strategy in the configuration option described above.

3) Finally, I propose an additional merge strategy option that would allow an environment to be selected from which all high data would be taken from. This could even default to `base` if we like. This would only use the selected environment as the authoritative source for high data, disregarding all others.

Does this proposal adequately cover the use cases outlined? All suggestions or feedback are very welcome. :]

**Comment by garo** [comment] 2015-06-12 03:55
The features @cachedout suggested sounds good.

Now I know this feature request isn't directly related to this issue but please also consider if #24622 could be implemented at the same time for pillars.

**Comment by cachedout** [comment] 2015-06-12 19:02
Hi @garo. I'll take a look at it and see. Thanks. We'll track the progress of that as a separate feature request, though. Follow #24622 for progress.

Anybody else have feedback before we get to writing this?

**Comment by cachedout** [comment] 2015-06-16 22:49
OK, I just about have a PR ready to go. Here are the changes I propose making:

After reviewing this in more detail, I think @driskell had the right idea in his earlier proposal. Therefore, I've done a few things:

1) Configuration files are now rendered as ordered dictionaries. I have added a new configuration file option called `ordered_top_files` as suggested by @driskell . It defaults to False, but when it is turned on, it will process environments in the order they are written in the configuration file.

2) I have added a configuration option called `top_file_merging_strategy`. This can be set to either `merge` or `same` (currently). If set to merge, the current behaviour is preserved. However, this can be influenced by the `ordered_top_files` setting above, in what should hopefully be an obvious way. If it's not, please let me know. :]

I did not implement fallback options because I feel like environments are already very difficult to reason about and I feel like adding fallback behaviour will only increase that complexity. Differing opinions are welcome of course. :]

3) I created a `default_top` option. If this is set, and no environment is speficially requested (via configuration or via a `saltenv` argument) and the `same` value is applied to the `top_file_merging_strategy` option, this is the environment that will be used.

Thoughts? I'll work on cleaning this up and submitting a PR, probably tomorrow.

**Comment by mathom** [comment] 2015-06-18 21:13
@cachedout I'd be very interested in seeing your PR. Being able to disable the topfile merging would greatly simplify our environment setup and test process.

**Comment by cachedout** [comment] 2015-06-19 15:28
@mathom I was just waiting for any feedback. :] I am planning on getting this cleaned up and submitted today. Thanks for being willing to review it. Much appreciated.

**Comment by jmelfi** [comment] 2015-06-19 18:44
@cachedout I will love to test this.

I assume that `top_file_merging_strategy` being set to merge by default and `ordered_top_files` being set to `True` would pull them from the top down.

Using this method, we would need to define the most generic first and then the most custom at the bottom to get a proper merge overwrite or is this resolved otherwise with the change to using ordered dictionaries?  I'm interested in seeing how much would need to be altered to use different branches in our git repositories to deploy our code base from a single top file for definition.

Thanks for all the work put in as this is a large problem that is quite complex from what I can understand.

**Comment by cachedout** [comment] 2015-06-22 16:23
@jmelfi I ended up running into a problem with `ordered_top_files` and so I'm changing it to support an `order:` flag for each env in `file_roots`. In the end, I think this is better since depending on ordering in a YAML dictionary is just asking for trouble. To answer your question though, yes, with the order flag set in your envs, the behaviour you describe is what should happen.

**Comment by cachedout** [comment] 2015-06-23 17:38
OK @jmelfi and @mathom. Have a look at #24878 and let me know what you think.

**Comment by jmelfi** [comment] 2015-06-23 17:42
@cachedout I'll give it a review over the next hour or so.  Thanks for the update!

**Comment by cachedout** [comment] 2015-06-23 17:44
@jmelfi Super. Be sure to configure things as described in the PR. It won't (or shouldn't) change behaviour out of the box. I'll be here if you have questions. Thanks for the testing help!

**Comment by DanyC97** [comment] 2015-07-24 21:11
wow, this was a long issue to read :))  Would love to see this merged soon, thx for the effort!

**Comment by cachedout** [comment] 2015-08-11 17:33
I have merged this fix into develop and it should be backported into the 2015.8 branch in the next day or two.

**Comment by basepi** [comment] 2015-08-11 17:34
:+1:

**Comment by rallytime** [comment] 2015-08-11 17:35
Back-port is in #26214. :)

**Comment by jmelfi** [comment] 2015-08-11 17:56
@cachedout sorry for a late reply here.  I was able to get the sorting to work properly after using the PR work.  Thanks you guys for this hard work.  I've been working the last week on moving from our puppet code completely into saltstack.

You guys are awesome!

**Comment by cachedout** [comment] 2015-08-11 18:00
@jmelfi I'm so glad! Thanks for testing this. For the time being, I am going to close this issue since we're using it to track progress toward our release. That doesn't mean, however, that people can't continue to post feedback here. We'll re-open it if we need to. Thanks again!

**Closed by cachedout** 2015-08-11 18:00 UTC
Labels: Beryllium, Blocker, Bug, Core, Fixed Pending Verification, High Severity, P1, ZD
