### ISSUE TITLE
archive.extracted tar_options does not support long options or non-option parameters

### ISSUE THREAD

**Issue by Bilge** [saltstack/salt#20795] opened 2015-02-18 14:53 UTC
### Since 2014.7.1

[This fix](https://github.com/saltstack/salt/pull/18345) only supports short options. It does not support long options or non-option parameters e.g. list of files to extract. If tests passed then the tests are surely deficient.

### Since 2014.7.0

The [documentation](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.archive.html#module-salt.states.archive) for `archive.extracted` claims that for `tar_options`:

>Main operators like -x, --extract, --get, -c and -f/--file **should not be used here**.

However, when I specify `- tar_options: --no-anchored foo` I receive the following error:

>      stderr:
          tar: You must specify one of the '-Acdtrux', '--delete' or '--test-label' options
          Try 'tar --help' or 'tar --usage' for more information.

I had to fix this error by manually adding `x`, against the command of the documentation. The following configuration worked: `- tar_options: x --no-anchored foo`.

**Comment by rallytime** [comment] 2015-02-18 19:16
@Bilge Can you post the output of `salt --versions-report` please?

**Comment by Bilge** [comment] 2015-02-18 23:55
>salt-ssh  --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: Not Installed
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: Not Installed
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: Not Installed
           RAET: Not Installed
            ZMQ: Not Installed
           Mako: 0.9.1

**Comment by rallytime** [comment] 2015-02-19 00:21
@Bilge Thanks for posting that. We actually had a regression here in 2014.7.0 as described in #18052, which has been fixed. The work around you've described of course works well for now, but the intended behavior was restored in 2014.7.1 where you do not have to specify the 'x'.

Since this is technically a duplicate and has also been fixed, is it alright if we close this?

**Comment by Bilge** [comment] 2015-02-19 11:44
It is not OK to close this. I updated to 2014.7.1 which now fails with both specifications. This version completely breaks `tar_options` for me.

**Comment by rallytime** [comment] 2015-02-19 16:00
Can you clarify what you mean by "which now fails with both specifications"? Removing the 'x' specification does not work for you either?

**Comment by Bilge** [comment] 2015-02-19 16:01
The following fail:

* - tar_options: --no-anchored foo
* - tar_options: x --no-anchored foo

**Comment by rallytime** [comment] 2015-02-19 16:04
Thanks for the clarification @Bilge. @jfindlay asked me to assign him to this one, so I'll defer to him on exploring this further.

**Comment by Bilge** [comment] 2015-02-19 16:08
@rallytime :+1: Thanks, I updated the issue title and description to reflect the current summary of affairs.

**Comment by jfindlay** [comment] 2015-02-19 16:18
@Bilge, #19930 is going into 2014.7.2, which should be released today or tomorrow.

**Comment by Bilge** [comment] 2015-02-19 17:27
@jfindlay I am not very good at Python, but judging from @highlyunavailable's [description](https://github.com/saltstack/salt/pull/19930#issue-55096435) the implementation is still incorrect:

> anything without a - to start gets appended to the "x" for extraction (e.g. "z" or "J")

That means that in my example, my path name *foo* will be sent to `tar` as: `tar xfoo --no-anchored` when it should be `tar x --no-anchored foo` because foo is the path name I want to extract, not tar options.

**Comment by highlyunavailable** [comment] 2015-02-19 17:59
@Bilge You're probably right, I didn't take non-parameter options into account. It would pass it as `tar xfoo` probably.

If you want to specify the path to extract to, I would love a `- extract_to: /foo` parameter but I don't know that other archive implementations can support it.

**Comment by jfindlay** [comment] 2015-02-19 18:00
What do you think about restricting short options to have length == 1?  The Real Solution I think is to enforce options, even short options being supplied with dashes, since the file pattern could potentially be one letter long:
```
- tar_options: -v -J --no-anchored f
```

**Comment by highlyunavailable** [comment] 2015-02-19 18:04
@jfindlay What if someone sets the options to `vJ` for example? The length thing would backfire then. The dash thing is going to backfire too since people (like me) have states with no dashes and concatenated short arguments.

**Comment by jfindlay** [comment] 2015-02-19 18:07
@highlyunavailable, you're right, I misunderstood at first.  What do you think of my revised patch?  You'd be required to concatenate all your short opts at the beginning of `tar_options`.

**Comment by jfindlay** [comment] 2015-02-19 18:09
Or we can deprecate `tar_options` in favor of `tar_shortopts` and `tar_longopts`, but that would have to go into 2015.2 at least and we would need to support both formats for a couple of releases.

**Closed** 2015-03-17 00:42 UTC
Labels: Bug, Fixed Pending Verification, Medium Severity, Needs Testcase, Regression

**Comment by Bilge** [comment] 2015-03-17 12:29
Should this have been closed while test cases are still outstanding?

**Comment by rallytime** [comment] 2015-03-17 14:50
@Bilge Thanks for pointing this out. It's actually ok that this is closed with out the tests being written yet. We use the "Needs Testcase" label differently than some of the other labels. We have a group of issues and pull requests with the label and within that group there are open and closed issues/PRs. When we write tests for the labeled item, we remove the "Needs Testcase" label. *Anything* that still has that label still needs test written for it. This helps distinguish between bugs that have been fixed but need tests, bugs that needs tests but still have not been fixed yet, as well as issues that are solely created to keep track of testing pieces of code.

**Comment by Bilge** [comment] 2015-03-17 15:19
@rallytime :+1: Thanks for the explanation, I understand the system you are using now.

**Comment by rallytime** [comment] 2015-03-17 15:38
No problem @Bilge! That whole process isn't documented anywhere, so it's a totally fair question.

This fix should be in the 2014.7.3 release, so you'll be able to try it out then! :)
