### ISSUE TITLE
Salt-ssh with sudo NOPASSWD required. 

### ISSUE THREAD

**Issue by hari316** [saltstack/salt#21719] opened 2015-03-16 23:02 UTC
Is it possible to ping remote server, without sudo configuration of the salt-minion machine  'sudo visudo' ??

 /etc/salt/roster:
```
test-ubuntu-minion01:
  host: 127.0.0.1
  user: abc
  passwd: ****
  sudo: True
```
Command:
`sudo salt-ssh -i 'test-ubuntu-minion01' state.sls test.ping`

```
   stderr:
        sudo: no tty present and no askpass program specified
        Sorry, try again.
        sudo: no tty present and no askpass program specified
        Sorry, try again.
        sudo: no tty present and no askpass program specified
        Sorry, try again.
        sudo: 3 incorrect password attempts

    stdout:
        ERROR: sudo expected a password, NOPASSWD required
```

**Comment by tbaker57** [comment] 2015-03-17 00:41
I think this is related to #8882.

cheers
Tim

**Comment by rallytime** [comment] 2015-03-17 15:46
I think @tbaker57 is right that this is a duplicate of #8882. However, @basepi might have more information about that.

@hari316 If you install `sshpass`, will that resolve the problem for you?

**Comment by hari316** [comment] 2015-03-17 22:18
I am still getting the error, even though sshpass is installed on salt-master and salt-minion.

/etc/salt/roster:

test-ubuntu-minion01:
  host: 10.xx.xxx.xxx
  user: username
  passwd: xxxxx
#  priv: /home/username/.ssh/id_rsa
  sudo: True

**Comment by basepi** [comment] 2015-03-17 22:38
Try adding `tty: True` to your roster entry.

**Comment by hari316** [comment] 2015-03-17 22:53
I get the following: 

```
[DEBUG   ] STDERR 10.xx.xxx.xxx
Connection to 10.20.165.207 closed.

[DEBUG   ] RETCODE 10.xx.xxx.xxx: 0
test-ubuntu-minion01:
    ----------
    _caller_cachedir:
        /var/cache/salt/master
    _error:
        Failed to return clean data
    _ssh_version:
        5.9p1 Debian-5ubuntu1.4
    ext_pillar:
    extension_modules:
        /var/cache/salt/extmods
    file_roots:
        ----------
        base:
            - /srv/salt
    id:
        test-ubuntu-minion01
    pillar_roots:
        ----------
        base:
            - /srv/pillar
    stderr:
        Connection to 10.xx.xxx.xxx closed.
```

In addition detailed dictionary as stdout

**Comment by basepi** [comment] 2015-03-18 20:40
Ah, now that I look at this in more detail, I do think it's a duplicate of #8882 and am going to close it as such.

**Closed by basepi** 2015-03-18 20:40 UTC
Labels: Pending Discussion, Salt-SSH

**Comment by hari316** [comment] 2015-03-18 20:47
@basepi I dont find any resolution to the issue, Kindly provide some pointer or the issue still exists ??

**Comment by basepi** [comment] 2015-03-18 20:59
#8882 is the issue that still exists. We don't yet support sudo with passwords over salt-ssh yet.

**Comment by basepi** [comment] 2015-03-18 20:59
But it is something we want to add.

**Comment by pythonwood** [comment] 2015-10-05 06:25
I am interested in salt too. and I wonder if pexpect library count help.

**Comment by ichilton** [comment] 2021-03-06 22:07
@basepi it seems that the ability to provide a sudo password was never added?

Is there no way of doing it?

Ansible does it.... it can prompt for the sudo password when running ansible.

**Comment by rallytime** [comment] 2021-03-08 13:38
@Ch3LL Can you comment on this issue about salt-ssh use with sudo password?
