### ISSUE TITLE
Feature request: cleanup old mine data on master

### ISSUE THREAD

**Issue by marek-obuchowicz** [saltstack/salt#11389] opened 2014-03-20 17:15 UTC
Whenever I remove a node, master still keeps it's mine information cached and sends it to all minions. Calling salt '*' mine.flush doesn't help, as master still has old mine data from not existing nodes. Calling salt-run cache.clear_mine on master also leaves all the cached data on master unchanged.

As a manual fix, I had to go to /var/cache/salt/master/minons and manually remove directories for minions, which don't exist anymore.

**Comment by dansoap** [comment] 2015-01-21 21:03
Ran into the same issue. I didn't destroy some servers using salt-cloud, so flush_mine_on_destroy didn't work of course.

@marek-obuchowicz: Thanks for the workaround, that did the trick for me...

**Comment by wt** [comment] 2015-01-21 22:11
Is there a reason not to just default that option to True? Seems like it'd be an strange default to keep the mine data.

**Comment by basepi** [comment] 2015-01-23 23:31
@wt You mean flush_mine_on_destroy? Yes, it does seem like True is a saner default there. I'll have to ask around for potential pitfalls there.

**Comment by wt** [comment] 2015-01-24 00:04
@basepi ack

**Comment by tkent-xetus** [comment] 2015-05-09 01:08
For what it's worth, mine data being removed when salt-cloud destroyed a minion is what I expected. Ended up at this issue trying to figure out why that wasn't happening.

**Comment by rikonor** [comment] 2015-05-31 19:59
@wt thanks for your example, I created a runner based on it over at [salt-mine-refresh](https://github.com/rikonor/salt-mine-refresh) that can be called from events, scheduled, etc

**Comment by jgmchan** [comment] 2015-07-15 05:36
:+1: for this feature, it can cause some weird issues for formulas which relies on this information like HDFS

**Comment by BretFisher** [comment] 2015-07-30 04:50
Yea I can't use salt-cloud to destroy and just assumed when `salt-key -d` was used it would cleanup mine. Thought it was a bug. Workaround from @wt works for me, but wished it was automatic.

**Comment by timcharper** [comment] 2015-10-27 15:58
I used `salt-cloud` to destroy an instance with `flush_mine_on_destroy: True` in salt 2015.5.3 and the data was left behind.

 ༼ ༎ຶ ෴ ༎ຶ༽

**Comment by imchairmanm** [comment] 2015-10-28 22:02
I'd like to add my vote for this feature.  It seems more like a bug fix to me though.  I'm not the most advanced user, but I can't think of a scenario where keeping the mine data for deleted nodes by default would be expected behavior.

Can we at least get some doc updates about the current behavior?  I'm finding myself having to look at GitHub issues and source code instead of the docs very frequently to get a handle on the actual way that SaltStack functions, which is unfortunate.

**Comment by basepi** [comment] 2015-10-29 21:28
I'm going to look into possibly adding this for Boron. No promises, though, I've assigned myself too much work for Boron already. ;)

**Comment by Dravu** [comment] 2015-10-29 21:44
Thanks @basepi! I ran into this earlier today and while it was diagnosed fairly quickly, it certainly didn't seem like intended/expected functionality. I personally expected a minion's cached data to get deleted once their key is revoked. Even some sort of sync or refresh functionality for the master's cache would work I suppose.

**Comment by danlsgiga** [comment] 2016-02-04 19:21
+1
I also thought this would be the default behaviour. Looking forward to get this feature in the next release.

**Comment by wt** [comment] 2016-02-04 19:52
Honestly, I think that the master should be smart enough not to respond with data from nodes that should be gone. I'm am a little worried about the case where the master crashes between removing the key and removing the mine data. I feel like the master should do something that is atomic so that failures have less chance of causing issues.

**Comment by basepi** [comment] 2016-02-05 18:44
You might be right. In addition to cleanup, we should probably filter mine results against accepted keys as well.

**Comment by anlutro** [comment] 2016-03-03 19:07
FWIW, I ran `salt-run cache.clear_all name-of-minion` after shutting down a minion today, and that cleared the mine data. Not sure if that's an intentional fix since this issue seems to indicate that it's still a problem?

**Comment by danlsgiga** [comment] 2016-03-03 22:41
Hey @anlutro, thanks for the trick. I can confirm that using `salt-run cache.clear_all name-of-minion` the cache is properly cleared.
I've also tested using a reactor to clear the minion cache once the minion is destroyed and it works seamlessly. Here is the reactor formula:

_/srv/reactor/clear_minion_cache.sls_


    clear_minion_cache:
      runner.cache.clear_all:
        - tgt: {{ data.id }}

**Comment by wt** [comment] 2016-03-04 02:03
This is a cool workaround.

However, there is still (presumably small) risk that the salt master crashes while doing that and doesn't remove everything. I'd still like to see the proactive filtering to make sure stray files don't cause problems.

**Comment by Reiner030** [comment] 2016-08-17 15:06
Hi, last error comments for this behavior are coming from still open bug https://github.com/saltstack/salt/issues/21986 which didn't clear cache since saltstack versions 2015.5.x (https://github.com/saltstack/salt/issues/21986#issuecomment-123132269).

Thx to @danlsgiga for the reactor state definition. I was searching for it (and therefore found this issue) but there is yet no official documentation howto use runner states in reactor definitions ...

**Comment by ealphonse** [comment] 2017-02-26 10:34
Hello, I tested this feature,as I am evaluating Mine, and `salt-key -d` does delete the minion's mine data on 2016.11.2.

Did something change? What is the issue status?

Thanks

**Comment by gtmanfred** [comment] 2017-02-27 14:59
This was implemented, but it appears that it might be broken for some cases?

I am closing this in favor of https://github.com/saltstack/salt/issues/21986

**Closed by gtmanfred** 2017-02-27 14:59 UTC
Labels: Core, Feature, P3

**Comment by ealphonse** [comment] 2017-02-27 15:03
@gtmanfred thank you for the info
