### ISSUE TITLE
Unable to send HTTP POST request with json encoded body when using http.query module

### ISSUE THREAD

**Issue by golmaal** [saltstack/salt#45759] opened 2018-01-29 17:47 UTC
### Description of Issue/Question
I am trying to use http.query and send "Content-Type: application/json" to our REST API server where the body is json-encoded. 
I can send urlencoded HTTP POST messages to Salt CherryPy as following -

```
salt-call http.query http://localhost:8000/login method=POST header_dict='{"Accept":"application/x-yaml", "Content-Type":"application/x-www-form-urlencoded"}' data='{"username": "saltapi", "password": "Random", "eauth": "pam"}' backend=requests
salt-call http.query http://localhost:8000 method=POST header_dict='{"Accept":"application/x-yaml", "Content-Type":"application/x-www-form-urlencoded", "X-Auth-Token": "3b332b5191f321655a2459f6e488ab991b8ab7b8"}' data='{"client": "local", "tgt": "master", "fun": "test.ping"}' backend=requests
```
Question - How do I do the same where the body is json encoded? When I use the following, I get error - 
```
salt-call http.query http://localhost:8000/login method=POST header_dict='{"Accept":"application/x-yaml", "Content-Type":"application/json"}' data='{"username": "saltapi", "password": "Random", "eauth": "pam"}' backend=requests
```
Error thrown by above - 
```
[06:32:01.681] [ERROR   ] An un-handled exception was caught by salt's global exception handler:
HTTPError: 400 Client Error: Bad Request
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/http.py", line 33, in query
    return salt.utils.http.query(url=url, opts=__opts__, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/http.py", line 316, in query
    result.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

I looked at the http.py in salt/utils, it seems to be not passing json value to sess.request method. This happens even when I explicitly supply it on command line because req_kwargs doesn't pick it from kwargs from parameters passed to query method. 

The following example shows the desired HTTP POST message using http.query execution module... 

```
import requests
import ast

sess = requests.Session()
header_dict = {"Content-Type": "application/json"}
sess.headers.update(header_dict)
method = 'POST'
url = 'http://localhost:8000/login'
json = [{"username":"saltapi", "password":"Random", "eauth":"pam"}]
result = sess.request(method, url, json=json)
token = ast.literal_eval(result.content)['return'][0]['token']

header_dict = {"Content-Type": "application/json", "X-Auth-Token": token}
sess.headers.update(header_dict)
url = 'http://localhost:8000'
json = [{"client":"local", "tgt":"master", "fun":"test.ping"}]
result = sess.request(method, url, json=json)
result.content
```
The above sends an HTTP POST request with application/json encoded body in the HTTP request. I can attach the Wireshark captures if needed.

Questions - 
**Am I using the http.query incorrectly? If no, could you please help me construct it correctly so my REST server which doesn't support urlencoded data could be sent the json encoded data.**

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment] 2018-01-30 22:29
So, i think that if the data is passed in is converted to a dict, it is then just passed as _urlencoded.

Can you try double quoting this string?

```
data="'{\"username\": \"saltapi\", \"password\": \"Random\", \"eauth\": \"pam\"}'"
```

Everything thing that comes in on the commandline gets passed through the pyyaml renderer.  I think the problem is that the single quoted dictionary gets converted into a dict in python, and that is passed through urlencode.  If it is double quoted, yaml will strip off the first set of quotes, and and will be a json quoted string.

```
>>> import yaml
>>> yaml.load("'{\"username\": \"saltapi\", \"password\": \"Random\", \"eauth\": \"pam\"}'")
'{"username": "saltapi", "password": "Random", "eauth": "pam"}'
```

Thanks,
Daniel

**Comment by golmaal** [comment] 2018-01-31 17:24
Hello Daniel,

Thanks for looking at this issue. I tried as you suggested and that seems to work. A couple of caveats with this approach are - 

1. All double quotes for the key/val need to be escaped
2. All special characters (e.g., in my actual password I had a $) need to be escaped.

Will using a data file be any different? 
Do you have suggestion to not have to escape the above two things?

Regards,
Vishal

**Comment by gtmanfred** [comment] 2018-01-31 18:04
To get away from not having to escape those things, you could write a python command that uses LocalClient to send the command instead of using the commandline.

Pulling from a data file might work, but it would be dependent on how the data file is loaded, which i am not familiar with in the code.

As this works now, I am going to close this issue.

Thanks!
Daniel

**Closed by gtmanfred** 2018-01-31 18:04 UTC
Labels: Info Needed
