### ISSUE TITLE
Archive.extracted fails if -user: root is specified

### ISSUE THREAD

**Issue by lordcirth** [saltstack/salt#37969] opened 2016-11-29 19:43 UTC
### Description of Issue/Question

archive.extracted fails with the confusing error: "User root does not exist" if - user: root is specified.
The bug appears to have been introduced in https://github.com/saltstack/salt/commit/3014afd51700e336b74bd4a73f2f1f1b36f95e0b , in archive.py .  if the uid is 0, the state reports that user doesn't exist.

Looking at the code, the same problem will happen if the group 'root' is specified.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
The failing state:

```
nextcloud_extract:
  archive.extracted:
    - name: /var/www
    - source: https://download.nextcloud.com/server/releases/nextcloud-{{ pillar['nextcloud']['version'] }}.tar.bz2
    - source_hash: https://download.nextcloud.com/server/releases/nextcloud-{{ pillar['nextcloud']['version'] }}.tar.bz2.sha256
    # 755/644 therefore read only by default
    - user:   root
    - group:  www-data
    - if_missing: /var/www/nextcloud
    - archive_format: tar
    - require:
      - pkg: nextcloud_packages
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Create a archive.extracted state.   Specify "- user: root ".  state.apply. State run fails with "User root does not exist".  /etc/passwd is intact, su and sudo work, etc.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
salt --versions-report:

Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial

salt-minion --version:
salt-minion 2016.11.0 (Carbon)
```

Boron does not appear to have this problem, it appeared after I updated salt-minion from a mirror of repo.saltstack.com/ .

**Comment by lordcirth** [comment] 2016-11-29 20:03
Note that leaving user or group unspecified works correctly, and is the workaround for this bug.

**Comment by Ch3LL** [comment] 2016-11-29 21:52
@lordcirth looks like i'm able to replicate this.

Here is a docker container for whoever wants to quickly replicate this:

1. `docker run -it -v /home/ch3ll/git/salt:/testing ch3ll/issues:37969 salt-call --local state.sls test` (where /home/ch3ll/git/salt is a local git repo of salt)

We will need to get this fixed up thanks. ping @terminalmage just fyi

**Comment by fcuozzo** [comment] 2016-11-30 01:26
Just dropping a note to say that we hit this issue as well. Looking forward to the fix. 
Workaround does work but will likely revert to a prior salt version until it's released.

**Comment by wolfpackmars2** [comment] 2016-11-30 01:49
I've been looking at this and I'm guessing that `__salt__['user.info'](runas)` is returning 0 to represent user id zero, or root.  Testing if the (function, dictionary?) returns a valid user object with `if uinfo:` returns false because that would be the same as `if 0:` which will evaluate to false.  This same test is used throughout salt.  I'm sure I've run into this problem myself, as have others.  The fix was probably just not to specify a user: root.  Which is fine and dandy, if Salt is run as root... but I imagine this would be a problem for environments running salt under an account other than root.

However, if you are running under an account that can impersonate root anyways (ie - execute commands as root, which is essentially what you are trying to do here with archive.extracted), then what would be the point of running salt under an account other than root?

I was hoping to find where __salt__['user.info'] is defined but was unable.  Specifically, I wanted to see if that object could be modified to avoid this problem, or if __salt__['user.info'] would return a None object that could be tested for `if is None uinfo:` would be more accurate.  This would require many changes throughout salt's codebase, from what I've seen, because `if uinfo` or similar is used *everywhere.

The desired result is achieved by omitting user: root, correct?  No need to downgrade salt - which likely only works because it wasn't possible to specify the user?

**Comment by ehibbsBV** [comment] 2016-11-30 17:19
This is not just a problem when specifying that the user is root, it's any user. My current workaround is to remove the user spec, then add a cmd.run chown on all extracted files.

**Comment by terminalmage** [comment] 2016-11-30 17:23
Looking at this now.

**Comment by terminalmage** [comment] 2016-11-30 18:37
@lordcirth You say that the problem appears to have been introduced in 3014afd, but that change never made it to the 2016.3 release cycle as it was submitted to what became 2016.11.0.

**Comment by terminalmage** [comment] 2016-11-30 18:58
Ahh, I see the problem. ``salt --versions-report`` is run on the master so it gives you the master version. Just FYI, it is not recommended to update the minion to a higher version than the master. The reason for this is that sometimes the way in which we pass around data from master to minion changes, and the newer version of the minion will be expecting information formatted in a way that the master won't be sending it, if the master is an older release.

At any rate, I can reproduce on 2016.11.0. Working on a fix.

**Comment by terminalmage** [comment] 2016-11-30 19:24
Fixed in https://github.com/saltstack/salt/pull/38004

**Closed** 2016-12-19 20:21 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P4, State Module
