### ISSUE TITLE
event teardown is broken in develop

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#20898] opened 2015-02-21 13:17 UTC
this rels #20869

Sometime at the end of the runners, i get:
```
[DEBUG   ] an integer is required
```
The incoming pullrequest will fix that.

**Comment by jacksontj** [comment] 2015-02-21 20:40
@kiorky How do you reproduce this case?

**Comment by jacksontj** [comment] 2015-02-21 20:57
From chatting on IRC seems that its not broken, just seeing some useless debug log messages on interpreter shutdown.

**Comment by kiorky** [comment] 2015-02-21 21:29
I just pushed a better fix (and a rebased branch)

**Comment by jacksontj** [comment] 2015-02-21 21:36
This doesn't make a lot of sense to me. The problem you are trying to workaround is a bit bigger than this patch. The issue you are running into is the non-deterministic order of the python interpreter's shutdown. This patch won't work on all combinations of python/zmq as the order of global cleanup is *not* gauranteed. 

In addition, there doesn't seem to be any need for the "swallow" kwarg as you can just do the same exception handling up in __del__ instead of in destroy (such as what already exists)

**Comment by kiorky** [comment] 2015-02-21 21:36
either a global try/catch or a specific swallow is ok for me.

**Comment by jacksontj** [comment] 2015-02-21 21:38
It already contains the global try/catch and #20905 removes the log line (since we can't trust that the logger will work).

**Comment by jfindlay** [comment] 2015-02-23 17:01
@kiorky, @jacksontj, thanks for working this out.

**Comment by cachedout** [comment] 2015-03-19 05:38
Sounds like this is resolved so I'm going to go ahead and close this.

**Closed by cachedout** 2015-03-19 05:38 UTC
Labels: Bug, Medium Severity
