### ISSUE TITLE
file:// sources for stats.file.manages shouldn't need a hash

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#26513] opened 2015-08-20 14:17 UTC
https://github.com/saltstack/salt/issues/26497#issuecomment-132993864 claims that `source_hash` must be specified for `file://` sources in `states.file.managed`. I have a use case where I have a debian package installing a template, and I'd like to populate that file. That means I don't have the checksum at hand when I'm defining my state.

Proposal: Not require `source_hash` for `file://` sources.

**Comment by jfindlay** [comment] 2015-08-20 18:10
@JensRantil, thanks for the feature request.

**Comment by terminalmage** [comment] 2016-10-14 16:27
This looks to have been fixed before or during the 2015.8 release cycle, I can't reproduce this on any non-EOL release.  Using either ``/path/to/file`` or ``salt:///path/fo/file`` does not require a ``source_hash`` param.

Marking this as closed.

**Closed by terminalmage** 2016-10-14 16:27 UTC
Labels: Feature, P3, Platform
