### ISSUE TITLE
pkgrepo.managed fails with UTF8 characters in PPA repository name

### ISSUE THREAD

**Issue by sc250024** [saltstack/salt#30490] opened 2016-01-21 01:28 UTC
Greetings,

The problem I ran into involves using SaltStack to obtain certain Ubuntu PPAs. In our organization we use PHP 5.6 for development, and for Ubuntu 14.04.3 LTS release, we use the PPA provided here: https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6

We use SaltStack to manage our PPAs. In our formula that has the list of PPAs we put on each machine, we have the following for PHP 5.6 from that Launchpad repo:

```
...
php56-ppa:
  pkgrepo.managed:
    - ppa: ondrej/php5-5.6
    - refresh_db: true
...
```

The other PPAs install fine, but when running the next `apt-get update`, we receive the following error from Ubuntu:

```
W: GPG error: http://ppa.launchpad.net trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C
```

That key in question is from the repository at https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6. If you notice, that developer's name is using UTF8 characters. The PPA page mentions an error with non-UTF8 locales as being a problem:

```
WARNING: add-apt-repository is broken with non-UTF-8 locales, see https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

# apt-get install -y language-pack-en-base
# LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php5-5.6
```

The workaround mentioned (https://github.com/oerdnj/deb.sury.org/issues/56) says to check your locales, but those are fine. In fact, I use SaltStack to make sure all of my environments are UTF8 based. 

```
root@salt-minion:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

The fix is for us to manually run the command `apt-add-repository ppa:ondrej/php5-5.6`, but that sort of defeats the purpose. You can also configure Salt to manually configure that repository using the `key_url` parameter; that will add the key name to `/etc/apt/trusted.gpg`, but again, that counteracts the functionality of simply being able to name the PPA repo, and have Salt automatically configure it for you.

I believe the problem has to do with which encoding Salt master uses to install PPAs on the target minions. 

```
root@salt-master# salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

```
root@salt-master:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

The offending GPG key is as follows for a *working* machine:
```
root@salt-minion:~# apt-key list
...
/etc/apt/trusted.gpg.d/ondrej-php5-5_6.gpg
------------------------------------------
pub   1024R/E5267A6C 2009-01-26
uid                  Launchpad PPA for Ondřej Surý
...
```

**Comment by jfindlay** [comment] 2016-01-21 19:34
@sc250024, thanks for the report.  Salt [defaults](https://github.com/saltstack/salt/blob/v2015.5.5/salt/modules/cmdmod.py#L345) to the `C` locale for command execution, which might be getting in the way here.

**Comment by jfindlay** [comment] 2016-01-21 19:57
@sc250024, this is actually a duplicate of #23543.  If you have any further information, please comment there.  Thanks.

**Closed by jfindlay** 2016-01-21 19:57 UTC
Labels: Bug, Duplicate, Execution Module, High Severity, P4, Platform
