### ISSUE TITLE
win_firewall generates an error in the minion log

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#31435] opened 2016-02-23 15:22 UTC
I run this sls:

``` yml
open_ports_rdp:
  win_firewall.add_rule:
    - name: Remote Desktop
    - localport: 3389
    - protocol: tcp
    - action: allow
```

And this is what happens in the log on the minion:

```
2016-02-23 15:18:06 [salt.state     ][INFO    ] Running state [Remote Desktop] at time 15:18:06.158000
2016-02-23 15:18:06 [salt.state     ][INFO    ] Executing state win_firewall.add_rule for Remote Desktop
2016-02-23 15:18:06 [salt.loaded.int.module.cmdmod][INFO    ] Executing command ['netsh', 'advfirewall', 'firewall', 'show', 'rule', 'name=Remote Desktop'] in directory 'C:\\Windows\\system32\\config\\systemprofile'
2016-02-23 15:18:06 [salt.loaded.int.module.cmdmod][ERROR   ] Command ['netsh', 'advfirewall', 'firewall', 'show', 'rule', 'name=Remote Desktop'] failed with return code: 1
2016-02-23 15:18:06 [salt.loaded.int.module.cmdmod][ERROR   ] output: 
No rules match the specified criteria.
2016-02-23 15:18:06 [salt.loaded.int.module.cmdmod][INFO    ] Executing command ['netsh', 'advfirewall', 'firewall', 'add', 'rule', 'name=Remote Desktop', 'protocol=tcp', 'dir=in', 'localport=3389', 'action=allow'] in directory 'C:\\Windows\\system32\\config\\systemprofile'
2016-02-23 15:18:06 [salt.state     ][INFO    ] {'new rule': 'Remote Desktop'}
2016-02-23 15:18:06 [salt.state     ][INFO    ] Completed state [Remote Desktop] at time 15:18:06.267000
```

The rule is in fact created on the minion, but I figured I'd report the fact that there's an `ERROR` as well.

I'm on Windows 10. Minion versions report:

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: 10 10.0.10240  Multiprocessor Free
```

**Comment by jfindlay** [comment] 2016-02-23 17:55
@fredrikaverpil, thanks for reporting.

**Comment by rrzaripov** [comment] 2016-03-10 07:53
Same situation with the execution module:

```
user@salt:/home/user$ salt win-test firewall.add_rule 'port104' '104' 'tcp'
win-test:
    False
user@salt:/home/user$ salt win-test firewall.get_config
win-test:
    ----------
user@salt:/home/user$ salt win-test firewall.disable
win-test:
    False
user@salt:/home/user$ salt win-test firewall.enable
win-test:
    False
```
All actions actually successfully done, but return value is False.

**Comment by otupman** [comment] 2017-02-01 09:10
We see the same error in the log file. 
 
I did a little digging and my belief is that this is caused by the state [win_firewall.py](https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/states/win_firewall.py#L89) when it checks for the existence of a rule prior to adding.  It does this by attempting get the rule via the win_firewall module.  

    # Check if rule exists
    commit = False
    current_rules = __salt__['firewall.get_rule'](name) # here it attempts to get the rule
    if not current_rules:
        commit = True
        ret['changes'] = {'new rule': name}

The [win_firewall.py](https://github.com/saltstack/salt/blob/4c2d4159fd8705d1b3bb8f90500635f8ccec4f22/salt/modules/win_firewall.py#L138) then attempts to get the rule by calling `netsh`, which fails of course as the rule does not exist. The default behaviour of `cmd.run` is to [log that as a failure](https://github.com/saltstack/salt/blob/a380c12159a3a6691081d30e33c16e6f534c4482/salt/modules/cmdmod.py#L932), hence the erroneous error in the log.

I'd suggest that adding a `rule_exists` call to the `win_firewall` module would be the way to go. Alternatively perhaps the `win_firewall` could pass in to `cmd.run` a log level that prevents the error being logged...

**Comment by rickh563** [comment] 2017-05-22 22:07
ZD-1466

**Comment by twangboy** [comment] 2017-05-26 22:37
The above PR should fix these issues. Will be in 2016.11.6 release.

**Closed** 2017-05-26 22:39 UTC
Labels: 2016.11.6, Blocker, Bug, High Severity, P3, Platform, State Module, Windows, ZD
