### ISSUE TITLE
Minion-master authentication fails

### ISSUE THREAD

**Issue by kriberg** [saltstack/salt#20630] opened 2015-02-12 14:53 UTC
I'm having issues with minions going into an unresponsive state, quite similar to issued #5768 and #16680. 

I'm running in multi-master node with two masters. Both are RedHat 6.6 with salt-master from epel:

```
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

In addition to the default configuration, pillar and state backend, I have worker_threads set to 20 and timeout to 10.

Minions are all RedHat 7.0 with salt-minion from epel:

```
           Salt: 2014.7.0
         Python: 2.7.5 (default, Feb 11 2014, 07:46:25)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

After installation and start of the minion, it connects to the master successfully and I accept the key on the master. Then when I try applying states on those minions, they do not respond at all. Running with salt -v, I get various output. Some are disconnected, some are not responding, some does answer. 

For those which are not responding, they either run the actual state that's being applied, as evident from the local minion log, or they fail with the minion log full of (error-1):

```
2015-02-12 15:14:45,521 [salt.minion      ][CRITICAL] An exception occurred while polling the minion
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1726, in tune_in_no_block
    self._do_socket_recv(socks)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1760, in _do_socket_recv
    self._handle_payload(payload)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 866, in _handle_payload
    payload['sig'] if 'sig' in payload else None)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 897, in _handle_aes
    data = self.crypticle.loads(load)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 791, in loads
    data = self.decrypt(data)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 774, in decrypt
    raise AuthenticationError('message authentication failed')
AuthenticationError: message authentication failed
```

Minions with message [Not connected] have logged (error-2):

```
2015-02-10 20:20:10,329 [salt.log.setup   ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltReqTimeoutError: SaltReqTimeoutError: after 21600 seconds, ran 3 tries
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 56, in salt_minion
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/__init__.py", line 264, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 557, in tune_in
    minion['minion'].pillar_refresh()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1411, in pillar_refresh
    self.opts['environment'],
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 234, in crypted_transfer_decode_dictentry
    ret = self.sreq.send('aes', self.auth.crypticle.dumps(load), tries, timeout)
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 224, in send
    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
SaltReqTimeoutError: SaltReqTimeoutError: after 21600 seconds, ran 3 tries
```

Other disconnected minions fail Immediately after master accepts the key (error-3):

```
2015-02-09 16:06:01,652 [salt.crypt       ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-02-09 16:06:12,000 [salt.log.setup   ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 56, in salt_minion
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/__init__.py", line 264, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 504, in tune_in
    minions = self.minions()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 484, in minions
    minions = self._gen_minions()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 470, in _gen_minions
    minions.append(Minion(s_opts, 5, False))
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 603, in __init__
    opts['environment'],
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 236, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
```

This last error message, error-3, is the only one seen consistently directly after accepting keys. The others can occur whenever. Minions previously connected and whom have previously run states and responded correctly, will also stop responding. So it's not isolated as one-time event. 

```
́́# salt-run manage.up|wc -l; salt-run manage.down|wc -l
13
65
```

Restarting the masters and minions can make the number of minions up increase, but after a while they stop responding again.

For error-3, restarting the minion service will make it reconnect and behave normally. There doesn't seem to be a consistent way to get error-1 and error-2 to stop occuring occationally.

**Comment by jfindlay** [comment] 2015-02-13 16:16
@kriberg, thanks for the detailed report.  We've found that upgrading to >=zmq-4.0 will resolve many of these communication errors.

**Comment by kriberg** [comment] 2015-02-16 10:47
I've been running a minion with rhel 5 and zmq 4.0.4 too:
```
# salt-call --versions
           Salt: 2014.7.0
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:34)
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
 msgpack-python: 0.1.12
   msgpack-pure: Not Installed
       pycrypto: 2.3
        libnacl: Not Installed
         PyYAML: 3.08
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

This minion stopped during the weekend (error-4):

```
2015-02-13 22:51:31,056 [salt.minion                                 ][INFO    ] Authentication with master at 10.246.159.5 successful!
2015-02-13 22:51:31,057 [salt.minion                                 ][INFO    ] User root Executing command pillar.items with jid 20150213225122432621
2015-02-13 22:51:31,075 [salt.minion                                 ][INFO    ] Starting a new job with PID 24262
2015-02-13 22:51:31,882 [salt.minion                                 ][INFO    ] Returning information for job: 20150213225122432621
2015-02-13 22:59:41,591 [salt.minion                                 ][INFO    ] User root Executing command pillar.items with jid 20150213225941586524
2015-02-13 22:59:41,606 [salt.minion                                 ][INFO    ] Starting a new job with PID 26838
2015-02-13 22:59:42,339 [salt.minion                                 ][INFO    ] Returning information for job: 20150213225941586524
2015-02-13 22:59:48,843 [salt.minion                                 ][INFO    ] User root Executing command pillar.items with jid 20150213225948839117
2015-02-13 22:59:48,857 [salt.minion                                 ][INFO    ] Starting a new job with PID 26848
2015-02-13 22:59:49,583 [salt.minion                                 ][INFO    ] Returning information for job: 20150213225948839117
2015-02-13 23:00:54,804 [salt.minion                                 ][INFO    ] User root Executing command saltutil.refresh_pillar with jid 20150213230054800216
2015-02-13 23:00:54,819 [salt.minion                                 ][INFO    ] Starting a new job with PID 26865
2015-02-13 23:00:54,859 [salt.minion                                 ][INFO    ] Returning information for job: 20150213230054800216
2015-02-14 01:00:57,318 [salt.payload                                ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 1 of 3)
2015-02-14 03:00:57,320 [salt.payload                                ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 2 of 3)
2015-02-14 05:00:57,323 [salt.payload                                ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 3 of 3)
2015-02-14 05:00:57,335 [salt.log.setup                              ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltReqTimeoutError: SaltReqTimeoutError: after 21600 seconds, ran 3 tries
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 56, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 264, in start
    self.minion.tune_in()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 557, in tune_in
    minion['minion'].pillar_refresh()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1411, in pillar_refresh
    self.opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 234, in crypted_transfer_decode_dictentry
    ret = self.sreq.send('aes', self.auth.crypticle.dumps(load), tries, timeout)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 224, in send
    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
SaltReqTimeoutError: SaltReqTimeoutError: after 21600 seconds, ran 3 tries
```

So I've seen this error for zmq4 too.

**Comment by jfindlay** [comment] 2015-02-16 15:22
Do you have any reason to suspect the network topology between the master and minion: complex network, distance, firewalls, VPNs, etc.?  I've seen a few issues come in similar to this.  I know that @basepi has seen more and I'm still trying to figure out how they're (not) related and what may be other causes worth exploring.

**Comment by jfindlay** [comment] 2015-02-16 15:23
I'd like to collect all the issues we have like this so I can try to better sort out what is happening.

**Comment by kriberg** [comment] 2015-02-19 09:51
The network is separated into different VLANs and the minions are spread out across 3-4 different virtual hosts. There are firewalls between some of the VLANs, but there are established openings between those. All keys are accepted and the minions at least connects initially, so something is working at least.

**Comment by jfindlay** [comment] 2015-02-19 16:32
@kriberg, with [this patch](https://github.com/saltstack/salt/pull/20774) backported to 2015.2, I'm hoping that we can find more explicit, interesting things happening at the transport layer that affect basic master/minion communication.  At around 0.10 packet loss, minion replies fail even when the master is actively looking with [find_job](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.find_job).

**Comment by jfindlay** [comment] 2015-02-19 18:35
https://github.com/saltstack/salt/pull/20838

**Comment by igorwidlinski** [comment] 2015-02-24 05:00
We are receiving exactly same errors as kriberg's 2nd comment. Our minions seem to return to normal operations (ie can be ping with test.ping) after the 3 timeouts happen 6 hours later:

2015-02-23 12:48:22,328 [salt.minion                                 ][INFO    ] Starting a new job with PID 29596
2015-02-23 12:48:22,331 [salt.utils.event                            ][DEBUG   ] SaltEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_6d9691626f_pub.ipc
2015-02-23 12:48:22,332 [salt.utils.event                            ][DEBUG   ] SaltEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_6d9691626f_pull.ipc
2015-02-23 12:48:22,334 [salt.utils.event                            ][DEBUG   ] Sending event - data = {'_stamp': '2015-02-23T12:48:22.333264'}
2015-02-23 12:48:22,335 [salt.minion                                 ][DEBUG   ] Handling event 'pillar_refresh||||||\x81\xa6_stamp\xba2015-02-23T12:48:22.333264'
2015-02-23 12:48:22,361 [salt.minion                                 ][INFO    ] Returning information for job: 20150223124822297185
2015-02-23 12:48:22,437 [salt.crypt                                  ][DEBUG   ] Decrypting the current master AES key
2015-02-23 12:48:22,438 [salt.crypt                                  ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-02-23 12:48:22,462 [salt.crypt                                  ][DEBUG   ] Decrypting the current master AES key
2015-02-23 12:48:22,462 [salt.crypt                                  ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-02-23 14:48:22,624 [salt.payload                                ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 1 of 3)
2015-02-23 16:48:22,658 [salt.payload                                ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 2 of 3)
2015-02-23 18:48:22,759 [salt.payload                                ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 3 of 3)
2015-02-23 18:48:22,760 [salt.minion                                 ][DEBUG   ] Exception while handling events
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1590, in tune_in
    self.pillar_refresh()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1411, in pillar_refresh
    self.opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 234, in crypted_transfer_decode_dictentry
    ret = self.sreq.send('aes', self.auth.crypticle.dumps(load), tries, timeout)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 224, in send
    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
SaltReqTimeoutError: SaltReqTimeoutError: after 21600 seconds, ran 3 tries


I kind of noticed connection on port 4506 between minion and master  lingers for a long time with very little traffic (if any??). Also I  notice today when running ' salt 'servername*' saltutil.refresh_pillar -b 5' our firewall would block first data from minion -> master:4506 as this connection was dropped from its active connections table. So when minion sent data to master:4506 it was  BLOCKED. It seems like the minion did create new connection to master:4506 but the original connection never went away or timed out.... until 6 hours later.. During this 6 hours the minion was not reachable.

The master sees nothing wrong. Seem  like the initial job finished alright:
2015-02-23 12:48:14,368 [salt.master                                ][INFO    ] Got return from node004.fuzzybunnies for job 20150223124814143424
2015-02-23 12:48:22,344 [salt.master                                ][INFO    ] Authentication request from node004.fuzzybunnies
2015-02-23 12:48:22,344 [salt.master                                ][INFO    ] Authentication accepted from node004.fuzzybunnies
2015-02-23 12:48:22,368 [salt.master                                ][INFO    ] Authentication request from node004.fuzzybunnies
2015-02-23 12:48:22,368 [salt.master                                ][INFO    ] Authentication accepted from node004.fuzzybunnies
2015-02-23 12:48:22,552 [salt.master                                ][INFO    ] Got return from node004.fuzzybunnies for job 20150223124822297185
2015-02-23 18:48:22,797 [salt.master                                ][INFO    ] Authentication request from node004.fuzzybunnies
2015-02-23 18:48:22,797 [salt.master                                ][INFO    ] Authentication accepted from node004.fuzzybunnies
2015-02-23 18:48:22,824 [salt.master                                ][INFO    ] Authentication request from node004.fuzzybunnies
2015-02-23 18:48:22,825 [salt.master                                ][INFO    ] Authentication accepted from node004.fuzzybunnies
2015-02-23 18:48:22,853 [salt.master                                ][INFO    ] Authentication request from node004.fuzzybunnies
2015-02-23 18:48:22,853 [salt.master                                ][INFO    ] Authentication accepted from node004.fuzzybunnies
2015-02-23 18:48:22,892 [salt.master                                ][INFO    ] Authentication request from node004.fuzzybunnies
2015-02-23 18:48:22,892 [salt.master                                ][INFO    ] Authentication accepted from node004.fuzzybunnies
2015-02-23 18:48:23,033 [salt.master                                ][INFO    ] Authentication request from node004.fuzzybunnies
2015-02-23 18:48:23,033 [salt.master                                ][INFO    ] Authentication accepted from node004.fuzzybunnies
2015-02-23 18:48:23,035 [salt.master                                ][INFO    ] Got return from node004.fuzzybunnies for job 20150223125005022024
2015-02-23 18:48:23,052 [salt.master                                ][INFO    ] Got return from node004.fuzzybunnies for job 20150223125010035529


This is very frustrating as I am just start replacing our current configuration management software (which i should not name) with salt... Until now I had no major issues, this seems to only happen with saltutil.refresh_pillar (i could be wrong on this one though...)

**Comment by basepi** [comment] 2015-02-25 17:50
It would make sense that these issues came with `saltutil.refresh_pillar` -- when the master syncs pillar with a minion, a new AES session specific to that minion must be created so as to keep the data secure to that minion only. So that's an auth-heavy operation.

These issues are just so hard to debug because we often cannot reproduce them locally. =\

**Comment by kriberg** [comment] 2015-03-02 09:59
@jfindlay the backported patch still requires 0MQ 4.x, which is not in epel. I'd probably try installing 0MQ 4 from the COPR before I rebuild the salt-packages in epel to do debugging.

Now, I started doing some logging to record how many minions were up or down. The chart below shows 16.02 16:00 -> 02.03 10:00. I recorded data with:

```
echo $(date; salt-run manage.up|wc -l; salt-run manage.down|wc -l)|xargs >> /root/salt.log
```

which was executed every hour. I started with 79 hosts and now I have 95. When the logging started, I had logged in on all 79 hosts and added this configuration:

```
master:
  - 10.[snipp]
  - 10.[snipp]
master_shuffle: True
restart_on_error: True  # Try self-recovery
ping_interval: 5        # Hassle the master every five minutes
log_level: info         # Increase verbosity to get normal commands logged
```

![minions](https://cloud.githubusercontent.com/assets/2341/6438373/aaf61cd2-c0c8-11e4-8caf-2bdbe5b145e5.png)

As you can see, There was a sudden drop of a lot of hosts. That was on 20.02 at 09:00. Most minions got error-2 from OP. The last job ran was saltutil.sync_all. Here's a snippet of the log from one of the minions:

```
2015-02-20 09:25:24,739 [salt.minion      ][INFO    ] Returning information for job: 20150220092448703427
2015-02-20 09:25:45,890 [salt.minion      ][INFO    ] User root Executing command saltutil.refresh_pillar with jid 20150220092545146358
2015-02-20 09:25:45,897 [salt.minion      ][INFO    ] Starting a new job with PID 21426
2015-02-20 09:25:45,925 [salt.minion      ][INFO    ] Returning information for job: 20150220092545146358
2015-02-20 11:25:49,686 [salt.payload     ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 1 of 3)
2015-02-20 13:25:49,788 [salt.payload     ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 2 of 3)
2015-02-20 15:25:49,883 [salt.payload     ][INFO    ] SaltReqTimeoutError: after 7200 seconds. (Try 3 of 3)
2015-02-20 15:25:49,895 [salt.log.setup   ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltReqTimeoutError: SaltReqTimeoutError: after 21600 seconds, ran 3 tries
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 56, in salt_minion
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/__init__.py", line 264, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 557, in tune_in
    minion['minion'].pillar_refresh()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1411, in pillar_refresh
    self.opts['environment'],
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 234, in crypted_transfer_decode_dictentry
    ret = self.sreq.send('aes', self.auth.crypticle.dumps(load), tries, timeout)
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 224, in send
    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
SaltReqTimeoutError: SaltReqTimeoutError: after 21600 seconds, ran 3 tries
```

At this point, I'm a unsure on what we should do. We have selected salt to run critical infrastructure for us, but my experience so far is that the combination of packages in el7 + epel 7 is not stable. The alternative, without using custom packages, is using RAET, which currently doesn't support multi-master failover. The documentation doesn't say wether or not is supports ```master_type: failover```, but that could be an alternative.

**Comment by jfindlay** [comment] 2015-03-02 22:21
This may be related, #21044.

**Comment by kriberg** [comment] 2015-03-04 08:54
I'll try to rebuild the epel packages with the patch from #21044 and see if it's more stable.

**Comment by kriberg** [comment] 2015-03-05 07:47
I took the patch from #21044 and attempted to backport it to 2014.7: 
https://gist.github.com/kriberg/707df0bfec982256abe8

I then rebuilt the salt srpm from epel with that patch. Still there seems to be some problems with returning.

Master:

```
# salt server1 saltutil.sync_all
server1:
    ----------
    grains:
    modules:
        - modules.depotpkg
        - modules.ibmim
        - modules.liberty
    outputters:
    renderers:
    returners:
    states:
        - states.depotpkg
        - states.eos
        - states.liberty
    utils:
# salt server1 saltutil.refresh_pillar
# salt-run jobs.lookup_jid 20150305083049108618
# salt server1 test.ping
# date; salt server1 test.ping
to. 05. mars 08:33:17 +0100 2015

```

Minion:

```
2015-03-05 08:30:39,106 [salt.minion      ][INFO    ] User sudo_et4787 Executing command saltutil.refresh_pillar with jid 20150305083039103533
2015-03-05 08:30:39,112 [salt.minion      ][INFO    ] Starting a new job with PID 18558
2015-03-05 08:30:39,140 [salt.minion      ][INFO    ] Returning information for job: 20150305083039103533
2015-03-05 08:30:49,804 [salt.minion      ][INFO    ] User sudo_et4787 Executing command saltutil.find_job with jid 20150305083049108618
2015-03-05 08:30:49,810 [salt.minion      ][INFO    ] Starting a new job with PID 18599
2015-03-05 08:30:49,813 [salt.minion      ][INFO    ] Returning information for job: 20150305083049108618
2015-03-05 08:32:19,459 [salt.minion      ][INFO    ] User sudo_et4787 Executing command test.ping with jid 20150305083219455398
2015-03-05 08:32:19,466 [salt.minion      ][INFO    ] Starting a new job with PID 18647
2015-03-05 08:32:19,467 [salt.minion      ][INFO    ] Returning information for job: 20150305083219455398
2015-03-05 08:32:29,470 [salt.minion      ][INFO    ] User root Executing command saltutil.find_job with jid 20150305083229466619
2015-03-05 08:32:29,478 [salt.minion      ][INFO    ] Starting a new job with PID 18654
2015-03-05 08:32:29,483 [salt.minion      ][INFO    ] Returning information for job: 20150305083229466619
2015-03-05 08:33:17,434 [salt.minion      ][INFO    ] User root Executing command test.ping with jid 20150305083317430295
2015-03-05 08:33:17,441 [salt.minion      ][INFO    ] Starting a new job with PID 18661
2015-03-05 08:33:17,442 [salt.minion      ][INFO    ] Returning information for job: 20150305083317430295
2015-03-05 08:33:27,445 [salt.minion      ][INFO    ] User root Executing command saltutil.find_job with jid 20150305083327441577
2015-03-05 08:33:27,452 [salt.minion      ][INFO    ] Starting a new job with PID 18668
2015-03-05 08:33:27,455 [salt.minion      ][INFO    ] Returning information for job: 20150305083327441577
```

**Comment by cachedout** [comment] 2015-03-18 15:18
@kriberg Could this be the same issue as #19932 ?

**Comment by cachedout** [comment] 2015-04-01 21:55
@kriberg With a minion that's unresponsive, it looks like it's receiving commands (generally) but the returns aren't making their way to the master, correct?

I'm curious about the state of the TCP session on a minion that exhibits this condition. Do you see any difference between the TCP session for port 4505 and the one for 4506 on an affected minion? If it's reporting as being connected on 4506, does an examination of the master's TCP sessions confirm that belief?

**Comment by alf** [comment] 2015-06-10 13:19
I've been looking at these issues for a bit and feel like chiming in with some conclusions I've made.

1. In salt-minion 2014.1 (and maybe 2014.7), we lose minions because of lost messages during key rotations. Thus the minion keeps trying to communicate to the master using the old key. (Or so I assume). Restarting the minion fixes this issue.
2. In salt-minion 2014.7 we lose minions because we use a broken response connection (cached in the sreq_cache in transport/__init__.py). Restarting the minion fixes this issue.

The root cause for both are the same: A firewall or loadbalancer drops the zeromq connection. Since zeromq allows us to keep sending data over the connection even if it's broken the salt-minion doesn't detect the issue until the connection times out.

From 2014.7.0 until but not including 2014.7.6 (I think), the return connection would never time out because the socket keepalive/timeout settings didn't get applied.

**Comment by alf** [comment] 2015-06-10 13:36
Just a note that the publish connection from the master to the minion has had the socket keepalive since v0.12.0 but the response connection from the minion to the master only has the socket keepalive since 2015.5.0 and 2014.7.6.

**Comment by alf** [comment] 2015-06-10 14:28
Looked some more at issue 1 in my message above and my assumptions doesn't hold.

Here's what I observe:

1. The minion was having some issues connecting to the master
2. The minion got into a re-authentication loop

Could there be a message that has been encrypted with the old key that is clogging the connection?

**Comment by kriberg** [comment] 2015-06-10 16:25
We upgraded to 2015.5 and since then we haven't seen any of these symptoms. Not sure exactly what changed that could cause this, but nothing in terms of our infrastructure at least. So stands to reason something changed in salt that solved the issue.

**Comment by cachedout** [comment] 2015-10-29 19:19
@kriberg Apologies for not seeing your response earlier. Sounds lke this is solved so I'll go ahead and close this. Thanks.

**Closed by cachedout** 2015-10-29 19:19 UTC
Labels: Bug, Core, Critical, P3, Pending Discussion, Transport, ZMQ
