### ISSUE TITLE
Single minion target waits full 5 secs when using syndic

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#21779] opened 2015-03-18 19:51 UTC
After testing the changes made to the syndic client by @cachedout in #21775, it is expected behavior for the CLI (when using a syndic) to wait ~5 seconds (the default value for `syndic_wait`) before returning to allow all configured syndics to return, which makes sense.

However, if you're targeting only one minion, the CLI still has to wait before returning. Since minion IDs must be unique, it doesn't make sense to make the CLI wait the full `syndic_wait` when we know that the minion we are targeting has already returned.

Example:
```
# time salt nt-m1 test.ping
nt-m1:
    True

real	0m5.449s
user	0m0.326s
sys	0m0.121s
```

Clearly, a potential work around here is to tune the `syndic_wait` time, but I think this can be further optimized.

**Comment by rallytime** [comment] 2015-03-18 21:06
I originally tested this on @cachedout PR, which was based on 2015.2. However, I have also seen this bug in 2014.7.

**Comment by basepi** [comment] 2015-04-16 21:37
The issue here is that minion IDs don't have to be unique across syndics. You definitely want them to be unique, but we don't mandate it. Just something to think about when we get to this.

**Comment by cachedout** [comment] 2015-06-17 20:51
I think that @basepi hits the nail on the head here. Since minion ids don't have to be unique in multi-tiered environments, I feel like a change here might introduce regressions down the road. I am closing this as won't-fix, but am happy to discuss it more if it seems like there's a reasonable workaround.

**Closed by cachedout** 2015-06-17 20:51 UTC
Labels: Bug, Core, Medium Severity, P1
