### ISSUE TITLE
Cron.present breaks the crontab

### ISSUE THREAD

**Issue by adambarnett52** [saltstack/salt#55102] opened 2019-10-23 14:09 UTC
### Description of Issue
We using cron.present to mannge the conrtab entires. We have seen a large number of machine that end up with a crontab looking like this: 

```
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```
and salt will never fix this and give the error 
```
----------
          ID: cron-mailto
    Function: cron.env_present
        Name: MAILTO
      Result: False
     Comment: Cron env MAILTO for user root failed to commit with error 
              "/tmp/__salt.tmp.l57W1F":1: bad minute
              errors in crontab file, can't install.
     Started: 06:59:46.975113
    Duration: 2135.032 ms
     Changes:   
----------
```

### Setup
sls looks like this
```
pidio2graphite >& /dev/null:
  cron:
    - present
    - user: root
    - identifier: pidio2graphite
```

### Steps to Reproduce Issue
It is not easy to repo it, it happens at some point 
```
2019-10-23 07:00:16,941 [salt.state       :1775][INFO    ][34651] Executing state cron.present for [/pidio2graphite >& /dev/null]
2019-10-23 07:00:16,942 [salt.loaded.int.module.cmdmod:388 ][INFO    ][34651] Executing command 'crontab -l' as user 'root' in directory '/root'
2019-10-23 07:00:18,011 [salt.loaded.int.module.cmdmod:388 ][INFO    ][34651] Executing command 'crontab /tmp/__salt.tmp.kIUH2F' as user 'root' in directory '/root'
2019-10-23 07:00:19,090 [salt.loaded.int.module.cmdmod:1715][ERROR   ][34651] Command 'crontab /tmp/__salt.tmp.kIUH2F' failed with return code: 1
```
### Versions Report
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.el7_lustre.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

I fell like salt should be handle these sort of failures

**Comment by arizvisa** [comment] 2019-10-26 22:14
@adambarnett52, heyo sir. An actual maintainer will probably ask these, but I'm just asking to help reduce the bug queue.

So a couple of things, can you output the logs with the loglevel set to `debug`? You can do this by adding `-ldebug`. In some cases it's better to run it on the minion directly with `salt-call`, but in this case as long master<->minion communication is working properly it shouldn't matter.

Anyways, the debug logs should output detailed info about what's happening during the execution of `crontab`, and despite the issue happening prior to the execution of `crontab -e`, `crontab -e` is the only thing that is actually touching the file.

Can you output the results of `cron.list_tab $your_user`? The first thing `salt.states.cron.present` does is use that function to get the contents of the cron table.

Last thing is the output of the results of `cron.raw_cron $your_user`, as `cron.list_tab` processes the output of this command. So, `raw_cron` produces the output, `cron.list_tab` parses it, and then that result gets passed to `cmd.run_all`.

I suspect the issue is either `cron.raw_cron` not emitting the correct data, or `cron.list_tab` parsing it incorrectly.

**Comment by adambarnett52** [comment] 2019-10-28 08:55
Hi, 

Thanks for getting back to me

Debug output: 
```
[INFO    ] Executing command 'crontab -l' as user 'root' in directory '/root'
[DEBUG   ] stdout: 
[INFO    ] Executing command 'crontab /tmp/__salt.tmp.zYbhtX' as user 'root' in directory '/root'
[ERROR   ] Command 'crontab /tmp/__salt.tmp.zYbhtX' failed with return code: 1
[ERROR   ] stderr: "/tmp/__salt.tmp.zYbhtX":1: bad minute
errors in crontab file, can't install.
[ERROR   ] retcode: 1
[ERROR   ] Cron /opt/dneg/bin/salt-repair for user root failed to commit with error 
"/tmp/__salt.tmp.zYbhtX":1: bad minute
errors in crontab file, can't install.
```

here is the output of cron.list

```
local:
    ----------
    crons:
    env:
    pre:
        - 
    special:
```
cron.raw outoput
```

[INFO    ] Executing command 'crontab -l' as user 'root' in directory '/root'
local:

```

and then output of `crontab -e`

```
crontab -e 
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

**Comment by arizvisa** [comment] 2019-10-28 21:29
@adambarnett52: Sorry, I meant to mention that those need to be executed before the file gets corrupted. The reason why they dont output anything now is because the file is already full of '\0'.

If you put a correct crontab, and then run those commands. One of those commands should corrupt the crontab which is what we're trying to track down.

**Comment by adambarnett52** [comment] 2019-10-29 10:14
Ah Ok, here are the results

Debug output:
```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/schedule.conf
[INFO    ] Starting new HTTP connection (1): mirrors
[DEBUG   ] "GET /systems/hosts.servers HTTP/1.1" 200 793
[INFO    ] Starting new HTTP connection (1): mirrors
[DEBUG   ] "GET /systems/hosts.linuxnfs HTTP/1.1" 200 140
[INFO    ] Starting new HTTP connection (1): mirrors
[DEBUG   ] "GET /systems/hosts.rack HTTP/1.1" 200 15501
[INFO    ] {'hostclass': 'farm'} hostclass
[INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
[INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/schedule.conf
[INFO    ] Starting new HTTP connection (1): mirrors
[DEBUG   ] "GET /systems/roles HTTP/1.1" 200 31981
[INFO    ] Starting new HTTP connection (1): mirrors
[DEBUG   ] "GET /systems/systems HTTP/1.1" 200 315696
[INFO    ] Starting new HTTP connection (1): mirrors
[DEBUG   ] "GET /systems/systems HTTP/1.1" 200 315696
[INFO    ] Starting new HTTP connection (1): dnsite
[DEBUG   ] "GET /sitedata/key/short_name/json HTTP/1.1" 200 20
[INFO    ] Starting new HTTP connection (1): dnsite
[DEBUG   ] "GET /sitedata HTTP/1.1" 200 3605
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '60000ms' (14123)
[DEBUG   ] Setting zmq_reconnect_ivl to '14123ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '60000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506')
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file 'salt://crontab.sls' in saltenv 'base'
[DEBUG   ] In saltenv 'base', looking at rel_path 'crontab/init.sls' to resolve 'salt://crontab/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/crontab/init.sls' to resolve 'salt://crontab/init.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/crontab/init.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/crontab/init.sls' using 'jinja' renderer: 0.00392198562622
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/crontab/init.sls:
include:
  - crontab.redhat

/etc/crontab:
  file:
    - managed
    - source: salt://crontab/files/etc/crontab
    - mode: '0644'

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('include', ['crontab.redhat']), ('/etc/crontab', OrderedDict([('file', ['managed', OrderedDict([('source', 'salt://crontab/files/etc/crontab')]), OrderedDict([('mode', '0644')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/crontab/init.sls' using 'yaml' renderer: 0.00473093986511
[DEBUG   ] In saltenv 'base', looking at rel_path 'crontab/redhat.sls' to resolve 'salt://crontab/redhat.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/crontab/redhat.sls' to resolve 'salt://crontab/redhat.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/crontab/redhat.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/crontab/redhat.sls' using 'jinja' renderer: 0.00289106369019
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/crontab/redhat.sls:
include:
  - crontab.weed

salt-repair-crontab:
  cron:
    - present
    - user: root
    - identifier: salt-repair
    - special: '@daily'
    - name: /opt/dneg/bin/salt-repair

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('include', ['crontab.weed']), ('salt-repair-crontab', OrderedDict([('cron', ['present', OrderedDict([('user', 'root')]), OrderedDict([('identifier', 'salt-repair')]), OrderedDict([('special', '@daily')]), OrderedDict([('name', '/opt/dneg/bin/salt-repair')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/crontab/redhat.sls' using 'yaml' renderer: 0.004558801651
[DEBUG   ] In saltenv 'base', looking at rel_path 'crontab/weed.sls' to resolve 'salt://crontab/weed.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/crontab/weed.sls' to resolve 'salt://crontab/weed.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/crontab/weed.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/crontab/weed.sls' using 'jinja' renderer: 0.00233697891235
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/crontab/weed.sls:
/etc/cron.hourly/tmpwatch-weed:
  file:
     - managed
     - source: salt://crontab/files/etc/cron.hourly/tmpwatch-weed
     - user: root
     - group: root
     - mode: '0755'

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('/etc/cron.hourly/tmpwatch-weed', OrderedDict([('file', ['managed', OrderedDict([('source', 'salt://crontab/files/etc/cron.hourly/tmpwatch-weed')]), OrderedDict([('user', 'root')]), OrderedDict([('group', 'root')]), OrderedDict([('mode', '0755')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/crontab/weed.sls' using 'yaml' renderer: 0.00353908538818
[DEBUG   ] LazyLoaded file.managed
[INFO    ] Running state [/etc/cron.hourly/tmpwatch-weed] at time 15:39:46.647740
[INFO    ] Executing state file.managed for [/etc/cron.hourly/tmpwatch-weed]
[DEBUG   ] LazyLoaded file.user_to_uid
[DEBUG   ] LazyLoaded cp.hash_file
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506')
[DEBUG   ] In saltenv 'base', looking at rel_path 'crontab/files/etc/cron.hourly/tmpwatch-weed' to resolve 'salt://crontab/files/etc/cron.hourly/tmpwatch-weed'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/crontab/files/etc/cron.hourly/tmpwatch-weed' to resolve 'salt://crontab/files/etc/cron.hourly/tmpwatch-weed'
[INFO    ] File /etc/cron.hourly/tmpwatch-weed is in the correct state
[INFO    ] Completed state [/etc/cron.hourly/tmpwatch-weed] at time 15:39:46.677540 duration_in_ms=29.801
[DEBUG   ] LazyLoaded cron.list_tab
[DEBUG   ] LazyLoaded cron.present
[INFO    ] Running state [/opt/dneg/bin/salt-repair] at time 15:39:46.680889
[INFO    ] Executing state cron.present for [/opt/dneg/bin/salt-repair]
[DEBUG   ] LazyLoaded cmd.run_stdout
[INFO    ] Executing command 'crontab -l' as user 'root' in directory '/root'
[INFO    ] Executing command 'crontab /user_data/.tmp/__salt.tmp.lwuejP' as user 'root' in directory '/root'
[INFO    ] {'root': '/opt/dneg/bin/salt-repair'}
[INFO    ] Completed state [/opt/dneg/bin/salt-repair] at time 15:39:48.762669 duration_in_ms=2081.78
[INFO    ] Running state [/etc/crontab] at time 15:39:48.763156
[INFO    ] Executing state file.managed for [/etc/crontab]
[DEBUG   ] In saltenv 'base', looking at rel_path 'crontab/files/etc/crontab' to resolve 'salt://crontab/files/etc/crontab'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/crontab/files/etc/crontab' to resolve 'salt://crontab/files/etc/crontab'
[INFO    ] File /etc/crontab is in the correct state
[INFO    ] Completed state [/etc/crontab] at time 15:39:48.778805 duration_in_ms=15.65
[DEBUG   ] File /var/cache/salt/minion/accumulator/56552656 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'c856b30.dhcp.dneg.com', 'tcp://10.25.20.142:4506')
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: /etc/cron.hourly/tmpwatch-weed
    Function: file.managed
      Result: True
     Comment: File /etc/cron.hourly/tmpwatch-weed is in the correct state
     Started: 15:39:46.647739
    Duration: 29.801 ms
     Changes:   
----------
          ID: salt-repair-crontab
    Function: cron.present
        Name: /opt/dneg/bin/salt-repair
      Result: True
     Comment: Cron /opt/dneg/bin/salt-repair added to root's crontab
     Started: 15:39:46.680889
    Duration: 2081.78 ms
     Changes:   
              ----------
              root:
                  /opt/dneg/bin/salt-repair
----------
          ID: /etc/crontab
    Function: file.managed
      Result: True
     Comment: File /etc/crontab is in the correct state
     Started: 15:39:48.763155
    Duration: 15.65 ms
     Changes:   

Summary for local
------------
Succeeded: 3 (changed=1)
Failed:    0
------------
Total states run:     3
Total run time:   2.127 s
```

cron.list
```
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] {'hostclass': 'farm'} hostclass
[INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
[INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): dnsite
[INFO    ] Starting new HTTP connection (1): dnsite
[INFO    ] Executing command 'crontab -l' as user 'root' in directory '/root'
local:
    ----------
    crons:
    env:
    pre:
    special:
        |_
          ----------
          cmd:
              /opt/dneg/bin/salt-repair
          comment:
          commented:
              False
          identifier:
              salt-repair
          spec:
              @daily
```
raw output

```
 salt-call cron.raw_cron root
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] {'hostclass': 'farm'} hostclass
[INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
[INFO    ] Cython is enabled in the options but not present in the system path. Skipping Cython modules.
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): mirrors
[INFO    ] Starting new HTTP connection (1): dnsite
[INFO    ] Starting new HTTP connection (1): dnsite
[INFO    ] Executing command 'crontab -l' as user 'root' in directory '/root'
local:
    # Lines below here are managed by Salt, do not edit
    # SALT_CRON_IDENTIFIER:salt-repair
    @daily /opt/dneg/bin/salt-repair
```

**Comment by arizvisa** [comment] 2019-10-31 22:02
Now we just need to break it and see what the debug logs emit...

**Comment by arizvisa** [comment] 2020-01-07 17:03
@adambarnett52, still having issues? If not, please close this issue so it can be marked as resolved.

**Comment by xeacott** [comment] 2020-01-13 21:59
@adambarnett52 I'll keep the issue open if you are still having issues.

**Comment by adambarnett52** [comment] 2020-01-16 09:55
we have not seen this again, strange, let me reopen if needed

**Comment by adambarnett52** [comment] 2021-04-08 11:24
Hi 

We are still seeing this, last then we used to, but still the same
We do not run debug login all the time so it is difficult to catch. 

What do you advise the next step should be 

Would you prefer me to make a new ticket instead see the age of this one

**Comment by xeacott** [comment] 2021-04-08 18:19
hi @adambarnett52 yeah I think that's fine to close this and re-open a new one to have less... entries from stalebot lol. That way we can get all the good information consolidated.

**Closed** 2022-12-04 23:19 UTC
Labels: Pending-Discussion
