### ISSUE TITLE
reg.present throws TypeError: expected str or bytearray

### ISSUE THREAD

**Issue by davejhahn** [saltstack/salt#47842] opened 2018-05-25 17:31 UTC
### Description of Issue/Question
After upgrading to 2018.3.0, reg.present is failing with "TypeError: expected str or bytearray" (on Win OS)

### Setup
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\Domains\test.com\abc\def\ghi:
  reg.present:
    - vname: http
    - vdata: 1
    - vtype: REG_DWORD

State above test.sls, then running:
salt <target> state.apply test.sls Generates:

XXX-X-XXX-XX-XX:
----------
          ID: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\Domains\test.com\abc\def\ghi
    Function: reg.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1878, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\reg.py", line 196, in present
                  vdata_decoded = salt.utils.stringutils.to_unicode(vdata, 'utf-8')
                File "c:\salt\bin\lib\site-packages\salt\utils\stringutils.py", line 115, in to_unicode
                  raise TypeError('expected str or bytearray')
              TypeError: expected str or bytearray
     Started: 12:28:14.767000
    Duration: 16.0 ms
     Changes

### Steps to Reproduce Issue
Run above state 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt-master:
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.21.4
         Python: 2.7.5 (default, Aug  9 2016, 05:27:46)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

salt-minion being targeted:
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.21.4
         Python: 2.7.5 (default, Aug  9 2016, 05:27:46)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by twangboy** [comment] 2018-05-29 20:29
Duplicate of: https://github.com/saltstack/salt/issues/47653
Fixed by: https://github.com/saltstack/salt/pull/47107

**Closed by twangboy** 2018-05-29 20:29 UTC
Labels: Bug, High Severity, P2, Windows, team-windows
