### ISSUE TITLE
salt-minion uses/caches master's IP address beyond its TTL

### ISSUE THREAD

**Issue by thanatos** [saltstack/salt#10032] opened 2014-01-29 19:32 UTC
If the salt-master moves to a different machine (to say, remove cruft, the machine died, etc.) _the minions will not reconnect._

Currently, the only way to reconnect minions appears to be to SSH into the machines and run `service salt-minion stop && service salt-minion start`.

`tcpdump` shows that the minions continue to try connecting to the IP address of the old master (they're sending `SYN` packets to that IP) long past the TTL. They do not appear to requery DNS at any point, other than startup, for the IP address, and thus can't ever reconnect.

**Comment by sjmh** [comment] 2015-07-07 16:44
+1 on this.  We're trying to use put our salt service into Consul and have it flip the DNS to an alternate master if the first fails, but running into the same issue that the minion never attempts to re-resolve the master IP.

It looks like there are some items in the config that should be causing the minion to restart itself upon a number of ping failures to the master ( and thus, would re-resolve the master DNS name ), but that doesn't appear to be working.

**Comment by sjmh** [comment] 2015-07-07 18:38
Looks like you can workaround this issue by setting master_type to failover and making your master list a single element list.

```
master:
  - salt.service.consul

master_type: failover
master_alive_interval: 30
```

**Comment by dverbeek84** [comment] 2016-02-27 14:19
@sjmh Your workaround does not work from me unfortunately.

**Comment by jlory** [comment] 2016-11-29 21:36
Any updates on that?

**Comment by marccardinal** [comment] 2017-03-21 01:37
Is this still planned?

**Comment by syphernl** [comment] 2017-04-18 11:25
This still appears to be happening in 2016.11.3

**Comment by Xaelias** [comment] 2017-12-08 15:53
2 years and counting guys...

**Comment by pstatho** [comment] 2018-01-26 23:52
This is truly surprising. Respecting the DNS TTL is pretty basic stuff and ends up being a logistical nightmare for IT providers managing multiple locations. I'm using a CNAME entry and now that we migrated our master we have almost 1000 minions that are not connected. Now we have to find a way to restart the service or reboot the machines ;(.

**Comment by dcovello** [comment] 2018-03-07 16:46
@Xaelias @pstatho I ran into this issue as well today when running a salt-master and salt-minion inside Kubernetes where there is no way to assign a static IP to the salt master easily. Every time the salt-master pod was recreated the IP was changed and the salt-minions within the cluster were unable to be contacted by the salt-master.

I fixed this after finding the following notes within the salt-minion configuration file :
``
# To auto recover minions if master changes IP address (DDNS)
#    auth_tries: 10
#    auth_safemode: False
#    ping_interval: 90
#
# Minions won't know master is missing until a ping fails. After the ping fail,
# the minion will attempt authentication and likely fails out and cause a restart.
# When the minion restarts it will resolve the masters IP and attempt to reconnect.
``

This caused my salt-minions to successfully fail their authentication attempts and succesfully reconnect after a ping interval. Note that ping_interval is in minutes and not in seconds.

Hope this helps!

**Comment by devopsdeluxe** [comment] 2019-11-11 19:52
Just ran into this issue with ~20 minions behind NAT.

**Comment by cr1st1p** [comment] 2020-04-06 07:15
I ran into the issue as well. Having master with a dynamic IP. 
5 years after the bug was reported :-(

Not respecting the TTL is really a bug and should be fixed.

Also, I wonder if the suggested *workaround* with faking a multi-master list works.
Reason is that I see the word 'ping' in the workaround and I am wondering if previous master IP is still answering standard PING packets. 
My minion is erroring with *timeout* and not 'master unreachable'.

**Comment by 234d** [comment] 2020-04-24 09:44
Also came across this issue. In my opinion salt-minion should handle this automatically. The proposed solution in the minion configuration didn't work for me. Had to use the single item master from [comment](https://github.com/saltstack/salt/issues/10032#issuecomment-119296425).

@cr1st1p It's not an [ICMP ping](https://github.com/saltstack/salt/blob/master/salt/modules/test.py#L111).

**Comment by cr1st1p** [comment] 2020-04-24 10:32
@234d - ack !
I also ended using https://github.com/saltstack/salt/issues/10032#issuecomment-119296425

**Comment by cr1st1p** [comment] 2020-05-01 07:11
and... sadly, I just found out that that workaround does NOT work.
I see in the logs that at least for several days, minion crashes with 
```
salt.exceptions.SaltReqTimeoutError: Message timed out
```
and is continuously using the wrong IP for the master to reconnect :-(

**Comment by soner89** [comment] 2020-08-12 14:13
We are running the Master in Kubernetes behind a LB Service with a static IP.

Unfortunately, we had to completely recreate the Kubernetes Cluster today which meant to reclaim a new IP address.
Now, our ~180 heterogenic Minions can't connect to the Master. Honestly, I have better things to do to connect to all Servers and restart the Salt-Minion.

Is there an ETA when Salt will respect the DNS TTL?

**Comment by oeuftete** [comment] 2020-11-19 18:47
ZD-6017

**Comment by oeuftete** [comment] 2020-11-19 20:47
I know there are some reports here that the workaround reported back in https://github.com/saltstack/salt/issues/10032#issuecomment-119296425 does not work, but it did appear to work for me with 3002.2, so it's worth trying if you need this before it is supported more officially.  To refresh, it's something like:

```yaml
master:
  - my.master.dns

master_type: failover
master_alive_interval: 30
retry_dns: 0
```

**Comment by keslerm** [comment] 2021-09-15 18:25
Well shoot hope someone things to search for this before having to do it, ran into this

**Comment by tvb** [comment] 2023-06-02 13:35
> > 
> 
> I wonder if you could configure a reactor on the minion to state.apply when the connection is lost for too long.

Probably yes, but this won't change the cached IP for the daemon afaik.

**Comment by tvb** [comment] 2023-06-02 13:46
Running the following config:

```yaml
---
color: False
log_level: debug
master: salt.<mydomain.com>
minion_id_lowercase: true
startup_states: highstate
http_request_timeout: 60
master_alive_interval: 30
master_type: failover
retry_dns: 0
master_tries: -1
auth_safemode: False
ping_interval: 5
auth_timeout: 10
acceptance_wait_time_max: 5
```

I now see that it "switches" master endpoints continuously:

```bash
2023-06-02 15:44:10,787 [salt.minion      :613 ][INFO    ][19302] Moving possibly failed master salt.<mydomain.com> to the end of the list of masters
2023-06-02 15:43:39,832 [salt.minion      :187 ][WARNING ][19302] Master ip address changed from x.x.x.1 to x.x.x.2
2023-06-02 15:39:04,873 [salt.minion      :2765][INFO    ][19302] Connection to master salt.<mydomain.com> lost
```

**Comment by dmurphy18** [comment] 2023-09-25 22:32
@thanatos  Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt (currently 3006.3) and if still an issue, please open a new issue, which will have metrics in tracking issues.

**Closed by dmurphy18** 2023-09-25 22:32 UTC
Labels: Feature, Core, ZD

**Comment by thusoy** [comment] 2023-10-31 13:54
@dmurphy18 this is still an issue, just experienced this myself with master on 3006.4 and minion on 3006.2, minion would only be accessible from the saltmaster after restarting the minion service, even though `sudo salt-call test.ping` and other salt commands worked fine from the minion. I had set `master_tries: -1` in the minion config to try to avoid this, but that was not sufficient. The following config did pick up the new master ip after a move, but this should be default behavior:
```yaml
master: salt.<domain>
master_tries: -1
master_alive_interval: 30
auth_safemode: False
master_type: failover
retry_dns: 0
```

**Comment by dmurphy18** [comment] 2023-10-31 19:30
@thusoy Please open a new issue against the current branch, detailing the issue, version, branch, platform, etc. and how to reproduce it, that is, filling out the template for a bug.  The original issue is almost 10 years old, hence adding to it is not productive, best to create a new issue with full details fleshed out, but please refer to this old issue too in the new issue.
