### ISSUE TITLE
The pillar run module does not honor saltenv

### ISSUE THREAD

**Issue by yhekma** [saltstack/salt#36629] opened 2016-09-28 05:38 UTC
### Description of Issue/Question

It seems like the pillar run module does not honor the salt environment. This results in hard to debug problems because the variables in your written salt code get expanded to different values than those you see when you run `salt-call pillar.items saltenv=bla`. Looking at the code it seems like the `satenv=bla` is ignored, but imo this should not be the case.
### Setup

Create separate pillars for 2 separate envs. Then write the following init.sls state file:

```
{% set content = salt['pillar.get']('content', '') %}
create pillar file:
  file.managed:
    - name: /tmp/pillarfile
    - contents: {{ content }}
```

And in the **base** pillar you set:

```
content: base_env
```

And in the **bla** env:

```
content: bla
```

Then when you do a `salt-call state.apply` or a `salt-call state.apply saltenv=bla` the contents of `/tmp/pillarfile` change to _base_env_ and _bla_ respectively as expected. Only when you check the pillar items with the pillar module, you always get _base_env_, regardless of the saltenv passed.

**Comment by Ch3LL** [comment] 2016-09-29 20:54
@yhekma looks like this is similar to #32435 although they are requesting `pillarenv` but I think to ensure we keep standardization we also include `saltenv` so I'll keep this issue open to track `saltenv` being added. Thanks.

**Comment by rickh563** [comment] 2016-10-17 15:06
ZD-990

**Comment by thatch45** [comment] 2016-10-25 20:33
I don't understand what the issue is here, pillar environments are completely derived on the salt master and cannot be defined when the pillar is retrieved, this would break the security of pillar. These functions never accepted `saltenv` or `pillarenv` arguments.

Please let me know what you are trying to do, because these options don't exist.

**Comment by yhekma** [comment] 2016-10-26 05:24
@thatch45 I'm not quite sure what you mean when you say it would break security. From a minion I can pass a saltenv when I invoke "salt-call" which will result in me (the minion) getting the states *and* the pillar data of that environment. Of course pillar merging on the master side still applies, so that way you can enforce that certain data is not visible on certain notes (at least that's how I understand the setup. If this is wrong, please enlighten me).

What I am asking here is that pillar.items behaves the same as calls to the pillar from the state. As in why would `salt 'server1' pillar.get value1 saltenv=myenv` result in different output from `salt-call state.apply saltenv=myenv` when in myenv there's a state that references the same pillardata:

```
myfile:
  file.managed:
    - name: /tmp/myfile
    - contents: {% salt['pillar.get']('value1') %}
```

As it stands, `{% salt['pillar.get']('value1') %}` results in different output when run from the command line/command module.

Once again, if I am missing something obvious, let me know.

**Comment by thatch45** [comment] 2016-10-26 15:49
Thanks, I was not aware that the saltenv has been added to the pillar compile, I will reset this as a bug and we will get it fixed

**Comment by yhekma** [comment] 2016-10-27 05:23
@thatch45 Also since you added the 2016.3.5 label, does that mean that if/when this is fixed/added it will be backported to 2016.3?
Just wondering...

**Comment by thatch45** [comment] 2016-10-27 05:38
Yes, that is the plan. It will be scheduled for sprints on the core team and fixed in the 2016.3 branch.

**Comment by terminalmage** [comment] 2016-11-08 16:53
@yhekma I can't reproduce the behavior you're describing. I always get the ``content`` pillar assigned the value from the ``bla`` environment, because it is evaluated after ``base`` and thus overwrites it.

Furthermore, ``pillar.get`` does not support a saltenv argument:

```
# salt tardis pillar.get content saltenv=base
tardis:
    ERROR executing 'pillar.get': The following keyword arguments are not valid: saltenv=base
# salt tardis pillar.get content saltenv=bla
tardis:
    ERROR executing 'pillar.get': The following keyword arguments are not valid: saltenv=bla
```

Salt fileserver environments, to my knowledge, have nothing to do with pillar compilation, so this is all very puzzling to me.

I feel like we're not on the same page, here. Can you please provide a more detailed, reproducible use case, and tell me what it is that you are trying to do? ``pillar.get`` should  never give different information depending on the effective saltenv, since it always simply returns the matching key (or ``default`` value if no match), based on the already-compiled pillar data, which includes merged results from all environments.

**Comment by yhekma** [comment] 2016-11-09 08:48
@terminalmage I believe we are not understanding each other (or at least I am not understanding you:)).
You state that pillar.get should never give different data based on saltenvs, but what's the point of pillar envs if this is the case?

In my salt master config I have:

```
--- snip ----
pillar_source_merging_strategy: none
file_roots:
  base:
    - /srv/salt/states/
  user1:
    - /srv/salt_envs/user1/states/
  user2:
    - /srv/salt_envs/user2/states/

pillar_roots:
  base:
    - /srv/salt/pillars/
  user1:
    - /srv/salt_envs/user1/pillars/
  user2:
    - /srv/salt_envs/user2/pillars/
```

Now, if I have a module in both in the `user1` env and the `user2` env like so:

```
my test file:
  file.managed:
    - name: /tmp/my_test_file
    - contents: {{ salt['pillar.get']('mykey') }}
```

And the pillar data in the `user1` env is:

```
mykey: key_in_user1_env
```

and the pillar data in the `user2` env is:

```
mykey: key_in_user2_env
```

The contents of `/tmp/my_test_file` change when I run salt for that specific env. To be explicit, when I run `salt-call state.apply saltenv=user1` the contents will be ***key_in_user1_env*** and when I run `salt-call state.apply saltenv=user2` the contents will be ***key_in_user2_env***.

So far this is what I would expect. However, when I run the pillar command module (which, as you probably know, is not the same as the one called from the salt code I believe), I have no option on specifying a saltenv of which I want the pillar data; I always get **base**.

I am not really sure what the salt fileserver has to do with this.

Am I fundamentally misunderstanding here? If so, please tell me.

**Comment by dropje86** [comment] 2016-11-09 09:55
> `pillar.get` should never give different information depending on the effective saltenv, since it always simply returns the matching key (or default value if no match), based on the already-compiled pillar data, which includes merged results from all environments.

Uhm.. I'm not sure you guys are on the same page.. There has been an addition to the pillar merge strategy: none. Which means pillar data is not merged at all (which absolutely makes sense and I still don't know why a core feature like this wasn't available in the first place). That means that if you don't merge you pillar data above statement is incorrect.

**Comment by yhekma** [comment] 2016-11-09 09:58
@dropje86 @terminalmage 

I would like to add that even if you discount the pillar_merge_strategy you can still get different data depending on which env you pass I think. Even if stuff gets merged, if a key is not in base, but is in `user1` and in `user2` you will get those values when passing ***user1*** or ***user2*** env respectively.

**Comment by terminalmage** [comment] 2016-11-09 15:21
Thanks, the ``pillar_source_merge_strategy`` information would have been good to have upfront.

So, here's the thing. ``pillar.get``, as I mentioned earlier, does not recompile pillar data. It operates on already-compiled pillar information. The reason that ``pillar.get`` gives different results when you specify a saltenv when running a ``state.apply`` is that a ``state.apply`` _does_ recompile pillar data before it executes.

I'll need to discuss with @thatch45 the best way to deal with this.

**Comment by yhekma** [comment] 2016-11-09 18:59
@terminalmage Yeah, sorry about not explicitly mentioning the merging strategy. I would still like to note that the data fetched from the pillar can differ from saltenv to saltenv regardless of merging strategy though.
So even if we discount the `pillar_source_merging_strategy = none`, there is still a discrepancy between the call from the formula (`salt['pillar.get']('key')`) vs the command module.

As stated, this is a feature request, not a bug per se in my opinion. But as it stands, it *is* pretty inconsistent when you look at it from a users perspective imo.

**Comment by terminalmage** [comment] 2016-11-16 21:35
@yhekma I talked with @thatch45 today and we came up with what we think will be a good solution.

So, right now we have ``pillar.get`` which just looks at the in-memory pillar data, but we also have ``pillar.items`` which generates fresh pillar data each time. I just opened https://github.com/saltstack/salt/pull/37738 as a possible solution for you. What it does is allows ``pillar.get`` to accept a ``saltenv`` argument which, if passed, triggers the master to compile a fresh set of pillar data specific to the requested environment.

For example:

```
# salt tardis pillar.get content
tardis:
    base
# salt tardis pillar.get content saltenv=base
tardis:
    base
# salt tardis pillar.get content saltenv=bla
tardis:
    bla
```

Thoughts?

**Comment by yhekma** [comment] 2016-11-17 10:02
@terminalmage without looking at the pull request in depth, if it does what you describe what it does it would be a perfect solution for this issue. Can we expect this to be available in bot 2016.3.X and 2016.11.X then?

**Comment by terminalmage** [comment] 2016-11-17 14:41
@yhekma I submitted it against develop since it is technically a feature enhancement. This would mean that it would not see a release before the Nitrogen release cycle, due in Spring 2017.

However, if @thatch45 agrees to it, I can treat it as a bugfix and resubmit against 2016.3, which would make it available in 2016.3.5 and 2016.11.1. I can't promise anything, though.

**Comment by yhekma** [comment] 2016-11-17 15:03
@terminalmage ok, thanks for the info. Please let me know if and when anything gets decided.

**Comment by thatch45** [comment] 2016-11-17 19:46
Yes, we can get this backported to 2016.3 etc.

**Comment by terminalmage** [comment] 2016-11-17 19:51
Since it hasn't been merged yet I'll just rework it and change the base branch of the PR to 2016.3 and then we won't need to worry about backporting.

**Comment by terminalmage** [comment] 2016-11-17 19:56
OK, https://github.com/saltstack/salt/pull/37738 is now opened against the 2016.3 release branch.

**Closed** 2016-11-29 16:07 UTC
Labels: 2016.11.1, 2016.3.5, Bug, Core, Pending Discussion, TEAM Core, ZD
