### ISSUE TITLE
Exception when using user.present with Windows

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#24196] opened 2015-05-27 21:39 UTC
This seems to be a fairly newly introduced bug. Here's an example output:-

```python
          ID: usrGhostFiles
    Function: user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1563, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\states\user.py", line 375, in present
                  expire)
                File "C:\salt\bin\lib\site-packages\salt\states\user.py", line 114, in _changes
                  if not os.path.isdir(newhome):
              TypeError: coercing to Unicode: need string or buffer, NoneType found
     Started: 19:27:49.649000
    Duration: 3.0 ms
     Changes:   
```
It seems to be because the "home" value for users on Windows is always none, as user.getent shows:-

```yaml
      ----------
      gid:
      groups:
      home:
          None
      name:
          usrGhostFiles
      passwd:
          None
      shell:
      uid:
          S-1-5-21-2033504833-1387376432-1020295716-1002
```

A workaround that I found is to add `createhome: False` to the user state.

**Comment by jfindlay** [comment] 2015-06-04 21:58
@johnccfm, thanks for the report.

**Comment by twangboy** [comment] 2015-06-12 17:06
@johnccfm Could you please provide the OS Version you're using as well as the salt versions_report (```salt '*' test.version_report```)?

**Comment by twangboy** [comment] 2015-06-12 17:54
I cannot reproduce this on the head branch of 2014.7.
Versions Report:
```

**Comment by twangboy** [comment] 2015-06-12 17:54
salt 'g*' test.versions_report
gringo:
               Salt: 2014.7.6-50-gd7a9999
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.6.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed

**Comment by twangboy** [comment] 2015-06-12 17:54
```
State file:
```

**Comment by johnccfm** [comment] 2015-06-14 20:51
Thanks for looking at this @twangboy. Seems like you're way ahead there. Do you still need anything from me at this point?

**Comment by twangboy** [comment] 2015-06-15 15:05
@johnccfm No, I was just waiting for the PR to be merged. I think we can close the issue. I will do that now.

**Closed by twangboy** 2015-06-15 15:05 UTC
Labels: Bug, High Severity, Low-Hanging Fruit, P1, Platform Mgmt, Windows
