### ISSUE TITLE
Possible Regression in Salt-Cloud firing of events. 

### ISSUE THREAD

**Issue by fxdgear** [saltstack/salt#36920] opened 2016-10-11 20:46 UTC
### Description of Issue/Question
When attempting to create a reaction to the event tag `salt/cloud/*/created` the reaction is never fired cause the event tag is never processed by the event bus. 

### Setup
nothing special. Simple salt-master and salt-cloud setup talking to aws. 

### Steps to Reproduce Issue
1. Watch the event bus 
```
sudo salt-run state.event pretty=True
```

2. In a different terminal create a new minion using salt-cloud

3. witness the `salt/cloud/*/created` tag never show up.

### Versions Report
```
salt-cloud 2016.3.3 (Boron)
```

```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 1.8.2
       cherrypy: 8.1.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-42-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment] 2016-10-11 21:20
@fxdgear this is a duplicate of #36055 which has been fixed in #35855 and will be included in the 2016.3.4 release in later october. Closing due to duplciate.

**Closed by Ch3LL** 2016-10-11 21:20 UTC

**Comment by fxdgear** [comment] 2016-10-11 21:21
Great!! Appreciate it. 

Was suggested in #salt on irc to create this ticket.

**Comment by Ch3LL** [comment] 2016-10-11 21:23
No problem! Thanks for reporting :) We always would rather someone report something so thank you a bunch :+1: If you want to give that fix a try it should definitely work for ya, but let us know otherwise
