### ISSUE TITLE
modules.cron.set_special: How to set identifier?

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#28201] opened 2015-10-22 09:18 UTC
Since cron.set_special does not support an identifier according to the docs:

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cron.html#salt.modules.cron.set_special

... I don't see a way to remove a "special" job.

I see these cases:

 1. I am blind, the docs explain it. Then I am very sorry.
 2. It is supported, but the docs don't explain it: Please update the docs.
 3. It is not supported. Please implement it. If you provide some hints, I might be able to write a patch.

**Comment by jfindlay** [comment] 2015-10-23 18:48
@guettli, thanks for the report.  This is a known problem, being a duplicate of #28171.  You are very welcome to [submit a patch](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for this against the 2015.8 branch.

**Closed by jfindlay** 2015-10-23 18:48 UTC
Labels: Duplicate
