### ISSUE TITLE
salt-cp copying a large file (256M) fails

### ISSUE THREAD

**Issue by perfecto25** [saltstack/salt#37520] opened 2016-11-07 16:21 UTC
### Description of Issue/Question
copying large .bin file to a minion fails
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
```
[root@mrxmaster]# salt-cp mytarget /tmp/atlassian-bitbucket-4.10.1-x64.bin /opt
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 321, in salt_cp
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/cp.py", line 38, in run
    cp_.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/cp.py", line 105, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 558, in cmd
    **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 313, in run_job
    raise SaltClientError(general_exception)
SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 321, in salt_cp
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/cp.py", line 38, in run
    cp_.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/cp.py", line 105, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 558, in cmd
    **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 313, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

I bumped up the worker thread count from 5 to 20, restarted master, still same error

### Versions Report
**Master**
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-642.6.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
 

**Minion**

Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by perfecto25** [comment] 2016-11-07 16:50
Wondering if the discrepancy between master and agent salt versions could be doing this

**Comment by Ch3LL** [comment] 2016-11-07 21:46
@perfecto25 this is expected behavior as documented [here](https://docs.saltstack.com/en/develop/ref/cli/salt-cp.html) : 

> Salt copy is only intended for use with small files (< 100KB). If you need to copy large files out to minions please use the cp.get_file function.

Please use cp module instead. Closing since this is expected behavior. Thanks

**Closed by Ch3LL** 2016-11-07 21:46 UTC
