### ISSUE TITLE
Errors during salt-master 3005.1 using onedir method [BUG]

### ISSUE THREAD

**Issue by barbaricyawps** [saltstack/salt#62948] opened 2022-10-24 16:31 UTC
NOTE: This issue was [originally opened in the Salt install guide](https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues/60) repository, but it's actually a bug in onedir, so I'm replicating this issue here. The issue was originally opened by a user named `infantvin1` . I can't find a user with that name on GitHub, so you might need to communicate with them on the original issue in GitLab: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues/60

**Description**
I am doing a fresh install of salt-master and salt-cloud on RHEL9 using the onedir method listed here:
[Install onedir on RHEL 9](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/rhel.html#install-onedir-packages-of-salt-on-redhat-rhel-9)

Command used on the OS is:
```
# dnf install salt-master salt-cloud
```
During the install, the error message below is given:

```
/opt/saltstack/salt/run/libssl.so.1.1: No such file or directory 403C9A61467F0000:error:80000002:system library:file_ctrl:No such file or directory:crypto/bio/bss_file.c:297:calling fopen(/opt/saltstack/salt/run/libssl.so.1.1, r) 403C9A61467F0000:error:10080002:BIO routines:file_ctrl:system lib:crypto/bio/bss_file.c:300: /opt/saltstack/salt/run/libcrypto.so.1.1: No such file or directory 40CCF897117F0000:error:80000002:system library:file_ctrl:No such file or directory:crypto/bio/bss_file.c:297:calling fopen(/opt/saltstack/salt/run/libcrypto.so.1.1, r) 40CCF897117F0000:error:10080002:BIO routines:file_ctrl:system lib:crypto/bio/bss_file.c:300:
```

I will attach the full output of the command in a text file.
NOTE FROM ALYSSA: See attached file on: [this comment in the original issue](https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues/60#note_1143496295) 

I am seeing that the files mentioned here are 0 byte files:

```
# ls -l .lib* -rw-r--r-- 1 root root 0 Oct 20 17:06 .libcrypto.so.1.1.hmac -rw-r--r-- 1 root root 0 Oct 20 17:06 .libssl.so.1.1.hmac

# pwd; /opt/saltstack/salt/run
```
Is this a bug or am I doing something wrong? Please provide a solution or redirect me to what needs to be done in case of some error from my side. Thanks.

**Comment by dmurphy18** [comment] 2022-10-24 16:47
The hmac files should only be getting generated for RHEL 8.
They are not needed for FIPS support on RHEL 9.
The fix is needs to be done in qa-master scripts, I believe, but need to check salt pkg-upload too

**Comment by dmurphy18** [comment] 2022-10-24 17:00
Problem is here in salt-pkg file https://gitlab.com/saltstack/open/salt-pkg/-/blob/master/pkgs/redhat/salt.spec#L368-382

Need to bound this by RHEL 8 check

**Comment by infantvin** [comment] 2022-10-25 15:05
Hi,
I am the user who reported this issue on gitlabs because thats where I got redirected from the documentation. I originally was using github to open saltstack issues or report problems related to the use of saltstack. My username is infantvin in github

Related to this issue, I tried using the bootstrap install method on RHEL9 and it worked without generating any errors. Snippet of the installation is below in the code formatted section

`# curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io`
`# chmod u+x bootstrap-salt.sh `
`# ./bootstrap-salt.sh -v`
`# ./bootstrap-salt.sh -- Version 2022.10.04`

`# ./bootstrap-salt.sh -L -M stable 3005 `
 `*  INFO: Running version: 2022.10.04`
` *  INFO: Executed by: /bin/sh`
` *  INFO: Command line: './bootstrap-salt.sh -L -M stable 3005'`
`...`
 ` salt-minion-3005.1-2.el9.noarch           zeromq-4.3.4-1.el9.x86_64  `        

`Complete!`
` *  INFO: Running install_red_hat_enterprise_linux_stable_post()`
`*  INFO: Running install_red_hat_enterprise_linux_restart_daemons()`
` *  INFO: Running daemons_running()`
` *  INFO: Salt installed!`

Method for using bootstrap is documented here on your documentation site
https://docs.saltproject.io/salt/install-guide/en/latest/topics/bootstrap.html

The problem is when we deploy the salt master into a live environment which is used daily, we cannot rely on the bootstrap method but need a more consistent way to apply minor updates to a major release. So, the repository update method works best for this.

I will wait for your reply on the fix. If you need anything else including any OS related details please feel free to let me know. I am willing to help.

Thanks

**Comment by dmurphy18** [comment] 2022-11-01 22:49
Merge Request https://gitlab.com/saltstack/open/salt-pkg/-/merge_requests/213 has been submitted, fix should work on RHEL 8 clones too, tested on Alma 8 and Rocky 8 apart from Centos Streaming 8

**Comment by dmurphy18** [comment] 2022-11-03 15:04
Fix has been merged in and should be available in the next release, hence closing this here since fix in GitLab, and automatic close for GitHub PR's don't apply.

**Closed by dmurphy18** 2022-11-03 15:04 UTC
Labels: Bug, Packaging
