### ISSUE TITLE
Add module/function and top.sls syntax to check for sls existence

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#16687] opened 2014-10-16 18:46 UTC
Currently, if I want to conditionally include an sls file, if the file exists, I need to do some ugly jinja magic:

``` yaml
base:
  # For each directory that can have pillar files
  {% for root in opts['pillar_roots']['base'] -%}
  # Set a variable to the path to check
  {% set service_group_sls = '{0}/{1}.sls'.format(root, grains['service_group']) -%}
  # Check to see if the file exists, if so, include that pillar file.
  {% if salt['file.file_exists'](service_group_sls) %}
  'service_group:{{ grains["service_group"] }}':
    - match: grain
    - {{ grains['service_group'] }}
  {% endif %}
  {% endfor -%}
```

What I really want to do is:

``` yaml
base:
  'service_group:{{ grains["service_group"] }}':
    - match: grain
    - ignore_missing: True
    - {{ grains['service_group'] }}
```

I also want to see if a pillar or state sls file exists from the cli, or from inside of a state, for conditional include:

``` bash
salt-call state.sls_exists mystatssls
salt-call pillar.sls_exists mypillarsls
```

This way I can call individual states, but only if they actually exist.

**Comment by ryan-lane** [comment] 2015-01-07 04:01
Fixed in #19429

**Comment by syphernl** [comment] 2015-05-08 12:51
I'm working on something that requires a similar approach and running into an issue that Salt doesn't ignore it if I try to `include` a state that does not exist.

It looks like for states the `cp.show_states` could come in handy. 
The proposed `sls_exists` can most likely be a wrapper around that probably?

**Comment by invsblduck** [comment] 2016-01-14 18:00
Too bad this was only implemented for Pillar!  Generic support for SLS inclusion in `top.sls` (as the title states!) or SLS inclusion from within another SLS would have been epic.  But that is no small patch, I'm sure.  Thanks @ryan-lane for getting the Pillar part done! :+1:

**Comment by ryan-lane** [comment] 2016-01-14 19:09
Yeah... The code for pillar and state top files are separate for some reason, even though they do the exact same thing. I was hoping to do both at the same time, but I only needed pillar and the state top file code looked more difficult to modify. I'm still hoping someone from SaltStackInc will finish this work up :)

**Comment by hartloosli** [comment] 2016-07-11 01:18
Bumping this, as it would really clean up a tedious top.sls in our code.

**Comment by dgorissen** [comment] 2016-09-14 17:00
Linking this to duplicate #20010

**Comment by ksoviero** [comment] 2017-02-06 18:58
#39186 is a duplicate as well.

**Comment by zerthimon** [comment] 2017-08-31 14:52
+1
I really need this functionality:
```
include:
  - ignore_missing: True
  - {{ "servers/%s" % grains.id.replace('.', '_') }}
```

**Comment by frleb** [comment] 2018-01-05 18:55
+1

**Comment by konstest** [comment] 2018-03-12 08:00
+1

**Comment by ksoviero** [comment] 2018-03-12 14:15
I tried adding support for it myself a while back, but SaltStack's code is... We'll, let's just say I still have nightmares about it.

**Comment by ksoviero** [comment] 2019-06-25 14:48
Oh no you don't mr.stale-bot. This is still very much needed.

**Comment by konstest** [comment] 2019-06-26 02:43
+1

**Comment by OrangeDog** [comment] 2020-01-08 10:40
This feature is still wanted.

**Comment by solomongumbie** [comment] 2020-01-27 15:34
I could really make use of this feature as well.

**Comment by dth202** [comment] 2020-02-11 17:09
I would also like this feature

**Comment by wwdillingham** [comment] 2021-12-09 15:58
I have tried to implement this by:

```
{% if salt['state.sls_exists'](sls_file) -%}
include:
  - {{ sls_file }}
{%- endif %}
```
but have found that sls_exists does not work in any saltenv other than base. Also seems I cant get ignore_missing at all with state includes.

**Comment by OrangeDog** [comment] 2021-12-09 16:10
@wwdillingham you need to pass `saltenv=saltenv` to `sls_exists`.
https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.sls_exists

**Comment by wwdillingham** [comment] 2021-12-09 16:13
@OrangeDog Thank you and sorry for not being clear. I did pass saltenv as such:

```
{% if salt['state.sls_exists'](sls_file, saltenv=saltenv) -%}
include:
  - {{ sls_file }}
{%- endif %}
```
and that does not include {{ sls_file }} at all, which decidedly exists in both saltenv and in base

**Comment by OrangeDog** [comment] 2021-12-09 16:16
@wwdillingham what is the value of `sls_file`? It shouldn't be a path.

**Comment by wwdillingham** [comment] 2021-12-09 16:21
The full contents of this "meta" state is:

```
{% set sls_file = "node." ~ grains.get('host') %}

{% if salt['state.sls_exists'](sls_file) -%}
include:
  - {{ sls_file }}
{%- endif %}
```

The idea here is i can setup a state file for minions at the root of the fileserver in "node/hostname" where hostname is the short hostname of a minion.

so for instance {{ sls_file }} would be rendered as "node/foo" for foo.example.com

and my fileserver has: "node/foo.sls" in both my testing saltenv and in base

**Comment by wwdillingham** [comment] 2021-12-09 16:29
@OrangeDog made a few edits to the above, flagging you again for visibility.

**Comment by wwdillingham** [comment] 2021-12-09 16:33
@OrangeDog  Was working with @whytewolf yesterday in slack about this I am working on 3001, he said he could reproduce in 3004, was going to submit a a new bug report regarding it but a search in github issues brought me to this issue here and was hoping to find another workaround. If you think its a genuine bug I would like to make a report.

**Comment by OrangeDog** [comment] 2021-12-09 16:38
It should probably be a separate issue, yes.
However, it seems to be working for me.

**Comment by wwdillingham** [comment] 2021-12-09 17:00
@OrangeDog and @whytewolf  I have submitted a new bug at https://github.com/saltstack/salt/issues/61343

**Comment by thatch45** [comment] 2023-07-11 21:11
The new bug has been resolved, closing this one.
If this is still an issue please open it up against a current version

**Closed by thatch45** 2023-07-11 21:11 UTC
Labels: Feature
