### ISSUE TITLE
Salt 2015.5.2 - Could not deserialize msgpack message error.

### ISSUE THREAD

**Issue by b18** [saltstack/salt#25581] opened 2015-07-21 15:11 UTC
I'm suddenly receiving this error message on my Salt Master (2015.5.2) when trying to run any commands against any of my minions (minions are also 2015.5.2 and a combination of Ubuntu or Windows 2008 R2). See below:

> salt:~# salt 'servername' state.show_highstate
> [CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often happens > when trying to read a file not in binary mode.Please open an issue and include the following error:
> unpack(b) recieved extra data.

I'm not sure if it's related, but I'm also receiving the following error when running **salt-run manage.versions**

> salt:~# salt-run manage.versions
> [CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often
> happens when trying to read a file not in binary mode.Please open an issue and include the
> following error: unpack(b) recieved extra data.
> unpack(b) recieved extra data.
> [ERROR   ] An un-handled exception was caught by salt's global exception handler:
> IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/c4
> /677de1330880597ff52d40bc532392/jid'
> Traceback (most recent call last):
> File "/usr/bin/salt-run", line 10, in <module>
>    salt_run()
>  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 250, in salt_run
>    client.run()
>  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 54, in run
>    runner.run()
>  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 166, in run
>    False)  # Don't daemonize
>  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 381, in _proc_function
>    return self.low(fun, low)
>  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 336, in low
>    mminion=self.mminion,
>  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 51, in store_job
>    mminion.returners[jidstore_fstr](False, passed_jid=load['jid'])
>  File "/usr/lib/python2.7/dist-packages/salt/returners/local_cache.py", line 124, in prep_jid
>    with salt.utils.fopen(os.path.join(jid_dir_, 'jid'), 'wb+') as fn_:
>  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1045, in fopen
>    fhandle = open(*args, **kwargs)
> IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/c4
> /677de1330880597ff52d40bc532392/jid'
> Traceback (most recent call last):
>  File "/usr/bin/salt-run", line 10, in <module>
>    salt_run()
> File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 250, in salt_run
>    client.run()
>  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 54, in run
>    runner.run()
>  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 166, in run
>    False)  # Don't daemonize
>  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 381, in _proc_function
>    return self.low(fun, low)
>  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 336, in low
>    mminion=self.mminion,
>  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 51, in store_job
>    mminion.returners[jidstore_fstr](False, passed_jid=load['jid'])
>  File "/usr/lib/python2.7/dist-packages/salt/returners/local_cache.py", line 124, in prep_jid
>    with salt.utils.fopen(os.path.join(jid_dir_, 'jid'), 'wb+') as fn_:
>  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1045, in fopen
>    fhandle = open(*args, **kwargs)
>IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/c4
>/677de1330880597ff52d40bc532392/jid'

**Comment by b18** [comment] 2015-07-21 15:54
Just an FYI that I was able to: 1) stop the salt-master service, 2) delete the directory **/var/cache/salt/master/jobs**, 3) restart the salt-master service, and fix the issue for now.

**Comment by jfindlay** [comment] 2015-07-21 21:09
@b18, thanks for the report.  Is there any other specific information you can think of that might make your situation unique, to help us narrow down this problem?  Can you reliably reproduce this?  Does it happen with all your minions or only a few?

**Comment by b18** [comment] 2015-07-22 01:06
Actually, it's now happening again. It appears to be related to any/all minions, not a specific one. I'm not doing anything I'd consider very out of the ordinary. The issue seems to have occurred after upgrading my master and minions to 2015.5.2. On my master, I have a cron job that runs every hour to enforce high states across all minions. That being said, this job has existed for probably around 5 months, with no issues until moving to the latest version. My Salt master is an Ubuntu 14.04 LTS server. For good measure, here is a uname -a for kernel info, etc.:

> Linux salt 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

My states are essentially managing user accounts, packages, and config files on Ubuntu 14.04 servers, and managing registry keys and packages on Windows 2008 R2 servers. If you need further info, I'm happy to provide it. Fortunately, this isn't a *huge* issue for us to be in this state for a small period of time, so I can leave it this way for a few days without clearing the jobs directory if the SaltStack team needs more info or wants me to test anything.

Below is the output requested:

**salt --versions-report**:
>salt --versions-report
>                  Salt: 2015.5.2
>                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
>                Jinja2: 2.7.2
>              M2Crypto: 0.21.1
>        msgpack-python: 0.3.0
>          msgpack-pure: Not Installed
>              pycrypto: 2.6.1
>               libnacl: Not Installed
>                PyYAML: 3.10
>                 ioflo: Not Installed
>                 PyZMQ: 14.0.1
>                  RAET: Not Installed
>                   ZMQ: 4.0.4
>                  Mako: 0.9.1
> Debian source package: 2015.5.2+ds-1trusty1

**salt 'Windows2008R2Server' test.versions_report**:

**salt 'Windows2008R2Server' test.versions_report**:
>[CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often happens >when trying to read a file not in binary mode.Please open an issue and include the following error: >unpack(b) recieved extra data.
>unpack(b) recieved extra data.

**salt 'Ubuntu14.04Server' test.versions_report**:
>[CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often happens >when trying to read a file not in binary mode.Please open an issue and include the following error: >unpack(b) recieved extra data.
>unpack(b) recieved extra data.

Thanks!

**Comment by jfindlay** [comment] 2015-07-22 22:08
@b18, do you have any minions with non UTF-8 chars in their minion IDs, or possibly any other unusually encoded strings associated with them?

**Comment by rzetterberg** [comment] 2015-09-08 08:24
I encountered the same problem today with `2015.5.3`.

For me, the problem was that I had been running `salt-master -l debug` recently and after stopping it with `Ctrl + C` some processes were still running. So when I started the `salt-master` service with systemctl again the debug processes were interfering. 

After stopping the service and killing all `salt-master` processes the problem was resolved.

**Comment by sjwoodr** [comment] 2015-10-19 18:34
I also encountered this problem but had an entirely different solution.  I was NOT out of disk space but the master cache had exhausted 100% of the inodes for the /var filesystem. Solution:

1) stop the salt master
2) rm -rf /var/cache/salt/master
3) restart the salt master
4) possibly also restart the minion(s)

**Comment by jfindlay** [comment] 2015-10-19 22:36
@sjwoodr's inode problem also resulted in #27792.

**Comment by cachedout** [comment] 2015-11-06 20:23
OK, so as best I can tell here the issue is fixed in #27025. I'm going to close this. Please let me know if that's in error and we'll take another look. Thanks.

**Closed by cachedout** 2015-11-06 20:23 UTC
Labels: Bug, Core, Critical, Fixed Pending Verification, P3

**Comment by lsuryo** [comment] 2015-12-24 03:04
Seeing the same problem...
tried all the steps mentions above and no luck, I need to copy a 13mb tgz file across all minions
salt-cp "*" my.tgz  /tmp/my.tgz

CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) recieved extra data.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltClientError: unpack(b) recieved extra data.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 203, in salt_cp
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 47, in run
    cp_.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 114, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 531, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 286, in run_job
    raise SaltClientError(general_exception)
SaltClientError: unpack(b) recieved extra data.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 203, in salt_cp
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 47, in run
    cp_.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 114, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 531, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 286, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: unpack(b) recieved extra data.

**Comment by lsuryo** [comment] 2015-12-24 03:08
Trying to copy a 13mb tgz file across all minions and failed 
deleted the directory mention above, restarted the master and all minions

```
 salt-cp "*" my.tgz /tmp/my.tgz
```

Error:
```
CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) recieved extra data.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltClientError: unpack(b) recieved extra data.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 203, in salt_cp
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 47, in run
    cp_.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 114, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 531, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 286, in run_job
    raise SaltClientError(general_exception)
SaltClientError: unpack(b) recieved extra data.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 203, in salt_cp
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 47, in run
    cp_.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 114, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 531, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 286, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: unpack(b) recieved extra data.
```

```
salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

All minions show the same versions-report

Any idea? It a huge issue...

thanks
