### ISSUE TITLE
Package conflict of python-ioflo in Saltstack Ubuntu repositories

### ISSUE THREAD

**Issue by dkorittki** [saltstack/salt#51101] opened 2019-01-08 17:17 UTC
### Description of Issue/Question
Package ```python-ioflo``` hosted in official Saltstack repositories for Ubuntu Xenial and Bionic share the same name packagename, version and architecture, but different content (filesize and real physical differences in metadata files ```control``` and ```prerm```). To my understanding this violates the Debian packaging policy.
https://github.com/saltstack/salt/issues/44872 mentions quiet the same problem with the difference, that this time the same package in the same repository for different OS versions is different.

It would be really great if you reconsider the way you deploy identical packages in your Debian repositories, because this is not only a hypothetical rule which is never applied in reality. For example the Debian package management software ```aptly``` is using this rule to deduplicate packages (which is where I got problems mirroring your repositories).

Debian packaging policy about duplicate packages:
https://wiki.debian.org/DebianRepository/Format?action=show&redirect=RepositoryFormat#Duplicate_Packages

Package files in question:
http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/pool/main/i/ioflo/python-ioflo_1.5.0-1_all.deb
http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest/pool/main/i/ioflo/python-ioflo_1.5.0-1_all.deb
(though there maybe more packages I am not aware of)

Sooo, is there any way to get this fixed?

### Steps to Reproduce Issue
On debian based systems:
```
mkdir /tmp/compare_packages && cd  /tmp/compare_packages
wget -O 1604.deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/pool/main/i/ioflo/python-ioflo_1.5.0-1_all.deb
wget -O 1804.deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest/pool/main/i/ioflo/python-ioflo_1.5.0-1_all.deb
dpkg -I 1604.deb | grep -e "Package\|Version\|Architecture\|Depends"
dpkg -I 1804.deb | grep -e "Package\|Version\|Architecture\|Depends"
```

Output from xenial package:
```
 Package: python-ioflo
 Version: 1.5.0-1
 Architecture: all
 Depends: python (>= 2.7), python (<< 2.8)
```
Output from bionic package:
```
 Package: python-ioflo
 Version: 1.5.0-1
 Architecture: all
 Depends: python (<< 2.8), python (>= 2.7), python:any (>= 2.6.6-7~)

```
Kind regards,
Dominik

**Comment by dwoz** [comment] 2019-01-09 16:22
@dkorittki Thanks for pointing this out. I think we can resolve this by changing the version `python-ioflo_1.5.0-1_all+18.deb`. Do you agree?

**Comment by dkorittki** [comment] 2019-01-14 13:45
I'm afraid this is not the only package affected. I searched the Saltstack Ubuntu repository for more duplicates and found the following conflicts (only precise/trusty/xenial/bionic latest paths):

(md5sum os/packagename)
```
574cf4c933e2e704abe3bb01da4b0dfd  trusty/libnacl-dev_20110221-4.1_amd64.deb
bb65882f8af3482b5f22680a69a651e8  precise/libnacl-dev_20110221-4.1_amd64.deb
c81579fc7b509a04c6d3e69afccb39f4  xenial/libnacl-dev_20110221-4.1_amd64.deb

b785e0852053e4da1bf14b2174665021  precise/libsodium13_1.0.3-1_amd64.deb
f2a563caffd691e1214334f0a1e77803  trusty/libsodium13_1.0.3-1_amd64.deb

8533064a1bb92e059a0bd09f4a23a3e5  trusty/libsodium-dbg_1.0.3-1_amd64.deb
c2a3d1ab91a30bd79ebc2491555b63c3  precise/libsodium-dbg_1.0.3-1_amd64.deb

e84090c58bf238e26d7145c3d78ed291  precise/libsodium-dev_1.0.3-1_amd64.deb
f6e3f5068aaeb0358b3780706d1a66a1  trusty/libsodium-dev_1.0.3-1_amd64.deb

9d2caaf6853bdc809670787ec30fd286  trusty/libzmq3_4.0.5+dfsg-3_amd64.deb
aff1f7d5b8430c88e55f1f2519e396cc  precise/libzmq3_4.0.5+dfsg-3_amd64.deb

1703b5618a190b1478ce950413952bfb  precise/libzmq3-dbg_4.0.5+dfsg-3_amd64.deb
b6a42473837733f3dd93d0daa723b9a4  trusty/libzmq3-dbg_4.0.5+dfsg-3_amd64.deb

03c3bf86e19ea9c3af45073be825ce3b  trusty/libzmq3-dev_4.0.5+dfsg-3_amd64.deb
2daf623e1fbfa0f637c16eefadd7c51b  precise/libzmq3-dev_4.0.5+dfsg-3_amd64.deb

0f7399f7df8c27e7cdc580b24415016e  precise/nacl-tools_20110221-4.1_amd64.deb
e9f2ed99742cdb8161d80d0d33cf5edc  xenial/nacl-tools_20110221-4.1_amd64.deb
eea25141ce06a47c84a778b4016d9ebf  trusty/nacl-tools_20110221-4.1_amd64.deb

3f56f98a8f6c2c77f941d9dbff21eaa1  trusty/python3-enum34_1.0.4-1_all.deb
485a3baeb9d29801716396603860bad5  precise/python3-enum34_1.0.4-1_all.deb

0d05df7e4c17d0fb43807754fa226ff3  precise/python-backports.ssl-match-hostname_3.4.0.2-1_all.deb
4f1d335c4d79d3b011969e0edb8c5039  trusty/python-backports.ssl-match-hostname_3.4.0.2-1_all.deb

b0352d4e84f5206d67d94699d55b4d0e  precise/python-concurrent.futures_3.0.3-1_all.deb
d368c9562515edc816d013a0bee77e16  trusty/python-concurrent.futures_3.0.3-1_all.deb

b75b80ab2a19eb5e9965e90bc3a886de  precise/python-enum34_1.0.4-1_all.deb
cb3a76df3ed1c57594b1a04a228a4bbb  trusty/python-enum34_1.0.4-1_all.deb

489340d05db705fae6e2bfdc8a1d6738  trusty/python-enum34-doc_1.0.4-1_all.deb
8f467f1a47bd6071ac247e823d3eaac4  precise/python-enum34-doc_1.0.4-1_all.deb

9e3bc8f579a3ba720c07fe1da8a81986  trusty/python-ioflo_1.3.8-1_all.deb
f9494b1f055cd65327cbad410608247b  precise/python-ioflo_1.3.8-1_all.deb

5ee478b8dd14581860aac1cb8eaac6d4  xenial/python-ioflo_1.5.0-1_all.deb
ad08a2b5f53b62577fc412aca856b4a7  bionic/python-ioflo_1.5.0-1_all.deb

15ee3ce39556b2b8529422bcd13d5aae  precise/python-raet_0.6.3-1_all.deb
91a9a65956e25bf6a3c26122c0c0cead  trusty/python-raet_0.6.3-1_all.deb

b7321ae4918c8d2d627a23b31590cc35  bionic/python-raet_0.6.5-1_all.deb
f919e85f4abb3744d9aa7cd7ced49d92  xenial/python-raet_0.6.5-1_all.deb

88deed3a233eddece7fe7d7d2f547f01  precise/python-timelib_0.2.4-1_amd64.deb
92ffb09ae10aceff8ce3bbefcd058494  trusty/python-timelib_0.2.4-1_amd64.deb
d4478bf67bb82afd3e9454915e2a9d02  xenial/python-timelib_0.2.4-1_amd64.deb

157be1c4d8db07eba27d363435796ba8  xenial/salt-api_2018.3.3+ds-1_all.deb
1e40f372cd424bdf95ced02e3552defc  trusty/salt-api_2018.3.3+ds-1_all.deb

25814dabb4650bfdcc96ed9950844706  xenial/salt-cloud_2018.3.3+ds-1_all.deb
b0b8dc052e47357e27afade2fa80f6d9  trusty/salt-cloud_2018.3.3+ds-1_all.deb

c177cf007af3482c592f33d77deb1759  xenial/salt-common_2018.3.3+ds-1_all.deb
f08274899f202d69db36e6ec6e5fb10b  trusty/salt-common_2018.3.3+ds-1_all.deb

83eb381f4ec57c3f5cd52875281ca1f2  trusty/salt-master_2018.3.3+ds-1_all.deb
ee3d29db7ee32df2ac5ac8c15a378d22  xenial/salt-master_2018.3.3+ds-1_all.deb

94d464b6decc9ff7b4def7975c531e42  xenial/salt-minion_2018.3.3+ds-1_all.deb
ad507ef222c467323120f4cf64440052  trusty/salt-minion_2018.3.3+ds-1_all.deb

4e803aadaaf0b2252b9426fa1637dd78  trusty/salt-ssh_2018.3.3+ds-1_all.deb
eed0f00c58dd9cda888fcfb611ac2fce  xenial/salt-ssh_2018.3.3+ds-1_all.deb

26d16d7d343384fb617d364638e8a3de  trusty/salt-syndic_2018.3.3+ds-1_all.deb
8f36a641a6b04f0b98accf8288802911  xenial/salt-syndic_2018.3.3+ds-1_all.deb
```

All packages listed have the same packagename, version and architecture in metadata but different control files (at least). All metadata differ in ```Installed-Size``` and some differ in ```Depends```.
I am not sure if differences in ```Installed-Size``` matter, but I guess on ```Depends``` it really does. Maybe someone with a better understanding of Debian packaging could verify this?

Fixing only the bionic files would mean only fixing ```python-raet_0.6.5-1_all.deb``` and ```python-ioflo_1.5.0-1_all.deb```, since there are no other conflicts for bionic. Like you said increasing the Version by adding ```+18``` to the package should work. This would imply to also fix ```Depends``` on reverse-dependend packages (which themselves probably must also increase in version then?), but it would be nice if someone with more Debian packaging knowledge could verify this.

**Comment by damon-atkins** [comment] 2019-01-14 15:15
Isn't he first question, why are they in the repo?

**Comment by dmurphy18** [comment] 2019-03-26 23:29
Closing this since Duplicate of https://github.com/saltstack/salt-pack/issues/594 which is currently being worked on.  Please review the contents of the issue in salt-pack which is the appropriate GitHub repo for discussing packaging issues.

**Closed by dmurphy18** 2019-03-26 23:29 UTC
Labels: Duplicate, Medium Severity, P1, Packaging
