### ISSUE TITLE
[BUG] pushover.post_message fails with TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by spinitron** [saltstack/salt#57829] opened 2020-06-28 15:44 UTC
**Description**
Sending a Pushover message with pushover.post_message fails

**Setup**

Problem was noticed in an orchestration like this

```
notify begin via pushover:
  salt.function:
    - tgt: MINIONID
    - name: pushover.post_message
    - kwarg:
        title: BEGIN
        message: update orchestration. Begin blah blah blah.
        user: xxxx
        token: xxxx
```

and verified the same problem with CLI.

That orch stopped working a while ago but unfortunatelyI can't figure out when or what changed at that time.

**Steps to Reproduce the behavior**

    salt MINIONID pushover.post_message message=FOO user=xxxx token=xxxx

Minion debug log

```

[DEBUG   ] LazyLoaded glob_match.match
[INFO    ] User root Executing command pushover.post_message with jid 20200628151928083155
[DEBUG   ] Command details {'fun': 'pushover.post_message', 'arg': [{'__kwarg__': True, 'message': 'fff', 'user': 'xxxxx', 'token': 'xxxxx'}], 'tgt': 'bhs7.spinitron.com', 'jid': '20200628151928083155', 'ret': '', 'tgt_type': 'glob', 'user': 'root'}
[DEBUG   ] Subprocess ProcessPayload-Job-20200628151928083155 added
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Starting a new job 20200628151928083155 with PID 31228
[DEBUG   ] Could not LazyLoad direct_call.allow_missing_func: 'direct_call.allow_missing_func' is not available.
[DEBUG   ] LazyLoaded pushover.post_message
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: bhs7.spinitron.com
[DEBUG   ] Requesting URL https://api.pushover.net/1/users/validate.json using POST method
[DEBUG   ] Using backend: tornado
[DEBUG   ] Response Status Code: 200
[WARNING ] Passed invalid arguments to pushover.post_message: expected string or bytes-like object

    Send a message to a Pushover user or group.

    :param user:        The user or group to send to, must be key of user or group not email address.
    :param message:     The message to send to the PushOver user or group.
    :param title:       Specify who the message is from.
    :param priority:    The priority of the message, defaults to 0.
    :param expire:      The message should expire after N number of seconds.
    :param retry:       The number of times the message should be retried.
    :param sound:       The sound to associate with the message.
    :param api_version: The PushOver API version, if not specified in the configuration.
    :param token:       The PushOver token, if not specified in the configuration.
    :return:            Boolean if message was sent successfully.

    CLI Example:

    .. code-block:: bash

        salt '*' pushover.post_message user='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' title='Message from Salt' message='Build is done'

        salt '*' pushover.post_message user='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' title='Message from Salt' message='Build is done' priority='2' expire='720' retry='5'

    
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 1870, in _thread_return
    opts, data, func, args, kwargs
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/pushover_notify.py", line 102, in post_message
    user_validate = salt.utils.pushover.validate_user(user, device, token)
  File "/usr/lib/python3/dist-packages/salt/utils/pushover.py", line 156, in validate_user
    data=_urlencode(parameters),
  File "/usr/lib/python3/dist-packages/salt/utils/pushover.py", line 88, in query
    opts=opts,
  File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 706, in query
    sess_cookies.save()
  File "/usr/lib/python3.7/http/cookiejar.py", line 1890, in save
    f.write(self.as_lwp_str(ignore_discard, ignore_expires))
  File "/usr/lib/python3.7/http/cookiejar.py", line 1877, in as_lwp_str
    r.append("Set-Cookie3: %s" % lwp_cookie_str(cookie))
  File "/usr/lib/python3.7/http/cookiejar.py", line 1849, in lwp_cookie_str
    return join_header_words([h])
  File "/usr/lib/python3.7/http/cookiejar.py", line 437, in join_header_words
    if not re.search(r"^\w+$", v):
  File "/usr/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20200628151928083155
```

**Expected behavior**

Pushover message sent without error

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3        
      docker-py: Not Installed
          gitdb: 2.0.5        
      gitpython: 2.1.11       
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6        
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1        
   pycryptodome: 3.6.1        
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-8-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**

**Comment by cmcmarrow** [comment] 2020-07-01 10:41
@spinitron I tried to reproduce your error but kept getting a different error. So I can at least confirmed `pushover.post_message
` does have a bug 😊 Thanks for the report!

**Comment by terminalmage** [comment] 2020-07-04 14:47
@cmcmarrow Weird, I was able to reproduce the traceback in a matter of minutes.

This is a bug in the code for parsing the `Set-Cookie` header in the response. It is setting boolean values for attributes in the header, and Python 3 is apparently less tolerant of this than Python 2. It's fixed in https://github.com/saltstack/salt/pull/57864.

**Comment by spinitron** [comment] 2020-07-04 15:52
Is there an easy way to add this fix to a system while keeping the 3001 Release?

**Comment by max-arnold** [comment] 2020-07-05 03:16
@spinitron Utility modules are harder to patch via the standard module overloading machinery, but here is a workaround:

```yaml
# pushover_patch.sls
# https://github.com/saltstack/salt/issues/57829

{% if grains['saltversion'] in ['3001'] %}

pushover_http_utils_patch:
  file.replace:
    - name: {{ grains['saltpath'] }}/utils/http.py
    - pattern: 'cookie\[parts\[0\]\] = True'
    - repl: 'cookie[parts[0]] = "true"'

restart_salt_minion_after_patching_pushover_http_utils:
  cmd.run:
    - name: 'salt-call service.restart salt-minion'
    - bg: true
    - onchanges:
      - file: pushover_http_utils_patch

{% endif %}
```

Then just run `salt MINION state.apply pushover_patch`

Caveats:

1. Completely untested, just adapted from an unrelated patch that I have in my state tree. Apply with caution.
2. Some tests in that PR are failing, so the fix could potentially break something else

**Comment by spinitron** [comment] 2020-07-05 14:17
Thanks @max-arnold

**Comment by terminalmage** [comment] 2020-07-05 17:26
Actually, I don't think my fix is correct, I'm looking closer now and it seems like some of these cookie attributes like `HttpOnly` and `Secure` are _supposed_ to get boolean values, and the cookie header parsing is failing because it's not taking into account the `SameSite` attribute, which causes the parsing logic to think that it's done with cookie attributes and that `SameSite=Lax` is a new cookie key/value pair, rather than an attribute.

**Comment by terminalmage** [comment] 2020-07-05 17:45
OK, I have updated that PR and I think I have the correct solution now.

**Comment by terminalmage** [comment] 2020-07-05 18:20
I have confirmed that my updated fix resolves the issue. Note that this will only trigger the traceback when writing the cookie file, so you will want to `rm -f /var/cache/salt/minion/cookies.*` before you test this to make sure that the code path that writes the file is reached.

**Closed** 2020-10-05 01:59 UTC
Labels: Bug, Magnesium, Regression, Severity: High
