### ISSUE TITLE
Number of scheduled jobs increases with number of masters

### ISSUE THREAD

**Issue by EddieOX** [saltstack/salt#26311] opened 2015-08-13 23:58 UTC
Hello all,
  I have noticed that the number of times a scheduled job runs equals the number of masters. To reproduce, I setup a Centos6 docker container with both a master and minion running. I faked the second master, but also see this behavior in my production environment with real separate master server.

/etc/salt/minion.d/test.conf:
```yaml
master:
 - localhost
 - 127.0.0.1

log_level: debug

schedule:
  run_sch:
    function: cmd.run
    seconds: 60
    args:
      - /tmp/test.sh
    splay:
      start: 0
      end: 1
```

grep run_sch  /var/log/salt/minion:
```
2015-08-14 00:01:10,044 [salt.utils.schedule                      ][DEBUG   ][23990] schedule.handle_func: adding this job to the jobcache with data {'fun': 'cmd.run', 'jid': '20150814000110041224', 'pid': 23990, 'id': '6e2a61a30cef', 'schedule': 'run_sch'}
2015-08-14 00:01:14,052 [salt.utils.schedule                      ][INFO    ][23509] Running scheduled job: run_sch
2015-08-14 00:01:14,056 [salt.utils.schedule                      ][DEBUG   ][23995] schedule.handle_func: adding this job to the jobcache with data {'fun': 'cmd.run', 'jid': '20150814000114053441', 'pid': 23995, 'id': '6e2a61a30cef', 'schedule': 'run_sch'}
2015-08-14 00:02:11,169 [salt.utils.schedule                      ][INFO    ][23509] Running scheduled job: run_sch
2015-08-14 00:02:11,180 [salt.utils.schedule                      ][DEBUG   ][24013] schedule.handle_func: adding this job to the jobcache with data {'fun': 'cmd.run', 'jid': '20150814000211173750', 'pid': 24013, 'id': '6e2a61a30cef', 'schedule': 'run_sch'}
2015-08-14 00:02:15,186 [salt.utils.schedule                      ][INFO    ][23509] Running scheduled job: run_sch
2015-08-14 00:02:15,189 [salt.utils.schedule                      ][DEBUG   ][24018] schedule.handle_func: adding this job to the jobcache with data {'fun': 'cmd.run', 'jid': '20150814000215187341', 'pid': 24018, 'id': '6e2a61a30cef', 'schedule': 'run_sch'}
```
The /tmp/test.sh script creates a random file, so I can verify that /tmp/test.sh really is running twice a minute. With just one master the cmd.run function will only run once a minute. You need to have the splay otherwise both will try to run both jobs at the exact same time and will get this error: "The scheduled job run_sch was not started, 1 already running". This behavior does not exist if I change `master_type: failover`.  
So it looks like, there's a minion instance for each master, and for each minion there's a schedule. Expected behavior would be running the scheduled job once per minute, regardless of the number of masters.

```
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
```

**Comment by garethgreenaway** [comment] 2015-08-14 21:07
I have an idea why this is happening.  Most likely related to event handling with multiple masters.

**Comment by jfindlay** [comment] 2015-08-17 16:47
@EddieOX, thanks for the report.

**Comment by EddieOX** [comment] 2015-08-18 16:16
Howdy @garethgreenaway,
  From my testing, the behavior in 2015.8 is the same as 2015.3.5. Did you see the correct behavior in your tests?

```
Salt Version:
           Salt: 2015.8.0rc3-1251-g65a29e6
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.11.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

**Comment by cachedout** [comment] 2016-05-18 20:45
I've been looking at this today. This is certainly happening in all branches. When we create multiple minion instances, we create a scheduler for each one. Then, they end up racing each other to schedule jobs. The tricky part here is to figure out what the intended behavior here should be.

In some cases, we might want scheduled jobs to return to both masters, such as events which might be fired from a job or scheduled jobs that should appear in both master job caches.

Obviously, the downside is that each job is performed twice on the minion which isn't exactly ideal and in some cases, really dangerous. Certainly, it will cause all sorts of racing and locking with states.

The final catch here is that even if we limit it to a single minion instance, how do we want to choose that instance? We could use the first connected minion, but this is a little non-intuitive.

I'm almost of the opinion here that we may need to detect multi-master mode and then change the scheduler so that it forks a new minion process which does the work and then sends the results back to the main minion process event bus which would then kick the results upstream to any connected masters.

What do you think, @garethgreenaway ?

cc: @thatch45

**Comment by thatch45** [comment] 2016-05-18 20:49
When I originally made the multi master I made sure that the schedule existed outside the minion instances. basically so that there was a top level loop that checked each connection instance for pubs and then ran them but processed the schedule in between so it always only ran once.
So my original design accounted for this.

**Comment by cachedout** [comment] 2016-05-18 20:54
I'm going to re-assign this to @DmitryKuzmenko. I think we'll need to move this up to a single event loop, as @thatch45 suggests.

**Closed** 2016-06-29 21:23 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P1, TEAM Core
