### ISSUE TITLE
salt-ssh failed to run after the python had been updated to 3.8

### ISSUE THREAD

**Issue by gray380** [saltstack/salt#55601] opened 2019-12-11 12:21 UTC
### Description of Issue
salt-ssh failed to run after the python had been updated to 3.8

### Setup
salt-ssh was in the normal condition and worked fine before python upgrade have been done
I've tried the following workaround:

```
source venv/bin/activate
pip install distro
pip install salt-ssh
```

### Steps to Reproduce Issue

```
$ salt-ssh
Traceback (most recent call last):
  File "/home/gray/salt/venv/bin/salt-ssh", line 8, in <module>
    sys.exit(salt_ssh())
  File "/home/gray/salt/venv/lib/python3.8/site-packages/salt/scripts.py", line 450, in salt_ssh
    import salt.cli.ssh
  File "/home/gray/salt/venv/lib/python3.8/site-packages/salt/cli/ssh.py", line 5, in <module>
    import salt.client.ssh
  File "/home/gray/salt/venv/lib/python3.8/site-packages/salt/client/__init__.py", line 30, in <module>
    import salt.config
  File "/home/gray/salt/venv/lib/python3.8/site-packages/salt/config/__init__.py", line 99, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/home/gray/salt/venv/lib/python3.8/site-packages/salt/config/__init__.py", line 88, in _gather_buffer_space
    import salt.grains.core
  File "/home/gray/salt/venv/lib/python3.8/site-packages/salt/grains/core.py", line 40, in <module>
    from platform import _supported_dists
ImportError: cannot import name '_supported_dists' from 'platform' (/usr/lib64/python3.8/platform.py)
```

### Versions Report
N/A

**Comment by gray380** [comment] 2019-12-24 07:18
So is there any way to solve the issue?

**Comment by peterhirn** [comment] 2019-12-30 10:52
This is a duplicate of Python 3.8 Support https://github.com/saltstack/salt/issues/55310

As a workaround you can patch `salt/grains/core.py`:
```diff
diff --git "a/salt/grains/core.py" "b/salt/grains/core.py"
index a3be0b8a1c..ff548923f4 100644
--- "a/salt/grains/core.py"
+++ "b/salt/grains/core.py"
@@ -35,12 +35,6 @@ except ImportError:
 __proxyenabled__ = ['*']
 __FQDN__ = None
 
-# Extend the default list of supported distros. This will be used for the
-# /etc/DISTRO-release checking that is part of linux_distribution()
-from platform import _supported_dists
-_supported_dists += ('arch', 'mageia', 'meego', 'vmware', 'bluewhite64',
-                     'slamd64', 'ovs', 'system', 'mint', 'oracle', 'void')
-
 # linux_distribution deprecated in py3.7
 try:
     from platform import linux_distribution as _deprecated_linux_distribution
@@ -1939,7 +1933,7 @@ def os_data():
         )
         (osname, osrelease, oscodename) = \
             [x.strip('"').strip("'") for x in
-             linux_distribution(supported_dists=_supported_dists)]
+             linux_distribution()]
         # Try to assign these three names based on the lsb info, they tend to
         # be more accurate than what python gets from /etc/DISTRO-release.
         # It's worth noting that Ubuntu has patched their Python distribution
```

Then you should be able to start `salt-ssh`, `salt-call` without the exception but you might run into other issues.

**Comment by waynew** [comment] 2019-12-30 19:25
Closing this, as @peterhirn points out it's a dupe of #55310

**Closed by waynew** 2019-12-30 19:25 UTC
Labels: Duplicate
