### ISSUE TITLE
[BUG] v3005 fails openssl FIPS self test

### ISSUE THREAD

**Issue by neutronscott** [saltstack/salt#62616] opened 2022-09-02 18:21 UTC
**Description**
Packaging problem with v3005 - lacks the .hmac files which openssl uses to test itself when fips=1

**Setup**
only relevant setup is kernel cmdline of fips=1

**Steps to Reproduce the behavior**
Boot Linux with FIPS enabled and run salt-call test.ping

**Expected behavior**
Return true

**Screenshots**
```
[root@rhel8 run]# salt-call test.ping
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
Aborted (core dumped)
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:33:26)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 8.6 Ootpa
        locale: utf-8
       machine: x86_64
       release: 4.18.0-372.19.1.el8_6.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.6 Ootpa
```
</details>

**Additional context**
I calculated the hmac of the supplied files as a workaround as such:

```
openssl sha256 -r -hmac orboDeJITITejsirpADONivirpUkvarP libssl.so.1.1 | cut -d' ' -f1 > /opt/saltstack/salt/run/.libssl.so.1.1.hmac
openssl sha256 -r -hmac orboDeJITITejsirpADONivirpUkvarP libcrypto.so.1.1 | cut -d' ' -f1 > /opt/saltstack/salt/run/.libcrypto.so.1.1.hmac
```

**Comment by dmurphy18** [comment] 2022-09-07 23:57
Looking at build containers for Centos 8 Stream and adjusting openssl used.

**Comment by dmurphy18** [comment] 2022-09-09 21:41
Building OpenSSL is not the answer since libk5crypto.so.3 misses its desired variables.
```
[root@ccd77cac6587 /]# find / -name libcrypto.so.1.1
/usr/local/openssl11/lib/libcrypto.so.1.1
/usr/lib64/libcrypto.so.1.1
[root@ccd77cac6587 /]# objdump -TC /usr/local/openssl11/lib/libcrypto.so.1.1 |grep EVP_K
[root@ccd77cac6587 /]# objdump -TC /usr/lib64/libcrypto.so.1.1 |grep EVP_K
00000000001715d0 g    DF .text	00000000000000f0  OPENSSL_1_1_1b EVP_KDF_ctrl
00000000001716c0 g    DF .text	000000000000008e  OPENSSL_1_1_1b EVP_KDF_ctrl_str
0000000000171570 g    DF .text	0000000000000021  OPENSSL_1_1_1b EVP_KDF_reset
0000000000171750 g    DF .text	0000000000000030  OPENSSL_1_1_1b EVP_KDF_size
00000000001715a0 g    DF .text	0000000000000023  OPENSSL_1_1_1b EVP_KDF_vctrl
0000000000171450 g    DF .text	0000000000000111  OPENSSL_1_1_1b EVP_KDF_CTX_new_id
0000000000171410 g    DF .text	0000000000000031  OPENSSL_1_1_1b EVP_KDF_CTX_free
0000000000171780 g    DF .text	0000000000000023  OPENSSL_1_1_1b EVP_KDF_derive
[root@ccd77cac6587 /]# 
```
The OS provided version contains them, puzzling

**Comment by dmurphy18** [comment] 2022-09-12 22:31
Well this appears to be the problem, using a build container with FIPS disabled with PyInstaller (which onedir currently uses) https://stackoverflow.com/questions/67981014/how-to-avoid-openssl-error-using-pyinstaller

Digging deeper

**Comment by dmurphy18** [comment] 2022-09-19 16:46
From trying to reproduce the issue, came across this when building on a FIPS enabled Centos 8 Stream which gives concern
```
5398 INFO: Processing pre-find module path hook distutils from '/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
5426 INFO: distutils: retargeting to non-venv dir '/usr/lib64/python3.9'
7515 INFO: Caching module dependency graph...
7630 ERROR: base_library.zip could not be created!
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/__main__.py", line 134, in <module>
    run() 
  File "/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/building/build_main.py", line 803, in main
    build(specfile, distpath, workpath, clean_build)
  File "/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/building/build_main.py", line 725, in build 
    exec(code, spec_namespace)
  File "/home/david/onedir_build/sources/salt.spec", line 6, in <module>
    a = Analysis([r"/tmp/tmpqn2uho33/bin/salt"],
  File "/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/building/build_main.py", line 277, in __init__
    self.__postinit__()
  File "/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/building/datastruct.py", line 155, in __postinit__
    self.assemble()
  File "/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/building/build_main.py", line 381, in assemble
    create_py3_base_library(libzip_filename, graph=self.graph)
  File "/tmp/tmpqn2uho33/lib64/python3.9/site-packages/PyInstaller/depend/utils.py", line 94, in create_py3_base_library
    source_hash = importlib_source_hash(source_bytes)
  File "/usr/lib64/python3.9/importlib/util.py", line 24, in source_hash
    return _imp.source_hash(_RAW_MAGIC_NUMBER, source_bytes)
ImportError: hash-based PYC validation (siphash24) not available in FIPS mode
```
This appears to be a PyInstaller calling basic Python functionality not available in FIPS mode at first glance.

**Comment by dmurphy18** [comment] 2022-09-19 20:53
Update to latest PyInstaller and managed to hand-build 3005-2 for Centos 8, but still get 
```
Installed:
  salt-3005-2.x86_64                                                                                         salt-minion-3005-2.x86_64                                                                                        

Complete!
[root@Unknown test_fips]# which salt-call
/bin/salt-call
[root@Unknown test_fips]# salt-call --local test.versions
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
Aborted (core dumped)
[root@Unknown test_fips]#
```
Hence building PyInstaller on FIPS enabled RHEL 8 doesn't help :(
Search for a fix continues

**Comment by neutronscott** [comment] 2022-09-19 21:32
Sorry I don't know anything about PyInstaller. Is it grabbing the system openssl lib? Might be their fault for not copying the .hmac as well

**Comment by dmurphy18** [comment] 2022-09-19 21:41
@neutronscott  I am floundering in trying to resolve this hence the Q, 
```
lacks the .hmac files
```
Given the same process was used to build RHEL 7  (openssl v1.0.2) and RHEL 9 (openssl v3.0.1) where there  are no .hmac files either but they work fine in fips mode.   What makes you think it is failing due to the lack of .hmac.  Also the key value orboDeJITITejsirpADONivirpUkvarP used below comes from where
```
openssl sha256 -r -hmac orboDeJITITejsirpADONivirpUkvarP libssl.so.1.1 | cut -d' ' -f1 > /opt/saltstack/salt/run/.libssl.so.1.1.hmac
``` 

Tried the above and it didn't work for me.

Lastly if you have a good url for explaining hmac and fips self-test for v1.1.1. would much appreciate it.  I have failed to google sufficiently well to find what I am after.
Thanks

**Comment by neutronscott** [comment] 2022-09-19 22:05
I had to go to the source. I found it in the srpm. The fips patch has the hmac secret.

**Comment by dmurphy18** [comment] 2022-09-19 22:11
Yeah, I was in there too, but what makes you think it is the hmac files or lack of them that is causing the problem.
And on RHEL 7, 8 and 9, it is using the system version of openssl, pyinstaller freezes a copy of libcrypto.so.1.1.1.

**Comment by dmurphy18** [comment] 2022-09-19 23:03
Beginning to think there are bigger FIPS issues with Centos 8 Stream, building an rpm and similar FIPS errors
```
warning: File listed twice: /opt/saltstack/salt/run/zmq/utils/zmq_compat.h
warning: File listed twice: /opt/saltstack/salt/run/zmq/utils/zmq_compat.h
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
/usr/lib/rpm/pythondistdeps.py:132: RuntimeWarning: Version for msgpack 1.0.2 (/home/david/rpmbuild/BUILDROOT/salt-3005-3.x86_64/opt/saltstack/salt/run) has not been found
  warn("Version for {!r} has not been found".format(dist), RuntimeWarning)
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE

```
And I am very familiar with building rpms

**Comment by dmurphy18** [comment] 2022-09-19 23:13
Installing a version of Salt with hmac files included still fails
```
  Preparing        :                                                                                                                                                                                                      1/1 
  Installing       : salt-3005-3.x86_64                                                                                                                                                                                   1/2 
  Installing       : salt-minion-3005-3.x86_64                                                                                                                                                                            2/2 
  Running scriptlet: salt-minion-3005-3.x86_64                                                                                                                                                                            2/2 
  Verifying        : salt-3005-3.x86_64                                                                                                                                                                                   1/2 
  Verifying        : salt-minion-3005-3.x86_64                                                                                                                                                                            2/2 

Installed:
  salt-3005-3.x86_64                                                                                         salt-minion-3005-3.x86_64                                                                                        

Complete!
[root@Unknown test_fips_2]# find /opt -name "*.hmac"
/opt/saltstack/salt/run/.libcrypto.so.1.1.hmac
/opt/saltstack/salt/run/.libssl.so.1.1.hmac
[root@Unknown test_fips_2]# salt-call --local -l trace test.versions
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
Aborted (core dumped)
[root@Unknown test_fips_2]# 
```

**Comment by neutronscott** [comment] 2022-09-19 23:40
> Yeah, I was in there too, but what makes you think it is the hmac files or lack of them that is causing the problem. And on RHEL 7, 8 and 9, it is using the system version of openssl, pyinstaller freezes a copy of libcrypto.so.1.1.1.
> 
> Did using the hmac files from above actually resolve the issue for you ?

When I created the .hmac files myself for the existing libs it did pass.

**Comment by dmurphy18** [comment] 2022-09-20 00:56
I am worried when rpmbuild fails with the same error, doesn't bode well.  Rebuilding from src rpm to see is I can gain any insight from built code other going through the source code itself.

Have to solve this in a CI/CD fashion to ensure consistency regardless of which user or system (considering Alma, Rocky,  Centos and RHEL)

**Comment by dmurphy18** [comment] 2022-09-21 00:04
@neutronscott While egg on face, first time I tried your solution it didn't work, must have fat-fingered something, but after being down in the bowels of openssl and then retrying your solution, it worked, thanks for that.

Working solution into CI/CD pipelines, and fix should appear with next minor release which is not far away, or sooner depending on how testing of the solution goes.

**Comment by dmurphy18** [comment] 2022-09-21 21:43
Fix by MR https://gitlab.com/saltstack/open/salt-pkg/-/merge_requests/205, under review

**Comment by dmurphy18** [comment] 2022-09-21 23:06
MR https://gitlab.com/saltstack/open/salt-pkg/-/merge_requests/205 merged, closing, fix will be available in next minor release which is soon.

**Closed by dmurphy18** 2022-09-21 23:06 UTC
Labels: Bug, Packaging
