### ISSUE TITLE
Unable to manage file: 'module' object has no attribute 'TEMPFILE_PREFIX'`

### ISSUE THREAD

**Issue by Sieabah** [saltstack/salt#43111] opened 2017-08-22 14:54 UTC
### Description of Issue/Question

    [salt.state       ][ERROR   ][1290] An exception occurred in this state: Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
        else:
    File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper with salt.utils.context.func_globals_inject(f, **inject_globals):
    File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 3366, in comment
        __salt__['file.comment_line'](name, regex, char, True, backup)
    File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 1160, in comment_line
        temp_file = _mkstemp_copy(path=path, preserve_inode=False)
    File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 1289, in _mkstemp_copy
        temp_file = salt.utils.mkstemp(prefix=salt.utils.files.TEMPFILE_PREFIX)
    AttributeError: 'module' object has no attribute 'TEMPFILE_PREFIX'

`[ERROR   ][1290] Unable to manage file: 'module' object has no attribute 'TEMPFILE_PREFIX'`

This was working until just recently, even with the patch version mismatch.

### Steps to Reproduce Issue
Minion tries to highstate by itself and fails, manual intervention with `sudo salt-call state.highstate` works just fine.

### Versions Report
Salt-Master: Salt: 2016.3.3
Salt-Minions: Salt: 2016.3.7

**Comment by gtmanfred** [comment] 2017-08-22 15:05
I believe that this was fixed, but I am not sure where.

It is worth noting that 2016.3 is in CVE release only, so we won't be releasing any bug fix patches for it.

Would you be able to update your master and minions to at least 2016.11 and see if the problem is fixed?

Also, your master should never be on an older release than the minion.  https://docs.saltstack.com/en/latest/faq.html#can-i-run-different-versions-of-salt-on-my-master-and-minion

Thanks,
Daniel

**Comment by Sieabah** [comment] 2017-08-22 15:18
It seems the latest supported for Ubuntu 14.04 is 2016.3.7, I'll try to see if I can get the 2016.11 release deployed.

**Comment by gtmanfred** [comment] 2017-08-22 15:23
We host our own packages

http://repo.saltstack.com/#ubuntu

There is an ubuntu tab on that page that will point you to the official repos for salt.

**Comment by Sieabah** [comment] 2017-08-22 18:40
It seems upgrading has solved the issue, weird bug between using 2016.11 (master) and 2016.3 (minion) that caused the minion unable to high state or use the package manager at all.

**Comment by gtmanfred** [comment] 2017-08-22 18:48
Hrm, if you have that error message, I would appreciate it, because we should be gauranteeing master -> minion backwards compatibility, where you can have a newer master with an older minion.

Thanks,
Daniel

**Comment by Sieabah** [comment] 2017-08-22 19:17
2016-10-27 19:04:07,794 [salt.cli.daemons ][INFO    ][3212] The Salt Minion is starting up
    2016-10-27 19:04:07,794 [salt.minion      ][INFO    ][3212] Minion is starting as user 'root'
    2016-10-27 19:04:07,795 [salt.utils.event ][INFO    ][3212] Starting pull socket on /var/run/salt/minion/minion_event_80a001ab8b_pull.ipc
    2016-10-27 19:04:35,074 [salt.utils.parsers][WARNING ][3212] Minion received a SIGTERM. Exiting.
    2016-10-27 19:04:35,074 [salt.cli.daemons ][INFO    ][3212] The salt minion is shutting down..
    2016-10-27 19:04:35,074 [salt.cli.daemons ][INFO    ][3212] The Salt Minion is shut down

**Comment by gtmanfred** [comment] 2017-08-22 19:24
Hrm, unfortunately, that isn't super helpful.  If you have the `-l debug`
log it might show a stack trace.

**Comment by Sieabah** [comment] 2017-08-23 01:07
I unfortunately don't have the master and minion in a state where it throws it anymore, but for testing purposes it was 2016.11 for the master and 2016.3.3 for the minion.

**Comment by gtmanfred** [comment] 2017-08-23 02:12
Ok, I will try and reproduce it tomorrow.

Thanks,
Daniel

**Comment by gtmanfred** [comment] 2017-09-01 16:01
Unfortunately I was unable to replace this :/

I am going to close this issue, if someone else reproduces it, please comment and I will re open it.

**Closed by gtmanfred** 2017-09-01 16:01 UTC
Labels: Info Needed
