### ISSUE TITLE
archive.extracted does not extract archives if file list has not changed but contents have

### ISSUE THREAD

**Issue by jerrykan** [saltstack/salt#40484] opened 2017-04-03 05:47 UTC
### Description of Issue/Question
The `archive.extracted` state does not extract the contents of an archive if the file list has not changed (even if the contents of the files has changed). The file list in the archive needs to change before salt will decide to extract the archive.

### Setup
Create 3 archives as follows:

```
$ mkdir files
$ echo "This is file1" > files/file1.txt
$ echo "This is file2" > files/file2.txt
$ tar -zvcf files-v1.tar.gz files/
files/
files/file1.txt
files/file2.txt
```

```
$ echo "This is and updated file1" > files/file1.txt
$ echo "This is and updated file2" > files/file2.txt
$ tar -zvcf files-v2.tar.gz files/
files/
files/file1.txt
files/file2.txt
```

```
$ echo "This is and updated file1" > files/file1.txt
$ echo "This is and updated file2" > files/file2.txt
$ echo "This is file3" > files/file3.txt
$ tar -zvcf files-v3.tar.gz files/
files/
files/file1.txt
files/file2.txt
files/file3.txt
```

```
$ sha256sum files-v*.tar.gz
12f347ab2b9e661ec96b6805cfed34598e2df138af35c91852c3c46ade10a8e7  files-v1.tar.gz
d7aea33efe98e9662c135af6e5730e978423740a8eb971b072d88a3f74f9897a  files-v2.tar.gz
ee22eecd4fe6c8d6daf012eb08d1ada4c94abd0614f6444826118ede3644053e  files-v3.tar.gz
```

### Steps to Reproduce Issue
Start with a state `usecase/test.sls` and run it:

```
files-archive:
  archive.extracted:
    - name: /opt/
    - source: http://fileserver/files-v1.tar.gz
    - source_hash: sha256=12f347ab2b9e661ec96b6805cfed34598e2df138af35c91852c3c46ade10a8e7
    - source_hash_update: True
    - archive_format: tar
```

```
$ salt-call state.apply usecase.test

local:
----------
          ID: files-archive
    Function: archive.extracted
        Name: /opt/
      Result: True
     Comment: http://fileserver/files-v1.tar.gz extracted to /opt/
     Started: 15:36:43.820642
    Duration: 210.415 ms
     Changes:   
              ----------
              extracted_files:
                  - files
                  - files/file2.txt
                  - files/file1.txt

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 210.415 ms
```

Update the state and run again:

```
files-archive:
  archive.extracted:
    - name: /opt/
    - source: http://fileserver/files-v2.tar.gz
    - source_hash: sha256=d7aea33efe98e9662c135af6e5730e978423740a8eb971b072d88a3f74f9897a
    - source_hash_update: True
    - archive_format: tar
```

```
$ salt-call state.apply usecase.test

local:
----------
          ID: files-archive
    Function: archive.extracted
        Name: /opt/
      Result: True
     Comment: All files in archive are already present
     Started: 15:39:07.857590
    Duration: 203.386 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 203.386 ms
```

Note that no changes are made even thought the `source_hash` is different and the contents of the files in the archive are different.

Update the state one more time and run again:

```
files-archive:
  archive.extracted:
    - name: /opt/
    - source: http://fileserver/files-v3.tar.gz
    - source_hash: sha256=ee22eecd4fe6c8d6daf012eb08d1ada4c94abd0614f6444826118ede3644053e
    - source_hash_update: True
    - archive_format: tar
```

```
$ salt-call state.apply usecase.test

local:
----------
          ID: files-archive
    Function: archive.extracted
        Name: /opt/
      Result: True
     Comment: http://fileserver/files-v3.tar.gz extracted to /opt/
     Started: 15:42:09.392288
    Duration: 205.973 ms
     Changes:   
              ----------
              extracted_files:
                  - files
                  - files/file2.txt
                  - files/file3.txt
                  - files/file1.txt

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 205.973 ms
```

Note how this time the archive is extracted because a new files has been added to the archive.

### Versions Report
```
Salt Version:
           Salt: 2016.11.0-1129-g058dcbf
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

**Comment by Ch3LL** [comment] 2017-04-03 16:20
Looks like i'm able to replicate this. I believe `archive.list` which does a check to see if it needs to be re-extracted only checks if there are files changes and doesn't check the contents of the files. Although we should be checking on the hash as well.

ping @terminalmage I am not sure if this is considered a duplicate of https://github.com/saltstack/salt/issues/39868 but might be a side case. Will label as a bug for now unless you tell me this will be fixed by that issue as well.

**Comment by terminalmage** [comment] 2017-04-06 01:12
``source_hash_update`` is working exactly as it's supposed to. You're changing the name of archive each time, so _of course_ we don't detect a change to the hash.

**Comment by jerrykan** [comment] 2017-04-06 02:28
@terminalmage this raises a new question then, what is the correct way to push out a new version of an archive (assuming the versions are contained in the archive name)? Based on the documentation I assumed that if the `source_hash` changed and `source_hash_update` was set to `True` then it would trigger an extract. Does the documentation need to be updated to reflect that this is not always the case?

I ran the original tests again against devel without changing the archive name, and changing only the contents and hashes, but only the initial run triggered an extract. I'll test again once the problems with pull request saltstack/salt#40551 mentioned in #40482 are resolved

**Comment by terminalmage** [comment] 2017-04-06 02:58
The way to do this would be to use the ``overwrite`` argument. If you don't wish to update your SLS file for this just to overwrite, then have to change it back after deploying the new version, then you could manage it using pillar data and pass in a pillar key on the CLI. For example:

```
deploy_tarball:
  archive.extracted:
    - name: /path/to/destination
    - source: salt://my-archive-v1.2.3.tar.gz
    - overwrite: {{ salt['pilllar.get']('force_deploy', False) }}
```

Assuming this is salt://foo.sls, you could then do the following:

```
salt myminion state.apply foo pillar='{force_deploy: True}'
```  

The documentation could be updated to be more clear on this, as well as the behavior of ``source_hash_update``. I'll see what I can do.

**Comment by jerrykan** [comment] 2017-04-06 06:59
OK, I've run some tests against saltstack/salt#40551 with the following results:

`source_hash_update: True`, `source` does not change, but archive contents and hash change:
 - v1 run: contents is extracted
 - v2 run: contents is extracted
 - v3 run: contents is extracted

`source_hash_update: False`, `source` does not change, but archive contents and hash change:
 - v1 run: contents is extracted
 - v2 run: no changes
 - v3 run: contents is extracted

`skip_verify: True`, `source` does not change, no use of hashes, but archive contents change:
 - v1 run: contents is extracted
 - v2 run: no changes
 - v3 run: error

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/srv/src/salt/state.py", line 1746, in call
    **cdata['kwargs'])
  File "/srv/src/salt/loader.py", line 1704, in wrapper
    return f(*args, **kwargs)
  File "/srv/src/salt/states/archive.py", line 877, in extracted
    __env__)
  File "/srv/src/salt/modules/file.py", line 614, in get_source_sum
    if os.path.isabs(source_hash):
  File "/opt/venv/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by terminalmage** [comment] 2017-04-06 14:01
@jerrykan I've pushed another commit to that PR

**Comment by terminalmage** [comment] 2017-04-07 15:42
@jerrykan have you had a chance to test the updated commit? I'm setting up a test environment to verify the fix now.

**Comment by terminalmage** [comment] 2017-04-07 16:47
I've already found a problem with the last commit, I'm working on a docker image that I can share with you for mutual testing.

**Comment by terminalmage** [comment] 2017-04-07 21:58
@jerrykan I've just pushed some more changes that I think will take care of the issues you found. If I haven't taken the time to say thank you already for your time and assistance, I'd like to do so now. Thanks!

I put together a docker container which uses a local nginx server to simulate a remote source with ``source_hash`` and ``source_hash_update``. The image is **terminalmage/issues:40484**. To use the image, all you need to do is run the following:

1. Run ``docker run --rm -it -v ~/path/to/git/checkout:/testing terminalmage/issues:40484`` to launch the container and get a shell.
2. Run ``nginx`` once the container is launched to start the local nginx server.

Replace ``~/path/to/git/checkout`` with a path to your git clone, and the container will run whatever revision you have checked out on your local machine. You can leave off the ``-v ~/path/to/git/checkout:/testing`` altogether and the container should fall back to using version 2016.11.3.

Here's the SLS that the docker container is using:

```
{%- set dest = '/tmp/' + sls %}
{%- set nginx_dir = '/usr/share/nginx/html' %}
{%- set tarball_name = 'foo.tar.gz' %}
{%- set hash_type = 'sha256' %}
{%- set hash_name = tarball_name + '.' + hash_type %}
{%- set tarball_symlink = nginx_dir + '/' + tarball_name %}
{%- set hash_symlink = nginx_dir + '/' + hash_name %}
{%- set pass = salt['pillar.get']('pass', 'first') %}
{%- set skip_verify = salt['pillar.get']('skip_verify', False) %}

{{ sls }}-{{ pass }}-tarball-link:
  file.symlink:
    - name: {{ tarball_symlink }}
    - target: {{ nginx_dir }}/{{ pass }}.tar.gz

{{ sls }}-{{ pass }}-hash-link:
  file.symlink:
    - name: {{ hash_symlink }}
    - target: {{ nginx_dir }}/{{ pass }}.tar.gz.{{ hash_type }}

{{ sls }}-{{ pass }}-extraction:
  archive.extracted:
    - name: {{ dest }}
    - source: http://localhost/{{ tarball_name }}
{%- if skip_verify %}
    - skip_verify: True
{%- else %}
    - source_hash: http://localhost/{{ hash_name }}
    - source_hash_update: {{ salt['pillar.get']('source_hash_update', False) }}
{%- endif %}
    - keep: {{ salt['pillar.get']('keep', False) }}
    - overwrite: {{ salt['pillar.get']('overwrite', False) }}
```

So, given this, you should be able to drive all the use cases you described in https://github.com/saltstack/salt/issues/40484#issuecomment-292086433 by passing the pillar data in on the CLI. For example:

```
salt-call state.apply testcase pillar='{source_hash_update: True, pass: first}'
```

There are three "passes" defined, i.e. three different tar archives. All of them are in ``/usr/share/nginx/html`` if you want to view them.  The SLS file manages a symlink which points at whatever tar archive is specified by the ``pass`` pillar value. This allows us to effectively change the contents of the tar archive without changing the filename, so that we can test ``source_hash_update`` properly.

So, to run the state with the second and third tar archives, just change ``first`` to ``second`` (or ``third``) in the CLI pillar you are passing in. To test deploying a new copy of the archive when the filename of the archive has changed, or if you're setting ``skip_verify`` to ``True``, again the only way to redeploy the archive is to use ``overwrite``, so you can add an ``overwrite: True`` to the pillar dictionary on the CLI and the SLS file will pick that up and use it.

Here's a [gist](https://gist.github.com/terminalmage/e5f84dd3a659a44c0fdad18f39fcd7be) containing some example usage.

**NOTE:** One caveat with the docker approach is that, since it runs from your local git checkout, if you've installed Salt from source before you may have a bunch of ``.pyc`` files in your git checkout. It might be a good idea to do a ``find ~/path/to/git/checkout -type f -name '*.pyc' -delete`` to clean them out before running tests in the docker container, just to remove a potential issue that might make troubleshooting frustrating (trust me, I've learned the hard way! :smile:).

Once you've had a chance to test, if everything looks good, can you please sign off on https://github.com/saltstack/salt/pull/40551? Thanks again for your time and effort.

**Comment by jerrykan** [comment] 2017-04-11 01:22
I've run the test against the latest saltstack/salt#40551 commits:

`source_hash_update: True`, `source` does not change, but archive contents and hash change:
 - v1 run: contents is extracted
 - v2 run: contents is extracted
 - v3 run: contents is extracted

`source_hash_update: False`, `source` does not change, but archive contents and hash change:
 - v1 run: contents is extracted
 - v2 run: no changes
 - v3 run: contents is extracted

(see notes below though)

`skip_verify: True`, `source` does not change, no use of hashes, but archive contents change:
 - v1 run: contents is extracted
 - v2 run: no changes
 - v3 run: no changes

So we have not errors now, which is good.


I believe there is an inconsistency in the second set of tests though. Both the v2 and v3 contain different contents in their archive. So for consistency I believe either the "v3 run" should result in no changes, or the "v2 run" should result in the contents being extracted. My opinion is that if we were being consistent with the third set of test then the "v3 run" should result in no changes. Thoughts?

**Comment by terminalmage** [comment] 2017-04-11 16:38
I guess you'll need to be more specific about what you mean by "archive contents change" in your testing. What is actually changing? Are the filenames all the same and what's in those files is changing? Or are the filenames different, leading to content being detected as missing, and thus triggering an extraction?

**Comment by jerrykan** [comment] 2017-04-12 00:28
The contents of the files in the archive change (see the first post about how the files were created).

**Comment by terminalmage** [comment] 2017-04-12 05:15
OK, the first time around I read that and I didn't catch that the third archive adds a new file. In that case, tests 1 and 2 that you doing are entirely expected, but test 3 is not... I've confirmed this and updated my docker container so that the third tar archive changes the contents of the file.

The state does not check the contents of all files in the archive, that would be a performance nightmare. It relies on knowing what files _should_ exist were the archive unpacked. This is why the v2 tar archive did not extract, but the v3 one did in your second test. The v3 archive has files that the other two doesn't, so it should result in being unpacked in your third test. I'll investigate in the morning, the issue most likely has to do with it (incorrectly) deciding it doesn't need to cache the archive.

**Comment by terminalmage** [comment] 2017-04-12 15:30
@jerrykan After doing some investigating, it looks like the ``file.managed`` state (which we use to pull down the source archive so that we get all the source_hash logic that ``file.managed`` provides) does not re-download a file if it was previously cached and ``skip_verify`` is set to ``True``.

We use ``file.managed`` to ensure that we get a copy of the file in a different location from where it would be cached, because when we track the hash (for ``source_hash_update``) we want to ensure that when we place the hash alongside the cached archive, it won't be in a location where it may be overwritten in the event that we subsequently cache a file by the same name as the file where we store the hash, in the same parent directory as the file we're caching.

This means that for remote file sources, we end up with 2 copies of the archive, one in the location where the fileclient caches it, and one in a separate location derived by the ``archive.extracted`` state. In the long term, we really should find a better way of dealing with this, such as automatically hashing remote files when they're downloaded so we always know the checksum of the cached copy and don't need to resort to saving the file to an alternate location. For the short term, I have pushed another commit which ensures that we delete _both_ cached copies of the archive when ``keep`` is set to ``False`` (the default).

This should resolve all the issues you discovered.

**Closed** 2017-04-14 11:53 UTC
Labels: 2016.11.4, Core, Expected Behavior, Fixed Pending Verification, High Severity, P4, State Module, TEAM Core
