### ISSUE TITLE
Auto restart of Salt Master service

### ISSUE THREAD

**Issue by pasmon** [saltstack/salt#47744] opened 2018-05-21 06:32 UTC
### Description of Issue/Question

Salt Master service not auto restarting after failure. Why auto restart is not defined in the SystemD service file? 

### Setup
This is the service file from our Salt Master

> [Unit]
> Description=The Salt Master Server
> Documentation=man:salt-master(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltstack.com/en/latest/contents.html
> After=network.target
> 
> [Service]
> LimitNOFILE=100000
> Type=notify
> NotifyAccess=all
> ExecStart=/usr/bin/salt-master
> 
> [Install]
> WantedBy=multi-user.target
> 

### Steps to Reproduce Issue
Our Salt Master should start automatically in cloud instance, but in this case our Gitlab was down for the moment:

> May 21 08:00:33 saltmaster.example.com systemd[1]: Starting The Salt Master Server...
> May 21 08:00:34 saltmaster.example.com systemd[1]: Started The Salt Master Server.
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: [CRITICAL] Exception caught while initializing gitfs remote 'git@gitlab.example.com:repository/repo.git': global name 'git' is not defined
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: Traceback (most recent call last):
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 353, in __init__
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: self.new = self.init_remote()
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 1474, in init_remote
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: self.configure_refspecs()
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 529, in configure_refspecs
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: except (git.exc.GitCommandError, GitRemoteError) as exc:
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: NameError: global name 'git' is not defined
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: [CRITICAL] Failed to load gitfs
> May 21 08:00:34 saltmaster.example.com salt-master[1634]: [CRITICAL] Master failed pre flight checks, exiting
> May 21 08:00:34 saltmaster.example.com systemd[1]: salt-master.service: main process exited, code=exited, status=1/FAILURE
> May 21 08:00:34 saltmaster.example.com systemd[1]: Unit salt-master.service entered failed state.
> May 21 08:00:34 saltmaster.example.com systemd[1]: salt-master.service failed.
 
Salt Master service failed, and it doesn't automatically try to restart since there is no restart defined in the service file.

### Versions Report
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Feb 20 2018, 09:19:12)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo

**Comment by gtmanfred** [comment] 2018-05-21 19:40
Duplicate of https://github.com/saltstack/salt/pull/45384

We do not want it to just keep restarting, if you want to set it to Restart = always, just put a drop-in file in `/etc/systemd/system/salt-master.service.d/restart.conf`
```
[Service]
Restart=always
```

**Closed by gtmanfred** 2018-05-21 19:40 UTC
