### ISSUE TITLE
Not Available error - Scheduling custom runner functions 

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#39333] opened 2017-02-11 23:20 UTC
### Description of Issue/Question
Custom runner functions are not working in scheduler

### Setup

Write a custom runner function add it to ```_runners``` dir
add ```_runners``` dir to ```runners_dir``` in salt master config

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

schedule the runner in salt master config as per documentation
```
    schedule:
      backup:
        function: myrunner.backup
        args:
          - 'server*'
        when: 9:00pm
```
check master logs ...
```Feb 12 08:01:17 master salt-master[41152]: Traceback (most recent call last):
Feb 12 08:01:17 master salt-master[41152]: File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 826, in handle_func
Feb 12 08:01:17 master salt-master[41152]: message=self.functions.missing_fun_string(func))
Feb 12 08:01:17 master salt-master[41152]: File "/usr/lib/python2.7/dist-packages/salt/utils/error.py", line 36, in raise_error
Feb 12 08:01:17 master salt-master[41152]: raise ex(message)
Feb 12 08:01:17 master salt-master[41152]: Exception: 'myrunner.backup' is not available.
```

### Versions Report
```
~:» salt-minion --versions-report                                                                                                                                                         [0]  09:59:45
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.1.3
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.3.8
         Jinja2: 2.9.4
        libgit2: 0.24.0
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: 0.6.3
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```
```
~:» salt-master --versions-report                                                                                                                                                         [0]  10:19:26
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.1.3
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.3.8
         Jinja2: 2.9.4
        libgit2: 0.24.0
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: 0.6.3
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```

**Comment by gtmanfred** [comment] 2017-02-13 16:21
Have you run `salt-run saltutil.sync_runners` so that the runner modules are in the master's extmods directory?

Thanks,
Daniel

**Comment by jagguli** [comment] 2017-02-16 22:37
Yes I have run this.

**Comment by gtmanfred** [comment] 2017-02-16 22:40
Is your runner.py available in /var/cache/salt/master/extmod/runners/runner.py ?

Also, if it is in the _runners directory, in the salt file_root, then you should not have to put _runners in the runner_dir.

**Comment by gtmanfred** [comment] 2017-02-28 19:11
It is worth noting that I am unable to get any runners to execute on the scheduler, and only minion modules are available.

If you use the saltutil.runner module, you can run the runners though.

```
schedule:
  job1:
    function: saltutil.runner
    minutes: 1
    args:
      - test.stdout_print
```

We will get this fixed, thanks for reporting it.

**Comment by mirceaulinic** [comment] 2017-03-02 01:59
Hi @gtmanfred - is there any specific timeframe _scheduled_ for this?
Besides this one, I have noticed another issue with the scheduler system: #39771. I am pretty sure there are not directly related, but I didn't see it in the past either. Which makes me think there could be some recent changes that triggered these.

**Comment by gtmanfred** [comment] 2017-03-02 02:00
I am going to try and look at it tomorrow, but we are going to get it into
2016.11.4

**Comment by mirceaulinic** [comment] 2017-03-02 02:01
That would be fantastic! Please let me know if I can help with anything! Thanks very much!

**Comment by gtmanfred** [comment] 2017-03-02 17:50
After a git bisect, this appears to be caused by this commit

https://github.com/saltstack/salt/commit/94977485460e8b472889be9554cc58fb365f23d4

**Comment by gtmanfred** [comment] 2017-03-02 17:55
Looks like this is also a duplicate of https://github.com/saltstack/salt/issues/38514

**Closed by gtmanfred** 2017-03-02 17:55 UTC
Labels: 2016.11.4, Blocker, Bug, Core, Critical, P1, TEAM Core

**Comment by gtmanfred** [comment] 2017-03-02 18:07
@mirceaulinic This should fix the problem https://github.com/saltstack/salt/pull/39791

**Comment by mirceaulinic** [comment] 2017-03-02 18:08
Awesome! Thank you so much @gtmanfred!
