### ISSUE TITLE
Providers option in salt minion config file is broken in 2015.2 and development branches

### ISSUE THREAD

**Issue by ag-wood** [saltstack/salt#22117] opened 2015-03-28 11:25 UTC
I've been trying to test the solarisips package provider which works after a few little tweeks (including changing the virtualname and autodetection parameters).  Solaris 11 requires the use of both IPS and SRV5 style packages which I planned to use the providers over-ride mechanism to switch as required.

The plan was to fix the autodetection such that IPS is the preferred package manager going forward with fall-back to SRV5 for selected packages.  This no longer works in the latest branches after changing to the LazyLoader scheme which appears to load every module when a provider is specified in a state or config file.

I have created a couple of gists to demonstrate the previous and new behaviours setting a provider over-ride for the brew package as an example.   Please refer to the following examples:

- Behaviour (expected) of salt as provided in the PyPi repository (2014.7.3):
https://gist.github.com/ag-wood/613c48504aeeec3ea790#file-salt-loader-raw_mod-2014-7-3

- Behaviour of salt in latest branches from GIT (2017.2 and Development):
https://gist.github.com/ag-wood/613c48504aeeec3ea790#file-salt-loader-raw_mod-2015-2

I will continue to look into the root cause of this but would love some pointers on how I might approach this.

**Comment by jfindlay** [comment] 2015-03-30 17:16
@ag-wood, thanks for the report.  I do not understand why this change is causing packaging failures, but @dmurphy18 or @cachedout may have better information here.

**Comment by cachedout** [comment] 2015-03-30 17:49
Hi @ag-wood 

```raw_mod``` doesn't evaluate ```__virtual__``` functions in execution modules so that won't do what I think you want. Could you use ```minion_mods()``` and just pull out the functions you want from that list? I don't fully understand the packaging concerns you have, so I might need a little more clarification to assist if that doesn't solve the issue you're having.

**Comment by ag-wood** [comment] 2015-03-30 22:12
To try to clarify further, I have looked out how raw_mod is used in throughout the salt codebase and found three instances -  state.py, minion.py and output/_ _ init_ _ .py.

All three appear to expect a specific module to be returned as a collection of functions.  The current code in loader.py returns all functions for __all modules__ of the specified module type.

To satisfy the three use cases found, I believe the function should read something like:
```python
def raw_mod(opts, module_name, functions, mod='modules'):
    '''
    Returns a single module loaded raw and bypassing the __virtual__ function

    .. code-block:: python

        import salt.config
        import salt.loader

        __opts__ = salt.config.minion_config('/etc/salt/minion')
        testmod = salt.loader.raw_mod(__opts__, 'test', None)
        testmod['test.ping']()
    '''
    loader = LazyLoader(_module_dirs(opts, mod, 'rawmodule'),
                      opts,
                      tag='rawmodule',
                      virtual_enable=False,
                      pack={'__salt__': functions})

	raw_module = {}
	for function_name in loader.keys():
		if function_name.split('.')[0] == module_name:
			raw_module[function_name] = loader.get(function_name)
			
	return raw_module
```

**Comment by cachedout** [comment] 2015-03-30 22:15
cc: @jacksontj You might be interested in this conversation.

**Comment by jacksontj** [comment] 2015-03-31 14:40
I guess I'm not following what the issue is here. The new loader returns a dict capable of loading all raw modules (to be clear it lazily loads). From a quick look at the uses around that should be fine-- as you still have to access the dict to call the functions. Is there somewhere that relies on iterating over all items in the dict and those being the only ones for a given module?

**Comment by ag-wood** [comment] 2015-03-31 20:02
Yes, the functions returned are expected to be those for the specified module only.  The functions that consume the output from raw_mod are expecting a single module that is fit for the purpose that they requested i.e. if a pkg state is being called from state.sls, and the package provider is specified in the pkg state, it is expecting the functions from a single pkg provider only.

The  get_progress function of the output module is expecting to retrieve the functions for a specific progress bar from the specified output provider module.

Minion.py which is expecting a single module that identifies returns the name of the master if the master_type option is set to func. 

There appear to be a few test modules that also have the same requirement.

I attached a couple of gists showing the old and new functionality in my first post to demonstrate the change in behaviour - it should be apparent from that what was and is expected by the consumers of raw_mod.

**Comment by ag-wood** [comment] 2015-04-01 12:31
I have created a pull request for this: https://github.com/saltstack/salt/pull/22240

**Comment by jacksontj** [comment] 2015-04-01 14:56
I see the issue-- that is a weird interface ;) I opened #22246 with a more efficient fix-- which gets the same result. I've also added a test for the interface.

**Comment by cachedout** [comment] 2015-04-01 21:32
@ag-wood Please test this now that @jacksontj 's fix is in and close this issue if appropriate. Thanks!

**Comment by ag-wood** [comment] 2015-04-01 23:19
Thanks very much @jacksontj and @cachedout , that's perfect - tested fine for my installation.

**Comment by jacksontj** [comment] 2015-04-01 23:55
Np, sorry for the breakage ;)

**Comment by ag-wood** [comment] 2015-04-02 03:15
Sorry to re-open this @jacksontj, @cachedout, but there's another aspect of this that seems to be missing.  I tested over-riding the package provider during state processing as described in the first section of the [State Providers](http://docs.saltstack.com/en/latest/ref/states/providers.html) documentation.  This works fine, however, over-riding the package provider using the [providers option in the minion configuration](http://docs.saltstack.com/en/latest/ref/states/providers.html#setting-a-provider-in-the-minion-config-file) still does not work.

Previously, the Loader class included a function called 'gen_functions' that see
```python
# Handle provider overrides
if provider_overrides and self.opts.get('providers', False):
    if isinstance(self.opts['providers'], dict):
        for mod, provider in self.opts['providers'].items():
            newfuncs = raw_mod(self.opts, provider, funcs)
            if newfuncs:
                for newfunc in newfuncs:
                    f_key = '{0}{1}'.format(
                        mod, newfunc[newfunc.rindex('.'):]
                    )
                    funcs[f_key] = newfuncs[newfunc]
```
I cannot find an equivalent in the LazyLoader class and would expect it to reference the recently repaired raw_mod function to over-ride the default pkg, service, user or group provider as per the documentation.  Again, I will continue to try to find the appropriate way to fix this but any pointers (or fixes) would be welcome.

**Comment by cachedout** [comment] 2015-04-21 22:16
@ag-wood I see that #22408 was merged. I'll go ahead and close this, since there hasn't been further activity. If we need to do more work here, feel free to leave a comment and we'll happily re-open it. Thanks!

**Closed by cachedout** 2015-04-21 22:16 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity
