### ISSUE TITLE
Issues with docs: Method not visible

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#40013] opened 2017-03-14 15:40 UTC
### Description of Issue/Question
If I follow this link I can't see the method. I need to scroll up before I see the method name. In this case **salt.states.file.exists**

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.exists

I see the following screen:

![screenshot-of-browser--method-not-visible](https://cloud.githubusercontent.com/assets/414336/23908605/c6b1387a-08d4-11e7-952f-6d74c79f8b76.png)

I use this browser:

Build-Identifikator: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by rallytime** [comment] 2017-03-14 15:44
Hi @guettli - thanks for reporting this issue. This is actually a duplicate of #37399 that we still need to get fixed. :)

I'll close this as a duplicate.

**Closed by rallytime** 2017-03-14 15:44 UTC
Labels: Duplicate
