### ISSUE TITLE
Jinja variable `'salt.utils.templates.AliasedLoader object'` has no attribute `'pkg'` [BUG]

### ISSUE THREAD

**Issue by jbartak** [saltstack/salt#62620] opened 2022-09-02 21:21 UTC
**Description**
Running highstate with salt-ssh lead to this error.
```
pweb1:
    - Rendering SLS 'base:all' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg'; line 1
      
      ---
      /root/.bashrc:    <======================
        file.managed:
          - source: salt://all/conf/bash.bashrc
          - template: jinja
      
      install all needed dependencies:
      [...]
      ---
```

**Setup**

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details (Debian 11 VM on Proxmox)
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Run `salt-ssh <node> state.highstate`

**Expected behavior**
Working highstate with salt-ssh

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
# salt --versions-report
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-17-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
N/A

**Comment by OrangeDog** [comment] 2022-09-05 08:57
You haven't shared the contents of bash.bashrc, but this is probably a duplicate of #41794

**Comment by jbartak** [comment] 2022-09-05 18:36
State:
```
/root/.bashrc:
  file.managed:
    - source: salt://all/conf/bash.bashrc
    - template: jinja
```

Content:
```
[ -z "$PS1" ] && return
PS1='\[\e[0;32m\]|{{ salt['grains.get']('osmajorrelease') }}|\[\e\][m[\u@{{ salt['grains.get']('id') }} \[\W\]: '
shopt -s checkwinsize
```

It is important to note that no matter if I remove state or not. It will always fail with error message pointing to the first state in SLS file.

**Comment by OrangeDog** [comment] 2022-09-05 19:41
You must have jinja code something like `salt.pkg` somewhere.

**Comment by jbartak** [comment] 2022-09-05 21:18
Yes I found it, it's in other state:
```
install all needed dependencies:
  cmd.run:
    - names:
      {% with pkgs_info = salt.pkg.info_installed() %}
      {% for package in ('netcat',) %}
      {% if package not in pkgs_info %}
      - apt -y install {{package}}
      {% endif %}
      {% endfor %}
      {% endwith %}
      - python3 -m pip install --user virtualenv
```

Looks like `salt.pkg.info_installed()` don't work. What's correct approach for salt-ssh then?
Even https://docs.saltproject.io/en/getstarted/config/jinja.html says that example `{{ salt.cmd.run('whoami') }}` should be correct.

**Comment by OrangeDog** [comment] 2022-09-05 21:30
As per the linked issue: `salt["pkg.info_installed"]()`.

Very odd that it's reporting the error in the wrong file. I think that's a new thing.

**Comment by jbartak** [comment] 2022-09-05 21:37
That's the point: `salt['pkg.info_installed']()` don't work either.

```
[CRITICAL] Rendering SLS 'base:all' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg.info_installed'; line 1

---
/root/.bashrc:    <======================
  file.managed:
    - source: salt://all/conf/bash.bashrc
    - template: jinja

install all needed dependencies:
[...]
---
pweb1:
    - Rendering SLS 'base:all' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg.info_installed'; line 1
      
      ---
      /root/.bashrc:    <======================
        file.managed:
          - source: salt://all/conf/bash.bashrc
          - template: jinja
      
      install all needed dependencies:
      [...]
      ---
```

**Comment by OrangeDog** [comment] 2022-09-06 08:03
Which salt installation are you using, classic or onedir?

**Comment by jbartak** [comment] 2022-09-06 08:15
It uses `classic`.

**Comment by jbartak** [comment] 2022-09-06 08:30
I just upgraded to `onedir` and there is still the same error.

**Comment by OrangeDog** [comment] 2022-09-06 09:57
For the error context issue, are those states in two separate files, or the same one, or one included from the other?

**Comment by jbartak** [comment] 2022-09-06 10:21
Both states are in the same SLS file.

**Comment by jbartak** [comment] 2022-09-06 10:21
Both states are in the same SLS file.

**Comment by papegaaij** [comment] 2022-09-07 14:05
I think I'm facing the same issue with the upgrade to salt 3005 (see below). It seems none of the execution modules are available when running `state.apply`. They do work when called directly with i.e. `salt-ssh <node> hosts.list_hosts`.

```    - Rendering SLS 'base:tkh.network.config' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'hosts.list_hosts'; line 8
      
      ---
      [...]
      
      {% set baseline = salt['pillar.get']('baseline') %}
      {% set network = salt['pillar.get']('network') %}
      {% set tkhiface = salt['grains.get']('tkh_iface:iface') %}
      {% set domain = salt['pillar.get']('network:domain', 'local') %}
      {% set hosts = salt['hosts.list_hosts']() %}    <======================
      
      configure-hostname:
        cmd.run: 
          - name: hostnamectl set-hostname {{ baseline.hostname }}.{{ domain }}
          - unless: test $(hostname -f) == "{{ baseline.hostname }}.{{ domain }}"
      [...]
      ---
    - Rendering SLS 'base:tkh.iptables.config' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'iptables.get_rules'; line 5
      
      ---
      # -*- coding: utf-8 -*-
      # vim: ft=yaml ts=2 expandtab
      
      {% set iptables = salt['pillar.get']('iptables') %}
      {% set current = salt['iptables.get_rules']() %}    <======================
      
      ###
      # Set sysconfig's iptables
      ###
      iptables-sysconfig:
      [...]
      ---
    - Rendering SLS 'base:tkh.replication.config' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg.version'; line 44
      
      ---
      [...]
        cmd.run:
          - name: |
              rm -f /srv/roster/key/salt-ssh.rsa /srv/roster/salt-ssh.rsa.pub /srv/roster/key/salt-ssh.ed25519 /srv/roster/salt-ssh.ed25519.pub
              ssh-keygen -P "" -f /srv/roster/key/salt-ssh.ed25519 -t ed25519 -C {{salt['grains.get']('id')}} -q
              mv /srv/roster/key/salt-ssh.ed25519.pub /srv/roster
              echo '{{ salt["pkg.version"]("tkh-installer") }}' > /srv/roster/key/salt-ssh.ed25519.generated    <======================
          - require:
            - file: configure-roster-key-dir
          - creates:
            - "/srv/roster/key/salt-ssh.ed25519.generated"
            - "/srv/roster/key/salt-ssh.ed25519"
      [...]
      ---
    - Rendering SLS 'base:tkh.docker.install' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg.version'; line 5
      
      ---
      # -*- coding: utf-8 -*-
      # vim: ft=yaml ts=2 sw=2 expandtab
      
      {% set docker = salt['pillar.get']('docker') %}
      {% set currentVersion = salt['pkg.version'](docker.pkg) %}    <======================
      
      {% if not currentVersion %}
      
      docker_pkg:
        pkg.installed:
      [...]
      ---
    - Rendering SLS 'base:tkh.docker.config' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg.version'; line 5
      
      ---
      # -*- coding: utf-8 -*-
      # vim: ft=yaml ts=2 expandtab
      
      {% set docker = salt['pillar.get']('docker') %}
      {% set currentVersion = salt['pkg.version'](docker.pkg) %}    <======================
      
      docker_etc_dir:
        file.directory:
          - name: /etc/docker
          - user: root
      [...]
      ---
    - Rendering SLS 'base:tkh.baseline.saltstack' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg.version'; line 5
      
      ---
      # -*- coding: utf-8 -*-
      # vim: ft=yaml ts=2 sw=2 expandtab
      
      {% set baseline = salt['pillar.get']('baseline') %}
      {% set saltcurrent = salt['pkg.version']('salt','salt-api','salt-master','salt-minion','salt-ssh') %}    <======================
      {% set saltavailable = salt['pkg.latest_version']('salt-master') %}
      {% set minion_id = salt['grains.get']('id') %}
      
      lock-salt-versions:
        pkg.installed:
      [...]
      ---
```

**Comment by papegaaij** [comment] 2022-09-07 14:57
I can confirm that this is a regression introduced between `3004.2` and `3005`, also with classic packaging. On two identical machines, one with `3004.2`, the other with `3005`, the first works fine, while the latter fails.

**Comment by papegaaij** [comment] 2022-09-07 18:14
Yes, that seems likely.

**Comment by Rudd-O** [comment] 2022-09-08 07:10
https://github.com/saltstack/salt/issues/62636

**Comment by MKLeb** [comment] 2022-10-04 16:42
fixed in https://github.com/saltstack/salt/pull/62635

**Closed by MKLeb** 2022-10-04 16:42 UTC
Labels: Bug, Regression, Salt-SSH, needs-triage, Phosphorus v3005.0
