### ISSUE TITLE
An unquoted date like 2014-12-31 breaks pillar-parsing

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#23506] opened 2015-05-08 21:45 UTC
Something I encountered some days ago: I wanted to include a date in a minions pillar.
The minion was a somewhat temporary VM so I added ``eol: 2015-12-31`` to it's pillar.

``saltutil.refresh_pillar`` and suddenly no more pillar for this minion. Not even ``salt $MINION 
pillar.items _errors`` was returning anything. So I set ``log_level_logfile: debug`` on both minion and master:
  - The minion complained it's pillar was a string instead of the expected dictionary
  - In the master's log I found a msgpack exception like "can't serialize datetime object"

So this msgpack-exception killed the minion's pillar completely. Not just an error and some 
missing data. 
As a workaround I quoted the date so it became a normal string. But I think something
like adding expiration dates to accounts should be possible w/o running in this issue.

**Comment by jfindlay** [comment] 2015-05-11 21:01
@0xf10e, thanks for the report.  This is a duplicate of #21721.  A workaround you can try is to put the date(time) in a string.

**Closed by jfindlay** 2015-05-11 21:01 UTC
Labels: Duplicate
