### ISSUE TITLE
2019.2.2 - match.filter_by not working when minion_id is passed unless 'compound' is used

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#55115] opened 2019-10-24 16:41 UTC
### Description of Issue
In 2019.2.2, the match.filter_by function does not return the expected result if any tgt_type other than 'compound' is used and a minion_id parameter is passed.

This works as expected in 2019.2.0 (or at least how *I* expected it to work, and how it has worked in the past).

This *can* be worked around by using the 'compound' matcher.

### Setup
No special setup

### Steps to Reproduce Issue
```
# salt-call match.filter_by "{'a': 'value_1', 'b': 'value_2', 'default': 'default_value'}" minion_id='a' tgt_type='pcre' --local -l debug
```
Expected return would be "value_1", but "default_value" is returned:

```
# salt-call match.filter_by "{'a': 'value_1', 'b': 'value_2', 'default': 'default_value'}" minion_id='a' tgt_type='pcre' --local -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10-80-18-37.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded match.filter_by
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded pcre_match.match
[DEBUG   ] LazyLoaded pcre_match.match
[DEBUG   ] LazyLoaded pcre_match.match
[DEBUG   ] LazyLoaded nested.output
local:
    default_value
```

with glob:
```
# salt-call match.filter_by "{'a': 'value_1', 'b': 'value_2', 'default': 'default_value'}" minion_id='a' tgt_type='glob' --local -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10-80-18-37.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded match.filter_by
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded glob_match.match
[DEBUG   ] LazyLoaded glob_match.match
[DEBUG   ] LazyLoaded glob_match.match
[DEBUG   ] LazyLoaded nested.output
local:
    default_value
```

"compound" works as expected:
```
# salt-call match.filter_by "{'a': 'value_1', 'b': 'value_2', 'default': 'default_value'}" minion_id='a' tgt_type='compound' --local -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10-80-18-37.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded match.filter_by
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded compound_match.match
[DEBUG   ] compound_match: a ? a
[DEBUG   ] LazyLoaded glob_match.match
[DEBUG   ] compound_match a ? "a" => "True"
[DEBUG   ] LazyLoaded nested.output
local:
    value_1
```

"compound" using the PCRE decorator:
```
# salt-call match.filter_by "{'E@a': 'value_1', 'b': 'value_2', 'default': 'default_value'}" minion_id='a' tgt_type='compound' --local -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10-80-18-37.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded match.filter_by
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded compound_match.match
[DEBUG   ] compound_match: a ? default
[DEBUG   ] LazyLoaded glob_match.match
[DEBUG   ] compound_match a ? "default" => "False"
[DEBUG   ] LazyLoaded compound_match.match
[DEBUG   ] compound_match: a ? b
[DEBUG   ] LazyLoaded glob_match.match
[DEBUG   ] compound_match a ? "b" => "False"
[DEBUG   ] LazyLoaded compound_match.match
[DEBUG   ] compound_match: a ? E@a
[DEBUG   ] LazyLoaded pcre_match.match
[DEBUG   ] compound_match a ? "E@a" => "True"
[DEBUG   ] LazyLoaded nested.output
local:
    value_1
```

On a 2019.2.0 node (or 2018.3/2017.7/etc):
```
# salt-call match.filter_by "{'a': 'value_1', 'b': 'value_2', 'default': 'default_value'}" minion_id='a' tgt_type='glob' --local -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10-80-18-56.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded match.filter_by
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded glob_match.match
[DEBUG   ] LazyLoaded nested.output
local:
    value_1
```
2019.2.0 pcre:
```
# salt-call match.filter_by "{'a': 'value_1', 'b': 'value_2', 'default': 'default_value'}" minion_id='a' tgt_type='pcre' --local -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10-80-18-56.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded match.filter_by
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded pcre_match.match
[DEBUG   ] LazyLoaded nested.output
local:
    value_1
```

Adding some logging to the matcher functions, it seems that the opts['id'] being used in the function for the compare is the actual id of the minion, and not the "minion_id" being passed in to the filter_by function.  (i.e. if the minion's id was actually "a", then the matches would return as expected)

### Versions Report
```
# salt-call --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

```

**Comment by Paulo-Nunes** [comment] 2019-10-24 17:35
Master and Minion are on version 2019.2.2.  When using Master 2019.2.2 with Minion on 2019.2.0 there is no problem and things work as expected.

**Comment by lomeroe** [comment] 2020-01-09 17:37
issue still exists and should not be closed

**Comment by xeacott** [comment] 2020-01-13 22:20
Thanks for reporting @lomeroe let me take a look and see what changes have been made to that module and see what's going on there.

**Comment by xeacott** [comment] 2020-01-13 23:23
Otherwise I can confirm that this is happening on 2019.2.2 but running `salt-call match.filter_by "{'a': 'value_1', 'b': 'value_2', 'default': 'default_value'}" minion_id='a' tgt_type='pcre' --local -l debug` should return `value_1` and not `default_value`

**Comment by dmurphy18** [comment] 2023-07-11 22:08
Closing this since 2019.2.x is long since EOL, as has Python 2.7

**Closed by dmurphy18** 2023-07-11 22:08 UTC
Labels: Bug, severity-low, Confirmed
