### ISSUE TITLE
[ERROR] Error encountered during module reload. Modules were not reloaded

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#45080] opened 2017-12-19 06:12 UTC
### Description of Issue/Question
Every time I run state.highstate, I got this error
```[ERROR] Error encountered during module reload. Modules were not reloaded```
By tracking down the code, I think this was caused by the following lines
```
/usr/local/lib/python3.6/site-packages/salt/state.py
    908     def module_refresh(self):
    909         '''
    910         Refresh all the modules
    911         '''
    912         log.debug('Refreshing modules...')
    913         if self.opts['grains'].get('os') != 'MacOS':
    914             # In case a package has been installed into the current python
    915             # process 'site-packages', the 'site' module needs to be reloaded in
    916             # order for the newly installed package to be importable.
    917             try:
    918                 reload_module(site)
    919             except RuntimeError:
    920                 log.error('Error encountered during module reload. Modules were not reloaded.')
    921             except TypeError:
    922                 log.error('Error encountered during module reload. Modules were not reloaded.')
    923         self.load_modules()
    924         if not self.opts.get('local', False) and self.opts.get('multiprocessing', True):
    925             self.functions['saltutil.refresh_modules']()
    926

```

I don't think this error affects anything. Can the loglevel be changed to info or warn instead of error.
### Setup
FreeBSD 11.1
Python 3.6.3

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.3 (default, Dec  8 2017, 18:14:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE-p4
         system: FreeBSD
        version: Not Installed

```

**Comment by garethgreenaway** [comment] 2017-12-19 17:52
@angeloudy Thanks for the report.  When you're seeing the errors in your logs following a module reload, are the modules successfully being reloaded?

**Comment by angeloudy** [comment] 2018-01-02 03:19
Yes, all the installed modules were successfully loaded.

**Comment by steverweber** [comment] 2018-05-08 19:03
i also get this... i assume its one of my custom modules that might be missing a `__virtual__` or an issue with having modules in sub directories cool custom stuff.

added some verbose logs...
```
            except RuntimeError as err:
                log.exception(err)
                log.error('Error encountered during module reload. Modules were not reloaded.')
            except TypeError as err:
                log.exception(err)
                log.error('Error encountered during module reload. Modules were not reloaded.')
```

found
```
[DEBUG   ] Refreshing modules...
[ERROR   ] expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 926, in module_refresh
    reload_module(site)
  File "/usr/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site.py", line 561, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 542, in main
    abs_paths()
  File "/usr/lib/python3.6/site.py", line 116, in abs_paths
    m.__cached__ = os.path.abspath(m.__cached__)
  File "/usr/lib/python3.6/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR   ] Error encountered during module reload. Modules were not reloaded.
[INFO    ] Loading fresh modules for state activity
```

python module `site` has:
```
def abs_paths():
    """Set all module __file__ and __cached__ attributes to an absolute path"""
    for m in set(sys.modules.values()):
        ...
        try:
            m.__cached__ = os.path.abspath(m.__cached__)
        except (AttributeError, OSError):
            pass
```

`m.__cached__` is type `None` and this is fine in python2.

**Comment by steverweber** [comment] 2018-05-08 19:05
found other projects with the same issue... also bug was reported to python:
https://bugs.python.org/issue30167

this issue should be fixed outside of salt.

/closed/

**Comment by steverweber** [comment] 2018-05-08 19:14
perhaps could change error message from
```
except TypeError as err:
                log.exception(err)
                log.error('Error encountered during module reload. Modules were not reloaded.')
```
to something like..

```
except TypeError as err:
                log.exception(err)
                log.error('Module reload issue, see: https://bugs.python.org/issue30167')
```

**Comment by steverweber** [comment] 2018-06-13 20:00
the PR in python was merged so this issue should be resolved once upstream builds of python have the patch.  https://github.com/python/cpython/commit/2487f30d5529948ace26559e274d7cac6abcd1a8

**Comment by Ch3LL** [comment] 2019-04-24 15:25
thanks for posting all that debugging information @steverweber i'll go ahead and close since its resolved in python.  I confirmed as of today that fix is currently in these versions:

```
v3.8.0a1
v3.8.0a2
v3.8.0a3
```

I also tested `unset PYTHONSTARTUP` environment variable and no longer received the error.

**Closed by Ch3LL** 2019-04-24 15:25 UTC
Labels: Upstream Bug
