### ISSUE TITLE
Salt-ssh no longer works on RHEL 8 with the python 3.6 shipped with the OS

### ISSUE THREAD

**Issue by clickbg** [saltstack/salt#59984] opened 2021-04-07 16:03 UTC
### Description of Issue
Since upgrading to salt-ssh (3003+ds-1) we can no longer provision RHEL 8 VMs since salt-ssh cannot work with python 3.6 and installing python 3.8 on RHEL introduces a lot of problems with our software. There is also no way to force salt-ssh to use specific python version so one has to change the OS default python.

### Setup
Master - salt-ssh 3003 (installed on Debian 10.9)
Minions - Red Hat Enterprise Linux release 8.3 (Ootpa)

### Steps to Reproduce Issue
root@atlas:~# salt-ssh [CENSORED] test.ping
[CENSORED]:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_1c7d78_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.root_1c7d78_salt/pyall/salt/scripts.py", line 437, in salt_call
            import salt.cli.call
          File "/var/tmp/.root_1c7d78_salt/pyall/salt/cli/call.py", line 6, in <module>
            import salt.cli.caller
          File "/var/tmp/.root_1c7d78_salt/pyall/salt/cli/caller.py", line 14, in <module>
            import salt.loader
          File "/var/tmp/.root_1c7d78_salt/pyall/salt/loader.py", line 7, in <module>
            import contextvars
          File "/var/tmp/.root_1c7d78_salt/py3/contextvars.py", line 1, in <module>
            from _contextvars import Context, ContextVar, Token, copy_context
        ModuleNotFoundError: No module named '_contextvars'
    stdout:
root@atlas:~# salt-ssh [CENSORED] -r "python3 --version"
[CENSORED]:
    ----------
    retcode:
        0
    stderr:
        Authorized uses only. All activity may be monitored and reported.
    stdout:
        Python 3.6.8

### Versions Report
root@atlas:~# salt-ssh --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 5.4.103-1-pve
        system: Linux
       version: Debian GNU/Linux 10 buster

**Comment by frogunder** [comment] 2021-04-13 16:40
Duplicate of https://github.com/saltstack/salt/issues/59942

Closing this to keep this issue to one ticket.

**Closed by frogunder** 2021-04-13 16:40 UTC
Labels: Bug, Salt-SSH, needs-triage
