### ISSUE TITLE
file.managed download failing checksum testing for Ubuntu initrd w/source_hash

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#29010] opened 2015-11-18 15:51 UTC
```
salt-call -l trace state.single file.managed name=/tmp/test source=http://nl.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/initrd.gz source_hash=http://nl.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/installer-amd64/current/images/SHA256SUMS
```

Relevant output:

```
[WARNING ] Please set "backend" to "requests" instead of setting "requests_lib" to "True"
[DEBUG   ] Requesting URL http://nl.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/installer-amd64/current/images/SHA256SUMS using GET method
[TRACE   ] Request Headers: {'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-agent': 'Salt/2015.8.1-1087-g5560cb6 http.query()'}
[INFO    ] Starting new HTTP connection (1): nl.archive.ubuntu.com
[DEBUG   ] "GET /ubuntu/dists/trusty-updates/main/installer-amd64/current/images/SHA256SUMS HTTP/1.1" 200 11834
[DEBUG   ] modules.file.py - extract_hash(): Extracting hash for file named: test
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (128), presumably hash type : sha512
[DEBUG   ] modules.file.py - extract_hash(): From "line": efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9  ./vivid-cdrom/initrd.gz got : []
(...)
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (96), presumably hash type : sha384
[DEBUG   ] modules.file.py - extract_hash(): From "line": efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9  ./vivid-cdrom/initrd.gz got : []
(...)
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (64), presumably hash type : sha256
[DEBUG   ] modules.file.py - extract_hash(): From "line": efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9  ./vivid-cdrom/initrd.gz got : ['efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9']
[DEBUG   ] modules.file.py - extract_hash(): Found: sha256 -- efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9
[DEBUG   ] modules.file.py - extract_hash(): From "line": 15cae8aac0936ee20a570b620b22d6707bf9c6a06ad0ce4953dbe9f9797e4169  ./vivid-cdrom/debian-cd_info.tar.gz got : ['15cae8aac0936ee20a570b620b22d6707bf9c6a06ad0ce4953dbe9f9797e4169']
[DEBUG   ] modules.file.py - extract_hash(): Found: sha256 -- efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9
[DEBUG   ] modules.file.py - extract_hash(): From "line": 217fba1e76b2b7733b3e8519d41f6e1097ec1903deca2eca163cb96ed1766305  ./vivid-cdrom/vmlinuz got : ['217fba1e76b2b7733b3e8519d41f6e1097ec1903deca2eca163cb96ed1766305']
(...)
[DEBUG   ] modules.file.py - extract_hash(): Found: sha256 -- efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (56), presumably hash type : sha224
[DEBUG   ] modules.file.py - extract_hash(): From "line": efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9  ./vivid-cdrom/initrd.gz got : []
(...)
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (40), presumably hash type : sha1
[DEBUG   ] modules.file.py - extract_hash(): From "line": efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9  ./vivid-cdrom/initrd.gz got : []
(...)
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (32), presumably hash type : md5
[DEBUG   ] modules.file.py - extract_hash(): From "line": efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9  ./vivid-cdrom/initrd.gz got : []
(...)
[DEBUG   ] modules.file.py - extract_hash: Returning the partially identified sha256 hash "efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9".
```

**Comment by The-Loeki** [comment] 2015-11-18 15:53
`efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9` ==  `./vivid-cdrom/initrd.gz`

**Comment by The-Loeki** [comment] 2015-11-18 15:54
Salt version = `2015.8.1-1087-g5560cb6`, but it's reproducable since at least 2015.5

**Comment by Ch3LL** [comment] 2015-11-18 17:20
@The-Loeki thanks for the report. I was able to reproduce this error. Also here is some additional output from the command:

```
local:
----------
          ID: /tmp/test
    Function: file.managed
      Result: False
     Comment: File sum set for file /tmp/test of efe2b5e68664fa07bad420a14147f68448d8bad44ef2650ac0074c3ec5d0e4e9 does not match real sum of 5e067bb85f226201a076c1da208ba676ef4ea0556d355d387277219f0b33d96a
     Started: 10:18:16.421082
    Duration: 6216.847 ms
     Changes:   
              ----------
              diff:
                  New file

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:   6.217 s
```

**Comment by Ch3LL** [comment] 2015-11-18 17:23
also I tested this on:

```
[ch3ll@ch3ll-centos states]$ sudo salt --versions-report
[sudo] password for ch3ll: 
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-123.8.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

**Comment by rhansen** [comment] 2016-03-22 08:46
The following four issues all seem to be the same bug:

  * #20681
  * #26981
  * #27397
  * #29010

I too am experiencing this with Salt 2015.8.7.

**Comment by The-Loeki** [comment] 2016-11-02 16:19
I'm working on the second problem here and that seems actually not that difficult either;

`extract_hash()` simply searches for `basename` of file.
The Ubuntu checksum file however sits several levels higher, and then says:
```
0570ffc6981f216d27cccf94232ca1b8d38df4133628fd6b17d1ffb1f9166054  ./xenial-hd-media/initrd.gz
5c412aa19b2dcd4978195153766a839ee8b557e71f3206e4d5a6ad2c208914a8  ./vivid-hd-media/initrd.gz
64f5479d55a537aaa935ae315bea9d7cd83f57d112cc6b7afdaa497330d67775  ./netboot/ubuntu-installer/amd64/initrd.gz
97b3fdac9991d5819c16f710882cc1c912ca6894ebb28baab05427198a098afd  ./wily-hd-media/initrd.gz
1a4702b075fbe20d237ce07a5508cc27329d83768109a94acaa4a026053ef4ba  ./hd-media/initrd.gz
```

And lo & behold, the erroneous hash returned is that of `./xenial-hd-media/initrd.gz`.

@terminalmage I'm thinking something along the lines of:
```
source_file = '/my/awesome/path/to/the/file'
source_hash =  '/my/awesome/hash'

if source_file is subpath of source_hash:
  sought_after = source_file - source_hash_path
else:
  sought_after = basename
```

Do you consider that a sane solution?

**Comment by terminalmage** [comment] 2016-11-02 17:55
The reason that ``./xenial-hd-media/initrd.gz`` is matched isn't because it's looking at the basename. It's because ``extract_hash()`` looks for an exact match on the file path passed, and none of these actually match. When no match is found, then it falls back to using the first line which contains a hash (which happens to be the ``./xenial-hd-media/initrd.gz`` line.

A possible fix for this would be to have ``extract_hash()`` look for _both_ an exact match, and a basename match.

**Comment by terminalmage** [comment] 2016-11-02 18:00
Correction, it looks like ``extract_hash()`` _does_ use basename. I've been hacking around in this code in a number of different branches and I must have confused it with something else.

Looking at the basename of the line in the hash file though, to match it with the basename of the path passed in, should be the correct fix though.

**Comment by The-Loeki** [comment] 2016-11-02 18:03
I'm not sure I follow there; basename of path occurs multiple times in source_hash exactly leading to this error in this specific instance?

**Comment by terminalmage** [comment] 2016-11-02 18:16
Yeah, it will, I just came to that realization.

So, there is something else at play here. We pass the path we're going to manage to ``extract_hash()``, so this wouldn't even work properly without some extra changes.

I'm working on a fix now.

**Comment by terminalmage** [comment] 2016-11-07 16:23
#37469 resolves this by allowing for a new argument to be specified to disambiguate ambiguous basename matches. It also resolves the problem of ``file.extract_hash`` only considering the basename of the file being passed in, and not the source URI.

Details on usage for the new ``source_hash_name`` argument are in #37469, and have also been added to the docs and the 2016.3.5 release notes.

Marking this issue as closed.

**Closed by terminalmage** 2016-11-07 16:23 UTC
Labels: Bug, Confirmed, High Severity, P3, Platform, State Module

**Comment by The-Loeki** [comment] 2016-11-07 19:09
@terminalmage THANKS :) I hope all your good work finally resolves most if not all outstanding hash_source issues; I'll test & of course report back if it doesn't ;)

**Comment by The-Loeki** [comment] 2016-11-07 19:21
The examples I gave [here](https://github.com/saltstack/salt/issues/29010#issuecomment-257916133) all work flawlessly now w00tw00t!

**Comment by terminalmage** [comment] 2016-11-07 22:30
Great, thanks for following up. Those edge cases have been around forever, so it's nice to see them handled properly now. Thanks for helping to get me pointed in the right direction.
