### ISSUE TITLE
file.recurse doesn't support multiple sources like file.managed does

### ISSUE THREAD

**Issue by localfilmmaker** [saltstack/salt#9304] opened 2013-12-17 00:34 UTC
I expect file.recurse to behave the same as file.managed when providing a source.  Meaning that you could provide a list of sources and it would use the first one that exists.  However, file.recurse doesn't do this; it only takes one source value.

I'd like to do something like this:
```
/etc/skel:
  file.recurse:
    - user: root
    - group: root
    - source:
      - salt://packages/core/files/skel.{{ grains['host'] }}
      - salt://packages/core/files/skel.{{ grains['server_role'] }}
      - salt://packages/core/files/skel
```
Thus having different files and subdirectories for /etc/skel/ for different hosts.  Currently it doesn't work this way and I don't know of any alternate way to do it.

**Comment by yermulnik** [comment] 2015-07-08 08:35
+1

**Comment by The-Loeki** [comment] 2015-08-04 11:40
Actually it already does exactly this, at least in 2015.5. I came here (@yermulnik, you did too?) because I would actually really like for file.recurse to take *all* sources.

Would `all_sources=False` be a nice option for this?

**Comment by yermulnik** [comment] 2015-08-04 12:11
@The-Loeki, on my side (salt 2015.5.2 (Lithium)) the problem is exactly as described by topicstarter.

**Comment by The-Loeki** [comment] 2015-08-04 12:40
@yermulnik héhéhé that's entirely possible in retrospect; looking at the commit history of `/salt/states/file.py` it was backported real recently (May)

**Comment by yermulnik** [comment] 2015-08-04 13:33
But it hasn't been committed into a release yet?

**Comment by The-Loeki** [comment] 2015-08-04 14:09
not sure; that particular commit ought to be in 2015.5.2, all I can tell you is that it's working here under git under CentOS 7.1

**Comment by basepi** [comment] 2015-08-04 17:35
Awesome, thanks for tracking down that commit, @The-Loeki! It appears to be in 2015.5.2 and will be in 2015.8.0 as well when it's released.

**Closed by basepi** 2015-08-04 17:35 UTC
Labels: Feature

**Comment by basepi** [comment] 2015-08-04 17:37
Gah, I didn't read closely enough. The commit does appear to be in 2015.5.2, if I'm reading the github summary correctly. It is definitely in 2015.8.0 release candidates.
