### ISSUE TITLE
win_certutil add_store state not installing certificates

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#36240] opened 2016-09-12 19:06 UTC
### Description of Issue/Question
The add_store function in the win_certutil module is not adding new certificates.

### Setup

Here is an example state file called
certificates.sls
```
salt://win/OURSISCAcert.cer:
   certutil.add_store:
       - store: TrustedPublisher
```

### Steps to Reproduce Issue
run the following

```
salt '000004' state.apply certificates
```
The output will be something like:

```
000004:
----------
          ID: salt://win/OURSISCAcert.cer
    Function: certutil.add_store
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1733, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\var\cache\salt\minion\extmods\states\win_certutil.py", line 66, in add_store
                  out = __salt__['certutil.add_store'](cert_file, store)
                File "c:\salt\var\cache\salt\minion\extmods\modules\win_certutil.py", line 87, in add_store
                  cert_file = __salt__['cp.cache_file'](source, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 421, in cache_file
                  result = _client().cache_file(path, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 178, in cache_file
                  return self.get_url(path, '', True, saltenv, cachedir=cachedir)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 706, in get_url
                  **get_kwargs
                File "C:\salt\bin\lib\site-packages\salt\utils\http.py", line 484, in query
                  **req_kwargs
                File "C:\salt\bin\lib\site-packages\tornado\httpclient.py", line 102, in fetch
                  self._async_client.fetch, request, **kwargs))
                File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 453, in run_sync
                  return future_cell[0].result()
                File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 232, in result
                  raise_exc_info(self._exc_info)
                File "<string>", line 3, in raise_exc_info
              ValueError: Unsupported url scheme: c:\salt\var\cache\salt\minion\files\base\win\OURSISCAcert.cer
     Started: 14:46:34.557000
    Duration: 406.0 ms
     Changes:   

```

### Versions Report
```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 1.4.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Aug  9 2016, 15:45:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.5
 
System Versions:
           dist: fedora 23 Twenty Three
        machine: x86_64
        release: 4.6.7-200.fc23.x86_64
         system: Linux
        version: Fedora 23 Twenty Three

```

**Comment by Ch3LL** [comment] 2016-09-12 22:59
@hrumph this is a duplicate of #33589 . Looks like you might be working on an possible fix which is awesome. I'm going to close this issue since there are more users on that other issue and if you could reference that issue from here on. Thanks

**Closed by Ch3LL** 2016-09-12 22:59 UTC
