### ISSUE TITLE
kwarg issue with reactor

### ISSUE THREAD

**Issue by niamtokik** [saltstack/salt#20788] opened 2015-02-18 10:42 UTC
Hi everyone,

I've an issue with one yaml script, I have read some other opened/closed issue on your github, but, I've not really found a good answer. So first, a small draw of my testing architecture:

```
   ________________________       _______________________
  |                        |     |                       |
  | Ubuntu 14.04 (OpenVZ)  |     | Ubuntu 14.04 (OpenVZ) |
  |________________________|     |_______________________|
  |          |             |     |             |         |
  | Salt-API | Salt-Master |<===>| Salt-minion | apache2 |
  |__________|_____________|     |_____________|_________|
   /_ _\   \\|             |
    | |     \| Reactor     |
    | |      |_____________|
    | |
   _|_|__________
  |              |
  | HTTP Request |
  |______________|

```

I use a full ubuntu 14.04 (on OpenVZ container) with official saltstack repository, all my server use last salt version (`salt 2014.7.1 (Helium)`). This project is simple, one HTTP request is sent to `Salt-API`, `Salt-API` send variables to `Reactor`, and `Reactor` exec `local.state.sls` with some defined action (currently only copy a template of  configuration file).

My problem is about kwarg passed on argument to reactor functionality. When I try to give one kwarg. Here my code (`/srv/reactor/template.sls`):

```yaml 
{% set postdata = data.get('post', {}) %}

thisisatest:
  local.state.sls:
    - tgt: 'hosting'
    - arg:
      - test
    - kwarg: 
      pillar:
        vhost: {{ postdata.vhost }}
```

Function called is `test`, located on (`/srv/salt/test/init.sls`) here:

``` yaml
{% set vartest = pillar.get('vhost') %}

/tmp/test.cfg:
  file.managed:
    - tgt: 'hosting'
    - name: '/tmp/test.cfg'
    - source: salt://test/vhost.txt
    - template: jinja
    - defaults:
      vhost: {{ vartest }}
```

Finally the template:

```
<VirtualHost *:80>
  ServerName {{ vhost }}
</VirtualHost>
```

When I launch this command manually (`salt 'hosting' state.sls test 'pillar={vhost: newtest}'`), all works well:

```
hosting:
----------
          ID: /tmp/test.cfg
    Function: file.managed
      Result: True
     Comment: File /tmp/test.cfg updated
     Started: 05:28:52.971499
    Duration: 284.935 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

On `salt-master`, in debug mode I have:

```
[DEBUG   ] Sending event - data = {'fun_args': ['test', {'pillar': {'vhost': 'newtest'}}], 'jid': '20150218053906555255', 'return': {'file_|-/tmp/test.cfg_|-/tmp/test.cfg_|-managed': {'comment': 'File /tmp/test.cfg updated', 'name': '/tmp/test.cfg', 'start_time': '05:39:07.728770', 'result': True, 'duration': 272.437, '__run_num__': 0, 'changes': {'diff': 'New file', 'mode': '0644'}}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-02-18T05:39:08.270062', 'fun': 'state.sls', 'id': 'hosting', 'out': 'highstate'}
[DEBUG   ] Sending event - data = {'fun_args': ['test', {'pillar': {'vhost': 'newtest'}}], 'jid': '20150218053906555255', 'return': {'file_|-/tmp/test.cfg_|-/tmp/test.cfg_|-managed': {'comment': 'File /tmp/test.cfg updated', 'name': '/tmp/test.cfg', 'start_time': '05:39:07.728770', 'result': True, 'duration': 272.437, '__run_num__': 0, 'changes': {'diff': 'New file', 'mode': '0644'}}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-02-18T05:39:08.270551', 'fun': 'state.sls', 'id': 'hosting', 'out': 'highstate'}
```

So work pretty well, my file is correctly created on minion, with good information on it. Now, If I send the same command over HTTP Request (`curl -H "Accept: application/json" -d vhost='vhosttest' -k https://master:8080/hook/template`), I've this (if file was not removed on minion):

```
[DEBUG   ] Sending event - data = {'fun_args': ['test'], 'jid': '20150218053248091506', 'return': {'file_|-/tmp/test.cfg_|-/tmp/test.cfg_|-managed': {'comment': 'File /tmp/test.cfg updated', 'name': '/tmp/test.cfg', 'start_time': '05:32:49.140810', 'result': True, 'duration': 277.989, '__run_num__': 0, 'changes': {'diff': '--- \n+++ \n@@ -1,3 +1,3 @@\n <VirtualHost *:80>\n-  ServerName newtest\n+  ServerName None\n </VirtualHost>\n'}}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-02-18T05:32:49.685212', 'fun': 'state.sls', 'id': 'hosting', 'out': 'highstate'}
[DEBUG   ] Sending event - data = {'fun_args': ['test'], 'jid': '20150218053248091506', 'return': {'file_|-/tmp/test.cfg_|-/tmp/test.cfg_|-managed': {'comment': 'File /tmp/test.cfg updated', 'name': '/tmp/test.cfg', 'start_time': '05:32:49.140810', 'result': True, 'duration': 277.989, '__run_num__': 0, 'changes': {'diff': '--- \n+++ \n@@ -1,3 +1,3 @@\n <VirtualHost *:80>\n-  ServerName newtest\n+  ServerName None\n </VirtualHost>\n'}}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-02-18T05:32:49.685600', 'fun': 'state.sls', 'id': 'hosting', 'out': 'highstate'}
```

and that (if the file was deleted):

```
[DEBUG   ] Sending event - data = {'fun_args': ['test'], 'jid': '20150218053528801241', 'return': {'file_|-/tmp/test.cfg_|-/tmp/test.cfg_|-managed': {'comment': 'File /tmp/test.cfg updated', 'name': '/tmp/test.cfg', 'start_time': '05:35:29.892781', 'result': True, 'duration': 271.797, '__run_num__': 0, 'changes': {'diff': 'New file', 'mode': '0644'}}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-02-18T05:35:30.431155', 'fun': 'state.sls', 'id': 'hosting', 'out': 'highstate'}
[DEBUG   ] Sending event - data = {'fun_args': ['test'], 'jid': '20150218053528801241', 'return': {'file_|-/tmp/test.cfg_|-/tmp/test.cfg_|-managed': {'comment': 'File /tmp/test.cfg updated', 'name': '/tmp/test.cfg', 'start_time': '05:35:29.892781', 'result': True, 'duration': 271.797, '__run_num__': 0, 'changes': {'diff': 'New file', 'mode': '0644'}}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-02-18T05:35:30.431603', 'fun': 'state.sls', 'id': 'hosting', 'out': 'highstate'}
```

My file is created, but `pillar` variables was not set and I've `None` value instead of `vhosttest`. Also, `fun_args` does not have same content if I send data manually with `salt` and with HTTP request via `Salt-API`

I don't know if I do one error on my configuration, or if its a bug... Could you help me? 

Many thanks in advance, and... This software is really really great! :)

**Comment by niamtokik** [comment] 2015-02-18 12:42
Youps, I've forgot some information, when I launch curl with HTTP Request, `salt-master` see good value:

```
[DEBUG   ] Gathering reactors for tag salt/netapi/hook/template
[DEBUG   ] Compiling reactions for tag salt/netapi/hook/template
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[DEBUG   ] Rendered data from file: /srv/reactor/services/template.sls:


thisisatest:
  local.state.sls:
    - tgt: 'hosting.'
    - arg:
      - test
    - kwarg: 
      pillar:
        vhost: vhosttest
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('thisisatest', OrderedDict([('local.state.sls', [OrderedDict([('tgt', 'hosting.')]), OrderedDict([('arg', ['test'])]), OrderedDict([('kwarg', None), ('pillar', OrderedDict([('vhost', 'vhosttest')]
))])])]))])
```

I've also try to "force" reactor configuration for generating the same output, but, doesn't work...

``` yaml
{% set postdata = data.get('post', {}) %}

thisisatest:
  local.state.sls:
    - tgt: 'hosting'
    - arg:
      - test
      - pillar: { vhost: {{ postdata.vhost  }}  }
```

This configuration return that on master:

```
[INFO    ] Got return from hosting. for job 20150218073735510445
[DEBUG   ] Sending event - data = {'fun_args': ['test', {'pillar': {'vhost': 'vhosttest'}}], 'jid': '20150218073735510445', 'return': "TypeError encountered executing state.sls: unhashable type: 'dict'. See deb
ug log for more info.", 'success': False, 'cmd': '_return', '_stamp': '2015-02-18T07:37:36.797839', 'fun': 'state.sls', 'id': 'hosting.', 'out': 'nested'}
[DEBUG   ] Sending event - data = {'fun_args': ['test', {'pillar': {'vhost': 'vhosttest'}}], 'jid': '20150218073735510445', 'return': "TypeError encountered executing state.sls: unhashable type: 'dict'. See deb
ug log for more info.", 'success': False, 'cmd': '_return', '_stamp': '2015-02-18T07:37:36.798171', 'fun': 'state.sls', 'id': 'hosting.', 'out': 'nested'}
```

So, I've "good" data structure, but not well parsing (yep, not really a clean method :P). Forcing is not the good way in this case... ;)

**Comment by whiteinge** [comment] 2015-02-18 17:53
You're very close!

This is a common YAML gotcha to get stuck on. The problem is that `pillar` needs to be indented under `kwarg` otherwise YAML will not interpret it as a sub-dictionary [as you can see here](http://yaml-online-parser.appspot.com/?yaml=thisisatest%3A%0A++local.state.sls%3A%0A++++-+tgt%3A+%27hosting%27%0A++++-+arg%3A%0A++++++-+test%0A++++-+kwarg%3A+%0A++++++pillar%3A%0A++++++++vhost%3A+%27%7B%7B+postdata.vhost+%7D%7D%27&type=json).

If you indent everything under `kwarg` by two more spaces it should work. [Example here](http://yaml-online-parser.appspot.com/?yaml=thisisatest%3A%0A++local.state.sls%3A%0A++++-+tgt%3A+%27hosting%27%0A++++-+arg%3A%0A++++++-+test%0A++++-+kwarg%3A+%0A++++++++pillar%3A+%0A++++++++++vhost%3A+%27%7B%7B+postdata.vhost+%7D%7D%27&type=json).

One final note, if you're passing more than one value from `postdata` into `pillar` this pattern is a nice short-hand:

```yaml
thisisatest:
  local.state.sls:
    - tgt: 'hosting'
    - arg:
      - test
    - kwarg: 
        pillar: {{ postdata | json() }}
```

**Comment by whiteinge** [comment] 2015-02-18 17:54
Also, kudos on the nicest and most helpful ascii-art I've seen in an issue in recent memory!  :-D

**Comment by niamtokik** [comment] 2015-02-18 19:53
Oh yeah! Its works! Crazy thing! Only for a small indentation! 

Many thanks! Saltstack is a crazy tool! I used fabric or ReX on other project, but, Saltstack is just... Awesome! Really nice works! Again: thanks! :)

PS: yep, I'm big fan of ascii-art. I think a small draw is better than long text! ;)

**Comment by rallytime** [comment] 2015-05-01 18:47
Looks like this one is resolved. I'm going to close this issue. Thanks!

**Closed by rallytime** 2015-05-01 18:47 UTC
Labels: Question
