### ISSUE TITLE
salt state.highstate 'data failed to compile' returns 0, but should return >1

### ISSUE THREAD

**Issue by jaybocc2** [saltstack/salt#25811] opened 2015-07-28 23:33 UTC
When running salt state.highstate it occasionally returns `data failed to compile` but still returns an exit code of 0 which makes it a little more difficult to verify the success of salt commands when scripted.

```
root@saltshaker-001:~# salt -b 1 -C 'G@ec2_tags:cluster:dash and G@ec2_tags:deployment:prod' state.highstate pillar='{"app_deploy": true}'

Executing run on ['prod-dash-003.us-west-2']

prod-dash-003.us-west-2:
Summary
-------------
Succeeded: 47 (changed=6)

Executing run on ['prod-dash-004.us-west-2']

prod-dash-003.us-west-2:
Failed:     0
-------------
Total states run:     47

Executing run on ['prod-dash-006.us-west-2']

prod-dash-006.us-west-2:
    Data failed to compile:
----------
    The function "state.highstate" is running as PID 10648 and was started at 2015, Jul 28 23:11:31.847915 with jid 20150728231131847915


root@saltshaker-001:~# echo $?
0

```

```
salt 2015.5.2 (Lithium)
```

**Comment by jfindlay** [comment] 2015-07-29 20:25
@jaybocc2, thanks for the report.

**Comment by cachedout** [comment] 2015-07-31 14:56
Does this only happen with batch mode?

**Comment by jaybocc2** [comment] 2015-07-31 17:42
I think, when not in batch mode, that it returns > 1.  I will need to reproduce for certain.

**Comment by cachedout** [comment] 2015-07-31 17:43
@jaybocc2 OK. That was my experience when testing and I wanted to confirm with you before we proceeded. Let us know. Thanks. :]

**Comment by rallytime** [comment] 2016-06-02 19:17
@jaybocc2 Were you able to confirm if this happens with batch mode? I suspect that is the case, but I wanted to check with you first. If so, this is a duplicate of #26230. While this issue is older, I think the other issue states the problem more accurately/succinctly and I'd like to close this as a duplicate and track the bug in only one place.

**Comment by jaybocc2** [comment] 2016-06-07 21:13
@rallytime Do as you wish. I ended up writing our own tool using the salt api to submit and process jobs.

This definitely occurred in batch mode; as you can see from the command i submitted with the bug report. `-b` is in use.

**Comment by rallytime** [comment] 2016-06-08 18:05
Yes, I think this is related to using batch. I just did some testing to double check and the highstate failure has the correct return code:
```
root@rallytime:~# salt rallytime state.highstate
rallytime:
    Data failed to compile:
----------
    ID this is a state in SLS no-compile is not a dictionary
ERROR: Minions returned with non-zero exit code
root@rallytime:~# echo $?
11
```
I'll close this as a duplicate and the issue can be tracked in #26230. Apologies for the trouble here.

**Closed by rallytime** 2016-06-08 18:05 UTC
Labels: Bug, Core, Duplicate, High Severity, P2
