### ISSUE TITLE
dockerio.run broken for command options

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#18939] opened 2014-12-11 23:16 UTC
This applies to v2014.7.0 and 2014.7 and develop HEADs.

```
docker-minion # <pkg-mgr> install docker python-six
docker-minion # pip install docker-py==0.5.0 # I had to manually download 0.5.0 from pypi and pip install the package file since pip kept wanting to install 0.6.0 over the net
docker-minion # docker login
<enter your info>
<email confirmation>
docker-minion # service docker start
docker-minion # docker run ubuntu:14.04 /bin/echo 'Hello world'
Hello world
docker-minion # docker run ubuntu:14.04 sleep 1024
docker-minion # docker ps
<grab docker ID from first column of output>
master # salt docker-minion docker.run <docker-ID> 'ls -l /etc'
docker-minion:
    ----------
    comment:
        Executed nsenter --target 9007 --mount --uts --ipc --net --pid ls "-l" "/etc"
    id: 
        <docker-ID>
    out:
        nsenter: invalid option -- 'l'

        Usage:
         nsenter [options] <program> [args...]

        Options:
         -t, --target <pid>     target process to get namespaces from
         -m, --mount [=<file>]  enter mount namespace
         -u, --uts   [=<file>]  enter UTS namespace (hostname etc)
         -i, --ipc   [=<file>]  enter System V IPC namespace
         -n, --net   [=<file>]  enter network namespace
         -p, --pid   [=<file>]  enter pid namespace
         -r, --root  [=<dir>]   set the root directory
         -w, --wd    [=<dir>]   set the working directory
         -F, --no-fork          do not fork before exec'ing <program>

         -h, --help     display this help and exit
         -V, --version  output version information and exit

        For more details see nsenter(1).
    status:
        True
```

**Comment by zxdvd** [comment] 2015-01-30 07:11
I can't reproduce this bug with version 2014.7.1.

    salt# salt '*' docker.run f7d 'ls -l  /etc'    
    zxd-PC:
        ----------
        comment:
            Executed nsenter --target 22194 --mount --uts --ipc --net --pid ls -l  / etc
        id:
            f7d
        out:
            total 616
            drwxr-xr-x 7 root root    4096 Aug 29 14:38 X11
            -rw-r--r-- 1 root root    2981 Jul 22  2014 adduser.conf
            drwxr-xr-x 2 root root    4096 Aug 29 14:39 alternatives
            drwxr-xr-x 4 root root    4096 Jul 22  2014 apparmor

**Comment by dmurphy18** [comment] 2015-06-02 20:21
Closing since not reproduced in later versions, also the Docker module has been extensively rewritten since

**Closed by dmurphy18** 2015-06-02 20:21 UTC
Labels: Bug, Medium Severity
