### ISSUE TITLE
REGRESSION: ERROR logs related to a previously working scheduled job

### ISSUE THREAD

**Issue by wt** [saltstack/salt#26480] opened 2015-08-19 18:09 UTC
salt-call --versions:

```
           Salt: 2015.5.3
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
```

The scheduled job in /etc/salt/minion:

```
schedule:
  highstate:
    function: state.highstate
    cron: "6-59/15 * * * *"
```

Error logs that show up over and over and over and ...:

```
[ERROR   ] Scheduled job "function" should have a dict value, not <ty...str'>
[ERROR   ] Scheduled job "minutes" should have a dict value, not <type 'int'>
```

Nothing more interesting pops up with "salt-minion -ldebug".

**Comment by wt** [comment] 2015-08-19 18:10
Oh, and this on a CentOS7 box using the latest EPEL7 packages.

**Comment by jfindlay** [comment] 2015-08-20 16:01
@wt, thanks for the report.  @garethgreenaway, do you have any ideas on this one?

**Comment by garethgreenaway** [comment] 2015-08-20 16:22
Will take a look.

**Comment by garethgreenaway** [comment] 2015-08-20 17:04
So far haven't been able to duplicate the error. I spun up a centos 7 docker instance with the same schedule item. Can you run it manually using schedule.run?

**Comment by wt** [comment] 2015-08-20 18:55
I will try to find some time to do this. I have a very busy day today.

**Comment by cachedout** [comment] 2016-05-19 20:35
I can't replicate this at all either. I'm closing this as "Cannot Reproduce" until we can come up with a better way to reliably illustrate this problem.

**Closed by cachedout** 2016-05-19 20:35 UTC
Labels: Bug, Cannot Reproduce, Core, High Severity, P3
