### ISSUE TITLE
Env is not working in cmd.run 2018.3.4 Release

### ISSUE THREAD

**Issue by andridzi** [saltstack/salt#53833] opened 2019-07-12 07:47 UTC
### Description of Issue
After upgrading from 2018.3.2 to 2018.3.4 Release module cmd.run with ENV variable has stopped working.

```create_mirror:
    cmd.run:
      - name: {{ create_mirror }}
      - env:
        - HOME: /home
```
While executing this state cmd "create_mirror" is executing in /root directory

In 2018.3.2 it was executing correctly in /home directory

Looks like a bug.

**Comment by cmcmarrow** [comment] 2019-07-12 14:46
Thank you @andridzi for making us aware of this regression.

**Comment by Ch3LL** [comment] 2020-04-07 19:09
im not able to replicate this on 3000.1 with this state:

```
test:
  cmd.run:
    - name: echo $HOME
    - env:
      - HOME: /home/
```

@andridzi are you still seeing this on the latest version of salt?

**Comment by adziura-ledger** [comment] 2020-05-21 20:38
@Ch3LL , I've tested and found that the problem is actually not with incorrect ENV.
before 2018.3.4 when env HOME was set cmd.run was executed exactly from this path.
Starting from 2018.3.4 - it's executing from /root directory

**Comment by sagetherage** [comment] 2021-08-12 00:12
Looks like this was never followed up - closing as not reported in later versions

**Closed by sagetherage** 2021-08-12 00:12 UTC
Labels: info-needed
