### ISSUE TITLE
Add OR Combine command "salt" and "salt-ssh"

### ISSUE THREAD

**Issue by NonCreature0714** [saltstack/salt#42348] opened 2017-07-17 20:08 UTC
### Description of Issue/Question
This is a feature request.

Pain: I have to type in "salt '*' cmd..." and "salt-ssh '*' cmd..." to execute the same commands on my agent and agentless systems. 

Example: 

    $ salt '*' text.ping
    saltminion01:
        True
    $ salt-ssh '*' text.ping
    saltminion02:
        True

Relief: A new command, whatever that may be (I suggest: 'salt-flats' | 'salt-coop') which executes both salt and salt-ssh commands on one target pattern.

Example: 

    $ salt-flats '*' test.ping 
    Agents:
    saltminion01:
        True

    Agentless: 
    saltminion02: 
        True

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt 2016.11.6 (Carbon)

**Comment by gtmanfred** [comment] 2017-07-17 20:37
https://github.com/saltstack/salt/issues/40997

This is a duplicate of the above request.  I am working on it for the Oxygen release

**Closed** 2017-07-17 20:37 UTC
Labels: Duplicate
