### ISSUE TITLE
OrderedDict pillar data on master becomes unordered dict data on minion - have cause and solution

### ISSUE THREAD

**Issue by wilminator** [saltstack/salt#42440] opened 2017-07-20 22:18 UTC
## Description of Issue/Question
Pillar data is ordered on master, but becomes unordered on minion.  This is seen by users when Jinja templates render dictionary based data out of the expected order on minions.  This was present in 2016.11.5 and is present in 2017.07.0

This example uses a modified version of formula-salt by blunix [https://github.com/blunix/formula-ssh](https://github.com/blunix/formula-ssh)

### /srv/salt/top.sls:
```
base:
  "*":
    - ssh.server
```

### /srv/salt/ssh/server/__init__.sls:
```
{% from "ssh/server/map.jinja" import ssh_info with context %}
{% from "ssh/server/map.jinja" import ssh_config with context %}

ssh_server_package:
  pkg.installed:
    - name: {{ ssh_info.server.package }}

ssh_server_sshd_config:
  file.managed:
    - name: /etc/ssh/sshd_config
    - source: salt://ssh/server/files/sshd_config.jinja2
    - template: jinja
    - context:
        config: {{ ssh_config.server.config }}
    - user: root
    - group: root
    - mode: 600

ssh_server_service:
  service.running:
    - name: {{ ssh_info.server.service }}
    - watch:
      - file: ssh_server_sshd_config
      - pkg: ssh_server_package
```

### /srv/salt/ssh/server/map.jinja:
```
{% set ssh_info = salt['grains.filter_by'] ({
    'Debian': {
        'server': {
            'package': 'openssh-server',
            'service': 'sshd',
            },
        },
    'RedHat': {
        'server': {
            'package': 'openssh-server',
            'service': 'sshd',
            },
        },
    })
%}
{% set ssh_config = salt['pillar.get']('ssh') %}
```

### /srv/salt/ssh/server/files/sshd_config.jinja2:
```
# This file is managed by Saltstack at {{ source }}
# DO NOT EDIT

{% for key, value  in config.items() %}
{%- if value is list %}
{%- for item in value %}
{{ key }} {{ item }}
{%- endfor %}
{%- else %}
{{ key }} {{ value }}
{%- endif %}
{%- endfor %}
```

### /srv/pillar/top.sls:
```
base:
  "*":
    - ssh
```

### /srv/pillar/ssh.sls:
```
ssh:
  server:
    config:
      Port: 22
      AddressFamily: any
      ListenAddress:
        - 0.0.0.0
        - "::"
      Protocol: 2

      HostKey:
        - /etc/ssh/ssh_host_rsa_key
        - /etc/ssh/ssh_host_ecdsa_key
        - /etc/ssh/ssh_host_ed25519_key

      KeyRegenerationInterval: 1h
      ServerKeyBits: 1024

      RekeyLimit: default none

      SyslogFacility: AUTHPRIV
      LogLevel: INFO

      LoginGraceTime: 2m
      PermitRootLogin: 'no'
      StrictModes: 'yes'
      MaxAuthTries: 6
      MaxSessions: 10

      RSAAuthentication: 'yes'
      PubkeyAuthentication: 'yes'

      AuthorizedKeysFile: .ssh/authorized_keys

      AuthorizedPrincipalsFile: none

      AuthorizedKeysCommand: none
      AuthorizedKeysCommandUser: nobody

      RhostsRSAAuthentication: 'no'
      HostbasedAuthentication: 'no'
      IgnoreUserKnownHosts: 'no'
      IgnoreRhosts: 'yes'

      PermitEmptyPasswords: 'no'
      PasswordAuthentication: 'yes'

      ChallengeResponseAuthentication: 'no'

      KerberosAuthentication: 'no'
      KerberosOrLocalPasswd: 'yes'
      KerberosTicketCleanup: 'yes'
#      KerberosGetAFSToken: 'no'
      KerberosUseKuserok: 'yes'

      GSSAPIAuthentication: 'no'
      GSSAPICleanupCredentials: 'no'
      GSSAPIStrictAcceptorCheck: 'yes'
      GSSAPIKeyExchange: 'no'
      GSSAPIEnablek5users: 'no'

      UsePAM: 'yes'

      AllowAgentForwarding: 'yes'
      AllowTcpForwarding: 'no'
      GatewayPorts: 'no'
      X11Forwarding: 'no'
      X11DisplayOffset: 10
      X11UseLocalhost: 'yes'
      PermitTTY: 'yes'
      PrintMotd: 'yes'
      PrintLastLog: 'yes'
      TCPKeepAlive: 'yes'
      UseLogin: 'no'
      UsePrivilegeSeparation: sandbox
      PermitUserEnvironment: 'no'
      Compression: delayed
      ClientAliveInterval: 0
      ClientAliveCountMax: 3
      ShowPatchLevel: 'no'
      UseDNS: 'yes'
      PidFile: /var/run/sshd.pid
      MaxStartups: 10:30:100
      PermitTunnel: 'no'
      ChrootDirectory: none
      VersionAddendum: none

      Banner: none

      AcceptEnv:
        - "LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES"
        - "LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT"
        - "LC_IDENTIFICATION LC_ALL LANGUAGE"
        - "XMODIFIERS"

      Subsystem:
        - "sftp /usr/libexec/openssh/sftp-server"

    default:
      SSHD_OPTS: ''
```

## Steps used to reproduce Issue
1. Install salt-master and salt minion on CentOS7 computer named "salt" using directions located at [https://repo.saltstack.com/#rhel](https://repo.saltstack.com/#rhel).
2. Create above configuration files.
3. Start the salt-master and salt-minion services then add the minion's key.
4. Run ```salt-call state.apply test=True``` to gauge new sshd_config file.  Note that the first items in the pillar are Port, AddressFamily, and ListenAddress, but the generated file would not match the order listed in the pillar.

## Root cause analysis
I dug through and confirmed that at least on the master that OrderedDicts were being passed internally.  I discovered that once the data structure hit the Serial.dumps method on the master and was transmitted to the minion's Serial.loads method, the mapping was switched to a standard dict object.

Rooting through the msgpack library, I found that it was encoding the OrderedDict on the master as a mapping, then decoding the mapping on the minion as a dict.  The library (at least msgpack-python) was not keeping the actual object type through the encoding and decoding process.

To fix this, I made the following changes in payload.py:
- Imported the OrderedDict object from salt.utils.odict 
- Edited the two msgpack.loads calls in Serial.loads to pass object_pairs_hook=OrderedDict so that the dictionary used when decoded would always be ordered.

This will have the side effect of always retaining dictionary order and the extra overhead associated with OrderedDict over dict, but this will cause pillar data rendering to work as expected.

### odict.patch
```
diff --git "a/C:\\Users\\mwilmes\\AppData\\Local\\Temp\\TortoiseGit\\payload-2fb986f.000.py" "b/C:\\Scripts\\salt\\salt\\payload.py"
index 1235a2e8b5..99446ace32 100644
--- "a/C:\\Users\\mwilmes\\AppData\\Local\\Temp\\TortoiseGit\\payload-2fb986f.000.py"
+++ "b/C:\\Scripts\\salt\\salt\\payload.py"
@@ -18,6 +18,7 @@ import salt.crypt
 import salt.transport.frame
 from salt.exceptions import SaltReqTimeoutError
 from salt.utils import immutabletypes
+from salt.utils.odict import OrderedDict
 
 # Import third party libs
 import salt.ext.six as six
@@ -134,9 +135,9 @@ class Serial(object):
                 # Due to this, if we don't need it, don't pass it at all so
                 # that under Python 2 we can still work with older versions
                 # of msgpack.
-                ret = msgpack.loads(msg, use_list=True, encoding=encoding)
+                ret = msgpack.loads(msg, use_list=True, encoding=encoding, object_pairs_hook=OrderedDict)
             else:
-                ret = msgpack.loads(msg, use_list=True)
+                ret = msgpack.loads(msg, use_list=True, object_pairs_hook=OrderedDict)
             if six.PY3 and encoding is None and not raw:
                 ret = salt.transport.frame.decode_embedded_strs(ret)
         except Exception as exc:
```

## Versions Report
[root@salttest srv]# salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment] 2017-07-21 16:59
@saltstack/team-core any ideas on this? do you think the fix is the right way to handle this?

**Comment by wilminator** [comment] 2017-07-26 04:50
I realized that I had seen something similar earlier this week.  Issue #17284 had a commit proposed that is extremely similar to my posted patch, then was reverted in issue #18206.  The committed code at the time was failing the test suite.  I will try to spin up a test environment, but I'm really short on time right now.

To clarify why the order is a problem, when specifying the port and IP address configuration to sshd_config, sshd requires that the Port statement comes before the address statements.  Yes, the template can be modified with dictsort|reverse for this specific problem, but I feel that being able to manage an arbitrary data order is reasonable and helpful.  Having the order of the pillar data reflected in rendered data helps visually verify correctness and in the case where a human must read through the file manually can save a man's sanity.

I can confirm that distributing this change in my salt environment has resolved my ordering issue with formula-ssh and for [samba-formula](https://github.com/saltstack-formulas/samba-formula) for RHEL and CentOS 6 & 7.

For the dev team, I did try to create an ExtType hook for OrderedDict, but the logic in msgpack-python detects the object as a dict before running the default object evaluation code unless we call loads with strict_types=True.  I don't know what that would break.

**Comment by wilminator** [comment] 2017-07-26 21:07
I downloaded and ran the test suite against my change.  There is one specific fail- there is a payload test that checks for no OrderedDicts coming out of the payload module.  I do not know why that test is present.  Any thoughts?

**Comment by github-abcde** [comment] 2018-02-01 08:38
@thatch45 Could you take a look at this? It would be very nice to be able to handle OrderedDicts, but I don't know the history of the failing PayloadTestCase above to say anything useful about that. I can confirm that the odict.patch does not break things on 2017.7.2 and allows OrderedDicts to be passed unharmed (for example as an execution module call result).

**Comment by edgan** [comment] 2018-02-26 19:46
I have a like problem. I have a formula with defaults as yaml in a map.jinja. I then merge in pillars into the jinja object.

It looks like local mode, aka masterless, keeps the order. Where as master mode and salt-ssh do not. In master mode it looks like the path the data takes is fairly complicated.

**Comment by edgan** [comment] 2018-02-26 22:00
My guess of why the test failed, is the version check was wrong. It was 'if msgpack.version >= (0, 2, 0):', but object_pairs_hook wasn't introduced till msgpack 0.2.3. The new patch will break anything older than msgpack 0.2.3 since object_pairs_hook is on both parts of the if statement. Also it looks like the new patch will break on Ubuntu 12.04 which is is on 0.1.10. It will also break rhel 5, which is on 0.1.9. Though I just checked the official supported list, and 12.04 and rhel 5 aren't on it.

**Comment by edgan** [comment] 2018-02-27 00:10
This is another patch that is probably a matching idea.

```--- salt/pillar/__init__.py.bak 2018-02-01 07:56:40.000000000 -0800
+++ salt/pillar/__init__.py     2018-02-26 13:34:14.370615200 -0800
@@ -90,7 +90,7 @@
             self.opts['pillarenv'] = pillarenv
         self.pillar_override = pillar_override or {}
         if not isinstance(self.pillar_override, dict):
-            self.pillar_override = {}
+            self.pillar_override = OrderedDict()
             log.error('Pillar data must be a dictionary')

     @tornado.gen.coroutine```

**Comment by edgan** [comment] 2018-02-28 19:43
I created PR #46257 to solve the problem, and I am already using the patch internally successfully.

**Comment by wilminator** [comment] 2018-03-02 22:49
I can confirm that this change is working for my example above as well.

**Comment by ixs** [comment] 2018-10-08 14:34
@rallytime I think you remove the fixed label. This is still open as the fix from @edgan was not actually merged.

And I just stumbled over this issue again...

**Comment by gtmanfred** [comment] 2018-10-08 14:37
removed

**Comment by ixs** [comment] 2020-01-13 11:47
Still valid with current salt.

**Comment by Oloremo** [comment] 2020-02-12 12:46
not stale

**Comment by Oloremo** [comment] 2020-03-13 13:55
not stale

**Comment by rnickle** [comment] 2020-09-23 16:46
Observing it in two minions with ordered dicts of lists, one running 2015.8.8, which evaluates in ordered mode, and the other running 3001.1.

My salt-master is 3000.3, so perhaps that is an issue also?

**Comment by Ch3LL** [comment] 2020-10-13 10:36
can you use the sort filter to resolve this issue?  `dict.items()|sort`

**Comment by sjorge** [comment] 2021-03-28 10:08
> can you use the sort filter to resolve this issue? `dict.items()|sort`

That would only work if the order doesn't matter, as that would sort A->Z.

**Comment by sagetherage** [comment] 2021-06-14 18:45
Another formula: https://github.com/saltstack-formulas/openssh-formula/blob/master/openssh/files/default/sshd_config handles this better

**Comment by sagetherage** [comment] 2021-06-22 20:12
@myii @dafyddj @javierbertoli 
do you know of other formulas that may be applicable, here?

**Comment by javierbertoli** [comment] 2021-06-22 21:16
@sagetherage if I understand your request, you're asking for another example where the order of the elements of a dict must be respected and that is working correctly?

If that's the case, I think the [iptables.tables](https://github.com/saltstack-formulas/iptables-formula/blob/master/iptables/tables.sls) state is an example or this. It uses an [ordered dict](https://github.com/saltstack-formulas/iptables-formula/blob/master/pillar.example#L81-L108) to create iptables rules.

**Comment by sagetherage** [comment] 2021-06-25 20:45
@javierbertoli yes and other formulas that may fit this use case, thank you!

**Closed** 2021-07-19 19:00 UTC
Labels: info-needed
