### ISSUE TITLE
Master is unable to target minion with space in ID from pillar top file

### ISSUE THREAD

**Issue by vutny** [saltstack/salt#39812] opened 2017-03-03 09:49 UTC
### Description of Issue/Question
If minion has a white space in the ID, the Salt Master cannot target it by ID specified in Pillar `top.sls` file.
Please look at the details below.

### Setup
```console
# curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
# sh bootstrap-salt.sh -M -A localhost -i "test minion"
# salt-key -y -A
# salt 'test minion' test.ping
test minion:
    True
# mkdir -p /srv/pillar     
# cat > /srv/pillar/top.sls <<EOF
base:
  'test minion':
    - test1
  '*':
    - test2
EOF
# cat > /srv/pillar/test1.sls <<EOF
test1: passed
EOF
# cat /srv/pillar/test2.sls <<EOF
test2: passed
EOF
```

### Steps to Reproduce Issue
```
# salt-call -l all pillar.items
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/99-master-address.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/99-master-address.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: test minion
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/99-master-address.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/99-master-address.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[TRACE   ] Loading core.hwaddr_interfaces grain
[TRACE   ] 'ip' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'ifconfig' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] Loading core.hostname grain
[TRACE   ] Loading core.get_master grain
[TRACE   ] Loading core.pythonversion grain
[TRACE   ] Loading core.path grain
[TRACE   ] Loading core.get_server_id grain
[TRACE   ] Loading core.saltversion grain
[TRACE   ] Loading core.saltpath grain
[TRACE   ] Loading core.pythonexecutable grain
[TRACE   ] Loading core.ip_fqdn grain
[TRACE   ] 'ip' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'ifconfig' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'ip' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'ifconfig' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] Loading core.dns grain
[TRACE   ] Loading core.ip6_interfaces grain
[TRACE   ] 'ip' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'ifconfig' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] Loading core.ip4_interfaces grain
[TRACE   ] 'ip' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'ifconfig' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] Loading core.append_domain grain
[TRACE   ] Loading core.os_data grain
[TRACE   ] 'dmidecode' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'smbios' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'virt-what' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[TRACE   ] 'virt-what' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'dmidecode' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] Loading core.zmqversion grain
[TRACE   ] Loading core.saltversioninfo grain
[TRACE   ] Loading core.pythonpath grain
[TRACE   ] Loading core.id_ grain
[TRACE   ] Loading core.locale_info grain
[TRACE   ] Loading core.get_machine_id grain
[TRACE   ] Loading core.ip_interfaces grain
[TRACE   ] 'ip' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[TRACE   ] 'ifconfig' could not be found in the following search path: '['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin']'
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (2949)
[DEBUG   ] Setting zmq_reconnect_ivl to '2949ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506', 'clear')
[TRACE   ] Inserted key into loop_instance_map id 28741360 for key ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506', 'clear') and process 1165
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_9b63fda306_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_9b63fda306_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_9b63fda306_pull.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/minion/minion_event_9b63fda306_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-03-03T09:40:47.850750', 'creds': {'publish_port': 4505, 'aes': 'l4jSPx5U/ljm+4BjUhvOVIKCyJb2l4ZCWLOcTObqEHqcbyqI90PGwON4AaJuOF3fQ162KCTS5ks=', 'master_uri': 'tcp://127.0.0.1:4506'}, 'key': ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506')
[TRACE   ] Inserted key into loop_instance_map id 28738696 for key ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506', 'aes') and process 1165
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pillar.items
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506')
[TRACE   ] Inserted key into loop_instance_map id 29647216 for key ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506', 'aes') and process 1165
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506')
[TRACE   ] Inserted key into loop_instance_map id 28762192 for key ('/etc/salt/pki/minion', 'test minion', 'tcp://127.0.0.1:4506', 'aes') and process 1165
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'local': {'test2': 'passed'}}
local:
    ----------
    test2:
        passed
[root@c7-systemd /]# salt -l all 'test minion' pillar.items
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: test minion
[DEBUG   ] Missing configuration file: /root/.saltrc
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: test minion
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'test minion_master', 'tcp://127.0.0.1:4506', 'clear')
[TRACE   ] Inserted key into loop_instance_map id 40671496 for key ('/etc/salt/pki/master', 'test minion_master', 'tcp://127.0.0.1:4506', 'clear') and process 1268
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] func get_cli_event_returns()
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/8e/515bf067c6989694cc3ac2c69e88a1d24d1373285d34daec315c17d0193f9a/.minions.p
[DEBUG   ] get_iter_returns for jid 20170303094558360836 sent to set(['test minion']) will timeout at 09:46:03.364459
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() received = {'tag': 'salt/job/20170303094558360836/new', 'data': {'tgt_type': 'glob', 'jid': '20170303094558360836', 'tgt': 'test minion', '_stamp': '2017-03-03T09:45:58.361804', 'user': 'root', 'arg': [], 'fun': 'pillar.items', 'minions': ['test minion']}}
[TRACE   ] get_event() received = {'tag': 'salt/job/20170303094558360836/ret/test minion', 'data': {'fun_args': [], 'jid': '20170303094558360836', 'return': {'test2': 'passed'}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2017-03-03T09:45:58.414697', 'fun': 'pillar.items', 'id': 'test minion'}}
[DEBUG   ] jid 20170303094558360836 return from test minion
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'test minion': {'test2': 'passed'}}
test minion:
    ----------
    test2:
        passed
[TRACE   ] _get_event() waited 0 seconds and received nothing
[DEBUG   ] jid 20170303094558360836 found all minions set(['test minion'])
```

#### Expected result
I assume that I should get `test1: passed` as well. But I don't.

### Versions Report
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 ```

**Comment by terminalmage** [comment] 2017-03-03 15:12
This is expected behavior as far as I know, since the default matcher is the compound matcher and this matcher parses each individual word separately. Add a ``- match: glob`` to the entry in the pillar top file and it should work.

**Comment by vutny** [comment] 2017-03-03 15:23
Thanks @gtmanfred ! It works with `- match: glob`. 
But I always thought that the `glob` is the default matcher in a top file. Is there any documentation page describing this?

**Comment by terminalmage** [comment] 2017-03-03 16:43
@vutny This changed to ``compound`` in 2014.7.0, but it looks like the docs were never updated to reflect this. In nearly every case, a single glob is processed identically by the ``compound`` and ``glob`` matchers, but since the compound matcher parses individual words, the whitespace causes the match to fail. I've opened https://github.com/saltstack/salt/pull/39819 to update the docs.

**Comment by terminalmage** [comment] 2017-03-03 19:09
Closing since tests have passed on https://github.com/saltstack/salt/pull/39819.

**Closed by terminalmage** 2017-03-03 19:09 UTC
Labels: Documentation, Expected Behavior, TEAM Core

**Comment by vutny** [comment] 2017-03-06 09:04
Awesome, thank you!
