### ISSUE TITLE
salt-minion memory overflow??

### ISSUE THREAD

**Issue by ivanwa** [saltstack/salt#30595] opened 2016-01-25 01:56 UTC
Last Friday,like memory leaks in some host problems.
 
![20160125095053](https://cloud.githubusercontent.com/assets/6895983/12540805/27442aee-c349-11e5-8e11-6a0e1a92d499.png)

ENV:
The server was started but havn't  connected with the salt-master.

LOG:(All is...)
RROR   ][2274] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2016-01-21 21:46:58,418 [salt.crypt                                          ][ERROR   ][2274] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2016-01-21 21:47:08,438 [salt.crypt                                          ][ERROR   ][2274] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2016-01-21 21:47:18,458 [salt.crypt                                          ][ERROR   ][2274] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2016-01-21 21:47:28,469 [salt.crypt                                          ][ERROR   ][2274] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2016-01-21 21:47:38,488 [salt.crypt 

Version:
salt-2015.8.3-1.el6.noarch
salt-minion-2015.8.3-1.el6.noarch

**Comment by jfindlay** [comment] 2016-01-25 19:19
@ivanwa, thanks for the report.  I am going to try to reproduce this today.  Any more information you can provide will be helpful.

**Comment by kingsquirrel152** [comment] 2016-01-25 20:22
Could this be related to #30411?

**Comment by jfindlay** [comment] 2016-01-25 21:45
@ivanwa, it could be.  I am not sure because I'm not very familiar with this code area.

**Comment by ivanwa** [comment] 2016-01-26 00:48
@jfindlay Thanks~

**Comment by basepi** [comment] 2016-01-26 16:47
I think I'm going to close this one as a duplicate of #30411 for now. If we end up with different reproduction steps for each leak we can split them off again. Would you mind adding your findings over there, @ivanwa?

**Closed by basepi** 2016-01-26 16:47 UTC
Labels: Bug, Core, Critical, P3
