### ISSUE TITLE
pkg.installed succeeds, but fails when you specify package version

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#42774] opened 2017-08-07 14:46 UTC
### Description of Issue/Question
The following works on 2016.11, but is broken on 2017.7
I suspect this is a result of the wildcards change, but I'm not sure if it is intended.

Works if I specify the full version, or the version with `*`

### Setup
Have the following state:
```salt
htop:
  pkg.installed:
    - version: 2.0.2
```

### Steps to Reproduce Issue
Running `salt-call state.sls htop` will install the package, but fail to recognize the package is installed and fail.

Debug log has the following line:

`[DEBUG   ] Current version (['2.0.2-1.el7']) did not match desired version specification (2.0.2), adding to installation targets`

### Versions Report
```text
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment] 2017-08-08 14:12
I was able to also bisect this failure to the wildcard pr here: https://github.com/saltstack/salt/pull/38621

@terminalmage is the above a bug or was this intended behavior to add the wildcard or the full version?

Also here is a docker container to quickly replicate the issue:

1. `docker run -it -v ~/git/salt/:/testing ch3ll/issues:42774 /bin/bash -c "yum remove htop -y; salt-call --local state.sls test -ldebug"` (where ~/git/salt is a local cloned git repo of salt)

**Comment by terminalmage** [comment] 2017-08-08 18:57
Fixed in https://github.com/saltstack/salt/pull/42808.

**Closed by terminalmage** 2017-08-08 18:57 UTC
Labels: 2017.7.2, Bug, Fixed Pending Verification, P3, Regression

**Comment by terminalmage** [comment] 2017-08-08 19:17
I've also added a test to prevent this sort of regression in the future.
