### ISSUE TITLE
Inconsistency between operations keywords in states.file (content vs contents)

### ISSUE THREAD

**Issue by tomlaredo** [saltstack/salt#34062] opened 2016-06-16 14:00 UTC
### Description of Issue
Following documentation (https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html):

- salt.states.file.blockreplace takes a "content" argument
- salt.states.file.managed takes a "contentS" argument

The bad thing in it is that the "file.managed" state seems to ignore the "- content: " (without "s") directive and to create an empty file.

### Setup
None working state:
```
/tmp/testfile.txt:
    file.managed:
        - content: |
            This sentence will never be added as file's content because we used "content" instead of "contents".
```

salt --version
salt 2015.8.10 (Beryllium)

**Comment by Ch3LL** [comment] 2016-06-16 16:56
@tomlaredo I believe this to be a duplicate of #29483. I am going to close this one and you can add your comments to that issue report that would be great and we will track this feature request there. Thanks!

**Closed by Ch3LL** 2016-06-16 16:56 UTC

**Comment by tomlaredo** [comment] 2016-06-17 07:32
Oh... I looked for an existing bug report and actually saw the one you marked as duplicate but didn't look well apparently (sorry).
