### ISSUE TITLE
Message set "hash_type" to SHA256

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#33671] opened 2016-06-01 14:28 UTC
### Description of Issue/Question
IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to SHA256 in Salt Minion config!

It appears that SHA256 is invalid and causes an issue, please fix the message to say

IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to "sha256" in Salt Minion config!

Or even better
IMPORTANT: Do not use md5 hashing algorithm! Please add "hash_type: sha256" in Salt Minion config!

Salt 2015.8.8.2

**Comment by rallytime** [comment] 2016-06-01 20:24
This warning is fixed in newer versions of Salt with #32360.

**Comment by Ch3LL** [comment] 2016-06-01 21:31
@damon-atkins are you okay to close this issue? Looks like also a duplicate of #33233

**Comment by damon-atkins** [comment] 2016-06-01 23:26
Yep

**Closed** 2016-06-02 13:16 UTC
Labels: Duplicate
