### ISSUE TITLE
2014.7.5 for Lucid packages?

### ISSUE THREAD

**Issue by junster1** [saltstack/salt#23179] opened 2015-04-29 18:53 UTC
Any chance we can get Lucid versions built for 2014.7.5?

@joehealy

**Comment by jfindlay** [comment] 2015-04-29 19:27
Lucid will reach end of life in a few days, so we've decided to similarly drop support.

**Comment by joehealy** [comment] 2015-04-29 22:12
I will be aiming to get a final release up today though.

Cheers,

Joe

**Comment by joehealy** [comment] 2015-04-30 00:26
Package has gone up to the main salt repository.

Should be available in a few minutes.

Cheers,

Joe

**Comment by jfindlay** [comment] 2015-04-30 15:44
Thanks, @joehealy!

**Comment by junster1** [comment] 2015-04-30 16:29
Thanks for taking the time to support on old os.   We are pushing to get off it as soon as we can, but would like to keep things as uniform as possible.

However, when testing this out I am getting these errors.

# dpkg -i salt-common_2014.7.5+ds-1lucid2_all.deb 
Selecting previously deselected package salt-common.
(Reading database ... 246384 files and directories currently installed.)
Unpacking salt-common (from salt-common_2014.7.5+ds-1lucid2_all.deb) ...
Setting up salt-common (2014.7.5+ds-1lucid2) ...

Processing triggers for man-db ...
Processing triggers for python-support ...
Compiling /usr/lib/pymodules/python2.6/salt/_syspaths.py ...
SyntaxError: ('invalid syntax', ('/usr/lib/pymodules/python2.6/salt/_syspaths.py', 2, 1, '. (Date from debian changelog)\n'))

Although it shows clean according to dpkg -l. 

# dpkg -l |grep salt
ii  salt-common                                       2014.7.5+ds-1lucid2                             shared libraries that salt requires for all 
ii  salt-minion                                       2014.7.5+ds-1lucid2                             client package for salt, the distributed rem


But when trying to run salt-call --versions, I get the following errors.  I tried installing salt-ssh, also doesn't include those libraries.

# salt-call --versions
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 7, in <module>
    from salt.scripts import salt_call
  File "/usr/lib/python2.6/dist-packages/salt/scripts.py", line 17, in <module>
  File "/usr/lib/python2.6/dist-packages/salt/cli/__init__.py", line 17, in <module>
  File "/usr/lib/python2.6/dist-packages/salt/client/ssh/__init__.py", line 143, in <module>
  File "/usr/lib/python2.6/dist-packages/salt/utils/__init__.py", line 1066, in fopen
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.6/dist-packages/salt/client/ssh/ssh_py_shim.pyc'

**Comment by joehealy** [comment] 2015-05-01 00:16
Thanks for the feedback - I'll look at getting another build up ASAP.

Thanks very much for testing these and the feedback.

I'm very keen to get a final "good" release up to launchpad before it shuts
off for lucid.

Cheers,

Joe

**Comment by joehealy** [comment] 2015-05-01 02:38
I've uploaded a new package to launchpad. This will have fixed the first
issue (the exception regarding _syspath).

It may have fixed the second issue as a result, but I'm not sure.

What version are you upgrading from as the exception following your
salt-call call is not from 2014.7.5 as line 1066 is not in fopen?

Can you please test and let me know how it goes - hopefully we can do this
while launchpad is still building for lucid.

cheers,

Joe

**Comment by joehealy** [comment] 2015-05-01 02:41
Looks like launchpad is now rejecting lucid builds. That is less than ideal.

I'll do a build on my own and host it at debian.saltstack.com - I'll let
you know when it is up (expecting this afternoon/over the weekend).

Cheers,

Joe

**Comment by joehealy** [comment] 2015-05-01 04:19
I haven't set up the hosting for the lucid packages yet, but they can be downloaded from
https://www.dropbox.com/s/92ldi8b8la50h6h/salt_2014.7.5%2Bds-1lucid3.tar.gz?dl=0
in the short term.

**Comment by junster1** [comment] 2015-05-01 04:55
That seems to have fixed the issue, thank you very much.

$ salt-call --versions 
                  Salt: 2014.7.5
                Python: 2.6.5 (r265:79063, Apr 16 2010, 13:57:41)
                Jinja2: 2.7.3
              M2Crypto: 0.22
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.1
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1lucid3

**Comment by joehealy** [comment] 2015-05-01 05:12
Great to hear - I'll get these hosted at debian.saltstack.com tonight.

**Comment by jfindlay** [comment] 2015-05-11 20:53
@junster1, do you think this issue can be closed now?

**Comment by dragon788** [comment] 2015-05-12 00:17
I can verify this works on a freshly built Ubuntu 10.04 machine whereas the version from ppa.launchpad.net/saltstack was failing horribly. Was actually just coming here to report the issue and was pleasantly surprised to see it fixed, and also a reason why I was unable to find it in the "usual places".

**Comment by joehealy** [comment] 2015-05-12 00:34
Great to hear. I'll delete the one from ppa.launchpad.net/saltstack as it
is broken and the debian.saltstack.com packages have been confirmed to work
by a real ubuntu user.

**Comment by junster1** [comment] 2015-05-12 00:49
Yes, I am happy with the current build, please close the ticket.  Thanks.

**Comment by svenehret** [comment] 2015-05-12 06:09
I installed the version from debian.saltstack.com and am not getting the one error anymore, but still the other one concerning missing libraries:

$ salt-minion -l info
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 6, in <module>
    from salt.scripts import salt_minion
  File "/usr/lib/python2.6/dist-packages/salt/scripts.py", line 17, in <module>
  File "/usr/lib/python2.6/dist-packages/salt/cli/__init__.py", line 17, in <module>
  File "/usr/lib/python2.6/dist-packages/salt/client/ssh/__init__.py", line 143, in <module>
  File "/usr/lib/python2.6/dist-packages/salt/utils/__init__.py", line 1066, in fopen
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.6/dist-packages/salt/client/ssh/ssh_py_shim.pyc'


$ dpkg -l |grep salt
ii  salt-common                     2014.7.5+ds-1lucid3                             shared libraries that salt requires for all 
ii  salt-minion                     2014.7.5+ds-1lucid3                             client package for salt, the distributed rem

**Comment by joehealy** [comment] 2015-05-12 06:17
What version are you upgrading from as the exception following your
salt-call call is not from 2014.7.5 as line 1066 is not in fopen?

Could that be left over from a manual install or from an earlier version?

**Comment by svenehret** [comment] 2015-05-12 06:30
it was version 2014.7.1:
```bash
Start-Date: 2015-05-12  08:56:36
Upgrade: salt-common (2014.7.1+ds-3lucid6, 2014.7.5+ds-1lucid2), salt-minion (2014.7.1+ds-3lucid6, 2014.7.5+ds-1lucid2)
End-Date: 2015-05-12  08:56:46
```
I tried purging both packets salt-common and salt-minion and reinstalling them afterwards, but the error stays.

**Comment by junster1** [comment] 2015-05-12 12:48
If you notice when you purge the 2014.7.1 package, it shows an error saying that /usr/lib/python2.6/dist-packages/salt/ is not empty, not removing.  That is what is causing this error.

If you simply remove the package and then remove that directory structure manually, the new package version installs and works cleanly.  I don't see it as an issue with the current package, more of an issue with the previous version.

**Comment by svenehret** [comment] 2015-05-12 12:52
true. Tried it and it works. Cheers!

**Comment by joehealy** [comment] 2015-05-12 12:56
Great to hear you have found a solution.

I think this issue can be closed.

thanks all.

**Comment by rallytime** [comment] 2015-05-12 15:44
Thanks everyone! Closing.

**Closed by rallytime** 2015-05-12 15:44 UTC
Labels: Feature, Fixed Pending Verification, Packaging

**Comment by dragon788** [comment] 2015-06-11 22:29
@junster1 Thanks for the tip. We had upgraded some minions from a much older version and on a couple hosts were having issues, removing the bad python salt dir fixed it.
