### ISSUE TITLE
file.append always results in change

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#35121] opened 2016-08-02 06:49 UTC
### Description of Issue/Question
While testing the 2016.3.2 package I noticed my file.append always triggers a change on my minions running 2016.3.2, not on those still running 2016.3.1!

### Setup
```yaml
######
## common.package.repo.pbd state
## -----------------------------------
## setup pkg.blackdot.be on SmartOS
######

## blackdot repository
{% if salt.grains.get('os', 'posix') == 'SmartOS' and salt.grains.get('virtual', 'physical') == 'zone' %}
package.repo.key::pkg.blackdot.be:
  file.managed:
    - name: /opt/local/etc/gnupg/keys/pbd.key
    - makedirs: true
    - source: salt://common/package/repo/_files/pbd-signature.key
  cmd.wait:
    - name: gpg --no-default-keyring --keyring /opt/local/etc/gnupg/pkgsrc.gpg --import /opt/local/etc/gnupg/keys/pbd.key
    - watch:
        - file: package.repo.key::pkg.blackdot.be

package.repo::pkg.blackdot.be:
  file.append:
    - name: /opt/local/etc/pkgin/repositories.conf
    - text: http://pkg.blackdot.be/packages/{{ salt.grains.get('pkgsrcversion') }}/x86_64/All
    - require:
        - cmd: package.repo.key::pkg.blackdot.be
  cmd.wait:
    - name: pkgin -fy up
    - watch:
        - file: package.repo::pkg.blackdot.be
{% endif %}

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
```

```yaml
          ID: package.repo::pkg.blackdot.be
    Function: file.append
        Name: /opt/local/etc/pkgin/repositories.conf
      Result: True
     Comment: File /opt/local/etc/pkgin/repositories.conf is in correct state
     Started: 08:44:04.391620
    Duration: 2.74 ms
     Changes:   
              ----------
              diff:
                  --- 
                  
                  +++ 
                  
                  @@ -5,7 +5,7 @@
                  
                   # Simply add repositories URIs one below the other
                   #
                   # WARNING: order matters, duplicates will not be added, if two
                  -# repositories hold the same package, it will be fetched from
                  +# repositories hold the same package, it will be fetched from 
                   # the first one listed in this file.
                   #
                   # This file format supports the following macros:
```
### Steps to Reproduce Issue
Snippet above, this one always triggers it.

### Versions Report
```yaml
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 6.0.1
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.5
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: 0.22
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, May  4 2016, 11:21:53)
   python-gnupg: 2.0.2
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.3
 
System Versions:
           dist:   
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed

```

**Comment by sjorge** [comment] 2016-08-02 07:11
resulting file encoded as base64 to make sure nothing gets managled in transport

```
IyAkSWQ6IHJlcG9zaXRvcmllcy5jb25mLHYgMS4zIDIwMTIvMDYvMTMgMTM6NTA6MTcgaW1pbGgg
RXhwICQKIwojIFBrZ2luIHJlcG9zaXRvcmllcyBsaXN0CiMKIyBTaW1wbHkgYWRkIHJlcG9zaXRv
cmllcyBVUklzIG9uZSBiZWxvdyB0aGUgb3RoZXIKIwojIFdBUk5JTkc6IG9yZGVyIG1hdHRlcnMs
IGR1cGxpY2F0ZXMgd2lsbCBub3QgYmUgYWRkZWQsIGlmIHR3bwojIHJlcG9zaXRvcmllcyBob2xk
IHRoZSBzYW1lIHBhY2thZ2UsIGl0IHdpbGwgYmUgZmV0Y2hlZCBmcm9tIAojIHRoZSBmaXJzdCBv
bmUgbGlzdGVkIGluIHRoaXMgZmlsZS4KIwojIFRoaXMgZmlsZSBmb3JtYXQgc3VwcG9ydHMgdGhl
IGZvbGxvd2luZyBtYWNyb3M6CiMgJGFyY2ggdG8gZGVmaW5lIHRoZSBtYWNoaW5lIGhhcmR3YXJl
IHBsYXRmb3JtCiMgJG9zcmVsZWFzZSB0byBkZWZpbmUgdGhlIHJlbGVhc2UgdmVyc2lvbiBmb3Ig
dGhlIG9wZXJhdGluZyBzeXN0ZW0KIwojIFJlbW90ZSBmdHAgcmVwb3NpdG9yeQojCiMgZnRwOi8v
ZnRwLm5ldGJzZC5vcmcvcHViL3BrZ3NyYy9wYWNrYWdlcy9OZXRCU0QvJGFyY2gvNS4xL0FsbAoj
CiMgUmVtb3RlIGh0dHAgcmVwb3NpdG9yeQojCiMgaHR0cDovL21pcnJvci1tYXN0ZXIuZHJhZ29u
Zmx5YnNkLm9yZy9wYWNrYWdlcy8kYXJjaC9EcmFnb25GbHktJG9zcmVsZWFzZS9zdGFibGUvQWxs
CiMKIyBMb2NhbCByZXBvc2l0b3J5IChtdXN0IGNvbnRhaW4gYSBwa2dfc3VtbWFyeS5neiBvciBi
ejIpCiMKIyBmaWxlOi8vL3Vzci9wa2dzcmMvcGFja2FnZXMvQWxsCiMKaHR0cDovL3BrZ3NyYy5q
b3llbnQuY29tL3BhY2thZ2VzL1NtYXJ0T1MvMjAxNVE0L3g4Nl82NC9BbGwKaHR0cDovL3BrZy5i
bGFja2RvdC5iZS9wYWNrYWdlcy8yMDE1UTQveDg2XzY0L0FsbAo=
```

**Comment by sjorge** [comment] 2016-08-02 12:24
Seems like adding a whitespace at the end of the line causes the line to always be marked as changed. See code comment above. I will try dig deeper when I have more time.

**Comment by sjorge** [comment] 2016-08-02 16:20
I have a patch,... rolling out internally now to see if it fixes it everwhere

**Comment by Ch3LL** [comment] 2016-08-03 20:46
@sjorge thanks for the PR. We will close this once the PR has been reviewed and looks like once the discussion over windows is resolved. Thanks!

**Comment by JaseFace** [comment] 2016-08-09 01:32
Just a note, this bug is present in 2016.3.1 also, confirmed the space at the end of the line triggers the results to believe something has changed, despite it really being a no-op.

**Closed** 2016-08-15 08:42 UTC
Labels: Bug, High Severity, P4, Platform, State Module
