### ISSUE TITLE
Orchestration run from scheduler throws tornado exception

### ISSUE THREAD

**Issue by clallen** [saltstack/salt#48639] opened 2018-07-18 02:37 UTC
We recently upgraded to 2017.7.7 from 2016.11.6, and there is a scheduled job that was working but now fails with this exception:
```
2018-07-17 21:32:47,839 [salt.state       :3279][CRITICAL][346] Rendering SLS 'base:orch.sparc_ovm.backup_spconfigs' failed: Traceback (most recent call last):
  File "/opt/apps/unix/salt/lib/python2.7/site-packages/salt/utils/templates.py", line 596, in py
    data = mod.run()
  File "/var/cache/salt/master/files/base/orch/sparc_ovm/backup_spconfigs.sls", line 6, in run
    caller = client.Caller()
  File "/opt/apps/unix/salt/lib/python2.7/site-packages/salt/client/__init__.py", line 2053, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/opt/apps/unix/salt/lib/python2.7/site-packages/salt/minion.py", line 650, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/opt/apps/unix/salt/lib/python2.7/site-packages/tornado/ioloop.py", line 576, in run_sync
    self.start()
  File "/opt/apps/unix/salt/lib/python2.7/site-packages/tornado/ioloop.py", line 930, in start
    raise RuntimeError("Cannot share PollIOLoops across processes")
RuntimeError: Cannot share PollIOLoops across processes
```
I created a test job that just calls client.Caller, and it fails the same way.
The SLS code I'm testing with (on my fileserver root as "test_sls/boom.sls"):
```python
#!py

from salt import client

def run():
  caller = client.Caller()
  return {}
```
To reproduce, call the above code from scheduler.  I'm using this config:
```
schedule:
    Testing exception:
        function: state.orch
        args:
          - test_sls.boom
        maxrunning: 1
        minutes: 5
```
I can run it from command line, no issues:
```
# salt-run state.orch test_sls.boom
test_master:

Summary for test_master
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
Total run time:  0.000 ms
```
Versions report:
```
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jul 10 2018, 14:46:38)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.1.6

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 4.1.12-124.15.2.el7uek.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

**Comment by Ch3LL** [comment] 2018-07-18 15:11
i'm having issues even running the orchestrator:

```
[root@f9111a6001df testing]# salt-run state.orchestrate test_sls.boom
[ERROR   ] Exception in callback <functools.partial object at 0x7fa940662b50>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 591, in _run_callback
    ret = callback()
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 342, in wrapped
    raise_exc_info(exc)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 313, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 597, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/testing/salt/crypt.py", line 510, in _authenticate
    io_loop=self.io_loop)
  File "/testing/salt/transport/client.py", line 108, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/testing/salt/transport/zeromq.py", line 130, in __new__
    obj.__singleton_init__(opts, **kwargs)
  File "/testing/salt/transport/zeromq.py", line 193, in __singleton_init__
    kwargs={'io_loop': self._io_loop})
  File "/testing/salt/transport/zeromq.py", line 907, in __init__
    super(AsyncReqMessageClientPool, self).__init__(AsyncReqMessageClient, opts, args=args, kwargs=kwargs)
  File "/testing/salt/transport/__init__.py", line 69, in __init__
    self.message_clients = [tgt(*args, **kwargs) for _ in range(sock_pool_size)]
  File "/testing/salt/transport/zeromq.py", line 954, in __init__
    self._init_socket()
  File "/testing/salt/transport/zeromq.py", line 1007, in _init_socket
    self.stream = zmq.eventloop.zmqstream.ZMQStream(self.socket, io_loop=self.io_loop)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 114, in __init__
    self._init_io_state()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 535, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self._state)
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 703, in add_handler
    self._impl.register(fd, events | self.ERROR)
TypeError: argument must be an int, or have a fileno() method.
```

is 2017.7.7 the master and minion version? Also is there a particular reason why you are using the `client.Caller()` class which is the same interface `salt-call` uses.

**Comment by clallen** [comment] 2018-07-18 19:01
Yes, both master and minions are at the same version.  I'm using client.Caller because we're gathering data from several minions and saving it on the master server itself.  
I'm open to a better way of doing it, but it's a little worrisome to even be having issues with such a basic operation.

If it helps, I compiled this build of Salt and its dependencies myself, since our IT infrastructure management requires us to use known fixed versions of everything.

**Comment by Ch3LL** [comment] 2018-07-19 12:40
ahh i think this might be a duplicate of https://github.com/saltstack/salt/issues/46905#issuecomment-405758480

you agree so we can close this issue and continue discussion there? it looks like pyzmq upgrade was one workaround, but we should be fixing it to work with both versions.

**Comment by Ch3LL** [comment] 2018-07-19 12:43
oh nevermind i just re-looked at your versions report and you have 17 for pyzmq, what about on the minions?

**Comment by clallen** [comment] 2018-07-19 12:49
The same build that the master has was distributed to the minions.  Although I don't think it's a master/minion issue because it's failing when trying to instantiate Caller on the master itself.
The thing that's really curious to me is that it only happens when running out of scheduler.

I notice in that other issue that the last comment says 17.1.0 and I'm using 17.0.0.  I'll try upgrading to that and see what happens.

**Comment by Ch3LL** [comment] 2018-07-19 12:52
yeah i think you might be right now that i look at your stack trace closer its not hitting zermomq. Now that i know what my stack strace error was let me try replicating with and updated pyzmq

**Comment by clallen** [comment] 2018-07-19 13:20
Right, I just tried it with pyzmq 17.1.0, same issue.

It seems to be happening in tornado, which now I recall an issue with tornado 5 and Salt being reported earlier this year.  However looking at the release notes, it should only affect builds based on python 3:
https://docs.saltstack.com/en/latest/topics/releases/2017.7.6.html

**Comment by Ch3LL** [comment] 2018-07-19 13:29
to note i did need to change `function: state.orch` to `function: state.orchestrate`

and my stack trace is:

```
/var/log/salt/minion:2018-07-19 13:09:14,529 [salt.utils.event                               :729 ][DEBUG   ][2373] Sending event: tag = __schedule_return; data = {'fun_args': ['test_sls.boom'], 'jid': 'req', 'return': {'outputter': 'highstate', 'data': {'b5872485b26d': ['Rendering SLS \'base:test_sls.boom\' failed: Traceback (most recent call last):\n  File "/testing/salt/utils/templates.py", line 596, in py\n    data = mod.run()\n  File "/var/cache/salt/minion/files/base/test_sls/boom.sls", line 6, in run\n    caller = client.Caller()\n  File "/testing/salt/client/__init__.py", line 2053, in __init__\n    self.sminion = salt.minion.SMinion(self.opts)\n  File "/testing/salt/minion.py", line 650, in __init__\n    lambda: self.eval_master(self.opts, failed=True)\n  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 439, in run_sync\n    self.start()\n  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 730, in start\n    raise RuntimeError("IOLoop is already running")\nRuntimeError: IOLoop is already running\n']}, 'retcode': 1}, 'retcode': 0, 'success': True, 'schedule': 'Testing exception', 'cmd': '_return', 'pid': 2373, '_stamp': '2018-07-19T13:09:14.528969', 'fun': 'state.orchestrate', 'id': 'b5872485b26d'}
```

**Comment by Ch3LL** [comment] 2018-07-19 13:30
also i tested with tornado 4.2.1 and 5 and still saw this

**Comment by zapetin52** [comment] 2019-07-22 01:39
Hi Everyone, actually i was using Python 2.7 (or 2.6), i uptaded to Python3
And its working fine :) 
The error was:
**RuntimeError: Cannot share PollIOLoops across processes**

Hope you fix your problem ;)

**Comment by twangboy** [comment] 2023-09-06 21:48
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!

**Closed by twangboy** 2023-09-06 21:48 UTC
Labels: Bug, severity-medium, Confirmed
