### ISSUE TITLE
Text on right sidebar overlapping on docs site

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#23858] opened 2015-05-18 15:28 UTC
The text on the side bar on the right is overlapping on some pages.

![screen shot 2015-05-18 at 11 25 32 am](https://cloud.githubusercontent.com/assets/3374962/7684004/d946167c-fd50-11e4-8883-833387876f27.png)

**Comment by rallytime** [comment] 2015-05-18 20:20
Thanks @nmadhok!

ping @jacobhammons

**Comment by jacobhammons** [comment] 2015-05-19 16:14
This is caused by some bad links on the 404.html page, we are tracking that issue in #23855.

**Comment by rallytime** [comment] 2015-05-19 16:42
Oh, is this a duplicate? Mind if we close this one in favor of #23855 @nmadhok?

**Closed** 2015-05-19 22:41 UTC
Labels: Bug, Documentation, Duplicate, High Severity, P1
