### ISSUE TITLE
[BUG] sqlite3 sdb module incorrectly returning bytes instead of strings

### ISSUE THREAD

**Issue by PaulChristophel** [saltstack/salt#61395] opened 2021-12-24 18:06 UTC
**Description**
In our environment, we are using the [postgres](https://docs.saltproject.io/en/latest/ref/returners/all/salt.returners.postgres.html) return module and the [sqlite3](https://docs.saltproject.io/en/latest/ref/sdb/all/salt.sdb.sqlite3.html#module-salt.sdb.sqlite3) sdb module. We are using the sdb module to obscure configuration data for things like external auth via ldap. Attempting to "get" strings from the sdb module using `salt-run sdb.get sdb://<path>` results in `TypeError: Object of type 'bytes' is not JSON serializable`. Additionally, the fact that the sqlite3 sdb module is returning byte strings causes things like ldap external authentication to break.

**Setup**
Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (vSphere)

```
/etc/salt/master.d/sqlsdb.conf:
sqlsdb:
  driver: sqlite3
  database: "/etc/salt/.sdb.sqlite"
  table: sdb
  create_table: True
```
  
**Steps to Reproduce the behavior**
1. Create the sqlsdb.conf noted above.
2. restart the salt-master
3. edit vim /lib/python3.6/site-packages/salt/sdb/sqlite3.py and alter the "get" function to return the type of the result.

```
def get(key, profile=None):
    """
    Get a value from sqlite3
    """
    if not profile:
        return None
    _, cur, table = _connect(profile)
    q = profile.get("get_query", "SELECT value FROM {} WHERE key=:key".format(table))
    res = cur.execute(q, {"key": key})
    res = res.fetchone()
    if not res:
        return None
    result = salt.utils.msgpack.unpackb(res[0])
    log.info(type(result))
    return result
```
4. Try to get an sdb.get secret

```
$> salt-run sdb.get  sdb://sqlsdb/example
[INFO    ] Executing command systemctl in directory '/root'
[INFO    ] Executing command systemctl in directory '/root'
[INFO    ] <class 'bytes'>
local:
    testing123
```

**Expected behavior**
I expect this behavior:
```
$> salt-run sdb.get  sdb://sqlsdb/example
[INFO    ] Executing command systemctl in directory '/root'
[INFO    ] Executing command systemctl in directory '/root'
[INFO    ] <class 'str'>
local:
    testing123
```

**Versions Report**
<details><summary>salt --versions-report</summary>
salt --versions-report
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.6.8 (default, Sep  9 2021, 07:49:02)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
Salt Extensions:
        SSEAPE: 8.4.2+4
 
System Versions:
          dist: rhel 8.5 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.2.1.el8_5.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.5 Ootpa
</details>

**Additional context**
I implemented a basic "fix" for this issue by changing the get function to:
```
def get(key, profile=None):
    """
    Get a value from sqlite3
    """
    if not profile:
        return None
    _, cur, table = _connect(profile)
    q = profile.get("get_query", "SELECT value FROM {} WHERE key=:key".format(table))
    res = cur.execute(q, {"key": key})
    res = res.fetchone()
    if not res:
        return None
    result = salt.utils.msgpack.unpackb(res[0])
    log.info(type(result))
    result = result if not isinstance(result, bytes) else result.decode('utf-8')
    log.info(type(result))                                                                                                                                                                                    
    return result
```

After doing this, ldap external authentication immediately starting working as expected, and the master was able to correctly return data to the postgres database.

**Comment by OrangeDog** [comment] 2022-01-05 16:35
Duplicate of #58533

**Closed by OrangeDog** 2022-01-05 16:35 UTC
Labels: Bug, needs-triage
