### ISSUE TITLE
funnel custom grain exceptions into minion log

### ISSUE THREAD

**Issue by alexykot** [saltstack/salt#35299] opened 2016-08-09 11:10 UTC
### Description of Issue/Question
Right now when you create custom grains, and an error of any kind happens within the grain python script - the salt-master call to `grains.get` silently returns nothing and no traces of the problem are left in neither master nor minion logs. The only way to see that the problem happens is to query custom grain locally from the minion itself with debug enabled via `salt-call -ldebug --local grains.get <custom_grain>`.

#### Good enough would be this:
1. write custom grain and install it on master.
2. sync it to minions.
3. call it from master.
4. it fails on minion.
5. failure and exception traceback are saved in minion log.

#### Even better would be this:
1. - 4. same.
5. failure and exception traceback are saved in minion log.
6. on master it returns an error saying that grain could not be executed and hinting to look into minion logs.

#### Ideal would be this:
1. - 4. same.
5. failure and exception traceback are saved in minion log.
6. on master it returns an error message, shows the backtrace of the error reference to actual grain .py file it helped in.

### Setup
I had a custom grain that referenced a python lib that was not installed, see details in #35079, and experienced this problem until @Ch3LL pointed out to test locally on the minion so I could see the actual issue.

### Versions Report
salt 2016.3.1 (Boron)
salt-minion 2016.3.1 (Boron)

**Comment by Ch3LL** [comment] 2016-08-09 16:41
@alexykot this is a duplicate of #33897 I will close this issue so we can track this feature request there. Please feel free to comment on that issue as well, so we can track on that issue. Thanks :+1:

**Closed by Ch3LL** 2016-08-09 16:41 UTC
