### ISSUE TITLE
[BUG] pkgrepo.managed doesn't account for architectures in test mode

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#57600] opened 2020-06-09 14:02 UTC
**Description**
When run in test mode on an apt system, `pkgrepo.managed` incorrectly determines that there would be changes if an architecture is defined.

**Setup**
```yaml
salt-repo:
  pkgrepo.managed:
    - name: deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main
    - file: /etc/apt/sources.list.d/saltstack.list
    - architectures: amd64
    - key_url: https://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub
```

**Steps to Reproduce the behavior**
```
# salt-call state.apply test=true
local:
----------
          ID: salt-repo
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main
      Result: None
     Comment: Package repo 'deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main' would be configured. This may cause pkg states to behave differently than stated if this action is repeated without test=True, due to the differences in the configured repositories.
     Started: 13:48:06.339543
    Duration: 93.91 ms
     Changes:
              ----------
              line:
                  ----------
                  new:
                      deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main
                  old:
                      deb [arch=amd64] http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main
----------
```

**Expected behavior**
After first application, no changes should be reported.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: 0.32.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-101-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Comment by frogunder** [comment] 2020-06-09 17:20
@OrangeDog Thanks for reporting this issue.

I am seeing the same thing.

Thanks.

**Comment by do3meli** [comment] 2021-01-26 11:20
this is not a new bug. i have already reported it a couple of years ago as #49894 and it just got never corrected the right way. i was unfortunately not able to test the old bug at the time the fix came out. 

@garethgreenaway as this seems to be assigned to you, what is the current status on it?

thanks & regards

**Comment by garethgreenaway** [comment] 2021-01-28 04:42
Apologies for the delay on this one but I did spend some time investigating it today.  The root of the issue is that when parse incoming `name` which ends up with the `uri` of the repo it doesn't contains the architecture but then entry on the system does contain the architecture, so they appear to be different.    Creating a SourceEntry object with the repo line and then updating the architecture attribute doesn't update the `line` attribute to include the architecture line.  This small patch is still a work in progress but does seem to fix the issue and includes the architecture information in the repo line.

```
diff --git a/salt/modules/aptpkg.py b/salt/modules/aptpkg.py
index 3a25f0b5c4..7fa84a1578 100644
--- a/salt/modules/aptpkg.py
+++ b/salt/modules/aptpkg.py
@@ -2553,6 +2553,13 @@ def expand_repo_def(**kwargs):
         if kwarg in kwargs:
             setattr(source_entry, kwarg, kwargs[kwarg])
 
+    source_list = sourceslist.SourcesList()
+    source_entry = source_list.add(type=source_entry.type,
+                                   uri=source_entry.uri,
+                                   dist=source_entry.dist,
+                                   orig_comps=kwargs.get("comps", []),
+                                   architectures=kwargs.get("architectures", []))
+
     sanitized["file"] = source_entry.file
     sanitized["comps"] = getattr(source_entry, "comps", [])
     sanitized["disabled"] = source_entry.disabled
```

**Closed** 2021-02-01 11:22 UTC
Labels: Aluminium, Bug, Community, phase-plan, severity-medium, status-in-prog
