### ISSUE TITLE
Orchestration runner, highstate and environment question

### ISSUE THREAD

**Issue by sokratisg** [saltstack/salt#40928] opened 2017-04-27 16:30 UTC
### Description of Issue/Question
Every time salt.orchestrate is called from the reactor, salt orchestrate applies all the states under "base" environment as listed in file top.sls. We are using a single top.sls file under base environment and it works fine if it is called via regular salt cli (e.g: salt 'minionA' state.highstate).

Someone would expect the salt.state orchestrate function for target "minionA" to apply all states (state1, state2 and state3) considering the pillar based targeting in file top file. "minionA" does have "role:production" set in its pillar data. Unfortunately **only state1 and state2 are run** when the salt.state orchestrate function runs.

Checked sat-master event bus (via salt-run state.event) and recorded the following call to state.orchestrate via the reactor system:
```
    "fun": "runner.state.orchestrate", 
    "fun_args": [
        [
            "orchestrate.minion.highstate" 
        ], 
        {
            "exclude": null, 
            "orchestration_jid": null, 
            "pillar": {
                "event_data": {
                    "_stamp": "2017-04-26T12:54:17.880661", 
                    "cmd": "_minion_event", 
                    "data": "Minion minionA started at Wed Apr 26 12:54:17 2017", 
                    "id": "minionA", 
                    "pretag": null, 
                    "tag": "salt/minion/minionA/start"
                }, 
                "event_tag": "salt/minion/minionA/start"
            }, 
            "pillarenv": null, 
            "saltenv": "base", 
            "test": null
        }
    ], 
```

I was quite sure this should be related to pillarenv being null but unfortunately I do not think this is the case. We are using just a single top.sls file under "base" environment and it is solely responsible of applying all states towards all other environments. For sake of readability I just included our "prod" environment in the setup details of this issue but we do also have "stag" and "dev" environments in the same salt-master setup.

This issue has also been reported on [google-groups salt-users list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/salt-users/hXjiIF8TvTw/dYzGOcsfBwAJ)

### Setup
Master config:
```
worker_threads: 20
max_open_files: 65535
job_cache: True
keep_jobs: 1
failhard: False
pillar_opts: False
pillar_safe_render_error: False
pillar_source_merging_strategy: recurse
pillar_merge_lists: True
pillarenv_from_saltenv: True
top_file_merging_strategy: merge
state_top_saltenv: base
state_auto_order: True
state_verbose: False
state_output: mixed
state_tabular: True

file_roots:
  base:
    - /opt/salt/files/base
  prod:
    - /opt/salt/files/prod

fileserver_backend:
  - roots

pillar_roots:
  base:
    - /opt/salt/pillars/base
  prod:
    - /opt/salt/pillars/prod
```
/opt/salt/files/base/top.sls:
```
base:
  '*':
    - state1
    - state2
prod:
  'I@env:production':
    - match: compound
    - state3
```

/opt/salt/pillars/base/top.sls
```
base:
  '*':
    - headers

prod:
  'minionA':
    - environment
```

/opt/salt/pillars/prod/environment.sls:
```
env: production
```

/etc/salt/master.d/reactor.conf:
```
reactor:
  - 'salt/minion/*/start':
    - /opt/salt/reactors/minion/start.sls
```

/opt/salt/reactors/minion/start.sls:
```
base.minion.onstart:
  runner.state.orchestrate:
    - mods:
        - orchestrate.minion.highstate
    - pillar:
        event_tag: {{ tag }}
        event_data: {{ data | json() }
```
/opt/salt/files/base/orchestrate/minion/highstate.sls;
```
{% set tag = salt.pillar.get('event_tag') %}
{% set data = salt.pillar.get('event_data') %}

run_minion_highstate:
  salt.state:
    - tgt: {{ data['id'] }}
    - highstate: True
    - queue: True
```

### Steps to Reproduce Issue
Just restarting salt-minion on "minionA" will trigger the reactor system which in turn will execute the orchestrate function.

### Versions Report
Salt Master
```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-696.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
 
```

Salt Minion
```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-642.4.2.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by gtmanfred** [comment] 2017-04-27 17:10
This is because you have `state_top_env: base` in the configuration.

Check the not in https://docs.saltstack.com/en/latest/ref/configuration/minion.html#std:conf_minion-state_top_saltenv

Specifically this line.

```
For instance, if top_file_merging_strategy is set to merge, and state_top_saltenv is set to foo, then any sections for environments other than foo in the top file for the foo environment will be ignored
```

Thanks,
Daniel

**Comment by sokratisg** [comment] 2017-04-27 18:12
Just tried again after commenting out ```state_top_env``` and had the same outcome.

**Comment by gtmanfred** [comment] 2017-04-27 18:25
Did you restart the master after you made the change?

**Comment by sokratisg** [comment] 2017-04-27 18:41
Of course.

Sent from a handheld device.

On 27 Apr 2017, at 21:26, Daniel Wallace <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you restart the master after you made the change?

**Comment by gtmanfred** [comment] 2017-04-27 22:16
I have been able to replicate this behavior.

```
$ docker run -ti --rm gtmanfred/issues:40928 bash
[root@15b039865dae /]# salt-master -d; salt-minion -d
[root@15b039865dae /]# salt self test.ping
self:
    True
[root@15b039865dae /]# ls -l /tmp
total 4
-rwx------ 1 root root 836 Apr  6 14:54 ks-script-MeHyWm
-rw------- 1 root root   0 Apr  6 14:52 yum.log
[root@15b039865dae /]# salt self state.apply
self:
22:10:32.772741 [4.26 ms]       file.touch      Changed   Name: /tmp/state1
22:10:32.777102 [0.311 ms]       file.touch      Changed   Name: /tmp/state2
22:10:32.777477 [0.287 ms]       file.touch      Changed   Name: /tmp/state3

Summary for self
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time:   4.858 ms
[root@15b039865dae /]# ls -l /tmp
total 4
-rwx------ 1 root root 836 Apr  6 14:54 ks-script-MeHyWm
-rw-r--r-- 1 root root   0 Apr 27 22:10 state1
-rw-r--r-- 1 root root   0 Apr 27 22:10 state2
-rw-r--r-- 1 root root   0 Apr 27 22:10 state3
-rw------- 1 root root   0 Apr  6 14:52 yum.log
[root@15b039865dae /]# rm -f /tmp/state*
[root@15b039865dae /]# salt-run state.orch deploy
15b039865dae_master:
22:10:55.317436 [381.486 ms]       salt.state      Changed   Name: run_minion_highstate

Summary for 15b039865dae_master
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 381.486 ms
[root@15b039865dae /]# ls -l /tmp/
total 4
-rwx------ 1 root root 836 Apr  6 14:54 ks-script-MeHyWm
-rw-r--r-- 1 root root   0 Apr 27 22:10 state1
-rw-r--r-- 1 root root   0 Apr 27 22:10 state2
-rw------- 1 root root   0 Apr  6 14:52 yum.log
```

It looks like the regular highstate behaves correctly, but when running it through the orchestrator it doesn't see the extra environment.

@terminalmage when you get a second you might be interested in this.  It is also worth noting that state_top_env does not appear to ignore the other environments in the specified environments top file, and instead still includes them.  (i moved the state_top_env to the minion config file since that is where it is in the documentation and still did not see a change in behavior)

Thanks,
Daniel

**Comment by terminalmage** [comment] 2017-05-03 16:24
@gtmanfred I think you misread the docs there. I will admit, they are a bit confusing and could probably be improved. What ``state_top_saltenv`` does is ignores top files from all other environments. Because the top file merging strategy remains unaffected, the behavior of making the ``base`` saltenv's states authoritative for any saltenv defined there means that we should be seeing all three states run.

This is actually being caused by a bug in state orchestration. There is a ``saltenv`` param which the ``salt.state`` orchestration jobs accept. This defaults to ``None``. That is, no specific saltenv, which means all targets from all saltenvs in the loaded top file(s) should be processed. But state orchestration jobs were ignoring this argument and instead using the magic dunder ``__env__``, which is always set to the effective saltenv (``base``, unless otherwise set). So, what ends up happening is the equivalent of running the highstate using ``saltenv=base``:

```
[root@0fd63a8b0009 ~]# salt self state.apply saltenv=base
self:
16:22:59.021354 [4.107 ms]       file.touch      Changed   Name: /tmp/state1
16:22:59.025569 [0.35 ms]       file.touch      Changed   Name: /tmp/state2

Summary for self
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:   4.457 ms
[root@0fd63a8b0009 ~]# ls -l /tmp/state?
-rw-r--r-- 1 root root 0 May  3 16:22 /tmp/state1
-rw-r--r-- 1 root root 0 May  3 16:22 /tmp/state2
```

https://github.com/saltstack/salt/pull/41036 fixes this.

**Comment by gtmanfred** [comment] 2017-05-03 16:26
Perfect, thanks for the explanation and fix.

Daniel

**Comment by cachedout** [comment] 2017-05-05 17:57
Looks like this has been resolved, therefore I am closing this. Thanks all.

**Closed by cachedout** 2017-05-05 17:57 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P3, State Compiler
