### ISSUE TITLE
Proxy minions: grains functions are started before proxy init()

### ISSUE THREAD

**Issue by jejenone** [saltstack/salt#27384] opened 2015-09-24 21:38 UTC
on 2015.8, it seems that grains functions are run before the proxy init() function. That renders impossible to retrieve grains from proxied device

```
[DEBUG   ] ----------- Trying to get facts
[DEBUG   ] LazyLoaded junos.facts
[CRITICAL] Failed to load grains defined in grain file junos.facts in function <function facts at 0x7fa371224758>, error:
Traceback (most recent call last):
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/loader.py", line 621, in grains
    ret = fun()
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/grains/junos.py", line 48, in facts
    facts = __opts__['proxymodule']['junos.facts']()
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/proxy/junos.py", line 43, in facts
    return thisproxy['conn'].facts
KeyError: 'conn'
[DEBUG   ] Opening connection to junos
[DEBUG   ] <SSHSession(session, initial daemon)> created: client_capabilities=['urn:ietf:params:netconf:capability:writable-running:1.0', 'urn:ietf:params:netconf:capability:rollback-on-error:1.0', 'urn:ietf:params:netconf:capability:validate:1.0', 'urn:ietf:params:netconf:capability:confirmed-commit:1.0', 'urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp', 'urn:ietf:params:netconf:base:1.0', 'urn:liberouter:params:netconf:capability:power-control:1.0', 'urn:ietf:params:netconf:capability:candidate:1.0', 'urn:ietf:params:netconf:capability:xpath:1.0', 'urn:ietf:params:netconf:capability:startup:1.0', 'urn:ietf:params:netconf:capability:interleave:1.0']
```

**Comment by jfindlay** [comment] 2015-09-25 15:32
@jejenone, thanks for the report.

@cro

**Comment by cro** [comment] 2015-09-25 16:30
@jejenone What Salt version is this?

**Comment by jejenone** [comment] 2015-09-25 17:04
2015.8.0

**Comment by cro** [comment] 2015-10-12 14:48
Ref #27731

**Comment by jejenone** [comment] 2015-10-12 18:30
That's a lot of interesting commits here! Thanks!

**Comment by rallytime** [comment] 2015-10-20 21:35
@jejenone Have you gotten a change to test the fix from @cro? Do you consider this issue resolved?

**Comment by jejenone** [comment] 2015-10-20 21:48
@rallytime I am running on latest 2015.8 and issue is not resolved. Grains collections are still started before the init() phase of the proxy minion.

**Comment by rallytime** [comment] 2015-10-20 22:04
@jejenone Just to clarify, are you running from the current HEAD of the branch, or from a release like 2015.8.0 or 2015.8.1?

The fix from @cro is only available from the HEAD of the 2015.8 branch. The reason I am asking is because in #27731, on [line 2541 of minion.py](https://github.com/saltstack/salt/pull/27731/files#diff-b5732eecf0273ccf6a96e1c720198dc6R2541) we're calling the init before setting the grains like so:
```
proxy_init_fn = self.proxy[fq_proxyname+'.init']
proxy_init_fn(self.opts)
self.opts['grains'] = salt.loader.grains(self.opts)
```
So I want to see if this is fixed or to see if this is broken in another way.

**Comment by cro** [comment] 2015-10-27 14:12
Closing for now, we believe this is fixed.  Feel free to reopen if that's not the case.

**Closed by cro** 2015-10-27 14:12 UTC
Labels: Bug, Fixed Pending Verification, Grains, High Severity, P3, Proxy Minion, RIoT

**Comment by jejenone** [comment] 2015-10-27 16:12
Sorry for late reply, we have a new problem where the __proxy__ object is not available in the grains module.

**Comment by cro** [comment] 2015-10-27 16:19
@jejenone Did you open a ticket for that?  I'll make sure we look at it asap.

**Comment by mirceaulinic** [comment] 2016-01-26 14:30
Actually there are two issues that might have the same root cause: in the grains the object \__proxy__ is not available:
```
NameError: global name '__proxy__' is not defined
```
And the grains are loaded **before** calling the init method from the proxy.
