### ISSUE TITLE
Minion ID globs are case-sensitive at the command line when one expects them to be case-insensitive a la DNS

### ISSUE THREAD

**Issue by xenophonf** [saltstack/salt#27062] opened 2015-09-11 16:31 UTC
Given a minion ID of `HOSTNAME.example.com`, the following will not work:

```shellsession
$ salt hostname.example.com test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

Likewise, Salt state or Pillar module assignments using minion ID globs in the corresponding top file _must_ match the case of the minion ID.  In nearly every other context hostnames get handled in a case-insensitive manner, e.g., DNS.

Note that Windows upcases hostnames by default.  I would rather not have to override the minion ID every time I install Salt on a Windows PC or server, especially since I want to deploy Windows images with a Salt minion pre-loaded.

**Comment by lorengordon** [comment] 2015-09-11 17:53
@xenophonf Possibly a duplicate issue of https://github.com/saltstack/salt/issues/8965. Also, there's a workaround in that issue using regex to force case insensitive matching. It would be nice if matching on minion id was case insensitive by default, though.

**Comment by jfindlay** [comment] 2015-09-11 21:53
Yes, this is a duplicate of that issue, but thanks for reporting anyway, @xenophonf, we need to get that fixed.

**Closed** 2015-09-11 22:04 UTC
Labels: Duplicate

**Comment by xenophonf** [comment] 2015-09-12 07:14
Ah, sorry for the dup.  I didn't see the older ticket in my searches.  And thanks for the workaround.  Regexps might be a better way to perform minion ID matches for my particular use case anyway (role and environment targeting based on fields in the minion ID).
