### ISSUE TITLE
salt-api cannot execute `runner`

### ISSUE THREAD

**Issue by krisoul** [saltstack/salt#41165] opened 2017-05-10 06:45 UTC
request:
```
curl -X POST -H "Content-Type: application/json" -H "X-Auth-Token: 6c0ea1829458556aaa16c9e28a0aa38c87a77369" -H "Cache-Control: no-cache"  -d '{
"client":"runner",
"fun":"manage.status",
 }' -k  "https://127.0.0.1:8888/"
```

return:
```
{"return": ["Exception occurred in runner manage.status: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 395, in _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: status() got an unexpected keyword argument '__current_eauth_groups'\n"]}
```

----
`salt --versions-report`

```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-514.6.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by krisoul** [comment] 2017-05-10 06:47
```client: "local"``` is ok
```client: "runner"``` error
```client: "wheel"``` error


help!!

**Comment by Ch3LL** [comment] 2017-05-10 14:01
This is a duplicate of https://github.com/saltstack/salt/issues/40845 Fix is here: https://github.com/saltstack/salt/pull/40894

**Closed by Ch3LL** 2017-05-10 14:01 UTC
