### ISSUE TITLE
modules/mount.py uses invalid arguments

### ISSUE THREAD

**Issue by liquidgecka** [saltstack/salt#24578] opened 2015-06-10 18:12 UTC
The call here:
https://github.com/saltstack/salt/blob/develop/salt/modules/mount.py#L699

Appears to disagree with the arguments here:
https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L4021

Hence, I get an error every time I try to mount a path that doesn't exist yet. =)

**Comment by arroyoc** [comment] 2015-06-12 19:46
@liquidgecka thanks for reporting. This is a duplicate of #24296, which has already been fixed on the head of 2015.5

**Closed by arroyoc** 2015-06-12 19:46 UTC
Labels: Duplicate
