### ISSUE TITLE
Report non existing or non existent minions when using list (salt -L)

### ISSUE THREAD

**Issue by Prakash82x** [saltstack/salt#48810] opened 2018-07-28 06:02 UTC
### Description of Issue/Question
When we submit any job on target minions using "salt -L" then it does not report any minion which does exist in the salt master. Can we have this feature ? this will help us lots of efforts while working on targets in bulk.

### Setup
We are targeting 5 minions below:
```
salt -L "minion1,minion2,minion3,minion4,minion5" test.ping
minion1:
    True
minion2:
    True
minion3:
    True
```

In the above result, minion4 and minion5 do not exist in salt and nothing is displayed about them. Can we have salt display a message stating minion4 and minion5 does not exist in salt. It is a much needed feature while we need to work with more minions at any given time.

### Steps to Reproduce Issue
It is a default behavior as of now.

**Comment by gtmanfred** [comment] 2018-07-30 14:06
What version of salt are you on, because this should be fixed in 2018.3.0

https://github.com/saltstack/salt/pull/42915

This appears to be a duplicate of https://github.com/saltstack/salt/issues/47852

**Closed by gtmanfred** 2018-07-30 14:06 UTC
