### ISSUE TITLE
Windows 2016.11.4 minion installer silent mode issue

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#41099] opened 2017-05-05 17:05 UTC
### Description of Issue/Question
Salt minion installer running in silent mode with a PATH environment variable > 1024 will hang.  When run in non-silent mode, a message box is displayed stating "PATH not updated, original length XXXX > 1024" (i.e. the cause of the apparent hang)

After clicking through the message box salt *seems* to run/function as expected.

1) Is the message a warning or an error that will affect something?
2) Should the /S switch continue on or fail the install instead of hanging

### Setup
Windows server with PATH environment variable longer than 1024 characters

### Steps to Reproduce Issue
install salt-minion in silent or non-silent mode

**Comment by gtmanfred** [comment] 2017-05-05 17:14
@twangboy can you take a look at this?

Thanks,
Daniel

**Comment by twangboy** [comment] 2017-05-05 23:09
This is a limitation with the NSIS installer. It is unable to handle variables larger than 1024. If the installer encounters this situation, it simply does not make changes to the path. Salt will function normally. If you need to run salt commands from the command line, you may need to add `C:\salt` to your path by hand. Otherwise you can ignore this.

I'll have to look at this for Silent Mode....

**Comment by twangboy** [comment] 2017-05-05 23:10
@cachedout Maybe a priority to get this fixed

**Comment by lorengordon** [comment] 2017-05-06 15:15
I wonder if I've been running into this also. I have not for the life of me been able to get salt 2016.11 (any version) to install silently in appveyor for CI testing of salt formulas. Works fine (seemingly) everywhere else I've tried it. Also, 2016.3 is fine in appveyor, so I've had to pin my CI tests to older versions. Been driving me crazy.

**Comment by twangboy** [comment] 2017-05-08 22:18
We may need to build our own version of the NSIS installer so that it will support strings up to 8192.

http://nsis.sourceforge.net/Special_Builds

**Comment by rickh563** [comment] 2017-05-09 23:34
ZD-1418

**Comment by twangboy** [comment] 2017-05-10 16:31
@cachedout We now have a ZD issue related to this....
1418

**Comment by twangboy** [comment] 2017-05-10 18:43
@rickh563 Just patched the 2016.11.5 installer to include this fix...

**Comment by lorengordon** [comment] 2017-05-10 18:54
@twangboy got a link? i don't see it in the repo yet, http://repo.saltstack.com/windows/. i'd be happy to test against appveyor really quick to see if this really is the same issue i was running into...

**Comment by twangboy** [comment] 2017-05-10 19:05
@lorengordon It's in staging since we haven't officially released...
https://repo.saltstack.com/staging/windows

**Comment by lorengordon** [comment] 2017-05-10 19:24
@twangboy Yep! That fixes the issue I was experiencing with appveyor! The install hangs when using 2016.11.4, and 2016.11.5 completes fine. 💥 🎆

**Comment by twangboy** [comment] 2017-05-10 21:21
@lorengordon Excellent! The PR has been merged and 2016.11.5 should be released sometime this week or next. Thanks for testing!

**Closed** 2017-05-10 21:22 UTC
Labels: Pending Discussion, Windows, ZD

**Comment by gaoweisgp** [comment] 2017-05-12 14:56
Tested the 'Salt-Minion-2016.11.5-AMD64-Setup.exe' on Helios10 (known issue with the PATH).
Here are the results

INSTALLATION
Manual install still shoots prompt, the prompt however is now worded:
"You may add C:\salt to the %PATH% for convenience when issuing local salt commands from the command line"
Clicking on the 'OK' button, finishes the installation, but the PATH variable is unchanged. (No salt addition)
Silent install completes with no pop-up, but PATH variable is unchanged. (No salt addition)

UNINSTALL
Both manual and Silent uninstall correctly

**Comment by twangboy** [comment] 2017-05-12 15:49
@gaoweisgp That is the intended behavior.

**Comment by gaoweisgp** [comment] 2017-05-12 17:42
@twangboy Thanks for the clarification
