### ISSUE TITLE
salt-ssh to localhost not working

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#47535] opened 2018-05-08 09:03 UTC
### Description of Issue/Question
salt-ssh as normal user to localhost does not work.

### Setup

I set up a python virtualenv as normal non-root user. 

Installed salt. Created symlinks (as root) from /etc/salt to my virtualenv.

Running salt-ssh to a remote system works.

### Steps to Reproduce Issue
```
===> salt-ssh localhost state.sls etckeeper
[ERROR   ] An Exception occurred while executing state.sls: [Errno 13] Permission denied: '/var/tmp/.root_483e1e_salt/running_data'
localhost:
    An Exception occurred while executing state.sls: [Errno 13] Permission denied: '/var/tmp/.root_483e1e_salt/running_data'
```

The same command work if I connect to a different host:

```
===> salt-ssh remote-host state.sls etckeeper
remote-host:
...
    Changes:   

Summary for remote-host
-------------
Succeeded: 13
Failed:     0
-------------
Total states run:     13
Total run time:   38.577 s
```

I think running salt-ssh on localhost is the most straight forward and simple way to learn salt-stack.

### Versions Report

```
===> salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-122-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
```

**Comment by Ch3LL** [comment] 2018-05-08 14:49
i'm not able to replicate this. might be a related or duplciate of https://github.com/saltstack/salt/issues/46891

was this working previously in 2017.7?

**Comment by guettli** [comment] 2018-05-09 10:32
@Ch3LL The client (ssh-salt) runs as non-root-user and the client connects to localhost as root.

I tried it with salt-2017.7.3, and yes, it works with the old version of salt.

**Comment by Ch3LL** [comment] 2018-05-09 16:54
ahh thanks for clarifying. I was not testing that exact scenario. I had the `user: <non-root>` in my roster file. Unfortunately I still am not able to replicate this. Can you share a sanitized version of your roster configuration? Or possibly provide a docker or vagrant machine that will allow us to quickly replicate this?

**Comment by mstarostik** [comment] 2018-11-21 22:31
Just stumbled over this.
Steps to reproduce:
* setup roster to include localhost with user root
* run salt-ssh as non-root

Apparently /var/tmp/.root_XXXXXX_salt is used on both the "master" (salt-ssh process, non-root) and the "minion" (what's run as root on the target). Using rand_thin_dir does not work around this, apparently the path for thin_dir is the same on both ends of the invokation:

$ cat ~/salt/config/roster
xps:
    host: localhost
    user: root

$ salt-ssh xps state.apply
[ERROR   ] An Exception occurred while executing state.apply: [Errno 13] Permission denied: '/var/tmp/.root_ea5a0f_salt/running_data'
xps:
    An Exception occurred while executing state.apply: [Errno 13] Permission denied: '/var/tmp/.root_ea5a0f_salt/running_data'

After removing /var/tmp/.root_ea5a0f_salt/ it works okay on different hosts, this problem is specific to the localhost case.

Tried with 2018.3.2 and 2018.3.3 with the same outcome

**Comment by guettli** [comment] 2019-02-07 14:00
For me it is the most simple and straight forward use case: Play and learn with salt by modifying localhost. 

It is very sad, that this simple use case gets ignored.

**Comment by Ch3LL** [comment] 2019-02-14 17:04
i see this as a clear duplicate of https://github.com/saltstack/salt/issues/46891

so i will close here and we will try to keep the conversation there so its in one issue

**Closed by Ch3LL** 2019-02-14 17:04 UTC
Labels: Info Needed
