### ISSUE TITLE
salt-ssh and --out json

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#27888] opened 2015-10-13 00:19 UTC
If you specify --out json with salt-ssh output would be not valid json, but rather concatenation of json outputs for each client. Parsing of this json requires additional processing. It would be great to have valid json there.

**Comment by jfindlay** [comment] 2015-10-14 18:54
@kt97679, thanks for the report.  This is a duplicate of #25154.  The note in the [documentation](https://docs.saltstack.com/en/latest/ref/cli/salt.html#cmdoption-salt--out) explains the need for using the `--static` option as well to ensure valid json as a whole.

**Closed by jfindlay** 2015-10-14 18:54 UTC
Labels: Duplicate
