### ISSUE TITLE
repo.saltstack.com contains only current latest release, should contain previous releases, too

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#27385] opened 2015-09-24 21:48 UTC
I see that only 2015.8.0 (the current latest release) is available in repo.saltstack.com. I would like to roll back to 2015.5.3, or at least 2015.5.5. The repo should contain at least a few prior releases.

**Comment by aboe76** [comment] 2015-09-25 12:49
Good, call, I would like to see this too, debian.saltstack.com had something like 
see http://debian.saltstack.com/
```
Available streams

The following streams are available:
lucid-saltstack
jessie-saltstack
jessie-saltstack-2014-01
jessie-saltstack-2014-07
jessie-testing
squeeze-saltstack
squeeze-saltstack-016
squeeze-saltstack-017
squeeze-saltstack-2014-01
squeeze-saltstack-2014-07
squeeze-testing
unstable
unstable-testing
wheezy-saltstack
wheezy-saltstack-016
wheezy-saltstack-017
wheezy-saltstack-2014-01
wheezy-saltstack-2014-07
wheezy-testing
```

**Comment by jfindlay** [comment] 2015-09-25 15:45
@ahammond, @aboe76, I have thought much about this and it would be nice to have.  The problem is that before 2015.8.0 packaging of salt was done in an ad-hoc manner, making it difficult to gather up all the packages and dependencies scattered across various repositories.  I am not opposed to doing this, but we will have to be sure they install and work.

Another issue to consider is whether we should put old packages into the same distro repositories or in an archived repository.  We'll have to make this decision at some point in the future anyway.  Something else that could be done, once we publish the package building states is that that should be theoretically enough to build packages against an arbitrary git tag.

We haven't done this or even considered it yet because we're overloaded with the package workload.  If anyone would like to help gather up previous releases, the help would be very appreciated.

**Comment by ahammond** [comment] 2015-09-25 19:01
epel has 2015.5.5 right now. If the package generation is automated, can you force a build for previous versions? If not, I'd say screw it and just keep new packages going forward.

**Comment by jfindlay** [comment] 2015-09-28 16:54
@ahammond, we can build packages at any git tag, but I am very wary of doing that and advertising them as official packages since the packaging process will have been different, resulting in subtly different packages.

**Comment by ahammond** [comment] 2015-09-28 17:11
I see what you mean. Personally I put on the cowboy boots and go for it,
maybe throw a caveat up there for those who care.

**Comment by arthurlogilab** [comment] 2015-11-10 14:57
Having wheezy is important for us too. There is also other people asking for this on the mailing list.

**Comment by tsaridas** [comment] 2015-11-17 14:54
+1 for wheezy please.

**Comment by blbradley** [comment] 2016-02-03 04:22
@jfindlay I can't downgrade salt without changing my apt repo URL to a specific archived version (i.e. http://repo.saltstack.com/apt/debian/8/amd64/archive/2015.8.3/). This is cumbersome especially if I have to change it on all minions (which may not be connecting to a master due to an upgrade). All released packages should be available from one repo for easy downgrading.

**Comment by babilen** [comment] 2016-02-03 05:47
It should be pointed out that Debian repositories are designed to only contain a single version. This means that the best way to implement this functionality is to provide a variety of repositories (or archives) that track different versions akin to the "streams" available on http://debian.saltstack.com. Debian itself provides http://snapshot.debian.org/ which contains all previously released versions.

**Comment by mrwboilers** [comment] 2016-02-03 20:29
I think what I might try to do then is to add the salt packages to my internal deb repo and just not use repo.saltstack.com. That seems like an easier way to maintain a consistent version (and only upgrade when I'm ready to.)

**Comment by usernkey** [comment] 2016-02-03 21:59
I report this info from another discussion.

You are actually able to pin on a release in the salt repo's for example, Redhat:
baseurl:=http://repo.saltstack.com/yum/redhat/7/x86_64/archive/2015.8.4

there are similar abilities for Debian and Ubuntu

The archive locations are not subject to change.

**Comment by blbradley** [comment] 2016-02-04 04:20
@usernkey Said who? Saltstack can change them at any time.

**Comment by vutny** [comment] 2016-02-04 11:17
@blbradley Nothing is eternal. Saltstack corporate repo provides all packages for current stable `2015.8` and old stable `2015.5` releases.
For example:
http://repo.saltstack.com/apt/debian/8/amd64/archive/
http://repo.saltstack.com/yum/redhat/7/x86_64/archive/

You can change the repository URLs by custom salt SLS for doing upgrades. As for me, unattended or manual upgrades/downgrades of Salt packages is not very reliable due to the role and nature of this software.

@ahammond I think this could be closed.

**Comment by warden** [comment] 2016-05-26 16:53
Actually I think that http://repo.saltstack.com/apt/*/...../archive/ is missing the index in this directory and then it would be fine.
Currently we need to add specific version to the sources file like:
http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2015.8.8.2/

**Comment by arthurlogilab** [comment] 2018-05-15 08:10
http://repo.saltstack.com/apt/debian/9/amd64/ and http://repo.saltstack.com/apt/debian/9/amd64/archive/ seem to have a bunch of packages, maybe this issue can be marked as fixed ?

**Comment by rallytime** [comment] 2018-05-15 13:35
Yeah, this can be closed. Thanks @arthurlogilab!

**Closed by rallytime** 2018-05-15 13:35 UTC
Labels: Feature, Packaging, Pending Discussion, Platform
