### ISSUE TITLE
salt.state.firewalld missing persist option

### ISSUE THREAD

**Issue by fenderle** [saltstack/salt#29641] opened 2015-12-11 21:41 UTC
Though `firewalld.present` (2015.8.3) manages to manage the runtime configuration, the changes are not persisted to the system configuration. Consequently a reboot reverts the changes which is most of the time not what is desired.

I propose to add the the following options to `firewalld.present`:
- **runtime** (default: `True`) - make changes to the runtime configuration
- **persist** (default: `True`) - make changes to the configuration on disk

Implementation details:
- **runtime** would execute the `firewall-cmd` command as currently implemented. 
- **persist** would add the `--permanent` option to the `firewall-cmd` command before execution.

Please be aware that `--permanent` will **not** change the runtime configuration until a reload of the firewall. I would advise against implementing a 'runtime and persist' configuration change using `firewall-cmd --permanent ...` followed by `firewall-cmd --reload` since this might reload changes from disk which are unwanted. So if the user requests `runtime: True` and `persist: True` actually two commands will be executed, whereof the 'persist' `firewall-cmd` call is identical to the 'runtime' `firewall-cmd` call, except it adds the `--permanent` option to the call.

**Comment by jfindlay** [comment] 2015-12-15 17:14
@fenderle, thanks for the report.  I think this is a duplicate of #29473, which will be fixed in 2015.8.4.

**Comment by cmercier** [comment] 2016-03-17 07:46
I would like to reopen the issue because it hasn't been implemented in the other issue which is now closed [#29473](https://github.com/saltstack/salt/issues/29473)
I can also try to work on it if needed, because right now I'm forced to do a reload of firewalld to be sure that the state is applied directly and will not be applied at the next restart of the service.
The current state is with `--permanent` option.
The philosophy is to be able to change the firewalld configuration without reloading.
Thanks

**Comment by jfindlay** [comment] 2016-03-18 19:31
@cmercier, any work you can do on this would be appreciated, thanks.

**Comment by cmercier** [comment] 2016-03-21 16:10
Ok i'm working on it already, it's good except for one thing which i don't understand. The original behavior is strange.

when i execute : 
`work:
      firewalld.present:
        - name: work
        - default: True
        - block_icmp:
          - echo-reply`

I get this result in debug mode : 
`work:
      firewalld.present:
        - name: work 
        - default: True
        - block_icmp:
          - echo-reply

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('work', OrderedDict([('firewalld.present', [OrderedDict([('name', 'work')]), OrderedDict([('default', True)]), OrderedDict([('block_icmp', ['echo-reply'])])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/firewalld_test/init.sls' using 'yaml' renderer: 0.00611996650696
[DEBUG   ] LazyLoaded firewalld.present
[INFO    ] Running state [work] at time 16:01:13.421225
[INFO    ] Executing state firewalld.present for work
[DEBUG   ] LazyLoaded firewalld.get_zones
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command '/usr/bin/firewall-cmd --get-zones' in directory '/home/admin'
[DEBUG   ] stdout: block dmz drop external home internal public trusted work
[INFO    ] Executing command '/usr/bin/firewall-cmd --get-icmptypes' in directory '/home/admin'
[DEBUG   ] stdout: destination-unreachable echo-reply echo-request parameter-problem redirect router-advertisement router-solicitation source-quench time-exceeded
[INFO    ] Executing command '/usr/bin/firewall-cmd --zone=work --list-icmp-blocks' in directory '/home/admin'
[INFO    ] Executing command '/usr/bin/firewall-cmd --get-icmptypes' in directory '/home/admin'
[DEBUG   ] stdout: destination-unreachable echo-reply echo-request parameter-problem redirect router-advertisement router-solicitation source-quench time-exceeded
[INFO    ] Executing command '/usr/bin/firewall-cmd --zone=work --list-icmp-blocks' in directory '/home/admin'
[INFO    ] Executing command '/usr/bin/firewall-cmd --zone=work --add-icmp-block=echo-reply' in directory '/home/admin'
[DEBUG   ] stdout: success
[INFO    ] Executing command '/usr/bin/firewall-cmd --get-default-zone' in directory '/home/admin'
[DEBUG   ] stdout: work
[INFO    ] Made the following changes:
'icmp_blocks' changed from 'absent' to ['echo-reply']

[INFO    ] Completed state [work] at time 16:01:14.143942
[DEBUG   ] File /var/cache/salt/minion/accumulator/139901636415760 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vps03.srv-test.milanamos.net', 'tcp://167.114.245.163:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'vps03.srv-test.milanamos.net', 'tcp://167.114.245.163:4506')
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: work
    Function: firewalld.present
      Result: True
     Comment: 'work' was configured.
     Started: 16:01:13.421225
    Duration: 722.717 ms
     Changes:   
              ----------                                                                                                                                                                                                                                                       
              icmp_blocks:
                  ----------
                  new:
                      - echo-reply
                  old:

Summary for local                                                                                                                                                                                                                                                              
------------                                                                                                                                                                                                                                                                   
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1`

This is the orignal behavior, so i don't understand why everything is executed twice for **firewall-cmd --get-icmptypes** and **firewall-cmd --zone=work --list-icmp-blocks**

Here is the code from /usr/lib/python2.7/dist-packages/salt/states/firewalld.py about this part of the state file : 
`if block_icmp:
        new_icmp_types = []
        try:
            _valid_icmp_types = __salt__['firewalld.get_icmp_types']()
            _current_icmp_blocks = __salt__['firewalld.list_icmp_block'](name)
        except CommandExecutionError as err:
            ret['comment'] = 'Error: {0}'.format(err)
            return ret

        for icmp_type in set(block_icmp):
            if icmp_type in _valid_icmp_types:
                if icmp_type not in _current_icmp_blocks:
                    new_icmp_types.append(icmp_type)
                    if not __opts__['test']:
                        try:
                            __salt__['firewalld.block_icmp'](name, icmp_type)
                        except CommandExecutionError as err:
                            ret['comment'] = 'Error: {0}'.format(err)
                            return ret
            else:
                log.error('{0} is an invalid ICMP type'.format(icmp_type))
        if new_icmp_types:
            ret['changes'].update({'icmp_blocks':
                                  {'old': _current_icmp_blocks,
                                   'new': new_icmp_types}})`

**Comment by cmercier** [comment] 2016-03-21 16:33
Ok i'm working on it already, it's good except for one thing which i don't understand. When everything will be good i will create a pull request

**Comment by cmercier** [comment] 2016-03-21 17:45
I have one fundamental question about the classical behavior of salt.
For example if I declare
```yaml
work:
    firewalld.present:
        - name: work
        - services: []
```
Are we supposed to remove all the services for the zone work ? Because usually it's more about adding new stuff but not remove the old ones.
Also for interfaces and sources (in firewalld.bind), it's removing everything which is not specified, but not for ports for example. 
Thanks for your answer about the normal behavior.

**Comment by cmercier** [comment] 2016-03-21 17:48
And my last question. The module has been developed my differents people so it's not always the same behavior in each function.

For example, in my mind we are not supposed to put verification in firewalld module like that : 
```python
def remove_source(zone, source, permanent=True):
    '''
    Remove a source bound to a zone

    .. versionadded:: Boron

    CLI Example:

    .. code-block:: bash

        salt '*' firewalld.remove_source zone 192.168.1.0/24
    '''
    if source not in get_sources(zone, permanent):
        log.info('Source is not bound to zone.')

    cmd = '--zone={0} --remove-source={1}'.format(zone, source)

    if permanent:
        cmd += ' --permanent'

    return __firewall_cmd(cmd)
```
The part with get_sources is strange for me, it's supposed to be in the state for me.

**Comment by jfindlay** [comment] 2016-03-21 19:26
@fenderle, I don't have strong opinions on the particular behaviors of the module as I've never used firewalld, but consistency seems like a good goal to have.  @dmyerscough, @whatevsz, do you have any opinions on this?

**Comment by whatevsz** [comment] 2016-03-21 19:58
Hi!

About the verification with `get_sources` in the module: I think this is necessary because the module might be used on its own, via `salt-call` or whatever, and should be able to report errors in that case. Also note that this check should never be triggered when used from the state module, relevant code from [states/firewalld.py](https://github.com/saltstack/salt/blob/d0ca640e6041e35b55890d70a35e25c2343fd32d/salt/states/firewalld.py#L324-L346):

```python
    try:
        _current_sources = __salt__['firewalld.get_sources'](name)
    except CommandExecutionError as err:
        ret['comment'] = 'Error: {0}'.format(err)
        return ret
    [...]
    for source in _current_sources:
        if source not in sources:
            old_sources.append(source)
            if not __opts__['test']:
                try:
                    __salt__['firewalld.remove_source'](name, source)
                except CommandExecutionError as err:
                    ret['comment'] = 'Error: {0}'.format(err)
                    return ret
```

Because `_current_sources` is populated by `get_sources()`, the check `if source not in get_sources(zone, permanent)` should always return false.

I don't know how such things are commonly handled in the rest of the source code, it just made sense to me at that time. I'm not at all adamant about keeping that behaviour, simply wanted to explain :smile:

About what to do when the state is given an empty list for `services`: I think it should remove all existing services. This way, the outcome of applying this state is always the same, and not dependant on the configuration of the system *before* the state was run, which I think is good behaviour for configuration management systems. Rather than imperative ("I want these services to also be allowed") it should be declarative ("I want *only* these services to be allowed."). Again, just my personal opinion.

Have a nice day!

**Comment by dmyerscough** [comment] 2016-03-21 21:19
I agree with @cmercier and @whatevsz we should make the modifications so that you have to be explicit. For example, an empty service list removes all services and if one service is added any pre-existing ones are removed.

**Comment by cmercier** [comment] 2016-03-22 09:14
I also agree for the empty list with all of you @dmyerscough @whatevsz . I will do that so.
@whatevsz, I understand your idea for the check in sources.
Is it strange for you @whatevsz  if I migrate _sources_ and _interfaces_ in **firewalld.present** ? So that you can define your zone entirely in one declaration and not with both **present** and **bind**
I will create a pull request soon so you will be able to review my code. I focused on consistency and mainly on permanent and runtime. I corrected all the checks made in runtime mode even if the execution was with permanent=True.

**Comment by whatevsz** [comment] 2016-03-22 13:08
There was never a real reason to separate state logic between `present` and `bind`, I simply did it because that meant I didn't have to touch `present`. So my point of view it's fine to merge `bind` into `present` if you want. And consistentcy with permanent/runtime config sounds awesome, this has always been a bit of an issue with firewalld!

**Comment by cmercier** [comment] 2016-03-24 13:18
#32120

**Comment by cmercier** [comment] 2016-03-25 09:54
Tests are failing, any idea why ? @jfindlay 
Honestly I'm not used to that and I don't find the reason in this amount of data, even if I looked for it.

**Comment by jfindlay** [comment] 2016-03-25 16:56
@cmercier, yes, the test results can be confusing.  There are some firewalld unit tests that need to be updated, that are listed on this page: http://166.78.178.63:8080/job/PR/job/salt-pr-linode-ubuntu14-n/251/#showFailuresLink and some lint errors here: http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/544/violations/.  Ping me if you need help working through any of those.

**Comment by cmercier** [comment] 2016-04-01 06:47
@jfindlay You can close the issue, the PR has been accepted, so problem solved.

**Closed** 2016-04-01 15:33 UTC
Labels: Execution Module, Feature, Platform, State Module
