### ISSUE TITLE
gem.installed upgrade hangs indefinitely awaiting keyboard input

### ISSUE THREAD

**Issue by feltech** [saltstack/salt#44623] opened 2017-11-21 15:36 UTC
### Description of Issue/Question
We had a case where a highstate had hung indefinitely with no output.  On checking the process tree we saw that salt was running gem.  On terminating the gem process, salt spat out
```
[ERROR   ] Command '['/opt/sensu/embedded/bin/gem', 'install', 'sensu-plugins-couchdb', '--version', '2.0.0', '--no-rdoc', '--no-ri']' failed with return code: -15
[ERROR   ] stdout: sensu-plugins-couchdb's executable "check-couchdb-alive.rb" conflicts with /opt/sensu/embedded/bin/check-couchdb-alive.rb
Overwrite the executable? [yN]
[ERROR   ] retcode: -15
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1733, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1652, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/states/gem.py", line 108, in installed
    source=source):
  File "/usr/lib/python2.6/site-packages/salt/modules/gem.py", line 138, in install
    runas=runas)
  File "/usr/lib/python2.6/site-packages/salt/modules/gem.py", line 66, in _gem
    raise CommandExecutionError(ret['stderr'])
CommandExecutionError
```
Note the stdout indicating it was requesting keyboard input.  We could reproduce the keyboard prompt by running in the command line.

Related / potential solutions: https://github.com/saltstack/salt/issues/14504 https://github.com/saltstack/salt/issues/15325 ; this problem specifically was not reported in those, so I thought it best to make a new issue.

### Setup
The state looks like
```
sensu_gem_sensu-plugins-couchdb:
  gem.installed:
    - name: sensu-plugins-couchdb
    - version: 2.0.0
    - gem_bin: {{ sensu.gem_bin | yaml_encode }}
```
The `gem_bin` version is
```
$ /opt/sensu/embedded/bin/gem --version
2.6.7
```
### Versions Report
**Minion**
```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 4.3.3-1.el6.elrepo.x86_64
         system: Linux
        version: CentOS 6.9 Final
```
**Master**
```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.8.0-53-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment] 2017-11-21 17:00
Hrm, after looking at the other reports, unless there is a way to just tell gem to do whatever it wants like `-y` then I think we should close this as a duplicate of the feature request here #15325

Let me know if that is possible.

Thanks!
Daniel

**Comment by feltech** [comment] 2017-11-24 11:46
That sounds reasonable to me, as long as the priority of #15325 is high enough, as appropriate for the severity of this issue.

**Comment by gtmanfred** [comment] 2017-11-27 16:25
So, the work around is to just uninstall the gem first, and then install the new version.

I would love to see a PR that adds this upgrade feature and handles these things for us, but it will probably need to be a community contribution.

THanks,
Daniel

**Comment by gtmanfred** [comment] 2017-11-27 16:26
Duplicate of https://github.com/saltstack/salt/issues/15325

**Closed by gtmanfred** 2017-11-27 16:25 UTC
Labels: Bug, Core, Execution Module, High Severity, team-core
