### ISSUE TITLE
table outputter failing due to str/unicode

### ISSUE THREAD

**Issue by wasabi222** [saltstack/salt#47910] opened 2018-05-31 12:39 UTC
### Description of Issue/Question

when calling `--out table` in 2018.3.0, I receive the following traceback (full command follows):

```
root@master:/srv/pillar# salt-run net.find ge --out table
Pattern "ge" found in the description of the following interfaces
Details for interface ge
Details for all interfaces on device ge
Pattern "ge" found in one of the following LLDP details
LLDP Neighbors for interface ge
LLDP Neighbors for all interfaces on device ge
MAC Address(es) on device ge
MAC Address(es) on interface ge
ARP Entries on device ge
[ERROR   ] Nested output failed:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/output/__init__.py", line 47, in try_printout
    printout = get_printout('nested', opts)(data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/table_out.py", line 370, in output
    labels_key=labels_key))
  File "/usr/local/lib/python2.7/dist-packages/salt/output/table_out.py", line 293, in display
    out.extend(self.display_rows(rows, labels, indent))
  File "/usr/local/lib/python2.7/dist-packages/salt/output/table_out.py", line 250, in display_rows
    return self.prepare_rows(labels_and_rows, indent + 4, has_header)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/table_out.py", line 187, in prepare_rows
    ]) + self.suffix
TypeError: descriptor 'center' requires a 'str' object but received a 'unicode'
```

versions:

```
root@master:/srv/pillar# salt --versions-report
Salt Version:
           Salt: 2018.2.0-50-g47bdea2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6

System Versions:
           dist: debian 9.4
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

**Comment by Ch3LL** [comment] 2018-05-31 13:28
duplicate of https://github.com/saltstack/salt/issues/47587 which is fixed in https://github.com/saltstack/salt/pull/47674

**Closed by Ch3LL** 2018-05-31 13:29 UTC
