### ISSUE TITLE
[BUG] onchanges_any (without changes) + prereq causes RecursionError

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#60641] opened 2021-07-28 22:07 UTC
**Description**
A state, which:
- has a `prereq` reference from another state emitting a change
- has an `onchanges_any` requisite on two other states emitting no changes

...causes `RecursionError: maximum recursion depth exceeded while calling a Python object`

Before being shrunk down to a minimal test-case, this was originally used for an image building process, where:
- `bug-file-A` and `bug-file-B` provided input files for the build
- `bug-remove-outdated-build` ensured an existing image file is removed first in case the build is executed again
- `bug-create-build` is the actual build process, which is triggered via `onchanges_any` by any changes to the input files

**Setup**
Create the file `bug.sls` with the following content:
```SaltStack
bug-file-A:
  test.succeed_without_changes

bug-file-B:
  test.succeed_without_changes

bug-remove-outdated-build:
  test.succeed_with_changes:
    - prereq:
      - bug-create-build

bug-create-build:
  test.succeed_without_changes:
    - onchanges_any:
      - bug-file-A
      - bug-file-B
```

**Steps to Reproduce the behavior**
Execute `salt-call state.template bug.sls`

<details><summary>The result will be a `RecursionError` preceded by the following debug output:</summary>

```
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003.1', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 112, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 219, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 584, in template
    ret = st_.state.call_high(high_state)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 3269, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2495, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2991, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2991, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2991, in call_chunk
    running = self.call_chunk(low, running, chunks)
  [Previous line repeated 971 more times]
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2856, in call_chunk
    low = self._mod_aggregate(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 852, in _mod_aggregate
    agg_opt = self.functions["config.option"]("state_aggregate")
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2282, in _run_as
    current_loader = salt.loader_context.loader_ctxvar.get()
RecursionError: maximum recursion depth exceeded while calling a Python object
```
</details>

**Expected behavior**
A successful execution of all states.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: 8.9.1
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-80-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**
Related issues, but under slightly different conditions and/or resulting in different tracebacks:
- #47154
- #50811 
- #56133
- #56822

**Comment by waynew** [comment] 2021-08-17 17:10
Hey @eliasp thanks for the report! This looks like it should be pretty straightforward to repro, hopefully I can get to it today :+1:

**Comment by waynew** [comment] 2021-08-24 17:04
Yep. That blows right on up, exactly as reported! :joy:

**Comment by waynew** [comment] 2021-08-24 17:16
Darn. I remembered working on something here recently - turns out it was https://github.com/saltstack/salt/pull/57103 -  and hoped it was related but reader, it was not related.

**Comment by waynew** [comment] 2021-08-24 18:23
I'm not 100% sure, but I *think* something is going wrong in the `check_requisites`. All of the requisites are completed for `bug-remove-outdated-build`, yet it's still using `self.pre` as the run_dict which seems... off :thinking: 

At the very least we should be detecting a cycle here, if not just fix this entirely, because I'm pretty sure it can be fixed :suspect:

**Comment by lkubb** [comment] 2022-06-27 16:17
Just stumbled into the other side of this bug: `prereq` on a state that runs `onchanges` in a state without changes causes this as well.

```sls
This does not change:
  file.absent:
    - name: /tmp/nonexistent

Only run onchanges:
  cmd.run:
    - name: /usr/bin/true
    - onchanges:
      - file: /tmp/nonexistent

Prerequisite for onchanges causes recursion exception:
  cmd.run:
    - name: /usr/bin/true
    - prereq:
      - Only run onchanges
```

The state compiles and runs normally once after running `touch /tmp/nonexistent` (aka with changes on the file state).

**Comment by twangboy** [comment] 2023-08-31 22:29
Duplicate of https://github.com/saltstack/salt/issues/47154

**Closed by twangboy** 2023-08-31 22:29 UTC
Labels: Bug, Duplicate
