### ISSUE TITLE
dockerng.running downloads images in test=true

### ISSUE THREAD

**Issue by p-thurner** [saltstack/salt#36587] opened 2016-09-27 00:52 UTC
### Description of Issue/Question

When I run dockerng.running in test=true it does things instead of saying that it would do things - it seems to download docker images for instead of just saying that it would do so.
Btw why does it download at all? I thought dockerng.image_present does this? Shouldnt dockerng.running fail if the image isnt present?

First run:

```
          ID: rancher_server_container
    Function: dockerng.running
        Name: rancher-server
      Result: None
     Comment: Container 'rancher-server' will be created
     Started: 00:45:26.067037
    Duration: 39270.397 ms
     Changes:   
              ----------
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - b171f9dbc13b
                          - ed40d4bcb313
                          - 96c6a1f3c3b0
                          - ccfc4df4fbba
                          - 9e4d5a1238bb
                          - f986ba0d224d
                          - 303d9649bb89
                          - 86a35696481e
                          - 56825bfb5bb7
                          - fabbcc718243
                          - eb2848176ff4
                          - 35489637da84
                          - 5c005e2df0e8
                          - 64ba16c4c9f4
                  Status:
                      Downloaded newer image for rancher/server:stable
                  Time_Elapsed:
                      39.2294640541
```

Second run:

```
          ID: rancher_server_container
    Function: dockerng.running
        Name: rancher-server
      Result: None
     Comment: Container 'rancher-server' will be created
     Started: 00:47:27.581069
    Duration: 10.533 ms
     Changes:  
```
### Setup

I used this state:

/srv/salt/test-container-running-issue.sls:

```
rancher_server_container:
  dockerng.running:
    - name: rancher-server
    - image: rancher/server:stable
    - environment:
      - CATTLE_DB_CATTLE_MYSQL_HOST: test
      - CATTLE_DB_CATTLE_MYSQL_PORT: test
      - CATTLE_DB_CATTLE_MYSQL_NAME: test
      - CATTLE_DB_CATTLE_USERNAME: test
      - CATTLE_DB_CATTLE_PASSWORD: test
    - port_bindings:
      - http://127.0.0.1:8080
    - restart_policy: always
#    - require:
#      - dockerng: rancher_server_image
```
### Steps to Reproduce Issue

salt 'testserver' state.sls 
### Versions Report

Both master and minion are  2016.3.3 (Boron) on Debian 8.

**Comment by cachedout** [comment] 2016-09-27 06:20
Hi @p-thurner. Very interesting.

@ticosax Do you have a moment to look at this and provide any insight?

**Comment by ticosax** [comment] 2016-09-28 07:50
> When I run dockerng.running in test=true it does things instead of saying that it would do things - it seems to download docker images for instead of just saying that it would do so.

I can see that test mode is not implemented for `dockerng.running`, and probably many others.

> Btw why does it download at all? I thought dockerng.image_present does this? Shouldn't dockerng.running fail if the image isn't present?

You can have some explanation about this behavior from #29727.
My guess is that it makes the state behaving closer to docker's client: `docker run ...` which is an expected behavior by some of the users. Personally I prefer using `dockerng.image_present` because the error message in case of failure is clearer and it helps managing requisites.

**Comment by zerthimon** [comment] 2016-09-28 16:09
+1
Just ran into the same issue.

**Comment by p-thurner** [comment] 2016-09-28 16:43
> Personally I prefer using dockerng.image_present because the error message in case of failure is clearer and it helps managing requisites.

I have an dockerng.image_present state before that state - however if I execute my formula with test=true, the image_present state behaves as expected, however it is followed by the dockerng.running state - which then downloads the image on test=true ;)

In my opinion the state should behave like the a pkg.installed state that cant find a certain package when run in test=true. The user may have provided a pkgrepo.managed state before that state that has never been run yet. pkgrepo.managed tells you this, and pkg.installed fails as expected at this point.

I think thats ok, as test=true is not designed to predict the future :)

``
Comment: Package repo 'saltstack' will be configured. This may cause pkg states to behave differently than stated if this action is repeated without test=True, due to the differences in the configured repositories.
``

**Comment by terminalmage** [comment] 2017-11-22 06:47
This has been fixed for some time. Marking as closed.

**Closed by terminalmage** 2017-11-22 06:47 UTC
Labels: Bug, High Severity, P2, Platform, State Module
