### ISSUE TITLE
file.copy force ignored during highstate, but not with 'salt-call state.sls_id'

### ISSUE THREAD

**Issue by naemono** [saltstack/salt#23714] opened 2015-05-14 14:43 UTC
During highstate, force is ignored:

```
     Comment: The target file "/home/deploy/.env" exists and will not be overwritten
```

State below

```yaml
bash_app_env:
  file.managed:
    - name: /home/deploy/.bash_app_env
    - source: salt://application-base/autoscale-base/deployment-user/bash_app_env
    - template: jinja
    - user: deploy
    - group: deploy
    - mode: 0644

formatappenv:
  file.replace:
    - name: /home/deploy/.bash_app_env
    - pattern: '^\s*$'
    - repl: ''
    - backup: False
    - require:
      - file: bash_app_env

removeblanklinesappenv:
  cmd.run:
    - name: "sed -i.bak '/^$/d' /home/deploy/.bash_app_env"
    - user: deploy
    - shell: /bin/bash
    - require:
      - file: formatappenv

createENV:
  file.copy:
    - name: /home/deploy/.env
    - source: /home/deploy/.bash_app_env
    - user: deploy
    - group: deploy
    - force: True
    - require:
      - cmd: removeblanklinesappenv
```

But run with 'salt-call state.sls_id', it functions as expected:

```yaml
     local:
----------
          ID: bash_app_env
    Function: file.managed
        Name: /home/deploy/.bash_app_env
      Result: True
     Comment: File /home/deploy/.bash_app_env updated
     Started: 14:32:44.099434
    Duration: 28.466 ms
     Changes:

          ID: formatappenv
    Function: file.replace
        Name: /home/deploy/.bash_app_env
      Result: True
     Comment: Changes were made
     Started: 14:32:44.132742
    Duration: 4.311 ms

          ID: removeblanklinesappenv
    Function: cmd.run
        Name: sed -i.bak '/^$/d' /home/deploy/.bash_app_env
      Result: True
     Comment: Command "sed -i.bak '/^$/d' /home/deploy/.bash_app_env" run
     Started: 14:32:44.140639
    Duration: 126.497 ms
     Changes:
              ----------
              pid:
                  16113
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: createENV
    Function: file.copy
        Name: /home/deploy/.env
      Result: True
     Comment: Copied "/home/deploy/.bash_app_env" to "/home/deploy/.env"
     Started: 14:32:44.269203
    Duration: 4.918 ms
     Changes:
              ----------
              /home/deploy/.env:
                  /home/deploy/.bash_app_env
              group:
                  deploy
              user:
                  deploy

Summary
------------
Succeeded: 4 (changed=4)
Failed:    0
------------
Total states run:     4
```

Versions

```yaml
deploy@prd-app-050521:~$ salt-call --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

**Comment by naemono** [comment] 2015-05-14 14:48
Nevermind... it's totally inconsistent... 

Now the sls_id is showing this after running a highstate:

```
          ID: createENV
    Function: file.copy
        Name: /home/deploy/.env
      Result: True
     Comment: The target file "/home/deploy/.env" exists and will not be overwritten
     Started: 14:47:19.610031
    Duration: 2.774 ms
     Changes:
```

What gives?  Is this a regression?

**Comment by rallytime** [comment] 2015-05-20 05:09
Hrm...I'm not sure. Can you elaborate of what you mean by "it's totally inconsistent"? Is the salt-call now failing where it wasn't before? Can you reproduce this consistently? For example, does it fail on the first attempt, but succeed on the second or anything like that?

**Comment by sambanshee** [comment] 2015-05-20 12:46
I did not verify the second part of the report, however for me in 2015.5.0 on CentOS 6.6 x64 "-force: True" does not have any effect on copying file. File is not copied - both under higshtate and state.sls

Salt: 2015.5.0
Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
Jinja2: 2.2.1
M2Crypto: 0.20.2
msgpack-python: 0.4.6
msgpack-pure: Not Installed
pycrypto: 2.0.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.3.1
RAET: Not Installed
ZMQ: 3.2.4
Mako: Not Installed

**Comment by sambanshee** [comment] 2015-05-20 12:48
For me it fails on all attempts, rerunning state does not help.

**Comment by naemono** [comment] 2015-05-20 14:42
I think the point here is that the force: True simply isn't working on file.copy.  

I get this:

```
     Comment: The target file "/home/deploy/.env" exists and will not be overwritten
```

I think I may have muddied the waters with the inconsistently comment.  Let's just say that highstates running file.copy with force, and not overwriting the files...consistently not overwriting the files.

**Comment by rallytime** [comment] 2015-05-20 15:09
Ok, that makes more sense. Thanks for the extra details!

**Comment by cro** [comment] 2016-04-21 00:36
Actually, in 2016.3 and 2015.8 it looks like no matter what (`state.sls`, `state.single`, `state.highstate`), `force=True` is ignored.

**Comment by lomeroe** [comment] 2016-04-21 00:46
@cro check out #32732

**Comment by cro** [comment] 2016-04-21 01:03
I think this appeared inconsistent because, even when `force=True` we were not overwriting the file if the source and target hashes were identical.  The PR by @lomeroe above will overwrite the file even if the hashes match.

**Comment by lomeroe** [comment] 2016-04-21 01:13
local testing seems 2015.5.2 worked like the above PR, 2015.5.8 does not

I can back port the fix if it is good in develop....

**Comment by rallytime** [comment] 2016-04-25 19:56
@lomeroe That would be great. Thanks!

**Comment by lomeroe** [comment] 2016-04-25 23:37
@rallytime backport PRs inbound, I don't believe 2014.7 suffers from the issue after review...

**Comment by rallytime** [comment] 2016-04-26 14:44
Thanks for doing these backports @lomeroe!

@naemono This bug should be fixed in the next releases of salt, on all current release branches. Can you confirm that this bug is fixed for you so we can close this issue?

**Closed** 2016-04-29 15:37 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P2, Platform, State Module

**Comment by dneades** [comment] 2016-05-20 07:33
With this change in place, it seems that adding `force: True` will always copy the file, regardless of whether the source and destination are already identical. This means that the `file.copy` state always results in a change when `force: True` is used.

If `force: True` is not present, then my understanding is that the destination will not be replaced even if it differs from the source.

Assuming the above is correct, how does one now use `file.copy` to copy a file *only* if the destination does not exist or differs from the source?

**Comment by lomeroe** [comment] 2016-05-20 17:33
If 'force: True' is not present, the file will be copied only if it doesn't exist.  This should match the documentation [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.copy) (though "moved" should probably be replaced with "copied" in the doc string, otherwise it is accurate)

The force flag will cause file.copy to always copy the file, if the destination exists, doesn't exist, or even if it hash matches the source.

Other than having the preserve option for user/group/mode settings, file.managed could possibly be used to do what you want.  This would only change /etc/localtime if it didn't match /usr/share/zoneinfo/UTC.  You'd have to explicitly set the user/group/mode you want...

```
/etc/localtime:
  file.managed:
    - source: /usr/share/zoneinfo/UTC
```

I suppose an "update" option could be added that would copy the file if the source and destination didn't match, but then you're very close to just having another "file.managed" (in my opinion).  Or maybe file.managed needs a preserve option for locally sourced files, if that is your reason for not using it...

**Comment by dneades** [comment] 2016-05-23 08:58
@lomeroe, thank you for the detailed response. I should be happy to use `file.managed`, and indeed that is what I was going to use first. However, the documentation for the `file.managed` `source` argument says:

> The source file to download to the minion, this source file can be hosted on either the salt master server, or on an HTTP or FTP server.

That led me to believe that a local source is not possible (only a file hosted on the salt master, or an HTTP or FTP server), which is why I went hunting for an alternative (and found `file.copy`) in the first place.

If local-to-the-minion files are indeed possible with `file.managed`, then that is a perfectly acceptable solution for me. May I suggest that the opening sentence of the documentation for the `file.managed` `source` argument be updated expressly to mention local-to-the-minion files? (I see now that the very last sentence of the `source` documentation does mention local files for the source-list functionality. That was insufficient to clue-me-in in the face of the opening sentence, and the rest of the long opening paragraph, which does not mention local files at all.)

Thanks again!
