### ISSUE TITLE
Not refreshing yum repo before install new package

### ISSUE THREAD

**Issue by grigory51** [saltstack/salt#38064] opened 2016-12-03 15:10 UTC
### Setup
```
eagle:
  pkg:
    - installed
    - version: {{ pillar['pkgs']['eagle'] }}
    - refresh: true
    - fromrepo: c7-fs-projects
    - require:
      - pkg: sentiment
```

### Steps to Reproduce Issue
Install salt-minion 2016.11
Try change version and update package via state.highstate with pkg.installed and exact version of package

```
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[INFO    ] Package hawk is already installed
[INFO    ] Completed state [hawk] at time 18:06:28.797004 duration_in_ms=789.92
[INFO    ] Running state [eagle] at time 18:06:28.797413
[INFO    ] Executing state pkg.installed for eagle
[DEBUG   ] Could not LazyLoad pkg.check_db: 'pkg.check_db' is not available.
[DEBUG   ] Could not LazyLoad pkg.check_extra_requirements: 'pkg.check_extra_requirements' is not available.
[DEBUG   ] Could not LazyLoad pkg.version_clean: 'pkg.version_clean' is not available.
[DEBUG   ] Current version (['0.2.0-14.el7.centos']) did not match desired version specification (0.2.0-15.el7.centos), adding to installation targets
[INFO    ] Restricting to repo 'c7-fs-projects'
[DEBUG   ] Failed to get holds, versionlock plugin is probably not installed
[INFO    ] Executing command ['systemd-run', '--scope', 'yum', '-y', '--disablerepo=*', '--enablerepo=c7-fs-projects', 'install', 'eagle-0.2.0-15.el7.centos'] in directory '/root'
[ERROR   ] Command '['systemd-run', '--scope', 'yum', '-y', '--disablerepo=*', '--enablerepo=c7-fs-projects', 'install', 'eagle-0.2.0-15.el7.centos']' failed with return code: 1
[ERROR   ] stdout: Running scope as unit run-27369.scope.
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
No package eagle-0.2.0-15.el7.centos available.
Error: Nothing to do
```

Then i downgrade salt-minion to 2016.3.4
```
[DEBUG   ] Current version (['0.2.0-14.el7.centos']) did not match desired version specification (0.2.0-15.el7.centos), adding to installation targets
[INFO    ] Restricting to repo 'c7-fs-projects'
[INFO    ] Restricting to repo 'c7-fs-projects'
[INFO    ] Executing command ['yum', '--quiet', 'clean', 'expire-cache', '--disablerepo=*', '--enablerepo=c7-fs-projects'] in directory '/root'
[DEBUG   ] output:
[INFO    ] Executing command ['yum', '--quiet', 'check-update', '--disablerepo=*', '--enablerepo=c7-fs-projects'] in directory '/root'
[INFO    ] Executing command ['systemd-run', '--scope', 'yum', '-y', '--disablerepo=*', '--enablerepo=c7-fs-projects', 'install', 'eagle-0.2.0-15.el7.centos'] in directory '/root'
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.version_clean
[INFO    ] Made the following changes:
'eagle' changed from '0.2.0-14.el7.centos' to '0.2.0-15.el7.centos'
```

`'yum', '--quiet', 'clean', 'expire-cache'` skipped in new version of minion :(

### Versions Report: Minion
salt-call --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

### Versions Report: Master
salt --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: unknown
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
   python-gnupg: Not Installed
         PyYAML: 3.09
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.4

System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-042stab113.21
         system: Linux
        version: CentOS 6.5 Final

**Comment by gtmanfred** [comment] 2016-12-05 16:12
I am also not seeing that the repository be refreshed.

```
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'test.sls' to resolve 'salt://test.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/test.sls' to resolve 'salt://test.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://test.sls'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'base', ** done ** 'test.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/test.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'jinja' renderer: 0.00291013717651
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/test.sls:
python-pip:
  pkg:
    - installed
    - version: 7.1.0-1.el7
    - refresh: true
    - fromrepo: epel,base

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('python-pip', OrderedDict([('pkg', ['installed', OrderedDict([('version', '7.1.0-1.el7')]), OrderedDict([('refresh', True)]), OrderedDict([('fromrepo', 'epel,base')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'yaml' renderer: 0.00551795959473
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg.installed
[ERROR   ] org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init: 'pkg.ex_mod_init' is not available.
[INFO    ] Running state [python-pip] at time 16:08:59.962619
[INFO    ] Executing state pkg.installed for python-pip
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.check_db: 'pkg.check_db' is not available.
[INFO    ] Restricting to repo 'epel,base'
[DEBUG   ] Failed to get holds, versionlock plugin is probably not installed
[INFO    ] Executing command ['yum', '-y', '--disablerepo=*', '--enablerepo=epel,base', 'install', 'python-pip-7.1.0-1.el7'] in directory '/root'
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.version_clean: 'pkg.version_clean' is not available.
[INFO    ] Made the following changes:
'python-pip' changed from 'absent' to '7.1.0-1.el7'
'python-setuptools' changed from 'absent' to '0.9.8-4.el7'

[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Completed state [python-pip] at time 16:10:15.819209 duration_in_ms=75856.59
[DEBUG   ] File /var/cache/salt/minion/accumulator/33598736 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: python-pip
    Function: pkg.installed
      Result: True
     Comment: 1 targeted package was installed/updated.
     Started: 16:08:59.962619
    Duration: 75856.59 ms
     Changes:
              ----------
              python-pip:
                  ----------
                  new:
                      7.1.0-1.el7
                  old:
              python-setuptools:
                  ----------
                  new:
                      0.9.8-4.el7
                  old:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  75.857 s
```

Thanks for reporting this.
Daniel

**Comment by terminalmage** [comment] 2016-12-06 22:38
Closing this as a duplicate of https://github.com/saltstack/salt/issues/38090.

**Closed by terminalmage** 2016-12-06 22:38 UTC
Labels: Duplicate
