### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 26: ordinal not in range(128)

### ISSUE THREAD

**Issue by xuwannian** [saltstack/salt#42736] opened 2017-08-04 04:08 UTC
### Description of Issue/Question
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 26: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 404, in salt_ssh
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 312, in __init__
    self.mods = mod_data(self.fsclient)
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 1311, in mod_data
    files = fsclient.file_list(env)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 896, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 415, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 391, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 339, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/lib/python2.6/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1119, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.6/logging/__init__.py", line 1172, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib64/python2.6/logging/__init__.py", line 306, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 26: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 404, in salt_ssh
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 312, in __init__
    self.mods = mod_data(self.fsclient)
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 1311, in mod_data
    files = fsclient.file_list(env)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 896, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 415, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 391, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 339, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/lib/python2.6/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1119, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.6/logging/__init__.py", line 1172, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib64/python2.6/logging/__init__.py", line 306, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 26: ordinal not in range(128)
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

salt-ssh '*' test.ping

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
[root@host-172-30-103-7 ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Nov 22 2013, 12:16:22)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final

```

**Comment by xuwn** [comment] 2017-08-04 04:18
```
[root@host-172-30-103-7 ~]# salt-ssh '*' test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 26: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 404, in salt_ssh
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 312, in __init__
    self.mods = mod_data(self.fsclient)
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 1311, in mod_data
    files = fsclient.file_list(env)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 896, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 415, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 391, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 339, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/lib/python2.6/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1119, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.6/logging/__init__.py", line 1172, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib64/python2.6/logging/__init__.py", line 306, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 26: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 404, in salt_ssh
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 312, in __init__
    self.mods = mod_data(self.fsclient)
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 1311, in mod_data
    files = fsclient.file_list(env)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 896, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 415, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 391, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/roots.py", line 339, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/lib/python2.6/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1119, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.6/logging/__init__.py", line 1172, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib64/python2.6/logging/__init__.py", line 306, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 26: ordinal not in range(128)
[root@host-172-30-103-7 ~]# 
```

**Comment by damon-atkins** [comment] 2017-08-04 04:20
It will be similar to this  https://github.com/saltstack/salt/issues/42278 `salt logging with plain str (ascii) with unicode chars causes UnicodeDecodeError PY2`
Python 2 expects strings to be less than chars<127  see the above issue for more details.

**Comment by gtmanfred** [comment] 2017-08-04 12:48
yes, this is a duplicate of #42278

**Closed by gtmanfred** 2017-08-04 12:48 UTC

**Comment by xuwn** [comment] 2017-08-04 14:24
it's not a salt bug!

salt-ssh work well when i delete /srv/salt/*!

**Comment by xuwn** [comment] 2017-08-04 14:27
thank's for all!

@damon-atkins you are so kind.
