### ISSUE TITLE
Missing repo for Ubuntu 24.04 LTS [BUG]

### ISSUE THREAD

**Issue by venomone** [saltstack/salt#66439] opened 2024-04-25 17:26 UTC
Hey folks, I'm currently missing the Repo for 24.04 LTS here::

https://repo.saltproject.io/salt/py3/ubuntu/

Can smb. fix this up, or is this still in the pipeline?

Kind regards

**Comment by steverweber** [comment] 2024-04-25 19:09
related: https://github.com/saltstack/salt/issues/66180

**Comment by ScriptAutomate** [comment] 2024-05-01 22:13
Duplicate of https://github.com/saltstack/salt/issues/66180

**Closed by ScriptAutomate** 2024-05-01 22:13 UTC
Labels: Bug, needs-triage
