### ISSUE TITLE
Regression: Salt-cloud does register an aws instance with an EIP instead of a public IP

### ISSUE THREAD

**Issue by martinhoefling** [saltstack/salt#28677] opened 2015-11-07 15:38 UTC
As written in the documentation: https://docs.saltstack.com/en/latest/topics/cloud/aws.html

```
  network_interfaces:
    - DeviceIndex: 0
   ...
      #auto assign public ip (not EIP)
      AssociatePublicIpAddress: True
...
```

I guess that commit 4d1fb4595b3c77c9311417d028262f9e7defb5a0 breaks this behavior.

**Comment by rallytime** [comment] 2015-11-07 15:51
@martinhoefling I have fixed this with #28584, which will be available in 2015.8.2. 

This is a duplicate of #27574.

**Closed** 2015-11-24 15:55 UTC
Labels: Bug, Duplicate, Fixed Pending Verification, High Severity, P2, RIoT, Salt-Cloud
