### ISSUE TITLE
salt-run cache.grains crashes

### ISSUE THREAD

**Issue by harmv** [saltstack/salt#39786] opened 2017-03-02 14:41 UTC
### Description of Issue/Question

retrieving the cached grains on the master no longer works.

We used this before on 2016.3.3
We noticed today that it fails on 2016.11.3,  (unsure if 2016.11.2 was ok or not)

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
Running salt-run cache.grains on our salt-master crashes

```
# salt-run cache.grains
Exception occurred in runner cache.grains: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/cache.py", line 38, in grains
    cached_grains = pillar_util.get_minion_grains()
  File "/usr/lib/python2.7/dist-packages/salt/utils/master.py", line 295, in get_minion_grains
    cached_minion_grains, cached_minion_pillars = self._get_cached_minion_data(*minion_ids)
  File "/usr/lib/python2.7/dist-packages/salt/utils/master.py", line 140, in _get_cached_minion_data
    if 'grains' in mdata:
TypeError: argument of type 'NoneType' is not iterable
[INFO    ] Runner completed: 20170302152847772427
```
### Fix

The following patch fixes the problem here, I'm not sure if this is a correct fix or not.

```
diff --git a/salt/utils/master.py b/salt/utils/master.py
index 483c056..9ba90e6 100644
--- a/salt/utils/master.py
+++ b/salt/utils/master.py
@@ -134,6 +134,8 @@ class MasterPillarUtil(object):
             if not salt.utils.verify.valid_id(self.opts, minion_id):
                 continue
             mdata = self.cache.fetch('minions/{0}'.format(minion_id), 'data')
+            if mdata is None:
+                continue
             if 'grains' in mdata:
                 grains[minion_id] = mdata['grains']
             if 'pillar' in mdata:
```

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 2.3.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by bkruger99** [comment] 2017-03-02 17:23
Looks like this is fixed in the develop branch from https://github.com/saltstack/salt/pull/39651.    Fix is similar to what you had posted.

**Comment by cachedout** [comment] 2017-03-02 17:25
I'll mark #39651 as a backport to 2016.11. Apologies for the regression.

**Comment by Ch3LL** [comment] 2017-03-02 22:37
@harmv can you give #39651 a try and report back if its working for you?

**Comment by harmv** [comment] 2017-03-03 07:35
I'll give it a try. (will be next week though)

**Comment by myii** [comment] 2017-03-07 00:24
@harmv Coming from probable duplicate issue #39835, I can report that this patch has worked for my `2016.11.3` master.  The strange thing is that my other `2016.11.3` master wasn't affected.

**Comment by harmv** [comment] 2017-03-07 08:39
@myii  perfect. I'll skip my test. (Wasn't that easy for me to do)

**Comment by myii** [comment] 2017-03-07 08:49
@harmv There is a workaround, as I mentioned in #39835:

> Found that explicitly stating the `tgt` worked fine, i.e.:
> 
> ```bash
> # salt-run cache.grains tgt='*'
> ```

**Comment by harmv** [comment] 2017-03-07 10:43
@myii hm.. in my case the workaround doesn't work

```
# salt-run cache.grains tgt='*'
Exception occurred in runner cache.grains: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/cache.py", line 38, in grains
    cached_grains = pillar_util.get_minion_grains()
  File "/usr/lib/python2.7/dist-packages/salt/utils/master.py", line 295, in get_minion_grains
    cached_minion_grains, cached_minion_pillars = self._get_cached_minion_data(*minion_ids)
  File "/usr/lib/python2.7/dist-packages/salt/utils/master.py", line 140, in _get_cached_minion_data
    if 'grains' in mdata:
TypeError: argument of type 'NoneType' is not iterable
[INFO    ] Runner completed: 20170307113924727982
```

Here somehow in the master minion cache, there is a minion directory without  a data.p file. (the minion directory is empty)
```
root@foo:/root/# ls /var/cache/salt/master/minions/14120026
root@foo:/root/#
```

**Comment by myii** [comment] 2017-03-07 11:06
@harmv Saw that @Ch3LL mentioned at https://github.com/saltstack/salt/issues/38216#issuecomment-266881930:

> looks like i'm able to replicate this but only when I do not have any minions attached to the master...
> 
> git bisect shows 6d1653d as the first bad commit

I suppose that the workaround requires some minions attached...

**Comment by harmv** [comment] 2017-03-07 11:12
I can confirm that the fix in pull request #39852 (merged), fixes my particular problem.
(tested version 8ecc719f905e1a2c5ab5e7d82dc7a6b3969acd90)

**Comment by myii** [comment] 2017-03-07 11:14
@harmv Better than any workaround.

**Comment by Ch3LL** [comment] 2017-03-08 20:39
Thanks for testing. Will close now thanks!

**Closed by Ch3LL** 2017-03-08 20:39 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P4, Runners

**Comment by DrMerlin** [comment] 2017-06-06 19:53
@harmv When you say "your particular problem" are you referring to cache.grains breaking due to the minion directory without a data.p file?  I am experiencing that same problem.  The "minion" in particular is not actually a minion, but a salt-ssh target.
