### ISSUE TITLE
Regression: Inverted diff on file.managed with --output-diff and test=True

### ISSUE THREAD

**Issue by tomlaredo** [saltstack/salt#47016] opened 2018-04-11 13:08 UTC
### Description of Issue/Question
Since saltstack 2018.3, file.managed displays a wrong diff when using --output-diff and test=True is the content is given by "source" (issue not present with "contents" keyword").

### Setup
salt_regression.sls

```
regression-proof-good-result:
    file.managed:
        - name: /tmp/test.conf
        - contents: |
            new_value via contents

regression-proof-bad-result:
    file.managed:
        - name: /tmp/test.conf
        - source: salt://server_test.conf
```

### Steps to Reproduce Issue

echo "old_value" > /tmp/test.conf

Run with test=True shoowing the wrong-wayed diff for the state with "source" keyword":

```
# salt-call --log-level=warning --output-diff state.apply salt_regression test=True
local:
----------
          ID: regression-proof-good-result
    Function: file.managed
        Name: /tmp/test.conf
      Result: None
     Comment: The file /tmp/test.conf is set to be changed
     Started: 14:54:33.274379
    Duration: 9.706 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1 +1 @@
                  -old_value
                  +new_value via contents
----------
          ID: regression-proof-bad-result
    Function: file.managed
        Name: /tmp/test.conf
      Result: None
     Comment: The file /tmp/test.conf is set to be changed
     Started: 14:54:33.284230
    Duration: 84.632 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1 +1 @@
                  -new_value in file
                  +old_value
```

Run without test=True shoowing the good/effective diff:
```
# salt-call --log-level=warning --output-diff state.apply salt_regression
local:
----------
          ID: regression-proof-good-result
    Function: file.managed
        Name: /tmp/test.conf
      Result: True
     Comment: File /tmp/test.conf updated
     Started: 14:53:56.242927
    Duration: 14.685 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1 +1 @@
                  -old_value
                  +new_value via contents
----------
          ID: regression-proof-bad-result
    Function: file.managed
        Name: /tmp/test.conf
      Result: True
     Comment: File /tmp/test.conf updated
     Started: 14:53:56.257804
    Duration: 82.645 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1 +1 @@
                  -new_value via contents
                  +new_value in file
```

### Versions Report

salt-call 2018.3.0 (Oxygen)

**Comment by pgporada** [comment] 2018-04-11 19:34
We're running into this as well.

**Comment by Ch3LL** [comment] 2018-04-12 13:51
this is a duplicate of https://github.com/saltstack/salt/issues/46931

**Closed by Ch3LL** 2018-04-12 13:51 UTC

**Comment by tomlaredo** [comment] 2018-04-16 08:54
Please add unit tests to this :)
