### ISSUE TITLE
2014.7 salt-cloud fails when using a map with make_master: True

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#16734] opened 2014-10-18 05:40 UTC
If I add `make_master: True` I get the following error when salt-cloud attempts to build the first vm.

```
root@boucha:~/salt# salt-cloud -m /etc/salt/technicolor.map 
[INFO    ] salt-cloud starting
[INFO    ] Applying map from '/etc/salt/technicolor.map'.
The following virtual machines are set to be created:
  saltmaster1
  saltrepo
  saltmaster2

Proceed? [N/y] y
... proceeding
[INFO    ] Calculating dependencies for saltmaster1
[INFO    ] Calculating dependencies for saltrepo
[INFO    ] Calculating dependencies for saltmaster2
[INFO    ] Creating Cloud VM saltmaster1 in us-east-1
[INFO    ] Created node saltmaster1
[INFO    ] Salt node data. Public_ip: 54.xxx.xxx.xxx
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Sat Oct 18 01:30:59 EDT 2014
[INFO    ] Rendering deploy script: /etc/salt/cloud.deploy.d/bootstrap-salt.sh
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Sat Oct 18 01:31:01 EDT 2014
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connection to 54.xxx.xxx.xxx closed.
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connection to 54.xxx.xxx.xxx closed.
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connection to 54.xxx.xxx.xxx closed.
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connected to 54.xxx.xxx.xxx.
sftp> put /tmp/tmpkxyImo /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/minion.pem
Uploading /tmp/tmpkxyImo to /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/minion.pem
/tmp/tmpkxyImo                                                                                                       100% 3243     3.2KB/s   00:00    
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connection to 54.xxx.xxx.xxx closed.
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connected to 54.xxx.xxx.xxx.
sftp> put /tmp/tmptWeFZ8 /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/minion.pub
Uploading /tmp/tmptWeFZ8 to /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/minion.pub
/tmp/tmptWeFZ8                                                                                                       100%  800     0.8KB/s   00:01    
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connected to 54.xxx.xxx.xxx.
sftp> put /tmp/tmp1DKCfL /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/minion
Uploading /tmp/tmp1DKCfL to /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/minion
/tmp/tmp1DKCfL                                                                                                       100% 3165     3.1KB/s   00:00    
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connected to 54.xxx.xxx.xxx.
sftp> put /tmp/tmpBPsauF /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/master.pem
Uploading /tmp/tmpBPsauF to /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/master.pem
/tmp/tmpBPsauF                                                                                                       100% 3243     3.2KB/s   00:00    
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connection to 54.xxx.xxx.xxx closed.
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connected to 54.xxx.xxx.xxx.
sftp> put /tmp/tmpmV7fO2 /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/master.pub
Uploading /tmp/tmpmV7fO2 to /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/master.pub
/tmp/tmpmV7fO2                                                                                                       100%  800     0.8KB/s   00:00    
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connected to 54.xxx.xxx.xxx.
sftp> put /tmp/tmpigaNyl /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/master
Uploading /tmp/tmpigaNyl to /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/master
/tmp/tmpigaNyl                                                                                                       100% 3825     3.7KB/s   00:00    
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connection to 54.xxx.xxx.xxx closed.
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connection to 54.xxx.xxx.xxx closed.
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connection to 54.xxx.xxx.xxx closed.
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connected to 54.xxx.xxx.xxx.
sftp> put /tmp/tmpHXWt2d /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/preseed-minion-keys/saltrepo
Uploading /tmp/tmpHXWt2d to /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/preseed-minion-keys/saltrepo
/tmp/tmpHXWt2d                                                                                                       100%  800     0.8KB/s   00:00    
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connected to 54.xxx.xxx.xxx.
sftp> put /tmp/tmpj06MhC /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/preseed-minion-keys/saltmaster1
Uploading /tmp/tmpj06MhC to /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/preseed-minion-keys/saltmaster1
/tmp/tmpj06MhC                                                                                                       100%  800     0.8KB/s   00:00    
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connected to 54.xxx.xxx.xxx.
sftp> put /tmp/tmppP2uks /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/preseed-minion-keys/saltmaster2
Uploading /tmp/tmppP2uks to /tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/preseed-minion-keys/saltmaster2
/tmp/tmppP2uks                                                                                                       100%  800     0.8KB/s   00:00    
Warning: Permanently added '54.xxx.xxx.xxx' (RSA) to the list of known hosts.
Connection to 54.xxx.xxx.xxx closed.
chown: cannot access `"/tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/preseed-minion-keys"': No such file or directory
Error: There was a query error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /root/.ssh/dave-test.pem -p 22 ec2-user@54.xxx.xxx.xxx \'sudo chown -R root \\"/tmp/.saltcloud-03bd3381-de7e-4421-95d5-195cc5e81402/preseed-minion-keys\\"\'' failed. Exit code: 1
```

This is on the latest from the 2014.7 branch:
```
root@boucha:~/salt# salt-master --versions-report
           Salt: 2014.7.0rc4-46-ga06ed6d
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.7.2
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

Here's my map file that causes this error:
```
amazon_redhat65:
  - saltmaster1:
      make_master: True
  - saltmaster2
  - saltrepo
```

Here's my map file that works just fine:
```
amazon_redhat65:
  - saltmaster1
  - saltmaster2
  - saltrepo
```

**Comment by MarkMarine** [comment] 2015-01-16 23:07
I'm seeing this as well, it looks from my stacktrace that a boolean is trying to be used with `.setdefault` and doesn't have that method.
Here is my stacktrace:
```
root@ip-10-0-0-50:/etc/salt/cloud.maps.d# salt-cloud -m ./ec2_test.map -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[INFO    ] Found minion id from generate_minion_id(): ip-10-0-0-50.us-west-1.compute.internal
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[WARNING ] DEPRECATED: Mako will no longer be the default renderer for Salt Cloud maps in the Lithium release
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'bool' object has no attribute 'setdefault'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 209, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 83, in run
    mapper = salt.cloud.Map(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1490, in __init__
    self.rendered_map = self.read()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1633, in read
    overrides.setdefault('name', name)
AttributeError: 'bool' object has no attribute 'setdefault'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 209, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 83, in run
    mapper = salt.cloud.Map(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1490, in __init__
    self.rendered_map = self.read()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1633, in read
    overrides.setdefault('name', name)
AttributeError: 'bool' object has no attribute 'setdefault'
```

Here is the offending map:
```
saltcloud_test_vpc:
  - testA:
    make_master: True
  - testB
  - testC
```
When running the same map with `make_master: True` is commented it, it works just fine.
Here is the versions:
```
Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by techhat** [comment] 2015-05-19 20:23
@nmadhok

**Comment by nmadhok** [comment] 2015-05-19 22:49
@techhat I'll look into this hopefully soon.

**Comment by roder** [comment] 2015-05-20 21:19
@nmadhok @UtahDave I am also getting this error, but I'm using GCE not EC2.

**Comment by rallytime** [comment] 2015-08-13 19:10
Is anyone running into problems with this bug on 2015.5.0 or newer? I am unable to reproduce any of these stack-traces at the HEAD of 2015.5 branch:
map file:
```
# cat mapfile
ec2-rhel-6:
  - nt-testing-4:
      make_master: True
  - nt-testing-5
```
Success!
```
# salt-cloud -m mapfile
[INFO    ] salt-cloud starting
<snipped>
Writing /usr/lib/python2.6/site-packages/salt-2015.5.3_630_g5dd5ac1-py2.6.egg-info
 *  INFO: Running install_red_hat_enterprise_server_git_post()
 *  INFO: Running install_red_hat_enterprise_server_restart_daemons()
Starting salt-minion daemon:                               [  OK  ]
Starting salt-master daemon:                               [  OK  ]
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!
[DEBUG   ]  *  INFO: Running install_red_hat_enterprise_server_git_post()
 *  INFO: Running install_red_hat_enterprise_server_restart_daemons()
Starting salt-minion daemon:                               [  OK  ]
Starting salt-master daemon:                               [  OK  ]
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!
<snipped>
[DEBUG   ] LazyLoaded nested.output
nt-testing-4:
    ----------
    amiLaunchIndex:
        0
    architecture:
        x86_64
    blockDeviceMapping:
        ----------
        item:
            ----------
            deviceName:
                /dev/sda1
            ebs:
                ----------
                attachTime:
                    2015-08-13T18:48:47.000Z
                deleteOnTermination:
                    true
                status:
                    attaching
                volumeId:
                    vol-f5050b1f
    clientToken:
        None
    deployed:
        True
    dnsName:
        ec2-x.compute-1.amazonaws.com
    ebsOptimized:
        false
    groupSet:
        ----------
        item:
            ----------
            groupId:
                sg-306bf158
            groupName:
                class
    hypervisor:
        xen
    imageId:
        ami-b06a98d8
    instanceId:
        i-8348ea28
    instanceState:
        ----------
        code:
            0
        name:
            pending
    instanceType:
        t1.micro
    ipAddress:
        x.x.x.x
    kernelId:
        aki-919dcaf8
    keyName:
        nt-cloud
    launchTime:
        2015-08-13T18:48:45.000Z
    monitoring:
        ----------
        state:
            disabled
    networkInterfaceSet:
        None
    placement:
        ----------
        availabilityZone:
            us-east-1b
        groupName:
            None
        tenancy:
            default
    privateDnsName:
        ip-10-65-140-140.ec2.internal
    privateIpAddress:
        x.x.x.x
    productCodes:
        None
    reason:
        None
    rootDeviceName:
        /dev/sda1
    rootDeviceType:
        ebs
    virtualizationType:
        paravirtual
```
Versions:
```
# salt-cloud --versions
            Salt: 2015.5.3-229-g65ab5aa
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
         Tornado: 4.2
         timelib: 0.2.4
 Apache Libcloud: 0.14.1
```
I think @dmaze is correct in that #16642 has fixed this issue.

**Comment by rallytime** [comment] 2015-08-21 22:02
Since I didn't hear back from anyone and I can no longer replicate this issue, I am going to close this. If the problem pops up again, please re-open. :)

**Closed by rallytime** 2015-08-21 22:02 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P2, RIoT, Salt-Cloud
