### ISSUE TITLE
Enabling services with runit fails

### ISSUE THREAD

**Issue by AFriemann** [saltstack/salt#42539] opened 2017-07-25 11:15 UTC
### Description of Issue/Question

I am having trouble with the enable feature for runit services on Void Linux. Unfortunately I do not really understand what exactly is happening - in fact I don't understand how this behaviour is even possible - but it seems services do not start up when being linked by saltstack.

### Setup

Using a very simple sls like this:

```
cron:
  pkg.installed:
    - name: cronie
  service.running:
    - name: crond
    - enable: True
    - require:
      - pkg: cron
```

On void linux `Linux mail.*.* 4.11.11_1 #1 SMP PREEMPT Sat Jul 15 21:48:45 UTC 2017 x86_64 GNU/Linux`

### Steps to Reproduce Issue

Make sure crond ist disabled:
```
[root@mail admin]# sv stop crond
ok: down: crond: 1s, normally up
[root@mail admin]# rm /var/service/cron*
```

run salt-call (in local mode, if that is relevant)
```
[root@mail admin]# salt-call --log-level debug state.apply
...
[INFO    ] Running state [cronie] at time 13:05:44.349576
[INFO    ] Executing state pkg.installed for [cronie]
[INFO    ] Executing command 'xbps-query -l' in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[DEBUG   ] Could not LazyLoad pkg.hold: 'pkg.hold' is not available.
[INFO    ] Package cronie is already installed
[INFO    ] Completed state [cronie] at time 13:05:44.394560 duration_in_ms=44.983
[INFO    ] Running state [crond] at time 13:05:44.395975
[INFO    ] Executing state service.running for [crond]
[INFO    ] Executing command 'sv start /var/service/crond' in directory '/root'
[ERROR   ] Command 'sv start /var/service/crond' failed with return code: 1
[ERROR   ] output: fail: /var/service/crond: unable to change to service directory: file does not exist
[INFO    ] Executing command 'sv status /var/service/crond' in directory '/root'
[ERROR   ] Command 'sv status /var/service/crond' failed with return code: 1
[ERROR   ] stdout: fail: /var/service/crond: runsv not running
[ERROR   ] retcode: 1
[INFO    ] Executing command 'sv status /var/service/crond' in directory '/root'
[ERROR   ] Command 'sv status /var/service/crond' failed with return code: 1
[ERROR   ] stdout: fail: /var/service/crond: runsv not running
[ERROR   ] retcode: 1
[INFO    ] Executing command 'sv status /var/service/crond' in directory '/root'
[DEBUG   ] stdout: down: /var/service/crond: 0s
[ERROR   ] {'crond': True}
[INFO    ] Completed state [crond] at time 13:05:45.946656 duration_in_ms=1550.677
...
----------
          ID: cron
    Function: pkg.installed
        Name: cronie
      Result: True
     Comment: Package cronie is already installed
     Started: 13:05:44.349577
    Duration: 44.983 ms
     Changes:   
----------
          ID: cron
    Function: service.running
        Name: crond
      Result: False
     Comment: Service crond has been enabled, and is dead
     Started: 13:05:44.395979
    Duration: 1550.677 ms
     Changes:   
              ----------
              crond:
                  True
----------
```

now to check if crond is running and fix it:
```
[root@mail admin]# ls -l /var/service/crond
lrwxrwxrwx 1 root root 13 Jul 25 13:05 /var/service/crond -> /etc/sv/crond
[root@mail admin]# sv status crond
down: crond: 166s, normally up
[root@mail admin]# rm /var/service/crond
[root@mail admin]# ln -s /etc/sv/crond /var/service/crond
[root@mail admin]# sv status crond
run: crond: (pid 6990) 1s
```

### Versions Report
running salt-call in local mode.

```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 2.7.13 (default, Jul 16 2017, 01:33:52)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.11.11_1
         system: Linux
        version: Not Installed
```

my minon config:

```
[root@mail admin]# cat /etc/salt/minion
master_type: disable
file_client: local
fileserver_backend:
    - git
gitfs_remotes:
    - git@*/infrastructure.git:
      - pubkey: /etc/salt/*.pub
      - privkey: /etc/salt/*
      - root: salt
```

**Comment by gtmanfred** [comment] 2017-07-25 15:50
@bjmllr or @Vaelatern can one of yall take a look at this?

We don't really have any experience with runit, so it would be good to have someone that knows it to look.

Thanks,
Daniel

**Comment by Vaelatern** [comment] 2017-09-27 11:35
I've noticed this. I'll report back with where I don't know enough to fix it.

**Comment by Vaelatern** [comment] 2017-09-27 23:36
This is triggered by passing `start=True` (second argument) to `enable` in `./salt/modules/runit.py`. Previously I have attempted to trace this call to work out how to pass this, but have not been successful. After that is done, it should work.

**Comment by Vaelatern** [comment] 2017-09-27 23:37
My apologies about the long lag between this issue and my report. Been a while since I cleared out my github notifications.

**Comment by Vaelatern** [comment] 2018-07-11 21:04
The problem appears to be that we always enable services but don't enable them in that one move.

**Comment by Vaelatern** [comment] 2020-01-12 03:08
This issue is still relevant.

**Comment by Vaelatern** [comment] 2020-02-11 07:38
sadly still relevant, trying to find a solution that satisfies everybody.

**Comment by sagetherage** [comment] 2020-03-17 19:02
@Vaelatern should we open up a discussion on this topic perhaps at one of the Working Groups or the weekly Community Open Hour to find a solution that also satisfies everyone? Would that be helpful, at all?

**Comment by Vaelatern** [comment] 2020-03-17 23:47
Yes, that would be nice. I don't know enough about salt internals to tackle it myself.

**Comment by sagetherage** [comment] 2020-06-02 20:51
kicking this back to triage in an attempt to get movement

**Comment by Vaelatern** [comment] 2020-06-02 22:24
ok, so:

When working with runit, to enable and start a service, you:
`ln -s /etc/sv/$service_name /var/service`

When enabling but NOT starting a service, do the above and then quickly stop it with an `sv stop $service_name` (or play with the `/etc/sv/$service_name/down` file, which, if it exists, will prohibit running the service).

To check that a service is in fact running, `sudo sv check $service_name` must succeed (0 return).

There is no way to run a service without enabling it, except manually. `sudo runsv /etc/sv/$service_name` (if I recall correctly).

My latest salt states just manually `file.symlink` to enable the service. This obviously makes things slightly less portable than they would be if I could use `service.running`.

**Comment by Vaelatern** [comment] 2020-06-03 18:46
I've confirmed that I can not make a runit service start with saltstack as of 3000.2.

**Comment by dmurphy18** [comment] 2020-06-03 19:49
@Vaelatern Could you repeat that with 3000.3 as there was an issue with runners in 3000.2.  Thanks

**Comment by Vaelatern** [comment] 2020-07-30 04:01
I intend to test this with 3000.3

Have not had the opportunity yet.

**Comment by Noah-Huppert** [comment] 2020-11-15 18:38
On Salt version:

```
% salt --versions-report                  64
Salt Version:
           Salt: 3002

Dependency Versions:
           cffi: 1.14.3
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: 1.1.3
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.9.0 (default, Oct 10 2020, 14:22:51)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3

System Versions:
           dist: void rolling void
         locale: utf-8
        machine: x86_64
        release: 5.8.16_1
         system: Linux
        version: void rolling void
% uname -a
Linux apollo 5.8.16_1 #1 SMP Sat Oct 17 12:21:35 UTC 2020 x86_64 GNU/Linux
```
I believe I am having this issue. I didn't use to have to manually create a symlink at `/var/service/<service name>` to `/etc/sv/<service name>`.

**Comment by Noah-Huppert** [comment] 2020-11-15 19:56
Ok, well, now I can't reproduce, so, uh....

For reference this is how I tried to reproduce the error:

`salt/runit-repro/init.sls`:
```yaml
/etc/sv/runit-repro/run:
  file.managed:
    - source: salt://runit-repro/run
    - mode: 755
    - makedirs: True

runit-repro-enabled:
  service.enabled:
    - name: runit-repro
    - require:
      - file: /etc/sv/runit-repro/run

runit-repro-running:
  service.running:
    - name: runit-repro
    - require:
      - service: runit-repro-enabled
```

`salt/runit-repro/run`:
```bash
#!/usr/bin/env bash
while true; do
  echo "ok"
done
```

And when I applied the state:

```
% salt-call --local --state-output=changes state.apply runit-repro saltenv=base pillarenv=base
[ERROR   ] Command '['sv', 'status', '/var/service/runit-repro']' failed with return code: 1
[ERROR   ] stdout: warning: /var/service/runit-repro: unable to open supervise/ok: file does not exist
[ERROR   ] retcode: 1
[ERROR   ] Command '['sv', 'status', '/var/service/runit-repro']' failed with return code: 1
[ERROR   ] stdout: warning: /var/service/runit-repro: unable to open supervise/ok: file does not exist
[ERROR   ] retcode: 1
[ERROR   ] Command '['sv', 'status', '/var/service/runit-repro']' failed with return code: 1
[ERROR   ] stdout: warning: /var/service/runit-repro: unable to open supervise/ok: file does not exist
[ERROR   ] retcode: 1
[ERROR   ] Command '['sv', 'status', '/var/service/runit-repro']' failed with return code: 1
[ERROR   ] stdout: warning: /var/service/runit-repro: unable to open supervise/ok: file does not exist
[ERROR   ] retcode: 1
[ERROR   ] Command '['sv', 'status', '/var/service/runit-repro']' failed with return code: 1
[ERROR   ] stdout: warning: /var/service/runit-repro: unable to open supervise/ok: file does not exist
[ERROR   ] retcode: 1
[ERROR   ] Command '['sv', 'status', '/var/service/runit-repro']' failed with return code: 1
[ERROR   ] stdout: warning: /var/service/runit-repro: unable to open supervise/ok: file does not exist
[ERROR   ] retcode: 1
local:
----------
          ID: /etc/sv/runit-repro/run
    Function: file.managed
      Result: True
     Comment: File /etc/sv/runit-repro/run updated
     Started: 14:52:59.595886
    Duration: 55.248 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0755
----------
          ID: runit-repro-enabled
    Function: service.enabled
        Name: runit-repro
      Result: True
     Comment: Service runit-repro has been enabled, and is in the desired state
     Started: 14:53:01.150640
    Duration: 3657.948 ms
     Changes:
              ----------
              runit-repro:
                  True
----------
          ID: runit-repro-running
    Function: service.running
        Name: runit-repro
      Result: True
     Comment: Started Service runit-repro
     Started: 14:53:04.810701
    Duration: 454.788 ms
     Changes:
              ----------
              runit-repro:
                  True

Summary for local
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time:   4.168 s
```

**Comment by Noah-Huppert** [comment] 2020-11-15 19:59
I had run into this error in the past and I figured out that I needed to use `service.enabled` followed by `service.running` instead of just `service.running` with the `enabled` argument set to true. So if anyone happens upon this error via google try that.

**Comment by Vaelatern** [comment] 2020-11-16 04:22
So you can still break it with `service.running: enabled: True`?

**Comment by sagetherage** [comment] 2020-11-17 23:23
@Noah-Huppert so is this a non-issue?

**Comment by Noah-Huppert** [comment] 2020-11-19 02:04
@Vaelatern @sagetherage no I can't. I unreliably reproduced it, not sure what I did. If I figure out what can reliably reproduce the bug I will let you know.

**Comment by Vaelatern** [comment] 2020-11-19 07:27
My guess is in one run you started it via running, but didn't enable it that run. That'll be my guess.

Runit doesn't have a concept of running without being enabled. This is a mismatch between the possible salt states and the usable salt states.

**Comment by sagetherage** [comment] 2021-02-03 17:10
I am going to close this as unreliably unable to reproduce, if it continues or you start to reproduce it consistently - mention me here or open another issue and we will gladly dig into it.

**Closed by sagetherage** 2021-02-03 17:10 UTC
Labels: info-needed

**Comment by Vaelatern** [comment] 2021-08-08 19:20
@sagetherage 

I have a consistent reproduction now

```
docker:
  service.running:
    - enable: True
```

Gives on the first run:
```
----------
          ID: docker
    Function: service.running
      Result: False
     Comment: Service docker has been enabled, and is dead
     Started: 12:44:30.353612
    Duration: 1049.387 ms
     Changes:
              ----------
              docker:
                  True

```

On the second run, it goes:

```
----------
          ID: docker
    Function: service.running
      Result: True
     Comment: Service docker is already enabled, and is running
     Started: 12:45:19.768495
    Duration: 439.049 ms
     Changes:
              ----------
              docker:
                  True
```

Then if I delete the symlink at `/var/service/docker` which disables and stops the service, then I can go through these steps again. This constitutes a reliable reproduction.

**Comment by Vaelatern** [comment] 2022-04-26 01:47
@sagetherage Would you like a `packer` based reproduction? I don't have a `docker` based reproduction handy yet, but I might at some point.
