### ISSUE TITLE
 cmd.run newline issue for user argument

### ISSUE THREAD

**Issue by ptavoularis** [saltstack/salt#24627] opened 2015-06-12 09:34 UTC
salt-minion 2015.5 inserts newline after user home folder when "- user" argument is used in cmd.run state.

example state:  https://gist.github.com/anonymous/acce56dc26a91084403e

example output: https://gist.github.com/anonymous/f3c9c1a66c360dfb6590

2014.7 salt-minion does not reproduce the issue

**Comment by anlutro** [comment] 2015-06-12 09:56
The underlying issue here seems to be that the NVM install script tries installing into `$HOME/.nvm`, and somehow `$HOME` includes a newline. Not sure how that can happen?

**Comment by ptavoularis** [comment] 2015-06-12 10:24
nvm was just an example. Same thing happens with any command that uses $HOME env variable and the state takes it from the "- user: username" argument. Only for 2015.5 salt-minion. Maybe they changed the underlying mechanism of cmd.run function?

**Comment by arroyoc** [comment] 2015-06-12 20:34
@ptavoularis @anlutro Thanks for your input. This issue is a duplicate of #24191, which has been fixed, but has not yet made it into release.

**Closed by arroyoc** 2015-06-12 20:34 UTC
Labels: Duplicate

**Comment by ptavoularis** [comment] 2015-06-15 06:40
@arroyoc and I made sure I searched before submitting this... Thanks!

**Comment by arroyoc** [comment] 2015-06-16 20:38
Not a big deal. Thanks for the information.
