### ISSUE TITLE
Unhandled exception running mine.update / KeyError: 'retcode'

### ISSUE THREAD

**Issue by hgfischer** [saltstack/salt#31038] opened 2016-02-09 13:34 UTC
This started happening, maybe because after the last update.

```
Unhandled exception running mine.update
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
```

```
salt-minion --versions
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-57-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment] 2016-02-09 16:30
@hgfischer, thanks for reporting.  This is a duplicate of #30472.

**Closed by jfindlay** 2016-02-09 16:30 UTC
Labels: Duplicate
