### ISSUE TITLE
salt-cloud exit code is 0 after failure (exception thrown)

### ISSUE THREAD

**Issue by borisovano** [saltstack/salt#39781] opened 2017-03-02 10:33 UTC
### Description of Issue/Question
**salt-cloud** exits with code 0 when execution is interrupted (exception thrown).

### Error flow
**salt execution commands:**

```
salt-cloud --log-file-level=debug --log-file=./saltcloud.log --config-dir=./tests/salt -dym ./integration_tests/configuration/map.sls
chk_error

salt-cloud --log-file-level=debug --log-file=./saltcloud.log --config-dir=./tests/salt -ym ./integration_tests/configuration/map.sls
chk_error


function chk_error {
if [ "$?" != "0" ];
      then
      echo "Salt execution failed! Exiting..."
      exit 1
fi
}

```

**result:**
```
+ salt-cloud --log-file-level=debug --log-file=./saltcloud.log --config-dir=./tests/salt -ym ./integration_tests/configuration/map.sls
[WARNING ] Although 'virt-what' was found in path, the current user cannot execute it. Grains output might not be accurate.
[ERROR   ] Error creating db6: exceptions must be old-style classes or derived from BaseException, not NoneType
db6:
    ----------
    Error:
        Error creating db6: exceptions must be old-style classes or derived from BaseException, not NoneType
+ chk_error
+ '[' 0 '!=' 0 ']'
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

**map file:**
```
db:
    - vmname_and_hostname:
        resourcepool: RP1
        datastore: RP-RND
        devices:
            network:
                Network adapter 1:
                    name: NETWORK1
                    switch_type: distributed
                    ip: 192.168.1.138
                    gateway: [192.168.1.254]
                    subnet_mask: 255.255.255.0
                    domain: example.com
```

**provider:**
```
vcloud:
  driver: vmware
  user: myuser
  password: secretpass
  url: 'vcenter.example.com'
  protocol: 'https'
  port: 443
```

### Steps to Reproduce Issue
If you'd like to reproduce consistently, run the salt commands above with malformed .sls file:
e.g replace the name field from : `   - vmname:` to `   - vmname.aa.aa:` (dots are not supported)

**result:**
[ERROR   ] Error creating vmname.aa.aa: Required field "folder" not provided (not @optional)
vmname.aa.aa:
    ----------

>     Error:
>         Error creating vmname.aa.aa: Required field "folder" not provided (not @optional)
> $ echo $?
> **0**

### Info
**system:**
```
$ uname -a
Linux hostname 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
```

**logs:**
```
2017-03-01 21:06:07,497 [salt.cloud.cli   ][INFO    ][102368] salt-cloud starting
2017-03-01 21:06:07,729 [salt.utils.lazy  ][DEBUG   ][102368] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
2017-03-01 21:06:07,729 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded parallels.avail_locations
2017-03-01 21:06:07,729 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded proxmox.avail_sizes
2017-03-01 21:06:07,730 [salt.utils.lazy  ][DEBUG   ][102368] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
2017-03-01 21:06:07,731 [salt.utils.lazy  ][DEBUG   ][102368] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
2017-03-01 21:06:07,732 [salt.utils.lazy  ][DEBUG   ][102368] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
2017-03-01 21:06:07,733 [salt.utils.lazy  ][DEBUG   ][102368] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
2017-03-01 21:06:07,733 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded rackspace.reboot
2017-03-01 21:06:07,733 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded openstack.list_locations
2017-03-01 21:06:07,733 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded rackspace.list_locations
2017-03-01 21:06:07,735 [salt.config      ][DEBUG   ][102368] Missing configuration file: /etc/salt/master
2017-03-01 21:06:07,735 [salt.config      ][DEBUG   ][102368] Guessing ID. The id can be explicitly set in /etc/salt/minion
2017-03-01 21:06:07,756 [salt.config      ][DEBUG   ][102368] Found minion id from generate_minion_id(): il-autoslave-lp1.example.local
2017-03-01 21:06:07,758 [salt.config      ][DEBUG   ][102368] Missing configuration file: /etc/salt/master
2017-03-01 21:06:08,039 [salt.loaded.int.grains.core][WARNING ][102368] Although 'virt-what' was found in path, the current user cannot execute it. Grains output might not be accurate.
2017-03-01 21:06:08,085 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded jinja.render
2017-03-01 21:06:08,087 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded yaml.render
2017-03-01 21:06:08,089 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded jinja.render
2017-03-01 21:06:08,089 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded yaml.render
2017-03-01 21:06:08,089 [salt.template    ][DEBUG   ][102368] compile template: ./tests/configuration/map.sls
2017-03-01 21:06:08,090 [salt.utils.jinja ][DEBUG   ][102368] Jinja search path: ['/var/cache/salt/cloud/files/base']
2017-03-01 21:06:08,094 [salt.template    ][PROFILE ][102368] Time (in seconds) to render './tests/configuration/map.sls' using 'jinja' renderer: 0.00444221496582
2017-03-01 21:06:08,095 [salt.template    ][DEBUG   ][102368] Rendered data from file: ./tests/configuration/map.sls:
db:
    - db6:
        datastore: RP-RND
        devices:
            network:
                Network adapter 1:
                    name: NETWORK1
                    switch_type: distributed
                    ip: 192.168.1.138
                    gateway: [192.168.1.254]
                    subnet_mask: 255.255.255.0
                    domain: example.com


2017-03-01 21:06:08,100 [salt.loaded.int.render.yaml][DEBUG   ][102368] Results of YAML rendering: 
OrderedDict([('db', [OrderedDict([('db6', OrderedDict([('datastore', 'RP-RND'), ('devices', OrderedDict([('network', OrderedDict([('Network adapter 1', OrderedDict([('name', 'NETWORK1'), ('switch_type', 'distributed'), ('ip', '192.168.1.138'), ('gateway', ['192.168.1.254']), ('subnet_mask', '255.255.255.0'), ('domain', 'example.com')]))]))]))]))])])])
2017-03-01 21:06:08,100 [salt.template    ][PROFILE ][102368] Time (in seconds) to render './tests/configuration/map.sls' using 'yaml' renderer: 0.00529813766479
2017-03-01 21:06:08,101 [salt.cloud.cli   ][INFO    ][102368] Applying map from './tests/configuration/map.sls'.
2017-03-01 21:06:08,102 [salt.config      ][DEBUG   ][102368] Missing configuration file: /etc/salt/master
2017-03-01 21:06:08,103 [salt.config      ][DEBUG   ][102368] Guessing ID. The id can be explicitly set in /etc/salt/minion
2017-03-01 21:06:08,123 [salt.config      ][DEBUG   ][102368] Found minion id from generate_minion_id(): il-autoslave-lp1.example.local
2017-03-01 21:06:08,125 [salt.config      ][DEBUG   ][102368] Missing configuration file: /etc/salt/master
2017-03-01 21:06:08,416 [salt.loaded.int.grains.core][WARNING ][102368] Although 'virt-what' was found in path, the current user cannot execute it. Grains output might not be accurate.
2017-03-01 21:06:08,466 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded jinja.render
2017-03-01 21:06:08,467 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded yaml.render
2017-03-01 21:06:08,469 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded jinja.render
2017-03-01 21:06:08,470 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded yaml.render
2017-03-01 21:06:08,470 [salt.template    ][DEBUG   ][102368] compile template: ./tests/configuration/map.sls
2017-03-01 21:06:08,471 [salt.utils.jinja ][DEBUG   ][102368] Jinja search path: ['/var/cache/salt/cloud/files/base']
2017-03-01 21:06:08,473 [salt.template    ][PROFILE ][102368] Time (in seconds) to render './tests/configuration/map.sls' using 'jinja' renderer: 0.0017831325531
2017-03-01 21:06:08,473 [salt.template    ][DEBUG   ][102368] Rendered data from file: ./tests/configuration/map.sls:
db:
    - db6:
        datastore: RP-RND
        devices:
            network:
                Network adapter 1:
                    name: NETWORK1
                    switch_type: distributed
                    ip: 192.168.1.138
                    gateway: [192.168.1.254]
                    subnet_mask: 255.255.255.0
                    domain: example.com 


2017-03-01 21:06:08,479 [salt.loaded.int.render.yaml][DEBUG   ][102368] Results of YAML rendering: 
OrderedDict([('db', [OrderedDict([('db6', OrderedDict([('datastore', 'RP-RND'), ('devices', OrderedDict([('network', OrderedDict([('Network adapter 1', OrderedDict([('name', 'NETWORK1'), ('switch_type', 'distributed'), ('ip', '192.168.1.138'), ('gateway', ['192.168.1.254']), ('subnet_mask', '255.255.255.0'), ('domain', 'example.com')]))]))]))]))])])])
2017-03-01 21:06:08,479 [salt.template    ][PROFILE ][102368] Time (in seconds) to render './tests/configuration/map.sls' using 'yaml' renderer: 0.00554490089417
2017-03-01 21:06:08,480 [salt.utils.lazy  ][DEBUG   ][102368] Could not LazyLoad vmware.optimize_providers: 'vmware.optimize_providers' is not available.
2017-03-01 21:06:08,480 [salt.cloud       ][DEBUG   ][102368] The 'vmware' cloud driver is unable to be optimized.
2017-03-01 21:06:08,552 [salt.utils.lazy  ][DEBUG   ][102441] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
2017-03-01 21:06:08,552 [salt.utils.lazy  ][DEBUG   ][102441] LazyLoaded parallels.avail_locations
2017-03-01 21:06:08,553 [salt.utils.lazy  ][DEBUG   ][102441] LazyLoaded proxmox.avail_sizes
2017-03-01 21:06:08,554 [salt.utils.lazy  ][DEBUG   ][102441] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
2017-03-01 21:06:08,554 [salt.utils.lazy  ][DEBUG   ][102441] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
2017-03-01 21:06:08,555 [salt.utils.lazy  ][DEBUG   ][102441] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
2017-03-01 21:06:08,556 [salt.utils.lazy  ][DEBUG   ][102441] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
2017-03-01 21:06:08,557 [salt.utils.lazy  ][DEBUG   ][102441] LazyLoaded rackspace.reboot
2017-03-01 21:06:08,557 [salt.utils.lazy  ][DEBUG   ][102441] LazyLoaded openstack.list_locations
2017-03-01 21:06:08,557 [salt.utils.lazy  ][DEBUG   ][102441] LazyLoaded rackspace.list_locations
2017-03-01 21:06:10,304 [salt.cloud       ][INFO    ][102368] Destroying in non-parallel mode.
2017-03-01 21:06:10,307 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded cloud.fire_event
2017-03-01 21:06:10,308 [salt.utils.event ][DEBUG   ][102368] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2017-03-01 21:06:10,308 [salt.utils.event ][DEBUG   ][102368] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2017-03-01 21:06:10,309 [salt.transport.ipc][DEBUG   ][102368] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
2017-03-01 21:06:12,054 [salt.loaded.int.clouds.vmware][INFO    ][102368] Destroying VM db6
2017-03-01 21:06:12,075 [salt.utils.vmware][DEBUG   ][102368] [ db6 ] Waiting for destroy task to finish [0 s]
2017-03-01 21:06:13,086 [salt.utils.vmware][DEBUG   ][102368] [ db6 ] Successfully completed destroy task in 1 seconds
2017-03-01 21:06:13,091 [salt.utils.event ][DEBUG   ][102368] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2017-03-01 21:06:13,092 [salt.utils.event ][DEBUG   ][102368] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2017-03-01 21:06:13,092 [salt.transport.ipc][DEBUG   ][102368] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
2017-03-01 21:06:14,121 [salt.utils.lazy  ][DEBUG   ][102368] LazyLoaded nested.output
2017-03-01 21:06:15,322 [salt.cloud.cli   ][INFO    ][102455] salt-cloud starting
2017-03-01 21:06:15,553 [salt.utils.lazy  ][DEBUG   ][102455] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
2017-03-01 21:06:15,554 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded parallels.avail_locations
2017-03-01 21:06:15,554 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded proxmox.avail_sizes
2017-03-01 21:06:15,555 [salt.utils.lazy  ][DEBUG   ][102455] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
2017-03-01 21:06:15,556 [salt.utils.lazy  ][DEBUG   ][102455] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
2017-03-01 21:06:15,557 [salt.utils.lazy  ][DEBUG   ][102455] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
2017-03-01 21:06:15,558 [salt.utils.lazy  ][DEBUG   ][102455] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
2017-03-01 21:06:15,558 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded rackspace.reboot
2017-03-01 21:06:15,558 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded openstack.list_locations
2017-03-01 21:06:15,559 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded rackspace.list_locations
2017-03-01 21:06:15,560 [salt.config      ][DEBUG   ][102455] Missing configuration file: /etc/salt/master
2017-03-01 21:06:15,561 [salt.config      ][DEBUG   ][102455] Guessing ID. The id can be explicitly set in /etc/salt/minion
2017-03-01 21:06:15,580 [salt.config      ][DEBUG   ][102455] Found minion id from generate_minion_id(): il-autoslave-lp1.example.local
2017-03-01 21:06:15,582 [salt.config      ][DEBUG   ][102455] Missing configuration file: /etc/salt/master
2017-03-01 21:06:15,865 [salt.loaded.int.grains.core][WARNING ][102455] Although 'virt-what' was found in path, the current user cannot execute it. Grains output might not be accurate.
2017-03-01 21:06:15,912 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded jinja.render
2017-03-01 21:06:15,914 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded yaml.render
2017-03-01 21:06:15,916 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded jinja.render
2017-03-01 21:06:15,916 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded yaml.render
2017-03-01 21:06:15,917 [salt.template    ][DEBUG   ][102455] compile template: ./tests/configuration/map.sls
2017-03-01 21:06:15,917 [salt.utils.jinja ][DEBUG   ][102455] Jinja search path: ['/var/cache/salt/cloud/files/base']
2017-03-01 21:06:15,921 [salt.template    ][PROFILE ][102455] Time (in seconds) to render './tests/configuration/map.sls' using 'jinja' renderer: 0.00416803359985
2017-03-01 21:06:15,921 [salt.template    ][DEBUG   ][102455] Rendered data from file: ./tests/configuration/map.sls:
db:
    - db6:
        datastore: RP-RND
        devices:
            network:
                Network adapter 1:
                    name: NETWORK1
                    switch_type: distributed
                    ip: 192.168.1.138
                    gateway: [192.168.1.254]
                    subnet_mask: 255.255.255.0
                    domain: example.com


2017-03-01 21:06:15,926 [salt.loaded.int.render.yaml][DEBUG   ][102455] Results of YAML rendering: 
OrderedDict([('db', [OrderedDict([('db6', OrderedDict([('datastore', 'RP-RND'), ('devices', OrderedDict([('network', OrderedDict([('Network adapter 1', OrderedDict([('name', 'NETWORK1'), ('switch_type', 'distributed'), ('ip', '192.168.1.138'), ('gateway', ['192.168.1.254']), ('subnet_mask', '255.255.255.0'), ('domain', 'example.com')]))]))]))]))])])])
2017-03-01 21:06:15,926 [salt.template    ][PROFILE ][102455] Time (in seconds) to render './tests/configuration/map.sls' using 'yaml' renderer: 0.00450801849365
2017-03-01 21:06:15,926 [salt.cloud.cli   ][INFO    ][102455] Applying map from './tests/configuration/map.sls'.
2017-03-01 21:06:15,927 [salt.utils.lazy  ][DEBUG   ][102455] Could not LazyLoad vmware.optimize_providers: 'vmware.optimize_providers' is not available.
2017-03-01 21:06:15,928 [salt.cloud       ][DEBUG   ][102455] The 'vmware' cloud driver is unable to be optimized.
2017-03-01 21:06:15,987 [salt.utils.lazy  ][DEBUG   ][102499] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
2017-03-01 21:06:15,987 [salt.utils.lazy  ][DEBUG   ][102499] LazyLoaded parallels.avail_locations
2017-03-01 21:06:15,988 [salt.utils.lazy  ][DEBUG   ][102499] LazyLoaded proxmox.avail_sizes
2017-03-01 21:06:15,989 [salt.utils.lazy  ][DEBUG   ][102499] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
2017-03-01 21:06:15,990 [salt.utils.lazy  ][DEBUG   ][102499] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
2017-03-01 21:06:15,990 [salt.utils.lazy  ][DEBUG   ][102499] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
2017-03-01 21:06:15,992 [salt.utils.lazy  ][DEBUG   ][102499] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
2017-03-01 21:06:15,993 [salt.utils.lazy  ][DEBUG   ][102499] LazyLoaded rackspace.reboot
2017-03-01 21:06:15,993 [salt.utils.lazy  ][DEBUG   ][102499] LazyLoaded openstack.list_locations
2017-03-01 21:06:15,993 [salt.utils.lazy  ][DEBUG   ][102499] LazyLoaded rackspace.list_locations
2017-03-01 21:06:17,358 [salt.cloud       ][INFO    ][102455] Calculating dependencies for db6
2017-03-01 21:06:17,358 [salt.cloud       ][DEBUG   ][102455] Got execution order 0 for db6
2017-03-01 21:06:17,358 [salt.cloud       ][DEBUG   ][102455] No make_master found in map
2017-03-01 21:06:17,362 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded cloud.fire_event
2017-03-01 21:06:17,362 [salt.utils.event ][DEBUG   ][102455] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2017-03-01 21:06:17,363 [salt.utils.event ][DEBUG   ][102455] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2017-03-01 21:06:17,363 [salt.transport.ipc][DEBUG   ][102455] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
2017-03-01 21:06:19,062 [salt.loaded.int.clouds.vmware][DEBUG   ][102455] Using folder in which vm agents-centos6-template is present
2017-03-01 21:06:19,536 [salt.loaded.int.clouds.vmware][DEBUG   ][102455] clone_spec set to:
(vim.vm.CloneSpec) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   location = (vim.vm.RelocateSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      service = <unset>,
      folder = <unset>,
      datastore = 'vim.Datastore:datastore-35300',
      diskMoveType = <unset>,
      pool = 'vim.ResourcePool:resgroup-26254',
      host = <unset>,
      disk = (vim.vm.RelocateSpec.DiskLocator) [],
      transform = <unset>,
      deviceChange = (vim.vm.device.VirtualDeviceSpec) [],
      profile = (vim.vm.ProfileSpec) []
   },
   template = false,
   config = (vim.vm.ConfigSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      changeVersion = <unset>,
      name = <unset>,
      version = <unset>,
      uuid = <unset>,
      instanceUuid = <unset>,
      npivNodeWorldWideName = (long) [],
      npivPortWorldWideName = (long) [],
      npivWorldWideNameType = <unset>,
      npivDesiredNodeWwns = <unset>,
      npivDesiredPortWwns = <unset>,
      npivTemporaryDisabled = <unset>,
      npivOnNonRdmDisks = <unset>,
      npivWorldWideNameOp = <unset>,
      locationId = <unset>,
      guestId = <unset>,
      alternateGuestName = <unset>,
      annotation = <unset>,
      files = <unset>,
      tools = <unset>,
      flags = <unset>,
      consolePreferences = <unset>,
      powerOpInfo = <unset>,
      numCPUs = <unset>,
      numCoresPerSocket = <unset>,
      memoryMB = <unset>,
      memoryHotAddEnabled = <unset>,
      cpuHotAddEnabled = <unset>,
      cpuHotRemoveEnabled = <unset>,
      virtualICH7MPresent = <unset>,
      virtualSMCPresent = <unset>,
      deviceChange = (vim.vm.device.VirtualDeviceSpec) [
         (vim.vm.device.VirtualDeviceSpec) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            operation = 'edit',
            fileOperation = <unset>,
            device = (vim.vm.device.VirtualVmxnet3) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 4000,
               deviceInfo = (vim.Description) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  label = 'Network adapter 1',
                  summary = 'NETWORK1'
               },
               backing = (vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  port = (vim.dvs.PortConnection) {
                     dynamicType = <unset>,
                     dynamicProperty = (vmodl.DynamicProperty) [],
                     switchUuid = '57 4e 1c 50 2e 1f bf b6-1f f1 76 bd 13 2a da e3',
                     portgroupKey = 'dvportgroup-26408',
                     portKey = <unset>,
                     connectionCookie = <unset>
                  }
               },
               connectable = (vim.vm.device.VirtualDevice.ConnectInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  startConnected = true,
                  allowGuestControl = true,
                  connected = false,
                  status = 'untried'
               },
               slotInfo = (vim.vm.device.VirtualDevice.PciBusSlotInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  pciSlotNumber = 160
               },
               controllerKey = 100,
               unitNumber = 7,
               addressType = 'assigned',
               macAddress = '00:50:56:9c:14:86',
               wakeOnLanEnabled = true,
               resourceAllocation = (vim.vm.device.VirtualEthernetCard.ResourceAllocation) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  reservation = 0L,
                  share = (vim.SharesInfo) {
                     dynamicType = <unset>,
                     dynamicProperty = (vmodl.DynamicProperty) [],
                     shares = 50,
                     level = 'normal'
                  },
                  limit = -1L
               },
               externalId = <unset>,
               uptCompatibilityEnabled = false
            },
            profile = (vim.vm.ProfileSpec) [],
            backing = <unset>
         }
      ],
      cpuAllocation = <unset>,
      memoryAllocation = <unset>,
      latencySensitivity = <unset>,
      cpuAffinity = <unset>,
      memoryAffinity = <unset>,
      networkShaper = <unset>,
      cpuFeatureMask = (vim.vm.ConfigSpec.CpuIdInfoSpec) [],
      extraConfig = (vim.option.OptionValue) [],
      swapPlacement = <unset>,
      bootOptions = <unset>,
      vAppConfig = <unset>,
      ftInfo = <unset>,
      repConfig = <unset>,
      vAppConfigRemoved = <unset>,
      vAssertsEnabled = <unset>,
      changeTrackingEnabled = <unset>,
      firmware = <unset>,
      maxMksConnections = <unset>,
      guestAutoLockEnabled = <unset>,
      managedBy = <unset>,
      memoryReservationLockedToMax = <unset>,
      nestedHVEnabled = <unset>,
      vPMCEnabled = <unset>,
      scheduledHardwareUpgradeInfo = <unset>,
      vmProfile = (vim.vm.ProfileSpec) [],
      messageBusTunnelEnabled = <unset>,
      crypto = <unset>,
      migrateEncryption = <unset>
   },
   customization = (vim.vm.customization.Specification) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      options = <unset>,
      identity = (vim.vm.customization.LinuxPrep) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         hostName = (vim.vm.customization.FixedName) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            name = 'db6'
         },
         domain = 'local',
         timeZone = <unset>,
         hwClockUTC = <unset>
      },
      globalIPSettings = (vim.vm.customization.GlobalIPSettings) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         dnsSuffixList = (str) [],
         dnsServerList = (str) []
      },
      nicSettingMap = (vim.vm.customization.AdapterMapping) [
         (vim.vm.customization.AdapterMapping) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            macAddress = <unset>,
            adapter = (vim.vm.customization.IPSettings) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               ip = (vim.vm.customization.FixedIp) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = '192.168.1.138'
               },
               subnetMask = '255.255.255.0',
               gateway = (str) [
                  '192.168.1.254'
               ],
               ipV6Spec = <unset>,
               dnsServerList = (str) [],
               dnsDomain = 'example.com',
               primaryWINS = <unset>,
               secondaryWINS = <unset>,
               netBIOS = <unset>
            }
         }
      ],
      encryptionKey = (byte) []
   },
   powerOn = true,
   snapshot = <unset>,
   memory = <unset>
}
2017-03-01 21:06:19,537 [salt.utils.event ][DEBUG   ][102455] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2017-03-01 21:06:19,537 [salt.utils.event ][DEBUG   ][102455] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2017-03-01 21:06:19,537 [salt.transport.ipc][DEBUG   ][102455] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
2017-03-01 21:06:20,564 [salt.loaded.int.clouds.vmware][INFO    ][102455] Creating db6 from vm(agents-centos6-template)
2017-03-01 21:06:20,613 [salt.loaded.int.clouds.vmware][ERROR   ][102455] Error creating db6: exceptions must be old-style classes or derived from BaseException, not NoneType
Traceback (most recent call last):
  File "/home/jenkins/saltsible/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 2613, in create
    salt.utils.vmware.wait_for_task(task, vm_name, 'clone', 5, 'info')
  File "/home/jenkins/saltsible/lib/python2.7/site-packages/salt/utils/vmware.py", line 936, in wait_for_task
    raise task.info.error
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
2017-03-01 21:06:20,616 [salt.cloud.cli   ][INFO    ][102455] Complete
2017-03-01 21:06:20,619 [salt.utils.lazy  ][DEBUG   ][102455] LazyLoaded nested.output
```

### Versions Report

```
$ salt-cloud --versions
Salt Version:
            Salt: 2016.11.3
 
Dependency Versions:
 Apache Libcloud: Not Installed
            cffi: 1.9.1
        cherrypy: Not Installed
        dateutil: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8.1
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: Not Installed
       pycparser: 2.17
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
    python-gnupg: Not Installed
          PyYAML: 3.12
           PyZMQ: 16.0.2
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.4.2
             ZMQ: 4.1.6
 
System Versions:
            dist: centos 7.3.1611 Core
         machine: x86_64
         release: 3.10.0-514.6.1.el7.x86_64
          system: Linux
         version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment] 2017-03-02 22:03
@borisovano this is related to https://github.com/saltstack/salt/issues/18510 which is an issue being tracked to help standardized exit codes within salt. This is also a duplicate of https://github.com/saltstack/salt/issues/27200 which is related to salt-cloud which encompasses not returning the correct exit code in salt-cloud when running into errors. I will close this issue so we can track this issue with 27200

**Closed by Ch3LL** 2017-03-02 22:03 UTC
