### ISSUE TITLE
Running salt minion as non-root with sudo hit concurrency error when running state.apply.

### ISSUE THREAD

**Issue by lweiyen** [saltstack/salt#37572] opened 2016-11-09 06:01 UTC
### Description of Issue/Question

When running state.apply with a minion setup to run under a non-root account with sudo to root, an error related to concurrent job running is always returned.

### Setup

Minion config is setup to run as non-root and sudo to root:

```
user: sysadm
sudo_user: root
```

Example sls files used:

banner.sls

```
/etc/issue:
  file.managed:
    - source: salt://issue
    - user: root
    - group: root
    - mode: 644
```

top.sls

```
base:
  '*':
    - banner
    - nsswitch
```

All relevant directories and files are chown-ed to sysadm.

### Steps to Reproduce Issue 

```
$ salt sm2adm1 state.apply banner
sm2adm1:
    Data failed to compile:
\----------
The function "state.apply" is running as PID 16027 and was started at 2016,  Nov 08 17:30:10.414707 with jid 20161108173010414707
```

The error is usually encountered when a previous job of the same function (in this case “state.apply”) is still running.

When we examine the relevant job list the single state.apply actually spawned two jobs in quick succession:

```
20161108173010414707:
    ----------
    Arguments:
        - banner
    Function:
        state.apply
    StartTime:
        2016, Nov 08 17:30:10.414707
    Target:
        sm2adm1
    Target-type:
        glob
    User:
        root

20161108173011457487:
    ----------
    Arguments:
        - banner
        - __pub_user=root
        - __pub_arg=['banner']
        - __pub_fun=state.apply
        - __pub_jid=20161108173010414707
        - __pub_tgt=sm2adm1
        - __pub_tgt_type=glob
        - __pub_ret=
    Function:
       state.apply
    StartTime:
        2016, Nov 08 17:30:11.457487
    Target:
        sm2adm1
    Target-type:
        glob
    User:
        root
```

This is different from when the minion is run as root where only one job is spawned without hitting issue

```
20161108175129983272:
    ----------
    Arguments:
        - banner
    Function:
        state.apply
    StartTime:
        2016, Nov 08 17:51:29.983272
    Target:
        sm2adm1
    Target-type:
        glob
    User:
        Root
```

We may workaround the issue running state.apply a single sls file by using concurrency=true.

```
$ salt sm2adm1 state.apply banner concurrent=true
sm2adm1:
\----------
          ID: /etc/issue
    Function: file.managed
      Result: True
     Comment: File /etc/issue is in the correct state
     Started: 10:16:07.363737
    Duration: 37.933 ms
     Changes:
Summary for sm2adm1
\------------
Succeeded: 1
Failed:    0
\------------
Total states run:     1
Total run time:  37.933 ms
```

However the issue remains when running highstate even with concurrency=true.

```
$ salt sm2adm1 state.apply concurrency=true
sm2adm1:
    Data failed to compile:
\----------
    The function "state.apply" is running as PID 18242 and was started at 2016, Nov 09 13:44:10.856471 with jid 20161109134410856471
```

```
$ salt sm2adm1 state.highstate concurrency=true
sm2adm1:
    Data failed to compile:
\----------
    The function "state.highstate" is running as PID 18336 and was started at 2016, Nov 09 13:44:19.397445 with jid 20161109134419397445
```

### Versions Report

```
Salt Version:
           Salt: 2016.3.4
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 21 2015, 00:39:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
System Versions:
           dist: oracle 7.2
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: Oracle Linux Server 7.2
```

**Comment by Ch3LL** [comment] 2016-11-09 21:23
@lweiyen looks like this is a duplicate of #25842 ill close this issue here and we can track this issue there. Thanks

**Closed by Ch3LL** 2016-11-09 21:23 UTC
