### ISSUE TITLE
feature request: relative salt:// paths

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#4348] opened 2013-04-02 07:28 UTC
I find myself repeatedly typing the same salt:// path:
```
munin-mysql-plugin:
  file.managed:
    - name: /usr/share/munin/plugins/mysql
    - source: salt://machine/database/munin-mysql/mysql

munin-mysql-config:
  file.managed:
    - name: /etc/munin/plugin-conf.d/mysql.conf
    - source: salt://machine/database/munin-mysql/mysql
```
Wouldn't it be useful to have a relative salt:// specifier like @ or $ that would be replaced with the 'current path' or the path of the .sls file file within the file_root?

salt://@/mysql would then be the mysql file in the same dir as the .sls is. Saves a lot of typing and makes re-using a state easier.

**Comment by v6** [comment] 2015-01-27 01:53
Why not just use Jinja2?

**Comment by lorengordon** [comment] 2015-02-21 14:22
@clinta, nice! If you need to get the path for an sls other than init.sls, try this:

```yaml
    - source: salt://{{ sls.split('.')[:-1] | join('/') }}/files/foo
```

That will take {{ sls }}, cut off the item following the last '.', and then join them with '/' to construct a path.

This one should work for any sls that is *not* init.sls. :/

**Comment by VynceMontgomery** [comment] 2015-04-16 04:06
relative paths for the destination would also be potentially useful, especially to deal with things like different OSs putting home directories in different places (and some special users having homedirs in arbitrary places).

**Comment by v6** [comment] 2015-04-16 05:08
// , This is one of my favorite feature requests. 

I can't help but think that there must be some sort of way to script this myself.

**Comment by aboe76** [comment] 2015-05-19 20:47
If salt is reading the sls file in question there should also be a path about this file known,
otherwise how is salt reading this file.
this information should be made available as a {{ pwd }} 
and if you want to use it just use salt://{{ pwd }}/files

Why use {{ pwd }} anybody that has done something on a linux box should know about pwd, and what it stands for. this way the formula creator can always deduct where its working directory.

**Comment by aneeshusa** [comment] 2015-06-09 08:14
Just looked into this, apparently @steverweber fixed this a year ago in #14535 :+1: . Also see #815, which is a partial dupe of this.

Motion to close with the ability to use {{ slspath }}.

**Comment by Mrten** [comment] 2015-06-09 10:13
I'd like to test before closing but some minions are still on 2014.1 which does not have {{slspath}}. Also, I'm wondering whether mako got the slspath var?

**Comment by lorengordon** [comment] 2015-06-09 10:13
@aneeshusa, I didn't realize that made it into 2015.5. I'll test it this week.

**Comment by aneeshusa** [comment] 2015-06-09 10:22
As far as I can tell, the slspath context variable should be available for mako as well as for the other renderers that are wrapped in salt/utils/template.py, although you should try it out to make sure.

And yes, this got merged in August 2014 so I believe it should be available in 2015.5 and up.

Also out of curiosity, is 2014.1 still supported/how many versions does Salt support at a time?

**Comment by steverweber** [comment] 2015-06-09 12:00
Use tplpath and tpldir.  I'll give a good example in a few hour

**Comment by steverweber** [comment] 2015-06-09 12:56
here is a pillar dir:
 - vars.jinja
 - db.sls
 - app.sls
 - fe.sls

vars.jinja
```
{% load_yaml as vars %}
    database:
        host: oat-db.private.uwaterloo.ca
        port: 5432
        name: odyssey
        user: _oat_ui
        password: {{ salt['nacl.dec']('ur5MzPTVwdU/pUs0XMUGHBe3GjbbCuzSaWQ5KlKLFcESlhU8EuOTOOc42dFWrMinVgszswlPXf8P3OF9Po=') }}

    server:
        dns:
            oat-app-1.math.private.uwaterloo.ca:
            oat-app-2.math.private.uwaterloo.ca:
            oat-db-1.private.uwaterloo.ca:
            oat-db-2.private.uwaterloo.ca:
            oat-db.private.uwaterloo.ca:
            oat-fe-1.math.uwaterloo.ca:
            oat-feed-1.private.uwaterloo.ca:
        ha:
            fe: oat-fe-1.math.uwaterloo.ca
            db: oat-db.private.uwaterloo.ca
            feed: oat-feed-1.private.uwaterloo.ca
        lb:
            fe:
                oat-fe-1.math.uwaterloo.ca:
            app:
                oat-app-1.math.private.uwaterloo.ca:
                oat-app-2.math.private.uwaterloo.ca:
            db:
                oat-db-1.private.uwaterloo.ca:
                oat-db-2.private.uwaterloo.ca:
            feed:
                oat-feed-1.private.uwaterloo.ca:
{% endload %}
{# RENDER IP ADDRESSES FOR SERVERS.DNS #}
{%- for s in vars.server.dns %}
{%- do vars.server.dns.update({s: {'ip': salt['dnsutil.A'](s)[0]}}) %}
{%- endfor %}
```


db.sls
```
{%- from tpldir + '/vars.jinja' import vars %}

{{ sls }}.postgresql_ha:
    replica_user: _replication
    replica_password: {{ vars.database._replication }}
    # primary_host: {{ vars.server.ha.db }}
    primary_ipaddress: {{ vars.server.db_replication_link[grains['id']] }}
    primary_port: {{ vars.database.port }}
```

**Comment by steverweber** [comment] 2015-06-09 13:01
here is a state dir:
 - _sdl/postgres/package:
    - init.sls
    - vars.jinja

vars.jinja
```
{%- from salt['file.normpath'](tpldir + '/../vars.jinja') import vars as _parent %}


{% load_yaml as _vars %}
    Default:
        _sls: {{ tpldot }}
        _parent: {{ _parent }}
    Debian:
        pkgs: ['postgresql']
    RedHat:
        pkgs: ['postgresql-server']
{% endload %}


{%- set vars = _vars.get('Default', {}) %}
{%- do vars.update(_vars.get(grains.get('os_family'), {})) %}
{%- do vars.update(_vars.get(grains.get('os'), {})) %}
{%- do vars.update(_vars.get(grains.get('osfinger'), {})) %}
{%- set vars = salt['pillar.get'](tpldot, default=vars, merge=True) %}
```

init.sls
```
{%- from tpldir + '/vars.jinja' import vars %}


{{ sls }}:
    pkg.installed:
        - pkgs: {{ vars.pkgs }}
        - reload_modules: true
        - watch_in:
            - service: {{ vars._parent._sls }}.service


    {%- if grains.get('osfinger') == 'CentOS Linux-7' %}
    # Cent OS does not initdb after install unlike Debian. so we preform it.
    cmd.wait:
        - name: 'postgresql-setup initdb'
        ## old way: - name: 'service postgresql initdb'
        - watch:
            - pkg: {{ sls }}
        - watch_in:
            - service: {{ vars._parent._sls }}.service
    {%- endif %}
```

**Comment by steverweber** [comment] 2015-06-09 13:04
I have a rather advanced collection of formulas building up that I like to share with the salt community. 
Perhaps I'll put them up this week.  The collection uses tpldir in advanced ways that allow for more moulder states.

**Comment by Mrten** [comment] 2015-06-09 13:12
sure there's no external password in your first example?

**Comment by rallytime** [comment] 2015-06-09 14:28
@aneeshusa To answer your question about supported releases, we typically only have one supported release/stable branch running at a time. Currently that is the releases on the 2015.5 branch. The previous supported release branch was 2014.7, but as soon as 2015.5.0 was officially released, the 2014.7 branch moved into the "we will no longer be releasing from this branch". We'll still accept fixes there from the community, but we'd rather push people to use the newer supported branches/releases.

I think I have an open bug somewhere saying we need to document this, because this question comes up a lot. Let me see if I can find it.

**Comment by rallytime** [comment] 2015-06-09 14:31
Oh, I was thinking of this one: https://github.com/saltstack/salt/issues/21270 I'll comment there to also explain the "supported branch" part.

**Comment by aneeshusa** [comment] 2015-06-10 00:30
@steverweber Can you explain the difference between slspath and tpldir? slspath seems to work ok in my states and looks nicer to me/is easier to remember than tpldir.

Also, the [Jinja docs](http://jinja.pocoo.org/docs/dev/templates/#other-operators) say to prefer ~ over + for string concatenation, so that's what I've been using.

**Comment by steverweber** [comment] 2015-06-10 03:38
I added slspath to solve your current problem... but after a few months of development I hit other issues if I included or used "from" to import other jinja template files... because the included template would have the same value for the slspath where it would be more helpfull if the value was relative to the current jinja template file.  That is why I added tpldir.  the name is tpldir because tplpath was already used.

so...
tpldir works even if you are inside a jinja file that was included from another jinja template file.

b/parent/tpl2/vars.jinja
```
{%- from salt['file.normpath'](tpldir + '/../vars.jinja') import vars as _parent %}
{{ tpldir }} = b/parent/tpl2
{{ slspath }} = b/parent/tpl2
{{ _parent.tpldir }} = b/parent
{{ _parent.slspath }} = b/parent/tpl2   <<<<< that's the problem
```

b/parent/vars.jinja
```
{% set vars = { "tpldir": tpldir, "slspath": slspath } %}
```

**Comment by Mrten** [comment] 2015-06-10 07:39
Regarding verification: I'm stuck on #24525 atm.

**Comment by lorengordon** [comment] 2015-06-10 11:29
@steverweber, thanks for the clarification! I just tested `tpldir` (and the [other](https://github.com/saltstack/salt/blob/develop/salt/utils/templates.py#L84) `tpl` vars), and it works for me. :+1: for closing this issue.

It would maybe be nice to add the vars to the 'cheat sheet' [issue](https://github.com/saltstack/salt/issues/12292) documenting various variables...

**Comment by aneeshusa** [comment] 2015-06-10 11:46
Oh, I didn't even think about plain template files or importing from other files; in that case tpldir is more clear than slspath. :+1:

Also, as 2015.5 is what's currently supported, I think we can update the various salt-formulas and their documentation? Using tpldir is definitely better than hard coding values.

**Comment by rallytime** [comment] 2015-06-10 15:23
I think that since the original feature request has been implemented and is working in the current release branch (2015.5), I am going to close this issue. If other fine tuning or documentation needs to be added to the salt-formulas, etc., then separate issues can be filed to track those. That way we won't miss anything buried in the comments. Sound good?

**Comment by timcharper** [comment] 2015-10-05 19:33
This is only a partial solution :( `tpldir` should return `'.'` if formula is top-level, otherwise the abstraction breaks.

 ༼ ༎ຶ ෴ ༎ຶ༽

**Comment by DanyC97** [comment] 2015-10-30 12:29
@steverweber you said you have a collection of formulas, are you able to share it ? thanks !

**Comment by steverweber** [comment] 2015-11-09 14:41
@DanyC97 undergoing some massive refactoring, so wont be released for sometime.

**Comment by DanyC97** [comment] 2015-11-09 14:57
sure, thanks @steverweber

**Comment by timcharper** [comment] 2015-11-12 01:42
@rallytime Regarding the above referenced patch: I've tested locally and have confirmed fixes the issue for me. With it, I can use `tpldir` for formulas in any folder, including ones in the top-level root directory, `/srv/salt`.

**Closed** 2015-11-12 05:20 UTC
Labels: Feature
