### ISSUE TITLE
2015.8.0: salt-minion failover broken. Hangs forever when connecting to the second failover

### ISSUE THREAD

**Issue by hubez** [saltstack/salt#27152] opened 2015-09-16 02:00 UTC
Configure salt minion as:
```
master_type: failover
master:
  - 192.168.0.9
  - 192.168.0.10
```
Shutdown salt-master on 192.168.0.9.
Start salt-master on 192.168.0.10.

Run salt minion
```
# salt-minion -l debug
...
[WARNING ] Master ip address changed from 192.168.0.9 to 192.168.0.10
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', '192.168.0.10', 'tcp://192.168.0.10:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9595)
[DEBUG   ] Setting zmq_reconnect_ivl to '9595ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
```

And it will just hang there indefinitely. Funny thing is if you hit CTRL-C, it'll unstuck it.

```
^CException KeyboardInterrupt in <bound method AsyncZeroMQPubChannel.__del__ of <salt.transport.zeromq.AsyncZeroMQPubChannel object at 0x1acbb90>> ignored
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', '192.168.0.10', 'tcp://192.168.0.10:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', '192.168.0.10', 'tcp://192.168.0.10:4506', 'aes')
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', '192.168.0.10', 'tcp://192.168.0.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
...
```

and it will function properly.

I'm hoping this is high priority, this completely breaks multi-master failover topology. Anyone know any workarounds?

Thanks

**Comment by jfindlay** [comment] 2015-09-16 18:18
@hubez, thanks for the report.  There is no workaround that I know of at this point.  This could be related to #24243.

**Comment by russ-blaisdell** [comment] 2015-09-21 16:35
I have seen the same on RHEL7.  Tried many installs with 2015.8.0 and all have the same issue.  The same setup on UBUNTU 14 works fine.

**Comment by Ch3LL** [comment] 2015-11-09 21:24
@hubez just for clarification have you setup your multi-master setup following these instructions: https://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html . I am trying to replicate your issue and I need to know if you setup the PKI settings because you stated your  minion file only includes the failover and list of masters in the file. 

There has been some changes for multi master represented in this PR:  #28302 which fixed this issue: #21744 and I hope to determine if these changes will fix this issue. Although this issue does not include the failover option so I want to test your exact settings to ensure if this PR does fix the issue or not and then I will update this issue with the results.

**Comment by hubez** [comment] 2015-11-12 01:51
@Ch3LL I did a simpler setup. I followed: https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html

I have open authentication where the master will accept any minion connecting.
And I give both my servers the same private keys by just copying them.

**Comment by Ch3LL** [comment] 2015-11-12 20:26
@hubez thanks for the additional information. I tested on the head of 2015.8 which includes the fix for multi master and I am still seeing the same issue, but some differences in your initial issue report.  So unfortunately it appears there is a bug in failover multi-master. 

Here is my output form `salt-minion -l debug`:

```
[DEBUG   ] sync_connect_master
[INFO    ] Got list of available master addresses: ['45.79.106.92', '45.33.39.38']
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', '45.33.39.100', 'tcp://45.79.106.92:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5845)
[DEBUG   ] Setting zmq_reconnect_ivl to '5845ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', '45.33.39.100', 'tcp://45.79.106.92:4506', 'clear')
```

As shown above my salt-minion process on the head of 2015.8 gets stuck at `Initializing new AsyncZeroMQReqChannel` not `Setting zmq_reconnect*` Another difference is if I try to select CTRL+C as you explained it just exits out of the minion process and does not get unstuck.

@cachedout looks like the master to master failover has a similar bug to just the normal master to master setup, even while testing on the head of 2015.8 with the new fix.

**Comment by syedaali** [comment] 2015-11-13 04:30
I am encountering a similar problem but I have a single master, the minion hangs randomly.

root@ip:~# service salt-minion stop
salt-minion stop/waiting
root@ip:~# salt-call state.highstate -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'dashboard1-test', 'tcp://X.X.X.X:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5364)
[DEBUG   ] Setting zmq_reconnect_ivl to '5364ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'dashboard1-test', 'tcp://X.X.X.X:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'dashboard1-test', 'tcp://X.X.X.X:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'dashboard1-test', 'tcp://X.X.X.X:4506', 'clear')

**Comment by cachedout** [comment] 2015-11-23 19:18
@syedaali This issue is specifically about multi-master installations. If you're seeing this on a single-master, could you please open that as a separate bug so that we can keep track of each independently? Thanks.

**Comment by usernkey** [comment] 2015-12-04 16:23
This is exaxctly my issue too :(

[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'rhel7.cmnet.internal', 'tcp://10.1.10.109:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5140)
[DEBUG   ] Setting zmq_reconnect_ivl to '5140ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'rhel7.cmnet.internal', 'tcp://10.1.10.109:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'rhel7.cmnet.internal', 'tcp://10.1.10.109:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'rhel7.cmnet.internal', 'tcp://10.1.10.109:4506', 'clear')
[WARNING ] SaltReqTimeoutError: Message timed out
Minion failed to authenticate with the master, has the minion key been accepted?
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 714, in remove_handler
    self._impl.unregister(fd)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "/usr/lib64/python2.7/site-packages/zmq/sugar/poll.py", line 71, in unregister
    idx = self._map.pop(socket)
KeyError: None

**Comment by basepi** [comment] 2016-01-07 16:57
I think this is a duplicate of #24243. I'm going to close this one and we can follow up there.

**Closed by basepi** 2016-01-07 16:57 UTC
Labels: Bug, Core, Critical, Multi-Master, P1
