### ISSUE TITLE
[BUG] "unless" not firing in 3000.3

### ISSUE THREAD

**Issue by udf2457** [saltstack/salt#57336] opened 2020-05-16 13:29 UTC
No matter the syntax I attempt, it seems that `unless` is being ignored and the state is being run.

I have tried:
```
pg12-dirempty:
  cmd.run:
    - names:
      - rm -rf /var/lib/postgresql/12/main/*
    - require:
      - pg12-shutdown
    - unless:
      - fun: file.file_exists
        path: /var/lib/postgresql/12/main/standby.signal
```

and

```
pg12-dirempty:
  cmd.run:
    - names:
      - rm -rf /var/lib/postgresql/12/main/*
    - require:
      - pg12-shutdown
    - unless: test -f /var/lib/postgresql/12/main/standby.signal
```

and

```
pg12-shutdown:
   service.dead:
    - name: postgresql
    - unless:
      - fun: file.file_exists
        path: /var/lib/postgresql/12/main/standby.signal
    - prereq:
      - pg12-dirempty

pg12-dirempty:
  cmd.run:
    - names:
      - rm -rf /var/lib/postgresql/12/main/*
    - unless:
      - fun: file.file_exists
        path: /var/lib/postgresql/12/main/standby.signal
```

But the result is always the same, the state gets fired:
```
----------                                                                                                                                                 
          ID: pg12-shutdown                                                                                                                                
    Function: service.dead                                                                                                                                 
        Name: postgresql                                                                                                                                   
      Result: True                                                                                                                                         
     Comment: Service postgresql was killed                                                                                                                
     Started: 14:17:07.730268                                                                                                                              
    Duration: 63.738 ms                                                                                                                                    
     Changes:                                                                                                                                              
              ----------                                                                                                                                   
              postgresql:                                                                                                                                  
                  False                                                                                                                                    
----------                                                                                                                                                 
          ID: pg12-dirempty                                                                                                                                
    Function: cmd.run                                                                                                                                      
        Name: rm -rf /var/lib/postgresql/12/main/*                                                                                                         
      Result: True                                                                                                                                         
     Comment: Command "rm -rf /var/lib/postgresql/12/main/*" run                                                                                           
     Started: 14:17:07.795876                                                                                                                              
    Duration: 59.113 ms                                                                                                                                    
     Changes:                                                                                                                                              
              ----------                                                                                                                                   
              pid:                                                                                                                                         
                  793                                                                                                                                      
              retcode:                                                                                                                                     
                  0                                                                                                                                        
              stderr:                                                                                                                                      
              stdout:  
```

**Comment by whytewolf** [comment] 2020-05-18 21:01
so the issue is `cmd.run` has it's own `mod_run_check`. This is more of a documentation bug then a code bug. See https://github.com/saltstack/salt/pull/51846#issuecomment-497913069 for a list of modules that use there own `mod_run_check`.

However your test of the file using bash is the one that is odd. here is my own test from 3000.3

```
[root@salt00 test]# cat unless.sls
testing:
  cmd.run:
    - name: echo test
    - unless:
      - fun: file.file_exists
        path: /tmp/testfile
testing2:
  cmd.run:
    - name: echo test
    - unless: test -f /tmp/testfile
[root@salt00 test]# salt-call state.apply test.unless
local:
----------
          ID: testing
    Function: cmd.run
        Name: echo test
      Result: True
     Comment: Command "echo test" run
     Started: 21:39:24.967311
    Duration: 20.949 ms
     Changes:
              ----------
              pid:
                  31948
              retcode:
                  0
              stderr:
              stdout:
                  test
----------
          ID: testing2
    Function: cmd.run
        Name: echo test
      Result: True
     Comment: unless condition is true
     Started: 21:39:24.988654
    Duration: 9.395 ms
     Changes:
Summary for local
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time:  30.344 ms
```

as can be seen the fun.file_exists doesn't trigger the unless, but the bash test works fine. Which is expected behavior.

We are going to need to see the exit code of `test -f  /var/lib/postgresql/12/main/standby.signal` on the minion in question. should be easy just `test -f  /var/lib/postgresql/12/main/standby.signal; echo $?`

**Comment by mchugh19** [comment] 2020-05-19 07:28
To backup @whytewolf, the custom requisite behavior of cmd.run has been unified with the rest of salt as of https://github.com/saltstack/salt/pull/55974. So in Sodium and on, all the requisite syntaxes (including use of salt execution modules) should work for cmd.run, just list any other state. 

For version 3000, cmd.run only support shell tests for unless. So your `unless: test -f /var/lib/postgresql/12/main/standby.signal` should be the correct syntax to cause cmd.run to not execute if that file exists.

**Comment by whytewolf** [comment] 2023-09-08 19:27
Lets go ahead and close this now. it has been 3 years and no follow up and looks to be expected behavior for the version involved.

**Closed by whytewolf** 2023-09-08 19:27 UTC
Labels: Pending-Discussion
