### ISSUE TITLE
Error when trying to use extend in cloud provider conf

### ISSUE THREAD

**Issue by sunstick** [saltstack/salt#31304] opened 2016-02-18 09:06 UTC
Hi,

I am trying to use the extend feature documented in https://docs.saltstack.com/en/develop/topics/cloud/config.html#extending-profiles-and-cloud-providers-configuration

My setup is that I have an `aws.conf` in /etc/salt/cloud.providers.d/ and it looks like the following

```
general-ec2:
  driver: ec2
  id: use-instance-role-credentials
  key: use-instance-role-credentials
  private_key: /etc/salt/salt_cloud_key
  keyname: salt_minion_key
  location: us-west-2

my-ec2:
  extends: general-ec2
  image: ami-86e605b5
```

However, when using this I got the following error
```
salt-cloud: error: The '-only-extendable-0' cloud provider entry in 'analytics-ec2' is trying to extend from 'aws-ec2' and no provider was specified. Not extending!
```

Any ideas what's going on here? What did I do wrong?

Thanks in advance for the help.

**Comment by rallytime** [comment] 2016-02-18 15:38
@sunstick Can you post the output of `salt-cloud --versions`? Also, if you change the word `driver` to `provider` in the `general-ec2` section, do you get the same error? I am wondering if that is where there might be a bug.

**Comment by sunstick** [comment] 2016-02-18 15:52
@rallytime Thanks for the reply. This is my `salt-cloud --versions` output

```
Salt Version:
            Salt: 2015.8.3

Dependency Versions:
 Apache Libcloud: 0.15.1
          Jinja2: 2.7.2
        M2Crypto: Not Installed
            Mako: 0.9.1
          PyYAML: 3.10
           PyZMQ: 15.1.0
          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.2
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.4.2
           gitdb: 0.5.4
       gitpython: 0.3.2 RC1
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.3.0
    mysql-python: 1.2.3
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: 0.8.2
         timelib: Not Installed

System Versions:
            dist: Ubuntu 14.04 trusty
         machine: x86_64
         release: 3.13.0-48-generic
          system: Ubuntu 14.04 trusty
```

I will try to change `driver` to `provider`

**Comment by sunstick** [comment] 2016-02-18 16:00
@rallytime changed `driver` to `provider`. Saw the same error message.

**Comment by rallytime** [comment] 2016-02-18 16:21
@sunstick Ok thanks for the info. I was thinking that might have been where the sticking point was, but it looks like something else in the `extends` functionality.

**Comment by sunstick** [comment] 2016-02-20 18:08
@rallytime Found a workaround for this. If I specify `my-ec2`'s extend to be 'general-ec2:ec2', it actually works.

```
my-ec2:
  extends: general-ec2
  image: ami-86e605b5
```

**Comment by rallytime** [comment] 2016-02-20 18:31
@sunstick Oh! You're right. That's how providers are supposed to be extended. I just forgot about that difference. It's documented [here](https://docs.saltstack.com/en/latest/topics/cloud/config.html#extending-providers).

Since this is working as intended, I'm tempted to close this. Unless there is something you can think of in the docs where we can make this more clear?

**Comment by sunstick** [comment] 2016-02-20 19:16
@rallytime Feel free to close this. I think when I first looked at the document, my impression was the `:` notation is only necessary when the provider to be extended has more than 1 driver.

**Comment by rallytime** [comment] 2016-02-20 19:37
Sounds good. Thanks @sunstick!

**Closed by rallytime** 2016-02-20 19:37 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P3, RIoT, Salt-Cloud
