### ISSUE TITLE
Regression in file.managed with source_hash

### ISSUE THREAD

**Issue by mafrosis** [saltstack/salt#27397] opened 2015-09-25 08:30 UTC
Test case:

```
s3proxy-install:
  file.managed:
    - name: /usr/local/bin/s3proxy
    - source: https://github.com/andrewgaul/s3proxy/releases/download/s3proxy-1.3.0/s3proxy
    - source_hash: sha1=805acf21aa9185e2539f6041ebe24b877f5b4284
```

In `2015.5.5`:

```
[INFO    ] Running state [/usr/local/bin/s3proxy] at time 09:06:11.482699
[INFO    ] Executing state file.managed for /usr/local/bin/s3proxy
[INFO    ] File changed:
New file
[INFO    ] Completed state [/usr/local/bin/s3proxy] at time 09:06:39.897139
local:
----------
          ID: s3proxy-install
    Function: file.managed
        Name: /usr/local/bin/s3proxy
      Result: True
     Comment: File /usr/local/bin/s3proxy updated
     Started: 09:06:11.482699
    Duration: 28414.44 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

In `2015.8.0`:

```
[INFO    ] Running state [/usr/local/bin/s3proxy] at time 09:06:11.482699
[INFO    ] Executing state file.managed for /usr/local/bin/s3proxy
[INFO    ] File changed:
New file
[INFO    ] Completed state [/usr/local/bin/s3proxy] at time 09:06:39.897139
local:
----------
          ID: s3proxy-install
    Function: file.managed
        Name: /usr/local/bin/s3proxy
      Result: False
     Comment: File sum set for file /usr/local/bin/s3proxy of 805acf21aa9185e2539f6041ebe24b877f5b4284 does not match real sum of e76791fc075adf7fd5dfd4a084ef1ccbe8f0fc6a
     Started: 09:20:34.400395
    Duration: 25107.115 ms
     Changes:
              ----------
              diff:
                  New file

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  25.107 s
```

**Comment by jfindlay** [comment] 2015-09-25 20:33
@mafrosis, thanks for the report.  I get the same result on 2015.8.0.  Also,
```console
# wget https://github.com/andrewgaul/s3proxy/releases/download/s3proxy-1.3.0/s3proxy
...

2015-09-25 14:30:39 (2.89 MB/s) - ‘s3proxy’ saved [7614984/7614984]
# sha1sum s3proxy 
805acf21aa9185e2539f6041ebe24b877f5b4284  s3proxy
```

**Comment by mafrosis** [comment] 2015-09-25 20:52
@jfindlay I didn't even think of trying that! Doh.

If I get time this weekend I might take a look at fixing this one.

**Comment by jfindlay** [comment] 2015-09-28 18:16
Thanks @mafrosis, that would be great.

**Comment by rhansen** [comment] 2016-03-22 08:46
The following four issues all seem to be the same bug:

  * #20681
  * #26981
  * #27397
  * #29010

I too am experiencing this with Salt 2015.8.7.

**Comment by terminalmage** [comment] 2016-11-02 17:21
I can't reproduce this on 2015.8.0, or any release for that matter.

```
# salt-call --version
salt-call 2015.8.0 (Beryllium)
# curl -sL https://github.com/andrewgaul/s3proxy/releases/download/s3proxy-1.3.0/s3proxy | sha1sum -
805acf21aa9185e2539f6041ebe24b877f5b4284  -
# salt-call --local -l debug state.single file.managed name=/tmp/test source=https://github.com/andrewgaul/s3proxy/releases/download/s3proxy-1.3.0/s3proxy source_hash=sha1=805acf21aa9185e2539f6041ebe24b877f5b4284
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /home/erik/saltdev/etc/salt/minion_id: tardis
12:18:15,960 [salt.utils.parsers][ 193][DEBUG   ][15136] Configuration file path: /etc/salt/minion
12:18:15,960 [salt.config][1340][DEBUG   ][15136] Reading configuration from /etc/salt/minion
12:18:15,963 [salt.config][1480][DEBUG   ][15136] Including configuration from '/etc/salt/minion.d/_schedule.conf'
12:18:15,964 [salt.config][1340][DEBUG   ][15136] Reading configuration from /etc/salt/minion.d/_schedule.conf
12:18:16,070 [salt.loaded.int.grains.core][ 486][DEBUG   ][15136] Please install 'virt-what' to improve results of the 'virtual' grain.
12:18:16,104 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded jinja.render
12:18:16,105 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded yaml.render
12:18:16,131 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded jinja.render
12:18:16,132 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded yaml.render
12:18:16,137 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded state.single
12:18:16,157 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded saltutil.is_running
12:18:16,167 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded jinja.render
12:18:16,168 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded yaml.render
12:18:16,178 [salt.state][ 738][INFO    ][15136] Loading fresh modules for state activity
12:18:16,189 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded jinja.render
12:18:16,190 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded yaml.render
12:18:16,193 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded file.managed
12:18:16,193 [salt.state][1506][INFO    ][15136] Running state [/tmp/test] at time 12:18:16.192895
12:18:16,193 [salt.state][1528][INFO    ][15136] Executing state file.managed for /tmp/test
12:18:16,194 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded config.manage_mode
12:18:16,200 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded file.source_list
12:18:16,201 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded cp.cache_file
12:18:16,203 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded roots.envs
12:18:16,271 [salt.utils.lazy][  92][DEBUG   ][15136] Could not LazyLoad roots.init
12:18:16,272 [salt.fileserver][ 411][DEBUG   ][15136] Updating roots fileserver cache
12:18:16,273 [salt.config][1340][DEBUG   ][15136] Reading configuration from /etc/salt/minion
12:18:16,277 [salt.config][1480][DEBUG   ][15136] Including configuration from '/etc/salt/minion.d/_schedule.conf'
12:18:16,277 [salt.config][1340][DEBUG   ][15136] Reading configuration from /etc/salt/minion.d/_schedule.conf
12:18:16,279 [salt.config][2650][DEBUG   ][15136] Using cached minion ID from /home/erik/saltdev/etc/salt/minion_id: tardis
12:18:16,280 [salt.utils.http][ 566][DEBUG   ][15136] file_roots is /home/erik/saltdev/srv/salt
12:18:16,280 [salt.utils.http][ 185][DEBUG   ][15136] Requesting URL https://github.com/andrewgaul/s3proxy/releases/download/s3proxy-1.3.0/s3proxy using GET method
12:18:21,046 [salt.state][ 225][INFO    ][15136] File changed:
New file
12:18:21,046 [salt.state][1640][INFO    ][15136] Completed state [/tmp/test] at time 12:18:21.045795
12:18:21,047 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded highstate.output
12:18:21,048 [salt.utils.lazy][  89][DEBUG   ][15136] LazyLoaded nested.output
local:
----------
          ID: /tmp/test
    Function: file.managed
      Result: True
     Comment: File /tmp/test updated
     Started: 12:18:16.192895
    Duration: 4852.9 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   4.853 s
# sha1sum /tmp/test
805acf21aa9185e2539f6041ebe24b877f5b4284  /tmp/test
```

**Comment by mafrosis** [comment] 2016-11-02 17:26
Wow yeah forgot about this report. I haven't seen this bug in a year, and I'm still using `2015.8.x` - so I would imagine it's been fixed along the way.

**Comment by The-Loeki** [comment] 2016-11-07 19:27
I've tested this after #37469 and the given example works fine now

**Comment by rallytime** [comment] 2016-11-07 19:44
Thanks for following up! Given the information above, I'll go ahead and close this up.

If it pops up again, don't hesitate to let us know.

**Closed by rallytime** 2016-11-07 19:44 UTC
Labels: Bug, Confirmed, High Severity, P2, Platform, Regression, State Module
