### ISSUE TITLE
[BUG] salt-master defunct after net-api runner_async

### ISSUE THREAD

**Issue by tibetsam** [saltstack/salt#63838] opened 2023-03-08 10:19 UTC
**Description**
there is zombie processes left with simply salt runner_async call

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

```
root@salt-master-64cb78499b-2vrx4:/srv/salt/orch# cat sam.sls
Trigger backup:
  salt.function:
    - name: test.ping
    - tgt: 'salt-master-minion'
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Steps to Reproduce the behavior**
```
root@salt-master-64cb78499b-2vrx4:/srv/salt/orch# curl -ks https://localhost:8001  -H "X-Auth-Token: e2d8138b224cb7674ecf57d88fd14bfa7bc55ce2" -H "Accept: application/json" -H "Content-type: application/json"     -d '{
        "client": "runner_async",
        "fun": "state.orchestrate",
        "arg": ["orch.sam"]
}'
{"return": [{"tag": "salt/run/20230308101554945482", "jid": "20230308101554945482"}]}root@salt-master-64cb78499b-2vrx4:/srv/salt/orch#
root@salt-master-64cb78499b-2vrx4:/srv/salt/orch# 2023-03-08 10:15:56,212 [salt.channel.client:427 ][DEBUG   ][120] PubChannel received: {'enc': 'aes', 'load': {'fun': 'test.ping', 'arg': [], 'tgt': 'salt-master-minion', 'jid': '20230308101556197766', 'ret': '', 'tgt_type': 'glob', 'user': 'root'}, 'sig': b'\x0e,\xcd]M\x13\xe3\x85\xc8\xd9Q\xfb<\xb1D\xa3\xc9\xad]; g\xf1\xab\xfb8\xd6\'\xde#\xd2\xd1\xd6\xca\x16K\xdd\xb8#j\x84\xfd\xab\x96\']\xd1\xc0\x01\x01\x97\xddz\xd9\xf0\x19\xa0\x83\xcfV=7g\xb5\x9ce>\xc0\x1f\x95m\xa7\x9e\x99\x12\xebe8?\xf61E\xabb\x96\x82\t2a\xc2\xc2m\xd4L\xea\xde\xb2\xec \x19\xf0\xfd\xa8\x1e#\xbf\x95v\x933O\x05\xc8\xba\xc1q\xa8~\xda)(t\x18\xc5\x19\x95\xfb\xdaN9\x8e$\xfc8\xb4)Q\x1e\xdd\xdb~\x12\xba>\xa4;I-@!\x0e\x8a\x9dk[A\xca\xf82\xd1\x8d\xc4\xc7\x99\xc3\x86:o\xfa\x94\xb19\xaa9\x1b\x10|\xa9\xaa\xba\xa9\x98\x8a\x14N\x04\x95\x16\xa8"bw\x96\x1c\xec\xda\xeeI\xb8\xc5U\x06\xe2\x16:w\x99\xfdx\x00\xdaA\xe5@O\x9f/\xbe\x94\xb3U\x97v3ZWKV\xd5\x8a\xcb\xab\x8f\xcb\x15\x94\xf0\x1a\x1fnEu\xaf\xa5zi\xa9\xf3\xa6\xc6\xaf(l\xbcHQ'}
2023-03-08 10:15:56,213 [salt.minion      :1709][INFO    ][120] User root Executing command test.ping with jid 20230308101556197766
2023-03-08 10:15:56,214 [salt.minion      :1717][DEBUG   ][120] Command details {'fun': 'test.ping', 'arg': [], 'tgt': 'salt-master-minion', 'jid': '20230308101556197766', 'ret': '', 'tgt_type': 'glob', 'user': 'root'}
2023-03-08 10:15:56,219 [salt.utils.process:1144][DEBUG   ][120] Subprocess ProcessPayload(jid=20230308101556197766) added
2023-03-08 10:15:56,303 [salt.loader.lazy :960 ][DEBUG   ][988] The functions from module 'jinja' are being loaded by dir() on the loaded module
2023-03-08 10:15:56,304 [salt.utils.lazy  :99  ][DEBUG   ][988] LazyLoaded jinja.render
2023-03-08 10:15:56,306 [salt.loader.lazy :960 ][DEBUG   ][988] The functions from module 'yaml' are being loaded by dir() on the loaded module
2023-03-08 10:15:56,306 [salt.utils.lazy  :99  ][DEBUG   ][988] LazyLoaded yaml.render
2023-03-08 10:15:56,310 [salt.minion      :1913][INFO    ][988] Starting a new job 20230308101556197766 with PID 988
2023-03-08 10:15:56,312 [salt.loader.lazy :960 ][DEBUG   ][988] The functions from module 'direct_call' are being loaded by dir() on the loaded module
2023-03-08 10:15:56,313 [salt.loader.lazy :960 ][DEBUG   ][988] The functions from module 'splay' are being loaded by dir() on the loaded module
2023-03-08 10:15:56,316 [salt.utils.lazy  :102 ][DEBUG   ][988] Could not LazyLoad direct_call.allow_missing_func: 'direct_call.allow_missing_func' is not available.
2023-03-08 10:15:56,318 [salt.loader.lazy :960 ][DEBUG   ][988] The functions from module 'test' are being loaded by dir() on the loaded module
2023-03-08 10:15:56,319 [salt.utils.lazy  :99  ][DEBUG   ][988] LazyLoaded test.ping
2023-03-08 10:15:56,320 [salt.loaded.int.module.test:120 ][DEBUG   ][988] test.ping received for minion 'salt-master-minion'
2023-03-08 10:15:56,320 [salt.minion      :2192][INFO    ][988] Returning information for job: 20230308101556197766
2023-03-08 10:15:56,322 [salt.utils.event :315 ][DEBUG   ][988] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_296b9b0042_pub.ipc
2023-03-08 10:15:56,322 [salt.utils.event :316 ][DEBUG   ][988] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_296b9b0042_pull.ipc
2023-03-08 10:15:56,325 [salt.utils.event :821 ][DEBUG   ][988] Sending event: tag = __master_req_channel_payload; data = {'cmd': '_return', 'id': 'salt-master-minion', 'success': True, 'return': True, 'retcode': 0, 'jid': '20230308101556197766', 'fun': 'test.ping', 'fun_args': [], '_stamp': '2023-03-08T10:15:56.325256'}
2023-03-08 10:15:56,326 [salt.transport.ipc:373 ][DEBUG   ][988] Closing IPCMessageClient instance
2023-03-08 10:15:56,327 [salt.minion      :2061][DEBUG   ][988] minion return: {'success': True, 'return': True, 'retcode': 0, 'jid': '20230308101556197766', 'fun': 'test.ping', 'fun_args': []}
2023-03-08 10:15:56,327 [salt.minion      :2690][DEBUG   ][120] Minion of '127.0.0.1' is handling event tag '__master_req_channel_payload'
2023-03-08 10:15:56,328 [salt.minion      :890 ][DEBUG   ][120] Minion return retry timer set to 10 seconds (randomized)
p2023-03-08 10:15:57,085 [salt.utils.process:1155][DEBUG   ][120] Subprocess ProcessPayload(jid=20230308101556197766) cleaned up
```

```
root@salt-master-64cb78499b-2vrx4:/srv/salt/orch# ps -ejHf
UID          PID    PPID    PGID     SID  C STIME TTY          TIME CMD
root          69       0      69      69  0 10:08 pts/0    00:00:00 bash
root         798      69     798      69  0 10:11 pts/0    00:00:00   tail -f /var/log/salt/minion
root        1004      69    1004      69  0 10:16 pts/0    00:00:00   ps -ejHf
root           1       0       1       1  0 10:08 ?        00:00:01 /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root          25       1      25      25  0 10:08 ?        00:00:00   /usr/bin/gcsfuse --foreground -o rw -o noexec -o nosuid -o nodev --key-file /root/storage_key.json radioswshare /mn
root          54       1      54      54  1 10:08 ?        00:00:06   /usr/bin/gcsfuse --foreground --key-file /root/storage_key.json -o rw -o noexec -o nosuid -o nodev --implicit-dirs
root          95       1      95      95  0 10:08 ?        00:00:00   /usr/bin/gcsfuse --foreground -o nodev --implicit-dirs --key-file /root/storage_key.json -o rw -o noexec -o nosuid
root         111       1       1       1  0 10:08 ?        00:00:00   bash -x /usr/local/bin/startup.sh
root         956     111       1       1  0 10:15 ?        00:00:00     sleep 60
root         117       1       1       1  0 10:08 ?        00:00:01   /usr/bin/python3 /usr/bin/salt-api --log-level=debug
root         142     117       1       1  2 10:08 ?        00:00:08     /usr/bin/python3 /usr/bin/salt-api --log-level=debug
root         118       1       1       1  0 10:08 ?        00:00:00   /usr/bin/python3 /usr/bin/salt-minion --log-level=debug
root         120     118       1       1  0 10:08 ?        00:00:01     /usr/bin/python3 /usr/bin/salt-minion --log-level=debug
root         150       1       1       1  0 10:08 ?        00:00:00   /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         151       1       1       1  0 10:08 ?        00:00:00   /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         154       1       1       1  0 10:08 ?        00:00:02   /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         155       1       1       1  0 10:08 ?        00:00:01   /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         156       1       1       1  0 10:08 ?        00:00:00   /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         158     156       1       1  0 10:08 ?        00:00:01     /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         159     156       1       1  0 10:08 ?        00:00:02     /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         162     156       1       1  0 10:08 ?        00:00:02     /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         163     156       1       1  0 10:08 ?        00:00:01     /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         171     156       1       1  0 10:08 ?        00:00:01     /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         172     156       1       1  0 10:08 ?        00:00:02     /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         177     156       1       1  0 10:08 ?        00:00:02     /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         836       1     836     836  0 10:12 ?        00:00:00   [salt-master] <defunct>
root         837       1     836     836  0 10:12 ?        00:00:01   [salt-master] <defunct>
root         933       1       1       1  0 10:14 ?        00:00:00   /usr/bin/python3 /usr/bin/salt-master --log-level=debug
root         963       1     963     963  0 10:15 ?        00:00:00   [salt-master] <defunct>
root         964       1     963     963 11 10:15 ?        00:00:01   [salt-master] <defunct>
```

**Expected behavior**
no zombie process

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
root@salt-master-64cb78499b-2vrx4:/srv/salt/orch# salt -V
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: 0.37.1
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.161+
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**

**Comment by tibetsam** [comment] 2023-03-15 14:48
Hi, 
is there any update? is this issue reproducible? 
Thanks

**Comment by Ch3LL** [comment] 2023-03-20 17:16
@tibetsam Is there some other bug associated with this? Do they keep accumulating or do they eventually go away?

**Comment by tibetsam** [comment] 2023-03-22 12:32
Hi @Ch3LL not really, perhaps, bcz we found saltrequesttime out with only 20+ minions when running state.orch, and yes, they are keep accumulating

**Comment by Ch3LL** [comment] 2023-05-12 15:22
Thanks for confirming. This has been set to be fixed in 3006.2 thanks

**Comment by tibetsam** [comment] 2023-06-12 08:32
Hi @Ch3LL ,

that is strange, i tried it again on my node, it is quite easy to reproduce.

1. we built our own container, here you can find the Dockerfile:
```dockerfile
FROM debian:11.2-slim
# package dependencies
COPY requirements.txt ./
RUN apt-get update \
    && apt-get install -y \
        git \
        curl \
        jq \
        patch \
        python3 \
        python3-pip \
        python3-packaging \
        ssh \
        gnupg \
        host \
        vim \
        less \
        unzip \
        rsync \
        screen \
        --no-install-recommends \
    && python3 -m pip install --upgrade pip \
    && python3 -m pip install --no-cache-dir --requirement requirements.txt \
    && curl https://repo.saltproject.io/py3/debian/11/amd64/archive/3004.1/salt-archive-keyring.gpg | apt-key add - \
    && echo "deb http://repo.saltproject.io/py3/debian/11/amd64/archive/3004.1 bullseye main" >> /etc/apt/sources.list.d/saltstack.list \
    && apt-get update \
    && apt-get install -y \
        salt-master=3004.1+ds-1 \
        salt-minion=3004.1+ds-1 \
        salt-ssh=3004.1+ds-1 \
        salt-api=3004.1+ds-1 \
        --no-install-recommends \
        python3-pygit2 \
        python3-openssl \
        python3-m2crypto \
        fuse \
    && hash -r pip \
    && python3 -m pip install --upgrade cherrypy \
    && apt-get clean

RUN mkdir /etc/salt/pki/ \
    && mkdir /etc/salt/pki/master \
    && salt-call --local tls.create_self_signed_cert

VOLUME ["/etc/salt/pki", "/var/cache/salt"]

# Copy the base config.
COPY etc/salt/master /etc/salt/master
COPY etc/salt/master.d /etc/salt/master.d

# Copy the key files into a temporary directory, because the persistent volume in k8s will overwrite the /etc/salt/pki directory. In run.sh the contents will be moved into the correct folder, before salt is started.
COPY etc/salt/pki/master/master_sign.* /etc/salt/tmp_pki/master/

# Minion
COPY etc/salt/minion /etc/salt/minion
COPY etc/salt/minion.d /etc/salt/minion.d
COPY etc/salt/minion_id /etc/salt/minion_id

COPY run.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/*
RUN printf "syn on\nset paste\nset mouse=r\n" > /root/.vimrc

EXPOSE 4505 4506 8001

ENTRYPOINT ["/usr/local/bin/run.sh"]
```

3. as you can see above, we are starting salt-master by run.sh, and basically we do this in the script:
```shell
/usr/bin/salt-api --log-level="$LOG_LEVEL" &
/usr/bin/salt-minion --log-level="$LOG_LEVEL" &
exec /usr/bin/salt-master --log-level="$LOG_LEVEL"
```
4. here you can find configuration for salt-master and api:

root@salt-master-797f6bb6-mj977:/srv/salt# grep -Ev "#|^$" /etc/salt/master
default_include: master.d/*.conf
root@salt-master-797f6bb6-mj977:/srv/salt# find /etc/salt/master.d/ -name "*.conf" | xargs -n1 sh -c 'echo "\n*****$1*****"; cat $1' sh;

<details>
*****/etc/salt/master.d/pillar.conf*****

pillar_roots:
  base:
    - /srv/env_paths/base_pillar/
  alt_1:
    - /srv/env_paths/alt_1_pillar/
  alt_2:
    - /srv/env_paths/alt_2_pillar/
  alt_3:
    - /srv/env_paths/alt_3_pillar/
  alt_4:
    - /srv/env_paths/alt_4_pillar/
  alt_5:
    - /srv/env_paths/alt_5_pillar/

*****/etc/salt/master.d/security_add.conf*****
file_recv: True

ssl:
  keyfile: /etc/pki/tls/certs/localhost.key
  certfile: /etc/pki/tls/certs/localhost.crt
  ssl_version: PROTOCOL_TLSv1_2

*****/etc/salt/master.d/thread.conf*****
####Standards for busy environments:
####Use one worker thread per 200 minions.
####The value of worker_threads should not exceed 1½ times the available CPU cores.
worker_threads: 6

*****/etc/salt/master.d/ext_pillar.conf*****
ext_pillar:
  - http_ic_json:
      url: #######
      key: #####
      kchost: #####

ext_pillar_first: False

*****/etc/salt/master.d/fileserver.conf*****

file_roots:
  mm:
    - /srv/mm/
  base:
    - /srv/env_paths/base_1/
    - /srv/env_paths/base_2/
    - /srv/env_paths/base_3/
    - /srv/env_paths/base_4/
    - /srv/env_paths/base_5/
  alt_1:
    - /srv/env_paths/alt_1_1/
    - /srv/env_paths/alt_1_2/
    - /srv/env_paths/alt_1_3/
    - /srv/env_paths/alt_1_4/
    - /srv/env_paths/alt_1_5/
  alt_2:
    - /srv/env_paths/alt_2_1/
    - /srv/env_paths/alt_2_2/
    - /srv/env_paths/alt_2_3/
    - /srv/env_paths/alt_2_4/
    - /srv/env_paths/alt_2_5/
  alt_3:
    - /srv/env_paths/alt_3_1/
    - /srv/env_paths/alt_3_2/
    - /srv/env_paths/alt_3_3/
    - /srv/env_paths/alt_3_4/
    - /srv/env_paths/alt_3_5/
  alt_4:
    - /srv/env_paths/alt_4_1/
    - /srv/env_paths/alt_4_2/
    - /srv/env_paths/alt_4_3/
    - /srv/env_paths/alt_4_4/
    - /srv/env_paths/alt_4_5/
  alt_5:
    - /srv/env_paths/alt_5_1/
    - /srv/env_paths/alt_5_2/
    - /srv/env_paths/alt_5_3/
    - /srv/env_paths/alt_5_4/
    - /srv/env_paths/alt_5_5/

*****/etc/salt/master.d/job.conf*****
timeout: 14
gather_job_timeout: 600
color: True

*****/etc/salt/master.d/reactor.conf*****
reactor:
  - 'salt/minion/salt-master-minion/start':
    - /srv/mm/reactor/mm-startup.sls
reactor_worker_threads: 20

*****/etc/salt/master.d/api.conf*****
external_auth:
  pam:
    saltdev:
    - '@runner'
    - '@wheel'
    - .*
rest_cherrypy:
  host: 0.0.0.0
  port: 8001
  debug: True
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key

*****/etc/salt/master.d/extensions.conf*****
extension_modules: /srv/extensions

*****/etc/salt/master.d/security.conf*****
autosign_file: /etc/salt/autosign.conf

master_sign_pubkey: True

*****/etc/salt/master.d/logging.conf*****
log_level_logfile: quiet
keep_jobs: 168

*****/etc/salt/master.d/interface.conf*****
interface: 0.0.0.0
ipv6: True
publish_port: 4505
ret_port: 4506
user: root
pidfile: /var/run/salt-master.pid
</details>

**Comment by Ch3LL** [comment] 2023-08-22 19:06
I'm not able to build the container, as the debian packages are not installing. I did notice the container is using 3004 which is an old version. Do you still see this issue on 3006.3?

**Comment by Ch3LL** [comment] 2023-09-12 20:08
Closing due to inactivity and cannot reproduce. If this is still a valid issue on teh latest version of Salt (3006.3 today) please open a new issue with the details and requested information to help reproduce the issue.

**Closed by Ch3LL** 2023-09-12 20:08 UTC
Labels: Bug, severity-high
