### ISSUE TITLE
Getting a bunch of warnings, errors and tracebacks when running salt-cloud command on develop branch

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#26669] opened 2015-08-26 18:00 UTC
```
root@nitin-salt-develop:~/salt$ salt-cloud -d salt-oel-1
[ERROR   ] Exception raised when processing __virtual__ function for boto_sns. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_sns.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_sns', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for selinux. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.selinux.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'selinux', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for groupadd. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.groupadd.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'groupadd', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for rh_service. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.rh_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_service', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for ifttt. Module will not be loaded global name '__salt__' is not defined
[WARNING ] salt.loaded.int.module.ifttt.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'ifttt', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for freebsdkmod. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.freebsdkmod.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsdkmod', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for systemd. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.systemd.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'systemd', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for freebsd_sysctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.freebsd_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsd_sysctl', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for layman. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.layman.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'layman', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for victorops. Module will not be loaded global name '__salt__' is not defined
[WARNING ] salt.loaded.int.module.victorops.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'victorops', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for freebsdservice. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.freebsdservice.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsdservice', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for openbsdrcctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.openbsdrcctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openbsdrcctl', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for linux_sysctl. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.linux_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'linux_sysctl', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for logadm. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.logadm.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'logadm', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for rest_service. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.rest_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rest_service', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for smf. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.smf.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'smf', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for pkgng. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.pkgng.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pkgng', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for solarispkg. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.solarispkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'solarispkg', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for debian_ip. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.debian_ip.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'debian_ip', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for openbsd_sysctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.openbsd_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openbsd_sysctl', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for keyboard. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.keyboard.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'keyboard', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for pw_user. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.pw_user.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pw_user', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for pkgin. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.pkgin.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pkgin', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for service. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'service', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for makeconf. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.makeconf.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'makeconf', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for kmod. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.kmod.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'kmod', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for poudriere. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.poudriere.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'poudriere', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for netbsdservice. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.netbsdservice.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'netbsdservice', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for win_powercfg. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.win_powercfg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_powercfg', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for darwin_pkgutil. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.darwin_pkgutil.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'darwin_pkgutil', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for solarisips. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.solarisips.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'solarisips', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_elb. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_elb.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_elb', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for pw_group. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.pw_group.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pw_group', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_iam. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_iam.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_iam', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_secgroup. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_secgroup.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_secgroup', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for pkgutil. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.pkgutil.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pkgutil', please fix this.
[ERROR   ] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
[ERROR   ] Exception raised when processing __virtual__ function for boto_ec2. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_ec2.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_ec2', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for openbsdpkg. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.openbsdpkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openbsdpkg', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for debian_service. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.debian_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'debian_service', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_elasticache. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_elasticache.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_elasticache', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for bridge. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.bridge.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'bridge', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for xapi. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.xapi.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'xapi', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for freebsdjail. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.freebsdjail.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsdjail', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for apache. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.apache.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'apache', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for openbsdservice. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.openbsdservice.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openbsdservice', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for launchctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.launchctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'launchctl', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for system_rest_sample. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.system_rest_sample.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'system_rest_sample', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_asg. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_asg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_asg', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for solaris_group. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.solaris_group.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'solaris_group', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for eselect. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.eselect.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'eselect', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for upstart. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.upstart.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'upstart', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_sqs. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_sqs.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_sqs', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for useradd. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.useradd.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'useradd', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for gentoo_service. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.gentoo_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'gentoo_service', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for nspawn. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.nspawn.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'nspawn', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for dpkg. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.dpkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'dpkg', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for grub_legacy. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.grub_legacy.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'grub_legacy', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for rh_ip. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.rh_ip.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_ip', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for eix. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.eix.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'eix', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for pacman. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.pacman.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pacman', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for freebsdpkg. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.freebsdpkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsdpkg', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for debconfmod. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.debconfmod.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'debconfmod', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_dynamodb. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_dynamodb.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_dynamodb', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for deb_apache. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.deb_apache.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'deb_apache', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for mdadm. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.mdadm.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'mdadm', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_rds. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_rds.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_rds', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for solaris_user. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.solaris_user.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'solaris_user', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for softwareupdate. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.softwareupdate.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'softwareupdate', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for netbsd_sysctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.netbsd_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'netbsd_sysctl', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_cloudwatch. Module will not be loaded 'boto.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_cloudwatch.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_cloudwatch', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for zfs. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.zfs.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'zfs', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for gentoolkitmod. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.gentoolkitmod.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'gentoolkitmod', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for darwin_sysctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.darwin_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'darwin_sysctl', please fix this.
[INFO    ] salt-cloud starting
/usr/lib/python2.6/site-packages/salt/cloud/clouds/vsphere.py:148: DeprecationWarning: The vsphere driver is deprecated in favor of the vmware driver and will be removed in Salt Carbon. Please convert your vsphere provider configs to use the vmware driver.
The following virtual machines are set to be destroyed:
  vcenter03:
    vmware:
      salt-oel-1

Proceed? [N/y]
```

**Comment by rallytime** [comment] 2015-08-26 18:07
Thanks @nmadhok. Those warnings won't hurt your salt-cloud commands, but they are certainly noisy. I'll look into cleaning this up today.

**Comment by rallytime** [comment] 2015-08-26 19:46
This appears to be caused by a4a3f7ff81c4e83edede4bce42c1651291ed2a22. The bug is present both in `develop` and `2015.8` when the change was back-ported in #26645.

**Comment by basepi** [comment] 2015-08-27 19:59
Should be fixed in https://github.com/saltstack/salt/pull/26717

**Comment by rallytime** [comment] 2015-08-27 21:37
@basepi Looks like this fixed the error messages from before, but now I am seeing this stack trace with this change, which is new, but related:
```
# salt-cloud --list-images linode
[ERROR   ] Failed to import log_handlers sentry_mod, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/loader.py", line 1105, in _load_module
    ), fn_, fpath, desc)
  File "/root/SaltStack/salt/salt/log/handlers/sentry_mod.py", line 96, in <module>
    __grains__ = salt.loader.grains(__opts__)
NameError: name '__opts__' is not defined
[INFO    ] salt-cloud starting
```

**Comment by twangboy** [comment] 2015-08-28 16:59
Also happening here: 
https://github.com/saltstack/salt/issues/26740
https://github.com/saltstack/salt/issues/26739

**Comment by rallytime** [comment] 2015-08-28 17:35
Tested...confirmed fixed. Thanks @basepi!

**Closed** 2015-08-28 17:34 UTC
Labels: Beryllium, Blocker, Bug, Core, Fixed Pending Verification, High Severity, P1

**Comment by arthurlogilab** [comment] 2015-10-15 15:21
am getting this in 2015.8.0 when can we expect to get a release for this ? Is there a workaround ? 

```
# salt-cloud --versions-report
Salt Version:
            Salt: 2015.8.0
 
Dependency Versions:
 Apache Libcloud: 0.15.1
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
            Mako: 1.0.0
          PyYAML: 3.11
           PyZMQ: 14.4.1
          Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
            cffi: 1.1.2
        cherrypy: 3.5.0
        dateutil: 2.2
           gitdb: 0.5.4
       gitpython: Not Installed
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.2
    mysql-python: Not Installed
       pycparser: 2.10
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: 0.8.2
         timelib: Not Installed
 
System Versions:
            dist: Ubuntu 15.04 vivid
         machine: x86_64
         release: 3.19.0-30-generic
          system: Ubuntu 15.04 vivid
```

**Comment by syedaali** [comment] 2015-11-07 05:41
I am seeing this error in 2015.8.1:

2015-11-07 05:40:23,012 [salt.loaded.int.module.tls][ERROR   ][9350] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions

# salt-minion --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 3.2
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty

**Comment by rarescosma** [comment] 2015-12-02 08:23
Dito. Seeing the same error message as @syedaali on fresh salt install on Ubuntu 14.04, after `dist-upgrade`:

```
2015-12-02 08:20:47,843 [salt.loaded.int.module.tls][ERROR   ][3773] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
```

### `salt-minion --versions`

```
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Ubuntu 14.04 trusty
```

**Comment by zmalone** [comment] 2015-12-09 21:02
This still appears to be happening with 2015.8.3 as installed from repo.saltstack.com on Ubuntu 14.04.

**Comment by rallytime** [comment] 2015-12-09 21:15
@syedaali and @rarescosma That error message is different than the one that was originally reported and fixed. However, I am not sure what the fix is for this new error, as I am uncertain about what we provide in regards to pyopenssl via packages. Can you please open up and new issue so we can get the right eyes on it to get it fixed?

**Comment by zmalone** [comment] 2015-12-09 21:18
I've opened https://github.com/saltstack/salt/issues/29581 for my pyOpenSSL version errors.

**Comment by rallytime** [comment] 2015-12-09 21:23
Perfect! Thank you!
