### ISSUE TITLE
[BUG] pkg.list_upgrades for redhat includes "Loaded:plugins:" as a package

### ISSUE THREAD

**Issue by ewhitesides** [saltstack/salt#60752] opened 2021-08-17 14:28 UTC
**Description**
the command `salt <target> pkg.list_upgrades --out=json` will list all available updates for a given system.  I noticed on redhat 7 systems, that it erroneously includes "Loaded: plugins:" as a pending package, so my guess it's some sort of parsing issue.

**Steps to Reproduce the behavior**
`salt <redhat 7 system> pkg.list_upgrades --out=json | jq 'to_entries[]'`

produces a response like this:
{
  "key": "mycomputer",
  "value": {
    "salt": "3003.2-1.el7",
    "salt-minion": "3003.2-1.el7",
    "Loaded": "plugins:" <---- need to filter this out
}

**Expected behavior**
expected behavior is to not include 

**Versions Report**
3003.1 for master and minions

**Comment by krionbsd** [comment] 2021-08-17 15:27
Could you provide `salt --versions-report` output?

**Comment by ewhitesides** [comment] 2021-08-17 16:20
this is from the master:

Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: rhel 7.9 Maipo
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.36.2.el7.x86_64
        system: Linux
       version: Red Hat Enterprise Linux Server 7.9 Maipo

**Comment by krionbsd** [comment] 2021-08-17 17:46
I couldn't reproduce it on CentOS7, did you run `sudo yum clean expire-cache` after adding new repositories? Does "Loaded plugins" appear with every `pkg.list_upgrades` invocation or only once?

**Comment by ewhitesides** [comment] 2021-08-17 18:13
the issue only appears on redhat, on my centos systems it is fine

**Comment by waynew** [comment] 2022-03-08 22:55
@ewhitesides I just took a look at the code in question and I cannot figure out for the life of me how to get this to show up.

We're passing the `--quiet` flag to both yum and dnf, so neither of them should report anything about the loaded plugins. It does appear that you are (were?) getting that output though. If you're still having that issue, let me know, and please provide the output of 

```
salt <rh7 system> cmd.run "yum --quiet list updates"
```

Thanks! (feel free to anonymize the updates or whatever - probably should only need the `head` of the output)

**Comment by ewhitesides** [comment] 2022-03-10 15:52
hi there - will try on my end again this afternoon and let you know.  all my machines are now on 3004.

**Comment by ewhitesides** [comment] 2022-03-11 16:49
looks like it's still there:
❯ salt mycomputer cmd.run 'yum --quiet list updates'
mycomputer:
    Updated Packages
    google-cloud-sdk.x86_64         376.0.0-1               google-cloud-sdk
    google-compute-engine.noarch    1:20220211.00-g1.el7    google-compute-engine
    google-osconfig-agent.x86_64    1:20220215.00-g1.el7    google-compute-engine
    qpid-proton-c.x86_64            0.36.0-1.el7            someprivaterepo
    Loaded plugins: product-id, subscription-manager
    
❯ salt mycomputer cmd.run 'cat /etc/yum.conf'
mycomputer:
    [main]
    cachedir=/var/cache/yum/$basearch/$releasever
    keepcache=0
    debuglevel=2
    logfile=/var/log/yum.log
    exactarch=1
    obsoletes=1
    gpgcheck=1
    plugins=1
    installonly_limit=2

    #  This is the default, if you make this bigger yum won't see if the metadata
    # is newer on the remote and so you'll "gain" the bandwidth of not having to
    # download the new metadata and "pay" for it by yum not having correct
    # information.
    #  It is esp. important, to have correct metadata, for distributions like
    # Fedora which don't keep old packages around. If you don't like this checking
    # interupting your command line usage, it's much better to have something
    # manually check the metadata once an hour (yum-updatesd will do this).
    # metadata_expire=90m

    # PUT YOUR REPOS HERE OR IN separate files named file.repo
    # in /etc/yum.repos.d
    ip_resolve=4

**Comment by waynew** [comment] 2022-03-31 21:26
Well, hello! That's exceedingly interesting. I'll check to see if that does, but IIRC i did check with that. That's actually *not* where I get plugin output from my previous tests... :thinking:

**Comment by waynew** [comment] 2022-03-31 21:43
I wonder if that's a customized redhat thing. A search did turn up https://access.redhat.com/solutions/3667101 - I'm not sure if that's what's causing your bug as well (and you can see in that output they're showing the plugins at the beginning, as well as at the end of the output).

I'm inclined to say that this is probably a bug in RedHat/Yum - reading https://man7.org/linux/man-pages/man8/yum.8.html it seems to agree with that take:

```
       -q, --quiet
              In combination with a non-interactive command, shows just
              the relevant content. Suppresses messages notifying about
              the current state or actions of DNF.
```

I don't see how loaded plugins are relevant to listing updates. In theory I suppose salt *could* workaround that by ignoring any `Loaded plugins:` line, or... maybe a filter/regex ignore line that one could pass in :thinking: 

Ultimately, unless there's a convincing reason that Salt is doing the wrong thing and this isn't just a bug in yum & friends... we should go ahead and close this issue.

---

*However* - while I doubt anyone on the core team has the bandwidth soon to make the change, I think we *would* accept a PR (with tests) that handle either `ignore` or `ignore_pattern` (or both) and ignores any line or package that matches.

**Comment by ewhitesides** [comment] 2022-04-01 14:57
it sounds like it's an edge case, and maybe something that doesn't occur on most other systems, so yes we can close it.  I handle excluding it on the front end in my shell script:

`
salt -C $target pkg.list_upgrades --hide-timeout --out=json |
    jq -r --arg t "$timestamp" --arg ng "$nodegroup" '
        to_entries[] | {
            t: ($t),
            g: ($ng),
            m: (.key),
            v: (
                if (.value|type=="object") then
                    (.value | map(select(.!="plugins:")) | length)
                else
                    (.value)
                end
            ),
            l: (
                if (.value|type=="object") then "INFO" else "ERROR" end
            )
        } |
        "Time=\(.t), NodeGroup=\(.g), Minion=\(.m), Pending_Updates=\(.v), Level=\(.l)"
    ' | tee -a "$logfile"
`

**Comment by waynew** [comment] 2022-04-04 15:55
:+1:

**Closed by waynew** 2022-04-04 15:55 UTC
Labels: Bug, needs-triage
