### ISSUE TITLE
Salt cloud installation fails sporadically - minion sometimes fails to start on windows

### ISSUE THREAD

**Issue by Mapel88** [saltstack/salt#53533] opened 2019-06-19 15:54 UTC
### Description of Issue
I'm running windows VM installation with salt-run (on XEN servers if t matters).
Salt minion is installed with setup.exe, then the setup supposed to stop then start the minion.
It seems that sometimes the service is not stopped in a timely fashion and therefore the start command fails.
Is there a way to add sleep for a few secs after stop command or maybe validate that the service actually stopped before trying to start it?

```
[INFO    ] Running command under pid 382: 'winexe -U 'Administrator%XXX-REDACTED-XXX' //10.0.0.1 "c:\salttemp\Salt-Minion-2018.3.4-Py3-AMD64-Setup.exe /S /master=[u'master1'] /minion-name=server11"'
[DEBUG   ] Executing command(PID 382): 'winexe -U 'Administrator%XXX-REDACTED-XXX' //10.0.0.1 "c:\salttemp\Salt-Minion-2018.3.4-Py3-AMD64-Setup.exe /S /master=[u'master1'] /minion-name=server11"'
[INFO    ] Running command under pid 449: 'winexe -U 'Administrator%XXX-REDACTED-XXX' //10.0.0.1 "sc stop salt-minion"'
[DEBUG   ] Executing command(PID 449): 'winexe -U 'Administrator%XXX-REDACTED-XXX' //10.0.0.1 "sc stop salt-minion"'
[DEBUG   ]
SERVICE_NAME: salt-minion
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 3  STOP_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)

SERVICE_NAME: salt-minion
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 3  STOP_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
[DEBUG   ]    SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x1
        WAIT_HINT          : 0x7d0
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x1
        WAIT_HINT          : 0x7d0
[INFO    ] Running command under pid 450: 'winexe -U 'Administrator%XXX-REDACTED-XXX' //10.0.0.1 "sc start salt-minion"'
[DEBUG   ] Executing command(PID 450): 'winexe -U 'Administrator%XXX-REDACTED-XXX' //10.0.0.1 "sc start salt-minion"'
[DEBUG   ] [SC] StartService FAILED 1056:

An instance of the service is already running.
[SC] StartService FAILED 1056:

An instance of the service is already running.


```

### Setup
my SLS:
```
provision_vm:
  salt.runner:
    - name: cloud.profile
    - prof: {{ vm.profile }}
    - instances:
      - {{ vm.hostname }}
    - order: 1
    - vm_overrides:
        minion:
          master:
            {%- for saltmaster in vm.masters %}
            - {{ saltmaster }}
            {%- endfor %}
          grains:
            roles:
              {%- for role in vm.roles %}
              - {{ role }}
              {%- endfor %}
            environment:
              {%- for env in vm.environment %}
              - {{ env }}
              {%- endfor %}
            region:
              {%- for reg in vm.region %}
              - {{ reg }}
              {%- endfor %}
```

### Steps to Reproduce Issue
This is the command I'm using:
`sudo salt-run state.orch orch.deploy_server pillar='{"profile": "vm-profile", "name": "server11", "region": ["region"], "env": ["env"], "roles": ["role"]}' -l debug
`
### Versions Report
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.7.0
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

```

**Comment by xeacott** [comment] 2019-06-20 15:54
Hi @Mapel88 I see your PR you've submitted. I'll link it here, also link this issue to the PR, update the labels and we'll see if that fix indeed addresses this. @twangboy might need your input on increasing the delay and if this does in fact help.

PR: https://github.com/saltstack/salt/pull/53547

**Comment by xeacott** [comment] 2019-06-24 22:32
@Mapel88 I'm okay with the sleep increase, how slow is the VM that you're running? Maybe it can be an optional argument so that in case 10 seconds doesn't work, then someone can supply whatever they need. I'll close the issue for now.

**Comment by xeacott** [comment] 2019-07-05 14:54
Whoops, thought this got merged sorry.

**Comment by Mapel88** [comment] 2019-10-06 12:13
Any updates?

**Comment by Akm0d** [comment] 2019-10-07 17:54
@Mapel88 Thank you for the PR! I will cherry-pick your changes into the master branch where we have test to verify that the issue is actually resolved

**Comment by Akm0d** [comment] 2019-10-07 21:38
I pulled that into master and the msazure test still failed: 
```15:35:44         ================================================  Overall Tests Report  ================================================
15:35:44         *** integration.cloud.clouds.test_msazure.AzureTest.test_instance Tests  ***********************************************
15:35:44          --------  Failed Tests  -----------------------------------------------------------------------------------------------
15:35:44            -> integration.cloud.clouds.test_msazure.AzureTest.test_instance  ...................................................
15:35:44         Traceback (most recent call last):
15:35:44           File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_msazure.py", line 60, in test_instance
15:35:44             self.assertCreateInstance(timeout=TIMEOUT)
15:35:44           File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 79, in assertCreateInstance
15:35:44             self.assertInstanceExists(creation_ret=stdout, instance_name=instance_name, stderr=stderr)
15:35:44           File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 93, in assertInstanceExists
15:35:44             self.fail('\n'.join(stderr))
15:35:44         AssertionError: [WARNING ] There's no master defined on the 'cloud-test-azu-8bvtv' VM settings.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         No ECDSA host key is known for 40.112.142.155 and you have requested strict checking.
15:35:44         Host key verification failed.
15:35:44         [ERROR   ] Failed to start Salt on host cloud-test-azu-8bvtv
15:35:44            .....................................................................................................................
15:35:44            -> integration.cloud.clouds.test_msazure.AzureTest.test_instance  ...................................................
15:35:44         Traceback (most recent call last):
15:35:44           File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 311, in tearDown
15:35:44             self.assertTrue(success, '\n'.join(fail_messages))
15:35:44         AssertionError: False is not true : The instance "cloud-test-azu-8bvtv" was deleted during the tearDown, not the test.
15:35:44            ```

**Comment by sagetherage** [comment] 2020-03-26 00:48
closing as fixed in master

**Closed by sagetherage** 2020-03-26 00:48 UTC
Labels: Bug, Confirmed, Fixed Pending Verification, P4, team-cloud, team-windows
