### ISSUE TITLE
[FEATURE REQUEST] Include accurate package version comparison for RHEL7

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#57972] opened 2020-07-17 12:29 UTC
**Is your feature request related to a problem? Please describe.**

The `pkg.version_cmp` module using Salt's built-in comparison is not always accurate on RedHat-derived machines; there is a helpful warning message to this effect when using the CLI.  However, when using external UI-driven products that depend on `pkg.version_cmp`, inaccurate version comparions can cause unexpected failures.  Since, on RHEL7, the accurate comparison depends on the `python3-rpm` package from EPEL, users may not have this out of the box, and adding EPEL may have obstacles depending on their environment.

One comparison example (from `libxml2` versions):

```
[root@rhel7 vagrant]# salt-call pkg.version_cmp '2.9.1-6.el7_2.3' '2.9.1-6.el7.4'
[WARNING ] Please install a package that provides rpm.labelCompare for more accurate version comparisons.
[WARNING ] Falling back on salt.utils.versions.version_cmp() for version comparisons
local:
    1
[root@rhel7 vagrant]# yum -y -q install python3-rpm
[root@rhel7 vagrant]# salt-call pkg.version_cmp '2.9.1-6.el7_2.3' '2.9.1-6.el7.4'
local:
    -1
```

**Describe the solution you'd like**

I spoke at length with @dmurphy18 on Slack, and doing the comparison by shelling out to `rpmdev-vercmp`, which is part of the base OS's `rpmdevtools`, would be the preferred solution.  I believe the implication is that the installation of salt packages should depend on `rpmdevtools`.

**Describe alternatives you've considered**

* Adding `python3-rpm` to Saltstack's repo and making it a dependency.
* No change.  External tools using `pkg.version_cmp` responsible for documenting installation of `python3-rpm` from EPEL to obtain working functionality.

**Comment by oeuftete** [comment] 2020-07-17 12:32
ZD-5419.

**Comment by krionbsd** [comment] 2020-08-18 10:19
@oeuftete I'm not very familiar with rpmdev tools, but looking briefly into the code it seems we support comparisons based on rpmdev-vercmp as well as on python3-rpm, so I'll see what we can do with dependencies for this case

**Comment by krionbsd** [comment] 2020-08-18 10:39
I tested it now on fresh CentOS 8 AMI and installed the packages from repo.saltstack.com:
```
[root@ip-10-31-2-156 centos]# salt-call pkg.version_cmp '2.9.1-6.el7_2.3' '2.9.1-6.el7.4'
local:
    -1
```
`rpmdevtools` was part of base install, not as part of EPEL. @oeuftete, what CentOS version did you reference for your case?

**Comment by wb529kq** [comment] 2020-08-18 10:52
@krionbsd RHEL 7.x

**Comment by oeuftete** [comment] 2020-08-18 13:21
@krionbsd I saw this on RHEL7/8.  I should have made this clear.

For RHEL7, yes, it looks like installing `rpmdevtools` is sufficient.  I completely missed that that was already supported, thanks for clearing that up.  Per the summary, I think adding `rpmdevtools` as a dependency in the package would be the right approach.

But, see also issue https://github.com/saltstack/salt/issues/57347, resolved in https://github.com/saltstack/salt/pull/57369 (included in 3001+), which is a bit at odds with the recommended solution noted above.  And it has a problem.

Default RHEL7:

```text
[vagrant@rhel7 ~]$ sudo salt-call pkg.version_cmp '2.9.1-6.el7_2.3' '2.9.1-6.el7.4'
[WARNING ] Please install a package that provides rpm.labelCompare for more accurate version comparisons.
[WARNING ] Falling back on salt.utils.versions.version_cmp() for version comparisons
local:
    1
```

That's OK:
* :heavy_check_mark: First warning is accurate and desirable
* :heavy_check_mark: Second warning is accurate and desirable
* :heavy_check_mark: Result is inaccurate, but we've been adequately warned it might be.

Now, after installing `rpmdevtools`:

```text
[vagrant@rhel7 ~]$ sudo salt-call pkg.version_cmp '2.9.1-6.el7_2.3' '2.9.1-6.el7.4'
[WARNING ] Please install a package that provides rpm.labelCompare for more accurate version comparisons.
[WARNING ] Installing the rpmdevtools package may surface dev tools in production.
local:
    -1
```

This is not OK.

* :heavy_multiplication_x: The first warning is undesirable, we already have `rpmdev-vercmp` installed to provide accurate comparison.
* :heavy_multiplication_x: In my opinion, the second warning is also undesirable, even if it may be accurate; we don't need to see this every time a comparison is made. ([This OWASP Top Ten entry](https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A6-Security_Misconfiguration) was cited as the reason for the warning.)
* :heavy_check_mark: Result is accurate.

**Comment by cro** [comment] 2020-08-25 15:37
@s0undt3ch and @krionbsd , are you OK with this getting fixed by adding python36-rpm.rpm as a dependency to Salt for CentOS 7 and including that package in our own repo?

**Comment by s0undt3ch** [comment] 2020-08-25 16:06
I'm good with the solution, but I'm not directly involved with packaging so we'll need input from @krionbsd

**Comment by wb529kq** [comment] 2020-08-25 16:43
Also needed for Oracle EL 7/8

**Comment by krionbsd** [comment] 2020-08-26 06:18
@cro I'm fine with it, does py36-rpm exist as pip package as well or it's only rpm available?

**Comment by saltybaker** [comment] 2020-09-18 21:09
after chatting with Bryce it appears these are our possible solutions:
1) centos 7 - we could theoretically copy python3-rpm from epel and build it ourself and put it in the salt repo.  It doesn't appear to pull in anything but python3 stuff (needed for salt anyway)
2) amazonlinux2 - python3-rpm is included in the amazonlinux2 repo, we could include it as a salt dependency

Request for agreement/comments/concerns

**Comment by bryceml** [comment] 2020-09-19 00:22
@saltybaker what do we do when we move to tiamat, and we don't use the system packages?  Is python3-rpm available from pypi ?

**Comment by saltybaker** [comment] 2020-09-19 07:10
At present salt does not use tiamat and as I understand from your explanations, it is not a big issue to include os package dependencies in the rpms that we produce for salt.

Regarding using pypi to install an os rpm like python3-rpm, it is probably not possible because the os packages are controlled and release by the os vendors.
However, we do have to address the issue of pypi packages that require os packages (libraries) to function in tiamat installations.  We have some now, and probably will have more in the future.

**Comment by dmurphy18** [comment] 2020-09-21 15:52
@saltybaker Tiamat already allows for the inclusion of OS dependent libraries which are not Python based.

Fixing the version comparison is relativity simple, the issue is catching the corner cases, for example: use of Py 3.6 or Py 3.8 on RHEL 7 and 8, the use and reporting from distro now that the older linux_distribution methods are deprecated.   A large testing matrix for handling Redhat but also Amazon and other Redhat family based distributions.

**Comment by saltybaker** [comment] 2020-09-21 19:41
We seem to have consensus on the solution described above.  @bryceml would you include python3-rpm (from epel) for the centos 7 salt rpm and pull the same package from amazonlinux2 for inclusion in the amazonlinux2 rpm for salt.

Please let us know when this is available so we can coordinate testing with @ssgward.

**Comment by bryceml** [comment] 2020-09-21 22:25
Can we investigate whether using https://pypi.org/project/rpm-vercmp/ will work.  Based on the example given above, it looks like it should.

**Comment by saltybaker** [comment] 2020-09-21 22:32
Looks like consensus completely fell apart, and folks want to use rpm-vercmp (python package last released Oct 2018) and change salt to use it instead.  So, probably not going to go into Retention Pack.

**Comment by saltybaker** [comment] 2020-09-21 22:51
Consensus has re-emerged to add python3-rpm to the salt install.  @bryceml and @jshatch will be taking on that task.  (once tiamat starts to be used for salt, the rpm-vercmp issue will have to be re-evaluated.

**Comment by sagetherage** [comment] 2020-10-13 14:37
@frogunder can you test this please?

**Comment by frogunder** [comment] 2020-10-13 22:00
This seems to be working correctly on Amazon Linux 2 using the 3002rc1 package.

There is no RHEL 7 package for 3002rc1, so will check again once RHEL 7 for 3002 is built.

**Comment by frogunder** [comment] 2020-10-15 16:39
This is also seems to work correctly for me on RHEL7 and CentOS7 for the 3002rc1 package.

**Comment by sagetherage** [comment] 2020-10-15 18:58
Closing as done and will be released next week for general availability and is in the RC as Frode stated.

**Closed by sagetherage** 2020-10-15 18:58 UTC
Labels: CS-R3, CS-S3, Feature, Magnesium, Packaging, Severity: High, ZD
