### ISSUE TITLE
top file merging same does produce conflicting ids with gitfs

### ISSUE THREAD

**Issue by mruepp** [saltstack/salt#46660] opened 2018-03-22 10:30 UTC
### Description of Issue/Question
We use gitfs as backend. We have three environments: dev-qa-staging
We use top file merging strategy same. Our Top files for every environment contains {{ saltenv }}:

We want to create and test states by branching away for instance from dev -> feature/branch, add changes, test them by using salt .. state.apply saltenv=feature/branch and after successfully highstating the changes, Pull Request and Merge.

So everything is fine except, as long as the feature branch exists, we are no longer able to highstate ALL environments at the same time without using saltenv. This will result in conflicting ids.

Also we are not able to move states from dev to qa for instance by checking out specific states or cherrypicking them from e.g. dev to qa to stage to prod because we will always having conflicting ids.

So I would expect with top file merging "same" for the environments to only account for the own files.

Do I miss something?

### Setup
Our gitfs config: 

```
fileserver_backend:
  - git

gitfs_provider: pygit2

gitfs_user: salt
gitfs_password: password

top_file_merging_strategy: same

default_top: base

gitfs_remotes:
  - https:/gitrepo/scm/devops/salt.git:
      - refspecs:
          - '+refs/heads/*:refs/remotes/origin/*'
          - '+refs/tags/*:refs/tags/*'
          - '+refs/pull/*/head:refs/remotes/origin/pr/*'
          - '+refs/pull/*/merge:refs/remotes/origin/merge/*'
      - root: states
      - base: master
      - saltenv:
          - dev:
              - ref: dev
          - qa:     
              - ref: qa
          - stage:
              - ref: stage

  #List the formula repos with respective base
  - https://gitrepo/scm/devops/salt-formulas.git:
      - name: vault-formula
      - root: vault-formula
      - saltenv:
          - dev:
              - ref: master

  - https://gitrepo/scm/devops/salt-formulas.git:
      - name: consul-formula
      - root: consul-formula
      - saltenv:
          - dev:
              - ref: master
```

### Steps to Reproduce Issue
Using Salt config as posted and try to create a feature branch to implement a change

### Versions Report
`Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
`

**Comment by Ch3LL** [comment] 2018-03-23 14:18
ping @terminalmage can you comment here on the best approach for @mruepp use case?

**Comment by rallytime** [comment] 2018-03-28 21:12
Closed via #46751

**Closed by rallytime** 2018-03-28 21:12 UTC
Labels: Pending Discussion

**Comment by terminalmage** [comment] 2018-06-16 01:58
I had to revert the changes made by @folti, as the way this was working was expected behavior. https://github.com/saltstack/salt/pull/46751 broke this because setting the environment manually in the opts ensures that *only* that environment is considered when finding top file matches.

To work around conflicting IDs using gitfs, consider using [state_top_saltenv](https://docs.saltstack.com/en/latest/ref/configuration/master.html#state-top-saltenv) to ensure that only a single environment's top file is used.

**Comment by banholzer** [comment] 2021-05-07 08:11
@terminalmage I think we should discuss this issue again.

Not having the top_file_meging_strategy "same" from my perspective blocks having a clean and modern GitOps environment. 

If you want to automatically test your new features that are developed in separate branches - which are mapped to saltenvs - you should be able to make sure that changes in your feature branch are not merged into other environments like base.

The approach should be to test every feature completely in separate environments - also the topfile + highstate before merging to another environment.

Could you please give an insight on why this is "expected behavior"? 

In my opinion gitfs should respect the same configuration for merging as the default file backend.

**Comment by terminalmage** [comment] 2021-05-07 15:08
It does, and it always has.

If you read the OP closely, you'll find that the issue wasn't that `top_file_merging_strategy` didn't work, but that the OP wanted to be able to run highstates without specifying the `saltenv`. He accomplished this in a PR by overwriting the effective fileserver environment for the salt run, **_which broke `top_file_merging_strategy`_** and had to be reverted.

Did you try to use `top_file_merging_strategy`? It honestly seems to work just fine:

```
% docker run --rm -it terminalmage/issues:46660
[root@c1f6ae503a4a /]# cat /etc/salt/master
top_file_merging_strategy: same

fileserver_backend:
  - git

gitfs_remotes:
  - file:///root/gitfs

log_level_logfile: debug
[root@c1f6ae503a4a /]# cat /etc/salt/minion
master: localhost
id: test
log_level_logfile: debug
[root@c1f6ae503a4a /]# cd /root/gitfs
[root@c1f6ae503a4a gitfs]# for branch in master dev qa; do echo $branch; echo ------; git show $branch:top.sls | cat; echo ----; git show $branch:test.sls | cat; echo -----------------------------; done
master
------
{{ saltenv }}:
  '*':
    - test
----
do_echo:
  cmd.run:
    - name: echo base
-----------------------------
dev
------
{{ saltenv }}:
  '*':
    - test
----
do_echo:
  cmd.run:
    - name: echo dev
-----------------------------
qa
------
{{ saltenv }}:
  '*':
    - test
----
do_echo:
  cmd.run:
    - name: echo qa
-----------------------------
[root@c1f6ae503a4a gitfs]# salt-master -d; salt-minion -d
[root@c1f6ae503a4a gitfs]# salt test test.ping
test:
    True
[root@c1f6ae503a4a gitfs]# salt test state.apply saltenv=base
test:
----------
          ID: do_echo
    Function: cmd.run
        Name: echo base
      Result: True
     Comment: Command "echo base" run
     Started: 14:38:58.543561
    Duration: 16.221 ms
     Changes:
              ----------
              pid:
                  846
              retcode:
                  0
              stderr:
              stdout:
                  base

Summary for test
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  16.221 ms
[root@c1f6ae503a4a gitfs]# salt test state.apply saltenv=dev
test:
----------
          ID: do_echo
    Function: cmd.run
        Name: echo dev
      Result: True
     Comment: Command "echo dev" run
     Started: 14:40:12.913843
    Duration: 11.874 ms
     Changes:
              ----------
              pid:
                  1021
              retcode:
                  0
              stderr:
              stdout:
                  dev

Summary for test
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  11.874 ms
[root@c1f6ae503a4a gitfs]# salt test state.apply saltenv=qa
test:
----------
          ID: do_echo
    Function: cmd.run
        Name: echo qa
      Result: True
     Comment: Command "echo qa" run
     Started: 14:40:21.638628
    Duration: 11.362 ms
     Changes:
              ----------
              pid:
                  1154
              retcode:
                  0
              stderr:
              stdout:
                  qa

Summary for test
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  11.362 ms
```

It is only when you try to run without a specific saltenv that this breaks.

```
[root@c1f6ae503a4a gitfs]# salt test state.apply
test:
    Data failed to compile:
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is 'do_echo' and is found in SLS 'base:test' and SLS 'dev:test'
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is 'do_echo' and is found in SLS 'dev:test' and SLS 'qa:test'
```

Now, let's take a look at the [docs](https://docs.saltproject.io/en/latest/ref/configuration/minion.html#std-conf_minion-top_file_merging_strategy):

```
When no specific fileserver environment (a.k.a. "saltenv") has been specified for a
highstate, all environments' top files are inspected. This config option
determines how the SLS targets in those top files are handled.

...

When set to "same", then for each environment, only that environment's top file
is processed, with the others being ignored. For example, only the "dev"
environment's top file will be processed for the "dev" environment, and any SLS
targets defined for "dev" in the "base" environment's (or any other environment's)
top file will be ignored. If an environment does not have a top file, then the
top file from the "default_top" config parameter will be used as a fallback.
```

The above example, which you can reproduce in docker with my `terminalmage/issues:46660` image, cannot IMO be interpreted as anything _other_ than expected behavior.

If a user wants to use a multi-branch approach for testing changes before merging them into `master`, and has set `top_file_merging_strategy: same` to facilitate this, then the user _must specify a saltenv_. This can be done at runtime by adding `saltenv=whatever` to your `state.apply`/`state.highstate`, or by setting the [saltenv](https://docs.saltproject.io/en/latest/ref/configuration/minion.html#saltenv) minion config parameter.

Let's go back to the example I set up. If I set a `saltenv` in the minion config, I no longer get the same conflicting IDs error that the OP was complaining about, because the `saltenv` is implicitly set to `base`. It can still be overridden at runtime, too.

```
[root@c1f6ae503a4a gitfs]# echo "saltenv: base" >> /etc/salt/minion
[root@c1f6ae503a4a gitfs]# pkill -f salt-minion
[root@c1f6ae503a4a gitfs]# salt-minion -d
[root@c1f6ae503a4a gitfs]# salt test state.apply
test:
----------
          ID: do_echo
    Function: cmd.run
        Name: echo base
      Result: True
     Comment: Command "echo base" run
     Started: 14:59:46.666527
    Duration: 15.814 ms
     Changes:
              ----------
              pid:
                  2194
              retcode:
                  0
              stderr:
              stdout:
                  base

Summary for test
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  15.814 ms
[root@c1f6ae503a4a gitfs]# salt test state.apply saltenv=dev
test:
----------
          ID: do_echo
    Function: cmd.run
        Name: echo dev
      Result: True
     Comment: Command "echo dev" run
     Started: 15:02:52.128294
    Duration: 9.888 ms
     Changes:
              ----------
              pid:
                  2450
              retcode:
                  0
              stderr:
              stdout:
                  dev

Summary for test
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   9.888 ms
```

**Comment by terminalmage** [comment] 2021-05-07 16:26
I added the `saltenv` example to the GitFS Walkthrough via https://github.com/saltstack/salt/pull/60161

**Comment by banholzer** [comment] 2021-06-21 14:38
@terminalmage I think I should be more precise - it does not directly map to the merging strategy. This was my mistake.

our requirement is to define the saltenv via extpillar.

We have kind of "solved" it this way:

merging strategy is "merge" and topfile includes this jinja: 
```
{% if saltenv == salt.pillar.get('foreman:saltenv') %}
{{ saltenv }}:

  "*":
    - client.apt
[...]
```

but this way someone who makes a jinja mistake in a feature branch could cause a top-sls that does not compile correctly and therefore blocks every further deployment on other branches.

we already investigated on this and there might be a solution by patching the minion - but the pillars used for highstate run are not refreshed before highstate is triggered automatically. --> I we switch environment in pillar it takes 2 highstates until the correct environment states reache the minion. So a refresh of pillars upfront highstate would be mandatory.

@bochi could you provide some technical details?
