### ISSUE TITLE
Missing quotes for ssh subcommand

### ISSUE THREAD

**Issue by abonillasuse** [saltstack/salt#36649] opened 2016-09-28 21:24 UTC
### Description of Issue/Question

sh syntax is wrong while trying to access 'minion'
### Setup

While using salt-cloud to create virtual machines on OpenStack, the VM is created successfully but when we start to ssh into the VM to "saltify" it, there is never a successful ssh login.
### Steps to Reproduce Issue

```
[DEBUG   ] Retrying connection to host 151.155.15.91 on port 22 (try 29)
[DEBUG   ] SSH port 22 on 151.155.15.91 is available
[DEBUG   ] Using /etc/salt/abonilla-geeko.pem as the key_filename
[DEBUG   ] Attempting to authenticate as root (try 1 of 15)
[DEBUG   ] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/abonilla-geeko.pem -oConnectTimeout=15 -p 22 root@151.155.15.91 date'
[DEBUG   ] Child Forked! PID: 914  STDOUT_FD: 12  STDERR_FD: 14
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/abonilla-geeko.pem -oConnectTimeout=15 -p 22 root@151.155.15.91 date
Could not create directory '/srv/salt/.ssh'.
[DEBUG   ] Could not create directory '/srv/salt/.ssh'.
```

The standalone command succeeds

```
bash-4.2# ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/abonilla-geeko.pem -oConnectTimeout=15 -p 22 root@151.155.15.91 date
Warning: Permanently added '151.155.15.91' (ECDSA) to the list of known hosts.
Wed Sep 28 21:10:32 UTC 2016
```

```
bash-4.2# sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/abonilla-geeko.pem -oConnectTimeout=15 -p 22 root@151.155.15.91 date
usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L [bind_address:]port:host:hostport] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R [bind_address:]port:host:hostport] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
```

It would be missing proper quotation

```
bash-4.2# sh -c "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/abonilla-geeko.pem -oConnectTimeout=15 -p 22 root@151.155.15.91 date"
Warning: Permanently added '151.155.15.91' (ECDSA) to the list of known hosts.
Wed Sep 28 21:16:53 UTC 2016
```
### Versions Report

```
bash-4.2# salt --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul 01 2016, 15:34:22) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2

System Versions:
           dist: SuSE 42.1 x86_64
        machine: x86_64
        release: 4.4.20-moby
         system: Linux
        version: openSUSE  42.1 x86_64
```

**Comment by Ch3LL** [comment] 2016-09-29 22:00
@abonillasuse i'm having a hard time replicating this in aws with saltify. Here is my test case:

/etc/salt/cloud.profiles.d/saltify.conf:

```
salt-this-machine:
  ssh_host: <ipaddress>
  ssh_username: ec2-user
  key_filename: '/home/ch3ll/.ssh/key'
  provider: saltify-conf
```

/etc/salt/cloud.providers.d/saltify.conf

```
saltify-conf:
  provider: saltify
```

And salt installs just fine and I see no errors when running: `sudo salt-cloud -p salt-this-machine ch3ll_salt_test2 -ldebug`

Is my test case different from yours? Do you have some additional configurations that I need to add to replicate the issue? Thanks

**Comment by abonillasuse** [comment] 2016-12-08 04:50
@Ch3LL I don't know which provider you are using. This is working fine for me with OpenStack but not AWS.

I'm not using saltify, I just set 
  minion:
    master: xxxxxx
and
  ssh_username: root
in my profiles


It's running
[DEBUG   ] Child Forked! PID: 27373  STDOUT_FD: 4  STDERR_FD: 8
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /etc/salt/abonilla-aws.pem -p 22 root@54.204.132.97 date
Warning: Permanently added '54.204.132.97' (ECDSA) to the list of known hosts.
[DEBUG   ] Warning: Permanently added '54.204.132.97' (ECDSA) to the list of known hosts.
Permission denied (publickey).

but if I run it right there, manually (using quotes for sh)

suma:~ # /bin/sh -c "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /etc/salt/abonilla-aws.pem -p 22 root@54.204.132.97 date"
Warning: Permanently added '54.204.132.97' (ECDSA) to the list of known hosts.
Thu Dec  8 04:08:57 UTC 2016

**Comment by gtmanfred** [comment] 2017-01-20 00:20
This does not need to be quoted, because this is been executed by os.execvp, with an arg array of `['/bin/sh', '-c', ' '.join(args)], so the command is actually passed to sh as if it was a quoted string inside of python.

https://github.com/saltstack/salt/blob/develop/salt/utils/vt.py#L413

**Comment by abonillasuse** [comment] 2017-01-20 14:40
@gtmanfred I understand. I don't know why else the server would reject the key or fail to authenticate (or test the ssh connection) but yet be able to SSH if I run the command manually.

**Comment by abonillasuse** [comment] 2017-01-20 14:41
#38821 might be a duplicate of this same problem.

**Comment by gtmanfred** [comment] 2017-01-20 14:43
YEah, it looks like that is the case.  I am going to close this issue and mark it as a duplicate of #38821 

I am still working on replicating that one.

**Closed by gtmanfred** 2017-01-20 14:43 UTC
Labels: Info Needed
