### ISSUE TITLE
module haproxyconn not working

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#25678] opened 2015-07-23 21:26 UTC
haproxyconn module does not work.  I think the problem is in in lazyload (whatever that is used for?)

```
           Salt: 2015.5.2
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

```

```
# salt-call -l debug haprpoxyconn.show_frontends
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'haproxy-staging', 'tcp://10.10.0.2:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Error loading module.tls: ['PyOpenSSL must be installed before this module can be used.']
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Could not LazyLoad haprpoxyconn.show_frontends
'haprpoxyconn' __virtual__ returned False
```

haproxyctl was installed with 'pip install haproxyctl'.  The library imports of haproxy.cmds and haproxy.conn ARE succeeding; I have no idea why the log is reporting __virtual__ is returning false.  It's in fact returning "haproxy"
```
# pwd
/usr/lib/python2.7/site-packages/haproxy
# ls -l
total 44
-rw-r--r-- 1 root root 5013 Jul 23 21:14 cmds.py
-rw-r--r-- 1 root root 8553 Jul 23 21:14 cmds.pyc
-rw-r--r-- 1 root root 1462 Jul 23 21:14 conn.py
-rw-r--r-- 1 root root 2239 Jul 23 21:14 conn.pyc
-rw-r--r-- 1 root root   59 Jul 23 21:14 const.py
-rw-r--r-- 1 root root  242 Jul 23 21:14 const.pyc
-rw-r--r-- 1 root root   20 Jul 23 21:14 __init__.py
-rw-r--r-- 1 root root  169 Jul 23 21:14 __init__.pyc
```

**Comment by jfindlay** [comment] 2015-07-24 20:57
@deuscapturus, thanks for the report.  The lazyloader is salt's default loader, which only loads modules as needed, giving salt a great speed improvement over the python loader, for example.

What happens when you copy the haproxyconn.py module to /srv/salt/_modules, remove everything below the `__virtual__` function and `salt minion saltutil.sync_modules`?

**Comment by cachedout** [comment] 2015-07-30 22:56
This is the intended behaviour. Salt provides a facility to represents execution modules by names other than their filenames. Assuming you have the appropriate python pre-requsites installed (as you mention that you do), the correct command is as follows:

```
 % sudo salt-call --local haproxy.list_servers                                               (git)-[develop] 

Passed invalid arguments: list_servers() takes at least 1 argument (0 given).

Usage:

    List servers in haproxy backend.

    backend
        haproxy backend

    socket
        haproxy stats socket

    .. code-block:: bash

        salt '*' haproxy.list_servers mysql
```

Since this works as-designed, I am closing this issue.

**Closed by cachedout** 2015-07-30 22:56 UTC
Labels: Cannot Reproduce, Info Needed
