### ISSUE TITLE
incorrect install instructions for salt 3004 windows

### ISSUE THREAD

**Issue by gee456** [saltstack/salt#61199] opened 2021-11-08 18:58 UTC
### Description of Issue
Salt 3004 now installs in new locations on windows . NONE of this is documented. please document

### Setup
missing install flags like INSTALLDIR

### Steps to Reproduce Issue
look at docs at https://docs.saltproject.io/en/latest/topics/installation/windows.html

### Versions Report
3004

**Comment by barbaricyawps** [comment] 2022-01-18 21:21
FYI, improving installation instructions is on the Salt Docs Roadmap, but it's likely we won't get to it for another 2-3 sprints while we're working on other priorities: https://saltdocs.prodcamp.com/3

For now, I've created a duplicate of this issue in the salt-install-guide repo for tracking: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues/17

**Comment by barbaricyawps** [comment] 2022-09-12 22:47
I have a new MR open to resolve this issue. Better late than never, right?

https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/54

**Comment by barbaricyawps** [comment] 2022-09-14 15:38
Those changes are now merged, so this issue is resolved: https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/windows.html#install-directory-locations

Thanks!

**Closed by barbaricyawps** 2022-09-14 15:38 UTC
Labels: Documentation, Packaging, Windows, severity-high, doc-correction, time-estimate-long-term, salt install guide
