### ISSUE TITLE
ini.options_present always report state change

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#34245] opened 2016-06-23 13:45 UTC
### Description of Issue/Question

ini.options_present reports `Succeeded: 1 (changed=1)` on every highstate, even if file really didn't change. It does add whitespace at the beginning of file on first run though, but it shows that last ini key has changed.
### Setup

Let's say there is already file `/etc/myapp.ini` with contents:

```
[general]
```

state declaration:

```
ini:
  ini.options_present:
    - name: /etc/myapp.ini
    - sections:
        general:
          server_hostname: my.company.com
          server_port: 12345
```

Now if highstate is run, it does add these state-declared ini keys successfully:

```
root@vdebian2:/# cat /etc/myapp.ini 
[general]
```

```
root@vdebian2:/# salt minion state.highstate
minion:
----------
          ID: ini
    Function: ini.options_present
        Name: /etc/myapp.ini
      Result: True
     Comment: Changes take effect
     Started: 16:38:59.794464
    Duration: 1.376 ms
     Changes:   
              ----------
              general:
                  ----------
                  server_hostname:
                      ----------
                      after:
                          my.company.com
                      before:
                          None
                  server_port:
                      ----------
                      after:
                          12345
                      before:
                          None

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1

```

```
root@vdebian2:/# cat /etc/myapp.ini 

[general]
server_hostname = my.company.com
server_port = 12345
```

Though there is some extra whitespace at the beginning of file.

highstate again:

```
root@vdebian2:/# salt minion state.highstate
minion:
----------
          ID: ini
    Function: ini.options_present
        Name: /etc/myapp.ini
      Result: True
     Comment: Changes take effect
     Started: 16:34:06.245743
    Duration: 1.709 ms
     Changes:   
              ----------
              general:
                  ----------
                  server_port:
                      ----------
                      after:
                          12345
                      before:
                          12345

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

It thinks that last key `server_port` changed, though it was and is the same.
Contents again (the same):

```
root@vdebian2:/# cat /etc/myapp.ini 

[general]
server_hostname = my.company.com
server_port = 12345
```

Every highstate results in that `Succeeded: 1 (changed=1)`, though nothing actually changes.
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3

System Versions:
           dist: debian 7.11 
        machine: x86_64
        release: 3.16.0-0.bpo.4-amd64
         system: Linux
        version: debian 7.11 
```

**Comment by Ch3LL** [comment] 2016-06-23 19:28
@Talkless i am able to replicate this behavior and seeing the change output each time running `state.sls`:

```
----------
          ID: ini
    Function: ini.options_present
        Name: /etc/myapp.ini
      Result: True
     Comment: Changes take effect
     Started: 13:28:15.748354
    Duration: 1.94 ms
     Changes:   
              ----------
              general:
                  ----------
                  server_port:
                      ----------
                      after:
                          12345
                      before:
                          12345
```

Thanks we will get this fixed up

**Comment by kevinquinnyo** [comment] 2016-06-23 22:36
I think this is a regression since it doesn't seem to affect me on 2015.8.8.2 by the way.

I might take a look at this one if no one else does.  I have a suspicion this is a type comparison problem since it seems to fail for the integer only.  it might need to be cast as `str()` for the `==` when it detects changes.  Just a guess from skimming the code.

**Comment by rallytime** [comment] 2016-06-23 22:39
@kevinquinnyo That would be fantastic! Thanks for takinga  look.

**Comment by kevinquinnyo** [comment] 2016-06-24 03:05
This is actually already fixed in develop.  This bug only seems to exist in v2016.3.1 as far as I can tell right now.  So it is a regression, but it was fixed at https://github.com/saltstack/salt/blob/develop/salt/states/ini_manage.py#L56 I think.

But I haven't gone through the git log/blame to track it down.  Anyway, since it's fixed in the develop branch I guess it can be closed, but I think a good idea would be to add a test to ensure it doesn't happen again.  I'll do it if I can find some time and wrap my head around what the actual problem was...

**Comment by Talkless** [comment] 2016-06-24 09:33
@kevinquinnyo there was another bug I reported on same day which looks like was introduced in big overhaul of the module: #34236, so maybe this bug has the same source?

And yeas, if where were tests, these two bugs would have been easily avoided...

Thanks!

**Comment by Talkless** [comment] 2016-06-27 13:31
My walkaround currently is to write `server_port: "12345"` instead of `server_port: 12345`, so string comparison works.

**Comment by onmeac** [comment] 2017-01-13 20:02
That workaround does not work for values like true or false.

"True" 'True' or any lower case form will always ini.options_present act, same goes for false.

**Closed** 2017-06-13 20:19 UTC
Labels: Bug, High Severity, P3, Platform, State Module
