### ISSUE TITLE
salt-ssh roster scan multiple minions

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#52675] opened 2019-04-24 06:12 UTC
### Description of Issue/Question
I know salt-ssh roster scan can execute command on one minion or on network segment.now I want to execute command on two minions on different network segment.I don‘t want to use /etc/salt/roster .I just want to use scan.what should i do? Thanks.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
![图片](https://user-images.githubusercontent.com/23496061/56636281-d0778000-669a-11e9-8bb5-310cf8d76fd8.png)

![图片](https://user-images.githubusercontent.com/23496061/56636291-dd946f00-669a-11e9-8263-507d50c6ea3b.png)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by DmitryKuzmenko** [comment] 2019-04-25 17:29
@liuhetongzi the described functionality never was implemented in `scan` roster. Your requests sounds reasonable for me but it's not a bug. So I'm marking this as a feature request.

Since it's very easy to do, I've already implemented it. It would come to develop branch but you can apply the PR to your code locally.

**Closed** 2020-09-08 20:19 UTC
Labels: Confirmed, Feature, Magnesium, Salt-SSH, team-ssh
