### ISSUE TITLE
Salt not detecting some KVM VMs properly

### ISSUE THREAD

**Issue by ALinuxNinja** [saltstack/salt#17090] opened 2014-11-01 23:17 UTC
For some reason, Salt is not detecting that my Vultr VPS is actually a KVM server and detects it as a physical machine.

Output of grains.items
```
Melanie:
  biosreleasedate: 04/01/2014
  biosversion: rel-1.7.5-0-ge51488c-20140602_164612-nilsson.home.kraxel.org
  cpu_flags: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm xsaveopt fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm
  cpu_model: Vultr Virtual CPU 2
  cpuarch: x86_64
  defaultencoding: None
  defaultlanguage: None
  domain: 
  fqdn: Melanie
  fqdn_ip4:
      127.0.0.1
  fqdn_ip6:
  gpus:
      {'model': 'SVGA II Adapter', 'vendor': 'unknown'}
  host: Melanie
  hwaddr_interfaces: {'lo': '00:00:00:00:00:00', 'eth0': '52:54:00:fd:04:dc', 'eth1': '52:54:00:aa:d6:da', 'tap0': '96:8a:52:0a:a9:5a'}
  id: Melanie
  ip_interfaces: <snip>
  ipv4:
<snip>
  ipv6:
<snip>
  kernel: Linux
  kernelrelease: 3.13.0-37-generic
  localhost: Melanie
  lsb_distrib_codename: trusty
  lsb_distrib_description: Ubuntu 14.04.1 LTS
  lsb_distrib_id: Ubuntu
  lsb_distrib_release: 14.04
  manufacturer: QEMU
  master: 167.160.167.225
  mem_total: 741
  nodename: Melanie
  num_cpus: 1
  num_gpus: 1
  os: Ubuntu
  os_family: Debian
  osarch: amd64
  oscodename: trusty
  osfinger: Ubuntu-14.04
  osfullname: Ubuntu
  osrelease: 14.04
  path: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
  productname: Standard PC (i440FX + PIIX, 1996)
  ps: ps -efHww
  pythonpath:
      /usr/bin
      /usr/lib/python2.7
      /usr/lib/python2.7/plat-x86_64-linux-gnu
      /usr/lib/python2.7/lib-tk
      /usr/lib/python2.7/lib-old
      /usr/lib/python2.7/lib-dynload
      /usr/local/lib/python2.7/dist-packages
      /usr/lib/python2.7/dist-packages
  pythonversion: 2.7.6.final.0
  saltpath: /usr/lib/python2.7/dist-packages/salt
  saltversion: 2014.1.13
  saltversioninfo:
      2014
      1
      13
      0
  serialnumber: Not Specified
  server_id: 89861426
  shell: /bin/sh
  virtual: physical
  zmqversion: 4.0.4
```

**Comment by Silvenga** [comment] 2015-03-17 02:01
Same issue:

```
dmidecode -s system-product-name
KVM
```

```
lshw -class system
    description: Computer
    product: KVM ()
    vendor: Red Hat
    version: RHEL 6.6.0 PC
    width: 64 bits
    capabilities: smbios-2.4 dmi-2.4 vsyscall32
    configuration: boot=normal family=Red Hat Enterprise Linux uuid=26361ED7-7D5C-42D7-9BC7-C2170204DAAF
```
However:

```
salt-call grains.get virtual
local:
    physical
```

```
salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by dmurphy18** [comment] 2015-04-14 21:34
I have not been able to reproduce this issue with minions on both local and remote KVM's to the salt-master, on Ubuntu 14.04.02, using salt 2014.7.1.  The KVM's were running Centos 6.6.

![image](https://cloud.githubusercontent.com/assets/9943204/7147800/dc1bc6f4-e2ba-11e4-9830-63f215ac33ed.png)

@StartledPhoenix Can you upgrade your version of salt and see if the problem still exists with your Vultr VPS.

**Comment by Silvenga** [comment] 2015-04-15 02:37
I don't believe this issue is solved. Running *Salt 2014.7.2* I'm still getting incorrect results from the virtual grain. 
```
salt-call --versions-report
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
```

```
salt-call grains.get virtual
local:
    physical
```

However, the container uses KVM:

```
dmidecode -s system-product-name
KVM
```

**Comment by dmurphy18** [comment] 2015-04-28 16:35
@StartledPhoenix @Silvenga  Could both of you send the complete output of running 'dmidecode' with no options, on your platforms, as it would assist in resolving this  issue.

Thanks

**Comment by dmurphy18** [comment] 2015-06-03 20:21
I obtained an account on Vultr with a Centos 6.6. instance with the latest salt and this appears to now function correctly:
root@vultr:~/tools# salt-call grains.get virtual
local:
    kvm
root@vultr:~/tools# 
root@vultr:~/tools# salt-call --versions-report
           Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
root@vultr:~/tools# 

@StartledPhoenix Can you upgrade your version of salt and see if the problem still exists with your Vultr

**Comment by dmurphy18** [comment] 2015-06-09 00:49
Closing due to working in 2015.5.1 on Vultr VPS

**Closed by dmurphy18** 2015-06-09 00:49 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P4, Platform Mgmt
