### ISSUE TITLE
zeromq not working with ipv6 in newest zmq release

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#24712] opened 2015-06-16 16:56 UTC
Hey all,

Can someone take a look at this?

https://bugs.archlinux.org/task/45345
```
I started to report on this in https://bugs.archlinux.org/task/45316 but it seems that these are two separate issues, hence the new report.

After upgrading zeromq (4.0.5-1 -> 4.1.1-1) and python2-pyzmq (14.6.0-1 -> 14.6.0-2) salt-zmq does not work anymore. The client gets stuck in an infinite loop with the uninformative error message »invalid argument«. Downgrading both packages makes the same setup work again instantly.

I've tried with the just-released zeromq 4.1.2-1 and python2-pyzmq 14.6.0-3, but no dice.

I've narrowed it down to the problem only occurring if IPv6 support is enabled and used. Otherwise salt-zmq seems to work just fine.

Here's a minimal test case which I've just verified produces the problem:

1. pacstrap a minimal installation, e.g. »mkdir ~/tmp/salt-zeromq-test && pacstrap -c -d ~/tmp/salt-zeromq-test base«
2. set a password for root in side the container
3. start a container with that installation: »systemd-nspawn -bD ~/tmp/salt-zeromq-test«
4. Login in as root
5. Install salt-zmq, don't start salt just yet
6. make sure »localhost« resolves to both IPv4 and IPv6 addresses
7. configure salt-master to use IPv6, e.g. create /etc/salt/master.d/test.conf with the following content:

ipv6: true
listen: "::"

8. Start salt-master
9. configure salt-minion to use »localhost« as the master, but no IPv6 yet, e.g. create /etc/salt/minion.d/test.conf with the following content:

master: localhost

10. Start the minion; accept the minion's key with »salt-key -A«
11. Stop the minion and configure it to use IPv6 by adjusting the content of /etc/salt/minion.d/test.conf to the following content:

master: localhost
ipv6: true

12. start the minion and observe the aforementioned »invalid argument« message

If you want to verify that the downgrade fixes things: stop the master and the minion, downgrade zeromq to 4.0.5-x and python2-pyzmq to 14.6.0-1, start the master, start the minion.
```
Is this something that can be fixed in salt, or does it need to go to zmq?

Thanks!
Daniel

**Comment by seblu** [comment] 2015-06-16 17:08
Here is a traceback I got on one of my computer with salt ipv6 enabled.
```
# salt-call test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ZMQError: Invalid argument
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 59, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 69, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 92, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 322, in __init__
    self.gen_modules(initial_load=True)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 334, in gen_modules
    self.opts['environment']
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 48, in get_pillar
    pillar=pillar)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 62, in __init__
    self.channel = salt.transport.Channel.factory(opts)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 61, in factory
    return ZeroMQChannel(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 268, in __init__
    self.auth = salt.crypt.SAuth(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 269, in __new__
    SAuth.instances[key].__singleton_init__(opts)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 308, in __singleton_init__
    self.authenticate()
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 326, in authenticate
    creds = self.sign_in(timeout, safe)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 687, in sign_in
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 283, in send_auto
    return self.send(enc, load, tries, timeout)
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 259, in send
    self.socket.send(pkg)
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 214, in socket
    self._socket.connect(self.master)
  File "zmq/backend/cython/socket.pyx", line 478, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4308)
ZMQError: Invalid argument
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 59, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 69, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 92, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 322, in __init__
    self.gen_modules(initial_load=True)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 334, in gen_modules
    self.opts['environment']
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 48, in get_pillar
    pillar=pillar)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 62, in __init__
    self.channel = salt.transport.Channel.factory(opts)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 61, in factory
    return ZeroMQChannel(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 268, in __init__
    self.auth = salt.crypt.SAuth(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 269, in __new__
    SAuth.instances[key].__singleton_init__(opts)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 308, in __singleton_init__
    self.authenticate()
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 326, in authenticate
    creds = self.sign_in(timeout, safe)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 687, in sign_in
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 283, in send_auto
    return self.send(enc, load, tries, timeout)
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 259, in send
    self.socket.send(pkg)
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 214, in socket
    self._socket.connect(self.master)
  File "zmq/backend/cython/socket.pyx", line 478, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4308)
zmq.error.ZMQError: Invalid argument
```

**Comment by techhat** [comment] 2015-06-16 17:12
#24630

**Comment by gtmanfred** [comment] 2015-06-16 17:22
It looks like this issue might still be a problem even with 4.1.2 working for what was broken in that one.

I asked that the reporter check again.

**Comment by seblu** [comment] 2015-06-16 18:09
That seems better with 4.1.2 but there is still issue with the master.

```
# pacman -Q zeromq python2-pyzmq salt-zmq
zeromq 4.1.2-1
python2-pyzmq 14.6.0-3
salt-zmq 2015.5.2-2
# salt-call test.ping                    
local:
    True
# salt black test.ping
Invalid argument
# salt -l debug black test.ping 
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: black
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: black
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-06-16T18:06:58.569670'}
[DEBUG   ] LazyLoaded nested.output
Invalid argument
# salt-run  manage.status 
Invalid argument
# salt-run -ldebug manage.status      
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: black
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] LazyLoaded manage.status
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-06-16T18:07:57.882319'}
[DEBUG   ] Sending event - data = {'fun': 'runner.manage.status', 'jid': '20150616200757881613', 'user': 'root', '_stamp': '2015-06-16T18:07:57.882923'}
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: black
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-06-16T18:07:57.970423'}
Invalid argument
[DEBUG   ] LazyLoaded nested.output
[DEBUG   ] Sending event - data = {'jid': '20150616200757881613', 'return': {}, 'success': True, '_stamp': '2015-06-16T18:07:58.008598', 'user': 'root', 'fun': 'runner.manage.status'}
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: black
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20150616200757881613
[DEBUG   ] Runner return: {}
```

**Comment by mbunkus** [comment] 2015-06-16 18:28
I'm the original reporter of the bug on Arch Linux's bug tracker. I can confirm that I can reproduce the issue with zeromq 4.1.2, both in the »salt« executable as well as in the minion. My setup is a fresh, minimal Arch Linux bootstrapped installation running inside a systemd-nspawn'ed container, with a fresh salt-zmq package and zeromq 4.1.2. The only configuration I've done is to enable IPv6 for the master by setting `ipv6: true` and `listen: "::"`.

For the tests involving the minion I've configured the minion to use IPv4 only, then connected to the master, approved the key and then switched IPv6 on for the minion, too.

I've included a list of all the steps I've taken for this test case in the Arch Linux bug report.

As I'm not a Python hacker myself I cannot really contribute to the bug hunt inside Salt or the Python modules for zeromq, I'm afraid, but if you need anything in terms of information just ask and I'll gladly provide it.

**Comment by thatch45** [comment] 2015-06-17 17:44
@cachedout @msteed from a quick glance it looks like zmq has made an api change, we might need to version check somewhere in Salt before this hits other distros.

**Comment by melvyn-sopacua** [comment] 2015-06-22 06:12
It's zmq.RECONNECT_IVL_MAX. Here's the test for it:

```python
import unittest
import zmq


class SocketOptsTestCase(unittest.TestCase):
    def setUp(self):
        self.test_dict = (
            (zmq.RECONNECT_IVL_MAX, 5000, 'RECONNECT_IVL_MAX'),
            (zmq.TCP_KEEPALIVE, True, 'TCP_KEEPALIVE'),
            (zmq.TCP_KEEPALIVE_IDLE, 300, 'TCP_KEEPALIVE_IDLE'),
            (zmq.TCP_KEEPALIVE_CNT, -1, 'TCP_KEEPALIVE_CNT=-1'),
            (zmq.TCP_KEEPALIVE_INTVL, -1, 'TCP_KEEPALIVE_INTVL=-1'),
            (zmq.TCP_KEEPALIVE_CNT, 30, 'TCP_KEEPALIV_CNT'),
            (zmq.TCP_KEEPALIVE_INTVL, 30, 'TCP_KEEPALIVE_INTVL'),
            (zmq.IDENTITY, 'mailtest'))
        self.dest6 = 'tcp://[::1]:4506'

    def test_socket_opts(self):
        context = zmq.Context()
        for opt_triple in self.test_dict:
            socket = context.socket(zmq.REQ)
            socket.setsockopt(opt_triple[0], opt_triple[1])
            try:
                socket.connect(self.dest6)
            except zmq.ZMQError:
                self.fail(opt_triple[2])
            else:
                self.assertGreater(
                    socket.getsockopt(zmq.FD), 0, opt_triple[2]
                )
                socket.close()


if __name__ == '__main__':
    unittest.main()
```

I checked, but there's no disconnect in integer values for between library and python binding, so it must be in libzmq itself.

**Comment by msteed** [comment] 2015-06-22 17:37
Minimal test case:
```python
import zmq

c = zmq.Context()
s = c.socket(zmq.REQ)
s.setsockopt(zmq.IPV6, True)                                                                                                               
s.connect('tcp://[::1]:4506')
```

Works on zeromq-4.0.6-1.

Fails on zeromq-4.1.1-1 and later:
```
Traceback (most recent call last):
  File "issue-24712.py", line 6, in <module>
    s.connect('tcp://[::1]:4506')
  File "zmq/backend/cython/socket.pyx", line 478, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4308)
zmq.error.ZMQError: Invalid argument
```

**Comment by msteed** [comment] 2015-06-22 19:10
Looks like it's getting tripped up on the address verification in `zmq::socket_base_t::connect()`, which fails on addresses that do not begin with an alphanumeric character.

**Comment by msteed** [comment] 2015-06-22 20:40
FIled [issue 43](https://github.com/zeromq/zeromq4-1/issues/43) against zeromq-4.1.

**Comment by melvyn-sopacua** [comment] 2015-06-23 07:45
That explains why after randomizing the options the first one always fails.

I took a look at zmq. Our ip_bracket is now doing the wrong thing, since they rolled their own inet_pton(3) in zmq_connect(), which now doesn't use brackets, contradicting a comment in our utils.ip_bracket:

> Convert IP address representation to ZMQ (URL) format. ZMQ expects
> brackets around IPv6 literals, since they are used in URLs.

which also makes detections fail in among others salt.payload. A work-around is to count the number of colons being greater than one for the detection and not using utils.ip_bracket.

**Comment by msteed** [comment] 2015-06-24 16:59
@gtmanfred, this should be fixed in the forthcoming zeromq-4.1.3. If you find otherwise, feel free to reopen this issue or create a new one.

**Closed by msteed** 2015-06-24 16:59 UTC
Labels: Blocker, Bug, Confirmed, Core, Critical, Upstream Bug

**Comment by mbunkus** [comment] 2015-06-24 17:00
Thank you all a lot for such a quick fix.

**Comment by seblu** [comment] 2015-06-24 17:07
Yes thanks !
