### ISSUE TITLE
Exception running state.apply from scheduler (state.check_result)

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#53502] opened 2019-06-16 20:20 UTC
### Description of Issue

Scheduled `state.apply` fails with `KeyError: 'state.check_result'`. Possibly related to #43931 or #49160.
 
```
[ERROR   ] Unhandled exception running state.apply
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 762, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 778, in apply_
    return sls(mods, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 1358, in sls
    _set_retcode(ret, high_)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 107, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
KeyError: 'state.check_result'
```

### Steps to Reproduce Issue

1. salt-master 2019.2.0 Py3 on Ubuntu 18.04
2. salt-minion 2019.2.0 Py3 on Windows 10 (run as a foreground process via `salt-minion.bat`). The error is not reproducible if the minion runs on Ubuntu 18.04.
3. Example state:

```
# example_state.sls
always-changes-and-succeeds:
  test.succeed_with_changes:
    - name: example_state
```

4. Schedule
```
# schedule.sls
scheduled_state:
  schedule.present:
    - function: state.apply
    - seconds: 15
    - job_args:
      - example_state
```

5. Apply the schedule:

```
$ sudo salt windows state.apply schedule
windows:
----------
          ID: scheduled_state
    Function: schedule.present
      Result: True
     Comment: Adding new job scheduled_state to schedule
     Started: 02:59:04.416278
    Duration: 46.829 ms
     Changes:

Summary for windows
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  46.829 ms
```

Contents of `C:\salt\conf\minion.d\_schedule.conf`:

```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, name: __mine_interval, return_job: false, run: true, run_on_start: true,
    splay: null}
  scheduled_state:
    args: [example_state]
    enabled: true
    function: state.apply
    jid_include: true
    maxrunning: 1
    name: scheduled_state
    seconds: 15
```

6. Wait until you see the following traceback in the minion log:

```
[ERROR   ] Unhandled exception running state.apply
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 762, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 778, in apply_
    return sls(mods, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 1358, in sls
    _set_retcode(ret, high_)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 107, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
KeyError: 'state.check_result'
```

`__utils__` dictionary seems to be empty.

### Versions Report

<details>
<summary>master:~$ sudo salt --versions-report</summary>

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

<details>
<summary>c:\salt>salt-call --versions-report</summary>

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```
</details>

**Comment by max-arnold** [comment] 2019-09-26 05:45
I'm not 100% sure, but it looks like issue goes away when I add `multiprocessing: False` to the windows minion config. It has drawbacks though, so it is not a good workaround

**Comment by max-arnold** [comment] 2019-09-26 05:53
Still happens on 2019.2.1

**Comment by wasabi222** [comment] 2019-09-26 22:18
I was able to fix this by installing python3-pip on the Ubuntu 16.04 minion.

**Comment by oeuftete** [comment] 2019-12-12 22:13
> I'm not 100% sure, but it looks like issue goes away when I add `multiprocessing: False` to the windows minion config. It has drawbacks though, so it is not a good workaround

I was most definitely able to make this go away with `multiprocessing: False`.  Linking in https://github.com/saltstack/salt/issues/37865 re concerns about using this setting, though.

**Comment by SDedik** [comment] 2020-03-05 06:13
May I please kindly ask what is the status of the issue?
Because I posted bug report #56301 on the same problem and it was closed in favor of this one, but seeing how this one has "High Severity" label, "P2 (The issue will be seen by most users)" label, has been in this state for half a year already and no progress has been done on it staggers me a bit.
I mean no disrespect, but this issue is game breaking for me. Client-Server architecture and automatic state convergence is the whole reason why I chose Salt over Ansible and now it turns our that the very core functionality is defect.

**Comment by asmialoski** [comment] 2020-03-05 14:05
This issue is game breaking for me too.

**Comment by sagetherage** [comment] 2020-05-11 21:08
@SDedik the status of this issue is that it is in the backlog and we attempted to find resources for the Sodium release, but have been unable to do that above other priorities. I am looking to dedicate resources to it for the following release, Magnesium. We welcome community members to submit a PR for a fix, at this time there are no resources available on the Core Team.

**Comment by max-arnold** [comment] 2020-07-25 10:31
Still happens on 2019.2.5 and 3001 too.

**Comment by Mateo-neo** [comment] 2020-08-18 09:51
Up. Any ideas? i have 3 *.sls and it's work from bash. But from sheduler (state.apply or state.sls) doesn't work

**Comment by sagetherage** [comment] 2020-08-18 16:01
@Mateo-neo I have this set for the Core Team to work and fix in this release cycle, but you're correct that hasn't started, yet. @garethgreenaway is assigned and has other work right now, but I expect he will start looking at this soon, if not I can reassign it.

**Comment by garethgreenaway** [comment] 2020-09-11 22:38
Apologies for the delay on this one.  Was able to reproduce, found the cause, have a fix in place, and just need to get some tests in place.  Should hopefully have this ready for Magnesium.

**Closed** 2020-09-30 21:07 UTC
Labels: CS-R2, CS-S3, Fixed Pending Verification, Magnesium, Severity: Medium, ZD

**Comment by Urmila4718** [comment] 2024-09-04 08:27
> Apologies for the delay on this one. Was able to reproduce, found the cause, have a fix in place, and just need to get some tests in place. Should hopefully have this ready for Magnesium.

Hello @garethgreenaway, Just the update, we are facing this issue in 3006.9 (sulfur) also.

**Comment by dmurphy18** [comment] 2024-09-04 16:52
@Urmila4718 Unfortunately @garethgreenaway is no longer with the Salt Team, and this issue was closed almost 4 years ago and is too old to reopen. Please open a new issue describing the problem encountered, steps to reproduce, versions report, etc. and reference this issue too. 
Thanks
