### ISSUE TITLE
integration.cloud.clouds.test_ec2.EC2Test.test_win2016_psexec

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52824] opened 2019-05-02 22:20 UTC
2019.2.1 failed [salt-centos-7-py2-cloud](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-cloud/11/testReport/junit/integration.cloud.clouds.test_ec2/EC2Test/test_win2016_psexec)
---

u'CLOUD-TEST-VFJP7P:' not found in []

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_ec2.py", line 263, in test_win2016_psexec
    self._test_instance('ec2-win2016-test', debug=True, timeout=TIMEOUT)
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_ec2.py", line 157, in _test_instance
    self.assertIn(ret_str, instance)
AssertionError: u'CLOUD-TEST-VFJP7P:' not found in []
		
```

**Comment by Ch3LL** [comment] 2019-05-03 13:50
duplicate of https://github.com/saltstack/salt/issues/52447

**Closed by Ch3LL** 2019-05-03 13:50 UTC
Labels: 2019.2.1, Test Failure
