### ISSUE TITLE
file.search always returns True?

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#20603] opened 2015-02-11 21:00 UTC
This seems broken...file.search always returns True, even if the pattern is not present.

```
# salt-call --local file.search /etc/rsyslog.conf 'foo':
local:
    True
```

```
# grep -c foo /etc/rsyslog.conf
0
```

```
# salt-call --local --versions
           Salt: 2014.7.1
         Python: 2.6.9 (unknown, Sep 13 2014, 00:25:11)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by cachedout** [comment] 2015-02-11 22:43
Could you try a more confied test? This seems to work for me:

```
mp@silver ...salt/salt/cli % sudo salt-call --local file.search /tmp/foo 'boo'                                                                                                      (git)-[2014.7] 
local:
    False
mp@silver ...salt/salt/cli % sudo salt-call --local file.search /tmp/foo 'baz'                                                                                                      (git)-[2014.7] 
local:
    True
mp@silver ...salt/salt/cli % cat /tmp/foo                                                                                                                                           (git)-[2014.7] 
baz
mp@silver ...salt/salt/cli %      
```

**Comment by lorengordon** [comment] 2015-02-11 22:52
Ugh, that's just frustrating. I tried with your example and it functions as expected. But anytime I search the file that actually matters, file.search always returns true. Can you try with more complex files?

**Comment by lorengordon** [comment] 2015-02-13 19:18
@cachedout Any chance you've been able to test on more complex files? I can reproduce this across different systems, over and over. I'm testing on Amazon Linux, in case that makes a difference.

**Comment by lorengordon** [comment] 2015-02-13 20:05
Just tested on Centos 6.6 and confirmed the problem there as well.

**Comment by lorengordon** [comment] 2015-02-13 20:20
@cachedout, I figured out a definitive test case. An empty line in the file will cause file.search to always return true.

```
# echo "baz" > ~/foo
# salt-call --local file.search ~/foo 'bar'
local:
    False
# echo "" >> ~/foo
# salt-call --local file.search ~/foo 'bar'
local:
    True
```

**Comment by lorengordon** [comment] 2015-02-13 20:29
This appears to affect any white space. Blank files (echo "" > foo), files with null lines (echo >> file), null files (echo > file), and even files with lines that contain only spaces (echo " " >> file).

**Comment by ferricoxide** [comment] 2015-02-18 05:39
There appears to be a few significant regressions in `file.search` since `salt-2014.7.1-1.el6.noarch.rpm` was published to EPEL. Regexes that worked flawlessly in `salt-2014.7.0-3.el6.noarch.rpm` now function completely differently than before (things that previously evaluated to false now evaluate to true).

**Comment by ferricoxide** [comment] 2015-02-18 06:05
Under 2014-7.0-3:
~~~
# echo "baz" > /tmp/foo
# salt-call --no-color --local file.search /tmp/foo 'bar'
local:
    False
# echo "" >> /tmp/foo
# salt-call --no-color --local file.search /tmp/foo 'bar'
local:
    False
# salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
~~~
Under 2014-7.1-1:
~~~
# echo "baz" > /tmp/foo
# salt-call --no-color --local file.search /tmp/foo 'ba r'
local:
    False
# echo "" >> /tmp/foo
# salt-call --no-color --local file.search /tmp/foo 'ba r'
local:
    True
[root@ip-172-31-18-194 ~]# salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
~~~
Other regex errors similarly show up after moving from 2014.7.0 to 2014.7.1 - but they probably all stem from similar "True should be False" conditions.

**Comment by lorengordon** [comment] 2015-02-18 12:44
Just tested with 2014.7.2 and can confirm the issue exists there as well.

```
# echo "baz" > ~/foo
# salt-call --local file.search ~/foo 'bar'
local:
    False
# echo "" >> ~/foo
# salt-call --local file.search ~/foo 'bar'
local:
    True
# salt-call --versions-report
           Salt: 2014.7.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by lorengordon** [comment] 2015-02-18 16:46
Well, I think I figured out what's going on here. The `replace` function in the `file.py` module was updated to check first whether the replacement string already exists in the file. As part of adding that feature, with commit a4dfb8af38cee5f57fb580a7c8b86e644ee719f4, the `search_only` behavior was modified; it no longer searches for the pattern and returns.

I would guess @eliasp modified the `search_only` behavior believing that the `if line == repl` test at line 1148 (tag v2014.7.1) would cover the desired behavior. However, when using `file.search` in particular, `repl` is always set to `''`. This means that whenever `file.search` encounters a blank line, then the test passes (as both `line==''` and `repl==''`) and `file.replace` returns `True`, regardless of the pattern that was actually passed in.
https://github.com/saltstack/salt/blob/v2014.7.1/salt/modules/file.py#L1148 

For the desired behavior, we actually want to test whether `line` contains the regex `cpattern`.

I'm struggling to understand the use case where `search_only` would be relevant within the `try` statement at L1127 checking whether the `repl` string is already present. For it to be relevant, someone would have to call `file.replace` with `search_only=True`, as well as values for `pattern` and `repl`. Would the desired behavior in that case be to return `True` if `repl` is present or return `True` if `pattern` is present? And for some reason we're doing it this way rather than just checking for two different patterns? If this type of behavior is desired (search for multiple patterns), it seems it would make more sense just to accept a list of patterns.

If it's not relevant, from my read of the code, the `if search_only` blocks can probably come out of that `try` block. 

I ask because the answer influences the best place to re-add the correct `search_only` behavior. Would it go in the try block at L1127, or the try block at L1157?

The working code from the prior commit is:
```
            if search_only:
                # Just search; bail as early as a match is found
                result = re.search(cpattern, line)

                if result:
                    return True  # `finally` block handles file closure
```

**Comment by cachedout** [comment] 2015-03-25 19:36
@lorengordon I see a number of commits that have been merged that reference this issue. Has it been resolved to your satisifaction or is there additional work to be done here?

**Comment by lorengordon** [comment] 2015-03-25 19:43
@cachedout, this was fixed by https://github.com/saltstack/salt/pull/21050, and it's been merged forward. I believe the issue can be closed.

**Comment by cachedout** [comment] 2015-03-25 20:17
Great! Thanks for the quick response and your excellent work on this issue, @lorengordon

**Closed by cachedout** 2015-03-25 20:17 UTC
Labels: Bug, Confirmed, High Severity
