### ISSUE TITLE
Unable to set 'Not Configured' using win_lgpo execution module

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#42600] opened 2017-07-27 19:59 UTC
### Description of Issue/Question
You can Enable and Disable a local group policy, but setting the policy to 'Not Configured' reports success but fails to make the change.

### Setup
Enable the following group policy object using `gpedit.msc`:
`Computer Configuration\Administrative Templates\Windows Components\Configure Automatic Updates`

### Steps to Reproduce Issue
Run the following command to set the Object to `Not Configured`
```
salt <minion name> lgpo.set_computer_policy 'Configure Automatic Updates' 'Not Configured'
```
The above command returns:
```
<minion name>:
    True
```
Look at the policy in `gpedit.msc` and it is still 'Enabled'. (`gpedit.msc` is refreshed by closing and opening.)

### Versions Report
```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```
Tag: @lomeroe

**Comment by lomeroe** [comment] 2017-08-01 14:43
@twangboy I cannot duplicate this.  Are you closing the local policy editor and reopening it after running the set_computer_policy?  The mmc snapin does not refresh dynamically and "gpedit.msc" must be restarted after making any changes via the salt module.

My steps:

1. run 'gpedit.msc', set the 'Configure Automatic Updates' policy to 'Enabled'
2. close the local policy editor
3. run the lgpo.set_computer_policy.  I am running in masterless, so my command exactly is:
```
salt-call lgpo.set_computer_policy 'Configure Automatic Updates' 'Not Configured' --local
```
4. run 'gpedit.msc' and policy now shows 'Not Configured'

I tested with both of these versions:
```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```
```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```

**Comment by twangboy** [comment] 2017-08-02 17:54
@lomeroe I was restarting gpedit (or I thought I was). I will test again to be sure and post the results here.

**Comment by twangboy** [comment] 2017-08-02 19:48
I'm still having this problem on Windows Server 2016. Here are my results so far:

Get the current "Configure Automatic Updates" policy. It's the last one shown with `lgpo.get machine`:

```
salt-call --local lgpo.get machine
...
        Windows Components\Windows Update\Configure Automatic Updates:
            Disabled
```

Set the policy to 'Not Configured':

```
salt-call --local lgpo.set_computer_policy "Configure Automatic Updates" "Not Configured"
local:
    True
```

Check the "Configure Automatic Updates" policy again:

```
salt-call --local lgpo.get machine
...
        Windows Components\Windows Update\Configure Automatic Updates:
            Disabled
```

Verify that the policy has not changed using `gpedit.msc` (opened new). Still set to "Disabled".

While `gpedit.msc` is open, set the "Configure Automatic Updates" policy to "Enabled". Close `gpedit.msc` and try again to see if maybe the issue is when going from "Enabled" to "Not Configured".

```
salt-call --local lgpo.set_computer_policy "Configure Automatic Updates" "Not Configured"
local:
    True
```

Check the "Configure Automatic Updates" policy again:
```
salt-call --local lgpo.get machine
...
        Windows Components\Windows Update\Configure Automatic Updates:
            ----------
            Configure automatic updating:
                3 - Auto download and notify for install
            Install during automatic maintenance:
                False
            Install updates for other Microsoft products:
                False
            Scheduled install day:
                0 - Every day
            Scheduled install time:
                03:00
```

Verify that the policy has not changed using `gpedit.msc` (opened new). Still set to "Enabled".

Will test on a 2012R2 box and report results here.

**Comment by twangboy** [comment] 2017-08-02 20:01
Same results on 2012R2. I'm running everything in an Elevated command prompt (Administrator). I also tried from an elevated Powershell prompt. I don't know what else I could be doing differently.

**Comment by lomeroe** [comment] 2017-08-02 22:12
@twangboy I will do another round of tests too.

**Comment by lomeroe** [comment] 2017-08-03 15:57
Ok, I figured out why my tests were succeeding.  I have other ADM templates set on the machine I was testing on.  If you configure another policy, then lgpo will correctly "Not Configure" the policy...

Now to track down why that is...

**Comment by lomeroe** [comment] 2017-08-03 17:12
@twangboy could you run the test branch mentioned above and verify that the problem is gone for you with this update too?

**Comment by twangboy** [comment] 2017-08-03 17:43
@lomeroe That worked beautifully!

**Closed** 2017-08-04 15:57 UTC
Labels: Bug, High Severity, P2, Platform, Windows
