### ISSUE TITLE
[BUG] onchanges_any triggers infinite recursion loop if the watched file isn't managed

### ISSUE THREAD

**Issue by tomlaredo** [saltstack/salt#56822] opened 2020-04-22 12:15 UTC
**Description**
onchanges_any triggers an infinite recursion loop if a whatched file isn't present in any other salt state (= not managed) whereas onchanges works properly.

Secondly and more generaly, watching (by using "watch", "onchanges*"...) files that are not managed by salt should show a warning but not fail with an error as it currently does.

**Setup**

```
command-test:
    cmd.run:
        - name: ls
        - onchanges_any:
            - file: /tmp/an-unfollowed-file
```

**Steps to Reproduce the behavior**

```
server:~# salt-call state.apply test_onchanges
```

<details><summary>See traceback of recursion loop here:</summary>

```
[INFO    ] Got list of available master addresses: ['master.salt.rodacom.net']
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'test_onchanges.sls'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
RecursionError: maximum recursion depth exceeded in __instancecheck__
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.1', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 782, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 1351, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2909, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2271, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)
  [Previous line repeated 982 more times]
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2604, in call_chunk
    status, reqs = self.check_requisite(low, running, chunks, pre=True)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2446, in check_requisite
    if (fnmatch.fnmatch(chunk['name'], req_val) or
  File "/usr/lib/python3.7/fnmatch.py", line 34, in fnmatch
    name = os.path.normcase(name)
  File "/usr/lib/python3.7/posixpath.py", line 55, in normcase
    if not isinstance(s, (bytes, str)):
RecursionError: maximum recursion depth exceeded in __instancecheck__
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.1', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 782, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 1351, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2909, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2271, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)
  [Previous line repeated 982 more times]
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2604, in call_chunk
    status, reqs = self.check_requisite(low, running, chunks, pre=True)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2446, in check_requisite
    if (fnmatch.fnmatch(chunk['name'], req_val) or
  File "/usr/lib/python3.7/fnmatch.py", line 34, in fnmatch
    name = os.path.normcase(name)
  File "/usr/lib/python3.7/posixpath.py", line 55, in normcase
    if not isinstance(s, (bytes, str)):
RecursionError: maximum recursion depth exceeded in __instancecheck__
```
</details>

Try to change onchanges_any to onchanges and it will work properly:
```
server:~# salt-call state.apply test_onchanges
[INFO    ] Got list of available master addresses: ['master.salt.rodacom.net']
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'test_onchanges.sls'
local:
----------
          ID: command-test
    Function: cmd.run
        Name: ls
      Result: False
     Comment: The following requisites were not found:
                                 onchanges:
                                     file: /tmp/an-unfollowed-file
     Started: 12:53:22.405591
    Duration: 0.004 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.004 ms
```

Related to:

- https://github.com/saltstack/salt/issues/50811
- https://github.com/saltstack/salt/issues/47154
- https://github.com/saltstack/salt/issues/56133 (for me, onchanges should act as onchanges_any does)

**Versions Report**
<details><summary>salt-call --versions-report</summary>
```
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10.3
         locale: UTF-8
        machine: x86_64
        release: 5.3.13-1-pve
         system: Linux
        version: debian 10.3
```
</details>

**Comment by twangboy** [comment] 2023-08-31 22:30
Duplicate of https://github.com/saltstack/salt/issues/47154

**Closed by twangboy** 2023-08-31 22:30 UTC
Labels: Bug, severity-medium, Duplicate, Confirmed
