### ISSUE TITLE
service.dead tries to start service

### ISSUE THREAD

**Issue by lsh-0** [saltstack/salt#20858] opened 2015-02-20 11:16 UTC
I have a flag switching services to 'dead' if it looks like it's provisioning a Docker container. The config looks a bit like:

```
    service:
        - {% if salt['grains.get']('dockerized') %}dead{% else %}running{% endif %}
        - require:
            - pkg: syslog-ng
```
However when running for the first time, I get this:
```
    State: - service
    Name:      syslog-ng
    Function:  dead
        Result:    False
        Comment:   Failed to start the service
        Changes:   syslog-ng: False
```
Subsequent runs succeed with:
```
    State: - service
    Name:      syslog-ng
    Function:  dead
        Result:    True
        Comment:   The service syslog-ng is already dead
        Changes:   
```

Is this a bug or expected behaviour?

**Comment by rallytime** [comment] 2015-02-20 23:08
@lsh-0 Is that first state the entire state that you're running, or just a piece of it? It looks like something isn't quite right there.

Also, can you post the output of `salt --versions-report`?

**Comment by lsh-0** [comment] 2015-02-23 12:29
That was just a snippet. The full state is/was:
```
syslog-ng:
    pkg.installed:
        - pkgs:
            - syslog-ng
            - syslog-ng-core
    
    file.managed:
        - name: /etc/syslog-ng/syslog-ng.conf
        - source: salt://base/config/etc-syslog-ng-syslog-ng.conf 
        - template: jinja
        - require:
            - pkg: syslog-ng
            
    service:
        {% if salt['grains.get']('dockerized') %}- dead{% else %}- running{% endif %}
        - reload: True
        - require:
            - pkg: syslog-ng
            - file: syslog-ng
        - watch:
            - file: syslog-ng
```

**Comment by rallytime** [comment] 2015-02-24 00:05
Thanks for added your state. I wonder if the first run is triggering the `watch`, which would throw away the original return data and replace it with the data from `mod_watch`, which may not be handling `service.dead` correctly. 

@lsh-0 If you remove the watch from your state, can your still reproduce this error?

**Comment by rallytime** [comment] 2015-05-04 01:31
@lsh-0 Just a bump here to see if you were able to reproduce the error even after removing the `watch` requisite from your state.

**Comment by lsh-0** [comment] 2015-06-05 15:42
ah, sorry for not getting back to you. that code evolved quite a bit and was eventually removed.

**Comment by rallytime** [comment] 2015-06-05 15:50
@lsh-0 No problem. So would you still consider this a bug, or can we close this since we can't reproduce this?

**Comment by lsh-0** [comment] 2015-06-05 15:51
Please close it, I can't reproduce it any more. Thanks for your patience.

On Fri, Jun 5, 2015 at 4:51 PM, Nicole Thomas <notifications@github.com>
wrote:

> @lsh-0 <https://github.com/lsh-0> No problem. So would you still consider
> this a bug, or can we close this since we can't reproduce this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/20858#issuecomment-109338442>.
>



-- 

Luke Skibinski

A human being.
Slinging code, wrangling data.
Just being human.

--

eLife Sciences Publications, Ltd is a limited liability non-profit
non-stock corporation incorporated in the State of Delaware, USA, with
company number 5030732, and is registered in the UK with company number
FC030576 and branch number BR015634 at the address First Floor, 24 Hills
Road, Cambridge CB2 1JP.

**Comment by rallytime** [comment] 2015-06-05 15:54
No problem at all! Thanks very much. :)

**Closed by rallytime** 2015-06-05 15:54 UTC
Labels: Info Needed

**Comment by cystek** [comment] 2015-10-06 20:11
I found this issue from similar circumstances of service.dead not stopping a service properly. I can confirm that commenting out watch conditions does cause the state to properly kill the service, so I assume your mod_watch assumption is correct.
