### ISSUE TITLE
Salt-ssh needs a way to set log-level for the remote side salt-call

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#29591] opened 2015-12-10 08:25 UTC
Actually there is an ability to specify minion_opts in the roster file but ssh-py-shim sets ```-l quiet``` command line argument that overrides minion config options. I propose to set quiet log level by default via minion config and update it with the roster minion_opts.
This would be helpful to get more information from customers in case of salt-ssh issues.

**Comment by basepi** [comment] 2015-12-10 23:52
@DmitryKuzmenko this is a duplicate of https://github.com/saltstack/salt/issues/16417 I think. You're welcome to work on it here or there.

I do not know if it will be as simple as increasing the loglevel. Otherwise on the master side it's hard to tell what was a return and what was logging. I'll be interested to see what you find.

**Comment by DmitryKuzmenko** [comment] 2015-12-11 06:52
Oops... Thank you @basepi , here I've behaved like a bad customer: created an issue without searching for an existing one. =)
BTW, the #16417 proposal looks more difficult but much more useful. Want to work on it. I'm going to close this one as a duplicate and self-assign #16417 for my backlog.

**Closed** 2015-12-11 06:52 UTC
Labels: Core, Duplicate, Feature, Salt-SSH

**Comment by basepi** [comment] 2015-12-11 17:53
Sounds great, thanks @DmitryKuzmenko.
