### ISSUE TITLE
DeprecationWarning on Debian installs

### ISSUE THREAD

**Issue by tj90241** [saltstack/salt#54801] opened 2019-09-29 16:45 UTC
### Description of Issue
A deprecation warning is shown in logs, when running the `salt` CLI, etc. when `2019.2.1` is installed on Debian 10.1 (buster).

```
[WARNING ] /usr/lib/python3/dist-packages/salt/transport/zeromq.py:42: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  import zmq.eventloop.ioloop
```

Manually installing `python3-tornado` and restarting the master/minion will make the deprecation notices disappear.  However, this does not make sense to me as the requirements for `2019.2.1` suggest that tornado4.x is the "right" choice for python3: https://github.com/saltstack/salt/blob/2019.2.1/requirements/base.txt#L9 and python3-tornado installs tornado 5.1.1-4.

### Setup
Install `2019.2.1` on Debian buster

### Steps to Reproduce Issue
Run `salt \* test.ping` on the master with at least one minion connected.  The deprecation warning will be displayed.

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.1 
         locale: UTF-8
        machine: x86_64
        release: 5.2.0-0.bpo.2-amd64
         system: Linux
        version: debian 10.1 
```

**Comment by SynPrime** [comment] 2019-09-29 20:26
Same here

**Comment by dwoz** [comment] 2019-09-29 22:09
duplicate of #54759

**Closed** 2019-10-13 23:45 UTC
Labels: Duplicate
