### ISSUE TITLE
pillar empty with ext_pillar

### ISSUE THREAD

**Issue by x70b1** [saltstack/salt#52319] opened 2019-03-26 12:02 UTC
I'm trying to use a git repo as a pillar. But it is still empty. This is my master config:

```
ext_pillar:
    - git:
        - master https://example.com/saltstack/pillar.git:
            - env: base
            - user: xxx
            - password: xxx
```

The `master` branch of my repo:
```
.
├── pushover
│   └── init.sls
└── top.sls
```

My top.sls:

```
base:
    '*':
        - pushover
```

I feel a little foolish. Have I forgotten something essential?

```
salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.28.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.0
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.8 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8 
```

**Comment by dmurphy18** [comment] 2019-03-27 16:11
@x70b1 sorry for the delay, had a comment and forgot to press 'Comment' before closing down.

Essentially, repeated your environment and it worked, however I did have one issue which took a while to identify: had three rather than two spaces as indent in a yaml file (essentially SLS files are yaml based), and yaml can be very picky about spaces (you'd think whitespace would be fine in this day and age).

Hence please check that you are using two spaces for all indents, secondly check that there is no mistake in the credentials supplied to git hub.

My /etc/salt/master:

 835 
 836 ext_pillar:
 837   - git:
 838     - master https://github.com/dabcdefg/test_salt.git:
 839       - user: 'dabcdefg'
 840       - password: 'pwd-to-use'

Also:
 955 git_pillar_user: 'dabcdefg'
 960 git_pillar_password: 'pwd-to-use'

Unsure if the git_pillar_user or git_pillar_password setting are required, as their setting was part of the debug process which resulted in finding 3 spaces instead of 2 used in one of the indents.

Also be sure to restart salt-master once changes are made to /etc/salt/master, and I also refresh the pillar items on the minion, for example:
 1985  systemctl restart salt-master
 1986  salt d9m saltutil.refresh_pillar
 1987  salt d9m pillar.items

Hopefully these suggestions will identify the issue in your environment.

**Comment by x70b1** [comment] 2019-03-28 15:23
@dmurphy18: Thanks a lot for your reply.

First of all, you're right. I'm using 4 characters as a indent instead of 2. That worked well so far. I tested a indent of 2 characters for confirmation. It didn't change anything.

The `git_pillar_user` and `git_pillar_password` statements don't change the result. 

I found this issue: https://github.com/saltstack/salt/issues/51894
Maybe there is a relationship? Of course the versions are different. 

Here are two log of my master which show an that there is something broken:

```
Current fetch URL for git_pillar remote 'master https://example.com/saltstack/pillar.git': https://example.com/saltstack/pillar.git (desired: https://example.com/saltstack/pillar.git)
[DEBUG   ] Current refspecs for git_pillar remote 'master https://example.com/saltstack/pillar.git': [u'+refs/heads/*:refs/remotes/origin/*', u'+refs/tags/*:refs/tags/*'] (desired: [u'+refs/heads/*:refs/remotes/origin/*', u'+refs/tags/*:refs/tags/*'])
[DEBUG   ] Current http.sslVerify for git_pillar remote 'master https://example.com/saltstack/pillar.git': true (desired: true)
[ERROR   ] Unable to get SHA of HEAD for git_pillar remote 'master https://example.com/saltstack/pillar.git'
[DEBUG   ] LazyLoaded localfs.init_kwargs
[DEBUG   ] Sending event: tag = minion/refresh/lab; data = {u'Minion data cache refresh': 'lab', u'_stamp': '2019-03-28T15:02:57.617697'}
[DEBUG   ] Gathering reactors for tag minion/refresh/lab
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
```

```
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] LazyLoaded local_cache.clean_old_jobs
[DEBUG   ] LazyLoaded localfs.list_tokens
[DEBUG   ] Set update lock for git_pillar remote 'master https://example.com/saltstack/pillar.git'
[DEBUG   ] Fetching git_pillar remote 'master https://example.com/saltstack/pillar.git'
[DEBUG   ] git_pillar remote 'master https://example.com/saltstack/pillar.git' is up-to-date
[DEBUG   ] pygit2 does not support detecting stale refs for authenticated remotes, saltenvs will not reflect branches/tags removed from remote 'master https://example.com/saltstack/pillar.git'
[DEBUG   ] Removed update lock for git_pillar remote 'master https://example.com/saltstack/pillar.git'
```

**Comment by dmurphy18** [comment] 2019-03-28 16:01
@x70b1 The problem may well be use of _https://example.com/saltstack/pillar.git_ which is not a real github repo.  I has assume that you had use https://example.com as filler since you did not want to state the actual github repo for legal/security reasons.

Please try with a real github repository.

For example: https://example.com

Example Domain
This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission.

Same for https://example.com/saltstack/pillar.git.

Closing this as working as intended.

Note that there is a community slack channel where help and advice on usage is available from Community users and SaltStack employees, https://saltstackcommunity.slack.com
There are other channels too on IRC

**Closed by dmurphy18** 2019-03-28 16:01 UTC
Labels: Cannot Reproduce

**Comment by x70b1** [comment] 2019-03-28 16:14
@dmurphy18: This is a filler to hide my real Git-Server.
I thought that was clear.
