### ISSUE TITLE
salt.module.run documentation improvement?

### ISSUE THREAD

**Issue by cr1st1p** [saltstack/salt#51349] opened 2019-01-26 09:18 UTC
### Description of Issue/Question
I wanted to run a module's function via module.run (namely systemd.force_reload).
Instead of the expected behavior I got an error related to the *name* of my state.
After spending some frustrating time, I discovered somehow that the documentation on how to use the module.run functionality forgets to mention that you need to enable the 'new' way of running it, via some 'superseeded' config entry.

Please:
- move at the TOP of the documentation, the part about 'this is new behavior', because you start the example WITH the new behavior syntax and people might not read the whole page to understand how it should be used and that in fact it does NOT work like.
- make the part about the 'superseeded'' configuration be PART of the same TOP paragraph and not even more down below.

Thank you.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by dwoz** [comment] 2019-01-27 23:37
@cr1st1p Thank you very much for the pull requests!

**Comment by devurandom** [comment] 2019-03-06 21:41
Is this related to or a duplicate of #44882?

**Comment by devurandom** [comment] 2019-03-06 21:43
How do I set `use_superseded` for `salt-ssh`?

**Closed** 2019-04-18 16:43 UTC
Labels: Documentation
