### ISSUE TITLE
memory leak in master schedule

### ISSUE THREAD

**Issue by mgwilliams** [saltstack/salt#17006] opened 2014-10-29 20:00 UTC
When running the following schedule, memory is leaked at a rate of approximately 200-300k per iteration:

```
$ cat /etc/salt/master.d/schedule.conf 
```
```yaml
schedule:
  test:
    function: test.arg
    seconds: 2
```

This was tested on 2014.7.0rc6-75-g0d0f2dd.

**Comment by hvnsweeting** [comment] 2015-01-19 08:25
I have the same problem with 3 gitfs_remotes,
And it for sure relate to gitfs. This is a graph for memory using on 512 MB machine, the MEMORY went down when I restart the salt-master (once per 2 days):

![saltmaster](https://cloud.githubusercontent.com/assets/1000665/5797553/191902b0-9fef-11e4-9b31-7b11c3007aa9.png)

````
salt --versions-report
           Salt: 2014.1.10
         Python: 2.7.3 (default, Dec 18 2014, 19:03:52)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.11
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
````

**Comment by arthurlutz** [comment] 2015-01-19 08:46
Oh and by the way : even when I disable gitfs (with local copies of the git repositories) the memory leak is the same.

**Comment by hvnsweeting** [comment] 2015-01-19 08:51
@arthurlutz  you mean you remove all gitfs relate config, including pillar?
it is not the case for me because when I disable gitfs, memory using is normal.

When gitfs is enabled, I notice that process check many files and after a long run (often when the memory using increased much) I see there are many opening fds using by salt-master, even reach 9000 files.

**Comment by hvnsweeting** [comment] 2015-01-20 08:37
@mgwilliams could you please provide which git back-end that you used?
as I'm using 2014.1, the only back-end is GitPython and I want to make sure the problem is in the back-end or the fileserver code. Thank you in advance.

**Comment by bhodges** [comment] 2015-02-04 06:21
I'm experiencing similar master worker excessive memory consumption symptoms which may be related to this bug report (this is the closest bug I could find...), although I am not using gifts.  I have roughly a dozen state trees and an equal number of pillar trees for various environments.  All of these trees are separate git repositories.  Currently, I am having to restart the master every two weeks or so, to periodically clear this up.

I did a bit of investigating, such as dumping and analyzing the heap for worker processes.  What I found was that approximately 80% of the consumption was due to lists of files residing within my state and pillar trees, and this was almost entirely made up of files found under .git directories.  As memory usage grows, redundancy is very evident in the file listing, the same files are repeated dozens of times in worker processes I inspected.

I grep'd around in the source and while unsure how/why this is occurring, my best guess is that the listing of files is coming from calls to file_list() in salt/fileserver/roots.py.  Perhaps somewhere within or near to master.py, there might be some sort of assignment of the results of file_list() occurring, and this is happening regularly (likely tied to my frequent, scheduled jobs) and in a way that seems to essentially be appending file_list results to the master worker instance.

**Comment by thedrow** [comment] 2015-02-04 06:25
@bhodges Can you post your versions list and memory usage over time?
Also kudos on the detective work. Very well done.

**Comment by bhodges** [comment] 2015-02-04 18:57
salt --versions-report
           Salt: 2014.1.10
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4

Below are some graphs that show VSZ for salt-master processes the 7 days following a master restart.

![master_processes_average_7d](https://cloud.githubusercontent.com/assets/404764/6047085/428b7046-ac5c-11e4-886a-f674c5b24834.png)

![master_processes_total_7d](https://cloud.githubusercontent.com/assets/404764/6047088/4c2bbc3c-ac5c-11e4-9eda-0ea648ce3573.png)

**Comment by bechtoldt** [comment] 2015-03-22 14:13
Can some experienced developers please fix this issue if its still present? IMHO Gitfs is one of the most important features of Salt. The above looks very weird.

**Comment by msteed** [comment] 2015-05-05 23:11
I'd like to get to the bottom of this. So far I haven't been able to reproduce the problem. I have tried 2014.1.10, 2014.7.0, and other more recent builds, using both pygit2 and GitPython. I have the git ```fileserver_backend``` with 8 repos in ```gitfs_remotes```. I can see that gitfs is getting hit pretty hard.

In all my tests the memory usage has remained steady. I'd like to work with someone who can reproduce it to figure out what is missing from my tests.

**Comment by mgwilliams** [comment] 2015-05-05 23:22
@msteed are you running something on a schedule in addition to using gitfs? I haven't looked into this in months, but that was my setup at the time.

**Comment by msteed** [comment] 2015-05-06 00:02
Yes @mgwilliams, sorry I forgot to mention that I am using your ```schedule.conf```.

**Comment by hvnsweeting** [comment] 2015-05-19 08:03
I'm not sure it relate to this or should I open new issue.
I still use the same old config, we upgraded our prod from ``2014.1.10`` to ``2014.7.5`` yesterday, now the memory goes worse.

So as on 2014.1.10, I think it relate to gitfs (because we have 1 another master without gitfs and it work perfectly well).
After upgrade to 2014.7.5, the memleak go faster on the master with gitfs, and it uses almost double RAM.
Notably, the process ``/usr/bin/python /usr/bin/salt-master _clear_old_jobs`` uses CPU extensively and use many RAM compares to all remain master processes:

````
root     27447  0.0  7.5  52060 38484 ?        Ss   03:56   0:03 /usr/bin/python /usr/bin/salt-master ProcessManager
root     27459 45.0 11.3  87280 57520 ?        R    03:56 108:25 /usr/bin/python /usr/bin/salt-master _clear_old_jobs
root     27460  0.0  3.7  45360 19136 ?        Sl   03:56   0:00 /usr/bin/python /usr/bin/salt-master Publisher
root     27461  0.0  3.6  44760 18628 ?        Sl   03:56   0:00 /usr/bin/python /usr/bin/salt-master EventPublisher
root     27526  0.7  7.3 155572 37544 ?        Sl   03:56   1:54 /usr/bin/python /usr/bin/salt-master Reactor
root     27527  0.0  6.5  52060 33076 ?        S    03:56   0:00 /usr/bin/python /usr/bin/salt-master ReqServer_ProcessManager
root     27529  1.6 10.1 147772 51800 ?        Sl   03:56   4:02 /usr/bin/python /usr/bin/salt-master MWorker
root     27532  1.7 10.1 146988 51332 ?        Sl   03:56   4:15 /usr/bin/python /usr/bin/salt-master MWorker
root     27535  0.0  6.9  78696 35228 ?        Sl   03:56   0:01 /usr/bin/python /usr/bin/salt-master MWorkerQueue
````

Graph of the one with gitfs, 18/May 12PM is ~ time we do upgrade

![master_gitfs](https://cloud.githubusercontent.com/assets/1000665/7698120/d641e9aa-fe37-11e4-8cec-1e2812571901.png)

And the one which does not use gitfs

![nogitfs](https://cloud.githubusercontent.com/assets/1000665/7698149/fbf95d68-fe37-11e4-87e8-8fa573f8c7f7.png)

````
[07:56:59] root@master:~ salt --versions-report
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Dec 18 2014, 19:03:52)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
````

**Comment by msteed** [comment] 2015-05-19 14:40
@hvnsweeting, thanks for the update. Could you post your `gitfs_provider`, and `gitfs_remotes` configs?

**Comment by hvnsweeting** [comment] 2015-05-19 15:17
@msteed  we don't use ``gitfs_provider``.

````
  gitfs_remotes:
    - git@git.DOMAIN.LTD:xxx/common.git
    - git@git.DOMAIN.LTD:yyy/states.git
````

it's path to our private repo on our private git server, nothing's special there. Anw, we also use pillar_ext:

````
ext_pillar:
  - git: branchX git@git.DOMAIN.LTD:xxx/blah.git
````

**Comment by msteed** [comment] 2015-05-19 21:42
@hvnsweeting - are there any recent errors in the salt-master log?

**Comment by hvnsweeting** [comment] 2015-05-20 02:38
No, there is no error log at all.

update:

In 2014.7.5, without gitfs, master not only use more memory but also leaks mem:

![nogitfs-20may](https://cloud.githubusercontent.com/assets/1000665/7717944/c8f834e2-fed3-11e4-9a13-14fe19c15a69.png)

and the one with gitfs is much more crazier

![saltgitfs](https://cloud.githubusercontent.com/assets/1000665/7717952/d5b04d8c-fed3-11e4-9168-c121a1e515fb.png)

**Comment by msteed** [comment] 2015-05-20 03:32
@hvnsweeting - since we are having trouble reproducing the problem here, would you be willing to collect some verbose logging from salt-master and make it available to us? You can do this manually by running 

```salt-master -ltrace -d```

as `root`, or you can set

```log_level_logfile: trace```

in `/etc/salt/master`. The log will grow quite large, but I think this will give us some insight into what is happening. Logging that covers a period when the salt-master memory usage is increasing rapidly will be most helpful.

**Comment by hvnsweeting** [comment] 2015-05-20 03:47
@msteed yes I will.
Btw, is that you are using RPM based OS? as I'm trying to switch the backend to pygit2 but it is not simple to install on Ubuntu 14.04.

This is version of GitPython I'm using: 
GitPython==0.3.2rc1 - installed from pip.

Could you give me your version? maybe something fixed in newer version.

**Comment by msteed** [comment] 2015-05-20 04:01
@hvnsweeting - I am testing on Arch Linux. I have GitPython 1.0.1 installed.

Note that pygit2 will work as a `gitfs_provider`, but for git `ext_pillar` only the GitPython provider is supported.

**Comment by hvnsweeting** [comment] 2015-05-20 04:08
@msteed thanks, I will upgrade it to see if it fix some leak issue.

Anw, it's clear that without gitfs, salt-master still leaks memory, should we open an issue for that? when as I see most of this issue is focus on gitfs relate.

**Comment by hvnsweeting** [comment] 2015-05-20 09:47
@msteed as I've upgraded to gitpython 1.0.1, I created this PR:

https://github.com/saltstack/salt/pull/23965

and by that I quite sure that you are trying to reproduce with  8 repos but all of them only have 1 same branch? as I hit the exception ASAP as I used 2 repos, each with severals or up to 20+ branches (some different in names in each repo). And back in the past (2014.1.10 with 0.3.2 gitpython), it seemed the more branches we have, the faster memleak is. I will observe to see if gitpython 1.0.1 fixed that.

**Comment by msteed** [comment] 2015-05-20 14:51
@hvnsweeting - yes, I have been testing with several repos but each with only one branch. I will try again with several branches.

**Comment by msteed** [comment] 2015-05-22 16:23
@hvnsweeting - using a repo with 10 branches I am still not able to reproduce the memory leak.

**Comment by hvnsweeting** [comment] 2015-05-22 17:28
let's me make it clear:

- as you see in the graph, one of my server which does not use gitfs still have small memleak, but the other with gitfs has much more leak than that.

- the other which use gitfs, configured 2 repos and 1 pillar git.
gitfs repo: one with  ~ 30 branches, the other with 8 branches, 1 branch has name == the former repo's branch.
- Pillar: 1 repo with  6 branches

And it not happen immediately, but you sure will see it in one day.

**Comment by hvnsweeting** [comment] 2015-05-25 06:34
update:

- without gitfs, master leak small portion of mem daily:

![master_nogitfs_0525](https://cloud.githubusercontent.com/assets/1000665/7792881/5443536c-02e2-11e5-8c17-77a90ee33ca2.png)

- with gitfs, after upgraded to gitpython 1.0.1 the master leaks with faster pace than 2014.1 with gitpython 0.3.2 but slower than 2014.1 with gitpython 1.0.1

![withgitfs_0525](https://cloud.githubusercontent.com/assets/1000665/7792900/89310af6-02e2-11e5-95ed-11ecf5962af2.png)

So conclude:

- gitpython 1.0.1 helps fix leak a bit
- salt-master 2014.7 leaks faster than 2014.1

**Comment by hvnsweeting** [comment] 2015-06-01 03:03
after switching gitfs backend to cgit, as in PR https://github.com/saltstack/salt/pull/24286
The memleak problem has gone, this is the graph:

![gitfscgit](https://cloud.githubusercontent.com/assets/1000665/7905591/4a3fdf6c-0845-11e5-9b96-efa141878533.png)

**Comment by WangWenchao** [comment] 2015-09-01 05:26
Today I met my salt-api (2014.7) has a memory leak 
```
[root@vm-base01 ~]# ps xua | grep salt
root     10157  0.0  0.0 285820 20364 ?        S    12:51   0:00 /usr/bin/python /usr/bin/salt-master -d
root     10158  3.4  0.1 351388 70312 ?        S    12:51   1:10 /usr/bin/python /usr/bin/salt-master -d
root     10159  0.0  0.0 371844 23988 ?        Sl   12:51   0:00 /usr/bin/python /usr/bin/salt-master -d
root     10162  0.0  0.0 371844 21712 ?        Sl   12:51   0:00 /usr/bin/python /usr/bin/salt-master -d
root     10165  0.0  0.0 285820 20148 ?        S    12:51   0:00 /usr/bin/python /usr/bin/salt-master -d
root     10166  0.4  0.0 734608 41788 ?        Sl   12:51   0:08 /usr/bin/python /usr/bin/salt-master -d
root     10167  0.4  0.0 734440 41536 ?        Sl   12:51   0:08 /usr/bin/python /usr/bin/salt-master -d
root     10168  0.3  0.0 735376 41572 ?        Sl   12:51   0:07 /usr/bin/python /usr/bin/salt-master -d
root     10169  0.4  0.0 735376 41724 ?        Sl   12:51   0:08 /usr/bin/python /usr/bin/salt-master -d
root     10170  0.3  0.0 738968 47212 ?        Sl   12:51   0:07 /usr/bin/python /usr/bin/salt-master -d
root     10171  0.0  0.0 674964 22780 ?        Sl   12:51   0:00 /usr/bin/python /usr/bin/salt-master -d
root     17794  0.0  0.0 286064 21296 ?        S    13:18   0:00 /usr/bin/python /usr/bin/salt-api -d
root     17795  2.0  0.1 19067192 102816 ?     Sl   13:18   0:07 /usr/bin/python /usr/bin/salt-api -d
root     17796  0.0  0.0 286064 21280 ?        S    13:18   0:00 /usr/bin/python /usr/bin/salt-api -d
root     19960  0.0  0.0 103244   852 pts/0    S+   13:25   0:00 grep salt

```
is there any fix

**Comment by frogunder** [comment] 2015-12-08 21:45
@hvnsweeting, @WangWenchao - Is this still an issue for you?

**Comment by hvnsweeting** [comment] 2015-12-09 04:50
@frogunder hi, we just gave up on saltfs , and using the traditional cron git pull and then all these problems gone, no more leak on my salt-master. (We are using 2014.7.5).
So I don't really know it's fixed or not.

**Comment by frogunder** [comment] 2015-12-16 16:18
@WangWenchao - Do you have any update on this on your end?

**Comment by WangWenchao** [comment] 2015-12-29 08:24
@frogunder , sorry . I have update the salt master to 2015.5

**Comment by frogunder** [comment] 2016-01-08 14:55
Since there has been no activity for a while, I will close this issue

**Closed by frogunder** 2016-01-08 14:55 UTC
Labels: Bug, Cannot Reproduce, Core, High Severity, Info Needed, P2
