### ISSUE TITLE
Issue with cron.file. Source: salt://path/to/crontab_file not found

### ISSUE THREAD

**Issue by fanirama** [saltstack/salt#38372] opened 2016-12-20 16:12 UTC
### Description of Issue/Question
Getting errors when running cron.file based state file in 2016.11.1
It was working without issue in 2016.3.4 
The file is present in the location specified -  base/crontab_root/files/crontab.root 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

    Install_root_cron:
      cron.file:
       - name: salt://crontab_root/files/crontab.root
       - template: jinja
       - user: root

### Steps to Reproduce Issue
   salt-call state.apply crontab_root

[ERROR   ] Source file salt://crontab_root/files/crontab.root not found
local:
----------
          ID: Install_root_cron
    Function: cron.file
        Name: salt://crontab_root/files/crontab.root
      Result: False
     Comment: Source file salt://crontab_root/files/crontab.root not found
     Started: 11:04:45.687077
    Duration: 15.336 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  15.336 ms

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment] 2016-12-21 18:33
@fanirama looks like i'm able to replicate it

looks like git bisect shows: 52fe72d402bf52b84e46b3ecc1c2a058a09fe40a and here is the PR: https://github.com/saltstack/salt/pull/37469

in file.py when it makes this call `source_sum = __salt__['cp.hash_file'](source, saltenv)` it  is returning empty and then theres logic to check if source_sum is not true and then spits out the error that the file is not availble.

Here is a docker container to replicate the issue:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38372` (where /home/ch3ll/git/salt is a lcoal cloned git repo of salt)
2. `salt-master -d; salt-minion -d`
3. `salt '*' state.apply test`


ping @terminalmage just to maek sure it looks like you changed some functionality in that `file.extract_hash` method. I'm not sure if we need to update docs to add some sort of argument to make sure the state is running correctly or if its a bug in the code and we need ot change the calls made from cron.file. Thanks

**Comment by terminalmage** [comment] 2016-12-21 20:05
Fixed in https://github.com/saltstack/salt/pull/38398

**Closed** 2017-01-01 20:45 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P3, State Module

**Comment by ericuldall** [comment] 2017-01-25 06:36
I'm running version 2016.11.1 from PPA and having this issue. What is the recommend LTS version for this?

**Comment by Ch3LL** [comment] 2017-01-25 16:11
@ericuldall this will be released in 2016.11.2 which we are currently working on releasing. We are in the QA Phase of this release.

**Comment by ericuldall** [comment] 2017-01-25 17:13
Wonderful. Do you have an ETA on that version?

**Comment by Ch3LL** [comment] 2017-01-25 17:17
If nothing is found during the QA Phase next week. :)

**Comment by ericuldall** [comment] 2017-01-25 17:41
Thank you. Do you know of any good way to work around the cron.file issue in the interim?

**Comment by dougreese** [comment] 2017-01-26 02:51
@ericuldall This worked for me: On the minion, add the line

```
            source_hash_name,
```

to call to `file.get_managed` as shown in the fix here: https://github.com/terminalmage/salt/blob/c80dbaa9142217e1eade946ec0af5922d90f15b6/salt/states/cron.py#L580

The line number was different in the file on my system, though.

**Comment by ericuldall** [comment] 2017-01-26 18:55
Yes, that did the trick. Thank you @dougreese!

**Comment by terminalmage** [comment] 2017-01-26 19:55
Yes, Debian and Ubuntu put packaged python modules into ``dist-packages`` instead of ``site-packages``.

**Comment by terminalmage** [comment] 2018-04-13 15:39
@skob I can't reproduce. Rather than continuing this conversation on an issue which has been closed for over a year, please open a new bug report and feel free to link back to this one. Please provide the SLS you used in the new report, and also please try running a `salt backend cp.list_master`. What I suspect happened is that you updated your `fileserver_backend` config option and you did not restart the `salt-master` daemon. Keep in mind that a `salt-run` spawns a new process, so its results are not indicative of what the `salt-master` daemon would see.
