### ISSUE TITLE
saltutil.sync_all runner function refreshes gitfs for each module type

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt#34984] opened 2016-07-27 14:26 UTC
With the new `saltutil.sync_all` function, gitfs remotes (and likely other types as well?) are refreshed before syncing every module type. Since there are 13 module types currently, this can take a fair amount of time. Expected behavior is that remotes are synced only once.

Version 2016.3.1.

**Comment by carlpett** [comment] 2016-07-27 14:26
Ping @terminalmage

**Comment by terminalmage** [comment] 2016-07-27 14:39
Thanks, I'll look into this!

**Comment by terminalmage** [comment] 2016-07-27 18:43
@carlpett As I thought when we discussed this in the other thread, this has been resolved already in the 2016.3 branch and the fix will be available in 2016.3.2.

As you can see in the below testing that I did, we now only fetch once and the total time has gone from 7.885 seconds to 1.808 seconds (for a gitfs repo that is already up-to-date on the master, and for which all of its files are already synced to the master).

```
# salt --version
salt 2016.3.1 (Boron)
# time salt-run -l debug saltutil.sync_all 2>&1 | grep 'Fetching gitfs remote' | wc -l
12
salt-run -l debug saltutil.sync_all 2>&1  1.48s user 0.53s system 25% cpu 7.885 total
grep 'Fetching gitfs remote'  0.01s user 0.00s system 0% cpu 7.885 total
wc -l  0.00s user 0.00s system 0% cpu 7.884 total
# salt --version
salt 2016.3.1-153-gd96386d (Boron)
# time salt-run -l debug saltutil.sync_all 2>&1 | grep 'Fetching gitfs remote' | wc -l
1
salt-run -l debug saltutil.sync_all 2>&1  0.75s user 0.21s system 52% cpu 1.808 total
grep 'Fetching gitfs remote'  0.01s user 0.01s system 1% cpu 1.807 total
wc -l  0.00s user 0.00s system 0% cpu 1.805 total
```

I'm going to go ahead and close this since the issue is resolved in the release branch. Thanks for bringing this up and forcing a sanity check on my part.

**Closed by terminalmage** 2016-07-27 18:43 UTC
Labels: 2016.3.2, Bug, Core, File Servers, P2, Runners, TEAM Core

**Comment by carlpett** [comment] 2016-07-27 18:59
Excellent, thank you very much!

**Comment by terminalmage** [comment] 2016-07-27 20:54
No problem!
