### ISSUE TITLE
file.replace not working correctly on newer minions

### ISSUE THREAD

**Issue by saltuser** [saltstack/salt#33118] opened 2016-05-09 12:25 UTC
file.replace doesn't work as expected on newer minions.

**Beginning**
```
salt '*' cmd.run 'cat /tmp/test.txt'

MINION1:
    FirstLine Here
    SecondLine Here
MINION2:
    FirstLine Here
    SecondLine Here
MINION3:
    FirstLine Here
    SecondLine Here
MINION4:
    FirstLine Here
    SecondLine Here
MINION5:
    FirstLine Here
    SecondLine Here
```

**Replace some text without [IGNORECASE]**
```
salt '*' file.replace /tmp/test.txt pattern='^.*FirstLine [Here|There].*$' repl='FirstLine There'
MINION5:
    ---
    +++
    @@ -1,2 +1,2 @@
    -FirstLine Here
    +FirstLine There
     SecondLine Here
MINION3:
    ---
    +++
    @@ -1,2 +1,2 @@
    -FirstLine Here
    +FirstLine There
     SecondLine Here
MINION1:
    ---
    +++
    @@ -1,2 +1,2 @@
    -FirstLine Here
    +FirstLine There
     SecondLine Here
MINION2:
    ---
    +++
    @@ -1,2 +1,2 @@
    -FirstLine Here
    +FirstLine There
     SecondLine Here
MINION4:
    ---
    +++
    @@ -1,2 +1,2 @@
    -FirstLine Here
    +FirstLine There
     SecondLine Here
```

```
salt '*' cmd.run 'cat /tmp/test.txt'
MINION5:
    FirstLine There
    SecondLine Here
MINION1:
    FirstLine There
    SecondLine Here
MINION2:
    FirstLine There
    SecondLine Here
MINION3:
    FirstLine There
    SecondLine Here
MINION4:
    FirstLine There
    SecondLine Here
```

**Replace some text with [IGNORECASE] Just trying revert previous change**
```
salt '*' file.replace /tmp/test.txt pattern='^.*FirstLine [Here|There].*$' repl='FirstLine Here' flags=[IGNORECASE]
MINION2:                        <- 2015.5.8
MINION1:                        <- 2015.5.3
    ---
    +++
    @@ -1,2 +1,2 @@    
    -FirstLine There
    +FirstLine Here
     SecondLine Here
MINION3:                        <- 2014.1.13
    ---
    +++
    @@ -1,2 +1,2 @@
    -FirstLine There
    +FirstLine Here
     SecondLine Here
MINION4:                        <- 2015.5.8
MINION5:                        <- 2015.8.8.2
```

```
salt '*' cmd.run 'cat /tmp/test.txt'
MINION2:
    FirstLine There
    SecondLine Here
MINION5:
    FirstLine There
    SecondLine Here
MINION3:
    FirstLine Here
    SecondLine Here
MINION1: 
    FirstLine Here
    SecondLine Here
MINION4:
    FirstLine There
    SecondLine Here
```

**Salt versions**
```
salt '*' test.versions_report
MINION3:
               Salt: 2014.1.13
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.11
              PyZMQ: 14.4.0
                ZMQ: 4.0.5

MINION2:
               Salt: 2015.5.8
             Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
             Jinja2: unknown
           M2Crypto: 0.20.2
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
           dateutil: Not Installed

MINION4:
               Salt: 2015.5.8
             Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.7
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
           dateutil: Not Installed

MINION1:
                      Salt: 2015.5.3
                    Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                    Jinja2: 2.6
                  M2Crypto: 0.21.1
            msgpack-python: 0.1.10
              msgpack-pure: Not Installed
                  pycrypto: 2.6
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 13.1.0
                      RAET: Not Installed
                       ZMQ: 3.2.3
                      Mako: 0.7.0
                   Tornado: Not Installed
     Debian source package: 2015.5.3+ds-1~bpo70+2

MINION5:
    Salt Version:
               Salt: 2015.8.8.2
    Dependency Versions:
             Jinja2: 2.5.5
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.08
              PyZMQ: 14.5.0
             Python: 2.6.8 (unknown, Aug 19 2015, 14:55:21)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.5
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
    System Versions:
               dist: redhat 5.11 Final
            machine: x86_64
            release: 2.6.18-409.el5
             system: CentOS 5.11 Final

MASTER:
salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo70+2
```

**Comment by lorengordon** [comment] 2016-05-09 20:51
I've worked on the `file.replace` module quite a bit; I'm betting when I [added multiline regex support](https://github.com/saltstack/salt/pull/28174), that probably introduced this behavior difference on newer versions...could you try passing both IGNORECASE and MULTILINE? 

I.e.:
```
salt '*' file.replace /tmp/test.txt pattern='^.*FirstLine [Here|There].*$' repl='FirstLine Here' flags=[IGNORECASE,MULTILINE]
```

**Comment by Ch3LL** [comment] 2016-05-09 23:29
@saltuser I was able to replicate this behavior with 2015.8.8.2: 

```
[ch3ll@ch3ll-master runners]$ cat /tmp/test.txt
FirstLine Here
SecondLine Here
```

If I do not use IGNORECASE it works:

```
[ch3ll@ch3ll-master runners]$ sudo salt 'ch3ll-mas*' file.replace /tmp/test.txt pattern='^.*FirstLine [Here|There].*$' repl='FirstLine Here' 
ch3ll-master:
    --- 
    +++ 
    @@ -1,2 +1,2 @@
    -    FirstLine Here
    +FirstLine Here
         SecondLine Here
```

If I use IGNORECASE it does not work:

```
[ch3ll@ch3ll-master runners]$ sudo salt 'ch3ll-mas*' file.replace /tmp/test.txt pattern='^.*FirstLine [Here|There].*$' repl='FirstLine Here' flags=[IGNORECASE]
ch3ll-master:
```

@lorengordon I went ahead and tested with multiline and this does appear to work:

```
[ch3ll@ch3ll-master runners]$ sudo salt 'ch3ll-mas*' file.replace /tmp/test.txt pattern='^.*FirstLine [Here|There].*$' repl='FirstLine Here' flags=[IGNORECASE,MULTILINE]
ch3ll-master:
    --- 
    +++ 
    @@ -1,2 +1,2 @@
    -    FirstLine There
    +FirstLine Here
         SecondLine Here
```

I confirmed this is also showing at the head of 2016.3.

Here is the git bisect:

```
5aea6647c9d360a9059472ea594f9fd0692c49f0 is the first bad commit
commit 5aea6647c9d360a9059472ea594f9fd0692c49f0
Author: Loren Gordon <loren@fleet-it.com>
Date:   Wed Oct 21 11:15:12 2015 -0400

    Add support for multiline regex in file.replace
    
    * use mmap to avoid reading the entire file into real memory
    * mmap treats the entire file as a single string
        * `re` functions work when using the multiline flag
        * `count` parameter works as expected
        * no need to read line-by-line; should be significantly faster
    
    Fixes #7999
    Fixes #8051

:040000 040000 026b19c1dcf538803fc0662ddaed4d03339f6413 84469bea5a3c3cc5b3f6fddf0986592011448236 M      salt
```

Looks like you were right, looks like the multiline addition caused this behavior.

**Comment by lorengordon** [comment] 2016-05-10 11:01
Ok, so, this could perhaps be considered more of a documentation issue than a bug, since the code is working as intended.

To support multiline search/replace, the entire file must be treated as a string. This was accomplished using `mmap` to help with the memory requirement of reading the entire file at once. The previous behavior was to read the file line-by-line.

Anchors such as `^` and `$` are relative to the string, not the line. When reading line-by-line, the string _is_ the line, so these can be conflated and it still works. When the entire file is the string, this no longer works. The `^` matches the beginning of the _file_ and `$` matches the end of the _file_. To get the desired behavior, you must pass the `MULTILINE` flag. This flag tells `re` to process line-ending characters in the string such that anchor patterns match on each line fragment.

To restore the line-by-line behavior of `file.replace`, the default for `flags` was set to `MULTILINE`. When the user passes in their own `flags` parameter, it overrides the default. So, if they override the default, do not set `MULTILINE`, *AND* use string anchors in the pattern, this is currently the expected result.

**Comment by saltuser** [comment] 2016-05-10 11:54
Explaining it this way actually makes sense. If this is indeed the expected result then updating documentation is enough. For example replacing `flags=8` with longer names like `flags=['IGNORECASE', 'MULTILINE']` would make the [file.replace doc](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.replace) easier to understand the default flags.
Perhaps add note about behaviour change to the docs as well?
Updating our SLS files to contain MULTILINE as well is relatively easy.

As said we are happy and this issue can be closed if docs get updated accordingly.
Thanks.

**Comment by lorengordon** [comment] 2016-05-10 12:23
@saltuser, @Ch3LL, how does this look?

```diff
diff --git a/salt/states/file.py b/salt/states/file.py
index 1f68210..1f238d1 100644
--- a/salt/states/file.py
+++ b/salt/states/file.py
@@ -2415,7 +2415,7 @@ def replace(name,
             pattern,
             repl,
             count=0,
-            flags=8,
+            flags=['MULTILINE'],
             bufsize=1,
             append_if_not_found=False,
             prepend_if_not_found=False,
@@ -2447,7 +2447,20 @@ def replace(name,
         correlate to the human-friendly flag name. E.g., ``['IGNORECASE',
         'MULTILINE']``. Optionally, ``flags`` may be an int, with a value
         corresponding to the XOR (``|``) of all the desired flags. Defaults to
-        8 (which supports 'MULTILINE').
+        ``['MULTILINE']``.
+
+        .. note::
+
+            ``file.replace`` reads the entire file as a string to support
+            multiline regex patterns. Therefore, when using anchors such as
+            ``^`` or ``$`` in the pattern, those anchors may be relative to
+            the line OR relative to the file. The default for ``file.replace``
+            is to treat anchors as relative to the line, which is implemented
+            by setting the default value of ``flags`` to ``['MULTILINE']``.
+            When overriding the default value for ``flags``, if
+            ``'MULTILINE'`` is not present then anchors will be relative to
+            the file. If the desired behavior is for anchors to be relative to
+            the line, then simply add ``'MULTILINE'`` to the list of flags.
```

**Comment by saltuser** [comment] 2016-05-10 12:34
@lorengordon, @Ch3LL, yes, a lot easier to understand. Thanks. Another issue resolved :)

**Comment by lorengordon** [comment] 2016-05-10 12:55
@saltuser, pylint is complaining about using a list as a default value like this. Do you think the explanation is clear enough without changing `flags=8` to `flags=['MULTILINE']`?

pylint's recommended fix would make the documentation even less clear...set the default to `flags=None`, then in the function body use `flags = flags or ['MULTILINE']`...

**Comment by saltuser** [comment] 2016-05-10 13:57
@lorengordon, I think it's fine.

**Comment by Ch3LL** [comment] 2016-05-12 22:16
@lorengordon agreed concerning it being a documentation issue if multiline in fact parses the entire file as a string. Thanks for the PR! I will wait for it to be merged before closing this issues :)

**Closed** 2016-05-13 21:39 UTC
Labels: Bug, Documentation, Execution Module, Fixed Pending Verification, Platform
