### ISSUE TITLE
digitalocean.py and private_networking

### ISSUE THREAD

**Issue by namcois** [saltstack/salt#19775] opened 2015-01-16 01:34 UTC
I'm currently running 2014.7.0 and private_networking is not working.
It looks like that digital ocean api v1 is only taking lower case for api call.
I've confirmed this by testing api call for private_networking option.

private_networking=true works but private_networking=True
I know v2 is being worked on, but I haven't moved to v2 yet and hoping if this can be corrected.

Thanks!

**Comment by rallytime** [comment] 2015-01-16 07:00
Hi @namcois - thanks for filing this issue. This is actually a duplicate of another bug report filed a couple of days ago. You can find that report here: #19306

I'm going to close this one in favor of the first ticket. We'll get it fixed up!

**Closed by rallytime** 2015-01-16 07:00 UTC
Labels: Bug, Duplicate, Medium Severity, Salt-Cloud
