### ISSUE TITLE
postgres return issue 

### ISSUE THREAD

**Issue by rajkamal31** [saltstack/salt#52316] opened 2019-03-25 22:06 UTC
salt 'minion1' disk.usage --return postgres just returns in json format. I followed https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.postgres_local_cache.html link to create postgres db on minion. When I looked at /var/log/salt/minion log file, it fails with the following error:

tailf /var/log/salt/minion                                                                                            ^
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1711, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/site-packages/salt/returners/postgres.py", line 239, in returner
    salt.utils.json.dumps(ret)))
ProgrammingError: relation "salt_returns" does not exist
LINE 1: INSERT INTO salt_returns

Salt version details on minion:

# salt-minion -V
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 3.12.74-60.64.40-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

salt version details on master:

 salt -V
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-95.6-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by rajkamal31** [comment] 2019-03-26 18:55
I tried to recreate the database and the tables, I am getting "Could not store return with postgres returner. PostgreSQL server unavailable." error now though the postgresql is running

**Comment by dmurphy18** [comment] 2019-03-26 19:23
@rajkamal31 This is fixed by PR https://github.com/saltstack/salt/pull/49133.

Can you try with that PR to ensure that it resolves your issue, and let me know of the result either way.

**Comment by dmurphy18** [comment] 2019-03-26 22:43
@rajkamal31 Thanks for trying, will dig into that one too then

**Comment by dmurphy18** [comment] 2019-03-27 00:05
With PR applied, seeing new similar failure when duplicating the original error, namely "PostgreSQL server unavailable"

**Comment by dmurphy18** [comment] 2021-06-17 17:16
@rajkamal31 Apologies for not checking sooner, but have the recent versions of Salt resolved this issue for you ?

**Comment by dmurphy18** [comment] 2022-01-14 00:36
@rajkamal31 I am closing this since the problem is Python 2.7 based which is End-Of-Lifed.  
If the problem is still occurring with the latest Salt 3004 which is Python 3, please open a new issue with the details, noting that the code paths will have changed somewhat with the move to Python 3.

**Closed by dmurphy18** 2022-01-14 00:36 UTC
Labels: Bug, severity-high, info-needed, Confirmed, Phosphorus v3005.0
