### ISSUE TITLE
Salt 2018.3.x breaks in an alpine container with msgpack 1.0.0

### ISSUE THREAD

**Issue by pcn** [saltstack/salt#56450] opened 2020-03-26 03:56 UTC
### Description of Issue
`msgpack` version `1.0.0` has been released, and it seems to break salt `2018.3.3` and later (haven't built with older versions, but I assume it'd be the same).

The error message when trying to run this command at the end of the saltstack/saltdocker:
```
RUN su - salt -c 'salt-run salt.cmd tls.create_self_signed_cert'
```
is this:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: __init__() got an unexpected keyword argument 'encoding'
Traceback (most recent call last):
  File "/usr/local/bin/salt-run", line 8, in <module>
    sys.exit(salt_run())
  File "/usr/local/lib/python3.7/site-packages/salt/scripts.py", line 422, in salt_run
    client.run()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/local/lib/python3.7/site-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/local/lib/python3.7/site-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/local/lib/python3.7/site-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/local/lib/python3.7/site-packages/salt/client/mixins.py", line 425, in _low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/local/lib/python3.7/site-packages/salt/utils/event.py", line 931, in fire_event
    self.event.fire_event(data, tagify(tag, base=self.base))
  File "/usr/local/lib/python3.7/site-packages/salt/utils/event.py", line 723, in fire_event
    if not self.connect_pull(timeout=timeout_s):
  File "/usr/local/lib/python3.7/site-packages/salt/utils/event.py", line 421, in connect_pull
    io_loop=self.io_loop
  File "/usr/local/lib/python3.7/site-packages/salt/transport/ipc.py", line 257, in __new__
    client.__singleton_init__(io_loop=io_loop, socket_path=socket_path)
  File "/usr/local/lib/python3.7/site-packages/salt/transport/ipc.py", line 280, in __singleton_init__
    self.unpacker = msgpack.Unpacker(encoding=encoding)
  File "msgpack/_unpacker.pyx", line 317, in msgpack._cmsgpack.Unpacker.__init__
TypeError: __init__() got an unexpected keyword argument 'encoding'
Traceback (most recent call last):
version = (1, 0, 0)
```
which looks like it's related to [this change in msgpack 1.0.0](https://pypi.org/project/msgpack/1.0.0/) for packer:
```
encoding option is removed. UTF-8 is used always.
```
and unpacker:
```
encoding option is removed. You can use raw=True to support old format.
```
### Setup
https://github.com/saltstack/saltdocker/blob/master/Dockerfile.j2

### Steps to Reproduce Issue
https://github.com/saltstack/saltdocker/blob/master/Dockerfile.j2

### Versions Report
```
/ # salt --versions-report
/usr/local/lib/python3.7/site-packages/salt/version.py:632: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  lin_ver = linux_distribution()
Salt Version:
           Salt: 2018.3.5
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.7 (default, Mar 24 2020, 03:07:37)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 5.3.0-42-generic
         system: Linux
        version: Not Installed
```

This would probably be fixed by changing https://github.com/saltstack/salt/blob/5b7b9aadb8f86310e6a5ae19cb394375231415ed/requirements/base.txt#L4 from 
```
msgpack>=0.5,!=0.5.5
```

to something like 
```
msgpack>=0.5,!=0.5.5,<1.0.0
```
for now.

**Comment by Ch3LL** [comment] 2020-03-26 14:23
Duplicate of https://github.com/saltstack/salt/issues/56007

**Closed by Ch3LL** 2020-03-26 14:23 UTC

**Comment by Ch3LL** [comment] 2020-03-26 14:25
also to note in the salt 3000 version we did pin msgpack version for now until that issue is resolved.
