### ISSUE TITLE
Salt CLI blocking for 1s

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#20950] opened 2015-02-23 22:46 UTC
``
mp@silver ~ % time sudo salt silver test.ping
silver:
    True
sudo LD_LIBRARY_PATH=/usr/local/lib salt silver test.ping  0.24s user 0.02s system 20% cpu 1.278 total
``

This is being caused by 1s wait on get_event(). I have pinged @jacksontj directly on the commit in question to ask about the history behind this change.

**Comment by jacksontj** [comment] 2015-02-24 05:40
@cachedout this was put in a while ago (Jan 10th #4ad53c). This is because ZMQ has no guarantees about when the socket is actually connected to peers. This means that although __init__ has finished the underlying socket is not gauranteed to be connected-- which is problematic for async-event stuff in the core.

THe reason this isn't on develop is that you reverted it in #9bfe83b. Although I agree this is a terrible timeout to have, zmq doesn't really give us any other options. If we want we could go add a kwarg to the __init__ which would trigger that behavior then track down all places in the code that require that it is connected after __init__ (from my looking in the code at the time everyone makes that assumption-- which IMO is reasonable).

**Comment by cachedout** [comment] 2015-02-27 21:33
@jacksontj Yes, I agree that we should have had this conversation before reverting. I apologize for that. 

Yes, I agree with your proposal about specifying a kwarg. That seems like the best comprimise. I'll cc: @thatch45 as well here.

**Comment by cachedout** [comment] 2015-03-10 23:06
@jacksontj I did some digging around here and found this thread where Pieter suggests that the behaviour of ``zmq_connect`` is synchronous on ``inproc`` endpoints: http://grokbase.com/t/zeromq/zeromq-dev/1343mv38cr/inproc%EF%BC%9A-message-dropped-after-zmq-dealer-connected

If that's the case, perhaps we could limit the use of the 1s poll on TCP sockets? That might get us around the LocalClient issue, at least.

**Comment by jacksontj** [comment] 2015-03-11 04:14
That doesn't help us since we are using ipc not inproc (https://github.com/saltstack/salt/blob/2015.2/salt/utils/event.py#L204). And we can't switch to inproc since this is across processes. After I finish up my work on transport stuff I plan on doing cleanup of all the IPC stuff, but as of right now zmq give us *no* mechanism to work around this issue... Although I guess we could fire a bunch of fake events to hopefully catch the connect sooner-- but there is no clean way to do it in zmq.

**Comment by cachedout** [comment] 2015-03-11 17:11
Yes, you are right. (Not sure what I was thinking there!) I looked around a bit today in the ZMQ source and did see that it looks as though changes in socket state are pushed across the monitor socket interface. Though monitor sockets are obviously a new addition in ZMQ, I'm going to play around a bit and see if it might be possible to setup a monitor socket and wait for it to report back that it is connected. Totally unsure if this is a workable solution for the problem at hand, but figured I'd explore a bit and see if it turns out to be viable. Thoughts?

**Comment by cachedout** [comment] 2015-03-11 18:24
Hi again @jacksontj 

So far this is a good news/bad news situation. The bad news is that monitor sockets won't work for this sort of application. (Not in any way surprising, but it was a fun experiment.) The good news is that it appears that the sub socket connect is happening fast enough that the monitor socket setup isn't fast enough to catch it. In reading the ZeroMQ source, it appears that it *should* pass an event to the monitor socket if it "connects" asyncrhronously and then another upon actual physical connection. The monitor socket establishment isn't fast enough to catch either of those.

So, this leads me to believe that while there is certainly a non-zero chance of late-joiner syndrome here, the IPC physical socket establishment is happening very fast and the liklihood of it being delayed enough that it misses returns coming back is not high.

Have you seen evidence that the time it takes to establish the sub socket to the event bus is slow enough that returns get dropped? Or is this just a defensive approach against the possibility that they could be? After playing with this a bit, I think I'm fine going in either direction but would definietely still like to prevent the (up to) 1s CLI delay if possible.

Thoughts?

**Comment by jacksontj** [comment] 2015-03-11 21:17
This was introduced specifically because we saw quite a few races in the setup of the IPC socket. This is primarily prevalent for things that return quickly-- since the race is easier to hit.

The easiest one to reproduce it so create a runner which simply returns "true" and remove this get_event-- and your CLI will stall for *timeout* since it will have missed the event.

That isn't the *only* way to reproduce, but it is the easiest ;)

The other way i was thinking was something like what i have in #21570. That does come with the downside of firing an event on the bus everytime you want a client... but it does work around the case where the event bus is quiet.

**Comment by thatch45** [comment] 2015-03-11 21:29
Bah, @jacksontj has produced a reasonable scenario. I will go for this with #21570, but I think that the event we fire should at least TRY to be useful. The event needs a namespaced tag, say "/salt/event/new_client" so that it is not one of the events we are trying to get rid of.

**Comment by cachedout** [comment] 2015-03-11 21:32
I think this is a reasonable workaround as well. Thanks for the discussion and insight @jacksontj

**Comment by jacksontj** [comment] 2015-03-11 22:05
@thatch45 I just committed the correctly namespaced version-- so that should help. Soon we can hopefully drop zmq for ipc ;)

**Closed** 2015-03-16 17:11 UTC
Labels: Blocker, Bug, High Severity
