### ISSUE TITLE
Unable to manage file: 'module' object has no attribute 'path' on suse

### ISSUE THREAD

**Issue by houtuo** [saltstack/salt#56090] opened 2020-02-07 12:49 UTC
### Description of Issue
I'm going to execute a salt state.
The first execution fails, and the second succeeds without any changes.
Report the following error:
salt07.suse:
----------
          ID: weblogic-noproc.conf
    Function: file.managed
        Name: /etc/security/limits.conf
      Result: False
     Comment: Unable to manage file: 'module' object has no attribute 'path'
     Started: 02:56:58.607345
    Duration: 27.992 ms
     Changes:   

Summary for salt07.suse
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  27.992 ms

### Setup

```
weblogic-noproc.conf:
  file.managed:
    - source:
      - salt://{{ pillar['template_suse_system_dir'] }}/weblogic-noproc.conf
    - name: /etc/security/limits.conf
    - user: root
    - group: root
    - mode: 644
    - backup: minion
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

salt06:/etc/security # salt-minion --version
salt-minion 2016.11.4 (Carbon)

**Comment by dhiltonp** [comment] 2020-02-14 15:07
Thanks!

Could you look for a related stack trace in the salt minion logs?

Something like: `grep -B1 -A10 Traceback /var/log/salt/salt_minion` on the affected minion.

**Comment by houtuo** [comment] 2020-02-15 06:17
Thanks for your reply!
Mail attachment is my minion logs.
houtuo_job@163.com
 
From: David Hilton
Date: 2020-02-14 23:07
To: saltstack/salt
CC: houtuo; Author
Subject: Re: [saltstack/salt] Unable to manage file: 'module' object has no attribute 'path' on suse (#56090)
Thanks!
Could you look for a related stack trace in the salt minion logs?
Something like: grep -B1 -A10 Traceback /var/log/salt/salt_minion on the affected minion.

**Comment by waynew** [comment] 2020-03-10 20:27
Hi @houtuo it looks like you've gotten something broken in your environment. The path says `python2.6` which hasn't been supported in some time. Not exactly sure what's happened, but at least at first glance this doesn't appear to be an issue with Salt. Also, your title says SUSE but your version report says `centos 7.4.1708 Core`.

I'm going to go ahead and close this for now, but if you can produce a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) we can definitely re-open it. HTH!

**Closed by waynew** 2020-03-10 20:27 UTC
Labels: Info Needed
