### ISSUE TITLE
salt pkg.upgrade reports new packages despite installing none (zypper module)

### ISSUE THREAD

**Issue by miukumac** [saltstack/salt#48701] opened 2018-07-22 04:54 UTC
### Description of Issue/Question
When issuing pkg.upgrade on any openSUSE or Enterprise Server, certain packages cause false reports of upgrading packages although nothing is actually installed. Such packages are always multiversion files such as kernel, crash-kmp and gpg-pubkey packages which many may be installed at the same time as well as custom packages that may have multiple versions such as nVidia or driver rpms.

Example:

```
zabbix:~ # salt '<sles12sp3host>' pkg.upgrade
sles12sp3host:
    ----------
    crash-kmp-default:
        ----------
        new:
            7.1.8_k4.4.92_6.30-4.6.2
        old:
            7.1.8_k4.4.131_94.29-4.8.1,7.1.8_k4.4.92_6.30-4.6.2
    gpg-pubkey:
        ----------
        new:
            edf0d733-54930778
        old:
            39db7c82-5847eb1f,50a3dd1c-50f35137,bf9a56ad-5758109f,e4e37c43-584f065d,e9e45fb5-57d42e04,edf0d733-54930778
    kernel-default:
        ----------
        new:
            4.4.138-94.39.1
        old:
            4.4.120-94.17.1,4.4.126-94.22.1,4.4.131-94.29.1,4.4.132-94.33.1,4.4.138-94.39.1
```

No new packages were installed, only reported as being "new" despite having already been installed on a previous run.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
No special configuration is required - even out of the box configuration produces the same issue.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Simply running salt 'host' pkg.upgrade reproduces the issue on all distribution versions that we currently use (SLE12SP3, SLE15)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.1
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1
 
System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.132-94.33-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
```

**Comment by Ch3LL** [comment] 2018-07-23 15:11
ping @saltstack/team-suse any ideas here?

**Comment by miukumac** [comment] 2018-07-23 15:14
Additional note; I upgraded our infrastructure to 2018.3.2 (Oxygen) and the same issue persists on this version as well.

**Comment by meaksh** [comment] 2018-07-23 15:40
@miukumac - Thanks for reporting this. The issue is fixed on https://github.com/saltstack/salt/pull/48712

**Comment by miukumac** [comment] 2018-07-23 15:43
That was damn fast. Great work 👍

**Comment by isbm** [comment] 2018-07-23 16:50
@miukumac OK, next time we will slow down for you. :laughing:

**Closed** 2018-08-02 19:33 UTC
Labels: Bug, Execution Module, Fixed Pending Verification, High Severity, P3
