### ISSUE TITLE
pip.installed fails after upgrading minion to 2014.7.1

### ISSUE THREAD

**Issue by bercab** [saltstack/salt#20191] opened 2015-01-29 13:43 UTC
State pip.installed worked fine with version 2014.7.0, but fails after upgrading 2014.7.1

An example failing: 

state:
```yaml
{{appname}}-pip:
    pip.installed:
        - name: pip==1.4.1
        - bin_env: {{virtualenv}}
        - user: {{username}}
        - activate: true
        - require:
            - virtualenv: {{appname}}-virtualenv
```
output:
```
    [INFO    ] Executing state pip.installed for pip==1.4.1
[DEBUG   ] Installed pip version is lower than 1.2
[INFO    ] Executing command '/opt/scf_engine/.virtualenvs/scf_engine/bin/pip --version' as user 'scf_engine' in directory '/opt/scf_engine'
[DEBUG   ] stdout: pip 6.0.7 from /opt/scf_engine/.virtualenvs/scf_engine/local/lib/python2.7/site-packages (python 2.7)
[INFO    ] Executing command '/opt/scf_engine/.virtualenvs/scf_engine/bin/pip freeze' as user 'scf_engine' in directory '/opt/scf_engine'
[INFO    ] Executing command ". /opt/scf_engine/.virtualenvs/scf_engine/bin/activate && /opt/scf_engine/.virtualenvs/scf_engine/bin/pip install 'pip==1.4.1'" as user 'scf_engine' in directory '/opt/scf_engine'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1529, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 552, in installed
    saltenv=__env__
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 560, in install
    return __salt__['cmd.run_all'](' '.join(cmd), python_shell=False, **cmd_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 877, in run_all
    use_vt=use_vt)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 371, in _run
    .format(cmd, kwargs, exc)
CommandExecutionError: Unable to run command ['.', '/opt/scf_engine/.virtualenvs/scf_engine/bin/activate', '&&', '/opt/scf_engine/.virtualenvs/scf_engine/bin/pip', 'install', 'pip==1.4.1'] with the context {'with_communicate': True, 'shell': False, 'env': {'HISTTIMEFORMAT': '%F %T ', 'LOGNAME': 'scf_engine', 'USER': 'scf_engine', 'HOME': '/opt/scf_engine', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games', 'DISPLAY': 'localhost:10.0', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'LANGUAGE': 'en_US:en', u'SHLVL': '1', 'SUDO_USER': 'bercab', 'USERNAME': 'root', 'SUDO_UID': '2021', 'VIRTUAL_ENV': '/opt/scf_engine/.virtualenvs/scf_engine', 'LC_ALL': 'C', u'_': '/usr/bin/python', 'SUDO_COMMAND': '/usr/bin/salt-call state.highstate -l debug', 'SUDO_GID': '2021', u'PWD': '/opt/scf_engine', 'MAIL': '/var/mail/scf_engine', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -1, 'cwd': '/opt/scf_engine', 'preexec_fn': <functools.partial object at 0x3f29680>}, reason: [Errno 13] Permission denied

```

**Comment by bercab** [comment] 2015-01-29 13:56
The same state working OK with version 2014.7.0:

```
[INFO    ] Executing state pip.installed for pip==1.4.1
.bashrc: line 5: workon: command not found
[INFO    ] Executing command '/opt/scf_engine/.virtualenvs/scf_engine/bin/pip --version' as user 'scf_engine' in directory '/opt/scf_engine'
[INFO    ] stdout: pip 6.0.6 from /opt/scf_engine/.virtualenvs/scf_engine/local/lib/python2.7/site-packages (python 2.7)
.bashrc: line 5: workon: command not found
[INFO    ] Executing command '/opt/scf_engine/.virtualenvs/scf_engine/bin/pip freeze' as user 'scf_engine' in directory '/opt/scf_engine'
[INFO    ] stderr: You are using pip version 6.0.6, however version 6.0.7 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
.bashrc: line 5: workon: command not found
[INFO    ] Executing command ". /opt/scf_engine/.virtualenvs/scf_engine/bin/activate && /opt/scf_engine/.virtualenvs/scf_engine/bin/pip install 'pip==1.4.1'" as user 'scf_engine' in directory '/opt/scf_engine'
[INFO    ] stdout: You are using pip version 6.0.6, however version 6.0.7 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip==1.4.1
  Using cached pip-1.4.1.tar.gz
Installing collected packages: pip
  Found existing installation: pip 6.0.6
    Uninstalling pip-6.0.6:
      Successfully uninstalled pip-6.0.6
  Running setup.py install for pip
    Installing pip script to /opt/scf_engine/.virtualenvs/scf_engine/bin
    Installing pip-2.7 script to /opt/scf_engine/.virtualenvs/scf_engine/bin
Successfully installed pip-1.4.1
.bashrc: line 5: workon: command not found
[INFO    ] Executing command '/opt/scf_engine/.virtualenvs/scf_engine/bin/pip --version' as user 'scf_engine' in directory '/opt/scf_engine'
[INFO    ] stdout: pip 1.4.1 from /opt/scf_engine/.virtualenvs/scf_engine/lib/python2.7/site-packages (python 2.7)
.bashrc: line 5: workon: command not found
[INFO    ] Executing command '/opt/scf_engine/.virtualenvs/scf_engine/bin/pip freeze' as user 'scf_engine' in directory '/opt/scf_engine'
[INFO    ] stdout: argparse==1.2.1
wsgiref==0.1.2
[INFO    ] {'pip==1.4.1': 'Installed'}
[INFO    ] Completed state [pip==1.4.1] at time 13:47:21.499630

```

**Comment by rallytime** [comment] 2015-01-29 17:25
Thanks! We'll get this regression fixed right up.

**Comment by jfindlay** [comment] 2015-01-30 22:02
@bercab, I have a fix for this in the referenced branch, but I would like to test it before submitting a pull request.  I should have that done sometime today.

**Comment by bercab** [comment] 2015-01-31 08:58
@rallytime @jfindlay Thanks so much!! :))

**Comment by jfindlay** [comment] 2015-02-03 23:54
@bercab, this went a little deeper than I was expecting, but I should have the pull request in soon since we're supposed to tag 2014.7.2 by the end of the week.

**Closed** 2015-02-06 23:59 UTC
Labels: Blocker, Bug, Fixed Pending Verification, in progress, Regression
