### ISSUE TITLE
Mount state failed after upgrade

### ISSUE THREAD

**Issue by nirnx** [saltstack/salt#21215] opened 2015-03-02 10:07 UTC
Hello 
I recently updated salt from salt-2014.7.0-3 to salt-2014.7.1-1 after that mount state is failed to finish

Centos 6.5 OpenVZ container 

State: 
```
mount_/vol:
    mount.mounted:
        - device: x.x.x.x:/vol/
        - fstype: nfs
        - mkmnt: True
        - name: /mnt/vol
        - opts:
            - ro,nosuid,noatime,nolock,nointr,timeo=14,nfsvers=3,rsize=8192,wsize=8192,auto,soft,nocto,acregmin=5,acregmax=60,acdirmin=60,acdirmax=90,tcp
```
```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1529, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 41, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1529, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/mount.py", line 201, in mounted
                  if opt not in active[real_name]['opts'] and opt not in active[real_name]['superopts'] and opt not in mount_invisible_options:
              KeyError: 'superopts'
```
Can someone help ?:)

Best Regards

**Comment by rallytime** [comment] 2015-03-02 19:21
@nirnx Thanks for this report. I know there were several fixes (and some regressions, too) to the mount states in the 2014.7 branch in general. My first suggestion would be to upgrade to the latest bugfix release, 2014.7.2, and see if that fixes your specific issue, as I think this one may have been fixed. 

Give that a try and if you're still seeing problems, let us know here and we can take another look!

**Comment by RobertFach** [comment] 2015-03-02 21:19
@nirnx Hi, can you run the following command on the corresponding minion and check if the superopts item is part of your device?
`salt-call mount.active extended=True`

Btw. the mount state change detection is not working correctly when you specify all options in one list elements, you would have to change it to look like below or, write each element as list item.
```
mount_/vol:
    mount.mounted:
        - device: x.x.x.x:/vol/
        - fstype: nfs
        - mkmnt: True
        - name: /mnt/vol
        - opts:  ro,nosuid,noatime,nolock,nointr,timeo=14,nfsvers=3,rsize=8192,wsize=8192,auto,soft,nocto,acregmin=5,acregmax=60,acdirmin=60,acdirmax=90,tcp
```

**Comment by RobertFach** [comment] 2015-03-02 23:00
@rallytime I think this is not yet fixed. I had a look at the code and it looks that the current mount state implementation should fail under some circumstances on freebsd, solaris and it looks as it also fails on CentOS.

**Comment by nirnx** [comment] 2015-03-03 08:27
Hello
as you requested

``salt-call mount.active extended=True``
```
local:
    ----------
    /:
        ----------
        alt_device:
            /dev/simfs
        device:
            /dev/simfs
        fstype:
            simfs
        opts:
            - rw
            - relatime
    /dev:
        ----------
        alt_device:
            none
        device:
            none
        fstype:
            devtmpfs
        opts:
            - rw
            - relatime
            - mode=755
    /dev/pts:
        ----------
        alt_device:
            none
        device:
            none
        fstype:
            devpts
        opts:
            - rw
            - relatime
            - mode=600
            - ptmxmode=000
    /dev/shm:
        ----------
        alt_device:
            none
        device:
            none
        fstype:
            tmpfs
        opts:
            - rw
            - relatime
    /proc:
        ----------
        alt_device:
            proc
        device:
            proc
        fstype:
            proc
        opts:
            - rw
            - relatime
    /proc/sys/fs/binfmt_misc:
        ----------
        alt_device:
            none
        device:
            none
        fstype:
            binfmt_misc
        opts:
            - rw
            - relatime
    /sys:
        ----------
        alt_device:
            sysfs
        device:
            sysfs
        fstype:
            sysfs
        opts:
            - rw
            - relatime
    /var/lib/nfs/rpc_pipefs:
        ----------
        alt_device:
            sunrpc
        device:
            sunrpc
        fstype:
            rpc_pipefs
        opts:
            - rw
            - relatime
    /var/lib/varnish:
        ----------
        alt_device:
            none
        device:
            none
        fstype:
            tmpfs
        opts:
            - rw
            - relatime
    /vol/1:
        ----------
        alt_device:
            x.x.x.x:/vol/1
        device:
            x.x.x.x:/vol/1
        fstype:
            nfs
        opts:
            - ro
            - nosuid
            - noatime
            - vers=3
            - rsize=8192
            - wsize=8192
            - namlen=255
            - acregmin=5
            - acdirmin=60
            - acdirmax=90
            - soft
            - nocto
            - nolock
            - proto=tcp
            - timeo=14
            - retrans=2
            - sec=sys
            - mountaddr=x.x.x.x
            - mountvers=3
            - mountport=4046
            - mountproto=tcp
            - local_lock=all
            - addr=x.x.x.x
    /vol/2:
        ----------
        alt_device:
            x.x.x.x:/vol/2
        device:
            x.x.x.x:/vol/2
        fstype:
            nfs
        opts:
            - ro
            - relatime
            - vers=3
            - rsize=65536
            - wsize=65536
            - namlen=255
            - hard
            - nocto
            - proto=tcp
            - timeo=600
            - retrans=2
            - sec=sys
            - mountaddr=x.x.x.x
            - mountvers=3
            - mountport=4046
            - mountproto=udp
            - local_lock=none
            - addr=x.x.x.x
    /vol/3:
        ----------
        alt_device:
            x.x.x.x:/vol/3
        device:
            x.x.x.x:/vol/3
        fstype:
            nfs
        opts:
            - ro
            - nosuid
            - noatime
            - vers=3
            - rsize=8192
            - wsize=8192
            - namlen=255
            - acregmin=5
            - acdirmin=60
            - acdirmax=90
            - soft
            - nocto
            - nolock
            - proto=tcp
            - timeo=14
            - retrans=2
            - sec=sys
            - mountaddr=x.x.x.x
            - mountvers=3
            - mountport=4046
            - mountproto=tcp
            - local_lock=all
            - addr=x.x.x.x
```



```
/proc/self/mountinfo:
60 22 0:40 /vz/private/1 / rw,relatime - simfs /vz/private/1 rw
79 60 0:54 / /proc rw,relatime - proc proc rw
80 79 0:57 / /proc/sys/fs/binfmt_misc rw,relatime - binfmt_misc none rw
81 60 0:42 / /sys rw,relatime - sysfs sysfs rw
82 60 0:41 / /dev rw,relatime - devtmpfs none rw,mode=755
83 82 0:56 / /dev/pts rw,relatime - devpts none rw,mode=600,ptmxmode=000
84 82 0:58 / /dev/shm rw,relatime - tmpfs none rw
85 60 0:59 / /var/lib/varnish rw,relatime - tmpfs none rw
86 60 0:60 / /var/lib/nfs/rpc_pipefs rw,relatime - rpc_pipefs sunrpc rw
94 60 0:66 / /vol/1 ro,nosuid,noatime - nfs x.x.x.x:/vol/1 ro,vers=3,rsize=8192,wsize=8192,namlen=255,acregmin=5,acdirmin=60,acdirmax=90,soft,nocto,nolock,proto=tcp,timeo=14,retrans=2,sec=sys,mountaddr=x.x.x.x,mountvers=3,mountport=4046,mountproto=tcp,local_lock=all,addr=x.x.x.x
93 60 0:65 / /vol/2 ro,nosuid,noatime - nfs x.x.x.x:/vol/2 ro,vers=3,rsize=8192,wsize=8192,namlen=255,acregmin=5,acdirmin=60,acdirmax=90,soft,nocto,nolock,proto=tcp,timeo=14,retrans=2,sec=sys,mountaddr=x.x.x.x,mountvers=3,mountport=4046,mountproto=tcp,local_lock=all,addr=x.x.x.x
95 60 0:67 / /vol/3 ro,relatime - nfs x.x.x.x:/vol/3 ro,vers=3,rsize=65536,wsize=65536,namlen=255,hard,nocto,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=x.x.x.x,mountvers=3,mountport=4046,mountproto=udp,local_lock=none,addr=x.x.x.x
```

**Comment by RobertFach** [comment] 2015-03-03 15:22
@nirnx Thx for your response. Your output shows clearly that if `salt-call mount.active extended=True`doesn't output the superopts keyvals, then the mount state will fail. The question is why the superopts are not added because the file `/proc/self/mountinfo` exists...
Is the file `/proc/self/mountinfo` accessible by the user who is running salt? On my CentOS it is only accessible by root which would be fine if one doesn't change the user.

**Comment by nirnx** [comment] 2015-03-03 15:46
Hello thanks for reply and I did some research and:
Xen: 
```
Linux xxx 2.6.32-279.19.1.el6.x86_64 #1 SMP Wed Dec 19 07:05:20 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

salt-2014.7.1-1.el6.noarch
```
strace shows:
```
open("/proc/self/mountinfo", O_RDONLY)  = 11
```
OpenVZ:

```
Linux xxx 2.6.32-042stab075.2 #1 SMP Fri Dec 19 20:34:40 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux

salt-2014.7.1-1.el6.noarch
```
strace shows
```
open("/proc/self/mounts", O_RDONLY)     = 11
```

maybe the problem is somewhere else ? system detect ?

**Comment by RobertFach** [comment] 2015-03-03 16:41
@nirnx : I have to try that in an OpenVZ Container, I'm not yet sure why that fails in OpenVZ. I tested it in CentOS 6.5 which was not causing an issue.

Anyway, I have attached a fix for the actual root problem, namly that the mount state doesn't check if superopts are existing or not.

**Comment by nirnx** [comment] 2015-03-04 15:12
Thanks Robert for help fix is working great !:)

**Comment by rallytime** [comment] 2015-03-04 15:38
Thanks very much for the fix @RobertFach. I've just now merged your pull request. @nirnx It looks like you've tested the change, and since it is working for you I am going to close this issue. If this pops up again for you, please leave a comment and we will be happy to re-open this.

**Closed by rallytime** 2015-03-04 15:38 UTC
Labels: Bug, Fixed Pending Verification, Medium Severity, Regression

**Comment by RobertFach** [comment] 2015-03-04 15:50
@nirnx no problem, thx for the feedback ...
