### ISSUE TITLE
git.latest seems to be doing something wrong

### ISSUE THREAD

**Issue by froztbyte** [saltstack/salt#23845] opened 2015-05-18 09:08 UTC
So I don't quite understand where this is going wrong yet, but I'll provide all the details I have. I have the following state:

```
ensure we have a rancid user:
  user.present:
    - name: rancid
    - group: rancid

install rancid dependencies:
  pkg.installed:
    - pkgs:
      - git
      - perl5
      - expect
      - tcl
      - diffutils
      - cvs
      - tcl

create the rancid checkout directory:
  file.directory:
    - name: /srv/rancid-git
    - owner: rancid
    - group: rancid
    - require:
      - user: rancid

fetch dotwaffle rancid-git:
  git.latest:
    - name: https://github.com/dotwaffle/rancid-git.git
    - target: /srv/rancid-git
    - rev: 06dc499279db3346607dee07f4fc8f56c979f013
    - user: rancid
    - require:
      - pkg: install rancid dependencies
      - user: rancid
```

Running it as-is results in the following:
```
          ID: fetch dotwaffle rancid-git
    Function: git.latest
        Name: https://github.com/dotwaffle/rancid-git.git
      Result: False
     Comment: Command "git clone https://github.com/dotwaffle/rancid-git.git '/srv/rancid-git' " failed. Stderr: "fatal: I don't handle protocol '/home/rancid/https'"
     Started: 11:03:56.555587
    Duration: 21.176 ms
     Changes:
```

However, when I run this manually as follows, it does appear to work.
```
root@rancid:/srv# su -c "git clone https://github.com/dotwaffle/rancid-git.git '/srv/rancid-git'" rancid
Cloning into '/srv/rancid-git'...
remote: Counting objects: 3544, done.
remote: Total 3544 (delta 0), reused 0 (delta 0), pack-reused 3544
Receiving objects: 100% (3544/3544), 3.08 MiB | 714 KiB/s, done.
Resolving deltas: 100% (2485/2485), done.
root@rancid:/srv# (cd rancid-git; git log | head -n 1)
commit 06dc499279db3346607dee07f4fc8f56c979f013
```

I'd guess that maybe the actual command that's run is different from the command that's indicated (which is the only way I could see the protocol changing), but I'm not sure why yet.

**Comment by froztbyte** [comment] 2015-05-18 09:26
If I do a checkout by hand, the rest of the state appears to work correctly:
```
rancid@rancid:/srv/rancid-git$ git reset d5a129204fed11c4131d8878e862e013bb6f7598
Unstaged changes after reset:
M	bin/fnrancid.in
M	configure
M	debian/changelog
rancid@rancid:/srv/rancid-git$ rm bin/fnrancid.in configure debian/changelog
rancid@rancid:/srv/rancid-git$
```

```
          ID: fetch dotwaffle rancid-git
    Function: git.latest
        Name: https://github.com/dotwaffle/rancid-git.git
      Result: True
     Comment: Repository /srv/rancid-git updated
     Started: 11:26:11.387516
    Duration: 131.497 ms
     Changes:
              ----------
              revision:
                  d5a129204fed11c4131d8878e862e013bb6f7598 => 06dc499279db3346607dee07f4fc8f56c979f013
```

**Comment by froztbyte** [comment] 2015-05-18 09:40
Hmm, I just found that the rancid user's home directory appears to have had some checkout-y bits as well (possibly from a former run when I was still figuring out my SLS structure). When I nuked this, the rest worked fine:

```
rancid@rancid:~$ pwd
/home/rancid
rancid@rancid:~$ ls
https:
rancid@rancid:~$ rm -rf https\:/```

->
```
          ID: fetch dotwaffle rancid-git
    Function: git.latest
        Name: https://github.com/dotwaffle/rancid-git.git
      Result: True
     Comment: Repository https://github.com/dotwaffle/rancid-git.git cloned to /srv/rancid-git
     Started: 11:38:14.418080
    Duration: 7692.387 ms
     Changes:
              ----------
              new:
                  https://github.com/dotwaffle/rancid-git.git
              revision:
                  06dc499279db3346607dee07f4fc8f56c979f013```

The error message didn't really give me a good indication about this as the source of the problem though.

**Comment by jfindlay** [comment] 2015-05-20 19:01
@froztbyte, thanks for the report.

**Comment by froztbyte** [comment] 2015-05-20 19:11
I'm not sure exactly how I managed to get that checkout to happen there,
presumably something with a missing name or target parameter while
figuring out the state. Let me know if I can help test.

**Comment by jfindlay** [comment] 2015-05-20 19:24
@froztbyte, but if you run the state in a known clean environment do you still encounter the original issue?

**Comment by froztbyte** [comment] 2015-05-20 19:36
I'll spin up a new instance tomorrow to test

**Comment by froztbyte** [comment] 2015-05-21 08:16
@jfindlay 

```
          ID: ensure we have a rancid user
    Function: user.present
        Name: rancid
      Result: True
     Comment: User rancid is present and up to date
     Started: 10:14:11.942376
    Duration: 0.573 ms
     Changes:
----------
          ID: install rancid dependencies
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
     Started: 10:14:11.943000
    Duration: 0.347 ms
     Changes:
----------
          ID: create the rancid directory
    Function: file.directory
        Name: /srv/rancid
      Result: True
     Comment: Directory /srv/rancid is in the correct state
     Started: 10:14:11.944577
    Duration: 0.591 ms
     Changes:
----------
          ID: create the rancid checkout directory
    Function: file.directory
        Name: /srv/rancid-git
      Result: True
     Comment: Directory /srv/rancid-git is in the correct state
     Started: 10:14:11.946346
    Duration: 0.46 ms
     Changes:
----------
          ID: fetch dotwaffle rancid-git
    Function: git.latest
        Name: https://github.com/dotwaffle/rancid-git.git
      Result: True
     Comment:
     Started: 10:14:11.948299
    Duration: 32.035 ms
     Changes:
```

Seems happy on a fresh instance.

**Comment by jfindlay** [comment] 2015-05-21 17:09
So the issue here is that we need a better error message in the case that the repository is not in the state that the git state expects it to be.

**Comment by terminalmage** [comment] 2015-08-20 15:56
This is actually an upstream bug with Git, and appears to be a duplicate of this issue: https://github.com/saltstack/salt/issues/15519#issuecomment-128531310

**Comment by terminalmage** [comment] 2015-08-20 16:00
I might be able to work around this by executing the ``git clone`` command using ``/tmp`` as the cwd, as this bug appears to be triggered when the cwd is ``/root`` (which is the default if the cwd is not specified, and we don't specify one when cloning).

**Comment by terminalmage** [comment] 2015-08-20 16:14
#26521 has a workaround for this. Marking as closed.

**Closed by terminalmage** 2015-08-20 16:14 UTC
Labels: Duplicate

**Comment by froztbyte** [comment] 2015-09-02 12:40
Awesome, thanks @terminalmage
