### ISSUE TITLE
[BUG] Regression; `junos.load` no longer renders jinja template

### ISSUE THREAD

**Issue by jtraub91** [saltstack/salt#59333] opened 2021-01-20 20:54 UTC
**Description**
Contrary to previous observed behavior, the `junos.load` command no longer renders the jinja template provided via the `path` argument

**Setup**
Normal salt installation.

Configure a junos proxy minion
```
# /srv/pillar/juniper-azure.sls
proxy:
  proxytype: junos
  host: x.x.x.x
  username: xxxx
  password: xxxxxxxxx
  port: 22
```
```
# /srv/pillar/top.sls
base:
  ...
  juniper-azure-proxy:
    - juniper-azure
```
and start the proxy
```
$ salt-proxy --proxyid=juniper-azure-proxy -d
```
Create a jinja template for abstraction
```
{# /srv/salt/templates/basic.j2 #} 
{%- set proxytype = pillar.get('proxy', {}).get('proxytype') %}
{%- set device_type = pillar.get('proxy', {}).get('device_type') %}
{%- if proxytype == 'junos' %}
set system no-redirects
set system no-redirects-ipv6
{%- elif proxytype == 'netmiko' and device_type == 'arista_eos' %}
aaa authorization console
no aaa root
{%- elif proxytype == 'netmiko' and device_type == 'cisco_nxos' %}
no ip access-list DENY-HOST
ip access-list DENY-HOST
deny ip host 10.0.0.1 any
{%- else %}
  {{ raise("Unsupported proxytype and / or device_type") }}
{%- endif %}
```
**Steps to Reproduce the behavior**
Attempt command
```
$ salt juniper-azure-proxy junos.load salt://templates/basic.j2 format='set'
```
See error below
```
juniper-azure-proxy:
    ----------
    format:
        set
    message:
        Could not load configuration due to : "ConfigLoadError(severity: error, bad_element: {#, message: error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command)"
    out:
        False
```
and we can see the un-rendered template in the debug logs
```
2021-01-20 20:52:20,310 [juniper-azure-proxy.salt.loaded.int.metaproxy.proxy                    :399 ][INFO    ][2689] Starting a new job with PID 2689
2021-01-20 20:52:20,311 [salt.utils.lazy                                                        :105 ][DEBUG   ][2689] Could not LazyLoad direct_call.allow_missing_func: 'direct_call.allow_missing_func' is not available.
2021-01-20 20:52:20,313 [salt.loader.localhost.int.module.junos                                 :132 ][DEBUG   ][2689] Caching file salt://templates/basic.j2 at /tmp/tmptpur_umd
2021-01-20 20:52:20,338 [salt.fileclient                                                        :1140][DEBUG   ][2689] In saltenv 'base', '/tmp/tmptpur_umd' is a directory. Changing dest to '/tmp/tmptpur_umd/basic.j2'
2021-01-20 20:52:20,339 [salt.fileclient                                                        :1162][DEBUG   ][2689] In saltenv 'base', ** considering ** path '/tmp/tmptpur_umd/basic.j2' to resolve 'salt://templates/basic.j2'
2021-01-20 20:52:20,339 [salt.fileclient                                                        :1183][DEBUG   ][2689] Fetching file from saltenv 'base', ** attempting ** 'salt://templates/basic.j2'
2021-01-20 20:52:20,355 [salt.fileclient                                                        :1299][INFO    ][2689] Fetching file from saltenv 'base', ** done ** 'templates/basic.j2'
2021-01-20 20:52:20,356 [ncclient.operations.rpc                                                :337 ][INFO    ][2689] [host juniper-azure session-id 24560] Requesting 'ExecuteRpc'
2021-01-20 20:52:20,357 [ncclient.transport.ssh                                                 :168 ][DEBUG   ][2689] [host juniper-azure session-id 24560] queueing <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:ebe86c0d-25ad-40dc-acd4-5acde6bf8691"><load-configuration format="text" action="set"><configuration-set>{# /srv/salt/templates/basic.j2 #} 
{%- set proxytype = pillar.get('proxy', {}).get('proxytype') %}
{%- set device_type = pillar.get('proxy', {}).get('device_type') %}
{%- if proxytype == 'junos' %}
set system no-redirects
set system no-redirects-ipv6
{%- elif proxytype == 'netmiko' and device_type == 'arista_eos' %}
aaa authorization console
no aaa root
{%- elif proxytype == 'netmiko' and device_type == 'cisco_nxos' %}
no ip access-list DENY-HOST
ip access-list DENY-HOST
deny ip host 10.0.0.1 any
{%- else %}
  {{ raise("Unsupported proxytype and / or device_type") }}
{%- endif %}
</configuration-set></load-configuration></nc:rpc>
2021-01-20 20:52:20,357 [ncclient.operations.rpc                                                :344 ][DEBUG   ][2689] [host juniper-azure session-id 24560] Sync request, will wait for timeout=30
2021-01-20 20:52:20,407 [ncclient.transport.ssh                                                 :500 ][DEBUG   ][2689] [host juniper-azure session-id 24560] Sending message
2021-01-20 20:52:20,408 [ncclient.transport.ssh                                                 :506 ][INFO    ][2689] [host juniper-azure session-id 24560] Sending:
<?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:ebe86c0d-25ad-40dc-acd4-5acde6bf8691"><load-configuration format="text" action="set"><configuration-set>{# /srv/salt/templates/basic.j2 #} 
{%- set proxytype = pillar.get('proxy', {}).get('proxytype') %}
{%- set device_type = pillar.get('proxy', {}).get('device_type') %}
{%- if proxytype == 'junos' %}
set system no-redirects
set system no-redirects-ipv6
{%- elif proxytype == 'netmiko' and device_type == 'arista_eos' %}
aaa authorization console
no aaa root
{%- elif proxytype == 'netmiko' and device_type == 'cisco_nxos' %}
no ip access-list DENY-HOST
ip access-list DENY-HOST
deny ip host 10.0.0.1 any
{%- else %}
  {{ raise("Unsupported proxytype and / or device_type") }}
{%- endif %}
</configuration-set></load-configuration></nc:rpc>]]>]]>
2021-01-20 20:52:20,502 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,506 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,536 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,544 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,545 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,546 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,546 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,547 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,548 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,549 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,549 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,552 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,554 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,567 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,568 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,568 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,569 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,570 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,571 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,571 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,573 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,575 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,579 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,580 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,580 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,581 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,582 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,583 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,583 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,584 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,585 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,585 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,586 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,587 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,587 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,588 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,589 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,589 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,590 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,591 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,595 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,595 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,596 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,597 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,597 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,598 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,599 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,600 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,600 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,601 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,601 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,602 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,603 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,603 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,604 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,604 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,605 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,608 [ncclient.transport.parser                                              :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] parsing netconf v1.0
2021-01-20 20:52:20,608 [ncclient.transport.ssh                                                 :125 ][INFO    ][2689] [host juniper-azure session-id 24560] Received message from host
2021-01-20 20:52:20,609 [ncclient.transport.ssh                                                 :127 ][DEBUG   ][2689] [host juniper-azure session-id 24560] Received:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/20.2R0/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:ebe86c0d-25ad-40dc-acd4-5acde6bf8691">
<load-configuration-results>
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>unknown command</error-message>
<error-info>
<bad-element>{#</bad-element>
</error-info>
</rpc-error>
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>unknown command</error-message>
<error-info>
<bad-element>{%-</bad-element>
</error-info>
</rpc-error>
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>unknown command</error-message>
<error-info>
<bad-element>{%-</bad-element>
...
```
**Expected behavior**
Salt should render the jinja and load the config

**Versions Report**
```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-62-generic
        system: Linux
       version: Ubuntu 20.04 focal

```

**Comment by dmurphy18** [comment] 2021-01-22 20:43
From chatting with @jtraub91 have the following:
```
ncclient==0.6.9
junos-eznc==2.5.4
```
Also this was working prior to 3002.2

**Comment by dmurphy18** [comment] 2021-01-26 00:46
@jtraub91 The code passes the tests for it, and wondering if this is a case of the code progressing past older functionality which has subsequently been tightened up by Juniper. for example:
```
root@Unknown:/srv/salt# salt p8000 junos.load "salt://files/rest.set" timeout=100 template_vars='{"mgmtip": "192.168.50.100"}'
p8000:
    ----------
    message:
        Successfully loaded the configuration.
    out:
        True

where rest.setroot@Unknown:/srv/salt# cat files/rest.set 
set system services rest control allowed-sources [ 127.0.0.1 {{ template_vars["mgmtip"] }} ]
root@Unknown:/srv/salt#
```

Similar to issue https://github.com/saltstack/salt/issues/57665 where template_vars appear to be required now.  This area has undergone significant contributions recently from Juniper.
Digging further but wanted to give some feedback

**Comment by jtraub91** [comment] 2021-01-26 15:39
@dmurphy18 Thanks for the update. If `template_vars` is now required for the template to render, this still should marked as a bug, right?

**Comment by sagetherage** [comment] 2021-01-26 16:12
@dmurphy18 since this is a `Regression` we really should fix it in `Aluminium` please let me know if you can get to this or not.

**Comment by dmurphy18** [comment] 2021-01-26 16:15
@sagetherage actually started working on it yesterday

**Comment by dmurphy18** [comment] 2021-01-26 22:05
@jtraub91 With junos-eznc and ncclient that oyu are using and salt-proxy version 3001.4 (early version for Ubuntu 20.04)
```root@Unknown:/srv/pillar# salt p7000 junos.load salt://templates/basic2.j2 format='set'
p7000:
    ----------
    format:
        set
    message:
        Could not load configuration due to : "ConfigLoadError(severity: error, bad_element: {%, message: error: unknown command
        error: invalid value
        error: invalid value
        error: unknown command)"
    out:
        False
root@Unknown:/srv/pillar# salt p7000 test.versions
p7000:
    Salt Version:
               Salt: 3001.4
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.7.3
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.1.0
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: Not Installed
       pycryptodome: 3.6.1
             pygit2: Not Installed
             Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
       python-gnupg: 0.4.5
             PyYAML: 5.3.1
              PyZMQ: 18.1.1
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.2
     
    System Versions:
               dist: ubuntu 20.04 focal
             locale: utf-8
            machine: x86_64
            release: 5.8.0-40-generic
             system: Linux
            version: Ubuntu 20.04 focal
     
root@Unknown:/srv/pillar# ```

Where the earlier version being used Python 2 based (believe Salt only release support for Ubuntu 20.04 with Salt v3001), or were you or are you using Ubuntu's fork of Salt ?

You said this was working with previous version, but I cannot get it to work with previous version, marking as 'cannot reproduce' for now.

Even tried with junos-eznc 2.5.0 and ncclient 0.6.6 and still the same configuration errors with bad_element

**Comment by jtraub91** [comment] 2021-01-26 22:25
@dmurphy18 I don't recall which version I was running when it was working.

Even if we cannot reproduce the working condition, I would argue this still warrants a bug fix. It should render the template regardless of whether `template_vars` are passed as a keyword argument.

**Comment by dmurphy18** [comment] 2021-01-26 22:55
@jtraub91 There are not very many versions of Salt to try on Ubuntu 20.04, v3001 and v3002 with minor releases and a lot of those are for CVE fixes.  I have tried both versions and it doesn't work, therefore you are requesting to fix something that from my testing doesn't work on wither of the versions that Salt as released for Ubuntu 20.04.

There no Py 2 version of Salt released for Ubuntu 20.04 from SaltStack.

Really need the version that this was working on to proceed further, since the changes from the native minion work went into v3002, but this still fails on v3001 which did not contain those changes.  Were the previous versions or the versions that you are using installed using pip and PyPi rather than packaged software ?
If so, can yu hazard a guess as to 2019.2.x or 3000 ?

**Comment by dmurphy18** [comment] 2021-01-27 00:43
@jtraub91 Tried installing a version of Salt before it was supported by v3001 and Salt did not support Py 3.8 which ships with Ubuntu 20.04.  After pip3 install salt==3000.6

```
root@david-VirtualBox:/home/david# salt-call --local test.versions
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 8, in <module>
    sys.exit(salt_call())
  File "/usr/local/lib/python3.8/dist-packages/salt/scripts.py", line 440, in salt_call
    import salt.cli.call
  File "/usr/local/lib/python3.8/dist-packages/salt/cli/call.py", line 5, in <module>
    import salt.utils.parsers
  File "/usr/local/lib/python3.8/dist-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/usr/local/lib/python3.8/dist-packages/salt/config/__init__.py", line 100, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/usr/local/lib/python3.8/dist-packages/salt/config/__init__.py", line 89, in _gather_buffer_space
    import salt.grains.core
  File "/usr/local/lib/python3.8/dist-packages/salt/grains/core.py", line 40, in <module>
    from platform import _supported_dists
ImportError: cannot import name '_supported_dists' from 'platform' (/usr/lib/python3.8/platform.py)
root@david-VirtualBox:/home/david# 
```

As expected, therefore I don't see how this worked previously, esp. given that Ubuntu 20.04 does not come with their fork of Salt.  I am using the current Ubuntu 20.04
```
root@david-VirtualBox:/home/david# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Comment by sagetherage** [comment] 2021-01-27 16:44
if this never worked then it isn't a regression and goes back into the planning phase, so I have updated the labels, and we would like to hear more from you @jtraub91 so we can appropriately plan. Thanks for submitting the issue and the continued communication.

**Comment by dmurphy18** [comment] 2021-01-27 18:13
Able to confirm that this works with the following seutp:   Centos 7
```
[root@Unknown salt]# salt p8000 test.versions
p8000:
    Salt Version:
               Salt: 3000.6
     
    Dependency Versions:
               cffi: 1.14.4
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.11.2
            libgit2: Not Installed
           M2Crypto: 0.35.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: 2.20
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
       python-gnupg: Not Installed
             PyYAML: 5.4.1
              PyZMQ: 15.3.0
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7.9.2009 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-1127.18.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.9.2009 Core
     
[root@Unknown salt]# salt p8000 junos.load "salt://files/rest.set" timeout=100 template_vars='{"mgmtip": "192.168.50.100"}'
p8000:
    ----------
    message:
        Successfully loaded the configuration.
    out:
        True
[root@Unknown salt]# salt p8000 junos.load salt://templates/basic.j2 format='set'
p8000:
    ----------
    message:
        Successfully loaded the configuration.
    out:
        True
[root@Unknown salt]# 
```

**Comment by dmurphy18** [comment] 2021-01-27 18:21
Breakage occurred by Salt 3001.4
```
[root@Unknown salt]# salt p8000 test.versions
p8000:
    Salt Version:
               Salt: 3001.4
     
    Dependency Versions:
               cffi: 1.14.4
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.11.2
            libgit2: Not Installed
           M2Crypto: 0.35.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: 2.20
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
       python-gnupg: Not Installed
             PyYAML: 5.4.1
              PyZMQ: 17.0.0
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-1127.18.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7 Core
     
[root@Unknown salt]# salt p8000 junos.load "salt://files/rest.set" timeout=100 template_vars='{"mgmtip": "192.168.50.100"}'
p8000:
    ----------
    message:
        Successfully loaded the configuration.
    out:
        True
[root@Unknown salt]# salt p8000 junos.load salt://templates/basic.j2 format='set'
p8000:
    ----------
    format:
        set
    message:
        Could not load configuration due to : "ConfigLoadError(severity: error, bad_element: {#, message: error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command)"
    out:
        False

```

**Comment by dmurphy18** [comment] 2021-01-27 18:43
functionality broke with first 3001 release
```
[root@Unknown salt]# salt p8000 test.versions
p8000:
    Salt Version:
               Salt: 3001
     
    Dependency Versions:
               cffi: 1.14.4
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.11.2
            libgit2: Not Installed
           M2Crypto: 0.35.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: 2.20
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
       python-gnupg: Not Installed
             PyYAML: 5.4.1
              PyZMQ: 17.0.0
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-1127.18.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7 Core
     
[root@Unknown salt]# salt p8000 junos.load "salt://files/rest.set" timeout=100 template_vars='{"mgmtip": "192.168.50.100"}'
p8000:
    ----------
    message:
        Successfully loaded the configuration.
    out:
        True
[root@Unknown salt]# salt p8000 junos.load salt://templates/basic.j2 format='set'
p8000:
    ----------
    format:
        set
    message:
        Could not load configuration due to : "ConfigLoadError(severity: error, bad_element: {#, message: error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command)"
    out:
        False
```

**Comment by dmurphy18** [comment] 2021-01-28 00:39
in the rewrite to use HandleFileCopy in the run up to v3001, an assumption was made that if a template was used, that kwargs would be used.  Previously they were not required for correct operation.
```
[root@Unknown salt]# salt p8000 junos.load salt://templates/basic.j2 format='set'
p8000:
    ----------
    format:
        set
    message:
        Could not load configuration due to : "ConfigLoadError(severity: error, bad_element: {#, message: error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command
        error: unknown command)"
    out:
        False
[root@Unknown salt]# salt p8000 junos.load salt://templates/basic.j2 format='set' template_vars='{"mgmtip": "192.168.50.100"}'
p8000:
    ----------
    message:
        Successfully loaded the configuration.
    out:
        True
```

see '# kwargs will have values when path is a template' on line https://github.com/saltstack/salt/blob/310405df2c2a0dafa07b39eb54178d0031ed12ee/salt/modules/junos.py#L114
and https://github.com/saltstack/salt/blob/310405df2c2a0dafa07b39eb54178d0031ed12ee/salt/modules/junos.py#L133-L140

@vnitinv Wonder if you have comments on these assumptions about kwargs which have caused a regression.

**Comment by vnitinv** [comment] 2021-01-28 05:16
@dmurphy18 That assumption was a mistake from my end. Do you want our team to fix this our can be taken care of by friends at saltstack.

**Comment by dmurphy18** [comment] 2021-01-28 16:37
@vnitinv My worry in SaltStack fixing it, is that I might kill something that Juniper is relying on, especially in relation to proxy vs minion usage with files.  I would prefer Juniper team to fix it given this code was provided by Juniper.  I would like to get the fix in for the Aluminium release time frame, will that be possible, if not, I shall fix it.

**Comment by dmurphy18** [comment] 2021-02-09 01:14
@vnitinv Is Juniper going to take this or shall I go ahead and fix ?

**Comment by dmurphy18** [comment] 2021-02-17 19:40
Moved to Silicon to allow time for writing tests and removing bad assumption

**Comment by vnitinv** [comment] 2021-02-19 17:48
@dmurphy18 I am checking with team so that someone can work and get this fixed with proper validation.

**Comment by dmurphy18** [comment] 2021-04-13 19:21
@vnitinv Going to work on this, will make you a reviewer on the PR.  Note, the Juniper native minion is going to be released as part of the Open-Source, which should not affect anything since at this point all changes are part of Salt open source and only the build script is different (will preserve cert's etc privately), similar to how Salt builds and signs Linux packages at present.

**Comment by dmurphy18** [comment] 2021-04-21 20:42
Closing since https://github.com/saltstack/salt/pull/60052 has been merged

**Closed by dmurphy18** 2021-04-21 20:42 UTC
Labels: Bug, Regression, Silicon, severity-medium
