### ISSUE TITLE
salt.modules.runit fails 'invalid argument' on non-symlinked service

### ISSUE THREAD

**Issue by bbczeuz** [saltstack/salt#52759] opened 2019-04-30 12:55 UTC
### Description of Issue/Question
Service management via salt-formula in a runit based container fails.

### Setup
state top.sls:
```
base:
  '*':
    - salt.minion
```
(use salt-formula; The whole salt-setup runs within a runit-based container)

pillar salt.sls:
```
salt:
  master_remove_config: True
  minion_remove_config: True
  release: '2018.3'
  version: latest
  minion:
    master: 192.168.0.1
    master_port: 4506
    publish_port: 4505
```

### Steps to Reproduce Issue
```
root@testsystem:~# salt 'saltmaster-test01' state.apply salt.minion
saltmaster-test01:
[...]
          ID: salt-minion
    Function: service.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1919, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1918, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/service.py", line 407, in running
                  if not _available(name, ret):
                File "/usr/lib/python2.7/dist-packages/salt/states/service.py", line 326, in _available
                  avail = __salt__['service.available'](name)
                File "/usr/lib/python2.7/dist-packages/salt/modules/runit.py", line 427, in available
                  return name in _get_svc_list(name)
                File "/usr/lib/python2.7/dist-packages/salt/modules/runit.py", line 390, in _get_svc_list
                  return sorted([os.path.basename(el) for el in _get_svc_path(name, status)])
                File "/usr/lib/python2.7/dist-packages/salt/modules/runit.py", line 354, in _get_svc_path
                  ena.add(os.readlink(el))
              OSError: [Errno 22] Invalid argument: '/etc/service/salt-minion'
     Started: 12:41:32.640261
    Duration: 2.0 ms
     Changes:   
[...]
```

### Versions Report
(same on master and minion)
```
# salt --versions-report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by zenitraM** [comment] 2020-01-22 20:59
This is still an issue today. Seems it might be fixed with #52760.

The code seems to assume available services will be symlinked from `/etc/sv`, but only considers this path for available services if running Void Linux - otherwise you need to specify the path manually. 
I haven't dug on if this part is a Void distro default or if it's a common `runit` standard, though.

**Comment by sagetherage** [comment] 2021-05-24 22:58
@zenitraM what supported version of Salt are you still seeing this issue?

**Comment by sagetherage** [comment] 2021-06-21 18:45
Reviewed in Grooming 2021-JUN-21 and is still a valid issue, moving to a stretch-goal for the Silicon release cycle and if not picked up and completed then it will soon after in another release cycle.

**Comment by waynew** [comment] 2021-06-21 18:47
Confirmed this is definitely an issue within salt/modules/runit.py - our existing code within `_get_svc_path` (and get_svc_alias) is using `os.readlink` which requires the argument be a symlink. The correct code at least for the problem in question can be found in the attached PR that didn't get any tests yet.

@bbczeuz if you're willing to write some tests & rebase against master we can totally re-open the PR and get that merged in!

Otherwise we need to add some tests - unit would be fine but it would also be possible to throw together a quick functional test that creates some files - both symlinks & actual files - and then ensures that this code works with either of them.

**Comment by bbczeuz** [comment] 2021-06-22 07:31
I'll keep this in my mind. Unfortunately, by the time in the application that had this issue, we moved away from runit to busybox, so recreating the test environment is non trivial.
Are there any good starting points for creating unittests in salt? Last saltconf I attended, pytest was the way to go, how about these days?

**Comment by waynew** [comment] 2021-11-19 18:10
@bbczeuz Doh! My bad - looks like my reply link got out of date - should have been https://www.twitch.tv/saltprojectoss/schedule - next week, due to holidays there won't be any test clinic.

**Comment by waynew** [comment] 2021-12-13 22:55
@bbczeuz if you're still interested in fixing this, I'll be doing a test clinic tomorrow and Thursday -- then nothing until January.

**Comment by waynew** [comment] 2022-01-05 00:34
@bbczeuz Just a ping - I'm back, had our first Test Clinic today. Back to Tuesday/Thursdays - if you need some help getting started just let me know! (or show up :) )

**Closed** 2022-02-22 19:30 UTC
Labels: Bug, severity-high, good first issue, Phosphorus v3005.0
