### ISSUE TITLE
[BUG] Pillar targetting fails when minion is offline

### ISSUE THREAD

**Issue by ari** [saltstack/salt#60710] opened 2021-08-11 00:40 UTC
**Description**
When a minion is offline, pillar targetting will incorrectly target that minion resulting in an error which will then break orchestration with dependencies between states.

**Setup**
One minion is offline (eg. for maintenance)

**Steps to Reproduce the behavior**
```
    # salt '*' saltutil.refresh_pillar
    # salt -I 'unused_key:123' test.version
    dead-minion:
        Minion did not return. [No response]
        The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
        salt-run jobs.lookup_jid 20210811003619253412
```

**Expected behavior**
Pillar is rendered on the server, so the server cache is only used for targetting. Commands should not be sent to offline minions.

**Versions Report**

```
# salt --versions-report
Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.7.11 (default, Jul  8 2021, 09:02:17)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.1.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: freebsd 13.0
        locale: utf-8
       machine: amd64
       release: 13.0-RELEASE-p1
        system: FreeBSD
       version: FreeBSD 13.0
```

**Comment by ari** [comment] 2021-08-11 01:25
I think I've not communicated the nature of the problem. The salt targeting should never attempt to contact that Minion at all. The pillar key doesn't exist on the server pillar cache.

The problem isn't that test ping doesn't return. The problem is that the command was sent to the Minion at all.

**Comment by dmurphy18** [comment] 2021-08-11 01:34
Saw your comment in community and answered some part of your issue there.
But the point here is that the master does not know if something is offline or unresponsive, a network outage may make something appear offline for a while and then it communicates again and all is well.

It is in the nature of async communication between master and minion.
My thought with test.ping is that when it fails, using requisites onfail you can skip it, pick appropriate timeouts so not waiting for too long.

**Comment by ari** [comment] 2021-08-11 03:40
Let me try to explain this another way. I have 100 minions. One of them is offline. If I do this:

    # salt good-minion.1 test.ping

then I get a good response. The bad minion is never even queried and we don't care it is offline. I can even use wildcards and target lots of minions without problem:

    # salt 'good-minion.*' test.ping

However if I do this:

    # salt -I 'invalid-key:123' test.ping

Despite the fact that the key doesn't exist in the pillar at all, the offline minion is still involved and we get a error. Since the docs clearly say that the targetting is done on the *master* using pillar calculated there, the minion should not have returned an error. https://docs.saltproject.io/en/latest/topics/targeting/pillar.html

It appears that the master is contacting ALL minions when -I targetting is used, but not when minion id targetting is used. This is wrong according to the docs.

**Comment by ari** [comment] 2021-08-11 10:26
To explain my use case more...

I use pillar data to define groupings of servers in interesting and useful ways. They tie into salt-cloud deployment, pull data from custom pillar from databases and files on disk. Customers can spin up their own servers using our portal which then fires an event to salt-cloud, adds a minion and provisions everything. They can reconfigure things in the portal database which then makes changes to the pillar data and updates load balancers and servers.

So I need a reliable way to target minions with:

* the correct pillar and only the pillar data they should be allowed to see
* the correct states for highstate
* within orchestration

Obviously minion ids scattered all through the code are not good. Nodegroups are an alias for lists of minions which is good, but they can't be updated dynamically (unless they rely on pillar data and we are right back to where we started).

I can't use grains for targetting since that's insecure.

PIllar is perfect. If only it was more reliable. In this ticket it looks like the master is sending events to minions even if they don't match the correct pillar.

**Comment by dmurphy18** [comment] 2021-08-11 15:16
@ari I see from your use-case explanation that the problem is not the underlying master minion communication but that from using -I offline minions are getting contacted when straight glob of minion ids does not contact offline minions, and that still is not as per documentation.  Do I have that correct ?

Will investigate that issue , which is somewhat different from the generic communications between the master and minion I was describing.

**Comment by dmurphy18** [comment] 2021-08-11 17:40
From running a test against a mix of Centos7, Debian 10 and Ubuntu, I see the following:
```
root@Unknown:/srv/pillar# salt -I 'foo:bar:version' test.version
tc7:
    3003.1
tu20:
    3003.1
td10:
    3002.6
tc7plus:
    3003.1
root@Unknown:/srv/pillar# salt '*' test.version
tu20:
    3003.1
tc7:
    3003.1
td10:
    3002.6
tc7plus:
    3003.1
```
turn off the Debian 10 machine, that is maintainence and offline

```
root@Unknown:/srv/pillar# salt '*' test.version
tu20:
    3003.1
tc7:
    3003.1
tc7plus:
    3003.1
td10:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20210811173458572877
ERROR: Minions returned with non-zero exit code
root@Unknown:/srv/pillar# salt -I 'foo:bar:version' test.version
tu20:
    3003.1
tc7:
    3003.1
tc7plus:
    3003.1
td10:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20210811173518927120
ERROR: Minions returned with non-zero exit code
root@Unknown:/srv/pillar# 
```
which implies both grain and pillar targeting operate no differently, that is, offline generates a 'no response'

**Comment by ari** [comment] 2021-08-11 21:15
OK, now try this with td10 offline:

    # salt 'tc*' test.version

I would expect td10 to not be contacted and not time out.

And then try (again with td10 offline):

    # salt '*' saltutil.refresh_pillar
    # salt -I 'foo:bar:1234' test.version

Since 'foo:bar:1234' does not exist in the pillar, it should return nothing and attempt to contact no minions. Does the test.version command give you a time out error for td10?

**Comment by dmurphy18** [comment] 2021-08-12 16:38
So trying your request, with my current environment and everything connected (except for two old Solaris 11 minions)

```
root@Unknown:~# salt 't*' test.version
td10:
    3002.6
tc7:
    3003.1
tu20:
    3003.1
tc7plus:
    3003.1
root@Unknown:~# salt -I 'foo:bar:version' test.version
td10:
    3002.6
tc7:
    3003.1
tu20:
    3003.1
tc7plus:
    3003.1
sol11ia:
    Minion did not return. [Not connected]
sol11b:
    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code
```
The Solaris machines were turned off yesterday evening, and this is the following morning, so caches should have expired.  Now turning off the Debian 10 minion td10 (and still fresh cache for it)

```
root@Unknown:~# salt -I 'foo:bar:version' test.version
td10:
    3002.6
tc7:
    3003.1
tu20:
    3003.1
tc7plus:
    3003.1
sol11ia:
    Minion did not return. [Not connected]
sol11b:
    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code
root@Unknown:~# salt 't*' test.version
tu20:
    3003.1
tc7:
    3003.1
tc7plus:
    3003.1
td10:
    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code
root@Unknown:~# salt -I 'foo:bar:version' test.version
tu20:
    3003.1
tc7:
    3003.1
tc7plus:
    3003.1
sol11b:
    Minion did not return. [Not connected]
td10:
    Minion did not return. [Not connected]
sol11ia:
    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code
root@Unknown:~# salt -I 'foo:bar:1234' test.version
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
root@Unknown:~# 
```

So  'foo:bar:1234' does not exist in the pillar, and hence nothing sent.  But I still get 'Minion did not return. [Not connected]' for tb10 with the grains glob, also the Solaris 11 machines, implying in cache or expired, get the same result 'Not Connected', and an attempt is made to contact the offline machines.

So in your environment, there is no attempt to contact the offline machine for grains glob ?

I am using VirtualBox VMs for all of my machines, but I don't expect that to affect anything, and the salt-master is Centos 7 (up to date) with both Salt 3003.1 and now the released yesterday Salt 3003.2 producing the same result, which is different to the result in your environment.

In my environment, both grains globing and target pillar produce the same error as attempts are made to contact the offline minion.  My environment is pretty basic too.  I tried making another minion offline (tc7 3003.1), and brought tb10 back online (it is 3002.6), to see if that makes a difference, also varied when refresh_pillar was used, before offline and after offline, but result was the same and different to your experience.

```
root@Unknown:~# salt 't*' test.version
tu20:
    3003.1
tc7:
    3003.1
td10:
    3002.6
tc7plus:
    3003.1
root@Unknown:~#  salt '*' saltutil.refresh_pillar
tu20:
    True
tc7:
    True
td10:
    True
tc7plus:
    True
sol11b:
    Minion did not return. [Not connected]
sol11ia:
    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code
root@Unknown:~# salt 't*' test.version
td10:
    3002.6
tu20:
    3003.1
tc7:
    3003.1
tc7plus:
    3003.1
root@Unknown:~# salt 't*' test.version
td10:
    3002.6
tu20:
    3003.1
tc7plus:
    3003.1
tc7:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20210812162850415799
ERROR: Minions returned with non-zero exit code
root@Unknown:~# salt '*' saltutil.refresh_pillar
tu20:
    True
td10:
    True
tc7plus:
    True
sol11b:
    Minion did not return. [Not connected]
sol11ia:
    Minion did not return. [Not connected]
tc7:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20210812163044279263
ERROR: Minions returned with non-zero exit code
root@Unknown:~# salt 't*' test.version
td10:
    3002.6
tu20:
    3003.1
tc7plus:
    3003.1
tc7:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20210812163106377483
ERROR: Minions returned with non-zero exit code
root@Unknown:~# 
```
I am unable to reproduce your experience with grains globing, is there any other information on your environment  that you can provide, which might enable me to achieve the same result that you are experiencing.
I have noted the target pillar globing issue in https://github.com/saltstack/salt/issues/60716 and the documentation, but that is unrelated to this issue since no target pillar globing is occurring here.

**Comment by ari** [comment] 2021-08-14 12:53
Perhaps the pillar problem is related to the grains bug. In my pillar I have entries in top like:

    - minions.{{ opts.id }}

which is used to add specific minion configuration by minion id. Is this accessing the grain and therefore contacting the minion? I can't think of anything else which is relevant.

**Comment by dmurphy18** [comment] 2021-08-17 20:08
@ari I believe the grains targeting should be independent of the pillar information, which raises the question:

Why does grains globing work for you but I cannot reproduce it, that is, when I try, it results in failure.

Is there any other information which you can supply which would help explain why you see grains globing working when the minion is offline?
Also without a sanitized copy of the pillar which produces the problem, it will be hard to debug the issue experienced, even the structure of the pillar files would help here.

**Comment by dmurphy18** [comment] 2022-02-04 21:20
@ari  Back working on this and kind of understand the issue, however believe the same problem exists whether using grain or pillar targeting.  Get the example above with 'tc*' and 'td*' not responding or being shown.  
It seems your issue is the response message for the turned off minion.   Please correct me if I am incorrect in that assumption.

Here is my setup, but note that if you target grains which don't exist, you get a similar response message whether you use grains or pillar targeting.

```
root@c7mstr:/srv/salt# salt '*' test.ping
tu20:
    True
tdeb10:
    True
m7m:
    True
tc8:
    True
root@c7mstr:/srv/salt# salt '*' pillar.items
tu20:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
m7m:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
tdeb10:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
tc8:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
root@c7mstr:/srv/salt#
```

I now target using specific grain id  tu20

```
root@c7mstr:/srv/salt# salt 'tu*' test.ping
tu20:
    True
root@c7mstr:/srv/salt# the salt-minion on tc8
```

Note no error message, but if target something which doesn't exist gives an error message

```
root@c7mstr:/srv/salt# salt 'd*' test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
root@c7mstr:/srv/salt# 
```

Similar with pillar targeting, and then for non-existing pillar key

```
root@c7mstr:/srv/salt# salt -I 'foo:bar:version' test.ping
tu20:
    True
tdeb10:
    True
m7m:
    True
tc8:
    True
root@c7mstr:/srv/salt# salt -I 'dog:bar:version' test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
root@c7mstr:/srv/salt# 
```

With salt-minion on tc8 taken offline, the following commands function exactly the same:
salt 'tu*' test.ping
salt 'd*' test.ping
salt -I 'dog:bar:version' test.ping

However do see differences for the following commands
```
root@c7mstr:/srv/salt# salt '*' test.ping
tu20:
    True
tdeb10:
    True
m7m:
    True
tc8:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20220204210346164449
ERROR: Minions returned with non-zero exit code
root@c7mstr:/srv/salt# salt -I 'foo:bar:version' test.ping
tu20:
    True
tdeb10:
    True
m7m:
    True
tc8:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20220204210413423030
ERROR: Minions returned with non-zero exit code
root@c7mstr:/srv/salt# 
```
Both grains and pillar targeting react similarly, whether the grain id doesn't exist or the pillar key doesn't exist, or all minions match id specified, or all pillar key specified.
Again communication between Master and Minion is asynchronous, hence Master will not known if a Minion is offline, or just unreachable over a network for some reason. Targeting with grains id 't*' notes tc8 is unavailable
```
root@c7mstr:/srv/salt# salt 't*' test.ping
tu20:
    True
tdeb10:
    True
tc8:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20220204211042157103
ERROR: Minions returned with non-zero exit code
root@c7mstr:/srv/salt# salt -I 'foo:bar:dog' test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
root@c7mstr:/srv/salt# 
```

If there is some other way to explain the issue, please attempt to do so, so I might understand further the issue.
While waiting for info, I shall work in the pillar key globing issue highlighted in https://github.com/saltstack/salt/issues/60716 which might highlight your issue in a different manner.

**Comment by ari** [comment] 2022-02-07 20:50
You've tested lots of things, but I'm not sure you tried the situation which causes the problem.

1. Make sure tc8 does NOT contain the pillar 'some_pillar'
1. Take tc8 offline
1. salt -I 'some_pillar' test.ping

You should now not get an error or report of a missing minion. The salt server should not be contacting minions to get their pillar as part of the targetting phase.


At any rate, I found all the pillar/grains targetting so unreliable I've stopped using it since I reported this bug. Now I have a lot more duplicate configuration but at least it works. Sorry that I can't help more to reproduce the problem but I'm just going by memory.

**Comment by dmurphy18** [comment] 2022-02-07 23:06
thanks for the update, so make sure the missing minion does not have that pillar entry that the other minions have.  Will try that and report back.

Understand, but just spent time debugging the pillar caching only to realize that, if I had read the documentation better, than it was working as documented (no wildcard in pillar keys)

**Comment by ari** [comment] 2022-02-08 00:10
What is the distinction between a pillar key and a pillar value? Can pillar contain a value which is a list?

**Comment by dmurphy18** [comment] 2022-02-08 01:35
```
root@c7mstr:/home/david# cat /srv/pillar/foo.sls 

foo:
  bar:
    version: 3003.1
```
foo, bar and version are keys, 3003.1 is a value, hence the follow command works since wildcard in value
```
salt -I 'foo:bar:version:30*' test.version
```
but wildcard in the key does not
```
salt -I 'foo:bar:vers*' test.version
```

Don't know about a list for the value of the top of my head, will check when trying this issue tomorrow

**Comment by dmurphy18** [comment] 2022-02-08 01:53
Have tdeb10, tdeb11 and tc8, added new dogs.sls to pillar top.sls file and updated the 'td*' Debian minions but leave tc8 out of it.
```
root@c7mstr:/srv/pillar# salt 'td*' saltutil.pillar_refresh
tdeb11:
    True
tdeb10:
    True
root@c7mstr:/srv/pillar# salt 'td*' pillar.items
tdeb11:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
    mutts:
        ----------
        fido:
            ----------
            age:
                5
        rex:
            ----------
            age:
                10
        rover:
            ----------
            age:
                6
tdeb10:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
    mutts:
        ----------
        fido:
            ----------
            age:
                5
        rex:
            ----------
            age:
                10
        rover:
            ----------
            age:
                6
root@c7mstr:/srv/pillar# salt 'tc*' pillar.items
tc8:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
    mutts:
        ----------
        fido:
            ----------
            age:
                5
        rex:
            ----------
            age:
                10
        rover:
            ----------
            age:
                6
root@c7mstr:/srv/pillar# 
```
Now turn tc8 offline and try pillar target for pillar items tc8 doesn't have.
```
root@c7mstr:/srv/pillar# salt -I 'mutts:rex:age:*' test.version
tdeb11:
    3004
tdeb10:
    3004
tc8:
    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code
root@c7mstr:/srv/pillar# 
```
And tc8 should not have had the pillar items, since the pillar refresh was not directed at it, unless the pillar items command did a refresh under the covers ?, which may have occurred since just brought it up. Will redo in the morning

**Comment by dmurphy18** [comment] 2022-02-08 02:00
Perhaps there is a pillar refresh occurring that is not obvious, since redoing the test but this time taking tc8 offline before the pillar_refresh command so that tc8 cannot have any connection or knowledge of the new pillar items, and everything appears to function correctly and tc8 is not included.
```
root@c7mstr:/srv/pillar# salt '*' pillar.items
tdeb11:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
tdeb10:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
tc8:
    ----------
    foo:
        ----------
        bar:
            ----------
            version:
                3003.1
root@c7mstr:/srv/pillar# salt tc8 pillar.items
tc8:
    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code
root@c7mstr:/srv/pillar# vim top.sls
root@c7mstr:/srv/pillar# salt 'tdeb*' saltutil.pillar_refresh
tdeb11:
    True
tdeb10:
    True
root@c7mstr:/srv/pillar# salt -I 'mutts:rex:age:*' test.version
tdeb11:
    3004
tdeb10:
    3004
root@c7mstr:/srv/pillar# 
```
Perhaps the non-obvious pillar refresh which was unexpected in the first attempt above is the reason for the offline minion being included, there must be at some point a pillar refresh occurring for it before the offline occurs

**Comment by ari** [comment] 2022-02-08 02:05
Sounds consistent with what I remember seeing. I would argue that the targeting phase should not cause any server-minion communication ever and should only rely on whatever existing cached data is on the server.

Is there a mechanism to refresh the pillar only on the server? pillar_refresh seems to be about updating the minion cache, not the server cache, but its really confusing how it all works.

Obviously targeting with grains is more complex and I have no opinion on how that should work (or whether that really should even be allowed)

**Comment by dmurphy18** [comment] 2022-02-08 02:21
@ari the master does rely on what it has, went through that code when it is processing the minion cache that it has.  The issue here I believe at the moment is that the master is getting the updated key in it's cache for the minion non-obviously, the only way I prevented that was by making the minion offline before updating the pillars.

I will be going through the master's cache update mechanisms tomorrow, but it may come down to what state the minion is offline/online before going offline when the pillar keys and values are updated, as seen in my final test above. If the minion is in the master's cache for the updated pillar information, before it goes offline, the master will look for that minion.

I need to determine when the pillar cache is getting updated for the minions, tomorrow

**Comment by dmurphy18** [comment] 2022-02-08 22:47
@ari Okay everything is working correctly, the problem I had in comment https://github.com/saltstack/salt/issues/60710#issuecomment-1032133551 was my mistake, I ran pillar.items on the Centos 8 minion tc8 which would have recompiled the pillar data, as stated in https://docs.saltproject.io/en/latest/topics/pillar/index.html#pillar-in-memory

```
In contrast to in-memory pillar data, certain actions trigger pillar data to be compiled to ensure that the most up-to-date pillar data is available. These actions include:

Running states

Running pillar.items
```

Whoops, sorry about forgetting that. Instrumented the salt-master and can confirm that only updated minions with pillar data from the refresh_pillar command are processed
```1996 2022-02-08 15:35:23,882 [salt.utils.minions:323 ][DEBUG   ][13576] DGM _check_cache_minions greedy 'True', cache_enabled 'True', cminions '['tc8', 'tdeb11', 'tdeb10']', minions '['tc8', 'tdeb10', 'tde     b11']'
1997 2022-02-08 15:35:23,882 [salt.utils.data  :979 ][DEBUG   ][13576] Attempting to match '*' in 'mutts:rex:age' using delimiter ':'
1998 2022-02-08 15:35:23,882 [salt.utils.data  :979 ][DEBUG   ][13576] Attempting to match 'age:*' in 'mutts:rex' using delimiter ':'
1999 2022-02-08 15:35:23,882 [salt.utils.data  :979 ][DEBUG   ][13576] Attempting to match 'rex:age:*' in 'mutts' using delimiter ':'
2000 2022-02-08 15:35:23,882 [salt.utils.data  :979 ][DEBUG   ][13576] Attempting to match '*' in 'mutts:rex:age' using delimiter ':'
2001 2022-02-08 15:35:23,883 [salt.utils.data  :979 ][DEBUG   ][13576] Attempting to match '*' in 'mutts:rex:age' using delimiter ':'
2002 2022-02-08 15:35:23,883 [salt.utils.minions:343 ][DEBUG   ][13576] DGM _check_cache_minions output list minions '['tdeb10', 'tdeb11']'
2003 2022-02-08 15:35:23,884 [salt.utils.lazy  :99  ][DEBUG   ][13576] LazyLoaded local_cache.prep_jid
2004 2022-02-08 15:35:23,887 [salt.utils.event :817 ][DEBUG   ][13576] Sending event: tag = 20220208223523884137; data = {'minions': ['tdeb10', 'tdeb11'], '_stamp': '2022-02-08T22:35:23.887787'}
2005 2022-02-08 15:35:23,888 [salt.utils.event :817 ][DEBUG   ][13576] Sending event: tag = salt/job/20220208223523884137/new; data = {'jid': '20220208223523884137', 'tgt_type': 'pillar', 'tgt': 'mutts:rex     :age:*', 'user': 'sudo_david', 'fun': 'test.version', 'arg': [], 'minions': ['tdeb10', 'tdeb11'], 'missing': [], '_stamp': '2022-02-08T22:35:23.888696'}
2006 2022-02-08 15:35:23,890 [salt.loaded.int.returner.local_cache:240 ][DEBUG   ][13576] Adding minions for job 20220208223523884137: ['tdeb10', 'tdeb11']
2007 2022-02-08 15:35:23,890 [salt.master      :2446][INFO    ][13576] User sudo_david Published command test.version with jid 20220208223523884137
2008 2022-02-08 15:35:23,890 [salt.master      :2453][DEBUG   ][13576] Published command details {'fun': 'test.version', 'arg': [], 'tgt': 'mutts:rex:age:*', 'jid': '20220208223523884137', 'ret': '', 'tgt_     type': 'pillar', 'user': 'sudo_david'}
```

**Comment by dmurphy18** [comment] 2022-02-28 16:22
@ari Closing this since no additional information provided.  Please re-open if more information on how to reproduce this is forth-coming.

**Closed by dmurphy18** 2022-02-28 16:22 UTC
Labels: Bug, cannot-reproduce, severity-high, info-needed, Phosphorus v3005.0

**Comment by sabedevops** [comment] 2022-05-12 16:36
@dmurphy18 I believe we're seeing the same issue. In our case, events are as follows:

1) Minion comes online and salt key is auto accepted by master
2) Minion fails to run highstate (for various reasons)
3) Minion is deleted or turned off (for various reasons)
4) Minion key has not been reaped
5) No `/var/cache/salt/master/minion/[minion_id]` directory was ever populated with `data.p`
6) No `salt -I "my_pillar:*" test.ping` nor any `salt -G 'my_grain:* ' test.ping` can succeed.

**Comment by dmurphy18** [comment] 2022-05-12 17:05
@sabedevops This issue is closed, if you are having an issue please consider opening a new issue and provide details on versions of Salt, and steps to reproduce the issue. The '**_various reasons_**' could contain a mine of information on some issue occurring which is preventing your intended operation. 

Note, in the original issue I was unable to reproduce the problem, probably due to an inherent refresh occurring but was never able to confirm with the originator of the issue.
