### ISSUE TITLE
"Cannot allocate memory" error everywhere on CI

### ISSUE THREAD

**Issue by htch** [saltstack/salt#25822] opened 2015-07-29 07:55 UTC
All tests on jenkins seem to fail due to "Cannot allocate memory" error, it cannot be right. For example [1](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/6604/testReport/integration.shell.matcher/MatchTest/test_compound/), [2](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/6604/testReport/integration.shell.matcher/MatchTest/test_glob/), [3](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/6604/testReport/integration.shell.matcher/MatchTest/test_grain/).

**Comment by jfindlay** [comment] 2015-07-29 21:10
@htch, thanks for the report.  We have been trying to narrow down on why this is happening for the past few days.  It may be one of a few different things in our testing infrastructure.

**Comment by htch** [comment] 2015-07-30 14:17
@jfindlay Glad to be of help.

**Comment by cachedout** [comment] 2015-08-06 22:04
@jfindlay Has this problem been resolved? I haven't seen it recently.

**Comment by jtand** [comment] 2015-08-06 22:30
@cachedout It seems to be intermittent. I'm not sure how to reproduce it quite yet. Still looking into it.

**Comment by cachedout** [comment] 2015-11-08 06:58
We have this problem resolved. Closing issue.

**Closed by cachedout** 2015-11-08 06:58 UTC
Labels: Bug, Core, High Severity, P3, Tests
