### ISSUE TITLE
git.latest "Not a valid commit name"

### ISSUE THREAD

**Issue by viict** [saltstack/salt#37551] opened 2016-11-08 16:12 UTC
### Description of Issue/Question

We've published a repository on our client server, after a few changes we made a "merge request" and then we ran again the state, it failed with "Not a valid commit name 73fd02afa3e1407912a95fb729208248cccc2015"

After a few hours trying to figure out the problem I ran a `git pull` and it worked fine. I think the problem was that we merged a few branches and publishing master it didn't not find the commits that were parent of the merge 73fd02afa3e1407912a95fb729208248cccc2015 which got updated when I ran `git pull`:

```bash
root@server-123:/# ssh-agent bash -c 'ssh-add /srv/deploy.key; git pull'
Identity added: /srv/deploy.key (/srv/deploy.key)
remote: Counting objects: 67, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 67 (delta 52), reused 0 (delta 0)
Unpacking objects: 100% (67/67), done.
From repository-url
   5c56e42..73fd02a  master     -> origin/master
   1343a4d..8fd1e4c  dev        -> origin/dev
   40984d3..fa82d0c  hml        -> origin/hml
Updating 5c56e42..73fd02a
```

I don't quite understand how git.latest works, but, if a pull worked fine without conflicts why git.latest did not?

### Setup

```bash
deploy_git_repository:
  git.latest:
    - name: repository.git
    - target: /efs/www/system
    - branch: master
    - force_clone: True
    - force_reset: True
    - force_fetch: True
    - force_reset: True
    - identity: /srv/deploy.key
```

I've also set:
>    - force_fetch: True
>    - force_reset: True

Nothing changed.

### Steps to Reproduce Issue

> CommandExecutionError: Command 'git merge-base 5c56e42d3e715d3eb7c5d7ac6db500c5e3191f7b 73fd02afa3e1407912a95fb729208248cccc2015' failed: > fatal: Not a valid commit name 73fd02afa3e1407912a95fb729208248cccc2015
> 2016-11-08 15:45:57,601 [salt.state       ][ERROR   ][3322] fatal: Not a valid commit name 73fd02afa3e1407912a95fb729208248cccc2015

#### Master

Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-92-generic
         system: Linux
        version: Ubuntu 14.04 trusty

#### Minion

Minion is running a Ubuntu 12.04 and cannot be updated for now.

**Comment by Ch3LL** [comment] 2016-11-08 19:57
ping @terminalmage would you mind answering @viict 's questions about git.latest? 

Thanks

**Comment by terminalmage** [comment] 2016-11-08 20:18
This could be an edge case due to Ubuntu 12.04 having an older version of git which does not have the ``--is-ancestor`` flag. We manually check for the ancestor in those versions, and we may be attempting this before we fetch, thus leading to this error because that commit hasn't been fetched yet. I'll investigate further.

**Comment by terminalmage** [comment] 2016-11-08 23:02
Yep, that is exactly what it was. The good news is that this was fixed in 2016.3.3 and remains working in the head of the 2016.3 release branch. You can see for yourself using a docker image I created. In it, I created a local bare repo at ``/root/repo``, ran a git.latest state once, then pushed to the repo at ``/root/repo`` (so that the ``target`` dir doesn't yet have the latest commit fetched).

Just use a clone of the salt source code repository and do a ``git checkout v2016.3.2``, then run the following command:

```
sudo docker run --rm -v ~/git/salt/main:/testing terminalmage/salt-ubuntu12-git:issue37551 salt-call --local -l debug state.single git.latest name=file:///root/repo target=/tmp/foo
```

``~/git/salt/main`` should be replaced with the path where the repo was cloned.

The command should reproduce the same error you experienced. Next, checkout the head of the 2016.3 branch in the clone and repeat the same ``docker run`` command, and you'll see it succeed.

This could still use an integration test, so I'll work to add one.

My console log from my testing is as follows:

```
(git) 96b8b9a8  2016.3 [upstream/2016.3] (3 stashed)
erik v(saltdev) ~/git/salt/main                                          [16:48:39]
(⌐■_■) % git checkout v2016.3.2
Note: checking out 'v2016.3.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 721e6dc... Merge pull request #34988 from rallytime/release-notes-update
(git) 721e6dcc  v2016.3.2 (3 stashed)
erik v(saltdev) ~/git/salt/main                                          [16:48:46]
(⌐■_■) % sudo docker run --rm -v ~/git/salt/main:/testing terminalmage/salt-ubuntu12-git:issue37551 salt-call --local -l debug state.single git.latest name=file:///root/repo target=/tmp/foo
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: e5f1f0d8a271
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.single
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded git.version
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command ['git', '--version'] in directory '/root'
[DEBUG   ] stdout: git version 1.7.9.5
[DEBUG   ] LazyLoaded git.latest
[INFO    ] Running state [file:///root/repo] at time 22:48:58.264021
[INFO    ] Executing state git.latest for file:///root/repo
[INFO    ] Checking remote revision for file:///root/repo
[INFO    ] Executing command ['git', 'ls-remote', 'file:///root/repo'] in directory'/root'
[DEBUG   ] stdout: 752d2d6fee20f48ea549947d638a22a4da4349a3     HEAD
752d2d6fee20f48ea549947d638a22a4da4349a3        refs/heads/master
[INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/heads/'] in directory '/tmp/foo'
[DEBUG   ] stdout: master
[INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/tags/'] in directory '/tmp/foo'
[INFO    ] Checking local revision for /tmp/foo
[INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] in directory '/tmp/foo'
[DEBUG   ] stdout: fe64ea81830758d8428eefe2d672971851807e00
[INFO    ] Checking local branch for /tmp/foo
[INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'HEAD'] in directory '/tmp/foo'
[DEBUG   ] stdout: master
[INFO    ] Executing command ['git', 'remote', '--verbose'] in directory '/tmp/foo'
[DEBUG   ] stdout: origin       file:///root/repo (fetch)
origin  file:///root/repo (push)
[INFO    ] Executing command ['git', 'diff', 'HEAD'] in directory '/tmp/foo'
[INFO    ] Executing command ['git', 'rev-parse', '752d2d6fee20f48ea549947d638a22a4da4349a3^{commit}'] in directory '/tmp/foo'
[DEBUG   ] stdout: 752d2d6fee20f48ea549947d638a22a4da4349a3^{commit}
[DEBUG   ] stderr: fatal: ambiguous argument '752d2d6fee20f48ea549947d638a22a4da4349a3^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
[DEBUG   ] retcode: 128
[INFO    ] Executing command ['git', 'rev-parse', '--verify', 'fe64ea81830758d8428eefe2d672971851807e00'] in directory '/tmp/foo'
[DEBUG   ] stdout: fe64ea81830758d8428eefe2d672971851807e00
[INFO    ] Executing command ['git', 'merge-base', 'fe64ea81830758d8428eefe2d672971851807e00', '752d2d6fee20f48ea549947d638a22a4da4349a3'] in directory '/tmp/foo'
[DEBUG   ] stderr: fatal: Not a valid commit name 752d2d6fee20f48ea549947d638a22a4da4349a3
[DEBUG   ] retcode: 128
[ERROR   ] Unexpected exception in git.latest state
Traceback (most recent call last):
  File "/testing/salt/states/git.py", line 882, in latest
    ignore_retcode=True)
  File "/testing/salt/modules/git.py", line 2537, in merge_base
    ignore_retcode=ignore_retcode) == first_commit
  File "/testing/salt/modules/git.py", line 2560, in merge_base
    failhard=False if is_ancestor else True)
  File "/testing/salt/modules/git.py", line 299, in _git_run
    raise CommandExecutionError(msg)
CommandExecutionError: Command 'git merge-base fe64ea81830758d8428eefe2d672971851807e00 752d2d6fee20f48ea549947d638a22a4da4349a3' failed: fatal: Not a valid commit name 752d2d6fee20f48ea549947d638a22a4da4349a3
[ERROR   ] fatal: Not a valid commit name 752d2d6fee20f48ea549947d638a22a4da4349a3
[INFO    ] Completed state [file:///root/repo] at time 22:48:58.409633 duration_in_ms=145.612
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: file:///root/repo
    Function: git.latest
      Result: False
     Comment: fatal: Not a valid commit name 752d2d6fee20f48ea549947d638a22a4da4349a3
     Started: 22:48:58.264021
    Duration: 145.612 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
(git) 721e6dcc  v2016.3.2 (3 stashed)
erik v(saltdev) ~/git/salt/main                                          [16:48:59]
(⌐■_■) % git checkout 2016.3
Previous HEAD position was 721e6dc... Merge pull request #34988 from rallytime/release-notes-update
Switched to branch '2016.3'
Your branch is up-to-date with 'upstream/2016.3'.
(git) 96b8b9a8  2016.3 [upstream/2016.3] (3 stashed)
erik v(saltdev) ~/git/salt/main                                          [16:49:08]
(⌐■_■) % sudo docker run --rm -v ~/git/salt/main:/testing terminalmage/salt-ubuntu12-git:issue37551 salt-call --local -l debug state.single git.latest name=file:///root/repo target=/tmp/foo
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: e5f1f0d8a271
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Missing configuration file: /etc/salt/minion
[INFO    ] Could not determine init system from command line: (python /testing/scripts/salt-call --local -l debug state.single git.latest name=file:///root/repo target=/tmp/foo)
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.single
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded git.version
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command ['git', '--version'] in directory '/root'
[DEBUG   ] stdout: git version 1.7.9.5
[DEBUG   ] LazyLoaded git.latest
[INFO    ] Running state [file:///root/repo] at time 22:49:25.094833
[INFO    ] Executing state git.latest for file:///root/repo
[INFO    ] Checking remote revision for file:///root/repo
[INFO    ] Executing command ['git', 'ls-remote', 'file:///root/repo'] in directory'/root'
[DEBUG   ] stdout: 752d2d6fee20f48ea549947d638a22a4da4349a3     HEAD
752d2d6fee20f48ea549947d638a22a4da4349a3        refs/heads/master
[INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/heads/'] in directory '/tmp/foo'
[DEBUG   ] stdout: master
[INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/tags/'] in directory '/tmp/foo'
[INFO    ] Checking local revision for /tmp/foo
[INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] in directory '/tmp/foo'
[DEBUG   ] stdout: fe64ea81830758d8428eefe2d672971851807e00
[INFO    ] Checking local branch for /tmp/foo
[INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'HEAD'] in directory '/tmp/foo'
[DEBUG   ] stdout: master
[INFO    ] Executing command ['git', 'remote', '--verbose'] in directory '/tmp/foo'
[DEBUG   ] stdout: origin       file:///root/repo (fetch)
origin  file:///root/repo (push)
[INFO    ] Executing command ['git', 'diff', 'HEAD'] in directory '/tmp/foo'
[INFO    ] Executing command ['git', 'rev-parse', '752d2d6fee20f48ea549947d638a22a4da4349a3^{commit}'] in directory '/tmp/foo'
[DEBUG   ] stdout: 752d2d6fee20f48ea549947d638a22a4da4349a3^{commit}
[DEBUG   ] stderr: fatal: ambiguous argument '752d2d6fee20f48ea549947d638a22a4da4349a3^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
[DEBUG   ] retcode: 128
[INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'master@{upstream}'] in directory '/tmp/foo'
[DEBUG   ] stdout: origin/master
[INFO    ] Executing command ['git', 'fetch', 'origin', 'refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'] in directory '/tmp/foo'
[DEBUG   ] stdout: From file:///root/repo
   fe64ea8..752d2d6  master     -> origin/master
[INFO    ] Executing command ['git', 'rev-parse', '752d2d6fee20f48ea549947d638a22a4da4349a3^{commit}'] in directory '/tmp/foo'
[DEBUG   ] stdout: 752d2d6fee20f48ea549947d638a22a4da4349a3
[INFO    ] Executing command ['git', 'rev-parse', '--verify', 'fe64ea81830758d8428eefe2d672971851807e00'] in directory '/tmp/foo'
[DEBUG   ] stdout: fe64ea81830758d8428eefe2d672971851807e00
[INFO    ] Executing command ['git', 'merge-base', 'fe64ea81830758d8428eefe2d672971851807e00', '752d2d6fee20f48ea549947d638a22a4da4349a3'] in directory '/tmp/foo'
[DEBUG   ] stdout: fe64ea81830758d8428eefe2d672971851807e00
[INFO    ] Executing command ['git', 'symbolic-ref', '--quiet', 'HEAD'] in directory '/tmp/foo'
[DEBUG   ] stdout: refs/heads/master
[INFO    ] Executing command ['git', 'merge', '752d2d6fee20f48ea549947d638a22a4da4349a3'] in directory '/tmp/foo'
[DEBUG   ] stdout: Updating fe64ea8..752d2d6
Fast-forward
 foo.txt |    2 ++
 1 file changed, 2 insertions(+)
[INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] in directory '/tmp/foo'
[DEBUG   ] stdout: 752d2d6fee20f48ea549947d638a22a4da4349a3
[INFO    ] Repository /tmp/foo updated: fe64ea81830758d8428eefe2d672971851807e00 =>752d2d6fee20f48ea549947d638a22a4da4349a3
[INFO    ] Made the following changes:
'revision' changed from 'fe64ea81830758d8428eefe2d672971851807e00' to '752d2d6fee20f48ea549947d638a22a4da4349a3'

[INFO    ] Completed state [file:///root/repo] at time 22:49:25.336355 duration_in_ms=241.522
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: file:///root/repo
    Function: git.latest
      Result: True
     Comment: file:///root/repo was fetched, resulting in updated refs. Repository was fast-forwarded to remote HEAD (752d2d6).
     Started: 22:49:25.094833
    Duration: 241.522 ms
     Changes:
              ----------
              revision:
                  ----------
                  new:
                      752d2d6fee20f48ea549947d638a22a4da4349a3
                  old:
                      fe64ea81830758d8428eefe2d672971851807e00

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 241.522 ms
```

**Comment by terminalmage** [comment] 2016-11-09 04:42
Test added in https://github.com/saltstack/salt/pull/37571.

**Comment by terminalmage** [comment] 2016-11-09 04:44
Based on the fact that this is already fixed, and this test has been added to ensure this does not regress, I'm going to close this.

**Closed by terminalmage** 2016-11-09 04:44 UTC
Labels: Bug, Fixed Pending Verification, State Module, TEAM Core

**Comment by viict** [comment] 2016-11-09 15:58
@terminalmage i've updated my salt-master and try to run a new git.latest, I agree it worked in your test case (as I tested it myself) but now I think it is just saying the repository is up to date. Unless it did something different from your test case.

I've noticed three things:
1. A new `git pull` to force the update gives me this result, which seems to not reference a remote url for the branch it checked out:
```base
root@server-123:/# ssh-agent bash -c 'ssh-add /srv/deploy.key; git pull'
Identity added: /srv/deploy.key (/srv/deploy.key)
remote: Counting objects: 30, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 30 (delta 11), reused 20 (delta 8)
Unpacking objects: 100% (30/30), done.
From repository-url
 * [new branch]      new-branch-1 -> origin/new-branch-1
 * [new branch]      new-branch-2 -> origin/new-branch-2
   3e2e5e0..9eba44a  dev        -> origin/dev
   55b7b00..20ed474  hml        -> origin/hml
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> hml
```
2. Setting the upstream at the branch did not solved the issue as I found this to be quite strange:
```base
root@server-123:/# salt-call state.apply state.applied.for.the.server
local:
----------
          ID: deploy_git_repository_uri
    Function: git.latest
        Name: repository-url
      Result: True
     Comment: Repository /repository/path is up-to-date
     Started: 15:47:46.979824
    Duration: 8009.828 ms
     Changes:   
```
3. After a few other similar tests I ended up updating by hand.
```bash
root@server-123:/repository/path# ssh-agent bash -c 'ssh-add /srv/deploy.key; git pull'
Identity added: /srv/deploy.key (/srv/deploy.key)
From repository-url
 * branch            hml        -> FETCH_HEAD
Updating f1a9e99..20ed474
Fast-forward
 .gitignore    |  2 ++
 .htaccess     | 12 ++++++++++++
 wp-config.php | 35 +++++++++++++++++++++--------------
 3 files changed, 35 insertions(+), 14 deletions(-)
 create mode 100644 .gitignore
```

So, should I try something else? Should I create a new issue with this behavior?

**Comment by terminalmage** [comment] 2016-11-09 17:37
Can you explain what you're doing with the ``git pull`` there? I don't understand the point of it. Are you running a ``git pull`` on the target directory (i.e. ``/efs/www/system`` or whatever it is)? If so, then I'm not sure why an "up-to-date" message is unexpected.

**Comment by viict** [comment] 2016-11-09 18:04
@terminalmage well, I want to update it, git.latest tells me it's already updated when it's not, and I confirmed it with the `git pull` updating the repository.

**Comment by terminalmage** [comment] 2016-11-09 18:21
Based on your SLS file, you're not specifying the revision. In these cases ``git.latest`` assumes you want to keep the local clone up-to-date with the remote HEAD, and ensures that no upstream tracking branch is set. So this is expected behavior.

If you want an upstream tracking branch, then you will need to set ``rev`` to point to the branch you wish to follow.

**Comment by viict** [comment] 2016-11-09 18:30
@terminalmage but, as docs says:
> Changed in version 2015.8.0: If not specified, rev now defaults to the remote repository's HEAD.

Doesn't it means that it should keep up with the remote repository instead of the local? As I don't specify the revision.

If not, what should I do to keep the local repository up with the remote one?

**Comment by terminalmage** [comment] 2016-11-09 19:13
The default value for ``rev`` is HEAD. In git, HEAD is the latest revision. So if you don't specify ``rev`` then you will follow the latest revision. But when you do this, Salt will also not set or modify the upstream tracking branch. I misspoke earlier, it doesn't "ensure that no upstream tracking branch is set", it just doesn't change upstream. HEAD isn't a branch. It's a symbolic ref, it could be pointing to anything, so if you're following HEAD then there is no reason for Salt to manage or set an upstream branch.

The docs do show that ``HEAD`` is the default revision, I just didn't think it was necessary to also mention that HEAD is the latest revision on the remote repository. I can update the documentation, I guess.

**Comment by viict** [comment] 2016-11-09 19:51
@terminalmage well, sorry for the stupidity but, if HEAD is the latest revision and the `branch` property is set to "hml" shouldn't it follow the remote branch for the latest revision? Also, if I'm not understanding the way git.latest works, could you explain it a bit more?

From what I've understand, I don't want to set a specific revision for each publication in my staging environment, just doesn't make sense for me I want it to always follow the latest remote branch revision.

So if that's the expected behaviour I understand that I should change the way I'm doing it, but, if `force_head` is by default `True` and git.latest doesn't track the remote branch, how would I update the repository for the latest commit as we don't have a `git.pull` state for example?

**Comment by terminalmage** [comment] 2016-11-09 20:11
I think you're misreading the docs. The ``branch`` parameter simply sets the local branch to use. If it's not specified, then the ``git.latest`` state just uses the default remote branch that it gets when the repo is cloned.

The ``rev`` parameter specifies the remote revision to follow. If you want to track the ``master`` branch on the remote repo, then set ``rev`` to ``master`` and ``git.latest`` will try to keep the local clone up-to-date with the latest commit in the ``master`` branch.

Also, there is no ``force_head`` argument. Are you talking about ``update_head``? That argument is only meant to be used for the rare instances in which the user wants to know that the remote revision has changed, but do not want to update the local HEAD. You probably don't need to consider this argument.

Keep in mind, ``git.latest`` will happily keep your local clone up-to-date with the latest commit in the remote repository if you just leave ``rev`` set to its default of ``HEAD``. It just won't set a tracking branch, because, as I've already explained, HEAD is a symbolic ref, it is not necessarily a branch. It is possible to detach the remote HEAD and point it at a tag. And you can't set upstream to a tag:

```
% git branch --set-upstream-to=v2016.3.0
fatal: Cannot setup tracking information; starting point 'v2016.3.0' is not a branch.
```

So, when ``rev`` is ``HEAD`` we simply ignore setting an upstream branch. Does this make sense now? Keep in mind that there is _nothing_ stopping you from pulling if you desire to do so. You can still manually run ``git pull origin master``.  Using ``git pull`` only works when there is an upstream branch.

**Comment by viict** [comment] 2016-11-09 20:12
@terminalmage just as a note, if the repository doesn't change the branch (we checked it out on master branch) ran the `git.latest` over it and it updated correctly, is there any kind of difference?

```base
ID: deploy_git_production
   Function: git.latest
       Name: repository-url
     Result: True
    Comment: repository-url was fetched, resulting in updated refs. Repository was fast-forwarded to remote HEAD (6d30405).
    Started: 20:03:46.744393
   Duration: 69760.841 ms
    Changes:  
             ----------
             revision:
                 ----------
                 new:
                     6d30405cad11a75a9df82917dca13960867372f0
                 old:
                     fa8d31b14e449a6983c7b8c65c13f5bdc33489b5
```

**Comment by viict** [comment] 2016-11-09 20:39
You're correct, I was talking about `update_head`.

And now I understood! Haha sorry. I saw that it worked fine on our master branch (which is default). Setting just `branch` did not work as we expected and after your explanation and setting `rev` to `hml` it worked fine! I did not undertood from the docs that I should set both to to keep track of a different branch, instead I set branch to the one I wanted and expected that HEAD would be always the same as the remote one, thanks for the clarification and maybe a clarification on the docs would be nice, unless I'm the only one confused haha.

```bash
 ID: deploy_git_repository_hml
   Function: git.latest
       Name: repository-url
     Result: True
    Comment: repository-url was fetched, resulting in updated refs. *Tracking branch was set to origin/hml. Repository was fast-forwarded to origin/hml* (f459163).
    Started: 20:29:17.424365                                                                                                                                       Duration: 26474.77 ms
Changes:
----------                                                                                                                                                      revision:                                                                                                                                                     ----------                                                                                                                                                                       new:
                     f459163d2465be3046ccbd1cc06ec06d1a31503d
                 old:
                     3c3a88ab3e2a35a3de8ca83275eef3797e62f590
```

**Comment by terminalmage** [comment] 2016-11-10 17:27
I opened https://github.com/saltstack/salt/pull/37604 which contains several updates to the ``git.latest`` documentation, including a more thorough explanation of the ``branch`` parameter.
