### ISSUE TITLE
Saltstack on archlinux

### ISSUE THREAD

**Issue by castroflavio** [saltstack/salt#22431] opened 2015-04-07 18:57 UTC
Hi I'm trying to install salt on archlinux, but I'm failing to run it because of the ioflo.base library.

The error I'm getting is:

Apr 07 14:39:17 b827ebd4c131 salt-master[249]: importlib.import_module(".{0}".format(m), package='raet.road')
Apr 07 14:39:18 b827ebd4c131 salt-master[249]: File "/usr/lib/python2.7/importlib/__init__.py", line 37, in ...dule
Apr 07 14:39:18 b827ebd4c131 salt-master[249]: __import__(name)
Apr 07 14:39:18 b827ebd4c131 salt-master[249]: File "/usr/lib/python2.7/site-packages/raet/road/stacking.py"...ule>
Apr 07 14:39:18 b827ebd4c131 salt-master[249]: from ioflo.base import nonblocking
Apr 07 14:39:18 b827ebd4c131 salt-master[249]: ImportError: cannot import name nonblocking

**Comment by frnco** [comment] 2015-04-07 20:51
I was trying `salt-raet` from `pacman` earlier today and had the same problem. The good news is: If you install `salt-git` from `AUR` it is working flawlessly. As soon as the patch is approved by Arch it will be available.

Just a disclaimer: I'm not a developer for Salt. Actually I started using it last friday.
But I just hit the same problem you did, and considering you're also using Arch and GitHub, I though I should drop by to let you know of the way around the issue. :D

**Comment by techhat** [comment] 2015-04-07 20:52
Ping @gtmanfred.

**Comment by gtmanfred** [comment] 2015-04-07 21:15
Has anyone double checked on 2014.7.4 in community testing?

**Comment by frnco** [comment] 2015-04-07 21:31
@gtmanfred not sure I understand what you meant. I didn't check anywhere, just searched a bit, found reports on this and other similar issues and  used the `salt-git` because it was easier.

But from my first investigations, dependencies on `pacman -S python2-m2crypto` and `base-devel` could help, especially considering Digital Ocean has no Arch Linux, and the script to convert Debian to Arch doesn't install these packages (And possibly many others), plus I'm not 100% sure if `zeromq` is listed as a dependency...

And yeah, I used pacman and nope, it didn't install many dependencies. But as I said, I was in a ridiculously 'bare' server since I like to play on DO Droplets. After getting to this point that I decided to go with `salt-git` because it was too much trouble, but I had already installed some dependencies so I'm not sure where I was at.

**Comment by gtmanfred** [comment] 2015-04-07 22:02
There is a new version of the latest stable release in the [community-testing] repository.  2014.7.4, which should be announced anyday now.  If someone can test that and see if they get the same behaviour, that would be awesome, because I have been unable to replicate what you are seeing.

**Comment by frnco** [comment] 2015-04-08 02:12
Feeling helpful today. :D

First, step by step how I replicated it exactly right:

- Created a new Droplet on Digital Ocean, Debian machine (7.0 Wheezy x64);
- Use `haveged` for generating entropy (Probably doesn't matter, but I'm being thorough);
- Wait untill it finishes/reboots, wait a few seconds/minutes and ssh again;
- You're on Arch, as seen here.

Release:

        [root@SaltTesting ~]# cat /etc/os-release 
        NAME="Arch Linux"
        ID=arch
        PRETTY_NAME="Arch Linux"
        ANSI_COLOR="0;36"
        HOME_URL="https://www.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"

Great! Let's continue:
- Enable `Community Testing` repository on `/etc/pacman.conf`.
- Update Arch. I ask to re-check everything with `pacman -Syyuu`. Nothing to do.
- Install `salt-raet` from official repo, community testing (`pacman -S salt-raet`);
- Try to start salt-master with `systemctl start salt-master.service`, aaaaand...

**Error!**

        [root@SaltTesting ~]# systemctl start salt-master.service
        Job for salt-master.service failed. See "systemctl status salt-master.service" and "journalctl -xe" for details.

Let's get the status with `systemctl status salt-master.service -l`:

        [root@SaltTesting ~]# systemctl status salt-master.service -l
        * salt-master.service - The Salt Master Server
           Loaded: loaded (/usr/lib/systemd/system/salt-master.service; disabled; vendor preset: disabled)
           Active: failed (Result: exit-code) since Wed 2015-04-08 01:32:02 UTC; 2min 38s ago
          Process: 1409 ExecStart=/usr/bin/salt-master (code=exited, status=1/FAILURE)
         Main PID: 1409 (code=exited, status=1/FAILURE)

        Apr 08 01:32:02 SaltTesting salt-master[1409]: importlib.import_module(".{0}".format(m), package='raet.road')
        Apr 08 01:32:02 SaltTesting salt-master[1409]: File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        Apr 08 01:32:02 SaltTesting salt-master[1409]: __import__(name)
        Apr 08 01:32:02 SaltTesting salt-master[1409]: File "/usr/lib/python2.7/site-packages/raet/road/stacking.py", line 27, in <module>
        Apr 08 01:32:02 SaltTesting salt-master[1409]: from ioflo.base import nonblocking
        Apr 08 01:32:02 SaltTesting salt-master[1409]: ImportError: cannot import name nonblocking
        Apr 08 01:32:02 SaltTesting systemd[1]: salt-master.service: main process exited, code=exited, status=1/FAILURE
        Apr 08 01:32:02 SaltTesting systemd[1]: Failed to start The Salt Master Server.
        Apr 08 01:32:02 SaltTesting systemd[1]: Unit salt-master.service entered failed state.
        Apr 08 01:32:02 SaltTesting systemd[1]: salt-master.service failed.


And then, if you follow my original steps, you try searching for it like a devil, and you even try `salt-zmq` before completely giving up and going for `salt-git`...

Reproduced with `v 7.4-1`, as can be seen here:

        [root@SaltTesting ~]# pacman -S salt-raet  
        warning: salt-raet-2014.7.4-1 is up to date -- reinstalling
        resolving dependencies...
        looking for conflicting packages...

        Packages (1) salt-raet-2014.7.4-1

        Total Installed Size:  21.16 MiB
        Net Upgrade Size:       0.00 MiB


Just for the sake of being sure, tried from testing too (Removed with `pacman -R salt-raet`, edited `/etc/pacman.conf`, did `systemctl daemon-reload` and tried again). Same thing. I won't post the error since it's exactly the same, but here goes the version check:

        [root@SaltTesting ~]# pacman -S salt-raet
        warning: salt-raet-2014.7.2-1 is up to date -- reinstalling
        resolving dependencies...
        looking for conflicting packages...

        Packages (1) salt-raet-2014.7.2-1

        Total Installed Size:  21.01 MiB
        Net Upgrade Size:       0.00 MiB



This apparently ONLY happens in Digital Ocean's Debian-Wheezy-x64-turned-Arch-using-this-script:
https://github.com/gh2o/digitalocean-debian-to-arch
(Ok, maybe Wheezy x32 will have the same problem, maybe even other Debians-turned-Arch do, but you get the idea. I didn't have this issue on AWS and they don't even have Arch, I just picked a community ami, so there you go.)


The said script basically replaces a lot of stuff, to make Digital Ocean's Debian behave as closely to an Arch as possible. But it also leaves the system with close to nothing installed in it. :D

Which leads me to believe it's either a dependency problem or a custom-kernel-thinggye or something like that. Considering `salt-git` from AUR works fine,  and I believe it also uses `raet`, I think we can just point people with similar problems to `salt-git` on AUR. I would suggest they use `yaourt` since it is pretty easy to install, and it even has a repository you can just drop into `/etc/pacman.conf` to install it using `pacman -S yaourt`.

Doing any more than this feels like a waste to me, if `salt-git` works people shut just use that. If you want *super stable stuff* you probably shouldn't even be using Arch Linux, much less a custom modified machine... But of course, if you guys need any help debugging, more info or ssh access to a server with this problem, just ask. I will keep this Droplet running for a few days (Maybe longer, depends on my mood =D), or until somebody closes this issue, whichever comes first.

**Comment by gtmanfred** [comment] 2015-04-08 02:50
@techhat you can close this. Nothing is really going to be solved here.  If it comes up again, this should be opened in the archlinux bug tracker.  But it looks like it is just this obscure case which isn't really a supported install.

@frnco thanks for writing that up!

**Comment by frnco** [comment] 2015-04-08 14:55
Just taking the chance to update: Didn't get to finish a working BSD-to-Arch install on DO, and not gonna invest more time in at as it is too much of a hack and too hard to pull through. Using Digital Ocean for Arch Droplets is unfeasible at the moment, and nobody in their right minds should support it.

**Closed** 2015-04-08 18:29 UTC
