### ISSUE TITLE
salt.loaded.int.module.sysrc.__virtual__() is wrongly returning `None`

### ISSUE THREAD

**Issue by mriedmann** [saltstack/salt#19524] opened 2015-01-08 17:10 UTC
I'am using Salt on 'CentOS 7'. After installing some python-libs, especially 'docker-py' this warning has started to pop up after each 'salt-call'-call:

    [WARNING ] salt.loaded.int.module.sysrc.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'sysrc', please fix this.

ATM I haven't recognized any effects unless this annoying message.

Can someone reproduce this or please tell me what I'am doing wrong?

```
salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```
```
pip list
Babel (0.9.6)
backports.ssl-match-hostname (3.4.0.2)
blivet (0.18.34)
chardet (2.0.1)
configobj (4.7.2)
coverage (3.6b3)
decorator (3.4.0)
docker-py (0.5.0)
fros (1.0)
iniparse (0.4)
IPy (0.75)
Jinja2 (2.7.2)
kitchen (1.1.1)
langtable (0.0.13)
M2Crypto (0.21.1)
MarkupSafe (0.11)
msgpack-python (0.4.2)
pycrypto (2.6.1)
pycurl (7.19.0)
pygobject (3.8.2)
pygpgme (0.3)
pykickstart (1.99.43.10)
pyliblzma (0.5.3)
pyparted (3.9)
python-meh (0.25)
python-nss (0.14.0)
pytz (2012d)
pyudev (0.15)
pyxattr (0.5.1)
PyYAML (3.10)
pyzmq (14.3.1)
requests (2.5.1)
salt (2014.7.0-6899-g1f39a65)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
urlgrabber (3.10)
urllib3 (1.5)
websocket-client (0.23.0)
wsgiref (0.1.2)
yum-metadata-parser (1.1.4)
```

**Comment by basepi** [comment] 2015-01-08 21:54
What was your install method? That module is not present at all in that version of salt, so I'm wondering if there's something wrong with the versions report or something.

**Comment by mriedmann** [comment] 2015-01-09 13:18
Thanks for your quick reply on this quite unurgent matter ;)
In the moment its really an aesthetical problem.

I ran the bootstrap scripts on a fresh CentOS7 minimal install (KVM virtualized).

```
curl -L https://bootstrap.saltstack.com -o /tmp/install_salt.sh
sh /tmp/install_salt.sh -P -g https://github.com/saltstack/salt.git git develop
```

Very strange. I also use Salt-Formula for minion- and master-config.

Is there a way to uninstall/deactivate this module to stop this messages?

**Comment by basepi** [comment] 2015-01-09 21:23
Ah, you installed from `develop`. It's still quite strange that the version is not reporting a specific hash, but that makes much more sense from devleop.

And yes, if you were to just delete the .py file from within the salt/modules directory in the installation location the warning would immediately go away. =)

**Comment by basepi** [comment] 2015-01-09 21:25
I actually think this has been fixed since you installed from `develop`, as the latest version of `develop` appears to follow correct guidelines for the `__virtual__` function. So I'm going to go ahead and close this one -- if you update to a later version and the problem is still present, feel free to comment and we can re-open.

**Closed by basepi** 2015-01-09 21:25 UTC
Labels: Bug, Low Severity, Low-Hanging Fruit
