### ISSUE TITLE
integration tests are failing on py2 on mac

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#51853] opened 2019-02-26 22:16 UTC
https://jenkinsci.saltstack.com/job/2017.7/job/salt-mac-sierra-py2/104/testReport/

Looking at most of these failures it looks like somehow return values are True/False instead of something iterable. I'll need to take a look at this - there's nothing obvious from the messages, and it's happening only on the macs :suspect:

**Comment by waynew** [comment] 2019-05-09 17:39
Looks like that issue is no longer the case - the current failure will be solved by https://github.com/saltstack/salt/pull/52754

**Comment by waynew** [comment] 2019-05-09 17:43
Original link is broken now but https://jenkinsci.saltstack.com/job/2017.7/job/salt-mac-sierra-py2/ is still failing.

https://jenkinsci.saltstack.com/job/2018.3/job/salt-mac-highsierra-py2/91/console is failing with a different problem:

```
00:40:16 [CPU:46.8%|MEM:77.6%]  ... 23:40:16,451 [salt.loader.localhost.int.module.cmdmod    :778 ][ERROR   ] Command '/bin/false' failed with return code: 127
00:40:16 23:40:16,453 [salt.loader.localhost.int.module.cmdmod    :780 ][ERROR   ] stdout: /bin/sh: /bin/false: No such file or directory
00:40:16 23:40:16,454 [salt.loader.localhost.int.module.cmdmod    :784 ][ERROR   ] retcode: 127
00:40:17 23:40:16,455 [salt.loader.localhost.int.module.cmdmod    :1112][ERROR   ] Command '/bin/false' failed with return code: 127
00:40:17 23:40:16,456 [salt.loader.localhost.int.module.cmdmod    :1117][ERROR   ] output: /bin/sh: /bin/false: No such file or directory
00:40:17 [ERROR   ] {u'ret': {u'minion': u'/bin/sh: /bin/false: No such file or directory'}, u'out': u'highstate'}
00:40:17 23:40:16,603 [salt.state                                 :321 ][ERROR   ] {u'ret': {u'minion': u'/bin/sh: /bin/false: No such file or directory'}, u'out': u'highstate'}
00:40:17 [ERROR   ] {u'return': {u'outputter': u'highstate', u'data': {u'master': {u'salt_|-cmd.run_|-cmd.run_|-function': {u'comment': u'Running function cmd.run failed on minions: minion Function cmd.run ran on minion.', u'name': u'cmd.run', u'start_time': '23:40:16.182775', u'result': False, u'duration': 421.567, u'__run_num__': 0, u'__jid__': u'20190501234016298745', u'__sls__': u'nested-orch.inner', u'changes': {u'ret': {u'minion': u'/bin/sh: /bin/false: No such file or directory'}, u'out': u'highstate'}, u'__id__': u'cmd.run'}}}, u'retcode': 1}}
00:40:18 23:40:16,621 [salt.state                                 :321 ][ERROR   ] {u'return': {u'outputter': u'highstate', u'data': {u'master': {u'salt_|-cmd.run_|-cmd.run_|-function': {u'comment': u'Running function cmd.run failed on minions: minion Function cmd.run ran on minion.', u'name': u'cmd.run', u'start_time': '23:40:16.182775', u'result': False, u'duration': 421.567, u'__run_num__': 0, u'__jid__': u'20190501234016298745', u'__sls__': u'nested-orch.inner', u'changes': {u'ret': {u'minion': u'/bin/sh: /bin/false: No such file or directory'}, u'out': u'highstate'}, u'__id__': u'cmd.run'}}}, u'retcode': 1}}
00:40:18 ok (15.047s)
```

**Comment by waynew** [comment] 2019-05-16 16:16
Okay! Tests are running!

One of the failures already has issue(s) open. These two are still failing:

- integration.modules.test_mac_system.MacSystemModuleTest.test_get_set_subnet_name
- integration.states.test_pip_state.PipStateTest.test_46127_pip_env_vars

**Comment by waynew** [comment] 2019-05-16 20:45
Okay, I'm not sure what's up with this subnet name problem. My money is on a race condition, because I've tried several times locally and it's always worked :suspect:

**Comment by KChandrashekhar** [comment] 2019-06-26 17:13
Closing as the issue is now fixed as confirmed by @garethgreenaway

**Closed by KChandrashekhar** 2019-06-26 17:13 UTC
Labels: 2017.7.9, 2019.2.1, Test Failure
