### ISSUE TITLE
[BUG] Onedir install broken on ARM64 Linux

### ISSUE THREAD

**Issue by voidmain** [saltstack/salt#62757] opened 2022-09-26 21:03 UTC
**Description**
It appears that the Onedir install (bootstrap and manual) is broken on `ARM64` versions of Linux. Everything appears to exist in the APT repository except for `salt-common`. The file exists, but it looks like it was built with `AMD64` only.

Directory listing: https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/latest/pool/

You can see in that directory that the `salt-common` file is targeting a specific architecture rather than `all` as the other packages are.

I'm assuming that Onedir is supposed to support ARM64 but the build was messed up or something.

**Comment by OrangeDog** [comment] 2022-09-27 08:46
Related: #62664

**Comment by dmurphy18** [comment] 2022-09-27 21:51
@voidmain Sorry but for the moment onedir only supports Intel family of processors. 
As it states in the URL above 'amd64' architecture and not 'arm64'.

For the current time I can recommend the classic packaging for Ubuntu 20.04 and ARM64 support for Salt 3005, https://repo.saltproject.io/py3/ubuntu/20.04/arm64/latest

Closing this since working as designed, that is, only x86_64/amd64 is supported in onedir at the moment, but arm64 support will be coming to onedir in the future, sorry cannot give a timeframe except near future.

**Closed by dmurphy18** 2022-09-27 21:51 UTC
Labels: Bug, Packaging, expected-behavior

**Comment by boltronics** [comment] 2022-11-07 04:53
@dmurphy18 If I may, I would like to suggest that this shouldn't have been closed without at least the documentation on the [onedir upgrade page](https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#timeline-for-upgrading-to-onedir-packaging) getting updated to reflect this fact.

Also, can there please also be a firm commitment from the Salt team documented somewhere on the main site (possibly also on the onedir page), indicating that ARM64 will in fact be supported prior to non-onedir installations being dropped?

At least in my workplace, we have a mix of ARM64 and AMD64 architectures (and have in fact recently replaced most AMD64 hosts with ARM64), so this news is of particular concern.

**Comment by barbaricyawps** [comment] 2022-11-07 16:12
@dmurphy18 , sure thing. I'm working on a Salt Install Guide issue right now and I can fold that into the work I'm doing.

**Comment by boltronics** [comment] 2022-11-07 22:22
Thanks guys. Much appreciated.

**Comment by gvengel** [comment] 2022-12-01 06:27
> You can be rest assured that ARM64 will be supported in onedir in the next major release 3006.0.

Sorry, does this mean "arm64 won't be supported until 3006 is released" or "arm64 will definitely be supported by 3006 and 3005 will support it sometime before then"? In other words, given relenv is required to support onedir on arm64, will 3k6 mark the transition from tiamat to relenv? Will 3k5 be transition to relenv too, or will it just never support arm64?

We've been stuck on 3k4, since Saltstack dropped support for classic packages built for Ubuntu 22.04, but onedir packages don't support arm64. As such, you cannot install salt on Ubuntu 22.04 arm64.

Is the CI/CD used to build these packages publicly available? If support isn't forth coming, I'd like to try to get classic packages building for Ubuntu 22.04, and possibly replicate the issues with onedir on arm64.

Thanks.

**Comment by gvengel** [comment] 2022-12-02 08:32
Thanks for the comprehensive response. After poking around, I discovered the Debian 11 classic arm64 package installs without issue on Ubuntu 24.04. While not optimal from a support point of view, I think it's an acceptable hold over until 3006 ships.

**Comment by dmurphy18** [comment] 2022-12-02 16:58
@gvengel That is interesting to know that Debian 11 will work on Ubuntu 22.04 (presume 24.04 was a typo).
Tried it the amd64 and it works, need to get my Pi 4 updated so can try arm64.
Thanks for the find

**Comment by bigbigmdm** [comment] 2023-12-29 13:24
yes, 24.04 was a typo...
