### ISSUE TITLE
Diffs (-/+) Opposite Way Round on Latest Minion Version

### ISSUE THREAD

**Issue by Scholar-DG** [saltstack/salt#47536] opened 2018-05-08 11:36 UTC
When test applying a state to a minion we're seeing the differences appear the opposite way round ('-' for things that should be applied and '+' for things that should be removed).

The minion was recently updated to run on version `2018.3.0` on Ubuntu 16.04 and the master is running on the same version but on Debian 8. Since upgrading the minion these changes have occurred. Downgrading the minion to version `2017.7.5+ds-1` resolves the issue and the changes are the correct way around. Both the master and minion are using the same repo of `https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main` but in order to down grade the minion it's using the following repo `https://repo.saltstack.com/apt/ubuntu/16.04/amd64/2017.7 xenial main`.

I have attached the output of the working minion and minion with the issue.

[with_issue.txt](https://github.com/saltstack/salt/files/1983690/with_issue.txt)
[without_issue.txt](https://github.com/saltstack/salt/files/1983691/without_issue.txt)

**Minion with issue**
`ii  salt-common                         2018.3.0+ds-1
ii  salt-minion                         2018.3.0+ds-1`

**Minion without issue**
`ii  salt-common                         2017.7.5+ds-1
ii  salt-minion                         2017.7.5+ds-1`

**Master**
`ii  salt-common                    2018.3.0+ds-1
ii  salt-master                    2018.3.0+ds-1
ii  salt-minion                    2018.3.0+ds-1
ii  salt-syndic                    2018.3.0+ds-1
`

**Comment by Ch3LL** [comment] 2018-05-08 14:54
duplicate of https://github.com/saltstack/salt/issues/46931

will be fixed in 2018.3.1 by https://github.com/saltstack/salt/pull/47046

**Closed by Ch3LL** 2018-05-08 14:54 UTC
