### ISSUE TITLE
salt-cloud deploy script not working

### ISSUE THREAD

**Issue by poliscialex** [saltstack/salt#58081] opened 2020-07-29 21:25 UTC
### Description of Issue
When deploying a droplet to digitalocean using salt-cloud, the droplet is successfully created, but salt-minion never installs.
First I get a number of messages saying this:
```
Warning: Permanently added '64.225.113.128' (ECDSA) to the list of known hosts.
root@64.225.113.128: Permission denied (publickey).
```
Then finally: `[ERROR   ] Failed to start Salt on host cdo-salt-02`

### Setup
Here is the providers.conf file we use for digital ocean:
```
do:
  driver: digitalocean
  personal_access_token: <REDACTED>
  ssh_key_file: /etc/salt/pki/cloud/do.pem
  ssh_key_names: <REDACTED>
  script: bootstrap-salt
  minion:
    master: <REDACTED>
  start_action: state.apply
```

### Steps to Reproduce Issue
spinning up a droplet using sudo salt-cloud -m path/to/cloud/map

### Versions Report
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-42-generic
         system: Linux
        version: Ubuntu 20.04 focal
```

**Comment by cmcmarrow** [comment] 2020-08-03 06:35
@poliscialex have you confirmed that your `.pem` and all other keys are working when used out side of salt? Thanks for the report!

**Comment by poliscialex** [comment] 2020-08-04 16:47
Yes as I use the .pem to ssh to the droplet once I know it's IP address. So the .pem is working fine.

**Comment by poliscialex** [comment] 2020-08-11 12:21
Anyone else seeing this behavior?

**Comment by Akm0d** [comment] 2020-08-12 16:54
I asked in the cloud group on the saltstack community slack in your behalf: 
https://saltstackcommunity.slack.com/archives/C7KKMMYDQ/p1597161774249300
Do you have some debug logs?

**Comment by poliscialex** [comment] 2020-08-13 16:03
I posted this in the slack channel, but got no response. I believe this is the relevant log.

`Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 911, in wrapped_run_func
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 897, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1251, in run
    self.__bind()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1109, in __bind
    self.io_loop.start()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 865, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1093, in _handle_signals
    channel.close()
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 725, in close
    log.info("MWorkerQueue under PID %s is closing", os.getpid())
  File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/_logging/impl.py", line 313, in _log
    LOGGING_LOGGER_CLASS._log(
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1093, in _handle_signals
    channel.close()
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 725, in close
    log.info("MWorkerQueue under PID %s is closing", os.getpid())
  File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/_logging/impl.py", line 313, in _log
    LOGGING_LOGGER_CLASS._log(
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>`

**Comment by waynew** [comment] 2020-08-17 22:27
This is actually *very* interesting - it looks like it could be related to this other `salt-call` issue that @DmitryKuzmenko and I (and others) have been working on. At least, this contains zmq, closing, and event handling, which are things that 100% are involved with the salt-call problem. 🤔

**Comment by poliscialex** [comment] 2020-08-26 12:50
@waynew any ETA on getting that issue resolved to see if it would resolve this as well?

**Comment by poliscialex** [comment] 2020-10-26 11:49
After upgrading salt master to 3002 I tried this again and still getting the same result

**Comment by sagetherage** [comment] 2021-04-23 00:03
@nicholasmhughes it looks like this is still an issue, yes?

**Comment by sagetherage** [comment] 2021-04-23 00:05
@poliscialex on v3002+ can you send your most recent debug logs, please?

**Comment by poliscialex** [comment] 2021-04-23 13:56
@sagetherage I can work on getting those. Can you remind me how to get the logs that I displayed earlier?

**Comment by poliscialex** [comment] 2021-04-23 17:19
I found this and am seeing this appears to no longer be an issue. Not sure if something fixed it or if something changed on our end. Thanks for reminding me to try this again.

**Closed** 2021-04-26 22:16 UTC
Labels: Bug, Salt-Cloud, info-needed, severity-high
