### ISSUE TITLE
2014.7.0 multimaster / multiprocessing issues

### ISSUE THREAD

**Issue by Rucknar** [saltstack/salt#18322] opened 2014-11-20 14:51 UTC
Slightly odd one this... We are upgrading from 2014.1.13 to 2014.7.0 in a multi-master environment. We've upgraded 3 of 600 minions to test (1RHEL5/2RHEL6) and all have exhibited the issue below: 

With `multiprocessing: True` as is set by default, the minions successfully connect to both master servers, receive commands from both masters successfully **but** the return's only ever seem to work with one of the two masters. 

For example, running a test.ping from master01 will show a return, running from master02 times out. The minion's log shows both masters as being connected and shows the results of the command as being sent off to the salt master. 

We've spent a while looking at this and started grabbing as straws, one of these was to disable multiprocessing. Once that's done then the minion successfully reports to both masters. 

I suspect this is just highlighting the root cause in a different light but were quite stuck with this and it's quite urgent for us. Disabling multiprocessing doesn't really work with our work flows.

**Comment by smithjm** [comment] 2015-01-05 18:45
I am seeing this issue as well, with 2014.7.0 deployed on various OSes (Centos 7, Scientific Linux 6.x, Fedora 17, Fedora19, and Fedora20 to name a few)

**Comment by thedrow** [comment] 2015-01-06 05:52
@smithjm It would be really helpful if you can set up some vagrant project we can reproduce.

**Comment by gavala** [comment] 2015-01-14 11:30
Coming back to have a look at this again I seem to now be able to reproduce this quite easily. The offending piece of config is on the minion, and this seems to happen when startup_states is set to 'highstate'. 

The setup I am using to investigate is two masters, master01 and master02 along with one salt minion, client01. Running "salt '*' test.ping" on master01 with startup_states set to 'highstate' on the minion results in no return and an error in the master log on master02:

```
2015-01-14 11:25:58,025 [salt.utils.event                           ][DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20150114111424565561', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-01-14T11:25:58.024948', 'fun': 'test.ping', 'id': 'client01.skybet.net'}
2015-01-14 11:25:58,026 [salt.utils.event                           ][DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20150114111424565561', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-01-14T11:25:58.025602', 'fun': 'test.ping', 'id': 'client01.skybet.net'}
2015-01-14 11:25:58,027 [salt.loaded.int.returner.local_cache       ][ERROR   ] An inconsistency occurred, a job was received with a job id that is not present in the local cache: 20150114111424565561
```

Running the same command from master02 works as expected. This is reproducible every time, and only happens when startup_states is set to 'high state'. Our top.sls looks like this:

```
base:
  '*':
    - common
```

common.sls looks like this:

```
salt-minion:
  pkg:
    - installed
```

Hope this helps

**Comment by thedrow** [comment] 2015-01-14 11:47
@gavala Thanks for the information.
@smithjm @Rucknar Is that the case for you guys as well?
If it isn't then @gavala should file a new issue about his problem.

**Comment by gavala** [comment] 2015-01-14 12:04
Apologies @thedrow, both myself and @Rucknar a reporting this issue from the same site

**Comment by thedrow** [comment] 2015-01-14 12:10
Oh cool. Good to know :)

**Comment by smithjm** [comment] 2015-01-14 19:16
Omar, no, in our case we do NOT have a startup state defined at all.  We
also don't have ANY multimaster configuration options defined in our minion
or master config files, just a list of masters configured for our minions
implicitly creating a multi-master setup, exactly as was done in Hydrogen.

**Comment by thedrow** [comment] 2015-01-15 07:40
@smithjm First of all it's Om**e**r. Common mistake.
Second, it means that either @gavala found one bug but not all of them or that he did not find the root cause of this bug yet.
Can you paste your (sanitized) configuration files?
What exactly are the steps to reproduce the same environment?

**Comment by Rucknar** [comment] 2015-01-15 08:26
Might be worth creating a seperate ticket if the issue appears to be different. @gavala indeed hasn't found the smoking gun but he's found a way to replicate the issue, this means the dev's can now troubleshoot locally and hopefully find the root cause.

**Comment by gavala** [comment] 2015-01-15 10:03
Hi, here is the minion configuration that causes this issue for me:

```
master:
    - master01
    - master02
id: gueaopsvtst04.skybet.net
random_reauth_delay: 60
auth_timeout: 60
recon_randomize: True
startup_states: 'highstate'
log_level: info
log_level_logfile: info
tcp_keepalive: True
tcp_keepalive_idle: 300
tcp_keepalive_cnt: 5
tcp_keepalive_intvl: 60
```

This minion configuration does not cause the issue:

```
master:
    - master01
    - master02
id: gueaopsvtst04.skybet.net
random_reauth_delay: 60
auth_timeout: 60
recon_randomize: True
log_level: info
log_level_logfile: info
tcp_keepalive: True
tcp_keepalive_idle: 300
tcp_keepalive_cnt: 5
tcp_keepalive_intvl: 60
```

This is using a master configuration as follows:

```
id: master01
worker_threads: 10
autoreject_file: /etc/salt/autoreject.conf
keep_jobs: 24
ping_on_rotate: True
auto_accept: True
file_roots:
  base:
    - /srv/salt
```

**Comment by jhenry82** [comment] 2015-01-29 16:33
I believe we are seeing this and/or issue #19932 after updating about 100 minions from 2014.1.7 to 2014.7.1. Switching our minion config to "multiprocessing: False" helped, but did not eliminate the issue. We run four masters (all listed in every minion's config). At any given time, about 10% of our minions are failing to respond to a simple "test.ping" from one or more master.

Would love any guidance on a workaround or where to start working to develop a patch. Otherwise we are going to have to roll back to the 2014.1 series. Salt is unusable in our environment as it stands.

**Comment by gavala** [comment] 2015-01-29 16:53
@jhenry82 Do you have "startup_states: 'high state'" set in your minion config?

**Comment by jhenry82** [comment] 2015-01-29 16:58
@gavala Nope. Here's a lightly sanitized gist with our non-default master and minion configs.

https://gist.github.com/jhenry82/57d3ae69b1b3994e4b1a

**Comment by bigg01** [comment] 2015-03-24 09:16
Hi I have the same issue with reactor. Any idea to fix that?

Works:
# /etc/salt/minion
master: master1

doesn't work:
# /etc/salt/minion
master:
 - master1
 - master2


alt --versions-report
           Salt: 2014.7.2
         Python: 2.6.9 (unknown, Mar 31 2014, 22:15:20)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

**Comment by bigg01** [comment] 2015-03-24 09:16
Hi I have the same issue with reactor. Any idea to fix that?

Works:
# /etc/salt/minion
master: master1

doesn't work:
# /etc/salt/minion
master:
 - master1
 - master2


alt --versions-report
           Salt: 2014.7.2
         Python: 2.6.9 (unknown, Mar 31 2014, 22:15:20)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

**Comment by rallytime** [comment] 2015-03-24 15:00
@bigg01 Without more information, I think perhaps what you're seeing might be #17033 or maybe even with #13879.

@Rucknar or @gavala After skimming the more recent responses, are you saying that you've narrowed this problem down to when you run a highstate? (I have been spending a lot of time in MM testing it and trying to track down bugs, and I have *definitely* seen problems with running highstates.)

**Comment by c4milo** [comment] 2015-05-16 13:08
I'm seeing this same problem with 2015.5:

salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
I'm not using reactor by the way. Just a simple multi-master setup with two masters. Also, I can replicate the problem just by trying to send pings to the minions. From my perspective, it seems minions are only connecting to one of the masters.

**Comment by c4milo** [comment] 2015-05-16 13:35
ah, I was misled by: 

```yaml
master_type: failover
master_shuffle: True
```
Removing them fixed my "issue".

**Comment by jhenry82** [comment] 2015-05-30 03:44
Just wanted to check in and say that multimaster seems MUCH improved in 2015.5.1. I upgraded our 2014.1.7 masters and minions this week and have encountered none of the many issues we saw with the 2014.7 series.

@Rucknar have you tried the new version yet? This may be fixed.

**Comment by Rucknar** [comment] 2015-05-30 08:57
I'm not currently working with a client that uses salt so can't say I'm afraid. Sounds promising though!

**Comment by rallytime** [comment] 2015-05-31 04:08
@jhenry82 This is such good news! I am glad the new release branch is working better for you. @Rucknar Since you're not able to test the new releases currently, and we have confirmation from @jhenry82 that this is fixed (we made multiple improvements and fixes to Multi Master in the 2015.5.x releases), do you think it is okay to close this issue? We can always open it again if this pops back up for you.

**Comment by Rucknar** [comment] 2015-05-31 09:36
Sounds fair enough to me!

**Comment by gavala** [comment] 2015-05-31 09:42
Hello,

We've also recently updated to 2015.5.1, this problem seems to have gone away and it's much more stable on the whole now as well

**Comment by rallytime** [comment] 2015-05-31 14:58
Excellent! That is great to hear. :)

Thanks all!

**Closed by rallytime** 2015-05-31 14:58 UTC
Labels: Bug, Cannot Reproduce, Core, Fixed Pending Verification, Medium Severity, Multi-Master
