### ISSUE TITLE
archive.extracted still fails with `UnicodeEncodeError`s

### ISSUE THREAD

**Issue by jf** [saltstack/salt#56224] opened 2020-02-21 12:49 UTC
### Description of Issue

as per subject, archive.extracted still fails with `UnicodeEncodeError`s. I see #40578, #47546, #48684 that claim that this has been fixed, but I'm still getting it, with 2019.2.3.

IF it matters, I'm using `salt-ssh` instead of the regular `salt`. I'm hoping it shouldn't matter... but if it does, boo!

```
----------
          ID: extract erlang
    Function: archive.extracted
        Name: /home/vagrant
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.vagrant_0b764e_salt/pyall/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/var/tmp/.vagrant_0b764e_salt/pyall/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/var/tmp/.vagrant_0b764e_salt/pyall/salt/states/archive.py", line 1116, in extracted
                  path_mode = os.lstat(full_path.rstrip(os.sep)).st_mode
              UnicodeEncodeError: 'ascii' codec can't encode characters in position 79-80: ordinal not in range(128)
     Started: 12:36:51.336438
    Duration: 3000.088 ms
     Changes:
```

### Setup

```
extract erlang:
  archive.extracted:
    - name: /home/{{ compile_user }}
    - source: salt://erl/otp_src_{{ otp_version }}.tar.gz
    - source_hash: {{ otp_tarball_hash }}
    - user: {{ compile_user }}
```

### Steps to Reproduce Issue

Use the state file, and try to extract http://erlang.org/download/otp_src_20.3.tar.gz

### Versions Report

```
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jan  7 2020, 18:15:51)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 19.3.0
         system: Darwin
        version: 10.15.3 x86_64
```

**Comment by waynew** [comment] 2020-03-23 18:31
Hey @jf thanks for the report. So far I've been unable to reproduce this - at least with Python 3, on either 2019.2.3 or 3000.

Python 2 *is* EOL, and Sodium (the next release that could include a fix for this) drops support for Python2. Are you able to try this on Python3? If not, I can try to reproduce under Python2.

**Comment by jf** [comment] 2020-03-24 00:14
I see. Thanks for the response, @waynew . Thank you for the note about Python 2 support. I use Ubuntu 18.04 VMs, and I've had issues getting salt-ssh to work with them right out of the box, and resorted to installing `python2.7-minimal` for ssh to work. `python3-minimal` is already installed by default, but without `python2.7-minimal` (?) I still get problems:

```
$ salt-ssh -i vm-xx test.ping
[ERROR   ] ERROR: Failure deploying thin, retrying:
STDOUT:

STDERR:

RETCODE: 10
vm-new:
    ----------
    retcode:
        10
    stderr:
    stdout:
        ERROR: Python version error. Recommendation(s) follow:
        Install Python 2.6 / Python 3 Salt dependencies on the Salt SSH master
        to interact with Python 2.6 / Python 3 targets
```

Why should python2.7-minimal be ok, but not python3-minimal?

**Comment by waynew** [comment] 2020-04-15 19:01
It looks like there's some kind of issue with the dependencies. I would guess that either:

- python2.7-minimal includes more dependencies
- salt has less dependencies under python2

How are you installing `salt-ssh`?

**Comment by jf** [comment] 2020-04-16 03:02
I installed it using the OS X pkg

**Comment by waynew** [comment] 2020-04-16 21:43
Which version of OSX are you on?

**Comment by jf** [comment] 2020-04-17 00:59
I'm on Catalina

**Comment by xeacott** [comment] 2020-06-19 18:33
Hi @jf thanks for getting back. Are you able to fully upgrade to Python3 and salt 3000/3001?

**Closed** 2021-06-16 00:41 UTC
Labels: cannot-reproduce
