### ISSUE TITLE
installation on Debian Jessie fails

### ISSUE THREAD

**Issue by chsa** [saltstack/salt#30859] opened 2016-02-03 13:26 UTC
Hi,

the new salt-master package for Debian Jessie (version 2015.8.4+ds-2) depends on package python-systemd (*) which is not available in Jessie.
Installation fails unless you remove systemd. Returning to legacy sysvinit isn't an option here.

ciao
Christian

(*) Depends: python-crypto (>= 2.6.1), python-msgpack, python-systemd | sysvinit-core, …

**Comment by babilen** [comment] 2016-02-03 14:24
Yeah,this issue is a duplicate of #30696 and https://github.com/saltstack/salt-pack/issues/25

**Comment by dmurphy18** [comment] 2016-02-03 14:27
@chsa removing the dependency in the next point release which is immanent.

**Comment by dmurphy18** [comment] 2016-02-03 14:28
Since duplicate, can this be closed.

**Comment by babilen** [comment] 2016-02-03 14:44
I think that it would be fine to close it.

**Closed** 2016-02-03 14:56 UTC

**Comment by chsa** [comment] 2016-02-03 15:01
oh, I didn't notice the dupe - sorry for the noice.

thx
Christian

**Comment by thatch45** [comment] 2016-02-03 20:48
No worries @chsa ! Thanks!
