### ISSUE TITLE
retcode field not availible on scheduled salt runs for reactors listening to events

### ISSUE THREAD

**Issue by ccoughle** [saltstack/salt#41379] opened 2017-05-22 15:12 UTC
### Description of Issue/Question

The field retcode is available on the salt-master for targeting within reactors seems to only be present went running a manual salt-call.  

Manual run:  

    "_stamp": "2017-05-22T15:05:30.078115",
    "arg": [],
    "cmd": "_return",
    "fun": "state.apply",
    "fun_args": [],
    "id": "<HOSTNAME>",
    "jid": "20170522100530067384",
    "out": "highstate",
    "retcode": 2,
    "return": {

Scheduled Run:  

    "_stamp": "2017-05-22T14:24:13.066578",
    "arg": [],
    "cmd": "_return",
    "fun": "state.apply",
    "fun_args": [],
    "id": "<HOSTNAME>",
    "jid": "20170522092413055890",
    "out": "highstate",
    "pid": 22587,
    "return":

I am attempting to use this to alert on failed IDs within the return field.  If the return code is anything other than zero, parse the event for the failed state and alert based on the state name.  Otherwise, don't parse.  

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment] 2017-05-23 16:10
This is a duplicate of this issue.

https://github.com/saltstack/salt/issues/36466

Thanks for reporting.

Daniel

**Closed by gtmanfred** 2017-05-23 16:10 UTC
