### ISSUE TITLE
#24492 may be evil, investigating the history

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#24533] opened 2015-06-09 16:03 UTC
#24492

**Comment by kiorky** [comment] 2015-06-09 16:06
bug i was in mind is #22891, investigating.

**Comment by kiorky** [comment] 2015-06-09 16:08
additionaly  #22561 & ping @jacksontj

**Comment by kiorky** [comment] 2015-06-09 19:57
Im affaid i have not the time, please do not close yet (or at least before having a deeper eye).
If i remember well, i commited something similar 2 monthes ago, and we decided to remove it as it had some bad side (performance penalty) effects.

@DmitryKuzmenko , was your problem grains that were empty in certain conditions (like in sls) ?

**Comment by DmitryKuzmenko** [comment] 2015-06-10 08:45
My problem was that different modules use different grains copies at least when you use salt API. Simple example:
```
caller = Caller()
caller.function('grains.append', 'roles', 'alpha')
caller.function('grains.append', 'roles', 'beta')
caller.function('grains.append', 'roles', 'gamma')
caller.function('state.highstate')
```
Here grains module writes data into one copy of grains and highstate reads stale data from another grains copy.
I discussed it with Tom and we decided we don't need to have different grains copies at all.

Anyway I'll take a deeper look to the history and the current code.

**Comment by DmitryKuzmenko** [comment] 2015-06-10 08:45
@kiorky thank you for taking care of this!

**Comment by DmitryKuzmenko** [comment] 2015-06-10 17:47
Looked up the patch you've applied in #22891. The mine one does another thing.

I discussed the grains issue with team and as I understood logically we don't need to have different grains copies in different modules. But in some cases grains data is transferred by opts dictionary ignoring (or not having) global injected __grains__. So there is no reason to remove it from opts.

Also I haven't changed  the grains initialization logic. If grains in the opts it would be passed to modules. But if grains is in opts and it's empty and it's not expected behavior we have to know it, investigate the reason that happened and fix it. If module needs grains data, it have to be initialized before.

**Comment by DmitryKuzmenko** [comment] 2015-06-10 17:47
Anyway let me know if you'll find something wrong there.

**Comment by kiorky** [comment] 2015-06-10 19:20
For now, i think we are just fine, after a deeper look, but then it defeat the purpose to have immutable opts.

**Comment by kiorky** [comment] 2015-06-10 19:20
(for me, i dont care)

**Comment by DmitryKuzmenko** [comment] 2015-06-11 07:17
Sounds soothingly. Thank you for heads up! Am I right it can be closed as won't fix?

**Closed** 2015-06-11 13:38 UTC
