### ISSUE TITLE
Salt-master ignoring symlinks with gitfs

### ISSUE THREAD

**Issue by DeadlyMercury** [saltstack/salt#42274] opened 2017-07-12 10:19 UTC
### Description of Issue/Question
Salt-master start to ignore symlinks to directories in states files if using gitfs

### Setup
Salt-master version: 2016.11.6 (prod) and 2016.11.2 (test) with gitfs only
gitfs provider: pygit2 and gitpython - same behavior

and some states that use symlinks - for example:
config-3.5.10.20170606+160848/
config-3.5.10.20170609+100415 -> config-3.5.10.20170606+160848/
config-3.5.10.20170619+114746 -> config-3.5.10.20170606+160848/

### Steps to Reproduce Issue
master config:
```
state_verbose: False
test: True
cachedir: /srv/salt_cache

fileserver_backend:
  - git

gitfs_provider: pygit2
gitfs_remotes:
  - git://github.com/DeadlyMercury/salttest.git
```

Result:
```
# salt-call state.sls test
[ERROR   ] Source file salt://test/files/test-4/conf.txt not found
local:
----------
          ID: /tmp/salttest.txt
    Function: file.managed
      Result: False
     Comment: Source file salt://test/files/test-4/conf.txt not found
     Started: 13:12:17.858247
    Duration: 31.468 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  31.468 ms
```

How this state can work: you need to create symlinks only to files, not dirs, or you need to use roots:
```
fileserver_backend:
#  - git
  - roots
#gitfs_provider: pygit2
#gitfs_remotes:
#  - git://github.com/DeadlyMercury/salttest.git

file_roots:
  base:
    - /srv/salt
```

```
stretch-test salt_cache # nano /etc/salt/master
stretch-test salt_cache # git clone https://github.com/DeadlyMercury/salttest /srv/salt
Cloning into '/srv/salt'...
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 38 (delta 4), reused 36 (delta 2), pack-reused 0
Unpacking objects: 100% (38/38), done.
stretch-test salt_cache # service salt-master restart
stretch-test salt_cache # salt-call state.show_top
local:
    ----------
    base:
        - test
stretch-test salt_cache # salt-call state.sls test
local:
----------
          ID: /tmp/salttest.txt
    Function: file.managed
      Result: None
     Comment: The file /tmp/salttest.txt is set to be changed
     Started: 13:15:53.102198
    Duration: 25.486 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:  25.486 ms
stretch-test salt_cache # ls -alh /srv/salt/test/files/
total 20K
drwxr-xr-x 5 root root 4.0K Jul 12 13:15 .
drwxr-xr-x 3 root root 4.0K Jul 12 13:15 ..
drwxr-xr-x 2 root root 4.0K Jul 12 13:15 test-1
drwxr-xr-x 2 root root 4.0K Jul 12 13:15 test-2
drwxr-xr-x 2 root root 4.0K Jul 12 13:15 test-3
lrwxrwxrwx 1 root root    6 Jul 12 13:15 test-4 -> test-3
stretch-test salt_cache # ls -alh /srv/salt/test/files/test-4/
total 12K
drwxr-xr-x 2 root root 4.0K Jul 12 13:15 .
drwxr-xr-x 5 root root 4.0K Jul 12 13:15 ..
-rw-r--r-- 1 root root    7 Jul 12 13:15 conf.txt
```

### Versions Report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.0
        machine: x86_64
        release: 2.6.32-openvz-042stab123.3-amd64
         system: Linux
        version: debian 9.0

**Comment by DeadlyMercury** [comment] 2017-07-12 10:23
Interesting fact that salt correctly detect symlink, but don't follow it:
```
stretch-test salt_cache # salt-run fileserver.symlink_list
test/files/test-4:
    test-3

```

**Comment by gtmanfred** [comment] 2017-07-12 12:36
Yup, it looks like we do not handle symlinks in the git fileserver.

```
[root@salt gitsalt]# salt-call --local cp.list_master
local:
    - test1/test.sls
    - test2
[root@salt gitsalt]# salt-call --local cp.list_master_symlinks
local:
    ----------
    test2:
        test1
[root@salt gitsalt]# tree /srv/gitsalt/
/srv/gitsalt/
├── test1
│   └── test.sls
└── test2 -> test1

2 directories, 1 file
[root@salt gitsalt]# cat /etc/salt/minion
fileserver_backend:
  - git
gitfs_remotes:
  - /srv/gitsalt
```

@terminalmage can you take a look at this when you get time?

Thanks,
Daniel

**Comment by terminalmage** [comment] 2017-07-13 15:43
This is a duplicate of https://github.com/saltstack/salt/issues/21413, and is targeted for the Oxygen release.

**Comment by gtmanfred** [comment] 2017-07-13 15:46
Perfect, thanks!

**Closed by gtmanfred** 2017-07-13 15:46 UTC
Labels: Bug, Core, Duplicate, High Severity, P3
