### ISSUE TITLE
Debian package 2014.7.2+ds-1~bpo70+1 gitfs broken ?

### ISSUE THREAD

**Issue by babs** [saltstack/salt#21747] opened 2015-03-17 22:42 UTC
Hello,

I've juste updated my salt installs and it seems that the one packaged in 2014.7.2+ds-1~bpo70+1 has the gitfs lock bug (#20896).

After remplacing gitfs references by clone and references in files_roots, it worked again.

D.

                     Salt: 2014.7.2
                   Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                   Jinja2: 2.6
                 M2Crypto: 0.21.1
           msgpack-python: 0.1.10
             msgpack-pure: Not Installed
                 pycrypto: 2.6
                  libnacl: Not Installed
                   PyYAML: 3.10
                    ioflo: Not Installed
                    PyZMQ: 13.1.0
                     RAET: Not Installed
                      ZMQ: 3.2.3
                     Mako: 0.7.0
    Debian source package: 2014.7.2+ds-1~bpo70+1

**Comment by rallytime** [comment] 2015-03-18 14:43
Thanks for the report @babs. We had a regression in the 2014.7.2 release with gitfs, as you've mentioned above. (The package you're referring to is built based on a git tag, which is static, and the package does not have fixes that were submitted upstream.) The bug has been fixed at the HEAD of the 2014.7 branch and the fix will be available in the next release, 2014.7.3.

Since this is a duplicate of #20896, and since it has already been fixed, I am going to close this issue. If you have troubles with this after 2014.7.3 comes out, please let us know and we'll be glad to re-open this bug report and readdress the bug. Thanks!

**Closed by rallytime** 2015-03-18 14:43 UTC
Labels: Duplicate

**Comment by babs** [comment] 2015-03-18 16:31
Those pacakges where released yesterday, isn't it weird to release a version with an upstream patched regression ?
Is there a stabilization cycle in between releases (like 2014.7.2.1 or 2014.7.2a) ?
I'm not really aware of the cycle of the packages. When does the 2014.7.3 would be released ?

**Comment by rallytime** [comment] 2015-03-18 16:47
@babs We have mainly community packagers that update their various repos as they are able, at this point in time. The 2014.7.2 release was announced several weeks ago, actually, but our packager only recently was able to get them finished up. We are working on a faster internal packaging process to remediate the Debian/Ubuntu lag currently. 

There is not a stabilization cycle currently. Really what we are working towards is a faster release process in general, with more stable releases.

As far as when 2014.7.3 will be released, we are working very hard to get that completed soon. We have a couple of release blocking bugs that we are working on fixing ASAP so we can move forward on this release.

**Comment by babs** [comment] 2015-03-18 16:50
@rallytime Thank you for all those clarifications !
I hope this will come soon. Wish I cound help :/

**Comment by rallytime** [comment] 2015-03-18 17:01
No problem! Sorry I didn't have any silver bullet answers here.
