### ISSUE TITLE
[BUG] Credentials with artifactory.downloaded do not work since python3 migration

### ISSUE THREAD

**Issue by tomsolpa** [saltstack/salt#63063] opened 2022-11-15 09:08 UTC
**Description**
Since upgrading from python2 to python3, using credentials with the artifactory.downloaded state function stopped working.

Headers are not cleaned ("\n" remain) before using.

Generating the errors :
```
[ERROR   ] Invalid header value b'Basic abcdefghijklmnopqrstuvwxyr01234567==\n'
[ERROR   ] Invalid header value b'Basic abcdefghijklmnopqrstuvwxyr01234567==\n'
```

```
          ID: Download archive file from artifactory
    Function: artifactory.downloaded
      Result: False
     Comment: Invalid header value b'Basic abcdefghijklmnopqrstuvwxyr01234567==\n'
     Started: 14:55:45.977941
    Duration: 3.367 ms
     Changes:   
```

**Setup**
Salt-minion : 3003.3, 3004
Python 3.7.3, 3.9.2

**Steps to reproduce**

```
Download archive file from artifactory:
  artifactory.downloaded:
    - artifact:
       artifactory_url: "{{pillar['artifactory_url']}}"
       repository: "{{ pillar['artifactory_repository']}}"
       group_id: "{{ pillar['artifactory_group_id'] }}"
       artifact_id: "{{ pillar['artifactory_artifact_id'] }}"
       packaging: "{{pillar['artifactory_packaging']}}"
       version: "{{pillar['artifactory_version']}}"
       username: "{{pillar['artifactory_username']}}"
       password: "{{pillar['artifactory_password']}}"
    - target_file: /var/local/share/file-downloaded.tar.gz
```

**Versions Report**

Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-9-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye

**Comment by joshmcorreia** [comment] 2023-02-22 22:56
It should be noted that this was not caught because there are not unit tests for calling this method with credentials.

**Comment by szjur** [comment] 2023-08-03 07:31
This is caused by https://github.com/saltstack/salt/commit/4960c908048320105643aa32eae80bb4e02f51fc by @DmitryKuzmenko and @dwoz which started encoding credentials with salt.utils.hashutils.base64_encodestring() which clearly says that _Among other possible differences, the "modern" encoder includes a newline ('\\n') character after every 76 characters **and always at the end of the encoded string**._ From what I can see httpclient has a regex for headers and most likely doesn't like that trailing \n.

**Comment by szjur** [comment] 2023-08-03 07:54
https://github.com/saltstack/salt/commit/4960c908048320105643aa32eae80bb4e02f51fc should have changed base64.b64encode() to salt.utils.hashutils.base64_b64encode() not salt.utils.hashutils.base64_encodestring() and then all would have been fine and dandy.

**Comment by dmurphy18** [comment] 2023-12-20 22:44
@joshmcorreia Just want to point out the tests for artifactory https://github.com/saltstack/salt/blob/master/tests/pytests/unit/modules/test_artifactory.py and https://github.com/saltstack/salt/blob/master/tests/pytests/unit/states/test_artifactory.py

**Comment by dmurphy18** [comment] 2023-12-20 23:17
@tomsolpa Working on this but can you confirm the issue still exists with a version of Salt that is supported, that is, 3006.4 or 3006.5, since 3004 is EOL.

**Comment by dmurphy18** [comment] 2024-01-02 23:06
@tomsolpa Ping ^^^m have you tried it on a supported version of Salt , that is , 3006.5

**Comment by dmurphy18** [comment] 2024-01-04 21:48
Closing since PR https://github.com/saltstack/salt/pull/65786 merged

**Closed by dmurphy18** 2024-01-04 21:48 UTC
Labels: Bug, python3
