### ISSUE TITLE
salt-cloud : Unable to add SSD disk and unable to auto-delete disk on instance termination on GCE

### ISSUE THREAD

**Issue by bramhg** [saltstack/salt#19236] opened 2014-12-23 20:43 UTC
I am not able to create a SSD disk for my instance created using salt-cloud on GCE. I have used 
```
boot-disk-type: pd-ssd
```
But it has not effect.

Also I am unable to check "Delete boot disk when instance is deleted" flag through salt-cloud profile. I have tied the following combination :
```
use_persistent_disk: False
delete_boot_pd: True
```
But it also does not work.

I am using salt version 2014.7.0   and apache-libcloud version 0.16.0.
```
bramhg@saltmaster:/etc/salt$ salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
        M2Crypto: 0.21.1
        msgpack-python: 0.3.0
        msgpack-pure: Not Installed
        pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
bramhg@saltmaster:/etc/salt$ pip list | grep apache
apache-libcloud (0.16.0)
```

**Comment by rallytime** [comment] 2015-09-23 18:47
@bramhg - Apologies for not coming back around to this issue for so long. The good news is that as I was looking into this issue, I realized that the first option you listed (adding an SSD disk) already implemented. Switch your `boot-disk-type` key to `ex_disk_type: pd-ssd` and it will work - I just tested it successfully on 2015.8.0 (though it's been there since 2014.7.0). I'll need to add some docs to expose this option.

In terms of the other options you were asking about, can you confirm what you're expecting to happen with those options? I have set the following option in my cloud profile config:
```
delete_boot_pd: True
```
And the result on my GCE VM was that the box labeled "Delete boot disk when instance is deleted" is checked, though I am unable to "uncheck" it, as demonstrated in this screen shot:
<img width="835" alt="screen shot 2015-09-23 at 12 43 18 pm" src="https://cloud.githubusercontent.com/assets/6547906/10054898/c170748e-61f0-11e5-950a-c411a498fe49.png">
This seems like the expected behavior to me, but I could be mis-reading your original report. Can you clarify that point?

**Comment by rallytime** [comment] 2015-09-23 19:12
@bramhg I've added the documentation for using `ex_disk_type` in #27345.

**Comment by rallytime** [comment] 2015-10-07 21:58
I think the behavior I described above is the expected behavior from GCE when using `delete_boot_pd: True`, and I've updated the docs about using `ext_disk_type`, so I am going to go ahead and close this. If more discussions should be had here, please leave a comment and we'll be happy to reopen.

**Closed by rallytime** 2015-10-07 21:58 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P3, RIoT, Salt-Cloud
