### ISSUE TITLE
test.provider(s) gives the wrong answer for module vsphere

### ISSUE THREAD

**Issue by erwindon** [saltstack/salt#49332] opened 2018-08-25 23:25 UTC
### Description of Issue/Question
The function `test.providers` returns value `"__init__"` as answer for module `"vsphere"`. The same happens for function `test.provider vsphere`.

### Setup
default system with a master and a minion.

### Steps to Reproduce Issue
issue `salt '*' test.provider vsphere`
See that the answer is `"__init__"` instead of `"vsphere"`.
This is the only module that returns this inaccurate result.

First investigation steps:
The function `test.provider` takes one of the functions of the given module to use for inspection. In my case that happens to be `add_host_to_dvs`. But the module for that one is somehow reported as `salt.utils.decorators`, probably due to the use of the annotations with this function. This ultimately leads to the indicated result.

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.3.12
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.8 (default, Mar 23 2018, 10:04:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by garethgreenaway** [comment] 2018-08-27 16:40
@erwindon Thanks for the report.  This seems to be fixed in the most recent 2018.3, so will be available in 2018.3.3.  I'll see if I can track down the PR that fixed it.

**Comment by garethgreenaway** [comment] 2018-08-27 23:09
@erwindon I checked the output with 2018.3.2 and I wasn't able to reproduce the error.    Can you check what version of `pyVmomi` you have installed?

**Comment by erwindon** [comment] 2018-08-28 00:07
@garethgreenaway I have not installed `pyVmomi` or any other vsphere tools.

**Comment by garethgreenaway** [comment] 2018-08-28 00:10
@erwindon Ahh that is likely the problem and appears to be a bug when the __virtual__ function for a module does not return True allowing the module to be loaded.  Without the pyVmomi library I also see the the same results.

**Comment by erwindon** [comment] 2020-01-06 22:21
In 2019.2.2, the problem seems to be resolved for "vsphere".
But now, module `saltcheck` returns `__init__`.
See `salt '*' test.provider saltcheck`

**Comment by mchugh19** [comment] 2020-06-05 07:25
@erwindon master branch saltcheck currently reports
```
# salt '*' test.provider saltcheck
saltdev:
    json
```

Is this still an issue?

**Comment by erwindon** [comment] 2020-06-05 16:29
@mchugh19 
That is not an improvement :-)
See output of `test.providers` for a complete overview of all values.
I have 162 entries there on a 3000.3 system.
* 134 use the same python modulename as the salt modulename; and
* 24 entries have similar names, e.g. `ansiblegate` vs `ansible`.

but 4 behave different, comparable to the initial report:
* `saltcheck`: in the source code, it intends to return `saltcheck`, but it returns `json` (see `modules/saltcheck.py`)
* `peeringdb`: in the source code, it intends to return `peeringdb`, but it returns `args` (see `modules/peeringdb.py`)
* 'sysmod': in the sourcecode, it intends to return `sys`, but `minion` is returned (see `modules/sysmod.py`)
* 'travisci': in the sourcecode, it intends to return `travisci`, but `parse` is returned (see `modules/travisci.py`)

I think the divergent values are due to some technical challenges in determining the python class hierarchy. I assume it is basically the same problem as the one that caused `__init__` to be returned earlier.

The effect seems to be caused by import statements that cause additional code to be added to a module. e.g. removing line `from salt.utils.args import clean_kwargs` from `modules/peeringdb.py` causes the correct value to be returned again (but the module is of course then broken since the import is still important for that). Same for `travisci`/`from salt.ext.six.moves.urllib.parse import parse_qs`.

Note that most of these packages are also reported by `test.not_loaded`. Which is a contradiction since they are also reported as loaded by `test.providers`.

**Comment by twangboy** [comment] 2023-09-06 22:51
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!

**Closed by twangboy** 2023-09-06 22:51 UTC
Labels: Bug, severity-medium
