### ISSUE TITLE
saltstack can't restart mysql

### ISSUE THREAD

**Issue by xuwn** [saltstack/salt#41573] opened 2017-06-04 12:42 UTC
### Description of Issue/Question
i can't use salt stack to restart minion's mysql service!!!

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
mysql.sls:
```
mysql_running:
  service.running:
    - name: mys
    - enable: True
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```
[root@salt-master ~]# salt '*' service.start mysql     
^C
Exiting gracefully on Ctrl-c
This job's jid is: 20170603224249262856
The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

salt-run jobs.lookup_jid 20170603224249262856
[root@salt-master ~]# 
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
[root@salt-master ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Nov 22 2013, 12:16:22)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final
 
[root@salt-master ~]# 
```

**Comment by xuwn** [comment] 2017-06-04 12:47
the same bug when i use:
salt '*' state.sls mysql
or 
salt-ssh '*' cmd.run cmd="service msyql restart"

mysql version:
5.6.36 and 5.7.18

**Comment by xuwn** [comment] 2017-06-04 12:59
it's long time to watting 
and
no return

**Comment by Ch3LL** [comment] 2017-06-05 18:05
This is a duplicate of https://github.com/saltstack/salt/issues/16153  Closing here but feel free to comment on that issue.

**Closed by Ch3LL** 2017-06-05 18:05 UTC

**Comment by xuwn** [comment] 2017-08-30 06:33
@Ch3LL

**Comment by xuwn** [comment] 2017-08-30 06:33
@Ch3LL

**Comment by xuwn** [comment] 2017-08-30 06:34
@Ch3LL i have found the problem where cause this issure.

**Comment by xuwn** [comment] 2017-08-30 06:35
@Ch3LL 
i have found the problem where cause this issure.

**Comment by xuwn** [comment] 2017-08-30 06:37
@Ch3LL 
i have found the problem where cause this issure.

centos6.5
/etc/init.d/mysql.d:
modify mysqld like this:
`            if [ -x /usr/bin/mysql_ssl_rsa_setup -a ! -e "${datadir}/server-key.pem" ] ; then
                /usr/bin/mysql_ssl_rsa_setup --datadir="$datadir" --uid=mysql **>/dev/null 2>&1**`

**Comment by xuwn** [comment] 2017-08-30 06:37
@Ch3LL 
i have found the problem where cause this issure.

centos6.5
/etc/init.d/mysql.d:
modify mysqld like this:
`if [ -x /usr/bin/mysql_ssl_rsa_setup -a ! -e "${datadir}/server-key.pem" ] ; then /usr/bin/mysql_ssl_rsa_setup --datadir="$datadir" --uid=mysql >/dev/null 2>&1`

**Comment by xuwn** [comment] 2017-08-30 06:38
@Ch3LL 
i have found the problem where cause this issure.

centos6.5
/etc/init.d/mysqld:
modify mysqld:
`if [ -x /usr/bin/mysql_ssl_rsa_setup -a ! -e "${datadir}/server-key.pem" ] ; then /usr/bin/mysql_ssl_rsa_setup --datadir="$datadir" --uid=mysql >/dev/null 2>&1`
