### ISSUE TITLE
[BUG][RC3006][RC1] Deltaproxy / netmiko  Exception in thread Schedule(name=__proxy_keepalive

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#63809] opened 2023-03-02 23:09 UTC
**Description**
Got this error while playing with deltaproxy and netmiko 

**Setup**
Deltaproxy with netmiko proxy module 

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Can't replicate it for now. I just found it in my logs. 

Will update the issue , if I am able to reproduce it. 

**Expected behavior**
Exception inside threading.py does not sound good... 

**Screenshots**

**Versions Report**

```
Salt Version:
          Salt: 3006.0rc1

Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.1.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.17
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 25.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-12-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
```
[ERROR   ] Creating connection to router_vm_netmiko
Exception in thread Schedule(name=__proxy_keepalive, jid=20230302230109981842):
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sharky/venv/salt3006rc1/lib/python3.9/site-packages/salt/utils/schedule.py", line 697, in handle_func
    self.utils = salt.loader.utils(self.opts)
  File "/home/sharky/venv/salt3006rc1/lib/python3.9/site-packages/salt/loader/__init__.py", line 534, in utils
    return LazyLoader(
  File "/home/sharky/venv/salt3006rc1/lib/python3.9/site-packages/salt/loader/lazy.py", line 249, in __init__
    opts = copy.deepcopy(opts)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 229, in _deepcopy_dict
    for key, value in x.items():
RuntimeError: dictionary changed size during iteration
```
</details>

**Comment by garethgreenaway** [comment] 2023-03-06 21:41
@network-shark Thanks for the report.  One quick question since this like something related to the scheduler, did you have multiprocessing enabled or disabled?

**Comment by network-shark** [comment] 2023-03-06 22:05
etc/salt/proxy
```
# DELTAPROXY
multiprocessing: True
metaproxy: deltaproxy
skip_connect_on_init : True
```

I do use napalm and netmiko minions , but I am not able to reproduce it at the moment. 

The only things what I found interesting is that skip_connect_on_init : True does not work for napalm minions  , I have not checked it for netmiko ones. 

Even if  skip_connect_on_init is set to true , napalm will connect anyway.

**Comment by garethgreenaway** [comment] 2023-03-06 22:08
@network-shark Thanks for the response.  I suspect this one will be a tricky one to reproduce so until we hear otherwise we won't consider it a block for the 3006.0 release.  

The `skip_connect_on_init` option needs to be in the individual proxy minions and I suspect it's not in the napalm one.  If it is, then that's a bug :)

**Comment by garethgreenaway** [comment] 2023-03-22 16:07
Haven't seen any updates on this one and since wasn't reproducible, I'll close this out.  If the problem does persist please let us know.

**Closed by garethgreenaway** 2023-03-22 16:07 UTC
Labels: Bug, needs-triage, Delta-Proxy
