### ISSUE TITLE
show_highstate failed sometimes

### ISSUE THREAD

**Issue by 9maf4you** [saltstack/salt#40849] opened 2017-04-24 12:14 UTC
Hello. As I said here https://github.com/saltstack/salt/issues/40526 I'm using salt-call state.show_highstate for monitoring my minions.
After updating to `Salt: 2016.3.3` I noticed that after calling `state.show_highstate` an output file is empty. It reproduces only when it is run by crontab
crontab looks like:
`*/30 * * * * sleep $(shuf -i 100-110 -n 1); /usr/bin/salt-call saltutil.refresh_pillar -l quiet > /tmp/fresh_pillar; /usr/bin/salt-call state.show_highstate --out=json --out-file=/var/tmp/check_high.out -l quiet`

when I changed `quiet` to `debug` i got this:
```
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'sas-minion-host-1.example.com', 'tcp://[sasd3-master-2.example.com]:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'sas-minion-host-1.example.com', 'tcp://[sasd3-master-2.example.com]:4506')
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'sas-minion-host-1.example.com', 'tcp://[sasd3-master-2.example.com]:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'sas-minion-host-1.example.com', 'tcp://[sasd3-master-2.example.com]:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem

Passed invalid arguments: string indices must be integers, not str.

Usage:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1165, in show_highstate
    st_ = salt.state.HighState(__opts__, pillar, pillar_enc=pillar_enc)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3535, in __init__
    loader=loader)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 662, in __init__
    self.opts['pillar'] = self._gather_pillar()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 704, in _gather_pillar
    ret = pillar.compile_pillar()
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 156, in compile_pillar
    dictkey='pillar',
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 200, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret['key'])
TypeError: string indices must be integers, not str
```

worthy of mention that it is floating problem.

salt version: 2016.11.3+ds-1

Could you suggest a workaround?
It's very annoying problem.

Thank you. Max.

**Comment by Ch3LL** [comment] 2017-04-25 14:59
@9maf4you this is a duplicate of https://github.com/saltstack/salt/issues/30066. I will close this issue in favor of that one and we can track this issue there. Thanks

**Closed by Ch3LL** 2017-04-25 14:59 UTC
