### ISSUE TITLE
windows winrepo installer makes wrong matches between 'pkg name' 'full_name' and 'version' number 

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#25510] opened 2015-07-17 14:15 UTC
__*Summary:*__
OK, I **seemingly** have 32-bit __*.x86__ pkgs that install on 64-bit __AMD64__ minions.
And also **seemingly** have 64-bit __AMD64__ pkgs that install on 32-bit minions.
And we know this is **NOT** even possible.
(Note: I really believe this is different (a bug) and not related to the troubleshooting warning you have in the windows winrepo instructions, about making sure that the ```'full_name'``` and ```'version'``` number need to match. see http://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#incorrect-name-version)

__*Suspicion:*__
I __*suspect*__ that the ```'pkg.install'``` or ```'pkg.installed'``` functions match 'too early', somehow?

__*Background:*__
The winrepo has pkgs called ```'mypkg.sls'``` and ```'mypkg_x86.sls'```, and the idea is that the ```'mypkg_x86.sls'``` file get's used on minions with ```'cpuarch = x86'``` and the ```'mypkg.sls'``` without the '_x86' suffix get's used on the 64-bit AMD64 machines, wiith the help of a little grains 'magic' stanza in the state files.
```
mypkg:
    pkg:
    {% if grains['cpuarch'] == 'x86'%}
    - name: mypkg_x86
    {% endif %}
    - installed
```
That's the **theory**, but **in practice** it seems to think it installed some _x86 pkgs on 64-bit minions and 64-bit pkgs on 32-bit minions. The strange thing is, it works correctly for some and incorrectly for other pkgs?

Here is my ```'test-packages.sls'`` file:
```
# test-packages.sls
7zip:
  pkg:
    {% if grains['cpuarch'] == 'x86'%}
    - name: 7zip_x86
    {% endif %}
    - installed

curl:
  pkg:
    {% if grains['cpuarch'] == 'x86'%}
    - name: curl_x86
    {% endif %}
    - installed

npp:
  pkg:
    {% if grains['cpuarch'] == 'x86'%}
    - name: npp_x86
    {% endif %}
    - installed

putty:
  pkg:
    {% if grains['cpuarch'] == 'x86'%}
    - name: putty_x86
    {% endif %}
    - installed

winscp:
  pkg:
    {% if grains['cpuarch'] == 'x86'%}
    - name: winscp_x86
    {% endif %}
    - installed
```
And here is what happens on a **64-bit** machine called ```'uk-it-20'```:
```
uk-it-20 is a 64-bit AMD64 machine

# salt uk-it-20 grains.item cpuarch

uk-it-20:
    ----------
    cpuarch:
        AMD64


# salt uk-it-20 pkg.list_pkgs | grep -i -E '7zip|curl|npp|notepad|putty|winscp|'

#
(Which returns no matches.)
# And now we install the ```'test-packages'```:
```

```
# salt uk-it-20 state.sls windows.test-packages

uk-it-20:

----------

          ID: 7zip

    Function: pkg.installed

      Result: True

     Comment: The following packages were installed/updated: 7zip=9.20.00.0

     Started: 12:13:07.173000

    Duration: 3839.0 ms

     Changes:

              ----------

              7zip:

                  ----------

                  new:

                      9.20.00.0

                  old:

----------

          ID: curl

    Function: pkg.installed

      Result: True

     Comment: The following packages were installed/updated: curl=7.43.0

     Started: 12:13:11.027000

    Duration: 2013.0 ms

     Changes:

              ----------

              curl:

                  ----------

                  new:

                      7.43.0

                  old:

----------

          ID: npp

    Function: pkg.installed

      Result: False

     Comment: The following packages failed to install/update: npp=6.7.9.2

     Started: 12:13:13.056000

    Duration: 4635.0 ms

     Changes:

              ----------

              npp_x86:

                  ----------

                  new:

                      6.7.9.2

                  old:

----------

          ID: putty

    Function: pkg.installed

      Result: False

     Comment: The following packages failed to install/update: putty=0.64

     Started: 12:13:17.706000

    Duration: 1842.0 ms

     Changes:

              ----------

              putty_x86:

                  ----------

                  new:

                      0.64

                  old:

----------

          ID: winscp

    Function: pkg.installed

      Result: True

     Comment: The following packages were installed/updated: winscp=5.7.4

     Started: 12:13:19.563000

    Duration: 7537.0 ms

     Changes:

              ----------

              winscp:

                  ----------

                  new:

                      5.7.4

                  old:



Summary

------------

Succeeded: 3 (changed=5)

Failed:    2

------------

Total states run:     5
```
So it thinks only 3 succeeded and 2 failed.

And to check what it actually installed we check which pkgs are on it.

```
# salt uk-it-20 state.sls windows.test-packages | grep -i -E '7zip|curl|npp|notepad|putty|winscp'

    7zip:

    curl:

    npp_x86:

    putty_x86:

    winscp:

#
```
So it actually installed all 5 pieces of software, but somehow believes it installed the **correct** files ```'7zip'```, ```'curl'```, and ```'winscp'```and somehow the **incorrect** ```'npp_x86'``` and ```'putty_x86'``` files? Why?

And here is what  it does on a 32-bit minion called ```'uk-it-70'```:

```
uk-it-70 is a 32-bit x86 machine

# salt uk-it-70 grains.item cpuarch

uk-it-70:
    ----------
    cpuarch:
        x86


# salt uk-it-70 pkg.list_pkgs | grep -i -E '7zip|curl|npp|notepad|putty|winscp'

#
```

(which returns no matches)

```
# salt uk-it-70 state.sls windows.test-packages

uk-it-70:

----------

          ID: 7zip

    Function: pkg.installed

        Name: 7zip_x86

      Result: True

     Comment: The following packages were installed/updated: 7zip_x86=9.20.00.0

     Started: 12:15:45.472000

    Duration: 1684.0 ms

     Changes:

              ----------

              7zip_x86

                  ----------

                  new

                      9.20.00.0

                  old

----------

          ID: curl

    Function: pkg.installed

        Name: curl_x86

      Result: False

     Comment: The following packages failed to install/update: curl_x86=7.43.0

     Started: 12:15:47.172000

    Duration: 2480.0 ms

     Changes:

              ----------

              curl

                  ----------

                  new

                      7.43.0

                  old

----------

          ID: npp

    Function: pkg.installed

        Name: npp_x86

      Result: True

     Comment: The following packages were installed/updated: npp_x86=6.7.9.2

     Started: 12:15:49.652000

    Duration: 4868.0 ms

     Changes:

              ----------

              npp_x86

                  ----------

                  new

                      6.7.9.2

                  old

----------

          ID: putty

    Function: pkg.installed

        Name: putty_x86

      Result: True

     Comment: The following packages were installed/updated: putty_x86=0.64

     Started: 12:15:54.535000

    Duration: 2075.0 ms

     Changes:

              ----------

              putty_x86

                  ----------

                  new

                      0.64

                  old

----------

          ID: winscp

    Function: pkg.installed

        Name: winscp_x86

      Result: False

     Comment: The following packages failed to install/update: winscp_x86=5.7.4

     Started: 12:15:56.626000

    Duration: 7597.0 ms

     Changes:

              ----------

              winscp

                  ----------

                  new

                      5.7.4

                  old



Summary

------------

Succeeded: 3 (changed=5)

Failed:    2

------------

Total states run:     5
```
So here it thinks 3 succeeded and 2 failed.

But if we check , we can see that all 5 actually did install.

```
# salt uk-it-70 pkg.list_pkgs | grep -i -E '7zip|curl|npp|notepad|putty|winscp'

    7zip_x86:

    curl:

    npp_x86:

    putty_x86:

    winscp:

```
And here it installed the **correct** 32-bit pkgs ```'7zip_x86'```, ```'npp_x86'```, and ```'putty_x86'```, but also the **incorrect** __**AMD64**__ ```'curl'``` and ```'winscp'```.

What is going on here? Why are the ```'wires crossed'``` for some pkgs and not for others?

Here is a summary in a table:

Name   | x86 platform     | success/fail   | AMD  platform  | success/fail
----------|----------------------|-------------------|---------------------|-----------------------
7zip	    | 7zip_x86           | s	               | 7zip                  | s
curl	    | curl_x86	       | f	               | curl	                 | s
npp	    | npp_x86	       | s                    | npp_x86	         | f
putty	    | putty_x86	       | s                    | putty_x86         | f
winscp |	winscp_x86    |	f	               | winscp	         | s

ping @jfindlay @UtahDave @twangboy any idea how I can avoid these crossed over wires? Why does pkg.installed think the 'other' pkg is installed, from the one it just installed itself?

**Comment by TheBigBear** [comment] 2015-07-17 14:45
ping @jfindlay @UtahDave any idea how I can avoid these crossed over wires? Why does pkg.installed think the 'other' pkg is installed, from the one it just installed itself?

**Comment by TheBigBear** [comment] 2015-07-19 15:28
OK, I thought some more abou thisvexing problem, and I think I now understand where the problem comes from. 
Basically the winrepo code tries to decide which pkgs are actually installed. And it bases that decsion on only two factors, the first match of the DisplayName and the DisplayVersion of the program installed in the registry and then compares it to the pkg files full_name and version in the repo. 

But this is not enough factors. As a 32-bit program installed on a 64-bit OS will always have the SAME DisplayName and DisplayVersion. 

The one thing that (usually) is different is the uninstaller. If salt could do one further check, and that only makes sense, if the uninstaller string is not empty, then check for the presence of the unistaller file itself, and if it doesn't exist keep looking through the dict of pkg names and versions for the next match and check for the installer file existence again, and if it is found , we found the right pkg name. 
Simple. ;-) (ahem!)
 Now if only my python weren't as rusty, but I think I would really struggle writing this bit myself, sorry. But hopefully the above info and findings help solve this issue.
ping @jfindlay @UtahDave @twangboy

**Comment by jfindlay** [comment] 2015-07-20 15:25
@TheBigBear, adding a check for the uninstaller seems like a good idea to help with a difficult problem, thanks.

**Comment by TheBigBear** [comment] 2015-07-24 09:38
@twangboy  I now finally have a windows develop system up, so if you have need of  some 'testing'  give me a shout and I'll gladly "play" around and report back any findings. My mind usually finds 'edge' cases quite quickly/easily.

**Comment by twangboy** [comment] 2015-07-24 23:25
Thanks @TheBigBear I plan on working this and a few others next week.

**Comment by twangboy** [comment] 2015-07-28 22:52
@TheBigBear I'm going through the code trying to figure this issue out and it looks to me like the problem occurs when the winrepo.p file is generated. There is a function in `win_pkg.py` called `_get_name_map()` that returns a dictionary containing the `full name` and `name` for each item in the `winrepo`. It looks like when you have two `.sls` files describing the same piece of software, one for 32bit and one for 64bit, whichever one is read last wins. So, it's not always consistent on which one will become a part of the name map in the `winrepo.p`. It doesn't seem to  necessarily be alphabetical. My results showed x86 for all but 7zip.

Here's a partial dump of the `name_map`:
```
'WinSCP 5.5': 'winscp',
'WinSCP 5.5.6': 'winscp',
'WinSCP 5.7.3': 'winscp',
'WinSCP 5.7.4': 'winscp_x86',
'Wireshark 1.11.0 (32-bit)': 'wireshark-32',
'Wireshark 1.11.0 (64-bit)': 'wireshark-64',
'Wireshark 1.11.1 (32-bit)': 'wireshark-32',
'Wireshark 1.11.1 (64-bit)': 'wireshark-64',
'Wireshark 1.12.1 (64-bit)': 'wireshark-64',
'Wireshark 1.12.6': 'wireshark_x86-32',
'Wireshark 1.12.6 (64-bit)': 'wireshark-64',
'Wireshark 1.99.0 (64-bit)': 'wireshark-devel-64',
'Wireshark 1.99.7': 'wireshark-devel_x86-32',
'Wireshark 1.99.7 (64-bit)': 'wireshark-devel-64',
'XAMPP 5.6.3': 'xampp',
'bulk_extractor': 'bulk_extractor',
'cURL': 'curl_x86',
'iCloud': 'icloud',
'iTunes': 'itunes',
'pGina v3.1.8.0': 'pgina'
```
I picked this portion to show WinSCP in particular. You'll notice that the only one that shows `x86` is the 5.7.4 version... the only version in the `winscp_x86.sls` file. So, this is a problem caused by creating '.sls' files for each `cpuarch`. The key for the `name_map` dictionary is the `full_name` which can be the same in multiple `.sls` files. It seems to be random as to which one wins.

I believe the solution that's coming out with 2015.8 will solve this problem because the `winrepo.p` file is generated on the minion and the software definitions are run through the parser so you can add Jinja to account for differing cpu architectures.

**Comment by twangboy** [comment] 2015-07-28 22:57
@UtahDave ^^^^
For reference here's the entire name_map:
http://pastebin.com/jkUuiMdG

**Comment by TheBigBear** [comment] 2015-08-05 07:44
@twangboy thanks for looking into this, but introducing jinja to windows winrepo files is going to break those files for all clients prior to the Berrylium ones?

**Comment by TheBigBear** [comment] 2015-08-05 08:24
@twangboy @UtahDave another issue is, that the fact that a minion is running x64 or x86 does NOT necessarily dictate which version of a pkg to install on it. It is perfectly legal (and even required) to be able to say that one wants to install the x86 version on a x64 cpuarch, or both versions. 
But this is a choice the IT admin makes on a case by case basis. Nothing that any jinja magic can do automatically, so I think there needs to be two names for a pkg, one the x86 name and another for the x64 version of it.

**Comment by twangboy** [comment] 2015-08-05 21:13
@TheBigBear That's the big reason why we wanted to parse the jinja on the minion. Take for example winscp. `winscp574setup.exe` will install just fine on a 32bit or a 64bit machine, as you said. They don't even make a 64bit version as far as I know. The only difference is where the uninstaller resides. On 32it machines it resides in `Program Files`. On 64bit machines it is found under `Program Files (x86)`. So, with a little jinja we could change the software definition for winscp to be something like the following:
```
{% if grains['cpuarch'] == 'AMD64' %}
    {% set PROGRAM_FILES = "Program Files (x86)" %}
{% else %}
    {% set PROGRAM_FILES = "Program Files" %}
{% endif %}

winscp:
  5.7.4:
    installer: 'http://cznic.dl.sourceforge.net/project/winscp/WinSCP/5.7.4/winscp574setup.exe'
    full_name: 'WinSCP 5.7.4'
    reboot: False
    locale: en_US
    install_flags: '/SP- /verysilent /norestart'
    uninstaller: '{{ PROGRAM_FILES }}\WinSCP\unins000.exe'
    uninstall_flags: '/verysilent'
```

That would fix the problem with the name mapping as well as the name would be the same whether it was installed on a 32 or 64 bit machine. The only time you would ever need separate software definitions would be when there actually are two separate installers for each cpuarch.

**Comment by twangboy** [comment] 2015-08-27 16:25
@TheBigBear This will be fixed when we finish transitioning over to salt-winrepo-ng

**Closed** 2015-08-27 23:06 UTC
Labels: Bug, High Severity, P4, Platform, Windows
