### ISSUE TITLE
Salt Cloud has broken `--output=compact` option

### ISSUE THREAD

**Issue by vutny** [saltstack/salt#30637] opened 2016-01-26 11:09 UTC
Hi there,

I got an exception when tried to use "compact" output option with `salt-cloud`:

```sh
$ sudo salt-cloud -l debug --output=compact -F
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: eng-saltmaster
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/ec2.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/ec2.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] LazyLoaded compact.output
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'result'
Traceback (most recent call last):
  File "/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 421, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 364, in run
    print(display_output(ret))
  File "/usr/lib/python2.7/site-packages/salt/output/compact.py", line 23, in output
    if data[min_][process]['result'] is False:
KeyError: 'result'
Traceback (most recent call last):
  File "/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 421, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 364, in run
    print(display_output(ret))
  File "/usr/lib/python2.7/site-packages/salt/output/compact.py", line 23, in output
    if data[min_][process]['result'] is False:
KeyError: 'result'
```

Salt version:

```
$ sudo salt --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.7.2.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

Look related to #18614

**Comment by jfindlay** [comment] 2016-01-26 21:40
@vutny, thanks for reporting.

**Comment by cachedout** [comment] 2016-02-02 22:06
@rallytime Is this something you can take a look at?

**Comment by rallytime** [comment] 2016-02-02 22:13
@cachedout I can definitely take a look.

**Comment by rallytime** [comment] 2016-02-05 23:04
@vutny After digging into this a little more, I don't think the `compact` outputter was ever meant to work with salt-cloud. The `compact` outputter was made to satisfy the feature request in #14470, which deals only with the output of state runs. 

Unfortunately, the compact outputter appears to be pretty broken even in its intended use case, which I am working on cleaning up now, including some more useful documentation indicating this functionality.

That being said, I think what you're looking for here is encompassed by the `--output=raw` option, which "displays the output as a python data structure, by printing a string representation of it."

**Comment by rallytime** [comment] 2016-02-06 00:14
@vutny Also see the discussion in [this comment](https://github.com/saltstack/salt/issues/18614#issuecomment-180631387) that I just posted after looking into the `compact` outputter even further.

**Comment by vutny** [comment] 2016-02-08 11:35
@rallytime Thanks for the update!
I was just experimenting with different output modes and accidentally discovered that `compact` outputter is broken indeed.

Maybe we should consider to remove it from output options listed in command usage instructions?
And even from codebase, because there are no tests written for it.

**Comment by rallytime** [comment] 2016-02-08 16:09
@vutny I think removing this option is likely the right way to go, as explained at the end of #18614. I'd like to hear what people have to say on that issue before doing so, though. Since this issue is very nearly a duplicate of #18614 (and this functionality was not intended to work with salt-cloud), would it be ok with you if we close this issue? That way we can track the progress of the `compact` outputter resolution in only one place.

**Comment by vutny** [comment] 2016-02-09 08:50
@rallytime Thanks for clarifications. I'll close this out.

**Closed** 2016-02-09 08:51 UTC
Labels: Bug, Core, High Severity, Outputters, P3, TEAM RIoT
