### ISSUE TITLE
Pillar inside pillar via Jinja doesn't work

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#29146] opened 2015-11-24 11:03 UTC
I want to use pillar values inside pillar. I've tried jinja tempting for that and couldn't get it work. To debug a problem I've tried to use grain values inside pillar and it worked. See complete example below:
```
$ cat /srv/pillar/top.sls
base:
  '*':
    - value
    - jinja_grain
    - jinja_salt_grain
    - jinja_pillar
    - jinja_salt_pillar
$ tail -n +1 /srv/pillar/jinja* /srv/pillar/value.sls
==> /srv/pillar/jinja_grain.sls <==
jinja:
  grain: {{ grains['id'] }}

==> /srv/pillar/jinja_pillar.sls <==
jinja:
  pillar: {{ pillar['key'] }}

==> /srv/pillar/jinja_salt_grain.sls <==
jinja:
  salt_grain: {{ salt['grains.get']('id') }}

==> /srv/pillar/jinja_salt_pillar.sls <==
jinja:
  salt_pillar: {{ salt['pillar.get']('key') }}

==> /srv/pillar/value.sls <==
key: value
$ salt-call pillar.items
local:
    key:
        value
    jinja:
        ----------
        grain:
            minion_id
        salt_grain:
            minion_id
        salt_pillar:
            None
```

PS:
The reason I need use pillar values inside pillar is this:
I have many paths inside my configuration and I decided to group them all into pillar `path`. I also use `postgres-formula` which has `postgres:conf_dir` value. I want to put this value into `path` hierarchy and still avoid values duplication.

**Comment by jfindlay** [comment] 2015-11-25 18:13
@rominf, thanks for the report.  There are some obvious bootstrapping and recursive divergence issues here, which would add complexity to both the use and implementation.  In this situation I would likely try to collect the path elements somewhere else, like in a custom execution module function, for example, but I'll let @basepi decide if this is a feature we would want to have.

**Comment by basepi** [comment] 2015-11-30 23:00
I'm going to close this as a duplicate of https://github.com/saltstack/salt/issues/6955

Basically, we want to add a pre-pillar that doesn't require jinja templating. You'll put it right in your pillar config, and it will be loaded into the templating context for the rest of the pillar. Otherwise it's a chicken and egg problem.

**Closed by basepi** 2015-11-30 23:00 UTC
Labels: Pending Discussion
