### ISSUE TITLE
File permission issue on Salt master

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#21981] opened 2015-03-25 12:09 UTC
I get intermittent error for non-existent file when running salt-key commands on the master. 
The process is running as non-root user and the .../master/ parent folder has the correct ownership.
End up touching the file to fix.
Also observed the issue when the file does exist.
```
Traceback (most recent call last):
  File "/pyvenv/salt/bin/salt-key", line 10, in <module>    salt_key()
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/scripts.py", line 174, in salt_key client.run()
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/cli/key.py", line 61, in run key.run()
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/key.py", line 421, in run self.delete(self.opts['delete'])
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/key.py", line 205, in delete
    self.key.delete_key(match_dict=matches)
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/key.py", line 755, in delete_key
    salt.crypt.dropfile(self.opts['cachedir'], self.opts['user'])
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/crypt.py", line 52, in dropfile
    with salt.utils.fopen(dfn, 'w+') as fp_:
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/utils/__init__.py", line 932, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 13] Permission denied: '/pyvenv/salt/salt-master-root/var/cache/salt/master/.dfn'
```
(salt)-bash-4.1$ salt --versions-report
```  
         Salt: 2015.2.0rc1
         Python: 2.7.8 (default, Sep 24 2014, 11:50:00)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.2
         PyYAML: 3.11
          ioflo: 1.2.1
          PyZMQ: 14.5.0
           RAET: 0.6.3
            ZMQ: 4.0.5
           Mako: 1.0.0
```

**Comment by rallytime** [comment] 2015-03-27 16:51
Hrm. Interesting. Thanks for the report @soodr.

**Comment by soodr** [comment] 2015-04-08 00:20
Occurs frequently with salt-key command when using the glob for filtering minions \:
salt-key -d prod310*

**Comment by cachedout** [comment] 2015-05-13 08:39
I would like to see a copy of `salt-key` run with `-ldebug` and also debug logs from the master for a case where this happens. I think I know what's going on here but would like to confirm. Thanks!

**Comment by soodr** [comment] 2015-05-14 19:25
A scenario where this manifests is when deleting a key which is both in pending and denied state.
Will post the debug log in the next response.

**Comment by dmacvicar** [comment] 2016-02-08 12:55
I suggest this is a duplicate of https://github.com/saltstack/salt/issues/27796 , which has more information to fix it.

**Comment by rallytime** [comment] 2016-02-08 16:02
@dmacvicar Yes, that certainly looks to be a duplicate. This issue is older, but the other issue has more information, so we'll close this one in favor of the new one and track this bug's progress there. @soodr Please defer to #27796 for more information and a potential fix.

**Closed by rallytime** 2016-02-08 16:02 UTC
Labels: Bug, Core, Duplicate, High Severity, Info Needed, P4
