### ISSUE TITLE
[feature request]Subscribe gitfs_remotes to specific branch

### ISSUE THREAD

**Issue by justindesilets** [saltstack/salt#32285] opened 2016-03-31 21:38 UTC
I would like to request the ability to subscribe a gitfs_remotes: git location to a specific branch / tag. Similar to the way you can with ext_pillar git resources. The use case for this is when trying to test between dev / qa / prod without having to maintain separate environments in your top file. This ensures that your applying the same states through each branch when testing and minimizing changes between each environment. An example of the syntax I would think could be something like this:
```
gitfs_remotes:
  - v1.0 git://github.com/example/first.git
    - env: prod
```

**Comment by jfindlay** [comment] 2016-04-01 17:57
@justindesilets, thanks for the feature request.  I am not fully understanding your request, but there are several [configurable parameters](https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#per-remote-configuration-parameters) with gitfs.  Specifically, does this do all or most of what you want?
```sls
gitfs_remotes:
  - git://github.com/example/first.git
    - base: prod
```
You will still have to associate git branches with salt environments in a top file, but I am assuming that that would be mostly static on the timescale of ordinary state development.

**Comment by justindesilets** [comment] 2016-04-02 22:55
@jfindlay Would that subscribe the gitfs_remote to the "prod" branch? With our use case, we will be testing branches often but would like to not have to update the top file each time with a new branch just to test. We are trying to keep code that is tested all the way through identical if we can. Our current work around is to have a testing server that clones the repo directly and then we just check out the branch we want tested. I just thought it would be nice if we could do it with gitfs instead. Where we would just update the master's config with the branch we were testing but had it mapped to the base environment. I only ask for this since you can do it right now with ext_pillar. It seems like it would be good to have matching functionality between the two.

**Comment by jfindlay** [comment] 2016-04-04 16:48
@justindesilets, yes, I think that that makes sense.

**Comment by terminalmage** [comment] 2016-04-21 01:40
This is a duplicate of https://github.com/saltstack/salt/issues/29954

**Closed** 2016-04-21 21:59 UTC
Labels: Duplicate, Feature, File Servers, Platform
