### ISSUE TITLE
[BUG] Centos7 pkg.installed issue when trying to install a package that is already at its latest version

### ISSUE THREAD

**Issue by saltybaker** [saltstack/salt#56654] opened 2020-04-15 18:03 UTC
**Description**
In Centos7 pkg.installed issue when trying to install a package that is already at its latest version

**Setup**
stuff.sls

bind-libs-lite:
  pkg:
    - installed
    - version: '9.11.4'

**Steps to Reproduce the behavior**
[root@master2 salt]# salt minion2 pkg.latest_version bind-libs-lite
[WARNING ][salt.client                              :1073][MainProcess:12806] jid does not exist
[WARNING ][salt.client                              :1078][MainProcess:12806] Returner unavailable: 
minion2:

This is expected if bind-libs-lite is already installed with the version latest available version.

So we try pkg.info_installed to get the version of the installed package
[root@master2 salt]# salt minion2 pkg.info_installed bind-libs-lite
[WARNING ][salt.client                              :1073][MainProcess:12818] jid does not exist
[WARNING ][salt.client                              :1078][MainProcess:12818] Returner unavailable: 
minion2:
    ----------
    bind-libs-lite:
        ----------
        arch:
            x86_64
        build_date:
            2019-08-08T12:20:30Z
        build_date_time_t:
            1565266830
        build_host:
            x86-02.bsys.centos.org
        description:
            Contains lite version of BIND suite libraries which are used by various
            programs to work with DNS protocol.
        epoch:
            32
        group:
            Unspecified
        install_date:
            2020-04-13T18:56:29Z
        install_date_time_t:
            1586804189
        license:
            MPLv2.0
        packager:
            CentOS BuildSystem <http://bugs.centos.org>
        release:
            9.P2.el7
        relocations:
            (not relocatable)
        signature:
            RSA/SHA256, Thu Aug 22 21:20:49 2019, Key ID 24c6a8a7f4a80eb5
        size:
            3091672
        source:
            bind-9.11.4-9.P2.el7.src.rpm
        summary:
            Libraries for working with the DNS protocol
        url:
            http://www.isc.org/products/BIND/
        vendor:
            CentOS
        version:
            9.11.4
[root@master2 salt]#

This confirms that bind-libs-lite is already installed with version 9.11.4
So lets apply the state.

[root@master2 salt]# salt minion2 state.apply stuff
[WARNING ][salt.client                              :1073][MainProcess:12772] jid does not exist
[WARNING ][salt.client                              :1078][MainProcess:12772] Returner unavailable: 
minion2:
----------
          ID: bind-libs-lite
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: bind-libs-lite=9.11.4
     Started: 17:42:43.700955
    Duration: 9997.687 ms
     Changes:   

Summary for minion2
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   9.998 s
ERROR: Minions returned with non-zero exit code

Normally we would expect a result of True and a comment of "All specified packages are already installed and are at the desired version".

Let's check rpm.
[root@master2 salt]# rpm -qa bind-libs-lite
bind-libs-lite-9.11.4-9.P2.el7.x86_64

Also found this in the minion log:
2020-04-15 17:17:19,817 [salt.loaded.int.states.pkg:804 ][DEBUG   ][11425] Current version (['32:9.11.4-9.P2.el7']) did not match desired version specification (9.11.4), 
adding to installation targets

However other packages seem to behave as expected.
 
**Expected behavior**
Normally we would expect a result of True and a comment of "All specified packages are already installed and are at the desired version".

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
[root@master2 salt]# salt --versions-report
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 4.19.76-linuxkit
         system: Linux
        version: CentOS Linux 7.7.1908 Core
 
[root@master2 salt]# 

```
</details>

**Additional context**
This was found while doing a SecOps protect remediation with raas-docker.

**Comment by terminalmage** [comment] 2020-04-17 03:55
This is expected behavior. bind-libs-lite has an epoch, and you didn't specify the epoch in your SLS file:

```
[root@60ae76fc2078 /]# salt-call --local pkg.version bind-libs-lite
local:
    32:9.11.4-9.P2.el7
```

You can either include the epoch, or add `- ignore_epoch: True` to your SLS file.

**Comment by terminalmage** [comment] 2020-04-17 04:30
I can see how `pkg.info_installed` would lead one to believe that this was a bug, but keep in mind that `pkg` states don't use `pkg.info_installed`. As a matter of fact, no states do:

```
% fgrep -r pkg.info_installed salt/states/*.py | wc -l
0
```

It's simply an information-gathering function designed to split the different bits of metadata the package DB contains into their own separate dictionary key/value pairs. `pkg.info_installed` has a `version` key, and `version` is an argument for the `pkg.installed` state, but for an RPM a unique package version consists of three things: epoch (`32`), version (`9.11.4`), and release (`9.P2.el7`).

When you run the `pkg.installed` state with no epoch, Salt will determine that this distinct version is not installed. It will then run the `pkg.install` function, and salt will end up running `yum -y install $PKGNAME-$VERSION`:

```
% salt-call --local -l info pkg.install bind-libs-lite version=9.11.4 2>&1 | fgrep 'Executing command' | fgrep install
[INFO    ] Executing command [u'yum', u'-y', u'install', u'bind-libs-lite-9.11.4'] in directory '/root'
```

Under the hood, yum is smart enough to figure out that you probably meant `32:9.11.4`, but after installation the `pkg.installed` state will check again using the same logic it did at the beginning, and the versions won't match because you specified a version without an epoch. Therefore, the state fails.

But when `ignore_epoch` is set to `True`, the installation works just fine:

```
[root@14ccc7d087e9 /]# salt-call --local state.single pkg.installed bind-libs-lite version=9.11.4 ignore_epoch=True
local:
----------
          ID: bind-libs-lite
    Function: pkg.installed
      Result: True
     Comment: 1 targeted package was installed/updated.
     Started: 04:24:29.735490
    Duration: 7855.878 ms
     Changes:
              ----------
              GeoIP:
                  ----------
                  new:
                      1.5.0-14.el7
                  old:
              bind-libs-lite:
                  ----------
                  new:
                      32:9.11.4-9.P2.el7
                  old:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   7.856 s
[root@14ccc7d087e9 /]# salt-call --local state.single pkg.installed bind-libs-lite version=9.11.4 ignore_epoch=True
local:
----------
          ID: bind-libs-lite
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed and are at the desired version
     Started: 04:25:25.624182
    Duration: 407.205 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 407.205 ms
```


I suppose there are some tweaks that could be made though, for example ignoring the epoch when `ignore_epoch` is not explicitly set to `True` or `False`, and no epoch is present in the specified version.

However, we must also take into account the fact that version comparison strings could also be used in a version string, and in those cases epochs are _quite_ important. So, any implicit ignoring of epochs could only be done when a specific version is requested.

**Comment by terminalmage** [comment] 2020-04-17 07:58
@saltybaker Have a look at https://github.com/saltstack/salt/pull/56681

**Comment by saltybaker** [comment] 2020-04-17 13:51
if I explicitly use ignore_epoch=True for all oses, will it cause a problem
for oses that do not track epoch?
(especially in versions of salt that we still support, but will not include
#56681 <https://github.com/saltstack/salt/pull/56681>)

   -
   - Robert Baker
   Sr. Software Developer II
      - *■ CISSP*
   - *M: *801.691.9761
   saltstack.com <https://www.saltstack.com/>

**Comment by terminalmage** [comment] 2020-04-17 15:45
All platforms which do not have a specific `version_cmp` function fall back on [this code](https://github.com/saltstack/salt/blob/0b2a561/salt/utils/versions.py#L330-L336), so no, there will be no problem.

I think my pull request from last night will make things a bit easier though because if allows for the formatting of the version number passed to the state to drive epoch handling. One limitation of `ignore_epoch` is that it takes effect for all packages in the state. So, if you use the `pkgs` argument to specify a bunch of packages, you have to either ignore or enforce epochs for all of them.

**Comment by saltybaker** [comment] 2020-04-17 16:27
Do you see an explicit downside to using ignore_epoch=True for oses that
track epoch?

   -
   - Robert Baker
   Sr. Software Developer II
      - *■ CISSP*
   - *M: *801.691.9761
   saltstack.com <https://www.saltstack.com/>

**Comment by terminalmage** [comment] 2020-04-17 16:32
The only downside I could see is that it would make version expressions with `<` or `>` inaccurate.

**Comment by sagetherage** [comment] 2020-05-12 18:04
closing as done in sodium if more work is to be done please comment and mention me, please

**Closed by sagetherage** 2020-05-12 18:04 UTC
Labels: P4, Sodium, State Module
