### ISSUE TITLE
2016.3.0 dockerng state fails comparing cmd configuration

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#33649] opened 2016-05-31 20:07 UTC
### Description of Issue/Question
I upgraded to 2016.3.0 from 2015.8.7 and am trying to start a docker container though the dockerng.running and it fails when trying to compare the cmd value and throws an uncaught exception causing the state to fail.

It will work on the first try but then fail on any subsequent tries. 

### Setup
Assuming the image exists and it has a Cmd specified when you do a docker inspect i.e. `"Cmd": [ "/bin/bash"]` is present when doing a docker inspect of the docker image.
```
Dockerng.running(test,
                name='test',
                hostname=service,
                detach=True,
                tty=True,
                entrypoint='entrypoint.sh',
                privileged=False,
                image='test')
```
Running this will work once as long as the container does not exist but if the container exists then it will fail with the exception.

### Steps to Reproduce Issue
Failure ouput form sate.apply call:
```
          ID: searchalpha_js-sessions
    Function: dockerng.running
        Name: js-sessions.searchalpha
      Result: False
     Comment: Uncaught exception "'NoneType' object is not iterable" encountered while comparing existing container against desired configuration. See minion log for exception info.
     Started: 19:50:53.833510
    Duration: 80.049 ms
     Changes:   
```
Minion log:
```
2016-05-31 19:31:50,263 [salt.loaded.int.states.dockerng][TRACE   ][32355] dockerng.running: comparing command
2016-05-31 19:31:50,263 [salt.loaded.int.states.dockerng][TRACE   ][32355] dockerng.running (command): desired value: [u'/bin/bash']
2016-05-31 19:31:50,263 [salt.loaded.int.states.dockerng][TRACE   ][32355] dockerng.running (command): actual value: None
2016-05-31 19:31:50,263 [salt.loaded.int.states.dockerng][TRACE   ][32355] None
2016-05-31 19:31:50,264 [salt.loaded.int.states.dockerng][ERROR   ][32355] Uncaught exception "'NoneType' object is not iterable" encountered while comparing existing container against desired configuration. Exception info follows:
  File "/usr/local/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1624, in running
    defaults_from_image)
  File "/usr/local/lib/python2.7/dist-packages/salt/states/dockerng.py", line 440, in _compare
    actual_data = sorted(actual_data)
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.23.4
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-71-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by tyhunt99** [comment] 2016-05-31 20:11
Although there is a comment in the code near the line where the exception occurrs:
```
# or "entrypoint" because those are both shell commands and the
# original order matters. It will, however, work for "volumes"
# because even though "volumes" is a sub-dict nested within the
# "actual" dict sorted(somedict) still just gives you a sorted
# list of the dictionary's keys. And we don't care about the
# value for "volumes", just its keys.
actual_data = sorted(actual_data) <-------- exception occurs here
desired_data = sorted(data)
```
Which would indicate command and entrypoint should no be going through this portion of code anyways?

**Comment by Ch3LL** [comment] 2016-06-01 20:15
@tyhunt99 would you mind sharing your state file to help me reproduce this error?

**Comment by developerinlondon** [comment] 2016-06-07 14:57
i have the same issue too. here is my state file:

```
#Run calico-etcd in a container 
# docker run --name calico-etcd -d -v /varetcd:/mnt/master-pd/var/etcd -p 6666:6666 gcr.io/google_containers/etcd:2.2.1 /bin/sh -c "/usr/local/bin/etcd --name=calico-etcd --data-dir=/var/etcd/calico-data --advertise-client-urls=http://kubernetes_master:6666 --listen-client-urls=http://0.0.0.0:6666 --listen-peer-urls=http://0.0.0.0:6660"
python-pip:
  pkg.installed

docker-py:
  pip.installed:
    - require:
      - pkg: python-pip

calico-etcd:
  dockerng.running: 
    - image: gcr.io/google_containers/etcd:2.2.1
    - port_bindings:
      - "6666:6666"
      - "6660:6660"
    - volumes: /mnt/master-pd/var/etcd
    - ports:
      - "6666/tcp"
      - "6660/tcp"
    - entrypoint: /bin/sh -c "/usr/local/bin/etcd --name=calico-etcd --data-dir=/var/etcd/calico-data --advertise-client-urls=http://kubernetes_master:6666 --listen-client-urls=http://0.0.0.0:6666 --listen-peer-urls=http://0.0.0.0:6660"
```

**Comment by ticosax** [comment] 2016-06-08 14:43
@developerinlondon Thank you for the state file.
I submitted a PR against `2016.3` branch. Please, can you give it a try ?

**Comment by Ch3LL** [comment] 2016-06-09 22:28
@ticosax thanks for the PR!! @developerinlondon or @tyhunt99 mind seeing if that PR fixes the issue?

**Comment by tyhunt99** [comment] 2016-06-16 22:03
Sorry for the delay but this has fixed the issue I was seeing.

**Comment by rallytime** [comment] 2016-06-16 22:12
Thanks for the update @tyhunt99! Closing.

**Closed by rallytime** 2016-06-16 22:12 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P4, RIoT, State Module

**Comment by mpaolini** [comment] 2016-06-29 21:45
Looks like this also affects 2015.8.10 ... should it be backported?

```
2016-06-29 21:43:15,532 [salt.loaded.int.states.dockerng][ERROR   ][8542] Uncaught exception "'NoneType' object is not iterable" encountered while comparing existing container against desired configuration. Exception info follows:
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1609, in running
    defaults_from_image)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 438, in _compare
    actual_data = sorted(actual_data)
```

Basically this happens 100% of the times when:

1. there is a running container
2. you apply a `dockerng.running` state that has a `entrypoint` param that is a list

**Comment by mpaolini** [comment] 2016-06-29 21:54
I applied the patch to 2015.8.10 and fixed the issue

**Comment by mpaolini** [comment] 2016-07-11 21:10
ping @rallytime this also affects 2015.8.10, do I need to open a new issue? can it be backported?

**Comment by rallytime** [comment] 2016-07-11 21:32
@mpaolini Oh, nah. I grabbed the backport in #34593.

**Comment by mpaolini** [comment] 2016-07-11 21:35
@rallytime Thanks!
