### ISSUE TITLE
States Failing Sometimes:  "Recurse failed: none of the specified sources were found"

### ISSUE THREAD

**Issue by rafamarangoni** [saltstack/salt#22040] opened 2015-03-26 14:08 UTC
Hi guys,

First of all, I want to congratulate all the community of SaltStack. It's a great tool, and we're using it since a few months ago on various implementations on AWS.

Now, we are running saltstack on more than 20 projects, always with 1 or 2 salt-masters and a lot of minions. Always with CentOS6/7 and installing salt from epel repository.

Since we updated SaltStack to version 2014.1, we started getting some issues on states using file.recurse sometimes. When we run the state we got a lot of "Recurse failed: none of the specified sources were found". All the files are stored on salt-master. 

Some statements that may lead us to a solution:

1. If I run like 10 times the state, just 1 or 2 times I got this issue. Appears that salt-minion get the state, tries to fetch the file on salt-master, and can not do that.
That's much worse then getting the issue everytime. Because we can't trust on the system.

2. we got the same behavior running the state from master to minion (using salt command), and from minion to master (using salt-call command).

3. It's not a fixed state that we got this issue (neither a fixed server). Sometimes happens with one state, sometimes another. The only common thing between all the states is that they all have file.recurse. States with no file.recurse we never have the issue.

4. We tried to update to salt version 2014.2, using the command:
yum --enablerepo=epel-testing install salt-master
But this not changed the behavior.

5. The same behavior is happening with different projects for us. Every project is isolated, with different salt-masters and minions. That's the main thing for us, and why we believe that is a bug.

Here goes a full output of the issue. We ran the following command for a state that configures php-fpm, fetching a few files on salt-master. With this output, you got the state (init.sls), and error at the end.

Thanks for your help in advanced.
```
[root@ip-172-31-41-254 ~]# salt-call state.sls php-php-fpm prod --log-file=/tmp/salt-test.log -l all
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/masters.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/masters.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: php-prod---ip-172-31-41-254.sa-east-1.compute.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/masters.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/masters.conf
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Mako not available
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/masters.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/masters.conf
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] Fetching file from saltenv 'prod', ** attempting ** 'salt://php-php-fpm.sls'
[INFO    ] Fetching file from saltenv 'prod', ** skipped ** latest already in cache 'salt://php-php-fpm/init.sls'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/prod']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/prod/php-php-fpm/init.sls:
/etc/php.ini:
  file.managed:
    - source:
      - salt://php-php-fpm/files/php.ini
    - mode: 644

/etc/sysconfig/php-fpm:
  file.managed:
    - source:
      - salt://php-php-fpm/files/php-fpm-sysconfig
    - mode: 644

/etc/php.d:
  file.recurse:
    - source: salt://php-php-fpm/files/php.d
    - include_empty: True
#    - clean: True
    - file_mode: 655
    - dir_mode: 655

/etc/php-fpm.conf:
  file.managed:
    - source:
      - salt://php-php-fpm/files/php-fpm.conf
    - mode: 644

/etc/php-fpm.d:
  file.recurse:
    - source: salt://php-php-fpm/files/php-fpm.d
    - include_empty: True
    - clean: True
    - file_mode: 644
    - dir_mode: 644


# Diretorio temp do PHP
/mnt/md0/php-tmp:
  file.directory:
    - user: nginx
    - group: nginx
    - mode: 755
    - makedirs: True

# Diretorio log do php
/mnt/md0/log/php:
  file.directory:
    - user: nginx
    - group: nginx
    - mode: 755
    - makedirs: True


# Servico do php-fpm
# restarta apenas se houver alteracao nos arquivos
php-fpm:
  service:
    - running
    - enable: True
    - watch:
      - file: /etc/php.ini
      - file: /etc/php-fpm.conf
      - file: /etc/php.d
      - file: /etc/php-fpm.d
      - file: /etc/sysconfig/php-fpm

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('/etc/php.ini', OrderedDict([('file.managed', [OrderedDict([('source', ['salt://php-php-fpm/files/php.ini'])]), OrderedDict([('mode', 644)])])])), ('/etc/sysconfig/php-fpm', OrderedDict([('file.managed', [OrderedDict([('source', ['salt://php-php-fpm/files/php-fpm-sysconfig'])]), OrderedDict([('mode', 644)])])])), ('/etc/php.d', OrderedDict([('file.recurse', [OrderedDict([('source', 'salt://php-php-fpm/files/php.d')]), OrderedDict([('include_empty', True)]), OrderedDict([('file_mode', 655)]), OrderedDict([('dir_mode', 655)])])])), ('/etc/php-fpm.conf', OrderedDict([('file.managed', [OrderedDict([('source', ['salt://php-php-fpm/files/php-fpm.conf'])]), OrderedDict([('mode', 644)])])])), ('/etc/php-fpm.d', OrderedDict([('file.recurse', [OrderedDict([('source', 'salt://php-php-fpm/files/php-fpm.d')]), OrderedDict([('include_empty', True)]), OrderedDict([('clean', True)]), OrderedDict([('file_mode', 644)]), OrderedDict([('dir_mode', 644)])])])), ('/mnt/md0/php-tmp', OrderedDict([('file.directory', [OrderedDict([('user', 'nginx')]), OrderedDict([('group', 'nginx')]), OrderedDict([('mode', 755)]), OrderedDict([('makedirs', True)])])])), ('/mnt/md0/log/php', OrderedDict([('file.directory', [OrderedDict([('user', 'nginx')]), OrderedDict([('group', 'nginx')]), OrderedDict([('mode', 755)]), OrderedDict([('makedirs', True)])])])), ('php-fpm', OrderedDict([('service', ['running', OrderedDict([('enable', True)]), OrderedDict([('watch', [OrderedDict([('file', '/etc/php.ini')]), OrderedDict([('file', '/etc/php-fpm.conf')]), OrderedDict([('file', '/etc/php.d')]), OrderedDict([('file', '/etc/php-fpm.d')]), OrderedDict([('file', '/etc/sysconfig/php-fpm')])])])])]))])
[INFO    ] Running state [/etc/php.ini] at time 13:35:15.322485
[INFO    ] Executing state file.managed for /etc/php.ini
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] File /etc/php.ini is in the correct state
[INFO    ] Completed state [/etc/php.ini] at time 13:35:15.810549
[INFO    ] Running state [/etc/sysconfig/php-fpm] at time 13:35:15.810857
[INFO    ] Executing state file.managed for /etc/sysconfig/php-fpm
[ERROR   ] Unable to manage file: none of the specified sources were found
[INFO    ] Completed state [/etc/sysconfig/php-fpm] at time 13:35:16.264091
[INFO    ] Running state [/etc/php.d] at time 13:35:16.264444
[INFO    ] Executing state file.recurse for /etc/php.d
[ERROR   ] Recurse failed: none of the specified sources were found
[INFO    ] Completed state [/etc/php.d] at time 13:35:16.276525
[INFO    ] Running state [/etc/php-fpm.conf] at time 13:35:16.276914
[INFO    ] Executing state file.managed for /etc/php-fpm.conf
[ERROR   ] Unable to manage file: none of the specified sources were found
[INFO    ] Completed state [/etc/php-fpm.conf] at time 13:35:17.027596
[INFO    ] Running state [/etc/php-fpm.d] at time 13:35:17.027858
[INFO    ] Executing state file.recurse for /etc/php-fpm.d
[ERROR   ] Recurse failed: none of the specified sources were found
[INFO    ] Completed state [/etc/php-fpm.d] at time 13:35:17.549932
[INFO    ] Running state [/mnt/md0/php-tmp] at time 13:35:17.550171
[INFO    ] Executing state file.directory for /mnt/md0/php-tmp
[INFO    ] Directory /mnt/md0/php-tmp is in the correct state
[INFO    ] Completed state [/mnt/md0/php-tmp] at time 13:35:17.551508
[INFO    ] Running state [/mnt/md0/log/php] at time 13:35:17.551736
[INFO    ] Executing state file.directory for /mnt/md0/log/php
[INFO    ] Directory /mnt/md0/log/php is in the correct state
[INFO    ] Completed state [/mnt/md0/log/php] at time 13:35:17.553011
[DEBUG   ] File /var/cache/salt/minion/accumulator/73266064 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded .returner
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[TRACE   ] data = {'local': {'file_|-/mnt/md0/php-tmp_|-/mnt/md0/php-tmp_|-directory': {'comment': 'Directory /mnt/md0/php-tmp is in the correct state', 'name': '/mnt/md0/php-tmp', 'start_time': '13:35:17.550171', 'result': True, 'duration': u'1.337 ms', '__run_num__': 5, 'changes': {}}, 'service_|-php-fpm_|-php-fpm_|-running': {'comment': "One or more requisite failed: {'php-php-fpm./etc/php-fpm.d': 'Recurse failed: none of the specified sources were found', 'php-php-fpm./etc/sysconfig/php-fpm': 'Unable to manage file: none of the specified sources were found', 'php-php-fpm./etc/php.d': 'Recurse failed: none of the specified sources were found', 'php-php-fpm./etc/php-fpm.conf': 'Unable to manage file: none of the specified sources were found'}", 'start_time': u'', 'result': False, 'duration': u'', '__run_num__': 7, '__sls__': 'php-php-fpm', 'changes': {}}, 'file_|-/etc/php-fpm.conf_|-/etc/php-fpm.conf_|-managed': {'comment': 'Unable to manage file: none of the specified sources were found', 'name': '/etc/php-fpm.conf', 'start_time': '13:35:16.276914', 'result': False, 'duration': u'750.682 ms', '__run_num__': 3, 'changes': {}}, 'file_|-/etc/php.ini_|-/etc/php.ini_|-managed': {'comment': 'File /etc/php.ini is in the correct state', 'name': '/etc/php.ini', 'start_time': '13:35:15.322485', 'result': True, 'duration': u'488.064 ms', '__run_num__': 0, 'changes': {}}, 'file_|-/etc/sysconfig/php-fpm_|-/etc/sysconfig/php-fpm_|-managed': {'comment': 'Unable to manage file: none of the specified sources were found', 'name': '/etc/sysconfig/php-fpm', 'start_time': '13:35:15.810857', 'result': False, 'duration': u'453.234 ms', '__run_num__': 1, 'changes': {}}, 'file_|-/etc/php-fpm.d_|-/etc/php-fpm.d_|-recurse': {'comment': 'Recurse failed: none of the specified sources were found', 'name': '/etc/php-fpm.d', 'start_time': '13:35:17.027858', 'result': False, 'duration': u'522.074 ms', '__run_num__': 4, 'changes': {}}, 'file_|-/mnt/md0/log/php_|-/mnt/md0/log/php_|-directory': {'comment': 'Directory /mnt/md0/log/php is in the correct state', 'name': '/mnt/md0/log/php', 'start_time': '13:35:17.551736', 'result': True, 'duration': u'1.275 ms', '__run_num__': 6, 'changes': {}}, 'file_|-/etc/php.d_|-/etc/php.d_|-recurse': {'comment': 'Recurse failed: none of the specified sources were found', 'name': '/etc/php.d', 'start_time': '13:35:16.264444', 'result': False, 'duration': u'12.081 ms', '__run_num__': 2, 'changes': {}}}}
local:
----------
          ID: /etc/php.ini
    Function: file.managed
      Result: True
     Comment: File /etc/php.ini is in the correct state
     Started: 13:35:15.322485
    Duration: 488.064 ms
     Changes:   
----------
          ID: /etc/sysconfig/php-fpm
    Function: file.managed
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 13:35:15.810857
    Duration: 453.234 ms
     Changes:   
----------
          ID: /etc/php.d
    Function: file.recurse
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 13:35:16.264444
    Duration: 12.081 ms
     Changes:   
----------
          ID: /etc/php-fpm.conf
    Function: file.managed
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 13:35:16.276914
    Duration: 750.682 ms
     Changes:   
----------
          ID: /etc/php-fpm.d
    Function: file.recurse
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 13:35:17.027858
    Duration: 522.074 ms
     Changes:   
----------
          ID: /mnt/md0/php-tmp
    Function: file.directory
      Result: True
     Comment: Directory /mnt/md0/php-tmp is in the correct state
     Started: 13:35:17.550171
    Duration: 1.337 ms
     Changes:   
----------
          ID: /mnt/md0/log/php
    Function: file.directory
      Result: True
     Comment: Directory /mnt/md0/log/php is in the correct state
     Started: 13:35:17.551736
    Duration: 1.275 ms
     Changes:   
----------
          ID: php-fpm
    Function: service.running
      Result: False
     Comment: One or more requisite failed: {'php-php-fpm./etc/php-fpm.d': 'Recurse failed: none of the specified sources were found', 'php-php-fpm./etc/sysconfig/php-fpm': 'Unable to manage file: none of the specified sources were found', 'php-php-fpm./etc/php.d': 'Recurse failed: none of the specified sources were found', 'php-php-fpm./etc/php-fpm.conf': 'Unable to manage file: none of the specified sources were found'}
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 3
Failed:    5
------------
Total states run:     8

```

**Comment by basepi** [comment] 2015-03-26 22:23
> We tried to update to salt version 2014.2, using the command:

Can you clarify which version was installed here? I'm guessing 2014.7.2, because 2014.2 is not a real salt version.

Additionally, can you include any configuration related to the fileserver you have? Configuration like `fileserver_backend`, `file_roots`, and any `gitfs` configuration if you're using gitfs.

**Comment by basepi** [comment] 2015-03-26 22:24
Oh, and I should mention that unless we explicitly ask, you should stick to the `debug` log-level -- `trace` tends to be pretty unreadable, it has so much information.

**Comment by rafamarangoni** [comment] 2015-03-27 13:33
Hello,

I understand about the log-level. So, no more traces in the future.

The version is 2014.7.2: 
[root@salt2 ~]# rpm -qa | grep salt-master
salt-master-2014.7.2-1.el6.noarch

(but we got the same issue in 2014.7.1)

I'm using file_roots in the salt masters:

Here is goes:

file_roots:
 base:
 - /srv/salt/base
 prod:
 - /srv/salt/prod
 dev:
 - /srv/salt/dev

Thanks!

**Comment by basepi** [comment] 2015-03-27 22:39
To verify, you're not using any non-default `fileserver_backend` setting, correct?

Very strange. Is your master under heavy load?

**Comment by rafamarangoni** [comment] 2015-03-27 23:15
Hello, 

That's right: no fileserver backend.

And the master servers (on every project we have 2 masters) are running fine, with just 5% of cpu. We run on aws ec2, size m3.medium for them.

Thanjs


Rafael

<div>-------- Mensagem original --------</div><div>De : Colton Myers <notifications@github.com> </div><div>Data:27/03/2015  19:39  (GMT-03:00) </div><div>Para: saltstack/salt <salt@noreply.github.com> </div><div>Cc: rafamarangoni <rafael.marangoni@brlink.com.br> </div><div>Assunto: Re: [salt] States Failing Sometimes:  "Recurse failed: none of the specified sources were found" (#22040) </div><div>
</div>To verify, you're not using any non-default fileserver_backend setting, correct?

Very strange. Is your master under heavy load?

**Comment by basepi** [comment] 2015-03-27 23:19
Ah, that's good to note, this could potentially be a multi-master issue.

**Comment by rafamarangoni** [comment] 2015-03-27 23:33
Colton,

One thing is that the same issue happens if we add --master on salt-call command line.




<div>-------- Mensagem original --------</div><div>De : Colton Myers <notifications@github.com> </div><div>Data:27/03/2015  20:19  (GMT-03:00) </div><div>Para: saltstack/salt <salt@noreply.github.com> </div><div>Cc: rafamarangoni <rafael.marangoni@brlink.com.br> </div><div>Assunto: Re: [salt] States Failing Sometimes:  "Recurse failed: none of the specified sources were found" (#22040) </div><div>
</div>Ah, that's good to note, this could potentially be a multi-master issue.

**Comment by rafamarangoni** [comment] 2015-03-31 19:21
Sorry, but, any news os sugestions?

**Comment by basepi** [comment] 2015-03-31 22:11
Unfortunately we haven't had a chance to investigate this further yet. It's going to be a beast to debug, I think, because I'm guessing it will be hard to reproduce.

**Comment by rafamarangoni** [comment] 2015-04-01 12:01
I understand Colton. Do you have any suggestion for work around?

**Comment by basepi** [comment] 2015-04-01 18:39
You might test on one of the 2015.2 release candidates (we're hoping to have v2015.2.0rc2 out in the next day or two), see if things are better there. Otherwise I'm stumped at the moment.

**Comment by basepi** [comment] 2015-04-01 20:33
Could you also add some debug logs from the minion with these problems occurring?

**Comment by rafamarangoni** [comment] 2015-04-02 12:49
those logs above are from the minion, running the salt-call. Is that ok? Do you need any other specific log?

About upgrading to 2015.2: I'm using yum/EPEL, and this version is not available yet. What's the best to install 2015.2 over the 2014.7.2 installed  by YUM/EPEL?

**Comment by basepi** [comment] 2015-04-02 17:07
You're right, they are indeed minion logs, sorry for my confusion.

The easiest way is to just use the [bootstrap script](https://github.com/saltstack/salt-bootstrap), and target a git tag for one of the release candidates. Looks like RC2 isn't quite up yet, but I'm hopeful it will go up later today.

```
sh salt-bootstrap.sh git v2015.2.0rc2
```

I'm mostly frustrated that there's not more in the logs....is there anything of interest in the master debug logs when this problem occurs?

**Comment by rafamarangoni** [comment] 2015-04-06 13:16
Thanks. 
Just to be sure: should I remove the old packages (yum remove salt*) before running the bootstrap script?

**Comment by basepi** [comment] 2015-04-06 16:26
As far as I know, there's actually no need. Bootstrap will just overwrite the files in `python2.7/dist-packages`. But removing the old packages also won't hurt.

**Comment by rafamarangoni** [comment] 2015-04-08 22:14
I tried to update to 2015.2 but the same thing happened. 

Maybe using another file backend? 

I suspect that can be a multimaster problem.

**Comment by basepi** [comment] 2015-04-16 21:05
Ah, you're using multiple masters? That may indeed be the problem. Can you reproduce this with only a single master?

**Comment by rafamarangoni** [comment] 2015-04-17 20:18
Hi! That's it! The problem don't happen when using just one master. I think that's a big clue. 

We use 2 masters because we need to support High Availability environments, and if the salt-master fails, our autoscaling servers can't be bootstrapped.

**Comment by basepi** [comment] 2015-04-20 17:23
Awesome! That should help a lot with reproducing and fixing this.

**Comment by rafamarangoni** [comment] 2015-05-16 00:45
Any news about your tests with 2 masters? Thanks

**Comment by tiger-seo** [comment] 2015-05-21 00:00
i'm having this to and i have only one master

**Comment by ssgward** [comment] 2015-07-29 17:17
Looks like this is fixed. Closing.

**Closed by ssgward** 2015-07-29 17:17 UTC
Labels: Beryllium, Bug, Fixed Pending Verification, High Severity, P4, Platform, State Module

**Comment by stardust85** [comment] 2016-06-20 18:55
I got this error when parent directory was missing.

**Comment by danielbjornadal** [comment] 2016-06-22 07:51
I have the same problem on the latest release:
```
$ salt --version
salt 2016.3.0 (Boron)
$ uname -a
Linux saltmaster 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
```

```
$ cat /srv/salt/logrotate/init.sls 
logrotate:
  pkg.latest:
    - name: {{ logrotate.pkg }}

logrotate_conf:
  file.managed:
    - name: /etc/logrotate.conf
    - source: salt://logrotate/files/logtotate.conf
    - user: root
    - group: root
    - mode: 644

logrotate_d:
  file.recurse:
    - name: /etc/logrotate.d  
    - source: salt://logrotate/files/logtotate.d
```

```
$ ls -laR /srv/salt/logrotate/files/
/srv/salt/logrotate/files/:
total 16
drwxr-xr-x 3 root root 4096 Jun 22 09:48 .
drwxr-xr-x 3 root root 4096 Jun 22 09:48 ..
-rw-r--r-- 1 root root  214 Jun 22 09:12 logrotate.conf
drwxr-xr-x 2 root root 4096 Jun 22 09:25 logrotate.d

/srv/salt/logrotate/files/logrotate.d:
total 48
drwxr-xr-x 2 root root 4096 Jun 22 09:25 .
drwxr-xr-x 3 root root 4096 Jun 22 09:48 ..
-rw-r--r-- 1 root root  173 Jun 22 09:25 apt
-rw-r--r-- 1 root root   79 Jun 22 09:25 aptitude
-rw-r--r-- 1 root root  232 Jun 22 09:25 dpkg
-rw-r--r-- 1 root root  146 Jun 22 09:25 exim4-base
-rw-r--r-- 1 root root  126 Jun 22 09:25 exim4-paniclog
-rw-r--r-- 1 root root  515 Jun 22 09:25 rsyslog
-rw-r--r-- 1 root root  227 Jun 22 09:25 salt-common
-rw-r--r-- 1 root root  321 Jun 22 09:25 samba
-rw-r--r-- 1 root root  235 Jun 22 09:25 unattended-upgrades
-rw-r--r-- 1 root root  191 Jun 22 09:25 winbind
```

ID: logrotate_d
Function: file.recurse
Name: /etc/logrotate.d
Result: False
Comment: Recurse failed: none of the specified sources were found
Started: 09:49:21.134663
Duration: 4.906 ms
Changes: 

[INFO    ] Executing state file.recurse for /etc/logrotate.d
[ERROR   ] Recurse failed: none of the specified sources were found
