### ISSUE TITLE
pkg.install with version=latest is broken in 2016.11.4

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#42318] opened 2017-07-14 22:44 UTC
### Setup

```yaml
# dig is in dnsutils
dnsutils:
  pkg.installed:
    - version: {{ salt.pillar.get('dnsutils:version', 'latest') }}
```

### Steps to Reproduce Issue

* Test run:

```
local:
----------
          ID: dnsutils
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: dnsutils=1:9.10.3.dfsg.P4-12.3+deb9u1
     Started: 22:38:43.087526
    Duration: 1853.056 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.853 s
```

Actual run:

```
local:
----------
          ID: dnsutils
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:

              errors:
                  - Running scope as unit: run-r2e4db2d3792b42a39ddb33d40daf291c.scope
                    E: Version 'latest' for 'dnsutils' was not found
     Started: 22:37:28.254254
    Duration: 7749.808 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   7.750 s
```

At the same time `pkg.latest` is working as expected:

```
$ salt-call pkg.latest_version dnsutils
local:
    1:9.10.3.dfsg.P4-12.3+deb9u1
```

From what I can see we resolve `latest` to actual versions here:

* https://github.com/saltstack/salt/blob/afc61ffe6377/salt/states/pkg.py#L1267-L1275

but then we just ignore what we resolved and pass `latest`:

* https://github.com/saltstack/salt/blob/afc61ffe6377/salt/states/pkg.py#L1419

Probably related to this:

* https://github.com/saltstack/salt/commit/92011dbe5fddaa9a8079aef57fcf792eb9528571

### Versions Report

```
$ salt-call --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.0
        machine: x86_64
        release: 4.9.36-moby
         system: Linux
        version: debian 9.0
```

**Comment by gtmanfred** [comment] 2017-07-15 15:51
This appears to be a duplicate of #42194

**Closed** 2017-07-15 15:52 UTC
Labels: Duplicate

**Comment by bobrik** [comment] 2017-07-15 17:52
@gtmanfred thanks, indeed. The title is yum specific there, so I skipped it during my initial search.
