### ISSUE TITLE
digital_ocean_v2.py doesn't restore snapshot

### ISSUE THREAD

**Issue by ty2u** [saltstack/salt#22724] opened 2015-04-15 22:44 UTC
Hey,

I'm wondering if someone can help me figure this out.

I made a snapshot of a server and I am trying to restore it via the digital_ocean_v2.py but it's not working properly.

The name of the snapshot in the example is server.example.com

Debug output of command:
salt-cloud -p server.example.com server.example.com
https://gist.github.com/ty2u/f48557e6c4bd56723f25

server.example.com profile:
```
server.example.com:
    provider: do
    image: server.example.com
    size: 4gb
    location: New York 3
    private_networking: True
    backups_enabled: False
    ipv6: False
    create_dns_record: True
    delete_dns_record: True
```

salt --versions-report
```
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
```

If I modify the digital_ocean_v2.py script to use the image id number instead of the name it will actually launch the server but still seems to display errors. I did this by replacing lines 226-229:

```python
        if vm_image in (images[image]['name'], images[image]['slug'], images[image]['id']):
            if images[image]['slug'] is not None:
                return images[image]['slug']
            return int(images[image]['id'])
```

with

```python
        if vm_image in (images[image]['id']):
            return int(images[image]['id'])
```

Furthermore, the ssh key is not valid, I think when the server has a different IP address sometimes.

**Comment by ty2u** [comment] 2015-04-15 22:51
Here is the output with the modification I made:
https://gist.github.com/ty2u/a398531662cf7799c180

**Comment by rallytime** [comment] 2015-04-15 23:16
@ty2u I suspect we just haven't implemented this kind of functionality yet, but i'm sure it can be done.

ping @techhat and @wesleylancel

**Comment by dmyerscough** [comment] 2015-04-16 04:41
I was looking into getting the snapshot functionality added soon

**Comment by ty2u** [comment] 2015-04-16 07:02
Yay! Thank you for the awesomeness everyone =)

**Comment by pravka** [comment] 2015-09-01 14:49
@dmyerscough are you close to getting snapshot integration working? I can take a stab if you want.

**Comment by twangboy** [comment] 2015-09-08 20:25
@ty2u @pravka @dmyerscough Did #26824 fix the issue of getting snapshots working in digital ocean?

**Comment by pravka** [comment] 2015-09-11 17:40
Works for me; salt-cloud creates droplet from a snap and uses the right ssh key. I'd still prefer for salt-cloud to be aware that private_networking is enabled and give you the option of using that to provision, but I'll be opening a separate issue for that.

**Comment by rallytime** [comment] 2015-09-11 18:17
@pravka Yeah, a separate issue for the private_networking option would be great. Since this is confirmed to be working, I am going to go a head a close this. If there are any other troubles here, let us know and we can re-open. Thanks everyone!

**Closed by rallytime** 2015-09-11 18:17 UTC
Labels: Feature, Fixed Pending Verification, RIoT, Salt-Cloud
