### ISSUE TITLE
State is applied despite test=true

### ISSUE THREAD

**Issue by LuboVarga** [saltstack/salt#35651] opened 2016-08-22 09:06 UTC
### Description of Issue/Question

when running salt with these parameters:
state.highstate --state-output=changes test=True

In summary it will print for example:
[endurance] Succeeded: 65 (unchanged=2, changed=2)
[endurance] Failed:     0
### Steps to Reproduce Issue

I think, any change in salt will trigger this.
### Versions Report

salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed

System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.3.1.el6.x86_64
         system: CentOS 6.5 Final

**Comment by thatch45** [comment] 2016-08-22 18:22
We need to know what states are being applied, so we need to see the output from the states that applied changes

**Comment by LuboVarga** [comment] 2016-08-23 05:41
I can right now give only examples of file.managed state. I can not find right now other ones. I will append any additional problematic state when I find them. I will give here only applied part and summarie (if it is not enough, please write me). Btw, I have feeling, that they are also applied when state-output parameter is not in use. I have thought that that was cause of problem.

```
[acct] ----------
[acct]           ID: logrotate
[acct]     Function: file.managed
[acct]         Name: /etc/logrotate.d/td-agent
[acct]       Result: None
[acct]      Comment: The file /etc/logrotate.d/td-agent is set to be changed
[acct]      Started: 13:18:45.489870
[acct]     Duration: 43.398 ms
[acct]      Changes:   
[acct]               ----------
[acct]               diff:
[acct]                   ---  
[acct]                   +++  
[acct]                   @@ -1,6 +1,6 @@
[acct]                    /var/log/td-agent/td-agent.log {
[acct]                   -  daily
[acct]                   -  rotate 30
[acct]                   +  size 100M
[acct]                   +  rotate 10
[acct]                      compress
[acct]                      delaycompress
[acct]                      notifempty
[acct]                   @@ -10,4 +10,4 @@
[acct]                        pid=/var/run/td-agent/td-agent.pid
[acct]                        test -s $pid && kill -USR1 "$(cat $pid)"
[acct]                      endscript
[acct]                   -}
[acct]                   +}
[acct] ----------

[acct] 
[acct] Summary for somehost1.somedomain.sk
[acct] -------------
[acct] Succeeded: 33 (unchanged=3, changed=1)
[acct] Failed:     0
[acct] -------------
```

**Comment by thatch45** [comment] 2016-08-23 15:54
@Ch3LL this should be fixed, but I bet the issue is that we are posting the changes that will be made and are not really changing the file, but both cases should be verified

**Comment by LuboVarga** [comment] 2016-08-24 05:04
Today I will test it and write here if it is so.

IMHO there could be some problem, when same file is modified by multiple states in some order (we have such bugs sometimes in our sls files).

**Comment by lorengordon** [comment] 2016-08-24 11:56
I actually like when `test=True` identifies the changes that _would_ be made in the diff.

I think the logic is something like `if changes, increment changed`, and some states populate `changes` with the diff even in a test run. So the test is true, which ends up counting the test run as a changed state.

Maybe just add a note to the summary when `test=True`, saying something like "Test=true, so `changed` is only reporting the number of states that _would_ be changed"?

**Comment by LuboVarga** [comment] 2016-08-24 13:09
> Maybe just add a note to the summary when test=True, saying something like "Test=true, so changed is only reporting the number of states that would be changed"?

I have thought that "unchanged" is how many would be changed if not in test. Definitely this needs better clarification directly in summary output.

PS: I also like the diff output what changes would be made. It is sort of dry-run for me to see, what can potentially broke after highstate and prepare for it.

**Comment by Ch3LL** [comment] 2016-08-24 19:32
Okay so I am able to replicate this behavior but on only the 2015.8 branch. This is actually working correctly on the 2016.3 branch. 

Given the following state:

```
[ch3ll@thecakeisalie salt]$ cat /srv/salt/issues/35651.sls
test:
  file.managed:
    - name: /tmp/testissue
    - content: 'yeah'
```

And top file:

```
[ch3ll@thecakeisalie salt]$ cat /srv/salt/top.sls 
base:
  '*':
    - issues.35651
```

2016.3.2 output:

```
[ch3ll@thecakeisalie salt]$ salt --version
salt 2016.3.2 (Boron)
[ch3ll@thecakeisalie salt]$ sudo salt '*the*'  state.highstate --state-output=changes test=True
thecakeisalie:
----------
          ID: test
    Function: file.managed
        Name: /tmp/testissue
      Result: None
     Comment: The file /tmp/testissue is set to be changed
     Started: 13:28:25.751579
    Duration: 6.637 ms
     Changes:   

Summary for thecakeisalie
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
```

2015.8.11 output:

```
[ch3ll@thecakeisalie salt]$ salt --version
salt 2015.8.11 (Beryllium)
[ch3ll@thecakeisalie salt]$ sudo salt '*the*'  state.highstate --state-output=changes test=True
thecakeisalie:
----------
          ID: test
    Function: file.managed
        Name: /tmp/testissue
      Result: None
     Comment: The file /tmp/testissue is set to be changed
     Started: 13:29:47.245547
    Duration: 32.348 ms
     Changes:   
              ----------
              newfile:
                  /tmp/testissue

Summary for thecakeisalie
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1
```

As shown above this issue is only on the 2015.8 branch and is fixed in 2016.3. As noted earlier, it doesn't actually change the file but is just reporting incorrectly.

and also for the record this is the case even if you remove `--state-output` on 2015.8:

```
[ch3ll@thecakeisalie salt]$ sudo salt '*the*'  state.highstate test=True
thecakeisalie:
----------
          ID: test
    Function: file.managed
        Name: /tmp/testissue
      Result: None
     Comment: The file /tmp/testissue is set to be changed
     Started: 13:30:17.496760
    Duration: 7.177 ms
     Changes:   
              ----------
              newfile:
                  /tmp/testissue

Summary for thecakeisalie
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1
```

**Comment by Ch3LL** [comment] 2016-08-24 19:38
@LuboVarga since this is fixed in 2016.3 are you okay to close this issue? Or maybe you want to verify it is working on your end as well on 2016.3?

**Comment by LuboVarga** [comment] 2016-08-25 05:42
If it is matter of updating salt-minion (client), I will try to test it (I hope that updating client in my virtual centos would be fine), but upgrading master would be hard for me in some reasonable time (so you probably should close this issue).

It is enough to test your fix by updating client/minion only?

**Comment by LuboVarga** [comment] 2016-08-26 09:31
I have upgraded to latest develop (I believe) version. I am not able to check if issue is fixed, as output of salt command has changed a lot.

```
salt-call --version
salt-call 2016.3.2-4386-g6784cb0 (Boron)
```

Current output does not have summary where changed and unchanged is printed. There are "changes:" and sometimes "pchanges:". When I remove `--state-output=changes` parameter and run highstate with only test=True parameter, summary is there and it is wrong (just relevant changed state and tail of output):

```
salt-call state.highstate test=True

----------
          ID: json.dashboard.request.for.instance-kafka-vagrant-vagrant-backend:8183
    Function: file.managed
        Name: /usr/share/grafana/public/dashboards/kafka-vagrant-vagrant-backend:8183.json.dashboard.request
      Result: None
     Comment: The file /usr/share/grafana/public/dashboards/kafka-vagrant-vagrant-backend:8183.json.dashboard.request is set to be changed
     Started: 11:29:46.125477
    Duration: 12.117 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,4 +1,4 @@
                   {
                  -    "dashboard": {},
                  +    "dashboard": {asdf},
                       "overwrite": true
                   }
----------
          ID: grafana-server-installation-and-run
    Function: service.running
        Name: grafana-server
      Result: True
     Comment: The service grafana-server is already running
     Started: 11:29:58.760786
    Duration: 20.203 ms
     Changes:   

Summary for local
-------------
Succeeded: 76 (unchanged=2, changed=1)
Failed:     0
-------------
Total states run:     76
Total run time:   13.924 s
```

**Closed** 2016-11-11 18:41 UTC
Labels: Bug, Core, Fixed Pending Verification, Medium Severity, P2
