### ISSUE TITLE
[BUG] Opening an issue causes a CI failure

### ISSUE THREAD

**Issue by DaAwesomeP** [saltstack/salt#64297] opened 2023-05-17 23:08 UTC
**Description**
Whenever an issue is opened the issue author receives a "run failed" notification from GitHub. This is from the "New Issues Triage Assignment" action.

For example, see this failed run: https://github.com/saltstack/salt/actions/runs/5008666986

**Setup**
N/A

**Steps to Reproduce the behavior**
Open an issue to this repo, then wait at most 5 minutes. You will get as GitHub notification that a run has failed.

**Expected behavior**
CI runner should not fail/notify on each issue opened.

**Screenshots**
N/A

**Versions Report**
N/A

**Additional context**
N/A

**Comment by s0undt3ch** [comment] 2023-05-22 06:31
Duplicate of https://github.com/saltstack/salt/issues/63831

**Closed by s0undt3ch** 2023-05-22 06:31 UTC
Labels: Bug, needs-triage
