### ISSUE TITLE
Dockerng does not properly generate host_config dict

### ISSUE THREAD

**Issue by fxdgear** [saltstack/salt#36544] opened 2016-09-23 22:18 UTC
### Description of Issue/Question

When attempting to bind mount the docker socket in a docker container on the `dockerng.create` function I get an error about string object has not attribute 'items'. 

I think this is a result of the create function not properly parsing the bind information (as declared in the doc string) and as such fails to create a host config object. 

### Setup

Simple instance of minion with docker installed. 

### Steps to Reproduce Issue

```bash
sudo salt minion dockerng.create alpine name=test binds="/var/run/docker.sock:/var/run/docker.sock"

    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 663, in wrapper
        returned = wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
      File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2966, in create
        **dict((arg, create_kwargs.pop(arg, None)) for arg in host_config_args if arg != 'version')
      File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 157, in create_host_config
        return utils.create_host_config(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 749, in create_host_config
        host_config['Binds'] = convert_volume_binds(binds)
      File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 301, in convert_volume_binds
        for k, v in binds.items():
    AttributeError: 'str' object has no attribute 'items'
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

minion:
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-96-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

master:
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 1.8.2
       cherrypy: 8.1.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-38-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment] 2016-09-27 16:02
@fxdgear looks like this is a duplicate of #30597 . If you try the suggestion in the comments on that issue does that help resolve the issue?

**Comment by Ch3LL** [comment] 2016-09-28 18:06
Closing due to duplicate and there is a solution in the issue posted above.

**Closed by Ch3LL** 2016-09-28 18:06 UTC
Labels: Duplicate, Info Needed
