### ISSUE TITLE
Salt version 2018.3.0.1.el7 broken on RHEL 7

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#47088] opened 2018-04-16 04:07 UTC
### Description of Issue/Question

I keep getting this error when trying to connect a minion to the master.  Key error.  I have deleted teh key on the client and restarted it.  Also updated the salt master and the minion's key seems to be accepted by salt.  

###=======
```
[ERROR   ] Error while bringing up minion for multi-master. Is master at salt responding?
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Master URI: tcp://10.100.32.67:4506
[DEBUG   ] Re-using AsyncAuth for (u'/etc/salt/pki/minion', u'vuwunicoedwdbd2.ods.vuw.ac.nz', u'tcp://10.100.32.67:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (3635)
[DEBUG   ] Setting zmq_reconnect_ivl to '3635ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'vuwunicoedwdbd2.ods.vuw.ac.nz', u'tcp://10.100.32.67:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.100.32.67:4506
[DEBUG   ] Trying to connect to: tcp://10.100.32.67:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2018.3.0, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
[ERROR   ] Error while bringing up minion for multi-master. Is master at salt responding?
[DEBUG   ] Connecting to master. Attempt 1 of 1
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

[root@vuwunicorhsat01 salt]# rpm -q salt-master
salt-master-2018.3.0-1.el7.noarch
[root@vuwunicorhsat01 salt]# 

[root@vuwunicoedwdbd2 ~]# rpm -q salt-minion
salt-minion-2018.3.0-1.el7.noarch
[root@vuwunicoedwdbd2 ~]#

[root@vuwunicorhsat01 salt]# salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: 0.3.7
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
 
[root@vuwunicorhsat01 salt]#

**Comment by gzcwnk** [comment] 2018-04-16 04:10
I am getting a padding check failed?

======
[root@vuwunicorhsat01 salt]# systemctl status salt-master
● salt-master.service - The Salt Master Server
   Loaded: loaded (/usr/lib/systemd/system/salt-master.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-04-16 16:01:44 NZST; 8min ago
     Docs: man:salt-master(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 17185 (salt-master)
   CGroup: /system.slice/salt-master.service
           ├─17185 /usr/bin/python /usr/bin/salt-master
           ├─17190 /usr/bin/python /usr/bin/salt-master
           ├─17195 /usr/bin/python /usr/bin/salt-master
           ├─17197 /usr/bin/python /usr/bin/salt-master
           ├─17199 /usr/bin/python /usr/bin/salt-master
           ├─17200 /usr/bin/python /usr/bin/salt-master
           ├─17201 /usr/bin/python /usr/bin/salt-master
           ├─17202 /usr/bin/python /usr/bin/salt-master
           ├─17203 /usr/bin/python /usr/bin/salt-master
           ├─17204 /usr/bin/python /usr/bin/salt-master
           ├─17205 /usr/bin/python /usr/bin/salt-master
           ├─17206 /usr/bin/python /usr/bin/salt-master
           ├─17223 /usr/bin/python /usr/bin/salt-master
           ├─17224 /usr/bin/python /usr/bin/salt-master
           ├─17225 /usr/bin/python /usr/bin/salt-master
           ├─17226 /usr/bin/python /usr/bin/salt-master
           ├─17227 /usr/bin/python /usr/bin/salt-master
           ├─17228 /usr/bin/python /usr/bin/salt-master
           ├─17229 /usr/bin/python /usr/bin/salt-master
           ├─17230 /usr/bin/python /usr/bin/salt-master
           ├─17231 /usr/bin/python /usr/bin/salt-master
           ├─17233 /usr/bin/python /usr/bin/salt-master
           └─17234 /usr/bin/python /usr/bin/salt-master

Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: pub = salt.crypt.get_rsa_pub_key(pubfn)
Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 210, in get_...ub_key
Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: key = RSA.load_pub_key(path)
Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 406, in ...ub_key
Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: return load_pub_key_bio(bio)
Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 422, in ...ey_bio
Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: rsa_error()
Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 302, in rsa_error
Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: raise RSAError, m2.err_reason_error_string(m2.err_get_error())
Apr 16 16:05:35 vuwunicorhsat01.ods.vuw.ac.nz salt-master[17185]: RSAError: padding check failed
Hint: Some lines were ellipsized, use -l to show in full.
[root@vuwunicorhsat01 salt]#

**Comment by gzcwnk** [comment] 2018-04-16 04:13
[root@vuwunicorhsat01 salt]# salt-key -L |grep edwdbd2
vuwunicoedwdbd2.ods.vuw.ac.nz
[root@vuwunicorhsat01 salt]#

So the 2 can talk, this problem suggests a bug.

**Comment by voki** [comment] 2018-04-16 09:06
We are getting the same error when updated minion to 2018.03 on RedHat 7.4.
Master is also 2018.03 but on CentOS 7.4, CentOS 2018.03 minions are working fine.

**Comment by gtmanfred** [comment] 2018-04-16 13:55
This is a duplicate of #46868

Daniel

**Closed by gtmanfred** 2018-04-16 13:55 UTC
