### ISSUE TITLE
salt-cloud fails to actually _run_ the bootstrap script

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#28466] opened 2015-10-31 01:25 UTC
As you can see in the output below, salt-cloud goes from copying keys/config files to the newly spun up instance straight to `rm`ing the files and skips the all important step of actually running the bootstrap script in the middle.

```
DEBUG   ] Terminal Command: /bin/sh -c echo "put  /tmp/tmpgVDxvl /tmp/.saltcloud-5aa045ff-e491-438b-aa6b-41d2a95e4355/minion" | sftp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlP
ath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -oIdentityFile=/etc/salt/cloud.providers.d/sal
t-cloud-ssh -oPort=22 root@159.203.134.244
Warning: Permanently added '159.203.134.244' (ECDSA) to the list of known hosts.
[DEBUG   ] Warning: Permanently added '159.203.134.244' (ECDSA) to the list of known hosts.
Connected to 159.203.134.244.
[DEBUG   ] Connected to 159.203.134.244.
sftp> put  /tmp/tmpgVDxvl /tmp/.saltcloud-5aa045ff-e491-438b-aa6b-41d2a95e4355/minion
Uploading /tmp/tmpgVDxvl to /tmp/.saltcloud-5aa045ff-e491-438b-aa6b-41d2a95e4355/minion
/tmp/tmpgVDxvl                                                                                                                                                          100% 4637     4.5KB/s   00:00
[DEBUG   ] sftp> put  /tmp/tmpgVDxvl /tmp/.saltcloud-5aa045ff-e491-438b-aa6b-41d2a95e4355/minion
Uploading /tmp/tmpgVDxvl to /tmp/.saltcloud-5aa045ff-e491-438b-aa6b-41d2a95e4355/minion
/tmp/tmpgVDxvl                                                                                                                                                          100% 4637     4.5KB/s   00:00 ETA
[DEBUG   ] SSH command: 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=ye
s -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/cloud.providers.d/salt-cloud-ssh -p 22 root@159.203.134.244 rm -f '/tmp/.saltcloud-5aa045ff-e491-438b-aa6b-41d2a95e4355/minion.pub''
[DEBUG   ] Child Forked! PID: 15026  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] Terminal Command: /bin/sh -c ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAu
thentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/cloud.providers.d/salt-cloud-ssh -p 22 root@159.203.134.244 'rm -f '"'"'/tmp/.saltcloud-5aa045ff-e491-438b-aa6b-41d2a
95e4355/minion.pub'"'"''
Warning: Permanently added '159.203.134.244' (ECDSA) to the list of known hosts.
```

```
salt --versions
Salt Version:
           Salt: 2015.8.0-669-g30ee4c1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-32-generic
         system: Ubuntu 14.04 trusty
```

**Comment by iggy** [comment] 2015-10-31 06:40
I tried to git bisect it, and it seems to be some mix of version and config causing the issue. The bisect was inconclusive. It works reliably on older versions, but fails intermittently on newer versions. Still trying to track it down.

**Comment by rallytime** [comment] 2015-11-02 14:40
Thanks for filing this @iggy. Do you think what you're seeing is the same thing as in #26699? I have been chasing that one for a while, but I can't reproduce it. Basically the bootstrap script doesn't get run because salt is looking for a file in a path that doesn't exist. This situation is seen specifically in [this comment](https://github.com/saltstack/salt/issues/26699#issuecomment-146112308) and [this comment](https://github.com/saltstack/salt/issues/26699#issuecomment-146895805).

**Comment by iggy** [comment] 2015-11-02 16:52
Related to #26699 I think.

**Comment by iggy** [comment] 2015-11-02 17:01
lol, mid-air collision. ;)

Yeah, doing the salt-cloud -u from that issue fixes mine too.

**Comment by rallytime** [comment] 2015-11-12 00:14
Good! Glad there is at least an easy work around. I am going to close this as a duplicate of #26699.

**Closed by rallytime** 2015-11-12 00:14 UTC
Labels: Bug, High Severity, P2, RIoT, Salt-Cloud
