### ISSUE TITLE
pillar.get and pillar.items have different sematics

### ISSUE THREAD

**Issue by frioux** [saltstack/salt#30239] opened 2016-01-08 18:50 UTC
TL;DR: pillar.items and pillar.get return different data.  Check this out:

```
$ salt -l error --out json pillar.get druby
{
    "local": {
        "gems": [], 
        "herp": []
    }
}
```

```
salt -l error --out json pillar.items | jq '.local.druby'
{
  "gems": [
    "bundler",
    "fontcustom",
    "fontcustom"
  ],
  "herp": [
    "www",
    "logsearch",
    "dbslave",
    "stats",
    "ops"
  ]
}
```

Ok so I have an ext_pillar that I use to share data between pillars.  The ext pillar defines roles that apply to a given server, and then based on those roles other pillars vary their data.  So here's a little example; here's the ext_pillar:

```python
#!/usr/bin/python

import logging
log = logging.getLogger(__name__)

all_roles = {
        '*': [],
        'rdb': ['elasticsearch-rdb'],
        'salt': ['aptly', 'salt-master'],
        }

def __virtual__():
    return 'rolex'

def ext_pillar( minion_id, pillar, *args, **kwargs ):

    roles = []

    server_class = __grains__.get('server_class', '')

    roles.extend(all_roles.get('*', []))
    roles.extend(all_roles.get(server_class, []))
    roles.extend(__grains__.get('roles', []))

    if __grains__.get('master', 'salt') != 'salt':
        roles.append('salt-minion')

    return { 'rolex': roles }
```

And here's the pillar:

```python
#!/usr/bin/python

import logging
log = logging.getLogger(__name__)

all_roles = {
        '*': [],
        'rdb': ['elasticsearch-rdb'],
        'salt': ['aptly', 'salt-master'],
        }

def __virtual__():
    return 'rolex'

def ext_pillar( minion_id, pillar, *args, **kwargs ):

    roles = []

    server_class = __grains__.get('server_class', '')

    roles.extend(all_roles.get('*', []))
    roles.extend(all_roles.get(server_class, []))
    roles.extend(__grains__.get('roles', []))

    if __grains__.get('master', 'salt') != 'salt':
        roles.append('salt-minion')

    return { 'rolex': roles }
```

Note that as above, for some reason, `pillar.get` causes this data not to be correctly calculated.

**UPDATE**: Running saltutil.pillar_refresh does not change the output.

**Comment by jfindlay** [comment] 2016-01-08 19:25
@frioux, thanks for the report.  I think this is a duplicate of #23391.  If you don't mind, I'm going to close this in favor of that.  Your additional information is helpful, though.  If you restart the minion as suggested in #23391, does that produce the correct `pillar.get` behavior?

**Closed by jfindlay** 2016-01-08 19:25 UTC
Labels: Duplicate

**Comment by frioux** [comment] 2016-01-08 19:27
I actually do not even have a minion to restart; I'm running all local with no services.

Also, you know more about this than I do for sure, but both `pillar.get` and `pillar.item` show the same results, only `pillar.items` has the complete data.
