### ISSUE TITLE
Issues running select states -  local variable 'salt' referenced before assignment

### ISSUE THREAD

**Issue by ldelossa** [saltstack/salt#28883] opened 2015-11-13 23:34 UTC
Hey guys,

I just bootstrapped a minino and a state I ran 100 times before simple does not work. 
```
[root@tmpsaltmaster01p srv]# salt --version
salt 2015.8.1-2928-g558be2e (Beryllium)
```
```
[root@tmpharaka01d tmp]# salt-minion --version
salt-minion 2015.8.1-3743-g3f8f47f (Beryllium)
```

```
tmpharaka01d.prod.corp.ad:
----------
          ID: get_node
    Function: file.managed
        Name: /tmp/node-v0.10.36.tar.gz
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1656, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1574, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 1466, in managed
                  **kwargs
                File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 3713, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 3348, in get_managed
                  hash_fn = __salt__['cp.cache_file'](source_hash, saltenv)
                File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 365, in cache_file
                  result = __context__['cp.fileclient'].cache_file(path, saltenv)
                File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 158, in cache_file
                  return self.get_url(path, '', True, saltenv)
                File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 621, in get_url
                  query = salt.utils.http.query(
              UnboundLocalError: local variable 'salt' referenced before assignment
     Started: 18:29:56.006160
    Duration: 947.933 ms
     Changes:   
----------
```

```
          ID: download.python3.4
    Function: file.managed
        Name: /tmp/Python-3.4.1.tgz
      Result: False
     Comment: Unable to manage file: local variable 'salt' referenced before assignment
     Started: 18:27:11.994094
    Duration: 18.982 ms
     Changes:   
```

Looks like it's surrounding the file.managed state. No other states seem to have an issue.

**Comment by bmcorser** [comment] 2015-11-16 14:06
I see this too.

**Comment by ldelossa** [comment] 2015-11-16 14:56
Work around for now:

wget -O install_salt.sh https://bootstrap.saltstack.com
sudo sh install_salt.sh -P git v2015.8.1

**Comment by andretost** [comment] 2015-11-16 21:22
I see it, too, but using the 2015.8.1 release is not an option for me, because I have a custom module which doesn't work, related to a bug in that release (https://github.com/saltstack/salt/pull/27725). So it looks like I am stuck for now.

**Comment by ldelossa** [comment] 2015-11-16 21:23
Can you use develop branch ? Or do same limits apply

**Comment by andretost** [comment] 2015-11-16 23:24
I reinstalled my minion using the bootstrap script with 'git develop' and I get the same problem.

**Comment by jfindlay** [comment] 2015-11-17 17:07
@ldelossa, thanks for the report.  Do you mean you ran the state 100 times and it failed on the 100th time?  Also, it looks like you're running on develop.  Can you reproduce this on the head of 2015.8?  Is there any more information you can give to help replicate a reproducible test case?

**Comment by ldelossa** [comment] 2015-11-17 17:09
Hey Justin,

No that means I just ran that state a bunch of times before in the past,
without any issues. Now that I used the latest bootstrap, its an issue.

I didn't use the develop bootstrap, I just used this command:

Using wget to install your distribution's stable packages:

wget -O install_salt.sh https://bootstrap.saltstack.comsudo sh install_salt.sh


Should have been the latest stable.

**Comment by jfindlay** [comment] 2015-11-17 18:33
@ldelossa, thanks for the clarification.

**Comment by TronPaul** [comment] 2015-11-19 05:55
I'm also seeing this issue when using pkgrepo.managed. Not getting a full stacktrace.
```
vagrant@app-01:~$ salt-minion --version
salt-minion 2015.8.0-795-g83e50d2 (Beryllium)
```
```
          ID: mopidy_repo
    Function: pkgrepo.managed
        Name: deb http://apt.mopidy.com/ stable main contrib non-free
      Result: False
     Comment: Failed to configure repo 'deb http://apt.mopidy.com/ stable main contrib non-free': local variable 'salt' referenced before assignment
     Started: 05:50:35.553179
    Duration: 136.597 ms
     Changes:  ```

Not getting a stacktrace so I'll need to investigate further.

**Comment by TronPaul** [comment] 2015-11-19 06:09
```
vagrant@app-01:~$ sudo salt-call pkg.mod_repo 'deb http://apt.mopidy.com/ stable main contrib non-free' key_url=http://apt.mopidy.com/mopidy.gpg file=/etc/apt/sources.list.d/mopidy.list                                                     
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnboundLocalError: local variable 'salt' referenced before assignment
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 333, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 1819, in mod_repo
    fn_ = __salt__['cp.cache_file'](key_url, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 365, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 171, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 634, in get_url
    query = salt.utils.http.query(
UnboundLocalError: local variable 'salt' referenced before assignment
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 333, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 1819, in mod_repo
    fn_ = __salt__['cp.cache_file'](key_url, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 365, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 171, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 634, in get_url
    query = salt.utils.http.query(
UnboundLocalError: local variable 'salt' referenced before assignment
```

Yep, same spot.

**Comment by TronPaul** [comment] 2015-11-19 06:19
Messing around with random print statements, this seems to only happen in `Client.get_url`. If I try to access `salt.utils.http` in `Client.cache_file` at line 170, python succeeds.

**Comment by TronPaul** [comment] 2015-11-19 06:25
I noticed there's an import for `salt.utils.s3` inside of `Client.get_url` at line. I added another import for `salt.utils.http` and that seemed to fix it. Those two solutions seemed wrong, so I removed the import for `salt.utils.s3` and the import for `salt.utils.http` from `Client.get_url`. It seemed to work after that. Probably need to test the s3 fileclient with that change though.

**Comment by TronPaul** [comment] 2015-11-19 06:52
Found #29036 while trying to test fileclient and s3.

**Comment by jfindlay** [comment] 2015-11-19 16:27
Ping @techhat.

**Comment by cachedout** [comment] 2015-11-19 22:47
This could be related to https://github.com/saltstack/salt/pull/28740 which was later reverted. For those who are seeing this, could you please double-check you aren't running a version with this commit present?

**Comment by TronPaul** [comment] 2015-11-20 02:00
@cachedout The commit seems to be present but I installed salt as of the configparser commit on this vagrant yesterday after getting the configparser stuff into develop.

The import added in #28740 is even still in my git checkout of develop.

**Comment by TronPaul** [comment] 2015-11-20 02:02
@cachedout looking at the PR linked on #28740, #28839. It seems it only got applied to the 2014.7 branch.

**Comment by cachedout** [comment] 2015-11-23 19:14
@TronPaul Now that we have these merged, could you verify that this issue is resolved?

**Comment by TronPaul** [comment] 2015-11-23 19:17
@cachedout I'll run it through my vagrant test environment and update here when it's finished.

**Comment by TronPaul** [comment] 2015-11-23 20:14
@cachedout my `pkgrepo.managed` state works in develop now. @ldelossa is it working for you?

**Comment by cachedout** [comment] 2015-11-23 20:16
@TronPaul Great! Thanks for testing that. Much appreciated. Unless we hear back from @ldelossa, I will close this shortly.

**Closed** 2015-11-30 22:55 UTC
Labels: Bug, Core, Critical, Fixed Pending Verification, P3, Regression
