### ISSUE TITLE
pkg.installed returns false , but program is installed correctly

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#55164] opened 2019-10-30 13:00 UTC
### pkg.installed returns false , but should be True
Trying to install samba via execution module works as expected. 

sudo salt 'smb' pkg.install name=samba48-4.8.12_4

Samba is installed correctly and the module returns true.

Using pkg.installed inside a state module returns false even if samba is correctly installed.

```
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[DEBUG   ] Could not LazyLoad pkg.check_db: 'pkg.check_db' is not available.
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[INFO    ] Executing command ['pkg', 'install', '-y', 'samba48-4.8.12_4'] in directory '/root'
[TRACE   ] stdout: Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed

[INFO    ] Executing command ['pkg', 'info', '-ao'] in directory '/root'
[TRACE   ] stdout: bash-5.0.11                    shells/bash
ca_root_nss-3.47               security/ca_root_nss
cmocka-1.1.3                   sysutils/cmocka
curl-7.66.0                    ftp/curl
cvsps-2.1_2                    devel/cvsps
.......
samba48-4.8.12_4               net/samba48

[ERROR   ] The following packages failed to install/update: samba48-4.8.12_4
[INFO    ] Completed state [samba48-4.8.12_4] at time 13:45:24.895033 (duration_in_ms=981.954)
[DEBUG   ] File /var/cache/salt/minion/accumulator/34439823256 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] Minion return retry timer set to 8 seconds (randomized)
[INFO    ] Returning information for job: 20191030124450147365
[TRACE   ] Return data: {'success': False, 'return': {'pkg_|-install_package_|-samba48-4.8.12_4_|-installed': {'name': 'samba48-4.8.12_4', 'changes': {}, 'result': False, 'comment': 'The following packages failed to install/update: s
amba48-4.8.12_4', '__sls__': 'samba', '__run_num__': 0, 'start_time': '13:45:23.913079', 'duration': 981.954, '__id__': 'install_package'}}, 'retcode': 2, 'jid': '20191030124450147365', 'fun': 'state.apply', 'fun_args': ['samba']}
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/usr/local/etc/salt/pki/minion', 'smb', 'tcp://192.168.6.163:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/usr/local/etc/salt/pki/minion', 'smb', 'tcp://192.168.6.163:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.168.6.163:4506
[DEBUG   ] Trying to connect to: tcp://192.168.6.163:4506
[TRACE   ] Inserted key into loop_instance_map id 34469951472 for key ('/usr/local/etc/salt/pki/minion', 'smb', 'tcp://192.168.6.163:4506', 'aes') and process 20160
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[TRACE   ] ret_val = None
[DEBUG   ] minion return: {'success': False, 'return': {'pkg_|-install_package_|-samba48-4.8.12_4_|-installed': {'name': 'samba48-4.8.12_4', 'changes': {}, 'result': False, 'comment': 'The following packages failed to install/update:
 samba48-4.8.12_4', '__sls__': 'samba', '__run_num__': 0, 'start_time': '13:45:23.913079', 'duration': 981.954, '__id__': 'install_package'}}, 'retcode': 2, 'jid': '20191030124450147365', 'fun': 'state.apply', 'fun_args': ['samba']}

```

### Setup

init.sls
```
install_package:
  pkg.installed:
  	- name: samba48-4.8.12_4

```

### Versions Report

MASTER:

```
─ salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Aug 22 2019, 01:16:05)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 12.0-RELEASE-p10
         system: FreeBSD
        version: Not Installed
```

MINION:

```
smb% salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Oct 24 2019, 01:18:01)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 12.0-RELEASE-p10
         system: FreeBSD
        version: Not Installed

```

**Comment by frogunder** [comment] 2019-10-31 17:40
@network-shark Thank you for reporting this issue.

**Comment by asomers** [comment] 2019-12-26 16:09
This is a duplicate of #55630 .

**Comment by waynew** [comment] 2020-01-09 21:13
Even though #55630 is later, there's more information attached to that issue - I'm going to go ahead and close this issue in favor of that one.

**Closed by waynew** 2020-01-09 21:13 UTC
Labels: Bug, High Severity, P3
