### ISSUE TITLE
Errors After Updating to 2015.8.5

### ISSUE THREAD

**Issue by jaipepe** [saltstack/salt#31163] opened 2016-02-12 16:13 UTC
We just updated to 2015.8.5 last night, and are seeing this issue on a few of the minions. 
```python-traceback
2016-02-12 16:10:15,703 [salt.utils.schedule][ERROR   ][15897] Unhandled exception running status.master
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 678, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/status.py", line 824, in master
    event.fire_event({'master': master}, '__master_disconnected')
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 580, in fire_event
    self.serial.dumps(data),
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 140, in dumps
    return msgpack.dumps(msg)
  File "/usr/lib64/python2.7/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 223, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:223)
  File "msgpack/_packer.pyx", line 225, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:225)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 220, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:220)
TypeError: can't serialize <tornado.concurrent.Future object at 0x23b2a90>
```
```yaml
salt-minion --versions-report
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-123.20.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

When running a highstate manually, the following error occurs:
```
sudo salt-call state.highstate
[ERROR   ] Error parsing configuration file: /etc/salt/minion.d/_schedule.conf - could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:tornado.concurrent.Future'
  in "<string>", line 7, column 15:
          master: !!python/object:tornado.concurre ...
                  ^
[ERROR   ] Error parsing configuration file: /etc/salt/minion.d/_schedule.conf - could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:tornado.concurrent.Future'
  in "<string>", line 7, column 15:
          master: !!python/object:tornado.concurre ...
```
When I look at _schedule.conf, it is different that my other minion's _scheudle.conf for some reason.

broken _schedule.conf
```yaml
sudo cat /etc/salt/minion.d/_schedule.conf
schedule:
  __master_alive:
    function: status.master
    jid_include: true
    kwargs:
      connected: true
      master: !!python/object:tornado.concurrent.Future
        _callbacks: []
        _done: false
        _exc_info: null
        _log_traceback: false
        _result: null
        _tb_logger: null
    maxrunning: 2
    seconds: 120
  __mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60,
    name: __mine_interval}
```
good _schedule.confsudo cat /etc/salt/minion.d/_schedule.conf
```sls
schedule:
  __master_alive:
    function: status.master
    jid_include: true
    kwargs: {connected: true, master: saltmaster.local.com}
    maxrunning: 1
    seconds: 120
  __mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60}
```

**Comment by jfindlay** [comment] 2016-02-12 18:26
@jaipepe, thanks for reporting.  How many minions have the tornado `Future` in place of the master location?  Have you setup any scheduling beyond the default?  Do you have any suspicions about why some minions may have a malformed schedule config and not others?

@garethgreenaway, @jacksontj

**Comment by jaipepe** [comment] 2016-02-12 20:33
@jfindlay , we do have a scheduled state.highstate that looks like this:

`schedule:
  highstate:
    function: state.highstate
    minutes: 15
    maxrunning: 1`

A couple suspicious things to note so far:
I am running a failover master setup and most of the minions only have 1 connection open to port 4505 at time. For the minions with this issue, they have two connections open to different masters on 4505. This is true for the other issue created as well, [https://github.com/saltstack/salt/issues/31159](url). If I restart the salt-minion, I go back to 1 connection to port 4505 and a state.highstate will run again.


All of my minions have this issue, but I believe that is covered in [https://github.com/saltstack/salt/issues/30472](url) . 

`2016-02-12 20:00:13,662 [salt.utils.schedule][INFO    ][628] Running scheduled job: __master_alive
2016-02-12 20:00:13,844 [salt.utils.schedule][ERROR   ][30899] Unhandled exception running status.master
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
2016-02-12 20:02:13,661 [salt.utils.schedule][INFO    ][628] Running scheduled job: __master_alive
2016-02-12 20:02:13,851 [salt.utils.schedule][ERROR   ][32141] Unhandled exception running status.master
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'`

**Comment by jfindlay** [comment] 2016-02-12 20:58
@jaipepe, thanks for the extra info.

**Comment by JaseFace** [comment] 2016-02-22 17:15
We are seeing this also, we have 2 masters in the setup, one 2015.8.5 and one 2015.8.3.  We flipped them over to .5 and then back to .3, and some started exhibiting this issue.  Still need to dig in a bit more, but it appears this may be caused by failed connections during highstate. Possibly a bug that still tries to populate the master hostname with an error that happened prior while trying to establish the connection w the master.

**Comment by JaseFace** [comment] 2016-02-25 16:55
I'm guessing this is known based on the schedule entry, but just to confirm, this is caused by the master_alive_interval setting.  If you leave that at the default of 0, the keep alive is not used and the __master_alive in the schedule doesn't exist.  I haven't dug in further yet, but it's likely this module blindly accepting the error as return when populating.

**Comment by JaseFace** [comment] 2016-02-25 19:31
I'm guessing this is known based on the schedule entry, but just to confirm, this is caused by the master_alive_interval setting. If you leave that at the default of 0, the keep alive is not used and the __master_alive in the schedule doesn't exist. I haven't dug in further yet, but it's likely this module blindly accepting the error as return when populating.

**Comment by jaipepe** [comment] 2016-02-26 03:55
I am seeing the issue with the master_alive_interval at 120.

**Comment by jaipepe** [comment] 2016-03-08 15:31
Did a little digging today on a box that saw this issue. I found the date/time that the defective _schedule.conf was modified, then I dug through the minion log and found that it appears this issue does occur when the minion tries to failover to a different master.

`2016-03-08 14:34:14,675 [salt.utils.schedule][INFO    ][7670] Running scheduled job: highstate
2016-03-08 14:34:15,175 [salt.minion      ][INFO    ][7670] Connection to master master3.local lost
2016-03-08 14:34:15,176 [salt.minion      ][INFO    ][7670] Trying to tune in to next master from master-list
2016-03-08 14:34:15,176 [salt.minion      ][INFO    ][7670] Removing possibly failed master master3.local from list of masters
2016-03-08 14:34:15,252 [salt.minion      ][WARNING ][7670] Master ip address changed from [redacted] to [redacted]
2016-03-08 14:34:15,869 [salt.utils.schedule][INFO    ][7670] Running scheduled job: __master_alive
2016-03-08 14:34:16,029 [salt.state       ][INFO    ][19625] Loading fresh modules for state activity
2016-03-08 14:34:16,121 [salt.utils.schedule][ERROR   ][19656] Unhandled exception running status.master
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
2016-03-08 14:34:16,327 [salt.fileclient  ][INFO    ][19625] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://top.sls'
2016-03-08 14:34:16,367 [salt.minion      ][INFO    ][7670] Connection to master <tornado.concurrent.Future object at 0x249bed0> re-established
2016-03-08 14:34:16,538 [salt.loaded.int.module.saltutil][INFO    ][19625] Creating module dir '/var/cache/salt/minion/extmods/beacons'
2016-03-08 14:34:16,539 [salt.loaded.int.module.saltutil][INFO    ][19625] Syncing beacons for environment 'base'
2016-03-08 14:34:16,540 [salt.loaded.int.module.saltutil][INFO    ][19625] Loading cache from salt://_beacons, for base)
2016-03-08 14:34:16,548 [salt.fileclient  ][INFO    ][19625] Caching directory u'_beacons/' for environment 'base'
2016-03-08 14:34:17,022 [salt.loaded.int.module.saltutil][INFO    ][19625] Creating module dir '/var/cache/salt/minion/extmods/modules'
2016-03-08 14:34:17,023 [salt.loaded.int.module.saltutil][INFO    ][19625] Syncing modules for environment 'base'
2016-03-08 14:34:17,024 [salt.loaded.int.module.saltutil][INFO    ][19625] Loading cache from salt://_modules, for base)
2016-03-08 14:34:17,024 [salt.fileclient  ][INFO    ][19625] Caching directory u'_modules/' for environment 'base'
2016-03-08 14:34:17,172 [salt.utils.schedule][INFO    ][7670] Running scheduled job: __master_alive
2016-03-08 14:34:17,208 [salt.loaded.int.module.saltutil][INFO    ][19625] Creating module dir '/var/cache/salt/minion/extmods/states'
2016-03-08 14:34:17,209 [salt.loaded.int.module.saltutil][INFO    ][19625] Syncing states for environment 'base'
2016-03-08 14:34:17,209 [salt.loaded.int.module.saltutil][INFO    ][19625] Loading cache from salt://_states, for base)
2016-03-08 14:34:17,210 [salt.fileclient  ][INFO    ][19625] Caching directory u'_states/' for environment 'base'
2016-03-08 14:34:17,318 [salt.utils.schedule][ERROR   ][19681] Unhandled exception running status.master
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 678, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/status.py", line 824, in master
    event.fire_event({'master': master}, '__master_disconnected')
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 580, in fire_event
    self.serial.dumps(data),
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 140, in dumps
    return msgpack.dumps(msg)
  File "/usr/lib64/python2.7/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 223, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:223)
  File "msgpack/_packer.pyx", line 225, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:225)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 220, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:220)
TypeError: can't serialize <tornado.concurrent.Future object at 0x249bed0>`

**Comment by cachedout** [comment] 2016-03-18 18:35
@jaipepe A fix for this should appear in the upcoming release of 2015.8.8.

**Closed by cachedout** 2016-03-18 18:35 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, Multi-Master, P2, Regression
