### ISSUE TITLE
PDF documentation has no content, just a SaltStack logo

### ISSUE THREAD

**Issue by thecosmicfrog** [saltstack/salt#21343] opened 2015-03-05 10:08 UTC
The PDF version of the Salt docs (linked to by the [docs latest page](http://docs.saltstack.com/en/latest/)) is just a blank PDF other than a SaltStack logo. File size is just 1.9KB. The ePub version is correct.

The PDF link is as below:
https://media.readthedocs.org/pdf/salt/latest/salt.pdf

**Comment by nmadhok** [comment] 2015-03-07 22:23
@thecosmicfrog Duplicate of https://github.com/saltstack/salt/issues/13755. This issue can be closed since the other issue was filed first. Thanks for reporting this!

**Comment by rallytime** [comment] 2015-03-09 16:30
@thecosmicfrog As stated above, this is indeed a duplicate and known issue. I am going to close this out in favor of the other one. Thanks!

**Closed by rallytime** 2015-03-09 16:30 UTC
Labels: Documentation, Duplicate
