### ISSUE TITLE
Salt-cloud create_snapshot is not recognizing snapshot_name parameter  in salt 2015.8.5

### ISSUE THREAD

**Issue by tmaulik** [saltstack/salt#30950] opened 2016-02-05 20:02 UTC
sudo salt-cloud -a create_snapshot Test-W2K8R2-TM snapshot_name="Test cloud" memdump=True -l debug

The following virtual machines are set to be actioned with "create_snapshot":
  Test-W2K8R2-TM

Error: There was an error actioning machines: You must specify snapshot name for the snapshot to be created.

Note: salt-cloud create_snapshot is working fine in salt 2015.8.3
[salt-debug-report.txt](https://github.com/saltstack/salt/files/119772/salt-debug-report.txt)
[salt-versions-report.txt](https://github.com/saltstack/salt/files/119771/salt-versions-report.txt)

**Comment by jfindlay** [comment] 2016-02-05 21:38
@tmaulik, thanks for reporting.

**Comment by techhat** [comment] 2016-02-05 23:58
@tmaulik, could you please post a (sanitized) copy of your provider config?

**Comment by tmaulik** [comment] 2016-02-06 16:41
louis:
  driver: vmware
  user: xxxxxxxx
  password: xxxxxxxxx
  url: 'louis.ad.co.pierce.wa.us'
  protocol: 'https'
  port: 443

kamet:
  driver: vmware
  user: xxxxxx
  password: xxxxxxxx
  url: 'kamet.ad.co.pierce.wa.us'
  protocol: 'https'
  port: 443

**Comment by tmaulik** [comment] 2016-02-06 16:44
Posted provider config above

**Comment by techhat** [comment] 2016-02-07 06:10
@nmadhok, do you have any thoughts here?

**Comment by nmadhok** [comment] 2016-02-07 06:19
@techhat It's because https://github.com/saltstack/salt/commit/c5fa9e9351dd099c257e2a05db224916cb896e83 was merged. I don't think it's needed. Should be reverted.

**Comment by rallytime** [comment] 2016-02-08 17:48
@tmaulik Can you give the PR above a try and confirm this fixes the issue for you?

Also, @nmadhok thanks for taking a look. When I added the `kwargs = {}` pieces, I didn't realize that you were implementing some of the function namespaces differently that in other drivers, making that change a problem. I would appreciate it if you could take a look at the PR above.

**Comment by tmaulik** [comment] 2016-02-08 19:45
Hello,

 Can you please tell how can I test the above PR. I am running from a ubunti12.4 environment
 and used the following URL as repository.
deb http://ppa.launchpad.net/saltstack/salt/ubuntu trusty main

Should I replace the VMware.py module?

**Comment by tmaulik** [comment] 2016-02-08 20:00
Hello Nicole,

  Can you please tell how can I install the above PR.I am running from a Ubuntu 14.4 environment
   and used the following URL as repository:

deb http://ppa.launchpad.net/saltstack/salt/ubuntu trusty main

Should I replace the VMware.py module?

I am new in this environment.

The installed version of salt is 2015.8.5

Thanks,

tmaulik

**Comment by rallytime** [comment] 2016-02-08 21:08
@tmaulik Yes, will work. Here is the raw file that contains my changes: https://raw.githubusercontent.com/rallytime/salt/fix-30950/salt/cloud/clouds/vmware.py

You can replace your vmware driver (make sure you back it up first. If not, you can grab the old one from a previous commit in github) in `path/to/your/salt/salt/cloud/clouds/vmware.py` on the machine you're running salt-cloud from.

**Comment by nmadhok** [comment] 2016-02-08 21:09
@rallytime Updated https://github.com/saltstack/salt/pull/31011 with some comments. Thanks for working on this!

**Comment by tmaulik** [comment] 2016-02-08 21:56
It did not work. Getting the same error:

Error: There was an error actioning machines: You must specify snapshot name for the snapshot to be created.

 Pasted below the diff VMware.py and old VMware.py

/usr/lib/python2.7/dist-packages/salt/cloud/clouds$ sudo diff vmware.py ~/vmware.py.old
3033a3034,3036
>     if kwargs is None:
>         kwargs = {}
>
3056c3059
<     desc = kwargs.get('description', '')
---
>     desc = kwargs.get('description') if 'description' in kwargs else ''
3104c3107,3110
<     suppress_power_on = _str_to_bool(kwargs.get('power_off', False)) if kwargs else False
---
>     if kwargs is None:
>         kwargs = {}
>
>     suppress_power_on = _str_to_bool(kwargs.get('power_off', False))

**Comment by nmadhok** [comment] 2016-02-08 22:20
@tmaulik I'm unable to reproduce this. @rallytime Are you able to reproduce this issue? Is a salt-master restart required? Is there a possibility that the old driver might still be cached?

**Comment by rallytime** [comment] 2016-02-08 22:21
@tmaulik It's a little bit hard to tell from your diff, but are these lines present in the driver that you're using?
```
if kwargs is None:
    kwargs = {}
```
Because that's where the regression was. Those lines should be removed.
Make sure you clean out stale `.pyc` files for the vmware.py file.

**Comment by rallytime** [comment] 2016-02-08 22:25
`salt-cloud` uses it's own process, so a master restart shouldn't be required. But if the file wasn't applied correctly, or if there is a stale `.pyc` file hanging around, then that could cause the old driver to come up instead of the new one.

**Comment by tmaulik** [comment] 2016-02-08 22:36
Nitin,

    I restarted the server. Still I have the issue. There is no old .pyc file.

-rw-r--r-- 1 root root 129429 Feb  8 13:45 vmware.py
-rw-r--r-- 1 root root  96682 Feb  8 13:46 vmware.pyc

Thanks,

@tmaulik

**Comment by tmaulik** [comment] 2016-02-08 22:36
Nicole,


    I restarted the server. Still I have the issue. There is no old .pyc file.

-rw-r--r-- 1 root root 129429 Feb  8 13:45 vmware.py
-rw-r--r-- 1 root root  96682 Feb  8 13:46 vmware.pyc

Thanks,

@tmaulik

**Comment by tmaulik** [comment] 2016-02-09 04:55
To confirm that the updated driver module is active, I prefixed the error message with a date in the updated VMware.py:

/usr/lib/python2.7/dist-packages/salt/cloud/clouds$ sudo salt-cloud -a create_snapshot Test-W2K8R2-TM snapshot_name="Test cloud" memdump=True -y
[INFO    ] salt-cloud starting
Error: There was an error actioning machines: **2/8/16 **You must specify snapshot name for the snapshot to be created.

Thanks

**Comment by rallytime** [comment] 2016-02-09 15:54
@tmaulik Thanks for testing that again. This isn't the right fix. I'll submit some new changes shortly.

**Comment by rallytime** [comment] 2016-02-09 21:29
@tmaulik I found where the problem was. There was a larger regression in salt-cloud causing this, plus a little bit of follow-up in the vmware driver as well. I was able to reproduce your issue, and the pull request as it stands right now fixes it. If you'd like to give the change another try, you'll need to replace two files:

- the vmware driver: https://raw.githubusercontent.com/rallytime/salt/fix-30950/salt/cloud/clouds/vmware.py
- the salt/cloud/__init__.py file: https://raw.githubusercontent.com/rallytime/salt/fix-30950/salt/cloud/__init__.py

Thank you for your help in debugging the issue!

**Comment by rallytime** [comment] 2016-02-09 21:33
Oh, and here's the reproduction of the bug:
```
# salt-cloud -a create_snapshot test_ub14 snapshot_name="Test4cloud" -y
[INFO    ] salt-cloud starting
Error: There was an error actioning machines: You must specify snapshot name for the snapshot to be created.
```
And here's the same command working, after applying those fixes:
```
# salt-cloud -a create_snapshot test_ub14 snapshot_name="Test4cloud" -y
[INFO    ] salt-cloud starting
[INFO    ] [ test_ub14 ] Waiting for create snapshot task to finish [0 s]
[INFO    ] [ test_ub14 ] Successfully completed create snapshot task in 3 seconds
vmware-config:
    ----------
    vmware:
        ----------
        test_ub14:
            ----------
            Snapshot created successfully:
                ----------
                created:
                    2016-02-09 12:47:20
                description:
                name:
                    Test4cloud
                path:
                    /Test3cloud/Test3cloud/Test4cloud/Test4cloud
                state:
                    poweredOff
```

**Comment by rallytime** [comment] 2016-02-09 22:17
Actually @tmaulik, don't bother testing. There is a change that fixed a bug that caused this error, and I was hoping to keep the change in, and fix this. But the original change that caused this regression is causing other problems in salt-cloud, so I am just going to revert the PR that caused this regression. Apologies for all of the noise.

**Comment by rallytime** [comment] 2016-02-09 22:52
The real, actual fix for this problem is in #31061. With this revert, I no longer see the errors you were getting. The fix will be available in the next release of salt, which we are working on getting out right now.

**Comment by tmaulik** [comment] 2016-02-11 16:50
Thanks rallytime. Can you please tell when the next release of salt can expected to be available?

**Comment by rallytime** [comment] 2016-02-11 17:07
The release has been tagged internally and we're running tests on it right now. I don't have hard date, but it should be very soon. This will be in the 2015.8.7 release.

**Comment by rallytime** [comment] 2016-02-23 20:51
Hi @tmaulik - 2015.8.7 has been officially released. Have you had a chance to test that this is fixed for you?

**Comment by tmaulik** [comment] 2016-02-23 22:41
Hello Nicole,

  Thanks for informing me. I will test it and let you know.

-Tapan Maulik

**Comment by tmaulik** [comment] 2016-02-24 17:57
Hello Nicole,

   I installed salt v 2015.8.7. Now I am able to create snapshot of a VM. This resolved the issue.

Thanks for all the hard work

-Tapan Maulik

**Comment by rallytime** [comment] 2016-02-24 17:58
Excellent! Thanks for testing and confirming. I'm glad we got this fixed up. :)

**Closed by rallytime** 2016-02-24 17:58 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P3, RIoT, Salt-Cloud, TEAM RIoT
