### ISSUE TITLE
bootstrap-salt.sh does not support Debian stable (9.0/Stretch)

### ISSUE THREAD

**Issue by kivoli** [saltstack/salt#42847] opened 2017-08-10 14:58 UTC
### Description of Issue/Question

Running `bootstrap-salt.sh stable` on Debian Stretch currently installs `2016.11.2+ds-1` from the Debian repositories. Even specifying another version as parameter (`bootstrap-salt.sh stable 2016.11.6`) does not work. The official Salt repositories are not added to the APT sources.

To quote the file: [# Let's start detecting the upcoming Debian 8 (Jessie)](https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/cloud/deploy/bootstrap-salt.sh#L838)
### Setup
N/A

### Steps to Reproduce Issue
Create `Vagrantfile`
```sh
cd $(mktemp -d) && cat >Vagrantfile <<EOF
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provision :salt do |salt|
    # This uses bootstrap-salt.sh to set up salt
    salt.install_master = true
    salt.no_minion = true
  end
end
EOF
```
Run `vagrant up` and `vagrant ssh` to access the machine. `apt show salt-master` and a quick glance at `/etc/apt/sources.list.d` will show that the Salt repository has not been set up and `2016.11.2` installed from the official Debian repositories.

### Versions Report
N/A

**Comment by rallytime** [comment] 2017-08-10 15:14
Hi @kivoli - this is a duplicate of #1118 and is fixed in the `develop` version of the script. It will be available in the next stable release, which we are hoping to get out in the few weeks or so.

**Comment by rallytime** [comment] 2017-08-10 15:17
Whoops! I thought this issue was in the [salt-bootstrap](https://github.com/saltstack/salt-bootstrap) repo. The duplicate issue is actually here: https://github.com/saltstack/salt-bootstrap/issues/1118.

The next stable release of the *bootstrap* repo will be released in the next few weeks, at which point we'll merge the new stable bootstrap script into the 2016.11 and 2017.7 branches.

**Closed** 2017-08-10 20:47 UTC
Labels: Duplicate

**Comment by kivoli** [comment] 2017-08-11 08:10
Sorry, didn’t realise that there’s a separate repository for salt-bootstrap when checking for an existing issue. Thank you!
