### ISSUE TITLE
Salt Can Not  run command with specify groups

### ISSUE THREAD

**Issue by shencan** [saltstack/salt#28769] opened 2015-11-11 14:57 UTC
###Salt  and OS(CentOS 6.6) version
<pre>
[root@master~]# salt --version
salt 2015.8.1 (Beryllium)

[root@master ~]# salt \* test.version
48a211c82b9f:
    2015.5.5
</pre>

###salt master  group configure
<pre>
nodegroups:
  group1: 'L@48a211c82b9f'
</pre>

### restrat salt-master and run command
<pre>
[root@master ~]# salt \* test.ping
48a211c82b9f:
    True

[root@master~]# salt -N group1 test.ping
48a211c82b9f:
    Minion did not return. [No response]
</pre>

###minion debug log 
<pre>
[DEBUG   ] Compound target received that is not a string
</pre>

**Comment by jfindlay** [comment] 2015-11-13 19:24
@shencan, thanks for the report.  This is a duplicate of #27219.

**Closed by jfindlay** 2015-11-13 19:24 UTC
Labels: Duplicate
