### ISSUE TITLE
develop: Huge performance regression in nested display

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#20259] opened 2015-01-30 16:48 UTC
Im noticing a huge performance regression in the nested output in develp.

This is only an empiric feeling for now, but on large dicts, the output computation before display take ages now

**Comment by basepi** [comment] 2015-01-30 20:27
We would love some timing numbers comparing different versions. But in any case, we'll see if we can see a marked difference and see what's going on here.

@cachedout ping

**Comment by kiorky** [comment] 2015-01-31 00:11
well its intermittent, im not sure there is really a bug, that's also possible that the ptoblem reside in makina-states ext_pillar for example here, where we have a huge logic.
Although it sems really blocking when trying to compute the display.

If other ppl also see the problem, then there is really a problem.

That's why i said 'empiric'

**Comment by cachedout** [comment] 2015-02-03 20:36
I cannot reproduce this when testing against ```grains.items```. In fact, the nested outputter is even faster than a couple of others. I suspect this may be limited to just your installation.

**Comment by kiorky** [comment] 2015-02-04 20:33
Uhm; today i think i may have a way to reproduce, its when we have a lot of states, depending on each other in chain, and mutliple of those ones depend of multiple others (even without making circles), when i state fails, and we have lot of data on this state changes (like a cmd.run which a load of output in stdout) , the outputter is gonna gone crazy with lot of '\\\\\\' causing MemoryError and such.

We did made an ugly hack to handle this is makina-states as i really do not time yet to investigate more.

For more info, you can have a look to : https://github.com/makinacorpus/makina-states/commit/69ad76f20128d5f9e655a0064cb9a399d8caf6a9

**Comment by jacksontj** [comment] 2015-04-08 01:21
This should be taken care of in #21920, we have noticed this when you have large numbers of states. From our testing its been fixed with that PR.

**Comment by rallytime** [comment] 2015-04-08 19:15
@kiorky I think #21920 should have cleaned this up nicely. Can you retest this and let us know how this issue stands? Thanks!

**Closed** 2015-04-23 23:32 UTC
Labels: Bug, Cannot Reproduce, Fixed Pending Verification, High Severity, P3
