### ISSUE TITLE
Ubuntu 18.04 Failing to use master key migrated, m2crypto dependency related.

### ISSUE THREAD

**Issue by nicomfer** [saltstack/salt#53659] opened 2019-06-28 13:42 UTC
### Description of Issue
We are trying to migrate our Salt Master from Ubuntu 16.04 to Ubuntu 18.04 reusing our `master key` (master.pub , master.pem) taken from the old one, both of them are running Salt version 2019.2.0. If we try to use a new key generated it works as expected.
This is the error on the new Salt Master:
```
2019-06-28 06:36:10,360 [tornado.application:129 ][ERROR   ][29140] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 743, in handle_message
    stream.send(self.serial.dumps(self._auth(payload['load'])))
  File "/usr/lib/python2.7/dist-packages/salt/transport/mixins/auth.py", line 513, in _auth
    ret['sig'] = salt.crypt.private_encrypt(self.master_key.key, digest)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 293, in private_encrypt
    return key.private_encrypt(message, salt.utils.rsax931.RSA_X931_PADDING)
  File "/usr/lib/python2.7/dist-packages/M2Crypto/RSA.py", line 76, in private_encrypt
    assert self.check_key(), 'key is not initialised'
AssertionError: key is not initialised
```
Error from the minion:
```
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/usr/local/etc/salt/pki/minion', u'01-xxxx.xxxx.com', u'tcp://xxx.xxx.xxx.xxx:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xxx.xxx.xxx:4506
[DEBUG   ] Trying to connect to: tcp://xxx.xxx.xxx.xxx:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (4/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (5/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (6/7)
```

### Steps to Reproduce Issue
Import `master.pem` and `master.pub` already generated from Ubuntu 16.04 and prior 2019.2.0 Salt Version. 

#### Old Salt Master
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1069-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```
#### New Salt Master Ubuntu 18.04
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.27.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1041-aws
         system: Linux
        version: Ubuntu 18.04 bionic
```

Our workaround was purging the `python-m2crypto` package in order to use the old `master key`, but the issue is when we try to use x509 managed certs due that x509 depends on `m2crypto` package.

**Comment by doesitblend** [comment] 2019-06-28 23:11
ZD-3888

**Comment by garethgreenaway** [comment] 2019-07-01 21:07
@nicomfer Thanks for the report.  I have been unable to reproduce this particular issue.  Were the master certificates generated with Ubuntu 16.04 or an earlier version?

**Comment by amontalban** [comment] 2019-07-02 01:36
@garethgreenaway that's correct the master certificates were generated with Ubuntu 16.04 with v2018.3.3.

**Comment by sagetherage** [comment] 2020-01-09 19:56
@garethgreenaway @Akm0d are either of you able to reproduce this with the information given?

**Comment by sagetherage** [comment] 2020-02-11 19:27
@garethgreenaway can you please follow up, here?

**Comment by espeh** [comment] 2020-03-24 07:57
Hi,

We are experiencing the same issue with the certificate when we try to upgrade our salt-master from python2 to python3.

Errors on master:
`2020-03-24 08:33:59,369 [tornado.application:340 ][ERROR   ][40981] Future <tornado.concurrent.Future object at 0x7fdf38bd9b70> exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 754, in handle_message
    stream.send(self.serial.dumps(self._auth(payload['load'])))
  File "/usr/lib/python3.6/site-packages/salt/transport/mixins/auth.py", line 513, in _auth
    ret['sig'] = salt.crypt.private_encrypt(self.master_key.key, digest)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 294, in private_encrypt
    return key.private_encrypt(message, salt.utils.rsax931.RSA_X931_PADDING)
  File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 76, in private_encrypt
    assert self.check_key(), 'key is not initialised'
AssertionError: key is not initialised`

Salt-master:
`Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core`

**Comment by garethgreenaway** [comment] 2023-08-28 17:03
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.

**Closed by garethgreenaway** 2023-08-28 17:03 UTC
Labels: severity-medium, Confirmed, ZD
