### ISSUE TITLE
Add an option for the onfail requisite to not report a failure

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#16291] opened 2014-10-01 16:24 UTC
If an onfail requisite provides some mitigation for the failure we should have an option to not count the original failure as a fail.

**Comment by arthurlogilab** [comment] 2015-07-10 09:12
@whiteinge @cachedout this feature would be really nice. Indeed naming is a difficult part of the job. 

@whiteinge I'm not sure what you mean about the reload in mod_watch. 

What about, for ``onfail_in`` : 

```onfail_in_but_report_ok_if : 
    - plan_b_that_succeeds
```

or for ``onfail`` : 

``` 
onfail_but_fails_reports_as_ok:
   - plan_a_that_fails
```

**Comment by whiteinge** [comment] 2015-07-10 15:47
The [service mod_watch function accepts arguments](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html#salt.states.service.mod_watch). E.g.,

```yaml
restart_stuff:
  service.restart:
    - watch: another_state
    - reload: True  # graceful reload instead of a restart
```

On onfail equivalent could be:

```yaml
recover_after_failure:
  some.recovery-action:
    - onfail: another_state
    - catch_error: True  # set result to True on the watched state because we fixed the error
```

**Comment by vernondcole** [comment] 2016-12-21 17:05
Me, too!   I was about to write this up as a bug, rather than an enhancement request. Recovered failures are not failures. For example, attempting to stop a service which has never been installed. I wrote several scripts like:...
```
provision_dynamux_a:
  service.dead:
    - name: rabbitmq-server
    - onfail:
      - p_d_a_ignore_failures
p_d_a_ignore_failures:
  test.nop
```
but, of course, that did not work as I had hoped.
For my purposes, something like the following would work, and be simpler to use and to implement:...
```
provision_dynamux_a:
  service.dead:
    - name: rabbitmq-server
    - ignore_failures: true
```

**Comment by whiteinge** [comment] 2018-03-14 22:49
I vaguely recall this was addressed...in #39874 perhaps? Looks like it wasn't documented/announced, if so. I don't have an env handy to verify -- do you mind trying the following syntax?

```
some_id:
  some.state:
    - onfail_stop: False
    - onfail:
      - other_id
```

**Comment by disaster123** [comment] 2018-03-28 20:15
May be i'm too stupid but i created this example:
```
id exit 1 state:
  cmd.run:
    - name: echo error; exit 1

id echo state:
  cmd.run:
    - name: echo recovered
    - onfail_stop: False
    - onfail:
      - cmd: id exit 1 state
```

But the output is still:

```
[ERROR   ] Command 'echo error; exit 1' failed with return code: 1
[ERROR   ] stdout: error
[ERROR   ] retcode: 1
[ERROR   ] {'pid': 14488, 'retcode': 1, 'stderr': '', 'stdout': 'error'}
...
Succeeded: 1 (changed=2)
Failed:    1
```

But i would expect that this state can't fail as it has recovered.

**Comment by whiteinge** [comment] 2018-03-29 00:04
Pinging @kiorky. Am I reading that PR correctly?

**Comment by BlaineAtAffirm** [comment] 2019-04-02 00:36
confirmed that the PR in the linked issue didn't work. I am seeing the same behaviour with or without the flag present. When present, set to true or false makes no difference either

```
$ salt test-minion state.sls onfail; echo retcode=$?
test-minion:
----------
          ID: fail
    Function: test.fail_without_changes
      Result: False
     Comment: Failure!
     Started: 00:24:56.127803
    Duration: 10.895 ms
     Changes:
----------
          ID: pass
    Function: test.succeed_without_changes
      Result: True
     Comment: Success!
     Started: 00:24:56.139146
    Duration: 0.652 ms
     Changes:

Summary for test-minion
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:  11.547 ms
ERROR: Minions returned with non-zero exit code
retcode=1
.
.
.

$ cat onfail.sls ;echo
fail:
  test.fail_without_changes: []

pass:
  test.succeed_without_changes:
    - onfail_stop: True
    - onfail:
      - id: fail

$ salt test-minion state.sls onfail-take-2; echo retcode=$?
test-minion:
----------
          ID: fail
    Function: test.fail_without_changes
      Result: False
     Comment: Failure!
     Started: 00:24:56.127803
    Duration: 10.895 ms
     Changes:
----------
          ID: pass
    Function: test.succeed_without_changes
      Result: True
     Comment: Success!
     Started: 00:24:56.139146
    Duration: 0.652 ms
     Changes:

Summary for test-minion
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:  11.547 ms
ERROR: Minions returned with non-zero exit code
retcode=1
.
.
.

$ cat onfail-take-2.sls ;echo
fail:
  test.fail_without_changes: []

pass:
  test.succeed_without_changes:
    - onfail_stop: False
    - onfail:
      - id: fail

```

This is the latest release version of salt
```
root@too-many-puppieesss:/srv/salt# salt --versions
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: 3.2.1
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.4.3
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1075-aws
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by disaster123** [comment] 2020-01-08 20:46
still valid

**Comment by kiorky** [comment] 2020-01-11 10:47
@whiteinge you are right, it was on that purpose.
sry, issue lost in  my github noise ...
See https://github.com/makinacorpus/makina-states/blob/v2/salt/makina-states/_macros/h.jinja#L121 for a real life example.

**Comment by dmurphy18** [comment] 2023-08-30 20:49
@whiteinge Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.

Understanding that you probably add this to track the issue back when on the core team in 2014.

**Closed by dmurphy18** 2023-08-30 20:49 UTC
Labels: Feature
