### ISSUE TITLE
Debian/Ubuntu 32 bit SaltStack repository - missing package for python-tornado

### ISSUE THREAD

**Issue by asg7443** [saltstack/salt#27818] opened 2015-10-09 08:18 UTC
I can't install 'salt-common' package from SaltStack repository on 32 bit Debian Jessie because of missing package 'python-tornado':

```
$ sudo apt-get install salt-common
...
The following packages have unmet dependencies:
salt-common : Depends: python-tornado (>= 4.2.1) but it is not going to be installed
```
It turned out to be there is no 'python-tornado' package description in
http://repo.saltstack.com/apt/debian/dists/jessie/contrib/binary-i386/Packages
and no such i386 package.
And the 'python-tornado' from standard distribution repository is too old (3.2.2).

The same is with 32 bit Ubuntu.

**Comment by jfindlay** [comment] 2015-10-13 17:50
@asg7443, thanks for the report.  This is a duplicate of #27437 and #27228.

**Closed** 2015-10-13 17:50 UTC
Labels: Duplicate

**Comment by ageld** [comment] 2017-04-28 14:20
Has this issue been ever resolved?  Are their packages for 32-bit versions of Ubuntu?
