### ISSUE TITLE
[BUG] pkg_resources.DistributionNotFound: The 'contextvars' distribution was not found and is required by salt

### ISSUE THREAD

**Issue by alexminder** [saltstack/salt#60483] opened 2021-07-02 16:36 UTC
**Description**
SaltStack 3003.1 fail to start

```
# /usr/bin/salt-master
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/salt-master", line 33, in <module>
    sys.exit(load_entry_point('salt==3003.1', 'console_scripts', 'salt-master')())
  File "/usr/lib/python3.9/site-packages/salt/scripts.py", line 95, in salt_master
    import salt.cli.daemons
  File "/usr/lib/python3.9/site-packages/salt/cli/daemons.py", line 17, in <module>
    from salt.utils import migrations
  File "/usr/lib/python3.9/site-packages/salt/utils/migrations.py", line 12, in <module>
    import salt.syspaths as syspaths
  File "/usr/lib/python3.9/site-packages/salt/syspaths.py", line 21, in <module>
    import salt.utils.platform
  File "/usr/lib/python3.9/site-packages/salt/utils/platform.py", line 10, in <module>
    from salt.utils.decorators import memoize as real_memoize
  File "/usr/lib/python3.9/site-packages/salt/utils/decorators/__init__.py", line 19, in <module>
    import salt.utils.args
  File "/usr/lib/python3.9/site-packages/salt/utils/args.py", line 15, in <module>
    import salt.utils.versions
  File "/usr/lib/python3.9/site-packages/salt/utils/versions.py", line 30, in <module>
    import salt.version
  File "/usr/lib/python3.9/site-packages/salt/version.py", line 9, in <module>
    import salt.utils.entrypoints
  File "/usr/lib/python3.9/site-packages/salt/utils/entrypoints.py", line 36, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'contextvars' distribution was not found and is required by salt
```

**Comment by OrangeDog** [comment] 2021-07-05 13:39
How did you install and/or upgrade it?

**Comment by alexminder** [comment] 2021-07-05 15:42
The package upgraded by `emerge` command from Gentoo Portage.

**Comment by OrangeDog** [comment] 2021-07-05 16:19
From repo.saltproject.io or does Gentoo build its own?

**Comment by alexminder** [comment] 2021-07-06 08:58
From Gentoo repo

**Comment by OrangeDog** [comment] 2021-07-06 09:05
Than it may be a downstream packaging issue, I'm not sure.

**Comment by alexminder** [comment] 2021-07-06 10:37
> Then it may be a downstream packaging issue, I'm not sure.

https://github.com/saltstack/salt/blob/master/requirements/base.txt require `contextvars`

**Comment by myii** [comment] 2021-07-06 10:43
@alexminder I submitted a bug report about this a few days back:

* https://bugs.gentoo.org/799431

A more complete discussion is in the bug report I submitted about the Arch Linux package the week before that:

* https://bugs.archlinux.org/task/71344

**Comment by OrangeDog** [comment] 2021-07-06 12:05
Making the source requirement `contextvars; python_version < '3.7'` may fix it everywhere without need for any special handling.

Not actually critical, as there is a workaround (install `contextvars`).

**Comment by bryceml** [comment] 2021-07-06 15:20
> How did you install and/or upgrade it?
> 
> `contextvars` shouldn't be required for python3.9 as it's part of the standard library.

It is needed for salt-ssh targets running less than py3.7.  If that doesn't matter it could be excluded on 3.7+

**Comment by vskubriev** [comment] 2021-08-18 08:46
JFYI. Downgrade starting container image to `alpine:3.13` and pin `salt-minion` to `3003-r0` solve and issue for me.

**Comment by bryceml** [comment] 2021-10-05 19:35
closing since this is expected behavior.

if downstream packages want to remove contextvars from the requirements on py3.7+, that's up to them, it just won't work with salt-ssh targets less than py3.7.

I think we should remove the contextvars requirement once we no longer support any python 3.5 or 3.6 distros.

Feel free to re-open if there are questions.

**Closed by bryceml** 2021-10-05 19:35 UTC
Labels: Packaging, expected-behavior, severity-high, info-needed
