### ISSUE TITLE
[BUG] NAPALM Proxy Minion startup time increased from 25 sec to 160sec salt3001

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#58493] opened 2020-09-18 13:00 UTC
**Description**
After upgrading from 2019.2.5 to 3001.1 napalm proxy minion now takes 160 sec to startup compared to 2019.2.5 it is only ~ 25sec .

**Logs**

[proxy_startup_salt_3001.log](https://github.com/saltstack/salt/files/5245618/proxy_startup_salt_3001.log)
[minion_startup_2019.2.5.log](https://github.com/saltstack/salt/files/5245629/minion_startup_2019.2.5.log)

**Steps to Reproduce the behavior**
salt-proxy -c . --proxyid=r1

**Expected behavior**

minion startup time should be equal or less than previous versions of salt.

**Versions Report**
```
Old ENV:
Salt Version:
           Salt: 2019.2.5

Dependency Versions:
           cffi: 1.14.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov  8 2019, 21:16:45)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 19.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 19.6.0
         system: Darwin
        version: 10.15.6 x86_64
```
```
New ENV:
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.15
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov  8 2019, 21:16:45)
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 3.0.4
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: darwin 19.6.0
         locale: UTF-8
        machine: x86_64
        release: 19.6.0
         system: Darwin
        version: 10.15.6 x86_64

```

With Version 3001 

I can see multiple events of looking up dns entries ?? 
I could understand one look up , but it does the same lookup more than five times. 

```


[DEBUG   ] Unable to resolve address 10.0.2.1: [Errno 1] Unknown host
[DEBUG   ]  #Unable to resolve address 172.16.173.1: [Errno 1] Unknown host
[DEBUG   ] Unable to resolve address 192.168.6.1: [Errno 1] Unknown host
[DEBUG   ] Unable to resolve address 192.168.10.17: [Errno 1] Unknown host
[DEBUG   ] Unable to resolve address fdaa::e01a:decb:8a0f:8d54: [Errno 1] Unknown host
[DEBUG   ] Sending global request "keepalive@lag.net"
[DEBUG   ] Global request denied.
[DEBUG   ] Unable to resolve address fe80::1170:263:bb28:8cc3: [Errno 1] Unknown host
[DEBUG   ] Sending global request "keepalive@lag.net"
[DEBUG   ] Global request denied.
[DEBUG   ] Unable to resolve address fe80::13e9:1504:54b3:ebbd: [Errno 1] Unknown host
[DEBUG   ] Unable to resolve address fdaa::12:efd2:dbd8:db48: [Errno 1] Unknown host
[DEBUG   ] Sending global request "keepalive@lag.net"
[DEBUG   ] Global request denied.
[DEBUG   ] Unable to resolve address fe80::1780:863a:6b9c:cd4c: [Errno 1] Unknown host
[DEBUG   ] Sending global request "keepalive@lag.net"
[DEBUG   ] Global request denied.
[DEBUG   ] Unable to resolve address fe80::7567:930c:72b4:9e74: [Errno 1] Unknown host
[DEBUG   ] Sending global request "keepalive@lag.net"
[DEBUG   ] Global request denied.
[DEBUG   ] Unable to resolve address fe80::a8ce:3295:cd37:4c29: [Errno 1] Unknown host
[DEBUG   ] Sending global request "keepalive@lag.net"
[DEBUG   ] Global request denied.
[DEBUG   ] Unable to resolve address fe80::e7eb:dcfa:916e:2609: [Errno 1] Unknown host
[DEBUG   ] Sending global request "keepalive@lag.net"
[DEBUG   ] Global request denied.
[DEBUG   ] Unable to resolve address fe80::f0a8:fdff:fe85:3d5c: [Errno 1] Unknown host
[DEBUG   ] Elapsed time getting FQDNs: 35.14765501022339 seconds


```

**Comment by garethgreenaway** [comment] 2020-09-22 18:24
@network-shark Thanks for the report.  The slowdown is caused by the FQDN grain attempting to be populated when Salt starts up.  For proxy minion it doesn't make sense.  Unfortunately we didn't realize the issue until after 3001.1 was released.  The fix here, #57676, will be available in the Magnesium release.

**Comment by sagetherage** [comment] 2020-09-22 18:28
@network-shark I will leave this issue open with the label `Fixed Pending Verification` and will close as we get into the Release Candidate Process for Magnesium or post release or if you are able to confirm the fix from the info above, please let us know. Thank you!

**Comment by network-shark** [comment] 2020-09-23 18:45
As a workaround I'm using enable_fqdns_grains: false . Does the patch does something else ?

**Comment by sagetherage** [comment] 2020-09-24 15:32
no, only we will merge that into the code base and there is a test for it, as well - is there something more you were expecting?

**Comment by sagetherage** [comment] 2020-10-13 22:16
this is in the RC for Magnesium - closing, please mention me @network-shark if you expected something else or feel free to open new issue and/or PR, we will gladly review it.

**Closed by sagetherage** 2020-10-13 22:16 UTC
Labels: Bug, Fixed Pending Verification, Magnesium
