### ISSUE TITLE
External_pillar returns twice?

### ISSUE THREAD

**Issue by onmeac** [saltstack/salt#36223] opened 2016-09-12 08:13 UTC
We are testing our own external_pillar source, we've seen "calls" to the external_pillar source twice on every call.
### Setup

our external_pillar used in debugging this "issue"

```
import logging
log = logging.getLogger(__name__)

def ext_pillar(minion_id, pillar, *args, **kwargs):

    log.info("### TEST LOG ###")
    pillar_dict = {'owner': 'Sebastiaan Glazenborg'}

    return pillar_dict
```
### Steps to Reproduce Issue

note: for debugging purposes we disabled all other pillar sources.

on minion:

```
sudo salt-call pillar.items
```

returns:

```
local:
    ----------
    owner:
        Sebastiaan Glazenborg
```

on salt-master:

```
[INFO    ] Authentication request from minion
[INFO    ] Authentication accepted from minion
[INFO    ] ### TEST LOG ###
[INFO    ] ### TEST LOG ###
[INFO    ] Got return from minion for job 20160912100733875050
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment] 2016-09-14 22:00
@onmeac i think this might be a duplicate of #21342 . Do you agree this is what you are running into? User states they found the initial problem when the external pillar was being called twice thanks

**Comment by Ch3LL** [comment] 2016-09-21 22:01
bump @onmeac any time to look at that issue? Want to get this closed if you agree that this is a duplciate. Thanks

**Comment by onmeac** [comment] 2016-09-25 19:26
To be honest I have no idea :$
Trying to understand what is being discussed in #21342;  it looks like that discussion is more about git as an external pillar source?

**Comment by Ch3LL** [comment] 2016-09-28 17:49
@onmeac seems i might have jumped the gun with that conclusion. Would you mind sharing your master config for your external_pillars to help try to replicate this issue? Thanks

**Comment by onmeac** [comment] 2016-12-11 15:13
Sorry for late reply.

Now running salt 2016.3.4

/etc/salt/master.d/ext_pillar.conf
```
ext_pillar:
   - test:
```

/usr/lib/python2.7/site-packages/salt/pillar/test.py
```
import logging
log = logging.getLogger(__name__)

def ext_pillar(minion_id, pillar, *args, **kwargs):

    log.info("### TEST LOG ###")
    pillar_dict = {'owner': 'Sebastiaan Glazenborg'}

    return pillar_dict
```

calling pillar.items results in:
```
[INFO    ] Authentication request from minion
[INFO    ] Authentication accepted from minion
[INFO    ] ### TEST LOG ###
[INFO    ] ### TEST LOG ###
[INFO    ] Got return from minion for job 20161211160927696526
```

**Comment by elxwill** [comment] 2017-01-20 19:39
+1 to this one... 2016.11.1

All my ext_pillars get called twice.

**Comment by ekristen** [comment] 2017-02-04 06:18
I'm seeing this to 2016.11.2, my git ext_pillar is getting called twice. What is worse is that I am using the new git syntax for pillar data and it correctly determines the environment the first run, then the second run defaults back 'master' (or base) and my base is empty and therefore all pillar data returned is EMPTY.

**Comment by Ch3LL** [comment] 2017-02-08 20:35
@onmeac thanks for the test case. looks like i'm able to replicate this. Here is a docker container to easily replicate this:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:36223` (where /home/ch3ll/git/salt/ is a  local cloned git repo of salt)
2. ` salt-master -d; salt-minion -d`
3. `echo "" > /var/log/salt/master`
4. `salt-call pillar.items`
5. `grep -i "test log" /var/log/salt/master`

ping @terminalmage is this expected behavior? 

@erikgrinaker seems you got your issue figured out and its not related to this issue. is that correct?

**Comment by terminalmage** [comment] 2017-02-12 20:14
@Ch3LL I see no matches in the master log using your container. I think you forgot to ``docker commit`` after adding the ext_pillar:

```
2017-02-12 20:11:12,446 [salt.utils.lazy                            ][DEBUG   ][95] Could not LazyLoad test.ext_pillar
2017-02-12 20:11:12,447 [salt.pillar                                ][CRITICAL][95] Specified ext_pillar interface test is unavailable
```

**Comment by terminalmage** [comment] 2017-02-12 20:31
I added an external pillar and pushed a docker image ``terminalmage/issues:36223`` which contains it. I can't reproduce this issue I tested using 2016.3.2, the head of the ``2016.3`` branch, and the head of the ``2016.11`` branch. I do see two occurrences of the log message in the log file, but as you can see when there is the context of the timestamp added, they do *not* occur at the same time:

```
[root@f54afaa67d23 pillar]# grep TEST /var/log/salt/master
2017-02-12 20:19:33,180 [salt.loaded.ext.pillar.test              ][CRITICAL][608]TEST LOG
2017-02-12 20:19:54,435 [salt.loaded.ext.pillar.test              ][CRITICAL][613]TEST LOG
```

I think this is just a simple misunderstanding. Pillar data is compiled for the minion's [in-memory pillar data](https://docs.saltstack.com/en/latest/topics/pillar/index.html#in-memory-pillar-data-vs-on-demand-pillar-data) when the minion connects to the master (that is the first entry you see in the log above). Then when I run ``pillar.items`` ~20 seconds later, the master compiles pillar again, and you get the second occurrence. The ``pillar.items`` function compiles fresh pillar data each time it is run.

It seems like @onmeac is just running the master in the foreground (where the default log format is different than the log file), and just made an incorrect assumption that the call to ``pillar.items`` was causing both instances of the log message. Setting the following in ``/etc/salt/master`` will make the console logging identical to the default format entries in ``/var/log/salt/master``:

```
log_fmt_console: '%(asctime)s,%(msecs)03.0f [%(name)-17s][%(levelname)-8s][%(process)d] %(message)s'
```

**Comment by Ch3LL** [comment] 2017-02-13 15:14
Thanks for pointing that out @terminalmage I think you are right that was misinterpreting that first log if it is indeed adding the pillar data to memory. And apologies on the wrong docker commit.

**Comment by rlifshay** [comment] 2017-06-03 09:34
I am writing a custom external pillar as well and seeing this issue. If I repeatedly call `pillar.items` using `salt-call` you can see it renders it twice for each call. I had more verbose logging on earlier and you can see it renders the entire pillar twice, it's not just calling only the external pillar.
```
09:15:52,683 [salt.transport.mixins.auth                           ][INFO    ][7175] Authentication request from ubuntu-xenial
09:15:52,683 [salt.transport.mixins.auth                           ][INFO    ][7175] Authentication accepted from ubuntu-xenial
09:15:52,743 [salt.loaded.ext.pillar.ssh_ca                        ][INFO    ][7172] Loading host key certificates for minion 'ubuntu-xenial'
09:15:52,807 [salt.loaded.ext.pillar.ssh_ca                        ][INFO    ][7174] Loading host key certificates for minion 'ubuntu-xenial'
09:15:52,822 [salt.utils.job                                       ][INFO    ][7173] Got return from ubuntu-xenial for job 20170603091552821936
09:15:54,427 [salt.transport.mixins.auth                           ][INFO    ][7171] Authentication request from ubuntu-xenial
09:15:54,427 [salt.transport.mixins.auth                           ][INFO    ][7171] Authentication accepted from ubuntu-xenial
09:15:54,482 [salt.loaded.ext.pillar.ssh_ca                        ][INFO    ][7175] Loading host key certificates for minion 'ubuntu-xenial'
09:15:54,541 [salt.loaded.ext.pillar.ssh_ca                        ][INFO    ][7172] Loading host key certificates for minion 'ubuntu-xenial'
09:15:54,550 [salt.utils.job                                       ][INFO    ][7174] Got return from ubuntu-xenial for job 20170603091554549462
09:15:56,129 [salt.transport.mixins.auth                           ][INFO    ][7173] Authentication request from ubuntu-xenial
09:15:56,130 [salt.transport.mixins.auth                           ][INFO    ][7173] Authentication accepted from ubuntu-xenial
09:15:56,197 [salt.loaded.ext.pillar.ssh_ca                        ][INFO    ][7171] Loading host key certificates for minion 'ubuntu-xenial'
09:15:56,253 [salt.loaded.ext.pillar.ssh_ca                        ][INFO    ][7175] Loading host key certificates for minion 'ubuntu-xenial'
09:15:56,262 [salt.utils.job                                       ][INFO    ][7172] Got return from ubuntu-xenial for job 20170603091556261587
```
if however I use `salt` instead of `salt-call` it only loads it once. That would make sense with `salt` from what @terminalmage was describing about rendering the pillar once when the minion initially connects to the master, and then once again later when you actually run the `pillar.items` command. However, the test cases in the previous comments were using `salt-call` like I am when I see the duplicate render steps. I am also not seeing any appreciable delay in between the two renders unlike @terminalmage.

**Comment by terminalmage** [comment] 2017-06-09 17:04
@rlifshay I can reproduce this. https://github.com/saltstack/salt/pull/41679 should address this.

**Closed** 2017-06-09 17:09 UTC
Labels: Has Testcase, Pending Discussion
