### ISSUE TITLE
DeprecationWarning for "osmajorrelease" breaks huge amounts of states / module functions

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#36677] opened 2016-09-29 14:26 UTC
Since latest update:
```
root@salt-euc1-01:~# lsb_release -d
Description:    Debian GNU/Linux 8.6 (jessie)
root@salt-euc1-01:~# salt-cloud --version
salt-cloud 2016.3.3 (Boron)
root@salt-euc1-01:~# salt-minion --version
salt-minion 2016.3.3 (Boron)
root@salt-euc1-01:~# salt-master --version
salt-master 2016.3.3 (Boron)
```

There comes this warning:
```
[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.
```

which breaks states in my setup for direct boto calls and also masses of other modules which calls 2nd level module functions.

**Workaround:**
I setup a system.fixes states with a patch:
```
{%- if grains.saltversioninfo[0] == 2016 and
         grains.saltversioninfo[1] == 3    and
         grains.saltversioninfo[2] == 3     %}
/usr/lib/python2.7/dist-packages/salt/grains/core.py:
  file.patch:
    - name: /usr/lib/python2.7/dist-packages/salt/grains/core.py
    - source: salt://system/files/saltstack_grains_core.py.patch
    - hash: md5=0e3eb44b2ca4945d473dc7bcdf6fa708
{%- endif %}
```

```
--- /usr/lib/python2.7/dist-packages/salt/grains/core.py.orig   2016-08-26 18:55:37.000000000 +0000
+++ /usr/lib/python2.7/dist-packages/salt/grains/core.py        2016-09-22 18:22:45.149977545 +0000
@@ -1490,7 +1490,7 @@
             osrelease_info[idx] = int(value)
         grains['osrelease_info'] = tuple(osrelease_info)
         grains['osmajorrelease'] = str(grains['osrelease_info'][0])  # This will be an integer in the two releases
-        salt.utils.warn_until('Nitrogen', 'The "osmajorrelease" will be a type of an integer.')
+        #salt.utils.warn_until('Nitrogen', 'The "osmajorrelease" will be a type of an integer.')
         os_name = grains['os' if grains.get('os') in (
             'FreeBSD', 'OpenBSD', 'NetBSD', 'Mac', 'Raspbian') else 'osfullname']
         grains['osfinger'] = '{0}-{1}'.format(
```

**Comment by Ch3LL** [comment] 2016-09-29 20:20
@Reiner030 this is a duplicate of https://github.com/saltstack/salt/issues/36359 which is fixed in https://github.com/saltstack/salt/pull/36068 which will be included in the next 2016.3.4 release which I believe is slated to be released in october. Closing due to being a duplicate.

**Closed by Ch3LL** 2016-09-29 20:20 UTC
