### ISSUE TITLE
gitfs is broken with gitpy2 is broken 2014.7.4-4

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#22721] opened 2015-04-15 22:34 UTC
Testing 2014.7.4-4 from epel-testing repo and found that gitfs returns zero objects when using pygit2

python-pygit2-0.20.3-4.el6.x86_64
Amazon Linux

Master Config:
```
gitfs_provider: pygit2
gitfs_remotes:
  - git@github.com:account/saltstack.git:
    - privkey: /root/.ssh/github-saltstack-id_rsa
    - pubkey: /root/.ssh/github-saltstack-id_rsa.pub
  - ssh://git@github.com/account/saltstack-iis-formula.git:
    - privkey: /root/.ssh/github-saltstack-iis-formula-id_rsa
    - pubkey: /root/.ssh/github-saltstack-iis-formula-id_rsa.pub
  - ssh://git@github.com/account/saltstack-cassandra-formula.git:
    - privkey: /root/.ssh/github-saltstack-cassandra-id_rsa
    - pubkey: /root/.ssh/github-saltstack-cassandra-id_rsa.pub
  - ssh://git@github.com/account/apache-formula.git:
    - privkey: /root/.ssh/github-saltstack-id_rsa
    - pubkey: /root/.ssh/github-saltstack-id_rsa.pub

```

Log
```
2015-04-15 22:20:57,770 [salt.loaded.int.fileserver.gitfs][DEBUG   ] Set lock for ssh://git@github.com/account/apache-formula.git
2015-04-15 22:20:57,770 [salt.loaded.int.fileserver.gitfs][DEBUG   ] gitfs is fetching from ssh://git@github.com/account/apache-formula.git
2015-04-15 22:20:58,590 [salt.loaded.int.fileserver.gitfs][DEBUG   ] gitfs received 0 objects for remote ssh://git@github.com/account/apache-formula.git
2015-04-15 22:20:59,124 [salt.loaded.int.fileserver.gitfs][DEBUG   ] gitfs cleaned the following stale refs: ['refs/remotes/origin/master', 'refs/remotes/origin/style-short-dec']
2015-04-15 22:20:59,125 [salt.loaded.int.fileserver.gitfs][DEBUG   ] Removed lock for ssh://git@github.com/account/apache-formula.git
2015-04-15 22:20:59,127 [salt.fileserver  ][DEBUG   ] Updating roots fileserver cache
```

Resolved this problem by reverting to Salt 2014.7.1

**Comment by terminalmage** [comment] 2015-04-17 21:56
The "received 0 objects" log message just means that the repo is up to date. I don't think this is a bug. Try stopping your master and removing the cache directory using ``rm -rf /var/cache/salt/master/gitfs``, then start up the master again. The first time the repo is fetched, you should see a non-zero number of objects.

**Comment by deuscapturus** [comment] 2015-04-26 00:36
Recently upgraded the salt master to 2014.7.5-1.  And this problem is back.  Yes.  I've deleted all gitfs cache (before and again now).  salt-run fileserver.update reports "gitfs received 0 objects for remote". salt-run fileserver.file_list shows none of the files in my git repo.  This was working before I upgraded.  I am not crazy.

**Comment by deuscapturus** [comment] 2015-04-26 00:51
I think this is the same issue as https://github.com/saltstack/salt/issues/23013

**Comment by terminalmage** [comment] 2015-04-27 14:28
Again, the "0 objects" message is returned from a successful fetch, and nothing else.

No one is saying you're crazy, I just can't reproduce this issue. It's possible that the github host key is not in your known_hosts file. See [here](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#adding-the-ssh-host-key-to-the-known-hosts-file).

**Comment by terminalmage** [comment] 2015-04-27 14:41
Well, now that I think about it, if you're getting a successful fetch, you definitely have the host key, so nevermind that.

**Comment by terminalmage** [comment] 2015-04-27 14:43
It looks like stale refs detection might have regressed, the log message seems to indicate that the master branch was cleaned. I'll investigate further.

**Comment by terminalmage** [comment] 2015-04-27 16:21
Yes, this is the same issue as #23013, I've opened a pull request to fix this. See https://github.com/saltstack/salt/issues/23013#issuecomment-96729498 for further details.

Closing this one as a duplicate.

**Closed by terminalmage** 2015-04-27 16:21 UTC
Labels: Duplicate
