### ISSUE TITLE
Complaints about pyOpenSSL version on Saltstack 2015.8.3

### ISSUE THREAD

**Issue by zmalone** [saltstack/salt#29581] opened 2015-12-09 21:18 UTC
When 2015.8.3 is installed on Ubuntu 14.04 from repo.saltstack.com, I get the following error on run:

```
[ERROR   ] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
```

**Comment by jfindlay** [comment] 2015-12-09 21:34
@zmalone, thanks for the report.

**Comment by zmalone** [comment] 2015-12-09 22:17
To provide a little more troubleshooting information, these errors end up flooding the /var/log/salt logs.

pyOpenSSL should probably be added at an appropriate version to the repos in https://repo.saltstack.com/apt/ubuntu/ubuntu14/ .

**Comment by abednarik** [comment] 2015-12-09 22:59
Same  issue #28872

**Comment by dmurphy18** [comment] 2015-12-09 23:30
@abednarik the repo for ubuntu 14.04 does not contain any openssl packages, either python-openssl or pyOpenSSL.  My currently up to date Ubuntu 14.04 has python-openssl 0.13-2ubuntu6.  Are you requesting that repo.saltstack.com provide a later version of python-openssl than that provided by Ubuntu for 14.04 ?

**Comment by dmurphy18** [comment] 2015-12-09 23:34
@zmalone FYI - the layout for repo.saltstack.com has been changed, but hopefully backwards compatibility has not been broken this time.  This ws done to allow for better archiving of previous versions and different architectures.  For example:
apt/ubuntu/14.04/amd64/latest has the latest, most recent version of salt (2015.8.3), but if a fixed version is desired, then apt/ubuntu/14.04/amd64/archive/2015.8.3 is a better location.

**Comment by zmalone** [comment] 2015-12-10 00:16
In this case, the problem is that pyOpenSSL 0.14.1 was added as a dependency in 2015.8.0, but Ubuntu 14.04 does not include pyOpenSSL 0.14.1.  Most installers of Salt will probably assume that the repo contains all non-Ubuntu packages required to make Salt work without errors.

The repo layout should be irrelevant, other than that pyOpenSSL 0.14.1 is not included in the repo.

I'd guess that either making the x509 module non-core, adding pyOpenSSL 0.14.1 to your repos (along with an appropriate dependency), or finding a way to suppress the error so that salt doesn't fill its logs with complaints about pyOpenSSL would work.  I'd think building pyOpenSSL 0.14.1 is the easiest way to go, and has precedent in the SaltStack build of zeromq3_4.0.4.

Unfortunately, the build framework for repo.saltstack.com is not public (to the best of my knowledge), so I cannot contribute a pull request at this time.

**Comment by jojimt** [comment] 2015-12-16 18:11
Is there a work-around for this issue? Hitting this on my k8 vagrant set up.

**Comment by zmalone** [comment] 2015-12-16 18:53
The error can be ignored if you are not using the x509 module, and pyOpenSSL can be installed at a newer version by hand if you are.  Either way will work around the issue, although it's annoying to get non-stop errors when running Salt.

**Comment by dmurphy18** [comment] 2016-08-09 22:52
@zmalone The framework used to build repo.saltstack.com is open-sourced on git, salt-pack, and was made available during SaltConf 2016.  The problem with pyOpenSSL is that it has under gone an API change which can break some installations, and since not a core dependency, it has been left to the user as to which version of pyOpenSSL best suits their environment.

**Comment by dmurphy18** [comment] 2017-08-29 21:01
@zmalone Wondering if this old issue can be closed, or if the problem is still be experienced with later releases of Salt, current version is 2017.7.1

**Comment by dmurphy18** [comment] 2018-05-16 16:51
@zmalone Closing this due to age of issue, if the problem is still occurring, please feel free to reopen it with the --versions-report for the current version of Salt that it is occurring with.

**Closed by dmurphy18** 2018-05-16 16:51 UTC
Labels: Bug, High Severity, P3, Packaging, Platform

**Comment by keithpjolley** [comment] 2020-04-20 16:35
```
$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.10 (Final)
Release:	6.10
Codename:	Final

```


```
$ salt --versions-report
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/bin/salt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: urllib3>=1.21.1,!=1.25.0,!=1.25.1,<1.26


```


```
$ head `which salt`
#!/opt/rh/python27/root/usr/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'salt==3000','console_scripts','salt'
__requires__ = 'salt==3000'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('salt==3000', 'console_scripts', 'salt')()
    )

```


```
$ sudo salt-call -l debug state.apply
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: asic04.example.com
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'asic04.example.com', 'tcp://10.0.110.12:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'asic04.example.com', 'tcp://10.0.110.12:4506')
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'asic04.example.com', 'tcp://10.0.110.12:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file from saltenv 'v1.1.0', 'salt://top.sls'
[DEBUG   ] Could not find file from saltenv 'v3.1.0', 'salt://top.sls'
[DEBUG   ] Could not find file from saltenv 'v1.0.0', 'salt://top.sls'
[DEBUG   ] Could not find file from saltenv 'v3.0.1', 'salt://top.sls'
[DEBUG   ] Could not find file from saltenv 'v3.0.0', 'salt://top.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://top.sls'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'top.sls'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] LazyLoaded pillar.get
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[ERROR   ] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
[DEBUG   ] Error loading module.glusterfs: glusterfs server is not installed
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Could not LazyLoad state.sls_exists
[ERROR   ] Unable to render top file: Jinja variable 'AliasedLoader' object has no attribute 'state.sls_exists'
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'asic04.example.com', 'tcp://10.0.110.12:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    ----------
    no_|-states_|-states_|-None:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            No Top file or external nodes data matches found.
        name:
            No States
        result:
            False

```

**Comment by keithpjolley** [comment] 2020-04-20 16:49
btw - was able to get past the above errors with these magical incantations:
```
# pip install 'msgpack!=0.5.5,<1.0.0,>=0.5'
# pip install 'chardet<4,>=3.0.2'
# pip install idna
```
