### ISSUE TITLE
unit.utils.test_vmware.GetServiceInstanceTestCase.test_uncached_service_instance

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52819] opened 2019-05-02 22:10 UTC
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.utils.test_vmware/GetServiceInstanceTestCase/test_uncached_service_instance)
---

<module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'GetSi'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 1811, in setUp
    patcher.start()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1524, in start
    result = self.__enter__()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1393, in __enter__
    original, local = self.get_original()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1367, in get_original
    "{} does not have the attribute {!r}".format(target, name)
AttributeError: <module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'GetSi'
		
```

**Comment by waynew** [comment] 2019-05-02 22:12
Also fails on these:

- unit.utils.test_vmware.GetServiceInstanceTestCase.test_current_time_raise_vim_fault
- unit.utils.test_vmware.GetServiceInstanceTestCase.test_unauthenticated_service_instance
- unit.utils.test_vmware.GetServiceInstanceTestCase.test_current_time_raise_no_permission
- unit.utils.test_vmware.GetServiceInstanceTestCase.test_default_params
- unit.utils.test_vmware.GetServiceInstanceTestCase.test_cached_service_instance_different_host
- unit.utils.test_vmware.GetServiceInstanceTestCase.test_current_time_raise_runtime_fault

**Comment by Ch3LL** [comment] 2019-05-03 13:45
duplicate of https://github.com/saltstack/salt/issues/51886

**Closed by Ch3LL** 2019-05-03 13:45 UTC
Labels: 2019.2.1, Test Failure
