### ISSUE TITLE
Windows: Salt and nssm crash with an offline master

### ISSUE THREAD

**Issue by efficks** [saltstack/salt#28604] opened 2015-11-05 12:57 UTC
My setup: Windows Minion + Saltstack 2015.8 (but I have a similar problem with 2015.5)
I setup my minion with an unexisting IP address and I've got problem when starting the minion.

First of all, I've got a popup from nssm reporting a crash! This is a big showstopper for me because nssm won't restart automatically and will also be display in front of every UI including servers.

Second, I've got an exception from the minion. Why the minion does not just try to reconnect later? after waiting some seconds by example.

Maybe it's two different bug and they need to be splitted.

Saltstack crash log
```
2015-11-04 15:12:50,138 [salt.cli.daemons ][INFO    ][1776] Setting up the Salt Minion "minionname
![crash1](https://cloud.githubusercontent.com/assets/8975620/10968898/9b07603c-8392-11e5-94ea-89c220b81b9b.PNG)
"
2015-11-04 15:12:50,890 [salt.utils.process][DEBUG   ][1776] Created pidfile: c:\salt\var\run\salt-minion.pid
2015-11-04 15:12:50,930 [salt.config      ][DEBUG   ][1776] Reading configuration from C:\salt\conf\minion
2015-11-04 15:13:07,654 [salt.cli.daemons ][INFO    ][1776] The salt minion is starting up
2015-11-04 15:13:07,654 [salt.minion      ][INFO    ][1776] Minion is starting as user 'SYSTEM'
2015-11-04 15:13:07,664 [salt.utils.event ][DEBUG   ][1776] AsyncEventPublisher PUB socket URI: tcp://127.0.0.1:4510
2015-11-04 15:13:07,664 [salt.utils.event ][DEBUG   ][1776] AsyncEventPublisher PULL socket URI: tcp://127.0.0.1:4511
2015-11-04 15:13:07,664 [salt.utils.event ][INFO    ][1776] Starting pub socket on tcp://127.0.0.1:4510
2015-11-04 15:13:07,664 [salt.utils.event ][INFO    ][1776] Starting pull socket on tcp://127.0.0.1:4511
2015-11-04 15:13:07,664 [salt.minion      ][DEBUG   ][1776] Minion 'minionname' trying to tune in
2015-11-04 15:13:07,664 [salt.minion      ][DEBUG   ][1776] sync_connect_master
2015-11-04 15:13:07,694 [salt.crypt       ][DEBUG   ][1776] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'minionname', 'tcp://192.168.1.200:4506')
2015-11-04 15:13:07,824 [salt.transport.zeromq][DEBUG   ][1776] Generated random reconnect delay between '1000ms' and '11000ms' (9315)
2015-11-04 15:13:07,824 [salt.transport.zeromq][DEBUG   ][1776] Setting zmq_reconnect_ivl to '9315ms'
2015-11-04 15:13:07,824 [salt.transport.zeromq][DEBUG   ][1776] Setting zmq_reconnect_ivl_max to '11000ms'
2015-11-04 15:13:07,824 [salt.transport.zeromq][DEBUG   ][1776] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'minionname', 'tcp://192.168.1.200:4506', 'clear')
2015-11-04 15:14:07,860 [salt.cli.daemons ][INFO    ][1776] The salt minion is shut down
2015-11-04 15:14:07,860 [salt.log.setup   ][ERROR   ][1776] An un-handled exception was caught by salt's global exception handler:
SaltClientError: Attempt to authenticate with the salt master failed
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 113, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 275, in start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1634, in tune_in
    self.sync_connect_master()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 725, in sync_connect_master
    raise six.reraise(*future_exception)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 732, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 496, in eval_master
    yield pub_channel.connect()
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt\transport\zeromq.py", line 325, in connect
    yield self.auth.authenticate()
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltClientError: Attempt to authenticate with the salt master failed
2015-11-04 15:14:07,920 [tornado.general  ][DEBUG   ][1776] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 715, in remove_handler
    self._impl.unregister(fd)
  File "C:\salt\bin\lib\site-packages\zmq\eventloop\ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "C:\salt\bin\lib\site-packages\zmq\sugar\poll.py", line 71, in unregister
    idx = self._map.pop(socket)
KeyError: None
```
![crash1](https://cloud.githubusercontent.com/assets/8975620/10968902/a6be7816-8392-11e5-9c30-52b10e880e72.PNG)
![crash2](https://cloud.githubusercontent.com/assets/8975620/10968904/aa367764-8392-11e5-96e2-e57e956b42d9.PNG)

NSSM crash dump
```
<?xml version="1.0" encoding="UTF-16"?>
<DATABASE>
<EXE NAME="nssm.exe" FILTER="GRABMI_FILTER_PRIVACY">
    <MATCHING_FILE NAME="nssm.exe" SIZE="294912" CHECKSUM="0x6778F15F" BIN_FILE_VERSION="2.24.0.74" BIN_PRODUCT_VERSION="2.24.0.74" PRODUCT_VERSION="2.24" FILE_DESCRIPTION="The non-sucking service manager" PRODUCT_NAME="NSSM 32-bit" FILE_VERSION="2.24" LEGAL_COPYRIGHT="Public Domain; Author Iain Patterson 2003-2014" VERFILEDATEHI="0x0" VERFILEDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x55306" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="2.24.0.74" UPTO_BIN_PRODUCT_VERSION="2.24.0.74" LINK_DATE="08/31/2014 15:34:44" UPTO_LINK_DATE="08/31/2014 15:34:44" />
    <MATCHING_FILE NAME="uninst.exe" SIZE="178412" CHECKSUM="0x5848123E" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x60000" LINK_DATE="10/07/2014 04:40:23" UPTO_LINK_DATE="10/07/2014 04:40:23" />
    <MATCHING_FILE NAME="bin\libeay32.dll" SIZE="1362432" CHECKSUM="0xCC5BD532" BIN_FILE_VERSION="1.0.2.3" BIN_PRODUCT_VERSION="1.0.2.3" PRODUCT_VERSION="1.0.2c" FILE_DESCRIPTION="OpenSSL Shared Library" COMPANY_NAME="The OpenSSL Project, http://www.openssl.org/" PRODUCT_NAME="The OpenSSL Toolkit" FILE_VERSION="1.0.2c" ORIGINAL_FILENAME="libeay32.dll" INTERNAL_NAME="libeay32" LEGAL_COPYRIGHT="Copyright  © 1998-2005 The OpenSSL Project. Copyright © 1995-1998 Eric A. Young, Tim J. Hudson. All rights reserved." VERFILEDATEHI="0x0" VERFILEDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x14DEBA" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="1.0.2.3" UPTO_BIN_PRODUCT_VERSION="1.0.2.3" LINK_DATE="06/12/2015 18:48:16" UPTO_LINK_DATE="06/12/2015 18:48:16" VER_LANGUAGE="English (United States) [0x409]" />
    <MATCHING_FILE NAME="bin\libsodium-13.dll" SIZE="545104" CHECKSUM="0x3C48EE36" MODULE_TYPE="WIN32" PE_CHECKSUM="0x88B22" LINKER_VERSION="0x0" LINK_DATE="05/09/2015 10:09:49" UPTO_LINK_DATE="05/09/2015 10:09:49" />
    <MATCHING_FILE NAME="bin\python.exe" SIZE="26624" CHECKSUM="0xA4B7D9FF" MODULE_TYPE="WIN32" PE_CHECKSUM="0x1336A" LINKER_VERSION="0x0" LINK_DATE="05/23/2015 16:40:35" UPTO_LINK_DATE="05/23/2015 16:40:35" />
    <MATCHING_FILE NAME="bin\python27.dll" SIZE="2459648" CHECKSUM="0xDA940ED1" BIN_FILE_VERSION="2.7.10150.1013" BIN_PRODUCT_VERSION="2.7.10150.1013" PRODUCT_VERSION="2.7.10" FILE_DESCRIPTION="Python Core" COMPANY_NAME="Python Software Foundation" PRODUCT_NAME="Python" FILE_VERSION="2.7.10" ORIGINAL_FILENAME="python27.dll" INTERNAL_NAME="Python DLL" LEGAL_COPYRIGHT="Copyright © 2001-2015 Python Software Foundation. Copyright © 2000 BeOpen.com. Copyright © 1995-2001 CNRI. Copyright © 1991-1995 SMC." VERFILEDATEHI="0x0" VERFILEDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x259BF5" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="2.7.10150.1013" UPTO_BIN_PRODUCT_VERSION="2.7.10150.1013" LINK_DATE="05/23/2015 16:40:33" UPTO_LINK_DATE="05/23/2015 16:40:33" VER_LANGUAGE="Language Neutral [0x0]" />
    <MATCHING_FILE NAME="bin\pythonw.exe" SIZE="27136" CHECKSUM="0x9D57CA4C" MODULE_TYPE="WIN32" PE_CHECKSUM="0x13C55" LINKER_VERSION="0x0" LINK_DATE="05/23/2015 16:40:57" UPTO_LINK_DATE="05/23/2015 16:40:57" />
    <MATCHING_FILE NAME="bin\ssleay32.dll" SIZE="357888" CHECKSUM="0x927CF117" BIN_FILE_VERSION="1.0.2.3" BIN_PRODUCT_VERSION="1.0.2.3" PRODUCT_VERSION="1.0.2c" FILE_DESCRIPTION="OpenSSL Shared Library" COMPANY_NAME="The OpenSSL Project, http://www.openssl.org/" PRODUCT_NAME="The OpenSSL Toolkit" FILE_VERSION="1.0.2c" ORIGINAL_FILENAME="ssleay32.dll" INTERNAL_NAME="ssleay32" LEGAL_COPYRIGHT="Copyright  © 1998-2005 The OpenSSL Project. Copyright © 1995-1998 Eric A. Young, Tim J. Hudson. All rights reserved." VERFILEDATEHI="0x0" VERFILEDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x59326" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="1.0.2.3" UPTO_BIN_PRODUCT_VERSION="1.0.2.3" LINK_DATE="06/12/2015 18:48:16" UPTO_LINK_DATE="06/12/2015 18:48:16" VER_LANGUAGE="English (United States) [0x409]" />
    <MATCHING_FILE NAME="bin\w9xpopen.exe" SIZE="49664" CHECKSUM="0x14EB69E" MODULE_TYPE="WIN32" PE_CHECKSUM="0xEAF3" LINKER_VERSION="0x0" LINK_DATE="05/23/2015 16:39:20" UPTO_LINK_DATE="05/23/2015 16:39:20" />
    <MATCHING_FILE NAME="bin\DLLs\sqlite3.dll" SIZE="426496" CHECKSUM="0xF5BCBC4" MODULE_TYPE="WIN32" PE_CHECKSUM="0x762BC" LINKER_VERSION="0x0" LINK_DATE="05/23/2015 16:39:25" UPTO_LINK_DATE="05/23/2015 16:39:25" />
    <MATCHING_FILE NAME="bin\Scripts\easy_install-2.7.exe" SIZE="91999" CHECKSUM="0xACE88196" MODULE_TYPE="WIN32" PE_CHECKSUM="0x1CF85" LINKER_VERSION="0x0" LINK_DATE="07/17/2014 18:51:11" UPTO_LINK_DATE="07/17/2014 18:51:11" />
    <MATCHING_FILE NAME="bin\Scripts\easy_install.exe" SIZE="91999" CHECKSUM="0xACE88196" MODULE_TYPE="WIN32" PE_CHECKSUM="0x1CF85" LINKER_VERSION="0x0" LINK_DATE="07/17/2014 18:51:11" UPTO_LINK_DATE="07/17/2014 18:51:11" />
    <MATCHING_FILE NAME="bin\Scripts\pip.exe" SIZE="91971" CHECKSUM="0xACE88196" MODULE_TYPE="WIN32" PE_CHECKSUM="0x1CF85" LINKER_VERSION="0x0" LINK_DATE="07/17/2014 18:51:11" UPTO_LINK_DATE="07/17/2014 18:51:11" />
    <MATCHING_FILE NAME="bin\Scripts\pip2.7.exe" SIZE="91971" CHECKSUM="0xACE88196" MODULE_TYPE="WIN32" PE_CHECKSUM="0x1CF85" LINKER_VERSION="0x0" LINK_DATE="07/17/2014 18:51:11" UPTO_LINK_DATE="07/17/2014 18:51:11" />
    <MATCHING_FILE NAME="bin\Scripts\pip2.exe" SIZE="91971" CHECKSUM="0xACE88196" MODULE_TYPE="WIN32" PE_CHECKSUM="0x1CF85" LINKER_VERSION="0x0" LINK_DATE="07/17/2014 18:51:11" UPTO_LINK_DATE="07/17/2014 18:51:11" />
    <MATCHING_FILE NAME="bin\Scripts\wheel.exe" SIZE="91987" CHECKSUM="0xACE88196" MODULE_TYPE="WIN32" PE_CHECKSUM="0x1CF85" LINKER_VERSION="0x0" LINK_DATE="07/17/2014 18:51:11" UPTO_LINK_DATE="07/17/2014 18:51:11" />
</EXE>
<EXE NAME="kernel32.dll" FILTER="GRABMI_FILTER_THISFILEONLY">
    <MATCHING_FILE NAME="kernel32.dll" SIZE="993280" CHECKSUM="0x599F4100" BIN_FILE_VERSION="5.1.2600.6532" BIN_PRODUCT_VERSION="5.1.2600.6532" PRODUCT_VERSION="5.1.2600.6532" FILE_DESCRIPTION="Windows NT BASE API Client DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="5.1.2600.6532 (xpsp_sp3_qfe.140312-0419)" ORIGINAL_FILENAME="kernel32" INTERNAL_NAME="kernel32" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERFILEDATEHI="0x0" VERFILEDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0xF63D5" LINKER_VERSION="0x50001" UPTO_BIN_FILE_VERSION="5.1.2600.6532" UPTO_BIN_PRODUCT_VERSION="5.1.2600.6532" LINK_DATE="03/12/2014 10:48:50" UPTO_LINK_DATE="03/12/2014 10:48:50" VER_LANGUAGE="English (United States) [0x409]" />
</EXE>
</DATABASE>

```

**Comment by jfindlay** [comment] 2015-11-07 06:36
@efficks, thanks for the report.

@UtahDave, @twangboy

**Comment by efficks** [comment] 2015-11-10 16:42
@jfindlay Any update?

**Comment by UtahDave** [comment] 2015-11-10 17:45
I'll be working on this today.

**Comment by twangboy** [comment] 2015-11-10 18:07
@UtahDave @jfindlay It looks like it's a time out issue. It tries 7 times, 1 minute between each try. After the 7th try it says it failed to authenticate and then throws a stack trace. Looks like the fact that it doesn't wait forever is by design. Is this something we want/need to change?

**Comment by mathrick** [comment] 2015-11-10 18:14
For a running service at least it's reasonable to keep trying, otherwise there's no way to have minions reconnect after a transient network/master outage without restarting them manually, which sounds like a Bad Thing™ for a configuration manager.

**Comment by twangboy** [comment] 2015-11-10 18:39
@efficks @mathrick I just tried this on a linux box. It does the same thing, tries 7 times to connect and then fails to authenticate. The difference being that after it fails to authenticate, it restarts the process and starts over.This is probably a bug in how windows handles the restarting process.

**Comment by efficks** [comment] 2015-11-10 19:54
@twangboy @mathrick I agree with @mathrick, the service should not stop and be restarted by the system. On Windows, normally a service can be defined to be restarted automatically. But I don't think saltstack should rely on the OS to be restarted.
There's a bigger problem here, when saltstack crash (exception), NSSM seems to crash too! The OS pop an error message and the service is not restarted until the popup is dismissed. This is a HIGE problem. Also, it can occur with an other exception throw by saltstack. I think we have 2 distincts issues here.

**Comment by twangboy** [comment] 2015-11-10 23:42
@efficks I can't reproduce the NSSM problem you're having. Could you post the version of salt you are running. Is it 32 or 64 bit? Are you on 32 or 64 bit windows?

**Comment by efficks** [comment] 2015-11-11 01:40
@twangboy, I'm on Windows XP  32 bits.
Let me try tomorrow on Windows 7.

**Comment by efficks** [comment] 2015-11-19 14:37
@twangboy I only got this exception on Windows XP or Windows Server 2003.

**Comment by efficks** [comment] 2015-11-19 14:39
@twangboy Maybe the crash from NSSM can be cleanly get a workaround. Instead on throwing an exception when we can't connect on the master, we can simply exit the minion with a bas exit status.

**Comment by twangboy** [comment] 2015-11-19 16:57
The earliest operating system I have access to is 2003r2. I'm still not getting this error.

**Comment by twangboy** [comment] 2015-11-19 18:14
I've tried both 32 and 64 bit. You might try finding an older version of nssm. It was upgraded with 2015.5 I believe. It used to ship with this one: http://www.nssm.cc/ci/nssm-2.21-136-ga8cb477.zip

**Comment by UtahDave** [comment] 2016-01-20 01:43
Hi, @efficks can you try an older version of nssm? That might help. We don't have Windows XP to test against. Windows XP is eol'd and we don't officially support it anymore. If you have a system we can test against that might help.

**Comment by UtahDave** [comment] 2016-01-20 18:18
I'm going to close this issue for now since this bug is on unsupported platforms. Feel free to comment and we'll reopen if we can find a solution to this.

**Closed by UtahDave** 2016-01-20 18:18 UTC
Labels: Bug, High Severity, P3, Platform, TEAM Platform, Windows

**Comment by efficks** [comment] 2016-04-04 13:23
@UtahDave Version 2.23 of NSSM seems to fix my problem on Windows XP. See it's chanlog for 2.23 on their web page.
[https://nssm.cc/changelog](https://nssm.cc/changelog)
