### ISSUE TITLE
pkg.latest and yumpkg.latest_version return incorrect package versions 2016.3 and 2016.11

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#38037] opened 2016-12-01 22:42 UTC
### Description of Issue/Question
pkg.latest is not parsing package names and versions correctly, as shown with yumpkg.latest_version for python-tornado.

```
root@localhost:~# yum list python-tornado
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.fileplanet.com
 * epel: mirror.symnds.com
 * extras: mirror.symnds.com
 * updates: repos.mia.quadranet.com
Installed Packages
python-tornado.x86_64                                                                     4.2.1-1.el7                                                                     @salt-latest
Available Packages
python-tornado.noarch                                                                     2.2.1-8.el7                                                                     base        
root@localhost:~# 

The command 
root@localhost:~# salt c7m pkg.latest_version python-tornado
c7m:
   2.2.1-8.el7
```

should be the 4.2.1-1.el7

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Can be duplicated on 2016.3 and 2016.11 versions.
No special files required

### Steps to Reproduce Issue
salt c7m pkg.latest_version python-tornado

### Versions Report
```
root@localhost:~# salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: Linux
        version: CentOS Linux 7.1.1503 Core
```

**Comment by rickh563** [comment] 2016-12-01 22:46
ZD-1065

**Comment by dmurphy18** [comment] 2016-12-01 22:49
The code is probably not excluding the architecture correctly when considering the name of the package, also need to allow for the version correctly.  This is needed since packages may over time add or remove architecture components.

**Comment by screentan** [comment] 2016-12-01 23:54
You might need to be careful because 64-bit systems can purposely have both 64-bit and 32-bit versions of the same package.  They would usually be the same version through.

**Comment by terminalmage** [comment] 2016-12-02 06:04
The architecture has nothing to do with it. On a side note, why aren't you building a noarch for tornado in salt-pack, does newer tornado have compiled bits that necessitate an architecture-specific package?

From the [documentation] (emphasis mine):(https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.yumpkg.html#salt.modules.yumpkg.latest_version):

> Return the latest version of the named package available for upgrade or installation. If more than one package name is specified, a dict of name/version pairs is returned.
>
> ***If the latest version of a given package is already installed, an empty string will be returned for that package.***

So you're correct that the function is misbehaving, but it shouldn't be returning the 4.2.1 version, it should be returning an empty string. The issue is that ``yum list available python-tornado`` is reporting the version from the ``base`` repo, because ``list available`` reports when a version is available for installation in a given repo.

This is an easy fix.

**Comment by terminalmage** [comment] 2016-12-02 06:33
Fixed in #38045.

**Comment by damon-atkins** [comment] 2016-12-02 09:15
I would suggest a better solution would be to use the yum python modules instead. Might even be faster.

**Comment by terminalmage** [comment] 2016-12-02 15:09
No, we've been down that road before and, frankly, the yum API was loaded with bugs, which in turn caused several nasty bugs in Salt that we had to work around. It's possible that the dnf API is more robust, and we at some point may revisit using the API for dnf, but definitely not for yum.

**Comment by damon-atkins** [comment] 2016-12-02 15:34
Interesting.

**Closed** 2016-12-19 20:22 UTC
Labels: 2016.3.5, Bug, Fixed Pending Verification, High Severity, P1, TEAM Core, ZD
