### ISSUE TITLE
python error in iptables if an insert rule is the only one rule

### ISSUE THREAD

**Issue by mochrul** [saltstack/salt#33624] opened 2016-05-30 19:26 UTC
### Description of Issue/Question
If there is only one rule in the ipables sls and that rule is an insert rule, a python error would appear.

### Setup

```
noise_10020100:
  iptables.insert:
    - table: filter
    - chain: INPUT
    - jump: DROP
    - source: '10.2.1.0'
```

### Steps to Reproduce Issue
When you run state.highstate you will get the following error message:

```
          ID: noise_10020100
    Function: iptables.insert
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1703, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1649, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/iptables.py", line 547, in insert
                  if not __salt__['iptables.insert'](table, kwargs['chain'], kwargs['position'], rule, family):
              KeyError: 'position'
     Started: 21:11:47.767851
    Duration: 52.405 ms
     Changes:   
```

### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Master:

```
# salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-79-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

Minion:

```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.4 
```

**Comment by Ch3LL** [comment] 2016-05-31 23:03
@mochrul diving into the code it looks like `position` is a required argument. Here is an example from teh docs:

```
httpd:
  iptables.insert:
    - position: 1
    - table: filter
    - chain: INPUT
    - jump: ACCEPT
    - match: state
    - connstate: NEW
    - dport: 80
    - proto: tcp
    - sport: 1025:65535
    - save: True
```

If you specify position in your sls are you still seeing an error?

**Comment by mochrul** [comment] 2016-06-01 17:40
No, if I specify the position, I get no error and it working.

**Comment by Ch3LL** [comment] 2016-06-01 19:50
@mochrul  Great! i'm glad its working! are you okay to close this?

**Comment by mochrul** [comment] 2016-06-01 21:10
Yes, of course.

**Comment by Ch3LL** [comment] 2016-06-01 22:40
@mochrul great thanks

**Closed by Ch3LL** 2016-06-01 22:40 UTC
Labels: Expected Behavior, Info Needed

**Comment by boltronics** [comment] 2018-06-27 03:59
Just hit this on 2017.7.4. The [docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.iptables.html#salt.states.iptables.insert) make no mention that `position` is a required argument. If the current behaviour is considered to be ideal, the docs should be updated to reflect this intended behaviour.

However I feel this is far from ideal. From the `iptables` man page:

> -I, --insert chain [rulenum] rule-specification
> Insert  one or more rules in the selected chain as the given rule number. So, if the rule number is 1, the rule or rules are inserted at the head of the chain.  This is also the default if no rule number is specified.

I imagine most people familiar with iptables use this to insert at the default position of 1, and aren't used to explicitly specifying it when not required. Regardless, this state has deviated from the expected iptables behaviour and is mandating an argument that is normally optional. When not given the argument it needs, it dies in a quite ugly manner by throwing an exception trace to the user. It would be good to have both of these problems addressed to be more in line with user expectations.
