### ISSUE TITLE
unit.modules.test_telegram.TelegramModuleTest.test_post_message - dictionary keys must be an imported module

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52925] opened 2019-05-07 16:23 UTC
Similar error as #52815, but `TelegramModuleTest` was different. Might be a dupe?

2019.2.1 failed [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/unit.modules.test_telegram/TelegramModuleTest/test_post_message), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/unit.modules.test_telegram/TelegramModuleTest/test_post_message)
develop failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/unit.modules.test_telegram/TelegramModuleTest/test_post_message)
---

The dictionary keys returned by TelegramModuleTest.setup_loader_modules() must be an imported module, not <class 'str'>

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 382, in wrapper
    type(module)
RuntimeError: The dictionary keys returned by TelegramModuleTest.setup_loader_modules() must be an imported module, not <class 'str'>
		
```

**Comment by garethgreenaway** [comment] 2019-05-10 23:38
Duplicate of #52817, fixed with https://github.com/saltstack/salt/pull/52972

**Closed** 2019-05-13 22:06 UTC
Labels: 2019.2.1, Blocker, Test Failure
