### ISSUE TITLE
schedule running state.orchestrate fails

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#27392] opened 2015-09-25 00:49 UTC
Schedule is on the master as follows:

```saltstack
schedule:
  update_inventory:
    function: state.sls
    seconds: 3600
    args:
      - salt.update_inventory

  branch_based_refresh:
    function: state.orchestrate
    hours: 6
    splay: 600
    args:
      - orchestration.branch_based_refresh
```

On version 2015.5.5 fails with:

```python-traceback
2015-09-24 17:43:03,218 [salt.utils.schedule                      ][ERROR   ][19131] Unhandled exception running state.orchestrate
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 571, in handle_func
    channel = salt.transport.Channel.factory(self.opts, usage='salt_schedule')
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 61, in factory
    return ZeroMQChannel(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 264, in __init__
    self.master_uri = opts['master_uri']
KeyError: 'master_uri'
2015-09-24 17:43:08,303 [salt.utils.schedule                      ][ERROR   ][19119] Unhandled exception running state.sls
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 571, in handle_func
    channel = salt.transport.Channel.factory(self.opts, usage='salt_schedule')
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 61, in factory
    return ZeroMQChannel(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 264, in __init__
    self.master_uri = opts['master_uri']
KeyError: 'master_uri'
```

On 2015.8.0 fails with:

```python-traceback
2015-09-24 17:44:16,711 [salt.utils.schedule                      ][ERROR   ][21954] Unhandled exception running state.orchestrate
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 703, in handle_func
    channel = salt.transport.Channel.factory(self.opts, usage='salt_schedule')
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 29, in factory
    return ReqChannel.factory(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/client.py", line 22, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 59, in __init__
    self.async = method(*args, **kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 32, in current_ioloop
    yield
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 59, in __init__
    self.async = method(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/client.py", line 101, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 78, in __new__
    new_obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 121, in __singleton_init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self._io_loop)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 316, in __new__
    key = cls.__key(opts)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 333, in __key
    opts['master_uri'],  # master ID
KeyError: 'master_uri'
2015-09-24 17:44:31,102 [salt.loaded.int.module.tls                 ][ERROR   ][21951] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
2015-09-24 17:44:50,515 [salt.transport.zeromq                    ][ERROR   ][21837] Bad load from minion
```

2015.5.5 is from epel, 2015.8.0 is repo.saltstack.com. Versions report follows (only for 2015.8.0)

```yaml
ahammond@salt.anchorfree.net[salt]:~ $ sudo salt-call test.versions_report
local:
    Salt Version:
               Salt: 2015.8.0
     
    Dependency Versions:
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.3.1
             Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
               RAET: 0.6.3
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: 1.2.1
           cherrypy: Not Installed
           dateutil: 1.4.1
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: 1.3.8
            libnacl: 1.4.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.1
            timelib: 0.2.4
     
    System Versions:
               dist: centos 6.7 Final
            machine: x86_64
            release: 2.6.32-504.3.3.el6.x86_64
             system: CentOS 6.7 Final
```

And I note that the gitpython is reported as not installed, although it clearly is.

```console
ahammond@salt.anchorfree.net[salt]:~ $ rpm -qa | grep -i git | grep -i python
GitPython-0.3.2-0.6.RC1.el6.noarch
python-gitdb-0.5.4-2.el6.x86_64
```

**Comment by ahammond** [comment] 2015-09-25 00:56
The orchestration is well tested, so I don't think it's that.

**Comment by jfindlay** [comment] 2015-09-25 16:27
@ahammond, thanks for the report.

**Comment by ymote** [comment] 2015-10-26 08:37
SAME HERE


local:
    Salt Version:
               Salt: 2015.8.1
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.6
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-48-generic
             system: Ubuntu 14.04 trusty

**Comment by redmcg** [comment] 2015-10-26 08:46
I've ran in to this problem too and using 2015.8.1 can easily reproduce it on both CentOS 6.7 and Ubuntu 14.04.3.

To reproduce - I just installed salt-master (no need for any minions) and added a schedule conf file to the /etc/salt/master.d directory. For example (/etc/salt/master.d/my_schedule.conf):
```yaml
schedule:
  schedule_test:
    function: my_schedule.test
    seconds: 30
```

The function being called is a simple custom runner (/srv/runners/my_schedule.py):
```python
import salt.client

def test():
    client = salt.client.LocalClient(__opts__['conf_file'])
    return client.cmd('*', 'test.ping')
```
This will quickly result in the exception starting at line 703 of utils/schedule.py shown above.

The workaround I'm using at the moment it to set 'return_job' to False. For example:
```yaml
schedule:
  schedule_test:
    function: my_schedule.test
    seconds: 30
    return_job: False
```
By setting `return_job: False` the code at line 703 of utils/schedule.py is skipped (thus no exception). I believe that code is trying to send the result back to the master. But the scheduler is running as part of the master so I'm not even sure if that's necessary.

When I add the line: `returner: syslog` I can see the returner is working. For example - with three minions using the above config I'll see the following in my system log:
```json
Oct 26 01:37:10 salt-master python2.6: salt-minion: {"jid": "20151026013708863996", "return": {"minion1.localdomain": true, "minion2.localdomain": true, "minion3.localdomain": true}, "success": true, "schedule": "schedule_test", "pid": 4773, "fun": "my_schedule.test", "id": "salt-master.localdomain_master"}
```

CentOS 6.7:
```yaml
Version report for CentOS 6.7:
    Salt Version:
               Salt: 2015.8.1
     
    Dependency Versions:
             Jinja2: unknown
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
             Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: centos 6.7 Final
            machine: x86_64
            release: 2.6.32-573.7.1.el6.x86_64
             system: CentOS 6.7 Final
```

Ubuntu 14.04.3:
```yaml
    Salt Version:
               Salt: 2015.8.1
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.4.0
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.19.0-31-generic
             system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment] 2015-10-27 23:04
ping @garethgreenaway

**Comment by garethgreenaway** [comment] 2015-10-27 23:15
Looks like return_job is on by default, needs to check if it's a master scheduled job and not return.  Will take a look. Thanks for the report.

**Comment by cachedout** [comment] 2015-11-09 22:50
@garethgreenaway Have you had a chance to look at this by chance?

**Comment by garethgreenaway** [comment] 2015-11-09 22:54
@cachedout Not yet.  Will take a look today.

**Comment by rallytime** [comment] 2016-05-24 20:35
@ahammond, @ymote, or @redmcg Are you guys still running into this issue? I was able to reproduce it on 2015.8.1, as you reported, but I am unable to reproduce is in 2015.8.2 and newer, all the way up to the latest release, 2015.8.10. I wanted to check with you guys before closing up.

**Comment by ahammond** [comment] 2016-05-25 01:09
Seems to be working now.

**Comment by rallytime** [comment] 2016-05-25 15:03
Great! Thanks for confirming. I'll close this.

**Closed by rallytime** 2016-05-25 15:03 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P2
