### ISSUE TITLE
top.sls: range not working as expected?

### ISSUE THREAD

**Issue by gdubroeucq** [saltstack/salt#41002] opened 2017-05-02 12:16 UTC
### Description of Issue/Question

In my top.sls, i would like to match a range of minion like this:
```

'toto[1-5]':
 - something
```

So "something" will be apply to toto1, toto2,..., toto5. (as expected)

but when i write:

```
'toto[1-50]':
 - something
```

It includes toto0 aswell.

You can try this with:
` salt 'toto[1-50]' test.ping`

Is it expected or i use it incorrectly ?

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: Linux
        version: CentOS Linux 7.1.1503 Core

**Comment by Ch3LL** [comment] 2017-05-02 15:24
This regex `toto[1-50]` with not find number 1-50, because regex deals in characters not numbers with that regex you have defined.

I created this regex which should work: `toto[1-9]?\b|toto[1-5][0-9]` (it might not be the most efficient way to do it since i'm not a regex master but as far as i understand you can't just do toto[1-50] to get hte range 1-50. I've just ben using this site to try to create a regex; http://pythex.org

Closing as this is expected behavior but please let me know if it still does not work.

**Closed by Ch3LL** 2017-05-02 15:24 UTC
