### ISSUE TITLE
Key 'file_ignore_glob' with value None has an invalid type of NoneType

### ISSUE THREAD

**Issue by emeryray02** [saltstack/salt#41627] opened 2017-06-07 11:28 UTC
We are getting this warning when running salt master:
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value

Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-78-generic
         system: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment] 2017-06-07 16:42
This is fixed in https://github.com/saltstack/salt/pull/32117

Which made it into 2015.8.10  https://docs.saltstack.com/en/latest/topics/releases/2015.8.10.html

This is a duplicate of #32114

**Closed by gtmanfred** 2017-06-07 16:42 UTC
