### ISSUE TITLE
salt 'testMinion' pkg.available_version firefox gives IndexError: pop from empty list

### ISSUE THREAD

**Issue by pratiktest** [saltstack/salt#34497] opened 2016-07-06 20:22 UTC
### Description of Issue/Question
Hi,
I am running **salt minion 2016.3.1** on a **windows 2003** server

**master is Ubuntu 14.04**

I am following documentation at
https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#windows-software-repository to install packages on remote  windows salt-minion

i ran the following in my master
//sls files used to install windows packages (these do not come in by default)
`salt-run winrepo.update_git_repos`

//run pkg.refresh on every minion
`salt -G 'os:windows' pkg.refresh_db`

and then restarted my master

`salt -G 'os:windows' pkg.list_pkgs` works and gives me all the pkg installed

`salt testMinion pkg.available_version firefox` fails and gives me following error

```
salt 'testMinion' pkg.available_version firefox
testMinion:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1318, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 97, in latest_version
        latest_available = _get_latest_pkg_version(pkg_info)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1099, in _get_latest_pkg_version
        return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
    IndexError: pop from empty list

```

`salt-run winrepo.genrepo` contains entries for firefox

```
firefox:
        ----------
        29.0.1:
            ----------
            full_name:
                Mozilla Firefox 29.0.1 (x86 en-US)
            install_flags:
                /s
            installer:
                http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/29.0.1/win32/en-US/Firefox%20Setup%2029.0.1.exe
            locale:
                en_US
            msiexec:
                False
            reboot:
                False
```

When i try to install any package minion responds saying package not found

```

salt testMinion pkg.install 'firefox' -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master-9660.slc01.dev.xxx.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master-9660.slc01.dev.xxx.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-07-06T20:15:48.055042'}
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] get_iter_returns for jid 20160706131548063742 sent to set(['testMinion']) will timeout at 13:15:53.067444
[DEBUG   ] jid 20160706131548063742 return from testMinion
[DEBUG   ] LazyLoaded nested.output
testMinion:
    ----------
    firefox:
        Unable to locate package firefox
[DEBUG   ] jid 20160706131548063742 found all minions set(['testMinion'])

```

**Comment by Ch3LL** [comment] 2016-07-06 21:59
@pratiktest I'm not seeing the same behavior with a windows2012. Can you ensure the firefox sls file was synced down to the minion by running:

`salt 'minion' cmd.run 'dir c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\'`

**Comment by pratiktest** [comment] 2016-07-06 22:06
looks like it was not synced

```
root@salt-master-9660:/home/prkale# salt 'testMinion' cmd.run 'dir c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\'
testMinion:
    The system cannot find the file specified.

```

shouldn't this command sync the file?
`salt -G 'os:windows' pkg.refresh_db`

**Comment by Ch3LL** [comment] 2016-07-06 22:21
@pratiktest yes `pkg.refresh_db` should be syncing that file and that cache directory path should be correct unless you are using different salt environments. 

What is the output when you run pkg.refresh_db on that minion?

**Comment by AvinashDeluxeVR** [comment] 2016-07-06 23:03
@Ch3LL @pratiktest  I had this issue also. The cause of all my issues was that the salt master on Ubuntu and the salt minion on Windows were on different versions. The latest version for Ubuntu is 2015.5.3 and the latest version for Windows is 2016.3.1 

The tutorial is slightly misleading as it doesn't indicate that both master and minion should be on the same versions.

**Comment by Ch3LL** [comment] 2016-07-06 23:12
@AvinashDeluxeVR thanks for the input! Really appreciate it. That does indeed explain why you were running into this issues since the old and new winrepo used a different directory structure as explained [here](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#maintaining-windows-repo-definitions-in-git-repositories) We do not support a master that is a lower version then minions in general although we could probably make it more clear in those docs specifically since they user different directory structures between the two. Would you mind opening up a separate issue to add those docs?

@pratiktest does @AvinashDeluxeVR 's information help you out at all

**Comment by pratiktest** [comment] 2016-07-06 23:37
that is true, sorry i forgot to put my salt master version here

```
root@salt-master-9660:/home/prkale# salt-master --version
salt-master 2015.5.3 (Lithium)
root@salt-master-9660:/home/prkale# 
```

@AvinashDeluxeVR : to solve this issue did you downgrade the salt version on the minion?

**Comment by AvinashDeluxeVR** [comment] 2016-07-06 23:46
@pratiktest Yes I downgraded Salt minion to 2015.5.3 to match the salt master

Here are the links

[2015.5.3 x64](https://repo.saltstack.com/windows/Salt-Minion-2015.5.3-2-AMD64-Setup.exe)
[2015.5.3 x86](https://repo.saltstack.com/windows/Salt-Minion-2015.5.3-2-x86-Setup.exe)
[All previous versions](https://repo.saltstack.com/windows/)

**Comment by AvinashDeluxeVR** [comment] 2016-07-07 00:34
@pratiktest Just another "gotcha" Ubuntu asked me to upgrade, which also upgraded my salt master to 2015.8.8 which then got me into this mismatch situation again.

**Comment by pratiktest** [comment] 2016-07-07 00:40
thanks for such quick help.

I just brought up a test vm in windows and matched the version to salt-master and it worked

Also when i do pkg.refresh_db this time it returned true, while for minions with higher version it did not return anything. **If it would have returned false , I would have known that sync failed**

```
root@salt-master-9660:~# salt -G 'os:windows' pkg.refresh_db
testminlower:
    True
testMinion:
progTestMinion:

```


**Installing package works after matching salt-master version with minion**

```

root@salt-master-9660:~# salt testminlower pkg.install 'firefox'
testminlower:
    ----------
    Mozilla Maintenance Service:
        ----------
        new:
            47.0
        old:
    firefox:
        ----------
        new:
            47.0
        old:

```

Is it possible to have good informative error message since the stack trace did not help me ?

Also a note in the [documentation](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html) tutorial would surely help for beginners like me :)

Thanks again for such quick responses.

**Comment by mbrgm** [comment] 2016-07-13 15:51
I can confirm the bug for salt-master 2016.3.1 in combination with salt-minion 2016.3.1.

**Comment by TheBigBear** [comment] 2016-07-14 17:12
@mbrgm the 'bug' as documented and tracked  here is not a bug but  a 'feature'  if one mixes master and minion of different versions. 

Can you document or backup your claim that using the identical version on master and windows minion you still get that ```IndexError: pop from empty list``` as you try to install a pkg?

**Comment by mbrgm** [comment] 2016-07-26 14:30
@TheBigBear 

```
$ salt-master --version
salt-master 2016.3.1 (Boron)

$ salt 'salt-minion.example.com' test.version
salt-minion.example.com:
    2016.3.1

$ salt 'salt-minion.example.com' grains.get os
salt-minion.example.com:
    Windows

$ salt 'salt-minion.example.com' pkg.available_version firefox
salt-minion.example.com:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1318, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 97, in latest_version
        latest_available = _get_latest_pkg_version(pkg_info)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1099, in _get_latest_pkg_version
        return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
    IndexError: pop from empty list
```

**Comment by TheBigBear** [comment] 2016-07-26 21:13
@mbrgm ok, a few more tests, please.

1. post your ```firefox.sls``` contents here, please.


2.
```salt 'salt-minion.example.com' cmd.run 'dir c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\firefox*'``` is it synced to the right version size and date?

3.
```salt 'salt-minion.example.com' winrepo.show_sls salt-winrepo-ng/firefox```

Do all of those work, or do some of them show other errors? I have seen 'pop from empty list' simply mean that the jinja2 sls file could not be compiled because of a syntax error.

**Comment by mbrgm** [comment] 2016-07-27 08:03
@TheBigBear 

1. see no. 2
2. It is not synced at all, although I ran `salt -G 'os:windows' pkg.refresh_db` before (and before that `salt-run winrepo.update_git_repos` on the master).

  In fact, `c:\salt\var\cache\salt\minion\files\base\win\repo-ng` is empty except for a `winrepo.p` file. This is the output:

  ```
$ salt-run winrepo.update_git_repos
https://github.com/saltstack/salt-winrepo-ng.git:
    /srv/salt/win/repo-ng/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo

$ salt -G 'os:windows' pkg.refresh_db
salt-minion.example.com:

$ echo $?
0
  ```

  and the file_roots section of my master config:

  ```
file_roots:
  base:
    - /srv/salt/state
    - /srv/salt/formulas/*
    - /srv/salt/win
  ```

3. see no. 2

**Comment by TheBigBear** [comment] 2016-07-27 16:01
@mbrgm did your masters or minions ever run earlier than 2015.8 (Berryllium)? If so did you read up on the changes between the config files for winrepo -> winrepo-ng?
particularly the changes referenced here? https://docs.saltstack.com/en/2015.8/topics/windows/windows-package-manager.html#winrepo-changes

What do the following return for you?

```salt salt-minion.example.com pkg.get_repo_data```
```salt salt-minion.example.com cmd.run 'c:\salt\salt-call  pkg.get_repo_data'```

do those two show the 'same' output? and what about?
```salt salt-minion.example.com cmd.run 'c:\salt\salt-call  --local pkg.get_repo_data'```

Is there 'any' pkgs being listed with any of these three instead?

```salt salt-minion.example.com winrepo.genrepo```
```salt salt-minion.example.com cmd.run 'c:\salt\salt-call  winrepo.genrepo'```
```salt salt-minion.example.com cmd.run 'c:\salt\salt-call  --local winrepo.genrepo'```

**Comment by mbrgm** [comment] 2016-07-28 09:18
@TheBigBear This is the output of the commands you aked for. The minion is running Windows 7 x64 with DE locale, so unfortunately the returned errors are in german language. It complains about the missing 'ServerManager' module. Let me know if you need help or a translation to figure something out.

```
$ salt 'salt-minion.example.com' pkg.get_repo_data                                                                                                       [51/51]
salt-minion.example.com:
    ----------
$ salt 'salt-minion.example.com' cmd.run 'c:\salt\salt-call pkg.get_repo_data'                                                                                  
salt-minion.example.com:
    local:
        ----------
$ salt 'salt-minion.example.com' cmd.run 'c:\salt\salt-call --local pkg.get_repo_data'
salt-minion.example.com:
    local:
        ----------
$ salt 'salt-minion.example.com' winrepo.genrepo
salt-minion.example.com:
    ----------
$ salt 'salt-minion.example.com' cmd.run 'c:\salt\salt-call winrepo.genrepo'
salt-minion.example.com:
    [ERROR   ] Command 'Import-Module ServerManager' failed with return code: 1
    [ERROR   ] output: Import-Module : Das angegebene Modul "ServerManager" wurde nicht geladen, da in
    
     keinem Modulverzeichnis eine gültige Moduldatei gefunden wurde.
    
    Bei Zeile:1 Zeichen:14
    
    + Import-Module <<<<  ServerManager
    
        + CategoryInfo          : ResourceUnavailable: (ServerManager:String) [Imp 
    
       ort-Module], FileNotFoundException
    
        + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Comm 
    
       ands.ImportModuleCommand
    [ERROR   ] Command '$PSVersionTable.PSVersion.Major | ConvertTo-Json' failed with return code: 1
    [ERROR   ] output: Die Benennung "ConvertTo-Json" wurde nicht als Name eines Cmdlet, einer Funktio
    
    n, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie 
    
    die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), u
    
    nd wiederholen Sie den Vorgang.
    
    Bei Zeile:1 Zeichen:49
    
    + $PSVersionTable.PSVersion.Major | ConvertTo-Json <<<< 
    
        + CategoryInfo          : ObjectNotFound: (ConvertTo-Json:String) [], Comm 
 a   
  aa     andNotFoundException
    
        + FullyQualifiedErrorId : CommandNotFoundException
    local:
        ----------
$ salt 'salt-minion.example.com' cmd.run 'c:\salt\salt-call --local winrepo.genrepo'
salt-minion.example.com:
    [ERROR   ] Command 'Import-Module ServerManager' failed with return code: 1
    [ERROR   ] output: Import-Module : Das angegebene Modul "ServerManager" wurde nicht geladen, da in
    
     keinem Modulverzeichnis eine gültige Moduldatei gefunden wurde.
    
    Bei Zeile:1 Zeichen:14
    
    + Import-Module <<<<  ServerManager
    
        + CategoryInfo          : ResourceUnavailable: (ServerManager:String) [Imp 
    
       ort-Module], FileNotFoundException
    
        + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Comm 
    
       ands.ImportModuleCommand
    [ERROR   ] Command '$PSVersionTable.PSVersion.Major | ConvertTo-Json' failed with return code: 1
    [ERROR   ] output: Die Benennung "ConvertTo-Json" wurde nicht als Name eines Cmdlet, einer Funktio
    
    n, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie 
    
    die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), u
    
    nd wiederholen Sie den Vorgang.
    
    Bei Zeile:1 Zeichen:49
    
    + $PSVersionTable.PSVersion.Major | ConvertTo-Json <<<< 
    
        + CategoryInfo          : ObjectNotFound: (ConvertTo-Json:String) [], Comm 
    
       andNotFoundException
    
        + FullyQualifiedErrorId : CommandNotFoundException
    local:
        ----------
```

**Comment by TheBigBear** [comment] 2016-07-28 21:45
@mbrgm the ```winrepo.genrepo``` output is fine. But the ```pkg.get_repo_data``` is not.

You should be seeing a name_map of all the pkgs first, followed by all the pkgs in the winrepo-ng.

Have another good look at the config files and how your winrepo-ng config is set up right now, as asked above (https://github.com/saltstack/salt/issues/34497#issuecomment-235633113), but you never answered those questions on whether you had been running older versions of salt master or minions or both?
make sure the changes highligted in the following link have been done on your system.
https://docs.saltstack.com/en/2015.8/topics/windows/windows-package-manager.html#winrepo-changes

**Comment by mbrgm** [comment] 2016-07-29 12:56
@TheBigBear They didn't run earlier than 2015.8, but when I read the whole article you posted (not just the changes part), I found what I was looking for: It's the `winrepo_source_dir` config parameter (default: `salt://win/repo`), which obviously wouldn't work with the file_roots config I posted above:
 
```
file_roots:
base:
  - /srv/salt/state
  - /srv/salt/formulas/*
  - /srv/salt/win
```

When I changed the last line to `/srv/salt`, everything worked as expected. Thank you very much for your help!

**Comment by TheBigBear** [comment] 2016-07-29 17:14
@pratiktest @Ch3LL this is not an issue (and never was). ;-) Agreed?

And the two people that thought they had this, have now found the setup error and fixed it. I think this can now be closed.

**Comment by pratiktest** [comment] 2016-08-04 19:14
Yes we can,  my issue got resolved after i ensured version of minion = version of master. Only request I had is if this can be mentioned in some documentation or a proper error message is returned it would be clear what the exact issue is. Since I am not much aware of the salt code base ``Index error: pop from empty list `` dosent give me any information.

**Comment by TheBigBear** [comment] 2016-09-03 12:07
@Ch3LL can you please close this. As has been confirmed by the folks on this issue, this is now resolved and never was an actual issue. Unless you want to keep this open to work on writing a  better error message, as suggested by @pratiktest in  https://github.com/saltstack/salt/issues/34497#issuecomment-237654297

**Comment by rallytime** [comment] 2016-09-06 15:05
Thanks for reminding us @TheBigBear! Much appreciated.

**Closed** 2016-09-06 15:04 UTC
Labels: Cannot Reproduce, Info Needed
