### ISSUE TITLE
[BUG] RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#57584] opened 2020-06-08 10:53 UTC
**Description**
Warning raised on py38
> [WARNING] /usr/lib/python3/dist-packages/salt/utils/files.py:396: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage

**Setup**
Unfortunately, there's no indication of which state triggered it, and I was applying a big highstate for the first time. The following state functions applied changes:
<details>

```
alternatives.set
cmd.mod_watch
cmd.run
file.absent
file.append
file.blockreplace
file.directory
file.managed
file.prepend
file.recurse
file.replace
file.uncomment
ini.options_present
mount.mounted
mount.unmounted
pip.installed
pkg.installed
pkgrepo.managed
service.running
ssh_auth.present
sysctl.present
timezone.system
ufw.allow
ufw.enabled
ufw.limit
user.absent
user.present
x509.certificate_managed
x509.pem_managed
x509.private_key_managed
```
</details>

**Expected behavior**
There should be no warnings during normal operation

**Versions Report**
Master is 3000.3
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3001rc1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: 1.0.3
         Python: 3.8.2 (default, Apr 27 2020, 15:53:34)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: ubuntu 20.04 focal
         locale: iso8859-1
        machine: x86_64
        release: 5.4.0-33-generic
         system: Linux
        version: Ubuntu 20.04 focal
```
</details>

**Additional context**

**Comment by frogunder** [comment] 2020-06-08 20:21
@OrangeDog Thank you for reporting this issue.

Not sure what triggered that warning, but will ping the core team for input and awareness.

@saltstack/team-core Any thoughts on this one?

Thanks.

**Comment by OrangeDog** [comment] 2020-06-09 09:24
Got it with debug logging enabled:
```
[INFO] Running state [/etc/ssh/sshd_config] at time 10:16:16.914930
[INFO] Executing state file.replace for [/etc/ssh/sshd_config]
[WARNING] /usr/lib/python3/dist-packages/salt/utils/files.py:396: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage

[INFO] File changed:
---
+++
@@ -113,7 +113,7 @@
 AcceptEnv LANG LC_*

 # override default of no subsystems
-Subsystem      sftp    /usr/lib/openssh/sftp-server
+Subsystem sftp /usr/lib/openssh/sftp-server

 # Example of overriding settings on a per-user basis
 #Match User anoncvs

[INFO] Completed state [/etc/ssh/sshd_config] at time 10:16:16.958029 (duration_in_ms=43.099)
```
That's [this state from openssl-formula](https://github.com/saltstack-formulas/openssh-formula/blob/v0.43.3/openssh/config_ini.sls#L12).

**Comment by OrangeDog** [comment] 2020-06-09 09:38
So the problem is here (default `bufsize` is 1).
https://github.com/saltstack/salt/blob/v3001rc1/salt/modules/file.py#L2552

**Comment by gvengel** [comment] 2020-06-15 19:27
Also seeing this issue. Confirmed the warning goes away if [file.py](https://github.com/saltstack/salt/blob/v3001rc1/salt/modules/file.py#L2552) is modified to either open the file as text or with buffering disabled.

**Comment by boltronics** [comment] 2020-09-06 07:09
This is still a thing in `3001.1+ds-1` on Ubuntu 20.04:
```
[WARNING ] /usr/lib/python3/dist-packages/salt/utils/files.py:396: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
```

For now, I just modified `/usr/lib/python3/dist-packages/salt/utils/files.py` and changed:

```
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
```

to

```
    if 'mode' in kwargs and 'b' in kwargs["mode"]:
        kwargs["buffering"] = 0
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
```

**Comment by OrangeDog** [comment] 2020-09-07 08:21
@boltronics it should also check for `kwargs['buffering'] == 1` before changing it.

**Comment by boltronics** [comment] 2020-09-07 08:47
@OrangeDog In that case, I think just `kwargs['buffering']` would be better (without a ` == 1` check)?

**Comment by OrangeDog** [comment] 2020-09-07 08:57
@boltronics no? Any value other than 1 will work. Although 2 is a very poor choice of buffer size.

**Comment by boltronics** [comment] 2020-09-07 14:12
Oh okay I see - I didn't realise it was strictly only 1 with the issue. Thanks.

**Comment by OrangeDog** [comment] 2020-09-07 14:27
1 is a magic number that means "line buffering", on the assumption that nobody wants a 1-byte buffer.

**Comment by EHJ-52n** [comment] 2020-09-15 11:54
This is still an issue but the [workaround](#issuecomment-687713733) provided by @boltronics works for me.

<details>
 <summary>sudo salt-call -V</summary>

```
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 4.1.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-47-generic
         system: Linux
        version: Ubuntu 20.04 focal
```

</details>

**Comment by xcorvis** [comment] 2020-10-29 17:39
Still getting this in 3002.

<details>
  <summary>sudo salt-call -V</summary>

```
Salt Version:
           Salt: 3002
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-52-generic
         system: Linux
        version: Ubuntu 20.04 focal
```

</details>

**Comment by EHJ-52n** [comment] 2020-11-12 11:31
Still getting this in 3002.1

<details>
 <summary>sudo salt-call -V</summary>

```
Salt Version:
           Salt: 3002.1
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: 8.9.1
       dateutil: 2.7.3
      docker-py: 4.1.0
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: 0.31.0
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.4
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 1.0.3
         Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-53-generic
         system: Linux
        version: Ubuntu 20.04 focal
```

</details>

**Comment by EHJ-52n** [comment] 2020-11-20 07:51
....and in 3002.2
<details>
 <summary>sudo salt-call -V</summary>

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.0
      cherrypy: 8.9.1
      dateutil: 2.7.3
     docker-py: 4.1.0
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: 0.31.0
          Mako: 1.1.0
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: 2.19
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-54-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

</details>

**Comment by sagetherage** [comment] 2021-02-17 19:29
The Core team isn't going to get to this in `Aluminium`, but we will review a PR and attempt to get that merged.

**Comment by OrangeDog** [comment] 2021-02-19 17:20
Note that this also means any documentation that says something like "The default value 1 processes one line at a time" is wrong.

Possibly some proper core work is required to sort out when text or binary mode should be used (a possible leftover from py2->p3) and which operations should support line buffering.

**Comment by EHJ-52n** [comment] 2021-03-31 06:51
...and in 3002.6
<details>
 <summary>sudo salt-call -V</summary>

```
 Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: 1.14.0
      cherrypy: 8.9.1
      dateutil: 2.7.3
     docker-py: 4.1.0
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: 0.31.0
          Mako: 1.1.0
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: 2.19
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-70-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

</details>

**Comment by jbouter** [comment] 2021-08-06 08:22
Taking over @EHJ-52n's tradition,

Still present in 3003.1 on Debian 11

```
$ sudo salt-call state.apply locale
[WARNING ] /usr/lib/python3/dist-packages/salt/utils/files.py:396: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
```

<details>
<summary>sudo salt-call -V</summary>
<p>

```
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.11.22-1-pve
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

</p>
</details>

**Comment by EHJ-52n** [comment] 2021-08-18 07:37
Thank you very much, @jbouter.

...and in 3003.2 on ubuntu 21.04 still present:

<details>
 <summary>sudo salt-call -V</summary>

```
Salt Version:
          Salt: 3003.2
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: 8.9.1
      dateutil: 2.8.1
     docker-py: 4.1.0
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 2.11.2
       libgit2: 1.1.0
      M2Crypto: 0.37.1
          Mako: 1.1.3
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.5 (default, May 11 2021, 08:20:37)
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 21.04 hirsute
        locale: utf-8
       machine: x86_64
       release: 5.11.0-26-generic
        system: Linux
       version: Ubuntu 21.04 hirsute
```

</details>

**Comment by EHJ-52n** [comment] 2021-09-13 11:22
Thank you very much, @jbouter.

...and in 3003.3 on ubuntu 21.04 still present:

<details>
 <summary>sudo salt-call -V</summary>

```
Salt Version:
          Salt: 3003.3
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: 8.9.1
      dateutil: 2.8.1
     docker-py: 4.1.0
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 2.11.2
       libgit2: 1.1.0
      M2Crypto: 0.37.1
          Mako: 1.1.3
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.5 (default, May 11 2021, 08:20:37)
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 21.04 hirsute
        locale: utf-8
       machine: x86_64
       release: 5.11.0-34-generic
        system: Linux
       version: Ubuntu 21.04 hirsute
```

</details>

**Comment by scy** [comment] 2021-10-29 21:09
A possible workaround if you don’t want to patch Salt’s source code is to set `bufsize: file` in your SLS. Tested successfully in Salt 3004 with Python 3.9.7 in a `file.replace` state.

Note that this might not be feasible if you are working with a large file, but it should be fine for most config files etc.

**Comment by xcorvis** [comment] 2021-11-01 18:32
@scy Thanks for the workaround, I didn't realize this was an option.

Just a couple of suggestions for alternate ways to handle this:
1. Drop this to an INFO, not a WARNING.
2. Fix the binary detection. None of my files triggering this are binary, they're all plain text.

**Comment by OrangeDog** [comment] 2021-11-01 19:50
The problem is all the core code was written assuming py2, where `str` and `bytes` are the same thing.
There are cases when files were deliberately read as text with line buffering, and cases where it's deliberately bytes with fixed buffers.

The choice is either work through all the relevant code paths and correct them based on which was the intention, or throw it all away by just deleting the parameter throughout , which keeps the behaviour as it currently is.

The second option won't make anything worse, but the first option will probably improve performance in some places, back to their py2 levels.

**Comment by rjc** [comment] 2021-12-01 21:01
> A possible workaround if you don’t want to patch Salt’s source code is to set `bufsize: file` in your SLS.

@scy, thanks a lot for that! I finally got rid of this annoying warning!

BTW, official _Salt 3004_ packages from project's [repository](https://repo.saltproject.io/) on _Ubuntu 20.04 LTS_.

**Comment by EHJ-52n** [comment] 2021-12-02 08:47
> A possible workaround if you don’t want to patch Salt’s source code is to set bufsize: file in your SLS. Tested successfully in Salt 3004 with Python 3.9.2 in a file.replace state.

@scy could you please add some more details. Maybe, provide a link to the according documentation or post your example here.

**Comment by scy** [comment] 2021-12-02 17:35
> @scy could you please add some more details

Okay. Let’s recap. The issue, as [pointed out](https://github.com/saltstack/salt/issues/57584#issuecomment-641168925) by @OrangeDog, is that [`file.replace` uses a default `bufsize` of `1`](https://github.com/saltstack/salt/blob/v3004/salt/modules/file.py#L2351), apparently [assuming that this means “line-buffered”](https://github.com/saltstack/salt/blob/v3001rc1/salt/modules/file.py#L2400-L2401). And it indeed [_would_ mean line-buffered](https://docs.python.org/3/library/functions.html#open) if the file was opened in text (not binary) mode – but [it isn’t](https://github.com/saltstack/salt/blob/v3001rc1/salt/modules/file.py#L2552).

The [workaround](https://github.com/saltstack/salt/issues/57584#issuecomment-687713733) suggested by @boltronics changes Salt’s file opening code to completely disable buffering when the file is opened in binary mode. All of the read/write operations on that file then will issue real filesystem requests (I guess) which may lead to a bit of degraded performance, depending on how many operations you’re actually doing. (NB: This is just guesswork, I haven’t measured any of this and I assume it will have no noticeable real-world impact in most scenarios.)

Instead of disabling buffering, you might as well set it to any value greater than `1` to mean “use a buffer that’s X bytes in size”. Any value other than `1` will make the warning go away, because `1` is reserved for line-based buffering, but you can’t use line-based buffering on a binary file. (See [Python’s `open()` documentation](https://docs.python.org/3/library/functions.html#open).)

As [stated in the documentation for `file.replace`](https://github.com/saltstack/salt/blob/v3004/salt/modules/file.py#L2399-L2401), `file.replace` also understands the special value `"file"` that means “[make the buffer as large as the file](https://github.com/saltstack/salt/blob/v3004/salt/modules/file.py#L2519-L2520)”. This will read the whole file into RAM, but all read operations will then not need to talk to the disk at all.

Also, and this is why I chose `bufsize: file` as my suggestion: It works without modifying Salt’s source code.

If you’d like to have an example for where to apply this workaround: Simply modify the `file.replace` use in your SLS to include `bufsize: file`, e.g.

```yaml
add_login_group_to_winbind_ssh_access_list:
  file.replace:
    - name: '/etc/security/pam_winbind.conf'
    - pattern: '^(require_membership_of = )(.*)$'
    - repl: '\1\2,append-new-group-to-line'
    - bufsize: file
```

You could, as a workaround, just as well basically use any integer > 1. Python’s default buffer size depends on the block size and might be something like 4096 or 8192.

The best solution, in my opinion, would be to not make the buffer size configurable at all and rely on Python’s defaults. Deprecate and/or ignore the `bufsize` parameter for `file.replace` (and other `file` functions that might be doing something similar). Why do you even want to configure such a low-level detail in the first place?

**Comment by scy** [comment] 2021-12-02 18:14
> Why do you even want to configure such a low-level detail in the first place?

Answering my own question: I’ve checked, and `bufsize` was included from the very commit that brought us `file.replace` in the first place, 89ebfc02d6682e39cdcc79db974773f5657a9fce. Its intention seems to be to make sure that multi-line search/replace works: The documentation points out that [you need to use `bufsize: file` for multi-line searches](https://github.com/saltstack/salt/blob/89ebfc02d6682e39cdcc79db974773f5657a9fce/salt/modules/file.py#L910-L918) because line buffering.

Okay, that’s a good reason, I guess. Or it was back then.

However, [nowadays the file is `mmap`ped anyway](https://github.com/saltstack/salt/blob/v3001rc1/salt/modules/file.py#L2555). Does the buffer size make any difference (in functionality, not in speed) at all anymore? Multi-line searches should work regardless of what `bufsize` is set to, or am I missing something here? Could we simply get rid of `bufsize` altogether and use Python’s defaults?

**Comment by OrangeDog** [comment] 2021-12-02 20:52
> I chose `bufsize: file` as my suggestion

Just to note that if the file is really big then that's a terrible idea.

**Comment by scy** [comment] 2021-12-02 21:37
> > I chose `bufsize: file` as my suggestion
> 
> Just to note that if the file is really big then that's a terrible idea.

You’re totally right :) Which is why I [originally wrote](https://github.com/saltstack/salt/issues/57584#issuecomment-955049346)

> Note that this might not be feasible if you are working with a large file, but it should be fine for most config files etc.

**Comment by zhuo1988** [comment] 2022-07-13 07:14
[WARNING ] /usr/lib/python3/dist-packages/salt/utils/files.py:396: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage

This problem always bothers me. How to solve this problem? Repeated installations always make mistakes. What can be done to solve this problem?

**Comment by LHozzan** [comment] 2022-07-13 07:22
> This problem always bothers me. How to solve this problem? Repeated installations always make mistakes. What can be done to solve this problem?

This two years old problem I personally "patch" by using older working salt version (yes, buggy too, but include small amount of bugs, that impact my automation) and it seems, that for final solution I must looking for some another automation toolkit ...
If nobody want fix this problem two years, I begining be sceptic :(.

**Comment by scy** [comment] 2022-07-13 15:15
There is a simple workaround in https://github.com/saltstack/salt/issues/57584#issuecomment-955049346. It should work for ≥ 95 % of use cases.

There’s also an explanation on why this issue is possibly not trivial to fix in https://github.com/saltstack/salt/issues/57584#issuecomment-956538491. So, if I were a developer on the Salt project, a bug

* that has an easy workaround
* is probably hard to fix correctly
* and doesn’t even cause issues except for printing a warning message

might not be that high on my list either.

**Closed** 2022-10-06 19:51 UTC
Labels: Bug, severity-medium
