### ISSUE TITLE
As of 2015.5.0, docker 1.5.0 cannot be used with quay.io (and presumably others)

### ISSUE THREAD

**Issue by tkent-xetus** [saltstack/salt#23612] opened 2015-05-12 19:44 UTC
After upgrading to docker 2015.5.0 the `docker.running` and `docker.installed` states always return an error in the following form for quay.io/\* images, when using docker 1.5.0.

```
image "quay.io/xyz/abc" does not exist
```

It's unlikely this is specific to quay.io, since the images are already locally downloaded on the minions when this error occurs. This appears to be due to the combination to #23610 and #13305.

We were able to work around the issue by upgrading to docker 1.6.1, but that might not be an option for everyone.

In case it's helpful here's the docker and salt information:

``` yaml
salt-call --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1

docker --version
Docker version 1.5.0, build a8a31ef
```

**Comment by blueyed** [comment] 2015-09-28 18:39
@tkent-xetus 
Is this still an issue for you?
Can you provide more information from any investigations, in case you've worked around or solved this?

**Comment by tkent** [comment] 2015-09-28 18:44
@blueyed 

Happy to test with a newer version of salt. Are you interested if it works with the newer docker-ng stuff in  `2015.8` or perhaps a patched version of the docker-io stuff in `2015.5.5`?

**Comment by blueyed** [comment] 2015-09-29 14:21
@tkent 
For me it is now working with 2015.8 and Docker 1.8.2, but there was a missing bug fix in the stable branch (https://github.com/saltstack/salt/pull/25162).

**Comment by blueyed** [comment] 2015-09-29 14:22
Was merged now in https://github.com/saltstack/salt/pull/27497.

**Comment by blueyed** [comment] 2015-09-29 18:05
> since the images are already locally downloaded on the minions when this error occurs

That seems like is a different issue then the one I've linked to above.

**Comment by tkent** [comment] 2015-09-29 23:52
@blueyed 

You're right, your patch is for a different issue. Certainly confusing though, since the symptom's are all around the existence of a docker image.

The one filed here is specific to docker `1.5.0` and salt `2015.5.X`, and occurs regardless of wether or not the image is already available locally. Just to close the loop, I did confirm that all versions of `2015.5.[0-5]` exhibit the same issue when using docker `1.5.0` (and possibly earlier versions).  You can work around the issue by using docker `1.6.1` or greater, or using salt before `2015.5`. The version match necessary to see the issue is probably why you haven't observed it locally.

I did not check if salt `2015.8` works with docker `1.5.0`, since the users on `2015.8` are very unlikely to be using an older version of docker.


---
For anybody considering picking up this issue, I think the community has voted that this is not a priority. If it was, you'd see a bunch of +1's here. Since it's easy enough to work around by moving either salt versions or docker versions, I think it's not worth fixing.

**Comment by tkent** [comment] 2017-04-20 19:25
@jfindlay @rallytime 

Like #23610, I think we close this. Both docker and salt have far moved on.

**Closed** 2017-04-20 19:33 UTC
Labels: Bug, High Severity, P1, Platform, Regression, State Module
