### ISSUE TITLE
While running an orchestration event passing in custom pillar data a highstate executed in the orchestration renders all blank pillar data

### ISSUE THREAD

**Issue by bgridley** [saltstack/salt#42592] opened 2017-07-27 16:12 UTC
### Description of Issue/Question
While running an orchestration event passing in custom pillar data a highstate executed in the orchestration renders all blank pillar data. This behavior is new after upgrading to 2017.7.0. It's almost as if the custom pillar data overwrites all existing pillar data for any state that runs in an orchestration file.

### Setup
The salt master is running Ubuntu 14.04 the minion is running Ubuntu 16.04. Minion and master are on the same salt version.

#/srv/salt/orch/new-host.sls
{% set tag = salt['pillar.get']('event_tag') %}
{% set data = salt['pillar.get']('event_data') %}
initial-highstate:
  salt.state:
    - tgt: {{ data.hostname }}
    - highstate: True

#/srv/salt/pillar
dns:
  server1: 8.8.8.8

#/srv/salt/dnsmask/init.sls
dnsmasq:
  pkg.installed:
    - name: dnsmasq
  service.running:
    - enable: True

/etc/dnsmasq.conf:
  file.managed:
    - source: salt://dnsmasq/files/dnsmasq.conf
    - template: jinja
    - mode: 755
    - watch_in:
      - service: dnsmasq

ignore-resolvconf:
  file.uncomment:
    - name: /etc/default/dnsmasq
    - regex: 'IGNORE_RESOLVCONF=yes'
    - watch_in:
      - service: dnsmasq

/etc/resolv.conf:
  file.symlink:
    - target: /run/resolvconf/resolv.conf
    - force: True

#/srv/salt/dnsmasq/files/dnsmasq.conf
server={{ salt['pillar.get']('dns:server1') }}

#also have some pillar data available to the minion in /srv/pillar/ that is required in a highstate as shown above.

### Steps to Reproduce Issue

Step 1. 
#Run a state.highstate on the minion (This command confirms that all pillar data is available to the minion). Running this below command will place the '/etc/dnsmasq.conf' file on the minion with the 'server=8.8.8.8' line added.
salt minion state.highstate

Step 2.
#After running a highstate on the minion all is well. However after the next command weather triggered from a reactor or called manually problems begin to arise. (This command confirms that pillar data returns null when running a highstate through orchestration) Running this below command will remove the line from '/etc/dnsmasq.conf' and replace it with 'server='

salt-run --out=json state.orchestrate orch.new-host pillar='{"event_data": {"_stamp": "2017-07-25T21:40:32.702598", "event": "created instance", "instance_id": "i-xxxxxxxxxxxxxxxx", "name": "minion", "profile": "ec2-homeauto-16-04", "provider": "ec2" }, "event_tag": "salt/cloud/minion/created"}'

#After doing the above the highstate runs from orch but all pillar values return as null resulting in missing configuration parameters, etc... Repeating Steps 1 and Steps 2 continues to swap out pillar data with the correct value to the null value from the minion configuration.

### Versions Report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: 0.3.6
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-65-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment] 2017-07-27 16:25
I believe this is fixed here

https://github.com/saltstack/salt/pull/42433

and a duplicate of this.

https://github.com/saltstack/salt/issues/42403

We are working on getting a 2017.7.1 release out to fix this.

Thanks,
Daniel

**Closed by gtmanfred** 2017-07-27 16:25 UTC
