### ISSUE TITLE
Vmware cloud driver: NIC not connected

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#23315] opened 2015-05-04 08:41 UTC
See #23312 for profile configuration.

Once the template has been cloned and the machine is running the NIC is not set to "connected" (and neither to "connect at power on"). This results in the machine not being reachable over the network, and results in `salt-cloud` being stuck at "Waiting to get IP information"

My template is based on Ubuntu 14.04 with `open-vm-tools` installed (as VMware recommends using this rather than their tar.gz one as it is easier to update)

**Comment by nmadhok** [comment] 2015-05-04 09:34
@syphernl Looking at the specs that were generated, it looks like the NIC was set to connect at boot ``startConnected = true``. How do you manually connect the NIC?

**Comment by syphernl** [comment] 2015-05-04 09:38
@nmadhok But it also says `connected = false`. 
You can connect the NIC via the vSphere client => VM => VM settings => NIC => Tick connected.

**Comment by nmadhok** [comment] 2015-05-04 09:45
@syphernl ``connected = false`` indicates whether the device is currently connected. Valid only while the virtual machine is running. The specs are generated before the deployment and since you're using a template, it's anyway powered off. Can you try to clone from a VM instead of a template that already has the NIC connected?

**Comment by syphernl** [comment] 2015-05-04 09:58
The template was created based on a VM that has the NIC connected. With the template-VM off the checkbox for connected is unchecked bt the "connect on power on" one is checked.

I have converted the Template back to a VM. The NIC in the template VM has the right checkmark set. If I let salt-cloud clone based on the "template VM" rather than the "template" there is no difference in behavior: the NIC does not get checked to enable on boot.

If I manually clone the "template vm" (or template) via the vSphere Client the created VM ends up *with* a checked "Connect at power on". ISTM something in the "post-cloning" process disables the checkbox somehow?

**Comment by nmadhok** [comment] 2015-05-04 10:17
@syphernl For some reason, I'm unable to reproduce this. I have the NIC connected and able to get an IP after about 90 seconds.

**Comment by syphernl** [comment] 2015-05-04 10:20
Odd, perhaps you are on a different version/revision of vCenter?

**Comment by nmadhok** [comment] 2015-05-04 13:42
@syphernl I'm running vCenter 5.5

**Comment by nmadhok** [comment] 2015-05-04 13:57
@syphernl Can you change ``adapter_type`` for the NIC from ``vmxnet3`` to ``e1000`` and try again?? Since you already have the NIC added in the template, you may have to delete it from your template and then try to clone the template.

**Comment by nmadhok** [comment] 2015-05-04 21:03
Just realized this issue is a duplicate of #23270

**Comment by nmadhok** [comment] 2015-05-04 21:43
@syphernl I created a template for Ubuntu 14.04 and deployed it using the same profile that you had and I didn't not experience any problem. The configuration was created properly in ``/etc/network/interfaces`` and the NIC was connected after boot. Once thing that's different is that I didn't have any NIC on the template and I had VMware tools installed instead of open-vm-tools. 

As long as the IP is visible in vcenter, salt-cloud should be able to get the IP and use it to ssh.

**Comment by jfindlay** [comment] 2015-05-04 23:44
Thanks, @nmadhok.  @syphernl, if you have any further information or questions, you're welcome to comment at #23270.

**Closed by jfindlay** 2015-05-04 23:44 UTC
Labels: Duplicate
