### ISSUE TITLE
although runas deprecation is a long run, zcbuildout needs it again 

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21202] opened 2015-03-02 00:17 UTC
can @cachedout or @thatch45 have a word here please.
This is the reopening of #21196

I think that the params glue that i readded back can prevent from ***ugly***  damages, without being really either intrusive in the codecase or in maintenance...

Why not accepting it.

@s0undt3ch i know that you are not agreeing, but can i have others word please, do not just answer no or close the issue ...

**Comment by kiorky** [comment] 2015-03-02 00:19
The main problem my coworkers are facing with salt is that it moves too fast from them.
Being rude on the upgrade path will just loose them.

**Comment by kiorky** [comment] 2015-03-02 00:20
see #21197 (mergeable, just closed), simple, & user friendly ...

**Comment by s0undt3ch** [comment] 2015-03-02 00:30
We're not being rude on the update path. As I said on https://github.com/saltstack/salt/issues/21196, runas was deprecated for enough versions.

Also, since you filed a new issue, not convinced of my response, and you're also asking other devs to pitch in, I wouldn't simply close it.

The other devs will be quite busy the next couple of days because of [SaltConf](http://saltconf.com/), so please allow a few days before pinging...

**Comment by kiorky** [comment] 2015-03-02 00:32
You are rude here ;) and i also know they are busy, i can afford to wait, no problem.

**Comment by kiorky** [comment] 2015-03-02 00:33
to @cachedout & @thatch45 ...
I also updated that branch, to remove the documentation about runas, (it got in as i took the revert patch from 27b7cdae90c5ef6c926846d2363b7086fb924c08 as a base)

**Comment by s0undt3ch** [comment] 2015-03-02 00:47
Why was I rude? I would have been rude if I closed the issue and PR without any justification, and that was not the case. Let's not make this a personal issue because it ain't.

Cool? :)

**Comment by kiorky** [comment] 2015-03-02 01:05
It is not personal, can we please stop the cockfight here as stated when opening this issue, you are on the opposite position from the beginning.

From a really poor user user like me, i feel that there is really room for discussion here, so let the interested persons have their words, when they will have time.

If i was not interested at first by making salt better, i won't post here, it is way quickier to fork, @s0undt3ch, but being forced to fork just because something miss some simple & non harmful backward compat glue is just idiot.

**Comment by thatch45** [comment] 2015-03-02 03:49
Are we doing this again @kiorky ?
@s0undt3ch was right to close the PR and issue, and I would appreciate it if every time we disagreed with you on something that you would not start a fight.

I am leaning toward the removal of zcbuildout from the mainline modules, it has been a problem in the test suite since it was introduced, has been problematic for users and is not widely used. So far it has been heavier to maintain then we think it is worth.

So I propose that we move the zcbuildout module and states into salt-contrib.
Please vote here:
#21209

**Comment by kiorky** [comment] 2015-03-02 08:53
Guess what, i will be the silent majority.

**Comment by kiorky** [comment] 2015-03-02 09:00
cc @regilero @toutpt @fle @gagaro @jpcw @ebrehault @davisp1 @gutard @leplatrem

**Comment by basepi** [comment] 2015-03-02 18:00
I'm going to close this, since it's a duplicate of #21196. See there for the discussion about the deprecation path of runas.

**Closed by basepi** 2015-03-02 18:00 UTC
