### ISSUE TITLE
Pillar show_top not working on ext_pillar git backend

### ISSUE THREAD

**Issue by mpaolini** [saltstack/salt#27730] opened 2015-10-06 23:00 UTC
`salt-run pillar.show_top` returns nothing

**Comment by Ch3LL** [comment] 2015-10-07 21:36
@mpaolini thanks for the report. Can you please paste the output of `salt-run --versions-report`

**Comment by eliasp** [comment] 2015-10-12 08:01
I can confirm this. Neither `pillar.show_pillar` nor `pillar.show_top` returns anything. The pillar are available on the Minions just as expected, it's just the broken `salt-run` functionality.
```


root@master:~# salt-call test.versions_report
local:
    Salt Version:
               Salt: 2015.8.0
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.4.0
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-55-generic
             system: Ubuntu 14.04 trusty
     
root@master:~# salt-run pillar.show_pillar
root@master:~# salt-run pillar.show_top
```

**Comment by Ch3LL** [comment] 2015-10-12 16:53
@eliasp thank you for the salt-versions report. @mpaolini are you running the same version?

**Comment by mpaolini** [comment] 2015-10-12 19:50
yep, same here

```Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-63-generic
         system: Ubuntu 14.04 trusty
 
```

**Comment by Ch3LL** [comment] 2015-10-14 21:36
@mpaolini  thanks for the additional information. 
I found this issue is related to the following github issue: [25891] (https://github.com/saltstack/salt/issues/25891)

Since the versions of salt are different I will make sure to keep both issues open but keep this link to the other issue and add the appropriate labels.

**Comment by wt** [comment] 2016-03-28 18:54
I don't think that both of these bugs should be kept open. You should close one of them as a dupe. Salt's issue list is already long enough.

**Comment by Ch3LL** [comment] 2016-09-21 22:04
agreed @wt thanks for pointing that out. This was one of the first issues when learning how to triage, but have learned we need to ensure we only track with one issue regardless of salt version Thanks :)  I will go ahead and close this issue and we can track the issue #25891 If anyone has any issues with this please ping me on this issue and I can re-open thanks

**Closed by Ch3LL** 2016-09-21 22:04 UTC
Labels: Bug, Duplicate, High Severity, P3, Pillar, Platform
