### ISSUE TITLE
Module postgres - wrong docs, doesn't work with debian 8.5

### ISSUE THREAD

**Issue by marek-obuchowicz** [saltstack/salt#37986] opened 2016-11-30 11:15 UTC
### Description of Issue/Question
Module `postgres` is reading setting `postgres.bins_dir` but documentation at the file header + docs site mentions wrong setting, `postgres.pg_bin`

Default settings (so no directory specified) used to work on Debian 8.5, but not anymore (it doesn't find initdb).

### Setup
As a result, while using salt-carbon on debian 8.5, postgres states fail by default, which was not case in earlier releases. Trying to manually fix it by providing path to binaries is also hard, because documentation is wrong.

### Steps to Reproduce Issue
Please compare:
https://github.com/saltstack/salt/blob/develop/salt/modules/postgres.py#L134
https://github.com/saltstack/salt/blob/develop/salt/modules/postgres.py#L28

### Versions Report
```
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5
```

**Comment by eliasp** [comment] 2016-11-30 13:10
See also:
http://askubuntu.com/a/402440

**Comment by gtmanfred** [comment] 2016-11-30 14:49
This appears to be a duplicate of https://github.com/saltstack/salt/issues/37935

Can you confirm and close this?  There should be a PR already in to fix this problem

**Closed** 2016-11-30 14:53 UTC
Labels: Duplicate

**Comment by marek-obuchowicz** [comment] 2016-11-30 14:58
:+1:
@gtmanfred please also make sure that documentation doesn't use `postgres.pg_bin` but `postgres.bins_dir`

**Comment by gtmanfred** [comment] 2016-11-30 15:00
That is not the change that was made here, the code was changed back to what was documented.

https://github.com/saltstack/salt/pull/37946
