### ISSUE TITLE
Feature Request: a state should not fail even if failhard: true when onfail is set

### ISSUE THREAD

**Issue by disaster123** [saltstack/salt#38548] opened 2017-01-04 09:29 UTC
Hello,

we run salt with failhard: true to be sure salt stops if something goes wrong which is not expected. But in case onfail is set for this state it seems to be expected it might fail. So salt should not stop.

Stefan

**Comment by gtmanfred** [comment] 2017-01-05 15:47
I have added the Feature request tag to this issue.

Thanks for the request,
Daniel

**Comment by whiteinge** [comment] 2017-07-03 16:03
Closing this as a duplicate of #16291. Please feel to comment there or reopen this if I've missed something.

**Closed by whiteinge** 2017-07-03 16:03 UTC
Labels: Core, Duplicate, Feature, TEAM Core
