### ISSUE TITLE
pip.installed Suddenly throwing exceptions.

### ISSUE THREAD

**Issue by ZacharyDuBois** [saltstack/salt#30145] opened 2016-01-05 04:46 UTC
Server is randomly having issues with `pip.installed` All my other servers are working in this setup and this one used to work, but not anymore. I have tried reinstalling via `apt-get` (Using official PPA for Ubuntu).

State file causing issues:
```yaml
basic_packages:
  pkg.installed:
  - refresh: True
  - pkgs:
    - build-essential
    - zip
    - libcurl4-openssl-dev
    - htop
    - mtr
    - libssl-dev
    - libperl-dev
    - vim
    - software-properties-common
    - python-software-properties
    - pkg-config
    - curl
    - ntp
    - python3-dev
    - tcl8.5-dev
    - python-pip
    - python-dev
    - git
    - screen
    - ncftp
    - openssl
    - lynx    
    - landscape-common
    - python-setproctitle
    - libicu-dev
    - dnsutils
glances:
  pip.installed:
    - require:
      - pkg: basic_packages
speedtest-cli:
  pip.installed:
    - require:
      - pkg: basic_packages
```
Output of `salt 'ami*' state.sls basicpkgs`
```
root@IonaI-401:/srv/salt/states# salt 'ami*' state.sls basicpkgs
amikawashima.zacharydubois.net:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 681, in sls
        ret = st_.state.call_high(high_)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
        self._mod_init(low)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
        self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
        raise KeyError(key)
    KeyError: 'pip.installed'
```
I've tried the following to resolve the issue:
- Reinstalling via `apt-get`.
- Restarting `salt-minion`
- Rebooting the entire system.
- Clearing salt's cache in `/var/cache`

Salt Version (`salt --version`)
`salt 2015.5.3 (Lithium)`

**Comment by rallytime** [comment] 2016-01-05 15:22
@ZacharyDuBois Thanks for filing this issue. This is actually a regression with the state compiler in version `2015.5.3` and happens when you're running states that depend on the existence of an external package. Instead of the state gracefully falling and telling you something like pip is unavailable, it stack traces. This is fixed on 2015.5.8 and is also fixed on the 2015.8.3 release as well.

**Comment by ZacharyDuBois** [comment] 2016-01-07 04:37
@rallytime, But it is odd when all my other servers have the exact same packages and all of a sudden, this one fails. I am able to still install packages using `pip` and `pip3` manually.

**Comment by rallytime** [comment] 2016-01-07 15:42
If you upgrade to a newer version of Salt, does the error still persist? We had a regression in the state compiler in `2015.5.3` that shows itself in precisely this manner.

**Comment by ZacharyDuBois** [comment] 2016-01-10 07:04
Sorry for the delay, @rallytime.
I would have to play with it because my current setup installs saltstack using the PPA for Ubuntu 14.04.

**Comment by rallytime** [comment] 2016-01-10 15:39
@ZacharyDuBois Ah, yes. I don't think the ppa has been updated from 2015.5.3 yet. If you want to install a newer package, you'll need to use a package from our [Ubuntu repo](http://repo.saltstack.com/#ubuntu).

**Comment by ZacharyDuBois** [comment] 2016-01-10 18:34
Will do later in the week :)

**Comment by dragon788** [comment] 2016-01-16 21:51
@rallytime Would be great if the PPA could get updated. We are only allowed to access the central Ubuntu repositories or ppa.launchpad.net, we can't get to anything else through our corporate proxies.

**Comment by ZacharyDuBois** [comment] 2016-01-17 22:24
@rallytime Got around to changing repos over. Works now `salt 2015.8.3 (Beryllium)` :)

**Comment by rallytime** [comment] 2016-01-21 23:25
@ZacharyDuBois Awesome! I am glad that is working for you. If it's alright with you, I'll go ahead and close this.

@dragon788 The PPA is updated and by the community, whereas the repo.saltstack.com packages are officially updated and maintained by SaltStack. Here's a link to a Google Group posting clarifying that point: https://groups.google.com/forum/#!topic/salt-users/cpRSmVVlZXI. Feel free to discuss that point there.

**Closed by rallytime** 2016-01-21 23:25 UTC
Labels: Bug, Core, Duplicate, Fixed Pending Verification, High Severity, P2

**Comment by DaveQB** [comment] 2016-04-11 08:36
I have this issue now upon upgrading to 2015.8.8 from 2014.7.5

Screenshot
http://wstaw.org/m/2016/04/11/plasma-desktopi26368.png

I grabbed the packages from:
http://repo.saltstack.com/#ubuntu

 salt --version
salt 2015.8.8.2 (Beryllium)

Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-38-virtual
         system: Ubuntu 12.04 precise

**Comment by ZacharyDuBois** [comment] 2016-04-11 13:12
@DaveQB Give `sudo pip install --upgrade pip` a shot on the systems that are giving you issues. Also, if you could, paste the error you're getting.

**Comment by DaveQB** [comment] 2016-04-12 02:04
@ZacharyDuBois Will this break my "python-pip" dep package installation?

**Comment by ZacharyDuBois** [comment] 2016-04-12 02:34
@DaveQB *No* pip only updated it's source, the package on you system is still needed for it.

**Comment by DaveQB** [comment] 2016-04-12 02:35
@ZacharyDuBois  Ok thank you.

**Comment by DaveQB** [comment] 2016-04-18 07:56
@ZacharyDuBois I am just checking into this solution.

So we have python-pip dpkg installed:
pip 1.0 from /usr/lib/python2.7/dist-packages (python 2.7)
which provides /usr/bin/pip

After the 'pip install --upgrade pip' we have:
pip 8.1.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
which provides /usr/local/bin/pip

My order for PATH for root user sees /usr/local/bin before /usr/bin so the new 8.1 version of pip is used.

So should I be concerned about this with my servers and any existing pip packages etc?

Thanks.

**Comment by ZacharyDuBois** [comment] 2016-04-20 01:34
I mean, it shouldn't. I wouldn't remove the deb package just for dependency issues. As for the path, I just use the default Ubuntu one (below):
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

**Comment by DaveQB** [comment] 2016-04-20 02:03
@ZacharyDuBois I haven't had any issues yet, but thought I'd ask in case there was something I was missing.

Yes, that's the default PATH that I use too. It means the pip installed pip is used over the package pip due to the order in the PATH.

We've started a project to upgrade to our servers 16.04, so this should all be a moot point in 12 months time.

Thanks

**Comment by ZacharyDuBois** [comment] 2016-04-20 03:37
@DaveQB I am actually planning to drop Ubuntu totally. Planning on moving to Debian Jessie or CoreOS. I'm going to hit off for notifications on this thread as the people who are subscribed are probably ripping their hair out with the notifications.
