### ISSUE TITLE
salt -S <ipaddress> test.ping  command output getting list of minions which did not not return.

### ISSUE THREAD

**Issue by roshan3133** [saltstack/salt#29733] opened 2015-12-16 09:55 UTC
salt -S 192.168.12.21 test.ping  
command output getting list of minions which did not not return.
```
test21:
    True
test22:
    Minion did not return. [No response]
test2:
    Minion did not return. [No response]
test1:
    Minion did not return. [No response]
test47:
    Minion did not return. [No response]
test44:
    Minion did not return. [No response]
```

**Comment by jfindlay** [comment] 2015-12-17 17:17
@roshan3133, thanks for the report.  What version of salt are you using?

**Comment by roshan3133** [comment] 2015-12-17 17:52
Latest 2015.8.3

**Comment by rallytime** [comment] 2016-02-12 23:11
@roshan3133 This is a duplicate of #29188. Since that issue is older and has more discussion, I am going to close this in favor of #29188. Please see the discussion there for more information and to track the progress of this bug.

**Closed by rallytime** 2016-02-12 23:11 UTC
Labels: Bug, Core, Duplicate, High Severity, P3

**Comment by roshan3133** [comment] 2016-02-13 06:51
Thanks for the update @rallytime

**Comment by roshan3133** [comment] 2016-02-13 09:58
@rallytime you are referring different issue and it was with diff version which is 2015.8.1 and i am working with 2015.8.3  which is a different version.
@jfindlay will you check on this and please open the issue again.

**Comment by rallytime** [comment] 2016-02-13 21:26
@roshan3133 This functionality is broken on all versions of the 2015.8 branch, as far as I have tested.

**Comment by roshan3133** [comment] 2016-02-26 06:13
@rallytime i have upgrade salt to salt-master 2015.8.7 (Beryllium) but still issue not resloved.

**Comment by The-Loeki** [comment] 2016-02-26 11:32
@roshan3133 that's because the commit (apparently) didn't make it into 2015.8.7
