### ISSUE TITLE
salt['pillar.get'] not picking up inline pillar data

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#47684] opened 2018-05-16 18:28 UTC
### Description of Issue/Question

salt['pillar.get'] not picking up inline pillar from cli while in cmd.script

### Setup

test1.sh
```
{% set username = salt['pillar.get']('username') %}
{% set name = salt['pillar.get']('name') %}
{% set password = salt['pillar.get']('password') %}

echo '{{ name }}'
echo '{{ username }}'
echo '{{ password }}'
echo "${username}@example.com"
```

test2.sh
```
{% set username = pillar['username'] %}
{% set name = pillar['name'] %}
{% set password = pillar['password'] %}
echo '{{ name }}'
echo '{{ username }}'
echo '{{ password }}'
echo "${username}@example.com"
```

```
salt master cmd.script salt://test/test1.sh template=jinja pillar='{"username": "testuser", "password": "testpassword", "name": "Test User"}'
master:
    ----------
    pid:
        15782
    retcode:
        0
    stderr:
    stdout:



        @example.com
```

```
[root@master test]# salt master cmd.script salt://test/test2.sh template=jinja pillar='{"username": "testuser", "password": "testpassword", "name": "Test User"}'
master:
    ----------
    pid:
        15807
    retcode:
        0
    stderr:
    stdout:
        Test User
        testuser
        testpassword
        @example.com
```

### Steps to Reproduce Issue

use salt['pillar.get'] expecting it to work for cli pillar data.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

This also happens on windows as well.

**Comment by whytewolf** [comment] 2018-05-16 18:28
zd-2535

**Comment by terminalmage** [comment] 2018-06-01 19:28
Inline pillar was only ever added for state runs. Re-categorizing this as a feature request.

**Comment by terminalmage** [comment] 2018-06-01 22:27
OK, so here's the thing. There are two kinds of Pillar data. They are described [here](https://docs.saltstack.com/en/latest/topics/pillar/#in-memory-pillar-data-vs-on-demand-pillar-data) in the docs. The `pillar.get` function returns from the in-memory pillar data, while inline pillar is only present in on-demand pillar data.

As it turns out, `cmd.script` does generate on-demand pillar data (though this is not documented). As you can see from the below docker image I've created to demonstrate this, inline pillar works just fine when referencing the `pillar` variable from the jinja context (on-demand pillar), but it does not when using `pillar.get`. This is expected behavior.

The good news though is that jinja supports Python's `dict.get()` function, so you can still get most of the same functionality by querying the `pillar` variable directly:

```
% docker run --rm -it -v $PWD:/testing terminalmage/issues:47684 cat /srv/salt/script.tmpl
#!/usr/bin/env sh

echo "foo == {{ pillar['foo'] }}"

echo "hello == {{ salt['pillar.get']('hello', 'not present') }}"
% docker run --rm -it -v $PWD:/testing terminalmage/issues:47684 salt-call cmd.script salt://script.tmpl pillar='{foo: bar, hello: world}' template=jinja
local:
    ----------
    pid:
        36
    retcode:
        0
    stderr:
    stdout:
        foo == bar
        hello == not present
```

The only caveat here is that since you are not using `pillar.get`, you don't get it's ability to traverse into nested data structures (e.g. using Pillar key `foo:bar:baz` to retrieve a the `baz` key from `{'foo': {'bar': {'baz': 1}}}`). So you'd need to use a more Python-like sequence of `.get()` calls to achieve the same effect on deeply-nested data. But if you're passing inline pillar, usually the pillar data passed on the CLI is not that deeply nested, so this probably won't present much of an inconvenience for you.

**Comment by rallytime** [comment] 2018-06-08 19:22
After discussing this with @terminalmage offline, I think the documentation change is sufficient for this request and that adding code for this is not necessary. Marking as 'Fixed'.

**Closed** 2018-06-26 16:39 UTC
Labels: Core, Execution Module, Feature, Fixed Pending Verification, Pillar, TEAM Core, ZD, team-core
