### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'lower' when running salt-run manage.versions

### ISSUE THREAD

**Issue by mikeadamz** [saltstack/salt#42822] opened 2017-08-09 14:43 UTC
### Description of Issue/Question
Exception when running salt-run manage.versions

```
[root@salty ~]# salt-run manage.versions
Exception occurred in runner manage.versions: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 392, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/manage.py", line 666, in versions
    minion_version = salt.version.SaltStackVersion.parse(minions[minion])
  File "/usr/lib/python2.7/site-packages/salt/version.py", line 261, in parse
    if version_string.lower() in cls.LNAMES:
AttributeError: 'bool' object has no attribute 'lower'
[root@salty ~]# 
```
### Setup
Standard master, couple of states, nothing crazy. One minion down.

### Steps to Reproduce Issue
1. Install salt 2017.7.0
2. Run salt-run manage.versions

### Versions Report
Master 
-------
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
 
```
Minions
--------------
```
[root@salty ~]# salt \* grains.item saltversion
salty.domain.org:
    ----------
    saltversion:
        2017.7.0
www.domain.com:
    ----------
    saltversion:
        2016.11.5
whiteout.domain.guru:
    ----------
    saltversion:
        2017.7.0
vengeance.domain.net:
    ----------
    saltversion:
        2017.7.0
plex.domain.net:
    ----------
    saltversion:
        2017.7.0
testbed.domain.org:
    Minion did not return. [Not connected]
```

**Comment by gtmanfred** [comment] 2017-08-09 15:41
This is a duplicate of #42660

This is fixed in 2017.7.1.

Thanks,
Daniel

**Closed by gtmanfred** 2017-08-09 15:41 UTC

**Comment by mikeadamz** [comment] 2017-08-09 17:12
doh, yeah, sorry, I just looked for open issues.

**Comment by gtmanfred** [comment] 2017-08-09 17:14
no worries :)
