### ISSUE TITLE
selinux.mode doesn't return any output and doesn't persist

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#38200] opened 2016-12-12 13:30 UTC
This might have been reported in 2 issues, but I'm not sure about the second one.

Let's say I have a system with SElinux running as enforcing.

If I push this I don't get any output:

```
selinux_mode:
  selinux.mode:
    - name: permissive
```

Getenforce shows that the system is now permissive though.

It should return that the system has been changed from enforcing to permissive.

Also selinux.mode doesn't persist after a reboot. Shouldn't there be an option to make the mode persistent? For now I manage /etc/selinux/config with file.managed.

Thanks

**Comment by gtmanfred** [comment] 2016-12-13 15:53
Can you provide the `salt --versions-report` output?

I was just playing with this the other day on 2016.11, and it is persistent for me.

**Comment by sebw** [comment] 2016-12-13 17:50
Hi,

Thanks for your answer.

Master:

swa ~ # salt --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: LinuxMint 17 qiana
        machine: x86_64
        release: 3.13.0-24-generic
         system: Linux
        version: LinuxMint 17 qiana


Minion:

# salt-call --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by gtmanfred** [comment] 2016-12-13 18:24
I have changed it so that it does now report if the setting has been changed.

https://github.com/saltstack/salt/pull/38236

But I am getting it to set the correct option in /etc/sysconfig/selinux correctly.

**Comment by sebw** [comment] 2016-12-13 18:30
Awesome, thanks!

**Comment by gtmanfred** [comment] 2016-12-13 18:31
Can we close this once that PR is merged?

**Comment by sebw** [comment] 2016-12-13 21:10
Just checked out your branch.

I just realized that I was not getting any output because I have `state_verbose: False` in my master configuration.

With `state_verbose: True` the comment states that the mode has been changed, but no change is reported under `Changes`.

After changing the mode, I get this under /etc/selinux/config:

```
[root@salt-minion states]# cat /etc/sysconfig/selinux

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=Permissive
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected.
#     mls - Multi Level Security protection.
SELINUX=Permissive
```

`SELINUXTYPE=` has been removed.

**Comment by gtmanfred** [comment] 2016-12-13 22:14
That should all be fixed with the latest patch on my branch.

If you are running salt 2016.11.0, you could apply the patch with 

`curl -sL https://github.com/gtmanfred/salt/commit/96eabd49394be97d4bb6fc5787e9aa6615e17a46.diff | patch -Np1 -d /usr/lib/python2.7/site-packages/`

on the minion.

**Comment by sebw** [comment] 2016-12-14 17:30
I confirm this patch fixes both the changes output and persistence.

We can close this once it is merged.

Thanks!

**Comment by dmaphy** [comment] 2017-02-08 10:20
Greetings,

the issue that the SELINUXTYPE variable is removed from ```/etc/selinux/config``` seems still to be present in the 2016.11.1 release. Is there any plan when this fix gets released officially?

Regards,
Dominic

**Comment by gtmanfred** [comment] 2017-02-08 13:47
Can you upgrade to the new 2016.11.2 release and see if the issue is fixed
there?

That should be the first release with the pull requests that I made in it.

**Closed** 2017-02-08 14:38 UTC
Labels: Info Needed

**Comment by dmaphy** [comment] 2017-02-08 16:48
Yep, looks good in 2016.11.2, Thanks! :-)
