### ISSUE TITLE
Custom execution modules are not available in pillars

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#19899] opened 2015-01-21 12:12 UTC
Hello,

a common pattern in the way I use salt is that I write Python code for parsing the minion id into meaningful parts. In order to overcome jinja's limitations and to be able to maintain that parsing code in a single place I would like to write a custom execution module that handles this.

This works quite well until I try to use this execution module in a pillar where it is not available. Assume, for example, that I have the following execution module:

```
#!/usr/bin/python                                                                
# -*- coding: utf-8 -*-                                                          
                                                                                 
import re                                                                        
                                                                                 
# this will be monkey patched later                                              
grains = None                                                                    
                                                                                 
# minions adhere to the following naming scheme:                                 
#                                                                                
#   foo-[(db|web|work|..)]NN            
#          -------------- --            
#            |             |             
#            |              `--- NUMBER   
#             `----------------- TYPE     

                                                                               
host_pat = re.compile(('foo-'                                                                                                
                       '(?P<type>\D+)'
                       '(?P<number>\d+)'),
                       re.VERBOSE)                                                
                                                                                 
def parse_hostname(hostname):                                                    
    """Parses given hostname and returns a dictionary with the following keys:   
                                       
        type:     (None|db|web|work|...)                                         
        number:   N                                                              
    """                                                                          
    if host_pat.match(hostname):                                                 
        return host_pat.match(hostname).groupdict()                              
                                                                                 
    return {}
```                                                                    
  
I would then very much like to use `parse_hostname` in a pillar, but salt always runs into a `KeyError` when it references the `__salt__` dunder dict even though the execution module *is* listed in `salt.modules.sysmod.list_functions`.

This happens in pillars rendered in both `#!py` and `#!jinja|yaml` (and presumably others).

That is the following pillar (`$PILLAR_ROOTS/parsed_hostname.sls`):

```
parsed_hostname:                                                                          
    foo: {{ salt['foo.parse_hostname']('foo-master1') }} 
```

results in:

```
2015-01-21 12:56:35,051 [salt.pillar                                ][CRITICAL] Rendering SLS 'parsed_hostname' failed, render error:
Jinja variable 'dict object' has no attribute 'foo.parse_hostname'
```

I am not yet sure what causes this, but it is obvious that the `__salt__` dunder dict that is being passed to renderers has not been monkey patched with the custom execution functions.

Version information:
```
# salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```

**Comment by wuxxin** [comment] 2015-01-21 12:48
#19816 is probably the same issue, but no answer so far

**Comment by babilen** [comment] 2015-01-21 12:54
@wuxxin Ah, yes! So somebody reported it in between the last time I checked. That might/is probably the same issue, yeah.

**Comment by rallytime** [comment] 2015-01-22 07:27
Thanks for the report(s) guys! I agree that this looks like the same issue. Apologies for not responding to the other one yet. We're running a bit behind on tackling this, but we will certainly look into it shortly. I am going to close this one as a duplicate of #19816. Cheers!

**Closed by rallytime** 2015-01-22 07:27 UTC
Labels: Duplicate
