### ISSUE TITLE
ToC/ Documentation chapters are mixed up

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#20489] opened 2015-02-07 17:34 UTC
http://docs.saltstack.com/en/latest/contents.html

- [x] Several chapters have the number 1 (ordering is broken?)
- [ ] The reference chapter contains references and descriptions/ articles to various features like renderers, returners, etc.. Those articles should be moved elsewhere (e.g. tutorials or dedicated chapters)

I'd like to have your feedback before starting and taking time on this issue.

**Comment by jfindlay** [comment] 2015-02-08 00:02
@bechtoldt, @whiteinge is usually the saltstack engineer most associated with the creation and maintenance of documentation.  You should discuss any such refactors with him.  Help is always welcome, thank you.

**Comment by whiteinge** [comment] 2015-02-09 20:50
I'd be in favor of pulling the section numbering out altogether. It was intended to make navigation easier but our docs shuffle around a bit too much so any given number never applies to the same doc for long. I think it's confusing and we should stick with un-numbered sections.

The reference and topics content distribution is a result of three years of documentation-creep and has been a long-standing todo. The `/ref` directory was originally intended for reference documentation, and the `/topics` directory was intended for narrative documentation. It would be great to have those two properly organized.

@bechtoldt let me know how I can help.

**Comment by rallytime** [comment] 2015-03-30 16:00
ping @jacobhammons

**Comment by bechtoldt** [comment] 2015-07-11 17:33
#25348 will improve this a bit

**Comment by rallytime** [comment] 2015-12-15 22:54
Since the docs were re-vamped a couple of months ago, it appears we're no longer displaying numbers of "chapters" in our docs any more, just major sections of interest. I am going to go ahead and close this. Let us know if this pops up again! Thanks!

**Closed by rallytime** 2015-12-15 22:54 UTC
Labels: Bug, Documentation, Medium Severity, P2
