### ISSUE TITLE
Filesystem creation is failing on newly created LV

### ISSUE THREAD

**Issue by marek-knappe** [saltstack/salt#43307] opened 2017-09-01 08:27 UTC
### Description of Issue/Question
The salt is failing when formatting empty lv/vg
Look at the logs below will tell you more than description :)

### Setup
```
datavg:
  lvm.vg_present:
    - devices: /dev/sdc

datalv:
  lvm.lv_present:
    - vgname: datavg
    - size: 15G

/dev/datavg/datalv:
  blockdev.formatted:
    - fs_type: ext4
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
[INFO    ] {'created': True}
[INFO    ] Completed state [/dev/sdc] at time 23:07:35.942381 duration_in_ms=536.763
[INFO    ] Running state [datavg] at time 23:07:35.942588
[INFO    ] Executing state lvm.vg_present for datavg
[INFO    ] Executing command ['vgdisplay', '-c', 'datavg'] in directory '/root'
[ERROR   ] Command '['vgdisplay', '-c', 'datavg']' failed with return code: 5
[ERROR   ] stderr:   Volume group "datavg" not found
  Cannot process volume group datavg
[ERROR   ] retcode: 5
[INFO    ] Executing command ['vgcreate', 'datavg', '/dev/sdc'] in directory '/root'
[DEBUG   ] output:   Volume group "datavg" successfully created
[INFO    ] Executing command ['vgdisplay', '-c', 'datavg'] in directory '/root'
[DEBUG   ] stdout:   datavg:r/w:772:-1:0:0:0:-1:0:1:1:20967424:4096:5119:0:5119:J3kfOD-BaXk-icFH-x0KA-Vz3h-2fiI-vUJ69k
[INFO    ] Executing command ['vgdisplay', '-c', 'datavg'] in directory '/root'
[DEBUG   ] stdout:   datavg:r/w:772:-1:0:0:0:-1:0:1:1:20967424:4096:5119:0:5119:J3kfOD-BaXk-icFH-x0KA-Vz3h-2fiI-vUJ69k
[INFO    ] {'created': {'Output from vgcreate': 'Volume group "datavg" successfully created', 'datavg': {'Total Physical Extents': '5119', 'Volume Group Name': 'datavg', 'Actual Physical Volumes': '1', 'M
aximum Physical Volumes': '0', 'Physical Extent Size (kB)': '4096', 'Volume Group Access': 'r/w', 'Free Physical Extents': '5119', 'UUID': 'J3kfOD-BaXk-icFH-x0KA-Vz3h-2fiI-vUJ69k', 'Internal Volume Group
Number': '-1', 'Open Logical Volumes': '0', 'Maximum Logical Volume Size': '-1', 'Current Logical Volumes': '0', 'Volume Group Size (kB)': '20967424', 'Current Physical Volumes': '1', 'Volume Group Status
': '772', 'Maximum Logical Volumes': '0', 'Allocated Physical Extents': '0'}}}
[INFO    ] Completed state [datavg] at time 23:07:35.991719 duration_in_ms=49.129
[INFO    ] Running state [datalv] at time 23:07:35.991959
[INFO    ] Executing state lvm.lv_present for datalv
[INFO    ] Executing command ['lvdisplay', '-c', '/dev/datavg/datalv'] in directory '/root'
[ERROR   ] Command '['lvdisplay', '-c', '/dev/datavg/datalv']' failed with return code: 5
[ERROR   ] stderr:   Failed to find logical volume "datavg/datalv"
[ERROR   ] retcode: 5
[INFO    ] Executing command ['/sbin/lvcreate', '-n', 'datalv', 'datavg', '-L', '15G'] in directory '/root'
[DEBUG   ] output:   Logical volume "datalv" created.
[INFO    ] Executing command ['lvdisplay', '-c', '/dev/datavg/datalv'] in directory '/root'
[DEBUG   ] stdout:   /dev/datavg/datalv:datavg:3:1:-1:1:31457280:3840:-1:0:-1:252:0
[INFO    ] Executing command ['lvdisplay', '-c', '/dev/datavg/datalv'] in directory '/root'
[DEBUG   ] stdout:   /dev/datavg/datalv:datavg:3:1:-1:0:31457280:3840:-1:0:-1:252:0
[INFO    ] {'created': {'/dev/datavg/datalv': {'Logical Volume Access': '3', 'Allocation Policy': '0', 'Logical Volume Name': '/dev/datavg/datalv', 'Read Ahead Sectors': '-1', 'Allocated Logical Extents': '-1', 'Volume Group Name': 'datavg', 'Logical Volume Size': '31457280', 'Logical Volume Status': '1', 'Current Logical Extents Associated': '3840', 'Open Logical Volumes': '1', 'Internal Logical Volume Number': '-1', 'Major Device Number': '252', 'Minor Device Number': '0'}, 'Output from lvcreate': 'Logical volume "datalv" created.'}}
[INFO    ] Completed state [datalv] at time 23:07:36.081224 duration_in_ms=89.265
[DEBUG   ] LazyLoaded blockdev.formatted
[INFO    ] Running state [/dev/datavg/datalv] at time 23:07:36.081925
[INFO    ] Executing state blockdev.formatted for /dev/datavg/datalv
[INFO    ] Executing command 'lsblk -o fstype /dev/datavg/datalv' in directory '/root'
[DEBUG   ] output: FSTYPE
[DEBUG   ] Could not LazyLoad disk.format_: 'disk.format_' is not available.
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1765, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1705, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/blockdev.py", line 162, in formatted
    __salt__['disk.format_'](name, fs_type, force=force, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1088, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'disk.format_'

[INFO    ] Completed state [/dev/datavg/datalv] at time 23:07:36.096053 duration_in_ms=14.128
[DEBUG   ] LazyLoaded mount.mounted
[INFO    ] Running state [/data] at time 23:07:36.096800
```

commands from the system:
```
root@jira-server-ubuntu-1604-vagrant:~# vgs
  VG     #PV #LV #SN Attr   VSize  VFree
  datavg   1   1   0 wz--n- 20.00g 5.00g
root@jira-server-ubuntu-1604-vagrant:~# lsblk -o fstype /dev/datavg/datalv
FSTYPE

root@jira-server-ubuntu-1604-vagrant:~# lsblk
NAME            MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda               8:0    0  10G  0 disk
└─sda1            8:1    0  10G  0 part /
sdb               8:16   0  10M  0 disk
sdc               8:32   0  20G  0 disk
└─datavg-datalv 252:0    0  15G  0 lvm
root@jira-server-ubuntu-1604-vagrant:~# lsblk -o fstype
FSTYPE

ext4
iso9660
LVM2_member

root@jira-server-ubuntu-1604-vagrant:~# lsblk -o fstype /dev/datavg/datalv
FSTYPE
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
ubuntu@jira-server-ubuntu-1604-vagrant:~$ salt --versions-report
Salt Version:
           Salt: 2016.11.0-n/a-26ff895

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-91-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by Ch3LL** [comment] 2017-09-01 15:55
@marek-knappe looks like its not loading `disk.format`. Do you have the commands `mkfs` and `sync` available?

**Comment by marek-knappe** [comment] 2017-09-03 21:54
{code}
root@jira-server-ubuntu-1604-vagrant:/home/ubuntu# mkfs
mkfs          mkfs.bfs      mkfs.btrfs    mkfs.cramfs   mkfs.ext2     mkfs.ext3     mkfs.ext4     mkfs.ext4dev  mkfs.fat      mkfs.minix    mkfs.msdos    mkfs.ntfs     mkfs.vfat     mkfs.xfs
{code}

It looks like it's getting nothing from command lsblk and trying to load module: disk.format_<nothing>

btw. that was working perfectly in v2016.11.6

**Comment by marek-knappe** [comment] 2017-09-03 22:03
```
root@jira-server-ubuntu-1604-vagrant:~# lsblk -o fstype /dev/datavg/datalv
FSTYPE

root@jira-server-ubuntu-1604-vagrant:~# echo $?
0
```
Maybe this is an pointer to an issue?

**Comment by marek-knappe** [comment] 2017-09-03 23:05
Just as the info, output from debug from v2016.11.6:
```
   [INFO    ] Completed state [datalv] at time 15:46:01.664786 duration_in_ms=172.604
       [DEBUG   ] LazyLoaded blockdev.formatted
       [INFO    ] Running state [/dev/datavg/datalv] at time 15:46:01.666277
       [INFO    ] Executing state blockdev.formatted for /dev/datavg/datalv
       [INFO    ] Executing command 'lsblk -o fstype /dev/datavg/datalv' in directory '/home/ubuntu'
       [DEBUG   ] output: FSTYPE
       [INFO    ] Executing command ['mkfs', '-t', 'ext4', '/dev/datavg/datalv'] in directory '/home/ubuntu'
       [DEBUG   ] output: mke2fs 1.42.13 (17-May-2015)
       Creating filesystem with 3932160 4k blocks and 983040 inodes
       Filesystem UUID: 8b0ee9b8-5e63-48e7-acb2-a0f1fb0cae9f
       Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208

       Allocating group tables: done
       Writing inode tables: done
       Creating journal (32768 blocks): done
       Writing superblocks and filesystem accounting information: done
```

**Comment by marek-knappe** [comment] 2017-09-06 02:19
@Ch3LL Is that enough info for unblock ticket?

**Comment by Ch3LL** [comment] 2017-09-28 15:18
Hmm weird. Yeah for some reason its not loading that disk.format_ module. `[DEBUG   ] Could not LazyLoad disk.format_: 'disk.format_' is not available.`. How did you install salt? Can you verify you indeed have that new `format_` method in salt/modules/disk.py?

The virtual function in that module isn't doing much either other then just verifying you aren't on windows so that shouldn't be impacting the loading of the module.

Can you also try changing `disk.format_` call to `disk.format` in the state module? I think the `func_alias`  might be conflicting there and it actually needs to be `__salt__['disk.format'](name, fs_type, force=force, **kwargs)`

**Comment by njhartwell** [comment] 2017-10-09 19:46
Also seeing this in 2017.7.2
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

Changing `disk.format_`  to `disk.format` in `/usr/lib/python2.7/site-packages/salt/states/blockdev.py +162` made it work 🐵

**Comment by msummers42** [comment] 2017-10-09 21:59
This is affecting salt-ssh-2017.7.2 as well.

**Comment by Secretions** [comment] 2017-10-09 22:09
This just popped up for us on 2016.11.8 installed from the salt repos targeting major version 2016.11.

Had to revert and pin to 2016.11.7.

**Comment by msummers42** [comment] 2017-10-10 00:57
@Ch3LL I can confirm that the s/disk.format_/disk.format/ in salt/states/blockdev.py line 162  works. Would you like a PR?

**Comment by msummers42** [comment] 2017-10-10 01:46
If this change is not what you want here, please feel free to close it. However, it appears that the usage of the disk module is consistent with the change in this PR. Weird thing: the format_ function is aliased to format. This aliasing appears to be dysfunctional, and the root cause of our problem here.

**Comment by Talkless** [comment] 2017-10-10 08:14
I got this problem when I tried to setup vanilla Debian 8 (jessie) virtual machine using new 2016.11.8. I am pretty sure it worked before with 2016.11.7.

**Comment by msummers42** [comment] 2017-10-12 14:39
@Ch3LL @rallytime Is there anything I can do to push this forward? I am concerned that the approach in my PR is more of a bandage and does not address some deeper issue with the function alias. However, I am unsure how to proceed and this does block using the 2017.7.2 release.

**Comment by d-shi** [comment] 2017-10-12 18:06
+1, we also had to revert back to 2017.7.1 as 2017.7.2 broke our installs.

**Comment by rallytime** [comment] 2017-10-13 15:33
@msummers42 Thank you for fixing this. The fix in #44029 is the correct one. The issue is that there wasn't an alias before. The alias was added in #43199, but the references weren't updated.

Since this bug also exists in 2016.11, I can back-port the fix there as well.

**Comment by Talkless** [comment] 2017-10-17 10:20
Any ideas why that unit test did not help before releasing new version?

**Comment by MikeH-Halo** [comment] 2017-10-25 07:22
+1 Same issue on RHEL 7. When will fix be available?

**Comment by rallytime** [comment] 2017-10-25 13:40
@MikeH-Halo It will be in the `2016.11.9` and `2017.7.3` release. In the mean time, you can place the patched file in the `_states` and [distribute the new state dynamically](https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html).

**Closed by rallytime** 2017-10-25 13:40 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P2, Regression

**Comment by Talkless** [comment] 2017-10-26 07:52
@rallytime what can be done to avoid salt releases with similar issues? How did that unit test that was fixed did not help?

**Comment by rallytime** [comment] 2017-10-26 13:49
@Talkless In this case, the unit test didn't catch the error due to the way the function was mocked and what the test was written for. That test wasn't really looking for changes in the function name, but was mocking out a dictionary of expected calls to test different functionality. An integration test would have been more effective for catching a regression like this one.
