### ISSUE TITLE
[salt-ssh] "cannot import name urllib3" while accessing CentOS7 or Fedora 21 from a Fedora 21 client

### ISSUE THREAD

**Issue by liquidat** [saltstack/salt#21664] opened 2015-03-14 19:07 UTC
When I try to execute

    $ salt-ssh '*' test.ping

on a Fedora 21 machine to test ping a CentOS 7 or the Fedora 21 itself (localhost), I get the following error:

    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/tmp/.liquidat_b233fb__salt/salt-call", line 2, in <module>
            from salt.scripts import salt_call
          File "/tmp/.liquidat_b233fb__salt/salt/__init__.py", line 44, in <module>
            from salt.utils import migrations
          File "/tmp/.liquidat_b233fb__salt/salt/utils/__init__.py", line 103, in <module>
            import salt.payload
          File "/tmp/.liquidat_b233fb__salt/salt/payload.py", line 14, in <module>
            import salt.crypt
          File "/tmp/.liquidat_b233fb__salt/salt/crypt.py", line 33, in <module>
            import salt.minion
          File "/tmp/.liquidat_b233fb__salt/salt/minion.py", line 60, in <module>
            import salt.client
          File "/tmp/.liquidat_b233fb__salt/salt/client/__init__.py", line 38, in <module>
            import salt.utils.event
          File "/tmp/.liquidat_b233fb__salt/salt/utils/event.py", line 73, in <module>
            import salt.state
          File "/tmp/.liquidat_b233fb__salt/salt/state.py", line 29, in <module>
            import salt.pillar
          File "/tmp/.liquidat_b233fb__salt/salt/pillar/__init__.py", line 14, in <module>
            import salt.fileclient
          File "/tmp/.liquidat_b233fb__salt/salt/fileclient.py", line 12, in <module>
            import requests
          File "/tmp/.liquidat_b233fb__salt/requests/__init__.py", line 58, in <module>
            from . import utils
          File "/tmp/.liquidat_b233fb__salt/requests/utils.py", line 26, in <module>
            from .compat import parse_http_list as _parse_list_header
          File "/tmp/.liquidat_b233fb__salt/requests/compat.py", line 7, in <module>
            from .packages import chardet
          File "/tmp/.liquidat_b233fb__salt/requests/packages/__init__.py", line 3, in <module>
            from . import urllib3
        ImportError: cannot import name urllib3

The salt version is:

     salt --versions-report
               Salt: 2014.7.2
             Python: 2.7.8 (default, Nov 10 2014, 08:19:18)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: 1.0.0

**Comment by jfindlay** [comment] 2015-03-16 16:34
@liquidat, how did you install salt?  Are there dependencies missing?  Thanks.

**Comment by liquidat** [comment] 2015-03-17 09:34
I used this repository to install the packages: https://copr.fedoraproject.org/coprs/saltstack/salt/
Regarding missing dependencies: the only package I am aware of that could cause this error would be the uribl libs for Pythong, but they are installed. Or do you have anything else on your mind?

**Comment by jfindlay** [comment] 2015-03-17 16:31
@liquidat, no, that is all the info I needed, thanks.

**Comment by ngrennan-inflection** [comment] 2015-03-25 21:53
The issue is that someone it is pulling the python3 version of urllib3 and requests, and installing them into the /tmp/.user_hash directory. If I manually replace them with the 2.7 versions of those modules then I can run python salt-call without error.

I am still trying to track down why it is pulling the python3 versions. I see that the 2.7 versions are installed. /usr/bin/python is 2.7, not 3.4. If I strace salt-ssh I see it reading the 2.7 versions of the files. But between eyeballing and sha1sums, they are definitely the 3.4 versions.

**Comment by ngrennan-inflection** [comment] 2015-03-25 21:57
It is calling git for copies. If I rename /usr/bin/git to /usr/bin/git.foo it works on Fedora 21.

**Comment by ngrennan-inflection** [comment] 2015-03-25 22:59
So the version issue is python-requests on Fedora 21 is updated to 2.5.0 from 2.0.0. If I downgrade to 2.0.0, it solves the original error. Then a second issue is hit related to ssl_match_hostname. Which I am still debugging.

**Comment by ngrennan-inflection** [comment] 2015-03-25 23:01
I was confused before, because the 2.5.0 was cached in cache/thin/thin.tgz, even after I had downgraded to 2.0.0. My python3 version was also 2.5.0, so it logged like the same code.

**Comment by ngrennan-inflection** [comment] 2015-03-26 00:20
The solution is to downgrade to the original fc21 packages for python-requests and python-urllib3. Then salt-ssh works. Though salt-ssh should adapt to the newer updates.

Original versions:
python-requests-2.3.0-3.fc21.noarch
python-urllib3-1.8.2-4.fc21.noarch

Updated versions:
python-requests-2.5.0-3.fc21.noarch
python-urllib3-1.10-2.fc21.noarch

**Comment by ngrennan-inflection** [comment] 2015-03-26 00:24
Other issues that make debugging hard is that salt-ssh caches versions in thin.tgz, and if it fails for a user the tmp directory, /tmp/.user_hash, has to manually be cleaned up, sometimes. salt-ssh should catch the exception, and clean up after itself, clean up on the next run, or randomize the directory name so that it doesn't keep using the broken copy that didn't work last time. It should also detect new versions of the python modules and update the cache.

**Comment by ngrennan-inflection** [comment] 2015-03-26 16:11
CentOS 7 seems to work as the client host talking to itself as localhost without any changes needed. This seems to be just a Fedora 21 issue.

**Comment by liquidat** [comment] 2015-03-27 12:22
@ngrennan-inflection Thanks for debugging so far - if I can help by testing a new version or anything else, just drop me a note.

**Comment by rallytime** [comment] 2015-04-15 21:08
I think that #22341 might have helped this issue with Fedora 21. Can either of you give pull request/change a try and let us know if that helped this bug at all?

**Comment by ngrennan-inflection** [comment] 2015-04-21 19:48
I confirm that followlinks=True patch fixes it on Fedora 22 with python-urllib3-1.10.2-1.fc22.noarch.

**Comment by rallytime** [comment] 2015-04-21 20:59
@ngrennan-inflection Thanks for verifying that fix! This fix was included in the upcoming 2014.7.5 release. I am fairly confident that the pull request that I referenced above has fixed this as well, as our salt-ssh tests are now working on Fedora 21 (they weren't at before that fix). As such, I am going to close this issue. 

If this pops up again for anyone after upgrading to 2014.7.5, please leave a comment and we can re-open. Thanks!

**Closed by rallytime** 2015-04-21 20:59 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P4, Salt-SSH
