### ISSUE TITLE
dockerng.create links kwargs error

### ISSUE THREAD

**Issue by adithep** [saltstack/salt#30266] opened 2016-01-11 13:00 UTC
This works:

```
module.run:
        - name: dockerng.create
        - kwargs:
            name: git
            image: host/user/git
            binds:
                - /ll/ll:/ll/ll
```

Where as this:

```

module.run:
        - name: dockerng.create
        - kwargs:
            name: git
            image: host/user/git
            links:
                - master:git

```

Throws this error:

```
ID: pushrepo
Function: module.run
Name: dockerng.create
Result: False
Comment: Module function dockerng.create threw an exception. Exception: too many values to unpack
Started: 12:55:52.593072
Duration: 3.747 ms
Changes:

```

**Comment by jfindlay** [comment] 2016-01-11 19:59
@adithep, thanks for the report.  What version of salt are you using?  Will you also post the minion debug log when you run the `dockerng.create` state?

**Comment by adithep** [comment] 2016-01-12 01:56
I am using salt develop, I do a pull every day so its fairly recent.

```

[DEBUG   ] Reading configuration from /salt/config/salt-minion/minion
[DEBUG   ] Including configuration from '/salt/config/salt-minion/minion.d/minion_extra.conf'
[DEBUG   ] Reading configuration from /salt/config/salt-minion/minion.d/minion_extra.conf
[DEBUG   ] Including configuration from '/salt/config/salt-minion/minion.d/minion_local_grain.conf'
[DEBUG   ] Reading configuration from /salt/config/salt-minion/minion.d/minion_local_grain.conf
[DEBUG   ] Reading configuration from /salt/config/salt-minion/minion
[DEBUG   ] Including configuration from '/salt/config/salt-minion/minion.d/minion_extra.conf'
[DEBUG   ] Reading configuration from /salt/config/salt-minion/minion.d/minion_extra.conf
[DEBUG   ] Including configuration from '/salt/config/salt-minion/minion.d/minion_local_grain.conf'
[DEBUG   ] Reading configuration from /salt/config/salt-minion/minion.d/minion_local_grain.conf
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] Configuration file path: /salt/config/salt-minion/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /salt/config/salt-minion/minion
[DEBUG   ] Including configuration from '/salt/config/salt-minion/minion.d/minion_extra.conf'
[DEBUG   ] Reading configuration from /salt/config/salt-minion/minion.d/minion_extra.conf
[DEBUG   ] Including configuration from '/salt/config/salt-minion/minion.d/minion_local_grain.conf'
[DEBUG   ] Reading configuration from /salt/config/salt-minion/minion.d/minion_local_grain.conf
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /salt/pillar/base/top.sls
[DEBUG   ] Jinja search path: '['/salt/pillar/base']'
[DEBUG   ] Jinja2 trim_blocks is enabled
[DEBUG   ] Jinja2 lstrip_blocks is enabled
[PROFILE ] Time (in seconds) to render '/salt/pillar/base/top.sls' using 'jinja' renderer: 0.00241279602051
[DEBUG   ] Rendered data from file: /salt/pillar/base/top.sls:
base:
    'git_home_linux_main':
        - minion_config
        - git_home_linux_main
        - alpha_git
    'git_office_linux_main':
        - minion_config
        - git_office_linux_main
        - alpha_git
    'salt_master':
        - minionspillar
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('base', OrderedDict([('git_home_linux_main', ['minion_config', 'git_home_linux_main', 'alpha_git']), ('git_office_linux_main', ['minion_config', 'git_office_linux_main', 'alpha_git']), ('salt_master', ['minionspillar'])]))])
[PROFILE ] Time (in seconds) to render '/salt/pillar/base/top.sls' using 'yaml' renderer: 0.0031259059906
[DEBUG   ] compound_match: lala ? git_home_linux_main
[DEBUG   ] compound_match lala ? "git_home_linux_main" => "False"
[DEBUG   ] compound_match: lala ? git_office_linux_main
[DEBUG   ] compound_match lala ? "git_office_linux_main" => "False"
[DEBUG   ] compound_match: lala ? salt_master
[DEBUG   ] compound_match lala ? "salt_master" => "False"
[DEBUG   ] LazyLoaded stack.ext_pillar
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded roots.envs
[WARNING ] /usr/lib/python2.7/dist-packages/cffi/model.py:526: UserWarning: 'git_checkout_notify_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())

[WARNING ] /usr/lib/python2.7/dist-packages/cffi/model.py:526: UserWarning: 'git_merge_tree_flag_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())

[DEBUG   ] pygit2 gitfs_provider enabled
[DEBUG   ] LazyLoaded git.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Updating git fileserver cache
[DEBUG   ] Set lock for gitfs remote 'git://github.com/saltstack-formulas/docker-formula'
[DEBUG   ] gitfs remote 'git://github.com/saltstack-formulas/docker-formula' is up-to-date
[DEBUG   ] Removed lock for gitfs remote 'git://github.com/saltstack-formulas/docker-formula'
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /salt/pillar/base/top.sls
[DEBUG   ] Jinja search path: '['/salt/pillar/base']'
[DEBUG   ] Jinja2 trim_blocks is enabled
[DEBUG   ] Jinja2 lstrip_blocks is enabled
[PROFILE ] Time (in seconds) to render '/salt/pillar/base/top.sls' using 'jinja' renderer: 0.00124907493591
[DEBUG   ] Rendered data from file: /salt/pillar/base/top.sls:
base:
    'git_home_linux_main':
        - minion_config
        - git_home_linux_main
        - alpha_git
    'git_office_linux_main':
        - minion_config
        - git_office_linux_main
        - alpha_git
    'salt_master':
        - minionspillar
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('base', OrderedDict([('git_home_linux_main', ['minion_config', 'git_home_linux_main', 'alpha_git']), ('git_office_linux_main', ['minion_config', 'git_office_linux_main', 'alpha_git']), ('salt_master', ['minionspillar'])]))])
[PROFILE ] Time (in seconds) to render '/salt/pillar/base/top.sls' using 'yaml' renderer: 0.0018630027771
[DEBUG   ] compound_match: lala ? git_home_linux_main
[DEBUG   ] compound_match lala ? "git_home_linux_main" => "False"
[DEBUG   ] compound_match: lala ? git_office_linux_main
[DEBUG   ] compound_match lala ? "git_office_linux_main" => "False"
[DEBUG   ] compound_match: lala ? salt_master
[DEBUG   ] compound_match lala ? "salt_master" => "False"
[DEBUG   ] LazyLoaded stack.ext_pillar
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'alpha_docker/containers/pushrepo.sls' to resolve 'salt://alpha_docker/containers/pushrepo.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/salt/cache/files/base/alpha_docker/containers/pushrepo.sls' to resolve 'salt://alpha_docker/containers/pushrepo.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://alpha_docker/containers/pushrepo.sls'
[DEBUG   ] No dest file found 
[INFO    ] Fetching file from saltenv 'base', ** done ** 'alpha_docker/containers/pushrepo.sls'
[DEBUG   ] compile template: /salt/cache/files/base/alpha_docker/containers/pushrepo.sls
[DEBUG   ] Jinja search path: '['/salt/cache/files/base']'
[DEBUG   ] Jinja2 trim_blocks is enabled
[DEBUG   ] Jinja2 lstrip_blocks is enabled
[PROFILE ] Time (in seconds) to render '/salt/cache/files/base/alpha_docker/containers/pushrepo.sls' using 'jinja' renderer: 0.000956058502197
[DEBUG   ] Rendered data from file: /salt/cache/files/base/alpha_docker/containers/pushrepo.sls:
pushrepo:
    module.run:
        - name: dockerng.create
        - kwargs:
            name: pushrepo
            image: salt
            client_timeout: 50000
            detach: False
            interactive: True
            links:
                - saltmaster:salt
            tty: True
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('pushrepo', OrderedDict([('module.run', [OrderedDict([('name', 'dockerng.create')]), OrderedDict([('kwargs', OrderedDict([('name', 'pushrepo'), ('image', 'salt'), ('client_timeout', 50000), ('detach', False), ('interactive', True), ('links', ['saltmaster:salt']), ('tty', True)]))])])]))])
[PROFILE ] Time (in seconds) to render '/salt/cache/files/base/alpha_docker/containers/pushrepo.sls' using 'yaml' renderer: 0.00228881835938
[DEBUG   ] LazyLoaded module.run
[INFO    ] Running state [dockerng.create] at time 01:52:18.235330
[INFO    ] Executing state module.run for dockerng.create
[DEBUG   ] File doesn't exist
[DEBUG   ] "GET /version HTTP/1.1" 200 191
[DEBUG   ] "GET /v1.21/version HTTP/1.1" 200 191
[DEBUG   ] LazyLoaded dockerng.create
[DEBUG   ] "GET /v1.21/images/salt/json HTTP/1.1" 200 1723
[DEBUG   ] "GET /v1.21/version HTTP/1.1" 200 191
[ERROR   ] Module function dockerng.create threw an exception. Exception: too many values to unpack
[INFO    ] Completed state [dockerng.create] at time 01:52:18.253576 duration_in_ms=18.246
[DEBUG   ] File /salt/cache/accumulator/140255707359760 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded highstate.output

```

**Comment by jfindlay** [comment] 2016-01-12 17:19
Thanks, @adithep.  The annoying thing here is that `module.run` is [hiding the traceback](https://github.com/saltstack/salt/blob/develop/salt/states/module.py#L240-L243) associated with the exception.  You could try this patch, which should give you more information on what the cause of the error is:
```patch
diff --git a/salt/states/module.py b/salt/states/module.py
index 1fe984b..6551f2c 100644
--- a/salt/states/module.py
+++ b/salt/states/module.py
@@ -238,9 +238,10 @@ def run(name, **kwargs):
         else:
             mret = __salt__[name](*args)
     except Exception as e:
-        ret['comment'] = 'Module function {0} threw an exception. Exception: {1}'.format(name, e)
-        ret['result'] = False
-        return ret
+        raise
+        #ret['comment'] = 'Module function {0} threw an exception. Exception: {1}'.format(name, e)
+        #ret['result'] = False
+        #return ret
     else:
         if mret is not None or mret is not {}:
             ret['changes']['ret'] = mret
```

**Comment by terminalmage** [comment] 2017-11-22 06:37
I'm going to close this since we haven't gotten a response in nearly 2 years. If this is still a problem, please respond and we'll revisit it. Thanks!

**Closed by terminalmage** 2017-11-22 06:37 UTC
Labels: Info Needed
