### ISSUE TITLE
Formula dependency management

### ISSUE THREAD

**Issue by chrismoos** [saltstack/salt#12179] opened 2014-04-22 04:52 UTC
I think there should be a standard way to manage formula dependencies. It is very natural for a state to be composed of other states but when using third party formula there is no easy way to manage the dependencies, versions, etc,.

A popular tool for Chef is [Berkshelf](http://berkshelf.com/). You put a file in your cookbook root (or _state tree root_ in Salt's case) like this:

```
source "https://api.berkshelf.com"

metadata

cookbook "mysql"
cookbook "nginx", "~> 2.6"
```

There is a CLI command so you can fetch and install all of the dependencies, for example.

I propose we do the same thing for Salt's formula:

_Saltfile_ - This will contain the dependencies, sources, etc,.
_Saltfile.lock_ - This will contain all of the active/installed dependencies and their versions.

There will be a tool that will fetch and install the dependences, just like the **berkshelf** command.

I think that having this feature is really important especially as your state tree gets more advanced and you start pulling in third party formula.

Example _Saltfile_:

``` yaml
- sources:
    - https://formula.mycompany.com
    - https://formula.saltstack.org
- dependencies:
    nginx:
    redis:
        version: '>= 1.0.5'
    ntp:
        git: 'https://github.com/saltstack-formulas/ntp-formula.git'
```

**Comment by bechtoldt** [comment] 2015-04-27 22:44
I'm thinking about extending https://github.com/bechtoldt/vcs-gather with dependency resolution support for SaltStack formulas and Puppet modules. The metadata.json file from Puppet (https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#write-a-metadatajson-file) could be acceptable for it.

**Comment by westurner** [comment] 2015-04-28 02:41
@bechtoldt https://github.com/westurner/pyrpo (`pyrpo -s . -r sh`) and/or pypi:vcs and/or https://github.com/conda/conda/tree/master/conda (http://conda.pydata.org/docs/#requirements (pycosat) may be useful).

Conda packages have a ``meta.yaml`` file. https://github.com/conda/conda-recipes/blob/master/requests/meta.yaml 

Python packages have a ``pydist.json`` (PEP 426)

**Comment by DanyC97** [comment] 2015-06-29 11:52
very useful info, is any traction being put on this for next Salt release?
Asking as i'm at the point where i want to move from states (where i have parent-child/ inheritance relationship) to formula based but then seeing this topic i'm worried i'll bum into a bigger problem.

**Comment by westurner** [comment] 2015-06-29 17:38
Salt Formulas work great without automated dependency resolution (formula
dependency management).

Here's one way to do Salt Formulas in separate repos + GItFS:

*
https://github.com/saltstack-formulas/salt-formula/blob/master/salt/formulas.sls

**Comment by bechtoldt** [comment] 2015-08-11 16:12
I'm going to implement https://github.com/bechtoldt/GatherGit/issues/3 in a few weeks which will address the ideas of this issue. If you have any further comments, let me know.

**Comment by westurner** [comment] 2015-08-11 20:13
That would be cool.

For test cases, you might have a look at some of the:
* https://github.com/h4ck3rm1k3/salt-formulas

And a start at a test framework for salt formulas:
* https://github.com/westurner/apt-cacher-ng-formula/pull/2

- [ ] ENH: GitFS integration with git submodules in a source repository, from https://github.com/saltstack-formulas/salt-formula/blob/master/salt/formulas.sls would be great.

**Comment by bechtoldt** [comment] 2015-08-11 21:15
@westurner salt formula testing is a completely different topic, I'll cover that in https://github.com/bechtoldt/formula-docs/issues/4 :)

**Comment by westurner** [comment] 2015-08-11 21:29
@bechtoldt Some tests are probably apropriate? (e.g. 'compiles' w/o syntax error, [...])

* http://conda.pydata.org/docs/building/meta-yaml.html#test-section
* http://conda.pydata.org/docs/config.html#track-features

Should this/these skeletons be standard functionality of e.g. salt.formulas or copied into *every* formula? 

An example metadata file in https://github.com/westurner/cookiecutter-saltformula could be helpful.

**Comment by bechtoldt** [comment] 2015-08-11 21:31
ouh, you mean testing the metadata itself? of course, this will be important.

**Comment by westurner** [comment] 2015-08-11 21:36
where/how do I call e.g. `check_formula_metadata('./path')`,
`check_formula_'importable'('name')`?

**Comment by bechtoldt** [comment] 2015-08-11 21:37
:+1:

**Comment by bechtoldt** [comment] 2015-09-12 09:03
The Salt Package Manager might be a solution for this issue in the future. I think it's still in a very early state. I'll file some feature requests.. :)

#24896 (PR)
#25210
#25211

**Comment by rallytime** [comment] 2015-09-12 16:03
Good call @bechtoldt. Any addition thoughts about this ^^ @techhat?

**Comment by activars** [comment] 2016-05-23 09:35
Here's my thought. The reason we need dependency management is being able to
1) Easily reproduce formular used in a code base
2) Explicitly understand it's original reference location
3) Being able to compare or track down changes for formulars
4) Being able to collaborate in both formular module development and large complex formular deployment

There are many ways to implement this, the simplest way is to use git to begin with - like Golang community's [Godep](https://github.com/tools/godep). There's a great advantage of this:
- Everything is version and hosted (privately or publicly), no need to worry about storage location
- Dependency is aiming to produce a working package (combination of formulars), using Godep's approach would help us to get there first (quick win)
- Introducing "Saltfile" like specification would be a second challenge (medium and long term)

**Comment by activars** [comment] 2016-05-23 09:37
btw, spm looks great.

**Comment by themalkolm** [comment] 2016-06-28 22:12
Are there any plans to have dependencies in spm?

**Comment by aphor** [comment] 2017-04-21 13:45
This ticket has gone quiet, but it's still open so I'm unclear whether there's lack of consensus, or whether there's consensus that SPM has made the problem go away.

Can anyone comment on successes/failures using SPM to manage formula interdependencies?

**Comment by techhat** [comment] 2017-04-21 14:51
SPM does have dependency management. An example formula might look like:
```
name: apache
os: RedHat, Debian, Ubuntu, Suse, FreeBSD
os_family: RedHat, Debian, Suse, FreeBSD
version: 201704
release: 1
summary: Formula for installing Apache
description: Formula for installing Apache web server
dependencies: zlib,pcre
optional: mod_perl
recommended: mod_ssl
```
If used, the `dependencies` field contains a list of SPM packages that must be installed before this one is, and SPM will attempt to install them at the same time. `optional` and `recommended` are currently informational only; no enforcement currently exists.

SPM has had this since last year, so I'm going to go ahead and close this. Of course, comments are still welcome, but if there are issues with dependencies, I would rather they go in a fresh ticket.

**Closed by techhat** 2017-04-21 14:51 UTC
Labels: Feature

**Comment by OrangeDog** [comment] 2020-07-16 11:47
Surely the formula should simply include states to manage its own dependencies?

**Comment by westurner** [comment] 2020-07-16 14:41
Conflicting ad-hoc approaches to dependency management is suboptimal: if X and Y depend upon Z being installed and configured and manage that dependency themselves, the order of operations determines which e.g. configuration file "wins" (remains on disk after the additive combinations of transformations are applied)

**Comment by westurner** [comment] 2020-07-16 14:48
Generally, it's not a safe assumption that - to reference the aforementioned example - both X and Y have utilized *idempotent* strategies for configuration management, so running both X and Y in any order an arbitrary number of times does not result in the desired outcome. For example, if X replaces httpd.conf and Y simply tries to append a configuration section, the end result is not consistent unless: (1) the execution order is consistent; and (2) Y is only run one time.
https://en..wikipedia.org/wiki/Idempotence

More abstract dependency management could avoid  applying multiple conflicting formulas (if it were possible to express that X and Y depend upon an *abstract requirement* Z, which e.g. Z-org-formula *provides*)

**Comment by aphor** [comment] 2020-07-18 23:03
Abstract dependencies are kicking the can down the road, not problem solving.

People will do it wrong, and the problems that result from well intentioned misunderstandings will be worse than the problems of fixing broken concrete dependencies.

https://twitter.com/Spearhafoc_/status/1028239907628740608?s=20

**Comment by westurner** [comment] 2020-07-18 23:08
https://docs.saltstack.com/en/latest/topics/spm/spm_formula.html#dependencies
