### ISSUE TITLE
Custom module breakage on RHEL/CentOS 6

### ISSUE THREAD

**Issue by dmarkwat** [saltstack/salt#43937] opened 2017-10-05 18:03 UTC
### Description of Issue/Question
RHEL/CentOS 6 python27-* packages will not import in custom modules when running on minions with version 2017.7.1.  Specifically, urllib3 (python27-urllib3) and requests (python27-requests) appear to be broken.  These include upgraded machines from the previous salt minion version as well as fresh installs.  RHEL/CentOS 7 appears to be unaffected.

Upon digging into the RPMs, I noticed wide discrepancies with the versions as they appear in PyPi, particularly related to urllib3 & backports and requests & certs. (a `less` of the RPMs shows directory/file differences when compared with the Pypi equivalent).

### Steps to Reproduce Issue
For instance, given the following custom module (_fsroot/_modules/dummy.py):
```
import requests

def __virtual__():
    return True

def method():
    pass
```

After syncing to a machine: `salt 'machine1' saltutil.sync_modules`

The following command yields an error:
```
salt 'machine1' dummy.method
# machine1:
#     'dummy' __virtual__ returned False: cannot import name certs
```

Digging further, I noticed that trying to import requests from python2.7 on the minion showed the requests package wasn't loading urllib3 the way it wanted to:
```
$ python2.7 -c 'import requests'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  Â½ile "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'
```

This also led to investigating urllib3 which also had a similar issue (due to a broken symlink, urllib3/packages/ssl\_match\_hostname):
```
$ python2.7 -c 'import urllib3'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .packages.ssl_match_hostname import CertificateError
  File "/usr/lib/python2.7/site-packages/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
ImportError: cannot import name ssl_match_hostname
```

From what I can tell, the requests version packaged via RPM had a different certs.py file which resulted in a cascading import of failing modules.  The force-reinstall of requests and urllib3 using pip2.7 resulted in desirable behavior (`import requests, urllib3` succeeded).

This finally led to reinstalling via pip2.7 (python27-pip) both requests (requests==2.6.0) and urllib3 (urllib3==1.10.2) to the versions reported by the RPMs (see parens) on all salt minions matching os: CentOS/RHEL and osmajorrelease: 6.  This seems to have fixed the issue, as now my custom modules work.

It appears the RPM packaged versions of requests==2.6.0 and urllib3==1.10.2 are not the same as what's distributed in pypi under the same version \#s.  This could be a simple mismatch of package-version labeling or partly could be due to pip2.7 (pip 9.0.1) using the dist package under the covers as opposed to the way both packages were put into the RPMs which appears to be using (legacy?) eggs.  Not sure, just reporting what I'm seeing.

RPMs under SaltStack:
[requests](https://repo.saltstack.com/yum/redhat/6Server/x86_64/2017.7/python27-requests-2.6.0-4.el6.noarch.rpm)
[urllib3](https://repo.saltstack.com/yum/redhat/6Server/x86_64/2017.7/python27-urllib3-1.10.2-2.el6.noarch.rpm)

PyPi links:
[requests](https://pypi.python.org/pypi/requests/2.6.0)
[urllib3](https://pypi.python.org/pypi/urllib3/1.10.2)

### Versions Report
Master/minion salt versions are the same but OS version differs.

Master:
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.2 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

Minion (affected):
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.8 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.13.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago
```

**Comment by dmurphy18** [comment] 2017-10-05 19:37
@dmarkwat The issue is the version of python27-requests is too low and this has been corrected in the next point release, which should be available soon. See https://github.com/saltstack/salt/issues/43128

**Comment by dmarkwat** [comment] 2017-10-05 19:56
Perfect!  Any approximate ETA on when 2017.7.2 will be available?  (Or where I might find this roadmap type information?) . Want to know how long I may need to support my workaround.

**Comment by dmurphy18** [comment] 2017-10-05 23:29
@dmarkwat Sorry but cannot give out dates for releases, however the policy is to release in the top half of the week, namely Monday - Wednesday since this gives time during the week to deal with any issues which may occur, that is, no releases on Friday afternoons etc. With that said, expect the release to be very soon unless something unforeseen occurs.

**Comment by Ch3LL** [comment] 2017-10-06 20:25
Closing as duplicate of #43128

**Closed by Ch3LL** 2017-10-06 20:25 UTC
