### ISSUE TITLE
Duplicate entry in top file gives unhelpful error message

### ISSUE THREAD

**Issue by nicholascapo** [saltstack/salt#20947] opened 2015-02-23 21:40 UTC
While cleaning up our top.sls I inadvertently created two identical entries.
This causes an unhelpful error message when running state.highstate on any minion.
```yaml
## Version Report:
Salt: 2014.7.1
Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
Jinja2: 2.6
M2Crypto: 0.21.1
msgpack-python: 0.1.10
msgpack-pure: Not Installed
pycrypto: 2.6
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 13.1.0
RAET: Not Installed
ZMQ: 3.2.3
Mako: 0.7.0
```
```
## Example:
### On Master
    $ cat salt/top.sls 
    base:
      '*':
      '*':
```
```
### On Any Minion
    $ sudo salt-call state.highstate -l debug
    [...]
    [DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://top.sls'
    [INFO    ] Fetching file from saltenv 'base', ** done ** 'top.sls'
    [DEBUG   ] Jinja search path: ['/srv/salt']
    [DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/top.sls:
    base:
      '*':
      '*':
    
    Passed invalid arguments: object of type 'ConstructorError' has no len()
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 129, in call
        ret['return'] = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 344, in highstate
        serial.dump(ret, fp_)
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 149, in dump
        fn_.write(self.dumps(msg))
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 139, in dumps
        return msgpack.dumps(odict_encoder(msg))
      File "_msgpack.pyx", line 169, in msgpack._msgpack.packb (msgpack/_msgpack.c:2384)
      File "_msgpack.pyx", line 153, in msgpack._msgpack.Packer.pack (msgpack/_msgpack.c:2020)
      File "_msgpack.pyx", line 136, in msgpack._msgpack.Packer._pack (msgpack/_msgpack.c:1761)
      File "_msgpack.pyx", line 136, in msgpack._msgpack.Packer._pack (msgpack/_msgpack.c:1761)
      File "_msgpack.pyx", line 139, in msgpack._msgpack.Packer._pack (msgpack/_msgpack.c:1803)
    TypeError: object of type 'ConstructorError' has no len()
```

**Comment by ssgward** [comment] 2015-02-23 22:18
Thanks for the report.

**Comment by colinnewell** [comment] 2015-07-15 19:20
I have experienced this too, but with a different error message.

    TypeError encountered executing state.highstate: cannot concatenate 'str' and 'ConstructorError' objects. See debug log for more info.

When I dug deeper and looked at the ConstructorError it became apparent that it was due to conflicting id's.

```
(Pdb) p err.error.context
"Conflicting ID 'odoo8*'"
```

**Comment by rallytime** [comment] 2015-10-02 19:42
@nicholascapo and @colinnewell This is actually a duplicate of #16753. As such, I am going to go ahead and close this.

The good news is that I've fixed the error with #27426. The fix will be available in upcoming 2015.5.6 and 2015.8.1 releases.

**Closed by rallytime** 2015-10-02 19:42 UTC
Labels: Bug, Core, High Severity, Low-Hanging Fruit, P4, State Module

**Comment by nicholascapo** [comment] 2015-10-02 20:48
@rallytime Thanks!

**Comment by Calygos** [comment] 2016-12-19 16:31
I just ran into this. Apparently it's still a thing almost two years later?
