### ISSUE TITLE
salt-call --local failing

### ISSUE THREAD

**Issue by furlongm** [saltstack/salt#28555] opened 2015-11-04 07:42 UTC
Salt-call since 2015.8.1 now fails with the following. This was not happening previously but I'm sure exactly which version it broke with.

```
# salt-call --local --file-root ./salt --pillar-root ./pillar state.highstate 
/usr/lib64/python2.7/site-packages/pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:208:18: fatal error: git2.h: No such file or directory
 #include <git2.h>
                  ^
compilation terminated.
[ERROR   ] Failed to import fileserver gitfs, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1110, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/gitfs.py", line 62, in <module>
    import salt.utils.gitfs
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 72, in <module>
    import pygit2
  File "/usr/lib64/python2.7/site-packages/pygit2/__init__.py", line 35, in <module>
    from .blame import Blame, BlameHunk
  File "/usr/lib64/python2.7/site-packages/pygit2/blame.py", line 32, in <module>
    from .errors import check_error
  File "/usr/lib64/python2.7/site-packages/pygit2/errors.py", line 29, in <module>
    from .ffi import ffi, C
  File "/usr/lib64/python2.7/site-packages/pygit2/ffi.py", line 35, in <module>
    ffi, C = get_ffi()
  File "/usr/lib64/python2.7/site-packages/pygit2/_utils.py", line 101, in get_ffi
    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 405, in verify
    lib = self.verifier.load_library()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 100, in load_library
    self._compile_module()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 196, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
VerificationError: CompileError: command 'gcc' failed with exit status 1
```

Can't get the version info:

```
# salt --versions-report
/usr/lib64/python2.7/site-packages/pygit2/__pycache__/pygit2_cffi_2c88a0e0x5470904.c:208:18: fatal error: git2.h: No such file or directory
 #include <git2.h>
                  ^
compilation terminated.
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 454, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 34, in run
    self.parse_args()
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 147, in parse_args
    self.print_versions_report()
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 214, in print_versions_report
    print('\n'.join(version.versions_report()), file=file)
  File "/usr/lib/python2.7/site-packages/salt/version.py", line 640, in versions_report
    ver_info = versions_information(include_salt_cloud)
  File "/usr/lib/python2.7/site-packages/salt/version.py", line 628, in versions_information
    lib_info = list(dependency_information(include_salt_cloud))
  File "/usr/lib/python2.7/site-packages/salt/version.py", line 578, in dependency_information
    imp = __import__(imp)
  File "/usr/lib64/python2.7/site-packages/pygit2/__init__.py", line 35, in <module>
    from .blame import Blame, BlameHunk
  File "/usr/lib64/python2.7/site-packages/pygit2/blame.py", line 32, in <module>
    from .errors import check_error
  File "/usr/lib64/python2.7/site-packages/pygit2/errors.py", line 29, in <module>
    from .ffi import ffi, C
  File "/usr/lib64/python2.7/site-packages/pygit2/ffi.py", line 35, in <module>
    ffi, C = get_ffi()
  File "/usr/lib64/python2.7/site-packages/pygit2/_utils.py", line 101, in get_ffi
    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 405, in verify
    lib = self.verifier.load_library()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 100, in load_library
    self._compile_module()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 196, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

Looks like it's trying to pip install something?

**Comment by cachedout** [comment] 2015-11-04 15:52
Your system may need `libgit2-dev` to be installed.

**Comment by furlongm** [comment] 2015-11-27 07:06
What is it trying to compile? Does this mean I need gcc and devel packages installed anywhere I use the salt-minion? I have the same on another system that doesn't have (or need) gcc installed:

```
# salt-minion     
unable to execute 'gcc': No such file or directory
[ERROR   ] Minion failed to start: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 275, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1634, in tune_in
    self.sync_connect_master()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 725, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 732, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 495, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/client.py", line 149, in factory
    import salt.transport.zeromq
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 24, in <module>
    import salt.transport.mixins.auth
  File "/usr/lib/python2.7/site-packages/salt/transport/mixins/auth.py", line 16, in <module>
    import salt.master
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 46, in <module>
    import salt.key
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 23, in <module>
    import salt.daemons.masterapi
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 37, in <module>
    from salt.pillar import git_pillar
  File "/usr/lib/python2.7/site-packages/salt/pillar/git_pillar.py", line 178, in <module>
    import salt.utils.gitfs
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 72, in <module>
    import pygit2
  File "/usr/lib64/python2.7/site-packages/pygit2/__init__.py", line 35, in <module>
    from .blame import Blame, BlameHunk
  File "/usr/lib64/python2.7/site-packages/pygit2/blame.py", line 32, in <module>
    from .errors import check_error
  File "/usr/lib64/python2.7/site-packages/pygit2/errors.py", line 29, in <module>
    from .ffi import ffi, C
  File "/usr/lib64/python2.7/site-packages/pygit2/ffi.py", line 35, in <module>
    ffi, C = get_ffi()
  File "/usr/lib64/python2.7/site-packages/pygit2/_utils.py", line 101, in get_ffi
    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 405, in verify
    lib = self.verifier.load_library()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 100, in load_library
    self._compile_module()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 196, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
VerificationError: CompileError: command 'gcc' failed with exit status 1
[WARNING ] ** Restarting minion **
```

**Comment by cachedout** [comment] 2016-03-18 18:53
The stacktrace shows that this is clearly failing inside pygit2.  You may be having the same issue with your pygit2 installation as what's outlined here: https://github.com/saltstack/salt/issues/28953

**Comment by rallytime** [comment] 2016-04-28 21:19
This is a duplicate of #28953. I'm going to close this one in favor of that issue since it has more discussion. That way we can track this bug in one place.

**Closed by rallytime** 2016-04-28 21:19 UTC
Labels: Fixed Pending Verification, Question
