### ISSUE TITLE
Starting rabbitmq-server hangs

### ISSUE THREAD

**Issue by belt-ascendlearning** [saltstack/salt#32875] opened 2016-04-26 20:35 UTC
### Setup
```
Pkgrepo.managed(
  'repo_rabbitmq', humanname='RabbitMQ -- AMQP service repository', name='rabbitmq',
  baseurl='http://dl.bintray.com/rabbitmq/rabbitmq-server-rpm',
  key_url='http://www.rabbitmq.com/rabbitmq-signing-key-public.asc', gpgcheck=1)
Pkgrepo.managed(
  'repo_erlang', humanname='Erlang -- AMQP service repository', name='erlang',
  baseurl='http://packages.erlang-solutions.com/rpm/centos/$releasever/$basearch',
  key_url='http://packages.erlang-solutions.com/rpm/erlang_solutions.asc', gpgcheck=0)
Pkg.latest('rabbitmq-server')
RabbitmqPlugin.enabled('rabbitmq_management')
Service.running('rabbitmq-server', enable=True)
```

Yields:
[INFO    ] Executing command '/sbin/service rabbitmq-server start' in directory '/root'
... but never moves on from there.

```ps aux | grep rabbit```
... will show rabbitmq-server running

### Steps to Reproduce Issue
I suspect this may be an upstream issue with python-subprocess or scripts not exiting properly... as that was the error "last time" this happened (albeit it was with the mysql state). Please advise.

### Versions Report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: CentOS 6.7 Final

**Comment by jfindlay** [comment] 2016-04-28 20:29
@belt-ascendlearning, thanks for reporting.  Can you reproduce the hang on the commandline or with `cmd.run` either in a state or as part of a salt command?  There may be subtle differences in how a command is executed and detached with how a shell uses the associated system calls and how python uses the same system calls.  I have seen this problem occur before with other services.

**Comment by belt-ascendlearning** [comment] 2016-04-28 20:43
Cmd.run also hangs.

**Comment by jfindlay** [comment] 2016-04-28 21:25
Thanks for the additional info.  This may still be an upstream bug, but there could be something more/better that we could do with cmd.run to make it work.  When you say command-line, do you mean you ran a command line directly on the minion, or you did a `cmd.run` from the master?

**Comment by belt-ascendlearning** [comment] 2016-04-28 21:28
Command line == ssh to the minion and run the service directive.
Cmd.run and Service.running were executed via salt-call on the minion

**Comment by jfindlay** [comment] 2016-04-28 21:33
@belt-ascendlearning, would you be willing to try `salt-call --local cmd.run '/sbin/service rabbitmq-server start'` for completeness?

**Comment by belt-ascendlearning** [comment] 2016-04-29 17:01
```
[vagrant@vagrant-centos ~]$ salt-call --local cmd.run '/sbin/service rabbitmq-server start'
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[WARNING ] Although 'virt-what' was found in path, the current user cannot execute it. Grains output might not be accurate.
[INFO    ] Determining pillar cache
Cannot write to process directory. Do you have permissions to write to /var/cache/salt/minion/proc/20160429130049159526 ?
[INFO    ] Executing command '/sbin/service rabbitmq-server start' in directory '/home/vagrant'
[ERROR   ] Command '/sbin/service rabbitmq-server start' failed with return code: 1
[ERROR   ] output: Starting rabbitmq-server: /etc/init.d/rabbitmq-server: line 67: /var/log/rabbitmq/startup_log: Permission denied
rmdir: failed to remove `/var/run/rabbitmq': Permission denied
FAILED - check /var/log/rabbitmq/startup_{log, _err}
rabbitmq-server.
local:
    Starting rabbitmq-server: /etc/init.d/rabbitmq-server: line 67: /var/log/rabbitmq/startup_log: Permission denied
    rmdir: failed to remove `/var/run/rabbitmq': Permission denied
    FAILED - check /var/log/rabbitmq/startup_{log, _err}
    rabbitmq-server.
```

**Comment by belt-ascendlearning** [comment] 2016-04-29 17:51
```
vagrant@vagrant-centos ~]$ ls -l /var/log/rabbitmq/
total 4
-rw-r--r-- 1 root root 67 Apr 29 12:58 startup_err
-rw-r--r-- 1 root root  0 Apr 29 12:58 startup_log
```
```
[vagrant@vagrant-centos ~]$ ls -al /var/run/rabbitmq/
total 8
drwxr-xr-x   2 rabbitmq rabbitmq 4096 Apr 29 12:58 .
drwxr-xr-x. 14 root     root     4096 Apr 29 12:58 ..
```

**Comment by belt-ascendlearning** [comment] 2016-04-29 17:52
Is this an upstream package-permissions problem we need to workaround with File.managed()??

**Comment by jfindlay** [comment] 2016-04-29 18:41
@belt-ascendlearning, what user do you run salt with on the minion?

**Comment by belt-ascendlearning** [comment] 2016-04-29 19:05
```
[vagrant@vagrant-centos ~]$ ps aux | grep salt-minion
root      4591  0.0  0.7 632568 29892 ?        Sl   12:49   0:04 /usr/bin/python2.6 /usr/bin/salt-minion -d
```

**Comment by jfindlay** [comment] 2016-04-29 19:12
Normally salt is run as root unless you [configure](https://docs.saltstack.com/en/latest/ref/configuration/nonroot.html) [it](https://docs.saltstack.com/en/latest/topics/tutorials/rooted.html) otherwise, so the permission errors are probably unrelated if `sudo salt-call --local cmd.run '/sbin/service rabbitmq-server start'` works.

**Comment by belt-ascendlearning** [comment] 2016-04-29 19:26
This is certainly an issue (centos-6.7):
```
[vagrant@vagrant-centos ~]$ cat /var/log/rabbitmq/startup_err
/etc/init.d/rabbitmq-server: line 67: startproc: command not found
```

**Comment by jfindlay** [comment] 2016-04-29 19:35
@belt-ascendlearning, yes, that does look like an upstream bug.  Do you think that that was the cause of the hang?

**Comment by belt-ascendlearning** [comment] 2016-04-29 19:39
Non-zero probability. What the the usual "START_PROG" on CentOS boxen?

```
  DAEMON=/usr/sbin/${NAME}
  START_PROG=startproc
  RABBITMQ_PID_FILE=$PID_FILE $START_PROG $DAEMON \
            > "${RABBITMQ_LOG_BASE}/startup_log" \
            2> "${RABBITMQ_LOG_BASE}/startup_err" \
            0<&- &
```

**Comment by jfindlay** [comment] 2016-04-29 19:52
I'm not sure, but as this seems to be an upstream problem, I am going to close the issue until more salt-specific information can be found.

**Closed by jfindlay** 2016-04-29 19:52 UTC
Labels: Bug, High Severity, P3, Platform

**Comment by belt-ascendlearning** [comment] 2016-05-06 19:55
Figured out the issue... and the workaround:
Add "exclude=*.suse" to your /etc/yum.repos.d/rabbitmq.repo

Issue: yum considers 'suse' a newer version than 'noarch' ... so it installs the suse-specific RPM instead of the one meant for centos.

Also seen in https://github.com/saltstack-formulas/rabbitmq-formula/issues/33

**Comment by jfindlay** [comment] 2016-05-06 21:31
@belt-ascendlearning, nice.  I'm glad you got it figured out.
