### ISSUE TITLE
Salt-SSH JSON output for multiple servers returns multiple JSON objects

### ISSUE THREAD

**Issue by Xiol** [saltstack/salt#28099] opened 2015-10-19 16:09 UTC
Hi,

salt-ssh's JSON output returns n-number of JSON objects depending on how many servers you've matched at once, rather than returning an array or hash of the results. For example:

```/usr/bin/salt-ssh --out json --no-color -E '(SID1|SID2)' state.sls whatever```

This will match both SID1 and SID2 from the roster and start to provision both of them. Once complete, the returned data will be exactly like this on the command line:

```json
{
    "SID1": {
        "pkg_|-firewalld_|-firewalld_|-removed": {
            "...snip...": "...snip..."
        }
    }
}
{
    "SID2": {
        "pkg_|-firewalld_|-firewalld_|-removed": {
            "...snip...": "...snip..."
        }
    }
}
```

This can be rather difficult to parse. I'd expect to see this returned as either an array of results or as a single key-value hash where the top level host IDs (SID1 and SID2 in this case) are the top level keys, e.g.:

```json
{
    "SID1": {
        "pkg_|-firewalld_|-firewalld_|-removed": {
            "...snip...": "...snip..."
        }
    },
    "SID2": {
        "pkg_|-firewalld_|-firewalld_|-removed": {
            "...snip...": "...snip..."
        }
    }
}
```

Thanks

**Comment by jfindlay** [comment] 2015-10-19 18:05
@Xiol, thanks for the report.  This is a duplicate of #25154.  Please comment there if the suggested action does not fix your issues.

**Closed by jfindlay** 2015-10-19 18:05 UTC
Labels: Duplicate
