### ISSUE TITLE
Support local user install of Ruby Gems

### ISSUE THREAD

**Issue by RobotLimeLtd** [saltstack/salt#43285] opened 2017-08-31 15:34 UTC
salt.states.gem should support the --user-install option, which installs gems under ~/.gem

e.g.
```
fpm:
  gem.installed:
    - user-install: bob
```

Would be the equivalent of Bob running:

`gem install --user-install fpm`

This allows Salt to install gems for a particular user without interfering with the system Ruby installation or worrying about permissions.

Note:  for this to work for Bob, he/she would need to have the following in their ~/.bashrc.  This is a separate responsibility, but should perhaps be noted in the documentation pages for salt.states.gem and salt.modules.gem.

```
if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi
```

**Comment by gtmanfred** [comment] 2017-08-31 15:49
This would be great.  I am marking it as a Feature Request.

Would you mind submitting a PR for this?

Thanks,
Daniel

**Comment by stooj** [comment] 2018-09-07 12:16
I think this is a duplicate of #31821

**Comment by gtmanfred** [comment] 2018-09-24 13:30
looks like it!

**Closed by gtmanfred** 2018-09-24 13:30 UTC
Labels: Feature
