### ISSUE TITLE
Incorrect coloring of patch diff - make yellow

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#19958] opened 2015-01-22 16:18 UTC
From [this comment](https://github.com/saltstack/salt/issues/18312#issuecomment-70873249):

> Also, it looks like the color of the patch now is in green (see attached screenshot). It used to be yellow along with other changes. Is that a separate issue or related?

**Comment by rallytime** [comment] 2015-01-22 17:48
Thanks for filing this issue. This is happening on the 2014.7 branch, correct?

**Comment by JensRantil** [comment] 2015-01-22 17:50
That is true.

**Comment by JensRantil** [comment] 2015-01-23 09:09
Also, this wasn't a problem in the previous version. Should it be considered a regression, perhaps?

**Comment by basepi** [comment] 2015-01-30 21:20
So I was completely mystified at first trying to track this down. I can reproduce the difference, but bringing the 2014.7.0 version of the highstate outputter into the current 2014.7 branch didn't change anything.

Then I noticed that it's actually a change in the *data*.

In 2014.7.0, the diff for a file.managed test run was all contained in the `Comment` section. However, it was moved to the `Changes` part of the dictionary at some point:

v2014.7.0 version:
```
[root@li737-184] [~/salt]
± salt '*' state.highstate test=True --out=json
{
    "basepi-debian": {
        "file_|-something_|-/tmp/myfile.txt_|-managed": {
            "comment": "The following values are set to be changed:\ndiff: --- \n+++ \n@@ -1 +1,3 @@\n some data\n+\n+some more data\n\n",
            "name": "/tmp/myfile.txt",
            "start_time": "21:15:28.450987",
            "result": null,
            "duration": 5.526,
            "__run_num__": 0,
            "changes": {}
        }
    }
}
```

2014.7 version:
```
[root@li737-184] [~/salt]
± salt '*' state.highstate test=True --out=json
{
    "basepi-debian": {
        "file_|-something_|-/tmp/myfile.txt_|-managed": {
            "comment": "The file /tmp/myfile.txt is set to be changed",
            "name": "/tmp/myfile.txt",
            "start_time": "21:16:11.300742",
            "result": null,
            "duration": 8.102,
            "__run_num__": 0,
            "changes": {
                "diff": "--- \n+++ \n@@ -1 +1,3 @@\n some data\n+\n+some more data\n"
            }
        }
    }
}
```

I'm not a fan of the fact that this was changed in a minor release, not sure how that slipped through. But I do think it's actually a pretty good change overall. By putting it in `Changes` as an actual dictionary, it gets formatted better.

Also, the more I look at this, the less I think that it's a problem that the color doesn't match. We see the "changes to be made" color in the main part of the state, and then see the normal "changes" coloring in the actual changes to be made summary.

I'd appreciate your thoughts on the matter -- right now I'm leaning towards not fixing this.

**Comment by JensRantil** [comment] 2015-02-03 11:28
Thanks for looking into this, @basepi! I'm ignoring the technicalities of where teh color formatting is done because it's irrelevant to the issue itself. :)

> Also, the more I look at this, the less I think that it's a problem that the color doesn't match. We see the "changes to be made" color in the main part of the state, and then see the normal "changes" coloring in the actual changes to be made summary.

I disagree. As a daily Salt user I really appreciate being able to quickly scroll through my `salt minion state.highstate test=True` output and immediately stop at everything that changed. The coloring is really useful for me to immediately pick this up from the output. Also, every single states' `Changes:` output is non-green when it would apply changes (without the `test=True` flag). If the diff is non-yellow it will diverge from the general output that every other state adheres to. I'd prefer to keep the output streamlined and standardized.

The above said, if the issue is hard to track down I don't see this as high priority to get into a bugfix release but _do_ think the output should be corrected. I'd love to hear your reasons for not sticking to the output coloring convention used by all other states.

**Comment by basepi** [comment] 2015-02-03 23:08
I think you're probably right, we should get the output the same color for test runs. I'll mark this as a bug.

**Comment by basepi** [comment] 2015-03-16 21:51
Just as an FYI here, we're going to move that diff back into the comment instead of the `changes` part of the return dictionary. `Changes` should only be populated if changes were actually made.

**Comment by basepi** [comment] 2015-03-16 21:54
I'm going to close this in favor of #21588. This will be resolved when that one is.

**Comment by Oloremo** [comment] 2019-03-08 17:39
@basepi and\or @Ch3LL 
As far as I understand this statement is no longer true:

>  Changes should only be populated if changes were actually made.

And I'd like to add yellow coloring to Changes in test=True as well. So, do you think that this issue should be re-opened?

**Comment by Ch3LL** [comment] 2019-03-12 15:37
> Changes should only be populated if changes were actually made. 

Can you elaborate why you t think this is not true anymore?

**Comment by Oloremo** [comment] 2019-03-12 16:22
@Ch3LL it was changed in https://github.com/saltstack/salt/pull/49832

**Comment by Ch3LL** [comment] 2019-03-13 16:16
thanks for pointing that out, i'll go ahead and re-open here

**Comment by Oloremo** [comment] 2020-01-09 00:11
not stale

**Comment by Oloremo** [comment] 2020-05-25 21:00
@sagetherage Why this issue was closed? It's totally valid and present in 3000.x

**Comment by dmurphy18** [comment] 2023-08-28 16:05
@JensRantil Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.

The new issue, if created, should show examples, of usage to ensure correct implementation.

**Closed by dmurphy18** 2023-08-28 16:05 UTC
Labels: Bug, severity-low, good first issue
