### ISSUE TITLE
Incorrect os* grains for RHEL6 in 3001.1

### ISSUE THREAD

**Issue by vaughanduncan** [saltstack/salt#58485] opened 2020-09-17 15:19 UTC
### Description of Issue
After upgrading from 2019.2.4 to 3001.1, our RHEL6 minions could not longer apply states.  The error returned is:

```
minion:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found. Please see master log for details.
     Changes:
```

When checking the os* grains, RHEL6 was reporting "rhel*" instead of "RedHat" as RHEL7 and the previous minion version does:

#### RHEL6 - 3001.1
```
    os:
        rhel
    os_family:
        rhel
    osarch:
        x86_64
    oscodename:
        Santiago
    osfinger:
        rhel-6
    osfullname:
        rhel
    osmajorrelease:
        6
    osrelease:
        6.10
    osrelease_info:
        - 6
        - 10
```

#### RHEL6 - 2019.2.4
```
    os:
        RedHat
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        Santiago
    osfinger:
        Red Hat Enterprise Linux Server-6
    osfullname:
        Red Hat Enterprise Linux Server
    osmajorrelease:
        6
    osrelease:
        6.10
    osrelease_info:
        - 6
        - 10
```

#### RHEL7 - 3001.1
```
    os:
        RedHat
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        Maipo
    osfinger:
        Red Hat Enterprise Linux Server-7
    osfullname:
        Red Hat Enterprise Linux Server
    osmajorrelease:
        7
    osrelease:
        7.8
    osrelease_info:
        - 7
        - 8
```

This does not impact our RHEL7 or Solaris minions.  I'm upgrading from python 3.7.6 to 3.8.3 however I don't believe this is a factor in the issue at hand.  I also have not upgraded the master yet however the workaround below suggests this is a minion issue.

### Setup
The top.sls is setup with many entries similar to the following to target RHEL/Solaris servers.  The states are all working in 2019.2.4.
```
dev:
  'G@os_family:Solaris or ( G@os_family:RedHat and P@osmajorrelease:[6-7] )':
    - match: compound
    - init_agent.salt_env
    - minion-heartbeat
```

### Steps to Reproduce Issue
After tracing the issue, I was able to determine the problem is related to the code changes to switch from the depreciated `platform.linux_distribution()` to the `distro` package and the fact that RHEL6 does not include a `/etc/os-release` file.

`plateform.linux_distribution()` returns:
```
bash> /apps/saltstack/bin/python
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.linux_distribution()
__main__:1: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
('Red Hat Enterprise Linux Server', '6.10', 'Santiago')
>>>
```

`distro` returns similar information with `linux_distribution()` however does not with `id` which is used in `salt/grains/core.py`:
```
bash> /apps/saltstack/bin/python
Python 3.8.3 (default, Jul  2 2020, 16:21:59)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distro
>>> distro.linux_distribution()
('RedHatEnterpriseServer', '6.10', 'Santiago')
>>> distro.id()
'rhel'
>>> distro.version()
'6.10'
>>> distro.codename()
'Santiago'
>>>
```

### Workaround
I can workaround the issue by creating the following `/etc/os-release` file on RHEL6:
```
NAME="Red Hat Enterprise Linux Server"
VERSION="6.10 (Santiago)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="6.10"
PRETTY_NAME="Red Hat Enterprise Linux"
```

Now the **RHEL6 - 3001.1** os* grains as follows and the state is successfully applied:
```
    os:
        RedHat
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        Santiago
    osfinger:
        Red Hat Enterprise Linux Server-6
    osfullname:
        Red Hat Enterprise Linux Server
    osmajorrelease:
        6
    osrelease:
        6.10
    osrelease_info:
        - 6
        - 10
```

### Versions Report
```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.8.3 (default, Jul  2 2020, 16:21:59)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: rhel 6.10 Santiago
         locale: utf-8
        machine: x86_64
        release: 2.6.32-754.31.1.el6.x86_64
         system: Linux
        version: RedHatEnterpriseServer 6.10 Santiago
```

**Comment by dmurphy18** [comment] 2020-09-17 16:55
SaltStack does not support RHEL 6 on Python 3, and only supports RHEL 6 on Python 2 and has only ever supported RHEL 6 on Python 2.

At the time of the decision to not support RHEL 6 on Python 3, RHEL 6 was supposed to End Of Life (EOL) by June 30th, 2020, however it subsequently has been extended to the end of November 2020.  Similarly at the time, Amazon Linux 1 (based on RHEL 6) was EOL by 30th June 2020, but it has now been extended to the end of the year by Amazon.

At the time, it was deemed that the effort to support RHEL 6 and Amazon Linux 1 on Python 3 was too large and with their EOL so soon,  that resources would be better spent on other efforts. Their life extension was unexpected and resources had already been committed to other efforts.

This explains why there are no packages provided by SaltStack for RHEL 6 and Amazon Linux 1 for Python 3.

Closing since this is expected behavior, however please reopen if there are other considerations which need to be brought to SaltStack's attention.

**Closed by dmurphy18** 2020-09-17 16:55 UTC
Labels: Expected Behavior, Packaging, Platform, python3
