### ISSUE TITLE
firewalld prune_services is still broken

### ISSUE THREAD

**Issue by hunkeelin** [saltstack/salt#39621] opened 2017-02-23 22:59 UTC
### Description of Issue/Question

This was previously mentioned. So basically prune_services: false will only stop pruning services, it will still prune rich rules and specific ports. This broken feature render firewalld unmanageable by salt. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment] 2017-02-23 23:01
This is a duplicate of #38855 

We would gladly accept a pull request to fix the issue, otherwise it is on our list to get fixed.

Thanks,
Daniel

**Closed by gtmanfred** 2017-02-23 23:01 UTC

**Comment by hunkeelin** [comment] 2017-02-23 23:10
Why not just remove the prune_services feature? It's broken since it's introduction, and it's not needed.

**Comment by gtmanfred** [comment] 2017-02-23 23:13
We can't remove it now because it works for certain usecases.  it would be nice to have an aggregator built into firewalld, so that the prune_services and prune_ports wouldn't matter and the whole thing was actually run as one state.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.mod_aggregate

Also, a pull request that removes it and gives the reason to remove it might be accepted.

**Comment by gtmanfred** [comment] 2017-02-23 23:15
It is also worth noting the work around would be to use firewalld.service to create a service for any port that you wanted to enable, and then you can use prune_services as it is written now.

In case anyone runs across this while googling.
