### ISSUE TITLE
LocalClient is not thread safe

### ISSUE THREAD

**Issue by matdrapeau** [saltstack/salt#14449] opened 2014-07-24 04:12 UTC
I am trying to use LocalClient in a web app context but it appears that it is not suitable...
Example:
```
from threading import Thread
import salt.client
l = salt.client.LocalClient()
for x in range(0,10):
    Thread(target=l.cmd, args=['*', 'test.ping']).start()
```

This crashes python:
>>>Assertion failed: ok (mailbox.cpp:82)
Abort trap: 6

Deeper traceback:
```
...
  File "/Users/mdrapeau/projects/utils/salt/salt/transport/__init__.py", line 238, in send
    return self._uncrypted_transfer(load, tries, timeout)
  File "/Users/mdrapeau/projects/utils/salt/salt/transport/__init__.py", line 231, in _uncrypted_transfer
    return self.sreq.send(self.crypt, load, tries, timeout)
  File "/Users/mdrapeau/projects/utils/salt/salt/payload.py", line 203, in send
    self.socket.send(pkg)
  File "/Users/mdrapeau/projects/utils/salt/salt/payload.py", line 168, in socket
    self._socket = self.context.socket(zmq.REQ)
  File "/Users/mdrapeau/projects/env/master/lib/python2.7/site-packages/zmq/sugar/context.py", line 85, in socket
    s = self._socket_class(self, socket_type)
  File "socket.pyx", line 216, in zmq.backend.cython.socket.Socket.__cinit__ (zmq/backend/cython/socket.c:2204)
```

**Comment by cachedout** [comment] 2016-05-25 21:11
This is a duplicate of #2536

**Closed by cachedout** 2016-05-25 21:11 UTC
Labels: Bug, Core, High Severity, P4
