### ISSUE TITLE
ini.options_present separator add extra whitespaces (and pkgrepo is not viable to manage yum)

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#50536] opened 2018-11-16 09:53 UTC
Hi,

When using ini.options_present with a defined separator, salt add extra whitespace around the separator.

If I apply this code, all the parameters of the file are converted from `key=value` to `key = value`
Also I do this because, it is not possible with pkgrepo to only disable an existant repo, you have to set all the parameters and you can't manage a yum repo configuration file with multiple entries (one file, one entry); so when the centos-release package is updated all the entries are recreated; so the only way I've found to have something not dirty when using a local YUM mirror, is to disable all the default repository and to manage each entry of the local mirror via pkgrepo.

```
yum_disable_centos_base_repo:
  ini.options_present:
    - name: /etc/yum.repos.d/CentOS-Base.repo
    - separator: '='
    - sections:
        base:
          enabled: 0
        updates:
          enabled: 0
        extras:
          enabled: 0
        centosplus:
          enabled: 0

CentOS-Base:
  pkgrepo.managed:
    - humanname: 'CentOS-$releasever - Base'
    - name: local-base
    - baseurl: 'https://repos.local/pulp/repos/centos/7/os/$basearch/'
    - enabled: 1
    - proxy: _none_

CentOS-Updates:
  pkgrepo.managed:
    - humanname: 'CentOS-$releasever - Updates'
    - name: local-updates
    - baseurl: 'https://repos.local/pulp/repos/centos/7/updates/$basearch/'
    - enabled: 1
    - proxy: _none_

CentOS-Extras:
  pkgrepo.managed:
    - humanname: 'CentOS-$releasever - Extras'
    - name: local-extras
    - baseurl: 'https://repos.local/pulp/repos/centos/7/extras/$basearch/'
    - enabled: 1
    - proxy: _none_
```

**Comment by Ch3LL** [comment] 2018-11-16 15:36
can you please include the output of `salt --versions-report`

**Comment by Poil** [comment] 2018-11-19 07:30
Hi,

```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.4.9 (default, Aug 14 2018, 21:28:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Ch3LL** [comment] 2018-11-19 15:53
thanks! Looks like i'm able to replicate this. Do you know if this was working previously? and if so what version?

**Comment by Poil** [comment] 2018-11-19 17:13
I don't know, I've found some old issue that seems to be fixed #31210

**Comment by Ch3LL** [comment] 2018-11-20 14:52
i checked out on the commit in that PR and its still failing with your states. ping @boltronics mind taking a look here if you have a moment?

**Comment by boltronics** [comment] 2018-11-22 08:47
@Ch3LL I have looked into the whitespace issue, and I believe that is a duplicate of issue #33669. Please see my comment there concerning that.

The addition of the whitespace isn't an issue in ini-like files for any application AFAIK. It appears CentOS is no different in this respect. `yum` is written in Python and uses the Python ConfigParser library which handles the spaces perfectly (and the https://docs.python.org/2/library/configparser.html docs even use spaces in at least one of their own examples).

It is a shame that Salt's `ini_manage` module doesn't also use Python's ConfigParser library or some such to avoid the complete file rewirite, but rewriting the module would be a big change for something that doesn't make any practical difference that I am aware of. The two PRs linked above this comment should go a long way to improving the situation at least.

As for the remaining issue described in the ticket, that is a completely separate issue and unrelated to ini management. I believe that really should be its own issue. In any case, I don't use RedHat or CentOS so that would be something for someone else to look into.

**Comment by chorne-togetherwork** [comment] 2019-10-23 17:21
I'm not sure how much this helps, but I've run into a case where the extra whitespace around the separator causes issues. I am installing logrhythm on a CentOS 7 server that uses an ini file as its config file. The only change that has to be made to the config post-installation is setting the host the service reports back to.

Unfortunately, the extra space between the key and value renders the file useless and the service fails to start.

This is a trivial issue in my case because a simple `file.managed` will suffice.

**Comment by digitalkram** [comment] 2021-07-27 12:59
> I'm not sure how much this helps, but I've run into a case where the extra whitespace around the separator causes issues. I am installing logrhythm on a CentOS 7 server that uses an ini file as its config file. The only change that has to be made to the config post-installation is setting the host the service reports back to.
> 
> Unfortunately, the extra space between the key and value renders the file useless and the service fails to start.
> 
> This is a trivial issue in my case because a simple `file.managed` will suffice.

Same here with Siemens NX Application. The extra white spaces make it fail.

**Comment by twangboy** [comment] 2023-08-21 21:29
duplicate of https://github.com/saltstack/salt/issues/33669

**Closed by twangboy** 2023-08-21 21:29 UTC
Labels: Bug, severity-medium, Duplicate, Confirmed
