### ISSUE TITLE
Thorium on GitFS

### ISSUE THREAD

**Issue by viq** [saltstack/salt#45850] opened 2018-02-02 23:01 UTC
### Description of Issue/Question
Is it possible to have Thorium formulas live on GitFS? After using GitFS for states and pillars it feels wrong to be forced to have something on disk.

Possbly related to #29081

**Comment by gtmanfred** [comment] 2018-02-05 18:14
You cannot yet, as mentioned in that issue, it would be nice to see that added.

https://github.com/saltstack/salt/issues/29081#issuecomment-249902902

I am closing this as a duplicate of that other issue.

Daniel

**Closed by gtmanfred** 2018-02-05 18:14 UTC
