### ISSUE TITLE
salt 2016.3.1 too slow 

### ISSUE THREAD

**Issue by ayeja** [saltstack/salt#34653] opened 2016-07-13 23:08 UTC
I recently updated salt  2015.8.0 to 2016.3.1. The execution time of formulas has increased greatly.  For example, a formula that takes eight seconds now takes 22. I have observed that CPU performance of minions has increased its load when I execute any state. I am concerned with this behavior.  

Master info:

Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-573.22.1.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final

Minion info:

Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-642.1.1.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final

**Comment by cachedout** [comment] 2016-07-16 19:09
We really need more information to go on here. Can you point to a particular formula that's slow so that we can try to pin this down to something specific?

**Comment by ayeja** [comment] 2016-07-16 22:19
cachedout, thanks for your response. You can try any case. For example, I have this formula:

/etc/rsyslog.d/file.conf:
  file.managed:
    - source: salt://logs/file.conf
    - user: root
    - group: root
    - mode: 644
    - template: jinja

{% if grains['osfinger'] == 'CentOS Linux-7' %}

syslogrestart:
  cmd.run:
    - name: systemctl restart rsyslog
    - user: root

{% else %}

syslogrestart:
  cmd.run:
    - name: /etc/init.d/rsyslog restart
    - user: root

{% endif %}

_Where file.conf is:_

$WorkDirectory /var/lib/rsyslog # where to place spool files
$ActionQueueFileName fwdRule1 # unique name prefix for spool files
$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
$ActionQueueType LinkedList   # run asynchronously
$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
authpriv.*                                       @@domain.example:1514

**Runtimes:**

Salt 2015.8.0

real    0m7.105s
user    0m0.730s
sys     0m0.088s

Salt 2016.3.1:

real    0m18.599s
user    0m0.909s
sys     0m0.098s

OS: Centos 6.8 Final (the same thing happens in centos 7).

This time difference is the tendency in all cases. 

Thanks again.

**Comment by eradman** [comment] 2016-07-18 17:20
This morning I upgraded from 2015.8 to 2016.3 and I did not observe a difference
in performance on CentOS 7.2

**2015.8.7**

    $ time sudo salt 'db1*' state.highstate env=$USER
    db1.mydomain.com:
    
    Summary for db1.mydomain.com
    -------------
    Succeeded: 10
    Failed:     0
    -------------
    Total states run:     10
    
    real    0m3.640s
    user    0m0.544s
    sys     0m0.068s

**2016.3.1**

    $ time sudo salt 'db1*' state.highstate env=$USER
    db1.mydomain.com:
    
    Summary for db1.mydomain.com
    -------------
    Succeeded: 10
    Failed:     0
    -------------
    Total states run:     10
    
    real    0m3.368s
    user    0m0.546s
    sys     0m0.061s

So it seems that the slowdown relates to a specific set of features or a particular master-minion configuration.

**Comment by cachedout** [comment] 2016-07-18 17:21
@eradman I suspect that you are correct. That's why I wanted a specific formula to test against.

**Comment by ayeja** [comment] 2016-07-18 17:45
@eradman Could you try the formula I published?

This is my salt-master configuration:

auth_mode: 1
auto_accept: true
cachedir: /var/cache/salt/master
cli_summary: false
client_acl: {}
client_acl_blacklist: {}
cluster_masters: []
cluster_mode: paranoid
conf_file: /etc/salt/master
cython_enable: false
default_include: master.d/*.conf
enable_gpu_grains: false
enforce_mine_cache: false
enumerate_proxy_minions: false
ext_job_cache: ''
ext_pillar: []
extension_modules: /var/cache/salt/extmods
external_auth:
  pam:
    salttest:
    - '@runner'
    - .*
    - pkg.*
    - cmd.*
    - state.*
    - test.*
failhard: false
file_buffer_size: 1048576

#file_ignore_glob: null
#file_ignore_regex: null
#file_recv: false


file_recv_max_size: 100
file_roots:
  base:
  - /srv/salt
fileserver_backend:
- roots
fileserver_followsymlinks: true
fileserver_ignoresymlinks: false
fileserver_limit_traversal: false
gather_job_timeout: 5
gitfs_base: master
gitfs_env_blacklist: []
gitfs_env_whitelist: []
gitfs_insecure_auth: false
gitfs_mountpoint: ''
gitfs_passphrase: ''
gitfs_password: ''
gitfs_privkey: ''
gitfs_pubkey: ''
gitfs_remotes: []
gitfs_root: ''
gitfs_user: ''
halite:
  certpath: /etc/pki/tls/certs/localhost.crt
  cors: false
  host: 0.0.0.0
  keypath: /etc/pki/tls/certs/localhost.key
  level: debug
  pempath: /etc/pki/tls/certs/localhost.pem
  port: '8080'
  server: cherrypy
  tls: true
rest_cherrypy:
  port: 9191
  host: 0.0.0.0
  ssl_crt: /etc/ssl/private/cert.pem
  ssl_key: /etc/ssl/private/key.pem

hash_type: sha256
hgfs_base: default
hgfs_branch_method: branches
hgfs_env_blacklist: []
hgfs_env_whitelist: []
hgfs_mountpoint: ''
hgfs_remotes: []
hgfs_root: ''
id: saltmaster.domain_master
interface: 0.0.0.0
ioflo_console_logdir: ''
ioflo_period: 0.01
ioflo_realtime: true
ioflo_verbose: 0
ipv6: false
jinja_lstrip_blocks: false
jinja_trim_blocks: false
job_cache: true
keep_jobs: 24
key_logfile: /var/log/salt/key
keysize: 4096
log_datefmt: '%H:%M:%S'
log_datefmt_logfile: '%Y-%m-%d %H:%M:%S'
log_file: /var/log/salt/master
log_fmt_console: '[%(levelname)-8s] %(message)s'
log_fmt_logfile: '%(asctime)s,%(msecs)03.0f [%(name)-17s][%(levelname)-8s] %(message)s'
log_granular_levels: {}
log_level: null
log_level_logfile: null
loop_interval: 60
maintenance_floscript: /usr/lib64/python2.6/site-packages/salt/daemons/flo/maint.flo
master_floscript: /usr/lib64/python2.6/site-packages/salt/daemons/flo/master.flo
master_job_cache: local_cache
master_pubkey_signature: master_pubkey_signature
master_roots:
  base:
  - /srv/salt-master
master_sign_key_name: master_sign
master_sign_pubkey: false
master_tops: {}
master_use_pubkey_signature: false
max_event_size: 1048576
max_minions: 0
max_open_files: 100000
minion_data_cache: true
minionfs_blacklist: []
minionfs_env: base
minionfs_mountpoint: ''
minionfs_whitelist: []
nodegroups:
  INFLUX: L@influxdb
open_mode: false
order_masters: false
outputter_dirs: []
peer: {}
yaml_utf8: True

permissive_pki_access: false
pidfile: /var/run/salt-master.pid
pillar_opts: true
pillar_roots:
  base:
  - /srv/pillar
pillar_source_merging_strategy: smart
pillar_version: 2
ping_on_rotate: false
pki_dir: /etc/salt/pki/master
preserve_minion_cache: false
pub_hwm: 1000
publish_port: '4505'
publish_session: 86400
queue_dirs: []
raet_main: true
raet_mutable: false
raet_port: 4506
range_server: range:80
reactor: []
reactor_refresh_interval: 60
renderer: yaml_jinja
rep_hwm: 50000
ret_port: '4506'
root_dir: /
rotate_aes_key: true
runner_dirs: []
search: ''
search_index_interval: 3600
serial: msgpack
show_jid: false
show_timeout: false
sign_pub_messages: false
sock_dir: /var/run/salt/master
sqlite_queue_dir: /var/cache/salt/master/queues
ssh_passwd: ''
ssh_port: '22'
ssh_sudo: false
ssh_timeout: 60
ssh_user: root
state_aggregate: false
state_auto_order: true
state_events: false
state_output: full
state_top: top.sls
state_verbose: true
svnfs_branches: branches
svnfs_env_blacklist: []
svnfs_env_whitelist: []
svnfs_mountpoint: ''
svnfs_remotes: []
svnfs_root: ''
svnfs_tags: tags
svnfs_trunk: trunk
syndic_event_forward_timeout: 0.5
syndic_master: ''
syndic_max_event_process_time: 0.5
syndic_wait: 5
timeout: 6
token_dir: /var/cache/salt/master/tokens
token_expire: 43200
transport: zeromq
user: root
verify_env: true
win_gitrepos:
- https://github.com/saltstack/salt-winrepo.git
win_repo: /srv/salt/win/repo
win_repo_mastercachefile: /srv/salt/win/repo/winrepo.p
worker_floscript: /usr/lib64/python2.6/site-packages/salt/daemons/flo/worker.flo
worker_threads: 5
zmq_filtering: false

**Comment by JensRantil** [comment] 2016-08-28 21:34
@ayeja The highstate output generally prints out how long each state took to execute. Does that time differ?

**Comment by bazuchan** [comment] 2016-08-30 13:35
I got same problem when updated minion from 2015.8.8 to 2016.3.1. state.highstate on 2016.3.1 takes 560 seconds and when I downgrade to 2015.8.8 it takes 40 seconds.

Execution times increased greatly for most file.managed states.
2015.8.8:
```----------
          ID: /etc/openvpn/fra.conf
    Function: file.managed
      Result: True
     Comment: File /etc/openvpn/fra.conf is in the correct state
     Started: 16:15:49.649047
    Duration: 157.687 ms
     Changes:   
```

2016.3.1:
```----------
          ID: /etc/openvpn/fra.conf
    Function: file.managed
      Result: True
     Comment: File /etc/openvpn/fra.conf is in the correct state
     Started: 16:20:17.097562
    Duration: 7205.328 ms
     Changes:   
```

state is:
```/etc/openvpn/fra.conf:
  file.managed:
    - source: salt://services/openvpn/fra.conf
    - template: jinja
    - context:
        config: {{ config }}
    - mode: 0600
    - user: root
    - group: root
    - watch_in:
      - service: openvpn
```

**Comment by JensRantil** [comment] 2016-08-30 14:32
@bazuchan If you run with `state.highstate test=true`, is it equally slow? If you run with/without Jinja template, is it equally slow?

**Comment by bazuchan** [comment] 2016-08-31 08:42
With `test=true` it runs twice faster, but still alot slower than 2015.8.8.
I checked states that runs very slow again and it seems only common is `source: salt://`. States with `content: ` runs fast.
BTW I'm running 2016.3.1 minion with 2015.8.8 master.

**Comment by JensRantil** [comment] 2016-08-31 12:45
@bazuchan Interesting. Could you check if https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.manage_file is slower between the versions, too?

**Comment by bazuchan** [comment] 2016-08-31 13:54
`salt 'fra*' file.manage_file /tmp/test_del_me '' '{}' 'salt://services/openvpn/fra.conf' "{hash_type: 'md5', 'hsum': <md5sum>}" root root 0700 base '' ` runs with the same timings.

I also tried `salt-call state.highstate` on the box itself and it runs fast, but calling it again remotely runs slow.

**Comment by bazuchan** [comment] 2016-08-31 14:27
One more experiment. Timings for file.managed depends on if pkg.installed is called before or not.

```
% cat test_only_file.sls
/tmp/test_del_me:
  file.managed:
    - source: salt://common/monit/monitrc
    - mode: 0600
    - user: root
    - group: root

% salt 'fra*' state.sls test_only_file
fra.yume.ru:
----------
          ID: /tmp/test_del_me
    Function: file.managed
      Result: True
     Comment: File /tmp/test_del_me is in the correct state
     Started: 17:07:20.003819
    Duration: 913.517 ms
     Changes:   

Summary for fra.yume.ru
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

```
% cat test_with_pkg.sls
openvpn:
  pkg.installed: []

/tmp/test_del_me:
  file.managed:
    - source: salt://common/monit/monitrc
    - mode: 0600
    - user: root
    - group: root

% salt 'fra*' state.sls test_with_pkg
fra.yume.ru:
----------
          ID: openvpn
    Function: pkg.installed
      Result: True
     Comment: Package openvpn is already installed
     Started: 17:07:42.137030
    Duration: 1639.925 ms
     Changes:   
----------
          ID: /tmp/test_del_me
    Function: file.managed
      Result: True
     Comment: File /tmp/test_del_me is in the correct state
     Started: 17:07:43.782368
    Duration: 5309.969 ms
     Changes:   

Summary for fra.yume.ru
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
```

**Comment by JensRantil** [comment] 2016-09-21 07:41
Duplicate of #33988?

**Comment by ayeja** [comment] 2016-09-21 12:47
I want to say that the problem was solved in 2016.3.2 version.

**Comment by JensRantil** [comment] 2016-09-22 09:02
@ayeja That's good news! How about you close this issue, then?

**Comment by ayeja** [comment] 2016-09-22 12:33
I did tests with the new version and it is perfect. I think you can close de issue. Thanks.

**Comment by JensRantil** [comment] 2016-09-22 14:05
@ayeja Good. Since you opened this issue, you can also close it. Feel free to do so.

**Comment by rallytime** [comment] 2016-09-22 14:08
Thanks for the discussion here everyone. I'm glad this is resolved for you @ayeja! I can close this up.

**Closed by rallytime** 2016-09-22 14:08 UTC
Labels: Info Needed
