### ISSUE TITLE
How does state pkg.installed update the installed pkg with sources?

### ISSUE THREAD

**Issue by abcfy2** [saltstack/salt#24738] opened 2015-06-17 02:34 UTC
Here is my state:

```
logstash:
  pkg.installed:
    - sources:
      - logstash: http://myserver/logstash_1.5.0-1_all.deb
```

Now I want to update logstash to 1.5.1. So I modify the sources config:

     - logstash: http://myserver/logstash_1.5.1-1_all.deb

But it's not working:

```
----------
          ID: logstash
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
     Started: 10:04:07.145625
    Duration: 33240.024 ms
     Changes:   
----------
```

How do I update my pkg with sources?

**Comment by tbaker57** [comment] 2015-06-17 10:10
I think this might be related to #7772 (which mentions a workaround)

cheers
Tim

**Comment by abcfy2** [comment] 2015-06-17 12:29
Thanks. But I think remove old pkg and install the new is not a good solution. Maybe lost data? At least this is slower than upgrade directly. Expect the official solutions.

**Comment by jtand** [comment] 2015-06-18 19:55
@abcfy2 This looks like a duplicate of  #7772 as @tbaker57 brought up. This is a high priority for us.

**Closed by jtand** 2015-06-18 19:55 UTC
Labels: Duplicate
