### ISSUE TITLE
[DOCS] firewalld state improve examples

### ISSUE THREAD

**Issue by Cobra1978** [saltstack/salt#59111] opened 2020-12-09 16:20 UTC
**Description**
The documentation of how to add a Rich Rule could be improved because the examples, INMHO, dosen't give right hint about how to add complex rule like port forwarding based on destination ip 

**Suggested Fix**
Add a complex example of a Rich Rule, something like:

```
myrule:
  firewalld.present:
    - name: public
    - prune_services: False
      rich_rules:
        - rule family="ipv4" destination address="myip" forward-port port="fromport" protocol="tcp" to-port="toport"
```

**Type of documentation**
Salt Modules/States

**Location or format of documentation**
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.firewalld.html

best Regards

**Comment by sagetherage** [comment] 2020-12-09 22:56
@Cobra1978 please feel free to submit a PR - this is great feedback! For Documentation PRs they don't usually require test written and if you link the PR to this issue I will make sure the PR gets the correct label so that is understood and thus skipped in the review.

**Comment by sagetherage** [comment] 2020-12-09 22:58
@ScriptAutomate simply mentioning you here for the @saltstack/docs-working-group :)

**Comment by Cobra1978** [comment] 2020-12-10 07:26
Honestl i'm not very experienced with pr on public project, but i will look for it :)

**Comment by ggiesen** [comment] 2020-12-12 13:58
This is more or less a dupe of #58360

**Closed** 2020-12-15 00:29 UTC
Labels: Documentation, doc-rework
