### ISSUE TITLE
git.latest ignoring user ssh key in salt 2015.8

### ISSUE THREAD

**Issue by slav0nic** [saltstack/salt#27202] opened 2015-09-17 19:55 UTC
```
$ salt-ssh --versions
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.10 (default, Jul  1 2015, 10:54:53)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: 1.1.2
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 4.1.0-2-amd64
         system: debian stretch/sid 
 
```
state:
```salt
update-git:
  git.latest:
    - name: {{ pillar.git.target }}
    - target: {{ pillar.project.path }}/project/
    - user: ubuntu
    - watch_in:
        - service: uwsgi
```
run via `salt-ssh .. state.highstate`:
```
----------
          ID: update-git
    Function: git.latest
        Name: git@git.assembla.com:waters.git
      Result: False
     Comment: Failed to check remote refs: Permission denied (publickey,keyboard-interactive).
              fatal: Could not read from remote repository.
              
              Please make sure you have the correct access rights
              and the repository exists.
     Started: 20:01:23.732077
    Duration: 200.297 ms
     Changes:   
----------
```
not work without ` - identity: /home/ubuntu/.ssh/id_rsa`, in salt 2015.5.5 and lower all was fine

**Comment by jfindlay** [comment] 2015-09-18 16:21
@slav0nic, thanks for the report.  Is that identity file configured as the ssh key for git (`git config ssh.key`) or automatically added to an agent somehow?

@terminalmage

**Comment by slav0nic** [comment] 2015-09-18 19:38
this is  user general ssh key (~/.ssh/id_rsa*  )without any specific settings

**Comment by amontalban** [comment] 2015-11-05 16:14
Hey guys,

I'm having the same issue, and I think the problem is that the git commands are ran with root instead of the desired user like original poster or in my case.

**This is my state:**

```yaml
source_code:
  git.latest:
    - require:
      - pkg: git
    - name: git@git.domain.com:developers/repo.git
    - rev: master
    - target: /usr/local/www/repo
    - user: git
    - force_checkout: True
```

**This is the command that are executed when it's trying to clone the repo:**

```bash
[root@devserver /srv]# ps auxwwf | grep -i git
root    3591   2.0  0.3  52568   6624  0  S+    4:01PM   0:00.04 ssh git@git.domain.com git-upload-pack 'developers/repo.git' 
root    3590   1.0  0.3  26772   5692  0  S+    4:01PM   0:00.13 git ls-remote git@git.domain.com:developers/repo.git
root    3593   0.0  0.1  10616   2164  2  RL+   4:01PM   0:00.01 grep -i git
```

Hope this data helps to pinpoint the issue.

Thanks!

**Comment by amontalban** [comment] 2015-11-05 16:17
#27363 looks like duplicate.

**Comment by terminalmage** [comment] 2015-11-06 16:53
Duplicate of https://github.com/saltstack/salt/issues/27703, which has been fixed.

**Closed by terminalmage** 2015-11-06 16:53 UTC
Labels: Bug, High Severity, P3, Platform, Regression, State Module
