### ISSUE TITLE
[Feature Request] Need a way to suppress runners from writing to stdout

### ISSUE THREAD

**Issue by donatello** [saltstack/salt#12884] opened 2014-05-19 08:16 UTC
I am trying to write an ext_pillar script that outputs yaml to stdout. In this script, I use the Python API RunnerClient to query the cached grains on the master. However, the output gets messed up because the runner call writes to stdout - https://github.com/saltstack/salt/blob/develop/salt/runners/cache.py#L45

Is this perhaps already possible? I checked the outputting code - https://github.com/saltstack/salt/blob/develop/salt/output/__init__.py#L50 - but there doesn't appear to be a config setting that might suppress it.

**Comment by whiteinge** [comment] 2015-02-14 18:36
Slow reply here. This is a dupe of #9444. There's a workaround in a comment on that issue. The next feature release of Salt (2015.2) also adds an [outputter](http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.jobs.html#salt.runners.jobs.lookup_jid) argument that can suppress this output as well. The long-term fix is with the new event-based runners. I expect more movement on this in 2015.5.

**Closed by whiteinge** 2015-02-14 18:36 UTC
Labels: Feature
