### ISSUE TITLE
Tornado minion http proxy support / Python 3

### ISSUE THREAD

**Issue by ymasson** [saltstack/salt#55426] opened 2019-11-25 10:05 UTC
### Description of Issue
Impossible to use archive.extracted, error on download with HTTP proxy defined
But, the problem seem to be in utils/http.py
 
### Setup
Simple example:
- start a Debian 10 container
- install salt-minion (Python 3) from Salt repositories

Test 1:
```
root@2a25eb5dded6:/# salt-call --local http.query https://www.google.com
local:
    ----------
    body:
            [........]
```
Test 2:
- Add `proxy_host` and `proxy_port` in minion configuration and restart it
```
root@2a25eb5dded6:/# salt-call --local http.query https://www.google.com
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
NameError: name 'AsyncHTTPClient' is not defined
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/http.py", line 41, in query
    return salt.utils.http.query(url=url, opts=opts, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 537, in query
    AsyncHTTPClient.configure('CurlAsyncHTTPClient')
NameError: name 'AsyncHTTPClient' is not defined
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/http.py", line 41, in query
    return salt.utils.http.query(url=url, opts=opts, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 537, in query
    AsyncHTTPClient.configure('CurlAsyncHTTPClient')
NameError: name 'AsyncHTTPClient' is not defined
```

### Versions Report
```
root@2a25eb5dded6:/# salt-call --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.2 
         locale: utf-8
        machine: x86_64
        release: 4.9.0-11-amd64
         system: Linux
        version: debian 10.2
```

**Comment by slaws** [comment] 2019-11-25 15:51
Hello,

I've made some tests to reproduce this issue. 
And something is bothering me ... the package does not install the sources from tag 2019.2.2 (or I have missed something ... )

For these tests I used the `debian:buster` image.
I installed salt with the bootstrap script with `-x python3`. I can reproduce this issue.
This is the container history
```
    1  apt-get update ; apt-get install -y wget vim
    2  wget https://bootstrap.saltstack.com -O bootstrap.sh 
    3  sh bootstrap.sh -x python3 
    4  vi /etc/salt/minion
    5  apt-get install python3-tornado4 python3-pycurl
    6  salt-call --local http.query https://www.google.com
    7  history 
```
On step 4, I just added `proxy_host` and `proxy_port`.
Same behaviour as @ymasson 
```
[...]
  File "/usr/lib/python3/dist-packages/salt/modules/http.py", line 41, in query
    return salt.utils.http.query(url=url, opts=opts, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 537, in query
    AsyncHTTPClient.configure('CurlAsyncHTTPClient')
NameError: name 'AsyncHTTPClient' is not defined
```

But when I looked into the code of utils/http.py I found out that the code does not match git tag `v2019.2.2`.
For exemple, line 68 : 
```
[...]
# Don't need a try/except block, since Salt depends on tornado
try:
    from tornado4.httputil import url_concat
    from tornado4.simple_httpclient import SimpleAsyncHTTPClient
    from tornado4.httpclient import HTTPClient, HTTPError
    try:
        from tornado4.curl_httpclient import CurlAsyncHTTPClient
        HAS_CURL_HTTPCLIENT = True
    except ImportError:
        HAS_CURL_HTTPCLIENT = False
except ImportError:
[...]
```
Which is quite different from https://github.com/saltstack/salt/blob/v2019.2.2/salt/utils/http.py#L68

So I tried installing salt-minion with the bootstrap using git method.
Here is the history ; 
```
    1  apt-get update ; apt-get install -y git-core vim wget
    2  wget  https://bootstrap.saltstack.com -O bootstrap.sh
    3  apt-get install procps
    4  sh bootstrap.sh -P -x python3 git v2019.2.2
    5  vi /etc/salt/minion
    6  apt-get install python3-pycurl python3-tornado4
    7  salt-call --local http.query https://www.google.com
    8  history 
```

And with this method the call to `http.query` works.

I've not been able to find any branch or tag refering to this code. I must have missed something .. 

Regards,

**Comment by dgengtek** [comment] 2019-11-30 00:19
same issue #54771

@slaws see the related issue.  dmurphy18 mentions that the saltstack package has been patched which is why you won't find any commits in this repository.

**Comment by ymasson** [comment] 2019-11-30 12:50
Thanks @dgengtek

**Comment by ymasson** [comment] 2019-11-30 12:57
I have patch http.py with:
```
diff --git a/http.py b/http.py
index e86ca32..a690ef1 100644
--- a/http.py
+++ b/http.py
@@ -69,7 +69,7 @@ from salt.ext.six.moves.urllib.parse import urlencode as _urlencode
 try:
     from tornado4.httputil import url_concat
     from tornado4.simple_httpclient import SimpleAsyncHTTPClient
-    from tornado4.httpclient import HTTPClient, HTTPError
+    from tornado4.httpclient import HTTPClient, HTTPError, AsyncHTTPClient
     try:
         from tornado4.curl_httpclient import CurlAsyncHTTPClient
         HAS_CURL_HTTPCLIENT = True
@@ -534,7 +534,7 @@ def query(url,
                 log.error(ret['error'])
                 return ret
 
-            AsyncHTTPClient.configure('CurlAsyncHTTPClient')
+            AsyncHTTPClient.configure(CurlAsyncHTTPClient)
             client_argspec = salt.utils.args.get_function_argspec(
                     CurlAsyncHTTPClient.initialize)
         else:
```
and setup
```
    1  apt-get update ; apt-get install -y vim gnupg2 wget git-core
    2  wget --no-check-certificate -O - https://repo.saltstack.com/py3/debian/10/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add - 
    3  echo 'deb https://repo.saltstack.com/py3/debian/10/amd64/latest buster main' >/etc/apt/sources.list.d/saltstack.list 
    4  apt-get update
    5  apt-get install --no-install-recommends salt-minion salt-common python3-pycurl
    6 salt-call --local http.query https://www.google.com
```
it is ok.

but we face this https://github.com/tornadoweb/tornado/pull/2275

**Comment by ymasson** [comment] 2019-11-30 12:58
@dmurphy18 , can you help us to fix it ?

**Comment by waynew** [comment] 2019-12-02 16:35
@ymasson FWIW, @cmcmarrow is assigned on that other issue and will likely be chasing that down. He is working on a limited schedule, though.

**Comment by ymasson** [comment] 2019-12-03 09:08
Thanks for the imput @waynew . I have found #54771 but I didn't see it as assigned, because the Assignees field is empty.

**Comment by garethgreenaway** [comment] 2019-12-18 22:26
@cmcmarrow Assigning this one to you since it appears to be similar to #54771

**Comment by ymasson** [comment] 2020-01-19 12:52
Please, review my PR.

Every new release break my Debian10 production servers.

**Comment by sagetherage** [comment] 2021-05-07 19:57
@cmcmarrow can you confirm this is still an issue in `master` please?

**Closed** 2021-06-29 22:34 UTC
Labels: Bug, info-needed, severity-medium
