### ISSUE TITLE
Doco salt.runners.manage indicates all actions do the same task

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#36521] opened 2016-09-23 02:37 UTC
### Description of Issue/Question

The doco on this page is not clear, what the differance is between the commands/actions. 
### Setup

2016 and develop doco

**Comment by rallytime** [comment] 2016-09-23 14:16
Hi @damon-atkins - Part of the discussion in #22386 includes (see [this comment](https://github.com/saltstack/salt/issues/22386#issuecomment-243972602)) includes updating all of these functions. 

I am planning on fixing that issue and the docs mentioned within the next couple of days. We can either keep this open and close it at the same time as #22386, or we can close it as a duplicate. Whichever you prefer.

**Comment by damon-atkins** [comment] 2016-09-27 18:04
What ever helps you manage it. I am happy with.

**Comment by damon-atkins** [comment] 2018-10-13 16:08
.

**Comment by sagetherage** [comment] 2020-04-25 00:11
@saltstack/docs-working-group

**Comment by twangboy** [comment] 2023-08-30 21:25
Closing this issue due to age and lack of activity. If you feel this is still an issue, please create a new issue and specify which specific function documentation is unclear. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!

**Closed by twangboy** 2023-08-30 21:25 UTC
Labels: Documentation, Bug, severity-medium, doc-rework, time-estimate-sprint
