### ISSUE TITLE
git.latest and user leads to error

### ISSUE THREAD

**Issue by gpkvt** [saltstack/salt#16927] opened 2014-10-27 13:51 UTC
When using git.latest together with user:

```
https://github.com/robbyrussell/oh-my-zsh.git:
    git.latest:
        - target: /myuser/.oh-my-zsh
        - rev: master
        - user: myuser
```
you will get an error:

```Environment could not be retrieved for User 'myuser'```

Without user:

```
https://github.com/robbyrussell/oh-my-zsh.git:
    git.latest:
        - target: /myuser/.oh-my-zsh
        - rev: master
```

everything works fine

**Comment by terminalmage** [comment] 2015-08-24 06:23
I've still never been able to reproduce this. We just don't have enough information to reproduce the issue, can you offer a more specific set of steps to reproduce this? "some changes to the root user environment" just doesn't isn't specific enough.

Also, I've rewritten the git.latest state for 2015.8.0 (see https://github.com/saltstack/salt/pull/26341), so this issue is likely resolved by that rewrite.

Please test again on 2015.8.0 and if you are still experiencing this issue, reply back with a more specific use case. Thanks!

**Comment by frogunder** [comment] 2015-12-02 21:46
@gpkvt - is this still an issue for you?

**Comment by terminalmage** [comment] 2015-12-02 21:50
@frogunder Since it has been over 3 months with no reply and e have many people using the "user" parameter with the new git.latest code from 2015.8.x, I'm going to close this.

**Closed by terminalmage** 2015-12-02 21:50 UTC
Labels: Bug, Cannot Reproduce, Fixed Pending Verification, High Severity, P4, Platform, State Module
