### ISSUE TITLE
salt/presence/present is not seen by /events of salt api

### ISSUE THREAD

**Issue by pass-by-value** [saltstack/salt#20082] opened 2015-01-26 22:13 UTC
This is happening with 2015.2

I'm able to see both the /change and /present when I run eventlisten but the /events end point does not see it.

**Comment by whiteinge** [comment] 2015-01-26 22:17
This is with the SSE stream, yes? Odd. We're not filtering events there.
How busy is the bus you're testing with? Are any other events missing?

I'll try to reproduce once I'm back in front of a keyboard today.

**Comment by pass-by-value** [comment] 2015-01-26 22:25
@whiteinge 

Yes afaik we didn't use to filter any events in the stream.

The load is small (just 1minion).

I'll have to check if there's anything else missing.

Thanks!

**Comment by whiteinge** [comment] 2015-01-27 04:25
This appears to be working for me on 2015.2 using both the HTTP stream as well as eventlisten. Will give another try on a new VM.

Found another issue though, there is a regression in the token handling on the /events URL. Will submit a pull req tonight or first thing tomorrow.

**Comment by pass-by-value** [comment] 2015-01-27 20:45
I'll verify and get back to you @whiteinge and @rallytime 

Thanks for the help!

**Comment by whiteinge** [comment] 2015-01-27 23:47
@pass-by-value trying again on a fresh VM and I'm not seeing any presence events at all. Looks like a traceback one of the Maintenance() workers? Investigating.

**Comment by whiteinge** [comment] 2015-01-28 01:20
@pass-by-value I tested against d54f3b5 (first commit before the pull req linked above). I'm still seeing events come through in both places at the same time. However the presence system just isn't working. There are no change events and the list of present minions is always empty:

SSE stream:

```
tag: salt/presence/present
data: {"tag": "salt/presence/present", "data": {"_stamp": "2015-01-28T01:14:23.599657", "present": []}}
```

eventlisten.py:

```
*************************
Tag: salt/presence/present
Data:
{'_stamp': '2015-01-28T01:14:23.599657', 'present': []}
```

Perhaps someone on the QA team can verify that. Seems there's a few things going on all at the same time here. :-P

**Comment by pass-by-value** [comment] 2015-01-28 19:42
Created a new ``2015.2`` VM and connected a minion (running on another box). 

I'm able to see the ``salt/present/present`` event and the actual minion under ``present``.

**Comment by pass-by-value** [comment] 2015-01-30 17:15
I'm seeing an issue with the presence events not being detected by ``/events`` on ``salt 2015.2.0-105-gb247b7d (Lithium)`` again.

**Comment by pass-by-value** [comment] 2015-01-30 17:16
Just to be clear, the events were being sent out by ``/events`` a couple days ago (when I tried with the ``2015.2`` branch)

**Comment by whiteinge** [comment] 2015-01-30 22:43
I'm going to close this out as a follow up to our Slack discussion. Let me know if I can help with the coroutine stuffs.

**Closed by whiteinge** 2015-01-30 22:43 UTC
Labels: Bug, Fixed Pending Verification, Medium Severity
