### ISSUE TITLE
salt-minion=2016.11.4+ds-1 master hostname resolving issue

### ISSUE THREAD

**Issue by keyd** [saltstack/salt#40938] opened 2017-04-27 20:35 UTC
### Description of Issue/Question
Error in salt master host name resolving after bootstrapping lxc container and salt-minion launching.
$ salt-minion 
[WARNING ] Unable to find IPv6 record for "salt minion hostname" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
[ERROR   ] Master address: 'salt master hostname' could not be resolved. Invalid or unresolveable address. Set 'master' value in minion config.
[ERROR   ] Master address: 'salt master hostname' could not be resolved. Invalid or unresolveable address. Set 'master' value in minion config.
The Salt Minion is shutdown.
Master address: 'salt master hostname' could not be resolved. Invalid or unresolveable address. Set 'master' value in minion config.
But network and resolving are working fine on this host:
$ host google.com
google.com has address 74.125.196.138
...
$ ping google.com
PING google.com (74.125.196.101) 56(84) bytes of data.
64 bytes from yk-in-f101.1e100.net (74.125.196.101): icmp_seq=1 ttl=44 time=105 ms
64 bytes from yk-in-f101.1e100.net (74.125.196.101): icmp_seq=2 ttl=44 time=104 ms
...
$ telnet master_hostname 4506
Trying master_host_ip_address...
Connected to master_hostname.
Escape character is '^]'.
^]
telnet> Connection closed.

### Setup
$ cat /etc/salt/minion
id: hostname of salt-minion
master: master hostname
master_port: '4506'
$ cat /etc/apt/sources.list.d/saltstack.list  
deb https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main

### Steps to Reproduce Issue
$ apt-get install salt-minion=2016.11.4+ds-1
...
$ tail /var/log/salt/minion
2017-04-27 23:25:33,512 [salt.cli.daemons ][ERROR   ][3560] Master address: 'salt master host' could not be resolved. Invalid or unresolveable address. Set 'master' value in minion config.
2017-04-27 23:25:39,528 [salt.loaded.int.grains.core][WARNING ][3637] Unable to find IPv6 record for "salt minion host" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
2017-04-27 23:25:39,624 [salt.minion      ][ERROR   ][3637] Master address: 'salt master host' could not be resolved. Invalid or unresolveable address. Set 'master' value in minion config.
$ ps ax | grep salt | grep -v grep
$ 
And previous version is working fine:
$ dpkg -i salt-minion_2016.11.3+ds-1_all.deb salt-common_2016.11.3+ds-1_all.deb
...
$ ps ax | grep salt | grep -v grep
 4897 ?        Ss     0:00 /usr/bin/python /usr/bin/salt-minion
 4903 ?        Sl     0:00 /usr/bin/python /usr/bin/salt-minion
 4922 ?        S      0:00 /usr/bin/python /usr/bin/salt-minion
$ /etc/init.d/salt-minion stop
$ salt-minion -l info
[INFO    ] Setting up the Salt Minion "salt minion hostname"
[INFO    ] Starting up the Salt Minion
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_f6be6e91aa_pull.ipc
[INFO    ] Creating minion process manager
[INFO    ] Executing command ['date', '+%z'] in directory '/root'
[INFO    ] Updating job settings for scheduled job: __mine_interval
[INFO    ] Added mine.update to scheduler
[INFO    ] Minion is starting as user 'root'
[INFO    ] Minion is ready to receive requests!

### Versions Report
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.8.0-45-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment] 2017-04-27 22:21
This is a duplicate of https://github.com/saltstack/salt/issues/40908

master_port should be an int, but it was able to be a string before, I have submitted a pr for this fix.

Thanks,
Daniel

**Closed by gtmanfred** 2017-04-27 22:21 UTC

**Comment by keyd** [comment] 2017-04-28 08:26
Thanks!
