### ISSUE TITLE
Windows package installer support should check for GET status

### ISSUE THREAD

**Issue by cournape** [saltstack/salt#20673] opened 2015-02-13 10:52 UTC
If one has a simple package definition as follows:

```
widget:
  1.0.0:
    installer: 'https://acme.com/widget'
...
```

and the given url does not exist or cannot be accessed for any reason, salt happily continues instead of failing early.

**Comment by cournape** [comment] 2015-02-13 10:58
Quickly looking at the code, seems that `cp.cache_file` is the culprit. It does not seem to check for http status.

**Comment by jfindlay** [comment] 2015-02-13 17:56
@cournape, will you also provide the output of `salt --versions-report`?  Thanks.

**Comment by eliasp** [comment] 2015-02-13 22:21
Duplicate of #20522

**Comment by basepi** [comment] 2015-05-19 20:30
Closing as a duplicate. Thanks for pointing that out, @eliasp

**Closed by basepi** 2015-05-19 20:30 UTC
Labels: Bug, Medium Severity
