### ISSUE TITLE
salt master added master_job_cache has error and warning messages

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#40071] opened 2017-03-16 07:13 UTC
### Description of Issue/Question
salt master added master_job_cache has error and warning messages
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
1.master versions
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
2.minion version
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
3.master has  master_cache_job
mysql.host: '***'
mysql.user: 'root'
mysql.pass: '***'
mysql.db: 'salt'
mysql.port: '3306'
master_job_cache: mysql

4.run command
```
salt '*' test.ping
[ERROR   ] Exception raised when processing __virtual__ function for pkgutil. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.pkgutil.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pkgutil', pl
ease fix this.[ERROR   ] Exception raised when processing __virtual__ function for pw_user. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.pw_user.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pw_user', pl
ease fix this.[ERROR   ] Exception raised when processing __virtual__ function for freebsdservice. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.freebsdservice.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freeb
sdservice', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for zfs. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.zfs.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'zfs', please fix
 this.[ERROR   ] Exception raised when processing __virtual__ function for makeconf. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.makeconf.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'makeconf', 
please fix this.[ERROR   ] Exception raised when processing __virtual__ function for solarisips. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.solarisips.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'solarisip
s', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for smf. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.smf.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'smf', please fix
 this.[ERROR   ] Exception raised when processing __virtual__ function for openbsd_sysctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.openbsd_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openb
sd_sysctl', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for logadm. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.logadm.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'logadm', plea
se fix this.[ERROR   ] Exception raised when processing __virtual__ function for eselect. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.eselect.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'eselect', pl
ease fix this.[ERROR   ] Exception raised when processing __virtual__ function for poudriere. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.poudriere.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'poudriere'
, please fix this.[ERROR   ] Exception raised when processing __virtual__ function for mdadm. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.mdadm.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'mdadm', please
 fix this.[ERROR   ] Exception raised when processing __virtual__ function for dpkg. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.dpkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'dpkg', please f
ix this.[ERROR   ] Exception raised when processing __virtual__ function for solaris_group. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.solaris_group.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'solari
s_group', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for openbsdrcctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.openbsdrcctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openbsd
rcctl', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for systemd. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.systemd.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'systemd', pl
ease fix this.[ERROR   ] Exception raised when processing __virtual__ function for mac_xattr. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.mac_xattr.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'mac_xattr'
, please fix this.[ERROR   ] Exception raised when processing __virtual__ function for solarispkg. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.solarispkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'solarispk
g', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for kmod. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.kmod.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'kmod', please f
ix this.[ERROR   ] Exception raised when processing __virtual__ function for eix. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.eix.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'eix', please fix
 this.[ERROR   ] Exception raised when processing __virtual__ function for xbpspkg. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.xbpspkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'xbpspkg', pl
ease fix this.[ERROR   ] Exception raised when processing __virtual__ function for netbsdservice. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.netbsdservice.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'netbsd
service', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for linux_sysctl. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.linux_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'linux_s
ysctl', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for service. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'service', pl
ease fix this.[ERROR   ] Exception raised when processing __virtual__ function for bridge. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.bridge.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'bridge', plea
se fix this.[ERROR   ] Exception raised when processing __virtual__ function for pkgng. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.pkgng.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pkgng', please
 fix this.[ERROR   ] Exception raised when processing __virtual__ function for openbsdpkg. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.openbsdpkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openbsdpk
g', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for freebsd_sysctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.freebsd_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freeb
sd_sysctl', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for grub_legacy. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.grub_legacy.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'grub_leg
acy', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for upstart. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.upstart.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'upstart', pl
ease fix this.[ERROR   ] Exception raised when processing __virtual__ function for freebsdports. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.freebsdports.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsd
ports', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for freebsdkmod. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.freebsdkmod.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsdk
mod', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for freebsdpkg. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.freebsdpkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsdpk
g', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for pacman. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.pacman.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pacman', plea
se fix this.[ERROR   ] Exception raised when processing __virtual__ function for keyboard. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.keyboard.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'keyboard', 
please fix this.[ERROR   ] Exception raised when processing __virtual__ function for nspawn. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.nspawn.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'nspawn', plea
se fix this.[ERROR   ] Exception raised when processing __virtual__ function for groupadd. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.groupadd.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'groupadd', 
please fix this.[ERROR   ] Exception raised when processing __virtual__ function for freebsdjail. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.freebsdjail.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsdj
ail', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for solaris_user. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.solaris_user.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'solaris
_user', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for pkgin. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.pkgin.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pkgin', please
 fix this.[ERROR   ] Exception raised when processing __virtual__ function for deb_apache. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.deb_apache.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'deb_apach
e', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for gentoo_service. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.gentoo_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'gento
o_service', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for mac_sysctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.mac_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'mac_sysct
l', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for gentoolkitmod. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.gentoolkitmod.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'gentoo
lkitmod', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for useradd. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.useradd.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'useradd', pl
ease fix this.[ERROR   ] Exception raised when processing __virtual__ function for linux_ip. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.linux_ip.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'linux_ip', 
please fix this.[ERROR   ] Exception raised when processing __virtual__ function for rh_service. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.rh_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_servic
e', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for apache. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.apache.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'apache', plea
se fix this.[ERROR   ] Exception raised when processing __virtual__ function for layman. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.layman.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'layman', plea
se fix this.[ERROR   ] Exception raised when processing __virtual__ function for xapi. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.xapi.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'xapi', please f
ix this.[ERROR   ] Exception raised when processing __virtual__ function for debian_service. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.debian_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'debia
n_service', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for netbsd_sysctl. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.netbsd_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'netbsd
_sysctl', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for rh_ip. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.rh_ip.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_ip', please
 fix this.[ERROR   ] Exception raised when processing __virtual__ function for win_powercfg. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.win_powercfg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_pow
ercfg', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for debconfmod. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.debconfmod.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'debconfmo
d', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for openbsdservice. Module will not be loaded 'os'
[WARNING ] salt.loaded.int.module.openbsdservice.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openb
sdservice', please fix this.[ERROR   ] Exception raised when processing __virtual__ function for debian_ip. Module will not be loaded 'os_family'
[WARNING ] salt.loaded.int.module.debian_ip.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'debian_ip'
, please fix this.[ERROR   ] Exception raised when processing __virtual__ function for pw_group. Module will not be loaded 'kernel'
[WARNING ] salt.loaded.int.module.pw_group.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pw_group', 
please fix this.[WARNING ] Returner unavailable: 'mysql.get_load'
172.20.7.35:
    True
```
please help me!
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment] 2017-03-16 12:13
This appears to be a duplicate of https://github.com/saltstack/salt/issues/40017

Thanks,
Daniel

**Closed by gtmanfred** 2017-03-16 12:13 UTC
