### ISSUE TITLE
[2016.11.3] salt/pillar/nodegroups.py not working with nested nodegroups

### ISSUE THREAD

**Issue by Herugrim** [saltstack/salt#40093] opened 2017-03-16 21:17 UTC
### Description of Issue/Question

I recently started using the Nodegroups pillar (https://github.com/saltstack/salt/blob/2016.11/salt/pillar/nodegroups.py) that was added in 2016.11.0 and i found an issue that nested nodegroups are not returned as a pillar.

### Setup

Example nodegroup configuration:

```
nodegroups:
 group1: L@salt-minion
 group2: L@salt-minion-2
 group3: L@salt-minion-3
 group4: 'E@salt-minion.*'
 group5: 'E@salt-minion.* and N@group3'
 group6: 'N@group1 or N@group2'
```

### Steps to Reproduce Issue

Targetting group5 and group6 from the cli salt or from the SLS is no issue:

```
root@saltmaster:~# salt -N group5 test.ping
salt-minion-3:
    True
root@saltmaster:~# salt -N group6 test.ping
salt-minion-2:
    True
salt-minion:
    True
```

I am using the nodegroups pillar loop through all nodegroups the minion is member of and apply roles. While setting this up i noticed that the nested nodegroups are not picked up in this pillar:

```
root@saltmaster:~# salt '*' saltutil.refresh_pillar
salt-minion:
    True
salt-minion-2:
    True
salt-minion-3:
    True
root@saltmaster:~# salt '*' pillar.get nodegroups
salt-minion:
    - group4
    - group1
salt-minion-3:
    - group4
    - group3
salt-minion-2:
    - group4
    - group2
```
As you can see groups 1-4 work fine, but the ones containing another nodegroup do not. I dove into the code and found that `nodegroups.py` uses the `check_minions()` method in https://github.com/saltstack/salt/blob/2016.11/salt/utils/minions.py to create the pillar. From this method `check_compound_minions()` is called. From what i am seeing there i think the assumption is that nodegroups are always expanded already (not sure if i am making sense here). 

On line 453:

```
if self.opts.get('minion_data_cache', False):
    ref = {'G': self._check_grain_minions,
              [...]
              'N': None, # nodegroups should already be expanded
```
On line 526:

```
elif target_info and target_info['engine']:
    if 'N' == target_info['engine']:
          # Nodegroups should already be expanded/resolved to other engines
          log.error('Detected nodegroup expansion failure of "{0}"'.format(word))
          return []

```

I suspect that this is the reason why nested nodegroups are not working in this pillar. I have spent some time on trying to solve this but my guess is that you are able to find it faster as it is functioning when targetting the specific group from CLI or SLS.

### Versions Report

```
root@saltmaster:~# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-112-generic
         system: Linux
        version: Ubuntu 14.04 trusty

```

Minions are the same, but they are not relevant for this issue as the pillar is rendered on the salt-master. If you need any other information please let me know, thanks in advance for the help.

**Comment by gtmanfred** [comment] 2017-03-16 21:45
As is noted here, because N@ is not listed, The compound matcher does not support node groups, therefore nodegroups do not support matching nodegroups when using the compound matcher.

This is a duplicate of this feature request https://github.com/saltstack/salt/issues/6602

Thanks,
Daniel

**Closed by gtmanfred** 2017-03-16 21:45 UTC
