### ISSUE TITLE
[BUG] Installing CentOS 7 along with Salt 3006.8 RPM fails

### ISSUE THREAD

**Issue by jcpearson** [saltstack/salt#66612] opened 2024-06-03 11:52 UTC
**Description**
Doing a kickstart install of CentOS 7 using repos that also contain the Salt 3006.8 RPMS fails

**Setup**
CentOS kickstart set to install salt and salt-minion v3006.8 RPMS 

Please be as specific as possible and give set-up details.

-  on-prem machine
-  VM (VMware, Nutanix)
-  onedir packaging

**Expected behavior**
CentOS 7 and Salt 3006.8 get installed

**Versions Report**
Can't supply versions report as install fails ...

**Additional context**

The CentOS 7 installer fails (from packaging.log):
```
09:20:52,691 INFO packaging: salt-3006.8-0.x86_64 (571/2681)
09:20:52,691 INFO packaging: warning: salt-3006.8-0.x86_64: Header V4 RSA/SHA256 Signature, key ID 73d76b3f: NOKEY
09:20:52,691 INFO packaging: /var/tmp/rpm-tmp.XAOFtB: line 18: usermod: command not found
09:20:52,691 INFO packaging: error: %pre(salt-3006.8-0.x86_64) scriptlet failed, exit status 127
09:20:52,691 INFO packaging: ==== end rpm scriptlet logs ====
```
The issue is that the installer is installing the salt RPM _before_ the shadow-utils RPM (which provides the usermod utility) - despite the RPM having an explicit requirement of the /usr/sbin/usermod utility

I don't get this issue when installing Rocky 9 along with Salt 3006.8 - nor when installing CentOS 7 with Salt 3006.7

I suspect this might have something to do with bug #66604 - as in, the CentOS 7 installer is installing the salt RPM early in the install process as the salt RPM is advertising that it is providing a number of core system libs (when it actually isn't) - which is somehow trumping the requirement of needing /usr/sbin/usermod ?

i.e. the 'fix' is probably to remove the bogus 'provides' the salt RPM is currently claiming it is providing ?

**Comment by jcpearson** [comment] 2024-06-03 18:09
Although I said I can install Rocky 9 along with Salt 3006.8, the resulting install is broken as various (required) packages are not installed as the installer thinks salt has provided them ... same issue as with bug #66604

**Comment by dwoz** [comment] 2024-06-11 04:39
Closing as a duplicate of #66604

**Closed by dwoz** 2024-06-11 04:39 UTC
Labels: Bug, needs-triage
