### ISSUE TITLE
salt.states.git.latest failure when specifying commit hash

### ISSUE THREAD

**Issue by ipmb** [saltstack/salt#24879] opened 2015-06-22 22:15 UTC
I typically use a branch for the `rev` kwarg to `git.latest` which works fine, but specifying a commit hash as the `rev` fails in 2015.5.0:

> Comment: Command 'git branch {HASH} --set-upstream origin/{HASH}' failed. Stderr: 'The --set-upstream flag is deprecated and will be removed. Consider using --track or --set-upstream-to\nerror: the requested upstream branch \'origin/{HASH}\' does not exist\nhint: \nhint: If you are planning on basing your work on an upstream\nhint: branch that already exists at the remote, you may need to\nhint: run "git fetch" to retrieve it.\nhint: \nhint: If you are planning to push out a new local branch that\nhint: will track its remote counterpart, you may want to use\nhint: "git push -u" to set the upstream config as you push.'

**Comment by jtand** [comment] 2015-06-24 19:38
@ipmb I think this may be a duplicate of #24386. Can you provide the state you are using to get this error?

**Comment by ipmb** [comment] 2015-06-24 21:38
```
{{ repo }}:
    git.latest:
      - rev: {{ branch }}
      - target: {{ src }}
      - user: {{ project }}
      - https_user: {{ pillar.github_token }}
      - https_pass: x-oauth-basic
      - require:
        - pkg: git-core
        - user: {{ project }}
```

**Comment by terminalmage** [comment] 2015-08-18 20:48
This will be fixed in 2015.8.0, as the git.latest state has been rewritten.

For its new behavior, when a SHA1 is specified as the rev, a branch is checked out at that SHA1. You can also now specify the local branch name to use. The state is smart enough now not to try to make a non-fast-forward change unless ``force_reset`` is set to ``True``, in which case it performs a ``git reset --hard`` to that SHA1.

Is this sufficient for your needs?

**Comment by ipmb** [comment] 2015-08-18 20:50
That sounds like it would work. Thanks!

**Comment by terminalmage** [comment] 2015-08-18 21:01
@ipmb Great! Also, note that short-SHA1s will now be supported.

Since this meets your needs, I'll go ahead and close this. Thanks for the quick follow-up.

**Closed by terminalmage** 2015-08-18 21:01 UTC
Labels: Info Needed
