### ISSUE TITLE
master exits with code 0 when minion did not return

### ISSUE THREAD

**Issue by cehrig** [saltstack/salt#30148] opened 2016-01-05 12:27 UTC
When a minion did not return the master exists with code 0, see example below.
```
admin@saltmaster:~# salt 'dev1.rdcn' test.ping
dev1.rdcn:
    Minion did not return. [Not connected]
admin@saltmaster:~# echo $?
0
```
I would expect an exit code > 0 since this is an error. 

```
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo8+1
```

**Comment by jfindlay** [comment] 2016-01-05 17:01
@cehrig, thanks for the report.  This is a duplicate of #18510.

**Closed by jfindlay** 2016-01-05 17:01 UTC
Labels: Duplicate

**Comment by logi** [comment] 2017-01-14 05:41
By closing this issue as a duplicate of #18510 it has become attached to much larger and hairier problem which is taking a long time to resolve and requires coordination among plugins etc. It seems that it would be much easier to just go ahead and return a non-zero code when a minion fails to even return.

In the mean time, I guess I'm going to have my script parse salt output for the phrase "Minion did not return" and report that as an error.
