### ISSUE TITLE
Current Ubuntu Lucid package (2014.7.5+ds-1lucid2) broken, missing file

### ISSUE THREAD

**Issue by righdforsa** [saltstack/salt#23195] opened 2015-04-30 01:19 UTC
Looks like there's a file missing in the current package version. After an update, I get the following error running salt-call.
```
hostname:~$ sudo salt-call --local state.highstate test=True
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 7, in <module>
    from salt.scripts import salt_call
  File "/usr/lib/python2.6/dist-packages/salt/scripts.py", line 17, in <module>
  File "/usr/lib/python2.6/dist-packages/salt/cli/__init__.py", line 17, in <module>
  File "/usr/lib/python2.6/dist-packages/salt/client/ssh/__init__.py", line 143, in <module>
  File "/usr/lib/python2.6/dist-packages/salt/utils/__init__.py", line 1066, in fopen
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.6/dist-packages/salt/client/ssh/ssh_py_shim.pyc'
hostname:~$ 
```

**Comment by jfindlay** [comment] 2015-05-01 00:17
@righdforsa, thanks for the report.  This is a duplicate of #23179.  If you have any updates, please comment there.

**Closed by jfindlay** 2015-05-01 00:17 UTC
Labels: Duplicate
