### ISSUE TITLE
Saltstack Coreos service provider

### ISSUE THREAD

**Issue by pguinardco** [saltstack/salt#48160] opened 2018-06-15 20:40 UTC
### Description of Issue/Question

Service.running does not work while running on coreos.

### Setup
_0_, facility0_.updated_dt as updated_7_11_0_, facility0_.collateral_type as collater8_11_0_, facility0_.collection_date_id as collect14_11_0_, facility0_.default_lender_id as default_9_11_0_, facility0_.determination_date_id as determi15_11_0_, facility0_.facility_n{"timestamp":"2018-06-15T13:34:03.150Z","level":"INdocker:
  service.running:
    - name: docker
    - enable: true
    - watch:
      - file: /etc/docker/daemon.json

### Steps to Reproduce Issue

Run saltstack on coreos (container linux).

### Steps to fix Issue

Follow documentation and add the provider section (https://docs.saltstack.com/en/latest/ref/modules/index.html#module-provider-override):

providers:
  service: systemd

Your documentation rocks!

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.15 (default, May 16 2018, 17:50:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist: fedora 28 Twenty Eight
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.14.32-coreos
         system: Linux
        version: Fedora 28 Twenty Eight

### Grains.items

    ----------
    SSDs:
        - dm-1
        - xvdc
        - xvda
        - dm-2
        - dm-0
        - dm-3
    biosreleasedate:
        08/24/2006
    biosversion:
        4.2.amazon
    cpu_flags:
        - fpu
        - vme
        - de
        - pse
        - tsc
        - msr
        - pae
        - mce
        - cx8
        - apic
        - sep
        - mtrr
        - pge
        - mca
        - cmov
        - pat
        - pse36
        - clflush
        - mmx
        - fxsr
        - sse
        - sse2
        - ht
        - syscall
        - nx
        - rdtscp
        - lm
        - constant_tsc
        - rep_good
        - nopl
        - xtopology
        - cpuid
        - pni
        - pclmulqdq
        - ssse3
        - fma
        - cx16
        - pcid
        - sse4_1
        - sse4_2
        - x2apic
        - movbe
        - popcnt
        - tsc_deadline_timer
        - aes
        - xsave
        - avx
        - f16c
        - rdrand
        - hypervisor
        - lahf_lm
        - abm
        - cpuid_fault
        - invpcid_single
        - pti
        - fsgsbase
        - bmi1
        - avx2
        - smep
        - bmi2
        - erms
        - invpcid
        - xsaveopt
    cpu_model:
        Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    cpuarch:
        x86_64
    disks:
    gid:
        0
    gpus:
        |_
          ----------
          model:
              GD 5446
          vendor:
              unknown
    groupname:
        root
    init:
        systemd
    kernel:
        Linux
    kernelrelease:
        4.14.32-coreos
    kernelversion:
        #1 SMP Tue Apr 3 05:21:26 UTC 2018
    locale_info:
        ----------
        defaultencoding:
            None
        defaultlanguage:
            None
        detectedencoding:
            ascii
    lsb_distrib_codename:
        Rhyolite
    lsb_distrib_description:
        Container Linux by CoreOS 1688.5.3
    lsb_distrib_id:
        Container Linux by CoreOS
    lsb_distrib_release:
        1688.5.3
    manufacturer:
        Xen
    num_cpus:
        2
    num_gpus:
        1
    os:
        Container by CoreOS
    os_family:
        Container by CoreOS
    osarch:
        x86_64
    oscodename:
        Rhyolite
    osfinger:
        Container Linux by CoreOS-1688
    osfullname:
        Container Linux by CoreOS
    osmajorrelease:
        1688
    osrelease:
        1688.5.3
    osrelease_info:
        - 1688
        - 5
        - 3
    path:
     /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/usr/local/sbin:/opt/usr/local/bin:/opt/usr/sbin:/opt/usr/bin:/opt/sbin:/opt/bin
    productname:
        HVM domU
    ps:
        ps -efHww
    pythonexecutable:
        /opt/usr/bin/python2
    pythonpath:
        - /opt/usr/bin
        - /opt/usr/lib/python27.zip
        - /opt/usr/lib64/python2.7
        - /opt/usr/lib64/python2.7/plat-linux2
        - /opt/usr/lib64/python2.7/lib-tk
        - /opt/usr/lib64/python2.7/lib-old
        - /opt/usr/lib64/python2.7/lib-dynload
        - /opt/usr/lib64/python2.7/site-packages
        - /opt/usr/lib/python2.7/site-packages
    pythonversion:
        - 2
        - 7
        - 15
        - final
        - 0
    saltpath:
        /opt/usr/lib/python2.7/site-packages/salt
    saltversion:
        2018.3.0
    saltversioninfo:
        - 2018
        - 3
        - 0
        - 0
    shell:
        /bin/sh
    swap_total:
        0
    systemd:
        ----------
        features:
            +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN +PCRE2 default-hierarchy=legacy
        version:
            237
    virtual:
        xen
    virtual_subtype:
        Xen PV DomU
    zfs_support:
        False
    zmqversion:
        4.1.6

**Comment by Ch3LL** [comment] 2018-06-18 20:06
duplicate of https://github.com/saltstack/salt/issues/38931  closing here and you can monitor issue there. thanks :)

**Closed by Ch3LL** 2018-06-18 20:06 UTC
