### ISSUE TITLE
[BUG] Installation of pycurl fails in onedir installation

### ISSUE THREAD

**Issue by Christoph-TKE** [saltstack/salt#62949] opened 2022-10-24 17:28 UTC
**Description**
At a fresh Ubuntu 22.04.1 installation, `salt-pip` fails to install `pycurl`. Normal installation of pycurl with system-default python/pip works as expected.

This only affects the installation of `pycurl` (and probably others) but is not a general issue. For instance, installation of `tornado` package works without any errors.

**Setup**

Default onedir minion installtion (v3005.1) on a fresh Ubuntu 22.04.1 from server installation image. No special configuration for master or minion required.

Environment in salt is the same as in a regular bash except for these values: (`/opt/saltstack/salt/run/run shell` -> examine `os.environ`)
```
_: /opt/saltstack/salt/run/run
LD_LIBRARY_PATH: /opt/saltstack/salt/run
TCL_LIBRARY: /opt/saltstack/salt/run/tcl
TK_LIBRARY: /opt/saltstack/salt/run/tk
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [X] VM (VMware ESXi)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

 1. Install Ubuntu 22.04.1 (minimal server installation, in case it matters)
 2. Install salt-minion from onedir deb repository (tested with v3005 and v3005.1)
 3. `sudo salt-pip install -v --no-cache-dir --no-clean pycurl`

The above sequence triggers this error message:
```
Collecting pycurl
  Downloading pycurl-7.45.1.tar.gz (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 kB 8.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-rwor65_m
```

There is no directory `/tmp/pip-pip-egg-info-xxxxxxx` (tempfile suffix changes with every run). But there are two other directories created by `salt-pip`:
```diff
--- tmp.before-pip      2022-10-24 17:05:27.873782893 +0200
+++ tmp.after-pip       2022-10-24 17:08:27.510012183 +0200
@@ -1,3 +1,5 @@
+pip-ephem-wheel-cache-8xt3qi4q/
+pip-install-s_1fb28u/
 ssh-XXXXLBaO0f/
 systemd-private-647016854e1e4c91b80f5d92d6ec5f06-systemd-logind.service-EDui5Q/
 systemd-private-647016854e1e4c91b80f5d92d6ec5f06-systemd-resolved.service-ypjjU6/
```

**Expected behavior**
`salt-pip` should install `pycurl` like the system-default python/pip does.

**Screenshots**
(no screenshots provided)

**Versions Report**
<details><summary>salt-minion --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.14 (main, Oct  3 2022, 21:22:21)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-48-generic
        system: Linux
       version: Ubuntu 22.04 jammy

```
</details>

**Additional context**
Branched off from issue #62930.

**Comment by maltris** [comment] 2022-11-04 12:16
I can confirm this, testing transition to the onedir packages. This whole change to onedir and salt-pip does not seem to make any sense, given that one must install so many dependencies and with each pip-package there is some unexpected problem, this really drops the experience-points to zero.

**Comment by maltris** [comment] 2022-11-08 17:25
Adding --debug to the salt-pip command will produce this:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/.pyenv/versions/3.9.14/envs/tmpkbzyfkoz/bin/salt:118 in <module>                           │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/.pyenv/versions/3.9.14/envs/tmpkbzyfkoz/bin/salt'    │
│                                                                                                  │
│ /root/.pyenv/versions/3.9.14/envs/tmpkbzyfkoz/bin/salt:101 in redirect                           │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/.pyenv/versions/3.9.14/envs/tmpkbzyfkoz/bin/salt'    │
│                                                                                                  │
│ /root/tiamatpip/cli.py:246 in process_pip_argv                                                   │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/tiamatpip/cli.py'                                    │
│                                                                                                  │
│ /root/tiamatpip/cli.py:214 in process_argv                                                       │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/tiamatpip/cli.py'                                    │
│                                                                                                  │
│ /root/tiamatpip/cli.py:315 in redirect_to_pip                                                    │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/tiamatpip/cli.py'                                    │
│                                                                                                  │
│ /root/tiamatpip/cli.py:344 in call_pip                                                           │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/tiamatpip/cli.py'                                    │
│                                                                                                  │
│ /root/pip/_internal/cli/main.py:70 in main                                                       │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/cli/main.py'                           │
│                                                                                                  │
│ /root/pip/_internal/cli/base_command.py:101 in main                                              │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/cli/base_command.py'                   │
│                                                                                                  │
│ /root/pip/_internal/cli/base_command.py:221 in _main                                             │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/cli/base_command.py'                   │
│                                                                                                  │
│ /root/pip/_internal/cli/req_command.py:247 in wrapper                                            │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/cli/req_command.py'                    │
│                                                                                                  │
│ /root/pip/_internal/commands/install.py:369 in run                                               │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/commands/install.py'                   │
│                                                                                                  │
│ /root/pip/_internal/resolution/resolvelib/resolver.py:92 in resolve                              │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/resolution/resolvelib/resolver.py'     │
│                                                                                                  │
│ /root/pip/_vendor/resolvelib/resolvers.py:481 in resolve                                         │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_vendor/resolvelib/resolvers.py'                 │
│                                                                                                  │
│ /root/pip/_vendor/resolvelib/resolvers.py:348 in resolve                                         │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_vendor/resolvelib/resolvers.py'                 │
│                                                                                                  │
│ /root/pip/_vendor/resolvelib/resolvers.py:172 in _add_to_criteria                                │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_vendor/resolvelib/resolvers.py'                 │
│                                                                                                  │
│ /root/pip/_vendor/resolvelib/structs.py:151 in __bool__                                          │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_vendor/resolvelib/structs.py'                   │
│                                                                                                  │
│ /root/pip/_internal/resolution/resolvelib/found_candidates.py:155 in __bool__                    │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/root/pip/_internal/resolution/resolvelib/found_candidates.py'                                  │
│                                                                                                  │
│ /root/pip/_internal/resolution/resolvelib/found_candidates.py:143 in <genexpr>                   │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/root/pip/_internal/resolution/resolvelib/found_candidates.py'                                  │
│                                                                                                  │
│ /root/pip/_internal/resolution/resolvelib/found_candidates.py:47 in _iter_built                  │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/root/pip/_internal/resolution/resolvelib/found_candidates.py'                                  │
│                                                                                                  │
│ /root/pip/_internal/resolution/resolvelib/factory.py:206 in _make_candidate_from_link            │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/resolution/resolvelib/factory.py'      │
│                                                                                                  │
│ /root/pip/_internal/resolution/resolvelib/candidates.py:297 in __init__                          │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/resolution/resolvelib/candidates.py'   │
│                                                                                                  │
│ /root/pip/_internal/resolution/resolvelib/candidates.py:162 in __init__                          │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/resolution/resolvelib/candidates.py'   │
│                                                                                                  │
│ /root/pip/_internal/resolution/resolvelib/candidates.py:231 in _prepare                          │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/resolution/resolvelib/candidates.py'   │
│                                                                                                  │
│ /root/pip/_internal/resolution/resolvelib/candidates.py:308 in _prepare_distribution             │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/resolution/resolvelib/candidates.py'   │
│                                                                                                  │
│ /root/pip/_internal/operations/prepare.py:438 in prepare_linked_requirement                      │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/operations/prepare.py'                 │
│                                                                                                  │
│ /root/pip/_internal/operations/prepare.py:524 in _prepare_linked_requirement                     │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/operations/prepare.py'                 │
│                                                                                                  │
│ /root/pip/_internal/operations/prepare.py:68 in _get_prepared_distribution                       │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/operations/prepare.py'                 │
│                                                                                                  │
│ /root/pip/_internal/distributions/sdist.py:61 in prepare_distribution_metadata                   │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/distributions/sdist.py'                │
│                                                                                                  │
│ /root/pip/_internal/req/req_install.py:539 in prepare_metadata                                   │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/req/req_install.py'                    │
│                                                                                                  │
│ /root/pip/_internal/operations/build/metadata_legacy.py:74 in generate_metadata                  │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/operations/build/metadata_legacy.py'   │
│                                                                                                  │
│ /root/pip/_internal/operations/build/metadata_legacy.py:26 in _find_egg_info                     │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/root/pip/_internal/operations/build/metadata_legacy.py'   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
InstallationError: No .egg-info directory found in /tmp/pip-pip-egg-info-d8n6uag2
[1937848] Failed to execute script 'salt' due to unhandled exception!

```

**Comment by tkaehn** [comment] 2022-11-21 08:30
I am also affected by this bug. Is there any workaround? Not being able to configure a proxy in the minion makes the onedir packages unusable for me.

**Comment by DaAwesomeP** [comment] 2022-12-03 20:25
Having this issue on RHEL 8. I'm also a bit confused why this package isn't included by default since it seemed to be installed as an OS Python dependency prior to onedir.

**Comment by maltris** [comment] 2022-12-07 10:07
Its a big riddle, these issues are all over your issue tracker, problems with metadata, problems like this one, many modules not installable. I for one will go on with the prebuilt tiamat solution and see if that works out. The organization here is a big mess, the ticket is from 24. october. Unfortunately I am forced to use salt, if not, I would have already abandoned it.

**Comment by DaAwesomeP** [comment] 2023-01-19 05:08
Any updates on this issue?

**Comment by mastrong** [comment] 2023-01-19 13:34
They aren't really looking to fix issues w/tiamat onedirs, since they've shifted to relenv for 3006 to resolve a lot of these issues.
See the Q&A section: https://saltproject.io/open-hour-2022-dec-1/

**Comment by dwoz** [comment] 2023-03-21 03:26
Closed by accident.

**Comment by lokichoggio** [comment] 2023-03-21 10:38
Is there any progress？

**Comment by DaAwesomeP** [comment] 2023-03-21 13:02
@lokichoggio from the above comment it sounds like we're waiting for v3006. I believe there is an approximate planned release timeline.

**Comment by garethgreenaway** [comment] 2023-04-03 17:37
The fix will be specific to 3006 and the approach to installing PyCURL is documented here: https://relenv.readthedocs.io/en/latest/additional-dependencies.html

**Closed by garethgreenaway** 2023-04-03 17:37 UTC
Labels: Bug, Packaging, dependency, pending-close
