### ISSUE TITLE
SaltStack removing / character from Debian APT URIs

### ISSUE THREAD

**Issue by nycnewman** [saltstack/salt#53529] opened 2019-06-19 13:56 UTC
### Description of Issue

SaltStack strips / character from APT URIs and Google package adds an entry with this extra character resulting in duplicate entry and apt upgrade failures. Settings as per SaltStack manual for pkg.managed

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Deploy Google Chrome through SaltStack package to Ubuntu. On next package upgrde from Google, machine will fail to upgrade due to duplicate entry in /etc/apt/source.d file

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt 2018.3.4
any recent Google Chrome version.

**Comment by xeacott** [comment] 2019-06-20 15:45
Which version of Ubuntu are you running for this? Will try to duplicate

**Comment by nycnewman** [comment] 2019-06-20 16:08
Ubuntu 18.04

**Comment by xeacott** [comment] 2019-06-21 19:08
Thanks!

**Comment by nycnewman** [comment] 2019-09-04 21:03
were you able to reproduce?

**Comment by nycnewman** [comment] 2020-01-08 01:41
@xeacott Any update?

**Comment by sagetherage** [comment] 2020-02-11 22:11
@dwoz looks like Joe just got busy and this needs a some follow up so re-assigning

**Comment by sagetherage** [comment] 2020-03-16 21:31
@dwoz can you triage this ticket this week, please?

**Comment by dwoz** [comment] 2020-03-16 22:05
@nycnewman Sorry this never got resolved. Can you provide me with an example state to help reproduce the issue?

**Comment by nycnewman** [comment] 2020-03-16 22:13
`google-chrome-stable:
  pkgrepo.managed:
    - humanname: Google Chrome
    - name: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - dist: stable
    - gpgcheck: 1
    - file: /etc/apt/sources.list.d/google-chrome.list
    - key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    - require_in:
      - pkg: google-chrome-stable
  pkg.installed:
    - name: google-chrome-stable

fix-google-chrome-list:
  cmd.run:
    - name: echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
`

**Comment by ymasson** [comment] 2020-12-19 15:59
I think the problem is here:
https://github.com/saltstack/salt/blob/master/salt/states/pkgrepo.py#L427
```
    if __grains__["os_family"] == "Debian":
        repo = salt.utils.pkg.deb.strip_uri(repo)
 ```
 
 I don't know the history of code, but this lead to modify the `name` for the whole code. And add it in the .list file without the trailing /. Even if `name` contain a URL with a trailing /.
 The tests doesn't verify that case.
 
 I've found a old issue #18909 .

**Comment by garethgreenaway** [comment] 2022-11-03 15:55
I believe this one was resolved via https://github.com/saltstack/salt/pull/61986, if the issue persists please let us know.

**Closed by garethgreenaway** 2022-11-03 15:55 UTC
Labels: State-Module, Bug, Regression, good first issue
