### ISSUE TITLE
[BUG] slsutil.renderer does not work with salt-ssh

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#57474] opened 2020-05-27 14:56 UTC
**Description**
`slsutil.renderer` does not work with salt-ssh. The underlying problem seems to be during the call to `cp.get_url` and the differences in that function between the minion and ssh agents.

**Setup**
The simplest setup is to call slsutil.renderer directly:
`salt-call slsutil.renderer salt://anything.yaml`

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
Using a minion, this correctly returns the rendered data structure. Using salt-ssh, it returns nothing.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 3.0.2
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: 1.1.1
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.2 (default, Feb 28 2020, 00:00:00)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 18.1.0
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

```
</details>

**Additional context**

**Comment by max-arnold** [comment] 2020-05-30 02:47
Looks like a duplicate of https://github.com/saltstack/salt/issues/50196

**Closed** 2020-06-01 19:13 UTC
Labels: Bug, P4, Renderers, Salt-SSH
