### ISSUE TITLE
rabbitmq_{user|vhost}.present in test=True reports unnecessary changes

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#25363] opened 2015-07-13 08:13 UTC
If you run `salt-call state.highstate test=True` and the state contains a `rabbitmq_user.present` it always results in an item marked as "to be changed":
```
----------
          ID: rabbitmq_user_userxyz
    Function: rabbitmq_user.present
        Name: userxyz
      Result: None
     Comment: User userxyz already presents
     Started: 10:10:31.939836
    Duration: 392.501 ms
     Changes:   
```

Most likely the `result: None` should be changed to `result: True` in case the user already exists. The same is the case for other states (e.g. `service.running`)

The same applies to `rabbitmq_vhost.present` states which also return `None` rather than `True`

**Comment by jfindlay** [comment] 2015-07-13 19:05
@syphernl, thanks for the report.

This is nearly a duplicate of #24856, but has more information on `rabbitmq_vhost.present` also behaving incorrectly under `test=True`.

**Comment by rallytime** [comment] 2015-10-23 23:07
@syphernl I've refactored the rabbitmq_user.present state to make sure we're reporting errors and test=true functionality correctly. Can you give that a spin and let me know if you run into any problems?

The vhost.present state still needs to be fixed, however.

**Comment by rallytime** [comment] 2016-01-22 23:38
I have fixed the rabbitmq_vhost states in #30567 so that test=true reports `None` only when there are changes.

**Closed** 2016-01-25 23:19 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P3, Platform, State Module, TEAM RIoT
