### ISSUE TITLE
Git pull via Salt is very slow

### ISSUE THREAD

**Issue by jagardaniel** [saltstack/salt#20093] opened 2015-01-27 01:45 UTC
Hi,

We are experiencing some issues with git on Windows machines. The problem is that the "git pull"-command is executed very slowly. I'm not sure if this is a Salt issue, Git issue or a Windows issue. 

Example
```
root@saltmaster:~# time salt 'host.domain.com' git.pull C:/tmp
host.domain.com:
    Already up-to-date.

real    0m48.787s
user    0m0.264s
sys     0m0.080s
```

```
root@saltmaster:~# time salt 'host.domain.com' cmd.run 'cd C:/tmp & git pull'
host.domain.com:
    Already up-to-date.

real    0m48.790s
user    0m0.288s
sys     0m0.044s

```
It works fine if you are using cmd from Windows to execute "git pull". Other git-command (clone, add, commit, push) via Salt works without any issues at all, and are all finished within a couple of seconds. 

If you start Salt Minion on the Windows Machine directly from cmd (salt-minion.exe -c c:\salt\conf as an example) it works and you will get a fast response. An example where I run the same command but the minion is started via cmd instead of as a service:

```
root@saltmaster:~# time salt 'host.domain.com' git.pull C:/tmp
host.domain.com:
    Already up-to-date.

real    0m0.812s
user    0m0.284s
sys     0m0.040s
```

We have tried with:

Git versions:
Git-1.9.5-preview20141217
Git-1.9.2-preview20140411

Windows OS:
Windows Server 2012
Windows 2008 R2 Standard

Salt Minion versions:
2014.7.1
2014.7.0

Salt Master versions:
2014.7.0
2014.1.13 

Any ideas? Have I done something stupid (it has happened before!)? I tried to search for similiar issues but didn't find anything. 

Thanks in advance
//Daniel

**Comment by jfindlay** [comment] 2015-01-27 19:20
@jagardaniel, thanks for reporting this.  Does `git fetch` have the same problem?  What about `git rebase`, and `git pull --rebase`?

**Comment by jagardaniel** [comment] 2015-01-27 22:59
Hello @jfindlay and thanks for the answer.

```
[root@saltmastertest bf4]# time salt 'game-test' git.fetch C:/tmp/temporary/
game-test:


real    0m2.110s
user    0m0.419s
sys     0m0.066s
```

```
[root@saltmastertest bf4]# time salt 'game-test' git.rebase C:/tmp/temporary/ master
game-test:
    Current branch master is up to date.

real    0m31.067s
user    0m0.814s
sys     0m0.110s
```

```
[root@saltmastertest bf4]# time salt 'game-test' git.pull  C:/tmp/temporary/  opts='--rebase origin master'
game-test:
    Current branch master is up to date.

real    0m32.771s
user    0m0.702s
sys     0m0.093s
```

/Daniel

**Comment by jagardaniel** [comment] 2015-02-04 02:46
Hi again,

We did deploy a state including a git pull on eight servers and it worked much faster on some of the machines.

```
[root@saltmastertest ~]# time salt 'server18' cmd.run 'cd C:/tmp/instances/bfh/13 & git pull'
server:
    Already up-to-date.

real    0m5.889s
user    0m0.452s
sys     0m0.065s
```

I'm not sure if this is a coincident, but one difference between the faster and slower servers is that the faster ones only got one IPv4 address assigned, and the slower has two IPs. They are running the same OS and the same hardware. Got same version of Salt minion and master. Same version of Git. 

Is there anything else I should look for when comparing them?

Thanks in advance
/Daniel

**Comment by jfindlay** [comment] 2015-02-04 19:06
@jagardaniel, that is a good point.  Thank you for providing all of the good information.

**Comment by UtahDave** [comment] 2015-07-13 21:23
I've reproduced this issue. I'm still running into this issue even though I have no IPv6 addresses on this VM

```
root@boucha:~# time salt 'windows*' git.pull C:/tmp/salt
windows_test01:
    Updating 2989a35..bcd91a9
    Fast-forward
     salt/modules/rh_ip.py              | 20 ++++++++++++++------
     salt/templates/rh_ip/rh7_eth.jinja | 11 ++++++++++-
     tests/unit/modules/rh_ip_test.py   |  6 ++++++
     3 files changed, 30 insertions(+), 7 deletions(-)

real	0m27.067s
user	0m0.620s
sys	0m0.216s
root@boucha:~# time salt 'windows*' git.pull C:/tmp/salt
windows_test01:
    Already up-to-date.
 
real	0m26.174s
user	0m0.612s
sys	0m0.228s
root@boucha:~# time salt 'windows*' network.interfaces
windows_test01:
    ----------
    AWS PV Network Device #0:
        ----------
        hwaddr:
            0A:6E:F9:E0:1D:3F
        inet:
            |_
              ----------
              address:
                  10.0.0.87
              broadcast:
                  10.0.0.1
              label:
                  AWS PV Network Device #0
              netmask:
                  255.255.255.0
        up:
            True

real	0m0.906s
user	0m0.412s
sys	0m0.148s
```

**Comment by UtahDave** [comment] 2015-07-13 22:44
OK, I've tracked this down to an issue with git and the user the salt-minion is running as.

If I change the salt-minion service to run as my local administrator account the delay goes away. This jives with the delay going away when running as salt-call or when the minion is running in the terminal because in both those cases the salt-minion is running as the same user as the terminal.

I ran ProcessMonitor and as far as I and another salt engineer can tell from the flood of info, git is trying to do something that's timing out when the user is the "Local System" user account. The Local System user account isn't quite a full administrator.

I'm not sure what to do at this point. @jagardaniel can you test setting your salt-minion to log on as an actual administrator account and see if you get the same behavior?

Thanks!

**Comment by edvinerikson** [comment] 2015-07-14 14:54
Hi.
I'm on the same team as @jagardaniel.

Back then when we experienced this bug, we tried to run the minion in cmd (on the Admin account) and it did work as expected (Speed was normal).


However I tried running `git pull` today in CMD and PS as Local System and got the delay, so I think the bug is actually in Git itself.

```
PS C:\Users\Administrator\Desktop\git-test\nuclide> whoami
nt authority\system
PS C:\Users\Administrator\Desktop\git-test\nuclide> git --version
git version 1.9.2.msysgit.0
PS C:\Users\Administrator\Desktop\git-test\nuclide> Measure-Command {start-process git -argumentlist "pull" -wait}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 29
Milliseconds      : 808
Ticks             : 298085221
TotalDays         : 0,000345006042824074
TotalHours        : 0,00828014502777778
TotalMinutes      : 0,496808701666667
TotalSeconds      : 29,8085221
TotalMilliseconds : 29808,5221



PS C:\Users\Administrator\Desktop\git-test\nuclide>
```

Reproduce:
1. Start cmd as Local System. (I used the tools linked in this [answer](http://stackoverflow.com/a/78691/3329156))
2. Clone repo. (I used [Nuclide](https://github.com/facebook/nuclide) via https)
3. Run `git pull` in the new git repo.

**Comment by UtahDave** [comment] 2015-07-14 15:21
I've found a few other people running into similar issues:

Same behavior with PHP: http://serverfault.com/questions/702837/debug-slow-git-pull-operation-executed-by-the-local-system-account-on-a-window

Possibly a permissions checking issue: https://confluence.atlassian.com/display/STASHKB/Git+push+operations+extremely+slow+on+Windows

With a possible fix: https://support.microsoft.com/en-us/kb/2545833

Some other possible fixes: http://stackoverflow.com/questions/2835775/msysgit-bash-is-horrendously-slow-in-windows-7

I'm going to try some of these fixes later today. Let me know if you get a chance to try any as well.

Thanks!

**Comment by UtahDave** [comment] 2015-07-16 22:36
OK, at this point I'm quite sure this is a bug in git itself. I'm going to close this issue for now. Hopefully this will get fixed in git sometime soon.

Please feel free to comment here if you feel this should be reopened. I appreciate everyone's help testing.

**Closed by UtahDave** 2015-07-16 22:36 UTC
Labels: Beryllium, Bug, High Severity, P2, Platform, Triangle, Windows
