### ISSUE TITLE
2015.2 Unable to pass http auth to util.http from state.file

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#21917] opened 2015-03-23 21:55 UTC
Basic http auth for the following state is not passed to util.http resulting in error 401.

using requests_lib: True
os: Windows
```
file.managed:
  - source: https://user:password@site.com:8080/httpAuth/app/rest/builds/
id%3A25026/artifacts/content/public-web-2015-03-23-14-24-52-15849.zip
```

Note, I've captured url and auth in the trace log.  The username and password were stripped from the url and auth is set to None.
```
[TRACE   ] Request Headers: {'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept
': '*/*', 'User-Agent': 'python-requests/2.5.3 CPython/2.7.9 Windows/2012Server'}
[TRACE   ] Request Auth: None
[TRACE   ] using Requests library.
[TRACE   ] Requesting https://site.com:8080/httpAuth/app/rest/builds/id%3A25026/artifa
cts/content/public-web-2015-03-23-14-24-52-15849.zip
[INFO    ] Starting new HTTPS connection (1): site.com
[DEBUG   ] "GET /httpAuth/app/rest/builds/id%3A25026/artifacts/content/public-web-2015-03-23-14-24-5
2-15849.zip HTTP/1.1" 401 None
[DEBUG   ] Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 1528, in managed
    follow_symlinks)
  File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 3531, in manage_file
    sfn = __salt__['cp.cache_file'](source, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 348, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 152, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 595, in get_url
    stream=True
  File "C:\salt\bin\lib\site-packages\salt\utils\http.py", line 255, in query
    result.raise_for_status()
  File "C:\salt\bin\lib\site-packages\requests\models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized
```
```
           Salt: 2015.2.0
         Python: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by jfindlay** [comment] 2015-03-24 17:19
@deuscapturus, thanks for the report.  I've read over the `file.managed` state function and `file.manage_file` module function and it seems that neither support authentication for retrieving remote files.  This would definitely be a good thing to have.

**Comment by deuscapturus** [comment] 2015-03-24 18:08
@jfindlay Thanks for the followup.  In past versions of Salt I was able to place the username and password in the url of file.managed (at least in Linux).  Is this a limitation of Requests over urllib2?  Is this also broken on Linux for 2015.2?

**Comment by jfindlay** [comment] 2015-03-24 18:11
@deuscapturus, those are good questions.  If this worked before it is probably because we're moving away from requests, since it has caused many dependency problems.

**Comment by deuscapturus** [comment] 2015-03-25 06:59
The problems is here https://github.com/saltstack/salt/blob/develop/salt/fileclient.py#L593 .  salt.utils.http.query is called without passing kwargs for authentication.  But it does look like somebody prepared them to be sent here https://github.com/saltstack/salt/blob/develop/salt/fileclient.py#L589

**Comment by techhat** [comment] 2015-03-25 13:14
@deuscapturus this is fixed with #21983, for requests. It looks like there's still some work to do for urllib2 though.

**Comment by avanha** [comment] 2015-06-15 16:16
This issue re-surfaced for me again, in release 2015.05.0 (Lithium), even when using the requests implementation.  This time the problem is caused by the Auth data being overwritten in query, salt/util/http.py near line 201, by the following block:

```python
if username and password:
            auth = (username, password)
        else:
            auth = None
```

The code above the query mehod is already parsing the username and password form the url, and supplying an auth parameter in the call to the query method, only to have query method overwrite it.

I fixed it locally by changing the above to:

```python
    if (auth is None) and username and password:
        auth = (username, password)
    else
        auth = None
```

**Comment by avanha** [comment] 2015-06-16 00:46
Looking at my fix again, I don't think that's quite right... It should probably just be:

```python
if (auth is None) and username and password:
    auth = (username, password)
```

That way, if the caller to the query supplied an auth argument, it won't get stomped.

**Comment by deuscapturus** [comment] 2015-06-17 18:32
@avanha That works, here is how I implemented it.  You will still need to have requests_lib: True set in the minion config since urllib2 doesn't use the auth.

/usr/lib/python2.7/site-packages/salt/utils/http.py" line 203
```
    if (auth is None) and username and password:
        auth = (username, password)
#    else:
#        auth = None
```

**Comment by rallytime** [comment] 2015-09-11 21:42
Thanks for the fix here @deuscapturus! Since your fix has been merged, I am going to close go ahead and close this.

If this pops up again, please let us know and we'd be happy to reopen this issue. Thanks!

**Closed by rallytime** 2015-09-11 21:42 UTC
Labels: Bug, Execution Module, Medium Severity, P2, Regression, RIoT
