### ISSUE TITLE
beacon.present only works with built-in beacons

### ISSUE THREAD

**Issue by oz123** [saltstack/salt#38934] opened 2017-01-25 09:26 UTC
`beacon.present` only works with built-in beacons, and is not able to load custom beacons found in `_beacons`. 
I created a custom beacon to read the memory usage of a host, I put it `_beacons` restart both the minion and the master, and I got the following error:

```
 salt "m*1*" state.sls_id config_becons bootstrap                     
minion1.local:
----------
          ID: beacons_bla
    Function: beacon.present
        Name: memory
      Result: False
     Comment: Beacon memory does not exist
     Started: 10:56:00.240625
    Duration: 86.418 ms
     Changes:   

Summary for minion1.local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  86.418 ms
```

The config beacons id is:
```
config_beacons:
  beacon.present:
    - enable: True
    - name: memory
```

Again the problem is solved if I put the following in `/etc/salt/minion.d/beacons.conf`:
```
beacons:
  memory:
   - interval: 10

```

### Setup
setup mentioned here:
https://github.com/saltstack/salt/issues/38909

**Comment by Ch3LL** [comment] 2017-01-26 21:32
@oz123 thanks for opening this. I was able to replicate this.

Here is a docker container with the replication test case:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38934` (where /home/ch3ll/git/salt is a local cloned git repo of salt)
2. `salt-master -d; salt-minion -d`
3. `salt-call state.sls test -ldebug`

**Comment by jlayze** [comment] 2017-06-16 20:06
I'm also finding this effects `salt.beacons.add`

When trying to add a custom beacon with `beacons.add` I get the same error "Beacon {beacon_name} does not exist."  `beacon.present` is making a call to `beacons.add`, and it looks like this error is being generated from line 100, but I'm not sure how to take it any further.
```Python
 99: try:
100:     beacon_module = __import__('salt.beacons.' + name, fromlist=['validate'])
101:     log.debug('Successfully imported beacon.')
102: except ImportError:
103:     ret['comment'] = 'Beacon {0} does not exist'.format(name)
104:     return ret
```
The same Try block is also used in `beacons.modify`

**Comment by garethgreenaway** [comment] 2017-08-18 01:31
The issue is that the custom beacons aren't able to imported like the stock ones are.  Working on a fix to move the validation to a different spot, which should allow custom beacons to be handled with the module & state module.

**Comment by garethgreenaway** [comment] 2017-09-13 16:49
@oz123 I'm going to close this out since the PR with the fix was merged.  If the issue persists please feel free to re-open this issue.

**Closed by garethgreenaway** 2017-09-13 16:49 UTC
Labels: Beacon, Bug, Core, High Severity, P4, State Module
