### ISSUE TITLE
ubuntu 14.04 salt source package hosted on http://repo.saltstack.com is broken

### ISSUE THREAD

**Issue by ageorgop** [saltstack/salt#29608] opened 2015-12-10 21:32 UTC
When attempting to rebuild the salt source package located at http://repo.saltstack.com/apt/ubuntu/ubuntu14/2015.8/  I am getting the following error

```
dpkg-source -x salt_2015.8.3+ds-1.dsc 
gpgv: Signature made Tue 01 Dec 2015 09:54:42 PM UTC using RSA key ID DE57BFBE
gpgv: Can't check signature: public key not found
dpkg-source: warning: failed to verify signature on ./salt_2015.8.3+ds-1.dsc
dpkg-source: error: file ./salt_2015.8.3+ds-1.debian.tar.gz has size 18396 instead of expected 18422
```

**Comment by jfindlay** [comment] 2015-12-11 17:59
@ageorgop, thanks for the report.

**Comment by edgan** [comment] 2015-12-22 17:33
I have a like issue where I try to say apt-get source salt, and it tells me no such package. I am trying to use "deb-src http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main".

**Comment by dmurphy18** [comment] 2016-03-11 21:46
@ageorgop @edgan I apologize for the sources not working when trying to obtain them from repo.saltstack.com.  Unfortunately due to backlog of issues this is not a high priority since the source code is freely available from github, both saltstack/salt and saltstack/salt-pack (which is used to build salt and its dependencies), both are open-source.

The focus has been on getting support for platforms, for example: wheezy is just  now available. As the package build automation framework matures, it is hoped to have the sources issue fixed along with 32-bit support.

**Comment by dmurphy18** [comment] 2016-09-28 22:11
@ageorgop @edgan Could you retry with the latest release salt 2016.3.3. I just tried on Debian 7 & 8, Ubuntu 16.04, 14.04 and 12.04 and was successful in downloading the sources for salt-minion.

I first had to make sure that **dpkg-dev** and **apt-transport-https** were installed.

On Debian 7 and 8, I had no problems with the public key, since as part of the install process it to wget the public key and pass it to 'apt-key add'.  However on Ubuntu platforms, I had to additionally add the key to my public keys, that is: gpg --import SALTSTACK-GPG-KEY.pub.

**Comment by dmurphy18** [comment] 2016-12-07 19:24
@ageorgop Would like to close this since the problem is not occurring with the current version, unless you are still experiencing the issue.

**Comment by ageorgop** [comment] 2016-12-08 20:20
feel free to close.  I cannot test this unfortunately so I will just take your word for it :+1:

**Closed** 2016-12-08 20:44 UTC
Labels: Bug, High Severity, Info Needed, P4, Packaging, Platform
