### ISSUE TITLE
documentation: make sure examples are ASCII

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#7976] opened 2013-10-19 07:20 UTC
I've gotten this error when I copy/pasted examples from the documentation PDF:

```
SyntaxError: Non-ASCII character '\xe2' in file testping.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

This particular example was from the code in chapter `44.9 Examples of Salt Modules`.
But perhaps this is an impossible request if you want to keep syntax-coloring...

**Comment by jacobhammons** [comment] 2015-10-07 12:23
going to close this, copying and pasting from the PDF works fine in my tests so something in the toolchain fixed this.

**Closed by jacobhammons** 2015-10-07 12:23 UTC
Labels: Documentation

**Comment by Mrten** [comment] 2015-10-07 13:12
I would disagree most vehemently: The first example I copy/pasted from https://docs.saltstack.com/en/pdf/Salt-2015.5.0.pdf was completely hosed wrt. formatting:
```
couchdb.db:
'
salt
'
couchdb.url:
'
http://salt:5984/
'
```
(spurious newlines)

Or:
```
alternative.carbon:
host: <server IP or hostname>
port: <carbon port>
skip_on_error: True
mode: (pickle|text)
```
(missing indent)

**Comment by jacobhammons** [comment] 2015-10-07 13:54
Hi @Mrten, I closed this based on the "Non-ASCII character" error reported in the title no longer occurring, but reading more closely it does appear this morphed to cover some other formatting issues. However, those other issues don't seem to be caused by formatting in the Salt docs but are more related to sphinx-doc.

In my tests, I'm using the Chrome PDF viewer and pasting into MacVim, and all newlines come through fine with no extra newlines. I also tested in Adobe Reader and  TextEdit with the same results. I can confirm that tabs are not copied though, if you look when you highlight the text the PDF does not contain spaces or tabs for indents.

We can take a look at the sphinx-doc project to see if there is a way to get the tabs to show up in the PDF, but I'm going to leave this closed since there isn't really anything we can do about this in the Salt project.
