### ISSUE TITLE
Syntax checking

### ISSUE THREAD

**Issue by j0nes2k** [saltstack/salt#802] opened 2012-03-01 09:49 UTC
When a salt state contains YAML syntax errors, it is quite hard to find these errors at the moment. It would be great to have a basic syntax check (validation agains a schema) and/or references check (e.g. do the references given in require-statements really exist).

**Comment by v6** [comment] 2015-01-14 22:13
I'm coming from Puppet, myself. I would have preferred to install SaltStack, but everyone and their mother was using it at my last company. 

Anyway, there were a lot of things that they put together to make life easier on non-expert users. These almost made up for the severe limitations of the Puppet system. 

Anyway, one of the things I liked best was `puppet validate`. 

It saved me a lot of time. 

Why no `salt validate`?

**Comment by thatch45** [comment] 2015-01-14 22:23
While it is not as convenient the 

```
salt-call state.show_highstate
```

Can compile the sls files and at least show you the errors. It is primarily because the sls files can be generated on the minions, so always getting the right data from Jinja can be tricky

**Comment by v6** [comment] 2015-01-14 23:37
OK.

I just wish there was a validation checker that could point me to the
location in the files, specifically.

IDEs have this, and I'm going to be installing one for Sublime Text
and Pycharm.

As to the generation, isn't it deterministic?


On 1/14/15, Thomas S Hatch <notifications@github.com> wrote:
> While it is not as convenient the
>
> ```
> salt-call state.show_highstate
> ```
>
> Can compile the sls files and at least show you the errors. It is primarily
> because the sls files can be generated on the minions, so always getting the
> right data from Jinja can be tricky
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt/issues/802#issuecomment-70004550


-- 
Nate B.

**Comment by v6** [comment] 2015-01-14 23:42
---------- Forwarded message ----------
From: Nate B <nathan@basanese.com>
Date: Wed, 14 Jan 2015 15:37:25 -0800
Subject: Re: [salt] Syntax checking (#802)
​​
To: saltstack/salt <
reply@reply.github.com
>
Cc: saltstack/salt <salt@noreply.github.com>, Nathan Dataguake Basanese <
github.com-v6@basanese.com>, an.lin@wdc.com

OK.

I just wish there was a validation checker that could point me to the
location in the files, specifically.

IDEs have this, and I'm going to be installing one for Sublime Text
and Pycharm.

As to the generation, isn't it deterministic?


On 1/14/15, Thomas S Hatch <notifications@github.com> wrote:
> While it is not as convenient the
>
> ```
> salt-call state.show_highstate
> ```
>
> Can compile the sls files and at least show you the errors. It is
primarily
> because the sls files can be generated on the minions, so always getting
the

**Comment by damon-atkins** [comment] 2015-01-15 01:03
http://docs.saltstack.com/en/latest/ref/states/testing.html 
It would be nice if you could setup a environment which defaults to testing only (dry-run).

**Comment by pcn** [comment] 2015-08-18 15:59
I've got an alternate take on this at https://github.com/librato/salt-state-test.  It's a bit rough, but feedback from someone beside me is appreciated.

**Comment by figtrap** [comment] 2015-10-24 01:30
We really need something like this ...

**Comment by damon-atkins** [comment] 2016-02-25 05:02
Need a tool which pulls in the pillar data, either a file or a list of files, directory and then give it a state file, and then it prints out the final state/catalog/manifest.   It can work outside of salt.   In fact it would be better if it did, so the checking can be perform before committing changes.

salt-call state.dry-run <grain file> <local pillar dir> <local state files>
salt-call state.process-state-only <grain file> <local pillar dir> <local state files>

**Comment by thatch45** [comment] 2016-02-25 06:30
I recently added the mocked option to the state calls:
Salt-call state.high state mocked=True
This does the full state run just without executing the states, so everything compiles with the pillar etc.

**Comment by pcn** [comment] 2016-02-25 06:48
@thatch45 where's the commit/branch with that in it?

**Comment by pcn** [comment] 2016-02-25 06:49
@damon-atkins the repo I pointed to early does something like what you're asking, but the pillar and the grains can each only be one file.

**Comment by thatch45** [comment] 2016-02-25 06:55
It is in 2015.8.7

**Comment by tampakrap** [comment] 2016-02-25 11:43
@thatch45 Can you explain please how is that different from test=True?

**Comment by thatch45** [comment] 2016-02-25 16:46
test=True runs in no-op mode and checks the state of the system
mocked=True runs the state runtime and resolves all requisites but it does not run any states on the target system
state.show_highstate just runs the data compiler and returns the data tht the runtime would execute with

Basically, show_highstate does syntax checks, mocked does syntax + runtime (requisites and ordering) checks, and test=True does a full state run with checks to see if anything will be changed with an actual state run

So it is basically just stopping the process at certain points to give you a clear representation of what your states are and will do

**Comment by figtrap** [comment] 2016-02-25 16:53
Oh what I really want is some sort of IDE for salt development that would
do things like autofill pillars and variables when you're writing jinja,
linting the yaml and things like that. There is just so much wasted time
with typos. But the "mocked" feature is much needed and appreciated.

Tim Kelley

**Comment by thatch45** [comment] 2016-02-25 16:54
Oh, yes, what you are describing would be great

**Comment by damon-atkins** [comment] 2016-02-26 00:56
One of the issue I was hoping this would resolve is the error messages not indicating where an issue is.   For example JINJA processing only says: 
Rendering SLS 'base:iscdhcp' failed: Jinja variable 'list object' has no attribute 'name'
Rendering SLS 'base:iscdhcp' failed: Jinja variable 'dict object' has no attribute 'path'
The problem is 'base:iscdhcp' as a whole can contain multiple name and path, which one is it in the structure. (2015.5.8)

**Comment by gravyboat** [comment] 2016-07-14 16:38
I'm just going to bump this again. People keep running into this issue of not being able to syntax check without doing a run, which doesn't provide great errors. There really needs to be a built in utility within salt to at least confirm the yaml/jinja is legit (even if it does not check against the pillar, though that would be nice). This has been a 'want' for both new and existing users for over 4 years now.

**Comment by jowolf** [comment] 2016-07-20 00:19
bump - I wrote a custom yaml module (for another project) to trace yaml compiiles and line numbers, for example - so when it died you could see where it was last.

It was crude, and used globals for state like the line number, but it's an idea

**Comment by RobotLimeLtd** [comment] 2016-07-20 13:22
The nearest you might get is the following, however it will only work for very simple Salt setups, and only on a server that has Salt Minion installed.  Assuming your source repo contains both "salt" and "pillar" directories, each with a top.sls in them... you could run:

`salt-call state.highstate --file-root=$PWD/salt --pillar-root=$PWD/pillar --local --retcode-passthrough mocked=True`

However, if you have anything more exotic, such as an external pillar directory, then you're out of luck.

**Comment by gravyboat** [comment] 2016-07-20 16:11
@RobotLimeLtd Yeah we've discussed that as an option before, and it's not a significantly satisfactory option for anyone I've talked to. Thanks for noting it though!

**Comment by chrismcmacken** [comment] 2017-03-11 17:38
Do salt states have a documented grammar that is used to parse them?

**Comment by pcn** [comment] 2017-03-11 18:00
@chrismcmacken have you read through https://docs.saltstack.com/en/latest/ref/renderers/ ?

**Comment by chrismcmacken** [comment] 2017-03-11 18:12
@pcn I hadn't, salt supports a lot more renderers than I thought. Still though, if it gets parsed it must be against some set of rules. I'm sure it's a tough problem to solve, otherwise it would have been solved already, just thought I'd ask and bump the thread.

**Comment by pcn** [comment] 2017-03-11 19:17
It doesn't seem to support a grammar so much as a list of existing and extensible grammars that map directly to a list of python dictionaries.

**Comment by soostdijck** [comment] 2017-08-25 11:51
Bump as well. Has anyone made progress on this? 
I'm still hoping that I'll be able to check syntax via commit hooks properly.

**Comment by JensRantil** [comment] 2017-08-25 13:12
Just wanted to share how we've created a workaround for syntax checking in our CI pipeline: In our `top.sls` files we've added a standardized way of adding example minion names:

    # CI example: my-minion-name
    'my-minion-*':
      - some.state

We then have a script that extracts all the example minion names (`salt-dry-run.sh`) for each minion name calls the script `salt-dry-run-single.sh` with the first (and only) parameter being the minion name.

You can find the code here: https://gist.github.com/JensRantil/c8757d607b379d3256299fd32a373a35

Obviously, this doesn't help with local development, but if you are for example using Github Pull Request you could add this as a CI step for this. Hope this makes the lives easier for some people.

**Comment by wyardley** [comment] 2018-01-12 21:36
Agree that this would be very useful, something like `puppet parser validate` for Puppet (to do at least a basic syntax check of the code itself.
Obviously, for YAML itself, it's not hard to just add commit hooks using yamllint or similar.

**Comment by wyardley** [comment] 2018-07-08 18:55
Just as a heads up, while `mocked=True` doesn't error, `mock=True` seems to be the correct arg now.

**Comment by Oloremo** [comment] 2020-01-10 13:17
not stale

**Comment by xyzst** [comment] 2021-03-02 15:15
I am interested in a syntax validator for salt that works on your local machine. Is there any progress on this?

**Comment by mchugh19** [comment] 2021-03-02 16:22
Not a solution, but there is a [salt-lint](https://github.com/warpnet/salt-lint) project now to look over yaml based sls files. For a CI pipeline, between that and rendering states to ensure salt can read them, our use cases are covered.

**Comment by raddessi** [comment] 2021-03-04 17:44
> Not a solution, but there is a [salt-lint](https://github.com/warpnet/salt-lint) project now to look over yaml based sls files. For a CI pipeline, between that and rendering states to ensure salt can read them, our use cases are covered.

I have been using this for a while and it does catch many things but better validation and error reporting is still a good ask since there are quite a few cases it won't catch.

**Comment by ITJamie** [comment] 2022-01-27 10:32
one example.
I had a user accidentally modify the following
```
  'hostname':i
    - some.sls.path
```
they added a charter after the hostname key in the top file. 
this was actually hard to track down
salt-lint saw no issue with this.
its obviously invalid yaml, but salt-lint was fine with it.
salt minions and master obviously wernt happy. but debug lines on both did not point to the specific line in the pillar top file with the issue. this was the output from any pillar or state command. pretty useless.
```
    ----------
    _errors:
        - Rendering Primary Top file failed, render error:
          could not find expected ':'
```

**Comment by MartinEmrich** [comment] 2022-11-16 11:16
Similar issue here, like many times. I just get the message: `[CRITICAL] Rendering SLS 'base:xxx.yy' failed: could not find expected ':'`. I am staring on that file for 30 minuted now, and I cannot find anything wrong.
salt-lint claims no errors, and as it is jinja with runtime-expanded variables, I cannot locally test with a regular YAML parser.

Often we don't need a perfect hint on what we have to fix, but a pointer to the line number or some context would help.

Is there a way to have the salt master do the jinja-templating, and give me the final rendered Should-Be-YAML-document?

**Comment by notpeter** [comment] 2022-11-16 14:03
> Is there a way to have the salt master do the jinja-templating, and give me the final rendered Should-Be-YAML-document?

Yes. state.show_sls and state.show_top

https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.state.html

**Comment by MartinEmrich** [comment] 2022-11-16 16:33
@notpeter thanks, but `state.show_top` shows only the state top, no issues there. `state.show_sls` on the relevant sls "xxx.yy" gives me the same error message without a line number, just as `state.show_highstate` or `state.apply`. The minion log also only containts that error message.

**Comment by notpeter** [comment] 2022-11-16 18:46
I don't use salt professionally anymore so I'm a bit out of practice. IIRC running salt or salt-call with `-l debug` or god forbid `-l trace` may show you enough context to help track it down. Often it's as simple as something in your jinja variables containing a colon or other special YAML characters: `:|[]{}<>-#?!,"'` etc which gets the parser into a funky state with a terrible error message. Good luck!

**Comment by MartinEmrich** [comment] 2022-11-17 08:45
Thanks! `salt-call -l debug state.show_highstate` produced the rendered Jinja among the debug output, which I could then run through a yaml parser again.
In the end, there was a "´" character hiding behind a jinja statement...🤦🏽‍♂️

**Comment by whytewolf** [comment] 2023-08-29 16:01
@MartinEmrich there are other methods now for showing rendered jinja. such as slsutil.renderer

```
root@salt00:/srv/salt/tests# salt-call slsutil.renderer salt://tests/json_q.sls default_renderer=jinja
local:
    ['a', 'c']
root@salt00:/srv/salt/tests# cat json_q.sls
{{
{"machines": [
  {"name": "a", "state": "running"},
  {"name": "b", "state": "stopped"},
  {"name": "c", "state": "running"}
]} | json_query("machines[?state=='running'].name") }}
```

there is also a built in yaml linter now. 

```
root@salt00:/srv/salt/tests# salt-call yaml.lint salt://tests/test.yaml
local:
    ----------
    problems:
        |_
          ----------
          column:
              11
          comment:
              syntax error: expected '<document start>', but found '<scalar>' (syntax)
          level:
              error
          line:
              1
    source:
        'hostname':i
          - some.sls.path
```

**Comment by whytewolf** [comment] 2023-08-30 17:23
I'm going to go ahead and close this issue. while there is not a generic salt lint within salt there is one that is wildly available called salt-lint. and there is a yaml lint as well as ways of rendering jinja into yaml for debugging. as well as another ticket that deals more with adding a salt-lint within salt. https://github.com/saltstack/salt/issues/5378

at this time anything further should get it's own ticket that is more direct and less open ended.

**Closed by whytewolf** 2023-08-30 17:23 UTC
Labels: Feature, Core

**Comment by kurtrwall** [comment] 2024-10-01 16:03
I'm sad to come across the closure, but understand that `salt-lint` is available for use. Is there any way saltproject could provide some better rules or config? The only linting that ever comes up for me is some pretty basic stuff, e.g. `File modes should always be encapsulated in quotation marks` and I'll never get something like `The require statement in state 'deploy helios' in SLS 'apps.helios' needs to be formed as a list`.

**Comment by ITJamie** [comment] 2024-10-01 17:32
Id also point out that salt-lint isnt being maintained. There are open pr's. Ive tried contacting the creator with no response
