### ISSUE TITLE
DeprecationWarning: The "osmajorrelease" will be a type of an integer.

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#35972] opened 2016-08-31 23:47 UTC
### Description of Issue/Question

I am seeing this warning message after 6.3.2 to 6.3.3 upgrade

### Setup
 salt-run -t 60 manage.down

### Steps to Reproduce Issue

[root@salt01 ~]# salt-run -t 60 manage.down
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.
### Versions Report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.3.8
         Jinja2: 2.8
        libgit2: 0.21.0
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by ndobbs** [comment] 2016-09-01 00:54
+1 I'm running into this, too. I am filtering on the grain 'osmajorrelease' in several of my states but do not see that being the issue here. 

```
alt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-59-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Sakorah** [comment] 2016-09-01 12:56
Hi,

I'm seeing this messages as well. I certainly do not use this grain in my environment and still get this message. Is this "works as designed" then?

**Comment by kkoppel** [comment] 2016-09-02 07:05
Same here. I believe version 2016.3.3 always shows this warning whenever the grains data is compiled.

This warning already got removed in 45a12ccaf092ca16e2b196a2440b7cb117622809. Would be really great if this could be back-ported to 2016.3.

**Comment by Ch3LL** [comment] 2016-09-02 23:41
Looks like we need to remove this warning in 2016 as well since it will be included in the release notes for nitrogen. Thanks for the heads up guys.

**Comment by rallytime** [comment] 2016-09-06 15:24
Thanks @tjyang for filing this and to @kkoppel for pointing to the fix in develop. I've submitted #36068 to fix this.

**Comment by willneumob** [comment] 2016-09-07 09:29
+1 for realeasing under 2016.3.

**Comment by cachedout** [comment] 2016-09-09 12:49
It will be in the next release of 2016.3. Thanks all.

**Closed by cachedout** 2016-09-09 12:49 UTC
Labels: 2016.3.4, Blocker, Bug, Carbon, Core, Fixed Pending Verification, Grains, Medium Severity, P1, TEAM Core

**Comment by tjyang** [comment] 2016-09-09 13:13
Thanks for the quick remedy.
