### ISSUE TITLE
State runs involving watch_in or extending break on 2015.8.4

### ISSUE THREAD

**Issue by Supermathie** [saltstack/salt#30820] opened 2016-02-02 18:06 UTC
Environment: rackspace, Ubuntu 14.04, salt packages from `http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest`

Not 100% sure why it's breaking, but the following statefile now causes an exception on a 2015.8.4 minion:

```
$ cat test.sls 
# vim:syn=yaml sw=2 ts=2 et:
# state file to test breakage on 2015.8.4
salt_minion_svc:
  service.running:
    - name: salt-minion

/etc/salt/minion.d/test.conf:
  file.managed:
    - mode: '0444'
    - contents: ''
    - watch_in:
      - service: salt-minion
```

2015.8.3, it works:

```
$ sudo salt host1 state.apply test
host1:
----------
          ID: /etc/salt/minion.d/test.conf
    Function: file.managed
      Result: True
     Comment: File /etc/salt/minion.d/test.conf updated
     Started: 17:44:13.062990
    Duration: 6.465 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0444
----------
          ID: salt_minion_svc
    Function: service.running
        Name: salt-minion
      Result: True
     Comment: Service restarted
     Started: 17:44:13.106278
    Duration: 40.803 ms
     Changes:   
              ----------
              salt-minion:
                  True

Summary for host1
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2

$ sudo salt host1 grains.item saltversion
host1:
    ----------
    saltversion:
        2015.8.3
```

But on 2015.8.4 it fails:

```
$ sudo salt host2 state.apply test
host2:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1071, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 320, in apply_
        return sls(mods, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 757, in sls
        ret = st_.state.call_high(high_)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2118, in call_high
        high, req_in_errors = self.requisite_in(high)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1528, in requisite_in
        req_in_high, req_in_errors = self.reconcile_extend(high)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1248, in reconcile_extend
        if state not in high[name]:
    KeyError: 'salt-minion'

$ sudo salt host2 grains.item saltversion
host2:
    ----------
    saltversion:
        2015.8.4
```

**Comment by gtmanfred** [comment] 2016-02-02 18:22
We are seeing the same thing when we directly use extend

https://docs.saltstack.com/en/latest/ref/states/extend.html

So i bet these two are related, cause it looks like watch_in uses extend to extend the other state.

```
extend:
    uwsgi:
        service:
            - listen:
                - file: api_config
```

results in this error in 2015.8.4

```
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 335, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 53, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 568, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3141, in call_highstate
    return self.state.call_high(high)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2113, in call_high
    high, ext_errors = self.reconcile_extend(high)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1248, in reconcile_extend
    if state not in high[name]:
KeyError: 'uwsgi'
```

**Comment by terminalmage** [comment] 2016-02-02 20:21
Git bisect suggests that 6d747df5db66be91283f1244dfcc6c1ad46f4137 broke this, I'm looking closer now.

**Comment by gtmanfred** [comment] 2016-02-02 20:22
```
(venv)root@reports:~/salt# git bisect log
# bad: [1c6c394d0ed51db613938dbfa4db6002eeb87a87] Merge pull request #30615 from jfindlay/2015.8
# good: [345206b68e97465c18450227e21adb888dd87358] Merge pull request #29173 from jfindlay/2015.8
git bisect start 'v2015.8.4' 'v2015.8.3'
# bad: [896655602e59ac01145a45d8f914ba695ab5329a] Merge pull request #30064 from rallytime/fix-30045
git bisect bad 896655602e59ac01145a45d8f914ba695ab5329a
# bad: [9673fd093745ac028c7865b6a92dc8ea60713962] Merge remote-tracking branch 'upstream/2015.5' into merge-forward-2015.8
git bisect bad 9673fd093745ac028c7865b6a92dc8ea60713962
# bad: [17d80c051ab6a0af696b2ac85cbd8d9c100148c0] Merge pull request #29334 from rallytime/bp-29237
git bisect bad 17d80c051ab6a0af696b2ac85cbd8d9c100148c0
# bad: [dbf7755aa2fe222e236cef7682a7fa89283a73fc] Merge pull request #29282 from cachedout/fix_29279
git bisect bad dbf7755aa2fe222e236cef7682a7fa89283a73fc
# good: [1efe484309a5c776974e723f3da0f5181f4bdb86] Merge pull request #29244 from isbm/isbm-zypper-products
git bisect good 1efe484309a5c776974e723f3da0f5181f4bdb86
# good: [8cc1d8de469e7c6b2f3d3dad08d251f0da32eda3] Merge pull request #29215 from rallytime/bp-29192
git bisect good 8cc1d8de469e7c6b2f3d3dad08d251f0da32eda3
# bad: [d651d7167e4f3ac737409e47ba876e2a24318ee7] Merge pull request #29067 from jacksontj/2015.8
git bisect bad d651d7167e4f3ac737409e47ba876e2a24318ee7
# bad: [64e439cda2178521845ba8f12f71001aafaa5ea0] Add test for infinite recursion with sls prerequisites
git bisect bad 64e439cda2178521845ba8f12f71001aafaa5ea0
# bad: [d6876820169faa096f924901233439c9b429e223] No reason to continuously resolve the k, v pair here since it doesn't change in the inner loop
git bisect bad d6876820169faa096f924901233439c9b429e223
# bad: [6d747df5db66be91283f1244dfcc6c1ad46f4137] Correctly resolve requisite_in for SLS requisites
git bisect bad 6d747df5db66be91283f1244dfcc6c1ad46f4137
# first bad commit: [6d747df5db66be91283f1244dfcc6c1ad46f4137] Correctly resolve requisite_in for SLS requisites
```
I got the same

**Comment by blbradley** [comment] 2016-02-02 20:39
This is happening in Debian Jessie also. Installed from `repo.saltstack.com`.

**Comment by terminalmage** [comment] 2016-02-02 20:52
Fixed in https://github.com/saltstack/salt/pull/30833

**Comment by blbradley** [comment] 2016-02-02 20:54
Can we get a fix in the package repos ASAP?

I hate using ASAP. :grinning:

**Comment by gtmanfred** [comment] 2016-02-02 21:01
confirmed that #30833 fixes this for me

**Comment by terminalmage** [comment] 2016-02-02 21:05
@blbradley We're on it. Sorry for the inconvenience.

**Comment by terminalmage** [comment] 2016-02-02 21:35
Integration test added in https://github.com/saltstack/salt/pull/30835

**Comment by terminalmage** [comment] 2016-02-03 00:13
2015.8.5 has been tagged and packages will be available soon. Marking this as closed.

**Closed by terminalmage** 2016-02-03 00:13 UTC
Labels: Bug, Core, High Severity, P2, Regression, State Compiler, TEAM Core

**Comment by gtmanfred** [comment] 2016-02-03 00:14
Thanks! <3 love y'all

**Comment by arthurlogilab** [comment] 2016-02-10 11:19
got hit by this too. Thanks for the quick update.
