### ISSUE TITLE
Resolve master address on reconnection attempt

### ISSUE THREAD

**Issue by diegows** [saltstack/salt#15122] opened 2014-08-20 20:48 UTC
I discovered that salt-minion doesn't resolve the IP address of the Master on reconnect. I've changed the IP address of master and updated the DNS record but the minion never get connected again. I had to restart all of them.

**Comment by tjstansell** [comment] 2015-03-07 01:03
This looks like the same issue as #10032, fyi...

**Comment by sjmh** [comment] 2015-07-07 18:08
You can workaround this by switching your master_type to 'failover' and listing your master name twice.  Also make sure you have your master_alive_interval set.

```
master:
  - salt.service.consul
  - salt.service.consul

master_type: failover
master_alive_interval: 30
```

I've tested this setup with a Consul setup that has salt registered as a service.  Once the DNS changes, it takes a bit, but the next name is resolved upon the failover and the new IP is used.

**Comment by jfindlay** [comment] 2015-10-13 18:22
This is a duplicate of #10032.

**Closed by jfindlay** 2015-10-13 18:22 UTC
Labels: Bug, Core, Duplicate, High Severity, P4
