### ISSUE TITLE
Comment: Source file not found in saltenv 'base'

### ISSUE THREAD

**Issue by avabraxas** [saltstack/salt#56684] opened 2020-04-17 15:00 UTC
### Description of Issue
Hello,

i'm trying to use the filemanagement fuction on Salt but I have this error all the time.
Strange thing that I make a class working but when I'm triying to do it for this new class is not working...

### Setup
sssd.sls:

sssd_config:
  file.managed:
  - user: root
  - group: root
  - mode: 600
  - names:
    - '/etc/sssd/sssd.conf':
      - source: 'salt://sssd/sssd.conf'

### Steps to Reproduce Issue
lnp03:/srv/salt # salt -l all 'lnp07' state.apply sssd
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/py26-compat-salt.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/py26-compat-salt.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/susemanager.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/susemanager.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/susemanager_engine.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/susemanager_engine.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/virtualization-host-formula.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/virtualization-host-formula.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: lnp03
[DEBUG   ] Missing configuration file: /root/.saltrc
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/py26-compat-salt.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/py26-compat-salt.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/susemanager.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/susemanager.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/susemanager_engine.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/susemanager_engine.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/virtualization-host-formula.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/virtualization-host-formula.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: lnp03
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'lnp03_master', 'tcp://*********:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://********:4506
[DEBUG   ] Trying to connect to: tcp://********:4506
[TRACE   ] Inserted key into loop_instance_map id 140705822583216 for key ('/etc/salt/pki/master', 'lnp03_master', 'tcp://*********:4506', 'clear') and process 13841
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[TRACE   ] func get_cli_event_returns()
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/7a/ac83ba03a14ed6ae8df5ffe6ebd749f147f3031b6bb94e49abd9bc7b918ce7/.minions.p
[DEBUG   ] get_iter_returns for jid 20200417165132404645 sent to {'lnp07'} will timeout at 16:53:32.411318
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() received = {'data': {'jid': '20200417165132404645', 'tgt_type': 'glob', 'tgt': 'lnp07', 'user': 'root', 'fun': 'state.apply', 'arg': ['sssd'], 'minions': ['lnp07'], 'missing': [], '_stamp': '2020-04-17T14:51:32.405344'}, 'tag': 'salt/job/20200417165132404645/new'}
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() received = {'data': {'cmd': '_return', 'id': 'lnp07', 'success': False, 'return': {'file_|-sssd_config_|-/etc/sssd/sssd.conf_|-managed': {'changes': {}, 'pchanges': {}, 'comment': "Source file salt://sssd/sssd.conf not found in saltenv 'base'", 'name': '/etc/sssd/sssd.conf', 'result': False, '__sls__': 'sssd', '__run_num__': 0, 'start_time': '16:51:32.793012', 'duration': 33.384, '__id__': 'sssd_config'}}, 'retcode': 2, 'jid': '20200417165132404645', 'fun': 'state.apply', 'fun_args': ['sssd'], 'out': 'highstate', '_stamp': '2020-04-17T14:51:32.831813'}, 'tag': 'salt/job/20200417165132404645/ret/lnp07'}
[DEBUG   ] jid 20200417165132404645 return from lnp07
[DEBUG   ] return event: {'lnp07': {'ret': {'file_|-sssd_config_|-/etc/sssd/sssd.conf_|-managed': {'changes': {}, 'pchanges': {}, 'comment': "Source file salt://sssd/sssd.conf not found in saltenv 'base'", 'name': '/etc/sssd/sssd.conf', 'result': False, '__sls__': 'sssd', '__run_num__': 0, 'start_time': '16:51:32.793012', 'duration': 33.384, '__id__': 'sssd_config'}}, 'out': 'highstate', 'retcode': 2, 'jid': '20200417165132404645'}}
[DEBUG   ] LazyLoaded highstate.output
[TRACE   ] data = {'lnp07': {'file_|-sssd_config_|-/etc/sssd/sssd.conf_|-managed': {'changes': {}, 'pchanges': {}, 'comment': "Source file salt://sssd/sssd.conf not found in saltenv 'base'", 'name': '/etc/sssd/sssd.conf', 'result': False, '__sls__': 'sssd', '__run_num__': 0, 'start_time': '16:51:32.793012', 'duration': '33.384 ms', '__id__': 'sssd_config'}}}
lnp07:
----------
          ID: sssd_config
    Function: file.managed
        Name: /etc/sssd/sssd.conf
      Result: False
     Comment: Source file salt://sssd/sssd.conf not found in saltenv 'base'
     Started: 16:51:32.793012
    Duration: 33.384 ms
     Changes:

Summary for lnp07
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  33.384 ms
[TRACE   ] _get_event() waited 0 seconds and received nothing
[DEBUG   ] jid 20200417165132404645 found all minions {'lnp07'}
[DEBUG   ] Closing IPCMessageSubscriber instance
ERROR: Minions returned with non-zero exit code

### Versions Report
salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.10 (default, Dec 19 2019, 15:48:40) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-197.34-default
         system: Linux
        version: Not Installed

**Comment by Akm0d** [comment] 2020-04-17 19:09
This looks like a duplicate of https://github.com/saltstack/salt/issues/56624

**Closed** 2020-04-23 14:18 UTC
Labels: Bug, Core, P1, State Module
