### ISSUE TITLE
SALT.STATES.BOTO_ELB register_instances error

### ISSUE THREAD

**Issue by HeathNaylor** [saltstack/salt#30843] opened 2016-02-03 00:59 UTC
my init.sls
```
add-instances:
  boto_elb.register_instances:
    - name: staging-elb
    - instances:
      - Salt-Minion-1
      - Salt-Minion-2
```

Generates this error in the minion log
```
2016-02-03 00:55:15,548 [salt.state       ][INFO    ][24611] Executing state boto_elb.register_instances for staging-elb
2016-02-03 00:55:15,549 [salt.state       ][ERROR   ][24611] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/boto_elb.py", line 384, in register_instances
    lb = __salt__['boto_elb.exists'](name, region, key, keyid, profile)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_elb.py", line 101, in exists
    conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
  File "/usr/lib/python2.7/dist-packages/salt/utils/boto.py", line 176, in get_connection
    keyid, profile)
  File "/usr/lib/python2.7/dist-packages/salt/utils/boto.py", line 91, in _get_profile
    if not region and __salt__['config.option'](service + '.region'):
NameError: global name '__salt__' is not defined
```

**Comment by jfindlay** [comment] 2016-02-03 06:30
@HeathNaylor, thanks for reporting.  This seems to be a duplicate of #30808.

**Closed by jfindlay** 2016-02-03 06:30 UTC
Labels: Duplicate

**Comment by rallytime** [comment] 2016-02-03 18:37
@HeathNaylor Can you test the following fix for me in `__virtual__()` function in the `salt/modules/boto_elb.py` file and let me know what your result is?
```
diff --git a/salt/modules/boto_elb.py b/salt/modules/boto_elb.py
index 46e489a..a207f85 100644
--- a/salt/modules/boto_elb.py
+++ b/salt/modules/boto_elb.py
@@ -86,7 +86,7 @@ def __virtual__():
     '''
     if not HAS_BOTO:
         return False
-    __utils__['boto.assign_funcs'](__name__, 'elb', module='ec2.elb')
+    __utils__['boto.assign_funcs'](__name__, 'elb', module='ec2.elb', pack=__salt__)
     return True
```
