### ISSUE TITLE
Gitfs causes random file not found with files in roots-folder

### ISSUE THREAD

**Issue by MakaHost** [saltstack/salt#21728] opened 2015-03-17 08:41 UTC
Hey,

we activated GitFS a few days ago and are now experiencing issues when deploying files to multiple-servers that are not located in git.

Example-output when executing the state:
```
www0-dus:
----------
          ID: /appdata/www/config/OrchestraConfigDUS.php
    Function: file.managed
      Result: True
     Comment: File /appdata/www/config/OrchestraConfigDUS.php is in the correct state
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 1
Failed:    0


www1-dus:
----------
          ID: /appdata/www/config/OrchestraConfigDUS.php
    Function: file.managed
      Result: False
     Comment: Source file salt://webserver/OrchestraConfigDUS.php not found
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
```

Output in the master-log:
```
OSError: [Errno 2] No such file or directory: '/appdata/salt/cache/master/gitfs/75248c36b09f8955bb05d9e2509b788f/update.lk'
2015-03-17 09:05:09,126 [salt.master                                ][ERROR   ] Error in function _file_hash:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/master.py", line 1336, in run_func
    ret = getattr(self, func)(load)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 423, in file_hash
    fnd = self.find_file(load['path'], load['saltenv'])
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 377, in find_file
    fnd = self.servers[fstr](path, saltenv, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/gitfs.py", line 1353, in find_file
    return fnd
  File "/usr/local/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/gitfs.py", line 916, in _aquire_update_lock_for_repo
    yield
  File "/usr/local/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/gitfs.py", line 932, in wait_for_write_lock
    os.remove(filename)
```

version-report of salt-master:
```
 Salt: 2014.7.2
         Python: 2.7.9 (default, Mar  4 2015, 14:41:42)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

The file we are trying to deploy is not within the gitfs, but the root-folder. The server failing is different everytime and so far only running it with a batch-size of 1 helped (even though it takes way more time).

**Comment by rallytime** [comment] 2015-03-17 15:53
@terminalmage can correct me if I am wrong, but I believe there were some GitFS-related regressions in the 2014.7.2 release that have now been addressed at the HEAD of the 2014.7 branch. @terminalmage Does this problem look familiar, or is this something different?

**Comment by terminalmage** [comment] 2015-03-17 15:55
Yes, this particular issue has been reported several times now, and is fixed in all branches.

**Comment by rallytime** [comment] 2015-03-17 16:00
Awesome! Thanks @terminalmage! I think the duplicate report is here #20896.

@MakaHost I would suggest giving the HEAD of the 2014.7 branch a try, or we should be releasing 2014.7.3 as well as 2015.2.0 all within a couple of weeks. Since this bug has already been reported and fixed, I am going to close this issue. If you still see problems with this issue after testing the newer code, please leave a comment and we will be very glad to open this again and readdress the issue.

**Closed by rallytime** 2015-03-17 16:00 UTC
Labels: Bug, Duplicate
