### ISSUE TITLE
integration.states.test_cron.CronTest.test_managed

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52079] opened 2019-03-08 01:28 UTC
```
integration.states.test_cron.CronTest.test_managed
--------------------------------------------------------------------------------
develop failed salt-fedora-28-py2, salt-fedora-28-py3, salt-fedora-29-py2, salt-fedora-29-py3
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
2019.2 failed salt-centos-6-py2, salt-fedora-28-py2, salt-fedora-28-py3, salt-fedora-29-py2
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
u'diff' not found in {}
................................................................................

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_cron.py", line 54, in test_managed
    self.assertIn('diff', ret['cron_|-salt://issue-46881/cron_|-salt://issue-46881/cron_|-file']['changes'])
AssertionError: u'diff' not found in {}
```

**Comment by waynew** [comment] 2019-03-28 14:22
Man... I cannot seem to reproduce this via kitchen -_-

This tests, and everything up to `integration.states.test_cron` all worked fine on Centos. Trying with fedora py2 now...

**Comment by waynew** [comment] 2019-04-02 11:33
While I couldn't reproduce this issue, I did realize that the test output could be improved by changing the assertion style. Created a PR for the change, so if this test fails again we should be able to get a more useful output than `AssertionError: u'diff' not found in {}`

**Comment by Ch3LL** [comment] 2019-04-26 20:59
its failing every test run on suse 42 py2: https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-42-py2/7/testReport/junit/integration.states.test_cron/CronTest/test_managed/

not sure if that will help you to replicate

**Comment by waynew** [comment] 2019-05-07 16:29
2019.2.1 failed [salt-fedora-28-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/21/testReport/junit/integration.states.test_cron/CronTest/test_managed), [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/integration.states.test_cron/CronTest/test_managed), [salt-fedora-29-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py2/21/testReport/junit/integration.states.test_cron/CronTest/test_managed), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/integration.states.test_cron/CronTest/test_managed), [salt-opensuse-42-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-42-py2/21/testReport/junit/integration.states.test_cron/CronTest/test_managed), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-42-py3/21/testReport/junit/integration.states.test_cron/CronTest/test_managed)
develop failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.states.test_cron/CronTest/test_managed)
---

'diff' not found in {}

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_cron.py", line 54, in test_managed
    self.assertIn('diff', ret['cron_|-salt://issue-46881/cron_|-salt://issue-46881/cron_|-file']['changes'])
AssertionError: 'diff' not found in {}
		
```

**Comment by waynew** [comment] 2019-05-20 21:05
Last attempt I made on this was to spin up a SUSE box using Kitchen on AWS, but the converge step failed. IIRC it was a failure to pip install, I think it couldn't find the pip command.

**Comment by Ch3LL** [comment] 2019-05-21 15:34
I just checked the recent builds for suse-42 and they are both converging correctly. Are you using nox now that its in the 2019.2.1 branch?

**Comment by twangboy** [comment] 2019-05-21 18:30
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/50/testReport/junit/integration.states.test_cron/CronTest/test_managed/

**Comment by waynew** [comment] 2019-05-21 19:05
Tried against develop - trying now against 2019.2.1, this time on py2-fedora-28

**Comment by waynew** [comment] 2019-05-21 20:13
Well, the great news is that I figured out what the problem *is*.

The problem is that I haven't a clue how to fix it.

The problem: `chattr +e <file>` doesn't work. It only runs on systems that have `lsattr` installed, so it appears that several of our environs just don't have lsattr installed so that particular problem never happens.

When chattr runs:

```
# chattr +e bar
chattr: No space left on device while setting flags on bar
```
Which is interesting. And uh, confusing. Because there's buckets of space and inodes left on the device.

**Comment by waynew** [comment] 2019-05-21 20:38
Well, in case things weren't confusing enough, `chattr` isn't the problem under SUSE - at least before kitchen transfers files :suspect:

**Comment by waynew** [comment] 2019-05-21 21:18
Hah. Spoke too soon. Still chattr, just a different problem!

```
21:15:33,222 [salt.state                               :322 ][ERROR   ] Unable to manage file: Command '[u'man', u'chattr']' returned non-zero exit status 16
       21:15:34,024 [salt.loader.localhost.int.module.cmdmod  :830 ][ERROR   ] Command 'crontab -u test_cron_user -r' failed with return code: 1
       21:15:34,024 [salt.loader.localhost.int.module.cmdmod  :832 ][ERROR   ] stdout: no crontab for test_cron_user
       21:15:34,024 [salt.loader.localhost.int.module.cmdmod  :836 ][ERROR   ] retcode: 1
       21:15:34,025 [salt.loader.localhost.int.module.cmdmod  :1186][ERROR   ] Command 'crontab -u test_cron_user -r' failed with return code: 1
       21:15:34,025 [salt.loader.localhost.int.module.cmdmod  :1191][ERROR   ] output: no crontab for test_cron_user
       FAIL (7.221s)

       ======================================================================
       FAIL [7.221s]: test_managed (integration.states.test_cron.CronTest)
       ----------------------------------------------------------------------
       Traceback (most recent call last):
         File "/tmp/kitchen/testing/tests/integration/states/test_cron.py", line 54, in test_managed
           self.assertIn('diff', ret['cron_|-salt://issue-46881/cron_|-salt://issue-46881/cron_|-file']['changes'])
       AssertionError: u'diff' not found in {}
```

**Comment by waynew** [comment] 2019-05-22 02:13
So the SUSE error can be fixed by reinstalling e2fsprogs - the manpages were gone, and we're parsing the `chattr` version from there.

The Fedora issue is something different - for some reason Fedora honors the bit from the manpage:

```
The 'e' attribute indicates that the file is using extents for mapping
the blocks on disk.  It may not be removed using chattr (1).
```

That limitation apparently doesn't apply in SUSE.

```
touch bar
chattr -e bar
chattr +e bar
```

All of that works on SUSE

```
touch bar
chattr -e bar
```

That works on Fedora, though it says the latter command shouldn't. What *actually* doesn't work is this:

```
chattr +e bar
```

That fails with the `no space left on device`.

**Comment by twangboy** [comment] 2019-05-22 18:41
Failing on 2019.2.1:
May 21, 2019 10:11:00 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-42-py2/54/
May 21, 2019 7:57:00 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/53/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-42-py3/54/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/56/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/54/

**Comment by Ch3LL** [comment] 2019-06-10 18:06
@waynew i'm still seeing this fail on 2019.2.1. i'm guessing the fix resolves the issue on 2019.2.1 as well? If so can you cherry-pick it onto 2019.2.1 branch as well? thanks

**Comment by waynew** [comment] 2019-06-12 14:52
Yeah, it should solve it on 2019.2.1. Should I just open a PR for it?

**Comment by DmitryKuzmenko** [comment] 2019-06-28 07:46
The same is happening with integration.states.test_cron.CronTest.test_46881
2019.2:
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-fedora-29-py3/144/testReport/junit/integration.states.test_cron/CronTest/test_46881/

```
Error Message

{'changes': {'diff': '--- \n+++ \n@@ -1 +1,2 @@\n-\n+#[403 chars]alse} != {'changes': {}, 'comment': 'Unable to manage file: cha[225 chars]ron'}   {'__id__': 'salt://issue-46881/cron',    '__run_num__': 0,    '__sls__': None, +  'changes': {}, -  'changes': {'diff': '--- \n' -                      '+++ \n' -                      '@@ -1 +1,2 @@\n' -                      '-\n' -                      '+# Lines below here are managed by Salt, do not edit\n' -                      '+@hourly touch /tmp/test-file\n', -              'group': 'test_cron_user', -              'user': 'test_cron_user'},    'comment': 'Unable to manage file: chattr failed to run, possibly due to bad '               'parameters.',    'duration': 312.787,    'name': 'salt://issue-46881/cron',    'result': False,    'start_time': '20:03:33.695674'}

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_cron.py", line 81, in test_46881
    ret[id_],
AssertionError: {'changes': {'diff': '--- \n+++ \n@@ -1 +1,2 @@\n-\n+#[403 chars]alse} != {'changes': {}, 'comment': 'Unable to manage file: cha[225 chars]ron'}
  {'__id__': 'salt://issue-46881/cron',
   '__run_num__': 0,
   '__sls__': None,
+  'changes': {},
-  'changes': {'diff': '--- \n'
-                      '+++ \n'
-                      '@@ -1 +1,2 @@\n'
-                      '-\n'
-                      '+# Lines below here are managed by Salt, do not edit\n'
-                      '+@hourly touch /tmp/test-file\n',
-              'group': 'test_cron_user',
-              'user': 'test_cron_user'},
   'comment': 'Unable to manage file: chattr failed to run, possibly due to bad '
              'parameters.',
   'duration': 312.787,
   'name': 'salt://issue-46881/cron',
   'result': False,
   'start_time': '20:03:33.695674'}
```

**Closed** 2019-07-02 22:09 UTC
Labels: 2019.2, 2019.2.1, Blocker, Fixed Pending Verification, Test Failure, develop
