### ISSUE TITLE
salt cmd.run arg parsing using --

### ISSUE THREAD

**Issue by joshmule** [saltstack/salt#23232] opened 2015-04-30 19:39 UTC
It would be nice to execute cmd.run with commands and command args not needing double quotes.  I'd like to see something like this:

salt  minionname cmd.run -- tail /path/file

... without seeing:

ERROR: Specified cwd '/path/file' either not absolute or does not exist

Thoughts?

**Comment by jfindlay** [comment] 2015-05-01 01:05
This gets tricky with the shell helping out/getting in the way and how we process command line arguments to modules, but if you would rather prepend a `--` than quote, then I think it could be implemented.  @basepi or @cachedout may have better opinions on this subject.

Note also that arguments can be single quoted as well as double quoted.  Standard shell considerations apply when deciding which.

**Comment by basepi** [comment] 2015-05-01 20:39
The `--` will prevent the argument parser from looking for any further `-` arguments, but it will not otherwise modify the remaining arguments, which we will still receive split on spaces, and then interpret as separate arguments to the salt command in question. You have to use quotes to group them into a single argument.

```
salt minionname cmd.run -- 'tail /path/file'
```

results in `cmd.run('tail /path/file')` while

```
salt minionname cmd.run -- tail /path/file
```

results in `cmd.run('tail', '/path/file')`. I don't think this is something we want to change, as it's a backwards-incompatible change, and gains us very little. (Maybe a couple of keystrokes? But no, because you have to type the `--`, so it saves nothing...)

**Comment by basepi** [comment] 2015-05-01 20:40
Closing this for now, but we'll still monitor for replies if you want to discuss further.

**Closed by basepi** 2015-05-01 20:40 UTC
Labels: Won't Fix For Now

**Comment by joshmule** [comment] 2015-05-01 22:13
I guess I'm just coming from the -- standard for most gnu tools and others.
  "--" is almost universal for "and everything after this is the rest of
the command".   Something I just used was:
watch -d -- free -m

I wanted to take that forward in salt if it didn't break anything, but I
understand if it does.

On Fri, May 1, 2015 at 4:40 PM, Colton Myers <notifications@github.com>
wrote:

> Closing this for now, but we'll still monitor for replies if you want to
> discuss further.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/23232#issuecomment-98230841>.
>



-- 
Joshua Jensen

**Comment by basepi** [comment] 2015-05-01 22:19
Right, and the same works in salt. But the issue is that we process "the rest of the command" as space-separated args, so we still need the quotes, unfortunately.

**Comment by joshmule** [comment] 2015-05-01 22:29
Are space-separated args part of the history of the salt command?  Do
people do multiple commands this way, or do they just find that they forgot
to add the quotes?

In theory the presence of a -- could explicitly signify "the rest of the
line is one command and its args", though that twist might not be inline
with the history of the salt command, and would just confuse users

On Fri, May 1, 2015 at 6:20 PM, Colton Myers <notifications@github.com>
wrote:

> Right, and the same works in salt. But the issue is that we process "the
> rest of the command" as space-separated args, so we still need the quotes,
> unfortunately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/23232#issuecomment-98253632>.
>



-- 
Joshua Jensen

**Comment by basepi** [comment] 2015-05-04 19:25
Not multiple commands. Multiple arguments to a single salt remote execution module function.

```
salt <target> <module.function> [arg1] [arg2] [arg3]
```

**Comment by Lokeshs2290** [comment] 2015-06-03 14:19
Hi 

i am not able to do a continuous tail from salt master

the command that i use is

salt -S 10.x.x.x cmd.run 'tail -f  /var/log/nginx'

**Comment by basepi** [comment] 2015-06-03 16:44
@Lokeshs2290 This is because salt does not keep a streaming connection open to the command in question, it only returns the output when the command ends. So streaming commands like `tail -f` will not work with cmd.run.

**Comment by Lokeshs2290** [comment] 2015-06-03 18:23
@basepi  Thanks for the quick reply 

is there any way i can stream log files from saltstack master .???

**Comment by basepi** [comment] 2015-06-04 16:52
@Lokeshs2290 not currently, no. I think we could construct such a feature using salt-vt, but it will take a little work. Would you mind opening a new issue with this feature request?
