### ISSUE TITLE
salt-minion process fails to stop on 'service salt-minion restart'

### ISSUE THREAD

**Issue by Eishzigh** [saltstack/salt#40815] opened 2017-04-21 07:48 UTC
### Description of Issue/Question
After every restart of salt-minion "service", one of the old salt-minion processes stays running, in addition to the new one gets started. In result every such restart grows number of currently running salt-minion processes.
### Setup
Minions:
salt-minion-2016.11.3-2.el5.noarch on RHEL5, and
salt-minion-2016.11.3-1.el6.noarch on RHEL6.

Master:
salt-master-2016.11.3-1.el6.noarch on RHEL6

### Steps to Reproduce Issue
Here is uninstall of salt-minion with dependencies, reinstall it fresh, start, and a few restarts.

# service salt-minion stop
Stopping salt-minion:root:client1.out.net daemon: OK
# killall salt-minion
# ps -ef |grep salt
root     13229 21603  0 19:19 pts/0    00:00:00 grep salt
# rpm -e $(rpm -qa |grep python26) salt salt-minion zeromq
warning: /etc/salt/minion saved as /etc/salt/minion.rpmsave
# yum --disablerepo=epel install salt-minion
...
Dependencies Resolved

========================================================================================
 Package                               Arch   Version          Repository          Size
========================================================================================
Installing:
 salt-minion                           noarch 2016.11.3-2.el5  saltstack-salt-el5  36 k
Installing for dependencies:
 python26                              x86_64 2.6.8-3.el5      saltstack-salt-el5 6.5 M
 python26-PyYAML                       x86_64 3.08-4.el5       saltstack-salt-el5 182 k
 python26-babel                        noarch 0.9.5-2.el5      saltstack-salt-el5 1.8 M
 python26-backports                    x86_64 1.0-4.el5        saltstack-salt-el5 4.7 k
 python26-backports-ssl_match_hostname noarch 3.4.0.2-2.el5    saltstack-salt-el5  11 k
 python26-chardet                      noarch 2.0.1-2.el5      saltstack-salt-el5 545 k
 python26-crypto                       x86_64 2.6.1-2.el5      saltstack-salt-el5 660 k
 python26-distribute                   noarch 0.6.10-4.el5     saltstack-salt-el5 512 k
 python26-jinja2                       noarch 2.8.1-1.el5      saltstack-salt-el5 741 k
 python26-libs                         x86_64 2.6.8-3.el5      saltstack-salt-el5 695 k
 python26-markupsafe                   x86_64 0.11-3.el5       saltstack-salt-el5  25 k
 python26-msgpack                      x86_64 0.4.5-1.el5      saltstack-salt-el5  85 k
 python26-ordereddict                  noarch 1.1-3.el5        saltstack-salt-el5 7.3 k
 python26-pycurl                       x86_64 7.15.5.1-9.el5   saltstack-salt-el5  74 k
 python26-requests                     noarch 1.1.0-5.el5      saltstack-salt-el5  80 k
 python26-six                          noarch 1.6.1-2.el5      saltstack-salt-el5  27 k
 python26-tornado                      x86_64 4.2.1-1.el5      saltstack-salt-el5 734 k
 python26-urllib3                      noarch 1.5-8.el5        saltstack-salt-el5  53 k
 python26-zmq                          x86_64 14.5.0-2.el5     saltstack-salt-el5 577 k
 salt                                  noarch 2016.11.3-2.el5  saltstack-salt-el5 9.5 M
 zeromq                                x86_64 4.0.5-4.el5      saltstack-salt-el5 628 k

Transaction Summary
========================================================================================
Install      22 Package(s)
Upgrade       0 Package(s)

Total download size: 23 M
Is this ok [y/N]: y
...
Complete!
# mv /etc/salt/minion.rpmsave /etc/salt/minion
mv: overwrite `/etc/salt/minion'? y
# egrep -v '#|^$' /etc/salt/minion
master: saltmaster.out.net
log_datefmt_logfile: '%Y-%m-%d %H:%M:%S'
# ps -ef |grep salt
root     13777 21603  0 19:23 pts/0    00:00:00 grep salt
# service salt-minion start
Starting salt-minion:root:client1.out.net daemon: OK
# ps -ef |grep salt
root     13991     1 19 19:23 ?        00:00:01 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     13992 13991  0 19:23 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14063 21603  0 19:24 pts/0    00:00:00 grep salt
# service salt-minion restart
Stopping salt-minion:root:client1.out.net daemon: OK
Starting salt-minion:root:client1.out.net daemon: OK
# ps -ef |grep salt
root     13992     1  0 19:23 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14291     1 22 19:24 ?        00:00:01 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14292 14291  0 19:24 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14363 21603  0 19:24 pts/0    00:00:00 grep salt
# service salt-minion restart
Stopping salt-minion:root:client1.out.net daemon: OK
Starting salt-minion:root:client1.out.net daemon: OK
# ps -ef |grep salt
root     13992     1  0 19:23 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14292     1  0 19:24 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14591     1 34 19:24 ?        00:00:01 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14592 14591  0 19:24 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14663 21603  0 19:24 pts/0    00:00:00 grep salt
#
# service salt-minion restart
Stopping salt-minion:root:client1.out.net daemon: OK
Starting salt-minion:root:client1.out.net daemon: OK
# ps -ef |grep salt
root     13992     1  0 19:23 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14292     1  0 19:24 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     14592     1  0 19:24 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     15224     1 34 19:30 ?        00:00:01 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     15225 15224  0 19:30 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     15290 21603  0 19:30 pts/0    00:00:00 grep salt
#

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Minion:
# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.8 (unknown, Jul 18 2016, 16:53:33)
   python-gnupg: Not Installed
         PyYAML: 3.08
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 5.11 Tikanga
        machine: x86_64
        release: 2.6.18-411.el5
         system: Linux
        version: Red Hat Enterprise Linux Server 5.11 Tikanga

Master:

# salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago

**Comment by githubcdr** [comment] 2017-04-21 09:29
This is a dupe of #40011

**Comment by Eishzigh** [comment] 2017-04-21 09:38
#40011 confirms this issue on rh6 and rh7.
I confirm this only on rh5 and rh6, but not on rh7. 
On my rh7 salt-minion-2016.11.3-1.el7.noarch restarts as expected with no issues.

**Comment by gtmanfred** [comment] 2017-04-21 15:29
I have also not been able to replicate this on rh7, but the pr to fix #40011 fixes it on rh5 too.

Unfortunately rh5 is end of support with redhat, so we won't be releasing a new package for it for 2016.11.4, but that is the release this will be fixed in.

Thanks,
Daniel

**Closed by gtmanfred** 2017-04-21 15:29 UTC
Labels: Duplicate
