### ISSUE TITLE
Can't delete a minion key from the Python API

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#31112] opened 2016-02-10 22:30 UTC
This doesn't work. No error, no return. Tested on 2015.8 and 2016.3.

```python
>>> import salt.wheel
>>> import salt.config
>>> master_opts = salt.config.client_config('/etc/salt/master')
>>> wheel = salt.wheel.WheelClient(master_opts)
>>> wheel.cmd('key.delete', kwarg={'match': 'jerry'})
```

**Comment by rallytime** [comment] 2016-02-12 17:37
@whiteinge I think this might be a duplicate of #30866. What do you think?

**Comment by rallytime** [comment] 2016-03-01 15:59
@whiteinge I think this should be fixed with #31570.

**Comment by cro** [comment] 2016-03-02 00:10
verified fixed.

**Closed by cro** 2016-03-02 00:10 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P3
