### ISSUE TITLE
Using bin_env to install packages for python3, the salt-call is successful but the package is installed for python2.

### ISSUE THREAD

**Issue by PierluigiGreto** [saltstack/salt#48793] opened 2018-07-27 11:32 UTC
### Description of Issue/Question
I updated the salt-minion from 2017.7.3 to 2018.3.2 (I updated my os from fedora26 to fedora28 and the salt-minion is updated automatically). I'm using the salt-minion masterless, and I'm trying to install pip install packages for python3 using the option bin_env. In the version 2017.7.3 the state is working. In the new version 2018.3.2 the salt-call is successful but the package is installed for python2 and not for python3. It is like the  `- bin_env: '/usr/bin/pip3'` option is not working anymore.
### Setup
```
Django==1.11.5:
  pip.installed:
    - bin_env: '/usr/bin/pip3'
```
### Steps to Reproduce Issue
Trying to install packages for python3, the salt-call is successful but the package is installed for python2.

### Versions Report
- old working salt-minion version: 2017.7.3 
- new not working salt-minion version: 2018.3.2

**Comment by gtmanfred** [comment] 2018-07-27 13:19
This will be fixed in the next release, 2018.3.3.

https://github.com/saltstack/salt/pull/48189

as a workaround specify bin_env to the python version you want to use. `bin_env: /usr/bin/python3`

**Closed by gtmanfred** 2018-07-27 13:19 UTC

**Comment by boltronics** [comment] 2020-07-03 06:56
This still seems to be broken. Please re-open.

Example output:
```
----------
          ID: Install python3-pip package
    Function: pkg.installed
        Name: python3-pip
      Result: True
     Comment: All specified packages are already installed
     Started: 16:39:24.749683
    Duration: 23.481 ms
     Changes:   
----------
          ID: Install pip dependencies for webp_generator.py
    Function: pip.installed
      Result: None
     Comment: Error installing 'Install pip dependencies for webp_generator.py': Could not find a `pip` binary
     Started: 16:39:24.774181
    Duration: 16.586 ms
     Changes:   
```

state.show_sls output:
```
    Install python3-pip package:
        ----------
        pkg:
            |_
              ----------
              name:
                  python3-pip
            |_
              ----------
              reload_modules:
                  True
            - installed
            |_
              ----------
              order:
                  10081
        __sls__:
            s3_webp_obj_gen
        __env__:
            base
    Install pip dependencies for webp_generator.py:
        ----------
        pip:
            |_
              ----------
              bin_env:
                  /usr/bin/pip3
            |_
              ----------
              user:
                  mks3webp
            |_
              ----------
              pkgs:
                  - pyvips >= 2.1 < 2.2
            |_
              ----------
              require:
                  |_
                    ----------
                    pkg:
                        Install python3-pip package
            - installed
            |_
              ----------
              order:
                  10082
        __sls__:
            s3_webp_obj_gen
        __env__:
            base
```

Version report:
```
Salt Version:
           Salt: 2019.2.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.12 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-12-amd64
         system: Linux
        version: debian 9.12 
 ```

**Comment by boltronics** [comment] 2020-07-03 07:03
Also, the suggested work-around does not work.
```
[INFO    ] Executing state pkg.installed for [python3-pip]
[INFO    ] All specified packages are already installed
[INFO    ] Completed state [python3-pip] at time 16:59:28.533555 (duration_in_ms=23.028)
[INFO    ] Running state [Install pip dependencies for webp_generator.py] at time 16:59:28.534548
[INFO    ] Executing state pip.installed for [Install pip dependencies for webp_generator.py]
[INFO    ] Executing command [u'/usr/bin/python3', u'-m', u'pip', u'--version'] in directory '/root'
[ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
[INFO    ] Completed state [Install pip dependencies for webp_generator.py] at time 16:59:29.809154 (duration_in_ms=1274.603)
----------
          ID: Install python3-pip package
    Function: pkg.installed
        Name: python3-pip
      Result: True
     Comment: All specified packages are already installed
     Started: 16:59:28.510527
    Duration: 23.028 ms
     Changes:   
----------
          ID: Install pip dependencies for webp_generator.py
    Function: pip.installed
      Result: False
     Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
     Started: 16:59:28.534551
    Duration: 1274.603 ms
     Changes:   
```

**Comment by boltronics** [comment] 2020-07-03 07:18
I can now verify that installing the legacy `python-pip` package for Python 2 allows Python 3 packages to be installed with Salt. :disappointed:

**Comment by gtmanfred** [comment] 2020-07-05 00:55
Switch to using the non python2 version of saltstack, and you will only need to install the python3 version of pip.

**Comment by gtmanfred** [comment] 2020-07-05 00:56
the `pip` module has to be importable by the python version that salt is running as in order to resolve dependencies and versions.

**Comment by boltronics** [comment] 2020-07-06 03:35
Okay, thanks. So this was't actually fixed then I guess. From the 2019.2 changelog:
> Python 2 will be deprecated from SaltStack no earlier than the 3001 release

We shouldn't have to upgrade yet, and this was marked as closed well within the 2019.2 Phase 1 support lifecycle.

**Comment by gtmanfred** [comment] 2020-07-18 13:59
what? this seems fine to close.  If you are using 2019.2 + python2 to install python3 packages, you still need pip for python2 installed for salt, so that it can import it.  This is not a bug.

**Comment by boltronics** [comment] 2020-07-20 02:28
Okay I see. I didn't understand why Salt would need to import something it would not be compatible with, so I just looked at the source to see how it works.

As I had thought, the the pip module doesn't import it at all (why else would we need to specify the pip command path), and the state module only uses it for `def _from_line()` and for a single reference to `pip.__version__`. I have to pull in a *lot* of packages to install `python-pip` just for that.

I think the developers of that function incorrectly assumed that since we're installing something via pip, we must have pip so is fine to use... but obviously there's more to it than that. Probably it is not strictly necessary and should not be imported at all, which I feel would be more inline with user expectations.
