### ISSUE TITLE
Can salt master reload the config ?

### ISSUE THREAD

**Issue by tenyearslater** [saltstack/salt#22840] opened 2015-04-20 06:26 UTC
I modify salt master config, and need to restart salt-master to make it work.
Can salt master reload the config ?

**Comment by cachedout** [comment] 2015-04-21 14:24
I'm afraid this is not currently possible. This has been an open feature request for a while. Since it's a duplicate of #570, I'm going to close this request as such. Please track any movement on this issue there. Thanks!

**Closed by cachedout** 2015-04-21 14:24 UTC
Labels: Bug, Duplicate
