### ISSUE TITLE
unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_userpass_mechanism_no_domain

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52816] opened 2019-05-02 22:01 UTC
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.utils.test_vmware/PrivateGetServiceInstanceTestCase/test_userpass_mechanism_no_domain)
---

<module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'SmartConnect'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 1363, in setUp
    patcher.start()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1524, in start
    result = self.__enter__()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1393, in __enter__
    original, local = self.get_original()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1367, in get_original
    "{} does not have the attribute {!r}".format(target, name)
AttributeError: <module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'SmartConnect'
		
```

**Comment by waynew** [comment] 2019-05-02 22:04
Also fails on these tests:

- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_second_attempt_successful_connection
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_userpass_mech_domain_unused
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_userpass_mechanism_empty_username
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_first_attempt_unsuccessful_connection_default_error
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_sspi_empty_domain
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_sspi_empty_principal
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_third_attempt_unsuccessful_connection_vim_fault
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_second_attempt_unsuccsessful_connection_vim_fault
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_first_attempt_successful_connection
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_userpass_mechanism_empty_password
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_third_attempt_successful_connection
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_second_attempt_unsuccsessful_connection_default_error
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_third_attempt_unsuccessful_connection_detault_error
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_first_attempt_unsuccessful_connection_vim_fault
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_sspi_get_token_error
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_sspi_get_token_success_
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_invalid_mechianism

**Comment by Ch3LL** [comment] 2019-05-03 13:26
duplicate of https://github.com/saltstack/salt/issues/51886

**Closed by Ch3LL** 2019-05-03 13:26 UTC
Labels: 2019.2.1, Test Failure
