### ISSUE TITLE
integration.states.test_file.FileTest.test_directory_broken_symlink

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53283] opened 2019-05-28 18:40 UTC
The test `integration.states.test_file.FileTest.test_directory_broken_symlink`

fails here: https://jenkinsci.saltstack.com/job/2019.2.1/view/Transport/job/salt-centos-7-py2-tcp/4/testReport/junit/integration.states.test_file/FileTest/test_directory_broken_symlink/

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_file.py", line 1271, in test_directory_broken_symlink
    file_mode=644, dir_mode=755)
  File "/tmp/kitchen/testing/tests/support/case.py", line 840, in run_state
    ret = self.run_function('state.single', [function], **kwargs)
  File "/tmp/kitchen/testing/tests/support/case.py", line 814, in run_function
    kwarg=kwargs)
  File "/tmp/kitchen/testing/salt/client/__init__.py", line 703, in cmd
    **kwargs)
  File "/tmp/kitchen/testing/salt/client/__init__.py", line 349, in run_job
    raise SaltClientError(general_exception)
SaltClientError: can not serialize 'set' object
```

**Comment by s0undt3ch** [comment] 2019-06-03 17:31
Closing as duplicate of #52912

**Closed by s0undt3ch** 2019-06-03 17:31 UTC
Labels: 2019.2.1, Test Failure
