### ISSUE TITLE
Salt 3000 won't work on CentOS7/Python 2

### ISSUE THREAD

**Issue by MartinEmrich** [saltstack/salt#56188] opened 2020-02-18 10:04 UTC
### Description of Issue
Installing the Salt minion 3000 on CentOS 7 using salt bootstrap results in a non-functioning installation (2019.x did work).
Calling e.g. state.highstate results in a long list of exceptions like

````
[ERROR   ] Failed to import states zone, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1607, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/states/zone.py", line 115, in <module>
    import logging
  File "/usr/lib64/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref
  File "/usr/lib64/python2.7/os.py", line 119, in <module>
    sys.modules['os.path'] = path
AttributeError: 'module' object has no attribute 'modules'
[ERROR   ] Failed to import states zpool, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1607, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/states/zpool.py", line 75, in <module>
    import os
  File "/usr/lib64/python2.7/os.py", line 119, in <module>
    sys.modules['os.path'] = path
AttributeError: 'module' object has no attribute 'modules'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'modules'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000', 'console_scripts', 'salt-call')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1087, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 4088, in call_highstate
    return self.state.call_high(high, orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2909, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2271, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2604, in call_chunk
    status, reqs = self.check_requisite(low, running, chunks, pre=True)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2446, in check_requisite
    if (fnmatch.fnmatch(chunk['name'], req_val) or
  File "/usr/lib64/python2.7/fnmatch.py", line 40, in fnmatch
    import os
  File "/usr/lib64/python2.7/os.py", line 119, in <module>
    sys.modules['os.path'] = path
AttributeError: 'module' object has no attribute 'modules'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000', 'console_scripts', 'salt-call')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1087, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 4088, in call_highstate
    return self.state.call_high(high, orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2909, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2271, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2604, in call_chunk
    status, reqs = self.check_requisite(low, running, chunks, pre=True)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2446, in check_requisite
    if (fnmatch.fnmatch(chunk['name'], req_val) or
  File "/usr/lib64/python2.7/fnmatch.py", line 40, in fnmatch
    import os
  File "/usr/lib64/python2.7/os.py", line 119, in <module>
    sys.modules['os.path'] = path
AttributeError: 'module' object has no attribute 'modules'
````

### Setup
Just install and configure salt-minion 3000 using salt bootstrap. If the `-x` option is not specified, a non-funtional install using python2.7 is installed.

If passing the `-x python3` option, a working installation using python3.6 is installed.

### Steps to Reproduce Issue
run `salt-call state.highstate test=true` on the python2.7-based system.

### Versions Report

Failing: 
````
# salt-call --versions
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
````

Working:
````
# salt-call --versions
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
 ````

I don't know about the politics about python 2 vs. python 3 with saltstack, but I guess making `-x python3` the default on EL7 would be sensible.

**Comment by OrangeDog** [comment] 2020-02-18 10:32
I believe bootstrap is generally broken for 3000, on every platform.

**Comment by MartinEmrich** [comment] 2020-02-18 14:30
@OrangeDog with `-x python3`, it works for both master and minion. Is bootstrap deprecated?

**Comment by OrangeDog** [comment] 2020-02-18 14:37
> Is bootstrap deprecated?

No, they just broke it.

**Comment by MartinEmrich** [comment] 2020-02-18 15:49
Indeed. At first I thought it would work, but in fact I have a wild mixture of python3 (master,minion) and python2-based stuff (api).

Actually I think the repo versioning is off, too. There's apparently a repo for python2 and on for python3... But both contain packages with the same RPM version number. That calls for trouble...

Next, I'll leave bootstrap aside, and try my luck with the py3 repo from https://repo.saltstack.com/#rhel

**Comment by max-arnold** [comment] 2020-02-19 04:47
The tracebacks look quite similar to this pip issue: https://github.com/saltstack/salt/issues/56131

Can you try installing `python-pip` (manually or through the [`-p python-pip`](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L358-L359) bootstrap option)?

**Comment by MartinEmrich** [comment] 2020-02-19 14:55
@max-arnold installing `python-pip` (which actially installed `python2-pip`) fixed it.

**Comment by waynew** [comment] 2020-02-19 22:44
Duplicate of #56131 (unless I misunderstood, in which case, please let me know and we'll re-open!)

**Closed by waynew** 2020-02-19 22:44 UTC
