### ISSUE TITLE
diskusage beacon returning all mounts

### ISSUE THREAD

**Issue by ProcenaFr** [saltstack/salt#49202] opened 2018-08-20 09:04 UTC
### Description of Issue/Question
When I use the beacon disk usage, it returns on the events all the mounts with wrong diskusage.
Also the % returned is wrong.

### Setup
On the minion : /etc/salt/minion.d/beacons.conf : 
beacons:
  diskusage:
    - /: 30%

With /dev/mapper/vg00-root   5,8G    2,6G  3,0G  47% /

### Steps to Reproduce Issue
systemctl restart-minion
On the master : salt-run state.event pretty=True | grep -A100 server

Result : 

salt/beacon/minion1/diskusage/  {
    "_stamp": "2018-08-20T08:56:08.449626",
    "diskusage": 44.1,
    "id": "minion1.sres.stech",
    "mount": "/"
}
salt/beacon/minion1/diskusage/  {
    "_stamp": "2018-08-20T08:56:08.450184", 
    "diskusage": 44.1, 
    "id": "minion1.sres.stech", 
    "mount": "/boot"
}
salt/beacon/minion1/diskusage/  {
    "_stamp": "2018-08-20T08:56:08.450501", 
    "diskusage": 44.1, 
    "id": "minion1.sres.stech", 
    "mount": "/data"
}
salt/beacon/minion1/diskusage/  {
    "_stamp": "2018-08-20T08:56:08.450796", 
    "diskusage": 44.1, 
    "id": "minion1.sres.stech", 
    "mount": "/tmp"
}
salt/beacon/minion1/diskusage/  {
    "_stamp": "2018-08-20T08:56:08.451084", 
    "diskusage": 44.1, 
    "id": "minion1.sres.stech", 
    "mount": "/home"
}
salt/beacon/minion1.sres.stech/diskusage/  {
    "_stamp": "2018-08-20T08:56:08.451368", 
    "diskusage": 44.1, 
    "id": "minion1.sres.stech", 
    "mount": "/var"
}
salt/beacon/minion1/diskusage/  {
    "_stamp": "2018-08-20T08:56:08.451653", 
    "diskusage": 44.1, 
    "id": "minion1.sres.stech", 
    "mount": "/opt"
}
salt/beacon/minion1/diskusage/  {
    "_stamp": "2018-08-20T08:56:08.451936", 
    "diskusage": 44.1, 
    "id": "minion1.sres.stech",
    "mount": "/nmon"
}

For information : 
[root@minion1 ~]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/vg00-root    5.8G  2.6G  3.0G  47% /
devtmpfs                 926M     0  926M   0% /dev
tmpfs                    937M   12K  937M   1% /dev/shm
tmpfs                    937M   91M  846M  10% /run
tmpfs                    937M     0  937M   0% /sys/fs/cgroup
/dev/sda1                976M  159M  750M  18% /boot
/dev/mapper/vg00-data    2.0G  116M  1.7G   7% /data
/dev/mapper/vg00-tmp     2.0G  6.3M  1.8G   1% /tmp
/dev/mapper/vg00-home    488M  816K  452M   1% /home
/dev/mapper/vg00-var     3.9G  3.3G  395M  90% /var
/dev/mapper/vg00-opt     2.9G  308M  2.5G  12% /opt
/dev/mapper/vg00-nmonlv   58M  4.0M   50M   8% /nmon
tmpfs                    188M     0  188M   0% /run/user/0

### Versions Report
On the master : Salt: 2018.3.0
On the minion : salt-minion-2018.3.0-58.1.x86_64

**Comment by ProcenaFr** [comment] 2018-08-20 13:35
So I changed "/" for '^\/$' because in the beacon (/usr/lib/python2.7/site-packages/salt/beacons/diskusage.py) it checks if it matches, so it checks all filesystem with "/".
Next I changed 
```
        for part in parts:
            if re.match(mount, part.mountpoint):
                mount = part.mountpoint

                try:
                    _current_usage = psutil.disk_usage(mount)

With 
        for part in parts:
            if re.match(mount, part.mountpoint):
                _mount = part.mountpoint

                try:
                    _current_usage = psutil.disk_usage(_mount)
```
So it checks not with '^\/$' but with the matched mount.

By the way the example given is wrong, because it advices to check "/" which won't work as intended.

**Comment by gtmanfred** [comment] 2018-08-20 14:07
would you submit a PR with this change?

That would be greatly appreciated.

https://docs.saltstack.com/en/latest/topics/development/contributing.html

Thanks!
Daniel

**Comment by rbthomp** [comment] 2018-08-20 15:32
This is a duplicate of #49174.

**Comment by gtmanfred** [comment] 2018-08-20 15:35
Cool, would one of yall mind submitting a PR to fix it, it would be greatly appreciated.

Thanks,
Daniel

**Comment by ProcenaFr** [comment] 2018-08-20 16:11
I've done a PR.
For the different "%" between `psutil` and `df ` it is a bug that has been fixed on newer Python.
It didn't take in count the reserved space.

**Comment by rbthomp** [comment] 2018-08-20 16:19
@ProcenaFr I looked at your PR I'll want to update the following line to reference the proper mount on error.
```
                except OSError:
                    log.warning('%s is not a valid mount point.', _mount)
                    continue
```

**Comment by ProcenaFr** [comment] 2018-08-20 17:29
@rbthomp I wanted to change it too but I don't know if on the logs I want the regular expression or the name of the mount. I guess "_mount" is better.

**Comment by gtmanfred** [comment] 2018-08-21 14:32
duplicate of #49174

**Closed** 2018-08-22 19:01 UTC
Labels: Bug, Duplicate

**Comment by gtmanfred** [comment] 2018-08-22 19:02
Fixed here https://github.com/saltstack/salt/pull/49264
