### ISSUE TITLE
postgres_initdb.present fails on Redhat with PostgreSQL provided installation

### ISSUE THREAD

**Issue by benhosmer** [saltstack/salt#34587] opened 2016-07-11 17:28 UTC
### Setup
The following state:

```
db-data-dir:                                                                    
   postgres_initdb.present:                                                      
     - name: /var/lib/pgsql/9.4/data/                                            
```

Fails with:

```
[INFO    ] Executing state postgres_initdb.present for /var/lib/pgsql/9.4/data/
[ERROR   ] initdb not found in path
[ERROR   ] Postgres data directory /var/lib/pgsql/9.4/data/ initialization failed
```

When using the the PostgreSQL provided repositories on RHEL 7 because initdb is located in `/usr/pgsql-<postgres-version>/bin/initdb`. This is not in root's path:

`/sbin:/bin:/usr/sbin:/usr/bin`

### Steps to Reproduce Issue
1. Use a RedHat 7 machine
2. Install the official PostgreSQL rpm: `# yum -y install http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-redhat94-9.4-1.noarch.rpm`
3. Install the _PostgreSQL Server_ group: `# yum -y groupinstall "PostgreSQL Database Server 9.4 PGDG"`

Attempt to use the `postgres_initdb.present` state.

### Versions Report

```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Linux
```

**Comment by Ch3LL** [comment] 2016-07-11 21:23
@benhosmer I would consider this expected behavior/upstream issue postgres is not adding that command to PATH. You could workaround this with salt by running a state before running the postgres_initdb state that adds that to PATH. But we don't want to add this to the module because it would become a little difficult to manage all the different OSs. Does that workaournd work for you?

**Comment by benhosmer** [comment] 2016-07-11 23:03
I'd already implemented a workaround actually by just symlinking it. I do see your point though about maintainability. I wonder though if this happens in Debian or Opensuse with the official PostgreSQL repos too. I only posted RedHat because that was what I was using at the time.

With this being the upstream official repo though, I wonder if this problem might crop up again and again.

Can we keep this open for a bit just in case other distros have this issue and maybe consider adding something to docs?

**Comment by gtmanfred** [comment] 2016-07-12 13:55
We should document this either way, just to mention that the initdb binary needs to be in the path.

**Comment by benhosmer** [comment] 2016-07-12 23:06
I'll get a PR in for the docs to add something to that effect then in case others come across this. I'll keep this open until I add it.

**Comment by rallytime** [comment] 2016-07-13 15:15
That sounds great @benhosmer! I'll adjust the labels here to indicate that something should be fixed in the docs.

**Comment by benhosmer** [comment] 2016-07-25 11:33
There was a comment I saw somewhere pertaining to this issue, but I can't seem to locate it now.

I'm working on adding configuration options to the `postgres.py` module so that users can specify the path to the `psql` and `initdb` binaries if they aren't on the path.

**Closed** 2016-08-01 17:38 UTC
Labels: Bug, Documentation, Medium Severity, P3
