### ISSUE TITLE
Include salt formulas from git inside states instead of gitfs_roots

### ISSUE THREAD

**Issue by tony** [saltstack/salt#22943] opened 2015-04-22 14:34 UTC
Currently the practice for adding formulas is to edit the config: http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html

I think this runs kind of contrary to intuition. I want to include redis-formula.  What does this have to do with adding a root? Adding a file root is a big deal, it requires editing a config. Snapping in a formula via an include makes life so much easier for testing and sharing formulas.

The markup / language I'm not fully looking closely at yet, here's the idea:

```yaml
# pip/gitfs_roots vcs uri style
include:
  - vim
  - https://github.com/saltstack-formulas/redis-formula.git:
    root: redis
    

# golang style
include:
  - vim
  - github.com/saltstack-formulas/redis-formula/redis
```

vcs import / packaging in production is already safe and commonplace. One programming language bakes it into the spec.

- golang vcs imports (https://golang.org/cmd/go/#hdr-Remote_import_paths)
- pip vcs urls (https://packaging.python.org/en/latest/installing.html#installing-from-vcs)

**Comment by tony** [comment] 2015-04-24 01:49
@andrew-vant, @nmadhok: I'm doing sort of a sanity-check on this.

In https://github.com/saltstack-formulas a lot of the formulas rely on other formulas (especially as user's build up their own reuseable configs). Has there ever been any desire / thought of a way to include / pull salt-formulas that didn't entail editing the salt master/minion config?

**Comment by nmadhok** [comment] 2015-04-24 02:29
I have been working on a package manager for salt formulas but I got busy with other projects. It's still on my todo list.

**Comment by tony** [comment] 2015-04-24 04:54
One of the issues I'm having is communty salt-states sort of lock config makers into one file structure. I have so many states I decided to organize them in a port-like structure: https://github.com/tony/salt-states-configs/tree/5580fc3ed4922f9eb3cc9e46edd8ddba2eebb0b0/salt/roots/salt

Ideally, I'd like to be able to include as a vcs, but also trim it at subdirectory level like golang does.

**Comment by jfindlay** [comment] 2015-05-27 00:13
Possibly a duplicate of #18290.

**Comment by rallytime** [comment] 2016-06-17 22:22
This should be addressed by the addition of the Salt Package Manager (or spm), which you can learn more about in the following docs:
- https://docs.saltstack.com/en/latest/topics/spm/
- https://docs.saltstack.com/en/latest/ref/cli/spm.html
- https://docs.saltstack.com/en/latest/topics/spm/dev.html

**Closed by rallytime** 2016-06-17 22:22 UTC
Labels: Core, Duplicate, Feature, File Servers, Pending Discussion, Platform

**Comment by tony** [comment] 2017-10-02 07:34
Woah. That is really complicated and it's introducing another feature to take account of. Why can't we just keep it simple and allow salt states (even when remote) to be retrieved via the top file?

Also, `mountpoint` was added between this post and the latest release.
