### ISSUE TITLE
Maintenance process dies every minute or so and restarts causing inode exhaustion

### ISSUE THREAD

**Issue by rvora** [saltstack/salt#33758] opened 2016-06-03 18:55 UTC
### Maintenance process dies every minute or so and restarts. End result is that /var/cache/salt/master/jobs is not being cleaned up and filesystem runs out of inodes.

I see the following messages in /var/log/salt/master.

   # master-of-master salt-master version:
   # salt-master --version
salt-master 2016.3.0 (Boron)

However, due to some legacy issues, I have a lot of syndics running very old version.

   # on lower-level master running the syndic
   # salt-syndic --version
salt-syndic 2014.7.5 (Helium)

These syndics are sending jobs from lower level minions up to the master-of-master which may be one of the reason why master-of-master jobs cache is filling up like crazy.

   # On the master-of-master
   # tail -f /var/log/salt/master | grep died
2016-06-03 18:45:33,822 [salt.utils.process                                   ][INFO    ][22587] Process <class 'salt.master.Maintenance'> (25542) died with exit status None, restarting...
2016-06-03 18:46:36,757 [salt.utils.process                                   ][INFO    ][22587] Process <class 'salt.master.Maintenance'> (25664) died with exit status None, restarting...
2016-06-03 18:47:39,733 [salt.utils.process                                   ][INFO    ][22587] Process <class 'salt.master.Maintenance'> (25924) died with exit status None, restarting...

I have lowest keep_jobs in /etc/salt/master but I still get inode exhaustion every few hours.
keep_jobs: 1

**Comment by babilen** [comment] 2016-06-03 19:02
Could this be https://github.com/saltstack/salt/issues/33544 as mentioned in  https://docs.saltstack.com/en/develop/topics/releases/2016.3.0.html ? If so you might want to apply https://github.com/saltstack/salt/pull/33555

**Comment by cachedout** [comment] 2016-06-03 20:29
This is indeed a duplicate of #33544. Closing as such.

**Closed by cachedout** 2016-06-03 20:29 UTC
Labels: Duplicate
