### ISSUE TITLE
jjid not shown when running the salt command line with --batch-size  using either --verbose or --show-jid  with certain salt versions

### ISSUE THREAD

**Issue by DeanScothern** [saltstack/salt#32856] opened 2016-04-26 07:47 UTC
### Description of Issue/Question
jid not shown when running the salt command line with --batch-size  using either --verbose or --show-jid with certain salt versions. I've tried 2015.5.5 (epel repos), 2015.8.1and 2015.8.7 (salt stack repos) so far.

### Setup
(Nothing special)

### Steps to Reproduce Issue

salt '*' --batch-size 5 --show-jid cmd.run 'sleep 15'
or
salt '*' --batch-size 5 --verbose cmd.run 'sleep 15'

and the jid is not included in the o/p, all I get is something like:

Executing run on ['minion1', 'minion2', 'minion3', 'minion4', 'minion5']

minion1:
retcode:
    0
minion2:
retcode:
    0
minion3:
retcode:
    0

Executing run on ['.....
### Versions Report

Production:

salt --versions-report
           Salt: 2015.5.5
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

Clients are the same

Test
salt --versions-report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.11.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core

client not updated yet  (still at salt-minion-2015.5.8-1.el7.noarch)

**Comment by jfindlay** [comment] 2016-04-26 16:37
@DeanScothern, thanks for reporting.

**Comment by rallytime** [comment] 2016-05-02 21:20
Hi @DeanScothern - It looks like the `--show-jid` functionality in conjunction with using `batch` has been fixed at the HEAD of the 2015.8 branch. I was able to reproduce the bug in both the 2015.8.7 and the most recent 2015.8.8.2 versions, but will be fixed in the upcoming 2015.8.9 release:
```
root@rallytime:~# salt '*' test.ping -b 50% --show-jid

Executing run on ['rallytime', 'ms-0', 'ms-1']

jid:
    20160502211717989004
ms-1:
    True
retcode:
    0
jid:
    20160502211717989004
rallytime:
    True
retcode:
    0
jid:
    20160502211717989004
ms-0:
    True
retcode:
    0

Executing run on ['ms-2', 'ms-3', 'ms-4']

jid:
    20160502211718304589
ms-4:
    True
retcode:
    0
jid:
    20160502211718304589
ms-3:
    True
retcode:
    0
jid:
    20160502211718304589
ms-2:
    True
retcode:
    0
```
Versions report:
```
root@rallytime:~# salt --versions
Salt Version:
           Salt: 2015.8.8-154-g00fbeab

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 5.0.1
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-x86_64-linode63
         system: Ubuntu 14.04 trusty
```
The `--verbose` option however is still broken.

**Comment by rallytime** [comment] 2016-05-02 22:13
@DeanScothern OK, the PR that fixed the `--show-jid` option is #32450. I just submitted #32996 to fix the `--verbose` setting with `--batch`.

**Comment by DeanScothern** [comment] 2016-05-03 14:25
Apologies, but  is this something I can or should verify now, or should I wait until the repos are updated?

**Comment by rallytime** [comment] 2016-05-03 14:43
@DeanScothern No worries. It's completely up to you. We can keep this open until you have a chance to confirm.

**Closed** 2016-05-09 19:24 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P3, TEAM Core

**Comment by DeanScothern** [comment] 2016-05-25 14:34
Its working correctly in salt-minion-2015.8.10-1, thanks.
