### ISSUE TITLE
[BUG] Salt repository sync problem on Foreman

### ISSUE THREAD

**Issue by Ivca50V** [saltstack/salt#67039] opened 2024-11-06 09:17 UTC
**Description**
Since Upstream URL for salt repository changed to https://packages.broadcom.com/artifactory/saltproject-rpm/ we can't sync that repository hosted on JFrog to Foreman. Errors on Foreman says: **XML file(s): filelists not found** and see this also on Foreman community: https://community.theforeman.org/t/external-private-yum-repository-on-jfrog-io-not-synchronizing-in-foreman-katello/24938 which is probably related to this problem.

**Setup**
Upstream URL used on Foreman: **https://packages.broadcom.com/artifactory/saltproject-rpm/**
GPG key:
`-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGPazmABDAC6qc2st6/Uh/5AL325OB5+Z1XMFM2HhQNjB/VcYbLvcCx9AXsU
eaEmNPm6OY3p5+j8omjpXPYSU7DUQ0lIutuAtwkDMROH7uH/r9IY7iu88S6w3q89
bgbnqhu4mrSik2RNH2NqEiJkylz5rwj4F387y+UGH3aXIGryr+Lux9WxfqoRRX7J
WCf6KOaduLSp9lF4qdpAb4/Z5yExXtQRA9HULSJZqNVhfhWInTkVPw+vUo/P9AYv
mJVv6HRNlTb4HCnl6AZGcAYv66J7iWukavmYKxuIbdn4gBJwE0shU9SaP70dh/LT
WqIUuGRZBVH/LCuVGzglGYDh2iiOvR7YRMKf26/9xlR0SpeU/B1g6tRu3p+7OgjA
vJFws+bGSPed07asam3mRZ0Y9QLCXMouWhQZQpx7Or1pUl5Wljhe2W84MfW+Ph6T
yUm/j0yRlZJ750rGfDKA5gKIlTUXr+nTvsK3nnRiHGH2zwrC1BkPG8K6MLRluU/J
ChgZo72AOpVNq9MAEQEAAbQ5U2FsdCBQcm9qZWN0IFBhY2thZ2luZyA8c2FsdHBy
b2plY3QtcGFja2FnaW5nQHZtd2FyZS5jb20+iQHSBBMBCAA8FiEEEIV//dP5Hq5X
eiHWZMu8gXPXaz8FAmPazmACGwMFCwkIBwIDIgIBBhUKCQgLAgQWAgMBAh4HAheA
AAoJEGTLvIFz12s/yf0L/jyP/LfduA4DwpjKX9Vpk26tgis9Q0I54UerpD5ibpTA
krzZxK1yFOPddcOjo+Xqg+I8aA+0nJkf+vsfnRgcpLs2qHZkikwZbPduZwkNUHX7
6YPSXTwyFlzhaRycwPtvBPLFjfmjjjTi/aH4V/frfxfjH/wFvH/xiaiFsYbP3aAP
sJNTLh3im480ugQ7P54ukdte2QHKsjJ3z4tkjnu1ogc1+ZLCSZVDxfR4gLfE6GsN
YFNd+LF7+NtAeJRuJceXIisj8mTQYg+esTF9QtWovdg7vHVPz8mmcsrG9shGr+G9
iwwtCig+hAGtXFAuODRMur9QfPlP6FhJw0FX/36iJ2p6APZB0EGqn7LJ91EyOnWv
iRimLLvlGFiVB9Xxw1TxnQMNj9jmB1CA4oNqlromO/AA0ryh13TpcIo5gbn6Jcdc
fD4Rbj5k+2HhJTkQ78GpZ0q95P08XD2dlaM2QxxKQGqADJOdV2VgjB2NDXURkInq
6pdkcaRgAKme8b+xjCcVjLkBjQRj2s5gAQwAxmgflHInM8oKQnsXezG5etLmaUsS
EkV5jjQFCShNn9zJEF/PWJk5Df/mbODj02wyc749dSJbRlTY3LgGz1AeywOsM1oQ
XkhfRZZqMwqvfx8IkEPjMvGIv/UI9pqqg/TY7OiYLEDahYXHJDKmlnmCBlnU96cL
yh7a/xY3ZC20/JwbFVAFzD4biWOrAm1YPpdKbqCPclpvRP9N6nb6hxvKKmDo7MqS
uANZMaoqhvnGazt9n435GQkYRvtqmqmOvt8I4oCzV0Y39HfbCHhhy64HSIowKYE7
YWIujJcfoIDQqq2378T631BxLEUPaoSOV4B8gk/Jbf3KVu4LNqJive7chR8F1C2k
eeAKpaf2CSAe7OrbAfWysHRZ060bSJzRk3COEACk/UURY+RlIwh+LQxEKb1YQueS
YGjxIjV1X7ScyOvam5CmqOd4do9psOS7MHcQNeUbhnjm0TyGT9DF8ELoE0NSYa+J
PvDGHo51M33s31RUO4TtJnU5xSRb2sOKzIuBABEBAAGJAbYEGAEIACAWIQQQhX/9
0/kerld6IdZky7yBc9drPwUCY9rOYAIbDAAKCRBky7yBc9drP8ctC/9wGi01cBAW
BPEKEnfrKdvlsaLeRxotriupDqGSWxqVxBVd+n0Xs0zPB/kuZFTkHOHpbAWkhPr+
hP+RJemxCKMCo7kT2FXVR1OYej8Vh+aYWZ5lw6dJGtgo3Ebib2VSKdasmIOI2CY/
03G46jv05qK3fP6phz+RaX+9hHgh1XW9kKbdkX5lM9RQSZOof3/67IN8w+euy61O
UhNcrsDKrp0kZxw3S+b/02oP1qADXHz2BUerkCZa4RVK1pM0UfRUooOHiEdUxKKM
DE501hwQsMH7WuvlIR8Oc2UGkEtzgukhmhpQPSsVPg54y9US+LkpztM+yq+zRu33
gAfssli0MvSmkbcTDD22PGbgPMseyYxfw7vuwmjdqvi9Z4jdln2gyZ6sSZdgUMYW
PGEjZDoMzsZx9Zx6SO9XCS7XgYHVc8/B2LGSxj+rpZ6lBbywH88lNnrm/SpQB74U
4QVLffuw76FanTH6advqdWIqtlWPoAQcEkKf5CdmfT2ei2wX1QLatTs=
=ZKPF
-----END PGP PUBLIC KEY BLOCK-----`

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
`2024-11-06T10:08:30 [I|app|0bb14c9e] Started GET "/katello/sync_management/sync_status?repoids%5B%5D=6472&organization_id=6&_=1730884089019" for 10.5.1.3 at 2024-11-06 10:08:30 +0100
2024-11-06T10:08:30 [I|app|0bb14c9e] Processing by Katello::SyncManagementController#sync_status as JSON
2024-11-06T10:08:30 [I|app|0bb14c9e]   Parameters: {"repoids"=>["6472"], "organization_id"=>"6", "_"=>"1730884089019"}
2024-11-06T10:08:30 [I|app|0bb14c9e] Completed 200 OK in 43ms (Views: 0.2ms | ActiveRecord: 6.5ms | Allocations: 21748)
2024-11-06T10:08:32 [I|app|4acb245b] Started GET "/katello/sync_management/sync_status?repoids%5B%5D=6472&organization_id=6&_=1730884089020" for 10.5.1.3 at 2024-11-06 10:08:32 +0100
2024-11-06T10:08:32 [I|app|4acb245b] Processing by Katello::SyncManagementController#sync_status as JSON
2024-11-06T10:08:32 [I|app|4acb245b]   Parameters: {"repoids"=>["6472"], "organization_id"=>"6", "_"=>"1730884089020"}
2024-11-06T10:08:32 [I|app|4acb245b] Completed 200 OK in 56ms (Views: 0.2ms | ActiveRecord: 5.9ms | Allocations: 21715)
2024-11-06T10:08:34 [I|app|96b0e9d7] Started GET "/katello/sync_management/sync_status?repoids%5B%5D=6472&organization_id=6&_=1730884089021" for 10.5.1.3 at 2024-11-06 10:08:34 +0100
2024-11-06T10:08:34 [I|app|96b0e9d7] Processing by Katello::SyncManagementController#sync_status as JSON
2024-11-06T10:08:34 [I|app|96b0e9d7]   Parameters: {"repoids"=>["6472"], "organization_id"=>"6", "_"=>"1730884089021"}
2024-11-06T10:08:34 [I|app|96b0e9d7] Completed 200 OK in 47ms (Views: 0.2ms | ActiveRecord: 5.2ms | Allocations: 21980)
**2024-11-06T10:08:36 [E|bac|9161b7fb] XML file(s): filelists not found (Katello::Errors::Pulp3Error)**
`

**Expected behavior**
I expecting the repository get mirrored normally without filelists problems.

**Screenshots**
![task salt sync problem](https://github.com/user-attachments/assets/140f1805-9297-4f78-acb6-f4f49d376469)

**Versions Report**
N/A

```yaml
N/A
```
</details>

**Additional context**
N/A

**Comment by ScriptAutomate** [comment] 2024-11-07 20:27
Duplicate of #67032

**Closed by ScriptAutomate** 2024-11-07 20:27 UTC
Labels: Bug, needs-triage
