### ISSUE TITLE
top.sls it taken from master rather than defined in base for gitfs_remotes

### ISSUE THREAD

**Issue by onorua** [saltstack/salt#31385] opened 2016-02-20 18:58 UTC
I've faced with strange behavior, when I have top.sls in master - everything is working fine, but when I have top.sls in branch, while master has it's own top.sls - salt-master takes top.sls from master branch. Example:
I have states in a different branches, I use it for production refactoring and e2e testing accordingly:
```
 $ git branch 
  master
  refactoring
* testing
```
/etc/salt/master.d/backends.conf:
```
gitfs_remotes:
  - https://bitbucket.org/onorua/salt-states.git:
    - user: onorua
    - password: "megasecurepass"
    - base: testing
```
testing branch has following top.sls:
```
base:
  '*':
    #    - base
    - deploy.salt-minion
    - manage.debian-auto-upgrades
    - manage.bash-profile
    - manage.locale
    - manage.hosts
    - manage.resolver
    - manage.sysctl
    - manage.timezone
    - manage.users
    - manage.logrotate
    - manage.network
    - manage.static-routes
    #    - manage.sudo 
    - manage.floating-ip
```
top.sls from master branch looks like this:
```
base:
  '*':
    - base
    #    - debian-auto-upgrades
    - floating-ip
    - network
    - salt-minion
    - ntp
    - scheduler
    - master-files
```
I'm executing salt-call state.highstate, and expect that top.sls from `testing` branch will be taken but this is not was really happened:
```
local:
    Data failed to compile:
----------
    No matching sls found for 'floating-ip' in env 'base'
----------
    No matching sls found for 'base' in env 'base'
----------
    No matching sls found for 'floating-services' in env 'base'
....
```
what is also important is that, in debug mode it states:
```
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/dedicated-repo/top.sls:
base:
  '*':
    - base
    #    - debian-auto-upgrades
    - floating-ip
    - network
    - salt-minion
    - ntp
    - scheduler
    - master-files
```

I've tried to clean the cache:
```
salt-call saltutil.clear_cache
local:
    True
```
but no luck... it keeps coming from `master` branch. 
Am I doing something wrong?

**Comment by EvaSDK** [comment] 2016-02-22 11:36
What version are you using, this looks like the issue I am currently being confronted to:

```
# salt-master --versions-report
           Salt: 2015.5.9
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.0
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.2
```

**Comment by onorua** [comment] 2016-02-22 11:41
Sorry, forgot to mention:
```
OS: Ubuntu 15.04
 dpkg -l | grep salt
ii  salt-common                         2015.8.1+ds-1                     all          shared libraries that salt requires for all packages
ii  salt-master                         2015.8.1+ds-1                     all          remote manager to administer servers via salt
ii  salt-minion                         2015.8.1+ds-1                     all          client package for salt, the distributed remote execution system
```

**Comment by jfindlay** [comment] 2016-02-22 16:18
@onorua, thanks for reporting.  Have you tried setting [`top_file_merging_strategy: same`](https://docs.saltstack.com/en/latest/ref/states/top.html#how-top-files-are-compiled) in your master config?

**Comment by onorua** [comment] 2016-02-22 18:01
@jfindlay it actually solved my problem, but I still believe it is a bug, salt-master should not check "master" branch at all if I've instructed it to use testing. At least logic tells me so.

**Comment by jfindlay** [comment] 2016-02-22 23:06
@onorua, I agree.  Unfortunately, in 2015.8.0 the new top file handling options, `top_file_merging_strategy`, `env_order`, and `default_top`, are a change to the default merging behavior of top files and we are very wary of breaking users' installations with such backwards-incompatible changes.

**Comment by warden** [comment] 2016-02-23 00:07
I didn't agree with the explanation, because I too thought that using master with explicitly specified branch is counterintuitive - so I digged in the docs;) Here is the key to this behavior I guess:
https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#branches-environments-and-top-files
So, maybe this will actually fix that case?
```
gitfs_base: testing
```

**Comment by onorua** [comment] 2016-02-23 01:37
@warden looks like we have different understanding of the documentation, for me the line you showed means - if all of your repos have similar base branch you remap base -> yourbranch. But last sentence makes it vague:

> To map a branch other than master as the base environment, use the gitfs_base parameter.
> `gitfs_base: salt-base`
> The base can also be configured on a [per-remote basis](https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#gitfs-per-remote-config).
 
and `per-remote` is exactly what I've in my config posted above.

**Comment by warden** [comment] 2016-02-23 11:05
Actually I was referring to those and the example just below it:
"There is one exception to this rule: the master branch is implicitly mapped to the base environment.
top.sls files from different branches will be merged into one at runtime. Since this can lead to overly complex configurations, the recommended setup is to have a separate repository, containing only the top.sls file with just one single master branch."

But I do agree: a warning can be added in the docs, that in case only one remote is used, but with non-master branch, then master will be fetched anyway without this option.

**Comment by terminalmage** [comment] 2016-06-28 17:29
This is actually the same issue as #34302. See my comment [here](https://github.com/saltstack/salt/issues/34302#issuecomment-229118438) for the solution.

@warden you don't need to mess with your gitfs configuration, it is fine. There's no bug with ``master`` being implicitly mapped, the issue is simply the fact that on a highstate, by default _all_ environments' top files are parsed. In your configuration, the ``master`` branch would be the ``master`` environment, since the base has been explicitly set to point to ``testing``. So, changing the merging strategy will cause the highstate to ignore top files not in ``base``, making it ignore your ``master`` branch.

As noted in #34302, I will be improving the documentation to make this more clear. Apologies for the confusion on this.

**Comment by terminalmage** [comment] 2016-06-28 17:37
Apologies, I meant to direct my last comment to @onorua.

**Comment by onorua** [comment] 2016-06-29 18:15
As I've reported previously setting merging strategy solved our problem. I'm closing this one in favour of #34302

**Closed** 2016-06-29 18:16 UTC
Labels: Bug, Documentation, Duplicate, Medium Severity, P2

**Comment by terminalmage** [comment] 2016-06-29 18:28
Ahh... thanks, I overlooked that comment. :blush: 

It is definitely not a bug, it's intended behavior. We just need to get it better documented, something I plan to have done within the next couple days.

**Comment by terminalmage** [comment] 2016-07-07 03:13
Improved documentation and logging are submitted in #34505.

In the process of standing up a test environment I found another method that may help avoid this issue with multiple top files. Passing a ``saltenv`` parameter when running a highstate will only process the top file from that environment. It will also only run states from that environment, so if you only desire to run states from a single environment this is a guaranteed way to keep top files from other branches/tags from appearing in your highstate.
