### ISSUE TITLE
return values for modules

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#28433] opened 2015-10-30 10:01 UTC
hello

currently the modules if they run form OS CLI return always 0 regardless their sub process output. For example:
>[root@saltm01 ~]# salt 'host' pkg.version httpd;echo $?
>host:
>0
>[root@saltm01 ~]# salt 'host' pkg.version vim-common;echo $?
>host:
>    7.4.629-5.el6
>0
therefore the salt CLI can't be scripted by return values. 
I think it would be extremely good. With this feature lots things can be automated which doesn't require SLS files. 
real life example
for patching: Salt command will be executed but checking everything is working as expected is not an easy task unless salt has the correct checking module or hasn't.

**Comment by jfindlay** [comment] 2015-11-03 17:44
@BalintSzigeti, thanks for the report.  This is a duplicate of #18510.

**Closed by jfindlay** 2015-11-03 17:44 UTC
Labels: Duplicate
