### ISSUE TITLE
at.at creates job with different time than specified

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#42008] opened 2017-06-29 12:43 UTC
### Description of Issue/Question
I wanted to register reboot at 23:52 on Debian 8 (Jessie) minion, but instead I've got reboot at 14:32 (?).

### Setup

Only salt-minion needed.

### Steps to Reproduce Issue

Simply execute `salt-call at.at 23:52 rebot`:
```
# salt-call at.at 23:52 reboot
local:
    ----------
    jobs:
        |_
          ----------
          date:
              2017-06-30
          job:
              11
          queue:
              a
          tag:
          time:
              14:32:00
          user:
              root
```

Debug output:
```
2017-06-29 15:33:56,549 [salt.loaded.int.module.cmdmod][INFO    ][1255] Executing command ['/usr/bin/at', 1432] in directory '/root'
2017-06-29 15:33:56,575 [salt.loaded.int.module.cmdmod][DEBUG   ][1255] output: warning: commands will be executed using /bin/sh
job 14 at Fri Jun 30 14:32:00 2017
2017-06-29 15:33:56,576 [salt.loaded.int.module.cmdmod][INFO    ][1255] Executing command ['/usr/bin/atq'] in directory '/root'
2017-06-29 15:33:56,590 [salt.loaded.int.module.cmdmod][DEBUG   ][1255] stdout: 14	Fri Jun 30 14:32:00 2017 a root
```

Why does it pass "1432" to `at`?

If I execute `at` manually, I get expected result:
```
# echo "reboot" | at 23:52
warning: commands will be executed using /bin/sh
job 15 at Thu Jun 29 23:52:00 2017
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.8 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.8
```

**Comment by gtmanfred** [comment] 2017-06-29 16:41
This has to be an issue with salt's parser or something in that portion of salt, because when I throw a log.debug in at the top of the `at()` function, It has 1432.

But it is worth noting that `11:52pm` and `2352` without the colon both work.

Thanks for reporting!
Daniel

**Comment by CorvinM** [comment] 2017-07-14 04:11
Did some investigating and narrowed down the issue to the third party yaml library.

[Salt exit point](https://github.com/saltstack/salt/blob/develop/salt/utils/args.py#L128)

I doubt the following is intended behavior but this is what I get attempting to load '23:35' and some similar strings with the yaml library.
```Python
Python 2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.__version__
'3.12'
>>> yaml.load('23:35')
1415
>>> yaml.load('23:35:58:6434')
'23:35:58:6434'
>>> yaml.load('23:35:58:64')
'23:35:58:64'
>>> yaml.load('23:35:58')
84958
>>> yaml.load('23:35:00')
84900
>>> yaml.load('23:35:01')
84901
>>> yaml.load('23:35:10')
84910
>>> yaml.load('23:35:16')
84916
>>> yaml.load('23:35:20')
84920
>>> yaml.load('23:35:50')
84950
>>> yaml.load('23:35:90')
'23:35:90'
>>> yaml.load('23:35:80')
'23:35:80'
>>> yaml.load('23:35:70')
'23:35:70'
>>> yaml.load('23:35:60')
'23:35:60'
>>> yaml.load('23:35:50')
84950
>>> yaml.load('23:59')
1439
```

**Comment by gtmanfred** [comment] 2017-07-14 14:15
Yup, that would do it.

On Thu, Jul 13, 2017 at 10:11 PM, Corvin Mcpherson <notifications@github.com

**Comment by Talkless** [comment] 2018-11-16 21:08
Ping?
So is it fixable if Yaml does that?

**Comment by Talkless** [comment] 2018-11-19 08:47
So maybe documentation [0] should have example with double-quotes like `'"23:00"'` to demonstrate that edge case?

[0] https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.at.html

**Comment by Ch3LL** [comment] 2023-08-22 20:03
Closed by https://github.com/saltstack/salt/pull/65031

**Closed by Ch3LL** 2023-08-22 20:03 UTC
Labels: Bug, severity-low, Core
