### ISSUE TITLE
archive.extracted/file.managed source_hash format is invalid

### ISSUE THREAD

**Issue by bartuss7** [saltstack/salt#44086] opened 2017-10-13 06:55 UTC
### Description of Issue/Question
When I try to extract archive or use file.managed with source_hash url, state fails.
Error returns:
```
ID: archieve
    Function: archive.extracted
        Name: /tmp/
      Result: False
     Comment: Source hash http://192.168.1.5/storage/test/archive.md5 format is invalid. The supported formats are: 1) a hash, 2) an expression in the format <hash_type>=<hash>, or 3) either a path to a local file containing hashes, or a URI of a remote hash file. Supported protocols for remote hash files are: salt, file, http, https, ftp, swift, s3. The hash may also not be of a valid length, the following are supported hash types and lengths: md5 (32), sha1 (40), sha224 (56), sha256 (64), sha384 (96), sha512 (128).
     Started: 02:29:24.927676
    Duration: 197.943 ms
     Changes:   

```

Error occurs on linux, on windows works fine

### Steps to Reproduce Issue
test_hash.sls:
```
archieve:
  archive.extracted:
    - name: /tmp/
    - if_missing: /tmp/test
    - source: http://192.168.1.5/storage/test/archive.tar.gz
    - source_hash: http://192.168.1.5/storage/test/archive.md5
    - archive_format: tar
    - options: zx
    - enforce_toplevel: False

/tmp/zaq.conf:
  file.managed:
    - source: http://192.168.1.5/storage/test/zaq.conf
    - source_hash: http://192.168.1.5/storage/test/zaq.md5
    - backup: minion
```

Create simple archive (archive.tar.gz) and file zaq.conf
Create md5sum using:
```
md5sum archive.tar.gz > archive.md5
md5sum zaq.conf > zaq.md5
``` 

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by terminalmage** [comment] 2017-10-13 15:43
Can you set `log_level_logfile: debug`, restart the minion, and run the state again? Then, post the debug logging from /var/log/salt/minion. It looks like our hash extraction code isn't working properly, and this will help us narrow down why.

**Comment by gtmanfred** [comment] 2017-10-13 15:47
I am unable to replicate this.

```
[root@salt html]# dd if=/dev/random of=/usr/share/nginx/html/this.txt bs=4 count=8
8+0 records in
8+0 records out
32 bytes (32 B) copied, 0.000185613 s, 172 kB/s
[root@salt html]# md5sum /usr/share/nginx/html/this.txt > /usr/share/nginx/html/this.md5
[root@salt html]# cat /srv/salt/test.sls
/tmp/this.txt:
  file.managed:
    - source: http://localhost/this.txt
    - source_hash: http://localhost/this.md5
    - backup: minion

[root@salt html]# salt-call --local state.apply test
local:
----------
          ID: /tmp/this.txt
    Function: file.managed
      Result: True
     Comment: File /tmp/this.txt updated
     Started: 15:47:02.221272
    Duration: 27.743 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  27.743 ms
```

The debug log would be helpful.

Thanks,
Daniel

**Comment by bartuss7** [comment] 2017-10-16 06:46
@terminalmage, I set `log_level_logfile: debug` as you said.

```
2017-10-16 08:15:48,789 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master
2017-10-16 08:15:48,879 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/auto_accept.conf'
2017-10-16 08:15:48,879 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/auto_accept.conf
2017-10-16 08:15:48,880 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/ext_pillar.conf'
2017-10-16 08:15:48,880 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/ext_pillar.conf
2017-10-16 08:15:48,881 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/external_auth.conf'
2017-10-16 08:15:48,881 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/external_auth.conf
2017-10-16 08:15:48,883 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/file_roots.conf'
2017-10-16 08:15:48,883 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/file_roots.conf
2017-10-16 08:15:48,884 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/fileserver_backend.conf'
2017-10-16 08:15:48,884 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/fileserver_backend.conf
2017-10-16 08:15:48,885 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/gitfs_remotes.conf'
2017-10-16 08:15:48,885 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/gitfs_remotes.conf
2017-10-16 08:15:48,887 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/logs.conf'
2017-10-16 08:15:48,887 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/logs.conf
2017-10-16 08:15:48,888 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/nodegroups.conf'
2017-10-16 08:15:48,888 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/nodegroups.conf
2017-10-16 08:15:48,890 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/pillar_roots.conf'
2017-10-16 08:15:48,890 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/pillar_roots.conf
2017-10-16 08:15:48,891 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/presence.conf'
2017-10-16 08:15:48,891 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/presence.conf
2017-10-16 08:15:48,892 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/reactor.conf'
2017-10-16 08:15:48,892 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/reactor.conf
2017-10-16 08:15:48,893 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/rest_cherrypy.conf'
2017-10-16 08:15:48,893 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/rest_cherrypy.conf
2017-10-16 08:15:48,894 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/smtp.conf'
2017-10-16 08:15:48,894 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/smtp.conf
2017-10-16 08:15:48,896 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/winrepo_remotes_ng.conf'
2017-10-16 08:15:48,896 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/winrepo_remotes_ng.conf
2017-10-16 08:15:48,897 [salt.config      ][DEBUG   ][10018] Including configuration from '/etc/salt/master.d/worker_threads.conf'
2017-10-16 08:15:48,897 [salt.config      ][DEBUG   ][10018] Reading configuration from /etc/salt/master.d/worker_threads.conf
2017-10-16 08:15:48,898 [salt.config      ][DEBUG   ][10018] Using cached minion ID from /etc/salt/minion_id: salt.testdomain
2017-10-16 08:15:48,899 [salt.config      ][DEBUG   ][10018] Missing configuration file: /root/.saltrc
2017-10-16 08:15:48,900 [salt.utils.event ][DEBUG   ][10018] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2017-10-16 08:15:48,900 [salt.utils.event ][DEBUG   ][10018] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2017-10-16 08:15:49,189 [salt.transport.zeromq][DEBUG   ][10018] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt.testdomain', 'tcp://127.0.0.1:4506', 'clear')
2017-10-16 08:15:49,190 [salt.transport.ipc][DEBUG   ][10018] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
2017-10-16 08:15:49,195 [salt.utils.lazy  ][DEBUG   ][8103] LazyLoaded local_cache.prep_jid
2017-10-16 08:15:49,196 [salt.transport.ipc][DEBUG   ][8103] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
2017-10-16 08:15:49,197 [salt.utils.event ][DEBUG   ][8103] Sending event: tag = 20171016081549195993; data = {'_stamp': '2017-10-16T06:15:49.197446', 'minions': ['test_server.test_domain']}
2017-10-16 08:15:49,198 [salt.utils.reactor][DEBUG   ][8084] Gathering reactors for tag 20171016081549195993
2017-10-16 08:15:49,199 [salt.utils.event ][DEBUG   ][8103] Sending event: tag = salt/job/20171016081549195993/new; data = {'tgt_type': 'glob', 'jid': '20171016081549195993', 'tgt': 'test_server.test_domain', '_stamp': '2017-10-16T06:15:49.199359', 'user': 'root', 'arg': ['test_hash'], 'fun': 'state.apply', 'minions': ['test_server.test_domain']}
2017-10-16 08:15:49,200 [salt.utils.reactor][DEBUG   ][8084] Gathering reactors for tag salt/job/20171016081549195993/new
2017-10-16 08:15:49,201 [salt.loaded.int.returner.local_cache][DEBUG   ][8103] Adding minions for job 20171016081549195993: ['test_server.test_domain']
2017-10-16 08:15:49,201 [salt.master      ][INFO    ][8103] User root Published command state.apply with jid 20171016081549195993
2017-10-16 08:15:49,201 [salt.master      ][DEBUG   ][8103] Published command details {'tgt_type': 'glob', 'jid': '20171016081549195993', 'tgt': 'test_server.test_domain', 'ret': '', 'user': 'root', 'arg': ['test_hash'], 'fun': 'state.apply'}
2017-10-16 08:15:49,201 [salt.transport.zeromq][DEBUG   ][8103] Signing data packet
2017-10-16 08:15:49,202 [salt.crypt       ][DEBUG   ][8103] salt.crypt._get_rsa_key: Loading private key
2017-10-16 08:15:49,202 [salt.crypt       ][DEBUG   ][8103] salt.crypt._get_key_with_evict: Loading private key
2017-10-16 08:15:49,203 [salt.crypt       ][DEBUG   ][8103] salt.crypt.sign_message: Signing message.
2017-10-16 08:15:49,215 [salt.utils.lazy  ][DEBUG   ][10018] LazyLoaded local_cache.get_load
2017-10-16 08:15:49,216 [salt.loaded.int.returner.local_cache][DEBUG   ][10018] Reading minion list from /var/cache/salt/master/jobs/c3/00c3ef3f411a8805e82b50077cd5075ac8dd1cd4babe59f1dff904dee16aac/.minion
s.p
2017-10-16 08:15:49,216 [salt.client      ][DEBUG   ][10018] get_iter_returns for jid 20171016081549195993 sent to set(['test_server.test_domain']) will timeout at 08
:15:54.216591
2017-10-16 08:15:49,939 [salt.pillar      ][DEBUG   ][8106] Determining pillar cache
2017-10-16 08:15:49,970 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded jinja.render
2017-10-16 08:15:49,971 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded yaml.render
2017-10-16 08:15:49,980 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded git.ext_pillar
2017-10-16 08:15:49,980 [py.warnings      ][WARNING ][8106] /usr/lib/python2.7/dist-packages/salt/pillar/git_pillar.py:742: DeprecationWarning: The git ext_pillar configuration is deprecated. Please refer to the documentation at https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html for more information. This configuration will no longer be supported as of the Oxygen release of Salt.

2017-10-16 08:15:49,993 [salt.loaded.int.pillar.git_pillar][DEBUG   ][8106] Legacy git_pillar: pillar_dir for 'master git@github.com:XXX/pillar.git' is '/var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d'
2017-10-16 08:15:49,994 [salt.loaded.int.pillar.git_pillar][DEBUG   ][8106] Legacy git_pillar: branch for 'master git@github.com:XXX/pillar.git' is 'master'
2017-10-16 08:15:50,027 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded jinja.render
2017-10-16 08:15:50,027 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded yaml.render
2017-10-16 08:15:50,035 [salt.template    ][DEBUG   ][8106] compile template: /var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d/top.sls
2017-10-16 08:15:50,036 [salt.utils.jinja ][DEBUG   ][8106] Jinja search path: ['/var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d']
2017-10-16 08:15:50,042 [salt.template    ][PROFILE ][8106] Time (in seconds) to render '/var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d/top.sls' using 'jinja' renderer: 0.00655198097229
2017-10-16 08:15:50,043 [salt.template    ][DEBUG   ][8106] Rendered data from file: /var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d/top.sls:
2017-10-16 08:15:49,970 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded jinja.render
2017-10-16 08:15:49,971 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded yaml.render
2017-10-16 08:15:49,980 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded git.ext_pillar
2017-10-16 08:15:49,980 [py.warnings      ][WARNING ][8106] /usr/lib/python2.7/dist-packages/salt/pillar/git_pillar.py:742: DeprecationWarning: The git ext_pillar configuration is deprecated. Please refer to the documentation at https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html for more information. This configuration will no longer be supported as of the Oxygen release of Salt.

2017-10-16 08:15:49,993 [salt.loaded.int.pillar.git_pillar][DEBUG   ][8106] Legacy git_pillar: pillar_dir for 'master git@github.com:XXX/pillar.git' is '/var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d'
2017-10-16 08:15:49,994 [salt.loaded.int.pillar.git_pillar][DEBUG   ][8106] Legacy git_pillar: branch for 'master git@github.com:XXX/pillar.git' is 'master'
2017-10-16 08:15:50,027 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded jinja.render
2017-10-16 08:15:50,027 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded yaml.render
2017-10-16 08:15:50,035 [salt.template    ][DEBUG   ][8106] compile template: /var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d/top.sls
2017-10-16 08:15:50,036 [salt.utils.jinja ][DEBUG   ][8106] Jinja search path: ['/var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d']
2017-10-16 08:15:50,042 [salt.template    ][PROFILE ][8106] Time (in seconds) to render '/var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d/top.sls' using 'jinja' renderer: 0.00655198097229
base:
  'roles:ceph_client':
     - match: grain
     - ceph
2017-10-16 08:15:50,054 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded config.get
2017-10-16 08:15:50,054 [salt.loaded.int.render.yaml][DEBUG   ][8106] Results of YAML rendering: 
OrderedDict([('base', OrderedDict([('roles:ceph_client', [OrderedDict([('match', 'grain')]), 'ceph']))])
2017-10-16 08:15:50,054 [salt.template    ][PROFILE ][8106] Time (in seconds) to render '/var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d/top.sls' using 'yaml' renderer: 0.0114929676056
2017-10-16 08:15:50,056 [salt.minion      ][DEBUG   ][8106] grains target: roles:ceph_client
2017-10-16 08:15:50,056 [salt.utils       ][DEBUG   ][8106] Attempting to match 'ceph_client' in 'roles' using delimiter ':'
2017-10-16 08:15:50,056 [salt.minion      ][DEBUG   ][8106] compound_match: test_server.test_domain ? *
2017-10-16 08:15:50,057 [salt.minion      ][DEBUG   ][8106] compound_match test_server.test_domain ? "*" => "True"
2017-10-16 08:15:50,059 [salt.template    ][DEBUG   ][8106] compile template: /var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d/functional_id.sls
2017-10-16 08:15:50,059 [salt.utils.jinja ][DEBUG   ][8106] Jinja search path: ['/var/cache/salt/master/pillar_gitfs/dccefc1a09876a87212b6172ee0dea2756d5581c6899b17198a2019fe963f75d']
2017-10-16 08:15:50,092 [salt.utils.lazy  ][DEBUG   ][8106] LazyLoaded localfs.init_kwargs
2017-10-16 08:15:50,093 [salt.utils.event ][DEBUG   ][8106] Sending event: tag = minion/refresh/test_server.test_domain; data = {'Minion data cache refresh': 'test_server.test_domain', '_stamp': '2017-10-16T06:15:50.093761'}
2017-10-16 08:15:50,095 [salt.utils.reactor][DEBUG   ][8084] Gathering reactors for tag minion/refresh/test_server.test_domain
2017-10-16 08:15:50,261 [salt.utils.job   ][INFO    ][8108] Got return from test_server.test_domain for job 20171016081549195993
2017-10-16 08:15:50,262 [salt.utils.event ][DEBUG   ][8108] Sending event: tag = salt/job/20171016081549195993/ret/test_server.test_domain; data = {'fun_args': ['test_hash'], 'jid': '20171016081549195993', 'return': {'archive_|-archieve_|-/tmp/_|-extracted': {'comment': 'Source hash http://192.168.1.5/storage/test/archive.md5 format is invalid. The supported formats are
: 1) a hash, 2) an expression in the format <hash_type>=<hash>, or 3) either a path to a local file containing hashes, or a URI of a remote hash file. Supported protocols for remote hash files are: salt, fi
le, http, https, ftp, swift, s3. The hash may also not be of a valid length, the following are supported hash types and lengths: md5 (32), sha1 (40), sha224 (56), sha256 (64), sha384 (96), sha512 (128).', '
name': '/tmp/', 'start_time': '02:15:50.182644', 'result': False, 'duration': 26.941, '__run_num__': 0, '__sls__': 'test_hash', 'changes': {}, '__id__': 'archieve'}, 'file_|-/tmp/zaq.conf_|-/tmp/zaq.conf_|-
managed': {'comment': 'Source hash http://192.168.1.5/storage/test/zaq.md5 format is invalid. The supported formats are: 1) a hash, 2) an expression in the format <hash_type>=<hash>, or 3) either a path to 
a local file containing hashes, or a URI of a remote hash file. Supported protocols for remote hash files are: salt, file, http, https, ftp, swift, s3. The hash may also not be of a valid length, the follow
ing are supported hash types and lengths: md5 (32), sha1 (40), sha224 (56), sha256 (64), sha384 (96), sha512 (128).', 'pchanges': {}, 'name': '/tmp/zaq.conf', 'start_time': '02:15:50.241531', 'result': Fals
e, 'duration': 8.814, '__run_num__': 1, '__sls__': 'test_hash', 'changes': {}, '__id__': '/tmp/zaq.conf'}}, 'retcode': 2, 'success': True, 'cmd': '_return', '_stamp': '2017-10-16T06:15:50.261915', 'fun': 's
tate.apply', 'id': 'test_server.test_domain', 'out': 'highstate'}
2017-10-16 08:15:50,264 [salt.client      ][DEBUG   ][10018] jid 20171016081549195993 return from test_server.test_domain
2017-10-16 08:15:50,264 [salt.client      ][DEBUG   ][10018] return event: {'test_server.test_domain': {'jid': '20171016081549195993', 'retcode': 2, 'ret': {'archive_|-archieve_|-/tmp/_|-extracted': {'comment': 'Source hash http://192.168.1.5/storage/test/archive.md5 format is invalid. The supported formats are: 1) a hash, 2) an expression in the format <hash_type>=<has
h>, or 3) either a path to a local file containing hashes, or a URI of a remote hash file. Supported protocols for remote hash files are: salt, file, http, https, ftp, swift, s3. The hash may also not be of
 a valid length, the following are supported hash types and lengths: md5 (32), sha1 (40), sha224 (56), sha256 (64), sha384 (96), sha512 (128).', 'name': '/tmp/', 'start_time': '02:15:50.182644', 'result': F
alse, 'duration': 26.941, '__run_num__': 0, '__sls__': 'test_hash', 'changes': {}, '__id__': 'archieve'}, 'file_|-/tmp/zaq.conf_|-/tmp/zaq.conf_|-managed': {'comment': 'Source hash http://192.168.1.5/storag
e/test/zaq.md5 format is invalid. The supported formats are: 1) a hash, 2) an expression in the format <hash_type>=<hash>, or 3) either a path to a local file containing hashes, or a URI of a remote hash fi
le. Supported protocols for remote hash files are: salt, file, http, https, ftp, swift, s3. The hash may also not be of a valid length, the following are supported hash types and lengths: md5 (32), sha1 (40
), sha224 (56), sha256 (64), sha384 (96), sha512 (128).', 'pchanges': {}, 'name': '/tmp/zaq.conf', 'start_time': '02:15:50.241531', 'result': False, 'duration': 8.814, '__run_num__': 1, '__sls__': 'test_has
h', 'changes': {}, '__id__': '/tmp/zaq.conf'}}, 'out': 'highstate'}}
2017-10-16 08:15:50,268 [salt.utils.lazy  ][DEBUG   ][10018] LazyLoaded highstate.output
2017-10-16 08:15:50,270 [salt.utils.reactor][DEBUG   ][8084] Gathering reactors for tag salt/job/20171016081549195993/ret/test_server.test_domain
2017-10-16 08:15:50,375 [salt.client      ][DEBUG   ][10018] jid 20171016081549195993 found all minions set(['test_server.test_domain'])
2017-10-16 08:16:24,633 [salt.config      ][DEBUG   ][8085] Reading configuration from /etc/salt/master
2017-10-16 08:16:24,744 [salt.config      ][DEBUG   ][8085] Using cached minion ID from /etc/salt/minion_id: salt.test_domain
2017-10-16 08:16:24,745 [salt.config      ][DEBUG   ][8085] Reading configuration from /etc/salt/master
2017-10-16 08:16:24,851 [salt.config      ][DEBUG   ][8085] Including configuration from '/etc/salt/master.d/auto_accept.conf'
2017-10-16 08:16:24,851 [salt.config      ][DEBUG   ][8085] Reading configuration from /etc/salt/master.d/auto_accept.conf

```

**Comment by bartuss7** [comment] 2017-10-18 14:09
@terminalmage @gtmanfred Any updates?

**Comment by maltris** [comment] 2017-10-25 07:14
I am able to confirm this with the Ubuntu archive:

```
   file.managed:
     - name: /test/trusty/initrd.gz
     - source: http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/initrd.gz
    - source_hash: http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/SHA256SUMS
     - source_hash_name: ./netboot/ubuntu-installer/amd64/initrd.gz
```

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-97-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by maltris** [comment] 2017-10-30 12:33
Hello, 

is there any solution/update in sight?

Cheers

**Comment by gtmanfred** [comment] 2017-10-30 15:27
What are the contents of http://192.168.1.5/storage/test/zaq.md5 ?

Again, I have been unable to replicate this, so if you can provide me with simple contents of a file that replicates this, that would be greatly appreciated.

**Comment by maltris** [comment] 2017-11-03 07:42
Sure, 

this is the file with its contents:

http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/initrd.gz

This is the list with the hashes (it also contains the hash for ./netboot/ubuntu-installer/amd64/initrd.gz): 

http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/SHA256SUMS

**Comment by maltris** [comment] 2017-11-13 11:03
Hello, sorry for bumping, but it has been 10 days now. Is there any progress on this?

**Comment by maltris** [comment] 2017-11-23 07:57
Hello, sorry for bumping, but it has been 20 days now. Is there any progress on this?

**Comment by terminalmage** [comment] 2017-11-25 03:33
I can reproduce this in 2017.7.2, but not on the head of the `2017.7` branch (which will become 2017.7.3 once we are ready to release it).

It seems that there was a regression, but it has since been fixed.

```
(git) d6ccf4bb  2017.7 [upstream/2017.7]
erik ~/git/salt/main                                                    [21:29:41]
(⌐■_■) % git checkout v2017.7.2
Note: checking out 'v2017.7.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 80d90307b0... Don't allow path separators in minion ID
(git) 80d90307  v2017.7.2
erik ~/git/salt/main                                                    [21:29:49]
(⌐■_■) % sudo find . -type f -name \*.pyc -delete
(git) 80d90307  v2017.7.2
erik ~/git/salt/main                                                    [21:29:52]
(⌐■_■) % docker run --rm -v $PWD:/testing terminalmage/issues:44086 salt-call state.apply test
[ERROR   ] Source hash http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/SHA256SUMS format is invalid. The supported formats are: 1) a hash, 2) an expression in the format <hash_type>=<hash>, or 3) either a path to a local file containing hashes, or a URI of a remote hash file. Supported protocols for remote hash files are: salt, file, http, https, ftp, swift, s3. The hash may also not be of a valid length, the following are supported hash types and lengths: md5 (32), sha1 (40), sha224 (56), sha256 (64), sha384 (96), sha512 (128).
local:
----------
          ID: /tmp/initrd.gz
    Function: file.managed
      Result: False
     Comment: Source hash http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/SHA256SUMS format is invalid. The supported formats are: 1) a hash, 2) an expression in the format <hash_type>=<hash>, or 3) either a path to a local file containing hashes, or a URI of a remote hash file. Supported protocols for remote hash files are: salt, file, http, https, ftp, swift, s3. The hash may also not be of a valid length, the following are supported hash types and lengths: md5 (32), sha1 (40), sha224 (56), sha256 (64), sha384 (96), sha512 (128).
     Started: 03:30:28.616681
    Duration: 467.443 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 467.443 ms
(git) 80d90307  v2017.7.2
erik ~/git/salt/main                                                    [21:30:30]
(⌐■_■) % git checkout 2017.7
Previous HEAD position was 80d90307b0... Don't allow path separators in minion ID
Switched to branch '2017.7'
Your branch is up to date with 'upstream/2017.7'.
(git) d6ccf4bb  2017.7 [upstream/2017.7]
erik ~/git/salt/main                                                    [21:31:09]
(⌐■_■) % docker run --rm -v $PWD:/testing terminalmage/issues:44086 salt-call state.apply test
local:
----------
          ID: /tmp/initrd.gz
    Function: file.managed
      Result: True
     Comment: File /tmp/initrd.gz updated
     Started: 03:31:22.809000
    Duration: 12570.065 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  12.570 s
```

**Comment by theWizK** [comment] 2018-01-16 16:55
Any update on when this fix will be released?  I'm affected by this on version 2017.7.2.

**Comment by gtmanfred** [comment] 2018-01-16 17:14
We are working on a release for 2017.7.3 now, it is branched, we just need to get it tested and stable and then it will be released.

**Comment by dumol** [comment] 2018-02-07 10:58
2017.7.3 fixes this for me.

**Comment by rallytime** [comment] 2018-02-07 14:39
@dumol Thanks for confirming. I'll go ahead and close this.

**Closed by rallytime** 2018-02-07 14:39 UTC
Labels: Info Needed
