### ISSUE TITLE
salt-key command raises an exception everytime on >=2014.7.2

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#19559] opened 2015-01-09 07:09 UTC
Running the latest master and minion from develop. Here's the versions report:
```
root@nitin-salt-develop:~$ salt-call --versions-report
           Salt: 2015.2.0-531-g6b24117
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

Here's the exception:
```
root@nitin-salt-develop:~$ salt-key -L
Accepted Keys:
nitin-salt-develop
Denied Keys:
Unaccepted Keys:
Rejected Keys:
Exception TypeError: 'an integer is required' in <bound method MasterEvent.__del__ of <salt.utils.event.MasterEvent object at 0x2afb350>> ignored
```

Here's the OS release information:
```
root@nitin-salt-develop:~$ cat /etc/system-release
Red Hat Enterprise Linux Server release 6.6 (Santiago)
```

**Comment by jfindlay** [comment] 2015-01-09 16:13
Thanks, @nmadhok, I've seen this as well.

**Comment by jfindlay** [comment] 2015-01-09 22:21
This is also happening on 2014.7 as well; I'm going to change the title to reflect this.

**Comment by rallytime** [comment] 2015-01-09 22:38
This is actually a duplicate of #19216. I'm going to close this one if favor of that one since it was filed first.

**Closed by rallytime** 2015-01-09 22:38 UTC
Labels: Bug, Confirmed, Duplicate, Medium Severity

**Comment by nmadhok** [comment] 2015-01-10 05:48
@rallytime No problem!
