### ISSUE TITLE
Remount forced with lizardfs fuse filesystem due to device missmatch

### ISSUE THREAD

**Issue by alexharrington** [saltstack/salt#39269] opened 2017-02-09 05:52 UTC
### Description of Issue/Question
I'm in the process of upgrading to 2016.11.2 (master and minion in question are upgraded to these versions) from 2015.8 but I have an issue where my lizardfs fuse mounts are always remounted. 2015.8 did this historically, but I was hoping I'd be able to stop that with the newer salt version.

When I run my mount.mounted state, I get:

> Forced unmount because devices don't match. Wanted: mfsmount, current: mfs#mfsmaster:9421, /mfs#mfsmaster:9421

### Setup
My mount SLS looks like this:

```
lizardfs-example-mount:
  mount.mounted:
    - fstype: fuse
    - mkmnt: True
    - opts: mfsdelayedinit,mfssubfolder=/path/to/directory,mfswritecachesize=5000,mfsioretries=20,_netdev
    - hidden_opts: mfsdelayedinit,mfssubfolder,mfsioretries
    - persist: False
    - device: mfsmount
    - name: /mnt/example
    - require:
      - pkg: lizardfs-client
    - device_name_regex:
      - mfs#mfsmaster:.*
```

I've tried various things in the device_name_regex field to try and persuade it that it is correct. I've tried directly putting what it says it's expecting - ie `mfs#mfsmaster:9421, /mfs#mfsmaster:9421`, and I've also tried things like just `mfs.*` since I think that should match anything starting mfs?

### Versions Report
Master
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-107-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment] 2017-02-09 15:15
My guess is that the : on the line is causing yaml to freak out.

Can you quote the string?

```
lizardfs-example-mount:
  mount.mounted:
    - fstype: fuse
    - mkmnt: True
    - opts: mfsdelayedinit,mfssubfolder=/path/to/directory,mfswritecachesize=5000,mfsioretries=20,_netdev
    - hidden_opts: mfsdelayedinit,mfssubfolder,mfsioretries
    - persist: False
    - device: mfsmount
    - name: /mnt/example
    - require:
      - pkg: lizardfs-client
    - device_name_regex:
      - "mfs#mfsmaster:.*"
```

**Comment by gtmanfred** [comment] 2017-02-09 15:16
Can you provide the debug log from the minion when you run this state with `salt-call`?

And also the output of /etc/mtab?

Thanks,
Daniel

**Comment by alexharrington** [comment] 2017-02-09 15:34
I tried adding the double quotes as suggested and that doesn't seem to make any difference.

Hopefully the output you wanted below. Thank you :)

/etc/mtab:
```
/dev/md0 / ext4 rw,errors=remount-ro 0 0
proc /proc proc rw,noexec,nosuid,nodev 0 0
sysfs /sys sysfs rw,noexec,nosuid,nodev 0 0
none /sys/fs/cgroup tmpfs rw 0 0
none /sys/fs/fuse/connections fusectl rw 0 0
none /sys/kernel/debug debugfs rw 0 0
none /sys/kernel/security securityfs rw 0 0
udev /dev devtmpfs rw,mode=0755 0 0
devpts /dev/pts devpts rw,noexec,nosuid,gid=5,mode=0620 0 0
tmpfs /run tmpfs rw,noexec,nosuid,size=10%,mode=0755 0 0
none /run/lock tmpfs rw,noexec,nosuid,nodev,size=5242880 0 0
none /run/shm tmpfs rw,nosuid,nodev 0 0
none /run/user tmpfs rw,noexec,nosuid,nodev,size=104857600,mode=0755 0 0
none /sys/fs/pstore pstore rw 0 0
tracefs /var/lib/ureadahead/debugfs/tracing tracefs rw,relatime 0 0
systemd /sys/fs/cgroup/systemd cgroup rw,noexec,nosuid,nodev,none,name=systemd 0 0
/dev/mapper/data0 /data/0 ext4 rw,noatime,nodiratime 0 0
/dev/mapper/data1 /data/1 ext4 rw,noatime,nodiratime 0 0
mfs#mfsmaster:9421 /mnt fuse rw,allow_other,default_permissions 0 0
mfs#mfsmaster:9421 /storage fuse rw,allow_other,default_permissions 0 0
```

Log:
```
[INFO    ] Running state [/storage] at time 15:23:37.916125
[INFO    ] Executing state mount.mounted for /storage
[INFO    ] Executing command 'mount -l' in directory '/root'
[DEBUG   ] stdout: /dev/md0 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)   
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
tracefs on /var/lib/ureadahead/debugfs/tracing type tracefs (rw,relatime)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
/dev/mapper/data0 on /data/0 type ext4 (rw,noatime,nodiratime)
/dev/mapper/data1 on /data/1 type ext4 (rw,noatime,nodiratime)
mfs#mfsmaster:9421 on /storage type fuse (rw,allow_other,default_permissions)
mfs#mfsmaster:9421 on /mnt type fuse (rw,allow_other,default_permissions)
[INFO    ] Executing command 'blkid' in directory '/root'
[DEBUG   ] stdout: /dev/sda3: UUID="8d0bdc6c-4b7d-48d2-b5d8-34acab588c68" TYPE="crypto_LUKS"
/dev/sdb3: UUID="d5e5b3f2-7a86-45c8-929b-82566d1ac58a" TYPE="crypto_LUKS" 
/dev/sda1: UUID="fa7e2d62-a1be-e2d4-ad34-06c2638ced2d" UUID_SUB="6e760424-bc27-6c8d-9200-1d0606ca0d7c" LABEL="d:0" TYPE="linux_raid_member"
/dev/sda2: UUID="e77617f6-6d58-4eed-a1df-ab0f575a1876" TYPE="swap" 
/dev/sdb1: UUID="fa7e2d62-a1be-e2d4-ad34-06c2638ced2d" UUID_SUB="fac8ee44-e6d1-901e-e30e-98d9f261d9cf" LABEL="d:0" TYPE="linux_raid_member"
/dev/sdb2: UUID="4b2dfaf7-c502-4f7f-be89-b1331eeffa38" TYPE="swap" 
/dev/md0: UUID="3825e5f5-8653-439d-85b4-6173d3ed3680" TYPE="ext4"  
/dev/mapper/data0: UUID="7b451633-5513-4089-b3da-0aa48e666eea" TYPE="ext4"
/dev/mapper/data1: UUID="73cb05f7-e362-4dd5-814a-ce5fb2f05e0d" TYPE="ext4"
[INFO    ] Executing command 'mount -l' in directory '/root'
[DEBUG   ] stdout: /dev/md0 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)   
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
tracefs on /var/lib/ureadahead/debugfs/tracing type tracefs (rw,relatime)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
/dev/mapper/data0 on /data/0 type ext4 (rw,noatime,nodiratime)
/dev/mapper/data1 on /data/1 type ext4 (rw,noatime,nodiratime)
mfs#mfsmaster:9421 on /storage type fuse (rw,allow_other,default_permissions)
mfs#mfsmaster:9421 on /mnt type fuse (rw,allow_other,default_permissions)
[INFO    ] Executing command 'umount /storage' in directory '/root'
[INFO    ] Executing command 'mount -o mfsdelayedinit,mfssubfolder=/,mfswritecachesize=128,mfsioretries=30,_netdev -t fuse mfsmount /storage ' in directory '/root'
[DEBUG   ] stderr: [ OK ] registered to master with new session (id #1971)
[ OK ] Received IO limits configuration update from master
[INFO    ] Executing command 'mount -l' in directory '/root'
[DEBUG   ] stdout: /dev/md0 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)   
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
tracefs on /var/lib/ureadahead/debugfs/tracing type tracefs (rw,relatime)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
/dev/mapper/data0 on /data/0 type ext4 (rw,noatime,nodiratime)
/dev/mapper/data1 on /data/1 type ext4 (rw,noatime,nodiratime)
mfs#mfsmaster:9421 on /mnt type fuse (rw,allow_other,default_permissions)
mfs#mfsmaster:9421 on /storage type fuse (rw,allow_other,default_permissions)
[INFO    ] Executing command 'umount /storage' in directory '/root'
[INFO    ] Executing command 'mount -o mfsdelayedinit,mfssubfolder=/,mfswritecachesize=128,mfsioretries=30,_netdev -t fuse mfsmount /storage ' in directory '/root'
[DEBUG   ] stderr: [ OK ] registered to master with new session (id #1972)
[ OK ] Received IO limits configuration update from master
[INFO    ] Executing command 'mount -l' in directory '/root'
[DEBUG   ] stdout: /dev/md0 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)   
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
tracefs on /var/lib/ureadahead/debugfs/tracing type tracefs (rw,relatime)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
/dev/mapper/data0 on /data/0 type ext4 (rw,noatime,nodiratime)
/dev/mapper/data1 on /data/1 type ext4 (rw,noatime,nodiratime)
mfs#mfsmaster:9421 on /mnt type fuse (rw,allow_other,default_permissions)
mfs#mfsmaster:9421 on /storage type fuse (rw,allow_other,default_permissions)
[INFO    ] Executing command 'umount /storage' in directory '/root'
[INFO    ] Executing command 'mount -o mfsdelayedinit,mfssubfolder=/,mfswritecachesize=128,mfsioretries=30,_netdev -t fuse mfsmount /storage ' in directory '/root'
[DEBUG   ] stderr: [ OK ] registered to master with new session (id #1973)
[ OK ] Received IO limits configuration update from master
[INFO    ] Executing command 'mount -l' in directory '/root'
[DEBUG   ] stdout: /dev/md0 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)   
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
tracefs on /var/lib/ureadahead/debugfs/tracing type tracefs (rw,relatime)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
/dev/mapper/data0 on /data/0 type ext4 (rw,noatime,nodiratime)
/dev/mapper/data1 on /data/1 type ext4 (rw,noatime,nodiratime)
mfs#mfsmaster:9421 on /mnt type fuse (rw,allow_other,default_permissions)
mfs#mfsmaster:9421 on /storage type fuse (rw,allow_other,default_permissions)
[INFO    ] Executing command 'umount /storage' in directory '/root'
[INFO    ] Executing command 'mount -l' in directory '/root'
[DEBUG   ] stdout: /dev/md0 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)   
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
tracefs on /var/lib/ureadahead/debugfs/tracing type tracefs (rw,relatime)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
/dev/mapper/data0 on /data/0 type ext4 (rw,noatime,nodiratime)
/dev/mapper/data1 on /data/1 type ext4 (rw,noatime,nodiratime)
mfs#mfsmaster:9421 on /mnt type fuse (rw,allow_other,default_permissions)
[INFO    ] Executing command 'blkid' in directory '/root'
[DEBUG   ] stdout: /dev/sda3: UUID="8d0bdc6c-4b7d-48d2-b5d8-34acab588c68" TYPE="crypto_LUKS"
/dev/sdb3: UUID="d5e5b3f2-7a86-45c8-929b-82566d1ac58a" TYPE="crypto_LUKS" 
/dev/sda1: UUID="fa7e2d62-a1be-e2d4-ad34-06c2638ced2d" UUID_SUB="6e760424-bc27-6c8d-9200-1d0606ca0d7c" LABEL="d:0" TYPE="linux_raid_member"
/dev/sda2: UUID="e77617f6-6d58-4eed-a1df-ab0f575a1876" TYPE="swap" 
/dev/sdb1: UUID="fa7e2d62-a1be-e2d4-ad34-06c2638ced2d" UUID_SUB="fac8ee44-e6d1-901e-e30e-98d9f261d9cf" LABEL="d:0" TYPE="linux_raid_member"
/dev/sdb2: UUID="4b2dfaf7-c502-4f7f-be89-b1331eeffa38" TYPE="swap" 
/dev/md0: UUID="3825e5f5-8653-439d-85b4-6173d3ed3680" TYPE="ext4"  
/dev/mapper/data0: UUID="7b451633-5513-4089-b3da-0aa48e666eea" TYPE="ext4"
/dev/mapper/data1: UUID="73cb05f7-e362-4dd5-814a-ce5fb2f05e0d" TYPE="ext4"
[INFO    ] Executing command 'mount -o mfsdelayedinit,mfssubfolder=/,mfswritecachesize=128,mfsioretries=30,_netdev -t fuse mfsmount /storage ' in directory '/root'
[DEBUG   ] stderr: [ OK ] registered to master with new session (id #1974)
[ OK ] Received IO limits configuration update from master
[INFO    ] Executing command 'mount -l' in directory '/root'
[DEBUG   ] stdout: /dev/md0 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)   
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
tracefs on /var/lib/ureadahead/debugfs/tracing type tracefs (rw,relatime)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
/dev/mapper/data0 on /data/0 type ext4 (rw,noatime,nodiratime)
/dev/mapper/data1 on /data/1 type ext4 (rw,noatime,nodiratime)
mfs#mfsmaster:9421 on /mnt type fuse (rw,allow_other,default_permissions)
mfs#mfsmaster:9421 on /storage type fuse (rw,allow_other,default_permissions)
[INFO    ] Executing command 'blkid' in directory '/root'
[DEBUG   ] stdout: /dev/sda3: UUID="8d0bdc6c-4b7d-48d2-b5d8-34acab588c68" TYPE="crypto_LUKS"
/dev/sdb3: UUID="d5e5b3f2-7a86-45c8-929b-82566d1ac58a" TYPE="crypto_LUKS" 
/dev/sda1: UUID="fa7e2d62-a1be-e2d4-ad34-06c2638ced2d" UUID_SUB="6e760424-bc27-6c8d-9200-1d0606ca0d7c" LABEL="d:0" TYPE="linux_raid_member"
/dev/sda2: UUID="e77617f6-6d58-4eed-a1df-ab0f575a1876" TYPE="swap" 
/dev/sdb1: UUID="fa7e2d62-a1be-e2d4-ad34-06c2638ced2d" UUID_SUB="fac8ee44-e6d1-901e-e30e-98d9f261d9cf" LABEL="d:0" TYPE="linux_raid_member"
/dev/sdb2: UUID="4b2dfaf7-c502-4f7f-be89-b1331eeffa38" TYPE="swap" 
/dev/md0: UUID="3825e5f5-8653-439d-85b4-6173d3ed3680" TYPE="ext4"  
/dev/mapper/data0: UUID="7b451633-5513-4089-b3da-0aa48e666eea" TYPE="ext4"
/dev/mapper/data1: UUID="73cb05f7-e362-4dd5-814a-ce5fb2f05e0d" TYPE="ext4"
[INFO    ] {'mount': True, 'umount': "Forced unmount because devices don't match. Wanted: mfsmount, current: mfs#mfsmaster:9421, /root/mfs#mfsmaster:9421"}
[INFO    ] Completed state [/storage] at time 15:23:38.367947 duration_in_ms=451.819
```

**Comment by gtmanfred** [comment] 2017-02-09 15:40
I know the problem.  We ran across this the other day, and I believe it was fixed in 2016.11 branch for 2016.11.3

**Comment by gtmanfred** [comment] 2017-02-09 15:41
https://github.com/saltstack/salt/issues/39106#issuecomment-276958303 I will submit a PR.

**Comment by alexharrington** [comment] 2017-02-09 15:45
Thank you

**Comment by gtmanfred** [comment] 2017-02-09 15:46
Should be fixed by https://github.com/saltstack/salt/pull/39276

Thanks for reporting so I didn't forget about it!
Daniel

**Comment by gtmanfred** [comment] 2017-02-09 15:47
I am going to mark this as a duplicate of #39106

**Closed by gtmanfred** 2017-02-09 15:47 UTC
Labels: Bug, Duplicate
