### ISSUE TITLE
[DOCS] Some examples not rendering properly in jinja docs

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#59907] opened 2021-03-26 10:02 UTC
**Description**
There should probably be something in these boxes:
![image](https://user-images.githubusercontent.com/675056/112615172-0fc82180-8e1a-11eb-9519-db536b9773af.png)

Happens a few times at least on that page, perhaps elsewhere too.

**Suggested Fix**
Looks like the code boxes and the subheadings don't interleave correctly. Should be:

> Example 1:
> ```sls
> {%- set foo = {'bar': {'baz': {'qux': 1}}} %} {{ foo | update_dict_key_value('bar:baz', {'quux': 3}) }}
> ```
> Returns:
> ```yaml
> {'bar': {'baz': {'qux': 1, 'quux': 3}}}
> ```
> Example 2:
> ```sls
> {{ {} | update_dict_key_value('bar:baz:qux', {'quux': 3}) }}
> ```
> Returns:
> ```yaml
> {'bar': {'baz': {'qux': {'quux': 3}}}}
> ```

etc.

**Type of documentation**
Salt documentation

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/jinja/index.html#set-dict-key-value

**Comment by SynPrime** [comment] 2021-03-26 12:39
duplicate of #56192 :-)

**Closed** 2021-03-26 13:32 UTC
Labels: Documentation, Duplicate
