### ISSUE TITLE
How to solve this problem:'log_file' is obsolete. Use 'log.error_file' instead.

### ISSUE THREAD

**Issue by zhulh200868** [saltstack/salt#38482] opened 2016-12-29 06:21 UTC
### Description of Issue/Question
2016-12-29 14:18:23,547 [py.warnings      ][WARNING ][4816] CherryPy Checker:
'log_file' is obsolete. Use 'log.error_file' instead.
section: [saltopts]

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[root@Richard ~]# salt --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by cachedout** [comment] 2016-12-29 17:30
This is a duplicate of an issue that has already been reported: https://github.com/saltstack/salt/issues/27048

This should be a non-fatal error and should not cause an issue, though it likely does need to be fixed up.

**Comment by whiteinge** [comment] 2016-12-30 04:00
The CherryPy Checker is seeing Salt's own `__opts__['log_file']` and incorrectly thinking that is part of the CherryPy config. There isn't a way to restrict the checker to only a subset of the configuration and this warning only appears when the user has `debug: True` enabled in the `rest_cherrypy` configuration.

Given that this is only a warning and only appears when debugging is enabled, I'm inclined to close this as wontfix. @cachedout thoughts?

**Comment by whiteinge** [comment] 2016-12-30 04:06
@zhulh200868 is this warning message the only problem you're reporting or is there another problem you're seeing? If so, please look through your log for other error messages since this warning message does not affect anything.

**Comment by zhulh200868** [comment] 2016-12-31 01:01
If I restart the salt-api,then this warning message will be existed in the log.But it doesn't affect to use the salt.
And my rest_cherrypy configuration is :
rest_cherrypy:
 host: 0.0.0.0
 port: 8088
 debug: true
 disable_ssl: True
 log.access_file: /var/log/salt/api
 log.error_file: /var/log/salt/api

**Comment by cachedout** [comment] 2016-12-31 01:07
@whiteinge I am fine with closing this as `wontfix`. We don't typically consider warnings which are thrown under debugging conditions as defects.

**Comment by whiteinge** [comment] 2016-12-31 01:29
@zhulh200868 thanks for raising the question.

**Closed by whiteinge** 2016-12-31 01:29 UTC
Labels: Duplicate, Expected Behavior, Medium Severity, Salt-API
