### ISSUE TITLE
salt-cloud azurearm [ERROR   ] There was a profile error: Parameter 'subscription_id' must be str.

### ISSUE THREAD

**Issue by cskowronnek** [saltstack/salt#46953] opened 2018-04-09 09:02 UTC
### Description of Issue/Question

I've upgraded my SaltStack to 2018.3.0, when I run salt-cloud I get the following message:

When I run "salt-cloud -p azure-test Test-VM3"

> [ERROR   ] There was a profile error: Parameter 'subscription_id' must be str.

With 2017.7 everything was working..

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

> Salt Version:
           Salt: 2018.3.0

> Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

> System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-119-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by cskowronnek** [comment] 2018-04-09 11:18
Sorry, I changed the title and description. I sould have opened a new issue.

**Comment by Ch3LL** [comment] 2018-04-09 16:01
as i'm sure you have seen this is a duplicate of https://github.com/saltstack/salt/issues/46935  please monitor the issue there which there is currently a proposed fix for. thanks :)

**Comment by cskowronnek** [comment] 2018-04-10 08:02
@Ch3LL Yes it looked like a duplicate, but we are not talking about the same version. I use 2018.3.0 Ubuntu release and the proposed fix is not working in my release.

**Comment by terminalmage** [comment] 2018-04-11 07:16
https://github.com/saltstack/salt/pull/47012 should ensure that the subscription_id is a str type.

**Closed** 2018-04-12 18:59 UTC
Labels: Bug, Critical, Fixed Pending Verification, P2, team-cloud
