### ISSUE TITLE
[BUG] solarisipspkg appears to be comparing versions as list vs string on pkg.installed

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#59306] opened 2021-01-15 18:32 UTC
**Description**

This is a second-hand report against 3000.4 on Sparc 11.

With a state like:

```sls
Salt Minion | Installed:
  pkg.installed:
    - name: salt-minion
    - version: 3000.4,5.11:20200825T201511Z
```

... an already-installed version doesn't appear to be matched as the version comparison involves a one-item list with the version string vs the version string only:

```text
[INFO ] Executing command [u'/bin/pkg', u'list', u'-aHv', u'salt-minion'] in directory '/root'
[DEBUG ] stdout: pkg://SaltStack/library/python/salt-minion@3000.4,5.11:20200825T201511Z i--
[DEBUG ] Could not LazyLoad pkg.version_cmp: 'pkg.version_cmp' is not available.
[DEBUG ] Could not LazyLoad pkg.check_db: 'pkg.check_db' is not available.
[DEBUG ] Could not LazyLoad pkg.check_extra_requirements: 'pkg.check_extra_requirements' is not available.
[DEBUG ] Could not LazyLoad pkg.version_clean: 'pkg.version_clean' is not available.
[DEBUG ] Could not LazyLoad pkg.version_cmp: 'pkg.version_cmp' is not available.
[DEBUG ] Current version ([u'3000.4,5.11:20200825T201511Z']) did not match desired version specification (3000.4,5.11:20200825T201511Z), adding to installation targets
```

**Versions Report**

3000.4.

**Additional context**

ZD-6213.

**Comment by dmurphy18** [comment] 2021-01-19 20:53
Currently there is a Python 3 version for Solaris 11 under development, and is functional.
Currently being integrated into SaltStack CI/CD pipelines.

This will be addressed as part of that development, since the current 3000.4 is based on Py 2 and support for Py 2 has been end-of-lifed.

**Comment by dmurphy18** [comment] 2021-01-19 21:43
see https://gitlab.com/saltstack/enterprise/native-minion/-/issues/24

**Comment by dmurphy18** [comment] 2021-02-05 22:49
Interestingly the versions produced changes between Py 2 and Py 3, even though the salt.mog file structure is the same:  

Py 2.7
```
set name=pkg.fmri value=library/python/salt-minion@${SALT_VER},5.11
```
produces from pkg info /library/python/salt-minion
```
FMRI: pkg://SaltStack/library/python/salt-minion@3000.4,5.11:20200825T201511Z
```

Py 3.7
```
set name=pkg.fmri value=library/python/salt-minion@3002.2,5.11
```
produces from pkg info /library/python/salt-minion
```
FMRI: pkg://SaltStack/library/python/salt-minion@3002.2:20210128T221107Z
```

Note: the Python 3.7 version is still under development

**Comment by dmurphy18** [comment] 2021-02-05 23:00
On Solaris 11.3 system with 3000.4 installed pkg.latest_version returns nothing, even though there is output in debug logs

Command on the Master:
```
root@Unknown:/home/david# salt sol113 pkg.latest_version salt-minion
sol113:
root@Unknown:/home/david#
```

Log file on the minion:
```
2021-02-05 15:57:36,756 [salt.loaded.int.module.cmdmod:397 ][INFO    ][1611] Executing command [u'/bin/pkg', u'list', u'-Hv', u'salt-minion'] in directory '/root'
2021-02-05 15:57:37,039 [salt.loaded.int.module.cmdmod:840 ][DEBUG   ][1611] stdout: pkg://SaltStack/library/python/salt-minion@3000.4,5.11:20200825T201511Z      i--
```

**Comment by dmurphy18** [comment] 2021-02-05 23:36
The issue is most probably the comma in the Py 2 version, esp. given with development Py 3 version 
```root@Unknown:/srv/salt# salt sol114 state.show_sls s2
sol114:
    ----------
    Salt_Minion_installed:
        ----------
        __env__:
            base
        __sls__:
            s2
        pkg:
            |_
              ----------
              name:
                  salt-minion
            |_
              ----------
              version:
                  3002.2:20210128T221107Z
            - installed
            |_
              ----------
              order:
                  10000
root@Unknown:/srv/salt# salt sol114 state.sls s2
sol114:
----------
          ID: Salt_Minion_installed
    Function: pkg.installed
        Name: salt-minion
      Result: True
     Comment: All specified packages are already installed and are at the desired version
     Started: 16:32:46.497607
    Duration: 3043.932 ms
     Changes:   

Summary for sol114
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   3.044 s
root@Unknown:/srv/salt# 
```

Also pkg.latest_version does not work on either Py 2 or Py 3 versions
```
root@Unknown:/srv/salt# salt sol114 pkg.latest_version
```
sol114:
root@Unknown:/srv/salt#
```

Given Py 2 versions are no longer supported, this may be a 'will not fix' since works in updated versions under development.  Requires discussion @oeuftete as to what to do here in this case.

**Comment by dmurphy18** [comment] 2021-02-08 17:13
Note Solaris 11.4
```
FMRI: pkg://solaris/editor/gvim@8.0.711-11.4.0.0.1.14.0:20180814T163519Z
```

Solaris 11.3
```
FMRI: pkg://solaris/editor/gvim@7.3.600,5.11-0.175.3.0.0.30.0:20150821T165112Z
```

Qucik check appears comma dropped in Solaris 11.4

**Comment by sjorge** [comment] 2021-02-09 06:55
Daithi on slack asked what it looks like on illumos (OmniOS in this case as they use IPS too)

```
root@inflaton:~# pkg info pkg:/editor/vim
             Name: editor/vim
          Summary: Vi IMproved
      Description: Advanced text editor that provides the power of the UNIX vi
                   editor with a more complete feature set.
            State: Installed
        Publisher: omnios
          Version: 8.2.1484
           Branch: 151036.0
   Packaging Date: Thu Oct 29 15:50:40 2020
Last Install Time: Sun Nov  3 16:10:46 2019
 Last Update Time: Tue Nov  3 06:34:19 2020
             Size: 33.85 MB
             FMRI: pkg://omnios/editor/vim@8.2.1484-151036.0:20201029T155040Z
       Source URL: https://mirrors.omniosce.org/vim/v8.2.1484.tar.gz
```

**Comment by dmurphy18** [comment] 2021-02-11 18:56
Having tested the Solarisipspkg module and pkg State on Solaris 11.3 (Py2.7) and Solaris 11.4 (Py3 under dev), it appears that pkg.installed on Solaris 11.3 is problematic, works fine on Solaris 11.4 (investigating further) but the other functions appear to function correctly and if any issues are encountered, it is due to a logical explanation, for example: running these commands without a support contract with Oracle to provide later versions.

**Comment by dmurphy18** [comment] 2021-02-11 21:47
The original error of failure to install appears to be due to error return codes form Solaris 11.3 or 11.4, for example with an already installed version of compress/gzip:
```
root@sol11:/export/home/david/salt/tests# pkg install -v --accept pkg://solaris/compress/gzip@1.5,5.11-0.175.3.0.0.30.0:20150821T161446Z
No updates necessary for this image.
root@sol11:/export/home/david/salt/tests# echo $?
4
root@sol11:/export/home/david/salt/tests#
```
And it is this return code is the reason for command failing.  Now if we allow for this, I wonder who will we break once they have come to rely on the current return - even though the docs state that Solaris is not supported

**Comment by dmurphy18** [comment] 2021-02-11 22:03
Will need to update tests for both states and modules in pytest to allow for Python 3 support, to ensure that commands function correctly, current tests are Python 2.7 based.

**Comment by dmurphy18** [comment] 2021-02-17 19:39
Moved to Silicon to allow time for writing tests, currently works by hand

**Comment by dmurphy18** [comment] 2021-03-11 18:12
Tested pkg install and uninstall with repeated actions on a Solaris 11.4 Intel VM command line and encountered no issues with the new Python 3 Tiamat based native minion (currently unreleased).

**Comment by dmurphy18** [comment] 2021-04-06 23:03
Closing this since the fix will be available in the next release of support for Solaris 11.4

**Closed by dmurphy18** 2021-04-06 23:03 UTC
Labels: Bug, CS-R3, CS-S3, Confirmed, Silicon, Tests, ZD, solaris
