### ISSUE TITLE
[FEATURE REQUEST] Packages for the just released Debian 12 (bookworm)

### ISSUE THREAD

**Issue by tkaehn** [saltstack/salt#64452] opened 2023-06-12 09:38 UTC
Debian 12 (bookworm) has just been released.

It would be great if new Salt packages for Debian 12 were added to the APT repository soon.

**Comment by Ch3LL** [comment] 2023-06-12 14:47
This is a duplicate of https://github.com/saltstack/salt/issues/64223

**Closed by Ch3LL** 2023-06-12 14:47 UTC
Labels: Feature, needs-triage
