### ISSUE TITLE
mysql_grants.present incorrect quotes in query in 2018.03

### ISSUE THREAD

**Issue by DavidVisscher** [saltstack/salt#47018] opened 2018-04-11 13:38 UTC
### Description of Issue/Question
Between 2017.07 and 2018.03 the queries resulting from `mysql_grants.present` have changed. Specifically regarding the wildcard character `*`.

### Setup
The state contains the following entry:
```
  mysql_grants.present:
    - grant: all privileges
    - database: "{{ user }}.*"
    - user: {{ user }}
    - host: "%"
    - connection_user: root
    - connection_pass: "{{ cfg.dbpasswords['root'] }}"
    - require:
      - service: mariadb
      - mysql_database: galera_secure dbuser {{ user }} host
```

In 2017.07, the MySQL query resulting from this state would be: 
``GRANT ALL PRIVILEGES ON `[USER]`.* TO `[USER]`@`%`;``
Since 2018.03, the query produced is:
``GRANT ALL PRIVILEGES ON `[USER]`.`*` TO `[USER]`@`%`;``

The result of this is different. In the second instance, the sequence `` `*` ``  is interpreted by mysql literally; Granting all privileges on a database named `` * ``, instead of all databases within the namespace.

This does not have the desired effect. Also, because mysql accepts this query, all states are reported as succesfully executed, while the outcome is no longer the same.

### Versions Report
Mysql version 10

Working version:
```
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

Non-working version:
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment] 2018-04-11 15:58
This is a duplicate of #46917 and #47004 
and will be fixed in 2018.3.1

**Closed by gtmanfred** 2018-04-11 15:58 UTC
