### ISSUE TITLE
salt minion start twice after reboot minion machine

### ISSUE THREAD

**Issue by SmartSara** [saltstack/salt#33970] opened 2016-06-13 10:00 UTC
### Description of Issue/Question
I have one salt minion virual machine, which requires a reboot. I delete the salt-key from master first, then reboot the salt minion vm. After the salt minion vm goes online, salt-minion was not running. I checked log file under /var/log/salt/minion, it seems salt-minion was successfully started and executing state files at first, but got start again, which results in duplicated salt-key on master, thus salt-minion service stops.

### Setup
I am using salt 2015.8.10 (Beryllium) and salt-minion 2015.8.10 (Beryllium).
### Steps to Reproduce Issue
1. sudo salt-key --delete esmaster04-esintusc01 -y (on salt master)
2. sudo reboot (on salt minion)
3. sudo salt-key --list-all (I ran this command twice on salt master within 30 seconds, I got 2 different results.
4. sudo service salt-minion status (on salt minion - got "salt-minion stop/waiting")

**The command and result I ran on master:**
sara_zhu@saltmaster01-supportintusc01:~$ sudo salt-key --delete esmaster04-esintusc01
The following keys are going to be deleted:
Accepted Keys:
esmaster04-esintusc01
Denied Keys:
esmaster04-esintusc01
Proceed? [N/y] y
Key for minion esmaster04-esintusc01 deleted.
**After I reboot the minion vm, I ran the following two commands within 30 seconds.**
sara_zhu@saltmaster01-supportintusc01:~$ sudo salt-key --list-all
Accepted Keys:
eshaproxy01-esintusc01
eshaproxy02-esintusc01
esmaster01-esintusc01
esmaster02-esintusc01
esmaster03-esintusc01
esmaster04-esintusc01
esmonitor02-esintusc01
saltmaster01-supportintusc01
Denied Keys:
Unaccepted Keys:
Rejected Keys:
sara_zhu@saltmaster01-supportintusc01:~$ sudo salt-key --list-all
Accepted Keys:
eshaproxy01-esintusc01
eshaproxy02-esintusc01
esmaster01-esintusc01
esmaster02-esintusc01
esmaster03-esintusc01
esmaster04-esintusc01
esmonitor02-esintusc01
saltmaster01-supportintusc01
Denied Keys:
esmaster04-esintusc01
Unaccepted Keys:
Rejected Keys:

**The command and result I ran on minion(within 30 seconds):**
sara_zhu@esmaster04-esintusc01:~$ sudo service salt-minion status
salt-minion start/running, process 2638
sara_zhu@esmaster04-esintusc01:~$ sudo service salt-minion status
salt-minion stop/waiting

**Salt minion logs:**
2016-06-13 09:55:24,158 [salt.cli.daemons ][WARNING ][1233] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
2016-06-13 09:55:27,874 [salt.state       ][WARNING ][1339] Top file merge strategy set to 'merge' and multiple top files found. Top file merging order is undefined; for better results use 'same' opti
on
2016-06-13 09:55:42,449 [py.warnings      ][WARNING ][1339] /usr/lib/python2.7/dist-packages/salt/utils/templates.py:73: DeprecationWarning: Starting in 2015.5, cmd.run uses python_shell=False by defa
ult, which doesn't support shellisms (pipes, env variables, etc). cmd.run is currently aliased to cmd.shell to prevent breakage. Please switch to cmd.shell or set python_shell=True to avoid breakage i
n the future, when this aliasing is removed.
2016-06-13 09:55:44,237 [salt.loaded.int.states.file][WARNING ][1339] State for file: /etc/sudoers.d/ryang - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, ye
t 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
2016-06-13 09:55:44,269 [salt.loaded.int.states.file][WARNING ][1339] State for file: /etc/sudoers.d/leong - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, ye
t 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
2016-06-13 09:55:58,720 [salt.cli.daemons ][WARNING ][2641] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
2016-06-13 09:55:58,822 [salt.crypt       ][INFO    ][2634] Generating keys: /etc/salt/pki/minion
2016-06-13 09:55:58,935 [salt.crypt       ][CRITICAL][2641] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2016-06-13 09:55:58,972 [salt.crypt       ][CRITICAL][2634] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2016-06-13 09:56:05,581 [salt.crypt       ][CRITICAL][2718] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.

### Versions Report
sara_zhu@saltmaster01-supportintusc01:~$ salt --versions-report
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: 0.2.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-59-generic
         system: Ubuntu 14.04 trusty

**Comment by SmartSara** [comment] 2016-06-13 10:02
Please help figure out the problem. Thanks a million in advance.

**Comment by Ch3LL** [comment] 2016-06-13 20:30
@SmartSara I have not been able to replicate this behavior. Could you try deleting the cache on your master and minion and restart it and see if you get the same behavior?

**Comment by SmartSara** [comment] 2016-06-14 08:58
I've tried to delete the cache on both master and minion, and restart it, same behavior happens.

I find another issue similar to the problem I encounter, https://github.com/saltstack/salt/issues/17289.
The thing is that I create a reactor:
reactor:                            # Master config section "reactor"
  - 'salt/minion/*/start':          # Match tag "salt/minion/*/start"
    - /srv/reactor/start.sls        # state.highstate when a minion starts

However, after I disabled this reactor, still no luck.
Log on salt minion: (Seems it still start the salt-minion twice, which results in duplicate salt-key, then salt-minion service stops)
**2016-06-14 08:44:03,954 [salt.cli.daemons ][WARNING ][1233] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
2016-06-14 08:44:26,481 [salt.cli.daemons ][WARNING ][2070] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!**
2016-06-14 08:44:26,654 [salt.crypt       ][CRITICAL][2070] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2016-06-14 08:44:26,727 [salt.crypt       ][CRITICAL][2063] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2016-06-14 08:44:27,040 [salt.crypt       ][CRITICAL][2145] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2016-06-14 08:46:27,376 [salt.crypt       ][CRITICAL][2228] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2016-06-14 08:46:27,728 [salt.cli.daemons ][WARNING ][2286] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
2016-06-14 08:46:27,731 [salt.crypt       ][CRITICAL][2277] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2016-06-14 08:46:27,753 [salt.crypt       ][CRITICAL][2286] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2016-06-14 08:46:28,052 [salt.crypt       ][CRITICAL][2358] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.

**Comment by Ch3LL** [comment] 2016-06-14 16:26
@SmartSara thanks for reporting back and I'm glad you got it working. I will go ahead and close this issue since this seems to be caused by a startup-script we do not manage. Let me know if there is any other reason to keep this open. Thanks!

**Closed by Ch3LL** 2016-06-14 16:26 UTC
Labels: Cannot Reproduce, Info Needed
