### ISSUE TITLE
ERROR: Minion failed to start

### ISSUE THREAD

**Issue by Timandes** [saltstack/salt#32950] opened 2016-04-29 15:39 UTC
### Description of Issue/Question
After upgrading salt-minion to 2015.8.8.2, I found that it could not be started on some machines.
However, even if I set `log_leve` to `garbage`, there were still not any useful outputs in log file:

```
2016-04-29 23:32:02,285 [salt.utils.parsers                       ][DEBUG   ][7491] SYSPATHS setup as: /etc/salt
2016-04-29 23:32:02,287 [salt.log.setup                           ][WARNING ][7491] Temporary logging is already configured
2016-04-29 23:32:02,287 [salt.config                              ][DEBUG   ][7491] Reading configuration from /etc/salt/minion
2016-04-29 23:32:02,292 [salt.utils.parsers                       ][DEBUG   ][7491] Configuration file path: /etc/salt/minion
2016-04-29 23:32:02,293 [salt.utils                               ][TRACE   ][7491] Trying pysss.getgrouplist for 'root'
2016-04-29 23:32:02,293 [salt.utils                               ][TRACE   ][7491] Trying generic group list for 'root'
2016-04-29 23:32:02,294 [salt.utils                               ][TRACE   ][7491] Group list for user 'root': ['adm', 'bin', 'daemon', 'disk', 'sys', 'wheel']
2016-04-29 23:32:02,314 [salt.log.setup                           ][WARNING ][7491] Logfile logging already configured
2016-04-29 23:32:02,315 [salt.utils.verify                        ][WARNING ][7491] Insecure logging configuration detected! Sensitive data may be logged.
2016-04-29 23:32:02,315 [salt.cli.daemons                         ][INFO    ][7491] Setting up the Salt Minion "t.xxx"
2016-04-29 23:32:02,319 [salt.cli.daemons                         ][INFO    ][7491] The Salt Minion is shut down
2016-04-29 23:32:02,321 [salt.cli.daemons                         ][INFO    ][7493] The Salt Minion is shut down
2016-04-29 23:32:02,322 [salt.utils.process                       ][DEBUG   ][7494] Created pidfile: /var/run/salt-minion.pid
2016-04-29 23:32:02,323 [salt.cli.daemons                         ][INFO    ][7494] The Salt Minion is starting up
2016-04-29 23:32:02,325 [salt.cli.daemons                         ][INFO    ][7494] The Salt Minion is shut down
2016-04-29 23:32:02,325 [salt.scripts                             ][ERROR   ][7494] Minion failed to start
2016-04-29 23:32:02,325 [salt.scripts                             ][WARNING ][7494] ** Restarting minion **
2016-04-29 23:32:02,325 [salt.scripts                             ][INFO    ][7494] Sleeping random_reauth_delay of 6 seconds
```

### Setup
```
# cat /etc/salt/minion
id: t.xxx
log_level: garbage
hash_type: sha256
master:
    - www.abc.com
```

### Steps to Reproduce Issue
```
service salt-minion start
tail -f /var/log/salt/minion
```

### Versions Report
```
# salt-minion --versions
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.08
          PyZMQ: 2.1.9
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 2.1.9
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 5.4 Final
        machine: x86_64
        release: 2.6.18-164.el5
         system: CentOS 5.4 Final

```

**Comment by jfindlay** [comment] 2016-04-29 16:49
@Timandes, thanks for reporting.  This is a duplicate of #32472.

**Closed by jfindlay** 2016-04-29 16:49 UTC
Labels: Duplicate
