### ISSUE TITLE
docker_container.running state is not stable.

### ISSUE THREAD

**Issue by BenjaminSchubert** [saltstack/salt#43001] opened 2017-08-17 02:50 UTC
### Description of Issue/Question

When using `docker_container.running`, the state needs to be applied twice to be in a consistent state.
The second time we run it, some changes are made, which is inconsistent with the fact that states should not change once run.

### Setup

A state that reproduce the issue would be : 

```
postgresql sonar container:
  docker_container.running:
    - name: psql-sonar
    - image: postgres:latest

    - binds:
      - /tmp/sonar/psql/config:/var/lib/postgresql:Z
      - /tmp/sonar/psql/data:/var/lib/postgresql/data:Z

    - environment:
        - POSTGRES_USER: test
        - POSTGRES_PASSWORD: test
```

### Steps to Reproduce Issue

1) install a salt minion with docker support
2) add a state with as shown before
3) apply the state (for example `salt my_node state.apply test.sls`)

This should give something like : 

```
172.17.0.1:
----------
          ID: postgresql sonar container
    Function: docker_container.running
        Name: psql-sonar
      Result: True
     Comment: 
     Started: 02:45:26.386970
    Duration: 51873.065 ms
     Changes:   
              ----------
              container_id:
                  ----------
                  added:
                      02e71748963d4d231e06e69b7cbeb519e07d756ec5e5b00adc0c165d69ffe847
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - 8996b4a29b2b
                          - bea3311ef15b
                          - 1d6d551d6af0
                          - ba16377760f9
                          - fd68bfa82d98
                          - b1b9eb0ac9c8
                          - 6b1468749943
                          - 29d82d6e2d6c
                          - ad849322ee0c
                          - c5539863a39f
                          - 18cc2b50256c
                          - ad74af05f5a2
                          - f49f2decd34d
                  Status:
                      Downloaded newer image for docker.io/postgres:latest
                  Time_Elapsed:
                      49.62261796
              state:
                  ----------
                  new:
                      running
                  old:
                      None

Summary for 172.17.0.1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  51.873 s
```

4) re-apply the state (same command)

This should give : 
```
172.17.0.1:
----------
          ID: postgresql sonar container
    Function: docker_container.running
        Name: psql-sonar
      Result: True
     Comment: Replaced container 'psql-sonar'
     Started: 02:46:39.755519
    Duration: 3759.944 ms
     Changes:   
              ----------
              container:
                  ----------
                  Config:
                      ----------
                      Image:
                          ----------
                          new:
                              sha256:82b06f064259120143321ba826ce7c172bf04404f9634911f545b7bac5aa547e
                          old:
                              postgres:latest
              container_id:
                  ----------
                  added:
                      87c4efaf5833c536fb857d16b1027b59ff3ca2adf32fb666b20d8b110c18716e
                  removed:
                      - 02e71748963d4d231e06e69b7cbeb519e07d756ec5e5b00adc0c165d69ffe847

Summary for 172.17.0.1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   3.760 s
```

However, this is not an expected output, as a state should be stable, and rerunning the state a second time should not change anything.

### Versions Report
```
Salt Version:
           Salt: 2017.7.0-455-gfbf2e0d
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jun 26 2017, 10:20:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 26 Twenty Six
         locale: UTF-8
        machine: x86_64
        release: 4.11.8-300.fc26.x86_64
         system: Linux
        version: Fedora 26 Twenty Six
```

**Comment by gtmanfred** [comment] 2017-08-17 14:49
thanks for reporting this.

@terminalmage when you get a second, could you take a look at this?

It looks like the docker image id is getting changed on the second time this is running through so the comparison to the old container looks like it has changed.

Thanks!
Daniel

**Comment by jared-mess** [comment] 2017-08-19 18:25
I'm having a similar issue where I need to run `state.highstate` twice for `docker_container.running` to take effect on a fresh Ubuntu 16.04 instance, but I get an error the first time.

#### Master Output
```
----------
          ID: my_container
    Function: docker_container.running
        Name: my_app
      Result: False
     Comment: Failed to get client args: docker Python module not imported
     Started: 17:07:15.496148
    Duration: 54.413 ms
     Changes:   
```

#### Minion Log
```  
File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 824, in _get_create_kwargs
    client_args = get_client_args()
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 786, in get_client_args
    return salt.utils.docker.get_client_args()
  File "/usr/lib/python2.7/dist-packages/salt/utils/docker/__init__.py", line 80, in get_client_args
    raise CommandExecutionError('docker Python module not imported')
CommandExecutionError: docker Python module not imported
```
#### SLS
```
docker_py:
  pip.installed:
    - name: docker
    - reload_modules: True
    - require:
      - cmd: pip-install

my_container:
  docker_container.running:
    - name: my_app
    - image: my-host/quickstart-image:latest
    - port_bindings: 80:80
    - require:
      - pip: docker_py
```
#### System Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-32-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment] 2017-08-21 15:38
@jared-mess that is a different issue, but will be fixed by this PR.  https://github.com/saltstack/salt/pull/43088

**Comment by gtmanfred** [comment] 2017-08-21 15:39
Also, I am able to replicate @BenjaminSchubert s issue pretty easily.

```
[root@salt ~]# salt-call --local state.apply test
local:
----------
          ID: docker_py
    Function: pip.installed
        Name: docker
      Result: True
     Comment: All packages were successfully installed
     Started: 15:34:50.107711
    Duration: 1901.278 ms
     Changes:
              ----------
              docker==2.5.0:
                  Installed
----------
          ID: my_container
    Function: docker_container.running
        Name: my_app
      Result: True
     Comment: Container 'my_app' is already configured as specified. State changed from 'stopped' to 'running'.
     Started: 15:34:52.040681
    Duration: 6557.599 ms
     Changes:
              ----------
              state:
                  ----------
                  new:
                      running
                  old:
                      stopped

Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:   8.459 s
(reverse-i-search)`un': pip ^Cinstall docker
[root@salt ~]# vi /srv/salt/test.sls
[root@salt ~]# salt-call --local state.apply test
local:
----------
          ID: postgresql sonar container
    Function: docker_container.running
        Name: psql-sonar
      Result: True
     Comment:
     Started: 15:37:57.657154
    Duration: 15856.747 ms
     Changes:
              ----------
              container_id:
                  ----------
                  added:
                      af697fea820a2f376e4dfdf88c5fee08410bcc40e4718f1f4efed94f76036020
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - 8996b4a29b2b
                          - bea3311ef15b
                          - 1d6d551d6af0
                          - b1b9eb0ac9c8
                          - ad74af05f5a2
                          - ba16377760f9
                          - fd68bfa82d98
                          - 6b1468749943
                          - 29d82d6e2d6c
                          - ad849322ee0c
                          - c5539863a39f
                          - f49f2decd34d
                          - 18cc2b50256c
                  Time_Elapsed:
                      15.2732021809
              state:
                  ----------
                  new:
                      running
                  old:
                      None

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  15.857 s
[root@salt ~]# salt-call --local state.apply test
local:
----------
          ID: postgresql sonar container
    Function: docker_container.running
        Name: psql-sonar
      Result: True
     Comment: Replaced container 'psql-sonar'
     Started: 15:38:31.405210
    Duration: 1078.994 ms
     Changes:
              ----------
              container:
                  ----------
                  Config:
                      ----------
                      Image:
                          ----------
                          new:
                              sha256:82b06f064259120143321ba826ce7c172bf04404f9634911f545b7bac5aa547e
                          old:
                              postgres:latest
              container_id:
                  ----------
                  added:
                      c16a147ca5ad4c6403c2f2b3d661950526408aa30ba8962d57ac7702abce6e48
                  removed:
                      - af697fea820a2f376e4dfdf88c5fee08410bcc40e4718f1f4efed94f76036020

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.079 s
```

**Comment by terminalmage** [comment] 2017-08-23 17:04
I couldn't reproduce this, and after talking to @gtmanfred he was also not able to reproduce either. But from the changes being reported in the state output, I can tell what is happening here. The image being reported when you inspect the temp container created by the `docker_container.running` state is the image's ID and not its name. https://github.com/saltstack/salt/pull/43155 should solve this by resolving the image down to its ID before comparing.

**Closed** 2017-08-28 14:07 UTC
Labels: 2017.7.2, Bug, Core, Fixed Pending Verification, High Severity, P2, State Module
