### ISSUE TITLE
I patched several hundred servers via pkg.upgrade module. I can lost my job. I will lost money and etc... Please, do not do my mistales. Perhaps need to highlight some things on documentation. Only small history and suggestion

### ISSUE THREAD

**Issue by 4815162342lost** [saltstack/salt#44589] opened 2017-11-17 21:04 UTC
Hi @all,

I did a hugest mistake on my it-career...

I only wanted to upgrade ntp package on all servers which i administrate. Simple task, huh?

I run this command:
`salt '*' pkg.upgrade name=ntp`

But i did not pay attention to this:
https://i.imgur.com/KyB6fdg.png

And some servers (several hundred!!!) was fully upgraded!!! Of course it is very high impact for business... Because some server was never updated several years...

So, I can lost my job, my reputation, money, my life and etc. Please, do not do my mistake...

I kindly ask you highlight this point on documentation such as **'DO NOT USE THIS MODULE IF YOU NOT SURE THAT YOUR MINIONS OLDER THAN  2016.3.0.'**
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.yumpkg.html#salt.modules.yumpkg.upgrade

 I do not sleep some nights... I am tired and feel me terrible.

Thanks a lot for any feedback. 

**update:**
I through again...
1) Why salt start action if it meet unrecognized options? i believe that salt should stop work if user did a grammar or logical mistake during salt modules calling. What f user type 'nane=ntp' or 'mame=ntp'? Need protect salt users from mistakes.
2) You  did user.delete module safely with adding remove=True and force=True options:
`salt '*' user.delete name remove=True force=True`
But why you did not add similar arguments for pkg.upgrade function? pkg.upgrade -- may destroy some servers in production environment. High-impact module.

**Comment by revmischa** [comment] 2017-11-17 21:51
![unixmagick](https://user-images.githubusercontent.com/245131/32970573-b0ea6872-cc3d-11e7-9f24-d991e715e2f3.jpg)

**Comment by Majora320** [comment] 2017-11-18 07:13
Why would salt simply ignore unrecognized arguments in the first place?

**Comment by austinpapp** [comment] 2017-11-18 21:47
i know this comment is not going to solve your _immediate issue_ at hand (bummer) but a few things come to mind for others looking at this ticket. This could be useful for those who are new to salt, devops or even new to managing systems/infrastructure. YMMV

Firstly, people will disagree with the things I'll say and others will agree (hopefully). But I would highlight when we don't disagree we don't progress as an industry. ok, now that that is out of the way...

Secondly, welcome to devops. You will make mistakes. You will do dumb stuff. It goes with the territory. I've taken down a backbone, a firewall or 3 and even had the luxury of stopping the enterprise mail servers (yes, servers) for a global financial data company. Point being, we all make mistakes and **survive**. 

**With all of that said, this is my 10 minute brain dump of just about a year of using salt and is by no means comprehensive.** 

## Targeting

Avoid using `*`. I would even go as far as complex regex matching. Both introduce high levels of risk as you may target an obscure edge case that you did not account for (or want).

Always be specific in your targeting. Salt gives you some idea as to what it thinks it should expect to be targeted but that's really only in simple architectures. 

Grains are about as complex as I get. If I want all rhel7 machines, I know the grain is going to handle this correctly. 

The safest bet is use a list. I use lists extensively as it allows me to prove not only the machines I would expect to communicate but also that those machines completed the task at hand.

## Testing

Whenever I run a salt command, I always run a test first. The simplest approach to get a handle as to what the heck you are about to do is:

```
salt -L 'minion1,minion2' state.apply test=True
```

From here i can confirm that 1) I am hitting the right minions and 2) get a general idea what might change. Using `mock` does offer some extra checks but thats up to you with state validation.

## Environments

I don't mean saltenv but rather the environment in which that minion (server) exists. The simple prod, staging, dev is fine but I prefer to take this a step further and use a concept called stages. Again, this is completely up to you.  For me, stages offer a finer level of roll out of applications. This also considers that your development servers may be used by multiple developers and thus, shouldn't just be kicked around. 

The point of all this is that you deploy your changes in controlled supersets of minions. 

## Final thoughts

This comment by no means covers everything. It would be months of documentation to do so. However, know that you should not take salt lightly. Salt is powerful. Very very powerful. 

Think before you run commands. 

-a

**Comment by gtmanfred** [comment] 2017-11-29 19:22
Thanks for the feedback.

I am going to close this as a duplicate of #37379

I would not be opposed to changing this to make it less disaster prone.

Thanks,
Daniel

**Closed by gtmanfred** 2017-11-29 19:22 UTC

**Comment by danielmotaleite** [comment] 2017-12-06 15:03
i also had a similar mistake, i wanted to upgrade only one package (security update), but instead i upgraded everything, including docker.  After the upgrade, docker was restarted and so it shutdown all the running containers, shutting down all the DBs (master and replicas). I was lucky that the DB system was good and after the docker restarted, the DB boot up and recovered quickly... so i only had a few minutes of downtime. 

But yes, pkg.upgrade should only act over few packages, upgrading everything is rare and dangerous, should need a special option for that, or even better, a new name (pkg.upgrade-all or similar)
