### ISSUE TITLE
Exceptions thrown when state is applied

### ISSUE THREAD

**Issue by nulfox** [saltstack/salt#44514] opened 2017-11-13 18:38 UTC
https://github.com/saltstack/salt/blob/2b9a4cf4c6ae31a1578d2e3e7ae04243e57f9864/salt/state.py#L1937

This line assumes runas/runas_password are in the state_con, but in a lot of cases, they are not. This leads to KeyError exceptions in state.apply runs. 

This has started with recent release. Should there be a try/except block around this. Seems like its just clearing those entries from state_con.

**Comment by gtmanfred** [comment] 2017-11-13 19:50
it just needs a default of None passed so that it doesn't throw an exception.

**Comment by gtmanfred** [comment] 2017-11-13 19:54
Actually, what are you running? because this should always be set, even if it is just set to None.

https://github.com/saltstack/salt/blob/2017.7/salt/state.py#L1762-L1767

since it is always set to None, even in `else` then it should always just pop that none value from the top of `call()`

**Comment by nulfox** [comment] 2017-11-16 18:00
@gtmanfred Yeah, I am not entirely sure how it winds up as missing. Will run trace/profiler to see exactly how that gets modified. Assumed it's being updated somewhere along the way.
I believe this is a duplicate of https://github.com/saltstack/salt/issues/44136

**Comment by gtmanfred** [comment] 2017-11-16 22:52
yeah it is a duplicate of that, but without us being able to reproduce it, there isn't a lot that we can do.

I am going to close this as a duplicate of #44136.

Thanks,
Daniel

**Closed** 2018-07-27 18:01 UTC
Labels: Duplicate, Info Needed
