### ISSUE TITLE
gitfs backend error related to SSH host key checking

### ISSUE THREAD

**Issue by pniederw** [saltstack/salt#8684] opened 2013-11-20 15:54 UTC
After setting up a gitfs backend for a (private) GitHub repo, the following appeared in the master log:

    [salt.loaded.int.fileserver.gitfs][WARNING ] GitPython exception caught while
    fetching: len(["c179aa10976f1152d37e1deca0736698da8744bd\tnot-for-
    merge\tbranch 'master' of git+ssh://xxx\n"]) != len(["Warning: Permanently added the 
    RSA host key for IP address 'xxx' to the list of known hosts.", '', ' = [up to date]      
    master     -> origin/master'])

Workaround was to add the following to `.ssh/config`:

    Host github.com
    User salt
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null

Salt 0.17.2, Ubuntu Raring

**Comment by c4milo** [comment] 2015-05-06 01:06
I'm having this same issue. I had to use `gitpython` because getting `pygit2` installed on Ubuntu Trusty is a pain in the butt. 

Here is my config: 

```yaml
auto_accept: True

file_roots:
  base:
    - /srv/salt/formulas

fileserver_backend:
  - git

gitfs_remotes:
  - git+ssh://git@github.com/managedbyq/salt-states.git

gitfs_root: formulas
gitfs_base: stg
```

I have my deploy key under `/root/.ssh/id_rsa`

After adding `StrictHostKeyChecking no` in `/root/.ssh/config` the host warning went away but I'm now getting this error: 


2015-05-06 01:00:25,735 [salt.loaded.int.fileserver.gitfs][ERROR   ] Exception ''Error when fetching: fatal: Could not read from remote repository.' returned exit status 2: None' caught while fetching gitfs remote git+ssh://git@github.com/managedbyq/salt-states.git

**Comment by terminalmage** [comment] 2015-12-01 17:03
@c4milo I can't reproduce this. Have you tried using ``ssh://`` instead of ``git+ssh://`` in your remote URL?

**Comment by c4milo** [comment] 2015-12-01 17:16
I stopped working on this project months ago. Unfortunately I cannot longer verify if it still persist :(

**Comment by terminalmage** [comment] 2015-12-09 01:14
@c4milo OK, well given that neither the originally-reported issue (nor yours) can be reproduced, this would appear most likely to be upstream issues with older versions of GitPython. I know in the past it leaned significantly more on assertions than it does now.

I'm going to close this as an upstream bug.

**Closed by terminalmage** 2015-12-09 01:14 UTC
Labels: Bug, Core, High Severity, P3, TEAM Core, Upstream Bug

**Comment by michaelkarrer81** [comment] 2016-01-18 16:39
Could you please reopen the bug! I do have the exact same problem on GitPython 1.0.1 on ubuntu 14.04 with saltstack 2015.8.3

**Comment by basepi** [comment] 2016-01-19 17:28
@michaelkarrer81 It sounds like this is an upstream bug for older versions of gitpython. Can you upgrade your gitpython?

**Comment by terminalmage** [comment] 2016-01-19 21:58
@michaelkarrer81 Do you have a reproducible use case?

**Comment by MadsRC** [comment] 2016-02-13 16:46
I'm experiencing the exact same bug as @michaelkarrer81... Here's an exempt of my logs:

```
[ERROR   ] Exception ''Error when fetching: fatal: Could not read from remote repository.
' returned with exit code 2' caught while fetching gitfs remote 'ssh://git@gitlab.com:v42/salt-states.git'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1860, in fetch_remotes
    if repo.fetch():
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 616, in fetch
    fetch_results = origin.fetch()
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 655, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 557, in _get_fetch_info_from_stderr
    raise GitCommandError(("Error when fetching: %s" % line,), 2)
GitCommandError: 'Error when fetching: fatal: Could not read from remote repository.
' returned with exit code 2
```
Doing, as root, a git clone https://hub.docker.com/r/madsrc/salt-master/ works brilliantly, so it's definitely either Salt or GitPython. I've event tried with the latest version of gitpython from pip.

For those of you wanting to reproduce this, I've got a Docker image that reproduces it here https://hub.docker.com/r/madsrc/salt-master/

**Comment by christianbundy** [comment] 2016-05-12 19:41
@MadsRC Can you try adding `StrictHostKeyChecking=no` to your SSH config? That fixed the issue for me.
