### ISSUE TITLE
salt-ssh: Too many authentication failures

### ISSUE THREAD

**Issue by ryanfields** [saltstack/salt#24096] opened 2015-05-23 07:51 UTC
salt-ssh ```--passwd``` option doesn't seem to work.  I'm getting a ```Too many authentication failures for root``` when trying to run anything.  Running from a script on an OSX machine if that matters.

I can execute a command in my terminal like ```ssh root@myhost 'ls /'``` without issue.  I'm prompted for a password and upon supplying it my command runs.  Therefore, it doesn't appear to be an issue with the ssh configuration on the host.

In the diagnostic info dumped when the command fails, ```ssh_user``` and ```ssh_passwd``` are correct, so I know the ```--passwd``` option is being seen.

If I use the ```--askpass``` option, I am prompted for a password.  Upon supplying it, the command fails with the same ```Too many...``` error.

Adding ```--key-deploy``` doesn't change anything, presumably because I'm never authenticated in the first place.

I'm trying to figure out if there's something I've overlooked.

**Comment by jfindlay** [comment] 2015-05-26 17:42
@ryanfields, what is the output of `salt-ssh --versions-report`, what is your roster file, and what is the salt-ssh debug log?  Thanks.

**Comment by ryanfields** [comment] 2015-05-26 22:28
Let's see if I can do this without leaking my hostname and password...

```
           Salt: 2015.5.0
         Python: 2.7.5 (default, Mar  9 2014, 22:15:05)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

```
web1:
  host: <host-ip>
  passwd:<password>
```

```
$ salt-ssh --config-dir=etc/salt --roster-file=roster -i -l debug '*' test.ping

[DEBUG   ] Reading configuration from /<obfuscated>/salt-ssh-test/etc/salt/master
[DEBUG   ] Configuration file path: /<obfuscated>/salt-ssh-test/etc/salt/master
[DEBUG   ] LazyLoaded flat.targets
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Jinja search path: ['/<obfuscated>/salt-ssh-test/cache/salt/master/files/base']
[DEBUG   ] Rendered data from file: roster:
web1:
  host: <host-ip>
  passwd: <password>


[DEBUG   ] Results of YAML rendering: 
OrderedDict([('web1', OrderedDict([('host', '<host-ip>'), ('passwd', '<password>')]))])
[INFO    ] minions list: {'web1': OrderedDict([('host', '<host-ip>'), ('passwd', '<password>')])}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Could not LazyLoad test.ping
[DEBUG   ] Performing shimmed, blocking command as follows:
test.ping
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 37023  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE <host-ip>: 255
[DEBUG   ] SHIM retcode(255) and command: 
[DEBUG   ] LazyLoaded nested.output

web1:
    ----------
    retcode:
        255
    stderr:
        Received disconnect from <host-ip>: 2: Too many authentication failures for root
    stdout:
```

**Comment by jfindlay** [comment] 2015-05-27 00:40
@ryanfields, thanks for the extra info.  What system are you trying to salt-ssh into?  Does it work if you try something else?

**Comment by ryanfields** [comment] 2015-05-27 03:37
Fresh Ubuntu-14.04 install with a root password set and no other modifications.  salt-ssh fails no matter what command I try.  As stated at the end of the above comment, other means of connecting via SSH w/ pasword work fine.  I can do it from command line with ssh, and I've got a node+pty.js script that spawns a command line process which also works fine.

**Comment by basepi** [comment] 2015-05-28 16:09
@DmitryKuzmenko is in the process of trying to reproduce this on a number of hosts and it's working fine for him. Could you potentially try changing your password to something pretty simple to eliminate the idea that there's something wrong with the password itself? Also, if you remove the password from the roster and just type it when prompted by salt-ssh to deploy the key, does it work there?

**Comment by ryanfields** [comment] 2015-05-29 05:32
Password was pretty simple to begin with, but I changed it to 8 characters, only letters and numbers.  Same result.  And no, typing the password manually has the same result, which seems wrong.  I am wondering if the initial password attempt is working, but then something fails after?  I'm not using sudo though, so I don't know why there'd be any follow up attempts.

**Comment by tbaker57** [comment] 2015-05-29 05:44
@ryanfields - do you have access to the server logs ? If your initial attempt was successful it should be recorded in the logs on the server.

**Comment by ryanfields** [comment] 2015-05-29 05:59
@tbaker57 That gets us a little closer, maybe.  Nothing shows up in my logs when I run salt-ssh, but I do get log updates from manual logins (and intentional login failures) via plain old ssh.

**Comment by tbaker57** [comment] 2015-05-29 06:10
You mean when you try using salt-ssh you don't get anything in the server logs at all ? That's very odd. Can you run tcpdump/wireshark to confirm that packets are actually sent to the target ? Just trying to figure out where the issue lies. I suspect the client being OSX might be relevant. Can you run salt-ssh from a non-OSX machine to the same Ubuntu target ?

**Comment by ryanfields** [comment] 2015-05-29 06:25
I don't have a non-OSX machine handy aside from the one I'm trying to Salt.  Tcpdump is showing traffic sent to the host when I run salt-ssh, so there is definitely communication.  And I do get ```Disconnecting: Too many authentication failures for root [preauth]``` in my auth logs, but not the usual logging that would suggest a password was tried.

**Comment by tbaker57** [comment] 2015-05-29 06:47
My last suggestion (before beer o'clock) is to run sshd in the foreground in debug mode on the Ubuntu box
```
/usr/sbin/sshd -d -d -d
```
and see if anything interesting shows up there.

**Comment by ryanfields** [comment] 2015-05-29 07:01
I think that gave me my answer.  I have a large number of keys and I have ssh-agent running.  I suspect that it's stepping in and trying to helpfully suggest keys.  If that's the case, pubkey attempts would be exhausting the allowed login attempts before a password attempt can be offered.

If that's the problem, then I know how to resolve it for my case.  However, I'm not sure how many people are relying on ssh-agent or a similar key service (knowingly or unknowingly) when running salt-ssh.  The fix for me might cause problems for others.

I think ```-o IdentitiesOnly=yes``` on the ssh command line called from salt-ssh would resolve this for me.  I'm betting that should *not* be default behavior though, in case there are a large number of people unknowingly depending on the current default behavior.

**Comment by DmitryKuzmenko** [comment] 2015-05-29 10:46
@ryanfields thank you for the solution description.
This is from ssh_config:
> IdentitiesOnly
> Specifies that ssh(1) should only use the authentication identity files configured in the ssh_config files, even if ssh-agent(1) or a PKCS11Provider offers more identities. The argument to this keyword must be ``yes'' or ``no''.  This option is intended for situations where ssh-agent offers many different identities.  The default is ``no''.
So this behavior looks expected and nothing shall be done here.
@basepi maybe we shall add a note about this to ssh-agent documentation?

**Comment by ryanfields** [comment] 2015-05-29 11:53
No, that's not quite right.  Something should be done here.  salt-ssh should probably provide an option on the command line that will pass ```IdentitiesOnly=yes``` to the ssh command it runs.  That, or automatically force that option whenever passwd or priv is set in the roster or one of --passwd or --askpass is specified on the command line.

If I've put a password or key path in my roster or otherwise indicated that I wish to use a password or specific key, then salt-ssh should pass that intent along to the ssh command it runs via the IdentitiesOnly option.  The only time ssh-agent should come into play is when I have not explicitly said "use a password" or "use this key".

Does that make sense?

**Comment by DmitryKuzmenko** [comment] 2015-05-29 12:01
@ryanfields ah, got it. Thanks.

**Comment by DmitryKuzmenko** [comment] 2015-06-08 08:07
Since the described behavior is default for ssh client we decided to not apply any automated logic as it suggested by @ryanfields. Now this behavior can be modified by one of the following ways:
* ssh_identities_only boolean flat in master config (False by default)
* --identities-only salt-ssh commandline flag

**Comment by ryanfields** [comment] 2015-06-08 08:18
This sounds perfect.  I'd be able to drop the command line flag into my existing scripts and be good to go.

**Comment by rallytime** [comment] 2015-06-25 15:19
@ryanfields Is this working for you? Can we close out this bug?

**Comment by ryanfields** [comment] 2015-06-25 17:16
@rallytime Which release did this make it into?  I haven't been able to get anything more recent than 2015.5.0 from homebrew.  (Homebrew indicates that 2015.5.1 is available, but after install it my --versions output still says 2015.5.0.)

**Comment by rallytime** [comment] 2015-06-25 17:39
Oh, looks like the fix went into the develop branch. So this code will be released in Salt Beryllium, which is targeted to release around August. We can keep this open until you've had a chance to test it.

**Comment by ryanfields** [comment] 2015-07-09 01:54
@rallytime If you just want to go ahead and close, I can always reopen if this doesn't work once it hits release.  The documentation posted above suggests that this will do exactly what I need it to do, so there's no need to keep this open.  If the feature itself doesn't work, it'll make more sense to open a separate issue specific to the --identities-only flag or its config counterpart.

**Comment by rallytime** [comment] 2015-07-09 01:56
@ryanfields That sounds great. Thanks!

**Closed by rallytime** 2015-07-09 01:56 UTC
Labels: Bug, Core, Critical, Fixed Pending Verification, P2, Salt-SSH
