### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by qiangshui** [saltstack/salt#40578] opened 2017-04-07 06:11 UTC
I use file.recurse to transfer directories and files,once the file name contains chinese,there will be problems,those files couldn't be transfered to the spectified minions.debug info shows "UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-34: ordinal not in range(128)".

Here are my .sls:
`test1:`
  `  file.recurse:`
    `    - name: /root/group2test`
    `    - source: salt://release/test/{{pillar["test"]}}`
    `    - mkdirs: True`
    `    - include_empty: True`
 

Here are the debug info:
----------
          ID: test1
    Function: file.recurse
        Name: /root/group2test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 2807, in recurse
                  manage_file(dest, src)
                File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 2685, in manage_file
                  **pass_kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 1814, in managed
                  __env__
                File "/usr/lib/python2.6/site-packages/salt/modules/file.py", line 3490, in source_list
                  contextkey = '{0}_|-{1}_|-{2}'.format(source, source_hash, saltenv)
              UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-34: ordinal not in range(128)
     Started: 20:08:21.608398
    Duration: 1467.811 ms
     Changes:   
  Summary for g146
  ------------
  Succeeded: 0
  Failed:    1
  ------------
  Total states run:     1
  Total run time:   1.468 s
  [DEBUG   ] jid 20170407133951142263 found all minions set(['jenkins', 'g146'])
  ERROR: Minions returned with non-zero exit code

Here are the  debug logs:
2017-04-07 14:00:40,412 [salt.utils.event                                     ][DEBUG   ][15280] Sending event: tag = file.recurse; data = {'comment': 'An exception occurred in this state: Traceback (most recent call last):\n  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1746, in call\n    **cdata[\'kwargs\'])\n  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1703, in wrapper\n    return f(*args, **kwargs)\n  File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 2807, in recurse\n    manage_file(dest, src)\n  File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 2685, in manage_file\n    **pass_kwargs)\n  File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 1814, in managed\n    __env__\n  File "/usr/lib/python2.6/site-packages/salt/modules/file.py", line 3490, in source_list\n    contextkey = \'{0}_|-{1}_|-{2}\'.format(source, source_hash, saltenv)\nUnicodeEncodeError: \'ascii\' codec can\'t encode characters in position 31-34: ordinal not in range(128)\n', '_stamp': '2017-04-07T06:00:40.412486', 'retcode': 2, 'name': '/root/group2test', 'start_time': '20:28:36.031209', 'result': False, 'duration': 1336.1479999999999, '__run_num__': 0, 'changes': {}, '__id__': 'test1'}

Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

I not sure if I should modify the default coding that saltstack uesd and don't know which .py file should be modified.
My English is terrible,please forgive me

**Comment by Ch3LL** [comment] 2017-04-07 18:57
Can you please share a sanitized version of your file.managed source file so I can try to replicate?

**Comment by qiangshui** [comment] 2017-04-08 08:14
Sorry to reply late.I couldn't drag files to here,so I push source file to the repository 
https://github.com/qiangshui/saltfile.git, and I don't know if those files are waht you want.Those files are blow /usr/lib/python2.6/site-packages/salt.

**Comment by qiangshui** [comment] 2017-04-08 11:03
I already set python defaultencoding to utf-8,but this condition still exist.

**Comment by lubyou** [comment] 2017-06-05 16:24
Hi,

I am having a similar problem.
```
# unicode_issue.sls

c:\Déjà vu:
  file.touch
```

```
C:\salt>salt-call state.apply unicode_issue
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 379, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 550, in apply_
    return sls(mods, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 1053, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 2268, in call_high
    chunks = self.compile_high_data(high, orchestration_jid)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1324, in compile_high_data
    chunks = self.order_chunks(chunks)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1261, in order_chunks
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1261, in <lambda>
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 379, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 550, in apply_
    return sls(mods, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 1053, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 2268, in call_high
    chunks = self.compile_high_data(high, orchestration_jid)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1324, in compile_high_data
    chunks = self.order_chunks(chunks)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1261, in order_chunks
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1261, in <lambda>
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
```

I guess this could be fixed by #37692, however, I am wondering whether there is a way to get this working without having to wait for the complete switch to unicode.

```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```

`yaml_utf8: True`

**Comment by lubyou** [comment] 2017-06-07 06:55
@Ch3LL can you chime in on this?

Thank you

**Comment by Ch3LL** [comment] 2017-06-08 16:20
Looks like i am able to replicate this on 2016.11 branch. I cannot get it to fail consistently though. Sometimes it passes but most of the time it fails which makes it hard to run a git bisect on to gather which commit broke this issue. I am seeing this in all v2016.11 versions, but i'm not seeing it on 2016.3 versions. Looks like we need to get this fixed. Thanks.

Here is a docker container for anyone to quickly replicate this issue:

1. ` docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:40578 /bin/bash -c "export LANG=en_US.UTF-8; salt-call --local state.sls test -ldebug; locale"` (where /home/ch3ll/git/salt is a local cloned git repo of salt)

Looks like we will need to get this fixed thanks.

**Comment by lubyou** [comment] 2017-06-08 18:29
Hi,

Thanks for getting back to me.

I seem to be able to reproduce this on 2016.3.5 on Windows, too.

```
C:\>salt-call state.apply unicode_issue
[WARNING ] Template is an empty file: C:\Users\me\Desktop\srv\pillars\top.sls
[WARNING ] Template is an empty file: C:\Users\me\Desktop\srv\pillars\top.sls
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 379, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 550, in apply_
    return sls(mods, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 1053, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 2268, in call_high
    chunks = self.compile_high_data(high, orchestration_jid)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1324, in compile_high_data
    chunks = self.order_chunks(chunks)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1261, in order_chunks
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1261, in <lambda>
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 379, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 550, in apply_
    return sls(mods, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 1053, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 2268, in call_high
    chunks = self.compile_high_data(high, orchestration_jid)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1324, in compile_high_data
    chunks = self.order_chunks(chunks)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1261, in order_chunks
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1261, in <lambda>
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
```

```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```
 
```
C:\>chcp
Page de codes active : 850
```

**Comment by lubyou** [comment] 2017-06-08 18:51
Hi,

This seems to be happening on 2016.3.6 as well, at least on Windows:

```
C:\salt>salt-call state.apply unicode_issue
[WARNING ] Template is an empty file: C:\Users\me\Desktop\srv\pillars\top.sls
[WARNING ] Template is an empty file: C:\Users\me\Desktop\srv\pillars\top.sls
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 372, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 459, in apply_
    return sls(mods, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 946, in sls
    ret = st_.state.call_high(high_)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 2258, in call_high
    chunks = self.compile_high_data(high)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1317, in compile_high_data
    chunks = self.order_chunks(chunks)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1256, in order_chunks
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1256, in <lambda>
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 372, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 459, in apply_
    return sls(mods, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 946, in sls
    ret = st_.state.call_high(high_)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 2258, in call_high
    chunks = self.compile_high_data(high)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1317, in compile_high_data
    chunks = self.order_chunks(chunks)
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1256, in order_chunks
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1256, in <lambda>
    chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
```

**Comment by damon-atkins** [comment] 2017-06-09 02:11
FYI: There are issues python does not support Unicode on the windows console  until python 3.6.0, the issue has been around for a long long time and only recently fixed.  However do not thing this is your issue.

Unicode string that contains the unicode character U+00E9 (LATIN SMALL LETTER E WITH ACUTE).

**Comment by lubyou** [comment] 2017-06-09 17:25
Hi,

I agree about this not being an issue with the windows console, as it also happens when I run state.apply remotely:

```
xx@salt:~$ sudo salt win7-french.corp.example.com state.apply unicode_issue
win7-french.corp.example.com:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1465, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 550, in apply_
        return sls(mods, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 1053, in sls
        ret = st_.state.call_high(high_, orchestration_jid)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 2268, in call_high
        chunks = self.compile_high_data(high, orchestration_jid)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 1324, in compile_high_data
        chunks = self.order_chunks(chunks)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 1261, in order_chunks
        chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 1261, in <lambda>
        chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
```

It is the mix of unicode and string objects that blow up format():

![screen shot 2017-06-09 at 19 19 30](https://user-images.githubusercontent.com/300014/26986713-0f722a34-4d49-11e7-9a56-3852df032c92.png)

If I add
`from __future__ import unicode_literals`
to state.py, execution continues, the file gets created, and finally there is another exception in file.py due to mixed unicode/str objects being passed to format():

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1747, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1704, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 4547, in touch
    ret['comment'] = 'Created empty file {0}'.format(name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)

local:
----------
          ID: c:\Déjà vu
    Function: file.touch
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1747, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 4547, in touch
                  ret['comment'] = 'Created empty file {0}'.format(name)
              UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
     Started: 19:25:09.711000
    Duration: 15.0 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  15.000 ms
```

**Comment by mbochenk** [comment] 2017-06-30 15:24
I am running into exactly the same issue since upgrading from 2016.11.1 to 2016.11.6 or 2016.11.5
I am using file.find to find a file in a directory and set it into a jinja variable I use later on in the state. 
Unfortunately, there are occasionally directories that include unicode characters. This happens on both CentOS6 and CentOS7 (latest) and I get this error:
```
10:56:03			Traceback (most recent call last):
10:56:03			  File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
10:56:03			    output = template.render(**decoded_context)
10:56:03			  File "/usr/lib/python2.6/site-packages/jinja2/environment.py", line 1008, in render
10:56:03			    return self.environment.handle_exception(exc_info, True)
10:56:03			  File "/usr/lib/python2.6/site-packages/jinja2/environment.py", line 780, in handle_exception
10:56:03			    reraise(exc_type, exc_value, tb)
10:56:03			  File "<template>", line 10, in top-level template code
10:56:03			  File "...sls", line 95, in top-level template code
10:56:03			    {% set copy_path = salt.file.find(...)|sort|last %}
10:56:03			  File "/usr/lib/python2.6/site-packages/salt/modules/file.py", line 880, in find
10:56:03			    ret = [item for i in [finder.find(p) for p in glob.glob(os.path.expanduser(path))] for item in i]
10:56:03			  File "/usr/lib/python2.6/site-packages/salt/utils/find.py", line 642, in find
10:56:03			    for dirpath, dirs, files in os.walk(path):
10:56:03			  File "/usr/lib64/python2.6/os.py", line 284, in walk
10:56:03			    if isdir(join(top, name)):
10:56:03			  File "/usr/lib64/python2.6/posixpath.py", line 70, in join
10:56:03			    path += '/' + b
10:56:03			UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 7: ordinal not in range(128)
```

If I do `yum downgrade salt...` to 2016.11.1 everything works again.

I've worked around it for now by removing unicode characters, but that is really not a solution and just a temporary workaround. I do not think `--versions-report` is required since this behaviour is confirmed - however if needed I can generate one.

**Comment by lubyou** [comment] 2017-07-12 15:30
Hi,

Is it possible to share what the near-term plans are in regards to unicode support?
Unfortunately, without fullunicode support salt has limited usage to me.

Thank you

**Comment by terminalmage** [comment] 2017-07-12 19:07
@mbochenk This is not the same issue as the one originally reported. Can you please open a new issue, with an example we can use to reproduce this? Feel free to @ mention me. Thanks!

**Comment by damon-atkins** [comment] 2017-07-13 01:02
If you use `from __future__ import unicode_literals` for PY2 , you need to remember the rest of salt code is not, and any function within a module needs string checks to see if they are Unicode, and if not convert them to Unicode, otherwise you have a mix of string types being used within the function.

e.g.
File "/usr/lib64/python2.6/posixpath.py", line 70, in join
10:56:03			    path += '/' + b    #  I find you cannot concatenate a Non-Unicode String type and a Unicode String with Unicode Chars
10:56:03			UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 7: ordinal not in range(128)

**Comment by mbochenk** [comment] 2017-07-13 09:47
@terminalmage here's the issue: #42292 
However this happens in `file.find` - to me it seems the error has the same origin (`file` module?), although at a slightly different place.

**Comment by terminalmage** [comment] 2017-07-13 14:51
@mbochenk Same file, but not the same issue. We're working on a strategy for full unicode support, but until then we have to address these issues separately.

**Comment by damon-atkins** [comment] 2017-07-14 01:53
Try running the master with `export PYTHONIOENCODING=utf8` and salt, salt-call, see if it makes a difference.

**Comment by damon-atkins** [comment] 2017-07-30 16:52
https://github.com/saltstack/salt/pull/9053 introduced   `_yaml_result_unicode_to_utf8(data)`  in `salt/renderers/yaml.py` which turns the data into bytes.  i.e.   PY3 x.encode() returns bytes.

From Python3 example
```
>>> f=z.encode('utf-8')
>>> print(type(z))
<class 'str'>
>>> print(type(f))
<class 'bytes'>
```
I suspect this function should be converting PY2 strings (bytes) into Unicode type.
i.e. it should be more like https://github.com/saltstack/salt/issues/42278#issuecomment-318913952

**Comment by terminalmage** [comment] 2018-01-29 23:30
Much of this was already done with the work to overhaul unicode support, but the last pieces needed to satisfy this issue on have been added in #45772.

**Closed** 2018-02-05 18:22 UTC
Labels: Blocker, Bug, Core, Fixed Pending Verification, High Severity, Oxygen, P4
