### ISSUE TITLE
salt-cloud can't create LXC container with a specific LVM volume group

### ISSUE THREAD

**Issue by multani** [saltstack/salt#28310] opened 2015-10-26 19:13 UTC
It's a bit difficult to sum up the problem in the title, but I have the following problem. Considering the following salt-cloud configuration:

```
$ cat /etc/salt/cloud.profiles.d/lxc.conf
lxc-profile:
  dnsservers:
  - 8.8.8.8
  lxc_profile: debian
  minion:
    master: salt-master
    master_port: 4506
  network_profile: debian
  provider: lxc-provider

$ cat /etc/salt/cloud.providers.d/lxc.conf
lxc-provider:
  driver: lxc
  target: mylxchost
```

And the following pillar on the ``mylxchost``:

```
lxc.container_profile:
  debian:
    template: debian
    backing: lvm
    vgname: main
    size: 8G


lxc.network_profile:
  debian:
    eth0:
      link: lxcbr0
      type: veth
      flags: up
```

When running the command ``sudo salt-cloud test-foo -p lxc-profile -l all``, I get the following (truncated to the relevant bits):

```
[TRACE   ] get_event() received = {'data': {'_stamp': '2015-10-26T18:30:16.662805',
          'arg': ['test-foo',
                  {'dnsservers': ['8.8.8.8'],
                   'driver': 'lxc-provider:lxc',
                   'inline_script': None,
                   'lxc_profile': 'debian',
                   'minion': {'master': 'salt-master',
                              'master_port': 4506},
                   'name': 'test-foo',
                   'network_profile': 'debian',
                   'os': 'bootstrap-salt',
                   'priv_key': '...',
                   'profile': 'debian',
                   'pub_key': '...',
                   'target': 'mylxchost'}],
          'fun': 'lxc.cloud_init_interface',
          'jid': '20151026193016661957',
          'minions': ['mylxchost'],
          'tgt': 'mylxchost',
          'tgt_type': 'list',
          'user': 'sudo_jballet'},
 'tag': 'salt/job/20151026193016661957/new'}
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() received = {'data': {'_stamp': '2015-10-26T18:30:16.814323',
          'cmd': '_return',
          'fun': 'lxc.cloud_init_interface',
          'fun_args': ['test-foo',
                       {'dnsservers': ['8.8.8.8'],
                        'driver': 'lxc-provider:lxc',
                        'inline_script': None,
                        'lxc_profile': 'debian',
                        'minion': {'master': 'salt-master',
                                   'master_port': 4506},
                        'name': 'test-foo',
                        'network_profile': 'debian',
                        'os': 'bootstrap-salt',
                        'priv_key': '...',
                        'profile': 'debian',
                        'pub_key': '...',
                        'target': 'mylxchost'}],
          'id': 'mylxchost',
          'jid': '20151026193016661957',
          'retcode': 0,
          'return': {'autostart': True,
                     'bootstrap_args': None,
                     'bootstrap_shell': 'sh',
                     'bootstrap_url': None,
                     'clone_from': None,
                     'config': {'master': 'salt-master',
                                'master_port': 4506},
                     'dnsservers': ['8.8.8.8'],
                     'force_install': True,
                     'fstype': None,
                     'lvname': None,
                     'memory': 0,
                     'name': 'test-foo',
                     'network_profile': 'debian',
                     'nic_opts': {'eth0': {}},
                     'password': 's3cr3t',
                     'password_encrypted': False,
                     'path': None,
                     'priv_key': '...',
                     'profile': {'backing': 'lvm',
                                 'size': '8G',
                                 'template': 'debian',
                                 'vgname': 'main'},
                     'pub_key': '...',
                     'size': '8G',
                     'snapshot': False,
                     'unconditional_install': False,
                     'users': [],
                     'vgname': 'main'},
          'success': True},
 'tag': 'salt/job/20151026193016661957/ret/mylxchost'}
[DEBUG   ] jid 20151026193016661957 return from mylxchost
[TRACE   ] _get_event() waited 0 seconds and received nothing
[DEBUG   ] jid 20151026193016661957 found all minions set(['mylxchost'])
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt-master_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] get_iter_returns for jid 20151026193016830204 sent to set(['mylxchost']) will timeout at 19:40:16.846376
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() received = {'data': {'_stamp': '2015-10-26T18:30:16.831154',
          'arg': ['test-foo',
                  {'__kwarg__': True,
                   'autostart': True,
                   'bootstrap_args': None,
                   'bootstrap_shell': 'sh',
                   'bootstrap_url': None,
                   'clone_from': None,
                   'config': {'master': 'salt-master',
                              'master_port': 4506},
                   'dnsservers': ['8.8.8.8'],
                   'force_install': True,
                   'fstype': None,
                   'lvname': None,
                   'memory': 0,
                   'network_profile': 'debian',
                   'nic_opts': {'eth0': {}},
                   'password': 's3cr3t',
                   'password_encrypted': False,
                   'path': None,
                   'priv_key': '...',
                   'profile': {'backing': 'lvm',
                               'size': '8G',
                               'template': 'debian',
                               'vgname': 'main'},
                   'pub_key': '...',
                   'seed': True,
                   'size': '8G',
                   'snapshot': False,
                   'unconditional_install': False,
                   'users': [],
                   'vgname': 'main'}],
          'fun': 'lxc.init',
          'jid': '20151026193016830204',
          'minions': ['mylxchost'],
          'tgt': 'mylxchost',
          'tgt_type': 'glob',
          'user': 'sudo_jballet'},
 'tag': 'salt/job/20151026193016830204/new'}
```

I get this error in return:

```
event:
    ----------
    message:
        ----------
        comment:
        done:
        errors:
            ----------
            mylxchost:
                ----------
                test-foo:
                    - Invalid return for test-foo: Passed invalid arguments to lxc.init: _get_base() got multiple values for keyword argument 'vgname'
                    -
                    -     Initialize a new container.
                    -
                    -     This is a partial idempotent function as if it is already provisioned, we
                    -     will reset a bit the lxc configuration file but much of the hard work will
                    -     be escaped as markers will prevent re-execution of harmful tasks.
                    -
                    -     name
                    -         Name of the container
                    -
                    -     image
                    -         A tar archive to use as the rootfs for the container. Conflicts with
                    -         the ``template`` argument.
                    -
                    -     cpus
                    -         Select a random number of cpu cores and assign it to the cpuset, if the
                    -         cpuset option is set then this option will be ignored
                    -
                    -     cpuset
                    -         Explicitly define the cpus this container will be bound to
                    -
                    -     cpushare
                    -         cgroups cpu shares
                    -
                    -     autostart
                    -         autostart container on reboot
                    -
                    -     memory
                    -         cgroups memory limit, in MB
                    -
                    -         .. versionchanged:: 2015.5.0
                    -             If no value is passed, no limit is set. In earlier Salt versions,
                    -             not passing this value causes a 1024MB memory limit to be set, and
                    -             it was necessary to pass ``memory=0`` to set no limit.
                    -
                    -     gateway
                    -         the ipv4 gateway to use
                    -         the default does nothing more than lxcutils does
                    -
                    -     bridge
                    -         the bridge to use
                    -         the default does nothing more than lxcutils does
                    -
                    -     network_profile
                    -         Network profile to use for the container
                    -
                    -         .. versionadded:: 2015.5.0
                    -
                    -     nic
                    -         .. deprecated:: 2015.5.0
                    -             Use ``network_profile`` instead
                    -
                    -     nic_opts
                    -         Extra options for network interfaces, will override
                    -
                    -         ``{"eth0": {"hwaddr": "aa:bb:cc:dd:ee:ff", "ipv4": "10.1.1.1", "ipv6": "2001:db8::ff00:42:8329"}}``
                    -
                    -         or
                    -
                    -         ``{"eth0": {"hwaddr": "aa:bb:cc:dd:ee:ff", "ipv4": "10.1.1.1/24", "ipv6": "2001:db8::ff00:42:8329"}}``
                    -
                    -     users
                    -         Users for which the password defined in the ``password`` param should
                    -         be set. Can be passed as a comma separated list or a python list.
                    -         Defaults to just the ``root`` user.
                    -
                    -     password
                    -         Set the initial password for the users defined in the ``users``
                    -         parameter
                    -
                    -     password_encrypted : False
                    -         Set to ``True`` to denote a password hash instead of a plaintext
                    -         password
                    -
                    -         .. versionadded:: 2015.5.0
                    -
                    -     profile
                    -         A LXC profile (defined in config or pillar).
                    -         This can be either a real profile mapping or a string
                    -         to retrieve it in configuration
                    -
                    -     start
                    -         Start the newly-created container
                    -
                    -     dnsservers
                    -         list of dns servers to set in the container, default [] (no setting)
                    -
                    -     seed
                    -         Seed the container with the minion config. Default: ``True``
                    -
                    -     install
                    -         If salt-minion is not already installed, install it. Default: ``True``
                    -
                    -     config
                    -         Optional config parameters. By default, the id is set to
                    -         the name of the container.
                    -
                    -     master
                    -         salt master (default to minion's master)
                    -
                    -     master_port
                    -         salt master port (default to minion's master port)
                    -
                    -     pub_key
                    -         Explicit public key to preseed the minion with (optional).
                    -         This can be either a filepath or a string representing the key
                    -
                    -     priv_key
                    -         Explicit private key to preseed the minion with (optional).
                    -         This can be either a filepath or a string representing the key
                    -
                    -     approve_key
                    -         If explicit preseeding is not used;
                    -         Attempt to request key approval from the master. Default: ``True``
                    -
                    -     path
                    -         path to the container parent directory
                    -         default: /var/lib/lxc (system)
                    -
                    -         .. versionadded:: 2015.8.0
                    -
                    -     clone
                    -         .. deprecated:: 2015.5.0
                    -             Use ``clone_from`` instead
                    -
                    -     clone_from
                    -         Original from which to use a clone operation to create the container.
                    -         Default: ``None``
                    -
                    -     bootstrap_delay
                    -         Delay in seconds between end of container creation and bootstrapping.
                    -         Useful when waiting for container to obtain a DHCP lease.
                    -
                    -         .. versionadded:: 2015.5.0
                    -
                    -     bootstrap_url
                    -         See lxc.bootstrap
                    -
                    -     bootstrap_shell
                    -         See lxc.bootstrap
                    -
                    -     bootstrap_args
                    -         See lxc.bootstrap
                    -
                    -     force_install
                    -         Force installation even if salt-minion is detected,
                    -         this is the way to run vendor bootstrap scripts even
                    -         if a salt minion is already present in the container
                    -
                    -     unconditional_install
                    -         Run the script even if the container seems seeded
                    -
                    -     CLI Example:
                    -
                    -     .. code-block:: bash
                    -
                    -         salt 'minion' lxc.init name [cpuset=cgroups_cpuset] \
                    -                 [cpushare=cgroups_cpushare] [memory=cgroups_memory] \
                    -                 [nic=nic_profile] [profile=lxc_profile] \
                    -                 [nic_opts=nic_opts] [start=(True|False)] \
                    -                 [seed=(True|False)] [install=(True|False)] \
                    -                 [config=minion_config] [approve_key=(True|False) \
                    -                 [clone_from=original] [autostart=True] \
                    -                 [priv_key=/path_or_content] [pub_key=/path_or_content] \
                    -                 [bridge=lxcbr0] [gateway=10.0.3.1] \
                    -                 [dnsservers[dns1,dns2]] \
                    -                 [users=[foo]] [password='secret'] \
                    -                 [password_encrypted=(True|False)]
                    -
                    [...]
```

I'm running the following:

```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 2.6.32-openvz-042stab111.11-amd64
         system: debian 8.2 

$ salt-cloud --versions-report
Salt Version:
            Salt: 2015.8.1
 
Dependency Versions:
 Apache Libcloud: 0.17.0
          Jinja2: 2.7.3
        M2Crypto: Not Installed
            Mako: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.4.0
          Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.2
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.2
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: Not Installed
         timelib: Not Installed
 
System Versions:
            dist: debian 8.2 
         machine: x86_64
         release: 2.6.32-openvz-042stab111.11-amd64
          system: debian 8.2 
```

The documentation regarding the LXC configuration and how it behave with salt-cloud is also not very clear, which bits go where, so hopefully the configuration is OK...

**Comment by jfindlay** [comment] 2015-10-29 20:30
@multani, thanks for the report.

**Comment by pass-by-value** [comment] 2015-12-02 20:14
Hi @multani 

Thanks for reporting this, sorry for the delay in getting back to you. I was able to reproduce this issue (but don't have a fix yet). Seems like specifying the `vgname` key causes this issue to manifest.

If you don't require a volume group the following should let you create lxc containers without any problem (posting them here just in case)

Cloud profile
```yaml
ubuntu-lxc:
  provider: dev-lxc
  lxc_profile:
    template: download
    options:
      release: trusty
      arch: amd64
  image: ubuntu
  seed: False
  network_profile: ubuntu
  minion:
    master: localhost
```

Network profile
```yaml
lxc.network_profile:
  ubuntu:
    eth0:
      link: virbr0
```

**Comment by pass-by-value** [comment] 2015-12-04 20:01
Created #29447 for this

**Comment by basepi** [comment] 2016-01-07 16:34
Looks like the pull request was merged. Closing.

**Closed by basepi** 2016-01-07 16:34 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P4, RIoT, Salt-Cloud, TEAM RIoT
