### ISSUE TITLE
postgres.has_privileges module breaks with Python3 when granting ALL privileges

### ISSUE THREAD

**Issue by haam3r** [saltstack/salt#48465] opened 2018-07-06 14:34 UTC
### Description of Issue/Question
The postgres.has_privileges module uses the .sort() method when checking 'ALL' privileges:
https://github.com/saltstack/salt/blob/develop/salt/modules/postgres.py#L2829

This is not supported in Python 3: https://docs.python.org/3/whatsnew/3.0.html thereby breaking.

If the proposed fix below is acceptable, I can make a PR.

### Setup
Ubuntu 18.04 server running salt minion 2018.3.2

Example state that will break: https://github.com/haam3r/cuckoo-salt/blob/master/cuckoo/deps.sls#L71-L80

```
cuckoodb_priv:
  postgres_privileges.present:
    - name: {{ salt['pillar.get']('db:name', 'cuckoo') }}
    - object_name: {{ salt['pillar.get']('db:user', 'cuckoo') }}
    - object_type: database
    - privileges:
      - ALL
    - require:
      - postgres_database: cuckoodb
      - postgres_user: cuckoodb_user
```

### Steps to Reproduce Issue
```
----------
          ID: db_priv
    Function: postgres_privileges.present
        Name: cuckoo
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1851, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/postgres_privileges.py", line 180, in present
                  name, object_name, object_type, **kwargs):
                File "/usr/lib/python3/dist-packages/salt/modules/postgres.py", line 2827, in has_privileges
                  retval = perms.sort() == _privileges[name].keys().sort()
              AttributeError: 'dict_keys' object has no attribute 'sort'
     Started: 08:43:19.595202
    Duration: 560.033 ms
     Changes:   
----------
```
### Fix

Change line https://github.com/saltstack/salt/blob/develop/salt/modules/postgres.py#L2829 to use the sorted method:

```python
retval = sorted(perms) == sorted(_privileges[name].keys())
```
After change:

```python
----------
          ID: db_priv
    Function: postgres_privileges.present
        Name: cuckoo
      Result: True
     Comment: The privilege(s): ALL have been granted to cuckoo
     Started: 09:33:41.933012
    Duration: 1429.773 ms
     Changes:   
              ----------
              cuckoo:
                  Present
```
### Versions Report

Salt master is running 2018.3.2 with Python 2 on Ubuntu 16.04

Versions report for the affected minion:
```
salt-call --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Apr  1 2018, 05:46:30)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-112-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by haam3r** [comment] 2018-07-13 06:31
@garethgreenaway Would you like me to make a PR with the proposed fix or is there some other plan?

**Comment by prakyathr-uc** [comment] 2019-01-22 10:31
I got same error. The fix provided works perfectly for python 2 and 3. @garethgreenaway when will the code be fixed? I checked the postgres module code in version 2019.1 RC and found that the issue is not yet fixed.

**Comment by x70b1** [comment] 2019-03-06 09:17
There is a second issue with that problem: https://github.com/saltstack/salt/issues/51450
But there is also no response.

**Comment by thequailman** [comment] 2020-04-03 21:05
Hello, when will this fix land?  I am encountering this error still on 3000.1

**Comment by alexinvestor** [comment] 2020-05-27 23:18
Still in 3000.3 (3000.3+ds-1 on Debian).  Workaround: I use a salt build, so add a perl stanza to overwrite this line after having installed saltstack.

**Comment by henning** [comment] 2020-07-03 21:18
I'm bitten by this, too. Is there anything I can do to help it being fixed? Is it worth to prepare a PR? there seem many open, so I'd like to invest the time only if theres chance it's getting considered.

**Comment by OrangeDog** [comment] 2020-07-03 22:49
@henning it was fixed over a year ago, but needs merging again: #57487.

@waynew this should also have the `python3` label.

**Comment by fpicot** [comment] 2020-07-16 09:08
This is still affecting salt 3001. Any chance it gets merged for the 3001.1 ?

**Comment by BrianSidebotham** [comment] 2020-10-19 12:26
What does someone need to do in order to re-merge this fix. It's a single line change and it's stood here for nearly 2.5 years.

Python 3 is now the only choice, so this bug is really annoying. The last thing we want to do is maintain salt states that patch salt's known bugs after installation.

Bugs in the modules like this really affect automated deployments. It appears there is zero feedback or involvement from anyone in the saltstack project.

**Comment by parmus** [comment] 2020-11-30 09:25
The Salt 3002 Release Notes (https://docs.saltstack.com/en/latest/topics/releases/3002.html) claims that this bug is fixed, but the conversation in this issue suggest otherwise. Which is true?

**Comment by OrangeDog** [comment] 2020-11-30 12:24
It looks like it's been fixed. I don't know why @sagetherage has moved it to Aluminium.

**Comment by sagetherage** [comment] 2020-11-30 20:50
I think Github didn't like me, I got it in the GH project, but the label never applied or the milestone, all fixed! thanks for the heads up.

**Comment by OrangeDog** [comment] 2020-11-30 21:23
@sagetherage this issue was fixed in Magnesium (3002).

**Comment by garethgreenaway** [comment] 2020-12-16 16:24
Closing per the fix in https://github.com/saltstack/salt/pull/57487

**Closed by garethgreenaway** 2020-12-16 16:24 UTC
Labels: Aluminium, Bug, Community, phase-plan, python3, severity-medium, status-in-prog
