### ISSUE TITLE
file.uncomment does not uncomment as expected 

### ISSUE THREAD

**Issue by Akshaykapoor** [saltstack/salt#24907] opened 2015-06-23 18:49 UTC
I want to uncomment a line from a config file,

```
# Use name-based virtual hosting.
#
# NameVirtualHost *:80 --> This line is to be uncommented
#
# NOTE: NameVirtualHost cannot be used without a port specifier
# (e.g. :80) if mod_ssl is being used, due to the nature of the
# SSL protocol.
```

In my salt state i'm writing the following,

```
/etc/httpd/conf/httpd.conf:
  file.uncomment:
    - regex: NameVirtualHost\W+\d+
```

This results in the a failure,

```
          ID: /etc/httpd/conf/httpd.conf
    Function: file.uncomment
      Result: False
     Comment: Expected uncommented lines not found
     Started: 18:40:32.721247
    Duration: 31.288 ms
```

Looking at the debug log, i came across this, 

```
sed -i.bak -r -e '/NameVirtualHost\\W+\\d+/ s/^([[:space:]]*)#/\\1/g' /etc/httpd/conf/httpd.conf
```

which makes me think that i cannot use the different characters that i'm using '\W\d'. Not quite sure if this is a bug in salt but the my running it on CentOS 6.6 and salt version 

```
           Salt: 2014.7.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

How can i achieve the desired output using file.uncomment ?

**Comment by arroyoc** [comment] 2015-06-25 19:51
@Akshaykapoor thanks for your report. Can you reproduce this on salt versions 2015.5.2?

**Comment by Akshaykapoor** [comment] 2015-06-26 21:57
@arroyoc Will update the salt versions to that and get back with the results soon.

**Comment by MoonSweep** [comment] 2015-08-05 11:13
I'm not sure if it's the same issue, but the error message makes me think it might be related.

I used to successfully uncomment a bunch of lines in `/etc/vim/vimrc` with a single `file.uncomment` snippet:

```
vim:
  file.uncomment:
    - name: /etc/vim/vimrc
    - char: '"'
    - regex: (syntax on|set (background=dark|showcmd|showmatch|ignorecase))
```

I'm *pretty sure* it used to work (at least on a first run, see [#25345](https://github.com/saltstack/salt/issues/25345)). Now with 2015.5.3, it doesn't work anymore:

```
----------
          ID: vim
    Function: file.uncomment
        Name: /etc/vim/vimrc
      Result: False
     Comment: Expected uncommented lines not found
     Started: 12:07:17.406047
    Duration: 36.188 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -16,11 +16,11 @@
                   
                   " Vim5 and later versions support syntax highlighting. Uncommenting the next
                   " line enables syntax highlighting by default.
                  -"syntax on
                  +(syntax on|set (background=dark|showcmd|showmatch|ignorecase))
                   
                   " If using a dark background within the editing area and syntax highlighting
                   " turn on this option as well
                  -"set background=dark
                  +(syntax on|set (background=dark|showcmd|showmatch|ignorecase))
                   
                   " Uncomment the following to have Vim jump to the last position when
                   " reopening a file
                  @@ -36,9 +36,9 @@
                   
                   " The following are commented out as they cause vim to behave a lot
                   " differently from regular Vi. They are highly recommended though.
                  -"set showcmd		" Show (partial) command in status line.
                  -"set showmatch		" Show matching brackets.
                  -"set ignorecase		" Do case insensitive matching
                  +(syntax on|set (background=dark|showcmd|showmatch|ignorecase))		" Show (partial) command in status line.
                  +(syntax on|set (background=dark|showcmd|showmatch|ignorecase))		" Show matching brackets.
                  +(syntax on|set (background=dark|showcmd|showmatch|ignorecase))		" Do case insensitive matching
                   "set smartcase		" Do smart case matching
                   "set incsearch		" Incremental search
                   "set autowrite		" Automatically save before commands like :next and :make
```
It successfully detects which lines to uncomment, but instead of uncommenting, **it replaces the matching pattern with the whole regexp**.

If file.(un)comment are untrustworthy to the point that your usual answer is to advise using `file.managed` instead (like [here](https://github.com/saltstack/salt/issues/2875#issuecomment-11273310) or [here](https://github.com/saltstack/salt/issues/25345#issuecomment-121020653)), you could as well remove them from Salt completely and be done with it. I'd rather *spend* my time being creative with less tools (`cmd.run` `sed` commands always works) than *wasting* my time fixing the mess and reporting issues about things that used to work and that I should be able to trust.

Seriously, this is an awful regression. It needs to be fixed ASAP.

**Comment by piotrooo** [comment] 2015-08-19 13:58
:+1: 

When this functionality will be back? This regression is really nasty.

**Comment by xcorvis** [comment] 2015-08-27 14:28
I can confirm this in 2015.5.3. What other info is needed?

```
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1precise2
```

**Comment by arroyoc** [comment] 2015-08-27 15:39
@Akshaykapoor We shouldn't need anymore information. This issue has been labeled appropriately and will be taken care of as soon as we can get to it. Thanks for your help.

**Comment by russellballestrini** [comment] 2016-12-22 01:55
Seems to still be an issue in 2016.11.1

**Comment by nhavens** [comment] 2017-08-02 22:01
Here's an example of file.uncomment not working properly:

/tmp/default.pa
```
#load-sample-lazy x11-bell /usr/share/sounds/freedesktop/stereo/bell.oga
### Load X11 bell module
#load-module module-x11-bell sample=x11-bell
```
/srv/salt/uncomment.sls
```
uncomment x11 bell lines in pulse audio config:
  file.uncomment:
    - name: /tmp/default.pa
    - regex: ".*x11-bell.*"
    - backup: False
```
```
# salt '*minion*' state.apply uncomment
minion.local:
----------
          ID: uncomment x11 bell lines in pulse audio config
    Function: file.uncomment
        Name: /tmp/default.pa
      Result: True
     Comment: Pattern already uncommented
     Started: 15:49:10.981964
    Duration: 6.449 ms
     Changes:   

Summary for minion.local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   6.449 ms
```

**Comment by russellballestrini** [comment] 2018-11-25 23:38
This is def still an issue, stale bot.

**Comment by nee2c** [comment] 2021-04-26 02:36
I question if it is the state file.uncomment function and not the renderer that is rendering the state file that is the root of the problem.  I had a similar problem and found it to be that the yaml was rendering the escape characters in the regex strings.  I had a look at the code and sure I think the code could be simplified a bit but logic looks good.

The code that dose the heavy lifting of updating the file has been update about year ago so I think MoonSweep's issue is now mute.

For future reference nhavens example he has an wild card that will include the comment character and docs says don't include comment character.  It is taking for example "#foox11-bellbar" to be uncommented due to wildcards and no matter what it will consider the line already uncommented.

So my take on this issue, that it has been all issues have been fixed or explained but docs could be updated to make things a little clearer.
I would put in a pull request updating docs with warnings to using wild cards and escape character.
Any thoughts?

**Comment by thatch45** [comment] 2023-07-11 21:21
I am going to close this out and request a new issue be filed verifying this on the latest release. Assuming this is a real issue it should be fixed.
Please verify this bug and open a fresh issue so that we can start from a clean place given that the code almost certainly has changed since this issue was opened

**Closed by thatch45** 2023-07-11 21:21 UTC
Labels: State-Module, Bug, severity-medium, Platform
