### ISSUE TITLE
dulwich powered gitfs_remotes act funky while being updated

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#21144] opened 2015-02-28 01:13 UTC
I took a look at using dulwich as my gitfs provider and although initially things seemed to work I ran into a major problem I can consistently reproduce.  My states are backed by a single repo. In the moments after push changes to simple state which is just a single file.recurse block and a directory with a dozen files and with this I can consistently get salt to fail. Running salt-call repeatedly ('state.sls whatever') on a minion I see the following behavior:

0-10 secs: old state applies cleanly with no error (time varies, my loop_interval is 15)
10-30 secs: 
```
local:
    Data failed to compile:
----------
    No matching sls found for 'whatever' in env 'base'
```
30-45 secs:
```
local:
----------
          ID: /srv/whatever
    Function: file.recurse
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 22:16:37.744695
    Duration: 151.943 ms
     Changes:   
```
And then at some point it actually picks up the change and that state runs fine again.  I do not see the same behavior with "gitfs_provider: gitpython" My git repo is on bitbucket and I'm connecting with a git+ssh://git@bitbucket.org/acct/repo.git url.

My dulwich version is 0.9.4 which (current version in Ubuntu 14.04 package 'python-dulwich'). So perhaps the minimum version of Dulwich specified in the docs needs to be higher than 0.9.4 from in #19875.  Honestly I didn't try 0.9.8 from pip, nor any intermediary release to see whether this issue went away, I just dropped Dulwich altogether.

**Comment by rallytime** [comment] 2015-03-02 17:40
Thanks for this great report @notpeter. I think you're right, the workaround here is "use GitPython or even better, PyGit2, if you can" but we should still address these issues with Dulwich.

ping @terminalmage

**Comment by terminalmage** [comment] 2015-03-02 18:21
@notpeter Did you try a different provider before dulwich? I've noticed some incompatibilities between how Dulwich and GitPython/pygit2 handle refs, which make it necessary to clear the cache if switching between dulwich and non-dulwich. I recently (within the last week or so) added some runner functions to the fileserver runner and updated the Gitfs Walkthrough. However, these docs updates have not yet been reflected on docs.saltstack.com.

**Comment by notpeter** [comment] 2015-03-02 21:02
@terminalmage Yes. I did have to purge my gitfs cache to start using dulwich, there were errors in my master log and I figured purging cache was the correct move and it got things going.

**Comment by terminalmage** [comment] 2015-03-19 20:43
@notpeter I am not able to reproduce this. Keep in mind that the master only updates the remote fileserver backends every 60 seconds or so. Therefore, in the "moments after" you push to a repository, it is unlikely that the updates will be available. This, I think, is the reason for the issue you were experiencing. I don't think it was a dulwich issue at all. If you have a minion running on the git server, you can use [this walkthrough](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#refreshing-gitfs-upon-push) to use the reactor system to force the fileserver to update whenever you push to the repo.

I'm going to close this for the reasons mentioned above. Please reply if the same issue comes up again and I'll be happy to investigate.

**Closed by terminalmage** 2015-03-19 20:43 UTC
Labels: Bug, Medium Severity

**Comment by notpeter** [comment] 2015-03-19 21:32
The issue is not that my changes were unavailable in the moments after push it's that *none* of my states were available while the repo was refreshing. It may be because of the size of my repo (current checkout 5M), past state of the repo (~30M history), round trip to bitbucket or my slightly out of date Dulwich but whatever the root cause the symptoms were clear: on every push my salt master would be out of commission for and throw errors at clients.

Pushing to a repo should never cause a minions highstate to fail, the master should handle those operations (semi) atomically. There should be zero time of "bad behavior" between serving two revisions of a file.

Perhaps this is an underlying provider agnostic gitfs issue and that window is just so small I never hit that race condition with GitPython, but in my setup when I used Dulwich it was 100% reproducible failures for many seconds following every gitfs refresh.

**Comment by terminalmage** [comment] 2015-03-19 21:49
OK, I still couldn't reproduce it. In the end, perhaps only newer dulwich releases are stable enough. I personally was testing with 0.9.7.
