### ISSUE TITLE
Documentation versioning broken after looking at Develop 

### ISSUE THREAD

**Issue by weswhet** [saltstack/salt#47192] opened 2018-04-19 19:59 UTC
### Description of Issue/Question

If you go to https://docs.saltstack.com/en/latest/ref/modules/all/index.html and the click on the "develop" version of the docs it will take you too https://docs.saltstack.com/en/develop/ref/modules/all/index.html which is expected. Except the red checkmark stays on 2018.3.0. Clicking on 2018.3.0 does not take you back to that version of documentation, it stays on develop. Same thing happens when clicking on 2017.7.3

Happens in both Safari and Chrome.

**Comment by Ch3LL** [comment] 2018-04-20 16:55
i'm pretty stumped on this one. @rallytime or @UtahDave  any ideas here? I swear this was working previously.

**Comment by weswhet** [comment] 2018-04-20 17:04
Fairly certain it was working last week.

**Comment by UtahDave** [comment] 2018-04-20 23:15
Duplicate of https://github.com/saltstack/salt/issues/47179

Let's continue convo there.

**Closed by UtahDave** 2018-04-20 23:15 UTC
Labels: Bug, Documentation, Medium Severity, P2
