### ISSUE TITLE
opts file_roots gets overwritten with pillar_roots in orchestration run

### ISSUE THREAD

**Issue by github-abcde** [saltstack/salt#46004] opened 2018-02-13 14:35 UTC
### Description of Issue/Question
Like https://github.com/saltstack/salt/issues/5449 but under different circumstances.
When perfoming an orchestration run with specific contents (see below), `__opts__['file_roots']` of the orchestration-salt-instance gets filled with the contents of `__opts__['pillar_roots']`, which causes all sorts of 'file not found'-problems.

### Setup
master config:
```
renderer: jinja | yaml | gpg
file_roots:
  base:
  - /srv/salt/states
pillar_roots:
  base:
  - /srv/salt/pillar/base
  test:
  - /srv/salt/pillar/test
  prod:
  - /srv/salt/pillar/prod
```

`/srv/salt/states/main.sls`:
```
include:
- one
- two
```
`/srv/salt/states/one.sls`:
```
{%- set foo = salt['saltutil.runner']('pillar.show_pillar', minion='foo') %}
{%- import_yaml tpldir + '/main.sls' as bar %}
placeholder_one:
  test.succeed_without_changes
```
`/srv/salt/states/two.sls`:
```
placeholder_two:
  test.succeed_without_changes
```

### Steps to Reproduce Issue
run `salt-run state.orchestrate main` and notice the error:
```
Specified SLS two in saltenv base is not available on the salt master or through a configured fileserver
```

It is also possible to move the `import_yaml`-statement to `two.sls`, and noticing that `two.sls` then fails to compile (because `main.sls` can not be found). However, that error is much more complex to parse.

Adding `    log.debug(__name__ + ':find_file:\n\t\topts: {}'.format(__opts__['file_roots']))` to `fileserver/roots.py:96` (before `for root in __opts__['file_roots'][saltenv]:`) clearly shows the change of the file_roots when running the orchestration with `-l debug`:
...
```
[DEBUG   ] salt.loaded.int.fileserver.roots:find_file:
		opts: {'base': ['/srv/salt/states']}
[DEBUG   ] In saltenv 'base', looking at rel_path 'one.sls' to resolve 'salt://one.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/master/files/base/one.sls' to resolve 'salt://one.sls'
[DEBUG   ] compile template: /var/cache/salt/master/files/base/one.sls
```
...
```
[DEBUG   ] Sending event: tag = salt/run/20180213152955427735/ret; data = {'fun_args': [{'minion': 'foo'}], 'jid': '20180213152955427735', 'return': {}, 'success': True, '_stamp': '2018-02-13T14:29:55.471971', 'user': 'UNKNOWN', 'fun': 'runner.pillar.show_pillar'}
[INFO    ] Runner completed: 20180213152955427735
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] salt.loaded.int.fileserver.roots:find_file:
		opts: {'test': ['/srv/salt/pillar/test'], 'base': ['/srv/salt/pillar/base'], 'prod': ['/srv/salt/pillar/prod']}
```

### Versions Report
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Waples** [comment] 2018-02-13 15:45
I am getting the same error as @github-abcde; reproduced with information given on a fresh salt. Note: I am using salt 2017.7.3 with python3.6

### Output
```
[DEBUG   ] Sending event: tag = salt/run/20180213164038482118/ret; data = {'fun': 'runner.state.orchestrate', 'jid': '20180213164038482118', 'user': 'root', 'fun_args': ['main', {'orchestration_jid': '20180213164038482118'}], '_stamp': '2018-02-13T15:40:40.217216', 'return': {'data': {'jotunheimr_master': ['Specified SLS two in saltenv base is not available on the salt master or through a configured fileserver']}, 'outputter': 'highstate', 'retcode': 1}, 'success': False}
[DEBUG   ] LazyLoaded highstate.output
jotunheimr_master:
    Data failed to compile:
----------
    Specified SLS two in saltenv base is not available on the salt master or through a configured fileserver
[INFO    ] Runner completed: 20180213164038482118
[DEBUG   ] Runner return: {'outputter': 'highstate', 'retcode': 1}
```

### Versions
```
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.11.4
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: 1.7.4
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.3
         Python: 3.6.4 (default, Jan  5 2018, 02:35:40)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.4
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: arch Arch Linux
         locale: UTF-8
        machine: x86_64
        release: 4.15.2-2-ARCH
         system: Linux
        version: arch Arch Linux
```

**Comment by Ch3LL** [comment] 2018-02-13 17:23
i'm able to replicate this with your current use case. Here is a docker container for anyone to quickly replicate this:

I think one of the issues that might be the cultprit is this `{%- set foo = salt['saltutil.runner']('pillar.show_pillar', minion='*') %}` 
When i remove that it works. Also i think thats why its showing the pillar files rendering.

Was this previously working because I see the same behavior in 7.2?

**Comment by github-abcde** [comment] 2018-02-14 10:43
I only started looking for the cause of this when I encountered it, and this was not the case in 7.2. However, the minimal reproduction steps I distilled seem to consistently replicate the issue in all versions I tested (2016.3.1, 2016.11.1, 2016.11.7, 2016.11.8, 2016.11.9, 2017.7.1, 2017.7.2 and of course 2017.7.3).

**Comment by github-abcde** [comment] 2018-02-16 08:42
Another weird thing, is that when I add `sleep(1)` on `salt/runners/pillar.py:101`, the issue does *not* seem to occur.

**Comment by github-abcde** [comment] 2018-02-19 10:32
@Ch3LL Do you have enough information to unblock this issue? Or is there something else you're waiting for?

**Comment by github-abcde** [comment] 2018-02-19 15:52
I suspect that it's related to the Jinja rendering context, which somehow mixes up between rendering the state (from `salt/state.py:render_state`) and the nested pillar render caused by the pillar runner.
When I wrap `__opts__` in a `copy.deepcopy` in https://github.com/saltstack/salt/blob/develop/salt/renderers/jinja.py#L63, the problem seems to go away (at least for me, at this moment).

**Comment by Ch3LL** [comment] 2018-02-20 15:53
ping @saltstack/team-core any ideas here as to why this is occuring?

**Comment by terminalmage** [comment] 2018-02-21 14:51
This seems to be happening because orchestration is not being used properly. When you run orchestration, you're supposed to use a different SLS schema. When I changed the main.sls in @Ch3LL's container to use proper orchestration SLS, the orchestration succeeded.

**Comment by github-abcde** [comment] 2018-02-21 15:56
@terminalmage Could you explain what changes those would be? When I download and use Ch3ll's container, I'm now unable to reproduce the problem, even when I use the sls-files I posted in the reproduction steps.

**Comment by terminalmage** [comment] 2018-02-21 16:20
@github-abcde when you run `salt-run state.orchestrate main`, what is happening is that `main.sls` is processed through the state compiler. The includes are resolved, and the end result is equivalent to if the contents of `one.sls` and `two.sls` were pasted into `main.sls`. The problem with this is that the orchestration engine is only supposed to run states expressed using [this schema](https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html#state). You are essentially short-circuiting how orchestration is supposed to work by telling the orchestration engine to run the contents of those SLS files rather than telling it to execute the SLS targets using a `salt.state` entry. You are misusing orchestration, albeit in a way that we are not catching and flagging as invalid usage.

We should be able to catch this when the low chunks are compiled, but there's a chicken-and-egg problem here because we can't compile the low chunks until the high data is rendered, which isn't able to complete because of the error in the jinja context.

I'll continue to look into ways of fixing that jinja issue so that we can properly render the high data and then check the low chunks. For now though, you should be able to get this to work if you just change `main.sls` to use orchestration SLS like so:

```yaml
step 1:
  salt.state:
    - tgt: some_minion
    - sls:
      - one

step 2:
  salt.state:
    - tgt: some_minion
    - sls:
      - two
```

**Comment by terminalmage** [comment] 2018-02-21 16:23
Note, if you want to run both SLS files in a single go, you can do:

```yaml
step 1:
  salt.state:
    - tgt: some_minion
    - sls:
      - one
      - two
```

**Comment by terminalmage** [comment] 2018-02-21 23:04
@github-abcde OK, so I've found the problem. You were still using orchestration incorrectly, but there is also a bug, so I'm working on both a fix to that bug and also a means to properly exit with an error when you try to run salt states directly in what should be an orchestration SLS file.

**Comment by terminalmage** [comment] 2018-02-22 01:30
@github-abcde I've had some conversations internally with the other devs and we've decided not to flag your usage as invalid. It's not technically orchestration, but it is the equivalent of running a `state.sls` on the master without needing a minion to do it, which is useful. So we'll keep the behavior and I will see to it that this is properly documented.

**Comment by terminalmage** [comment] 2018-02-22 03:58
Fix submitted in https://github.com/saltstack/salt/pull/46145

**Comment by github-abcde** [comment] 2018-02-22 08:38
Awesome. And all this while I was sleeping :)
The 'misuse' of orchestration was a (happy?) coincidence when trying to derive a minimal reproduction for this issue. Originally I have proper calls to `state.sls` in the included sls-files (but that would require a running minion).

**Comment by terminalmage** [comment] 2018-02-28 22:50
Fix is merged, marking this as closed. Thanks for helping alert us to this!

**Closed by terminalmage** 2018-02-28 22:50 UTC
Labels: Fixed Pending Verification, Pending Discussion
