### ISSUE TITLE
Minions can have *s in the minion-id, but salt-key doesn't handle *s for targetting

### ISSUE THREAD

**Issue by zmalone** [saltstack/salt#30182] opened 2016-01-06 19:29 UTC
It's possible to create minions with special characters, like "*" or "\" in the minion-id, as long as the minion-id does not start with a special character.  After you've done that, it is difficult to target those minions using salt-key, for example:

```
$ sudo salt-key -d "foo.bar.com*"
The following keys are going to be deleted:
Accepted Keys:
foo.bar.com
foo.bar.com*
$ sudo salt-key -d "foo.bar.com\*"
The key glob 'foo.bar.com\\*' does not match any accepted, unaccepted or rejected keys.
$ sudo salt-key -d foo.bar.com\*
The following keys are going to be deleted:
Accepted Keys:
foo.bar.com
foo.bar.com*
```

This can be worked around by manually deleting the keys from the salt-master, but special characters in minion-ids should probably either be illegal, or escapable within salt-key.

**Comment by jfindlay** [comment] 2016-01-07 17:33
@zmalone, thanks for the report.

**Comment by basepi** [comment] 2016-01-08 00:13
I would call this expected behavior. My guess is that fnmatch (which we use for glob matches) doesn't support escaping asterisks via backslashes. Maybe there's an option we could add, or maybe it's an issue in our parsing. But I'm going to just say "we don't support asterisks in minion IDs". Because that seems like an exercise in frustration, and I can't see a good reason that you need that particular character.

If you want to delete a minion ID which you created with asterisks by mistake, just remove the key from /etc/salt/pki/master/minions/

I'm happy to discuss it more, but that's where I'm landing on this issue right now.

**Comment by pzipoy** [comment] 2016-02-23 17:03
Is there clear documentation to specify which characters are acceptable and not acceptable to use in a minion ID?

From what I understand, wildcard characters such as <question-mark>, <asterisk>, and <square brackets> should generally be avoided as they have special use cases for unix fnmatch (https://docs.python.org/2/library/fnmatch.html). Would you agree?

**Comment by basepi** [comment] 2016-02-24 20:03
Agreed. In my opinion minion IDs should be limited to alphanumerics, plus dash, underscore, and dot.

I'm going to close this issue based on my comment above.

**Closed by basepi** 2016-02-24 20:03 UTC
Labels: Expected Behavior, Won't Fix For Now
