### ISSUE TITLE
Salt job hangs/runs forever when printing large number of lines to stdout 

### ISSUE THREAD

**Issue by ajaydwarkani** [saltstack/salt#58014] opened 2020-07-23 13:52 UTC
### Description of Issue
Salt job runs forever when executing shell or python script on Windows Minion, but the same script runs just fine on Ubuntu/Mac minion and has complete under few seconds. After checking the job status after 12 hours, it was still running.

If I run the script directly on the Windows VM, it runs fine.

### Setup
**Python script: "CreateP4Tickets.py"**
```python
#!/bin/python3

import shlex
import subprocess
import os
import sys
import argparse
import re
import time

def login2P4(name, p4Port, p4User, p4Passwd):
    print(f"\nINFO: ----- Creating P4 ticket for {name} -----")

    cmd = f'p4 -p {p4Port} trust -y -f'
    p0 = subprocess.Popen(shlex.split(cmd), encoding='utf-8', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if p0.returncode:
        for line in p0.stderr.split('\n'):
            if line != '':
                print(f"ERROR: {line}")
        return
    p0.stdout.close()

    # Read the password for input for next command.
    cmd = f'echo {p4Passwd}'
    p1 = subprocess.Popen(shlex.split(cmd), encoding='utf-8', stdout=subprocess.PIPE)

    cmd = f'p4 -u walf -p {p4Port} login'
    p2 = subprocess.Popen(shlex.split(cmd), encoding='utf-8', stdin=p1.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    p1.stdout.close()
    output, err = p2.communicate()
    if p2.returncode:
        for line in err.split('\n'):
            if line != '':
                print(f"ERROR: {line}")
        sys.exit(1)
        print('INFO: P4 Ticket successfully created.')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--p4User', default=os.getenv('P4USER'),
                         help='Perforce Username. Default is environment variable "P4USER"')
    parser.add_argument('--p4Passwd', default=os.getenv('P4PASSWD'),
                         help='Perforce Password. Default is environment variable "P4PASSWD"')
    parser.add_argument('--p4ServerList',
                         help='File with P4 server names and ports separated by "~". One P4 server per line. Default file is "P4ServerList.txt"')

    args = parser.parse_args()
    if args.p4Passwd is None or args.p4Passwd == "Dummy":
        sys.exit('ERROR: Please provide a valid password or make sure environment variable "P4PASSWD" is set correctly')

    if args.p4ServerList is None:
        args.p4ServerList = os.path.join(os.path.dirname(os.path.realpath(__file__)), "P4ServerList.txt")

    if not os.path.exists(args.p4ServerList):
        sys.exit(f'ERROR: File "{args.p4ServerList}" doesn\'t exist')

    with open(args.p4ServerList, encoding='utf-8') as f:
        # login2P4('calf', 'ssl:basil:20460', args.p4User, args.p4Passwd)
        for line in f:
            if re.match(r"\s*(#|$)", line):
                continue
            line = line.strip()
            name, p4Port = line.split('~')
            login2P4(name, p4Port, args.p4User, args.p4Passwd)

if __name__ == "__main__":
    start = time.perf_counter()
    print('\nRunning...{}'.format(os.path.basename(sys.argv[0])))

    main()

    end = time.perf_counter()
    minutes, seconds = divmod(end - start, 60)
    if minutes > 0:
        print('\nTime elapsed = {} min {} secs'.format(minutes, seconds))
    else:
        print('\nTotal time elapsed - {0:.2f} secs'.format(seconds))
    print('Done.')
```

**State File: "test-create-p4ticket.sls"**
```salt
{% if grains['os'] == "Windows" %}
{% set tempFolder = "c:/tmp" %}
Create Temp Directory:
  file.directory:
    - name: {{ tempFolder }}
{% else %}
{% set tempFolder = '/tmp' %}
{% endif %}
{% set p4TicketScript = 'CreateP4Tickets.py' %}
{% set p4ServerList = 'P4ServerList.txt' %}

Copy script:
  file.managed:
    - name: {{ tempFolder }}/{{ p4TicketScript }}
    - source: "salt://{{ p4TicketScript }}"
    - skip_verify: True
    - require:
      - file: Copy serverlist

Copy serverlist:
  file.managed:
    - name: {{ tempFolder }}/{{ p4ServerList }}
    - source: "salt://{{ p4ServerList }}"
    - skip_verify: True

Create P4 Ticket:
  cmd.run:
    - name: python3 {{ p4TicketScript }} --p4User {{ pillar['l10nuser'] }} --p4Passwd {{ pillar['P4PASSWD'] }}
    - cwd: {{ tempFolder }}
    - runas: {{ pillar['l10nuser'] }}
    - require:
      - file: Copy script
```

### Steps to Reproduce Issue
Here is direct command
`salt -G 'os:windows' cmd.run 'python3 CreatePerforceTickets.py --p4User user --p4Passwd password' runas=localuser cwd="C:\\tmp"`

The job runs forever. 

I debugged the command using the below command
`salt-call -l debug state.apply test-create-p4ticket`
Here is the error I get
`Unable to OpenProcess pid=4 name=System`

```bash
salt -G 'os:windows' cmd.run 'cmd.exe /c python3 CreatePerforceTickets.py --p4User user --p4Passwd password' runas=localuser cwd="C:\\tmp" -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/file_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/file_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: myhostname
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/file_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/file_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: myhostname
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None)
[DEBUG   ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None)
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'myhostname_master', 'tcp://xxx.xxx.xxx.xxx:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xxx.xxx.xxx:4506
[DEBUG   ] Trying to connect to: tcp://xxx.xxx.xxx.xxx:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/f1/a0c99915c21419729d48151385b97705c9be807ef3f234faaeef8d32b8e9ac/.minions.p
[DEBUG   ] get_iter_returns for jid 20200715210816677523 sent to {'minion-1'} will timeout at 14:11:36.692135
[DEBUG   ] Checking whether jid 20200715210816677523 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'myhostname_master', 'tcp://xxx.xxx.xxx.xxx:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xxx.xxx.xxx:4506
[DEBUG   ] Trying to connect to: tcp://xxx.xxx.xxx.xxx:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] retcode missing from client return
[DEBUG   ] Checking whether jid 20200715210816677523 is still running
```

#### Salt Master
```
$ salt --versions-report
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pygit2: 0.26.2
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-101-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver
```

#### Salt-minion 
```
$ salt-minion --versions-report
    Salt Version:
               Salt: 3001

    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.10
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.9.7
             pygit2: Not Installed
             Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 5.1.2
              PyZMQ: 18.0.1
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1

    System Versions:
               dist: msys_nt-10.0-19041 3.0.7
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.19041 SP0
```

**Salt master OS:** Ubuntu 18.04
**Salt-minion version:** 3001
**Salt-minion OS:** Windows 10 version 2004

**Comment by ajaydwarkani** [comment] 2020-09-11 06:47
@krionbsd , @sagetherage any update on this?

**Comment by sagetherage** [comment] 2020-09-14 15:52
@ajaydwarkani this has gone through the issue triage process and is currently a `Medium` severity level. Given the current backlog of issues this is to be reviewed for a fix in the (code name) Aluminium Release cycle which is targeted for release in early 2021.

**Comment by ajaydwarkani** [comment] 2020-09-16 01:05
Thanks for the update.

**Comment by doesitblend** [comment] 2020-10-27 16:07
ZD-5912

**Comment by ajaydwarkani** [comment] 2021-01-04 19:16
@sagetherage , is it possible to fix this in an earlier release instead of Silicon?

**Comment by sagetherage** [comment] 2021-01-12 20:33
I have assigned it to the Windows team and will need to get with them this week to determine the release. I will follow up within the next 7 business days.

**Comment by ajaydwarkani** [comment] 2021-01-12 20:48
Thanks.

**Comment by xeacott** [comment] 2021-01-14 20:26
Checked this out a little today... and reduced the python file by a bit. Here's my working copy and below is the command I used to run it:
`salt-call --local cmd.run "python C:\dev\testdir\createp4tickets.py " -l debug`

Is there a piece to this example @ajaydwarkani that I am missing? I can spawn a master and also try using the `runas` too to see if that is causing issues.

Also I am running 3002.2 let me try with 3001.

```
#!/bin/python3

import shlex
import subprocess
import os
import sys
import argparse
import re
import time

def spawn_process(user, pw):
    print('spawn process')

    cmd = f'echo {pw}'
    p0 = subprocess.Popen(shlex.split(cmd), encoding='utf-8', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if p0.returncode:
        for line in p0.stderr.split('\n'):
            if line != '':
                print(f"ERROR: {line}")
        return
    p0.stdout.close()

    # Read the password for input for next command.
    cmd = f'echo {pw}'
    p1 = subprocess.Popen(shlex.split(cmd), encoding='utf-8', stdout=subprocess.PIPE)

    p2 = subprocess.Popen(shlex.split(cmd), encoding='utf-8', stdin=p1.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    p1.stdout.close()
    output, err = p2.communicate()
    if p2.returncode:
        for line in err.split('\n'):
            if line != '':
                print(f"ERROR: {line}")
        sys.exit(1)
        print('INFO: P4 Ticket successfully created.')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--user')
    parser.add_argument('--password')

    args = parser.parse_args()
    spawn_process(args.user, args.password)

if __name__ == "__main__":
    main()

```

**Comment by xeacott** [comment] 2021-01-25 23:54
Following up here once again just to make sure... (also read a little bit more into the logs)

Setup: linux master - 3002.2 / windows minion - 3002.2
Cmd: `salt -G 'os:windows' cmd.run "python C:\dev\testdir\createp4tickets.py " runas='customuser' -l debug`

Up and running smoothly on my end... I am wondering if you're able to send other commands to the minion and have them return? Or Could you try the broken down version of that file I posted above and see if the behavior is any different?

**Comment by ajaydwarkani** [comment] 2021-01-26 00:52
Apologize for the delay, I will take a look in next couple of days and get
back to you.

**Comment by twangboy** [comment] 2021-02-24 00:41
@ajaydwarkani Ping

**Comment by ajaydwarkani** [comment] 2021-02-24 20:08
Apologize for the delay Shane.

I will make this priority and update you by end of this week.

Regards,
Ajay

**Comment by ajaydwarkani** [comment] 2021-03-10 12:22
@twangboy / @xeacott , after testing your suggestion(s) and on further more testing, it seems like the problem is not with Python script. I have tested the same with a shell script and the problem seems to be with cmd.run or cmd.script where even after the script is successful, the saltstack job doesn't receive terminate signal and will keep it running. This is only happening on Windows minion.

I am using the latest version of Salt server and minion version 3002.2

**Comment by sagetherage** [comment] 2021-03-11 00:10
updating this milestone and release label since it will likely not get into Aluminium since the RC1 tag and packages are already live for Aluminium. I will come back to this for the next release cycle Silicon in planning in the next few weeks.

**Comment by ajaydwarkani** [comment] 2021-03-11 00:16
Ok, thanks for the update. Were you able to reproduce it on your end?

As there is a workaround by logging the messages to a file instead of
stdout, it should be fine to push it to next week.

**Comment by xeacott** [comment] 2021-03-15 21:42
I'll have to get with @twangboy on this as I've been unable to reproduce that specific behavior when the minion just doesn't respond anymore. But that makes sense as to what the actual issue. I'll update the ticket accordingly.

**Comment by MKLeb** [comment] 2023-05-23 18:45
@ajaydwarkani Would you be willing to test this on 3006.1?

**Comment by twangboy** [comment] 2023-06-20 22:59
I just tried again to reproduce this. I created the following script in `C:\Temp\spawn.py` which will create 2500 messages:

```
def spawn_process(n):
    for i in range(1, 11):
        print(f"spawn process {(n*10) + i}")

def main():
    for n in range(250):
        spawn_process(n)

if __name__ == "__main__":
    main()
```

Working off the head of master, I ran locally with `salt-call` without issue:

```
PS> salt-call --local cmd.run "python C:\temp\spawn.py"
    spawn process 1
    spawn process 2
    spawn process 3
    ...
    spawn process 2495
    spawn process 2496
    spawn process 2497
    spawn process 2498
    spawn process 2499
    spawn process 2500
```

Then I spun up a master on a Windows VM and connected the minion. I ran the salt command:
```
PS>salt dev10 cmd.run "python C:\temp\spawn.py" 
    spawn process 1
    spawn process 2
    spawn process 3
    ...
    spawn process 2495
    spawn process 2496
    spawn process 2497
    spawn process 2498
    spawn process 2499
    spawn process 2500
```
I killed the minion and installed a 3004.2 minion... Failed to reproduce.
I killed that minion and installed a 3002.9 minion... failed to reproduce.

**Comment by twangboy** [comment] 2023-08-22 15:00
Closing this as we have failed to reproduce the issue in more recent versions of Salt. Please open a new issue if the problem persists.

**Closed by twangboy** 2023-08-22 15:00 UTC
Labels: Bug, severity-medium, Windows, ZD
