### ISSUE TITLE
Master's DNS resolving to a new IP, minions not reconnecting automatically

### ISSUE THREAD

**Issue by michaelforge** [saltstack/salt#27846] opened 2015-10-10 12:20 UTC
Transferred salt-master to another IP and changed it's DNS.
All salt-minions using master's DNS.

After migration, minions are not reconnecting to new master's IP. They are not available through salt '*' commands.

1. Does already running minions automatically acknowledge that master's DNS resolving to a new IP? How much time it could take?
2. The only way to make all minions to reconnect to a new master is do `service salt-minion restart` on each minion?

We didn't had salt-ssh roster, so looks like we need to build one from the scratch to let minions know that their master's IP has changed.

salt-master & minion: 2015.5.3

**Comment by JDiPierro** [comment] 2015-10-10 13:10
Hi Michael,

The amount of time it might take for the minions to resolve the new IP address depends on the TTL (Time To Live) setting on your DNS entry. After the configured TTL time has passed the minions should be resolving the DNS entry to the new IP address and should successfully connect. If your minions are running linux you could check the IP they're resolving by SSHing into one of them and running `nslookup {{ master_url }}`.

I'm actually not certain of the answer to your 2. question. If your minion config file has the master's URL I think it's possible that they might reconnect automatically once the new IP starts resolving, but I'm not positive of that.

As for the salt-ssh roster: I don't think that's necessary for your case, but I'm not certain of this either, as I haven't used salt-ssh. My understanding is that it's for executing salt on machines that aren't running salt-minion. It makes sense though that you could set it up as a backup in case minions lose connectivity to the master.

If your minions don't reconnect after the new IP is resolving and you don't want to build a salt-ssh roster one of my coworkers came up with a one-liner that you can run on the master to restart all minions:

    for HOST in `sudo ls /etc/salt/pki/master/minions`; do echo $HOST; ssh -oStrictHostKeyChecking=no $HOST "sudo restart salt-minion"; done

Hope this helps!

**Comment by michaelforge** [comment] 2015-10-10 14:34
@JDiPierro Thanks for reply!

DNS TTL: 300 sec. New IP already resolving on minions by manual ping, but already running salt-minion are **not reconnecting** to changed IP, even after 2 hours. 
The only way I found to make them do it is manually run `service salt-minion restart` on each minion, but that is not always a possible practice, so I wonder if salt-minions are trying to reconnect to changed DNS reply at all.

I tried what you suggested about doing nslookup.
nslookup returns a new IP on minion server, but it's not reconnecting to it.

**minion:**
```
root@www-db01:~# nslookup saltmaster
# returns new IP, everything is fine
```
**master:**
```
root@saltmaster:~# salt 'www-db01' test.ping
www-db01:
    Minion did not return. [Not connected]
```

About one-liner, it looks beautiful and handy. If minions wouldn't return back, I'm going to try that one. =)
Thanks to you and your coworkers for your time!

**Comment by ogabrielsantos** [comment] 2015-10-11 06:07
Same issue here. When master changes IP, minions can ping the new IP but does not respond to master anymore. I need to manually restart..

Currently I've setupped a cron to restart minion every 4 hours but is a ugly workaround.

**Comment by jfindlay** [comment] 2015-10-13 18:26
Thank you everyone for reporting.  This issue is a duplicate of #10032.

**Closed by jfindlay** 2015-10-13 18:26 UTC
Labels: Duplicate
