### ISSUE TITLE
salt-run pillar.show_pillar fails if no grain data is present

### ISSUE THREAD

**Issue by JustKiddingCode** [saltstack/salt#41003] opened 2017-05-02 13:26 UTC
### Description of Issue/Question

```
Exception occurred in runner pillar.show_pillar: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/pillar.py", line 78, in show_pillar
    id_, grains, _ = salt.utils.minions.get_minion_data(minion, __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 85, in get_minion_data
    grains = data['grains']
KeyError: 'grains'
```

### Steps to Reproduce Issue

Add a new host to your pillar data but don't add it to salt.
Useful for example for virtual machines.

### Fix

Change
```
        if data is not None:
            grains = data['grains']
            pillar = data['pillar']

```
To
```
        if data is not None:
            if grains in data:
                grains = data['grains']
            if pillar in data:
                pillar = data['pillar']


```
### Versions Report

Salt Version:
           Salt: 2016.11.4

**Comment by Ch3LL** [comment] 2017-05-02 15:28
@JustKiddingCode did you want to submit a PR? Seems you understand what the fix is.

**Comment by Ch3LL** [comment] 2017-05-02 16:02
This is actually a duplicate of https://github.com/saltstack/salt/issues/40784 I will close this issue and we can track it there.

**Closed by Ch3LL** 2017-05-02 16:02 UTC
Labels: Bug, Core, High Severity, P4, Runners
