### ISSUE TITLE
why does mine_interval not work in pillar file？ And how to set mine_interval value by seconds? 

### ISSUE THREAD

**Issue by xiaoyukakagithub** [saltstack/salt#39240] opened 2017-02-08 07:18 UTC
### Description of Issue/Question
I tried to use mine followed the guild https://docs.saltstack.com/en/latest/topics/mine/index.html. 
I found that mine_interval can only be configured in minion config. It don't work in pillar file. 
Is there any way to use it in pillar file.
Another question is that how to set mine_interval value by seconds?  I cannot find the answer on website.
 
root@saltstack:/srv/pillar# salt --versions-report
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: 0.24.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-46-generic
         system: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment] 2017-02-08 16:32
@xiaoyukakagithub this has already been requested in this feature request: https://github.com/saltstack/salt/issues/18098

To answer your questions it looks like in the code its coded to minutes not seconds. So 1 minute is the least amount of time you can set. Will close this as its a duplicate of #18098 adn you can trakc this fetaure request there. thanks

**Closed by Ch3LL** 2017-02-08 16:32 UTC

**Comment by boltronics** [comment] 2017-08-24 04:42
@Ch3LL According to the [mine_interval](https://docs.saltstack.com/en/latest/ref/configuration/minion.html#mine-interval) docs, it's supposed to be managed by seconds, not minutes.

Since this question was related to setting the mine by seconds which seems like it's broken or documented incorrectly (and not specifically about setting different intervals for different items in the mine), perhaps this can be re-opened?
