### ISSUE TITLE
duplicate returns from one minion

### ISSUE THREAD

**Issue by tbaschak** [saltstack/salt#36162] opened 2016-09-08 17:34 UTC
### Setup

I've got a salt master with ~30 or so minions. One of the minions always returns twice whenever it is targeted. I've tried removing it and re-adding it, and it is still returning twice.

Where I originally noticed the problem was doing apt operations, doing a pkg.list_upgrades would return a locking error. I realized this error was because this one minion was included twice in the list of minions somehow.

### Steps to Reproduce Issue

`salt \* test.ping`

### Versions Report

master:
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```

minion in question:
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
 ```

**Comment by aty010** [comment] 2016-09-09 07:52
Hi @tbaschak 
I countered this issue before.  In my case  returning test.ping twice meaning there were two instances of minions  running on same box. ssh login minion to restart the minion process should resolve the issue.

**Comment by tjyang** [comment] 2016-09-09 07:57
Hi @tbaschak,
I like to share my own experience with your,  my workaround fix was to ssh login minion to restart the minion process should resolve this issue. The issue was due to two instances of salt-minions running on same box.

**Comment by Ch3LL** [comment] 2016-09-09 15:57
@tbaschak does @tjyang 's suggestion work for you?

**Comment by tbaschak** [comment] 2016-09-09 16:37
Yes @tjyang 's suggestion does work for me. I'm a little embarrassed this was this simple. I find it a little unexpected that a client is able to connect multiple times like this, but I can see the use case for where it would be useful. This can be closed unless the behaviour of allowing multiple connections from a minion/key is unintended.

**Comment by tjyang** [comment] 2016-09-09 16:49
@tbaschak, this actually can be classified as bug IMHO. Because the init/startup script is not doing a good job detecting existing minion process. Either bailout or send out warning, running 2nd minion process is the worst action.

**Comment by tbaschak** [comment] 2016-09-09 16:53
@tjyang during the troubleshooting I did before reporting this issue in the first place, I did use the init script to restart the minion multiple times, and apparently the multiple processes persisted across that. I didn't reboot however.

**Comment by tjyang** [comment] 2016-09-09 16:57
Lets hear @Ch3LL's opinion. Hope she can reproduce this issue.

**Comment by Ch3LL** [comment] 2016-09-09 19:45
Would you guys agree the issue at hand would be considered a duplicate of #29307 ?

**Comment by tjyang** [comment] 2016-09-09 19:48
@Ch3LL, I agree this is a duplicate of #29307.

**Comment by tbaschak** [comment] 2016-09-09 19:50
Yes, I agree as well. Now that I've determined that it was a 2nd instance running its definitely a dupe of #29307

**Comment by Ch3LL** [comment] 2016-09-14 23:19
awsome. Ill close this one and we can monitor this issue there.

**Closed by Ch3LL** 2016-09-14 23:19 UTC
Labels: Pending Discussion
