### ISSUE TITLE
salt-ssh publish.publish: Permission denied on thin_dir

### ISSUE THREAD

**Issue by stieizc** [saltstack/salt#28278] opened 2015-10-24 02:52 UTC
I'm having problem with ```salt-ssh``` using ```publish.publish```, basically when I run:
```bash
salt-ssh -i 'compute-*' publish.publish 'compute-*' grains.get fqdn_ip4
```
I got:
```bash
compute-1:
    An Exception occurred while executing publish.publish: [Errno 13] Permission denied: '/var/lib/salt-ssh-agent'
compute-2:
    An Exception occurred while executing publish.publish: [Errno 13] Permission denied: '/var/lib/salt-ssh-agent
```
The directory above was the ```thin_dir``` that I set on my ```roster``` file:
```yaml
compute-1:
  host: what.ever
  user: charlie
  sudo: True
  thin_dir: /var/lib/salt-ssh-agent

compute-2:
  host: what.ever
  user: charlie
  sudo: True
  thin_dir: /var/lib/salt-ssh-agent
```
I got ```requiretty``` turned off. And here's my ```master``` file that allows ```grains.get``` on every minion:
```yaml
---
root_dir: .
file_roots:
  base:
    - srv/salt
pillar_roots:
  base:
    - srv/pillar
peer:
  .*:
    - grains.get
```
I use a ```Saltfile``` pointing the config directory to my current directory.

Am I doing it wrong? Does ```salt-ssh``` support the ```publish``` module?

**Comment by jfindlay** [comment] 2015-10-29 20:22
@stieizc, thanks for the report.  What is the output of `salt-ssh --versions-report`?

**Comment by stieizc** [comment] 2015-10-30 01:23
Sorry, forgot to mention that:
```
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.10+ (default, Oct 10 2015, 09:11:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.4
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 4.2.0-1-amd64
         system: debian stretch/sid 

```

**Comment by jfindlay** [comment] 2015-11-03 22:07
Thanks, @stieizc.  This looks like a bug to me.

**Comment by cachedout** [comment] 2015-11-05 23:15
I don't see how salt-ssh would work with `publish.publish`. I believe this is unsupported behavior. @basepi can confirm.

**Comment by stieizc** [comment] 2015-11-07 05:18
Well that's sad. I'm trying to ```publish``` the ip of a node to the other nodes so that they could set up their ```hosts``` file. Currently I don't know of other solutions.

**Comment by basepi** [comment] 2015-11-10 18:25
Technically publish.publish should work. But it's not very applicable to salt-ssh, since what actually happens is the master just runs the published command as a normal salt-ssh command.

The only reason we wrote the wrapper function was to support publish calls from within jinja templates that were ported over from normal salt.

Anyway, this looks like it's probably a bug with the thin_dir. At least, that's assuming that your users in question can access that directory on the minion. Have you double checked that `charlie` has access to that directory on the targets?

**Comment by stieizc** [comment] 2015-11-28 02:15
Sorry for the really long delay. I do not have access to the three machines any more (they are virtual machines and I've reinstalled the hypervisor), so I could not verify. But I'm quiet sure that `charlie` do not have access to that directory.

**Comment by basepi** [comment] 2015-12-01 00:03
In that case I think this is expected behavior. The user used for salt-ssh must have access to the thin_dir, or it can't copy the thin over and execute salt-ssh. Based on this, I'm going to close this issue. Please comment if you disagree.

**Closed** 2015-12-01 00:03 UTC
Labels: Bug, Core, Expected Behavior, High Severity, P3, Salt-SSH

**Comment by stieizc** [comment] 2015-12-01 02:12
Well, I will verify when I have the time, as salt really looks promising.
