### ISSUE TITLE
Orchestration gives exception when a target does not exist

### ISSUE THREAD

**Issue by beelit94** [saltstack/salt#33467] opened 2016-05-24 09:36 UTC
### Description of Issue/Question
It's a regression bug for 2015.8.10 since I'm not seeing this in 2015.8.8
I think it might duplicate from 32479, but it was only fixed in 2016

### Steps to Reproduce Issue
Create some orchestration file test.sls
```
indexer_setup:
  salt.state:
    - tgt: 'G@role:matchnothing'
    - tgt_type: compound
    - sls: somestate.somestates
```
and run it
```
salt-run state.orch orchestration.test
```

and seeing the error
```
No minions matched the target. No command was sent, no jid was assigned.
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 221, in state
    cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 911, in cmd
    client, tgt, fun, arg, timeout, expr_form, ret, kwarg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 879, in _exec
    tgt, fun, arg, timeout, expr_form, ret, kwarg, **kwargs):
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 663, in cmd_iter
    self._clean_up_subscriptions(pub_data['jid'])
KeyError: 'jid'
```

### Versions Report
```
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Ubuntu 14.04 trusty
```

**Comment by ssgward** [comment] 2016-05-24 15:01
Duplicate of #32479. We'll close this issue and track from #32479.

**Closed by ssgward** 2016-05-24 15:01 UTC
