### ISSUE TITLE
salt-cloud: 'Salt installed' success shown but not installed without bootstrap update

### ISSUE THREAD

**Issue by blbradley** [saltstack/salt#30336] opened 2016-01-13 20:46 UTC
Hello!

I was running `salt-cloud` without first running `salt-cloud -u`. So, no bootstrap script existed. Cloud machines were started fine, and I was getting `[INFO    ] Salt installed on my-test-instance`. But salt was not installed on instances. Everything works fine after running `salt-cloud -u`. So, this is clearly a bug.

I tested this on `v2015.8.3` and develop.

**Comment by jfindlay** [comment] 2016-01-14 17:29
@blbradley, thanks for the report.  Salt ships with a stable version of bootstrap and `salt-cloud -u` updates it to the latest develop version, so something is not working in the current stable version, but it is fixed in the development version.

**Comment by rallytime** [comment] 2016-01-14 17:34
This is a duplicate of #26699. I'm going to close this in favor of the older issue. I was thinking about that bug the other day and wondering if it was still happening on newer versions (we started seeing this in 2015.8.0), which appears to be the case. Thank you for letting us know.

**Closed by rallytime** 2016-01-14 17:34 UTC
Labels: Bug, Duplicate, High Severity, P3, RIoT

**Comment by blbradley** [comment] 2016-01-14 17:40
@rallytime Definitely a duplicate. Thanks!

**Comment by rallytime** [comment] 2016-01-14 17:52
Sure thing! Thanks for confirming the bug!
