### ISSUE TITLE
salt-cloud (CLI) & (maybe) cloud runner  should query pillar for cloud.conf/providers/profiles/etc 

### ISSUE THREAD

**Issue by gladiatr72** [saltstack/salt#21071] opened 2015-02-26 15:55 UTC
I'm leveraging salt-cloud's pillar configuration bits to enable automated deployment of cloud controllers into the provider's cloud (cloudctrl for ec2 will live somewhere in ec2-land, etc)  Part of this includes an external pillar that will only provide provider/profile data relevant to the targeted provider.  Why put rackspace creds on a system that will only deal with ec2 minions, right? :)

Okay, so that all works well; however, the salt-cloud CLI and the cloud runner have no knowledge of this pillar data.  While it might be problematic to integrate this with a runner (I have yet to dive into runners), the salt-cloud CLI should definitely include this piece.  While my goal is for the client to not interact with the controller from the command-line, it just makes sense that it should work.

**Comment by rallytime** [comment] 2015-02-26 16:12
@gladiatr72 Thanks for this report! This is a great idea, which has actually already been discussed as a new feature in #16850. Since this is a duplicate of that issue, I'm going to close this one in favor of the previously opened one where much discussion of this idea has taken place.

Thanks again!

**Closed by rallytime** 2015-02-26 16:12 UTC
Labels: Duplicate, Feature, Salt-Cloud

**Comment by DanyC97** [comment] 2016-01-08 14:32
@gladiatr72 if you don't mind can you pls share/ explain how salt-cloud can leverage salt master pillar data or ext_pillar (which i believe has been defined in salt master running on same node with salt-cloud)?

Much thanks.

@rallytime sorry for reviving a closed issue but on the other one you reference i got a bit confused.
