### ISSUE TITLE
ext_pillar does not honor gitfs_provider option

### ISSUE THREAD

**Issue by drawsmcgraw** [saltstack/salt#22702] opened 2015-04-15 11:47 UTC
I use the GitFS backend for my state tree and have set `gitfs_provider: pygit2` in my master config.

When I follow the [Git as External Pillar](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#using-git-as-an-external-pillar-source) doc and have a minion attempt a `pillar.get`, the following appears in the master log:

```
[ERROR   ] Git-based ext_pillar is enabled in configuration but could not be loaded, is GitPython installed?
[CRITICAL] Specified ext_pillar interface git is unavailable
```

Installing `GitPython` and restarting the master resolves the issue and the minion is able to successfully pull values out of Pillar.

I have no issues running both `GitPython` and `pygit2` in my environment so it's not a show-stopper for me. I'm filing this issue because I hadn't seen it mentioned before.

Unless this is already solved and I'm just missing another option to pass to `ext_pillar`?

**Comment by rallytime** [comment] 2015-04-15 22:13
Hrm. I haven't used gitfs in conjunction with pillar.get, so I am not sure. Is there anything specified in the master config saying that you should use GitPillar over pygit2 (either for gitfs or for some ext_pillar configuration)? I wondering if maybe it's hitting a default check of GitPython. (I vaguely remember a setting like this in master config file, but I can't remember what the default is.)

**Comment by drawsmcgraw** [comment] 2015-04-16 13:59
It looks like it's hitting a default check of GitPython. I had just gone with `pygit2` because it seems to be the preferred package (going by [this doc](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html)). Of course, that could be an incorrect assumption.

[Looking at the code](https://github.com/saltstack/salt/blob/develop/salt/pillar/git_pillar.py#L87-L114), it looks like it checks specifically for GitPython. 

It's not a big deal for me (I have no problems installing both packages for my systems), it's just not the behavior I expected.

**Comment by rallytime** [comment] 2015-04-16 15:07
@drawsmcgraw Thanks for checking that. I think your assumption makes sense, but we just haven't adapted git_pillar to work with pygit2 like we did with gitfs. Let's make that a feature request. :)

**Comment by drawsmcgraw** [comment] 2015-04-16 16:14
@rallytime Sounds good. Thanks!

**Comment by JaseFace** [comment] 2015-04-21 19:29
Just ran into this myself trying to chase down a bug in the library used for access git via ext_pillar.. Thinking we should update the docs with a note until pygit2 is implemented for git_pillar.

**Comment by JaseFace** [comment] 2015-04-21 19:46
I'm not sure which branch is proper when pushing docs.. but here is a small addition:

https://github.com/saltstack/salt/pull/22910

**Comment by rallytime** [comment] 2015-04-22 00:48
@JaseFace Thanks for this addition to the docs! You submitted the fix to the correct branch. We'll get that change merged forward to the other branches as well.

**Comment by cubranic** [comment] 2015-05-12 19:23
Is this now a duplicate of #20100?

**Comment by drawsmcgraw** [comment] 2015-05-12 19:28
@cubranic I'm going to go with 'yes' since the common denominator with both issues is "ext_pillar doesn't support pygit2".

**Comment by rallytime** [comment] 2015-05-12 20:20
@drawsmcgraw Should we close this one in favor of #20100 then?

**Comment by drawsmcgraw** [comment] 2015-05-12 20:25
I'm okay with that, yeah. Anything to help reduce the noise for y'all :)

**Comment by rallytime** [comment] 2015-05-13 14:45
Thanks!

**Closed by rallytime** 2015-05-13 14:45 UTC
Labels: Duplicate, Feature, Platform Mgmt
