### ISSUE TITLE
unexpected osrelease grain...

### ISSUE THREAD

**Issue by unassassinable** [saltstack/salt#27528] opened 2015-09-29 23:10 UTC
Minion is Centos 7.1.1503.

I see in /var/log/messages:
```
Sep 29 19:07:45 localhost salt-minion: [WARNING ] Unexpected osrelease grain '7.1.1503', please report this
```

**Comment by jfindlay** [comment] 2015-09-30 16:02
@unassassinable, thanks for the report.  This is a duplicate of #27065.

**Closed by jfindlay** 2015-09-30 16:02 UTC
Labels: Duplicate
