### ISSUE TITLE
Warning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#56051] opened 2020-02-03 14:19 UTC
### Description of Issue

salt-minion 2019.2.3 produces deprecation warning in Debian 10 (buster) when it starts up:
```
2020-02-03 16:06:52,370 [py.warnings      :110 ][WARNING ][29744] /usr/lib/python3/dist-packages/salt/transport/zeromq.py:42: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  import zmq.eventloop.ioloop
```
I don't see this message on Debian Stretch minions (same salt version).

### Setup

Nothig.

### Steps to Reproduce Issue

`systemctl restart salt-minion`

### Versions Report

```


Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.2 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.2 
 ```

**Comment by Talkless** [comment] 2020-02-03 14:23
BTW, Salt is installed from `http://repo.saltstack.com/py3/debian/10/amd64/2019.2` repo.

**Comment by dhiltonp** [comment] 2020-02-05 15:33
Thanks! This looks like it's a duplicate of #54759, take a look and feel free to chime in!

**Closed by dhiltonp** 2020-02-05 15:33 UTC

**Comment by Talkless** [comment] 2020-02-05 18:40
> Thanks! This looks like it's a duplicate of #54759, take a look and feel free to chime in!

Ouch, I've tried to search but obviously failed.
