### ISSUE TITLE
minon  hangs on Re-using SAuth 

### ISSUE THREAD

**Issue by szin2012** [saltstack/salt#38760] opened 2017-01-17 05:12 UTC
### Description of Issue/Question
minon  hangs on Re-using SAuth  if "/srv/salt" dir is large, when action any state.sls 
 
### Setup

du -sh the /srv/salt
```
[root1@ salt]# du -sh 
6.3G
         
[root1@ salt]#cat cmd.sls 
aaa:
  cmd.run:
    - name: 'uptime'
```

```
[root1@ salt]]# time salt 'vm6' state.sls cmd
vm6:
    ----------
    cmd_|-aaa_|-uptime_|-run:
        ----------
        __run_num__:
            0
        changes:
            ----------
            pid:
                13193
            retcode:
                0
            stderr:
            stdout:
                 12:58:52 up 22 days, 19:14,  2 users,  load average: 0.13, 0.09, 0.06
        comment:
            Command "uptime" run
        duration:
            19.826
        name:
            uptime
        result:
            True
        start_time:
            12:58:52.124893

real    0m19.065s
user    0m1.554s
sys     0m0.123s

2017-01-17 12:58:34,672 [salt.minion                              ][INFO    ][24889] User root1 Executing command state.sls with jid 20170117125834830966
2017-01-17 12:58:34,673 [salt.minion                              ][DEBUG   ][24889] Command details {'tgt_type': 'glob', 'jid': '20170117125834830966', 'tgt': 'vm6', 'ret': '', 'user': 'root1', 'arg': ['cmd'], 'fun': 'state.sls'}
2017-01-17 12:58:34,683 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:34,684 [salt.minion                              ][INFO    ][13176] Starting a new job with PID 13176
2017-01-17 12:58:34,694 [salt.utils.lazy                          ][DEBUG   ][13176] LazyLoaded state.sls
2017-01-17 12:58:34,702 [salt.utils.lazy                          ][DEBUG   ][13176] LazyLoaded saltutil.is_running
2017-01-17 12:58:34,703 [salt.utils.lazy                          ][DEBUG   ][13176] LazyLoaded grains.get
2017-01-17 12:58:34,704 [salt.crypt                               ][DEBUG   ][13176] Re-using SAuth for ('/etc/salt/pki/minion', 'vm6', 'tcp://192.168.10.75:4506')
2017-01-17 12:58:35,686 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:36,688 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:37,689 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:38,691 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:39,693 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:40,695 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:41,697 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:42,699 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:43,701 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:44,703 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:45,705 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:46,707 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:47,709 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:48,711 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:49,713 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:50,715 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:51,557 [salt.config                              ][DEBUG   ][13176] Reading configuration from /etc/salt/minion
2017-01-17 12:58:51,608 [salt.config                              ][DEBUG   ][13176] Including configuration from '/etc/salt/minion.d/_schedule.conf'
2017-01-17 12:58:51,608 [salt.config                              ][DEBUG   ][13176] Reading configuration from /etc/salt/minion.d/_schedule.conf
2017-01-17 12:58:51,716 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 12:58:52,021 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram0 does not report itself as an SSD
2017-01-17 12:58:52,021 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram1 does not report itself as an SSD
2017-01-17 12:58:52,021 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram2 does not report itself as an SSD
2017-01-17 12:58:52,022 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram3 does not report itself as an SSD
2017-01-17 12:58:52,022 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram4 does not report itself as an SSD
2017-01-17 12:58:52,022 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram5 does not report itself as an SSD
2017-01-17 12:58:52,022 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram6 does not report itself as an SSD
2017-01-17 12:58:52,022 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram7 does not report itself as an SSD
2017-01-17 12:58:52,023 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram8 does not report itself as an SSD
2017-01-17 12:58:52,023 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram9 does not report itself as an SSD
2017-01-17 12:58:52,023 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram10 does not report itself as an SSD
2017-01-17 12:58:52,023 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram11 does not report itself as an SSD
2017-01-17 12:58:52,023 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram12 does not report itself as an SSD
2017-01-17 12:58:52,024 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram13 does not report itself as an SSD
2017-01-17 12:58:52,024 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram14 does not report itself as an SSD
2017-01-17 12:58:52,024 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device ram15 does not report itself as an SSD
2017-01-17 12:58:52,024 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device loop0 does not report itself as an SSD
2017-01-17 12:58:52,024 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device loop1 does not report itself as an SSD
2017-01-17 12:58:52,025 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device loop2 does not report itself as an SSD
2017-01-17 12:58:52,025 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device loop3 does not report itself as an SSD
2017-01-17 12:58:52,025 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device loop4 does not report itself as an SSD
2017-01-17 12:58:52,025 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device loop5 does not report itself as an SSD
2017-01-17 12:58:52,025 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device loop6 does not report itself as an SSD
2017-01-17 12:58:52,026 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device loop7 does not report itself as an SSD
2017-01-17 12:58:52,026 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device sr0 does not report itself as an SSD
2017-01-17 12:58:52,026 [salt.loaded.int.grains.ssds              ][TRACE   ][13176] Device sda does not report itself as an SSD
2017-01-17 12:58:52,027 [salt.crypt                               ][DEBUG   ][13176] Re-using SAuth for ('/etc/salt/pki/minion', 'vm6', 'tcp://192.168.10.75:4506')
2017-01-17 12:58:52,084 [salt.crypt                               ][DEBUG   ][13176] Loaded minion key: /etc/salt/pki/minion/minion.pem
2017-01-17 12:58:52,093 [salt.state                               ][INFO    ][13176] Loading fresh modules for state activity
2017-01-17 12:58:52,107 [salt.utils.lazy                          ][DEBUG   ][13176] LazyLoaded jinja.render
2017-01-17 12:58:52,108 [salt.utils.lazy                          ][DEBUG   ][13176] LazyLoaded yaml.render
2017-01-17 12:58:52,111 [salt.fileclient                          ][DEBUG   ][13176] Fetching file from saltenv 'base', ** attempting ** 'salt://cmd.sls'
2017-01-17 12:58:52,116 [salt.fileclient                          ][INFO    ][13176] Fetching file from saltenv 'base', ** done ** 'cmd.sls'
2017-01-17 12:58:52,117 [salt.utils.jinja                         ][DEBUG   ][13176] Jinja search path: ['/var/cache/salt/minion/files/base']
2017-01-17 12:58:52,121 [salt.template                            ][DEBUG   ][13176] Rendered data from file: /var/cache/salt/minion/files/base/cmd.sls:
aaa:
  cmd.run:
    - name: 'uptime' 

2017-01-17 12:58:52,123 [salt.utils.lazy                          ][DEBUG   ][13176] LazyLoaded config.get
2017-01-17 12:58:52,124 [salt.loaded.int.render.yaml              ][DEBUG   ][13176] Results of YAML rendering: 
OrderedDict([('aaa', OrderedDict([('cmd.run', [OrderedDict([('name', 'uptime')])])]))])
2017-01-17 12:58:52,125 [salt.utils.lazy                          ][DEBUG   ][13176] LazyLoaded cmd.run
2017-01-17 12:58:52,125 [salt.state                               ][INFO    ][13176] Running state [uptime] at time 12:58:52.124893
2017-01-17 12:58:52,125 [salt.state                               ][INFO    ][13176] Executing state cmd.run for uptime
2017-01-17 12:58:52,126 [salt.loader                              ][TRACE   ][13176] Loaded cmdmod as virtual cmd
2017-01-17 12:58:52,127 [salt.utils.lazy                          ][DEBUG   ][13176] LazyLoaded cmd.run_all
2017-01-17 12:58:52,127 [salt.loaded.int.module.cmdmod            ][INFO    ][13176] Executing command 'uptime' in directory '/home/root1'
2017-01-17 12:58:52,144 [salt.loaded.int.module.cmdmod            ][DEBUG   ][13176] stdout:  12:58:52 up 22 days, 19:14,  2 users,  load average: 0.13, 0.09, 0.06
2017-01-17 12:58:52,145 [salt.state                               ][INFO    ][13176] {'pid': 13193, 'retcode': 0, 'stderr': '', 'stdout': ' 12:58:52 up 22 days, 19:14,  2 users,  load average: 0.13, 0.09, 0.06'}
2017-01-17 12:58:52,145 [salt.state                               ][INFO    ][13176] Completed state [uptime] at time 12:58:52.144719
2017-01-17 12:58:52,145 [salt.state                               ][DEBUG   ][13176] File /var/cache/salt/minion/accumulator/50282128 does not exist, no need to cleanup.
2017-01-17 12:58:52,146 [salt.minion                              ][DEBUG   ][13176] Minion return retry timer set to 5 seconds (randomized)
2017-01-17 12:58:52,146 [salt.minion                              ][INFO    ][13176] Returning information for job: 20170117125834830966
```

### Steps to Reproduce Issue

when I delete some files and dirs 

du -sh the /srv/salt
```
[root1@ salt]# du -sh 
1016M  

[root1@ salt]# time salt 'vm6' state.sls cmd
vm6:
    ----------
    cmd_|-aaa_|-uptime_|-run:
        ----------
        __run_num__:
            0
        changes:
            ----------
            pid:
                14173
            retcode:
                0
            stderr:
            stdout:
                 13:06:35 up 22 days, 19:21,  2 users,  load average: 0.00, 0.02, 0.05
        comment:
            Command "uptime" run
        duration:
            20.635
        name:
            uptime
        result:
            True
        start_time:
            13:06:35.670912

real    0m2.427s
user    0m1.386s
sys     0m0.113s

`2017-01-17 13:06:34,866 [salt.minion                              ][INFO    ][24889] User root1 Executing command state.sls with jid 20170117130635026571
2017-01-17 13:06:34,866 [salt.minion                              ][DEBUG   ][24889] Command details {'tgt_type': 'glob', 'jid': '20170117130635026571', 'tgt': 'vm6', 'ret': '', 'user': 'root1', 'arg': ['cmd'], 'fun': 'state.sls'}
2017-01-17 13:06:34,875 [salt.minion                              ][TRACE   ][24889] Check main poller timeout 1
2017-01-17 13:06:34,876 [salt.minion                              ][INFO    ][14156] Starting a new job with PID 14156
2017-01-17 13:06:34,886 [salt.utils.lazy                          ][DEBUG   ][14156] LazyLoaded state.sls
2017-01-17 13:06:34,895 [salt.utils.lazy                          ][DEBUG   ][14156] LazyLoaded saltutil.is_running
2017-01-17 13:06:34,896 [salt.utils.lazy                          ][DEBUG   ][14156] LazyLoaded grains.get
2017-01-17 13:06:34,897 [salt.crypt                               ][DEBUG   ][14156] Re-using SAuth for ('/etc/salt/pki/minion', 'vm6', 'tcp://192.168.10.75:4506')
2017-01-17 13:06:35,128 [salt.config                              ][DEBUG   ][14156] Reading configuration from /etc/salt/minion
2017-01-17 13:06:35,178 [salt.config                              ][DEBUG   ][14156] Including configuration from '/etc/salt/minion.d/_schedule.conf'
2017-01-17 13:06:35,178 [salt.config                              ][DEBUG   ][14156] Reading configuration from /etc/salt/minion.d/_schedule.conf
2017-01-17 13:06:35,571 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram0 does not report itself as an SSD
2017-01-17 13:06:35,572 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram1 does not report itself as an SSD
2017-01-17 13:06:35,572 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram2 does not report itself as an SSD
2017-01-17 13:06:35,572 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram3 does not report itself as an SSD
2017-01-17 13:06:35,572 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram4 does not report itself as an SSD
2017-01-17 13:06:35,573 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram5 does not report itself as an SSD
2017-01-17 13:06:35,573 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram6 does not report itself as an SSD
2017-01-17 13:06:35,573 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram7 does not report itself as an SSD
2017-01-17 13:06:35,573 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram8 does not report itself as an SSD
2017-01-17 13:06:35,573 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram9 does not report itself as an SSD
2017-01-17 13:06:35,574 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram10 does not report itself as an SSD
2017-01-17 13:06:35,574 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram11 does not report itself as an SSD
2017-01-17 13:06:35,574 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram12 does not report itself as an SSD
2017-01-17 13:06:35,574 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram13 does not report itself as an SSD
2017-01-17 13:06:35,574 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram14 does not report itself as an SSD
2017-01-17 13:06:35,575 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device ram15 does not report itself as an SSD
2017-01-17 13:06:35,575 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device loop0 does not report itself as an SSD
2017-01-17 13:06:35,575 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device loop1 does not report itself as an SSD
2017-01-17 13:06:35,575 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device loop2 does not report itself as an SSD
2017-01-17 13:06:35,575 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device loop3 does not report itself as an SSD
2017-01-17 13:06:35,576 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device loop4 does not report itself as an SSD
2017-01-17 13:06:35,576 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device loop5 does not report itself as an SSD
2017-01-17 13:06:35,576 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device loop6 does not report itself as an SSD
2017-01-17 13:06:35,576 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device loop7 does not report itself as an SSD
2017-01-17 13:06:35,576 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device sr0 does not report itself as an SSD
2017-01-17 13:06:35,576 [salt.loaded.int.grains.ssds              ][TRACE   ][14156] Device sda does not report itself as an SSD
2017-01-17 13:06:35,577 [salt.crypt                               ][DEBUG   ][14156] Re-using SAuth for ('/etc/salt/pki/minion', 'vm6', 'tcp://192.168.10.75:4506')
2017-01-17 13:06:35,631 [salt.crypt                               ][DEBUG   ][14156] Loaded minion key: /etc/salt/pki/minion/minion.pem
2017-01-17 13:06:35,642 [salt.state                               ][INFO    ][14156] Loading fresh modules for state activity
2017-01-17 13:06:35,656 [salt.utils.lazy                          ][DEBUG   ][14156] LazyLoaded jinja.render
2017-01-17 13:06:35,656 [salt.utils.lazy                          ][DEBUG   ][14156] LazyLoaded yaml.render
2017-01-17 13:06:35,659 [salt.fileclient                          ][DEBUG   ][14156] Fetching file from saltenv 'base', ** attempting ** 'salt://cmd.sls'
2017-01-17 13:06:35,663 [salt.fileclient                          ][INFO    ][14156] Fetching file from saltenv 'base', ** done ** 'cmd.sls'
2017-01-17 13:06:35,664 [salt.utils.jinja                         ][DEBUG   ][14156] Jinja search path: ['/var/cache/salt/minion/files/base']
2017-01-17 13:06:35,668 [salt.template                            ][DEBUG   ][14156] Rendered data from file: /var/cache/salt/minion/files/base/cmd.sls:
aaa:
  cmd.run:
    - name: 'uptime' 

2017-01-17 13:06:35,670 [salt.utils.lazy                          ][DEBUG   ][14156] LazyLoaded config.get
2017-01-17 13:06:35,670 [salt.loaded.int.render.yaml              ][DEBUG   ][14156] Results of YAML rendering: 
OrderedDict([('aaa', OrderedDict([('cmd.run', [OrderedDict([('name', 'uptime')])])]))])
2017-01-17 13:06:35,671 [salt.utils.lazy                          ][DEBUG   ][14156] LazyLoaded cmd.run
2017-01-17 13:06:35,671 [salt.state                               ][INFO    ][14156] Running state [uptime] at time 13:06:35.670912
2017-01-17 13:06:35,671 [salt.state                               ][INFO    ][14156] Executing state cmd.run for uptime
2017-01-17 13:06:35,672 [salt.loader                              ][TRACE   ][14156] Loaded cmdmod as virtual cmd
2017-01-17 13:06:35,673 [salt.utils.lazy                          ][DEBUG   ][14156] LazyLoaded cmd.run_all
2017-01-17 13:06:35,673 [salt.loaded.int.module.cmdmod            ][INFO    ][14156] Executing command 'uptime' in directory '/home/root1'
2017-01-17 13:06:35,690 [salt.loaded.int.module.cmdmod            ][DEBUG   ][14156] stdout:  13:06:35 up 22 days, 19:21,  2 users,  load average: 0.00, 0.02, 0.05
2017-01-17 13:06:35,691 [salt.state                               ][INFO    ][14156] {'pid': 14173, 'retcode': 0, 'stderr': '', 'stdout': ' 13:06:35 up 22 days, 19:21,  2 users,  load average: 0.00, 0.02, 0.05'}
2017-01-17 13:06:35,692 [salt.state                               ][INFO    ][14156] Completed state [uptime] at time 13:06:35.691547
2017-01-17 13:06:35,692 [salt.state                               ][DEBUG   ][14156] File /var/cache/salt/minion/accumulator/50282128 does not exist, no need to cleanup.
2017-01-17 13:06:35,693 [salt.minion                              ][DEBUG   ][14156] Minion return retry timer set to 7 seconds (randomized)
2017-01-17 13:06:35,694 [salt.minion                              ][INFO    ][14156] Returning information for job: 20170117130635026571
2017-01-17 13:06:35,694 [salt.crypt                               ][DEBUG   ][14156] Re-using SAuth for ('/etc/salt/pki/minion', 'vm6', 'tcp://192.168.10.75:4506')
```

### Versions Report
```
[root1@ salt]# salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by Ch3LL** [comment] 2017-01-18 21:38
@szin2012 can you describe further what you mean by the minion hangs? It seems the command results have returned on both state.sls commands. Maybe you can't run any further commands?

Also do you ahve a lot of big files in /srv/salt? I am not able to replicate this with a 6.1G /srv/salt but its only one big file in that directory. So trying to figure out how to replicate this so any other information would be great.

**Comment by szin2012** [comment] 2017-01-19 07:54
@Ch3LL thanks..

I mean when there are big file and folders on /srv/salt,its very slow to execute any state.sls,like cmd.sls, I find out that the minion log will get stuck after Re-using SAuth. It takes 20 seconds to return the result. However when there is very small file on the directory, every thing is fine , it only took few seconds . the big files and folders cannot be deleted from /srv/salt as I need to use them , any help ? 

ps... this issues like  https://groups.google.com/forum/#!msg/salt-users/1WEaKf_TVv8/L3UEcmukDwAJ
```
Found the solution to this problem if someone else has the same issue.
We had the one state with 700 MgB in /srv/salt. (some files to transfer to minions)

Once this state folder was moved outside of /srv/salt, the step "Re-using SAuth for..."
 is now half a second or less. And that is over 3G connection.
Left now is just to figure out how to still transfer those files with salt.

I hope it helps someone else.
Regards
```

**Comment by szin2012** [comment] 2017-01-29 09:24
this like #34428

**Comment by szin2012** [comment] 2017-01-29 09:29
if i use fileserver transfer file to minion, its very slow if large number of files in file_roots

**Comment by szin2012** [comment] 2017-01-29 09:48
#38901 Can solve this problem？

**Comment by stefano-pogliani** [comment] 2017-01-29 11:39
I have never tried a setup that has such a large state directory but I'm tempted to say to no, #38901 will not help in your case.

This is because the glob matching is resolved while loading the configuration and it is resolved to a full list of directories.
Based on the notes in this issue and in #34428 the problem seems to be in traversing such a large state directory.
Globbing patters do not change the number of files/folders visited by Salt.

Are the files in your state directory all states/templates/map.jinja files?
May I suggest moving static files (packages, non-template configs, ...) to a separate directory and using nginx (or similar) on the master to fetch the files?

**Comment by szin2012** [comment] 2017-01-29 12:12
@stefano-pogliani thank you for your reply,
actually, most of the files in my state are static files (packages, non-template configs, ...)
regarding your suggestion  ,it works well , but i want use filesever to sync files and directory ,any other ideas?

**Comment by stefano-pogliani** [comment] 2017-01-29 14:56
I suppose it depends on the exact needs of your use case.
Off the top of my head I can think of:

  1. Wait for/help make salt optimised to deal with large number of files.
  2. Use rsync (or similar) based solutions.
  3. Move files into git and usa a git server to sync them down.

These options are based on the idea of reducing the amount of files salt needs to handle to work around its current limit.
More experienced salt users may provide alternatives that do not require external systems.

**Comment by Ch3LL** [comment] 2017-02-09 17:47
@szin2012 I think you might be exaclty right that this is a duplicate of https://github.com/saltstack/salt/issues/34428 nice find on that one. 

Are you okay closing this and tracking the issue there?

**Closed** 2017-02-10 02:27 UTC
Labels: Cannot Reproduce, Info Needed
