### ISSUE TITLE
[BUG][REGRESSION] 3003.1 Salt-ssh does not work because of jinja import from included state

### ISSUE THREAD

**Issue by TeddyAndrieux** [saltstack/salt#60620] opened 2021-07-26 12:26 UTC
**Description**

When running a salt state with salt-ssh that include another salt state that then import a value from a "map.jinja" for example, the map.jinja is not part of the resulting thin file

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

```yaml
# grep -v "^#" /etc/salt/roster 
node1:
  host: 10.200.2.31
  user: root
  priv: /root/.ssh/id_rsa
```

```jinja
# cat /srv/salt/map.jinja 
{%- set abc = "def" %}
```

```yaml
# cat /srv/salt/test/init.sls 
include:
  - .state1
```

```yaml
# cat /srv/salt/test/state1.sls 
{%- from "map.jinja" import abc with context %}

Ok with {{ abc }}:
  test.succeed_without_changes
```

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

```console
# salt-ssh 'node1' state.sls test
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 500, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 198, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.jinja

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 262, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 546, in render_jinja_tmpl
    "Jinja error: {}{}".format(exc, out), line, tmplstr, trace=tracestr
salt.exceptions.SaltRenderError: Jinja error: map.jinja
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 500, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 198, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.jinja

; line 1

---
{%- from "map.jinja" import abc with context %}    <======================

Ok with {{ abc }}:
  test.succeed_without_changes

Traceback (most recent call last):
[...]
---
[CRITICAL] Rendering SLS 'base:test.state1' failed: Jinja error: map.jinja
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 500, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 198, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.jinja

; line 1

---
{%- from "map.jinja" import abc with context %}    <======================

Ok with {{ abc }}:
  test.succeed_without_changes

Traceback (most recent call last):
[...]
---
node1:
    - Rendering SLS 'base:test.state1' failed: Jinja error: map.jinja
      Traceback (most recent call last):
        File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 500, in render_jinja_tmpl
          output = template.render(**decoded_context)
        File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
          self.environment.handle_exception()
        File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
          reraise(*rewrite_traceback_stack(source=source))
        File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
          raise value.with_traceback(tb)
        File "<template>", line 1, in top-level template code
        File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 198, in get_source
          raise TemplateNotFound(template)
      jinja2.exceptions.TemplateNotFound: map.jinja
      
      ; line 1
      
      ---
      {%- from "map.jinja" import abc with context %}    <======================
      
      Ok with {{ abc }}:
        test.succeed_without_changes
      
      Traceback (most recent call last):
      [...]
      ---
```

**Expected behavior**

Exactly the same as older salt versions, if I downgrade salt-ssh to 3002.6 and run the exact same command it works well

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
 
```
</details>

**Additional context**

I did not have time to investigate more what changes in 3003 have introduced this, but I will at the end of the week if needed

**Comment by TeddyAndrieux** [comment] 2021-07-27 16:31
Ok I investigated a bit so it's seems it's something that changed in fileclient

On 3003.1 (where it does not work)
```console
[DEBUG   ] Jinja search path: ['/var/tmp/.root_d9ba66_salt/running_data/var/cache/salt/minion/files/base']
[DEBUG   ] In saltenv 'base', looking at rel_path 'map.jinja' to resolve 'salt://map.jinja'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/master/files/base/map.jinja' to resolve 'salt://map.jinja'
[DEBUG   ] Jinja Error
```

On 3002.6 (where it actually work)
```console
[DEBUG   ] Jinja search path: ['/var/tmp/.root_d9ba66_salt/running_data/var/cache/salt/minion/files/base']
[DEBUG   ] In saltenv 'base', looking at rel_path 'map.jinja' to resolve 'salt://map.jinja'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/tmp/.root_d9ba66_salt/running_data/var/cache/salt/minion/files/base/map.jinja' to resolve 'salt://map.jinja'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://map.jinja'
```

It seems in 3003.1 it use the cache instead of the thin dir

But it's weird because for state it use the thin dir :confused: 

I will investigate a bit more

**Comment by dwoz** [comment] 2021-08-31 05:17
The following patch will fix this issue:

```
diff --git a/salt/utils/jinja.py b/salt/utils/jinja.py
index 68a8646474..4666dc6ba3 100644
--- a/salt/utils/jinja.py
+++ b/salt/utils/jinja.py
@@ -99,6 +99,10 @@ class SaltCacheLoader(BaseLoader):
         if self._file_client is None:
             attr = "_cached_pillar_client" if self.pillar_rend else "_cached_client"
             cached_client = getattr(self, attr, None)
+            if cached_client is not None:
+                if cached_client.opts['cachedir'] != self.opts['cachedir']:
+                    self.shutdown()
+                    cached_client = None
             if cached_client is None:
                 cached_client = salt.fileclient.get_file_client(
                     self.opts, self.pillar_rend
```

**Comment by dwoz** [comment] 2021-09-01 23:21
Closing this as a duplicate of #60003

**Closed by dwoz** 2021-09-01 23:21 UTC
Labels: Bug, Duplicate, severity-high

**Comment by djneades** [comment] 2021-11-09 22:36
I agree that this issue is not a duplicate. I am not using `extra_filerefs`, and am still running into this issue’s problem (even with `3004`, where my changes to local imported templates are not being picked up).

**Comment by TeddyAndrieux** [comment] 2021-12-17 15:33
@dwoz can you consider re-opening this issue ?
