### ISSUE TITLE
Managing a file:// source fails

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#26526] opened 2015-08-20 18:28 UTC
To reproduce:
 1. Created a file `/tmp/a` and added some garbage content.
 2. Created the following state:
```
/tmp/b:
  file.managed:
   - source: file:///tmp/a
   - source_hash: md5=4f4748076f2f9b71dcb672604e7bca0c
```
Executing the state yields
```
          ID: /tmp/b
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1423, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3147, in check_managed_changes
                  group, mode, saltenv, template, contents)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3180, in check_file_meta
                  lstats = stats(name, hash_type=source_sum.get('hash_type', None), follow_symlinks=False)
              AttributeError: 'str' object has no attribute 'get'
     Started: 15:51:56.549278
    Duration: 4.289 ms
     Changes:
```
My version:
```bash
$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1precise2
```

This came out of #26497.

**Comment by jfindlay** [comment] 2015-08-20 18:55
@JensRantil, thanks for the report.

**Comment by jfindlay** [comment] 2015-09-25 19:52
This may be related or a duplicate of #26526.

**Comment by JensRantil** [comment] 2015-09-26 12:02
@jfindlay It is definitely a duplicate of itself! ;-)

**Comment by jfindlay** [comment] 2015-09-28 18:28
@JensRantil, sorry, I can't remember what the issue was about or why I thought this might be related.

**Comment by jfindlay** [comment] 2015-09-28 18:29
I think I may be suffering from some degree of issue madness.

**Comment by terminalmage** [comment] 2015-11-30 21:58
``file:///`` now works but source_hash is not checked for ``file:///`` URLs.

**Comment by terminalmage** [comment] 2015-11-30 22:07
Working on a fix now.

**Comment by terminalmage** [comment] 2015-11-30 22:45
Fix submitted in https://github.com/saltstack/salt/pull/29289.

**Closed** 2015-12-02 08:47 UTC
Labels: Bug, Execution Module, High Severity, P1, Platform, TEAM Core

**Comment by JensRantil** [comment] 2015-12-16 00:03
@terminalmage Great news!! Thanks! :clap: :clap: :clap:
