### ISSUE TITLE
No atomic  thin.tgz deploy

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#34509] opened 2016-07-07 12:51 UTC
It appears to me that the deploy of the salt-ssh thin.tgz is not atomic and very sensitive to environmental influences. The following minion has a bad network connectivity.

### First run:
```
minion:
    ----------
    retcode:
        255
    stderr:
        Connection to <IP> timed out while waiting to read
    stdout:
```

### Second run (which can also occur randomly after deleting the .root_dcdf8c_salt dir)
```
minion:
    ----------
    retcode:
        12
    stderr:
        1f8c882cd3d9c0813c2b44aec0873eebaf20bf11
        6e862ca205fbf41b72be7729b685f23fa7b104a2
        WARNING: checksum mismatch for "/var/tmp/.root_dcdf8c_salt/salt-thin.tgz"
    stdout:
        ERROR: Failure deploying thin: 
        1f8c882cd3d9c0813c2b44aec0873eebaf20bf11
        6e862ca205fbf41b72be7729b685f23fa7b104a2
        WARNING: checksum mismatch for "/var/tmp/.root_dcdf8c_salt/salt-thin.tgz"
```

### Alternative second run
```
minion:
    ----------
    retcode:
        11
    stderr:
        WARNING: Unable to locate current thin  version: /var/tmp/.root_dcdf8c_salt/version.
    stdout:
        ERROR: Failure deploying thin: /usr/bin/scp
        _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
        deploy
        
        WARNING: Unable to locate current thin  version: /var/tmp/.root_dcdf8c_salt/version.
```

```
salt:/srv # salt-ssh --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.2
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
 
System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.40-desktop
         system: Linux
        version: openSUSE  12.3 x86_64
```

NOTE: sometimes, it's a single tgz, sometimes there are two tgz in this directory and sometimes, there a lot of files.

Why does salt not recover here automatically?

**Comment by Ch3LL** [comment] 2016-07-07 18:22
@srkunze agreed this should be able to be more flexible. As a side note I believe this is also related to #26467, although it seems that issue is a different use case of selecting ctrl + c but is still the same concept that we do not provide more flexibility when copying over the thin tarbal. What do you think about closing 26467 and tracking it here? I guess it could also be argued to keep it open since its a unique test case from this as well. thoughts?

**Comment by srkunze** [comment] 2016-07-07 21:59
We can track everything here. :)

**Comment by Ch3LL** [comment] 2016-07-07 22:54
great thanks!

**Comment by thatch45** [comment] 2016-07-20 20:44
Just a quick question @srkunze , does running salt-ssh with the `-w` option get things working again?

**Comment by thatch45** [comment] 2016-07-20 20:57
@srkunze does the above change work for you? Can you test it out in your environment please? Since I can only fake a corrupted thin it would be helpful to verify if this recovers for you

**Comment by srkunze** [comment] 2016-07-31 10:57
@thatch45 Thanks for your effort here. I am still on vacations but I will give it a try soon. :)

**Comment by srkunze** [comment] 2016-08-24 13:44
@thatch45 
1) I tried the '-w' and it does not work consistently.
2) I also tried your patch, first deployment yields: "ERROR: Failure deploying thin: <checksum>", the second and third try are successful.

I still don't have a good feeling about this.

3) We use custom grains, maybe that results in the error. In the failure situation, a single /var/tmp/.root_dcdf8c_salt/salt-ext_mods.tgz stays there with the following content:
ext_version
grains/mygrain.py
grains/another_grain.py

**Comment by srkunze** [comment] 2016-08-25 10:11
More bits just to get you more context:

We have salt-ssh run for say 20 hosts. 10 of them fail with checksum mismatch. Next run, only 8 of them fail, next run, 8 again, next run, 5 etc. etc.

The pattern is not deterministic at least not to us.

**Comment by thatch45** [comment] 2016-08-25 20:03
I see it, there is a re-deploy problem, my fix makes it try to re-deploy once, but you need more, lemme try something

**Comment by thatch45** [comment] 2016-08-25 20:21
Thanks @srkunze , try this patch out please:
#35781
it is hard for me to reliably reproduce this failure case, thanks for helping out.

**Comment by thatch45** [comment] 2016-08-25 20:26
Oh, and I would say that, for your case, I would avoid `-w`

**Comment by srkunze** [comment] 2016-08-25 22:17
@thatch45 Will do tomorrow at work. Thanks for your help as well. :)

Looking at your patch, I still don't understand what the underlying problem really is.

Retrying it over and over again might work eventually but it feels strange. What's broken for us?

**Comment by thatch45** [comment] 2016-08-25 22:19
we shell out to scp to copy the file and then verify it, the scp seems to be failing to copy cleanly on your system. This I find very odd, and this is not something we see a lot (if any) of

**Comment by srkunze** [comment] 2016-08-25 22:20
It's like hitting the wall with a hammer not knowing where the nail is. But it's more likely to hit the nail if we hit more frequently.

**Comment by srkunze** [comment] 2016-08-25 22:21
> we shell out to scp to copy the file and then verify it, the scp seems to be failing to copy cleanly on your system. This I find very odd, and this is not something we see a lot (if any) of

Will investigate this further.

What I find irritating on salt's side, is that I don't see the corrupted thin.tgz on the minion. So, I cannot see what exactly when wrong during transfer (or what parts are missing).

Why gets it removed?

**Comment by thatch45** [comment] 2016-08-25 22:36
It is removed so that we don't just keep looking at it as a failed deployment. But this is a good idea, I can add a patch that backs it up so that you can inspect the bad checksumed file.

**Comment by srkunze** [comment] 2016-08-25 22:41
> It is removed so that we don't just keep looking at it as a failed deployment.

That's odd. The said /var/tmp/.root_dcdf8c_salt/ directory stays there with the salt-ext_mods.tgz file in it. Shouldn't these be removed also?

It's just that I try to make sense from what I have here. :)

**Comment by srkunze** [comment] 2016-08-25 22:48
Ah and last thought for tonight, why couldn't the corrupted thin.tgz and all other artifacts remain there until the next redeployment starts?

It seems to me that it could be possible that the deployment process could crash at any instance of this very process. So, the corrupted files and dirs will be there for the next salt-ssh run in this case anyway. This means the next salt-ssh call should be able to handle this no matter what.

Am I complete off track here?

**Comment by thatch45** [comment] 2016-08-25 23:03
it is designed to handle them if they are there, it is more of the overall "leave no trace" policy. I should at least add a no-cleanup flag

**Comment by srkunze** [comment] 2016-08-26 10:52
I tried out your patch:

It seem to work for some hosts but other others it crashes furiously:
```
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-29' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 613, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 391, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 801, in run
    stdout, stderr, retcode = self.cmd_block()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 1096, in cmd_block
    log.error('ERROR: Failure deploying thin, retrying: {0}\n{1}'.format(stdout, stderr), stderr, retcode)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1166, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1257, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

NOTE: line 1096 belongs to the " if not self.tty:" block.

**Comment by srkunze** [comment] 2016-08-26 11:19
I tried to fix your patch by removing ", stderr, retcode" from the log.logger.

Now, I basically an infinite loop. The following errors intertwined (in order of frequency):

```
[ERROR   ] ERROR: Failure deploying thin, retrying: _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
deploy
```


```
some-minion:
    ----------
    retcode:
        255
    stderr:
        Connection to <IP> timed out while waiting to read
    stdout:
[ERROR   ] ERROR: Failure deploying thin, retrying: 
Timeout, server minion not responding.
```

```
WARNING: Unable to locate current thin  version: /var/tmp/.root_dcdf8c_salt/version.
```

**Comment by srkunze** [comment] 2016-08-26 11:23
Interestingly, one minion which repeatedly fails to deploy and exits with "Timeout, server minion not responding." goes well the first time, it's deploy ALONE.

Is there a difference between running with other minions and running alone?

**Comment by srkunze** [comment] 2016-08-26 13:00
I tried more things out. Hope that this will help you to find the right spot.

We have several groups of minions. Depending on the number of deployment failures, the largest group does not recover at all after repeated execution. When "healing" some minions minions by running them alone, after a critical mass is reached, the largest group can recover completely. (example see below)

The smallest group needs only 2 or 3 rounds of re-running to recover completely.

I also noticed that only a fixed number of minions can recover per run. 4 seems to be the max for all groups (but it can be less, even 0).


----

```
salt-ssh 'large*' test.ping # 20x without recovery

salt-ssh large1 test.ping
salt-ssh large2 test.ping
.... # etc.

salt-ssh 'large*' test.ping # 5x then completely recovered
```

**Comment by thatch45** [comment] 2016-08-26 15:15
This information is VERY telling, I think that we have been digging in the wrong place. Set `--max-procs 1` in your command and see what happens.
How salt-ssh works is that it will spin up a bunch of parallel ssh connections to do the work, but I bet that the problem you are seeing with an unreliable transport is being exponentially exacerbated by have the default 25 procs working. Try some lower numbers there to see how it goes.

Also, can you post your log changes that got rid of the error so I have them for reference?

**Comment by srkunze** [comment] 2016-08-29 08:39
@thatch45 We can now confirm that it's not a problem in salt.
```
parallel -q --bar -j0 scp /var/cache/salt/master/thin/thin.tgz {}:/tmp ::: minion1 minion2 minion3 minion4....
```
Et voilà, randomly occurs:
```
Timeout, server minion3 not responding.
lost connection
```

It seems your version of the ssh/openssl/network stack is somehow broken. Distributions other than openSUSE 12.3 worked perfectly.

**Comment by srkunze** [comment] 2016-08-29 08:43
Thanks again for your support here. +1

About your patches. I leave it to you as you better know what should be in salt and what shouldn't.

My opinion: first patch, maybe; second patch, no.

Another suggestion from a colleague of mine:

```
[ERROR   ] ERROR: Failure deploying thin, retrying: _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
deploy
```
 this should also return the original error message of ssh (i.e why the deployment failed):

```
Timeout, server minion3 not responding.
lost connection
```


Shall I close this issue?

**Comment by srkunze** [comment] 2016-08-29 12:24
PS: WE FOUND IT!

In /root/.ssh/config ServerAliveInterval was set to 1. That also explains why parallel load causes the problem. It slows down the network beyond 1 sec.

**Comment by thatch45** [comment] 2016-08-29 15:20
Awesome, lets close this issue out and I will fix up my patches!

**Closed** 2016-08-29 17:14 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P2, Salt-SSH
