### ISSUE TITLE
Incorrect Logging of info for multimaster setup

### ISSUE THREAD

**Issue by daswathn** [saltstack/salt#39807] opened 2017-03-03 05:08 UTC
### Description of Issue/Question
The minion is setup for multi-master setup, but when you restart the minion the log says "random_master is True but there is only one master specified. Ignoring" which is not true, this error is being reported in the salt-call 2016.11.2 (Carbon) . It was working well with 2016.3.1.

But its working fine, communication between the multi-master and minion is fine. 

### Setup
cat /etc/salt/minion
```
master:
  - master01
  - master02
  - master03
random_master: True
```
### Steps to Reproduce Issue
Install the minion 2016.11.2 (Carbon)  with multi-master setup as show below, start the minion check the logs. 

> 2017-03-02[salt.minion][WARNING ][24488] random_master is True but there is only one master specified. Ignoring.
> 2017-03-02 [salt.minion][WARNING ][24488] random_master is True but there is only one master specified. Ignoring.
> 2017-03-02 [salt.minion][WARNING ][24488] random_master is True but there is only one master specified. Ignoring.

 
### Versions Report
Salt Master version 
salt-call --version
salt-call 2016.11.2 (Carbon)

Minion Version 
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.4.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.2
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Aug  5 2016, 11:15:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.3

System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-94-default
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64

**Comment by gtmanfred** [comment] 2017-03-03 16:03
I have confirmed this.  It actually looks like it is not choosing a random master.

There is also somewhere that is overwriting the opts['master'] list, which is causing problems with this check here.

Thanks for reporting.
Daniel

**Comment by terminalmage** [comment] 2017-03-30 18:56
Having looked at the code, it seems like ``random_master`` and ``master_shuffle`` both do almost the same thing, and both are only intended to be used when ``master_type`` is set to ``failover``. When the ``master_type`` is not ``failover``, then we spawn a separate coroutine for each minion (see the ``_spawn_minions()`` func in the ``salt.minion.MinionManager`` class), and each minion coroutine connects to a different master.

However, if you look at the [documentation](https://docs.saltstack.com/en/latest/ref/configuration/minion.html#master-shuffle), ``random_master`` doesn't mention anything about ``failover``, while ``master_shuffle`` does. This doesn't seem like a case where ``random_master`` is just a relic of an earlier salt release though, since it was introduced at the same time as ``master_shuffle``.

As another data point, If I start a minion with both ``random_master: True`` and ``master_type: failover``, I do get a single random master chosen, giving further credence to the idea that it's designed specifically for failover.

Given this information, I think we need to update the documentation, and also put one of ``random_master`` and ``master_shuffle`` on a deprecation path.

I would like some input from @cachedout and/or @thatch45 though, as this is my first time analyzing this code and I may well have a blind spot here.

**Comment by thatch45** [comment] 2017-04-03 17:37
@terminalmage I think you are over complicating this, basically the master key in opts is not a list when it should be, thats it, no need to worry about master_shuffle

**Comment by thatch45** [comment] 2017-04-03 18:53
@terminalmage I am up to speed now, you are not over-complicating this, sorry

**Comment by thatch45** [comment] 2017-04-03 18:58
@terminalmage you are completely correct. This is a documentation update

**Comment by thatch45** [comment] 2017-04-03 20:11
#40502 should handle it

**Comment by terminalmage** [comment] 2017-04-04 20:40
Since this is for failover only, and this has been cleared up with @thatch45's documentation fix, I will close this. I've opened https://github.com/saltstack/salt/issues/40532 to handle deprecation of ``master_shuffle`` and absorb its unique functionality into ``random_master``.

**Closed by terminalmage** 2017-04-04 20:40 UTC
Labels: 2016.11.4, Blocker, Core, High Severity, Multi-Master, P1, Regression, TEAM Core
