### ISSUE TITLE
S3 file module detect HTTP response codes != 200

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#25010] opened 2015-06-26 22:03 UTC
If you attempt to use an S3 url in file.managed (e.g. source: s3://bucket/etc and in source_hash)  but your IAM role lacks the proper permissions the http get fails ("S3 Response Status Code: 403"). Instead of detecting that failure, salt naively dumps that XML response into the file:

````xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>4136C880802B5BBC</RequestId><HostId>Hk4driOhdz18SdfP2NGWtaetZQmEui/MoYqrEAA5/TTrlDgxwdYO5tFmGicsVoUs</HostId></Error>  
````

The error you get from the failing file.managed state is quite opaque, because it the hash validation is what actually causes the error (the fetched hash contents contains a similar XML error.)

````
local:
----------
          ID: my_file
    Function: file.managed
        Name: /tmp/whatever/file_2015-06-25_9e978a5.tar.gz
      Result: False
     Comment: File sum set for file /tmp/whatever/file_2015-06-25_9e978a5.tar.gz of b65615672f727055dfad50cb6b33d047 does not match real sum of e9653c0b0236dc1f4e9b4f228c79f4bb
     Started: 21:58:05.181635
    Duration: 354.876 ms
     Changes:   
              ----------
              diff:
                  New file
````   

Tested with 2014.7.5+ds-1ubuntu1 and 2015.5.0+ds-1trusty1

**Comment by jtand** [comment] 2015-06-29 19:55
@notpeter Thanks for the bug report!

**Comment by rallytime** [comment] 2015-09-22 20:25
@notpeter Is this bug still happening for you on a newer release of salt? I just tried this at the head of the 2015.5 branch and I was not able to reproduce your issue:
```
local:
----------
          ID: my_file
    Function: file.managed
        Name: /tmp/whatever/file_2015-06-25_9e978a5.tar.gz
      Result: False
     Comment: Unable to determine upstream hash of source file s3://bucket/etc
     Started: 20:23:13.640479
    Duration: 6.029 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
And no file was made in the `/tmp/` directory. 
```
# salt --versions
           Salt: 2015.5.5-109-g775a4f9
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: Not Installed
```
If you could give this another try and let us know if this is still a problem or not, that would be great.

**Comment by notpeter** [comment] 2015-09-23 23:06
I'm still waiting for 2015.5.5 or 2015.8.0 to be packaged for Ubuntu,  I'll test when those binaries are available.

**Comment by rallytime** [comment] 2015-09-23 23:09
@notpeter Ok, no problem at all. Thanks for being patient. Hopefully we'll have those packages available soon. :)

**Comment by rallytime** [comment] 2015-12-08 00:18
@notpeter Just another ping to see if you were able to test this with newer packages.

**Comment by rallytime** [comment] 2016-01-07 01:16
I'm going to go ahead and close this for now. If this bug shows up again after upgrading, leave a comment and we can take another look!

**Comment by notpeter** [comment] 2016-01-09 10:45
This wasn't fixed, it just manifests itself differently. It's still trying to parse a hash out of the XML error (and failing).  Unless you are running with loglevel=debug, there's no indication this was a 403 or 404.  For example:
````
poop:
  file.managed:
    - name: /tmp/poop
    - source: s3://fakebucket/file.whatever
    - source_hash: s3://fakebucket/file.whatever.md5
````
Output (info)
````
[INFO    ] Starting new HTTP connection (1): 169.254.169.254
[INFO    ] Starting new HTTPS connection (1): fakebucket.s3.amazonaws.com
[ERROR   ] Source hash file s3://fakebucket/file.whatever.md5 contains an invalid hash format, it must be in the format <hash type>=<hash>.
[INFO    ] Completed state [/tmp/poop] at time 10:42:35.243886
local:
----------
          ID: poop
    Function: file.managed
        Name: /tmp/poop
      Result: False
     Comment: Source hash file s3://fakebucket/file.whatever.md5 contains an invalid hash format, it must be in the format <hash type>=<hash>.
     Started: 10:42:35.193922
    Duration: 49.964 ms
     Changes:   
````
But with -l debug you can see what's actually happening.
````
[INFO    ] Starting new HTTPS connection (1): fakebucket.s3.amazonaws.com
[DEBUG   ] Setting read timeout to None
[DEBUG   ] "GET /file.whatever.md5 HTTP/1.1" 404 None
[DEBUG   ] S3 Response Status Code: 404
[DEBUG   ] Saving to local file: /var/cache/salt/minion/extrn_files/base/fakebucket/file.whatever.md5
[DEBUG   ] modules.file.py - extract_hash(): Extracting hash for file named: poop
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (128), presumably hash type : sha512
[DEBUG   ] modules.file.py - extract_hash(): From "line": <?xml version="1.0" encoding="UTF-8"?> got : []
[DEBUG   ] modules.file.py - extract_hash(): From "line": <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>fakebucket</BucketName><RequestId>6B87654EDEBC1308</RequestId><HostId>kvkzJRPqu/IkQ1OzUkbaQzNdKDD/yTagzXIIh45w7tWcljUWh04S01GQciR5/ZZaooTjKqPj118=</HostId></Error> got : []
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (96), presumably hash type : sha384
[DEBUG   ] modules.file.py - extract_hash(): From "line": <?xml version="1.0" encoding="UTF-8"?> got : []
[DEBUG   ] modules.file.py - extract_hash(): From "line": <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>fakebucket</BucketName><RequestId>6B87654EDEBC1308</RequestId><HostId>kvkzJRPqu/IkQ1OzUkbaQzNdKDD/yTagzXIIh45w7tWcljUWh04S01GQciR5/ZZaooTjKqPj118=</HostId></Error> got : []
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (64), presumably hash type : sha256
[DEBUG   ] modules.file.py - extract_hash(): From "line": <?xml version="1.0" encoding="UTF-8"?> got : []
[DEBUG   ] modules.file.py - extract_hash(): From "line": <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>fakebucket</BucketName><RequestId>6B87654EDEBC1308</RequestId><HostId>kvkzJRPqu/IkQ1OzUkbaQzNdKDD/yTagzXIIh45w7tWcljUWh04S01GQciR5/ZZaooTjKqPj118=</HostId></Error> got : []
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (56), presumably hash type : sha224
[DEBUG   ] modules.file.py - extract_hash(): From "line": <?xml version="1.0" encoding="UTF-8"?> got : []
[DEBUG   ] modules.file.py - extract_hash(): From "line": <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>fakebucket</BucketName><RequestId>6B87654EDEBC1308</RequestId><HostId>kvkzJRPqu/IkQ1OzUkbaQzNdKDD/yTagzXIIh45w7tWcljUWh04S01GQciR5/ZZaooTjKqPj118=</HostId></Error> got : []
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (40), presumably hash type : sha1
[DEBUG   ] modules.file.py - extract_hash(): From "line": <?xml version="1.0" encoding="UTF-8"?> got : []
[DEBUG   ] modules.file.py - extract_hash(): From "line": <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>fakebucket</BucketName><RequestId>6B87654EDEBC1308</RequestId><HostId>kvkzJRPqu/IkQ1OzUkbaQzNdKDD/yTagzXIIh45w7tWcljUWh04S01GQciR5/ZZaooTjKqPj118=</HostId></Error> got : []
[DEBUG   ] modules.file.py - extract_hash(): Will use regex to get a purely hexadecimal number of length (32), presumably hash type : md5
[DEBUG   ] modules.file.py - extract_hash(): From "line": <?xml version="1.0" encoding="UTF-8"?> got : []
[DEBUG   ] modules.file.py - extract_hash(): From "line": <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>fakebucket</BucketName><RequestId>6B87654EDEBC1308</RequestId><HostId>kvkzJRPqu/IkQ1OzUkbaQzNdKDD/yTagzXIIh45w7tWcljUWh04S01GQciR5/ZZaooTjKqPj118=</HostId></Error> got : []
[DEBUG   ] modules.file.py - extract_hash: Returning None.
[ERROR   ] Source hash file s3://fakebucket/file.whatever.md5 contains an invalid hash format, it must be in the format <hash type>=<hash>.
[INFO    ] Completed state [/tmp/poop] at time 10:40:35.995289
````

**Comment by notpeter** [comment] 2016-01-09 10:47
And versions if it matters:
````
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty
 ````

**Comment by rallytime** [comment] 2016-01-10 00:09
Thanks for the extra info.

**Closed** 2016-06-06 20:14 UTC
Labels: Bug, High Severity, P2, RIoT, State Module
