### ISSUE TITLE
archive.extracted hashes the wrong value

### ISSUE THREAD

**Issue by jasonkeene** [saltstack/salt#20681] opened 2015-02-13 16:12 UTC
I have this in my states:

```
ioncube_loaders_lin_x86-64.tar.gz:
  archive.extracted:
    - name: /srv/ioncube/
    - source: http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
    - source_hash: sha1=f763ea8f1acfbd27c4fb6e43af3c3748ae6399a8
    - archive_format: tar
    - tar_options: z
```

It gives me this error:

```
          ID: ioncube_loaders_lin_x86-64.tar.gz
    Function: archive.extracted
        Name: /srv/ioncube/
      Result: False
     Comment: File sum set for file /var/cache/salt/minion/files/base/_srv_ioncube_.tar of f763ea8f1acfbd27c4fb6e43af3c3748ae6399a8 does not match real sum of b3efce1a8bf153871f576cecb5c627a827114294
     Started: 11:07:34.778603
    Duration: 1743.854 ms
     Changes:
```

Here are the hash values for the .tar and .tar.gz:

```
$ wget -O- http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz 2> /dev/null | tee >(echo '.tar.gz' $(sha1sum)) >(echo '.tar' $(gunzip -c | sha1sum)) > /dev/null
.tar b3efce1a8bf153871f576cecb5c627a827114294 -
.tar.gz f763ea8f1acfbd27c4fb6e43af3c3748ae6399a8 -
```

So it is checking the hash against the gunziped tar. This is unexpected behavior as the source_hash worked for file.managed.

I am running 2014.7.1 on both minions and master.

**Comment by jfindlay** [comment] 2015-02-13 18:01
@jasonkeene, thanks for the report.

**Comment by jasonkeene** [comment] 2015-02-14 09:15
No problem. I was thinking a solution would be to add a tar.gz archive_format that did the hash on the whole thing. This wouldn't break anyone's states.

**Comment by cachedout** [comment] 2015-02-17 23:37
@jasonkeene We would happily accept a PR to fix this if you would like to take a swing at it. :]

**Comment by edwardsgs** [comment] 2015-04-03 18:55
I am running into almost exactly the same thing, but my source file is simply .tar, not a .tar.gz. 

My State
untar:
  archive:
    - extracted
    - name: /usr/local/
    - source: /usr/local/staging/file.tar
    - source_hash: md5=934f86bda6a757b44e53c7131e9e23b5
    - if_missing: test -d /usr/local/App
    - archive_format: tar
    - tar_options: x
    - require:
        - cmd: downloadfile

Error seen in state run
          ID: untar
    Function: archive.extracted
        Name: /usr/local
      Result: False
     Comment: File sum set for file /var/cache/salt/minion/_usr_local_App.tar of ee2300f8f21d2c22bbf0cb493dd26955 does not match real sum of ac269bfee5ed35b4c682669f766f0cd1
     Changes:  

The tar file ends up in the /usr/local/staging directory I can manually get a correct md5 sum from it.

Does this look like the same error or at least a valid error?

**Comment by rhansen** [comment] 2016-03-22 08:45
The following four issues all seem to be the same bug:

  * #20681
  * #26981
  * #27397
  * #29010

I too am experiencing this with Salt 2015.8.7.

**Comment by llevar** [comment] 2016-09-16 12:50
I also have this issue.

**Comment by terminalmage** [comment] 2016-11-02 17:52
I cannot reproduce this in 2015.8.0 or anything later, it looks to have been fixed in a past release. @llevar your issue might have been something completely different, having to do with tornado's handling of gzip'ed data. That particular issue was fixed earlier today in https://github.com/saltstack/salt/pull/37418.

I'm going to close this. @llevar If https://github.com/saltstack/salt/pull/37418 doesn't fix it for you, please open a new issue and include the information requested in the issue template, so that we can better troubleshoot this.

**Closed by terminalmage** 2016-11-02 17:52 UTC
Labels: Bug, High Severity, P4, Platform, State Module
