### ISSUE TITLE
Installing 2014.7.1 -- find: `/usr/lib/python2.7/dist-packages/salt/': No such file or directory

### ISSUE THREAD

**Issue by DaveQB** [saltstack/salt#21107] opened 2015-02-27 02:18 UTC
Ubuntu 12.04.4 LTS
salt 2014.1.3-2precise1

Hi all,

Trying to install 2014.7.1 on my secondary master which is running 2014.1.3. 

The exact message I get is this:

```
Preparing to replace salt-master 2014.1.3-2precise1 (using .../salt-master_2014.7.1+ds-3precise1_all.deb) ... 
salt-master stop/waiting 
Unpacking replacement salt-master ... 
dpkg: warning: unable to delete old directory '/etc/salt/pki/master': Directory not empty 
dpkg: warning: unable to delete old directory '/var/cache/salt/master': Directory not empty 
Preparing to replace salt-minion 2014.1.3-2precise1 (using .../salt-minion_2014.7.1+ds-3precise1_all.deb) ... 
salt-minion stop/waiting 
Unpacking replacement salt-minion ... 
dpkg: warning: unable to delete old directory '/etc/salt/pki/minion': Directory not empty 
dpkg: warning: unable to delete old directory '/var/cache/salt/minion': Directory not empty 
Preparing to replace salt-common 2014.1.3-2precise1 (using .../salt-common_2014.7.1+ds-3precise1_all.deb) ... 
Removing stale pyc files 
find: `/usr/lib/python2.7/dist-packages/salt/': No such file or directory 
dpkg: error processing /var/cache/apt/archives/salt-common_2014.7.1+ds-3precise1_all.deb (--unpack): 
 subprocess new pre-installation script returned error exit status 1 
Processing triggers for ureadahead ... 
Processing triggers for man-db ... 
Processing triggers for python-support ... 
Errors were encountered while processing: 
 /var/cache/apt/archives/salt-common_2014.7.1+ds-3precise1_all.deb 
E: Sub-process /usr/bin/dpkg returned an error code (1) 
```

I am now left in this state:

```
ii  salt-common                                     2014.1.3-2precise1                              Shared libraries that salt requires for all packages
un  salt-doc                                        <none>                                          (no description available)
iU  salt-master                                     2014.7.1+ds-3precise1                           remote manager to administer servers via salt
iU  salt-minion                                     2014.7.1+ds-3precise1                           client package for salt, the distributed remote execution system
```

So it's the salt-common package.
Looking at the contents of my installed salt-common, it looks to be working out of:

/usr/share/pyshared/salt/

Looks like an issue in the install script not handling a missing /usr/lib/python2.7/dist-packages/salt/ gracefully.

**Comment by DaveQB** [comment] 2015-02-27 02:20
An purge of all three packages and install fixed this. So far. I am not sure what that has broken. Nothing I can't rebuild. But I will have 150 servers that I need to upgrade, so this is going to be a problem for me.

**Comment by RobertFach** [comment] 2015-02-27 07:29
Hi, I have already reported that issue in ticket #19124, I "fixed" that by creating the directory the find is looking for... Anyway, sthg. is wrong with the installer script.

**Comment by jfindlay** [comment] 2015-02-27 19:36
@DaveQB, this looks to be a duplicate of #19124.  Let us know if you have any updates, thanks.

**Closed by jfindlay** 2015-02-27 19:36 UTC
Labels: Duplicate

**Comment by DaveQB** [comment] 2015-03-02 01:45
@jfindlay I hate it when a duplicate ticket is created. My bad, sorry.

**Comment by jfindlay** [comment] 2015-03-03 22:23
@DaveQB, no problem.  I hate it too, but keeping the salt community positive is far more important to me.  Thanks for your attention and contributions to this issue.
