### ISSUE TITLE
gpg renderer doesn't seem to work with salt-ssh, tries to execute gpg on the minion?

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#41135] opened 2017-05-08 21:15 UTC
Hi,

I tried to follow the instructions at https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.gpg.html to the letter, but I got stuck with:

```
% salt-ssh -c /opt/stuff/salt '*' pillar.get users
[WARNING ] Could not decrypt cipher -----BEGIN PGP MESSAGE-----
Version: GnuPG v1

[...]
-----END PGP MESSAGE-----
, received: gpg: keyblock resource `/.salt-ssh-thin-dir/gpgkeys/secring.gpg': file open error
gpg: keyblock resource `/.salt-ssh-thin-dir/gpgkeys/pubring.gpg': file open error
gpg: encrypted with RSA key, ID 5FF68C1B
gpg: decryption failed: secret key not available

minion-name:
    ----------
    josip:
        ----------
        [...]
        home:
            /home/josip
        password:
            -----BEGIN PGP MESSAGE-----
            Version: GnuPG v1

            [...]
            -----END PGP MESSAGE-----
        [...]
```

```
% salt-ssh -c /opt/stuff/salt '*' state.apply create-users
[WARNING ] Could not decrypt cipher -----BEGIN PGP MESSAGE-----
Version: GnuPG v1

[...]
-----END PGP MESSAGE-----
, received: gpg: keyblock resource `/.salt-ssh-thin-dir/gpgkeys/secring.gpg': file open error
gpg: keyblock resource `/.salt-ssh-thin-dir/gpgkeys/pubring.gpg': file open error
gpg: encrypted with RSA key, ID 5FF68C1B
gpg: decryption failed: secret key not available

[WARNING ] This is my custom logging after reading decrypted data: super extra secret
[CRITICAL] Rendering SLS 'base:create-users' failed: could not found expected ':'; line 16

---
[...]

    - password: -----BEGIN PGP MESSAGE-----
Version: GnuPG v1


hQIMA2Oj5Rhf9owbARAAiFacgMG5VESnd4du1Z9HfNjCpkd6O/xfe19LXuUSR+tN
RR03iZ1L9Kk4WuR6bhWwEOKQncaHhFpW0wGPi/pBhscBlv5lhFpd8y+ii3NJYPwi    <======================
siXEuIJ+Kd8xCB6EK5655ryYw8jBCIZn50ueCmEYB0NCdJgjA9sDDMH2F289DswC
[...]
```

So it does a decryption on the master at least once, which succeeds, but is ignored. And then the run on the minion mucks it up somehow.

I must be doing something wrong because https://github.com/saltstack/salt/issues/19114 indicates this should be working... but what? What is making it run on the minion? Did I miss something obvious in the documentation?

This is with 2016.11.3.

TIA.

**Comment by Ch3LL** [comment] 2017-05-09 16:12
@shallot looks like i was able to replicate this behavior. This was working in 2015.8.8 and broke in 2016.3 branch. The first commit to break it was c4c037d600b54de7d07626dc1a34a9f0f41fc9a6. 

The reason it was working previously was this call: `salt.syspaths.CONFIG_DIR, 'gpgkeys'` grabbed the correct value for the gpg_keydir in salt-ssh. Now it is this call in 2016.11.4: `os.path.join(__opts__['config_dir'], 'gpgkeys')` which grabs the salt-ssh config_dir of: `('/var/tmp/.root_e5ce0d_salt', 'gpgkeys')` which doesn't grab the correct dir to render the gpg data.

You can work around this by specifying the `gpg_keydir: /etc/salt/gpgkeys/` in your master config or roster config. This will work.

**Comment by shallot** [comment] 2017-05-09 21:12
@Ch3LL I actually already have something like that, in my master config:

```
root_dir: /opt/stuff/salt
gpg_keydir: /opt/stuff/salt/gpgkeys
```

But it had no effect. For some reason, `__salt__['config.get']('gpg_keydir')` returns nothing. Am I missing something?

**Comment by The-Loeki** [comment] 2017-05-09 22:54
The PR I just submitted fixes the logic bug of `gpg_keydir` being ignored

**Comment by shallot** [comment] 2017-05-10 08:41
@The-Loeki I tried that patch, and it resolved gpg_keydir into the equivalent of `thin_dir` + `/gpgkeys` again, and it sadly still doesn't work. Any suggestions?

**Comment by The-Loeki** [comment] 2017-05-10 09:13
Well @Ch3LL mentioned the switch to `config.get` as opposed to `CONFIG_DIR` as the possible culprit.

You might try reverting that one temporarily to see if that does it; in that case @rallytime should probably chime in, as she's the one who made that switch to enable the `--config-dir` cli option.

**Comment by shallot** [comment] 2017-05-10 13:03
Unfortunately none of that helps - reverting back to `os.path.join(salt.syspaths.CONFIG_DIR, 'gpgkeys')
` just gets me the value `/etc/salt/gpgkeys` which merely changes the error message to:

```
gpg: keyblock resource `/etc/salt/gpgkeys/secring.gpg': file open error
gpg: keyblock resource `/etc/salt/gpgkeys/pubring.gpg': file open error
gpg: encrypted with RSA key, ID FFFFFFFF
gpg: decryption failed: secret key not available
```

**Comment by shallot** [comment] 2017-05-10 13:04
Maybe my issue is that I don't see any `prepend_root_dir` coverage with this renderer's config variable?

**Comment by PauloGDPeixoto** [comment] 2017-05-19 12:41
I'm having the exact same issue since I updated from 2016.11.4 to 2016.11.5.

**Comment by shallot** [comment] 2017-05-19 18:38
@PauloGDPeixoto are you running salt-ssh as root, with config based in /etc/salt ?

**Comment by PauloGDPeixoto** [comment] 2017-05-22 08:37
@shallot I'm running as root, my config is inside my salt dir (/srv/salt-ssh/etc/salt).

**Comment by danielmotaleite** [comment] 2017-06-07 18:05
for me, appying patch  #41161 fixed the problem

**Comment by Ch3LL** [comment] 2017-06-08 15:27
Okay I was able to replicate the issue that @PauloGDPeixoto pointed out between versions 2016.11.4 and 2016.11.5 (I had to move my gpgkeydir to another location - /etc/salt2/gpgkeys/) and the commit is 9f6e2e9c92faf5c5f2354ed2ecacf2b1a35c382b. But this is fixed at the head of 2016.11 so that will be fixed with 2016.11.6.

I was also able to replicate @shallot 's issue on v2016.11.3 by changing both the root dir and gpg key dir locations to /etc/salt2 but i noticed this is fixed at the head of 2016.11 as well. Can both of you guys confirm this is the case?

**Comment by shallot** [comment] 2017-06-08 19:30
@Ch3LL I tried it again with 2016.11.5 but it was still broken; I then manually applied the current version, 24946fe, and that one actually works.

**Comment by rmarchei** [comment] 2017-06-20 10:15
I can confirm that applying both https://github.com/saltstack/salt/commit/9f6e2e9c92faf5c5f2354ed2ecacf2b1a35c382b and https://github.com/saltstack/salt/commit/24946fef189eb6f21792cb3dcf93ae236f7611f4 fixes the issue. Thanks for the patches!

**Comment by Ch3LL** [comment] 2017-06-21 18:22
Perfect I will close this issue. Please let us know if it needs to be re-opened

**Closed by Ch3LL** 2017-06-21 18:22 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P3, Renderers, Salt-SSH
