### ISSUE TITLE
Change state from service.start ignored if enable is used

### ISSUE THREAD

**Issue by adyxax** [saltstack/salt#21928] opened 2015-03-24 10:47 UTC
Salt doesn't report starting a service if the enable function is used. This behaviour happens on both Gentoo running salt  2014.7.2 or debian running salt 2014.1.13

The problem is triggered with this state :
```
sshd:
  service.running:
    {% if grains['os'] == 'Debian' %}
    - name: ssh
    {% endif %}
    - sig: /usr/sbin/sshd
    - enable: True
```

Running with salt-call on a server with sshd stopped properly start the service but fails to report it:
```
[INFO    ] Executing command '/etc/init.d/sshd start'
[...]
[INFO    ] Service sshd is already enabled, and is running
          ID: sshd
    Function: service.running
      Result: True
     Comment: Service sshd is already enabled, and is running
     Started: 23:22:52.715354
    Duration: 334.136 ms
     Changes:
```

Removing the enable function fixes that behaviour, which means that the changes from service.start are ignored if salt code branches into the enable function.

Big thanks to phx and BtbN on the irc channel for helping diagnose this issue.

**Comment by jfindlay** [comment] 2015-03-24 19:04
@adyxax, thanks for the report.

**Comment by lorengordon** [comment] 2015-03-26 01:43
I believe this is a duplicate of https://github.com/saltstack/salt/issues/20915, and has already been fixed in the 2014.7 branch.

**Comment by jfindlay** [comment] 2015-03-26 02:25
Thanks, @lorengordon, I forgot about that one.

**Comment by rallytime** [comment] 2015-04-03 20:44
Since this has already been fixed and since it was a duplicate of another issue, I am going to close this bug report. Please leave a comment if this issue pops up again!

**Closed by rallytime** 2015-04-03 20:44 UTC
Labels: Bug, Fixed Pending Verification, Medium Severity
