### ISSUE TITLE
git.latest incorrectly wants local and remote HEAD refs to match exactly

### ISSUE THREAD

**Issue by sparrc** [saltstack/salt#27487] opened 2015-09-29 00:38 UTC
Since upgrading to saltstack 2015.8.0, the `git.latest` function is returning incorrect results when the first commit on top of a repo is not the same as the origin repo.

Here is the local repo:

```
3ec6283 CSparr     2015-06-12 00:12 o [master] ignore bundle dir
b4174e4 Lifepillar 2015-09-20 20:28 o {origin/master} {origin/HEAD} Fix typo in pathogen#surround()
```

And here is the salt failure message.

```
----------
          ID: pathogen
    Function: git.latest
        Name: https://github.com/tpope/vim-pathogen
      Result: False
     Comment: Repository would be updated from 3ec6283 to b4174e4, but this is not a fast-forward merge. Set 'force_reset' to True to force this update.
     Started: 17:32:44.881669
    Duration: 1079.109 ms
     Changes:
----------
```

Commit `b4174e4` is already in the local repo, but salt thinks that it needs to be the HEAD of the repo. The HEAD of a local repo does *not* need to be the same as the remote for it to be up to date with the remote.

**Comment by jfindlay** [comment] 2015-09-29 18:09
@sparrc, thanks for the report.  I think the issue depends on what you mean by having a local repo uptodate with a remote repo.  Does it mean the remote repo has been fetched, or the current branch successfully rebased on the corresponding remote branch?

**Comment by sparrc** [comment] 2015-09-29 18:34
@jfindlay I would say yes to both. In my case, the local current branch has been successfully rebased. The error message from salt is stating that it wants commit `b4174e4`, but you can see in my commit history that `b4174e4` already is there, it's just not the HEAD

**Comment by jfindlay** [comment] 2015-09-30 18:09
@sparrc, that seems reasonable to me, thanks.

**Comment by drawsmcgraw** [comment] 2015-10-01 18:00
+1. Getting the same thing here. I'm using `git.latest()` with `force: True` (not sure if that is relevant). Running my state twice gives the same error.

```
riemann-server-configs:
  git.latest:
    - name: http://git.com/team/riemann-configs.git
    - target: /etc/riemann
    - force: True
```

And the error:

```
----------
          ID: riemann-server-configs
    Function: git.latest
        Name: http://git.com/team/riemann-configs.git
      Result: False
     Comment: Repository would be updated from da2b65a to da2b65a, but this is not a fast-forward merge. Set 'force_reset' to True to force this update.
     Started: 10:44:22.253934
    Duration: 162.76 ms
     Changes:   
```

Trying to appease Salt by using `force_reset` as mentioned doesn't help. Definitely introduced with 2015.8.0.

Versions:

```
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: CentOS 6.7 Final

```

**Comment by blast-hardcheese** [comment] 2015-10-08 20:49
+1, also experiencing this issue

**Comment by blast-hardcheese** [comment] 2015-10-08 20:59
Turns out this is because `--is-ancestor` is not available in the version of Git I'm running, `git-1.7.1-3.el6_4.1.x86_64` on Cent 6

**Comment by drawsmcgraw** [comment] 2015-10-08 21:08
Wait, @blast-hardcheese do you mean to say you're running an old version of git? I'm also on Cent 6. Maybe I just need an upgrade?

**Comment by blast-hardcheese** [comment] 2015-10-08 21:51
According to yum, 1.7.1 is the latest available in Cent 6+epel, but that doesn't have --is-ancestor

**Comment by jfindlay** [comment] 2015-10-08 23:35
@terminalmage

**Comment by drawsmcgraw** [comment] 2015-10-09 17:58
@blast-hardcheese, sure enough. I have a CentOS 7 machine with Git `1.8.3.1` installed and I do not have this issue with `git.latest`.

**Comment by blast-hardcheese** [comment] 2015-10-09 18:01
@drawsmcgraw The test is checking the return code of `git merge-base --is-ancestor`. If it's unsupported, the return code seems to be very high (129 iirc)

**Comment by blast-hardcheese** [comment] 2015-10-09 18:06
Seems like prior to this option, `--is-ancestor` was implemented via:

```
A=$(git rev-parse --verify A)
if test "$A" = "$(git merge-base A B)"
then
    ... A is an ancestor of B ...
fi
```

Source: https://git-scm.com/docs/git-merge-base

**Comment by terminalmage** [comment] 2015-10-12 22:11
@blast-hardcheese @drawsmcgraw 

I just opened https://github.com/saltstack/salt/pull/27883 which uses the logic from the [earlier post](https://github.com/saltstack/salt/issues/27487#issuecomment-146949948) from @blast-hardcheese to check ancestry in git versions older than 1.8.

With regards to the original post (which is a separate point), I'm investigating now.

**Comment by terminalmage** [comment] 2015-10-12 22:37
@sparrc Please post the SLS example to help us better troubleshoot this for you.

**Comment by sparrc** [comment] 2015-10-12 23:35
This is basically it:

```
{% set HOME = "/Users/csparr" %}

pathogen:
  git.latest:
    - name: https://github.com/tpope/vim-pathogen
    - target: {{ HOME }}/.vim
```

**Comment by blast-hardcheese** [comment] 2015-10-13 01:41
I can confirm, in my case as well, simply using git latest triggered this issue

**Comment by terminalmage** [comment] 2015-10-13 04:41
@sparrc What rev do you want the local checkout to display?

**Comment by sparrc** [comment] 2015-10-13 05:23
@terminalmage I'm not sure what you mean by display, I would want it to pass the salt state since `origin/HEAD` is in the history. The HEAD of the local repo is a child commit of `origin/HEAD` and thus is up-to-date with the origin repository.

**Comment by blast-hardcheese** [comment] 2015-10-13 14:21
The problem is that git.latest checks to see if the current commit is an ancestor of the remote ref, checking that the retcode of `--is-ancestor` is 0. Old versions of git always return non-zero for that flag though, so it always fails that check.

The problem I am experiencing is on the initial highstate the repo is empty, so it's cloned.

On subsequent highstates, the current ref (say 123abc) is not an ancestor of the remote ref (123abc), so I have to pass `force_reset: True` to get it to not fail, but it reports changed every time, which runs watches unnecessarily.

**Comment by terminalmage** [comment] 2015-10-13 14:24
@blast-hardcheese did you not see my [earlier comment](https://github.com/saltstack/salt/issues/27487#issuecomment-147535273)?

**Comment by blast-hardcheese** [comment] 2015-10-13 14:30
@terminalmage: I might be missing some context for the issue-- I thought you were still trying to track down
>Commit b4174e4 is already in the local repo, but salt thinks that it needs to be the HEAD of the repo. The HEAD of a local repo does not need to be the same as the remote for it to be up to date with the remote.

**Comment by terminalmage** [comment] 2015-10-13 14:44
@blast-hardcheese yeah... Like I said, these are separate issues. The ``--is-ancestor`` issue you identified is handled by the pull request I opened yesterday. Secondarily, I am now adding an ``update_head`` argument to the ``git.latest`` state which, if set to ``False``, will return a ``True`` result from the state without updating HEAD when the remote rev exists locally.

Sorry for not explaining this better before.

**Comment by drawsmcgraw** [comment] 2015-10-13 14:59
@terminalmage #27883 sounds great. Looking forward to the next release so I can upgrade to 2015.8. If there's a specific tag/branch you can point me to, I'd be glad to test it out in my environment.

Thanks!

**Comment by terminalmage** [comment] 2015-10-13 15:11
@drawsmcgraw The PR was just merged, so the 2015.8 branch now has this fix.

**Comment by blast-hardcheese** [comment] 2015-10-13 15:47
@terminalmage: My apologies, I must have lost the thread. Glad you didn't :)

**Comment by terminalmage** [comment] 2015-10-13 15:51
@blast-hardcheese Well, I didn't mention the additional argument I was adding.  I could have made things easier to grok had I done so. :)

**Comment by drawsmcgraw** [comment] 2015-10-13 19:35
@terminalmage Beautiful! Can confirm it works in my environment. Thanks a bunch!

**Comment by terminalmage** [comment] 2015-10-13 19:55
@drawsmcgraw Thanks for taking the time to confirm!

**Comment by terminalmage** [comment] 2015-10-21 14:18
Hey, just wanted to give an update, I had some hardware issues and am now back up and running with a new laptop, so I should be able to complete the fix I described last week. Sorry for the delay.

**Comment by terminalmage** [comment] 2015-11-16 23:02
@sparrc Sorry for all the delays, I had hardware issues and family illness and all manner of things getting in my way these last few weeks, but I finally did get a pull request opened today: https://github.com/saltstack/salt/pull/28934

If possible, could you test this pull request? You can use [this walkthrough](https://help.github.com/articles/checking-out-pull-requests-locally/) to checkout a pull request locally.

Otherwise, you could wait for it to be merged and just install salt from the 2015.8 branch.

To tell Salt not to update the local HEAD, you'd have to use the new ``update_head`` option, like so:

```
{% set HOME = "/Users/csparr" %}

pathogen:
  git.latest:
    - name: https://github.com/tpope/vim-pathogen
    - target: {{ HOME }}/.vim
    - update_head: False
```

**Comment by sparrc** [comment] 2015-11-17 00:03
@terminalmage thanks! I'll try it out in the release :+1:

**Comment by terminalmage** [comment] 2015-11-17 15:34
@sparrc OK, cool. Just FYI, I mistakenly marked it as a 2015.8.2 feature in my pull request, but it just missed the cut for that release. I've fixed the version number [here](https://github.com/saltstack/salt/pull/28957/files).

**Comment by terminalmage** [comment] 2015-12-09 22:08
Closing this as the fix was merged a few weeks ago.

**Closed** 2015-12-09 22:08 UTC
Labels: Bug, Core, High Severity, Info Needed, P3, Regression, State Module, TEAM Core

**Comment by blast-hardcheese** [comment] 2015-12-09 22:38
Good to know, thanks @terminalmage!
