### ISSUE TITLE
FreeBSD contextvars DistributionNotFound

### ISSUE THREAD

**Issue by erai271** [saltstack/salt#65394] opened 2023-10-12 20:45 UTC
**Description**
Salt requires contextvars. 

**Setup**
FreeBSD 13.2 with py39-salt-3006.2.

- [x] on-prem machine
- [x] VM (KVM)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

```
[erai@bsd ~]$ sudo salt-call --local state.apply
[ERROR   ] Failed to import module config, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/salt/loader/lazy.py", line 772, in _load_module
    mod = self.run(spec.loader.load_module)
  File "/usr/local/lib/python3.9/site-packages/salt/loader/lazy.py", line 1232, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/salt/loader/lazy.py", line 1247, in _run_as
    return _func_or_method(*args, **kwargs)
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/salt/modules/config.py", line 22, in <module>
    import salt.utils.cloud
  File "/usr/local/lib/python3.9/site-packages/salt/utils/cloud.py", line 82, in <module>
    import pkg_resources  # pylint: disable=3rd-party-module-not-gated
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'contextvars' distribution was not found and is required by salt
```

**Expected behavior**
The salt command to not return an error about contextvars.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
[erai@bsd ~]$ salt --versions-report
Salt Version:
          Salt: 3006.2

Python Version:
        Python: 3.9.18 (main, Oct  3 2023, 01:17:31)

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.19.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 25.0.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: freebsd 13.2
        locale: utf-8
       machine: amd64
       release: 13.2-RELEASE
        system: FreeBSD
       version: FreeBSD 13.2
```
</details>

**Additional context**
At first glance this might seem like a FreeBSD packaging error to omit context vars. Howerver, since python 3.7, contextvars is part of the standard library. Salt can use the standard library module instead of requiring it.

**Comment by s0undt3ch** [comment] 2023-10-13 07:39
https://github.com/saltstack/salt/issues/64972
https://github.com/saltstack/salt/issues/64493

Closing as not a bug and desired behavior, as shown in comment, https://github.com/saltstack/salt/blob/e0bc1bd255b8745f1f31e78bba74edc66152a655/requirements/base.txt#L13

Looks like we might need to expand on the comment.
If this is missing on freebsd, install it, it's part of the base requirements.

**Closed by s0undt3ch** 2023-10-13 07:39 UTC
Labels: expected-behavior
