### ISSUE TITLE
[WARNING ] salt.loaded.int.module.zenoss.__virtual__() is wrongly returning `None`. 

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#38091] opened 2016-12-06 01:16 UTC
### Description of Issue/Question
I followed this tutorial at https://docs.saltstack.com/en/latest/topics/tutorials/docker_sls.html
and failed at step of "salt-call --local dockerng.sls_build test base=my_base_image mods=vim"
### Setup
centos7t01 is both minion and master.
```
[root@centos7t01 ~]# salt-call state.show_sls vim
local:
    ----------
    vim:
        ----------
        __env__:
            base
        __sls__:
            vim
        pkg:
            - installed
            |_
              ----------
              order:
                  10000
[root@centos7t01 ~]#
[root@centos7t01 ~]# rpm -qa |grep docker
python-docker-py-1.7.2-1.el7.noarch
python-docker-scripts-0.4.4-1.el7.noarch
docker-engine-selinux-1.12.3-1.el7.centos.noarch
docker-engine-1.12.3-1.el7.centos.x86_64
[root@centos7t01 ~]#
[root@centos7t01 ~]# pip install docker-py
Requirement already satisfied: docker-py in /usr/lib/python2.7/site-packages
Requirement already satisfied: websocket-client>=0.32.0 in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: requests!=2.11.0,>=2.5.2 in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: docker-pycreds>=0.2.1 in /usr/lib/python2.7/site-packages (from docker-py)
[root@centos7t01 ~]#
[root@centos7t01 ~]# python -c "import docker ; import docker.utils"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 20, in <module>
    from .client import Client, AutoVersionClient # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 19, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 29, in <module>
    from .exceptions import InvalidURL, InvalidHeader, FileModeWarning
ImportError: cannot import name InvalidHeader
[root@centos7t01 ~]#


```

### Steps to Reproduce Issue

```

[root@centos7t01 ~]# salt-call --local dockerng.sls_build test base=my_base_image mods=vim
[WARNING ] salt.loaded.int.module.zenoss.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If yoper of the module 'zenoss', please fix this.
'dockerng' __virtual__ returned False: Docker module could not get imported; You need to "pip install docker-py"
[root@centos7t01 ~]# salt-call --local dockerng.sls_build test base=my_base_image mods=vim
[WARNING ] salt.loaded.int.module.zenoss.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'zenoss', please fix this.
'dockerng' __virtual__ returned False: Docker module could not get imported; You need to "pip install docker-py"
[root@centos7t01 ~]# 
```
### Versions Report

```
[root@centos7t01 ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

[root@centos7t01 ~]#
```

**Comment by rallytime** [comment] 2016-12-06 16:26
@tjyang Does the PR above clear this up for you?

**Comment by tjyang** [comment] 2016-12-06 16:36
@rallytime, thanks for the quick reply. I will report back the PR fix.

**Comment by tjyang** [comment] 2016-12-06 16:48
@rallytime 
 Yes.  the PR fixed the zenoss warning message. I only have docker-py issue left.
Not sure how to fix this docker-py issue.

```
[root@centos7t01 yum.repos.d]# salt-call --local dockerng.sls_build test base=my_base_image mods=vim
'dockerng' __virtual__ returned False: Docker module could not get imported; You need to "pip install docker-py"
[root@centos7t01 yum.repos.d]# date
Tue Dec  6 10:44:02 CST 2016
[root@centos7t01 yum.repos.d]# pip install docker-py
Requirement already satisfied: docker-py in /usr/lib/python2.7/site-packages
Requirement already satisfied: websocket-client>=0.32.0 in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: requests!=2.11.0,>=2.5.2 in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied: docker-pycreds>=0.2.1 in /usr/lib/python2.7/site-packages (from docker-py)
[root@centos7t01 yum.repos.d]#

```

**Comment by rallytime** [comment] 2016-12-06 17:13
@tjyang Ah, right, I missed that part. Which version of docker-py do you have installed?

**Comment by tjyang** [comment] 2016-12-06 17:16
```
Looks like it is 1.7.2
```
[root@centos7t01 ~]# locate docker-py
/usr/share/doc/python-docker-py-1.7.2
/usr/share/doc/python-docker-py-1.7.2/LICENSE
/usr/share/doc/python-docker-py-1.7.2/README.md
[root@centos7t01 ~]# 
```

```

**Comment by tjyang** [comment] 2016-12-06 17:21
from pip show command it is version 1.10.6
```
[root@centos7t01 ~]# pip show docker-py
Name: docker-py
Version: 1.10.6
Summary: Python client for Docker.
Home-page: https://github.com/docker/docker-py/
Author: Joffrey F
Author-email: joffrey@docker.com
License: UNKNOWN
Location: /usr/lib/python2.7/site-packages
Requires: websocket-client, backports.ssl-match-hostname, ipaddress, six, requests, docker-pycreds
[root@centos7t01 ~]#

```

**Comment by rallytime** [comment] 2016-12-06 17:23
Hrm... I am unable to reproduce the error you're seeing when you try the `python -c "import docker ; import docker.utils"` What version of requests is installed?

**Comment by tjyang** [comment] 2016-12-06 17:28
1. remove docker-py rpm package(1.7.2) to keep just one version of docker-py from pip install's version(1.10.6)

```
Removing:
 python-docker-py               noarch          1.7.2-1.el7          @extras          235 k
Removing for dependencies:
 python-docker-scripts          noarch          0.4.4-1.el7          @epel             98 k
```

2.  I am seeing missing "docker" module after step above.

```
[root@centos7t01 ~]# python -c "import docker ; import docker.utils"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named docker
[root@centos7t01 ~]#

```

**Comment by rallytime** [comment] 2016-12-07 23:44
The problem seems to be coming from the requests import. What version of requests do you have installed?

**Comment by tjyang** [comment] 2016-12-08 10:11
It is 2.12.3
```
[root@centos7t01 ~]# pip show requests
Name: requests
Version: 2.12.3
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/lib/python2.7/site-packages
Requires:
[root@centos7t01 ~]#

```

**Comment by tjyang** [comment] 2016-12-13 16:15
@rallytime , I think this issue can be closed. 

I don't know exactly who but following are the steps I did (plus your zenoss patch) to fix the issue.

-  Update CentOS OS

```
yum update -y && reboot # update to CentOS 7.3 from 7.2
 pip install docker-py --upgrade
 [root@centos7t01 ~]#  python -c "import docker ; import docker.utils" ;echo $?
0
[root@centos7t01 ~]# 
```

- No more python module error

```
[root@centos7t01 ~]# salt-call --local dockerng.sls_build test base=my_base_image mods=vim
Error running 'dockerng.sls_build': Pull failed for my_base_image. Error(s) follow:

Error: image library/my_base_image:latest not found
[root@centos7t01 ~]#
```

- OS and Salt version info

```
[root@centos7t01 ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

[root@centos7t01 ~]#

```

**Comment by rallytime** [comment] 2016-12-13 16:19
@tjyang Ah, great! Thanks for following up. I think something strange must have been going on with the interaction of the version of dockerpy and requests on your box, but this is just my guess. I'll close this.

**Closed by rallytime** 2016-12-13 16:19 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P4, Platform, TEAM Core
