### ISSUE TITLE
[BUG] salt-master 3006 'onedir' packages don't include support for gitfs backend by default

### ISSUE THREAD

**Issue by jcpearson** [saltstack/salt#65182] opened 2023-09-13 12:39 UTC
I've attempted to update an existing salt-master that uses gitfs as a backend running 3004 on CentOS 7 to 3006.3 - but the onedir salt-master fails with 'No suitable gitfs provider module is installed.'

The documentation at https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html states that salt-pip needs to be used to install third party Python packages - but this won't work as there is no Internet access available to the salt-master

The previous 'classic' install of Salt from the RPMS provided via the repo at https://repo.saltproject.io/py3/redhat/7/x86_64/3004/ didn't need anything extra to support gitfs - so this is a regression with the 3006 packages

The onedir salt packages should include gitfs by default

**Comment by OrangeDog** [comment] 2023-09-13 15:28
Duplicate of #64299

**Closed by OrangeDog** 2023-09-13 15:28 UTC
Labels: Bug, needs-triage
