### ISSUE TITLE
Presence Events in the Event-Bus not reporting correctly

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#24374] opened 2015-06-03 20:17 UTC
I believe that a regression has been uncovered in 2015.5.0 in the Presences Events in the Event-Bus that impacts the Reactor system.  

###) Synopsis of Report:
* Identified in 2015.5.0 
* Same behavior not in 2014.7.1
* Re: `salt/presence/change` bus-event

** All the present Minions are showing up in `new` and anything that is `Lost` is not coming through in the Lost list. (See ticket for example output).

**Comment by rickh563** [comment] 2015-06-03 20:18
ZD-306

**Comment by tbaker57** [comment] 2015-06-03 20:39
Is this related to #23776 ?

cheers
Tim

**Comment by jfindlay** [comment] 2015-06-09 19:31
@rickh563, this looks like a duplicate, is it possible for them to try the fix mentioned in #23776?

**Comment by jfindlay** [comment] 2015-06-09 19:40
@rickh563, they can try the HEAD of the 2015.5 branch, which already has the fix.

**Comment by rallytime** [comment] 2016-06-17 22:25
Closing as duplicate (also confirmed that ZD-306 is resolved).

**Closed by rallytime** 2016-06-17 22:25 UTC
Labels: Duplicate, ZD
