### ISSUE TITLE
2015.8.0rc4_TheBigBear git rel. 'gcb9fddd' 'pkg,refresh_db' is not available.

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26740] opened 2015-08-28 16:34 UTC
@UtahDave ^^^ @twangboy 

At start of it this one has same error as #26739 but then it claims that ```pkg.refresh_db``` is also not available? Maybe I misinterpreted what was wrong in the other isssue or we really have two issues?
Or maybe just the one, the __opts__ arent there?

```
C:\salt>salt-call  --local pkg,refresh_db
[ERROR   ] Failed to import log_handlers sentry_mod, this is due most likely to
a syntax error:
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\loader.py", line 1105, in _load_module
    ), fn_, fpath, desc)
  File "c:\salt-dev\salt\salt\log\handlers\sentry_mod.py", line 96, in <module>
    __grains__ = salt.loader.grains(__opts__)
NameError: name '__opts__' is not defined
'pkg,refresh_db' is not available.
```

The ```salt-call --local --versions``` are still the same:
```
C:\salt>salt-call  --local --versions
Salt Version:
           Salt: 2015.8.0rc3-147-gcb9fddd

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD6
4)]
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.2.1
       cherrypy: 3.8.0
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: 1.3.8
        libnacl: 1.4.3
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.3
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
```

**Comment by twangboy** [comment] 2015-08-28 17:00
@TheBigBear This is affecting a lot of modules right now. @basepi Is working on a fix. Shouldn't be long.

**Comment by TheBigBear** [comment] 2015-08-28 17:10
@twangboy thanks. I have already created another one #26743 but lloks like they are all stemming from the same base. So I will stop flooding the issue list. Sorry.

**Comment by rallytime** [comment] 2015-08-28 17:22
Thanks @TheBigBear for the report! This should be fixed by #26744 and is also a duplicate of #26717. I'm going to close this for now so we have only one place to track the fix.

**Comment by TheBigBear** [comment] 2015-08-28 17:46
@basepi @rallytime @twangboy can you please re-open this? it is still there, and I do believe winrepo.refresh_db should be in a windows 2015.8 minion? but I still get
```
C:\salt-dev\salt>salt-call  --local winrepo.refresh_db
'winrepo.refresh_db' is not available.
```

**Comment by basepi** [comment] 2015-08-28 17:50
I was afraid that was the case. The error log was unrelated to whatever is not letting your module load.

**Comment by rallytime** [comment] 2015-08-28 17:51
@twangboy Can you take a look at this then, since it appears to be a different issue than originally thought?

**Comment by TheBigBear** [comment] 2015-08-28 17:53
maybe the clue to the cause of this is actually in https://github.com/saltstack/salt/issues/26748 ?

**Comment by twangboy** [comment] 2015-09-03 15:38
@TheBigBear I just noticed in the initial description of this issue, there's a comma in the command instead of a period. That would cause it not to be found. When I run it with a period, it works. A comma gives me the same error.

**Comment by TheBigBear** [comment] 2015-09-03 15:41
@twangboy oh silly me,. sorry I din't spot that earlier.

**Comment by twangboy** [comment] 2015-09-03 15:59
@TheBigBear We all missed it... :)

**Closed** 2015-09-03 15:58 UTC
Labels: Bug, High Severity, P1, Platform, Windows
