### ISSUE TITLE
FreeBSD pkgng provider raising error for minion

### ISSUE THREAD

**Issue by palica** [saltstack/salt#28262] opened 2015-10-23 21:17 UTC
When I change the provider for pkg to pkng the minion fails to start.
This is FreeBSD 10.2 and salt 2015.8.0_1
```python-traceback
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 8 seconds
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/grains.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/grains.conf
[DEBUG   ] Configuration file path: /usr/local/etc/salt/minion
[INFO    ] Setting up the Salt Minion "kostej"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/grains.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/grains.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] AsyncEventPublisher PUB socket URI: ipc:///var/run/salt/minion/minion_event_e3d2b40525_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: ipc:///var/run/salt/minion/minion_event_e3d2b40525_pull.ipc
[INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_e3d2b40525_pub.ipc
[INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_e3d2b40525_pull.ipc
[DEBUG   ] Minion 'kostej' trying to tune in
[DEBUG   ] sync_connect_master
[DEBUG   ] Initializing new SAuth for ('/usr/local/etc/salt/pki/minion', 'kostej', 'tcp://37.59.112.xx:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (10576)
[DEBUG   ] Setting zmq_reconnect_ivl to '10576ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/usr/local/etc/salt/pki/minion', 'kostej', 'tcp://37.59.112.xx:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/usr/local/etc/salt/pki/minion', 'kostej', 'tcp://37.59.112.xx:4506', 'aes')
[DEBUG   ] Re-using SAuth for ('/usr/local/etc/salt/pki/minion', 'kostej', 'tcp://37.59.112.xx:4506')
[DEBUG   ] Loaded minion key: /usr/local/etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/usr/local/etc/salt/minion.d/grains.conf'
[DEBUG   ] Reading configuration from /usr/local/etc/salt/minion.d/grains.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[ERROR   ] Exception raised when processing __virtual__ function for ifttt. Module will not be loaded global name '__salt__' is not defined
[WARNING ] salt.loaded.int.module.ifttt.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If
 you're the developer of the module 'ifttt', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for victorops. Module will not be loaded global name '__salt__' is not defi
ned
[WARNING ] salt.loaded.int.module.victorops.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name
. If you're the developer of the module 'victorops', please fix this.
[DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.10 or later must be installed before this module can be used.']
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[ERROR   ] Exception raised when processing __virtual__ function for zfs. Module will not be loaded global name '__salt__' is not defined
[WARNING ] salt.loaded.int.module.zfs.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If y
ou're the developer of the module 'zfs', please fix this.
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[INFO    ] The salt minion is shut down
[ERROR   ] Minion failed to start: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/daemons.py", line 272, in start
    self.minion.tune_in()
  File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 1596, in tune_in
    self.sync_connect_master()
  File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 724, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 732, in connect_master
    yield self._post_master_init(master)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 763, in _post_master_init
    self.returners)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/schedule.py", line 318, in __init__
    self.time_offset = self.functions.get('timezone.get_offset', lambda: '0000')()
  File "/usr/local/lib/python2.7/site-packages/salt/modules/timezone.py", line 94, in get_offset
    out = __salt__['cmd.run'](cmd)
NameError: global name '__salt__' is not defined
```

**Comment by palica** [comment] 2015-10-23 21:28
with the default provider values the packages don't get upgraded.

[INFO    ] Running state [mosh] at time 23:27:07.528386
[INFO    ] Executing state pkg.latest for mosh
[INFO    ] Executing command 'pkg search mosh' in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.version_cmp
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[INFO    ] Executing command 'pkg install  -y mosh' in directory '/root'
[INFO    ] Executing command 'pkg info -ao' in directory '/root'
[ERROR   ] Package mosh failed to update.
[INFO    ] Completed state [mosh] at time 23:27:09.335900

**Comment by jfindlay** [comment] 2015-10-26 16:41
@palica, thanks for the report.  It seems that there are three issues here:  my guess is that there is a syntax error the loader encounters when the pkg provider is set to `pkgng`, not setting the pkg provider, causes install candidates to not get installed, and when the loader encounters the pkgng error, rather than handling it gracefully, it fails to generate `__salt__`, which crashes the minion.

**Comment by palica** [comment] 2015-10-26 22:05
Thank you. I couldn't have said it nicer :). If there is something I can do
to debug it more, let me know.

**Comment by kraileth** [comment] 2015-10-27 09:06
On friday I ran into the same or a related issue, I think. Perhaps I can supply a bit more of information that may be helpful. My test machine is also FreeBSD 10.2 and I'm also using Salt Stack version 2015.8.0 for evaluation. I begun with a simple masterless setup and specifying programs to install **does** work. What does **not** is using "latest" - it will install the package if it is absent but then error out for some reason.

For example this works as intended:
sudo:
  pkg.installed

Whereas this causes the same problem that palica described above:

sudo:
  pkg.latest

Using "latest" leads to this output if sudo is not yet present on the system:

    sudo:
      pkg.latest
    
    [DEBUG   ] LazyLoaded config.get
    [DEBUG   ] Results of YAML rendering: 
    OrderedDict([('sudo', 'pkg.latest')])
    [DEBUG   ] LazyLoaded pkg.install
    [DEBUG   ] LazyLoaded pkg.latest
    [DEBUG   ] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
    [DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
    [DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.10 or later must be installed before this module can be used.']
    [DEBUG   ] Error loading module.victorops: No VictorOps api key found.
    [DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
    [DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
    [DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
    [DEBUG   ] Could not LazyLoad pkg.ex_mod_init
    [INFO    ] Running state [sudo] at time 09:53:15.896138
    [INFO    ] Executing state pkg.latest for sudo
    [INFO    ] Executing command 'pkg info -ao' in directory '/root'
    [INFO    ] Executing command 'pkg search sudo' in directory '/root'
    [DEBUG   ] Could not LazyLoad pkg.version_cmp
    [DEBUG   ] Could not LazyLoad pkg.normalize_name
    [INFO    ] Executing command 'pkg install  -y sudo' in directory '/root'
    [INFO    ] Executing command 'pkg info -ao' in directory '/root'
    [ERROR   ] Made the following changes:
    'sudo' changed from 'absent' to '1.8.14p3'

    [DEBUG   ] Refreshing modules...
    [INFO    ] Loading fresh modules for state activity
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [INFO    ] Completed state [sudo] at time 09:53:16.950213
    [DEBUG   ] File /var/cache/salt/minion/accumulator/34563144144 does not exist, no need to cleanup.
    [DEBUG   ] LazyLoaded highstate.output
    [DEBUG   ] LazyLoaded nested.output
    local:
    ----------
              ID: sudo
        Function: pkg.latest
          Result: False
         Comment: The following packages failed to update: sudo
         Started: 09:53:15.896138
        Duration: 1054.075 ms
         Changes:   
                  ----------
                  sudo:
                      ----------
                      new:
                          1.8.14p3
                      old:
    
    Summary for local
    ------------
    Succeeded: 0 (changed=1)
    Failed:    1
    ------------
    Total states run:     1
    Total run time:   1.054 s

I have no idea why Salt Stack thinks that installing failed. The change that it detected is exactly what it was meant to apply. And here's what happens if the current version of sudo is already present:

    sudo:
      pkg.latest
    
    [DEBUG   ] LazyLoaded config.get
    [DEBUG   ] Results of YAML rendering: 
    OrderedDict([('sudo', 'pkg.latest')])
    [DEBUG   ] LazyLoaded pkg.install
    [DEBUG   ] LazyLoaded pkg.latest
    [DEBUG   ] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
    [DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
    [DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.10 or later must be installed before this module can be used.']
    [DEBUG   ] Error loading module.victorops: No VictorOps api key found.
    [DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
    [DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
    [DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
    [DEBUG   ] Could not LazyLoad pkg.ex_mod_init
    [INFO    ] Running state [sudo] at time 09:55:23.267159
    [INFO    ] Executing state pkg.latest for sudo
    [INFO    ] Executing command 'pkg info -ao' in directory '/root'
    [INFO    ] Executing command 'pkg search sudo' in directory '/root'
    [DEBUG   ] Could not LazyLoad pkg.version_cmp
    [DEBUG   ] Could not LazyLoad pkg.normalize_name
    [INFO    ] Executing command 'pkg install  -y sudo' in directory '/root'
    [INFO    ] Executing command 'pkg info -ao' in directory '/root'
    [ERROR   ] Package sudo failed to update.
    [INFO    ] Completed state [sudo] at time 09:55:24.019566
    [DEBUG   ] File /var/cache/salt/minion/accumulator/34563144144 does not exist, no need to cleanup.
    [DEBUG   ] LazyLoaded highstate.output
    local:
    ----------
              ID: sudo
        Function: pkg.latest
          Result: False
         Comment: Package sudo failed to update.
         Started: 09:55:23.267159
        Duration: 752.407 ms
         Changes:   
    
    Summary for local
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1
    Total run time: 752.407 ms

I've tested the commands from the "[INFO    ] Executing command" lines and they all result in a return code of 0 so that should not be a problem.

If any more information is needed, I'd also gladly provide it.

**Comment by jfindlay** [comment] 2015-10-27 23:31
ping @cedwards, @kim0.

**Comment by cedwards** [comment] 2015-10-27 23:46
On FreeBSD 10.x the pkg provider will default to pkgng, so setting the value is not required. It was primarily put in place (and perhaps @terminalmage can comment here) for use during the transitional period between 9.x and 10.x as people on-boarded to pkgng.

According to the ``__virtual__`` function:

```
Load as 'pkg' on FreeBSD 10 and greater.
Load as 'pkg' on FreeBSD 9 when config option
``providers:pkg`` is set to 'pkgng'.
```

Sounds to me like we need to clarify when/if ``providers`` should be set.

**Comment by cedwards** [comment] 2015-10-28 00:04
I can confirm that ``pkg.latest`` gives false-negative output. It tells me that the ``latest`` fails, but it actually looks to be successful. I have not caught this before because I prefer not to use latest to avoid surprise updates.

**Comment by amontalban** [comment] 2016-04-05 12:23
+1

**Comment by amontalban** [comment] 2016-04-05 14:28
This are my findings so far:

**Salt Versions (I'm using latest version available in FreeBSD packages)**
```
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Mar 19 2016, 01:13:51)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.1-RELEASE-p31
```

My example SLS:

```yaml
nginx:
  pkg.latest:
    - name: nginx
    - require:
      - cmd: repository_update
    - fromrepo: REPOSITORY

repository_update:
  cmd.wait:
    - name: pkg update -f
```

My scenario:

- I have a custom packages repository where I have latest version of NGINX of port which is 1.8.1_1,2
- FreeBSD official packages repository have a NGINX version of 1.8.1,2 (Older than latest port, at least right now).
- This have not failed for me before (Been using pkg.latest for a while) so I think this can be a corner case.

The lines that mark the package upgrade as failed are present in [salt/states/pkg.py](https://github.com/saltstack/salt/blob/v2015.8.8/salt/states/pkg.py#L1538-L1541).

So for the help of any developer this are some useful outputs:

**Command:** `pkg search -q nginx`

```bash
[root@devserver ~]# pkg search -q nginx
nginx-1.8.1,2
nginx-devel-1.9.12
p5-Nginx-ReadBody-0.07_1
p5-Nginx-Simple-0.07_1
p5-Test-Nginx-0.25
nginx-1.8.1_1,2
```

**Command:** `pkg info -ao | grep -i nginx`

```bash
[root@devserver ~]# pkg info -ao | grep -i nginx
nginx-1.8.1_1,2                www/nginx
```

What I found is that pkg.py targets to version `1.8.1,2` and when it does the following comparision:

```python
            # Find failed and successful updates
            failed = [x for x in targets
                      if not changes.get(x) or changes[x]['new'] != targets[x]]
```

`changes[x]['new']` will be different than `targets[x]` because `changes[x]['new']` will be `1.8.1_1,2` and `targets[x]` will be `1.8.1,2`.

So the proper way to fix this will be to parse the output of `pkg search -q packagename` and select the higher version and assign it to `targets` so it compares the proper versions.

Hope this helps someone to get on the right direction, unfortunately I'm lacking of time to take this but if no one takes it maybe I can do it over weekend.

Thanks!

**Comment by amontalban** [comment] 2016-04-05 18:51
Well, actually I got some time to fix this because it was affecting our CD process.

**Before patching:**
```bash
[root@devserver /usr/local/lib/python2.7/site-packages]# salt-call --local pkg.latest_version nginx                                                                                                                                [1432/1975]
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
[INFO    ] Determining pillar cache
[INFO    ] Executing command 'pkg info -ao' in directory '/root'
[INFO    ] Executing command ['pkg', '--version'] in directory '/root'
[INFO    ] Executing command ['pkg', 'search', '-q', 'nginx'] in directory '/root'
local:
    1.8.1,2
```

**Applying patch:**

```bash
[root@devserver /usr/local/lib/python2.7/site-packages]# patch -p1 < /root/patch                                                                                                                                                              
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- a/salt/modules/pkgng.py
|+++ b/salt/modules/pkgng.py
--------------------------
Patching file salt/modules/pkgng.py using Plan A...
Hunk #1 succeeded at 277.
done
```

**After patching:**

```bash
[root@devserver /usr/local/lib/python2.7/site-packages]# salt-call --local pkg.latest_version nginx
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
[INFO    ] Determining pillar cache
[INFO    ] Executing command 'pkg info -ao' in directory '/root'
[INFO    ] Executing command ['pkg', '--version'] in directory '/root'
[INFO    ] Executing command ['pkg', 'search', '-S', 'name', '-Q', 'version', '-e', '-q', 'nginx'] in directory '/root'
local:
    1.8.1_1,2
```

The patch is the following:

```patch
--- a/salt/modules/pkgng.py
+++ b/salt/modules/pkgng.py
@@ -277,15 +277,19 @@ def latest_version(*names, **kwargs):
         quiet = False
 
     for name in names:
-        cmd = [_pkg(jail, chroot), 'search']
+        cmd = [_pkg(jail, chroot), 'search', '-S', 'name', '-Q', 'version', '-e']
         if quiet:
             cmd.append('-q')
         cmd.append(name)
 
         pkgver = _get_version(
             name,
-            __salt__['cmd.run'](cmd, python_shell=False, output_loglevel='trace')
+            sorted(
+                __salt__['cmd.run'](cmd, python_shell=False, output_loglevel='trace').splitlines(),
+                reverse=True
+            ).pop(0)
         )
+
         if pkgver is not None:
             installed = pkgs.get(name, [])
             if not installed:
```

The patch does the following:

  1) Make pkg search more efficient, it nows search for exact match searching for name and outputting version.

  **Prior output:**

  ```bash
[root@devserver ~]# pkg search -q nginx
nginx-1.8.1,2
nginx-devel-1.9.12
p5-Nginx-ReadBody-0.07_1
p5-Nginx-Simple-0.07_1
p5-Test-Nginx-0.25
nginx-1.8.1_1,2
```
  
  **Current output:**
  
  ```bash
[root@devserver ~]# pkg search -S name -Q version -e -q nginx
nginx-1.8.1,2
nginx-1.8.1_1,2
```

  As you can see the output is more accurate (Matching against our search `nginx` and not for any other package containing the `nginx` word). 

  2) Get the output of above command, transform it to a list, order it in descendant way and selecting the first item of the list.

This patch is also available as a [gist](https://gist.githubusercontent.com/amontalban/ca617b5f944144b0ad0a1116e6e7ce4a/raw/4f6857f6ed04cc56a1ac50e0544ebfc7090134f1/pkgpng.py) in case you want to test in your environment (This patch is against 2015.8.8).

Let me know if you need a PR for this.

Thanks!

**Comment by terminalmage** [comment] 2016-04-05 19:00
The `pkg.latest` state will run the `pkg.latest_version` to find out what the latest available version of the targeted package is, and then after the install it checks that the version it found earlier is now the one which is installed. So, at a glance, your patch looks good in that it corrects the `pkg.latest_version` output.

With your patch applied, can you run `salt minion-id pkg.latest pkgname --out=pprint` on a package known to be up-to-date, so we can be sure that we get an empty string as the return?

**Comment by amontalban** [comment] 2016-04-05 19:37
@terminalmage actually `pkg.latest` is not supported by FreeBSD, what should I do?

**Comment by terminalmage** [comment] 2016-04-05 19:39
Sorry, I meant `pkg.latest_version`.

**Comment by amontalban** [comment] 2016-04-05 19:45
Sure!

```bash
[root@devserver ~]# pkg info sudo
sudo-1.8.16
Name           : sudo
Version        : 1.8.16
Installed on   : Sat Mar 26 14:59:35 2016 UTC
Origin         : security/sudo
Architecture   : freebsd:10:x86:64
Prefix         : /usr/local
Categories     : security
Licenses       : sudo
Maintainer     : garga@FreeBSD.org
WWW            : http://www.sudo.ws/
Comment        : Allow others to run commands as root
Options        :
        AUDIT          : on
        DISABLE_AUTH   : off
        DISABLE_ROOT_SUDO: off
        DOCS           : on
        INSULTS        : off
        LDAP           : off
        NLS            : on
        NOARGS_SHELL   : off
        OPIE           : off
        SSSD           : off
Shared Libs required:
        libintl.so.8
Shared Libs provided:
        libsudo_util.so.0
Annotations    :
        cpe            : cpe:2.3:a:todd_miller:sudo:1.8.16:::::freebsd10:x64
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 3.46MiB
Description    :
This is the CU version of sudo.

Sudo is a program designed to allow a sysadmin to give limited root
privileges to users and log root activity.  The basic philosophy is to
give as few privileges as possible but still allow people to get their
work done.

WWW: http://www.sudo.ws/
```

As you can see in http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/ the latest version of sudo is `sudo-1.8.16.txz`.

This is the output with the patch applied:

```bash
[root@devserver ~]# salt-call --local pkg.latest_version sudo --out=pprint
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
[INFO    ] Determining pillar cache
[INFO    ] Executing command 'pkg info -ao' in directory '/root'
[INFO    ] Executing command ['pkg', '--version'] in directory '/root'
[INFO    ] Executing command ['pkg', 'search', '-S', 'name', '-Q', 'version', '-e', '-q', 'sudo'] in directory '/root'
{'local': ''}
```

Thanks for the quick reply!

**Comment by terminalmage** [comment] 2016-04-05 19:49
Awesome. I just wanted to make sure that we preserved expected behavior when a package is already up-to-date.

Can you submit a pull request?

**Comment by amontalban** [comment] 2016-04-05 19:51
Sure thing! Should I do it against 2015.8.8 or develop branch?

Thanks

**Comment by terminalmage** [comment] 2016-04-05 19:56
Open it against the [2015.8 branch](https://github.com/saltstack/salt/tree/2015.8), please. Thanks!

**Comment by amontalban** [comment] 2016-04-05 23:01
@terminalmage sorry for the noise, but github was acting funny and the commits were not visible. I have created PR #32376.

Thanks!

**Comment by terminalmage** [comment] 2016-04-06 20:30
Thanks, I've merged the pull request.

**Closed** 2016-04-06 20:30 UTC
Labels: Bug, High Severity, Loader, P3, Platform
