### ISSUE TITLE
[BUG] Can't generate keys on minion

### ISSUE THREAD

**Issue by p3lim** [saltstack/salt#63116] opened 2022-11-25 12:31 UTC
**Description**

After a fresh install of salt-minion it can't generate keys when attempting to contact the master.

```
[ERROR   ] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fa4506f4e18>, <salt.ext.tornado.concurrent.Future object at 0x7fa4507c8b00>)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 628, in _discard_future_result
    future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 653, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 779, in sign_in
    ret = self.handle_signin_response(sign_in_payload, payload)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 791, in handle_signin_response
    clear_signature = payload["sig"]
KeyError: 'sig'
```

It will hang here forever.

**Setup**
This is a fresh installation with only the master url changed.

**Steps to Reproduce the behavior**

- Install salt-minion from the official salt yum repos
- Configure master URL in `/etc/salt/minion`
- Run salt-call state.highstate

**Expected behavior**

Keys should be generated for the minion and is awaiting acceptance on the master.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

Master is running 3000.9

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: 5.0.3
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Comment by OrangeDog** [comment] 2022-11-25 13:25
Duplicate: #62780

**Comment by p3lim** [comment] 2022-11-25 16:46
The master is available though, I have other minions on earlier versions connected to my master just fine.

**Comment by OrangeDog** [comment] 2022-11-26 17:52
The stack trace is exactly the same though. Are you sure the master is reachable from that minion? Have you tried an earlier version on it?

**Comment by p3lim** [comment] 2022-11-27 14:18
I downgraded to 3000.9 and was able to connect to the master just fine.

**Comment by OrangeDog** [comment] 2022-11-27 14:37
Sorry, this is a duplicate of #61874.
Masters that old cannot communicate with current minions. You have to upgrade the master first.

**Closed by OrangeDog** 2022-11-27 14:37 UTC
Labels: Bug, Duplicate, needs-triage
