### ISSUE TITLE
 win_wua: uptodate fails with KeyError

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#52387] opened 2019-04-02 13:02 UTC
### Description of Issue/Question
I've not tried to use this before, so I'm not sure if this is specifically related to using `uptodate` or whether it can also happen with individual updates, but the installation process causes an unhandled KeyError.

### Setup
<pre># cat updatetest.sls
update_system:
  wua.uptodate:
    - skip_reboot: False</pre>

### Steps to Reproduce Issue

<pre># salt salt-test state.apply updatetest test=True --timeout=30
salt-test:
----------
          ID: update_system
    Function: wua.uptodate
      Result: None
     Comment: Updates will be installed:
              e47de1ba-26bc-40a4-88d7-849d03ed0be2: 2019-02 Cumulative Update for .NET Framework 3.5 and 4.7.2 for Windows 10 Version 1809 for x64 (KB4483452)
              cd50fb41-6418-490b-a685-869004e02656: 2019-02 Cumulative Update for .NET Framework 3.5 and 4.7.2 for Windows 10 Version 1809 for x64 (KB4486553)
              7c087cb2-e64e-4219-bd54-5b6a328b8cc1: Windows Malicious Software Removal Tool x64 - March 2019 (KB890830)
              bb071b97-fe31-42ec-badb-77e782f88bba: 2019-03 Security Update for Adobe Flash Player for Windows 10 Version 1809 for x64-based Systems (KB4489907)
              b0e02433-34e0-477d-830b-88366785595f: 2019-03 Cumulative Update for Windows 10 Version 1809 for x64-based Systems (KB4489899)
     Started: 12:43:38.357000
    Duration: 4672.0 ms
     Changes:

Summary for salt-test
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   4.672 s

# salt salt-test state.apply updatetest --timeout=30
salt-test:
----------
          ID: update_system
    Function: wua.uptodate
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1933, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_wua.py", line 486, in uptodate
                  if not salt.utils.data.is_true(post_info[item]['Installed']):
              KeyError: u'e47de1ba-26bc-40a4-88d7-849d03ed0be2'
     Started: 12:44:07.215000
    Duration: 823243.0 ms
     Changes:

Summary for salt-test
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 823.243 s
ERROR: Minions returned with non-zero exit code</pre>

### Versions Report
<pre># salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 25 2018, 20:42:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.11
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-7-amd64
         system: Linux
        version: debian 8.11</pre>

**Comment by frogunder** [comment] 2019-04-02 15:56
Thanks for the report. However I am not able to replicate this error. 

```
salt win2019 state.apply updatetest test=True --timeout=300

win2019:
----------
          ID: update_system
    Function: wua.uptodate
      Result: None
     Comment: Updates will be installed:
              5fed0b19-9930-49a2-9914-cefdbfb18043: Definition Update for Windows Defender Antivirus - KB2267602 (Definition 1.291.993.0)
     Started: 15:48:13.433000
    Duration: 2624.0 ms
     Changes:   

Summary for win2019
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   2.624 s
[root@li602-105 salt]# salt win2019 state.apply updatetest --timeout=300

win2019:
----------
          ID: update_system
    Function: wua.uptodate
      Result: True
     Comment: Updates installed successfully
     Started: 15:48:25.495000
    Duration: 44235.0 ms
     Changes:   
              ----------
              installed:
                  ----------
                  5fed0b19-9930-49a2-9914-cefdbfb18043:
                      ----------
                      KBs:
                          - KB2267602
                      NeedsReboot:
                          False
                      Title:
                          Definition Update for Windows Defender A...

Summary for win2019
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  44.235 s
```

What salt version is your windows minion? Can you run a `test.versions`?

**Comment by morganwillcock** [comment] 2019-04-02 17:22
It is likely update specific and order specific:

- I've installing the two .NET updates using win_wua.get, and then applied the uptodate state, and didn't get the same problem
- I've applied the uptodate state twice in a row and didn't get the problem on the second try

...so there seems to be a logic problem in the way installation results are processed.

<pre># salt salt-test test.versions
salt-test:
    Salt Version:
               Salt: 2019.2.0

    Dependency Versions:
               cffi: 1.11.5
           cherrypy: 17.4.1
           dateutil: 2.7.5
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.3
             PyYAML: 3.13
              PyZMQ: 17.1.2
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.2.5

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2019
             system: Windows
            version: 2019 10.0.17763  Multiprocessor Free</pre>

**Comment by frogunder** [comment] 2019-04-02 18:04
@twangboy @dwoz any thoughts on this?

**Comment by morganwillcock** [comment] 2019-04-02 18:37
I think it doesn't handle the case where installing an update makes a second update no longer eligible for installation, so it ends up looking for an update id that was initially available, but then isn't returned by `wua.updates().list()`.

https://github.com/saltstack/salt/blob/1bf25a10261d3b671fdc9d67851ee6cfcb83af70/salt/states/win_wua.py#L476-L486

I guess that technically this isn't a failure, so the first block of the 'if' statement should probably check `post_info[item]` and then report it as skipped rather than installed.

**Comment by morganwillcock** [comment] 2020-01-09 00:33
Ping

**Comment by sagetherage** [comment] 2020-02-11 20:49
@Akm0d @xeacott another follow up that looks like Shane got swamped and never was able to get back to, so reassigning for you two to tackle. Thx!

**Comment by xeacott** [comment] 2020-02-25 18:24
This is good I've been in these modules a lot lately, let me spend some time on this today and I should get back EOD with an answer for this but after quickly skimming @morganwillcock you're probably correct on that note.

**Comment by xeacott** [comment] 2020-02-25 18:40
Yeah @morganwillcock that's definitely the case. This edge case will probably be hard to reproduce, because its very conditional - so what probably happened here is that applying the `uptodate` state first found a security update, and then a cumulative update. The cumulative update contained the patch needed for the security update, but Window's decided that the cumulative update should be applied first (because its newer, contains more patches, etc. ) and then installed the cumulative update but still downloaded the security patch. 

After the installation of the cumulative update, the KB article number should have been found as present on the system, but what was returned to you was the GUID of the update as not found, which is correct but it shouldn't have failed. So then after re-running the state, the WUA was reinitialized with a fresh start and fresh scan, and then the system found that security update that caused the issue 😄 

By the looks of the code, though, `wua.refresh()` _should_ have did this for you, whereas `wua = salt.utils.win_update.WindowsUpdateAgent()` did it. Right, refreshing the agent versus created another entire instance of the agent. I'll figure out the correct fix to address this from happening in the future.

**Comment by morganwillcock** [comment] 2020-03-26 19:53
Ping

**Comment by xeacott** [comment] 2020-03-26 20:07
Hey! So would you be able to see if this PR fixes that issue? https://github.com/saltstack/salt/pull/56256

I realize your machine may not be in that same state as before, but never hurts to try!
And my PR is waiting on tests to be written, and since there are no tests for that module at all, I'll have to write some from scratch. That may take some time as of right now...

**Comment by sagetherage** [comment] 2020-05-19 21:53
closing as fixed @morganwillcock please let us know if this does not correct your issue

**Closed by sagetherage** 2020-05-19 21:53 UTC
Labels: Cannot Reproduce, Fixed Pending Verification, Sodium, Windows
