### ISSUE TITLE
mysql_grants.present adds extra characters to mysql

### ISSUE THREAD

**Issue by markododa** [saltstack/salt#47586] opened 2018-05-10 10:47 UTC
### Description of Issue/Question
I'm trying to grant all privileges to a user in mysql

`grant_all_on_db:
  mysql_grants.present:
    - grant: ALL PRIVILEGES
    - database: owncloud.*
    - host: localhost
    - user: {{ salt['pillar.get']('owncloud_dbuser', 'owncloud') }}
    - require:
      - pkg: python-mysqldb
`
I get a rule in mysql

GRANT ALL PRIVILEGES ON \`owncloud\`.\`*\` TO 'owncloud'@'localhost
which is faulty and doesn't grant anything

if i add a grant manualy with
GRANT ALL PRIVILEGES ON \`owncloud\`.* TO 'owncloud'@'localhost'

everything is ok.
Running  2018.3.0 (Oxygen) on both the master and minion

**Comment by Ch3LL** [comment] 2018-05-10 15:06
possible duplicate of https://github.com/saltstack/salt/issues/46917 ?

**Closed** 2018-05-10 18:06 UTC
Labels: Duplicate, Info Needed
