### ISSUE TITLE
salt-ssh should support the use of sudo with a password

### ISSUE THREAD

**Issue by ichilton** [saltstack/salt#60403] opened 2021-06-18 13:07 UTC
**Is your feature request related to a problem? Please describe.**

salt-ssh is a great tool, for bootstrapping or development. However, it's hampered by requiring either a root login (bad) or the use of sudo with NOPASSWD (not great).

**Describe the solution you'd like**

This is handled great by ansible. When you run with --ask-become-pass or -K, it prompts for the sudo password. It then passes that through to the target host.

salt-ssh should do the same thing - allow entry of the sudo password, which is passed to the host when running commands with sudo.

**Describe alternatives you've considered**

The only workarounds are bad for security - either allowing root logins, or allowing users to use sudo without the entry of their password.

**Additional context**

This has been mentioned/requested several times in the past, but never implemented.

eg:
https://github.com/saltstack/salt/issues/8723
https://github.com/saltstack/salt/issues/8882
https://github.com/saltstack/salt/pull/48435

**Comment by ichilton** [comment] 2022-01-30 18:49
@waynew Were you ever able to take a look at this?

It's a really important feature to make salt-ssh more useful and bring it inline with Ansible.

Thanks.

**Comment by OrangeDog** [comment] 2022-04-07 08:46
Duplicate of #60042

**Closed by OrangeDog** 2022-04-07 08:46 UTC
Labels: Feature, Salt-SSH

**Comment by heldner** [comment] 2024-02-22 20:07
It's not dup of #60042. It's about asking password for sudo.
