### ISSUE TITLE
git.latest exception when requested branch doesn't exist

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#30437] opened 2016-01-19 13:47 UTC
2015.8.3 (Beryllium)

```
myproject_dev_myproject_repo:
  git.latest:
    - name: git@myproject_dev_myproject:myproject_dev/myproject.git
    - target: /opt/projects/myproject
    - rev: master
    - identity: /root/.ssh/myproject.pkey
    - user: root
    - require:
      - pkg: git_package
      - ssh_known_hosts: myproject_dev_myproject_known_hosts
      - file: myproject_dev_myproject_directory
      - file: myproject_dev_myproject_keyfile
      - file: myproject_dev_myproject_ssh_config
```
When 'master' branch is not available in git repo:
```
[INFO    ] Running state [git@mycompany_dev_myproject:mycompany_dev/myproject.git] at time 16:31:42.369478
[INFO    ] Executing state git.latest for git@mycompany_dev_myproject:mycompany_dev/myproject.git
[INFO    ] Checking remote revision for git@mycompany_dev_myproject:mycompany_dev/myproject.git
stdin: is not a tty
[INFO    ] Executing command ['git', 'ls-remote', 'git@mycompany_dev_myproject:mycompany_dev/myproject.git'] as user 'root' in directory '/root'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 519, in latest
    if remote_rev_type == 'sha1':
UnboundLocalError: local variable 'remote_rev_type' referenced before assignment

[INFO    ] Completed state [git@mycompany_dev_myproject:mycompany_dev/myproject.git] at time 16:31:43.954007
```

----------
          ID: mycompany_dev_myproject_repo
    Function: git.latest
        Name: git@mycompany_dev_myproject:mycompany_dev/myproject.git
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 519, in latest
                  if remote_rev_type == 'sha1':
              UnboundLocalError: local variable 'remote_rev_type' referenced before assignment
     Started: 16:31:42.369478
    Duration: 1584.529 ms
     Changes:   
----------

**Comment by jfindlay** [comment] 2016-01-19 17:34
@zerthimon, thanks for the report.  I am going to close this as a duplicate of #29870.

**Closed by jfindlay** 2016-01-19 17:34 UTC
Labels: Duplicate
