### ISSUE TITLE
Another dead jenkins saltstack link in tutorial writing tests page

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#56544] opened 2020-04-03 19:37 UTC
Relevant salt docs pages:
- https://docs.saltstack.com/en/master/topics/tutorials/writing_tests.html

Relevant salt docs file and error:
```
writing output... [ 99%] topics/tutorials/writing_tests

(line  484) broken    https://jenkins.saltstack.com - HTTPSConnectionPool(host='jenkins.saltstack.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9ae7827940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
Comments
- manually verified

**Comment by ggiesen** [comment] 2021-03-12 03:56
I believe this is resolved by #56210, and this is issue is basically a dupe of #56209

**Comment by barbaricyawps** [comment] 2022-01-10 21:48
In light of @ggiesen 's comment, I am closing this issue.

**Closed by barbaricyawps** 2022-01-10 21:48 UTC
Labels: Documentation, severity-low
