### ISSUE TITLE
Parallel mode crashes with "list index out of range"

### ISSUE THREAD

**Issue by ninja-** [saltstack/salt#39832] opened 2017-03-04 18:45 UTC
### Description of Issue/Question
This is my first take at using the new parallel feature and it doesn't quite work in my setup.

SLS file
```
some_task:
  cloudflare.manage_zone_records:
    - zone: {{ pillar["xxx"]["dns"]["xxx.xyz"]|yaml }}
#    - parallel: True
```

```
    Function: cloudflare.manage_zone_records
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1817, in call
                  ret = self.call_parallel(cdata, low)
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1699, in call_parallel
                  ret = {'name': cdata['args'][0],
              IndexError: list index out of range
     Started: 19:38:35.127274
    Duration: 3.431 ms
```

Any ideas?

@thatch45 would you have an idea as an author of this feature.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Latest Salt Develop, python3
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by ninja-** [comment] 2017-03-04 22:23
This looks like a logical failure because the cdata[args][0] fallback should be duplicated to the second function. @thatch45 ?

https://github.com/saltstack/salt/blob/develop/salt/state.py#L1667

**Comment by Ch3LL** [comment] 2017-03-06 16:08
@ninja- thanks for the PR on this. Please feel free to close this issue once the PR has been reviewed/merged or we can.

**Comment by thatch45** [comment] 2017-03-06 18:37
Thanks for the cleanup here @ninja- ! I don't write features as much anymore because I just don't have the time to work on the cleanup and polish anymore. You assistance here is greatly appreciated!

**Comment by nullify005** [comment] 2017-09-18 05:11
Hey @ninja- @thatch45 this still looks to be a problem with 2017.7.1

I notice that the referenced PR also was closed due to inactivity, not because it got merged

Is it possible to get this fixed?

The parallel feature in the documentation appears to be entirely broken at the moment

**Comment by ninja-** [comment] 2017-09-18 16:19
@nullify005 I had a look at my unfinished PR, there was some race condition in there under heavy load, which I was out of ideas how to fix at that time. If you could try testing master branch + https://github.com/ninja-/salt/commit/3d7802b1d0e05f9ae148537db69449406b656b52 that would help a lot :) if installing a custom version from git isn't too much work for you :(

**Comment by nullify005** [comment] 2017-09-19 00:12
@ninja- thanks for getting back onto this!

Applying https://github.com/ninja-/salt/commit/3d7802b1d0e05f9ae148537db69449406b656b52 allows the states to execute with parallel: true, however any tasks which are executed and happen to have a require against the parallel state & take longer than say 20 seconds to run end up falling victim to an infinite recursion problem in check_requisite.

To demonstrate with a simple sls:
```
sleep 5:
    cmd.run:
        - name: sleep 5

sleep 60:
    cmd.run:
        - name: sleep 60
        - parallel: true
        - require:
            - cmd: sleep 5
        - require_in: {# or the require for the subsequent states #}
            - cmd: waited for sleep 60

sleep 120:
    cmd.run:
        - name: sleep 120
        - parallel: true
        - require:
            - cmd: sleep 5
        - require_in: {# or the require for the subsequent states #}
            - cmd: waited for sleep 120

waited for sleep 60:
    cmd.run:
        - name: echo waited for sleep 60
        #- require:
        #    - cmd: sleep 60

waited for sleep 120:
    cmd.run:
        - name: echo waited for sleep 120
        #- require:
        #    - cmd: sleep 120
```
results in:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "./bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "./lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "./lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "./lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "./lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "./lib/python2.7/site-packages/salt/modules/state.py", line 1109, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "./lib/python2.7/site-packages/salt/state.py", line 2515, in call_high
    ret = self.call_chunks(chunks)
  File "./lib/python2.7/site-packages/salt/state.py", line 2008, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "./lib/python2.7/site-packages/salt/state.py", line 2245, in call_chunk
    status, reqs = self.check_requisite(low, running, chunks, pre=True)
  File "./lib/python2.7/site-packages/salt/state.py", line 2148, in check_requisite
    return self.check_requisite(low, running, chunks, pre)
 (... LOTS AND LOTS AND LOTS AND LOTS AND LOTS AND LOTS OF THE ABOVE ...)
  File "./lib/python2.7/site-packages/salt/state.py", line 2148, in check_requisite
    return self.check_requisite(low, running, chunks, pre)
  File "./lib/python2.7/site-packages/salt/state.py", line 2088, in check_requisite
    self.reconcile_procs(running)
  File "./lib/python2.7/site-packages/salt/state.py", line 2040, in reconcile_procs
    if not proc.is_alive():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 158, in is_alive
    self._popen.poll()
RuntimeError: maximum recursion depth exceeded
```

If the parallel state runs quickly OR doesn't have anything which relies on it then the the RuntimeError doesn't happen.

So the original issue reported appears to be solved by your proposed patch.

Should I raise another issue regarding problems when you require a parallel state though?

**Comment by ninja-** [comment] 2017-09-19 00:15
@nullify005 which part of the stacktrace /exactly/ gets repeated until recursion error? is it check_requisite then reconcile_procs or something different?

**Comment by nullify005** [comment] 2017-09-19 00:26
It is
```
  File "./lib/python2.7/site-packages/salt/state.py", line 2149, in check_requisite
    return self.check_requisite(low, running, chunks, pre)
```
I've looked at https://github.com/saltstack/salt/issues/15171 which feels like it might be related but applying the merged PR directly into state.py doesn't seem to change the behaviour

**Comment by ninja-** [comment] 2017-09-29 16:50
@nullify005 I think that was fixed here ?? https://github.com/saltstack/salt/pull/42985

**Comment by nullify005** [comment] 2017-10-08 23:10
Hey @ninja- so I've merged https://github.com/saltstack/salt/pull/42985 by hand into 2017 so that parallel is still present & unfortunately it doesn't make a difference. Still the same issue

**Comment by nullify005** [comment] 2017-10-11 22:52
Looks like this https://github.com/saltstack/salt/issues/43668 is a duplicate of what I'm seeing

**Closed** 2018-04-12 18:59 UTC
Labels: Bug, Core, High Severity, P4
