### ISSUE TITLE
state.highstate does not refresh minion cache pillar data

### ISSUE THREAD

**Issue by hal58th** [saltstack/salt#24050] opened 2015-05-21 22:01 UTC
***NOTE:*** The original test steps do not work anymore because "salt-call" always gives you the latest data. But this still is broken when you run the pillar calls (pillar.item and pillar.get) from the master.

If you change pillar data, and then run state.highstate (via salt or salt-call), the pillar data will not be refreshed on the minion cache. It was my understanding that a state.highstate run should update pillar minion cache.

To test this, run "salt-call pillar.get key"
Change the value of that key.
Verify it has changed by running "salt-call pillar.item key"  (You use pillar.item because it will use a refreshed pillar value instead of cached item).
Run state.highstate any way you like.
Verify the minion cache has NOT been updated with "salt-call pillar.get key".
Run a "salt-call saltutil.refresh_pillar" to update minion pillar cache.
Verify the minion cache has now been successfully updated with "salt-call pillar.get key".

(To know the difference between pillar.get and pillar.item, please refer to this issue. https://github.com/saltstack/salt/issues/21765)

Tested in 2015.5.0 (Lithium)

**Comment by hal58th** [comment] 2015-05-21 22:22
For anyone else needing a temporary fix, this worked for me.

refresh_pillar:
  module.run:
    - name: saltutil.refresh_pillar
    - order: 1

**Comment by jfindlay** [comment] 2015-05-26 17:20
@hal58th, thanks for the report.

**Comment by DanyC97** [comment] 2015-08-09 05:55
hmmm, is this still present in latest release?

**Comment by icanhazpython** [comment] 2015-09-21 17:54
I can confirm that state.highstate is not refreshing cached pillar data even in 2015.8.0. saltutil.refresh_pillar does the trick though.

**Comment by hal58th** [comment] 2015-10-20 19:35
***NOTE:*** The original test steps do not work anymore because "salt-call" always gives you the latest data. But this still is broken when you run the pillar calls (pillar.item and pillar.get) from the master.

**Comment by dmcteer** [comment] 2015-10-30 14:47
I am also experiencing issues with this. If I run "salt-call pillar.get key", I get the most current value. If I pass "__salt__['pillar.get'](key)" in a custom module, I get cached data. Once I run a saltutil.refresh_pillar, the updated data is present, but it is not available until then.

**Comment by dmcteer** [comment] 2015-11-06 18:19
This may or may not be related, but, I have also noticed that external pillar data supplied through a Python script using the ext_pillar function:

https://docs.saltstack.com/en/latest/topics/development/external_pillars.html#ext-pillar

is being handled incorrectly. I am able to call the data from the master and the minions properly through the command line, but if I call this from a module, the behavior is inconsistent. This works properly from a module when executed on the master, but pillar.get from a custom module executed on a minion does not return any data.

**Comment by Grokzen** [comment] 2015-11-16 16:33
@dmcteer I can confirm that `__salt__['pillar.get'](key)` inside a module still returns cached data and `saltutil.refresh_pillar` do not update that. This was tested on 2015.5.6 and inside a custom module calling `__salt__['pillar.get'](key)`

**Comment by aabognah** [comment] 2015-12-15 15:30
Same here. using external pillars on git repo. saltutil.refresh_pillars does not refresh. Salt version 2015.8.1

**Comment by aabognah** [comment] 2015-12-15 16:05
updated master and minions to 2015.8.3. problem still persists.

**Comment by wt** [comment] 2015-12-23 18:00
This is a pretty awful bug. Is it really still broken?

**Comment by cachedout** [comment] 2015-12-23 18:02
Wow, yeah. I agree. This is a terrible bug. I don't recall a PR that addresses it specifically so it might well be. I am going to bump the severity up to critical, which is what it should have been originally. Good eye, @wt

**Comment by DmitryKuzmenko** [comment] 2016-02-18 17:00
In PR #31319 I've fixed the following:
* Properly initialize modules pillar data on minion start. Previously it was empty because minion was initializing modules before getting pillar from master so modules was initialized with an empty pillar dict. So now such requests like ```salt '*' pillar.get name``` and ```salt '*' pillar.item name``` don't return 'no key' response if executed right after minion start.
* Use the current (set on the minion) pillar environment in pillar.items call. Previously it was returning pillar data merged from all environments.

What about the initial request: according to [the doc](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pillar.html) pillar functions should work as the following:
1. pillar.get: use local pillar data already injected into the module
2. pillar.item: the same, use local
3. pillar.items: query master for the fresh pillar, return the fresh pillar, don't update the local data
4. saltutil.refresh_pillar: command minion to request fresh pillar from master and update it in modules

Now (with #31319) it works as described in the doc.
1 and 2 are lightweight ways to get the cached pillar data, 3 is more expensive but fetches the fresh data, 4 is more expensive that 3 because it also reloads modules.
As I can see the normal case should look like this: if master pillar data has been updated all related minions should be notified with ```refresh_pillar```.

And about the difference between ```salt-call``` and ```salt```: salt-call initializes it's own minion instance and gets pillar data from master on start. This is the reason it always uses the fresh pillar data.

@cachedout could you please confirm (or ping somebody else?) am I right here?

**Comment by thatch45** [comment] 2016-02-19 16:02
Thanks @DmitryKuzmenko ! Spot on in all cases!

**Comment by DmitryKuzmenko** [comment] 2016-02-19 17:15
@thatch45 thank you!
In this case I can declare: now (where the fixes are merged) Salt works as documented.
If anybody needs to update pillar on master side he needs to send refresh_pillar request to teh related minions.
If anybody has a case where you have a logic that needs to have frequently updated on-demand pillar data, please create a new issue with the detail description of your special case: either you do something wrong or we missed a special pillar request function.

**Closed** 2016-02-19 17:16 UTC
Labels: Bug, Core, Critical, P1, Pillar, TEAM Core

**Comment by DanyC97** [comment] 2016-02-22 09:38
@DmitryKuzmenko superb notes, thanks !!
