### ISSUE TITLE
Feature Request: Support for homebrew cask

### ISSUE THREAD

**Issue by fgimian** [saltstack/salt#24653] opened 2015-06-12 23:46 UTC
Hey there guys, hope you're doing well :smile: 

I was wondering if you would please consider supporting [homebrew-cask](https://github.com/caskroom/homebrew-cask) in the future?

This allows OS X users to install desktop applications via the CLI.  Ansible contains [support for it](http://docs.ansible.com/homebrew_cask_module.html) and it works rather well, but I'd really like to try Salt instead for automating the build of my Mac :smile: 

Thanks heaps and have a great weekend!
Fotis

**Comment by jtand** [comment] 2015-06-16 19:40
@fgimian Thank you for this feature idea.

**Comment by DavidJFelix** [comment] 2015-07-15 03:04
:+1: +1

**Comment by cliffrowley** [comment] 2015-11-30 20:01
Yes please! ;-)  I'm more than happy to help test (I am refactoring my home lab and looking at using saltstack to orchestrate my mini server and its virtual machines).

**Comment by fgimian** [comment] 2018-02-19 07:50
This would still be desirable if possible 😄

**Comment by weswhet** [comment] 2018-04-03 00:42
I believe this merged [PR](https://github.com/saltstack/salt/pull/45309) should bring support for cask installs. e.g. `caskroom/cask/opera`

**Comment by lmf-mx** [comment] 2019-04-30 06:06
#45309 adds some support for checking if a cask is installed. There are, however, a few outstanding issues.

1. caskroom/cask appears to be an alias/redirect from the migration of the repo to [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask). With cask becoming part of core, tapping caskroom/cask is no longer necessary. brew taps the repo as homebrew/cask.

2. caskroom/versions is also now located at [Homebrew/homebrew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions) and tapped as homebew/cask-versions. The check at https://github.com/saltstack/salt/commit/4aa3e234544cc9518ef9ae48a3270742c36b3841#diff-922c510bbabef7d622da0ff9dce6acd3R151 doesn't account for the casks in this repo.
 Installing a package such as vlc-nightly via homebrew/cask-versions/vlc-nightly or caskroom/versions/vlc-nightly will sucessfully install. The pkg.installed state will return as failed, since vlc-nightly will be returned as 'caskroom/cask/vlc-nightly'.

**Comment by cdalvaro** [comment] 2020-07-14 17:25
It is currently supported, just install your package specifying the full name: `homebrew/cask/visual-studio-code`

```sls
visual-studio-code:
  pkg.installed:
    - name: homebrew/cask/visual-studio-code
```

**Comment by gabeio** [comment] 2021-01-14 19:16
brew changed how to interface with casks:

```
[ERROR   ] The following packages failed to install/update: homebrew/cask/google-chrome
[ERROR   ] Command '['su', '-l', 'gabeio', '-c', 'cd -- /Users/gabeio && { /usr/local/bin/brew cask list --versions\n }']' failed with return code: 1
[ERROR   ] stderr: Error: Calling brew cask list is disabled! Use brew list [--cask] instead.
[ERROR   ] retcode: 1
```

**Comment by cdalvaro** [comment] 2021-01-14 19:18
> brew changed how to interface with casks:
> 
> ```
> [ERROR   ] The following packages failed to install/update: homebrew/cask/google-chrome
> [ERROR   ] Command '['su', '-l', 'gabeio', '-c', 'cd -- /Users/gabeio && { /usr/local/bin/brew cask list --versions\n }']' failed with return code: 1
> [ERROR   ] stderr: Error: Calling brew cask list is disabled! Use brew list [--cask] instead.
> [ERROR   ] retcode: 1
> ```
> 
> if anyone is interested in the brew version(s) I have:
> 
> ```
> $ brew --version
> Homebrew 2.7.4
> Homebrew/homebrew-core (git revision b36d1; last commit 2021-01-14)
> Homebrew/homebrew-cask (git revision 71a8b0; last commit 2021-01-15)
> ```
> 
> and salt version:
> 
> ```
> $ salt --version
> salt 3002.2
> ```

This have been solved in #58381

**Comment by gabeio** [comment] 2021-01-14 19:19
@cdalvaro do you know when that is going to get out onto salt?

**Comment by cdalvaro** [comment] 2021-01-14 19:22
> @cdalvaro thanks for the info! do you know when that is going to get out onto salt?

You are welcome! I know that it is planned to be release with the Aluminum version. But I don't know the release date yet.

**Comment by maneamarius** [comment] 2021-02-16 10:27
Hey guys, as of salt 3002.2, this doesn't work on Mac:

```
visual-studio-code:
  pkg.installed:
    - name: homebrew/cask/visual-studio-code
```

It just fails this way:

```
----------
          ID: vscode-installed
    Function: pkg.installed
        Name: homebrew/cask/visual-studio-code
      Result: False
     Comment: The following packages failed to install/update: homebrew/cask/visual-studio-code
     Started: 05:22:27.302660
    Duration: 5702.606 ms
     Changes:
```

Is there any way to make this work?

**Comment by cdalvaro** [comment] 2021-02-16 10:45
At the moment, if you have access to you salt-master files, you can add this file: [`mac_brew_pkg.py (04b62a5)`](https://github.com/saltstack/salt/blob/c2f7be7c8600597bc567ac74895338c63f637825/salt/modules/mac_brew_pkg.py) to your custom `_modules` directory in order to overwrite the bundled one:

```
pillar/
reactor/
salt/
  _modules/
    mac_brew_pkg.py
  _states/
  data/
```

and then sync your minion modules:

```sh
salt '*' saltutil.sync_modules
```

If you prefer, you can use this version of [`mac_brew_pkg.py (7129b5b)`](https://github.com/cdalvaro/salt/blob/7768b3766f91183c2512d3d72a2487b091c47d12/salt/modules/mac_brew_pkg.py), which is already merged into master, but not yet released.

**Comment by maneamarius** [comment] 2021-02-16 12:23
Thank you!
I tried that, and for some reason, it installs the package and fails the state:

`----------
          ID: p4v-installed
    Function: pkg.installed
        Name: homebrew/cask/p4v
      Result: False
     Comment: The following packages failed to install/update: homebrew/cask/p4v=21.1
     Started: 07:20:22.134855
    Duration: 20268.193 ms
     Changes:
              ----------
              homebrew/cask/p4v:
                  ----------
                  new:
                      21.1,2075061
                  old:
              p4v:
                  ----------
                  new:
                      21.1,2075061
                  old:`

and here's the code I used:

`p4v-installed:
  pkg.installed:
    - runas: {{ mac_user }}
    - name: homebrew/cask/p4v
    - version: {{ p4v_version }}
    - unless: brew list | grep p4v`

**Comment by cdalvaro** [comment] 2021-02-16 13:01
Could you try this instead (if you have used patch #59439)?

```
p4v-installed:
  pkg.installed:
    - name: p4v
```

or if you have used #58381, try using this one?

```
p4v-installed:
  pkg.installed:
    - name: homebrew/cask/p4v
```

`brew` won't update the cask if it is already installed so the `unless` condition is not necessary.

**Comment by maneamarius** [comment] 2021-02-16 18:10
I did not use any patches, I just used vanilla 3002.2
Which patch should I use? And how do I apply it? (I haven't done that before)
I think I should apply a patch which will be included in the next release, right?

thanks a lot,
Marius

**Comment by cdalvaro** [comment] 2021-02-16 18:33
#58381 and #59371 are already merged with master and should be available when Salt Aluminium version is released.

Download the `salt/modules/mac_brew_pkg.py` file from master ([link](https://raw.githubusercontent.com/saltstack/salt/master/salt/modules/mac_brew_pkg.py)) and put it inside `salt/_modules` directory in your salt-master host.

```
pillar/
  top.sls
salt/
  _modules/
    mac_brew_pkg.py
  top.sls
```

Then you have to sync all modules with your minions (`salt '*' saltutil.sync_modules`) and try your `p4v` formula this way:

```sls
p4v-installed:
  pkg.installed:
    - name: homebrew/cask/p4v
```

**Warning**: You must remember to delete this file when Salt 3003 is available to avoid freezing the module for future updates.

**Comment by maneamarius** [comment] 2021-02-16 18:49
I copied the file, did refresh modules, and I still get this error.
So it installs it, but returns with error for some reason.

`----------
          ID: p4v-installed
    Function: pkg.installed
        Name: homebrew/cask/p4v
      Result: False
     Comment: The following packages failed to install/update: homebrew/cask/p4v=21.1
     Started: 13:45:26.494591
    Duration: 25542.42 ms
     Changes:
              ----------
              homebrew/cask/p4v:
                  ----------
                  new:
                      21.1,2075061
                  old:

Summary for xyz
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  25.542 s`

**Comment by maneamarius** [comment] 2021-02-16 18:50
If I remove `runas` from my state, it doesn't run at all, I get this:

`----------
          ID: p4v-installed
    Function: pkg.installed
        Name: homebrew/cask/p4v
      Result: False
     Comment: Unable to run command '['brew', '--prefix']' with the context '{'cwd': '/var/root', 'shell': False, 'env': {'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PWD': '/', 'XPC_FLAGS': '0x0', 'XPC_SERVICE_NAME': 'com.saltstack.salt.minion', 'SHLVL': '0', 'LC_CTYPE': 'C', 'LC_NUMERIC': 'C', 'LC_TIME': 'C', 'LC_COLLATE': 'C', 'LC_MONETARY': 'C', 'LC_MESSAGES': 'C', 'LC_PAPER': 'C', 'LC_NAME': 'C', 'LC_ADDRESS': 'C', 'LC_TELEPHONE': 'C', 'LC_MEASUREMENT': 'C', 'LC_IDENTIFICATION': 'C', 'LANGUAGE': 'C'}, 'stdin': None, 'stdout': -1, 'stderr': -2, 'with_communicate': True, 'timeout': None, 'bg': False, 'close_fds': True}', reason: [Errno 2] No such file or directory: 'brew': 'brew'
     Started: 13:48:30.725950
    Duration: 18.479 ms
     Changes:`

**Comment by cdalvaro** [comment] 2021-02-16 18:51
I think the problem is that you are specifying the version of the app `homebrew/cask/p4v=21.1`, try without telling salt to install version 21.1

**Comment by maneamarius** [comment] 2021-02-16 18:52
yeah you are right, I just tried without version, and doesn't error out anymore.

I'd like to pin to specific version though, is there a way to do that?

**Comment by cdalvaro** [comment] 2021-02-16 18:55
I have never tried that feature. Not even directly with `brew`. I will try to test it as soon as possible.

**Comment by maneamarius** [comment] 2021-02-16 19:13
thanks a lot, I appreciate all your help so far!

**Comment by maneamarius** [comment] 2021-02-16 19:14
Just to note, that visual-studio-code brew package can be installed using cask and version.
But p4v package cannot be installed using the version, it errors out as described above.
Maybe it helps you in troubleshooting?

**Comment by cdalvaro** [comment] 2021-02-16 19:20
May be you need to specify the full p4v version: `21.1,2075061`

**Comment by maneamarius** [comment] 2021-02-16 19:53
I tried that as well, still didn't work :(

**Comment by cdalvaro** [comment] 2021-02-16 20:42
I'm not really sure, but it seems like casks cannot be pinned:

```sh
~
❯  brew pin visual-studio-code
Error: No available formula with the name "visual-studio-code".

~
❯  brew pin homebrew/cask/visual-studio-code
Error: No available formula with the name "homebrew/cask/visual-studio-code".

~
❯  brew list --pinned

~
❯  brew pin boost

~
❯  brew list --pinned
boost

~
❯  brew unpin boost

~
❯  brew list --pinned
```

**Comment by maneamarius** [comment] 2021-02-17 13:32
Yes, I think you are right, some casks offer the option to specify version, and some not.
It's a pity they don't follow same standard across..

**Closed** 2022-09-22 15:31 UTC
Labels: Feature, Platform, MacOS
