### ISSUE TITLE
salt-minion[8140]

### ISSUE THREAD

**Issue by Zayan1221** [saltstack/salt#62907] opened 2022-10-18 19:24 UTC
**Description**
AttributeError: 'dict' object has no attribute 'append'
Oct 18 14:19:40  salt-minion[8140]: [CRITICAL] The beacon errored:
Oct 18 14:19:40  salt-minion[8140]: Traceback (most recent call last):
Oct 18 14:19:40  salt-minion[8140]:   File "/usr/lib/python3.6/site-packages/salt/minion.py", line 2954, in handle_beacons
Oct 18 14:19:40  salt-minion[8140]:     beacons = self.process_beacons(self.functions)
Oct 18 14:19:40 salt-minion[8140]:   File "/usr/lib/python3.6/site-packages/salt/minion.py", line 517, in process_beacons
Oct 18 14:19:40  salt-minion[8140]:     b_conf, self.opts["grains"]
Oct 18 14:19:40  salt-minion[8140]:   File "/usr/lib/python3.6/site-packages/salt/beacons/__init__.py", line 74, in process
Oct 18 14:19:40  salt-minion[8140]:     b_config[mod].append({"_beacon_name": mod})
Oct 18 14:19:40  salt-minion[8140]: AttributeError: 'dict' object has no attribute 'append'

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine  - Yes
- [ ] VM (Virtualbox, KVM, etc. please specify) - Virtual Box
- [ ] VM running on a cloud service, please be explicit and add details - Not on Cloud, On Hypervisor
- [ ] container (Kubernetes, Docker, containerd, etc. please specify) - No
- [ ] or a combination, please be explicit - No
- [ ] jails if it is FreeBSD   - Dont know
- [ ] classic packaging  - Dont know
- [ ] onedir packaging  - Dont know 
- [ ] used bootstrap to install - Downloaded version

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
PASTE HERE
```
</details>

**Additional context**
<img width="654" alt="Capture" src="https://user-images.githubusercontent.com/65530039/196524950-a54e9df9-8011-4772-820c-3aa338455cf5.PNG">

**Comment by OrangeDog** [comment] 2022-10-19 09:48
You still (#62864) haven't provided the information requested by the template nor a descriptive title.

Regardless, this is a duplicate of #60838.

**Closed by OrangeDog** 2022-10-19 09:48 UTC
Labels: Bug, needs-triage
