### ISSUE TITLE
file.copy is not replacing destination file even with force: True in state.orchestrate

### ISSUE THREAD

**Issue by fportillo-daitan** [saltstack/salt#28780] opened 2015-11-11 18:25 UTC
file.copy is not replacing destination file even with force: True

Salt version report:

```
[root@daitan-dev-salt podmaster]# salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core

```

Dir /srv/salt/podmaster is file_roots for podmaster environment.

```
[root@daitan-dev-salt podmaster]# pwd
/srv/salt/podmaster
```

My state file:

```
[root@daitan-dev-salt podmaster]# cat moveconfigfile.sls 
move-config-file:
  file.copy:
    - name: {{ pillar['config_file_destination'] }}
    - source: {{ pillar['config_file_source'] }}
    - user: root
    - group: root
    - mode: '644'
```

When I run this state.orchestrate command:

```
[root@daitan-dev-salt podmaster]# salt-run state.orchestrate moveconfigfile saltenv=podmaster pillar="{'config_file_source':'/tmp/config_file.sls', 'config_file_destination': '/tmp/config_file_dest2.sls'}"
daitan-dev-salt_master:
----------
          ID: move-config-file
    Function: file.copy
        Name: /tmp/config_file_dest2.sls
      Result: True
     Comment: Copied "/tmp/config_file.sls" to "/tmp/config_file_dest2.sls"
     Started: 18:06:45.129049
    Duration: 5.971 ms
     Changes:   
              ----------
              /tmp/config_file_dest2.sls:
                  /tmp/config_file.sls

Summary for daitan-dev-salt_master
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   5.971 ms
[root@daitan-dev-salt podmaster]# ls -lhart /tmp/*.sls
-rw-r--r--. 1 root root 19 Nov 11 17:26 /tmp/config_file.sls
-rw-r--r--. 1 root root 19 Nov 11 17:32 /tmp/foo.sls
-rw-r--r--. 1 root root 19 Nov 11 17:33 /tmp/config_file_dest.sls
-rw-r--r--. 1 root root 19 Nov 11 18:06 /tmp/config_file_dest2.sls
[root@daitan-dev-salt podmaster]# 
```

I can see and verify that the file has been copied as expected. Great. Then after that I edit my moveconfigfile.sls state file, add **force: True** as stated in the docs (https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.copy) and change the **mode to '655'**. I expected the existing file to be replace because force: True,
and mode updated, but the file is not overridden and mode not updated:

```
[root@daitan-dev-salt podmaster]# vim moveconfigfile.sls 
[root@daitan-dev-salt podmaster]# cat moveconfigfile.sls 
move-config-file:
  file.copy:
    - name: {{ pillar['config_file_destination'] }}
    - source: {{ pillar['config_file_source'] }}
    - user: root
    - group: root
    - mode: '655'
    - force: True
[root@daitan-dev-salt podmaster]# salt-run state.orchestrate moveconfigfile saltenv=podmaster pillar="{'config_file_source':'/tmp/config_file.sls', 'config_file_destination': '/tmp/config_file_dest2.sls'}"
daitan-dev-salt_master:
----------
          ID: move-config-file
    Function: file.copy
        Name: /tmp/config_file_dest2.sls
      Result: True
     Comment: The target file "/tmp/config_file_dest2.sls" exists and will not be overwritten
     Started: 18:11:23.978100
    Duration: 5.66 ms
     Changes:   

Summary for daitan-dev-salt_master
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   5.660 ms
[root@daitan-dev-salt podmaster]# ls -lhart /tmp/*.sls
-rw-r--r--. 1 root root 19 Nov 11 17:26 /tmp/config_file.sls
-rw-r--r--. 1 root root 19 Nov 11 17:32 /tmp/foo.sls
-rw-r--r--. 1 root root 19 Nov 11 17:33 /tmp/config_file_dest.sls
-rw-r--r--. 1 root root 19 Nov 11 18:06 /tmp/config_file_dest2.sls
[root@daitan-dev-salt podmaster]#
```

Note that if I remove the destination file and run the command again, it copies the file with mode 655:

```
[root@daitan-dev-salt podmaster]# rm -f /tmp/config_file_dest2.sls
[root@daitan-dev-salt podmaster]# ls -lhart /tmp/*.sls
-rw-r--r--. 1 root root 19 Nov 11 17:26 /tmp/config_file.sls
-rw-r--r--. 1 root root 19 Nov 11 17:32 /tmp/foo.sls
-rw-r--r--. 1 root root 19 Nov 11 17:33 /tmp/config_file_dest.sls
[root@daitan-dev-salt podmaster]# salt-run state.orchestrate moveconfigfile saltenv=podmaster pillar="{'config_file_source':'/tmp/config_file.sls', 'config_file_destination': '/tmp/config_file_dest2.sls'}"
daitan-dev-salt_master:
----------
          ID: move-config-file
    Function: file.copy
        Name: /tmp/config_file_dest2.sls
      Result: True
     Comment: Copied "/tmp/config_file.sls" to "/tmp/config_file_dest2.sls"
     Started: 18:13:30.967885
    Duration: 10.691 ms
     Changes:   
              ----------
              /tmp/config_file_dest2.sls:
                  /tmp/config_file.sls
              mode:
                  0655

Summary for daitan-dev-salt_master
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  10.691 ms
[root@daitan-dev-salt podmaster]# ls -lhart /tmp/*.sls
-rw-r--r--. 1 root root 19 Nov 11 17:26 /tmp/config_file.sls
-rw-r--r--. 1 root root 19 Nov 11 17:32 /tmp/foo.sls
-rw-r--r--. 1 root root 19 Nov 11 17:33 /tmp/config_file_dest.sls
-rw-r-xr-x. 1 root root 19 Nov 11 18:13 /tmp/config_file_dest2.sls
[root@daitan-dev-salt podmaster]# 
```

Why **force: True** is not overriding the destination file with new mode? It seems to be a bug. BTW, key state is the following:

```
[root@daitan-dev-salt podmaster]# salt-key --list-all
Accepted Keys:
centos-minion-1
Denied Keys:
Unaccepted Keys:
daitan-dev-salt
Rejected Keys:
```

daitan-dev-salt is the master, against it the state.orchestrate command is run. Only one minion present, centos-minion-1.

Cheers.

**Comment by jfindlay** [comment] 2015-11-13 19:38
@fportillo-daitan, thanks for the report.

**Comment by fportillo-daitan** [comment] 2015-11-13 19:53
yrw

**Comment by rallytime** [comment] 2016-04-26 14:47
@fportillo-daitan I think this is likely a duplicate of #23714, which has been fixed at the current HEAD of all current release branches. For the 2015.8 branch, the PR fixing this is #32847. Are you in a position to test that fix and see if it is resolved for you?

**Comment by fportillo-daitan** [comment] 2016-04-26 16:04
Yes, it seems a duplicate. Unfortunately I'm not in a position to test this anymore. I think we managed with a workaround using `cmd.run`, sadly. :(

**Comment by rallytime** [comment] 2016-04-26 16:58
No problem. I'm going to close this as a duplicate so we can track the issue there. If you ever circle back around here and are still running into this issue, let us know. Thanks!

**Closed by rallytime** 2016-04-26 16:58 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P1, Platform, Regression, State Module
