### ISSUE TITLE
gitfs fails with pygit2 v0.27.4

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#51664] opened 2019-02-15 14:35 UTC
### Description of Issue/Question
Using gitfs with the lastest version of pygit2 (v0.27.4) causes a stack trace:

```
2019-02-14 23:55:45,939 [salt.master                              :448 ][ERROR   ][33914] Uncaught exception while updating gitfs fileserver cache
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/master.py", line 444, in _do_update
    update_func(*args)
  File "/usr/local/lib/python3.6/site-packages/salt/fileserver/gitfs.py", line 133, in update
    _gitfs().update(remotes)
  File "/usr/local/lib/python3.6/site-packages/salt/utils/gitfs.py", line 2412, in update
    self.find_file
  File "/usr/local/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 256, in reap_fileserver_cache_dir
    ret = find_func(filename, saltenv=saltenv)
  File "/usr/local/lib/python3.6/site-packages/salt/utils/gitfs.py", line 2755, in find_file
    blob, blob_hexsha, blob_mode = repo.find_file(repo_path, tgt_env)
  File "/usr/local/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1809, in find_file
    tree = self.get_tree(tgt_env)
  File "/usr/local/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1016, in get_tree
    candidate = func(tgt_ref)
  File "/usr/local/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1852, in get_tree_from_branch
    'refs/remotes/origin/{0}'.format(ref)).get_object().tree
AttributeError: '_pygit2.Reference' object has no attribute 'get_object'
```

According to the pygit2 [CHANGELOG](https://github.com/libgit2/pygit2/blob/master/CHANGELOG.rst), `Reference.get_object()` was deprecated in v0.21.4 (November, 2014), and removed entirely in v0.27.4 (January, 2019)

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.6.8 (default, Feb  8 2019, 21:14:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.2-STABLE
         system: FreeBSD
        version: Not Installed
```

**Comment by garethgreenaway** [comment] 2019-02-19 20:25
Duplicate of https://github.com/saltstack/salt/issues/51270 and fixed in https://github.com/saltstack/salt/pull/51304

**Closed** 2020-01-13 20:26 UTC
Labels: Bug, Duplicate, High Severity, P2
