### ISSUE TITLE
Service module doesn't recognize OpenSuSE

### ISSUE THREAD

**Issue by eckardclemson** [saltstack/salt#46154] opened 2018-02-22 22:18 UTC
### Description of Issue/Question
When I use the `service` module or state, my brand-new OpenSuSE version Leap 42.3 is not recognized as a SuSE variant.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
$ cat /srv/salt/salt/minion.sls
{% from "salt/map.jinja" import at, pkg with context %}

{{sls}} - Install salt-minion pkg:
  pkg.installed:
    - name: {{pkg.minion}}
    - refresh: True

{{sls}} - Ensure salt-minion service is running:
  service.running:
    - name: salt-minion
    - enable: True
    - require:
      - {{sls}} - Install salt-minion pkg

{{sls}} - Install 'at' package:
  pkg.installed:
    - name: {{at.pkg}}
    - refresh: True

{{sls}} - Enable 'at' daemon:
  service.running:
    - name: {{at.daemon}}
    - enable: True
    - watch:
      - {{sls}} - Install 'at' package
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Output of above state:
```
$ sudo salt-ssh vdi state.sls salt.minion test=t
vdi:
----------
          ID: salt.minion - Install salt-minion pkg
    Function: pkg.installed
        Name: salt-minion
      Result: True
     Comment: All specified packages are already installed
     Started: 16:51:42.793176
    Duration: 418.764 ms
     Changes:
----------
          ID: salt.minion - Ensure salt-minion service is running
    Function: service.running
        Name: salt-minion
      Result: False
     Comment: State 'service.running' was not found in SLS 'salt.minion'
              Reason: 'service' __virtual__ returned False: No service execution module loaded: check support for service management on Leap-42
     Changes:
----------
          ID: salt.minion - Install 'at' package
    Function: pkg.installed
        Name: at
      Result: True
     Comment: All specified packages are already installed
     Started: 16:51:44.134715
    Duration: 15.775 ms
     Changes:
----------
          ID: salt.minion - Enable 'at' daemon
    Function: service.running
        Name: atd
      Result: False
     Comment: State 'service.running' was not found in SLS 'salt.minion'
              Reason: 'service' __virtual__ returned False: No service execution module loaded: check support for service management on Leap-42
     Changes:

Summary for vdi
------------
Succeeded: 3
Failed:    2
------------
Total states run:     5
Total run time: 449.165 ms
```
Similar failure when using `service` module:
```
$ sudo salt-ssh vdi servic
e.status salt-minion
vdi:
    ----------
    retcode:
        0
    stderr:
        'service' __virtual__ returned False: Your OS is on the disabled list
    stdout:
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
"Master" (Fedora 26 on bare metal):
```
$ sudo salt-ssh --versions-report
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Dec 11 2017, 16:08:01)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: fedora 26 Twenty Six
         locale: UTF-8
        machine: x86_64
        release: 4.11.11-300.fc26.x86_64
         system: Linux
        version: Fedora 26 Twenty Six
```
Minion (OpenSuSE Leap-42 on Windows 10 WSL on Citrix VDI XenServer):
```$ sudo salt-ssh vdi cmd.run 'salt-call --versions-report'
vdi:
    Salt Version:
               Salt: 2017.7.2

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.2.2

    System Versions:
               dist: SuSE 42.3 x86_64
             locale: ANSI_X3.4-1968
            machine: x86_64
            release: 4.4.0-43-Microsoft
             system: Linux
            version: openSUSE  42.3 x86_64
```
Grains on minion:
```
$ sudo salt-ssh vdi grains.items
vdi:
    ----------
    cpuarch:
        x86_64
    gpus:
    groupname:
        root
    id:
        vdi
    init:
        unknown
    kernel:
        Linux
    kernelrelease:
        4.4.0-43-Microsoft
    locale_info:
        ----------
        defaultencoding:
            UTF-8
        defaultlanguage:
            en_US
        detectedencoding:
            UTF-8
    lsb_distrib_codename:
        openSUSE Leap 42.3
    lsb_distrib_id:
        openSUSE Leap
    lsb_distrib_release:
        42.3
    master:
        salt
    mem_total:
        8183
    num_cpus:
        4
    num_gpus:
        0
    os:
        SUSE
    os_family:
        Suse
    osarch:
        x86_64
    oscodename:
        openSUSE Leap 42.3
    osfinger:
        Leap-42
    osfullname:
        Leap
    osmajorrelease:
        42
    osrelease:
        42.3
    osrelease_info:
        - 42
        - 3
    path:
        /sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/usr/local/bin
    pid:
        2027
    ps:
        ps -efHww
    pythonexecutable:
        /usr/bin/python2.7
    pythonpath:
        - /var/tmp/.root_44845a_salt/py2
        - /var/tmp/.root_44845a_salt
        - /usr/lib/python27.zip
        - /usr/lib64/python2.7
        - /usr/lib64/python2.7/plat-linux2
        - /usr/lib64/python2.7/lib-tk
        - /usr/lib64/python2.7/lib-old
        - /usr/lib64/python2.7/lib-dynload
        - /usr/lib64/python2.7/site-packages
        - /usr/local/lib64/python2.7/site-packages
        - /usr/local/lib/python2.7/site-packages
        - /usr/lib/python2.7/site-packages
    pythonversion:
        - 2
        - 7
        - 13
        - final
        - 0
    saltpath:
        /var/tmp/.root_44845a_salt/py2/salt
    saltversion:
        2017.7.3
    saltversioninfo:
        - 2017
        - 7
        - 3
        - 0
    shell:
        /bin/bash
    systemd:
        ----------
        version:
            228
    uid:
        0
    username:
        root
    virtual:
        VirtualPC
    zmqversion:
        4.2.2
```

**Comment by gtmanfred** [comment] 2018-02-22 23:00
How are you virtualizing this?

```
            release: 4.4.0-43-Microsoft
```

I see that the kernel is listed as Microsoft? is this running in a docker container?

The problem is that your init system grain is unknown.

```
    init:
        unknown
```

If you are running this in docker, or in a chroot or bsd jail like thing, you have to make sure you actually execute an init system inside of the container, otherwise salt cannot manage services using the init system.

Daniel

**Comment by chruck** [comment] 2018-02-23 02:37
Well now, that's a good point.  I think it's SystemD, but:
```$ sudo service --status-all
[sudo] password for root:
                                                                     unknown
$ sudo systemctl -a
Failed to connect to bus: No such file or directory
$ sudo service salt-minion status
service: no such service salt-minion
$ sudo rpm -ql salt-minion
/etc/salt/minion
/etc/salt/minion.d
/etc/salt/minion_id
/etc/salt/pki/minion
/usr/bin/salt-minion
/usr/lib/systemd/system/salt-minion.service
/usr/lib/zypp/plugins/commit/zyppnotify
/usr/sbin/rcsalt-minion
/usr/share/man/man1/salt-minion.1.gz
/var/cache/salt/minion
```
This is an OpenSuSE "package" on Windows 10 under the Windows Subsystem for Linux (WSL).  Think of it like WINE in reverse, although it's closer to FreeBSD's Linux compatibility layer.  And I think Docker on Windows is using HyperV (?) so that's really like a VM (so not really a container after all!).  This is my first effort with WSL, so it seems still in beta.  I'll use `salt-ssh` instead of running a minion process and close this ticket.

Thank you, @gtmanfred !

**Comment by gtmanfred** [comment] 2018-02-23 14:00
Yeah, so that is not a real linux installation, so the init system is not systemd, it just captures the syscalls and converts them to syscalls for the windows nt kernel.

You won't be able to use salt-ssh to connect into that instance either.  Since the system is actually a windows machine, if you want to control services, you will need to install the salt-minion windows package.

http://repo.saltstack.com/#windows

Thanks,
Daniel

**Closed by gtmanfred** 2018-02-23 14:00 UTC
Labels: Info Needed
