### ISSUE TITLE
2015.2.0rc1: parameter "outputter" not working for salt-run

### ISSUE THREAD

**Issue by dennisjac** [saltstack/salt#20634] opened 2015-02-12 17:04 UTC
According to the current documentation it should be possible to set an outputter for salt-run commands. However when I add "outputter=yaml" to the command line like shown in the example in the documentation the output format doesn't change instead the result get the following appended:

outputter:
    yaml

**Comment by rallytime** [comment] 2015-02-12 17:36
@dennisjac Thanks for the report! Is this happening with a specific command, or with anything that you've tried with `salt-run` and `outputter=xxxx`? Were you seeing this behavior work in a previous release?

**Comment by dennisjac** [comment] 2015-02-12 20:49
I tried jobs.print_job and jobs.lookup_jid and the behavior is the same in both cases.
According to the documentation this parameter was not available before ("New in version Lithium.") and the idea behind upgrading to 2015.2.0rc1 was specifically to make use of this new parameter to monitor and log the job runs.

**Comment by dennisjac** [comment] 2015-02-13 01:49
I just looked at the code and found this:
```
    if outputter:
        return {'outputter': outputter, 'data': ret}
    else:
        return ret
```
This makes no sense and certainly doesn't match the documentation.

**Comment by rallytime** [comment] 2015-02-13 04:09
Yeah good call. Thanks for testing this out and letting us know! You've found the right place to start fixing. We'd happily accept a pull request if you want to give it a try. No worries if not though, as we can take a look as well.

**Comment by dennisjac** [comment] 2015-02-13 05:32
After looking into this more the code above actually makes more sense but the data needs to be interpreted correctly elsewhere but I have no idea how to fix this.

**Comment by rallytime** [comment] 2015-02-13 14:38
Ok, no problem. Thanks for taking a look!

**Comment by whiteinge** [comment] 2015-02-14 22:41
I can duplicate this on 2015.2.

**Comment by dennisjac** [comment] 2015-02-24 12:30
I actually managed to fix this but now I'm not sure how to contribute this? Should I create a PR for develop and this will be merged into 2015.2 on your end or should I create two independent PRs?

**Comment by dennisjac** [comment] 2015-02-24 12:53
Never mind. I just looked at the develop branch at this apparently has already been fixed. The fix seems to be incorrect though:
```
            if isinstance(event['return'], dict):
                outputter = event['return'].pop('outputter', None)
            else:
                outputter = None
            salt.output.display_output(event['return'], outputter, self.opts)
```
Isn't event['return'] always a dict? And if it wasn't wouldn't that code result in two different outputs depending on outputter being provided or not? ("<data>" in one case and "{'data':<data>}" in the other)

**Comment by rallytime** [comment] 2015-02-24 15:43
@dennisjac Thanks for investigating! As for your first comment, whenever you're doing bugfixes you should make the fix against the earliest support branch that has the bug. We merge the older release branches forward into the newer branches (i.e. 2014.7 --> 2015.2, then 2015.2 --> develop) so the fix will occur in all places necessary. You can find more info about that here: http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch and we are of course happy to answer any questions about that.

For your second question, I think you might have a point. @cachedout - Looks like this was your change. Mind taking a look and commenting about the question above?

**Comment by ckochenower** [comment] 2015-03-07 03:14
I am unable to reproduce this problem:

```
root@saltmaster:~# salt-run --version
salt-run 2015.2.0rc1-705-gd64c109 (Lithium)
root@saltmaster:~# salt-run jobs.list_job 20150307025503854882 outputter=yaml
[ERROR   ] Error loading runners.nacl: libnacl import error, perhaps missing python libnacl package
data:
    ----------
    Arguments:
    Function:
        test.ping
    Minions:
        - master_minion
        - minion1
        - minion3
        - minion2
    Result:
        ----------
        master_minion:
            ----------
            return:
                True
        minion1:
            ----------
            return:
                True
        minion2:
            ----------
            return:
                True
        minion3:
            ----------
            return:
                True
    StartTime:
        2015, Mar 07 02:55:03.854882
    Target:
        *
    Target-type:
        glob
    User:
        root
    jid:
        20150307025503854882
outputter:
    yaml
```

**Comment by terminalmage** [comment] 2015-03-10 20:35
#21454 was initially opened to fix this, but this turned out not to be the right fix. I opened #21463 and #21512, which resolve this. Note that this pull request deprecates the "outputter" argument as it is now redundant. This is because, as of the 2015.2 branch, the outputter is passed in the event return data.

Be advised that these fixes will need to be merged forward to be reflected in develop, they currently only exist in the 2015.2 branch

**Comment by rallytime** [comment] 2015-03-11 21:29
I have tested this and confirmed that it is indeed fixed.

**Closed by rallytime** 2015-03-11 21:29 UTC
Labels: Blocker, Bug, Confirmed, Fixed Pending Verification
