### ISSUE TITLE
Amazon Linux 15.03 with EPEL6 package broken when writing plugin for use with collectd

### ISSUE THREAD

**Issue by wt** [saltstack/salt#22544] opened 2015-04-10 21:57 UTC
The Amazon LInux 15.03 release made major changes to how python works. It now uses python2.7 by default. They also provide a collectd package with a python plugin module that links against python2.7. Of course, this means that writing any plugins that use the salt modules don't work since they are only available in python2.6 on Amazon Linux. Is there any way that the EPEL6 package can be installed in a location that can be used by either python2.6 or python2.7?

**Comment by lorengordon** [comment] 2015-04-12 17:05
Guessing this is related to https://github.com/saltstack/salt/issues/22003...

**Comment by rallytime** [comment] 2015-04-13 17:39
Yes, this is a duplicate of #220003. @wt I am going to close this in favor of the earlier issue, which has lots of discussion on the matter. Thanks!

**Closed by rallytime** 2015-04-13 17:39 UTC
Labels: Duplicate

**Comment by wt** [comment] 2015-04-16 22:49
In case anyone stumbles upon this issue, here's the correct issue number: #22003

**Comment by rallytime** [comment] 2015-04-16 23:09
Heh, whoops! I had one too many zeros there. Thanks!
