### ISSUE TITLE
Error in iptables module: argument --match-set: expected 2 argument(s)

### ISSUE THREAD

**Issue by falzm** [saltstack/salt#23643] opened 2015-05-13 09:32 UTC
Hello

When upgrading from 2014.7.5. to 2015.5.0, my `iptables` states fail on the rules using `match-set` keyword:

```
# salt-call state.sls iptables
usage: salt-call [-h] [-A APPEND] [-D DELETE] [-I INSERT] [-R REPLACE]
                 [-L LIST] [-F FLUSH] [-Z ZERO] [-N NEW-CHAIN]
                 [-X DELETE-CHAIN] [-P POLICY] [-E RENAME-CHAIN] [-p PROTOCOL]
                 [-s SOURCE] [-d DESTINATION] [-j JUMP] [-g GOTO]
                 [-i IN-INTERFACE] [-o OUT-INTERFACE] [-f FRAGMENT]
                 [-c SET-COUNTERS] [-m MATCH] [--src-type SRC-TYPE]
                 [--dst-type DST-TYPE] [--limit-iface-in LIMIT-IFACE-IN]
                 [--limit-iface-out LIMIT-IFACE-OUT] [--ahspi AHSPI]
                 [--ahlen AHLEN] [--ahres AHRES] [--bytecode BYTECODE]
                 [--cluster-total-nodes CLUSTER-TOTAL-NODES]
                 [--cluster-local-node CLUSTER-LOCAL-NODE]
                 [--cluster-local-nodemask CLUSTER-LOCAL-NODEMASK]
                 [--cluster-hash-seed CLUSTER-HASH-SEED] [--h-length H-LENGTH]
                 [--mangle-mac-s MANGLE-MAC-S] [--mangle-mac-d MANGLE-MAC-D]
                 [--comment COMMENT] [--connbytes CONNBYTES]
                 [--connbytes-dir CONNBYTES-DIR]
                 [--connbytes-mode CONNBYTES-MODE] [--label LABEL]
                 [--connlimit-upto CONNLIMIT-UPTO]
                 [--connlimit-above CONNLIMIT-ABOVE]
                 [--connlimit-mask CONNLIMIT-MASK]
                 [--connlimit-saddr CONNLIMIT-SADDR]
                 [--connlimit-daddr CONNLIMIT-DADDR] [--mark MARK]
                 [--ctstate CTSTATE] [--ctproto CTPROTO]
                 [--ctorigsrc CTORIGSRC] [--ctorigdst CTORIGDST]
                 [--ctreplsrc CTREPLSRC] [--ctrepldst CTREPLDST]
                 [--ctorigsrcport CTORIGSRCPORT]
                 [--ctorigdstport CTORIGDSTPORT]
                 [--ctreplsrcport CTREPLSRCPORT]
                 [--ctrepldstport CTREPLDSTPORT] [--ctstatus CTSTATUS]
                 [--ctexpire CTEXPIRE] [--ctdir CTDIR] [--cpu CPU]
                 [--sport SOURCE_PORT] [--dport DESTINATION_PORT]
                 [--dccp-types DCCP-TYPES] [--dccp-option DCCP-OPTION]
                 [--src-group SRC-GROUP] [--dst-group DST-GROUP] [--dscp DSCP]
                 [--dscp-class DSCP-CLASS] [--dst-len DST-LEN]
                 [--dst-opts DST-OPTS] [--ecn-tcp-cwr ECN-TCP-CWR]
                 [--ecn-tcp-ece ECN-TCP-ECE] [--ecn-ip-ect ECN-IP-ECT]
                 [--espspi ESPSPI] [--fragid FRAGID] [--fraglen FRAGLEN]
                 [--fragres FRAGRES] [--fragfirst FRAGFIRST]
                 [--fragmore FRAGMORE] [--fraglast FRAGLAST]
                 [--hashlimit-upto HASHLIMIT-UPTO]
                 [--hashlimit-above HASHLIMIT-ABOVE]
                 [--hashlimit-burst HASHLIMIT-BURST]
                 [--hashlimit-mode HASHLIMIT-MODE]
                 [--hashlimit-srcmask HASHLIMIT-SRCMASK]
                 [--hashlimit-dstmask HASHLIMIT-DSTMASK]
                 [--hashlimit-name HASHLIMIT-NAME]
                 [--hashlimit-htable-size HASHLIMIT-HTABLE-SIZE]
                 [--hashlimit-htable-max HASHLIMIT-HTABLE-MAX]
                 [--hashlimit-htable-expire HASHLIMIT-HTABLE-EXPIRE]
                 [--hashlimit-htable-gcinterval HASHLIMIT-HTABLE-GCINTERVAL]
                 [--hbh-len HBH-LEN] [--hbh-opts HBH-OPTS] [--helper HELPER]
                 [--hl-eq HL-EQ] [--hl-lt HL-LT] [--hl-gt HL-GT]
                 [--icmp-type ICMP-TYPE] [--icmpv6-type ICMPV6-TYPE]
                 [--src-range SRC-RANGE] [--dst-range DST-RANGE] [--soft SOFT]
                 [--header HEADER] [--ipvs IPVS] [--vproto VPROTO]
                 [--vaddr VADDR] [--vport VPORT] [--vdir VDIR]
                 [--vmethod VMETHOD] [--vportctl VPORTCTL] [--length LENGTH]
                 [--limit LIMIT] [--limit-burst LIMIT-BURST]
                 [--mac-source MAC-SOURCE] [--mh-type MH-TYPE]
                 [--sports SOURCE-PORTS] [--dports DESTINATION-PORTS]
                 [--ports PORTS] [--nfacct-name NFACCT-NAME] [--genre GENRE]
                 [--ttl TTL] [--log LOG] [--uid-owner UID-OWNER]
                 [--gid-owner GID-OWNER] [--socket-exists SOCKET-EXISTS]
                 [--physdev-in PHYSDEV-IN] [--physdev-out PHYSDEV-OUT]
                 [--physdev-is-in PHYSDEV-IS-IN]
                 [--physdev-is-out PHYSDEV-IS-OUT]
                 [--physdev-is-bridged PHYSDEV-IS-BRIDGED]
                 [--pkt-type PKT-TYPE] [--dir DIR] [--pol POL]
                 [--strict STRICT] [--reqid REQID] [--spi SPI] [--proto PROTO]
                 [--mode MODE] [--tunnel-src TUNNEL-SRC]
                 [--tunnel-dst TUNNEL-DST] [--next NEXT] [--quota QUOTA]
                 [--rateest RATEEST] [--rateest1 RATEEST1]
                 [--rateest2 RATEEST2] [--rateest-delta RATEEST-DELTA]
                 [--rateest-bps RATEEST-BPS] [--rateest-bps1 RATEEST-BPS1]
                 [--rateest-bps2 RATEEST-BPS2] [--rateest-pps RATEEST-PPS]
                 [--rateest-pps1 RATEEST-PPS1] [--rateest-pps2 RATEEST-PPS2]
                 [--rateest-lt RATEEST-LT] [--rateest-gt RATEEST-GT]
                 [--rateest-eq RATEEST-EQ] [--rateest-name RATEEST-NAME]
                 [--rateest-interval RATEEST-INTERVAL]
                 [--rateest-ewma RATEEST-EWMA] [--realm REALM] [--name NAME]
                 [--set SET] [--rsource RSOURCE] [--rdest RDEST] [--mask MASK]
                 [--rcheck RCHECK] [--update UPDATE] [--remove REMOVE]
                 [--seconds SECONDS] [--reap REAP] [--hitcount HITCOUNT]
                 [--rttl RTTL] [--loose LOOSE] [--validmark VALIDMARK]
                 [--accept-local ACCEPT-LOCAL] [--invert INVERT]
                 [--rt-type RT-TYPE] [--rt-segsleft RT-SEGSLEFT]
                 [--rt-len RT-LEN] [--rt-0-res RT-0-RES]
                 [--rt-0-addrs RT-0-ADDRS] [--rt-0-not-strict RT-0-NOT-STRICT]
                 [--chunk-types CHUNK-TYPES] [--match-set MATCH-SET MATCH-SET]
                 [--return-nomatch RETURN-NOMATCH]
                 [--update-counters UPDATE-COUNTERS]
                 [--update-subcounters UPDATE-SUBCOUNTERS]
                 [--packets-eq PACKETS-EQ] [--packets-lt PACKETS-LT]
                 [--packets-gt PACKETS-GT] [--bytes-eq BYTES-EQ]
                 [--bytes-lt BYTES-LT] [--bytes-gt BYTES-GT]
                 [--transparent TRANSPARENT] [--nowildcard NOWILDCARD]
                 [--state STATE] [--probability PROBABILITY] [--every EVERY]
                 [--packet PACKET] [--algo ALGO] [--from FROM] [--to TO]
                 [--string STRING] [--hex-string HEX-STRING]
                 [--tcp-flags TCP-FLAGS] [--syn SYN] [--tcp-option TCP-OPTION]
                 [--mss MSS] [--datestart DATESTART] [--datestop DATESTOP]
                 [--timestart TIMESTART] [--timestop TIMESTOP]
                 [--monthdays MONTHDAYS] [--weekdays WEEKDAYS]
                 [--contiguous CONTIGUOUS] [--kerneltz KERNELTZ] [--utc UTC]
                 [--localtz LOCALTZ] [--tos TOS] [--ttl-eq TTL-EQ]
                 [--ttl-gt TTL-GT] [--ttl-lt TTL-LT] [--u32 U32]
                 [--condition CONDITION] [--mac MAC]
                 [--lower-limit LOWER-LIMIT] [--upper-limit UPPER-LIMIT]
                 [--src-cc SOURCE-COUNTRY] [--dst-cc DESTINATION-COUNTRY]
                 [--enabled ENABLED] [--disabled DISABLED] [--iface IFACE]
                 [--dev-in DEV-IN] [--dev-out DEV-OUT] [--up UP] [--down DOWN]
                 [--broadcast BROADCAST] [--loopback LOOPBACK]
                 [--pointtopoint POINTTOPOINT] [--running RUNNING]
                 [--noarp NOARP] [--arp ARP] [--promisc PROMISC]
                 [--multicast MULTICAST] [--dynamic DYNAMIC]
                 [--lower-up LOWER-UP] [--dormant DORMANT] [--edk EDK]
                 [--kazaa KAZAA] [--gnu GNU] [--dc DC] [--bit BIT]
                 [--apple APPLE] [--soul SOUL] [--winmx WINMX] [--ares ARES]
                 [--debug DEBUG] [--flags FLAGS] [--any ANY] [--layer3 LAYER3]
                 [--layer4 LAYER4] [--layer5 LAYER5] [--stealth STEALTH]
                 [--synscan SYNSCAN] [--cnscan CNSCAN] [--grscan GRSCAN]
                 [--psd-weight-threshold PSD-WEIGHT-THRESHOLD]
                 [--psd-delay-threshold PSD-DELAY-THRESHOLD]
                 [--psd-lo-ports-weight PSD-LO-PORTS-WEIGHT]
                 [--psd-hi-ports-weight PSD-HI-PORTS-WEIGHT] [--grow GROW]
                 [--no-change NO-CHANGE] [--packets PACKETS]
                 [--knockports KNOCKPORTS] [--time TIME]
                 [--autoclose AUTOCLOSE] [--checkip CHECKIP] [--type TYPE]
                 [--checksum-fill CHECKSUM-FILL] [--set-class SET-CLASS]
                 [--new NEW] [--hashmode HASHMODE] [--clustermac CLUSTERMAC]
                 [--total-nodes TOTAL-NODES] [--local-node LOCAL-NODE]
                 [--hash-init HASH-INIT] [--set-xmark SET-XMARK]
                 [--save-mark SAVE-MARK] [--restore-mark RESTORE-MARK]
                 [--and-mark AND-MARK] [--or-mark OR-MARK]
                 [--xor-mark XOR-MARK] [--set-mark SET-MARK] [--save SAVE]
                 [--restore RESTORE] [--notrack NOTRACK] [--ctevents CTEVENTS]
                 [--expevents EXPEVENTS] [--zone ZONE] [--timeout TIMEOUT]
                 [--to-destination TO-DESTINATION] [--random RANDOM]
                 [--persistent PERSISTENT] [--src-pfx SRC-PFX]
                 [--dst-pfx DST-PFX] [--set-dscp SET-DSCP]
                 [--set-dscp-class SET-DSCP-CLASS]
                 [--ecn-tcp-remove ECN-TCP-REMOVE] [--hl-set HL-SET]
                 [--hl-dec HL-DEC] [--hl-inc HL-INC]
                 [--hmark-tuple HMARK-TUPLE] [--hmark-mod HMARK-MOD]
                 [--hmark-offset HMARK-OFFSET]
                 [--hmark-src-prefix HMARK-SRC-PREFIX]
                 [--hmark-dst-prefix HMARK-DST-PREFIX]
                 [--hmark-sport-mask HMARK-SPORT-MASK]
                 [--hmark-dport-mask HMARK-DPORT-MASK]
                 [--hmark-spi-mask HMARK-SPI-MASK]
                 [--hmark-proto-mask HMARK-PROTO-MASK] [--hmark-rnd HMARK-RND]
                 [--led-trigger-id LED-TRIGGER-ID] [--led-delay LED-DELAY]
                 [--led-always-blink LED-ALWAYS-BLINK] [--log-level LOG-LEVEL]
                 [--log-prefix LOG-PREFIX]
                 [--log-tcp-sequence LOG-TCP-SEQUENCE]
                 [--log-tcp-options LOG-TCP-OPTIONS]
                 [--log-ip-options LOG-IP-OPTIONS] [--log-uid LOG-UID]
                 [--to-ports TO-PORTS] [--nflog-group NFLOG-GROUP]
                 [--nflog-prefix NFLOG-PREFIX] [--nflog-range NFLOG-RANGE]
                 [--nflog-threshold NFLOG-THRESHOLD] [--queue-num QUEUE-NUM]
                 [--queue-balance QUEUE-BALANCE] [--queue-bypass QUEUE-BYPASS]
                 [--queue-cpu-fanout QUEUE-CPU-FANOUT]
                 [--rateest-ewmalog RATEEST-EWMALOG]
                 [--reject-with REJECT-WITH] [--nodst NODST] [--selctx SELCTX]
                 [--add-set ADD-SET] [--del-set DEL-SET] [--exist EXIST]
                 [--to-source TO-SOURCE] [--set-mss SET-MSS]
                 [--clamp-mss-to-pmtu CLAMP-MSS-TO-PMTU]
                 [--strip-options STRIP-OPTIONS] [--gateway GATEWAY]
                 [--set-tos SET-TOS] [--and-tos AND-TOS] [--or-tos OR-TOS]
                 [--xor-tos XOR-TOS] [--on-port ON-PORT] [--on-ip ON-IP]
                 [--tproxy-mark TPROXY-MARK] [--ttl-set TTL-SET]
                 [--ttl-dec TTL-DEC] [--ttl-inc TTL-INC]
                 [--ulog-nlgroup ULOG-NLGROUP] [--ulog-prefix ULOG-PREFIX]
                 [--ulog-cprange ULOG-CPRANGE]
                 [--ulog-qthreshold ULOG-QTHRESHOLD] [--addr ADDR]
                 [--tname TNAME] [--delude DELUDE] [--tarpit TARPIT]
                 [--set-mac SET-MAC] [--prefix PREFIX] [--reuse REUSE]
                 [--static STATIC] [--and-mask AND-MASK] [--or-mask OR-MASK]
                 [--shift SHIFT] [--honeypot HONEYPOT] [--reset RESET]
salt-call: error: argument --match-set: expected 2 argument(s)
```

Rules in the rule set triggering this error are:

```yaml
...
    -
      name: filter_accept_in_whitelisted_ssh
      table: filter
      chain: INPUT
      match: set
      match-set: whitelisted src
      proto: tcp
      dport: ssh
      jump: ACCEPT
    -
      name: filter_accept_in_whitelisted_http
      table: filter
      chain: INPUT
      match: set
      match-set: whitelisted src
      proto: tcp
      dport: http
      jump: ACCEPT
```
I don't have this error in 2014.7.5.

Let me know if you need me to provide more details.

**Comment by jfindlay** [comment] 2015-05-14 15:16
@falzm, thanks for the report.  I think this should be enough information for now.

**Comment by falzm** [comment] 2015-07-17 13:09
Hi

Any idea if this could be fixed any time soon? It prevents me from upgrading Salt to 2015.* branch...

**Comment by jfindlay** [comment] 2015-07-17 16:48
@thusoy, @tankywoo, do you have any ideas?  Thanks.

**Comment by tankywoo** [comment] 2015-07-18 12:30
@jfindlay hi, link to my previous pr #24595 , @thusoy have summarize some plans: https://github.com/saltstack/salt/pull/24595#issuecomment-111798250

>  Least effort is probably 3., so maybe do that for now (with tests!), and have a long-term plan of moving to python-iptables?

for now, first, add test case and  maybe revert to the commit in previous version?

**Comment by tankywoo** [comment] 2015-07-18 12:31
@jfindlay hi, link to my previous pr #24595 , @thusoy have summarize some plans: https://github.com/saltstack/salt/pull/24595#issuecomment-111798250

>  Least effort is probably 3., so maybe do that for now (with tests!), and have a long-term plan of moving to python-iptables?

for now, first, add test case and maybe revert to the commit in previous version?

**Comment by tankywoo** [comment] 2015-07-18 12:31
@jfindlay hi, link to my previous pr #24595 , @thusoy have summarize some plans: https://github.com/saltstack/salt/pull/24595#issuecomment-111798250

>  Least effort is probably 3., so maybe do that for now (with tests!), and have a long-term plan of moving to python-iptables?

for now, first, add test case and maybe revert to the commit in previous version?

**Comment by jfindlay** [comment] 2015-07-18 18:54
@tankywoo, this error has been happening since before #24595.  I think what needs to be done is to gather as many iptables use cases that we can find and put them into unit and integration tests, since iptables commands can be very complex.  This will make it so changes can be made to the module without breaking use cases.

**Comment by thusoy** [comment] 2015-07-20 10:03
@jfindlay I'm all for more tests.

Arguments like match-set are weird, since they behave a little unusal compared to most CLIs in that spaces are allowed in the operand without quoting. Anyway, could we have a list of flags that behave this way and check whether the current flag is one of them before applying the quoting rule?

**Comment by jfindlay** [comment] 2015-07-20 14:31
@thusoy, certainly.  When I have some time, I'll write some tests and you can add or suggest anything you want.

**Comment by falzm** [comment] 2015-09-16 18:22
Hello

This issue still has not been fixed in release 2015.8.0, I cannot upgrade from 2014.7.x. This is getting embarrassing... could you please focus on fixing this "high severity" bug?

**Comment by thusoy** [comment] 2015-09-16 18:50
@falzm I can't reproduce the issue with the following state:
```
test-firewall-state:
    iptables.append:
        - name: filter_accept_in_whitelisted_http
          table: filter
          chain: INPUT
          match: set
          match-set: whitelisted src
          proto: tcp
          dport: http
          jump: ACCEPT

        - name: filter_accept_in_whitelisted_ssh
          table: filter
          chain: INPUT
          match: set
          match-set: whitelisted src
          proto: tcp
          dport: ssh
          jump: ACCEPT
```

This results in the following rules:
```
Chain INPUT (policy DROP 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1       0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set whitelisted src tcp dpt:80
2       0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set whitelisted src tcp dpt:22
```

**Comment by z1oy** [comment] 2015-09-21 12:18
@thusoy 
Run again.
When you first start all ok.
Repeated, you get an error, because iptables-save in the output will be a string ipset
Firts run:
----------
          ID: iptables-test
    Function: iptables.append
      Result: True
     Comment: Set and saved iptables rule iptables-test for ipv4
              /sbin/iptables --wait -t filter -A INPUT  -p tcp -m state -m set --state NEW --dport 80 --sport 1025:65535 --match-set test src --jump ACCEPT
              Wrote 1 lines to "/etc/iptables/rules.v4"
     Started: 15:04:10.853191
    Duration: 42.902 ms
     Changes:
              ----------
              locale:
                  iptables-test

------
```
 /sbin/iptables-save
-A INPUT -p tcp -m state --state NEW -m set --match-set test src -m tcp --sport 1025:65535 --dport 80 -j ACCEPT
```
```
salt-call state.highstate
usage: salt-call [-h] [-A APPEND] [-D DELETE] [-I INSERT] [-R REPLACE]
salt-call: error: argument --match-set: expected 2 argument(s)
```

**Comment by l13t** [comment] 2015-10-07 16:03
Got same issue. First run on clean iptables rules is fine. And on next applying iptables got same error.

**Comment by l13t** [comment] 2015-10-08 15:37
I'm not so good in python, but if I'm removing nargs option in this line: https://github.com/saltstack/salt/blob/develop/salt/modules/iptables.py#L1237 - all works fine for me.
I think argparser want to see something like:
```python
args=['-A', 'INPUT', '-m', 'set', '--match-set', 'allowed-list', 'src', '-j', 'ACCEPT']
```
But after _parse_conf manipulations it gets:
```python
args=['-A', 'INPUT', '-m', 'set', '--match-set', 'allowed-list src', '-j', 'ACCEPT']
```
So it can't proceed with parsing arguments. Maybe this would be a solution after you'll test this.

**Comment by jfindlay** [comment] 2015-10-08 23:29
Thanks, @l13t, that is some good info.

**Comment by l13t** [comment] 2015-10-09 11:28
Actually in 2014.7.5 there were no nargs option for --match-set parameter: https://github.com/saltstack/salt/blob/v2014.7.5/salt/modules/iptables.py#L1079

**Comment by gerhardqux** [comment] 2016-05-17 18:01
When #33314 is merged, this issue should be completely resolved on all branches. Thanks!

**Closed** 2016-05-18 16:42 UTC
Labels: Bug, Fixed Pending Verification, Help Wanted, High Severity, Needs Testcase, P4, Platform, Regression, State Module
