### ISSUE TITLE
Every sls file is rendered via compile_template() twice

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#27443] opened 2015-09-27 20:42 UTC
While working on #27346, I added this minor patch (which I'll clean up a bit and send a proper PR for):

```diff
$ git diff
diff --git a/salt/template.py b/salt/template.py
index a334498..15d641b 100644
--- a/salt/template.py
+++ b/salt/template.py
@@ -76,7 +76,10 @@ def compile_template(template,
         render_kwargs.update(kwargs)
         if argline:
             render_kwargs['argline'] = argline
+        start = time.time()
         ret = render(input_data, saltenv, sls, **render_kwargs)
+        end = time.time() - start
+        log.info('Time to render \'{}\': {}'.format(template, end))
         if ret is None:
             # The file is empty or is being written elsewhere
             time.sleep(0.01)
```

It lead to the very interesting discovery, that **every** single sls file, pillar or not, is rendered twice by [compile_template()](https://github.com/saltstack/salt/blob/develop/salt/template.py#L30).

The master log (with the above patch) shows things like this when running `salt \* saltutil.refresh_pillar`:

```
[INFO    ] Time to render '/srv/salt/pillars/top.sls': 0.00321197509766
[INFO    ] Time to render '/srv/salt/pillars/top.sls': 0.00289797782898
[INFO    ] Time to render '/srv/salt/pillars/default.sls': 0.000541925430298
[INFO    ] Time to render '/srv/salt/pillars/default.sls': 0.000375986099243
```

I showed this to @terminalmage, which he confirms, as he is here (in person) hacking on salt with me. I'll polish up that patch to make it a bit more configurable, but this uncovered a serious issue. We are going to try to bisect and find the source problem, but this would cut down the pillar render times quite literally in 1/2 for our production env.

cc: @grichmond-salt @cachedout

**Comment by SEJeff** [comment] 2015-09-27 20:48
I've went back to the `2014.7.6` tag, and it still exists there, so this has been around for awhile.

**Comment by terminalmage** [comment] 2015-09-27 20:50
Looking at this right now.

**Comment by SEJeff** [comment] 2015-09-27 20:53
Full log of the session:

```yaml
[INFO    ] User jschroeder Published command saltutil.refresh_pillar with jid 20150927155046602605
[INFO    ] Time to render '/srv/salt/pillars/top.sls': 0.00294899940491
[INFO    ] Time to render '/srv/salt/pillars/top.sls': 0.004390001297
[INFO    ] Time to render '/srv/salt/pillars/default.sls': 0.000685930252075
[INFO    ] Time to render '/srv/salt/pillars/default.sls': 0.000519990921021
[INFO    ] Got return from chit-jsl3.w2k.jumptrading.com for job 20150927155046602605
```

**Comment by SEJeff** [comment] 2015-09-27 21:06
And from a highstate:

```yaml
[INFO    ] User jschroeder Published command state.highstate with jid 20150927160529142617
[INFO    ] Time to render '/srv/salt/pillars/top.sls': 0.00112390518188
[INFO    ] Time to render '/srv/salt/pillars/top.sls': 0.00160789489746
[INFO    ] Time to render '/srv/salt/pillars/default.sls': 0.00080394744873
[INFO    ] Time to render '/srv/salt/pillars/default.sls': 0.000571012496948
[INFO    ] Got return from chit-jsl3 for job 20150927160529142617
```

**Comment by terminalmage** [comment] 2015-09-28 01:01
This might not be a bug after all. It looks like we're just running ``render()`` twice here because we're doing so once for jinja, and again for yaml.

**Comment by terminalmage** [comment] 2015-09-28 01:11
Yep, @SEJeff, this is confirmed:

Using the following patch...

```diff
diff --git a/salt/template.py b/salt/template.py
index a334498..51b5c20 100644
--- a/salt/template.py
+++ b/salt/template.py
@@ -76,7 +76,15 @@ def compile_template(template,
         render_kwargs.update(kwargs)
         if argline:
             render_kwargs['argline'] = argline
+        start = time.time()
         ret = render(input_data, saltenv, sls, **render_kwargs)
+        log.info(
+            'Time to render \'{0}\' using \'{1}\' renderer: {2}'.format(
+                template,
+                render.__module__.split('.')[-1],
+                time.time() - start
+            )
+        )
         if ret is None:
             # The file is empty or is being written elsewhere
             time.sleep(0.01)
```

I get this:

```
[INFO    ] Time to render '/home/erik/saltdev/srv/pillar/base/top.sls' using 'jinja' renderer: 0.0100169181824
[INFO    ] Time to render '/home/erik/saltdev/srv/pillar/base/top.sls' using 'yaml' renderer: 0.00803804397583
[INFO    ] Time to render '/home/erik/saltdev/srv/pillar/base/test.sls' using 'jinja' renderer: 0.00477004051208
[INFO    ] Time to render '/home/erik/saltdev/srv/pillar/base/test.sls' using 'yaml' renderer: 0.00179886817932
```

**Comment by terminalmage** [comment] 2015-11-13 22:24
My patch, along with the new "profile" loglevel that @SEJeff and I discussed, have been added in https://github.com/saltstack/salt/pull/28880. Closing.

**Closed by terminalmage** 2015-11-13 22:24 UTC
Labels: Core, Expected Behavior, Pillar
