### ISSUE TITLE
salt-cloud digital ocean api v2 doesn't implement all available actions

### ISSUE THREAD

**Issue by mshirley** [saltstack/salt#31639] opened 2016-03-02 23:34 UTC
### Description of Issue/Question
The digital ocean api v2 provider does not support droplet actions like "reboot".

https://developers.digitalocean.com/documentation/v2/#reboot-a-droplet

### Setup
driver: digital_ocean

### Steps to Reproduce Issue
```
sudo salt-cloud -a reboot node1                                                                                                     
[INFO    ] salt-cloud starting
The following virtual machines are set to be actioned with "reboot":
  node1

Proceed? [N/y] y
... proceeding
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] 'digital_ocean.reboot()' is not available. Not actioning...
Invalid Actions:
    ----------
    digital_ocean.reboot:
        - node1
Not Actioned/Not Running:
    - node1
Not Found:
    - node1
```
### Versions Report
```
Salt Version:
           Salt: 2015.8.4
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: 1.0.2
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.8.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment] 2016-03-03 16:37
@mshirley, thanks for the report.

**Comment by rallytime** [comment] 2016-03-03 16:41
Thanks for letting us know @mshirley. All salt-cloud drivers should have support for `start`, `stop`, and `reboot` actions. Marking this as a bug.

**Comment by rallytime** [comment] 2016-03-08 00:06
I have fixed this with #31735.

**Comment by mshirley** [comment] 2016-03-08 23:34
Thanks!  Fix is working for me.
```
$ sudo salt-cloud -a reboot node1        
[INFO    ] salt-cloud starting
The following virtual machines are set to be actioned with "reboot":
  node1

Proceed? [N/y] y
... proceeding
digitalocean:
    ----------
    digital_ocean:
        ----------
        node1:
            ----------
            action:
                reboot
            state:
                in-progress
            success:
                True
```

I'll let you guys/girls close this as you see fit.

**Comment by rallytime** [comment] 2016-03-08 23:49
Awesome! Glad it is working for you. I'll go ahead and close this since you've confirmed. We'll get that change merged in!

**Closed by rallytime** 2016-03-08 23:49 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P2, RIoT, Salt-Cloud, TEAM RIoT
