### ISSUE TITLE
datetime as value in pillar causes error

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#21721] opened 2015-03-16 23:19 UTC
A datetime as a pillar value causes the pillar to fail to render.

```
           Salt: 2014.7.1
         Python: 2.6.9 (unknown, Sep 13 2014, 00:25:11)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

Pillar Example
```
serverConfig:
  Tableaugle: 2015-02-27T21:13:00
  orthis: 2015-01-01
```

```
2015-03-16 23:13:55,828 [salt.master                                ][ERROR   ] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1336, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1110, in _pillar
    'pillar': data})
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 115, in dumps
    return msgpack.dumps(msg)
  File "/usr/lib64/python2.6/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 223, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:223)
  File "msgpack/_packer.pyx", line 225, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:225)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 220, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:220)
TypeError: can't serialize datetime.datetime(2015, 2, 27, 21, 13)
```

**Comment by jfindlay** [comment] 2015-03-17 16:06
@deuscapturus, thanks for the report.

**Comment by jfindlay** [comment] 2015-03-17 16:06
Related to #/21113.

**Comment by dmyerscough** [comment] 2015-03-24 18:36
@rallytime I was just looking at this issue and I can see you can specify the `msgpack.dumps(msg, default=str)`. However, you would need to use msgpack.loads() and the OrderedDict changes to a list of dicts.

**Comment by surajssd** [comment] 2015-04-01 18:32
Hi, I did submit patch for this issue and has been merged in [issue#22118](https://github.com/saltstack/salt/pull/22118). So please take a look.

**Comment by jfindlay** [comment] 2015-04-01 18:58
Actually, I referenced this issue, by editing @surajssd's commit message.

**Comment by rallytime** [comment] 2015-05-01 16:51
@deuscapturus Given the referenced pull request above, can you give the fix a try and let us know if this issue is resolved? Thanks!

**Comment by jfindlay** [comment] 2015-05-11 21:01
Related to #11630.

**Comment by rallytime** [comment] 2015-07-13 22:45
Since I haven't heard back here for a while I am going to close this issue. If this remains an issue on newer versions of salt (current stable is 2015.5.3) please leave a comment and we will gladly re-open this and take another look. Thanks!

**Closed by rallytime** 2015-07-13 22:45 UTC
Labels: Feature, Fixed Pending Verification, Low-Hanging Fruit

**Comment by pomeh** [comment] 2018-10-01 14:13
Hi,

I'm using and old version of Salt, and I encountered the same error with my setup.

As stated by @surajssd, this bug as been fixed by PR #22118.
A (rapid) Google lookup make me think this fix has been published with version 2015.8.0rc1 Salt version (cf. https://github.com/tjstansell/salt-changelogs/blob/master/details/2015.8.0rc1-details.rst#L3351).

As upgrading Salt version was, sadly, not an option in my case (don't ask me why), I'm posting here workarounds I found, just for helping anyone facing the same situation in the future.

salt --versions-report:
```
           Salt: 2015.5.10
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5
```

Pillar example (failing)
```
foo:
  bar: 2018-11-25
```

The above example raise the error `TypeError: Cannot serialize datetime.date(2018, 12, 25)`.



**Workaround 1**
Add quotes around date value so the value is interpreted as a string (and won't be parsed):

Corrected pillar example (working)
```
foo:
  bar: '2018-11-25'
```


**Workaround 2**
Change date format (from YYYY-MM-DD to DD/MM/YYYY in my case)

Another pillar example (working)
```
foo:
  bar: 11/25/2018
```

**Comment by diepes** [comment] 2019-03-11 21:55
I just ran into this problem,   

```
2019-03-11 21:45:26,306 [salt.master      :1621][ERROR   ][3186] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1611, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1335, in _pillar
    'pillar': data})
...
...
  File "/usr/local/lib/python2.7/dist-packages/msgpack/fallback.py", line 896, in _pack
    raise TypeError("Cannot serialize %r" % (obj, ))
TypeError: Cannot serialize datetime.date(2019, 3, 14)

```
Salt Version:
           Salt: 2017.7.8

It was caused by a pillar value:
```
xx:
  expiredate: 2019-03-14
```

Fixed by quoting the date
```
 xx:
    expiredate: '2019-03-14'
```

**Comment by rallytime** [comment] 2019-03-13 16:32
@garethgreenaway or @Ch3LL can you guys help out on this one?

**Comment by Ch3LL** [comment] 2019-03-18 14:19
looks like the original fix was changed here https://github.com/saltstack/salt/pull/46269  in version 2018.3.0

Can anyone confirm if its working in 2018.3.0 or not?
