### ISSUE TITLE
Salt ignoring locale setting

### ISSUE THREAD

**Issue by alsmith2011** [saltstack/salt#58649] opened 2020-10-06 11:30 UTC
### Description of Issue
Salt is seemingly ignoring the minions locale settings and using US instead.

### Setup
Running the command

salt 'Minion_name' locale.get_locale  
Gives the output:

Minion_name:     en_GB.UTF-8

However when i use cmd.run to execute a script it is using US lang

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
           Salt: 2015.5.10
         Python: 2.7.5 (default, Apr  2 2020, 13:16:51)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by alsmith2011** [comment] 2020-10-07 08:21
@sagetherage upgraded to the latest version and onto python 3 but the issue persists.

As far as i can tell the salt-minion is overwriting the locale setting.
On the minion, as root, locale -v output:
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=


From the salt master running the command **salt "Minion_ID" cmd.run "locale -v"** output:
    LANG=
    LC_CTYPE=C
    LC_NUMERIC=C
    LC_TIME=C
    LC_COLLATE=C
    LC_MONETARY=C
    LC_MESSAGES=C
    LC_PAPER=C
    LC_NAME=C
    LC_ADDRESS=C
    LC_TELEPHONE=C
    LC_MEASUREMENT=C
    LC_IDENTIFICATION=C
    LC_ALL=

I assume i need to set the land for the salt minion process, i have seen mentions of doing this with modules but i have not used any modules yet so any guidance on how to implement would be appreciated

**Comment by sagetherage** [comment] 2020-10-08 16:36
Ok, so you are seeing this on latest as of yesterday v3001.1, putting this back into triage with an Open Core Dev.

**Comment by alsmith2011** [comment] 2020-10-09 07:38
Yes now on the latest version one the master and minion.

I have also checked the environment for the salt minion process and it has the correct lang and TC settings of en_GB.UTF-8 

I have even sent a sleep 100 command from the master to the minion to check the environment settings of the spawned salt process and that has the correct environment. But still running locale -v as a command sent from salt master to minion the environment variables are not correct. This is pretty confusing i think

**Comment by sagetherage** [comment] 2020-10-09 14:59
@alsmith2011 thank you for the confirmation, getting this triaged and reviewed @garethgreenaway

**Comment by garethgreenaway** [comment] 2020-10-13 20:06
@alsmith2011 Thanks for the report.  I'm able to reproduce this one and work around it by ensuring that the right LANG values are set in the shell where starting up the Salt minion.  If the values are `en_US.UTF-8` when the minion starts then the minion reports that value when running cmd.run and running the locale module.  If I update them to `en_GB.UTF-8`, ensure those values are set, and start the Salt minion process then I see the expected values.

**Comment by alsmith2011** [comment] 2020-10-14 07:34
Thanks for looking into it @garethgreenaway 
So the output from locale -v when i run on the server as root are correct (see above)stopping and starting the salt-minion has no change to the settings i see when sending the locale -v command from the master (again see above).
Could you confirm where you updated your setting?

**Comment by alsmith2011** [comment] 2020-10-21 14:28
Found the solution. 
In the file /salt/modules/cmdmod.py the LC values are hard coded, changed them to match my preference and working as it should now.

**Comment by alsmith2011** [comment] 2020-11-04 22:10
I put the path in my original comment but I beleive the fill path with change based on distribution. You can search on git or in the mention file for "LC_TYPE" and you should find it

**Comment by garethgreenaway** [comment] 2023-08-28 17:49
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.

**Closed by garethgreenaway** 2023-08-28 17:49 UTC
Labels: Bug, Pending-Discussion
