### ISSUE TITLE
SaltCloud leaves zombie processes if Salt is terminated early

### ISSUE THREAD

**Issue by SmithSamuelM** [saltstack/salt#8990] opened 2013-12-03 21:15 UTC
Salt Cloud creates processes that can become zombies if salt is terminated while the cloud processes are still alive.

For example:

map_providers_parallel

**Comment by rallytime** [comment] 2015-06-02 18:45
I think in the interim of when this bug was filed and now, this has been fixed. I can't reproduce the zombie processes. Steps I've tried to reproduce:
1. Start salt-master and salt-minion (local)
2. Use salt-cloud to provision a VM on EC2
3. While that salt-cloud process is running, kill the the salt-master and salt-minion processes.
4. Wait for salt-cloud to finish provisioning VM. 
5. Check for zombies: There are none.

The VM was provisioned appropriately and no zombie processes were created. I also attempted this same process/test when calling a map file with `salt-cloud -m ~/mapfile` and still didn't find any zombies.

```
# salt-cloud --versions
            Salt: 2015.5.1-97-g88a997e
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.17.0
```
I am going to go ahead and close this bug, but if someone is able to reproduce it on a newer version of salt, then please comment and we can reopen.

**Closed by rallytime** 2015-06-02 18:45 UTC
Labels: Bug, Medium Severity, Salt-Cloud
