### ISSUE TITLE
[develop] file.serialized with json and merge_if_exists doesn't work due to wrong options being passed to deserialize function

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#47921] opened 2018-06-01 13:35 UTC
I was looking forward to using `file.serialize`'s new `serializer_opts` argument on the develop branch, but ran into a problem when trying it out.

Given a state like:

```
/path/to/file.json:
  file.serialize:
    - dataset:
        foo: bar
    - formatter: json
    - serializer_opts:
      - indent: 4
    - merge_if_exists: true
    - replace: false
```

Produces the following error:

```
Function: file.serialize
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/var/tmp/.salt_08831c_salt/pyall/salt/serializers/json.py", line 41, in deserialize
              stream_or_string, _json_module=_json, **options)
            File "/var/tmp/.salt_08831c_salt/pyall/salt/utils/json.py", line 77, in load
              return kwargs.pop('_json_module', json).load(fp, **kwargs)
            File "/usr/lib/python3.5/json/__init__.py", line 268, in load
              parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
            File "/usr/lib/python3.5/json/__init__.py", line 332, in loads
              return cls(**kw).decode(s)
          TypeError: __init__() got an unexpected keyword argument 'indent'

          During handling of the above exception, another exception occurred:

          Traceback (most recent call last):
            File "/var/tmp/.salt_08831c_salt/pyall/salt/state.py", line 1928, in call
              **cdata['kwargs'])
            File "/var/tmp/.salt_08831c_salt/pyall/salt/loader.py", line 1837, in wrapper
              return f(*args, **kwargs)
            File "/var/tmp/.salt_08831c_salt/pyall/salt/states/file.py", line 6309, in serialize
              existing_data = __serializers__[deserializer_name](fhr, **options.get(serializer_name, {}))
            File "/var/tmp/.salt_08831c_salt/pyall/salt/serializers/json.py", line 48, in deserialize
              raise DeserializationError(error)
          salt.serializers.DeserializationError: __init__() got an unexpected keyword argument 'indent'
 Started: 15:26:49.300034
Duration: 4.08 ms
 Changes:
```

This solution makes the error go away, but might break other use cases.

```diff
diff --git a/salt/states/file.py b/salt/states/file.py
index 920d7bbfad..67b7cb52c7 100644
--- a/salt/states/file.py
+++ b/salt/states/file.py
@@ -6306,7 +6306,7 @@ def serialize(name,
                         'result': False}
 
             with salt.utils.files.fopen(name, 'r') as fhr:
-                existing_data = __serializers__[deserializer_name](fhr, **options.get(serializer_name, {}))
+                existing_data = __serializers__[deserializer_name](fhr)
 
             if existing_data is not None:
                 merged_data = salt.utils.dictupdate.merge_recurse(existing_data, dataset)
```

```
$ salt-ssh --versions
Salt Version:
           Salt: 2018.3.0-473-g2bac7b2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 19 2017, 14:11:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.1.6
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

**Comment by gtmanfred** [comment] 2018-06-04 14:57
Are you sure you are on the latest develop?

Because there are quite a few more commits in my version number.

```
[root@19871b3237e0 salt]# salt-call --versions-report
Salt Version:
           Salt: 2018.3.0-3919-gb004a1a
```

And I am unable to replicate this issue.

Daniel

**Comment by anlutro** [comment] 2018-06-04 15:11
I did a `git pull` just now but problem is still present. I can't get the same version number as you, though:

```
$ git remote -v
origin	git@github.com:alprs/salt.git (fetch)
origin	git@github.com:alprs/salt.git (push)
upstream	https://github.com/saltstack/salt (fetch)
upstream	git@github.com:saltstack/salt (push)
$ git pull upstream develop
From https://github.com/saltstack/salt
 * branch                  develop    -> FETCH_HEAD
Already up-to-date.
$ salt-ssh --versions
Salt Version:
           Salt: 2018.3.0-492-gb004a1a
```

**Comment by gtmanfred** [comment] 2018-06-04 15:12
How did you install salt?

did you do a `pip install -e .`?

Can you run `git describe` in the repository?

```
[root@19871b3237e0 salt]# git describe
v2018.3.0-3919-gb004a1a
```

**Comment by anlutro** [comment] 2018-06-04 15:15
Made a virtualenv, `pip install -e .`. I re-created the virtualenv from scratch just now and wiped all .pyc and __pycache__ files just to be sure.

```
$ git describe 
v2018.3.0-3919-gb004a1ace7
$ salt-ssh --versions
Salt Version:
           Salt: 2018.3.0-492-gb004a1a
```

**Comment by gtmanfred** [comment] 2018-06-04 15:28
I am unable to replicate not getting the version to update.

When I update my repository that is installed with `pip install -e` the git salt version updates.

Without being able to replicate this issue with the current develop, there is not a lot that we can do to fix this.

Thanks,
Daniel

**Comment by anlutro** [comment] 2018-06-04 15:31
Well, my version did update from `2018.3.0-473-g2bac7b2` to `2018.3.0-492-gb004a1a` when I `git pull`ed so I can't be that far off the mark... But I will `rm -rf` literally everything and start over to be 110% sure.

**Comment by anlutro** [comment] 2018-06-04 15:39
Here's my entire installation process, could you point out what I'm doing wrong please? https://bpaste.net/show/4c07f7232421

**Comment by gtmanfred** [comment] 2018-06-04 17:20
Looks like this was caused by https://github.com/saltstack/salt/commit/6b935442766b3a81dc4ca62a319d3586fc8e3d7b

@nocturo can you take a look at this since you implemented this?

Thanks,
Daniel

**Comment by nocturo** [comment] 2018-06-04 20:36
On 2018.3.0 with patches for `serializer_opts` backported, python 3.4 from epel, everything seems to be working:
```
[root@687b0ccee927 salt]# salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.8 (default, Mar 23 2018, 10:04:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.60-linuxkit-aufs
         system: Linux
        version: CentOS Linux 7.4.1708 Core

[root@687b0ccee927 salt]# cat testjson.sls
/testjson.json:
  file.serialize:
    - dataset:
        foo: bar
    - formatter: json
    - serializer_opts:
      - indent: 4
    - merge_if_exists: true
    - replace: false
[root@687b0ccee927 salt]# rm -rf /testjson.json
[root@687b0ccee927 salt]# salt-call state.sls testjson
local:
----------
          ID: /testjson.json
    Function: file.serialize
      Result: True
     Comment: File /testjson.json updated
     Started: 20:33:52.148738
    Duration: 2.725 ms
     Changes:
              ----------
              diff:
                  New file

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   2.725 ms
[root@687b0ccee927 salt]# cat /testjson.json
{
    "foo": "bar"
}
[root@687b0ccee927 salt]#
```

so this is most likely caused by something that got diverged from between 2018.3.0 and develop. I'll see if I can dig what's causing it.

**Comment by gtmanfred** [comment] 2018-06-04 20:39
Awesome, thanks!
Daniel

**Comment by nocturo** [comment] 2018-06-05 12:56
Pushed a fix for this to develop. Let me know if everything is working for you @anlutro and if this is good enough code for salt @gtmanfred :)

**Comment by gtmanfred** [comment] 2018-06-05 13:18
Thanks for the PR, comment added.

**Closed** 2018-06-06 15:27 UTC
Labels: Blocker, Bug, Core, Fluorine, High Severity, TEAM Core, team-core
