### ISSUE TITLE
 zmq and msgpack for arm don't appear to be packaged

### ISSUE THREAD

**Issue by Tejeev** [saltstack/salt#19587] opened 2015-01-09 21:48 UTC
####  When using apt-get to install salt-minion on the following setup it finds unmet dependencies: 
ARM based [ts7600] (http://wiki.embeddedarm.com/wiki/TS-7600) or [ts7400v2] (http://wiki.embeddedarm.com/wiki/TS-7400v2) from [Technologic Systems] (http://www.embeddedarm.com/) 

#####  We added the following in our apt sources:
deb http://debian.saltstack.com/debian wheezy-saltstack main

#####  and added the salt gpg key:
wget -q -O- "http://debian.saltstack.com/debian-salt-team-joehealy.gpg.key" | apt-key add -
 
 
#### Error:
The following packages have unmet dependencies:
```
salt-minion : Depends: python-zmq (>= 13.1.0) but it is not going to be installed
               Recommends: dmidecode but it is not installable
               Recommends: debconf-utils but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
 
 
#### Workaround:
We have been working around this by manually obtaining and installing the following packages:
    http://ftp.us.debian.org/debian/pool/main/p/pyzmq/python-zmq_13.1.0-1~bpo70+1_armel.deb
    http://ftp.us.debian.org/debian/pool/main/m/msgpack-python/python-msgpack_0.3.0-1~bpo70+2_armel.deb

We were also including (in sources):  
    deb http://ftp.de.debian.org/debian wheezy main

**Comment by joehealy** [comment] 2015-01-11 11:37
odd. I don't remember off hand where the armel packages came from (ie did I build them myself in a chroot or vm or copy them from debian backports?) I'll be in at work tomorrow and check my notes.

I'll add them to the repo. 

Thanks for reporting this - not using arm machines directly myself, it is good to know if it is working or not.

thanks,

Joe

**Comment by pitatus** [comment] 2015-01-12 17:05
thanks for looking at this Joe, I have ARM available and can test some too..

**Comment by damon-atkins** [comment] 2015-01-12 17:51
This is from Fedora 20 standard repo:
yum deplist salt
Loaded plugins: langpacks, refresh-packagekit
package: salt.noarch 2014.7.0-3.fc20
  dependency: /bin/sh
   provider: bash.armv7hl 4.2.53-1.fc20
  dependency: PyYAML
   provider: PyYAML.armv7hl 3.10-10.fc20
  dependency: m2crypto
   provider: m2crypto.armv7hl 0.21.1-13.fc20
  dependency: pciutils
   provider: pciutils.armv7hl 3.3.0-1.fc20
  dependency: python(abi) = 2.7
   provider: python.armv7hl 2.7.5-15.fc20
  dependency: python-crypto
   provider: python-crypto.armv7hl 2.6.1-1.fc20
  dependency: python-jinja2
   provider: python-jinja2.noarch 2.7.3-2.fc20
  dependency: python-msgpack
   provider: python-msgpack.armv7hl 0.4.2-1.fc20
  dependency: python-requests
   provider: python-requests.noarch 1.2.3-5.fc20
  dependency: python-zmq
   provider: python-zmq.armv7hl 13.0.2-1.fc20
  dependency: sshpass
   provider: sshpass.armv7hl 1.05-5.fc20
  dependency: systemd-python
   provider: systemd-python.armv7hl 208-28.fc20
  dependency: systemd-units
   provider: systemd.armv7hl 208-28.fc20
  dependency: yum-utils
   provider: yum-utils.noarch 1.1.31-27.fc20

**Comment by Tejeev** [comment] 2015-01-13 23:47
I of course have arm boards laying about and am more than happy to test.

**Comment by joehealy** [comment] 2015-01-14 10:03
I've discovered the issue - I'd built the packages, but the (python-zmq)
didn't pass their tests.

Wasn't able to resolve the issue. I'll try a newer version to see if it has
been resolved.

Joe

**Comment by pitatus** [comment] 2015-01-22 20:03
@Tejeev, missing pkgs have been copied to repo and Packages files have been updated, Update and try this and let me know if this works.

**Comment by joehealy** [comment] 2015-01-22 22:04
I suspect this will give failures because the changes won't be signed. If
you can send me the deb file, I can upload it.

Cheers,

Joe

**Comment by pitatus** [comment] 2015-01-22 22:28
it is the .deb from the debian site, I didn't build..

**Comment by joehealy** [comment] 2015-01-22 22:41
Have you got a link? I'm fairly time constrained at the moment, but can
grab a file and get it uploaded.

Joe

**Comment by pitatus** [comment] 2015-01-22 22:59
The two files referenced in the original comment:

http://ftp.us.debian.org/debian/pool/main/p/pyzmq/python-zmq_13.1.0-1~bpo70+1_armel.deb
http://ftp.us.debian.org/debian/pool/main/m/msgpack-python/python-msgpack_0.3.0-1~bpo70+2_armel.deb

I copied these to the debian.saltstack.com/...  area

**Comment by joehealy** [comment] 2015-01-22 23:22
I've added them to the repo and am rsyncing it up now.

Thanks for your help

Joe

**Comment by Tejeev** [comment] 2015-01-23 22:03
Are the files I originally linked the best sources?  I don't know enough about how all the packages are dependent on each other or what all is entailed, I just don't want something to eventually brake because one of them wasn't being managed and another has been upgraded.

**Comment by pitatus** [comment] 2015-01-24 01:31
From your initial comment you already have the repo enabled, you should be able to do an 'apt-get update' and then try your install as you attempted before.  However, since you probably already have the dependencies installed, you can manually remove one (and the salt pkg that had that dependency) and try the pkg install again to see if it will pull the dependency automatically.

The dependencies you referenced above were added to this repo and should satisfy the depency requirements for this OS version.  When other salt versions are released these depencies will be used as a baseline for creating the next package and updated as requirements change.

It may be a good idea to reproduce on a duplicate OS/board install to be sure everything is ok.  If you have additional problems let us know.

(thanks @joehealy)

**Comment by Tejeev** [comment] 2015-01-27 20:04
Thanks @pitatus and @joehealy.  Ill be installing from scratch and building a new image anyway (waiting on an update from the manufacturer of my board that will require me to rebuild our primary image) so Ill get a good opp to test this when I do that later this week.

**Comment by joehealy** [comment] 2015-02-12 11:44
Any feedback on whether or not this is solved?

Thanks,

Joe

**Comment by Tejeev** [comment] 2015-02-14 00:02
Sorry Joe, been stuck on other aspects of the project and haven't gotten around to rebuild yet.

**Comment by Tejeev** [comment] 2015-02-14 00:04
@pitatus have you gotten around to testing with your ARM?

**Comment by pitatus** [comment] 2015-02-17 16:58
@Tejeev no mine is not same architecture so can't test this specifically

**Comment by kmt28** [comment] 2015-02-21 19:29
@whiteinge ping

**Comment by rallytime** [comment] 2015-04-03 19:50
Since it looks like this is likely fixed since the packages have been added to the saltstack debian repo, I am going to close this issue. If someone runs into problems here when testing the packages, please leave note here and we can reopen this bug.

**Closed by rallytime** 2015-04-03 19:50 UTC
Labels: Bug, Fixed Pending Verification, Medium Severity, Packaging
