### ISSUE TITLE
Windows minions assume winrepo cache file location regardless of win_repo_mastercachefile value

### ISSUE THREAD

**Issue by joshmule** [saltstack/salt#15926] opened 2014-09-18 16:34 UTC
Windows minions seem to assume winrepo cache file location regardless of the win_repo_mastercachefile: setting on the master side.

Unless win_repo_mastercachefile: is set to something that translates to salt://win/repo/winrepo.p , the Windows minion will complain that salt://win/repo/winrepo.p can't be found.  Setting win_repo_mastercachefile: to another file or directory/file that is within salt://win/ doesn't work either, even though the minion can clearly access that location.

The minion conf file contains the default contents of:
```
# win_repo_cachefile: 'salt://win/repo/winrepo.p'
```
... but is clearly insisting on using that commented out default regardless of the win_repo_mastercachefile: location set on the master side.

Is this a bug?

```
Minion version: salt-2014.1.10.win-amd64
Master version: 2014.1.7+ds-1trusty1
```

**Comment by eliasp** [comment] 2015-02-16 17:01
**Related**:   #20526 - *`winrepo.genrepo` runner joins 2 absolute paths for writing the winrepo cache file*

**Comment by UtahDave** [comment] 2015-06-29 21:14
I'm going to close this issue since Salt is working as designed at the moment.  I'm considering removing the option to specify a non-default location and putting it in the file_roots under _winrepo, or something.

**Closed by UtahDave** 2015-06-29 21:14 UTC
Labels: Beryllium, Feature, P3, Platform, Windows
