### ISSUE TITLE
Syndication issues when using authentication on master of masters. 

### ISSUE THREAD

**Issue by paclat** [saltstack/salt#24147] opened 2015-05-26 18:34 UTC
In our environment we are attempting to use a hierarchy of salt-masters that are syndicated across multiple levels.
When we connect to the machine that is running the master that is at the top of the hierarchy and run
```yaml
salt '*' test.ping

dtc-master-chi:
    True
dtc-master-aus:
    True
flt-master:
    True
pod-master-chi-unos:
    True
pod-master-aus-sxsw:
    True
pod-master-aus-sema:
    True
pod-minion-chi-unos-admin:
    True
pod-minion-chi-unos-crm:
    True
pod-minion-chi-unos-bi:
    True
pod-minion-aus-sxsw-admin:
    True
pod-minion-aus-sxsw-bi:
    True
pod-minion-aus-sema-crm:
    True
pod-minion-aus-sema-admin:
    True
pod-minion-aus-sema-bi:
    True
pod-minion-aus-sxsw-crm:
    True
```

as the root user we get the test.ping call passed all the way down through the syndication hierarchy with no problem.

We are trying to leverage the security capabilities of Salt and so we created a "saltdev" user for testing purposes and
also configured external auth on each of the masters to match..
```yaml
external_auth:
  pam:
    saltdev:
      - .*
```

What is odd is that when we run the command as the authenticated user saltdev
```yaml
salt -a pam --username=saltdev --password=saltdev '*' test.ping

flt-master:
    True
dtc-master-chi:
    True
dtc-master-aus:
    True
```
The request only executes on the direct minions and is not propagated to the syndics.

We do see
```
2015-05-19 18:50:15,383 [salt.master      ][WARNING ][61]  Authentication failure of type "user" occurred
```
offending line in master.py seems to be 

```python
    elif clear_load.pop('key') != self.key[self.opts.get('user', 'root')]:                     log.warning(                         'Authentication failure of type "user" occurred.'                     )

````

**Comment by thatch45** [comment] 2015-05-28 15:19
@paclat can you please give us a version report so we can try to reproduce this on the correct version? But this does look like we have a bug in sending the relative user data down the pipe.
This looks like the user check is being run on the lower level because the user from the higher level is being pushed down.

@msteed can you please take a look at this? You have spent the most time with syndics recently. It looks like this should be an easy fix.

**Comment by msteed** [comment] 2015-05-28 20:20
Reproduced in 2015.5

**Comment by paclat** [comment] 2015-05-29 15:08
Thanks for the amazingly quick turn around.  We tried the fix locally and it worked  perfectly

**Comment by msteed** [comment] 2015-05-29 15:15
@paclat - Excellent, thanks for the confirmation. Yes, this will be in the next 2015.5 update.

**Closed by msteed** 2015-05-29 15:15 UTC
Labels: Bug, Confirmed, Fixed Pending Verification, High Severity, P3, Salt-Syndic
