### ISSUE TITLE
salt-cloud -u broken

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#26299] opened 2015-08-13 19:06 UTC
salt-cloud -u is broken.  I think it's an [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) thing (see curl output below).

````
# salt-cloud -u
[INFO    ] Starting new HTTPS connection (1): bootstrap.saltstack.com
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SSLError: hostname 'bootstrap.saltstack.com' doesn't match either of '*.wpengine.com', 'wpengine.com'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 316, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 78, in run
    ret = salt.utils.cloud.update_bootstrap(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2302, in update_bootstrap
    req = requests.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: hostname 'bootstrap.saltstack.com' doesn't match either of '*.wpengine.com', 'wpengine.com'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 316, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 78, in run
    ret = salt.utils.cloud.update_bootstrap(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2302, in update_bootstrap
    req = requests.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'bootstrap.saltstack.com' doesn't match either of '*.wpengine.com', 'wpengine.com'
````

````
# salt-cloud --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
       Apache Libcloud: 0.17.0
 Debian source package: 2015.5.3+ds-1trusty1
````

````
# curl -sv https://bootstrap.saltstack.com/
* Hostname was NOT found in DNS cache
*   Trying 45.33.31.154...
* Connected to bootstrap.saltstack.com (45.33.31.154) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: *.saltstack.com
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root

# curl -sv https://45.33.31.154/
* Hostname was NOT found in DNS cache
*   Trying 45.33.31.154...
* Connected to 45.33.31.154 (45.33.31.154) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.wpengine.com
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
 ````

**Comment by jfindlay** [comment] 2015-08-13 19:17
@notpeter, thanks for reporting.  This is a duplicate of #24317.

**Closed by jfindlay** 2015-08-13 19:17 UTC
Labels: Duplicate
