### ISSUE TITLE
mysql_user error in host with IP/netmask

### ISSUE THREAD

**Issue by minusf** [saltstack/salt#52337] opened 2019-03-27 13:56 UTC
### Description of Issue/Question

```
          ID: mariadb-create-user-monitor
    Function: mysql_user.present
        Name: monitor
      Result: False
     Comment: Failed to create user monitor@10.10.10.0/255.255.255.0
     Started: 13:38:44.108402
    Duration: 17.458 ms
     Changes:   
```

```
[INFO    ] Running state [monitor] at time 13:38:44.108402
[INFO    ] Executing state mysql_user.present for [monitor]
[DEBUG   ] Doing query: SELECT VERSION()
[DEBUG   ] Doing query: SELECT column_name from information_schema.COLUMNS WHERE table_schema=%(schema)s and table_name=%(table)s and column_name=%(column)s args: {u'column': u'Password', u'table': u'user', u'schema': u'mysql'} 
[ERROR   ] MySQL Error 1045: Access denied for user 'monitor'@'localhost' (using password: YES)
[DEBUG   ] Doing query: SELECT VERSION()
[DEBUG   ] Doing query: SELECT column_name from information_schema.COLUMNS WHERE table_schema=%(schema)s and table_name=%(table)s and column_name=%(column)s args: {u'column': u'Password', u'table': u'user', u'schema': u'mysql'} 
[DEBUG   ] Doing query: SELECT User,Host FROM mysql.user WHERE User = %(user)s AND Host = %(host)s args: {u'host': u'10.10.10.0/255.255.255.0', u'user': u'monitor'} 
[DEBUG   ] Doing query: SELECT VERSION()
[DEBUG   ] Doing query: SELECT VERSION()
[DEBUG   ] Doing query: SELECT column_name from information_schema.COLUMNS WHERE table_schema=%(schema)s and table_name=%(table)s and column_name=%(column)s args: {u'column': u'Password', u'table': u'user', u'schema': u'mysql'} 
[DEBUG   ] Doing query: SELECT User,Host FROM mysql.user WHERE User = %(user)s AND Host = %(host)s args: {u'host': u'10.10.10.0/255.255.255.0', u'user': u'monitor'} 
[DEBUG   ] Doing query: SELECT column_name from information_schema.COLUMNS WHERE table_schema=%(schema)s and table_name=%(table)s and column_name=%(column)s args: {u'column': u'Password', u'table': u'user', u'schema': u'mysql'} 
[DEBUG   ] Doing query: CREATE USER %(user)s@%(host)s IDENTIFIED BY %(password)s args: {u'host': u'10.10.10.0/255.255.255.0', u'password': u'password', u'user': u'monitor'} 
[DEBUG   ] Doing query: SELECT VERSION()
[ERROR   ] MySQL Error 1045: Access denied for user 'monitor'@'localhost' (using password: YES)
[INFO    ] User 'monitor'@'10.10.10.0/255.255.255.0' was not created
[ERROR   ] Failed to create user monitor@10.10.10.0/255.255.255.0
[INFO    ] Completed state [monitor] at time 13:38:44.125860 (duration_in_ms=17.458)
```

But the user is created:

```
+--------------------------+----------+-------------------------------------------+
| host                     | user     | password                                  |
+--------------------------+----------+-------------------------------------------+
| 10.10.10.0/255.255.255.0 | monitor  | *91F4DA1D373A3012AAE8C67A1DF9C54CBD0846F9 |
+--------------------------+----------+-------------------------------------------+
```

I think the issue is, that the creation is considered successful _only_ if the user can connect back using 'localhost' (the last section of the debug log).

This of course fails, as these users have explicit IPs that they can connect from and localhost is not one of them.  I think the check should simply see if the user is present in `mysql.user` and not try to be too "smart" about it.

### Setup

```
mariadb-create-user-monitor:
  mysql_user.present:
    - name: "monitor"
    - password: "password"
    - host: "10.10.10.0/255.255.255.0"
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by dmurphy18** [comment] 2019-03-27 19:11
@minusf I would have thought that application could always communicate with 127.0.0.1 (localhost), suspect the problem is due to password changes between mysql and mariadb handling, and is similar to issue https://github.com/saltstack/salt/issues/48204.  Hence marking as duplicate and closing.

Please re-open if you find that the issues are not related, and the issue will be reviewed again.

**Closed by dmurphy18** 2019-03-27 19:11 UTC
Labels: Duplicate

**Comment by minusf** [comment] 2019-03-28 09:28
This is not a duplicate of the __password__ related ticket, I have read it before submitting this one.   This is an issue with the __host__ field.

Your assumption that any user can always connect from `localhost` is incorrect. The `host` field is consulted for every connection to see if the user is allowed to connect from the given host. It is perfectly fine to have accounts that cannot connect from `localhost`.

I find it very hostile that you simply closed the ticket without giving me the chance to explain why your suspicion and assumption is wrong.  Please reopen this ticket.
