### ISSUE TITLE
repo.saltstack.com should support IPv6

### ISSUE THREAD

**Issue by Deshke** [saltstack/salt#27861] opened 2015-10-12 09:43 UTC
Guys,

it's 2015. Digital Ocean supports IPv6 just enable it please

**Comment by cachedout** [comment] 2015-10-12 14:46
+1

**Comment by job** [comment] 2016-01-03 14:37
This has been fixed via https://github.com/saltstack/salt/issues/29580

**Comment by rallytime** [comment] 2016-01-04 18:58
Unfortunately, we re-opened #29580 because of the caveat mentioned in [this comment](https://github.com/saltstack/salt/issues/29580#issuecomment-168768513). However, since this issue is a duplicate of #29580, and there is more discussion going on there, I am going to close this as a duplicate issue. Please see #29580 for more information.

**Closed by rallytime** 2016-01-04 18:58 UTC
Labels: Duplicate, Feature, Packaging, Platform
