### ISSUE TITLE
Minion restart very slow since 2016.11.2

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#39052] opened 2017-01-31 12:12 UTC
### Minion restart is slow since 2016.11.2

After upgrading from 2016.11.1 to 2016.11.2 I noticed a very long minion restart time on CentOS 5, 6 and 7. Some minions disconnected after upgrading forcing manual start.

```
time service salt-minion restart
Stopping salt-minion:root:saltstack daemon: OK
Starting salt-minion:root:saltstack daemon: OK

real    0m24.356s
user    0m12.422s
sys     0m0.980s

uptime
 13:10:33 up  2:32,  2 users,  load average: 0.10, 0.43, 0.33
```

Before a minion restart would not take more than a few seconds. I noticed that startup parameters have changed since upgrade, introducing "-c /etc/salt" in 2016.11.2, the config has not been changed.

### Setup

CentOS 5 6 and 7

### Versions Report

```
salt --versions
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 0.9.2
       cherrypy: 3.2.2
       dateutil: 2.4.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.4.6
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: 1.0.0
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.13.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by githubcdr** [comment] 2017-02-01 09:57
Might be related to the netstat command that runs on startup. On servers with many open connections this causes a significant delay.

Resolving names is the issue I think;

```
time netstat --notrim
real    0m6.519s
user    0m0.037s
sys     0m0.034s

vs

time netstat --notrim -n
real    0m0.034s
user    0m0.004s
sys     0m0.025s
```

**Comment by gtmanfred** [comment] 2017-02-01 16:31
It looks like that command was added 9 months ago, so you should have seen it in 2016.11.1 as well.

Also, this issue shouldn't be present in CentOS 7, since that uses the systemd unit which doesn't use notrim.

**Comment by githubcdr** [comment] 2017-02-01 20:07
@gtmanfred correct, I noticed long delay on old CentOS 5 and 6 machines, guess by accident I ran into this.

**Comment by gtmanfred** [comment] 2017-02-01 20:20
Cool, we also ran into some issues with our smoke tests.

https://github.com/saltstack/salt/issues/39119

So this might be a duplicate of that eventually.  But yes I am going to close this one.

Thanks,
Daniel

**Closed by gtmanfred** 2017-02-01 20:20 UTC
Labels: Info Needed

**Comment by PierreR** [comment] 2017-05-20 17:27
From #40489 still an issue for me.
