### ISSUE TITLE
"Cannot allocate memory" error on multiple tcp transport test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53284] opened 2019-05-28 18:46 UTC
Multiple tests on the tcp transport tests are failing here:
https://jenkinsci.saltstack.com/job/2019.2.1/view/Transport/job/salt-centos-7-py2-tcp/9/

the tests failing due to this error are as follows:

unit.returners.test_local_cache.Local_CacheTest.test_clean_old_jobs
unit.returners.test_local_cache.Local_CacheTest.test_not_clean_new_jobs
unit.test_minion.MinionTestCase.test_beacons_before_connect
unit.test_minion.MinionTestCase.test_handle_decoded_payload_jid_match_in_jid_queue
unit.test_minion.MinionTestCase.test_handle_decoded_payload_jid_queue_addition
unit.test_minion.MinionTestCase.test_handle_decoded_payload_jid_queue_reduced_minion_jid_queue_hwm
unit.test_minion.MinionTestCase.test_process_count_max
unit.test_minion.MinionTestCase.test_scheduler_before_connect
unit.modules.test_yumpkg.YumUtilsTestCase.test_call_yum_default
unit.modules.test_yumpkg.YumUtilsTestCase.test_call_yum_with_kwargs
unit.tops.test_ext_nodes.ExtNodesTestCase.test_ext_nodes
unit.tops.test_ext_nodes.ExtNodesTestCase.test_ext_nodes_with_environment
unit.test_config.ConfigTestCase.test_backend_rename
unit.test_config.ConfigTestCase.test_cloud_config_deploy_scripts_search_path
unit.test_config.ConfigTestCase.test_cloud_config_double_profiles_path
unit.test_config.ConfigTestCase.test_cloud_config_double_providers_path
unit.test_config.ConfigTestCase.test_cloud_config_providers_in_opts
unit.test_config.ConfigTestCase.test_cloud_config_providers_in_opts_path
unit.test_config.ConfigTestCase.test_common_prefix_stripping
unit.test_config.ConfigTestCase.test_conf_file_strings_are_unicode_for_master
unit.test_config.ConfigTestCase.test_conf_file_strings_are_unicode_for_minion
unit.test_config.ConfigTestCase.test_default_root_dir_included_in_config_root_dir
unit.test_config.ConfigTestCase.test_deploy_search_path_as_string
unit.test_config.ConfigTestCase.test_issue_5970_minion_confd_inclusion
unit.test_config.ConfigTestCase.test_load_client_config_from_environ_var
unit.test_config.ConfigTestCase.test_load_cloud_config_from_environ_var
unit.test_config.ConfigTestCase.test_load_master_config_from_environ_var
unit.test_config.ConfigTestCase.test_load_minion_config_from_environ_var
unit.test_config.ConfigTestCase.test_master_confd_inclusion
unit.test_config.ConfigTestCase.test_master_file_roots_glob
unit.test_config.ConfigTestCase.test_master_id_function
unit.test_config.ConfigTestCase.test_master_pillar_roots_glob
unit.test_config.ConfigTestCase.test_minion_file_roots_glob
unit.test_config.ConfigTestCase.test_minion_id_function
unit.test_config.ConfigTestCase.test_minion_id_lowercase
unit.test_config.ConfigTestCase.test_minion_pillar_roots_glob
unit.test_config.ConfigTestCase.test_proper_path_joining
unit.test_config.ConfigTestCase.test_sha256_is_default_for_master
unit.test_config.ConfigTestCase.test_sha256_is_default_for_minion
unit.utils.test_pydsl.PyDSLRendererTestCase.test_cmd_call
unit.utils.test_pydsl.PyDSLRendererTestCase.test_compile_time_state_execution
unit.utils.test_pydsl.PyDSLRendererTestCase.test_include_extend
unit.utils.test_pydsl.PyDSLRendererTestCase.test_load_highstate
unit.utils.test_pydsl.PyDSLRendererTestCase.test_multiple_state_func_in_state_mod
unit.utils.test_pydsl.PyDSLRendererTestCase.test_nested_high_state_execution
unit.utils.test_pydsl.PyDSLRendererTestCase.test_no_state_func_in_state_mod
unit.utils.test_pydsl.PyDSLRendererTestCase.test_ordered_states
unit.utils.test_pydsl.PyDSLRendererTestCase.test_pipe_through_stateconf
unit.utils.test_pydsl.PyDSLRendererTestCase.test_repeat_includes
unit.utils.test_pydsl.PyDSLRendererTestCase.test_requisite_declarations
unit.utils.test_pydsl.PyDSLRendererTestCase.test_state_declarations
unit.utils.test_pyobjects.RendererTests.test_basic
unit.utils.test_pyobjects.RendererTests.test_context_manager
unit.utils.test_pyobjects.RendererTests.test_duplicates
unit.utils.test_pyobjects.RendererTests.test_extend
unit.utils.test_pyobjects.RendererTests.test_factory_serialization
unit.utils.test_pyobjects.RendererTests.test_import_random_password
unit.utils.test_pyobjects.RendererTests.test_import_scope
unit.utils.test_pyobjects.RendererTests.test_include
unit.utils.test_pyobjects.RendererTests.test_invalid_function
unit.utils.test_pyobjects.RendererTests.test_random_password
unit.utils.test_pyobjects.RendererTests.test_requisite_implicit_list
unit.utils.test_pyobjects.RendererTests.test_salt_data
unit.utils.test_pyobjects.RendererTests.test_serialization
unit.utils.test_pyobjects.RendererTests.test_sls_imports
integration.wheel.test_client.WheelModuleTest.test_cmd_async
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_adding_state_name_arg_for_dot_state_id
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_dot_state_id_in_requisites
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_goal_state_generation
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_implicit_require_with_goal_state
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_multilevel_relative_include_beyond_top_level
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_multilevel_relative_include_with_requisites
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_relative_include_and_extend
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_relative_include_with_requisites
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_sls_dir
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_slsdir
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_start_state_generation
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_state_config
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_state_prefix
unit.renderers.test_stateconf.StateConfigRendererTestCase.test_states_declared_with_shorthand_no_args
unit.test_loader.RawModTest.test_bad_name
unit.test_loader.RawModTest.test_basic
unit.test_cloud.MapConfTest.test_cloud_map_merge_conf
unit.modules.test_linux_sysctl.LinuxSysctlTestCase.test_persist_no_conf_failure
integration.wheel.test_key.KeyWheelModuleTest.test_gen
integration.wheel.test_key.KeyWheelModuleTest.test_list_all
unit.renderers.test_yamlex.RendererTests.test_basic
unit.renderers.test_yamlex.RendererTests.test_complex
unit.test_master.ClearFuncsTestCase.test_publish_cmd_blacklisted
unit.test_master.ClearFuncsTestCase.test_publish_eauth_authorization_error
unit.test_master.ClearFuncsTestCase.test_publish_eauth_not_authenticated
unit.test_master.ClearFuncsTestCase.test_publish_token_authorization_error
unit.test_master.ClearFuncsTestCase.test_publish_token_not_authenticated
unit.test_master.ClearFuncsTestCase.test_publish_user_authenticated_missing_auth_list
unit.test_master.ClearFuncsTestCase.test_publish_user_authorization_error
unit.test_master.ClearFuncsTestCase.test_publish_user_is_blacklisted
unit.test_master.ClearFuncsTestCase.test_publish_user_not_authenticated
unit.test_master.ClearFuncsTestCase.test_runner_eauth_authorization_error
unit.test_master.ClearFuncsTestCase.test_runner_eauth_not_authenticated
unit.test_master.ClearFuncsTestCase.test_runner_eauth_salt_invocation_error
unit.test_master.ClearFuncsTestCase.test_runner_token_authorization_error
unit.test_master.ClearFuncsTestCase.test_runner_token_not_authenticated
unit.test_master.ClearFuncsTestCase.test_runner_token_salt_invocation_error
unit.test_master.ClearFuncsTestCase.test_runner_user_not_authenticated
unit.test_master.ClearFuncsTestCase.test_wheel_eauth_authorization_error
unit.test_master.ClearFuncsTestCase.test_wheel_eauth_not_authenticated
unit.test_master.ClearFuncsTestCase.test_wheel_eauth_salt_invocation_error
unit.test_master.ClearFuncsTestCase.test_wheel_token_authorization_error
unit.test_master.ClearFuncsTestCase.test_wheel_token_not_authenticated
unit.test_master.ClearFuncsTestCase.test_wheel_token_salt_invocation_error
unit.test_master.ClearFuncsTestCase.test_wheel_user_not_authenticated
setUpClass (unit.states.test_boto_apigateway.BotoApiGatewayTestCase)
setUpClass (unit.states.test_boto_apigateway.BotoApiGatewayUsagePlanAssociationTestCase)
setUpClass (unit.states.test_boto_apigateway.BotoApiGatewayUsagePlanTestCase)
setUpClass (unit.states.test_boto_cloudtrail.BotoCloudTrailTestCase)
setUpClass (unit.states.test_boto_cloudwatch_event.BotoCloudWatchEventTestCase)
setUpClass (unit.states.test_boto_cognitoidentity.BotoCognitoIdentityTestCase)
setUpClass (unit.states.test_boto_elasticsearch_domain.BotoElasticsearchDomainTestCase)
setUpClass (unit.states.test_boto_iot.BotoIoTPolicyTestCase)
setUpClass (unit.states.test_boto_iot.BotoIoTThingTypeTestCase)
setUpClass (unit.states.test_boto_iot.BotoIoTTopicRuleTestCase)
setUpClass (unit.states.test_boto_lambda.BotoLambdaAliasTestCase)
setUpClass (unit.states.test_boto_lambda.BotoLambdaEventSourceMappingTestCase)
setUpClass (unit.states.test_boto_lambda.BotoLambdaFunctionTestCase)
setUpClass (unit.states.test_boto_s3_bucket.BotoS3BucketTestCase)
setUpClass (unit.states.test_boto_vpc.BotoVpcInternetGatewayTestCase)
setUpClass (unit.states.test_boto_vpc.BotoVpcRouteTableTestCase)
setUpClass (unit.states.test_boto_vpc.BotoVpcSubnetsTestCase)
setUpClass (unit.states.test_boto_vpc.BotoVpcTestCase)
setUpClass (unit.utils.test_schedule.ScheduleTestCase)
setUpClass (unit.utils.test_reactor.TestReactor)
setUpClass (unit.test_loader.LazyLoaderDeepSubmodReloadingTest)
setUpClass (unit.test_loader.LazyLoaderModulePackageTest)
setUpClass (unit.test_loader.LazyLoaderOptimizationOrderTest)
setUpClass (unit.test_loader.LazyLoaderReloadingTest)
setUpClass (unit.test_loader.LazyLoaderSingleItem)
setUpClass (unit.test_loader.LazyLoaderSubmodReloadingTest)
setUpClass (unit.test_loader.LazyLoaderTest)
setUpClass (unit.test_loader.LazyLoaderVirtualAliasTest)
setUpClass (unit.test_loader.LazyLoaderVirtualDisabledTest)
setUpClass (unit.test_loader.LazyLoaderVirtualEnabledTest)
setUpClass (unit.test_loader.LazyLoaderWhitelistTest)
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_equal1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_equal2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_false1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_false2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater3
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater_equal1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater_equal2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater_equal3
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_in1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_in2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less3
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less_equal1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less_equal2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less_equal3
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_not_equal1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_not_equal2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_not_in1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_not_in2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_true1
unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_true2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test_call_salt_command
unit.modules.test_saltcheck.LinuxSysctlTestCase.test_call_salt_command2
unit.modules.test_saltcheck.LinuxSysctlTestCase.test_run_test_1
unit.utils.test_network.NetworkTestCase.test__generate_minion_id_with_unicode_in_etc_hosts
unit.utils.test_network.NetworkTestCase.test_generate_minion_id
unit.utils.test_network.NetworkTestCase.test_generate_minion_id_with_long_hostname
unit.utils.test_timed_subprocess.TestTimedSubprocess.test_timedproc_with_shell_true_and_list_args
unit.states.test_winrepo.WinrepoTestCase.test_genrepo
integration.states.test_supervisord.SupervisordTest.test_dead_notexists
integration.states.test_supervisord.SupervisordTest.test_dead_removed
integration.states.test_supervisord.SupervisordTest.test_dead_started
integration.states.test_supervisord.SupervisordTest.test_dead_stopped
integration.states.test_supervisord.SupervisordTest.test_restart_needsupdate
integration.states.test_supervisord.SupervisordTest.test_restart_notexists
integration.states.test_supervisord.SupervisordTest.test_restart_started
integration.states.test_supervisord.SupervisordTest.test_restart_stopped
integration.states.test_supervisord.SupervisordTest.test_running_needsupdate
integration.states.test_supervisord.SupervisordTest.test_running_notexists
integration.states.test_supervisord.SupervisordTest.test_running_started
integration.states.test_supervisord.SupervisordTest.test_running_stopped
unit.utils.test_pyobjects.MapTests.test_map
unit.utils.test_pyobjects.MapTests.test_map_with_priority
unit.modules.test_yumpkg.YumTestCase.test_latest_version_with_options
unit.modules.test_yumpkg.YumTestCase.test_list_repo_pkgs_with_options
unit.modules.test_yumpkg.YumTestCase.test_list_upgrades_dnf
unit.modules.test_yumpkg.YumTestCase.test_list_upgrades_yum
unit.modules.test_yumpkg.YumTestCase.test_refresh_db_with_options
unit.modules.test_zypperpkg.ZypperTestCase.test_remove_purge
unit.modules.test_kernelpkg_linux_yum.YumKernelPkgTestCase.test_remove_error
unit.modules.test_kernelpkg_linux_yum.YumKernelPkgTestCase.test_remove_success

**Comment by s0undt3ch** [comment] 2019-05-29 12:18
These failures will most likely be fixed by https://github.com/saltstack/salt/pull/53297

**Comment by DmitryKuzmenko** [comment] 2019-05-29 13:15
Let's see. Thank you!

**Comment by rares-pop** [comment] 2019-05-29 13:51
I don't know what @s0undt3ch change does, but there is a fair amount of leaks when using TCP.
Here are some attempts to fix some of them (not all):
#52260
#52259

Also, in case you start salt-api on Windows, a good part of leaks are solved by:
#52471

Attn @dwoz, @twangboy

**Comment by s0undt3ch** [comment] 2019-05-29 14:35
Yeah, I should have been more clear.
The list of failures above should decrease once my PR is in.
It just makes sure we have the required dependencies to run the tests.

**Comment by rares-pop** [comment] 2019-05-29 14:40
@s0undt3ch - why are the tcp tests related to zmq?

**Comment by s0undt3ch** [comment] 2019-05-29 15:18
They aren't.
But the way we previously tested meant we always had all deps installed, so, only now we see places where salt needs to be refactored in order not to depend on ZMQ

**Comment by KChandrashekhar** [comment] 2019-06-26 17:10
With the swap file changes that @s0undt3ch did the tests are finishing. Hence the issue is no longer a blocker for 2019.2.1 The memory leak will be investigated in Neon release

**Comment by DmitryKuzmenko** [comment] 2019-06-28 05:49
The same just happened on Debian 8 py2 tests of 2019.2 branch
https://jenkinsci.saltstack.com/job/2019.2/job/salt-debian-8-py2/144/testReport/junit/unit.transport.test_zeromq/PubServerChannel/test_publish_to_pubserv_tcp/
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/transport/test_zeromq.py", line 503, in test_publish_to_pubserv_tcp
    'log_queue': salt.log.setup.get_multiprocessing_logging_queue()
  File "/tmp/kitchen/testing/salt/transport/zeromq.py", line 964, in pre_fork
    process_manager.add_process(self._publish_daemon, kwargs=kwargs)
  File "/tmp/kitchen/testing/salt/utils/process.py", line 427, in add_process
    process.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
BTW, previous build of the same revision has no this issue.

**Closed** 2019-11-15 17:09 UTC
Labels: 2019.2, Neon, Test Failure
