### ISSUE TITLE
[FEATURE REQUEST] add support for Fedora 39

### ISSUE THREAD

**Issue by jeff350** [saltstack/salt#65859] opened 2024-01-14 00:58 UTC
**Is your feature request related to a problem? Please describe.**
Fedora 39 was released Nov 7th 2023, Support has not been added for salt.

**Describe the solution you'd like**
Please update documentation to add Fedora 39 as supported and provide builds.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by ScriptAutomate** [comment] 2024-02-28 17:18
Has been merged into `3006.x`, and will be included in future merge-forwards into `3007.x` and `master`.
Closing as complete.

**Closed by ScriptAutomate** 2024-02-28 17:18 UTC
Labels: Feature, Packaging, Platform, Tests, package-repo

**Comment by defanator** [comment] 2024-04-01 07:16
Was it actually released to onedir repos? There is no `39` here - https://repo.saltproject.io/salt/py3/fedora/. Also, instructions do not mention it as well - https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/fedora.html.

cc/ @dwoz @ScriptAutomate

**Comment by ScriptAutomate** [comment] 2024-04-02 15:31
> from @defanator :
> Was it actually released to onedir repos? There is no `39` here - https://repo.saltproject.io/salt/py3/fedora/. Also, instructions do not mention it as well - https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/fedora.html.

Looks like what happened was:

- The change was merged in, but not included in the 3006.7 release
- The change was merged in, but also not included in the 3007.0 release

Which means one of two things is going to happen:

- Fedora 39 will be included in the next 3006.x and/or 3007.x release, OR
- Fedora 40 will be introduced, and the Fedora 39 will have been skipped :sweat_smile: 
  - #66300

It will depend upon the release timelines with Salt. Introducing new operating systems has been simplified some more, so future Fedora releases will see faster implementation of support in our CI/CD and published packages.

As part of looking into this, there were some fixes to our nightlies that will also show - in the coming week or two - published packages of Fedora 39 in the nightlies. I'll update in this issue upon confirmation that they are publishing as expected.

**Comment by ScriptAutomate** [comment] 2024-04-03 16:17
Update: Confirmed that nightlies publishing are including Fedora 39
- https://repo.saltproject.io/salt-dev/3006.x/2024-04-03/salt/py3/fedora/

Though, my previous statement will still be valid, depending on release timelines:

> Which means one of two things is going to happen:
>
> - Fedora 39 will be included in the next 3006.x and/or 3007.x release, OR
> - Fedora 40 will be introduced, and the Fedora 39 will have been skipped 😅
>   - https://github.com/saltstack/salt/issues/66300

**Comment by ScriptAutomate** [comment] 2024-05-01 22:21
@defanator 

Latest Salt v3006.8 release included Fedora 39:

- https://repo.saltproject.io/salt/py3/fedora/39/

Since Fedora 40 came out recently, that is now in-progress for replacing Fedora 39 in future releases depending on when next point releases come out for v3007.x and v3006.x
