### ISSUE TITLE
Strange "Permission denied" error with "/etc/apache2/sites-available/default-ssl.conf" with salt-ssh

### ISSUE THREAD

**Issue by eht16** [saltstack/salt#25721] opened 2015-07-25 11:28 UTC
I noticed a strange error when I tried to write a state which manages `/etc/apache2/site-available/default-ssl.conf`.
The state failed with:

```
Permission denied for host <hostname>, do you want to deploy the salt-ssh key? (password required):
```

This can be more easily reproduced by simply reading the file from the remote system: `salt-ssh '*' -r 'cat /etc/apache2/sites-available/default-ssl.conf'` this gives also:

```
Permission denied for host <hostname>, do you want to deploy the salt-ssh key? (password required):
[Y/n]
```

I can read other files easily this way, and on the remote system, I can read the default-ssl.conf also with the user I'm using with salt-ssh, so it is not a permission problem.
It rather seems to me that something in this file is kind of interpreted by salt-ssh or during the transfer or so. Renaming the file and also moving into another location didn't help, so I guess it is related to the contents but couldn't find anything obvious which is causing this.

Version information:
- Client: `salt-ssh 2015.5.3 (Lithium)` installed in a virtualenv using pip
- Remote system: Ubuntu 14.04 LTS

Full debug log:

```
[INFO    ] Loading Saltfile from '/tmp/salttest/Saltfile'
[DEBUG   ] Reading configuration from /tmp/salttest/Saltfile
[DEBUG   ] Reading configuration from /tmp/salttest/master
[DEBUG   ] Configuration file path: /tmp/salttest/master
[DEBUG   ] LazyLoaded flat.targets
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Jinja search path: ['/tmp/salttest/cache/files/base']
[DEBUG   ] Rendered data from file: /tmp/salttest/roster:
<hostname>:
  host: <ip_address>
  port: 22
  user: enrico

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('<hostname>', OrderedDict([('host', '<ip_address>'), ('port', 22), ('user', 'enrico')]))])
[INFO    ] minions list: {'<hostname>': OrderedDict([('host', '<ip_address>'), ('port', 22), ('user', 'enrico')])}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Executing command: ssh <ip_address>  -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/tmp/salttest/pki/ssh/salt-ssh.rsa -o User=enrico  cat\ \/etc\/apache2\/sites-available\/default\-ssl\.conf
[DEBUG   ] Child Forked! PID: 25328  STDOUT_FD: 8  STDERR_FD: 10
[DEBUG   ] Terminal Command: /bin/sh -c ssh <ip_address>  -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/tmp/salttest/pki/ssh/salt-ssh.rsa -o User=enrico  cat\ \/etc\/apache2\/sites-available\/default\-ssl\.conf
Permission denied for host <hostname>, do you want to deploy the salt-ssh key? (password required):
[Y/n] 
```

This might be related to https://github.com/saltstack/salt/issues/18310#issuecomment-98094716 as the error message is the same.

**Comment by jfindlay** [comment] 2015-07-27 14:44
@eht16, thanks for the report.  What happens if you replace the contents of the file with nothing or something else?  Are there any extended attributes on the file?

**Comment by eht16** [comment] 2015-07-27 15:24
The file has no special/extended attributes, no acls. Plain 0644.
Replacing the contents by something like "12345" makes the `-r cat` working as expected, so it pretty much must be related to original contents.

You can easily reproduce this by just copying the contents into a file on any remote server and trying to retrieve the contents via salt-ssh.
For reference, I put the contents of the file on http://pastebin.geany.org/8Oemn/. Note. that this is the stock Apache2 config of the Ubuntu 14.04 apache2 package.

**Comment by jfindlay** [comment] 2015-07-27 16:42
@eht16, thanks for the extra info; that is strange.

**Comment by anlutro** [comment] 2015-08-04 18:47
The file contains the string "password:", which makes salt-ssh think it's being prompted for a password.

**Comment by anlutro** [comment] 2015-08-04 19:09
salt.client.ssh.shell does a simple search for a password string [here](https://github.com/saltstack/salt/blob/b794dbf7e463efbd943d425f3782d0957126d851/salt/client/ssh/shell.py#L346), using a regex defined [here](https://github.com/saltstack/salt/blob/b794dbf7e463efbd943d425f3782d0957126d851/salt/client/ssh/shell.py#L23).

I can't see any way to check if the VT is waiting for input or not, but a crude fix may be to check if there's more in stdout before aborting, or possibly changing the regex to only match if the line *ends* with a password prompt-like string, not if it's in the middle of some output.

**Comment by anlutro** [comment] 2015-08-04 19:11
Also, the bug is easily reproduced via `salt-ssh minion -r 'echo password: foobar' -l trace`

**Comment by jfindlay** [comment] 2015-08-04 20:10
@anlutro, awesome, thanks for finding that.

**Comment by bernieke** [comment] 2016-02-29 13:28
I just ran up against this (very nasty!) problem. To get around it I just commented out that block of code in the version we deploy.

May I inquire why you're even using ssh through subprocess, instead of just using an actual ssh library like paramiko?

**Comment by jfindlay** [comment] 2016-02-29 18:10
@bernieke, what version of salt are you using?  I am not aware of the design decisions involved with the choice of ssh tools.  I wouldn't be surprised if it is because paramiko does not provide desired/enough features for the extensive needs of salt-ssh to make salt work as seamlessly as possible over ssh.

**Comment by bernieke** [comment] 2016-03-01 07:41
We're using 2015.8.1 with that password: scraping else block commented out as well as my fix for this ticket: https://github.com/saltstack/salt/issues/3436 (https://github.com/Awingu/salt/commit/53285f778164c1cb471fd04050f3917b0a47ef2e)

**Comment by anlutro** [comment] 2018-04-01 19:15
This might have been fixed? I'm not sure.

If I run `salt-ssh minion -r 'echo password: foobar' -l trace` now I get asked if I want to deploy the SSH key despite it already being deployed, so that's weird - but `salt-ssh minion cmd.run 'echo password: foobar' -l trace` works.

**Comment by sagetherage** [comment] 2021-03-01 21:44
There is a PR for this, but it is failing tests and has many merge conflicts and needs more review. I will attempt to plan for this in Silicon

**Closed** 2022-01-17 03:03 UTC
Labels: Bug, severity-medium, Core, Salt-SSH
