### ISSUE TITLE
KeyError for pkg.installed state for python-pip (2015.5.3)

### ISSUE THREAD

**Issue by buddyp450** [saltstack/salt#27687] opened 2015-10-05 18:01 UTC
Running sudo apt-get install python-pip on the salt minion was all that was needed to fix but curious as to why the minion function raised an exception? Debug from the salt-minion below:

    [DEBUG   ] Could not LazyLoad pip.installed
    [WARNING ] The minion function caused an exception 
    Traceback (most recent call last):
       File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 523, in highstate
         whitelist=kwargs.get('whitelist')
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2968, in call_highstate
        return self.state.call_high(high)
       File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
        self._mod_init(low)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
        self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
        raise KeyError(key)
    KeyError: 'pip.installed'

If more debug information is required please let me know and I will obtain it.

**Comment by rallytime** [comment] 2015-10-05 18:05
@buddyp450 Thanks very much for this report. This is a actually a duplicate of #26280 and #26882. As such, I am going to go ahead a close this. 

However, note that I have recently submitted a fix for this error in #27681. This bug is also already fixed in the 2015.8.0 release.

**Closed by rallytime** 2015-10-05 18:05 UTC
Labels: Bug, Core, Duplicate, High Severity, P2

**Comment by dragon788** [comment] 2016-01-18 01:52
@buddyp450 According to rallytime on another issue the PPA lags behind their own repository. https://github.com/saltstack/salt/issues/30145#issuecomment-170360607
