### ISSUE TITLE
master's os system is less than minion's os system

### ISSUE THREAD

**Issue by yyf1986** [saltstack/salt#28397] opened 2015-10-29 08:53 UTC
My master is run on RHEL 6.5,and I have some minions run on 'CentOS Linux release 7.0.1406 (Core)'.
when I use 'salt-ssh' to install salt-minion on these minions.
The following erros like:
stderr:
        Traceback (most recent call last):
          File "/tmp/.root_228c1c__salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_228c1c__salt/salt/scripts.py", line 221, in salt_call
            import salt.cli.call
          File "/tmp/.root_228c1c__salt/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/tmp/.root_228c1c__salt/salt/utils/parsers.py", line 28, in <module>
            import salt.config as config
          File "/tmp/.root_228c1c__salt/salt/config.py", line 28, in <module>
            import salt.utils.network
          File "/tmp/.root_228c1c__salt/salt/utils/network.py", line 26, in <module>
            from salt._compat import subprocess
          File "/tmp/.root_228c1c__salt/salt/_compat.py", line 22, in <module>
            import xml.etree.cElementTree as ElementTree
          File "/tmp/.root_228c1c__salt/xml/etree/cElementTree.py", line 3, in <module>
            from _elementtree import *
          File "<string>", line 147, in <module>
        AttributeError: 'module' object has no attribute 'fromstringlist'

**Comment by ssgward** [comment] 2015-10-29 20:19
@yyf1986 - what salt version is on your master and minions? Same version on both or master is one salt version and minions are another salt version?

**Comment by yyf1986** [comment] 2015-10-30 01:49
My master version is 2015.5.5.I only use salt-ssh to deploy salt-minion on new machine.

**Comment by cachedout** [comment] 2015-11-03 14:50
This is a duplicate of https://github.com/saltstack/salt/issues/26584. Please see the workaround there and follow any ongoing progress with this issue there. I'm closing this one as a duplicate.

**Closed by cachedout** 2015-11-03 14:50 UTC
