### ISSUE TITLE
Targeting by matching ip address doesn't work

### ISSUE THREAD

**Issue by fantasy86** [saltstack/salt#30962] opened 2016-02-06 04:00 UTC
salt -S <IP>  or 'S@<IP>' in nodegroups  doesn't work.
I'm using salt version 2015.8.3 (Beryllium)

**Comment by fantasy86** [comment] 2016-02-06 04:10
15e85184dc2135b69eb90d46b28063a5f3a3b39c `_check_ipcidr_minions` in this commit:
1. changed `grains` to `this.opts['grains'] ` so the match doesn't work.
2. check ip_network first and then ip_address, but one ipv4 address is also a ip network in the form <IP>/32, so single address always treated as a network.

**Comment by jfindlay** [comment] 2016-02-08 16:18
@fantasy86, thanks for reporting.  @The-Loeki, do you have any ideas on this one?

**Comment by rallytime** [comment] 2016-02-12 23:08
@fantasy86 Thank you for finding the commit where this broke. I can confirm that #24282 is the culprit. However, this issue is a duplicate of #29188. I'm going to close this in favor of the older issue so we can track progress all in one place.

**Closed by rallytime** 2016-02-12 23:08 UTC
Labels: Bug, Core, Duplicate, High Severity, P3
