### ISSUE TITLE
2015.8.7 pkg.installed fails using version if epoch is set.

### ISSUE THREAD

**Issue by stepherg** [saltstack/salt#31517] opened 2016-02-26 17:42 UTC
Trying to move from 2015.5.5-1 to 2015.8.7-1, I found the following issue:

Installing RPMs by version that have an 'epoch' set (like sensu) report install failure apparently because the version returned by parse_pkginfo() is prepending the epoch to the version that's used by _verify_install(). Although the installation actually succeeds, it causes problems with other states that have the install as a dependency.

I edited my local version of rpm.py to remove the addition of the 'epoch' field to the version and the installation worked as expected. Would it be safe to do this as a fix or will that create other issues? Is this a known problem in this version?

Thank you.

**Failure case:**

----------
          ID: sensu.pkg
    Function: pkg.installed
        Name: sensu
      Result: False
     Comment: The following packages failed to install/update: sensu=0.22.0-1
     Started: 16:51:34.022065
    Duration: 5048.761 ms
     Changes:   
              ----------
              sensu:
                  ----------
                  new:
                      1:0.22.0-1
                  old:

**Comment by jfindlay** [comment] 2016-02-26 18:27
@stepherg, thanks for reporting.  This is a duplicate of #31014.

**Closed by jfindlay** 2016-02-26 18:27 UTC
Labels: Duplicate
