### ISSUE TITLE
Multiple DeprecationWarning with python3.7 during Openmediavault migration

### ISSUE THREAD

**Issue by mplm17** [saltstack/salt#55976] opened 2020-01-25 21:41 UTC
### Description of Issue
```
2020-01-25 22:18:11,899 [py.warnings      :110 ][WARNING ][15029] /usr/lib/python3/dist-packages/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping, namedtuple

2020-01-25 22:18:11,966 [py.warnings      :110 ][WARNING ][15029] /usr/lib/python3/dist-packages/salt/utils/jinja.py:638: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(lst1, collections.Hashable) and isinstance(lst2, collections.Hashable):

2020-01-25 22:18:12,103 [py.warnings      :110 ][WARNING ][15029] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)
```

### Setup
This is a basic configuration, only salt-common and salt-minion are installed as openmediavault's dependencies: 
```
ii  salt-common                                                 2019.2.2+ds-1                                                  all          shared libraries that salt requires for all packages
ii  salt-minion                                                 2019.2.2+ds-1                                                  all          client package for salt, the distributed remote execution system
```
```
# apt-cache policy openmediavault
openmediavault:
  Installé : 5.2.4-1
  Candidat : 5.2.4-1
 Table de version :
 *** 5.2.4-1 995
        995 http://packages.openmediavault.org/public usul/main amd64 Packages
        500 https://openmediavault.github.io/packages usul/main amd64 Packages
        100 /var/lib/dpkg/status
```
### Steps to Reproduce Issue
It's happening during openmediavault migration from version 5.0.3 to 5.2.0. It seems that dpkg cannot configure openmediavault because of these Salt errors:
```
#apt-get upgrade
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Calcul de la mise à jour... Fait
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
1 partiellement installés ou enlevés.
Après cette opération, 0 o d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n]
Paramétrage de openmediavault (5.2.4-1) ...
Creating configuration database ...
Migrating configuration database ...
  Running migration conf_5.0.0
WARNING: The node 'timemachine' already exists at XPath '/config/services/smb/shares/share'.
  Running migration conf_5.0.3
  Running migration conf_5.2.0
Setting up Salt environment ...
Setting up system ...
[WARNING ] /usr/lib/python3/dist-packages/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping, namedtuple

[WARNING ] /usr/lib/python3/dist-packages/salt/utils/jinja.py:638: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(lst1, collections.Hashable) and isinstance(lst2, collections.Hashable):

[WARNING ] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)

Processing system modifications ...
dpkg: erreur de traitement du paquet openmediavault (--configure) :
 installed openmediavault package post-installation script subprocess returned error exit status 1
Des erreurs ont été rencontrées pendant l'exécution :
 openmediavault
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
### Versions Report
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10.2
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.2
```

**Comment by Ch3LL** [comment] 2020-01-29 17:14
thanks i'll add this issue to our supporting python3.8 epic issue here: https://github.com/saltstack/salt/issues/55835  we will need to get these cleaned up.

**Comment by bdrung** [comment] 2020-01-30 12:21
This is a duplicate of #50911 (which I have merge request #56027 for it).

**Comment by sferia82** [comment] 2020-02-11 10:46
any solution? It also gave me that error in the installation and it is coming out while I am using the web portal.

**Comment by Ch3LL** [comment] 2020-03-24 18:08
@bdrung looks like its a duplicate only for the `formatargspec` warning. looks like there are others that need to be cleaned up:

```
2020-01-25 22:18:11,899 [py.warnings      :110 ][WARNING ][15029] /usr/lib/python3/dist-packages/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping, namedtuple

2020-01-25 22:18:11,966 [py.warnings      :110 ][WARNING ][15029] /usr/lib/python3/dist-packages/salt/utils/jinja.py:638: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(lst1, collections.Hashable) and isinstance(lst2, collections.Hashable):
```

@sferia82 there is not a solution currently for the warnings above. we just need to clean them up. this is currently on my backlog

**Comment by bdrung** [comment] 2020-03-26 16:40
@Ch3LL The remaining warnings are addressed in pull request #56031

**Comment by Ch3LL** [comment] 2020-03-31 13:17
thanks @bdrung ! helps me out a lot!

**Comment by Ch3LL** [comment] 2020-03-31 13:19
i'll go ahead and close and we can keep communications on PR

**Closed by Ch3LL** 2020-03-31 13:19 UTC
Labels: Bug, High Severity, P2

**Comment by mplm17** [comment] 2020-03-31 13:26
Thanks you all for the help!
