### ISSUE TITLE
Targeting non-existent minion with list

### ISSUE THREAD

**Issue by saltuser** [saltstack/salt#33496] opened 2016-05-25 13:12 UTC
Hi

When targeting multiple minions as a list, (described [here](https://docs.saltstack.com/en/latest/topics/targeting/globbing.html#lists)), salt silently ignores the fact that some ID-s were non-existent.
```
$salt -v -L 'RANDOM,RANDOM2,RANDOM3,SMC7-SANDBOX' test.version
Executing job with jid 20160525160203815674
-------------------------------------------

SMC7-SANDBOX:
    2015.5.8
```

Yet when none of the minionID-s match an clear error message is given.
```
salt -v -L 'RANDOM,RANDOM2,RANDOM3' test.version
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

### Setup
Master version
```
$salt --version
salt 2015.8.8.2 (Beryllium)
```

Is it meant to behave this way? I think salt should warn the user if some minionID was not found.
If the command output is several pages long, the fact that some minionID-s had typos and were silently skipped can be quite annoying.

Thank you.

**Comment by jf** [comment] 2016-05-25 15:18
+1 here; makes sense and would be nice! :)

**Comment by Ch3LL** [comment] 2016-05-25 16:26
@saltuser @jf  looks like this is a duplicate of #14977

I will close this as a duplicate and we can track this feature request on that issue. Feel free to comment on that issue as well :)

**Closed by Ch3LL** 2016-05-25 16:26 UTC
