### ISSUE TITLE
[2017.7.0rc1] file.line triggers warning that seems wrong.

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#42190] opened 2017-07-06 23:14 UTC
### Description of Issue/Question

As mentioned https://docs.saltstack.com/en/develop/ref/states/all/salt.states.file.html#salt.states.file.line file.line takes the 'content' parameter.

```
isotope.pkgsrc.sandbox::hook:
  file.line:
    - name: /data/pkgbuild/scripts/run-sandbox
    - mode: ensure
    - before: "/usr/sbin/chroot ${chrootdir} /bin/bash --login"
    - content: "/data/keys/setup-env ${chrootdir}"
```

Now generates a warning:
```
    2017-07-07 01:02:15,901 [salt.loaded.int.states.file                                            ][WARNING ][25062] State for file: /data/pkgbuild/scripts/run-sandbox - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
```

It as the file was already in the good state, I am not 100% the state still works.

### Versions Report
```yaml
Salt Version:
           Salt: 2017.7.0rc1

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.1.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: 1.6.7
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec 31 2016, 10:50:46)
   python-gnupg: 2.2.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.6
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

**Comment by gtmanfred** [comment] 2017-07-07 14:44
I just checked, it was caused by this pr https://github.com/saltstack/salt/pull/39592

We should get this fixed so that this actually reports changes to the user and file_mode, but it does look like it is working even with the error message.

Thanks,
Daniel

**Comment by waynew** [comment] 2019-06-27 18:30
From what I can tell, this was fixed in https://github.com/saltstack/salt/commit/2fd172e07bca3e6379ddac5095130231ff7c7745

In case future someone wonders 😂

**Closed by waynew** 2019-06-27 18:30 UTC
Labels: Bug, Core, Medium Severity, P1, State Module
