### ISSUE TITLE
AttributeError: 'Minion' object has no attribute 'remove_periodic_callbback'

### ISSUE THREAD

**Issue by paladox** [saltstack/salt#54795] opened 2019-09-27 11:09 UTC
### Description of Issue

Upgrading to salt 2019.2.1 from 2019.2.0 is causing:

```
2019-09-27 10:55:02,759 [salt.minion      :2313][ERROR   ][11194] This Minion is already running. Not running Minion.tune_in()
2019-09-27 10:55:02,899 [salt.minion      :1049][CRITICAL][11194] Unexpected error while connecting to misc4.miraheze.org
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 1027, in _connect_minion
    )
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2733, in tune_in
    self.periodic_callbacks['ping'] = tornado.ioloop.PeriodicCallback(ping_master, ping_interval * 1000)
AttributeError: 'Minion' object has no attribute 'remove_periodic_callbback'
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

(We use debian 9)

We use https://github.com/miraheze/puppet/tree/master/modules/salt / https://github.com/miraheze/puppet/tree/master/modules/role/manifests/salt

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Install salt-minion, watch the logs && see that the salt master has high load.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

I downgraded from 2019.2.1 back to 2019.2.0.

**Comment by dwoz** [comment] 2019-09-27 14:41
duplicate of #54776

**Comment by hedrickbt** [comment] 2019-10-01 20:05
I have created a support ticket for this:
https://help.saltstack.com/hc/en-us/requests/4183

**Comment by waynew** [comment] 2019-10-01 20:55
Closing this, as it's a duplicate

**Closed by waynew** 2019-10-01 20:55 UTC
Labels: Duplicate
