### ISSUE TITLE
Saltstack 2019 no longer showing diff of changes when test=True

### ISSUE THREAD

**Issue by rsuarezsoto** [saltstack/salt#52218] opened 2019-03-17 10:40 UTC
Neither `salt-call` nor `salt` show a diff of the changes that will be made since updating to Saltstack 2019.2.0. Before the update, this command:

```
salt-call state.highstate --state-output=changes test=True
```
Would show a preview of the changes that would be made to each file (if any) in "diff" form. But now just the comment "The file <whatever> is set to be changed" is shown. This is quite inconvenient, because you can't know beforehand if the changes that are to be made are the ones you want or some other that you didn't expect.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-1077-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by tbaker57** [comment] 2019-03-18 01:15
I think this is related to #51932

**Comment by lordcirth** [comment] 2019-03-18 14:58
Pretty sure this is a duplicate of #51932 , in fact.

**Comment by dwoz** [comment] 2019-03-18 20:12
@rsuarezsoto I'm closing this as it is a duplicate. Please check #51932 for the status of this bugfix. Thanks!

**Closed by dwoz** 2019-03-18 20:12 UTC
Labels: Duplicate
