### ISSUE TITLE
salt-call cannot send custom events without Minion daemon running

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#26411] opened 2015-08-17 23:02 UTC
Reproduced on 2015.2 and develop (6b109be01892).

No minion daemon running:

```
% salt-call event.send foo1
```

Event bus on the master:

```
salt/job/20150817165953179552/ret/jerry {
    "_stamp": "2015-08-17T22:59:53.181536",
    "arg": [
        "foo1"
    ],
    "cmd": "_return",
    "fun": "event.send",
    "fun_args": [
        "foo1"
    ],
    "id": "jerry",
    "jid": "20150817165953179552",
    "retcode": 0,
    "return": true,
    "tgt": "jerry",
    "tgt_type": "glob"
}
```

With minion daemon running:

```
% salt-call event.send foo2
```

Event bus on the master:

```
foo2    {
    "_stamp": "2015-08-17T23:01:43.232102",
    "cmd": "_minion_event",
    "data": {
        "__pub_fun": "event.send",
        "__pub_jid": "20150817170143221319",
        "__pub_pid": 33743,
        "__pub_tgt": "salt-call"
    },
    "id": "jerry",
    "pretag": null,
    "tag": "foo2"
}
salt/job/20150817170143256311/ret/jerry {
    "_stamp": "2015-08-17T23:01:43.258510",
    "arg": [
        "foo2"
    ],
    "cmd": "_return",
    "fun": "event.send",
    "fun_args": [
        "foo2"
    ],
    "id": "jerry",
    "jid": "20150817170143256311",
    "retcode": 0,
    "return": true,
    "tgt": "jerry",
    "tgt_type": "glob"
}
```

**Comment by tsharpe** [comment] 2015-08-17 23:04
Sorry I pointed out the regression error in the code. But for the record, this was @UtahDave suggestion.

/me blames UtahDave.

**Comment by Snergster** [comment] 2015-10-18 16:47
well after fighting through many a tornado issue to actually get up to 2015.8.1 I then slammed into this head first.  Any update on either fixing the regression or getting whatever the breaking commit was yanked out?

**Comment by rickh563** [comment] 2015-10-19 16:42
ZD-475

**Comment by cachedout** [comment] 2015-10-20 20:02
Yup, this is awfully broken.

The issue here is that the way this is written assumes a running minion (obviously). A simple patch illustrates an obviously contrived "fix".

```

diff --git a/salt/modules/event.py b/salt/modules/event.py
index d1c76f0..2508f7c 100644
--- a/salt/modules/event.py
+++ b/salt/modules/event.py
@@ -50,8 +50,8 @@ def fire_master(data, tag, preload=None):
         except Exception:
             pass
         return True
-
-    if preload:
+    preload={}
+    if True:
         # If preload is specified, we must send a raw event (this is
         # slower because it has to independently authenticate)
         load = preload
```

So, we just need to detect that this is being run in masterless mode and then spin up a channel back to the master to deliver the load. Should be straightforward. @Snergster I can have something over to you in the morning that accomplishes this.

**Comment by cachedout** [comment] 2015-10-21 20:06
I thought the above solution would work but it won't because there is no clean way that I can find to detect whether or not a minion is running from the perspective of salt-call. Still investigating.

**Comment by cachedout** [comment] 2015-10-26 15:57
Resolved by #28263

**Comment by Snergster** [comment] 2015-10-26 16:32
This fix works for me…..any issues with this also getting merged on 2015.8  ?

thanks

**Comment by cachedout** [comment] 2015-10-26 16:56
@Snergster It will be merged forward and will be present in 2015.8.2.

**Comment by tsharpe** [comment] 2015-10-26 17:18
Thanks Mike.

**Comment by cachedout** [comment] 2015-10-26 17:20
@tsharpe Sure thing. Happy to help.

**Closed** 2015-11-05 21:19 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P3, Regression, ZD
