### ISSUE TITLE
file.managed ignores http_proxy settings when running salt-call

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt#27285] opened 2015-09-21 19:27 UTC
I'm running the following salt state:

```yaml
docker-compose:
  file.managed:
    - name: /usr/local/bin/docker-compose
    - mode: 755
    - source: https://github.com/docker/compose/releases/download/1.3.1/docker-compose-Linux-x86_64
    - source_hash: sha1=948e13fdf9f552575a1760c7a42bb79ef4f6ff0a
```

using `sudo -E salt-call --local --config-dir=./ state.highstate`

with my proxy settings set locally, in network settings (ubuntu) and in /etc/environment. Regardless of all of these settings, the download is timing out, despite the fact that this easily resolves and all other commands work fine, including:

```yaml
rust-nightly:
  cmd.run:
    - name: curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly -y
```

**Comment by DavidJFelix** [comment] 2015-09-21 19:28
Version is Ubuntu 14.10, I'm using the PPA, version salt-call 2015.5.2 (Lithium).

**Comment by jfindlay** [comment] 2015-09-22 19:01
@DavidJFelix, thanks for the report.  I'm going to close this as a duplicate of #23617.

**Closed by jfindlay** 2015-09-22 19:01 UTC
Labels: Duplicate
