### ISSUE TITLE
master job cache does not fall back if db is not available (returner is not available)

### ISSUE THREAD

**Issue by pitatus** [saltstack/salt#21449] opened 2015-03-09 21:15 UTC
Using the following contents in master config file, 
```
mysql.host: 'IP of remote db'
mysql.user: 'myuser'
mysql.pass: 'mypass'
mysql.db: 'mydb'
mysql.port: 3306
master_job_cache: mysql
event_return: mysql
```
if db is not available test.ping will fail with the following:
```
# salt '*' test.ping
[ERROR   ] Salt request timed out. If this error persists, worker_threads may need to be increased.
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```
master log file contents:
```
2015-03-09 14:55:04,179 [salt.client      ][WARNING ][7215] Returner unavailable: MySQL returner could not connect to 
database: (1045, "Access denied for user 'user'@'localhost' (using password: YES)")
```
if master_job_cache and event_return entries are remarked in master config then operation will continue normally.

```
           Salt: 2015.2.0rc1-125-g5fee4a2
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by UtahDave** [comment] 2015-03-10 00:24
I can confirm that I've seen this behavior. The salt master just stops working. At a minimum it should log the error and continue. Optimally, it would cache all the jobs in the local job cache and then upload them to whatever database once the database comes back online.

**Comment by cachedout** [comment] 2015-03-10 00:27
I suspect this is actually failing on trying to gather a jid. We need to just catch the exception bubbled up from the returner and default back to our own jid selection.

**Comment by pitatus** [comment] 2015-03-11 16:22
with current build (2015.2.0rc1-147-g1d60775), here is what I see in master log:
```
2015-03-11 09:55:44,594 [salt.master      ][ERROR   ][26202] Exception occurred while introspecting key.list_all: 'mysql.prep_jid'
2015-03-11 09:55:44,617 [salt.utils.event ][ERROR   ][19802] Could not store return for events <generator object iter_events at 0x7f143faea780>. Returner mysql not found.
2015-03-11 09:55:48,222 [salt.utils.event ][ERROR   ][19834] Could not store return for events <generator object iter_events at 0x7f143fab4190>. Returner mysql not found.
2015-03-11 09:55:51,863 [salt.utils.event ][ERROR   ][19862] Could not store return for events <generator object iter_events at 0x7f143fab4aa0>. Returner mysql not found.
2015-03-11 09:55:55,684 [py.warnings      ][WARNING ][19907] /usr/lib/python2.7/dist-packages/salt/client/mixins.py:312: DeprecationWarning: kwargs must be passed inside the low under "kwargs"
2015-03-11 09:55:55,683 [salt.utils.event ][ERROR   ][19910] Could not store return for events <generator object iter_events at 0x7f143fa61500>. Returner mysql not found.
2015-03-11 09:55:57,797 [py.warnings      ][WARNING ][19934] /usr/lib/python2.7/dist-packages/salt/client/mixins.py:312: DeprecationWarning: kwargs must be passed inside the low under "kwargs"
2015-03-11 09:55:58,876 [salt.utils.event ][ERROR   ][19969] Could not store return for events <generator object iter_events at 0x7f143fa61e10>. Returner mysql not found.
```

**Comment by terminalmage** [comment] 2015-03-13 15:36
Hmm, I'm removing the Fixed Pending Verification tag for now, I just realized that I haven't checked to see what happens when the connection just times out.

**Comment by terminalmage** [comment] 2015-03-13 15:43
As long as the returner raises an exception, I think we should be good here thanks to my and Mike's recent commits, but I want to confirm for myself before I turn this over to QA.

**Comment by terminalmage** [comment] 2015-03-13 16:00
OK, so when the MySQL server cannot be reached, there is no error sent to the CLI but the exception is logged. Do we want to still try to filter this error to the CLI if possible?

**Comment by cachedout** [comment] 2015-03-13 16:02
I would say that ideally, it would reach the CLI if the CLI used the ``--returner`` option but if it's just the master_job_cache that can't reach the the returner that it would be confusing to have the message appear there.

**Comment by terminalmage** [comment] 2015-03-13 16:11
Actually, we do have a warning that goes to the CLI when the master_job_cache can't be reached. Not so with the ``--return`` arg though, because that's on the minion side. I'll check to see if I can return the error in the pub data.

**Comment by terminalmage** [comment] 2015-03-13 17:02
I can get the information back in the pub data, but more work will need to be done to get it filtered back up to the CLI, if that's even possible. It also should be checked for and added to the job cache, and that will take some extra work as well.

For now, we are at least not hanging on this condition, which in my mind closes this blocker. We can look at enhancements to how we handle errors as a separate issue.


To test this, first set the following in the master config:

```
mysql.host: 'localhost'
mysql.user: 'myuser'
mysql.pass: 'mypass'
mysql.db: 'mydb'
mysql.port: 3306
master_job_cache: mysql
event_return: mysql
```

Then, on a master *without* the python **MySQLdb** module, attempt to do any command (ex. ``salt myminion test.ping``). You should see an error on the CLI and the command should fail to even be published to the minion. You should also see errors in the master log. The error on the CLI should happen quick, there should be no several second timeout.

Next, install **MySQLdb** using pip:

```bash
pip install MySQL-python
```

The important thing is not to have a database running at the configured address. Now repeat the above test, and you should also see errors, but they should only be logged, and there should be a warning on your CLI command.

Finally, uncomment the **master_job_cache** and **event_return** lines from the master config file, restart the master, and make sure that the minion has **MySQLdb** installed. Copy the lines starting with ``mysql.`` that you added to the master config earlier, into the minion config, and restart the minion. Then, run ``salt myminion test.ping --return=mysql``. The result should come back to the CLI, and you should see an error in the minion log.

**Comment by pitatus** [comment] 2015-03-14 01:23
Confirmed with 2015.2.0rc1-164-g7d03108, if python-mysqldb is not installed (Ubuntu) I get an error at the CLI and command returns.
```
Failed to allocate a jid. The requested returner 'mysql' could not be loaded.
```
If python-mysqldb is installed test.ping will return successfully, if mysql config is setup properly in master config, and will also return successfully if mysql config is bad (test.ping returns True).
```
[WARNING ] Returner unavailable: MySQL returner could not connect to database: (2003, 'Can\'t connect to MySQL server on \'10.1.45.6\' (113 "No route to host")')
arch2:
    True
```

**Comment by ssgward** [comment] 2015-03-17 23:08
This has been fixed. Closing.

**Closed by ssgward** 2015-03-17 23:08 UTC
Labels: Blocker, Bug, Fixed Pending Verification, Medium Severity
