### ISSUE TITLE
pygit 0.23.2 is not supported in Salt 2015.8.1

### ISSUE THREAD

**Issue by johnwchadwick** [saltstack/salt#28072] opened 2015-10-19 02:57 UTC
I just rolled a fresh Salt master running 2015.8.1, freshly installed libgit2 from source and hit this issue:
```
[ERROR   ] Exception 'authentication required but no callback set' caught while fetching git_pillar remote 'production git@gitlab.com:...'
[ERROR   ] Exception 'authentication required but no callback set' caught while fetching gitfs remote 'git@gitlab.com:...
```

Rolling back to pygit/libgit 0.22.x solved my issue, but I didn't see an open issue regarding this problem, so I figured it'd be good to at least have an issue open about it. I don't have time to produce a fix right now - sorry! For anyone curious, I believe the problem ties to this pull request: https://github.com/libgit2/pygit2/pull/568

**Comment by turnred** [comment] 2015-10-19 13:17
I'm experiencing the same problem here.

**Comment by jfindlay** [comment] 2015-10-19 17:04
@johnwchadwick, @turnred, thanks for the report.  @terminalmage, ping.

**Comment by terminalmage** [comment] 2015-10-19 19:03
Looks like 0.23 probably changed how authentication is handled. Thanks for the report, I'll make sure I get in a fix for this.

**Comment by terminalmage** [comment] 2015-11-18 23:00
Confirmed that the gitfs code did work in 0.22.x, as well as 0.23.0 and 0.23.1, but breaks with 0.23.2. Looks like the pygit2 developers decided to once again make a major change in a point release. They have a history of doing that, unfortunately.

Sorry for the inconvenience, I'll get a fix for this in the next day or two.

**Comment by terminalmage** [comment] 2015-11-18 23:07
In the meantime, @johnwchadwick, you can work around this by uninstalling pygit2, and installing 0.23.1 using pip:

```
pip install 'pygit2==0.23.1'
```

**Comment by terminalmage** [comment] 2015-11-19 15:28
Working on a fix in Salt code right now, and I opened an upstream bug in pygit2: https://github.com/libgit2/pygit2/issues/583

**Comment by terminalmage** [comment] 2015-11-19 20:00
Fix submitted in #29059.

**Comment by herbmaster** [comment] 2015-11-30 21:48
I'd like to kindly suggest, to ship a working version of pygit in salt, if there are no licencing issues. According to the docs, this is not the first time, so every package update potentially breaks the salt master.

**Comment by eliasp** [comment] 2015-12-01 00:48
@herbmaster Dependencies should never be bundled for a multitude of reasons. Instead, compatible releases need to be strictly declared in the package's requirements instead.

**Closed** 2015-12-02 08:47 UTC
Labels: Bug, High Severity, P4, Platform, TEAM Core

**Comment by tryauuum** [comment] 2024-09-26 16:03
@eliasp 
> Dependencies should never be bundled for a multitude of reasons. Instead, compatible releases need to be strictly declared in the package's requirements instead

how the tables have turned after 10 years with the onedir, which have bundled libraries but not the pygit2

ironically I found this page by searching for the error "Exception 'authentication required but no callback set" which I have with pygit2 and onedir. Supposedly I have to set paths to private keys now? but I've tried it and it doesn't work

```
gitfs_pubkey: /root/.ssh/id_ed25519.pub
gitfs_privkey: /root/.ssh/id_ed25519
```

Just had to vent, please ignore
