### ISSUE TITLE
[BUG] Undocumented Peer System dependency on Job Cache

### ISSUE THREAD

**Issue by nmulcahey** [saltstack/salt#57538] opened 2020-06-03 22:53 UTC
I have found that configuring a master to use `job_cache: False` results in `publish.publish` calls from a minion receiving an empty return from the master despite the peer returning a complete response to the master.

This does in fact make some sense that the result is discarded and the isn't query-able to be returned to the caller so I'm uncertain if this is missing documentation or a functional bug.

I was able to reproduce this on `3000.2`, `2019.2.4`, `2019.2.5`.

**Comment by dmurphy18** [comment] 2020-06-04 17:49
@nmulcahey Can you provide example configuration and commands to reproduce the issue to ensure that the issue is understood and reproducible as seen by you. This ensures your issue when examining and testing for your issue, and not some other item found.  And please include a versions-report for the master and minion that you are testing with. 
Thanks.

**Comment by dmurphy18** [comment] 2021-05-03 22:34
@nmulcahey Is this still an issue for you, if so, can you provide the requested information.

If this is not an issue, please consider closing this issue.

**Comment by dmurphy18** [comment] 2021-06-24 15:39
Closing this due to lack of response.  If this is still an issue, please re-open it addressed to @dmurphy18 with the information requested, that is, versions-report and example of how to reproduce the issue

**Closed by dmurphy18** 2021-06-24 15:39 UTC
Labels: Bug, info-needed
