### ISSUE TITLE
[BUG]salt-minion[8299]: [WARNING ] Unable to process beacon vnc_cleaner

### ISSUE THREAD

**Issue by sr1k5f4** [saltstack/salt#59738] opened 2021-03-07 08:22 UTC
**Description**
Repeated warning messages as below on installing and starting salt-minion on SLES 15 Sp2 for SAP

salt-minion[8299]: [WARNING ] Unable to process beacon vnc_cleaner

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by sr1k5f4** [comment] 2021-03-07 08:26
Can anyone help me understand how do I get rid of these warning messages ?

**Comment by sr1k5f4** [comment] 2021-03-07 08:27
salt-minion[8299]: [WARNING ] Unable to process beacon vnc_cleaner 

The above messages keep filling up everytime i check /var/log/messages or salt-minion status

**Comment by lukasraska** [comment] 2021-03-08 11:05
@sr1k5f4 `vnc_cleaner` beacon isn't part of standard Salt installation, so why the beacon can't be processed is probably something you need to check within the custom beacon (or disable it entirerly)

**Comment by sr1k5f4** [comment] 2021-03-08 17:43
Ok. I don’t see any of the SLES 12 SP3 systems calling this out which report to the same salt master. Only the new SLES 15 SP2 Images I am seeing these warnings. So is there a way I can disable it only for these sles 15 sp2 instances or make some modifications on the minion rather than the master. Please advise

**Comment by lukasraska** [comment] 2021-03-10 14:59
@sr1k5f4 If this is not your Salt installation but something coming from SUSE (e.g. SUSE Manager), you might have better luck raising ticket with SUSE directly. But maybe somebody from Salt core team has some knowledge about `vnc_cleaner` beacon

**Comment by sr1k5f4** [comment] 2021-03-16 11:41
@lukasraska Yes I have tried reaching out to SUSE. Will update on any findings. Thank you.

**Comment by sagetherage** [comment] 2021-03-31 22:38
@meaksh any thoughts here?

**Comment by meaksh** [comment] 2021-04-05 09:00
@sr1k5f4 setting `log_level: trace` in the salt minion configuration, for example in `/etc/salt/minion.d/custom.conf`, usually helps to debug beacons on the minion.

As @lukasraska already mentioned, this failing `vnc_cleaner` is not part of the built-in Salt beacons and AFAIK it's also not part of SUSE Manager. Is this a custom beacon module that you provide via `_beacons` in your salt-master instance?

In any case, you big different between SLE12SP3 and SLE15SP2 is the Python version. In SLE12SP3, Salt runs with Python2 by default, while SLE15SP2 uses Python 3.6.

Could it be that the custom beacon contains code that is not Python 3 compatible? Usually the error you're getting happens when there is an error loading/importing the beacon file. This could be caused by a missing library that is imported on the beacons code, a syntax error, not compatible code between Python 2-3, etc.

One thing you can try is to execute the beacon code to see if Python raises some syntax/import error. Something like the following in the failing SLE15SP2 minion: (I think the path to the cached minion code should be correct)

```console
# python3 /var/cache/salt/minion/extmods/beacons/vnc_cleaner.py

Hth!
```

**Comment by sagetherage** [comment] 2021-04-30 00:29
This does not seem to be a Salt issue - closing.

**Closed by sagetherage** 2021-04-30 00:29 UTC
Labels: info-needed
