### ISSUE TITLE
TypeError: can't serialize <DNS IN A rdata: 56.67.78.89>

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#37000] opened 2016-10-14 08:21 UTC
### Problem

Today without no apparent reason we could no longer run any commands towards one of our minions. This was easily worked around by stopping the minion and purging the contents of `/var/cache/salt/minion/`
### Debug output

```
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'master.example.com', 'tcp://12.23.34.45:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'master.example.com', 'tcp://12.23.34.45:4506')
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: can't serialize <DNS IN A rdata: 56.67.78.89>
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 79, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 274, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 102, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 609, in __init__
    self.gen_modules(initial_load=True)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 640, in gen_modules
    pillarenv=self.opts.get('pillarenv'),
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 170, in compile_pillar
    dictkey='pillar',
  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 186, in crypted_transfer_decode_dictentry
    self._package_load(self.auth.crypticle.dumps(load)),
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 1210, in dumps
    return self.encrypt(self.PICKLE_PAD + self.serial.dumps(obj))
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 141, in dumps
    return msgpack.dumps(msg)
  File "/usr/lib64/python2.7/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:231)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:233)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:192)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:192)
  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:228)
```
### Versions Report

```
$ salt-call --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment] 2016-10-14 20:21
@rbjorklin what version is the minion? Also when you say you can't run any commands were you attempting execution modules or possibly running a state? thanks

**Comment by rbjorklin** [comment] 2016-10-14 22:50
The minion and master are both running 2016.3.3. The versions report from above is from the minion. Neither execution nor states were working.

**Comment by terminalmage** [comment] 2016-10-17 22:51
@rbjorklin After a little web-searching, it seems that the object you're referencing is the product of a query run using the ``dns`` module from the Python stdlib. It looks like the only place this is used in Salt's codebase is the ``ddns`` execution module. Are you using this in any way, and if so, how?

**Comment by rbjorklin** [comment] 2016-10-18 07:52
@terminalmage Thanks for taking a look at this. We actually have a custom grain using the `dns` python module.

    import dns.resolver
    import socket

    def get_public_ip():
        grains = {}
        try:
          query = dns.resolver.query(socket.gethostname())
          grains['public_ip'] = query.response.answer[0].items[0]
        except e:
          grains['public_ip'] = '127.0.0.1'
        return grains

If this is what's causing the above stack trace maybe there could be a way of catching it and providing a pointer to what broke?

**Comment by terminalmage** [comment] 2016-10-18 15:57
I don't know that there is a good way to catch this, since the serializer is used by so many different parts of Salt.

You should keep in mind though that msgpack can only serialize data structures. ``query.response.answer[0].items[0]`` refers to an A record object, what you probably want here is ``query.response.answer[0].items[0].address``:

```python
>>> query = dns.resolver.query('saltstack.com')
>>> query.response.answer[0].items[0]
<DNS IN A rdata: 104.199.122.13>
>>> query.response.answer[0].items[0].address
u'104.199.122.13'
>>>
```

**Comment by terminalmage** [comment] 2016-10-18 16:01
We definitely shouldn't leave an non-operable minion though when this happens, so I'll see what I can find.

**Comment by terminalmage** [comment] 2017-01-24 15:28
@rbjorklin Sorry I had to put this issue aside for a while. I came back to it today and I was unable to reproduce having an inoperable minion when using your custom grain. It does fail to compile as expected, but I can still run commands on the minion.

**Comment by rbjorklin** [comment] 2017-01-24 15:51
No worries @terminalmage. I see now that I forgot to reply here myself, your pointer on the object I was trying to serialize by mistake was correct and this hasn't been an issue for us since. Feel free to close this issue.

**Comment by terminalmage** [comment] 2017-01-24 16:17
@rbjorklin OK, thanks for following back up and confirming. I'll close this.

**Closed by terminalmage** 2017-01-24 16:17 UTC
Labels: Info Needed
