### ISSUE TITLE
[BUG] salt-master 3005: [WARNING ] Config option 'ipc_write_buffer' with value 415937536.0 has an invalid type of float

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#62591] opened 2022-08-31 13:37 UTC
**Description**
Getting this error after upgraded from 3004.2 to 3005
```
[WARNING ] Config option 'ipc_write_buffer' with value 415937536.0 has an invalid type of float, a int is required for this option
```
**Setup**
/etc/salt/master: has following line enabled. dynamic is not recognized as valid value in 3005 anymore.

```
ipc_write_buffer: 'dynamic'
```
Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**

Add folloiwng line in  /etc/salt/master and restart salt-master.
ipc_write_buffer: 'dynamic' 

**Expected behavior**
version 3005 should honor dynamic as an valid option.
if only integer value is allowed , pls provide an example range.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.0
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: 1.1.0
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 1.6.1
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core


```

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by OrangeDog** [comment] 2022-08-31 16:00
It doesn't seem to be documented either.
https://docs.saltproject.io/en/latest/ref/configuration/master.html

**Comment by dmurphy18** [comment] 2022-09-06 20:53
This is an old piece of code and not changed in a few years, 'dynamic' is checked for and translated into an integer value, see https://github.com/saltstack/salt/blame/master/salt/config/__init__.py

The problem is due to https://github.com/saltstack/salt/commit/c138cc03e39cd9c61b4b780cbdd3852858a890f3 from Jul 14 , 2016, where a float is used for _DFLT_IPC_BUFFER
```
_DFLT_IPC_WBUFFER = _gather_buffer_space() * 0.5
```
So this issue has been present for sometime, but is only now being flagged in the log files with the re-working of the transport layer in Salt 3005.  The same error is present in 3005 and 3004.2 https://github.com/saltstack/salt/blob/master/salt/config/__init__.py, but on 3004.2 is not being triggered, since in 3005 the addition of enforcing config types was added, see https://github.com/saltstack/salt/blob/master/salt/config/__init__.py

Will check for other opts with similar issue

**Comment by tjyang** [comment] 2022-09-08 14:43
Can https://docs.saltproject.io/en/latest/ref/configuration/master.html be updated with examples for ipc_write_buffer usage ?

**Comment by dmurphy18** [comment] 2022-09-08 17:49
Yes, it should be better documented
@barbaricyawps can you add an issue to document usage for ipc_write_buffer

**Comment by Ch3LL** [comment] 2022-09-08 19:36
fixed by https://github.com/saltstack/salt/pull/62634

**Closed by Ch3LL** 2022-09-08 19:36 UTC
Labels: Bug, Regression, doc-param-missing, Phosphorus v3005.0
