### ISSUE TITLE
git.latest SSH authentication regression

### ISSUE THREAD

**Issue by mafrosis** [saltstack/salt#27363] opened 2015-09-24 08:03 UTC
I have some states which install a private SSH key into `~/.ssh` along with a `~/.ssh/config` which maps that key to `github.com`. Subsequently a `git.latest` for a private repo occurs with the relevant user.

States:

    git:
        pkg.installed

    /home/vagrant/.ssh/config:
      file.managed:
        - name: 
        - contents: |
            Host github.com
                IdentityFile ~/.ssh/github.{{ grains['host'] }}.pky
        - user: vagrant
        - group: vagrant
        - mode: 600
        - replace: false

    github.com:
      ssh_known_hosts.present:
        - user: vagrant
        - fingerprint: 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48

    github.pky:
      file.managed:
        - contents_pillar: github_key
        - name: /home/vagrant/.ssh/github.{{ grains['host'] }}.pky
        - user: vagrant
        - group: vagrant
        - mode: 600

    dotfiles:
      git.latest:
        - name: git@github.com:mafrosis/dotfiles.git
        - target: /home/vagrant/dotfiles
        - user: vagrant
        - submodules: true

Version `2015.5.5`:

    [INFO    ] Running state [git] at time 07:43:39.744099
    [INFO    ] Executing state pkg.installed for git
    [INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
    [INFO    ] Package git is already installed.
    [INFO    ] Completed state [git] at time 07:43:39.824560
    [INFO    ] Running state [/home/vagrant/.ssh/config] at time 07:43:39.829778
    [INFO    ] Executing state file.managed for /home/vagrant/.ssh/config
    [INFO    ] File changed:
    New file
    [INFO    ] Completed state [/home/vagrant/.ssh/config] at time 07:43:39.834629
    [INFO    ] Running state [github.com] at time 07:43:39.836393
    [INFO    ] Executing state ssh_known_hosts.present for github.com
    [INFO    ] Executing command 'ssh-keygen -F "github.com" -f "/home/vagrant/.ssh/known_hosts"' in directory '/root'
    [INFO    ] Executing command 'ssh-keyscan -H github.com' in directory '/root'
    [INFO    ] {'new': {'hostname': '|1|kXNEJ8FQ6T3Y9wD/iBPIauGQNGE=|RMLKGdTmYy6zX/1ywic5HdVGE1Y=', 'enc': 'ssh-rsa', 'key': 'AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==', 'fingerprint': '16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48'}, 'old': None}
    [INFO    ] Completed state [github.com] at time 07:43:40.668967
    [INFO    ] Running state [/home/vagrant/.ssh/github.vagrant.pky] at time 07:43:40.670501
    [INFO    ] Executing state file.managed for /home/vagrant/.ssh/github.vagrant.pky
    [INFO    ] File changed:
    New file
    [INFO    ] Completed state [/home/vagrant/.ssh/github.vagrant.pky] at time 07:43:40.676775
    [INFO    ] Running state [git@github.com:mafrosis/dotfiles.git] at time 07:43:40.687513
    [INFO    ] Executing state git.latest for git@github.com:mafrosis/dotfiles.git
    [INFO    ] Repository git@github.com:mafrosis/dotfiles.git cloned to /home/vagrant/dotfiles
    [INFO    ] {'new': 'git@github.com:mafrosis/dotfiles.git', 'revision': 'ecd6a71768e8051fc12f67acbe4c05e9af23f47c'}
    [INFO    ] Completed state [git@github.com:mafrosis/dotfiles.git] at time 07:43:53.847584

Version `2015.8.1`:

    [INFO    ] Running state [git] at time 07:46:59.410349
    [INFO    ] Executing state pkg.installed for git
    [INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
    [INFO    ] Package git is already installed
    [INFO    ] Completed state [git] at time 07:46:59.606263
    [INFO    ] Running state [/home/vagrant/.ssh/config] at time 07:46:59.614633
    [INFO    ] Executing state file.managed for /home/vagrant/.ssh/config
    [INFO    ] File changed:
    New file
    [INFO    ] Completed state [/home/vagrant/.ssh/config] at time 07:46:59.624901
    [INFO    ] Running state [github.com] at time 07:46:59.627682
    [INFO    ] Executing state ssh_known_hosts.present for github.com
    [INFO    ] Executing command 'ssh-keygen -F "github.com" -f "/home/vagrant/.ssh/known_hosts"' in directory '/root'
    [INFO    ] Executing command 'ssh-keyscan -H github.com' in directory '/root'
    [INFO    ] {'new': {'hostname': '|1|kXNEJ8FQ6T3Y9wD/iBPIauGQNGE=|RMLKGdTmYy6zX/1ywic5HdVGE1Y=', 'enc': 'ssh-rsa', 'key': 'AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==', 'fingerprint': '16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48'}, 'old': None}
    [INFO    ] Completed state [github.com] at time 07:47:02.524971
    [INFO    ] Running state [/home/vagrant/.ssh/github.vagrant.pky] at time 07:47:02.525363
    [INFO    ] Executing state file.managed for /home/vagrant/.ssh/github.vagrant.pky
    [INFO    ] File changed:
    New file
    [INFO    ] Completed state [/home/vagrant/.ssh/github.vagrant.pky] at time 07:47:02.530746
    [INFO    ] Running state [git@github.com:mafrosis/dotfiles.git] at time 07:47:02.543295
    [INFO    ] Executing state git.latest for git@github.com:mafrosis/dotfiles.git
    [INFO    ] Checking remote revision for git@github.com:mafrosis/dotfiles.git
    [INFO    ] Executing command ['git', 'ls-remote', 'git@github.com:mafrosis/dotfiles.git'] in directory '/root'
    The authenticity of host 'github.com (192.30.252.130)' can't be established.
    RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
    Are you sure you want to continue connecting (yes/no)? ^C
    Exiting gracefully on Ctrl-c

**Comment by jfindlay** [comment] 2015-09-24 18:27
@mafrosis, thanks for the report.

**Comment by terminalmage** [comment] 2015-11-06 16:53
Duplicate of https://github.com/saltstack/salt/issues/27703, which has been fixed.

**Closed by terminalmage** 2015-11-06 16:53 UTC
Labels: Bug, High Severity, P3, Platform, Regression, State Module
