### ISSUE TITLE
starting mysql-community via service or cmd hangs on el6 (CentOS6)

### ISSUE THREAD

**Issue by mbochenk** [saltstack/salt#36116] opened 2016-09-07 15:57 UTC
### Description of Issue/Question

Starting latest MySQL community edition hangs (waits) indefinitly  both via cmd.run and service states. Actual service is started and running.

This looks like a recent change in latest MySQL releases, for example: https://github.com/mysql/mysql-server/commit/684a165f28b3718160a3e4c5ebd18a465d85e97c#diff-26228c60f7753d111a177fa638fb5838R283

Affects 5.5.52, 5.6.33, 5.7.15. Switching to previous releases - 51, 32 and 14 resolves the issue.

In general quite a lot of commands ending with `>/dev/null 2>&1 &` were changed to `>/dev/null &`, stating security reasons which looks dubious to me.

While this might be MySQL bug, if you run manually from command line "service mysqld start" it works - either via bash or sh. Feel free to close if MySQL, though looks like if it is executed via command line it also should work in salt.

Does not affect CentOS7 (presumably because of systemd)
### Setup

These states hang:

```
mysql57-service:
  service.running:
    - name: mysqld
    - enable: True
```

```
mysql55-service:
  cmd.run:
    - name: service mysqld start; chkconfig mysqld on; sleep 5
    - shell: /bin/bash
```
### Steps to Reproduce Issue

Try starting mysqld via service or cmd states via salt. State executes indefinitely.  Actual service is started and running.
If executed via `service mysqld start` - exit code is 0 and service is started.
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 0.6
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.8
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.09.1
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.4.2.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by Ch3LL** [comment] 2016-09-08 18:58
@mbochenk i'm not able to replicate this on mysql 5.6.33-2.el7. if you try that version is it working for you?

**Comment by mbochenk** [comment] 2016-09-12 08:09
What definitely failed for me:
5.6.33, 5.7.14 and 5.5.52. Looking back I might have not tested only on CentOS6 and missed el7.

el7 is on systemd, so it might be working fine there. I will do more testing this week and let you know.

**Comment by mbochenk** [comment] 2016-09-12 12:19
So, I've checked and this does not affect el7, but it does affect el6. All versions released September 6 seem affected.: 
```
[INFO    ] Running state [mysqld] at time 05:15:50.590562
[INFO    ] Executing state service.running for mysqld
[INFO    ] Executing command '/sbin/service mysqld status' in directory '/root'
[INFO    ] Executing command '/sbin/chkconfig --list mysqld' in directory '/root'
[INFO    ] Executing command '/sbin/runlevel' in directory '/root'
[INFO    ] Executing command '/sbin/service mysqld start' in directory '/root'
```

**Comment by mbochenk** [comment] 2016-09-19 10:50
@Ch3LL - let me know if you need additional information on this.

**Comment by Ch3LL** [comment] 2016-09-21 21:38
@mbochenk thanks for all the great investigation work. Really appreciate it. Looks like we might need to look on our end to see if we can work around this new change in the new service files for mysql. Thanks for the heads up :)

Would you mind checking one more thing for me so we can possibly find you a workaround: Can you attempt restarting with the service module like so: `salt '*' service.start <service name>` and while attempting to run on the minion `salt-call --local service.start <service name> -ldebug`

**Comment by zerthimon** [comment] 2016-09-22 09:07
Workaround in https://github.com/saltstack/salt/issues/33442

**Comment by mbochenk** [comment] 2016-09-22 09:36
@Ch3LL I will see what I can do, most likely - next week.
@zerthimon Not sure if that works for centos - I think there are different functions used.

FYI, I had the same behaviour on `cmd.run` with `nohup` and with `nohup` as described [here](https://docs.saltstack.com/en/latest/faq.html#linux-unix). Did not try `at` as in my experience it is somewhat unreliable.

**Comment by zerthimon** [comment] 2016-09-22 09:55
@mbochenk Just use this workaround https://github.com/saltstack/salt/issues/9736#issuecomment-176351724 by @michalsuba it should work in all distros.

**Comment by mbochenk** [comment] 2016-09-22 10:09
@zerthimon yes, that should work. But as I see that is a fancy way of reverting commits that changed all `>/dev/null 2>&1` to `>/dev/null &`. I am not sure which one would be more secure - mysql commit or this one.
For me a workaround is to fix MySQL version - in my current use case this is less of a concern as it is available only on private network and the benefit is that does not require changes in mysql startup scripts.

**Comment by mbochenk** [comment] 2016-09-22 10:29
The actual cause could be as described in this https://github.com/saltstack/salt/issues/9736#issuecomment-181409447
However I am concerned that if I run `service mysqld start` in bash I get exit status 0 - which to me (and I suspect most users and mysql devs) looks like everything has finished executing.

**Comment by Ch3LL** [comment] 2016-09-22 18:49
@mbochenk thanks for all your input. I agree we need to find a way to workaround these files. And #9736 looks like it is a duplicate of this same scenario. And it seems its not just the mysql package that been causing this issue it seems a bigger problem that will might need to handle for. Do you mind if we close this issue and monitor the issue on 9736? or do you see the situation to where these are different issues?

**Comment by mbochenk** [comment] 2016-09-23 06:50
@Ch3LL I do not mind as long as MySQL gets fixed :)

**Comment by mbochenk** [comment] 2016-09-28 07:29
@Ch3LL as noted - please close the issue if you see fit. I do think that people are more likely to run into this on mysql service - so maybe that should be mentined in #9736 
I had a similar issue with latest `ambari-server` from preview of `hdp 2.5` (it should be ambari 2.4.x) - however that one is in beta so I do not see fit to report it before ambari-server is released and I cannot spend more time investigating it for now.
I could imagine this applied to, for example, (other) java services - anything that is not native and not packed and tested by distro maintainers. I would say all of these should be fixed and it does not really matter which issue tracks this behaviour. 
Maybe it is possible to add a flag to [`cmd`](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#salt.states.cmd.run) that does not wait for command to end? For example, something like `wait_for` or `detach`? I do not see anything like this at the moment. And similar for `service`.

**Comment by mbochenk** [comment] 2017-02-16 14:29
@Ch3LL I've posted a lengthy comment on #9736 trying to explain why it seems to me that this should be at least examined. While workarounds exist, this one is really annoying.

**Comment by Ch3LL** [comment] 2017-02-24 16:56
@mbochenk thanks for bumping this one for me. I agree we will close this issue here and monitor it in #9736 

Thanks for your comment. I also like the idea to add an argument to help handle the defunct processes thanks

**Closed by Ch3LL** 2017-02-24 16:56 UTC
Labels: Bug, High Severity, P3, RIoT, State Module
