### ISSUE TITLE
Error with minion highstate and tcp transport

### ISSUE THREAD

**Issue by jakehilton** [saltstack/salt#33046] opened 2016-05-04 18:29 UTC
### Description of Issue/Question
When running highstate on a minion using the tcp transport I see the following error a few times in my log:
`2016-05-04 18:22:53,955 [tornado.application][ERROR   ][11620] Future exception was never retrieved: StreamClosedError: Stream is closed`

Here is more context of that error:
```
[INFO    ] Got list of available master addresses: ['localhost']
[ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 476, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(opts, **factory_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 163, in factory
    return salt.transport.tcp.AsyncTCPPubChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 201, in __init__
    self.io_loop = kwargs['io_loop'] or tornado.ioloop.IOLoop.current()
KeyError: 'io_loop'
Exception AttributeError: "'AsyncTCPPubChannel' object has no attribute '_closing'" in <bound method AsyncTCPPubChannel.__del__ of <salt.transport.tcp.AsyncTCPPubChannel object at 0x7fe0d9f4f850>> ignored
[INFO    ] Determining pillar cache
[ERROR   ] Future exception was never retrieved: StreamClosedError
[INFO    ] Determining pillar cache
[ERROR   ] Future exception was never retrieved: StreamClosedError
```

Everything seems to run ok but I"m not sure if this will cause issues down the road.

### Setup
Fresh install from repo.saltstack.com running on ubuntu 14.04.

Master config:
```
hash_type: sha256
keep_jobs: 1
open_mode: True
timeout: 30
transport: tcp

file_roots:
  base:
    - /etc/salt/git/salt
    - /etc/salt/git/salt/states

pillar_roots:
  base:
    - /etc/salt/git/salt/pillar
```

Minion config:

```
hash_type: sha256
random_reauth_delay: 10
master:
  - smaster1-dusc.xxxxx.com
  - smaster2-dusc.xxxxx.com
master_type: failover
master_shuffle: True
master_alive_interval: 60
auth_timeout: 10
auth_tries: 0
retry_dns: 0
transport: tcp
startup_states: highstate
grains:
  ulsite: downlynk
  ulprovider: aws
  ultype: smaster
```

### Steps to Reproduce Issue
Configure the master and minion to both use the tcp transport and run a highstate from the minion.

### Versions Report
```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment] 2016-05-04 20:08
@jakehilton, thanks for reporting.  This looks like a duplicate of #32609.  If you think it is different, you are welcome to reopen, but be sure to also post your master and minion configs.

**Comment by jakehilton** [comment] 2016-05-04 21:35
Well this ticket had two items in it.. so I'll modify it to just include the one that is different from the ticket you referenced.

**Comment by jakehilton** [comment] 2016-05-04 21:36
Sadly.. I cannot re-open this.. unless I"m missing some button somewhere to do that.

**Comment by jfindlay** [comment] 2016-05-05 15:00
@jakehilton, thanks for clarifying.

**Comment by cachedout** [comment] 2016-05-09 20:14
I don't understand how this would be a duplicate. I don't see the above traceback anywhere in there.

**Comment by cachedout** [comment] 2016-05-09 20:25
I can definitely verify this on the 2015.8 branch but it appears to be fixed on 2016.3.0. Because we have no plans to fully support the TCP transport on 2015.8, we aren't going to search for and backport a fix here. As you point out, this should be a non-fatal error anyhow.

**Comment by jakehilton** [comment] 2016-05-09 20:27
Always good to hear it's fixed somewhere. :)

Loaded question.. when is the 2016.3.0 scheduled to land? I'd love to run TCP transport in a fully supported version.

**Comment by cachedout** [comment] 2016-05-09 20:30
@jakehilton First half of June is where we're at right now. Hopefully sooner.

**Closed** 2016-05-09 20:35 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P2, Transport
