### ISSUE TITLE
Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.

### ISSUE THREAD

**Issue by syed-salt** [saltstack/salt#43436] opened 2017-09-11 16:00 UTC
### Description of Issue/Question
Team - 

When I try to do  salt pid\* state.apply icinga-setup.sls. I am getting below error - Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.

Please look into this ASAP.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by garethgreenaway** [comment] 2017-09-12 16:49
@syed-salt A couple questions.  Do you have a Salt master setup and the salt minion(s) in question are configured to connect to that Salt master?  Are you able to run simple commands targeting your minions such as test.ping and receive back a valid response?

**Comment by mikadell** [comment] 2017-11-17 07:21
Same issue, any resolution yet ?
Thanks

**Comment by Reiner030** [comment] 2018-10-04 16:10
Here also since 1-2 weeks suddenly all instances got same problem notifications running Debian Jessie / Debian Stretch with `salt-call 2017.7.2 (Nitrogen)` since ~ end of last year/ one year already running this version without it. 
All instances are using nptd so it can be a time difference problem and there are no differences in instance sizes / amount of instances.
Only difference which might be problematic here were the latest kernel and python security updates of Debian.
* https://www.debian.org/security/2018/dsa-4306
* https://www.debian.org/security/2018/dsa-4307
* https://www.debian.org/security/2018/dsa-4308

**Comment by AmiramMaimon** [comment] 2019-09-08 07:58
Hey,

I'm having the same issue with salt-master version 2019.2.0.
The error is the same but for a simpler command: salt '*' cmd.run hostname

Amiram

**Comment by tjyang** [comment] 2019-12-12 22:19
This happened to my 9.2.2  salt-master also. I restored the VM back as old as 9.2.0 and issue still exist.

**Comment by Reiner030** [comment] 2020-01-12 13:30
Seems I added my "solution" of this lagg to another issue ...
Im my case I added a gluster share within the /srv/salt/ folder to have some self-compiled / prepareed Debian packages included for reference.
The problem was here that the saltmaster is doing ON EVERY STUPID REQUEST STEP A FULL RECURSIVE DIRECTORY SCAN which occures in such timeout when the folder structure gets too big/has too slowly response.

=> There should be a check/scan only for needed files referenced by needed apply command.

**Comment by sagetherage** [comment] 2020-02-11 19:22
@garethgreenaway can you please follow up, here?

**Comment by sagetherage** [comment] 2020-03-17 19:30
looks like this still needs @saltstack/team-core follow up, here. I will look into getting someone to respond sooner rather than later on this ticket, today

**Comment by DmitryKuzmenko** [comment] 2020-03-18 13:39
I can't say exactly is this related to the original report or not, but I've reproduced the issue after I've mounted a samba share with big enough directory structure to the salt root sub-directory and ran any state.

**Comment by DmitryKuzmenko** [comment] 2020-03-19 08:02
So since we have no information from @syed-salt I'm treating this issue as reported by @Reiner030.

**Comment by DmitryKuzmenko** [comment] 2020-04-06 11:33
Possible fix: https://github.com/saltstack/salt/pull/54468

**Comment by sagetherage** [comment] 2020-05-29 21:25
Closing as fixed in the above PR, will be released in Sodium mid-Jun 2020, please comment and mention me if this is incorrect.

**Closed by sagetherage** 2020-05-29 21:25 UTC
Labels: Bug, Confirmed, Fixed Pending Verification

**Comment by priyank-R** [comment] 2022-06-13 10:16
Issue is appearing on salt-master 

```
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.3.12
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.59.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

We're targeting around 130 minions and applying some formula which is causing this issue. Can someone recommend tweaking some specific configs or something to help tackle the problem ?

I tried increasing the response timeout but no luck.

` sudo salt -C '*' state.apply formulas.ossec.setup_repo -t 20 test=True &> ~/temp.log`

All the minions that are being targeted are having versions 3004 / 3004.1 - Nothing less.
