### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kefatong** [saltstack/salt#65522] opened 2023-11-08 06:37 UTC
###### SLS file #########
extract_package:
  module.run:
    - name: archive.unzip
    - zip_file: "C:/AgentCacheFiles/{{ pillar.package_name }}.zip"
    - dest: "C:/AgentCacheFiles"
    - password: 'xxxxxxx'

####### SLS Exec output #######

    ID: extract_package
    Function: module.run
        Name: archive.unzip
      Result: False
     Comment: Module function archive.unzip threw an exception. Exception: Exception encountered unpacking zipfile: pwd: expected bytes, got str
     Started: 14:25:08.362932
    Duration: 31.277 ms
     Changes:

Summary for windows_agent1

######## CLI Exec Output #########
salt -c config/salt '*' archive.unzip C:/AgentCacheFiles/Windows.zip C:/AgentCacheFiles/ password='xxxx'

windows_agent1:
    ERROR: Exception encountered unpacking zipfile: pwd: expected bytes, got str

####### Salt Version ########
salt -c config/salt '*' test.version
windows_agent1:
    3005.4

**Comment by OrangeDog** [comment] 2023-11-08 10:47
Duplicate of #61422. Fixed in 3006.

**Closed by OrangeDog** 2023-11-08 10:47 UTC
Labels: Bug, needs-triage
