### ISSUE TITLE
External Authentication System does not work for groups of users

### ISSUE THREAD

**Issue by donatello** [saltstack/salt#12111] opened 2014-04-18 15:19 UTC
I have the following external authentication system config in the master:

```
external_auth:
  pam:
    saltusers%:
      - '*'
        - 'test.*'
        - 'grains.get'
        - 'grains.items'
        - 'grains.item'
        - 'grains.has_value'
        - 'grains.ls'
```

According to the example at - http://docs.saltstack.com/en/latest/topics/eauth/index.html - this is valid.

However, on restarting the master, there are errors:

```
# /etc/init.d/salt-master restart
[....] Restarting salt master control daemon: salt-master[ERROR   ] Error parsing configuration file: /etc/salt/master - while parsing a block collection
  in "<string>", line 188, column 7:
          - '*'
          ^
expected <block end>, but found '<block sequence start>'
  in "<string>", line 189, column 9:
            - 'test.*'
            ^
. ok 

```

**Comment by cachedout** [comment] 2015-01-08 22:19
This appears resolved in my testing against both 2014.7 and develop. Since the last report of this was prior to the release of 2014.7, I'm going to go ahead and close this. If it can be reproduced on either of those branches, please re-open and we'll have a look. Thanks!

**Closed by cachedout** 2015-01-08 22:19 UTC
Labels: Bug, Medium Severity
