### ISSUE TITLE
Problem with cyrillic file names in salt exported direcory

### ISSUE THREAD

**Issue by NVoronchev** [saltstack/salt#27805] opened 2015-10-08 19:37 UTC
If one create a file with cyrillic name, for example `touch /srv/salt/абвгд.txt`, then no one state from SLS-files can be applyed to a Windows minion:
```
root@ubuntu-srv:~# salt -L 'ubuntu-srv-1,winxp-virtual' test.ping
ubuntu-srv-1:
    True
winxp-virtual:
    True

root@ubuntu-srv:~# salt -L 'ubuntu-srv-1,winxp-virtual' state.highstate
ubuntu-srv-1:
----------
          ID: test_sls
    Function: module.run
        Name: test.ping
      Result: True
     Comment: Module function test.ping executed
     Started: 02:47:23.790793
    Duration: 18.702 ms
     Changes:   
              ----------
              ret:
                  True

Summary for ubuntu-srv-1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  18.702 ms
              ----------
              winxp-virtual:
                  The minion function caused an exception: Traceback (most recent call last):
                    File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1004, in _thread_return
                      return_data = func(*args, **kwargs)
                    File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 540, in highstate
                      whitelist=kwargs.get('whitelist')
                    File "C:\salt\bin\lib\site-packages\salt\state.py", line 3069, in call_highstate
                      self.load_dynamic(matches)
                    File "C:\salt\bin\lib\site-packages\salt\state.py", line 2601, in load_dynamic
                      refresh=False)
                    File "C:\salt\bin\lib\site-packages\salt\modules\saltutil.py", line 478, in sync_all
                      ret['beacons'] = sync_beacons(saltenv, False)
                    File "C:\salt\bin\lib\site-packages\salt\modules\saltutil.py", line 265, in sync_beacons
                      ret = _sync('beacons', saltenv)
                    File "C:\salt\bin\lib\site-packages\salt\modules\saltutil.py", line 111, in _sync
                      source, sub_env, include_pat=r'E@\.(pyx?|so|zip)$'
                    File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 444, in cache_dir
                      path, saltenv, include_empty, include_pat, exclude_pat
                    File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 230, in cache_dir
                      if fn_.strip() and fn_.startswith(path):
                  UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```
This issue was tested with minons run under Windows XP and Windows 8.1.

**Comment by jfindlay** [comment] 2015-10-09 20:54
@NVoronchev, thanks for the report.  This is a duplicate of #27789, which is fixed in #27833.

**Closed by jfindlay** 2015-10-09 20:54 UTC
Labels: Duplicate
