### ISSUE TITLE
salt-ssh return code doesn't reflect critical SLS rendering errors

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#41296] opened 2017-05-17 11:22 UTC
Hi,

Apparently this can happen:

```
% salt-ssh minion-name state.apply state.name
[ERROR   ] Rendering exception occurred: Jinja variable 'salt.pillar object' has no attribute 'something'
[CRITICAL] Rendering SLS 'base:state.name' failed: Jinja variable 'salt.pillar object' has no attribute 'something'
minion-name:
    - Rendering SLS 'base:state.name' failed: Jinja variable 'salt.pillar object' has no attribute 'something'
% echo $?
0
```

One would think that "CRITICAL" is supposed to mean something... :)

This is with 2016.11.4.

TIA.

**Comment by gtmanfred** [comment] 2017-05-18 15:18
Exit codes are something that we are working on and hope to have fixed across the board and tested in the Oxygen release.

https://github.com/saltstack/salt/issues/18510

I am going to close this as a duplicate of that issue.

Thanks,
Daniel

**Closed by gtmanfred** 2017-05-18 15:18 UTC
