### ISSUE TITLE
Saltstack repo: "size mismatch" error when downloading dependancies from latest debian jessie directory

### ISSUE THREAD

**Issue by flo-blg** [saltstack/salt#44488] opened 2017-11-10 17:58 UTC
### Description of Issue/Question

Hi,
Installing the latest salt-minion debian package using the Salt repository on a fresh install results in an error occurring during some of the dependancies installations, also coming from the Salt repository. 

Error is: 
> E: Failed to fetch http://repo.saltstack.com/apt/debian/8/amd64/latest/pool/main/libs/libsodium/libsodium13_1.0.3-1_amd64.deb: Size mismatch

The error is not specific to libsodium13 and occurs with some others packages as well.

By making apt points to "archive/2017.7.1" instead of "latest", the installation chain works like a charm.

### Setup

- Debian Jessie
- Fresh install (no installed salt-minion, no configured salt repository)

### Steps to Reproduce Issue

Example isolating the issue with libsodium13 package only:

```
$ wget -O - https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
> [...]
> 2017-11-10 18:29:21 (59.6 MB/s) - written to stdout [1727/1727]
> 
> OK
$ echo "deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main" > /etc/apt/sources.list.d/saltstack.list
$ aptitude update
> [...]
> Get: 8 http://repo.saltstack.com jessie InRelease [2,837 B]
> [...]
> Get: 19 http://repo.saltstack.com jessie/main amd64 Packages [15.0 kB]
> [...]
> Ign http://repo.saltstack.com jessie/main Translation-en_GB
> Ign http://repo.saltstack.com jessie/main Translation-en
> [...]
> Fetched 20.6 MB in 15s (1,323 kB/s)
> 
> Current status: 137 updates [+7], 754 new [+14].
$ aptitude install libsodium13=1.0.3-1
> The following NEW packages will be installed:
>  libsodium13
> 0 packages upgraded, 1 newly installed, 0 to remove and 137 not upgraded.
> Need to get 138 kB of archives. After unpacking 407 kB will be used.
> Get: 1 http://repo.saltstack.com/apt/debian/8/amd64/latest/ jessie/main libsodium13 amd64 1.0.3-1 [138 kB]
> Fetched 139 kB in 0s (0 B/s)
> E: Failed to fetch http://repo.saltstack.com/apt/debian/8/amd64/latest/pool/main/libs/libsodium/libsodium13_1.0.3-1_amd64.deb: Size mismatch
```

Then, same process on the same host, but replacing "latest" with "archive/2017.7.1" in the repo pointer: 

```
$ aptitude clean
$ echo "deb http://repo.saltstack.com/apt/debian/8/amd64/archive/2017.7.1 jessie main" > /etc/apt/sources.list.d/saltstack.list
$ aptitude update
> [...]
> Get: 3 http://repo.saltstack.com jessie InRelease [2,837 B]
> [...]
> Get: 12 http://repo.saltstack.com jessie/main amd64 Packages [15.0 kB]
> [...]
> Ign http://repo.saltstack.com jessie/main Translation-en_GB
> Ign http://repo.saltstack.com jessie/main Translation-en
> [...]
> Fetched 19.4 MB in 13s (1,422 kB/s)
> 
> Current status: 754 new [+3].
$ aptitude install libsodium13=1.0.3-1
> The following NEW packages will be installed:
>  libsodium13
> 0 packages upgraded, 1 newly installed, 0 to remove and 137 not upgraded.
> Need to get 139 kB of archives. After unpacking 407 kB will be used.
> Get: 1 http://repo.saltstack.com/apt/debian/8/amd64/archive/2017.7.1/ jessie/main libsodium13  amd64 1.0.3-1 [139 kB]
> Fetched 139 kB in 0s (0 B/s)
> Selecting previously unselected package libsodium13:amd64.
> (Reading database ... 71355 files and directories currently installed.)
> Preparing to unpack .../libsodium13_1.0.3-1_amd64.deb ...
> Unpacking libsodium13:amd64 (1.0.3-1) ...
> Setting up libsodium13:amd64 (1.0.3-1) ...
> Processing triggers for libc-bin (2.19-18+deb8u6) ...

```

**Comment by dmurphy18** [comment] 2017-11-10 22:39
@flo-blg That is quite interesting since 'latest' is a symbolic link, currently to 'archive/2017.7.2'.  Does the issue disappear when you use 'archive/2017.7.2' similar to 'archive/2017.7.1' ?

It would also be interesting to see if there was a problem with '2017.7' since that is also a symbolic link, currently to 'archive/2017.7.2' which is the latest point release for that branch.

**Comment by flo-blg** [comment] 2017-11-13 11:10
@dmurphy18 That's a very good point! I skipped this test because I've guessed that "latest" was a symlink to "archive/2017.7.2", so I supposed that the behaviour was going to be exactly the same, but I was wrong: the error occurs only with the "latest" pointer.

```
# wget -O - https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
> [...]
> OK
# echo "deb http://repo.saltstack.com/apt/debian/8/amd64/archive/2017.7.2 jessie main" > /etc/apt/sources.list.d/saltstack.list
# aptitude update
> [...]
> Current status: 2860 new [+3].
# aptitude install libsodium13=1.0.3-1
> The following NEW packages will be installed:
>   libsodium13
> 0 packages upgraded, 1 newly installed, 0 to remove and 137 not upgraded.
> Need to get 138 kB of archives. After unpacking 407 kB will be used.
> Get: 1 http://repo.saltstack.com/apt/debian/8/amd64/archive/2017.7.2/ jessie/main libsodium13 amd64 1.0.3-1 [138 kB]
> Fetched 138 kB in 0s (280 kB/s)
> Selecting previously unselected package libsodium13:amd64.
> (Reading database ... 58541 files and directories currently installed.)
> Preparing to unpack .../libsodium13_1.0.3-1_amd64.deb ...
> Unpacking libsodium13:amd64 (1.0.3-1) ...
> Setting up libsodium13:amd64 (1.0.3-1) ...
> Processing triggers for libc-bin (2.19-18+deb8u6) ...
> 
# 
```

Then, after purging this package to try again the install with the "latest" pointer:
```
# apt-get purge libsodium13=1.0.3-1
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following packages will be REMOVED:
>  libsodium13*
> 0 upgraded, 0 newly installed, 1 to remove and 137 not upgraded.
> After this operation, 407 kB disk space will be freed.
> Do you want to continue? [Y/n]
> (Reading database ... 58549 files and directories currently installed.)
> Removing libsodium13:amd64 (1.0.3-1) ...
> Purging configuration files for libsodium13:amd64 (1.0.3-1) ...
> Processing triggers for libc-bin (2.19-18+deb8u6) ...
# echo "deb http://repo.saltstack.com/apt/debian/8/amd64/latest/ jessie main" > /etc/apt/sources.list.d/saltstack.list
# aptitude clean
# aptitude update
> [...]
> Current status: 2860 new [+3].
# aptitude install libsodium13=1.0.3-1
> The following NEW packages will be installed:
>   libsodium13
> 0 packages upgraded, 1 newly installed, 0 to remove and 137 not upgraded.
> Need to get 138 kB of archives. After unpacking 407 kB will be used.
> Get: 1 http://repo.saltstack.com/apt/debian/8/amd64/latest/ jessie/main libsodium13 amd64 1.0.3-1 [138 kB]
> Fetched 139 kB in 0s (0 B/s)
> E: Failed to fetch http://repo.saltstack.com/apt/debian/8/amd64/latest/pool/main/libs/libsodium/libsodium13_1.0.3-1_amd64.deb: Size mismatch
```

Then, I've still been able to reinstall it by setting again the pointer to "archive/2017.7.2" (just to make sure):
```
# echo "deb http://repo.saltstack.com/apt/debian/8/amd64/archive/2017.7.2 jessie main" > /etc/apt/sources.list.d/saltstack.list
# aptitude clean
# aptitude update
> [...]
> Current status: 2860 new [+3].
# aptitude install libsodium13=1.0.3-1
> The following NEW packages will be installed:
>   libsodium13
> 0 packages upgraded, 1 newly installed, 0 to remove and 137 not upgraded.
> Need to get 138 kB of archives. After unpacking 407 kB will be used.
> Get: 1 http://repo.saltstack.com/apt/debian/8/amd64/archive/2017.7.2/ jessie/main libsodium13 amd64 1.0.3-1 [138 kB]
> Fetched 138 kB in 0s (0 B/s)
> Selecting previously unselected package libsodium13:amd64.
> (Reading database ... 58541 files and directories currently installed.)
> Preparing to unpack .../libsodium13_1.0.3-1_amd64.deb ...
> Unpacking libsodium13:amd64 (1.0.3-1) ...
> Setting up libsodium13:amd64 (1.0.3-1) ...
> Processing triggers for libc-bin (2.19-18+deb8u6) ...
> 
# 
```

**Comment by flo-blg** [comment] 2017-11-13 11:18
@dmurphy18 Sorry, I've just realized that I missed the second part of your comment. So I've juste made a test using the "2017.7" symlink, and it worked perfectly:

(Skipping the traces of the first steps that are always the same)
```
# aptitude install libsodium13=1.0.3-1
> The following NEW packages will be installed:
>   libsodium13
> 0 packages upgraded, 1 newly installed, 0 to remove and 137 not upgraded.
> Need to get 138 kB of archives. After unpacking 407 kB will be used.
> Get: 1 http://repo.saltstack.com/apt/debian/8/amd64/2017.7/ jessie/main libsodium13 amd64 1.0.3-1 [138 kB]
> Fetched 138 kB in 0s (245 kB/s)
> Selecting previously unselected package libsodium13:amd64.
> (Reading database ... 58541 files and directories currently installed.)
> Preparing to unpack .../libsodium13_1.0.3-1_amd64.deb ...
> Unpacking libsodium13:amd64 (1.0.3-1) ...
> Setting up libsodium13:amd64 (1.0.3-1) ...
> Processing triggers for libc-bin (2.19-18+deb8u6) ...
> 
```

=> So it clearly seems that the problem only occurs with the "latest" symlink.

**Comment by dmurphy18** [comment] 2017-11-13 18:07
@flo-blg Thanks for checking that, but it is very puzzling that '2017.7' works and 'latest' does not, yet they both are symbolic links, for example from the build server supplying the web servers:

lrwxrwxrwx.  1 root root   16 Sep 27 14:32 2017.7 -> archive/2017.7.2
lrwxrwxrwx.  1 root root   16 Sep 27 14:32 latest -> archive/2017.7.2

I shall investigate as to how the web-servers are delivering this since the original sources link to the same directory.

**Comment by flo-blg** [comment] 2017-11-15 15:27
@dmurphy18 Ok I've got some new elements and I now understand what's happening!

I've just discovered that my company is using an apt caching proxy (apt-cacher-ng, see https://www.unix-ag.uni-kl.de/~bloch/acng/ for details). Every time a package is downloaded for the first time by a host in our network, the package is cached by this proxy. Then, every host that is requiring the same package url will be served by the caching proxy, and not by the distant repository. 

But the host client verifies that the size of the expected package matches the effective size of the downloaded package. And what happens with your repository is very strange. The package libsodium13_1.0.3-1_amd64.deb doesn't have the same size in your "archive/2017.2.1" and "archive/2017.2.2" directories, whereas it's supposed to be the same version of the package:

```
$ curl -s --head http://repo.saltstack.com/apt/debian/8/amd64/archive/2017.7.1/libsodium13_1.0.3-1_amd64.deb | grep Content-Length
> Content-Length: 138598
$ curl -s --head http://repo.saltstack.com/apt/debian/8/amd64/archive/2017.7.2/libsodium13_1.0.3-1_amd64.deb | grep Content-Length
> Content-Length: 138472
```

So what happened was the following:
- When a host in my network requested for the first time the libsodium13 package, it called http://repo.saltstack.com/apt/debian/8/amd64/latest/libsodium13_1.0.3-1_amd64.deb, that was pointing to the equivalent of the current "archive/2017.7.1/libsodium13_1.0.3-1_amd64.deb" with a 138598 content-length.
- Our caching proxy cached the "http://repo.saltstack.com/apt/debian/8/amd64/latest/libsodium13_1.0.3-1_amd64.deb" url with this file.
- Several other hosts ask for the same file, and are served by our proxy without any problem.
- On your repo, "latest" points now to "archive/2017.7.2".
- A host in our network is requesting "http://repo.saltstack.com/apt/debian/8/amd64/latest/libsodium13_1.0.3-1_amd64.deb", and the repo source index tells him that this file has a 138472 content-length.
- As the url is exactly the same, our caching proxy still serves the already cached file.
- The host apt client detects a mismatch between the expected size and the downloaded one.
- That also explains why the problem doesn't exist when I try other pathnames that point to the same file on your repo server, as these paths were not cached yet.

So:
- The issue I reported is in fact specific to people using an apt caching proxy system.
- And the question is becoming: why do the sizes of several dependancies packages differs from one Salt version to another, whereas these packages versions are supposed to be exactly the same?

**Comment by dmurphy18** [comment] 2017-11-15 17:40
@flo-blg Apt caching has proven to be an issue with other users too in the past.

Usually the dependency packages are copied from one release to the next, unless there is a new version required.  However, I can think of only the following explanations for changes in size of dependencies, in order of likelihood:
1. Had to rebuilt on rebuilt VM on build infrastructure due to machines getting moved around and this affected the hashes, size.
2. something went wrong and did a clean build (don't remember doing this, except for when doing a completely new version of an OS, e.g. Debian 9
3. Updated the VM with OS updates and this affected the size of the package, if it got rebuilt.

This has been raised before, giving issues to people using other package monitoring software on Debian, but did not have time at that moment to investigate it due to other pressures.

At that time though I did a quick check, sha1sum,  2017.7.0 and 2017.7.1 for python-concurrent.futures_3.0.3-1_all.deb are the same but 2017.7.2 is different.  

My bet is that VM machines used to built the packages moved between releases and hence the change.  However, this should be a rare occurrence.

But reliance on items remaining the same given VMs come up and down, and being dependent on the machines that build the package is kind troublesome for the future.  For example: some part of infrastructure fails or is upgraded which may required items to be rebuilt from the same source code cannot guarantee that the same size of sha256sum for the package will be generated since headers in compilers / interpreters etc. can change due to fixes be they upgrades or security being applied.

The 'latest' is always the most recent point release for the most currently active branch of Salt, and '2017.7' is always the most recent point release for the named branch. Currently 'latest' and '2017.7' are the same but will change once the branch code-named Oxygen is released.

That said: Salt tries to ensure that all of the dependencies are the same from point release to point release for a branch unless a dependency upgrade is required.  Salt is currently developing build/package/test automation (utilizing states/execution modules) to try to ensure consistency etc. which should help with the issues you are encountering by removing the human element.

Unfortunately there is no time-frame for the release of the automation but it is being actively worked on and shall be open-sourced once it is complete, similar to salt-pack which is used to build the packages.

**Comment by jerrykan** [comment] 2018-03-15 06:42
I regularly hit this problem using apt-cacher-ng

>My bet is that VM machines used to built the packages moved between releases and hence the change. However, this should be a rare occurrence.

The problem occurs with every single new release, so unfortunately it isn't rare at all. A lot of things can cause a package to change each time it is rebuilt, even if nothing on the build host changes. If the intention is to continue to rebuild these dependency packages for each new release, then the only thing that might resolve this issue if some work is undertaken to ensure the packages can be built in a [reproducible](https://reproducible-builds.org/) way.

Other options might be to symlink the dependency package files in each release to a common set of package files, or to see if a HTTP 302 Redirect would work better than just a symlink for the "latest" the directories (though I haven't tested this second option, so I'm not sure if it would make any difference to apt-cacher-ng).

**Comment by dmurphy18** [comment] 2019-04-08 19:49
Closing this since duplicate, and issue in salt-pack https://github.com/saltstack/salt-pack/issues/594

See details there too

**Closed by dmurphy18** 2019-04-08 19:49 UTC
Labels: Duplicate, Pending Discussion
