### ISSUE TITLE
[BUG] __virtual__ returned False: IOLoop is already running

### ISSUE THREAD

**Issue by binooetomo** [saltstack/salt#58730] opened 2020-10-14 02:31 UTC
**Description**
Execution module return __virtual__ returned False: IOLoop is already running 
Probably caused by initiating salt.client.Caller

**Setup**
_modules/bino.py
```

import logging

from subprocess import Popen, PIPE

try:
    import salt.client
    HAS_SALTCLIENT = True
    caller = salt.client.Caller()
except ImportError:
    HAS_SALTCLIENT = False



log = logging.getLogger(__name__)

__virtual_name__ = 'bino'


def __virtual__():
    '''
    Only load  if salt.client is available
    '''
    if HAS_SALTCLIENT:
        return __virtual_name__
    else:
        return False, 'The bino module cannot be loaded: salt.client package unavailable.'

def getstats():
    retDict={}
    retDict['rootdevs'] = _getStorage()
    retDict['users'] = _getUsers()

    return retDict

def _mypopen(cmd):
    myexec = caller.sminion.functions['cmd.run'](cmd)
    return myexec.strip().split('\n')

def _getStorage():
    exclMount=('boot','tmp')
    # Only Check Host storage stats:
    stdout = _mypopen('df')
    inlines = [l.decode() for l in stdout]
    inlines = [l.strip() for l in inlines]
    rootdfs = [l for l in inlines if l.startswith('/dev')]
    rootdfs = [l for l in rootdfs if not l.endswith(exclMount)]
    return rootdfs


def _getUsers() :
    stdout = _mypopen('cat /etc/passwd')
    users=[s.split(':') for s in stdout]
    users=[[s[0],s[2]] for s in users]    
    return users

```

**Steps to Reproduce the behavior**
Test script :

```


from pepper import Pepper
master_url = 'https://localhost:8080'
api = Pepper(master_url)
thislogin=api.login('saltdev', 'saltdev', 'pam')

pings=api.low([{'client': 'local', 'tgt': '*', 'fun': 'test.ping'}])


for k,v in pings['return'][0].items():
    if not v :
        continue
    print('\nProcessing: {}'.format(k))
    api.low([{'client': 'local', 'tgt': k, 'fun': 'bino.getstats'}])




```

result :
Processing: plesk-telkom.mydomain.net
{'return': [{'plesk-telkom.mydomain.net': {'rootdevs': ['/dev/vda1       52417516 47822600   4594916  92% /'], 'users': [['root', '0'], ['bin', '1'], ['daemon', '2'], ['adm', '3'], ['lp', '4'], ['sync', '5'], ['shutdown', '6'], ['halt', '7'], ['mail', '8'], ['operator', '11'], ['games', '12'], ['ftp', '14'], ['nobody', '99'], ['systemd-network', '192'], ['dbus', '81'], ['polkitd', '999'], ['rpc', '32'], ['rpcuser', '29'], ['nfsnobody', '65534'], ['sshd', '74'], ['postfix', '89'], ['chrony', '998'], ['mysql', '27'], ['psaadm', '997'], ['drweb', '100'], ['sw-cp-server', '996'], ['saslauth', '995'], ['ntp', '38'], ['apache', '48'], ['named', '25'], ['mailman', '41'], ['dovecot', '994'], ['dovenull', '993'], ['popuser', '30'], ['mhandlers-user', '31'], ['horde_sysuser', '992'], ['roundcube_sysuser', '991'], ['webalizer', '67'], ['postgres', '26'], ['nginx', '990'], ['psaftp', '989'], ['grafana', '988'], ['centos', '1000'], ['tss', '59'], ['lsadm', '987'], ['gedanggoreng.xyz', '10001'], ['david', '10002'], ['dika', '10003'], ['firebird', '986'], ['gemak', '10004'], ['redis', '985'], ['ryan', '10005'], ['plesk45idw', '10007'], ['memcached', '984'], ['ajacid', '10008'], ['cobacute', '10009'], ['hwstrave', '10010'], ['invoice', '10010'], ['bengkellaptop', '10011'], ['davdolanan', '10012']]}}]}

Processing: locally.mydomain.net
{'return': [{'locally.mydomain.net': "'bino' __virtual__ returned False: IOLoop is already running"}]}

Processing: plesky.mydomain.net
{'return': [{'plesky.mydomain.net': "'bino' __virtual__ returned False: IOLoop is already running"}]}

Processing: debian-mon.novalocal
{'return': [{'debian-mon.novalocal': "'bino' __virtual__ returned False: IOLoop is already running"}]}

**Expected behavior**
Processing: plesk-telkom.mydomain.net
{'return': [{'plesk-telkom.mydomain.net': {'rootdevs': ['/dev/vda1       52417516 47822600   4594916  92% /'], 'users': [['root', '0'], ['bin', '1'], ['daemon', '2'], ['adm', '3'], ['lp', '4'], ['sync', '5'], ['shutdown', '6'], ['halt', '7'], ['mail', '8'], ['operator', '11'], ['games', '12'], ['ftp', '14'], ['nobody', '99'], ['systemd-network', '192'], ['dbus', '81'], ['polkitd', '999'], ['rpc', '32'], ['rpcuser', '29'], ['nfsnobody', '65534'], ['sshd', '74'], ['postfix', '89'], ['chrony', '998'], ['mysql', '27'], ['psaadm', '997'], ['drweb', '100'], ['sw-cp-server', '996'], ['saslauth', '995'], ['ntp', '38'], ['apache', '48'], ['named', '25'], ['mailman', '41'], ['dovecot', '994'], ['dovenull', '993'], ['popuser', '30'], ['mhandlers-user', '31'], ['horde_sysuser', '992'], ['roundcube_sysuser', '991'], ['webalizer', '67'], ['postgres', '26'], ['nginx', '990'], ['psaftp', '989'], ['grafana', '988'], ['centos', '1000'], ['tss', '59'], ['lsadm', '987'], ['gedanggoreng.xyz', '10001'], ['david', '10002'], ['dika', '10003'], ['firebird', '986'], ['gemak', '10004'], ['redis', '985'], ['ryan', '10005'], ['plesk45idw', '10007'], ['memcached', '984'], ['ajacid', '10008'], ['cobacute', '10009'], ['hwstrave', '10010'], ['invoice', '10010'], ['bengkellaptop', '10011'], ['davdolanan', '10012']]}}]}

**Screenshots**

**Versions Report**
The one that success
```
    [root@plesk-telkom ~]# salt-minion --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Apr  2 2020, 13:16:51)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed


```
All the fails :
```
    [root@locally ~]# salt-minion -V
/usr/lib/python2.7/site-packages/salt/scripts.py:212: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  2 2020, 13:16:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core




```

</details>

**Additional context**
Looks like the only one that success have no Tornado installed.

**Comment by garethgreenaway** [comment] 2020-11-17 17:56
@binooetomo Thanks for the report.  The problem is definitely related to the fact that you're importing`salt.client`.  If you remove those imports and update the `_mypopen` function to the following I believe if should resolve the issues you're seeing.

```
def _mypopen(cmd):
    myexec = __salt__['cmd.run'](cmd)
    return myexec.strip().split('\n')
```

**Comment by whytewolf** [comment] 2023-09-10 18:39
closing this issue, this was caused by importing salt.client into a module, which in turn will load the module which in turn loads salt.client so on and so forth. this is not proper inside a module.

**Closed by whytewolf** 2023-09-10 18:39 UTC
Labels: Pending-Discussion
