### ISSUE TITLE
Highstate running multiple times on Windows servers

### ISSUE THREAD

**Issue by OpusX** [saltstack/salt#33335] opened 2016-05-18 15:42 UTC
### Steps to Reproduce Issue
1) Kick off scheduled task that highstates machine
2) From command line run salt-call state.highstate
NOTE:  Multiple Highstates run whether logged in as same user or not

### Versions Report
v 2015.5.2

There is a scheduled task that runs highstate every 2 hours.  The highstate also runs on reboot.  Problem occurs when a user logs on and manually runs the highstate after box has been rebooted or during the scheduled task execution.  This causes 2 (or more) highstates to run simultaneously.  We have had multiple installation failures because of this.

I need a way to prevent multiple highstates from running concurrently.  I am under the impression that this is supposed to be default behavior....it is on Linux at least.

This has happened multiple times now and I am hoping that there is a safety to prevent the highstate from running again when it is already running on the server.

**Comment by cachedout** [comment] 2016-05-18 17:34
Hrm. I don't see offhand there this would be happening, though I do wonder if it's related to multiprocessing.

@twangboy what do you think here? Can you confirm this behavior?

**Comment by UtahDave** [comment] 2016-05-18 20:36
This is a known issue due to the salt proc system not working correctly on windows.

**Comment by OpusX** [comment] 2016-05-18 21:01
Is there an open bug we can track?

**Comment by Ch3LL** [comment] 2016-05-18 22:26
@OpusX I found this issue: #20836  . As this seems to be a duplicate of 20836 I will close this here and we can track it there.

**Closed by Ch3LL** 2016-05-18 22:26 UTC
