### ISSUE TITLE
[BUG] service beacon does not fire when emitatstartup is false

### ISSUE THREAD

**Issue by gbunt** [saltstack/salt#62675] opened 2022-09-13 15:49 UTC
**Description**
While testing the bugfix from https://github.com/saltstack/salt/pull/62096 in v3005-1, it seems that when `emitatstartup` is `False` for a service beacon, it never gets issued to master when a services' state changes.

**Setup**
Setup is a test environment, single master, 2 nodes. The following beacons 

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify) LXD 5.4
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
- Using the following beacons config:
```
$ salt 4fe54169-4253-4e66-bf87-9726f771ff7b pillar.item beacons
4fe54169-4253-4e66-bf87-9726f771ff7b:
    ----------
    beacons:
        ----------
        service:
            |_
              ----------
              services:
                  ----------
                  rngd:
                      ----------
                      emitatstartup:
                          False
                      onchangeonly:
                          True
                  sshd:
                      ----------
                      emitatstartup:
                          True
                      onchangeonly:
                          True
            |_
              ----------
              interval:
                  5
            |_
              ----------
              disable_during_state_run:
                  True
```
- If i issue a pillar refresh:
```
$ salt '*' saltutil.refresh_pillar
4fe54169-4253-4e66-bf87-9726f771ff7b:
    True
```
- I only see an event on the messagebus for sshd, as expected as `emitatstartup` is `False` for service rngd:
```
salt/beacon/4fe54169-4253-4e66-bf87-9726f771ff7b/service/sshd	{"sshd": {"running": true}, "service_name": "sshd", "id": "4fe54169-4253-4e66-bf87-9726f771ff7b", "_stamp": "2022-09-13T15:08:05.116873"}
```
- Stopping and starting service sshd correctly picks up the state change events:
```
salt/beacon/4fe54169-4253-4e66-bf87-9726f771ff7b/service/sshd	{"sshd": {"running": false}, "service_name": "sshd", "id": "4fe54169-4253-4e66-bf87-9726f771ff7b", "_stamp": "2022-09-13T15:08:15.064076"}
salt/beacon/4fe54169-4253-4e66-bf87-9726f771ff7b/service/sshd	{"sshd": {"running": true}, "service_name": "sshd", "id": "4fe54169-4253-4e66-bf87-9726f771ff7b", "_stamp": "2022-09-13T15:08:30.060864"}
```
- However, when stopping and starting service rngd, no events are sent to master. Just to rule out something weird going with `service.status` for rngd, i've also switched it around and configured service sshd with `emitatstartup: False` in which case, sshd service state changes were not sent to master when stopping- and starting the service.

**Expected behavior**
Regardless of the value for `emitatstartup`, service state changes must be picked up.

**Screenshots**

**Versions Report**
<details><summary>Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.8.1
       libgit2: Not Installed
      M2Crypto: 0.33.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.11
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 5.15.0-46-generic
        system: Linux
       version: CentOS Linux 7 Core
</summary>
</details>

**Additional context**
Btw. it's debatable whether a `saltutil.refresh_pillar` should count as "reload" of a minion. We've had several scenarios now where we _do_ need to refresh pillar (eg. to generate a pillar-based target based on new pillar data), but we don't want service state changes to be sent, resulting in reactor/orchestrator runs to kick off, while at the same time we _do_ need those to run when a minion is started and hence, for some services we do need `emitatstartup` to be set to `True`.

**Comment by OrangeDog** [comment] 2022-09-13 16:13
> it's debatable whether a `saltutil.refresh_pillar` should count as "reload" of a minion

I don't see why it should count as a service reload by any definition.

**Comment by garethgreenaway** [comment] 2022-09-14 00:00
Definitely looks like a bug if the beacon is not picking up on the state change of one service but is picking up on the state change of another, I'll try to reproduce.  As far as the pillar refresh counting as a service reload...to be clear, you're storing your beacon configuration in pillar, then doing a pillar refresh, which is reloading the beacon configuration for the minion from pillar.  This is reloading the configuration, while not a full reload or restart, it is refreshing and replacing the running beacon configuration.

**Comment by gbunt** [comment] 2022-09-14 07:55
> while not a full reload or restart, it is refreshing and replacing the running beacon configuration

From a technical perspective understandable given the modules are reloaded. It might be a good idea though to update the beacon docs as those only mention "when the minion is reload", which will likely be interpreted as either a restart or reload of the minion service.

Thanks for the quick follow up btw.

**Comment by Ch3LL** [comment] 2022-09-14 16:24
fixed by https://github.com/saltstack/salt/pull/62682

**Closed by Ch3LL** 2022-09-14 16:24 UTC
Labels: Bug, Beacon, Phosphorus v3005.0
