### ISSUE TITLE
state.low causing traceback

### ISSUE THREAD

**Issue by hunter86bg** [saltstack/salt#53870] opened 2019-07-16 16:44 UTC
### Description of Issue
During running a state.low all minions generate a traceback.

### Setup
```
master:/srv/salt # salt '*' state.low '{"state": "user", "fun": "present", "name": "wilma"}'
master:/srv/salt # salt '*' state.low '{state: user, fun: present, name: wilma}'
master:/srv/salt # salt-call --local state.show_low_sls user-wilma
local:
    |_
      ----------
      __env__:
          base
      __id__:
          user_wilma
      __sls__:
          user-wilma
      fun:
          present
      name:
          wilma
      order:
          10000
      state:
          user
```

### Steps to Reproduce Issue
Run the state.low and a traceback is generated:
```
ubuntu19:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1645, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 454, in low
        ret = st_.call(data)
      File "/usr/lib/python3/dist-packages/salt/utils/decorators/state.py", line 30, in _func
        result = func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/state.py", line 1977, in call
        ret['__id__'] = low['__id__']
    KeyError: '__id__'
opensuse15:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1597, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/state.py", line 454, in low
        ret = st_.call(data)
      File "/usr/lib/python3.6/site-packages/salt/utils/decorators/state.py", line 23, in _func
        result = func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/state.py", line 1951, in call
        ret['__id__'] = low['__id__']
    KeyError: '__id__'
centos7:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1597, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 454, in low
        ret = st_.call(data)
      File "/usr/lib/python2.7/site-packages/salt/utils/decorators/state.py", line 23, in _func
        result = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1937, in call
        ret['__id__'] = low['__id__']
    KeyError: u'__id__'
openbsd65:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 454, in low
        ret = st_.call(data)
      File "/usr/local/lib/python2.7/site-packages/salt/utils/decorators/state.py", line 23, in _func
        result = func(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1970, in call
        ret['__id__'] = low['__id__']
    KeyError: u'__id__'
```

### Versions Report

```
master:/srv/salt # salt '*' pkg.version salt-minion salt
openbsd65:
    ----------
    salt:
        2018.3.3p0
    salt-minion:
ubuntu19:
    ----------
    salt:
    salt-minion:
        2018.3.4~git20180207+dfsg1-1
centos7:
    ----------
    salt:
        2018.3.0-33.1
    salt-minion:
        2018.3.0-33.1
opensuse15:
    ----------
    salt:
        2018.3.0-lp150.3.27.1
    salt-minion:
        2018.3.0-lp150.3.27.1
master:/srv/salt # salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.2
 
System Versions:
           dist: SuSE 42.3 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.180-102-default
         system: Linux
        version: openSUSE  42.3 x86_64
```

####################################
I'm learning salt with "Salt Essentials" and despite being a little bit older - the state.low should work.
Using the example from sys.doc for "state.low" leads to a traceback:

```
# salt 'centos7' state.low '{"state": "pkg", "fun": "installed", "name": "vim-enhanced"}'
centos7:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1597, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 454, in low
        ret = st_.call(data)
      File "/usr/lib/python2.7/site-packages/salt/utils/decorators/state.py", line 23, in _func
        result = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1937, in call
        ret['__id__'] = low['__id__']
    KeyError: u'__id__'
```

**Comment by hunter86bg** [comment] 2019-07-16 16:46
Hm... the formatting of my first comment is out of control. Just ignore bolds/italic/difference in size.

**Comment by waynew** [comment] 2019-07-18 22:18
@hunter86bg thanks for reporting this! I've fixed the formatting - if you click the little markdown icon at the bottom right you can see how to do formatting fun.

Something is definitely off here, though!

**Comment by OrangeDog** [comment] 2019-10-28 17:00
Duplicate of #45682

**Comment by waynew** [comment] 2020-02-27 21:03
Closing this and adding #45682 to the planning instead.

**Closed by waynew** 2020-02-27 21:03 UTC
Labels: 2018.3, 2019.2, Bug, Confirmed, develop
