### ISSUE TITLE
pkg.installed always fails for custom package

### ISSUE THREAD

**Issue by mirko** [saltstack/salt#34867] opened 2016-07-21 23:50 UTC
I'm experiencing the issue, that ensuring a pkg-state for a custom deb file always fails.
The package gets installed fine and the dpkg call succeeds. Even if the package is already installed (state being pushed before or package installed manually) ensuring the state fails.

relevant content of sls file:
```
grafana-data:
  pkg.installed:
    - sources:
      - salt-repo: salt://mon-master/grafana-data_2.6.0+dfsg-3_all.deb
```

Output:
```
          ID: grafana-data
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: salt-repo
     Started: 23:44:16.500298
    Duration: 10845.388 ms
     Changes:
```

Observed call on minion:
```
\_ /usr/bin/python2.7 /var/tmp/.conf_7c7bca_salt/salt-call --local --metadata --out json -l quiet -c /var/tmp/.conf_7c7bca_salt -- state.pkg /var/tmp/.conf_7c7bca_salt/salt_state.tgz test=None pkg_sum=e954a4212dc0658cdd4a252a079c32fb hash_type=md5
    \_ dpkg -i --force-confold /var/tmp/.conf_7c7bca_salt/running_data/var/cache/salt/minion/files/base/mon-master/grafana-data_2.6.0+dfsg-3_all.deb
```

Call executed manually (*just for reference, since even if package is installed enforcing state fails!*):
```
# dpkg -i --force-confold /var/tmp/.conf_7c7bca_salt/running_data/var/cache/salt/minion/files/base/mon-master/grafana-data_2.6.0+dfsg-3_all.deb ; echo $?
(Reading database ... 52147 files and directories currently installed.)
Preparing to unpack .../grafana-data_2.6.0+dfsg-3_all.deb ...
Unpacking grafana-data (2.6.0+dfsg-3) over (2.6.0+dfsg-3) ...
Setting up grafana-data (2.6.0+dfsg-3) ...
0
```

**Comment by derekmaciel** [comment] 2016-07-22 07:33
Possibly related to #34861

**Comment by Ch3LL** [comment] 2016-07-26 16:53
@mirko I believe this is a duplicate of #34508 But ust to make certain its a duplicate are you also seeing the package installed under the `changes` output for example:

```
     Changes:   
              ----------
              alien:
                  ----------
                  new:
                      8.93
                  old:
```

**Comment by mirko** [comment] 2016-07-26 17:16
If grafana is *already installed*:
```
[..]
----------
          ID: grafana-data
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: local
     Started: 17:12:07.389679
    Duration: 31194.915 ms
     Changes:   
----------
          ID: grafana
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: local
     Started: 17:12:38.608266
    Duration: 28571.105 ms
     Changes:   
----------
          ID: grafana
    Function: file.managed
        Name: /etc/grafana/grafana.ini
      Result: False
     Comment: One or more requisite failed: mon-master.grafana
     Started: 
    Duration: 
     Changes:   
----------
          ID: grafana
    Function: service.running
      Result: False
     Comment: One or more requisite failed: mon-master.grafana
     Started: 
    Duration: 
     Changes:   

Summary for mon.nanl.de
-------------
Succeeded: 64
Failed:     4
-------------
Total states run:     68
```

If grafana is *not yet installed*:
```
[..]
----------
          ID: grafana-data
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: local
     Started: 17:14:10.125238
    Duration: 15505.545 ms
     Changes:   
              ----------
              grafana-data:
                  ----------
                  new:
                      2.6.0+dfsg-3
                  old:
----------
          ID: grafana
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: local
     Started: 17:14:27.184569
    Duration: 28430.111 ms
     Changes:   
              ----------
              grafana:
                  ----------
                  new:
                      2.6.0+dfsg-3
                  old:
----------
          ID: grafana
    Function: file.managed
        Name: /etc/grafana/grafana.ini
      Result: False
     Comment: One or more requisite failed: mon-master.grafana
     Started: 
    Duration: 
     Changes:   
----------
          ID: grafana
    Function: service.running
      Result: False
     Comment: One or more requisite failed: mon-master.grafana
     Started: 
    Duration: 
     Changes:   

Summary for mon.nanl.de
-------------
Succeeded: 64 (changed=2)
Failed:     4
-------------
Total states run:     68
```

I assume that qualifies for a *yes* as an answer.

**Comment by Ch3LL** [comment] 2016-09-21 21:55
Okay great thanks for checking that. I will close this issue and we can track the issue in the other issue. Thanks

**Closed by Ch3LL** 2016-09-21 21:55 UTC
Labels: Duplicate, Info Needed
