### ISSUE TITLE
Include "runas" argument in djangomod.command module

### ISSUE THREAD

**Issue by andhieka** [saltstack/salt#39224] opened 2017-02-07 16:04 UTC
### Description of Issue/Question

Category: **Feature Request**

I use SaltStack in masterless mode, and my main usage pattern is `sudo salt-call --local state.apply`. I use `sudo` is because I use salt to manage nginx, redis, etc. whose configuration files are only editable by `root`. As the result, I need to use the `- runas` argument of `cmd.run` module whenever I need to run a command not as root.

I need to run [djangomod.collectstatic](https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/modules/djangomod.py#L178), and module not as root, because otherwise the collected static files cannot be served by web servers like nginx, etc. Besides djangomod.collectstatic, I also need to run djangomod.command as non-root user for some management tasks. However, djangomod does not currently accept `runas` argument or the likes.

Since djangomod is implemented by calling `cmd.run` module, this behaviour is actually simple to achieve.  We can modify the last line of [djangomod.command](https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/modules/djangomod.py#L72):

```__salt__['cmd.run'](cmd, env=env, python_shell=False)``` 

either by explicitly reading and passing `runas` argument or passing `**kwargs` altogether to `cmd.run`.

I would love to hear opinion from the core salt team about this. I think this usage pattern should be fairly common to saltstack users who manage a django deployment. Hence this feature would benefit many. I would be happy to provide a pull request.

### Checklist
 - [ ] Modify the last line of [djangomod.command](https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/modules/djangomod.py#L72).
 - [ ] Update documentation of djangomod module, adding runas as an accepted argument.
 - [ ] Do some manual testing.
 - [ ] Do some unit testing if possible.

**Comment by gtmanfred** [comment] 2017-02-07 17:42
My recommendation would be to only pass runas to cmd.run, and not all of kwargs.

I have dropped this into our #dev channel on slack and asked for more feed back for you if anyone else has time.

Thanks!
Daniel

**Comment by andhieka** [comment] 2017-02-08 03:44
Thank you @gtmanfred. I have been browsing other issues and I noticed my use case seems like a subset of a more general feature request #37835 "Make "runas" a global state argument iso specific to cmd.run". Do you think so?

**Comment by gtmanfred** [comment] 2017-02-08 03:45
Yup, I would agree with that.

**Comment by andhieka** [comment] 2017-02-08 03:48
But I'm not sure whether anyone has started working on #37835. Moreover, it seems more difficult and I don't know where to start if I were to help 😅

**Comment by gtmanfred** [comment] 2017-02-08 15:44
In that case, I am going to close this as a duplicate of #37835

Thanks,
Daniel

**Closed** 2017-02-08 15:45 UTC
Labels: Duplicate, Feature, Platform, TEAM Platform

**Comment by gtmanfred** [comment] 2017-02-08 16:15
We will see how this is taken https://github.com/saltstack/salt/pull/39248

:D
