### ISSUE TITLE
Issues with pip states in 2015.8

### ISSUE THREAD

**Issue by moloney** [saltstack/salt#28239] opened 2015-10-22 22:54 UTC
I installed the `python-pip` package before trying to use any pip states. However, when trying to run any pip.installed states I get the error:

> "An importable pip module is required but could not be found on your system. This usually means that the systems pip package is not installed properly"

I can login to the minion, fire up python, and do `import pip` and `import pip.req` without any issue. Doing `pip install -U pip` fixes the issue.

This issue didn't come up on 2015.5 and it didn't occur on any servers I updated from 2015.5 to 2015.8.

**Comment by jfindlay** [comment] 2015-10-23 23:38
@moloney, thanks for the report.  This problem only happens on systems newly provisioned (not upgraded) with 2015.8.0 or later?

**Comment by jfindlay** [comment] 2015-10-23 23:39
Were you upgrading from systems that were installed with bootstrap?  It might be possible that bootstrap was upgrading pip.

**Comment by rallytime** [comment] 2015-10-26 18:07
@moloney I suspect this is a duplicate of #21845 and I am curious if my fix for that issue works for you as well. Can you give the changes made in #27996 a try and see if that resolves this issue for you? If so, that fix will be available in 2015.8.2.

**Comment by moloney** [comment] 2015-11-04 21:23
Sorry for being slow to respond.

@jfindlay - All systems were installed with salt-bootstrap.  However since it currently doesn't install 2015.8, I had to use pip to upgrade salt from 2015.5 to 2015.8 after the bootstrap.  Systems that had already been configured under 2015.5 (i.e. already ran the highstate) before upgrading to 2015.8 didn't show the issue.  Systems that applied their first highstate on 2015.8 did show the problem.

@rallytime - Pretty sure that is a separate issue, the error is different.

**Comment by rallytime** [comment] 2015-11-04 21:44
@moloney Perhaps, however, I don't think so. That same `An importable pip module is required but could not be found on your system.` message was exactly what I was seeing when I was investigating/fixing the previously mentioned bug. The `pip install` and `echo $?` output mentioned at the top of #21845 was the resulting confirmation that the exit codes of that command are different between pip versions. Which is why upgrading pip also worked here.

My fix in #27996 allows for both versions of pip to work correctly with the imports necessary for the pip state file. (I was also able to `import pip` and `import pip.req` just fine from a python interpreter, but the pip state file imports didn't work.) This fix makes it so that upgrading pip wouldn't be necessary.

Does that help explain why this should be fixed now?

**Comment by cachedout** [comment] 2015-11-30 23:20
@moloney Did you see the above comment from @rallytime? We'd like to figure out a way to verify if this has been fixed or if additional work is needed. Thanks.

**Comment by moloney** [comment] 2015-12-08 00:45
Hi, sorry again for the delay. The branch in the @rallytime repo was already deleted, so I tried to test by doing the bootstrap on a fresh system with the command:

$ sh install_salt.sh -P -F -U -A mymaster.example.com -g https://github.com/saltstack/salt.git git 2015.5

The version string from "salt-minion --version" is "salt-minion 2015.5.8-14-g0918c92 (Lithium)".  The bug does not show up here, but honestly I am not sure I did the test correctly.

**Comment by rallytime** [comment] 2015-12-08 00:52
@moloney That looks like the correct way to install from the head of 2015.5 to me, which would include the mentioned fixes, FWIW. :)

**Comment by moloney** [comment] 2015-12-08 01:19
Awesome, thanks for the fix!

**Comment by rallytime** [comment] 2015-12-08 01:30
Sure thing! I'll go ahead and close this up, but let us know if you run into any problems. Thanks!

**Closed by rallytime** 2015-12-08 01:30 UTC
Labels: Bug, Execution Module, Fixed Pending Verification, High Severity, P3, Platform, Regression
