### ISSUE TITLE
SLS files cannot contain period character (.)

### ISSUE THREAD

**Issue by Bilge** [saltstack/salt#19513] opened 2015-01-08 10:20 UTC
If one were to name an SLS file `example 1.0.sls` it is impossible to create a top file that can point to it. The following top file will generate the following error.

```yml
base:
  '*':
    - example 1.0
```

>\- No matching sls found for 'example 1.0.sls' in env 'base'

**Comment by rallytime** [comment] 2015-01-08 21:13
@Bilge thanks for opening this issue. This is expected behavior. When the state system was first devised with the top file, the decision was made to follow the python import model where dots are interpreted as slashes. This means that `example 1/0.sls` would work, but not the example you've provided.

After a quick glance at our docs, however, I can't seem to find any prominent references to this fact. I'm going to label this as a documentation fix. Whomever fixes this bug should include this point both on the FAQ page as well as one of the prominent SLS pages such as http://docs.saltstack.com/en/latest/topics/tutorials/starting_states.html.

**Comment by Bilge** [comment] 2015-01-08 21:17
I guess it's too late to change it, due to backwards compatibility breaking, but it should not otherwise be necessary to support dot as a path separator since slashes work for this purpose like normal file paths.

**Comment by twellspring** [comment] 2015-01-20 05:08
Found that this behavior happens in both top.sls and in include statements in other sls files. 

This issue is fixed in the documentation in pull request #19859

Best place to put this information was in the SLS Namespace section of doc/topics/tutorials/states_pt1.rst
Also created an include and inserted it in two other locations.  I looked at the FAQ and I don't think this issue warrants an entry there.

**Comment by rallytime** [comment] 2015-01-22 07:55
Thanks for the documentation fix @twellspring! I didn't realize that there was already another issue opened about this. As such, and since the docs have now been updated, I am going to close this one as a duplicate of the earlier issue. I think there is more discussion on that issue to go on. If anyone feels to the contrary, leave a comment and we can re-open the issue and discuss. Thanks all!

**Closed by rallytime** 2015-01-22 07:55 UTC
Labels: Documentation, Fixed Pending Verification, Low-Hanging Fruit

**Comment by leeclemens** [comment] 2015-02-13 23:31
While sub directories make sense for things that are hierarchical (like example.com), mirroring directory names like "conf.d" in the path don't fit as nicely into that workaround. I just wanted to add that use-case.

**Comment by damon-atkins** [comment] 2015-06-08 04:49
Its not documented in http://docs.saltstack.com/en/latest/topics/pillar/index.html that you can not use dot in the file name. I suggest if file name restrictions exist that they are documented on the relevant pages. Thanks

If you currently do it by mistake we get
[ERROR ] Specified SLS 'abc.one.two' in environment 'base' is not available on the salt master
[CRITICAL] Pillar render error: Specified SLS 'abc.one.two' in environment 'base' is not available on the salt master

It does not inform you that dot in the name is not allowed.

**Comment by martinadolfi** [comment] 2018-01-02 15:49
Hi, I can see that there's no more reference to the dot issue in the current docs (2017.7.2). Is it because there's a workaround? o it's just that they forgot to put it there?
Thanks!
