### ISSUE TITLE
update failure

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#33812] opened 2016-06-07 04:05 UTC
### Description of Issue/Question

salt no longer updates a client while running a high.state.

update[.sls]  is in top.sls

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

-bash-4.1# more update.sls 
{% if grains['os_family'] == 'RedHat' %}
pkg.upgrade:
  module.run
{% endif %}
-bash-4.1#

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

When running this code,

-bash-4.1# more update.sls 
{% if grains['os_family'] == 'RedHat' %}
pkg.upgrade:
  module.run
{% endif %}
-bash-4.1#

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

=====client=====
-bash-4.1# salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-573.18.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.7 Santiago
 
-bash-4.1#
==============

====server====
-bash-4.1# salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-573.18.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.7 Santiago
 
-bash-4.1# 
===============

While running a high.state part of upgrading RHEL6.8 is to patch it, but I get this error,

----------
          ID: pkg.upgrade
    Function: module.run
      Result: False
     Comment: Module function pkg.upgrade threw an exception. Exception: 'NoneType' object is not iterable
     Started: 15:42:59.897830
    Duration: 6944.157 ms
     Changes:   
----------

command is,

-bash-4.1# more update.sls 
{% if grains['os_family'] == 'RedHat' %}
pkg.upgrade:
  module.run
{% endif %}
-bash-4.1#

**Comment by githubcdr** [comment] 2016-06-07 08:30
Probably related to https://github.com/saltstack/salt/issues/33609

**Comment by Ch3LL** [comment] 2016-06-07 21:36
@gzcwnk yes this is a duplicate of 33609. I will close this as a duplicate and keep the other issue open and we can track the issue there. Thanks

**Closed by Ch3LL** 2016-06-07 21:36 UTC
