### ISSUE TITLE
[BUG] pkgrepo.managed fails to configure ppa on Ubuntu 20.10

### ISSUE THREAD

**Issue by raczkow** [saltstack/salt#59065] opened 2020-12-02 08:30 UTC
**Description**
After upgrade to Ubuntu 20.10, I can't setup my ppa repositories. Running high.state fails with error:
```
          ID: ppa keepassxc
    Function: pkgrepo.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2153, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/pkgrepo.py", line 396, in managed
                  pre = __salt__["pkg.get_repo"](repo=repo, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/aptpkg.py", line 1735, in get_repo
                  repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(
              AttributeError: 'PPAShortcutHandler' object has no attribute 'expand'
     Started: 09:03:34.633592
    Duration: 1068.175 ms
```
Looks, like changes in `python3-software-properties` break salt.

**Setup**
I'm using masterless salt configuration.

sls that fails to run:

```
ppa keepassxc:
  pkgrepo.managed:
    - ppa: phoerious/keepassxc
```

**Steps to Reproduce the behavior**
1. set sls to configure ppa with `pkgrepo.managed`
2. run high.state

**Expected behavior**
ppa is properly configured.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: 4.1.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.6 (default, Sep 25 2020, 09:36:53)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.10 groovy
         locale: utf-8
        machine: x86_64
        release: 5.8.0-29-lowlatency
         system: Linux
        version: Ubuntu 20.10 groovy
```
</details>

<details><summary>python3-software-properties version</summary>

```
||/ Name                        Version
+++-===================================
ii  python3-software-properties 0.99.3 
```
</details>

**Additional context**
Salt installed from official Ubuntu 20.10 packages. Problem also exists on latest 3002.2 provided from saltstack repositories.

**Comment by OrangeDog** [comment] 2020-12-03 11:24
The `expand` method doesn't appear to have any documentation so it's not clear what replaces it.

I'm not even sure the python API is supposed to be public. The `PPAShortcutHandler` class is completely different, with no mention in the changelog. Perhaps salt should be using the CLI instead (`add-apt-repository`).

**Comment by MurzNN** [comment] 2020-12-21 07:42
I got the same problem, here is my sls part that generate this error:
```
plasma-applet-qalculate:
  pkgrepo.managed:
    - ppa: dschopf/plasma-applet-qalculate
  pkg.installed:
    - pkgs:
      - qalculate
      - plasma-applet-qalculate

**Comment by krionbsd** [comment] 2021-01-05 09:12
Hmm I couldn't reproduce it with 3002.2, could you please try 3002.2?

**Comment by raczkow** [comment] 2021-01-05 17:01
Looks like it works now both on 3002.2 from Saltstack repo and on 3001+dfsg1-2 from Ubuntu repository. Ubuntu devs had to fixed python3-software-properties package.

But there's one new small issue now: every time I run high state, ppa repositories are updated.

```

```

**Comment by krionbsd** [comment] 2021-01-05 17:11
@raczkow are you ok to close this issue?

**Comment by raczkow** [comment] 2021-01-05 17:15
Yes, it's OK.
I'll check why ppa repos are changing every high state when I get more spare time. I'll open next issue when I get more informations.

**Comment by krionbsd** [comment] 2021-01-05 17:16
cool, thanks a lot @raczkow

**Comment by ngirard** [comment] 2021-01-09 15:53
Happy new year folks,

although this issue is closed, I'm experiencing the problem here on Ubuntu 20.10 running 3002.2 from Saltstack repo. python3-software-properties version is 0.99.3.

Cheers

**Comment by Artanicus** [comment] 2021-04-28 16:47
FYI for anyone finding this issue, looks like the problem was merely punted forward into Ubuntu 21.04 which includes Salt 3002.2. So the problem isn't solved but more like postponed. Installing 3003.3 does not resolve the issue, but since the distribution includes 3002.2 that's what I'll list below.

```
%> apt show salt-minion                
Package: salt-minion
Version: 3002.2+dfsg1-1
Priority: optional
Section: universe/admin
Source: salt
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Salt Team <pkg-salt-team@alioth-lists.debian.net>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 119 kB
Pre-Depends: init-system-helpers (>= 1.54~)
Depends: dctrl-tools, lsb-base (>= 3.0-6), python3-pycryptodome (>= 2.6) | python3-crypto (>= 2.6), python3-systemd | sysvinit-core, python3-zmq (>= 13.1.0), salt-common (= 3002.2+dfsg1-1), python3:any
Recommends: debconf-utils, dmidecode, e2fsprogs, sfdisk
Suggests: python3-augeas
Homepage: http://saltstack.org/
Download-Size: 27.7 kB
APT-Manual-Installed: yes
APT-Sources: http://fi.archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
Description: client package for salt, the distributed remote execution system
```

```
%> apt show python3-software-properties        
Package: python3-software-properties
Version: 0.99.10
Priority: optional
Section: python
Source: software-properties
Origin: Ubuntu
Maintainer: Michael Vogt <michael.vogt@ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 197 kB
Depends: gpg, iso-codes, lsb-release, python3, python3-apt (>= 0.6.20ubuntu16), python3-gi, python3-launchpadlib, python3:any
Recommends: unattended-upgrades
Task: server, ubuntu-desktop-minimal, ubuntu-desktop, cloud-image, server-raspi, kubuntu-desktop, xubuntu-core, xubuntu-desktop, lubuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-budgie-desktop, ubuntu-budgie-desktop-raspi
Download-Size: 32.0 kB
APT-Manual-Installed: yes
APT-Sources: http://fi.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
Description: manage the repositories that you install software from
```

**Comment by raczkow** [comment] 2021-05-13 12:48
@krionbsd This bug should be reopened as it still doesn't work in Ubuntu 20.10 and, as @Artanicus said - on Ubuntu 21.04

I have confirmed, that it was fixed in Ubuntu 20.10 but apparently  it is not. I didn't noticed that I already patched my `/usr/lib/python3/dist-packages/salt/modules/aptpkg.py` to workaround the problem. Here's my patch:

```
--- aptpkg.py~	2020-06-17 20:05:55.000000000 +0200
+++ aptpkg.py	2021-05-12 14:35:46.578742084 +0200
@@ -1732,9 +1732,10 @@
             if HAS_SOFTWAREPROPERTIES:
                 try:
                     if hasattr(softwareproperties.ppa, "PPAShortcutHandler"):
-                        repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(
-                            dist
-                        )[0]
+                        #repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(
+                        #    dist
+                        #)[0]
+                        repo = ''
                     else:
                         repo = softwareproperties.ppa.expand_ppa_line(repo, dist)[0]
                 except NameError as name_error:
@@ -2549,9 +2550,10 @@
         else:
             if HAS_SOFTWAREPROPERTIES:
                 if hasattr(softwareproperties.ppa, "PPAShortcutHandler"):
-                    repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(dist)[
-                        0
-                    ]
+                    #repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(dist)[
+                    #    0
+                    #]
+                    repo = ''
                 else:
                     repo = softwareproperties.ppa.expand_ppa_line(repo, dist)[0]
             else:
```
With this patch I am allowed to configure PPA with salt, but PPA repos are changing every time I run a high state. It works for me, but it is not a good solution :-/

**Comment by cloudwitch** [comment] 2022-02-14 21:48
Seeing it in Ubuntu 22.04 pre-release, salt-minion 3004 (installed from `https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal InRelease`:
```
chromium ppa:
  pkgrepo.managed:
    - ppa: phd/chromium-browser
```

```
/srv/salt$ sudo salt-call --local state.apply work_laptop.programs.chromium
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2179, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/pkgrepo.py", line 400, in managed
    pre = __salt__["pkg.get_repo"](repo=repo, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/aptpkg.py", line 1850, in get_repo
    repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(
AttributeError: 'PPAShortcutHandler' object has no attribute 'expand'

local:
----------
          ID: chromium ppa
    Function: pkgrepo.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2179, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/pkgrepo.py", line 400, in managed
                  pre = __salt__["pkg.get_repo"](repo=repo, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/aptpkg.py", line 1850, in get_repo
                  repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(
              AttributeError: 'PPAShortcutHandler' object has no attribute 'expand'
     Started: 15:45:21.422122
    Duration: 2663.127 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   2.663 s
```

**Comment by tuck182** [comment] 2022-05-05 02:43
Still happening with 3004.1. I'm not sure whether this is the right fix, but this is the patch I'm using locally, which seems to work and also doesn't change the PPA repo entry every time it runs:

```
--- /usr/lib/python3/dist-packages/salt/modules/aptpkg.py.orig  2022-05-04 18:45:18.181727709 -0700
+++ /usr/lib/python3/dist-packages/salt/modules/aptpkg.py       2022-05-04 19:31:25.042603741 -0700
@@ -1847,9 +1847,11 @@
             if HAS_SOFTWAREPROPERTIES:
                 try:
                     if hasattr(softwareproperties.ppa, "PPAShortcutHandler"):
-                        repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(
-                            dist
-                        )[0]
+                        handler = softwareproperties.ppa.PPAShortcutHandler(repo)
+                        if hasattr(handler, "expand"):
+                            repo = handler.expand(dist)[0]
+                        else:
+                            repo = handler.SourceEntry().line
                     else:
                         repo = softwareproperties.ppa.expand_ppa_line(repo, dist)[0]
                 except NameError as name_error:
@@ -1930,7 +1932,11 @@
                 repo = LP_SRC_FORMAT.format(owner_name, ppa_name, dist)
         else:
             if hasattr(softwareproperties.ppa, "PPAShortcutHandler"):
-                repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(dist)[0]
+                handler = softwareproperties.ppa.PPAShortcutHandler(repo)
+                if hasattr(handler, "expand"):
+                    repo = handler.expand(dist)[0]
+                else:
+                    repo = handler.SourceEntry().line
             else:
                 repo = softwareproperties.ppa.expand_ppa_line(repo, dist)[0]

@@ -2657,9 +2663,11 @@
         else:
             if HAS_SOFTWAREPROPERTIES:
                 if hasattr(softwareproperties.ppa, "PPAShortcutHandler"):
-                    repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(dist)[
-                        0
-                    ]
+                    handler = softwareproperties.ppa.PPAShortcutHandler(repo)
+                    if hasattr(handler, "expand"):
+                        repo = handler.expand(dist)[0]
+                    else:
+                        repo = handler.SourceEntry().line
                 else:
                     repo = softwareproperties.ppa.expand_ppa_line(repo, dist)[0]
             else:
```

**Comment by christophlsa** [comment] 2022-10-02 00:06
I have the same issue. The patch in https://github.com/saltstack/salt/issues/59065#issuecomment-1118112165 helped.

**Comment by digitalcircuit** [comment] 2022-10-06 23:59
Retesting with the most recent Salt 3005.1 release, this issue still exists.

**Comment by nickhilliard** [comment] 2022-11-19 00:48
Confirmed that this is still a problem on Ubuntu 22.04 + Salt 3004.1.  The patch in https://github.com/saltstack/salt/issues/59065#issuecomment-1118112165 fixes it. It would be great if this could be committed.

**Comment by dfidler** [comment] 2022-12-21 01:16
Confirmed still happening in 3005.1
```
# salt-minion --version
salt-minion 3005.1

# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

**Comment by dfidler** [comment] 2022-12-21 01:40
Ummm... I have to amend the above.  I have two ubuntu systems, both started their lives as 20.04LTS and have gone through do-release-upgrade.  Both have 3005.1 installed.

However, I got the error on one of the systems but not on the other.  

Here's the diff between them:

**Server WITHOUT error:**
```
# cat /etc/apt/sources.list.d/salt.list
deb [signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main
```

As you can see, on the server that doesn't fail, this is a onedir package.  

**Server WITH error **
```
# cat /etc/apt/sources.list.d/salt.list
deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal main
```

As you can see, this is a legacy package for Ubuntu 20 (focal)... not 22 (jammy)

So.. I updated my apt-source by following the install guide (https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html#install-onedir-packages-of-salt-on-ubuntu-22-04-jammy) to update to a onedir package.

After running the following....
```
apt-get update 
apt-get dist-upgrade 
systemctl restart salt-minion
```

... no more error.  

Moral of the story....  Don't forget to update third-party apt sources when doing a release upgrade.  :/

**Comment by dfidler** [comment] 2022-12-21 01:46
This begs the question (for another thread), should the salt-minion issue an "unsupported os version for salt-minion" warning when running jobs to help incompetent people, like me, to do a proper upgrade?  :)

**Comment by alexhayes** [comment] 2022-12-28 11:16
Confirmed this exists in a brand new Ubuntu 22.04.1 LTS (installed on OSX using multipass).

```bash
$ salt-minion --version
salt-minion 3005.1
```

```bash
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

Note I've done `apt-get update && apt-get upgrade && service salt-minion restart` but that didn't help.

The patch in [#59065 (comment)](https://github.com/saltstack/salt/issues/59065#issuecomment-1118112165) fixed it for me and I applied it using a salt-state (on my masterless-minion).

```yaml
{% if grains.saltversion == "3005.1" %}

# Just in case there is no patch command installed
patch:
  pkg.installed

# We use directory name here (saltpath) to apply patches that touch multiple files
patch_applied_59065:
  file.patch:
    - name: '{{ grains.saltpath }}'
    - source: salt://patches/files/saltstack_issue_59065.diff
    - strip: 6
    - require:
        - pkg: patch

# Restart salt minion after the patch is applied and the config option is set
restart_salt_minion:
  cmd.run:
    - name: 'salt-call service.restart salt-minion'
    - bg: true
    - onchanges:
      - patch_applied_59065
{%- endif %}
```

Where `patches/files/saltstack_issue_59065.diff` is the patch as referenced above.

**Comment by yadkov** [comment] 2023-04-03 06:51
The bug can be bypassed by switching to a regular type of repository instead of ppa. E.g.:
```
formula.python.ubuntu.deadsnakes.repo:
  pkgrepo.managed:
    - ppa: deadsnakes/ppa
    - refresh: true
  ```
to 
```
formula.python.ubuntu.deadsnakes.repo:
  pkgrepo.managed:
     - name: "deb [signed-by=/etc/apt/keyrings/deadsnakes.gpg] https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu {{ grains.oscodename }} main"
    - file: /etc/apt/sources.list.d/deadsnakes.list
    - key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xba6932366a755776
    - aptkey: False
    - refresh: true
  ```

**Comment by cp-samantha** [comment] 2023-05-17 20:38
I find dfidler's response is still accurate today ( https://github.com/saltstack/salt/issues/59065#issuecomment-1360653475 ). The onedir version meant for jammy doesn't have this issue.

It's worth noting that the 22.04 server that I bumped into this issue on was only provisioned yesterday, but used the salt-bootstrap.sh script to provision salt on this server (forcing an install of the 3005 branch with the options).

The bootstrap script incorrectly provisioned the repo to point to the focal/20.04 classic download repo and not using the onedir repo. Installer made no complaints and the install was generally functional except for this issue.

Since swapping the repo list to the following and upgrading packages:
```
deb [signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/3005 jammy main
```

The problem has vanished. So I would encourage folks to check their jammy repos as they may not be what you expect them to be. As far as I can tell, all releases meant for Jammy should be onedir only. There have been **no** classic releases for jammy (classic https://repo.saltproject.io/py3/ubuntu/ vs onedir https://repo.saltproject.io/salt/py3/ubuntu/)

Just postulating here, but it's possible onedir doesn't have this problem since python is self-contained and doesn't require the OS to have python installed to be functional.

**Comment by dmurphy18** [comment] 2023-07-11 21:11
To confirm, there are no classic packages for Jammy, and only onedir packages were built for Jammy.
With Salt 3006.x only onedir package are being supported going forward, 3005.1 were the last classic packages.
Onedir packages where Salt has control over shipping dependencies, including the version of Python, is the method going forward.  Understand Jammy is recent, but look at RHEL 7, Py 3.6 out of date, not to mention OS dependencies, hence the reason for onedir style of packaging,

Closing this issue since there is a work-around, and the direction forward is onedir which does not exhibit the problem, but please re-open if you feel there is other information relevant to the issue

**Closed by dmurphy18** 2023-07-11 21:11 UTC
Labels: Bug, severity-medium, ubuntu, package-repo

**Comment by roelandjansen** [comment] 2024-07-03 06:00
@alexevan13

we faced this too in our salt code where the fix also was to remove python3-software-properties.
