### ISSUE TITLE
RedHat/CentOS 6: ImportError: cannot import name certs

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#43739] opened 2017-09-26 10:52 UTC
### Description of Issue/Question

I'm trying to use requests in one of my execution modules, but when I try to import I get an error.
Currently, salt ships requests 2.6.0, upgrading to 2.6.1 fixes the issue.

### Setup / Steps to reproduce
Try to run custom module that imports `requests`. Here is snippet of the debug log

```bash
[ERROR   ] cannot import name certs
Traceback (most recent call last):
  File "/var/cache/salt/minion/extmods/modules/abc.py", line 24, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs
[DEBUG   ] Failed to import module wazuh:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1411, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/abc.py", line 24, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs
[DEBUG   ] Failed to import module pagerduty_util:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1411, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/modules/pagerduty_util.py", line 24, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs
```

### Workarounds

* Use older version of salt, or

* Install newer version of requests package

```bash
yum -y install python27-pip
pip2.7 install requests==2.6.1
```

### Versions Report
```yaml
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by garethgreenaway** [comment] 2017-09-26 18:24
@dmurphy18 Would you mind commenting on this one?

**Comment by dmurphy18** [comment] 2017-09-26 21:15
@rossengeorgiev @garethgreenaway This is due to an issue with the version of python-requests (v2.6.0) used to build python27-requests.  The next point release which will be soon is built using v2.7.0 for python27-requests. This is a duplicate of https://github.com/saltstack/salt-pack/issues/412.
Hence closing this as an issue since it has already been addressed and the fix will be released soon.
Thanks for bring it to attention though.

**Closed by dmurphy18** 2017-09-26 21:15 UTC
Labels: Duplicate, Packaging, Platform, TEAM Platform

**Comment by rossengeorgiev** [comment] 2017-09-26 21:17
Thanks @dmurphy18 and sorry for the duplicate
