### ISSUE TITLE
Salt does not run "systemd daemon-reload" on unit override

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#34927] opened 2016-07-25 15:32 UTC
### Description of Issue/Question

When some package provides legacy init.d script but you wish to use your own shiny systemd unit file, salt resists to help out.

### Setup

I managed to get "minimal" working example. There may be extra bits here, but the whole thing shows the issue.

State in question (the only one):

```yaml
dbus:
  pkg.installed:
    - name: dbus
  service.running:
    - name: dbus
    - sig: dbus-daemon
    - enable: true

/usr/sbin/policy-rc.d:
  file.managed:
    - mode: 755
    - contents: |
        #!/bin/sh -e
        # Deny execution of any automatic restarts via invoke-rc.d.

        exit 101

unbound:
  pkg.installed:
    - version: 1.4.22-3+deb8u1 # 1.5+ may need chroot setting

/etc/unbound:
  file.directory:
    - mode: 755

/etc/unbound/unbound.conf:
  file.managed:
    - contents: |
        server:
         interface: 0.0.0.0

unbound-control-setup:
  cmd.run:
    - name: unbound-control-setup -d /etc/unbound
    - creates: /etc/unbound/unbound_control.key

/etc/systemd/system/unbound.service:
  file.managed:
    - contents: |
        [Unit]
        Description = Recursive DNS server

        [Service]
        ExecStartPre=/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -v
        ExecStartPre=/usr/sbin/unbound-checkconf
        ExecStart=/usr/sbin/unbound -d
        ExecReload=/bin/kill -HUP $MAINPID
        Restart=always

unbound-service:
  service.running:
    - name: unbound
    - enable: true
    - reload: true
```

Highstating from it gives us running unbound, that's great:

```
root@36com0:/# systemctl status unbound
● unbound.service - (null)
   Loaded: loaded (/etc/init.d/unbound; static)
  Drop-In: /run/systemd/generator/unbound.service.d
           └─50-insserv.conf-$named.conf, 50-unbound-$named.conf
   Active: active (running) since Mon 2016-07-25 15:17:35 UTC; 39s ago
  Process: 501 ExecStart=/etc/init.d/unbound start (code=exited, status=0/SUCCESS)
   CGroup: /docker/c223dc315de57f3c12c70fee3db0ec3350f45b4c1c3b0f14759f2e9245b3351f/system.slice/unbound.service
           └─511 /usr/sbin/unbound

Jul 25 15:17:35 36com0 unbound-anchor[508]: /var/lib/unbound/root.key has content
Jul 25 15:17:35 36com0 unbound-anchor[508]: success: the anchor is ok
Jul 25 15:17:35 36com0 unbound[501]: Starting recursive DNS server: unbound.
Jul 25 15:17:35 36com0 systemd[1]: Started (null).
Jul 25 15:17:35 36com0 unbound[511]: [511:0] notice: init module 0: validator
Jul 25 15:17:35 36com0 unbound[511]: [511:0] notice: init module 1: iterator
Jul 25 15:17:35 36com0 unbound[511]: [511:0] info: start of service (unbound 1.4.22).
```

But don't be fooled and look at the second line:

```
   Loaded: loaded (/etc/init.d/unbound; static)
```

That's not right, there should be our unit file. Let's try to reload service to see if it helps:

```
root@36com0:/# systemctl reload unbound
root@36com0:/# systemctl status unbound
● unbound.service - (null)
   Loaded: loaded (/etc/init.d/unbound; static)
  Drop-In: /run/systemd/generator/unbound.service.d
           └─50-insserv.conf-$named.conf, 50-unbound-$named.conf
   Active: active (running) since Mon 2016-07-25 15:17:35 UTC; 3min 28s ago
  Process: 547 ExecReload=/etc/init.d/unbound reload (code=exited, status=0/SUCCESS)
  Process: 501 ExecStart=/etc/init.d/unbound start (code=exited, status=0/SUCCESS)
   CGroup: /docker/c223dc315de57f3c12c70fee3db0ec3350f45b4c1c3b0f14759f2e9245b3351f/system.slice/unbound.service
           └─511 /usr/sbin/unbound

Jul 25 15:21:00 36com0 systemd[1]: Reloading (null).
Jul 25 15:21:00 36com0 unbound[511]: [511:0] info: service stopped (unbound 1.4.22).
Jul 25 15:21:00 36com0 unbound[511]: [511:0] info: server stats for thread 0: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch
Jul 25 15:21:00 36com0 unbound[511]: [511:0] info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0
Jul 25 15:21:00 36com0 unbound[511]: [511:0] notice: Restart of unbound 1.4.22.
Jul 25 15:21:00 36com0 unbound[511]: [511:0] notice: init module 0: validator
Jul 25 15:21:00 36com0 unbound[511]: [511:0] notice: init module 1: iterator
Jul 25 15:21:00 36com0 systemd[1]: Reloaded (null).
Jul 25 15:21:00 36com0 unbound[547]: Reloading recursive DNS server: unbound.
Jul 25 15:21:00 36com0 unbound[511]: [511:0] info: start of service (unbound 1.4.22).
```

Nope, same thing. Now let's tell systemd to do `daemon-reload`:

```
root@36com0:/# systemctl daemon-reload
```

And then let's look at the state of our service:

```
root@36com0:/# systemctl status unbound
● unbound.service - Recursive DNS server
   Loaded: loaded (/etc/systemd/system/unbound.service; static)
  Drop-In: /run/systemd/generator/unbound.service.d
           └─50-insserv.conf-$named.conf, 50-unbound-$named.conf
   Active: active (running) since Mon 2016-07-25 15:17:35 UTC; 4min 17s ago
   CGroup: /docker/c223dc315de57f3c12c70fee3db0ec3350f45b4c1c3b0f14759f2e9245b3351f/system.slice/unbound.service
           └─511 /usr/sbin/unbound

Jul 25 15:21:00 36com0 systemd[1]: Reloading (null).
Jul 25 15:21:00 36com0 unbound[511]: [511:0] info: service stopped (unbound 1.4.22).
Jul 25 15:21:00 36com0 unbound[511]: [511:0] info: server stats for thread 0: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch
Jul 25 15:21:00 36com0 unbound[511]: [511:0] info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0
Jul 25 15:21:00 36com0 unbound[511]: [511:0] notice: Restart of unbound 1.4.22.
Jul 25 15:21:00 36com0 unbound[511]: [511:0] notice: init module 0: validator
Jul 25 15:21:00 36com0 unbound[511]: [511:0] notice: init module 1: iterator
Jul 25 15:21:00 36com0 systemd[1]: Reloaded (null).
Jul 25 15:21:00 36com0 unbound[547]: Reloading recursive DNS server: unbound.
Jul 25 15:21:00 36com0 unbound[511]: [511:0] info: start of service (unbound 1.4.22).
```

Great, systemd picked up our unit file. Let's reload the service:

```
root@36com0:/# systemctl reload unbound
Job for unbound.service failed. See 'systemctl status unbound.service' and 'journalctl -xn' for details.
```

Not if we look at the reason:

```
root@36com0:/# systemctl status unbound
● unbound.service - Recursive DNS server
   Loaded: loaded (/etc/systemd/system/unbound.service; static)
  Drop-In: /run/systemd/generator/unbound.service.d
           └─50-insserv.conf-$named.conf, 50-unbound-$named.conf
   Active: active (running) (Result: exit-code) since Mon 2016-07-25 15:17:35 UTC; 5min ago
  Process: 570 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=1/FAILURE)
   CGroup: /docker/c223dc315de57f3c12c70fee3db0ec3350f45b4c1c3b0f14759f2e9245b3351f/system.slice/unbound.service
           └─511 /usr/sbin/unbound

Jul 25 15:22:29 36com0 kill[570]: <pid> [...]            send signal to every <pid> listed
Jul 25 15:22:29 36com0 kill[570]: -<signal>, -s, --signal <signal>
Jul 25 15:22:29 36com0 kill[570]: specify the <signal> to be sent
Jul 25 15:22:29 36com0 kill[570]: -l, --list=[<signal>]  list all signal names, or convert one to a name
Jul 25 15:22:29 36com0 kill[570]: -L, --table            list all signal names in a nice table
Jul 25 15:22:29 36com0 kill[570]: -h, --help     display this help and exit
Jul 25 15:22:29 36com0 kill[570]: -V, --version  output version information and exit
Jul 25 15:22:29 36com0 kill[570]: For more details see kill(1).
Jul 25 15:22:29 36com0 systemd[1]: unbound.service: control process exited, code=exited status=1
Jul 25 15:22:29 36com0 systemd[1]: Reload failed for Recursive DNS server.
```

We can see (if we look very closely) that it's because systemd doesn't work nicely when we run service via legacy init script, reload daemon config and then try to reload service for which systemd doesn't know `$MAINPID`. Here systemd is to blame, but salt could've helped us to avoid this situation.

I think salt should do `systemd daemon-reload` before starting up `unbound` state here. Right now it's confused because it sees that systemd is happy (not complaining about running `daemon-reload`), unit file (our override) is readable and state is known to systemd (legacy script!).

If we try to remove legacy script before starting the state:

```
root@36com0:/# systemctl status unbound
● unbound.service - (null)
   Loaded: loaded (/etc/init.d/unbound; static)
  Drop-In: /run/systemd/generator/unbound.service.d
           └─50-insserv.conf-$named.conf, 50-unbound-$named.conf
   Active: failed (Result: exit-code) since Mon 2016-07-25 15:31:38 UTC; 6s ago
  Process: 507 ExecStart=/etc/init.d/unbound start (code=exited, status=203/EXEC)

Jul 25 15:31:38 36com0 systemd[507]: Failed at step EXEC spawning /etc/init.d/unbound: No such file or directory
Jul 25 15:31:38 36com0 systemd[1]: unbound.service: control process exited, code=exited status=203
Jul 25 15:31:38 36com0 systemd[1]: Failed to start (null).
Jul 25 15:31:38 36com0 systemd[1]: Unit unbound.service entered failed state.

Warning: Unit file changed on disk, 'systemctl daemon-reload' recommended.
```

This looks like another bug. Systemd says to do `daemon-reload`, but salt ignored the advice:

```
root@36com0:/# systemctl daemon-reload
root@36com0:/# systemctl start unbound
root@36com0:/# systemctl status unbound
● unbound.service - Recursive DNS server
   Loaded: loaded (/etc/systemd/system/unbound.service; static)
   Active: active (running) since Mon 2016-07-25 15:32:35 UTC; 5s ago
  Process: 553 ExecStartPre=/usr/sbin/unbound-checkconf (code=exited, status=0/SUCCESS)
  Process: 552 ExecStartPre=/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -v (code=exited, status=0/SUCCESS)
 Main PID: 554 (unbound)
   CGroup: /docker/f87e6bf46ab94a7aa4b25f61d3377a4951d2ef8e2eb4b55869fd1fd4e29b5d69/system.slice/unbound.service
           └─554 /usr/sbin/unbound -d

Jul 25 15:32:35 36com0 unbound-anchor[552]: /var/lib/unbound/root.key has content
Jul 25 15:32:35 36com0 unbound-anchor[552]: success: the anchor is ok
Jul 25 15:32:35 36com0 unbound-checkconf[553]: unbound-checkconf: no errors in /etc/unbound/unbound.conf
Jul 25 15:32:35 36com0 systemd[1]: Started Recursive DNS server.
Jul 25 15:32:35 36com0 unbound[554]: [554:0] notice: init module 0: validator
Jul 25 15:32:35 36com0 unbound[554]: [554:0] notice: init module 1: iterator
Jul 25 15:32:35 36com0 unbound[554]: [554:0] info: start of service (unbound 1.4.22).
```

### Versions Report

```
root@36com0:/# salt-call --versions
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed

System Versions:
           dist: debian 8.5
        machine: x86_64
        release: 4.4.14-cloudflare
         system: Linux
        version: debian 8.5
```

**Comment by eliasp** [comment] 2016-07-26 06:51
This is intentional - `daemon-reload` is an operation which is to be called explicitly, otherwise `systemd` could simply monitor `/etc/systemd/{system,user}` for changes and do the reload on its own.

The reason, why this doesn't happen automatically is to prevent a situation where systemd reloads unfinished/half-edited files and renders the service's configuration useless.

Use a `module.run` state to execute `service.systemctl_reload` on changes of your unit like this:

```SaltStack
service.systemctl_reload
  module.run:
    - onchanges:
      - file: /etc/systemd/system/unbound.service
```

**Comment by bobrik** [comment] 2016-07-26 08:37
> This is intentional - daemon-reload is an operation which is to be called explicitly

It is also an operation that salt runs for me.

> The reason, why this doesn't happen automatically

But it does.

* https://github.com/saltstack/salt/blob/0e0c428/salt/modules/systemd.py#L74-L84

**Comment by eliasp** [comment] 2016-07-26 11:57
…I stand corrected. So there's actually a bug.

**Comment by Ch3LL** [comment] 2016-07-27 16:47
looks like we need to clear this up to ensure daemon-reload is called correctly.

ping @terminalmage

**Comment by terminalmage** [comment] 2016-07-27 21:35
@bobrik this may be caused by our saving ``systemctl status`` output in ``__context__`` as a performance measure. Thus we don't catch the need for a daemon-reload. This is something that we do in fact look for, but I think that caching the ``systemctl status`` output might be keeping us from running it after the unit file is placed.

Can you help test this hypothesis by editing systemd.py (on a debian box it's probably at ``/usr/lib/python2.7/dist-packages/salt/modules/systemd.py``, you can also run ``dpkg -L salt-common | fgrep systemd.py`` to get the location). At the beginning of the ``_systemd_status()`` function, I'd like to bypass ``__context__`` by adding the following block of code at the beginning of the function:

```python
    return __salt__['cmd.run'](
        _systemctl_cmd('status', name),
        python_shell=False,
        ignore_retcode=True
    )
```

If this gets rid of the problem, then the solution will be to simply yank all of the ``__context__`` code from that function and go through with running ``systemctl status`` every time that function is invoked.

**Comment by terminalmage** [comment] 2016-07-27 21:37
You will of course need to restart the salt-minion process after making the above-mentioned edit.

**Comment by bobrik** [comment] 2016-07-28 11:24
@terminalmage that's not the case, the following did the trick when I remove legacy script:

```diff
diff --git a/salt/modules/systemd.py b/salt/modules/systemd.py
index 28e2ec6..e50b4dc 100644
--- a/salt/modules/systemd.py
+++ b/salt/modules/systemd.py
@@ -76,7 +76,7 @@ def _check_for_unit_changes(name):
     Check for modified/updated unit files, and run a daemon-reload if any are
     found.
     '''
-    contextkey = 'systemd._check_for_unit_changes'
+    contextkey = 'systemd._check_for_unit_changes.{}'.format(name)
     if contextkey not in __context__:
         if _untracked_custom_unit_found(name) or _unit_file_changed(name):
             systemctl_reload()
```

This should work if you don't change systemd unit several times during the same salt run. It's hard for me to come up with a reason to do so. It probably doesn't work right now anyway.

I can make a PR if this makes sense. Let me know the which branch to use.

**Comment by terminalmage** [comment] 2016-07-28 14:01
@bobrik Ahh yes, this definitely makes sense. Yes, please open a PR if you don't mind. It should be against the 2015.8 branch. We use a merge-forward workflow, so bugfixes go to the oldest non-EOL release branch where the bug exists, and are merged forward until they reach the develop branch.

There is one minor change that I'll need you to make to the above patch, though, and that is to use ``{0}`` instead of ``{}``. We need to support Python 2.6, and format placeholders without numbers are only valid Python in 2.7 and later.

Thanks!

**Comment by cachedout** [comment] 2016-07-28 17:56
Closed via #35024

**Closed by cachedout** 2016-07-28 17:56 UTC
Labels: Bug, Core, Execution Module, High Severity, P4

**Comment by bobrik** [comment] 2016-07-29 07:45
@terminalmage is there an ETA for 2016.3.2? 24 days ago: https://github.com/saltstack/salt/issues/33697#issuecomment-230550738

**Comment by terminalmage** [comment] 2016-07-29 16:24
@bobrik We are close to tagging and hope to have the release out early next week. Because this fix had not been merged forward into the 2016.3 release branch, and we may not merge-forward before we tag the 2016.3.2 release, I cherry-picked your fix into the 2016.3 branch and opened https://github.com/saltstack/salt/pull/35060 to get your fix into that release branch so that we make sure to include it.

**Comment by terminalmage** [comment] 2016-07-29 17:02
@bobrik Sorry, there was some miscommunication internally, 2016.3.2 was already tagged prior to your opening that PR, so I've closed #35060 and your fix will make it into 2016.3.3.

Apologies for the confusion.

**Comment by bobrik** [comment] 2016-07-31 09:39
What's the usual time for tagged release to appear in debian repos? 2015.5.11 was tagged 9 days ago, but it's not in repos yet.

**Comment by dmurphy18** [comment] 2016-08-01 16:27
@bobrik 2015.5.11 has been build but not tested yet, since 2016.3.2 is currently undergoing test. It is hoped that it's release is very soon, barring any blocker found in QA. It was felt that 2016.3.2 was more important to release first.
