### ISSUE TITLE
v2015.5.5 highstate outputter stacktracing for jobs.lookup_jid

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#27831] opened 2015-10-09 18:18 UTC
ZD-446

```
[DEBUG   ] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/local/lib/python2.7/dist-packages/salt/output/highstate.py", line 86, in output
    return _format_host(host, hostdata)[0]
  File "/usr/local/lib/python2.7/dist-packages/salt/output/highstate.py", line 130, in _format_host
    rcounts.setdefault(ret['result'], 0)
KeyError: 'result'

[DEBUG   ] LazyLoaded nested.output
data:
    ----------
    vagrant-base-trusty-amd64:
        ----------
        file_|-something_else_|-/tmp/something_else.txt_|-managed:
            ----------
            __run_num__:
                1
            changes:
                ----------
            comment:
                File /tmp/something_else.txt exists with proper permissions. No changes made.
            duration:
                0.448
            name:
                /tmp/something_else.txt
            result:
                True
            start_time:
                17:15:56.239146
        file_|-something_|-/tmp/something.txt_|-managed:
            ----------
            __run_num__:
                0
            changes:
                ----------
            comment:
                File /tmp/something.txt exists with proper permissions. No changes made.
            duration:
                3.241
            name:
                /tmp/something.txt
            result:
                True
            start_time:
                17:15:56.235841
```

Somewhere between when the runner returns the data, and when it's passed to the highstate outputter, it's being wrapped in a `data` key, which messes up the highstate outputter. Still looking.

**Comment by jfindlay** [comment] 2015-10-09 21:27
@basepi, this is a duplicate of #27723.

**Comment by basepi** [comment] 2015-10-09 22:23
Good call. Should have searched more.

Either way, they're both fixed.

**Closed** 2015-10-09 22:26 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, Outputters, P2, Regression, Runners, ZD
