### ISSUE TITLE
Syndic and the Mine

### ISSUE THREAD

**Issue by AusIV** [saltstack/salt#21732] opened 2015-03-17 15:26 UTC
I've recently started trying to get a hierarchical salt system set up with Syndic, and it all seems to work as expected, except for the mine. It seems that each syndic master has an isolated mine, which serves its minions independently. This is a problem for me for a couple of reasons:

On one hand, I have a central LDAP server that lots of services need to authenticate against. It puts its IP address in the mine, and other services get the IP out of the mine when configuring what LDAP server to talk to. With just one salt master this works very smoothly. Right now, I have the LDAP server configured by the master of masters, and its IP is in the mine for the master of masters. But when a service configured by a sub-master tries to get the LDAP server's IP address out of the mine, it gets nothing back. **The mine for the master of masters is not accessible to minions configured by sub-masters.**

On the other hand, I have the reverse problem. I have a DNS server, also configured by the master of masters, which takes IP addresses out of the mine, along with minion IDs, and sets up DNS so that services can be accessed over the nework using minion IDs as host names. In this case, the DNS service configured by the master of masters doesn't get mine entries for services configured by sub masters. **The mine for sub-masters is not accessible to minions configured by the master of masters.**

Ultimately, it looks like syndic isn't propagating the mine in either direction. My expectation would generally be for mine entries to propagate both up and down, essentially creating one large mine for the entire topology.

**Comment by basepi** [comment] 2015-03-17 16:29
This is a known issue. The mine has not been updated such that it will support the syndic architecture, but it's something we definitely want to add.

**Comment by thatch45** [comment] 2015-03-17 16:32
Yes, the syndic is designed to keep the sub masters isolated. Opening it up in this way should be a reasonable thing, but we will want to config gate it because for many syndic users turning it on by default will have security implications

**Comment by AusIV** [comment] 2015-03-17 16:52
I meant to mention that I saw [this thread](https://groups.google.com/forum/#!topic/salt-users/C5vz53aIjUQ) while troubleshooting, but it didn't appear that any issues had been logged as a result.

**Comment by thatch45** [comment] 2015-03-17 16:55
We are looking at some major syndic enhancements for the beryllium release, so this will be in there :)

**Comment by SEJeff** [comment] 2015-07-24 17:35
This is definitely an issue we are running into in our production usage of salt.

What would also be nice, perhaps as a separate issue, is a way to specify a master to retrieve mine data from. We setup isolated masters on our desktops for testing big state changes sometimes, but the mine data is (by design) empty. It would be great if you could say run a highstate, but look at this other master for the mine data.

Food for thought.

**Comment by basepi** [comment] 2015-10-27 21:36
This is going to be solved by https://github.com/saltstack/salt/issues/27446, so I'm going to close this in favor of that feature.

**Closed by basepi** 2015-10-27 21:36 UTC
Labels: Boron, Core, Feature, P2
