### ISSUE TITLE
[BUG] Salt 3004 is not compatible with slackclient 2.x or higher

### ISSUE THREAD

**Issue by sdklein** [saltstack/salt#61308] opened 2021-12-01 17:58 UTC
**Description**
Salt 3004 is not compatible with slackclient 2.x or higher but it was installed by default. Must use slackclient==1.3.1. 

Per https://github.com/slackapi/python-slack-sdk/wiki/Migrating-to-2.x, the slack client usage has changed considerably. For instance, the import here no longer work and has to be changed. https://github.com/saltstack/salt/blob/master/salt/engines/slack.py#L169

The simple fix is to make sure the slackclient is pinned appropriately.

However as of today the entire legacy RTM methodology will no longer work for any new slack bots. More information about that can be found here: https://api.slack.com/changelog/2021-10-rtm-start-to-stop. This is going to require the entire slack engine and supporting libraries to be upgraded. 

**Setup**
Install salt master 3004, configure slack engine.
Slack engine will not start. Error printed is:
```Could not LazyLoad slack.start: 'slack' __virtual__ returned False: The 'slackclient' Python module could not be loaded```

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Install salt 3004 and attempt to configure the slack engine. It will not start. 

**Expected behavior**
slack engine should start

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.12.3
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.20
        Jinja2: 2.11.1
       libgit2: 0.28.2
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.28.2
        Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-957.12.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Comment by OrangeDog** [comment] 2021-12-03 09:12
Possible duplicate of #57842.

**Comment by garethgreenaway** [comment] 2022-09-06 17:34
Closing this one because it's a duplicate of #57842

**Closed** 2022-09-06 17:34 UTC
Labels: Bug, Duplicate, needs-triage, slack
