### ISSUE TITLE
state zpool.present gives a (non-fatal) error on Ubuntu

### ISSUE THREAD

**Issue by morgana2313** [saltstack/salt#46755] opened 2018-03-28 14:29 UTC
### state zpool.present gives a (non-fatal) error in the logfile when used on Ubuntu:

This might be a duplicate of #38671

```
[INFO    ] Executing state zpool.present for [lxd]
[INFO    ] Executing command '/sbin/zpool list lxd' in directory '/root'
[INFO    ] Executing command '/sbin/zpool get -H -o property,value,source all lxd' in directory '/root'
[ERROR   ] Command '/sbin/zpool get -H -o property,value,source all lxd' failed with return code: 2
[ERROR   ] stderr: invalid option 'o'
usage:
	get [-pH] <"all" | property[,...]> <pool> ...

the following properties are supported:

	PROPERTY         EDIT   VALUES

	allocated          NO   <size>
	capacity           NO   <size>
	dedupratio         NO   <1.00x or higher if deduped>
	expandsize         NO   <size>
	fragmentation      NO   <percent>
	free               NO   <size>
	freeing            NO   <size>
	guid               NO   <guid>
	health             NO   <state>
	leaked             NO   <size>
	size               NO   <size>
	altroot           YES   <path>
	ashift            YES   <ashift, 9-13, or 0=default>
	autoexpand        YES   on | off
	autoreplace       YES   on | off
	bootfs            YES   <filesystem>
	cachefile         YES   <file> | none
	comment           YES   <comment-string>
	dedupditto        YES   <threshold (min 100)>
	delegation        YES   on | off
	failmode          YES   wait | continue | panic
	listsnapshots     YES   on | off
	readonly          YES   on | off
	version           YES   <version>
	feature@...       YES   disabled | enabled | active

The feature@ properties must be appended with a feature name.
See zpool-features(5).
```

### Setup
Saltstack 2017.7.4

### Steps to Reproduce Issue: salt-call -l info state.apply [state below]
zfs_lxd:
  zpool.present:
    - name: lxd
    - properties:
        autoexpand: on

### Versions Report

```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment] 2018-03-29 14:08
This is definitely a duplicate of #38671 .  We would greatly appreciate any assistance in improving the zpool modules.

Thanks,
Daniel

**Closed by gtmanfred** 2018-03-29 14:08 UTC
