### ISSUE TITLE
[FEATURE REQUEST] Packaging - Require a newer Python version on RHEL 8

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#61346] opened 2021-12-10 02:41 UTC
**Is your feature request related to a problem? Please describe.**
Python 3.6 EOL is 2 weeks away or so. Currently, the RHEL8 RPM requires this version and installs it on systems which may already have Python installed.

**Describe the solution you'd like**
The EL repos have Python 3.8 and Python 3.9 available. Pick a winner and have the RPM require that version instead.

**Describe alternatives you've considered**
N/A

**Additional context**
Red Hat doesn't install Python on RHEL 8 by default, and doesn't pick a default "system" version of Python. That should allow internal considerations and testing dictate the default Python version required by the Salt RPM.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by dmurphy18** [comment] 2022-01-06 18:27
The problem is somewhat due to the following line in the spec file
```
228 CFLAGS="${CFLAGS:-${RPM_OPT_FLAGS}}" LDFLAGS="${LDFLAGS:-${RPM_LD_FLAGS}}" %{__python3} %{py_setup} %{?py_setup_args} build --executable="%{__python3}" %{?*}
```
where the version of Python used is provided by the OS's macro __python3, which of course would be python3.6 on the build machines used.

Correction would be to replace use of macro and utilize 'python3', might want to check paths used too.

**Comment by dmurphy18** [comment] 2022-01-11 17:16
Well the suspect line at 228 does not appear to be the issue as the out from rpmspec is as follows:
```
225 CFLAGS="${CFLAGS:-${RPM_OPT_FLAGS}}" LDFLAGS="${LDFLAGS:-${RPM_LD_FLAGS}}" /usr/libexec/platform-python setup.py  build --executable="/usr/libexec/platform-python"
```

However from the output for files:
```
311 %files
312 %defattr(-,root,root,-)
313 /usr/lib/python3.6/site-packages/salt/*
314 /usr/lib/python3.6/site-packages/salt-*-py?.?.egg-info
315 /etc/logrotate.d/salt
```
And on the RHEL 8 system used with Python 3.6 installed (which was default at the time of its creation), currently updated
```
david@Unknown:~/rpmbuild$ cat /etc/redhat-release 
CentOS Linux release 8.5.2111
```
only have /usr/lib/python3.6

After installing Python 3.8 and Python 3.9, we now have the following directories in /usr/lib
```
root@Unknown:/home/david/rpmbuild# ls -D /usr/lib/python3*
/usr/lib/python3.6:
site-packages

/usr/lib/python3.8:
site-packages

/usr/lib/python3.9:
site-packages
root@Unknown:/home/david/rpmbuild# 
```
This implies would need to create a symbolic link to whichever python version is preferred, something very user specific, for example:
```
/usr/lib/pythyon3 -> /usr/lib/python3.X   # where X is whatever the user perfers
```

Alternatives doesn't really help
```
root@Unknown:/home/david/rpmbuild# alternatives --display python3
python3 - status is auto.
 link currently points to /usr/bin/python3.6
/usr/bin/python3.6 - priority 1000000
 slave easy_install-3: /usr/bin/easy_install-3.6
 slave pip-3: /usr/bin/pip-3.6
 slave pip3: /usr/bin/pip3.6
 slave pydoc-3: /usr/bin/pydoc3.6
 slave pydoc3: /usr/bin/pydoc3.6
 slave pyvenv-3: /usr/bin/pyvenv-3.6
 slave python3-man: /usr/share/man/man1/python3.6.1.gz
/usr/bin/python3.8 - priority 3800
 slave easy_install-3: /usr/bin/easy_install-3.8
 slave pip-3: /usr/bin/pip-3.8
 slave pip3: /usr/bin/pip3.8
 slave pydoc-3: /usr/bin/pydoc3.8
 slave pydoc3: /usr/bin/pydoc3.8
 slave pyvenv-3: (null)
 slave python3-man: /usr/share/man/man1/python3.8.1.gz
/usr/bin/python3.9 - priority 3900
 slave easy_install-3: /usr/bin/easy_install-3.9
 slave pip-3: /usr/bin/pip-3.9
 slave pip3: /usr/bin/pip3.9
 slave pydoc-3: /usr/bin/pydoc3.9
 slave pydoc3: /usr/bin/pydoc3.9
 slave pyvenv-3: (null)
 slave python3-man: /usr/share/man/man1/python3.9.1.gz
Current `best' version is /usr/bin/python3.6.
```

**Comment by dmurphy18** [comment] 2022-01-11 17:19
This is not really a Salt issue but a packaging issue for RedHat and determining which Python 3 version is preferred, and which has been selected as current 'best'.  It also triples the Salt testing since need to test with Py 3.6, Py 3.8 and Py 3.9, and presumably Py 3.10 when it appears for RedHat 8.

**Comment by dmurphy18** [comment] 2022-01-11 22:14
Note with current Centos 9 stream, packages are Python3 labelled but only the following libraries:
```
[root@Unknown david]# l /usr/lib/python3.9/
total 8.0K
drwxr-xr-x.  3 root root   27 Jan 11 14:50 .
dr-xr-xr-x. 42 root root 4.0K Jan 11 14:52 ..
drwxr-xr-x. 58 root root 4.0K Jan 11 14:52 site-packages
[root@Unknown david]# cat /etc/redhat-release 
CentOS Stream release 9
```

**Comment by dmurphy18** [comment] 2022-01-11 23:50
@nicholasmhughes A clean install of Centos 8.5 from iso (without any update) installed Python 3.6 by default.
```
david@Unknown:~$ command -v python3
/usr/bin/python3
david@Unknown:~$ python3 --version
Python 3.6.8
david@Unknown:~$ cat /etc/redhat-release 
CentOS Linux release 8.5.2111
david@Unknown:~$ 
```
Hence whether Python 3 is installed by default depends on the packages installed as part of the installation process, I picked Server with GUI and some tools, obviously part of those tools selection installed Python 3.6,, and I just installed standard stuff, hence expect other users to do similar.

I believe your installation is a special case compared to the average user who will probably end up with Python 3.6 installed. I am not sure if Tiamat based Salt will resolve this for you either, given it is built with it's own version of Python 3 internally (currently Py 3.7 but discussions are occurring to update that to current favorite Py 3.9).  Perhaps for your use case an install from PyPI of Salt into your desired version of Python 3.x might be more appropriate.

**Comment by nicholasmhughes** [comment] 2022-01-11 23:58
/shrug

If you don't want to do anything about the python dependency, fine.

However, I need #61345 fixed. Fixing a she-bang pointing to a static, EOL Python version is not an unreasonable ask.

**Comment by dmurphy18** [comment] 2022-01-12 01:03
@nicholasmhughes The problem is how do we know which version of Python 3 the user will have installed and wants to function with.  I count 3 versions Py 3.6, Py 3.8 and Py 3.9 and Py 3.10 is probably soon on its way.

The she-bang problem is tied to the output line, as originally stated above
```
225 CFLAGS="${CFLAGS:-${RPM_OPT_FLAGS}}" LDFLAGS="${LDFLAGS:-${RPM_LD_FLAGS}}" /usr/libexec/platform-python setup.py  build --executable="/usr/libexec/platform-python"
```
that is generated by the /usr/libexec/platform-python but I will dig in deeper to ensure I am correct.
This still leaves the issue of /usr/lib/python3.6/site-packages to be cleared up, but perhaps there is something I can try there too, just had a thought to try as typing, will let you know.

**Comment by dmurphy18** [comment] 2022-01-12 01:16
This may be out of Salt's control given rpm building output has 
```
Bytecompiling .py files below /home/david/rpmbuild/BUILDROOT/salt-3004-1.el8.x86_64/usr/lib/python3.6 using /usr/libexec/platform-python
+ /usr/lib/rpm/brp-python-hardlink
+ PYTHON3=/usr/libexec/platform-python
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
mangling shebang in /usr/lib/python3.6/site-packages/salt/templates/git/ssh-id-wrapper from /usr/bin/env sh to #!/usr/bin/sh
```

but perhaps there is a way to update the scripts before they are packaged into the rpm and srpm.
It requires overriding regular rpm building tools from RedHat, as that is what is putting it there.

**Comment by dmurphy18** [comment] 2022-01-12 01:23
Updated #61345 correctly now, but understand, but she-bang appears to be coming from RedHat rpm tools, but discussion in #61345

**Comment by dmurphy18** [comment] 2022-02-02 21:32
Closing this as a won't fix, since the solution is to utilize Tiamat based packages with pip install capabilities which should be released in the next major version of Salt, Phosphorous.

The problem is really the rpm tools provided by RedHat, for example: use of the rpm supplied macro python3_sitelib in the spec file, and currently most RHEL / Centos 8 installations will install Python 3.6.  If you have other suggestions as to how to resolve this issue, please feel free to re-open.

**Closed by dmurphy18** 2022-02-02 21:32 UTC
Labels: Feature, won't-fix, Packaging

**Comment by DaAwesomeP** [comment] 2022-07-08 20:25
Having an issue getting a working pygit2 capable of SSH for gitfs on RHEL8. Is there a way to switch Salt to use a newer Python ot Appstream Python (where I can install a pygit2 wheel)?

**Comment by DaAwesomeP** [comment] 2022-07-08 20:28
The only way I can think to do this is to use a systemd override to start `/usr/bin/salt-master` using the newer Python (and therefore overriding the shebang).

**Comment by whytewolf** [comment] 2022-07-08 20:28
> Having an issue getting a working pygit2 capable of SSH for gitfs on RHEL8. Is there a way to switch Salt to use a newer Python ot Appstream Python (where I can install a pygit2 wheel)?

You can update the pip on the system python. that will allow you to install the pygit2 wheel.

**Comment by DaAwesomeP** [comment] 2022-07-08 20:30
> You can update the pip on the system python. that will allow you to install the pygit2 wheel.

No, or at least not to the latest pip now that 3.6 is EOL:
```
pip requires Python '>=3.7' but the running Python is 3.6.8
```

If I try to build the pygit2 wheel with the current pip, it depends on `libgit2-devel`, which is too old for `pygit2`.

**Comment by whytewolf** [comment] 2022-07-08 20:51
> 

You don't need latest pip. just new enough to install wheels from pypi so that you are not building the wheel. 

I used to do this all the time in centos 7 which has a slightly older version of python 3.6.

**Comment by DaAwesomeP** [comment] 2022-07-08 21:09
Ah, perfect! For reference for anyone else who runs into this issue:
```bash
python3 -m pip install --upgrade pip==21.3.1 wheel==0.37.1
python3 -m pip install pygit2==1.6.1
```
