### ISSUE TITLE
salt-ssh '*' state.sls fails to run...

### ISSUE THREAD

**Issue by jcftang** [saltstack/salt#19949] opened 2015-01-22 10:13 UTC
Given,

<pre>
# salt-ssh --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
</pre>

When I run state.sls

<pre>
# salt-ssh 'foo' state.sls avahi -lerror
Exception AttributeError: "'Terminal' object has no attribute 'pid'" in <bound method Terminal.__del__ of <salt.utils.vt.Terminal object at 0x7f0815eae510>> ignored
foo:
    An Exception occurred while executing state.sls: I/O operation on closed file
</pre>

running regular modules seems to work fine.

The avahi state that i have just installs a few packages and enables the services.

update: state.highstate also produces the same error for me. It looks like this is a regression and it may relate to https://github.com/saltstack/salt/pull/19202

**Comment by rallytime** [comment] 2015-01-22 19:15
Interesting. I've been using salt-ssh with state.sls calls on 2014.7.0 quite a bit recently, and I haven't seen this one. How did you install salt-ssh and what distribution are you running on?

**Comment by rallytime** [comment] 2015-01-22 19:15
@basepi ping

**Comment by jcftang** [comment] 2015-01-22 19:56
@rallytime I'm running this on ubuntu precise (latest updates and all) on the x86_64 platform. I've installed salt-ssh and friends from the saltstack ppa's

It occurs on the my two salt masters which are distinct and on separate networks with different configs.

**Comment by jcftang** [comment] 2015-01-23 10:49
After a bit of tracking down the problem, it looks like when I execute

salt-ssh 'foo' state.sls update 

This scp command is generated

<pre>
]
[DEBUG   ] Rendered data from file: /var/cache/salt/master/files/base/update.sls:
# I can be executed as such
# salt '*' state.sls update
#include:
# - common

common_upd:
  pkg:
    - uptodate
    - refresh: True
#    - require_in:
#      - pkg: common

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('common_upd', OrderedDict([('pkg', ['uptodate', OrderedDict([('refresh', True)])])]))])
[DEBUG   ] Executing command: scp host.foo.com  -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/root/.ssh/salt-ssh.rsa -o User=ubuntu  /tmp/tmpGzDxmm host.foo.com:/tmp/.ubuntu_6a7d07__salt/salt_state.tgz
Exception AttributeError: "'Terminal' object has no attribute 'pid'" in <bound method Terminal.__del__ of <salt.utils.vt.Terminal object at 0x7f6c944be450>> ignored
aws-wiki:
    An Exception occurred while executing state.sls: I/O operation on closed file
</pre>

An extra hostname is added right after the scp command before the options are appended. This causes the scp command to just exit right away and not upload the states at all

**Comment by jcftang** [comment] 2015-01-23 16:24
Upon further digging, it looks like its failing at the upload step with scp.

**Comment by jcftang** [comment] 2015-01-24 09:17
This seems fixed in the recent 2014.7.1 branch

<pre>
x01:
----------
          ID: uptime
    Function: cmd.run
      Result: True
     Comment: Command "uptime" run
     Started: 09:15:00.607431
    Duration: 5.173 ms
     Changes:
              ----------
              pid:
                  13980
              retcode:
                  0
              stderr:

              stdout:
                   09:15:00 up 20:30, 12 users,  load average: 0.34, 0.26, 0.22

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
(venv)jtang@x01:~/sandbox/sf$ salt-ssh --versions-report
           Salt: 2014.7.1-133-gfd8e474
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: Not Installed
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: Not Installed
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: Not Installed
           RAET: Not Installed
            ZMQ: Not Installed
           Mako: Not Installed
</pre>

Since the debian packages aren't out which is what I prefer to use, this should probably be left open for now.

**Comment by rallytime** [comment] 2015-01-24 16:31
Ok no problem! We can keep this open as long as you need. Let us know the result when you get a chance to test with the packages.

**Comment by jcftang** [comment] 2015-01-29 10:33
I just updated to the latest 2014.7.1 packages from the ppa on ubuntu trusty, I'm still having this issue, it looks like the fix didn't make it to the 2014.7.1 tag.

**Comment by rallytime** [comment] 2015-01-29 16:15
Ok, thanks for the update! We'll have to take another look.

**Comment by basepi** [comment] 2015-01-30 23:20
Based on the versions-report above, this is probably a fix that's going to be in 2014.7.2.

**Comment by rallytime** [comment] 2015-04-03 19:52
@jcftang Apologies for the back-and-forth here. Ubuntu packages are out for 2014.7.2. Have you had a chance to test the new version is regards to this issue?

**Comment by jcftang** [comment] 2015-04-03 20:01
@rallytime I plan on trying it out next week, I've just gone through a number of upgrades so my environment is different now. I will do my best to verify this fix next week.

**Comment by rallytime** [comment] 2015-04-03 20:31
No problem! Thanks!

**Comment by jcftang** [comment] 2015-04-07 08:35
@rallytime Unfortunately I can't verify this fix right now as my targetting minions have all changed to debian and I am affected by this bug now https://github.com/saltstack/salt/issues/16739. The scope of my original bug report is different now as my environment is pretty different to what I started with.

Perhaps someone else can verify this on ubuntu 12.04 for the master and minions being targeted.

Please close this if necessary.

**Comment by rallytime** [comment] 2015-04-28 20:49
I am not able to reproduce this error, so I'll close this. If it pops up again for anyone, please leave a comment and we will be glad to re-open. Thanks!

**Closed by rallytime** 2015-04-28 20:49 UTC
Labels: Bug, Fixed Pending Verification, Medium Severity, Salt-SSH
