### ISSUE TITLE
VirtuozzoLinux not realized as RedHat by pkg

### ISSUE THREAD

**Issue by msdogado** [saltstack/salt#34816] opened 2016-07-20 14:57 UTC
### Description of Issue/Question
Virtuozzo released new RedHat based OS Versions that can be handled with yum and so should be handled with pkg/yumpkg
### Setup

OS: 
```
cat /etc/virtuozzo-release
Virtuozzo release 6.0.11
```
grains.items output without network and hostname related information as requested on: 

https://docs.saltstack.com/en/latest/ref/modules/index.html#module-provider-override

```
grains.items:
    ----------
    SSDs:
    biosreleasedate:
        01/08/2016
    biosversion:
        1.6.2
    cpu_flags:
        - fpu
        - vme
        - de
        - pse
        - tsc
        - msr
        - pae
        - mce
        - cx8
        - apic
        - sep
        - mtrr
        - pge
        - mca
        - cmov
        - pat
        - pse36
        - clflush
        - dts
        - acpi
        - mmx
        - fxsr
        - sse
        - sse2
        - ss
        - ht
        - tm
        - pbe
        - syscall
        - nx
        - pdpe1gb
        - rdtscp
        - lm
        - constant_tsc
        - arch_perfmon
        - pebs
        - bts
        - rep_good
        - xtopology
        - nonstop_tsc
        - aperfmperf
        - cpuid_faulting
        - pni
        - pclmulqdq
        - dtes64
        - monitor
        - ds_cpl
        - vmx
        - smx
        - est
        - tm2
        - ssse3
        - fma
        - cx16
        - xtpr
        - pdcm
        - pcid
        - dca
        - sse4_1
        - sse4_2
        - x2apic
        - movbe
        - popcnt
        - tsc_deadline_timer
        - aes
        - xsave
        - avx
        - f16c
        - rdrand
        - lahf_lm
        - abm
        - ida
        - arat
        - epb
        - pln
        - pts
        - dtherm
        - tpr_shadow
        - vnmi
        - flexpriority
        - ept
        - vpid
        - fsgsbase
        - bmi1
        - avx2
        - smep
        - bmi2
        - erms
        - invpcid
        - xsaveopt
    cpu_model:
        Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
    cpuarch:
        x86_64
    disks:
        - ram0
        - ram1
        - ram2
        - ram3
        - ram4
        - ram5
        - ram6
        - ram7
        - ram8
        - ram9
        - ram10
        - ram11
        - ram12
        - ram13
        - ram14
        - ram15
        - loop0
        - loop1
        - loop2
        - loop3
        - loop4
        - loop5
        - loop6
        - loop7
        - ploop24322
        - ploop58653
        - sda
        - dm-0
        - dm-1
        - dm-2
        - ploop16549
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 8.8.8.8
        ip6_nameservers:
        nameservers:
            - 8.8.8.8
        search:
    environment:
        prd
    gid:
        0
    gpus:
        |_
          ----------
          model:
              G200eR2
          vendor:
              unknown
    groupname:
        root
    kernel:
        Linux
    kernelrelease:
        2.6.32-042stab116.2
    locale_info:
        ----------
        defaultencoding:
            UTF8
        defaultlanguage:
            de_DE
        detectedencoding:
            UTF-8

    lsb_distrib_codename:
        VirtuozzoLinux
    lsb_distrib_id:
        VirtuozzoLinux
    lsb_distrib_release:
        7
    machine_id:
        184fadae91b20db82d978fb400000012
    manufacturer:
        Dell Inc.
    mdadm:
    mem_total:
        31909
    num_cpus:
        12
    num_gpus:
        1
    os:
        VirtuozzoLinux
    os_family:
        VirtuozzoLinux
    osarch:
        x86_64
    oscodename:
        VirtuozzoLinux
    osfullname:
        VirtuozzoLinux
    osrelease:
        7
    osrelease_info:
        - 7
    path:
        /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
    pid:
        365629
    productname:
        PowerEdge R430
    ps:
        ps -fH -p $(grep -l "^envID:[[:space:]]*0\$" /proc/[0-9]*/status | sed -e "s=/proc/\([0-9]*\)/.*=\1=")  | awk '{ $7=""; print }'
    pythonexecutable:
        /usr/bin/python2.6
    pythonpath:
        - /usr/bin
        - /usr/lib64/python26.zip
        - /usr/lib64/python2.6
        - /usr/lib64/python2.6/plat-linux2
        - /usr/lib64/python2.6/lib-tk
        - /usr/lib64/python2.6/lib-old
        - /usr/lib64/python2.6/lib-dynload
        - /usr/lib64/python2.6/site-packages
        - /usr/lib/python2.6/site-packages
        - /usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info
    pythonversion:
        - 2
        - 6
        - 6
        - final
        - 0
    saltpath:
        /usr/lib/python2.6/site-packages/salt
    saltversion:
        2016.3.1
    saltversioninfo:
        - 2016
        - 3
        - 1
        - 0
    selinux:
        ----------
        enabled:
            False
        enforced:
            Disabled
    serialnumber:
        HSR30D2
    server_id:
        997327583
    shell:
        /bin/bash
    uid:
        0
    username:
        root
    virttest:
        PCS
    virtual:
        openvzhn
    zmqversion:
        3.2.5
```

### Versions Report
master version: 
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-042stab108.7
         system: Linux
        version: Ubuntu 14.04 trusty
```
minion version: 
```
salt-minion 2016.3.1 (Boron)
```

**Comment by rallytime** [comment] 2016-07-20 17:01
Thanks @msdogado for bringing this to our attention and for providing the grains details - that is very helpful! It should be simple to add this support.

**Comment by msdogado** [comment] 2016-07-20 18:02
Thanks for the quick reply @rallytime 

Hope this helps to. It affects enableing services as well. 

Here is wat I get for an state with "enable: True" set for a service: 

Comment: Enable is not available on this minion, service salt-minion started

**Comment by rallytime** [comment] 2016-07-22 15:20
@msdogado Can you give the fix in #34878 a try? Perhaps it would be better to create a new issue for the service module change.

@abednarik Thanks for submitting that fix!

**Comment by msdogado** [comment] 2016-07-22 15:38
Hi, 

sorry but this did not help. 

after exchanging 

enabled = ('amazon', 'xcp', 'xenserver')

by 

enabled = ('amazon', 'xcp', 'xenserver', 'virtuozzolinux')

And removing this form minions config: 

providers:
  pkg: yumpkg


I get: 

     Comment: State 'pkg.installed' was not found in SLS 'global'
              Reason: 'pkg' __virtual__ returned False

**Comment by rallytime** [comment] 2016-07-22 15:50
@msdogado What happens when you do run a pkg execution modules instead of the state? I don't have a virtuozzolinux box to test on right now, but maybe there are some insights in there to see why the pkg execution modules isn't loading. Maybe just something like `salt '*' pkg.list_pkgs`?

**Comment by abednarik** [comment] 2016-07-22 15:58
HI @msdogado  Where did you edit that? In the master or minion? You can also try to put this module in *_modules* flush cache and sync the module. For how to do this check https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html

Sorry this didn't work, will follow up this issue and try to help.
Cheers.

**Comment by msdogado** [comment] 2016-07-22 16:32
@rallytime 

pkg.list_pkgs works! (before @abednarik 's suggestion about the modules)
highstate did not. 

@abednarik 

i now changed it on master and minion. 

no change

**BUT**

after copying yumpgk.py to /srv/salt/_modules 
it works!

**Comment by rallytime** [comment] 2016-07-22 16:37
@msdogado Awesome! Glad that syncing the updated module down to your minions fixed it via the `_modules` directory worked. Thanks again @abednarik!

@msdogado Can you make a new issue for the service module item you mentioned so we can track that in it's own issue? Since you confirmed this particular bug was solved, I'm going to close this ticket. 

Thanks all!

**Closed by rallytime** 2016-07-22 16:37 UTC
Labels: Bug, Core, Execution Module, Fixed Pending Verification, Help Wanted, High Severity, P3

**Comment by msdogado** [comment] 2016-07-22 17:14
@rallytime @abednarik Thanks for your help!

As suggestet by @rallytime I have opened following issue: #34890
