### ISSUE TITLE
[DOCS] Documentation broken in Master for a number of Salt modules

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#59798] opened 2021-03-14 04:48 UTC
**Description**
Master version of Salt Modules Index is missing entire categories of modules, and module indexes for categories as well as the module documentation are all broken in some form or another.

Examples:

Salt Module Index
https://docs.saltproject.io/en/master/py-modindex.html

Salt Beacons Index:
https://docs.saltproject.io/en/master/ref/beacons/all/index.html

Salt.Beacons.BTMP:
https://docs.saltproject.io/en/master/ref/beacons/all/salt.beacons.btmp.html#module-salt.beacons.btmp

It appears to be impacting at least these categories:

- Auth
- Beacons
- Cache
- Cloud
- Engines
- Fileserver
- NetAPI
- Output
- Pillar
- Queues
- Roster
- Thorium
- Token
- Wheel

**Suggested Fix**
Restore formatting and missing sections

**Type of documentation**
Salt documentation (Salt Module Reference)

**Location or format of documentation**
https://docs.saltproject.io/en/master/py-modindex.html

**Comment by max-arnold** [comment] 2021-03-15 03:08
Tried to reproduce the issue locally using `nox -e 'docs-html(compress=False, clean=True)'`, and everything renders just fine. Maybe the root cause is buried somewhere in CI pipelines.

**Comment by ScriptAutomate** [comment] 2021-03-15 23:02
> Tried to reproduce the issue locally using `nox -e 'docs-html(compress=False, clean=True)'`, and everything renders just fine. Maybe the root cause is buried somewhere in CI pipelines.

I have verified the same thing off of `master`. Taking a look at:
- https://gitlab.com/saltstack/open/docs/builddocs

**Comment by ScriptAutomate** [comment] 2021-03-16 15:56
It's definitely the build job for `master-html`:

```
$ cat master-docs.log | grep "Failed to import '" | head
Failed to import 'salt.returners.syslog_return': no module named salt.returners.syslog_return
Failed to import 'salt.modules.vmctl': no module named salt.modules.vmctl
Failed to import 'salt.states.win_powercfg': no module named salt.states.win_powercfg
Failed to import 'salt.modules.solarispkg': no module named salt.modules.solarispkg
Failed to import 'salt.modules.nfs3': no module named salt.modules.nfs3
Failed to import 'salt.modules.mac_timezone': no module named salt.modules.mac_timezone
Failed to import 'salt.modules.postgres': no module named salt.modules.postgres
Failed to import 'salt.grains.lvm': no module named salt.grains.lvm
Failed to import 'salt.returners.elasticsearch_return': no module named salt.returners.elasticsearch_return
Failed to import 'salt.modules.uwsgi': no module named salt.modules.uwsgi
```

This is a long list of `Failed to import...` calls coming from Sphinx that aren't present in the other builds.

```
$ cat master-docs.log | grep "Failed to import '" | wc -l
905
```

```
$ cat latest-docs.log | grep "Failed to import '" | wc -l
0
```

I think this may have to do with the way we are caching virtualenvs, as `nox` is not what is being used to build the docs on that repo. I think that needs to be updated. I think we should update the following, which use venvs? Continuing to look.

- https://gitlab.com/saltstack/open/docs/builddocs/-/blob/master/build_env.sh
- https://gitlab.com/saltstack/open/docs/builddocs/-/blob/master/build_html.sh#L10

**Comment by ScriptAutomate** [comment] 2021-03-16 17:53
When replicating the following locally, I get the failures:

```
# Using Python 3.8.6, like builddocs
python3 -m venv .venv
source .venv/bin/activate
pip install -U pip setuptools wheel
pip install -r requirements/static/ci/py3.8/docs.txt
make -C doc/ clean
make -C doc/ html
```
This is what `builddocs` is using. When using `nox`, on the other hand:

```
nox -e 
```

It looks like `nox` is running one more command that the `build_env.sh` in `builddocs` isn't doing:

```
pip install -r requirements/static/pkg/py3.8/linux.txt
```

When doing this locally, in my `venv` mirroring what is done on `builddocs`, this resolved the import failures. I will be creating a PR to `builddocs` to add this.

**Comment by ScriptAutomate** [comment] 2021-03-16 20:24
WIP MR in the works to resolve this:
- https://gitlab.com/saltstack/open/docs/builddocs/-/merge_requests/18

By the time it is tested and merged, it will be resulting in some follow-up tasks in this repo. These would likely be connected to the need to resolve #59451 due to end of our docs pipeline - being a separate pipeline and repo - being impacted by changes without us knowing until docs are published or the `builddocs` pipeline breaks.

**Comment by ScriptAutomate** [comment] 2021-03-16 23:14
This has been resolved:
- https://docs.saltproject.io/en/master/py-modindex.html (renders as expected)
- https://docs.saltproject.io/en/master/ref/beacons/all/salt.beacons.btmp.html#module-salt.beacons.btmp (renders as expected)
- https://docs.saltproject.io/en/master/ref/beacons/all/index.html (renders as expected)

Resolved by:
- https://gitlab.com/saltstack/open/docs/builddocs/-/merge_requests/18
- https://gitlab.com/saltstack/open/docs/builddocs/-/merge_requests/19

**Closed by ScriptAutomate** 2021-03-16 23:14 UTC
Labels: Bug, Documentation, severity-high
