### ISSUE TITLE
state.dockerio.run: docked_onlyif and docked_unless do not work

### ISSUE THREAD

**Issue by umireon** [saltstack/salt#17088] opened 2014-11-01 12:20 UTC
```docked_onlyif``` and ```docked_unless``` is usable to make the state idempotent.

With the following state:
```
thecommand:
  docker.run:
    - cid: container
```
```thecommand``` will always be executed in the docker container.

With the following state:
```
thecommand:
  docker.run:
    - cid: container
    - docked_unless: /bin/true
```
```thecommand``` will not be executed because ```/bin/true``` indicates the system is already converged in the desired state.

However, ```docked_onlyif``` disables the function ```state.dockerio.run``` entirely and ```docked_unless``` have totally no effects in the current implement.

This malfunction is caused by the bug in the function ```modules.dockerio.retcode```.
```modules.dockerio.retcode``` should return the return code as ```int```, but it returns an instance of ```dict```.
I created the minimum case to prove ```modules.dockerio.retcode``` returns ```dict```:
https://github.com/umireon/salt-docker-retcode-is-broken-vagrant
and the log:
https://gist.github.com/umireon/baa589bf1d74ce3b9f7e

**Comment by tkent-xetus** [comment] 2015-04-21 21:09
This is very easy work around by using a `docker exec` command, but it does take some time to figure out that it's not working. Any chance the docs could be updated to remove referencing to these features until it's resolved?

**Comment by Arabus** [comment] 2015-09-06 21:53
As this just bit me in the but quite hard when trying to create a couple of database users and dbs after starting a container I'd really like to fix this.

@basepi does your comment concern only references to the retcode function inside the docker.io module? If so I'd be happy to track them down and provide a patch.

**Comment by Arabus** [comment] 2015-09-06 23:12
After going through the code of the state for dockerio.run I become more and more convinced that the whole method is borked. Take for example this part:

```python
    if onlyif is not None:
        if not isinstance(onlyif, string_types):
            if not onlyif:
                return valid(comment='onlyif execution failed')
        elif isinstance(onlyif, string_types):
            if retcode(cid, onlyif) != 0:
                return valid(comment='onlyif execution failed')

    if unless is not None:
        if not isinstance(unless, string_types):
            if unless:
                return valid(comment='unless execution succeeded')
        elif isinstance(unless, string_types):
            if retcode(cid, unless) == 0:
                return valid(comment='unless execution succeeded')
```

According to documentation the commands in the `unless` and `onlyif` variables should be run on the host of the docker container identified by `cid`. The calls above run the commands inside the containers though. In fact the code is no different than the one for running a test command inside a container as in this code-snippet:

```python
    if docked_onlyif is not None:
        if not isinstance(docked_onlyif, string_types):
            if not docked_onlyif:
                return valid(comment='docked_onlyif execution failed')
        elif isinstance(docked_onlyif, string_types):
            if retcode(cid, docked_onlyif) != 0:
                return valid(comment='docked_onlyif execution failed')

    if docked_unless is not None:
        if not isinstance(docked_unless, string_types):
            if docked_unless:
                return valid(comment='docked_unless execution succeeded')
        elif isinstance(docked_unless, string_types):
            if retcode(cid, docked_unless) == 0:
                return valid(comment='docked_unless execution succeeded')
```

Which behaves exactly the same using `docked_onlyif` and `docked_unless`.

**Comment by basepi** [comment] 2015-09-15 18:43
Looks like you got a fix in @Arabus. Can this be closed?

**Comment by Arabus** [comment] 2015-09-15 21:39
I guess so, though I'd like it if someone other than me to also tested this, just to be sure it works as intended.

**Comment by basepi** [comment] 2015-09-15 23:18
@umireon Can you test the merged fix above?

**Comment by umireon** [comment] 2015-09-17 15:41
I confirmed with latest `2015.5` that everything works as expected.

```
2015-09-17 15:35:04,837 [salt.state       ][INFO    ][15354] Running state [echo desired to be executed (if)] at time 15:35:04.836652
2015-09-17 15:35:04,837 [salt.state       ][INFO    ][15354] Executing state docker.run for echo desired to be executed (if)
2015-09-17 15:35:04,943 [salt.loaded.int.module.cmdmod][INFO    ][15354] Executing command 'nsenter --target 13493 --mount --uts --ipc --net --pid -- /bin/true' in directory '/root'
2015-09-17 15:35:05,065 [salt.loaded.int.module.cmdmod][INFO    ][15354] Executing command 'nsenter --target 13493 --mount --uts --ipc --net --pid -- echo desired to be executed (if)' in directory '/root'
2015-09-17 15:35:05,073 [salt.state       ][INFO    ][15354] Executed nsenter --target 13493 --mount --uts --ipc --net --pid -- echo desired to be executed (if)
2015-09-17 15:35:05,074 [salt.state       ][INFO    ][15354] Completed state [echo desired to be executed (if)] at time 15:35:05.072940

2015-09-17 15:35:05,074 [salt.state       ][INFO    ][15354] Running state [echo desired not to be executed (if)] at time 15:35:05.073930
2015-09-17 15:35:05,074 [salt.state       ][INFO    ][15354] Executing state docker.run for echo desired not to be executed (if)
2015-09-17 15:35:05,179 [salt.loaded.int.module.cmdmod][INFO    ][15354] Executing command 'nsenter --target 13493 --mount --uts --ipc --net --pid -- /bin/false' in directory '/root'
2015-09-17 15:35:05,187 [salt.loaded.int.module.cmdmod][ERROR   ][15354] Command 'nsenter --target 13493 --mount --uts --ipc --net --pid -- /bin/false' failed with return code: 1
2015-09-17 15:35:05,187 [salt.loaded.int.module.cmdmod][ERROR   ][15354] output:
2015-09-17 15:35:05,188 [salt.state       ][INFO    ][15354] docked_onlyif execution failed
2015-09-17 15:35:05,188 [salt.state       ][INFO    ][15354] Completed state [echo desired not to be executed (if)] at time 15:35:05.187816

2015-09-17 15:35:05,188 [salt.state       ][INFO    ][15354] Running state [echo desired not to be executed (unless)] at time 15:35:05.188076
2015-09-17 15:35:05,188 [salt.state       ][INFO    ][15354] Executing state docker.run for echo desired not to be executed (unless)
2015-09-17 15:35:05,285 [salt.loaded.int.module.cmdmod][INFO    ][15354] Executing command 'nsenter --target 13493 --mount --uts --ipc --net --pid -- /bin/true' in directory '/root'
2015-09-17 15:35:05,295 [salt.state       ][INFO    ][15354] docked_unless execution succeeded
2015-09-17 15:35:05,295 [salt.state       ][INFO    ][15354] Completed state [echo desired not to be executed (unless)] at time 15:35:05.295128

2015-09-17 15:35:05,296 [salt.state       ][INFO    ][15354] Running state [echo desired to be executed (unless)] at time 15:35:05.295580
2015-09-17 15:35:05,296 [salt.state       ][INFO    ][15354] Executing state docker.run for echo desired to be executed (unless)
2015-09-17 15:35:05,398 [salt.loaded.int.module.cmdmod][INFO    ][15354] Executing command 'nsenter --target 13493 --mount --uts --ipc --net --pid -- /bin/false' in directory '/root'
2015-09-17 15:35:05,406 [salt.loaded.int.module.cmdmod][ERROR   ][15354] Command 'nsenter --target 13493 --mount --uts --ipc --net --pid -- /bin/false' failed with return code: 1
2015-09-17 15:35:05,406 [salt.loaded.int.module.cmdmod][ERROR   ][15354] output:
2015-09-17 15:35:05,570 [salt.loaded.int.module.cmdmod][INFO    ][15354] Executing command 'nsenter --target 13493 --mount --uts --ipc --net --pid -- echo desired to be executed (unless)' in directory '/root'
2015-09-17 15:35:05,585 [salt.state       ][INFO    ][15354] Executed nsenter --target 13493 --mount --uts --ipc --net --pid -- echo desired to be executed (unless)
2015-09-17 15:35:05,586 [salt.state       ][INFO    ][15354] Completed state [echo desired to be executed (unless)] at time 15:35:05.585766
```

**Comment by Arabus** [comment] 2015-09-17 17:30
Nice! lets close this issue then.

**Closed** 2015-09-17 17:52 UTC
Labels: Bug, Execution Module, Fixed Pending Verification, High Severity, P3
