### ISSUE TITLE
[BUG] 3005 pillar.get, vault.read_secret, vault.list_secrets changes are slightly problematic

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#62450] opened 2022-08-09 23:07 UTC
**Description**

Severial modules were updated in 3005 to change their default behavior of the... `default` parameter: https://github.com/saltstack/salt/pull/61089

There are several issues with that change:
1. Change is not documented. Nothing states that if the **default** is **None** it will lead to the error raise.
2. Changing the defaults should be done very carefully and usually with some kind of deprecation policy. People could rely on defaults. Like we used `default=None` as a secret default for the vault! It just makes sense to us.

**Expected behavior**
I do not fully understand the issue that was attempted to be fixed here so I can't really suggest the change here.

**Comment by ITJamie** [comment] 2022-08-10 09:08
+1 on this. None is a sane fallback incase a vault item cant be read. It allows us to easily gate out code in states as we can easily do `{% if vault_item_var %}` 

+1 on needing a deprecation warning. This is a common usecase (at least from my experience across a few companies that use salt + vault)

**Comment by Oloremo** [comment] 2022-08-10 16:22
@OrangeDog technically it's not only about the vault, pillars.get affected as well.

**Comment by OrangeDog** [comment] 2022-08-10 16:35
@Oloremo the linked PR didn't change the pillar behaviour. It's still `KeyError` by default.

**Comment by Oloremo** [comment] 2022-08-10 16:46
It's not, it became `None` by default with None leading to `KeyError`, same as with vault modules.

So you now **can't** do:
```
pillar.get some_key default=None
```

**Comment by OrangeDog** [comment] 2022-08-10 17:03
I see what you mean. You are correct - that is a breaking change.

**Comment by twangboy** [comment] 2022-08-11 16:37
The reason this was changed is because we were passing `KeyError` as the default to the function. This was causing a serialization error as you can't serialize `type` objects. So, we set it to `None` and if it is `None`, then the default becomes `KeyError`.

I don't understand your example saying that you can't do `pillar.get nonexisting_key default=None`. Since the default is `None` I don't see why that is a breaking change. Maybe I'm misunderstanding something.

**Comment by OrangeDog** [comment] 2022-08-11 16:55
Because then it will raise `KeyError` instead of returning `None`.

**Comment by waynew** [comment] 2022-08-11 17:11
nice catch!

I see what the problem is, and it was a case that we hadn't really considered - namely that folks would *want* a `default=None`. On the subject of deprecation for default args - under normal circumstance I'd agree, but the *existing* defaults are actually bugs.

In this case what we *probably* want to do is have a `salt.common.SPECIAL_DEFAULT` or something that we can use that's literally just `SPECIAL_DEFAULT = object()`. I think that would solve the serializable issue as well as give us the correct fallback behavior.

**Comment by Ch3LL** [comment] 2022-08-18 01:18
Closed by https://github.com/saltstack/salt/pull/62458

**Closed by Ch3LL** 2022-08-18 01:18 UTC
Labels: Bug, Regression, Pillar, needs-triage, Phosphorus v3005.0, Vault
