### ISSUE TITLE
cloud roster not working

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#31005] opened 2016-02-08 16:43 UTC
### configs

``` yaml
jmoney-main ~ master # cat /etc/salt/master
log_fmt_console: '%(colorlevel)s %(colormsg)s'
```

``` yaml
jmoney-main ~ master # cat /etc/salt/cloud
update_cachedir: True
```
### salt-cloud

``` console
jmoney-main ~ master # salt-cloud --no-deploy -p do-centos-7 jmoney-centos-7
[INFO    ] salt-cloud starting
[WARNING ] %s
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[INFO    ] Creating Cloud VM jmoney-centos-7
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] Created Cloud VM 'jmoney-centos-7'
jmoney-centos-7:
    ----------
    Error:
        ----------
        No Deploy:
            'deploy' is not enabled. Not deploying.
    backup_ids:
    created_at:
        2016-02-08T16:33:37Z
    ...
    kernel:
        ----------
        id:
            6028
        name:
            CentOS 7 x64 vmlinuz-3.10.0-229.20.1.el7.x86_64
        version:
            3.10.0-229.20.1.el7.x86_64
    locked:
        True
    memory:
        2048
    name:
        jmoney-centos-7
    ...
```

``` console
jmoney-main ~ master # ls -lh /var/cache/salt/cloud/active/digital_ocean/do/jmoney-centos-7.p 
-rw-r--r-- 1 root root 917 Feb  8 09:31 /var/cache/salt/cloud/active/digital_ocean/do/jmoney-centos-7.p
```
### salt-ssh

``` console
jmoney-main ~ master # salt-ssh -l debug --roster=cloud jmoney-centos-7 -i test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: jmoney-main
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded cloud.targets
No hosts found with target jmoney-centos-7 of type glob
```
### versions

``` yaml
jmoney-main ~ master # salt-cloud --versions
Salt Version:
            Salt: 2015.8.3

Dependency Versions:
 Apache Libcloud: 0.20.0
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
            Mako: 1.0.0
          PyYAML: 3.11
           PyZMQ: 14.4.0
          Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
            cffi: 0.8.6
        cherrypy: Not Installed
        dateutil: Not Installed
           gitdb: 0.5.4
       gitpython: 0.3.2 RC1
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.2
    mysql-python: Not Installed
       pycparser: 2.10
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: 0.8.2
         timelib: Not Installed

System Versions:
            dist: debian 8.2
         machine: x86_64
         release: 3.16.0-4-amd64
          system: debian 8.2
```

**Comment by martinhoefling** [comment] 2016-03-31 09:04
I checked my cache but I do not have an index.p top level in the cloud cache. Thus, I assume that: https://github.com/saltstack/salt/blob/develop/salt/roster/cloud.py#L45 is the problem.

**Comment by martinhoefling** [comment] 2016-03-31 10:16
Further, I would suggest to remove the code or adapt the documentation until that bug is fixed.

**Comment by jfindlay** [comment] 2016-04-25 18:45
I worked on this over the weekend, but it is not finished yet: https://github.com/saltstack/salt/compare/2015.8...jfindlay:cloud_roster.

**Comment by martinhoefling** [comment] 2016-04-26 01:14
Great, let me know when it's ready to test it (we only have AWS accounts).

**Comment by sestary** [comment] 2017-02-05 18:55
Anything happening with this ticket? I am having this same issue, but with the Linode provider, in my case though it doesn't seem to be putting anything in the /var/cache/salt/cloud directory, even with this option set in the /etc/salt/cloud config file `update_cachedir: True`

**Comment by gtmanfred** [comment] 2017-03-21 19:44
@martinhoefling which version of salt are you running?

This is currently working for me in 2016.11.  The problem is that the way that the lookups are done does not allow for matching more than one minion.

If you take a look at the changes to the cloud roster in develop, this should be able to be used, and I have tested that it works with several different providers.

Thanks,
Daniel

**Comment by martinhoefling** [comment] 2017-03-21 21:25
So we're still running 2016.3.

**Comment by gtmanfred** [comment] 2017-03-21 21:33
It is very unlikely that we will get this fixed on 2016.3, because we have already tagged the last non CVE fix for 2016.3.  So you will need to check out the cloud roster on 2016.11, and possibly the cloud drivers which should all have cache_node built in now?

Nitrogen will be the first one that is certain to work with multiple minions in a glob because of the addition of the cache.cloud runner module.

**Comment by martinhoefling** [comment] 2017-03-21 21:36
All right, we've currently worked around that issue but it's good to know that we maybe can remove this in the future. Feel free to close the issue if you consider it fixed in a recent version.

**Comment by gtmanfred** [comment] 2017-03-21 21:36
Thanks!

**Closed by gtmanfred** 2017-03-21 21:36 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P3, RIoT, Salt-Cloud, Salt-SSH
