### ISSUE TITLE
v2015.8.0 fails ec2 deploy with 401: "AWS was not able to validate the provided access credentials"

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#27121] opened 2015-09-15 01:54 UTC
A downgrade to 2015.5.5 confirms that this did work in the earlier release.

Profile:
```
haproxy-gateway:
  extends: base-ec2-linux
  private_key: /etc/salt/.ssh/staging-sshkey-proxy.pem
  keyname: staging-sshkey-proxy.pem.pub
  iam_profile: HAProxyRole
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: False
      SubnetId: subnet-xxxxx
      SecurityGroupId: sg-xxxxx
  tag: {'Environment': 'staging', 'Role': 'proxy'}
```

Response:
```
[DEBUG   ] Using EC2 endpoint: ec2.us-west-2.amazonaws.com
[DEBUG   ] EC2 Request: https://ec2.us-west-2.amazonaws.com/
[INFO    ] Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
[DEBUG   ] "GET /?Action=ModifyNetworkInterfaceAttribute&NetworkInterfaceId=eni-71970d17&Attachment.DeleteOnTermination=True&Attachment.AttachmentId=eni-attach-6f56f064&Version=2014-10-01 HTTP/1.1" 401 None
[DEBUG   ] EC2 Response Status Code: 401
[ERROR   ] EC2 Response Status Code and Error: [401 401 Client Error: Unauthorized] {'Errors': {'Error': {'Message': 'AWS was not able to validate the provided access credentials', 'Code': 'AuthFailure'}}, 'RequestID': '5ac5b0e1-09f2-4f03-9847-7b4936e77861'}
```

The deploy does continue and does create a running instance, albeit without a network interface.

**Comment by jfindlay** [comment] 2015-09-15 17:07
@rterbush, thanks for the report.

**Comment by rallytime** [comment] 2015-09-22 22:01
It looks to me like this was likely broken by the changes in #25319. @ruzarowski Do you think you could take a look at this bug if you get a moment?

**Comment by ruzarowski** [comment] 2015-09-23 08:32
@rallytime We've been using #25319 as backported patch to 2014.7 since my MR in a production env, but I might take a look at it sometime soon. Though it looks as if another change in 2015.8 might interfere here.

**Comment by rallytime** [comment] 2015-09-23 14:59
@ruzarowski OK, thanks for confirming. There must be something else causing this error.

**Comment by ruzarowski** [comment] 2015-09-23 15:35
I'd say it could be something with the IAM Role the reporter specified in
his map, as we do not use it so it might be the cause
(As in :  have never seen it working)

**Comment by rterbush** [comment] 2015-09-23 15:59
Provider details:
```
aws-us-west-2a-public-ips:
  minion:
    master: hostname

  private_key: /etc/salt/salt-provisioning-key
  keyname: salt-provisioning-key
  ssh_interface: public_ips
  ssh_username: ec2-user
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  location: us-west-2
  availability_zone: us-west-2a
  iam_profile: ManagementServerRole
  driver: ec2
```

Complete profile:
```
haproxy-gateway:
  provider: aws-us-west-2a-public-ips
  image: ami-xxxx
  size: t2.micro
  del_root_vol_on_destroy: True
  rename_on_destroy: True
  private_key: /etc/salt/staging-sshkey-proxy.pem
  keyname: staging-sshkey-proxy.pem.pub
  iam_profile: HAProxyRole
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: False
      SubnetId: subnet-xxxxx
      SecurityGroupId: sg-xxxxx
  tag: {'Environment': 'staging', 'Role': 'proxy'}
```

As I mentioned in the initial report, this works in 2015.5.5. IAM Profiles do work in 2015.5.5 as well.

In the error message I included above, the specific issue it is failing on is changing attribute for the network interface which as I remember, was not the first action the process performed which needed credentials (which it gets in the IAM profile assignment). It seems those credentials may not be getting carried through all required actions.

**Comment by ruzarowski** [comment] 2015-09-23 19:44
Sounds like modify_eni_properties is using the wrong
api call wrapper maybe...

**Comment by ruzarowski** [comment] 2015-09-23 20:12
@rterbush Are you able to test with the following commit?
https://github.com/ruzarowski/salt/commit/c58e7a00f31539ccadfdaf2c9b66af1cc3374a13

**Comment by rterbush** [comment] 2015-09-23 22:55
@ruzarowski I've attempted to test with this change but am running into a different problem. 

DEBUG below
```
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Created network interface eni-dcd5a9ba inst 0
[DEBUG   ] Using AWS endpoint: ec2.us-west-2.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-2.amazonaws.com/?Action=AllocateAddress&Domain=vpc&Version=2014-10-01
[INFO    ] Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
[DEBUG   ] "GET /?Action=AllocateAddress&Domain=vpc&Version=2014-10-01 HTTP/1.1" 400 None
[DEBUG   ] AWS Response Status Code: 400
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': 'The maximum number of addresses has been reached.', 'Code': 'AddressLimitExceeded'}}, 'RequestID': 'bce18bfb-c2d7-4694-a3d0-c1c0895c23f0'}
[DEBUG   ] Using AWS endpoint: ec2.us-west-2.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-2.amazonaws.com/?Action=AssociateAddress&AllocationId=None&NetworkInterfaceId=eni-dcd5a9ba&Version=2014-10-01
[INFO    ] Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
[DEBUG   ] "GET /?Action=AssociateAddress&AllocationId=None&NetworkInterfaceId=eni-dcd5a9ba&Version=2014-10-01 HTTP/1.1" 400 None
[DEBUG   ] AWS Response Status Code: 400
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': "The allocation ID 'None' does not exist", 'Code': 'InvalidAllocationID.NotFound'}}, 'RequestID': '4e56392c-2a32-43cf-baa0-ee6c4375ffc9'}
[DEBUG   ] Using AWS endpoint: ec2.us-west-2.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-2.amazonaws.com/?Action=AssociateAddress&AllocationId=None&NetworkInterfaceId=eni-dcd5a9ba&Version=2014-10-01
[INFO    ] Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
[DEBUG   ] "GET /?Action=AssociateAddress&AllocationId=None&NetworkInterfaceId=eni-dcd5a9ba&Version=2014-10-01 HTTP/1.1" 400 None
[DEBUG   ] AWS Response Status Code: 400
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': "The allocation ID 'None' does not exist", 'Code': 'InvalidAllocationID.NotFound'}}, 'RequestID': 'd2aaa521-cdbd-4e33-9eca-b85c0a30f201'}
[DEBUG   ] Using AWS endpoint: ec2.us-west-2.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-2.amazonaws.com/?Action=AssociateAddress&AllocationId=None&NetworkInterfaceId=eni-dcd5a9ba&Version=2014-10-01
```

**Comment by rterbush** [comment] 2015-09-23 23:02
@ruzarowski This does solve the problem.

```
# salt --version
salt 2015.8.0 (Beryllium)
```

Note that this is salt 2015.8.0 with your changes only. This is not the develop branch.

Thanks for your help. Let me know if you need any other info to close this out.

**Comment by rallytime** [comment] 2015-09-23 23:08
@rterbush That's great news!

@ruzarowski Would you like to submit a pull request against the 2015.8 branch with this fix? If not, I can grab it as well. Thank you very much for looking at this issue.

**Comment by ruzarowski** [comment] 2015-09-24 09:19
@rallytime MR #27364

**Comment by rallytime** [comment] 2015-09-24 14:47
@ruzarowski Awesome! Thank you!

@rterbush Since you've confirmed that this fixes the issue for you, I'll go ahead and close this.

**Closed by rallytime** 2015-09-24 14:47 UTC
Labels: Bug, High Severity, P2, Regression, RIoT, Salt-Cloud

**Comment by rterbush** [comment] 2015-09-25 21:24
Would like to reopen this issue in case this is related. Note that this same setup works as expected on 2015.5.5. Not sure if we have not fully fixed this reported issue or if I am finding a new issue. Let me know if you would prefer that I open a new issue.

As reported, the deployment now works with an exception that the salt-minion code does not get installed. I am only finding one error in the log and would appreciate if you can advise if this is related.

```
[DEBUG   ] Using AWS endpoint: ec2.us-west-2.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-2.amazonaws.com/?Action=CreateTags&ResourceId.1=i-1aede1df&Tag.0.Key=Environment&Tag.0.Value=staging&Tag.1.Key=Monitored&Tag.1.Value=Yes&Tag.2.Key=Name&Tag.2.Value=nat.staging.west.lhn&Tag.3.Key=Role&Tag.3.Value=nat&Version=2014-10-01
[Info    ] Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
[DEBUG   ] "GET /?Action=CreateTags&ResourceId.1=i-1aede1df&Tag.0.Key=Environment&Tag.0.Value=staging&Tag.1.Key=Monitored&Tag.1.Value=Yes&Tag.2.Key=Name&Tag.2.Value=nat.staging.west.lhn&Tag.3.Key=Role&Tag.3.Value=nat&Version=2014-10-01 HTTP/1.1" 400 None
[DEBUG   ] AWS Response Status Code: 400
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': "The instance ID 'i-1aede1df' does not exist", 'Code': 'InvalidInstanceID.NotFound'}}, 'RequestID': '7266fdce-f367-418f-a978-1bae34141620'}
```

**Comment by rallytime** [comment] 2015-09-25 21:32
@rterbush when you run this does it look like the bootstrap script is getting deployed (and executed) on the minion? Do you have an `/etc/salt/cloud.deploy.d/` directory on the machine you're running salt-cloud on?

**Comment by rterbush** [comment] 2015-09-25 21:50
@rallytime 
Here is a gist of the entire debug output: https://gist.github.com/rterbush/76b047502cfced8daa96

Yes, it appears that the minion bootstrap and install process is running and there is no error recorded anywhere other than the snippet I provided.

I do not have an /etc/salt/cloud.deploy.d/ directory. Everything currently local to the profile definitions. (which amounts to the cloud.providers and cloud.profiles)

**Comment by rterbush** [comment] 2015-09-25 21:57
Additionally, the /tmp directory referenced in the minion bootstrap process exists, but is empty at the stage that the deploy completes. (name here is different from the debug I supplied since this is a different run)

```
[root@ip-10-0-1-206 ec2-user]# ls -la /tmp/.saltcloud-650d7493-5d7e-40da-b705-0622982b957d/
total 8
drwx------ 2 ec2-user root 4096 Sep 25 21:43 .
drwxrwxrwt 5 root     root 4096 Sep 25 21:54 ..

```

**Comment by rallytime** [comment] 2015-09-25 21:58
@rterbush I think you might be hitting #26699 (see [final comments](https://github.com/saltstack/salt/issues/26699#issuecomment-140566010) as to the true error in question, as the title isn't quite right for the problem).

If you run a `salt-cloud -u` this should create this directory for you and should bootstrap and install the minion on the next `salt-cloud -p` run.

Also if you could post the output of `ls path/to/your/salt/install/salt/cloud/deploy/` that would be great. I can't figure out where this bug is coming from if it is the same one.

**Comment by rterbush** [comment] 2015-09-25 22:05
@rallytime 
Here is the requested directory listing: (installed with install_salt.sh -P -M git v2015.8.0)
```
[root@manage salt]# ls -l /usr/lib/python2.6/dist-packages/salt/cloud/deploy/
total 292
-rw-r--r-- 1 root root    864 Sep 24 23:21 Arch-git.sh
-rw-r--r-- 1 root root    677 Sep 24 23:21 Arch.sh
-rw-r--r-- 1 root root 209530 Sep 24 23:21 bootstrap-salt.sh
-rw-r--r-- 1 root root    737 Sep 24 23:21 curl-bootstrap-git.sh
-rw-r--r-- 1 root root    710 Sep 24 23:21 curl-bootstrap.sh
-rw-r--r-- 1 root root   1297 Sep 24 23:21 Debian-git.sh
-rw-r--r-- 1 root root   1049 Sep 24 23:21 Debian.sh
-rw-r--r-- 1 root root   1187 Sep 24 23:21 Fedora-git.sh
-rw-r--r-- 1 root root    982 Sep 24 23:21 Fedora.sh
-rw-r--r-- 1 root root   1000 Sep 24 23:21 FreeBSD-git.sh
-rw-r--r-- 1 root root    938 Sep 24 23:21 FreeBSD.sh
-rw-r--r-- 1 root root    407 Sep 24 23:21 None.sh
-rw-r--r-- 1 root root    809 Sep 24 23:21 python-bootstrap.sh
-rw-r--r-- 1 root root    913 Sep 24 23:21 RHEL5-git.sh
-rw-r--r-- 1 root root    725 Sep 24 23:21 RHEL5.sh
-rw-r--r-- 1 root root    934 Sep 24 23:21 RHEL6-git.sh
-rw-r--r-- 1 root root    751 Sep 24 23:21 RHEL6.sh
-rw-r--r-- 1 root root   1031 Sep 24 23:21 SmartOS.sh
-rw-r--r-- 1 root root   1464 Sep 24 23:21 Ubuntu-git.sh
-rw-r--r-- 1 root root   1217 Sep 24 23:21 Ubuntu.sh
-rw-r--r-- 1 root root    759 Sep 24 23:21 wget-bootstrap-nocert.sh
-rw-r--r-- 1 root root    713 Sep 24 23:21 wget-bootstrap.sh
```

**Comment by rterbush** [comment] 2015-09-25 22:12
Your suggestion of salt-cloud -u solves the problem.

As has been sorted out #26699, my environment was also an upgrade from 2015.5.5, then a downgrade when encountering the error reported in #27121 and up and down. I've saved the /etc/salt directories that were created on each of those upgrades and none of them contain this required directory and script.

Thanks again for your help. Seems there should be an error generated if that script does not exist.

**Comment by rallytime** [comment] 2015-09-25 22:14
Awesome! I'm glad that was easy to fix. Hopefully you're off to the races now.

I haven't figured out where the bug is here. You shouldn't HAVE to have that directory. Salt-cloud **can** pull it from there, but if `/etc/salt/cloud.deploy.d/` doesn't exist, it's supposed to pull it from your `/usr/lib/python2.6/dist-packages/salt/cloud/deploy/` directory. So, I'll keep trying to find where that is falling down. Thanks!
