### ISSUE TITLE
pillar render errors when launching states from master, but none on minions themselves

### ISSUE THREAD

**Issue by alienzrcoming** [saltstack/salt#13080] opened 2014-05-28 17:23 UTC
Hi,

I've been seeing an issue when I target many minions with state runs, where the output on the master indicates that there are pillar issues with various minions.  The issues it reports are old, and no longer in place in the pillar files themselves.  I've tried saltutil.refresh_pillar from the master, and killing off the /var/cache/salt directory on the minions themselves followed by a restart of salt-minion to no avail.   As a last resort, I also tried deleting /var/cache/salt/master on the master followed by a restart of salt-master, which hasn't worked either.  Any ideas what could be causing this?

```
salt -E ^ln.* state.sls states.monitoring.diskspace
...
...
minion01:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'environments.live.web.django-sites.beta' failed, render error:
while parsing a block collection
  in "<unicode string>", line 167, column 11:
              - 'pkg:  build-essential pkg for ... 
              ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 170, column 14:
              - 'file:  /root/.pypirc file for dj ... 
                 ^
```

Again, these are pillar issues that did exist at one time, but have been fixed.  Running 'salt-call pillar.data' on the minions themselves show proper pillar rendering.

MASTER:  (Debian Wheezy)
```
salt --versions-report
           Salt: 2014.1.4
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

MINIONS:  (Debian Wheezy)
```
salt-call --versions-report
           Salt: 2014.1.4
         Python: 2.7.3 (default, Jan  2 2013, 13:56:14)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

**Comment by jfindlay** [comment] 2015-07-14 20:46
@alienzrcoming, @boltronics, have either of you experienced this issue with the latest release of salt (2015.5.3)?

**Comment by boltronics** [comment] 2015-07-15 09:07
I haven't noticed the issue, but I haven't had to spend that much time adding and modifying states this year (relatively speaking). Since I only saw the issue the one time, it's clearly extremely rare.

It's also interesting that we both saw the issue on Wheezy. We've begun rolling out Jessie, so it's unclear that I'd be able to reproduce this anyway.

**Comment by jfindlay** [comment] 2015-07-15 16:22
I am going to close this based on the information from @boltronics.  If anyone else encounters this again, please comment and we will reopen it.

**Closed by jfindlay** 2015-07-15 16:22 UTC
Labels: Bug, Core, High Severity, P4, Pillar

**Comment by temal-** [comment] 2018-03-08 07:23
The same thing happened in our stage environment this morning. A couple of pillars gather data from a Vault server via the [vault module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.vault.html). This morning the vault server was sealed which resulted in expected errors when rendering pillars. After unsealing vault the salt master (even after a restart) failed to render multiple templates.

```
root@salt.stage.mgmt:~# salt 'ip-10-3-66-61.eu-central-1.compute.internal' state.apply
ip-10-3-66-61.eu-central-1.compute.internal:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'order-service-stage' failed. Please see master log for details.
```

The master log does not contain any errors after making vault available again and restarting the salt-master process.

Running `salt-call state.apply` on the minions did work. After the first run it also worked on the salt-master again.

Versions:

Master:
```
malte@salt.stage.mgmt:~$ salt --versions-report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1052-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minions:
```
malte@ip-10-3-75-78.eu-central-1.compute.internal:~$ salt-call --versions-report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1052-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

In the meantime the hosts which had problems got destroyed by the autoscaling group and therefore I currently cannot reproduce the error. There are no errors on the newly provisioned hosts.
