### ISSUE TITLE
Issue with compound matching in Salt if grain name has space in name

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#21565] opened 2015-03-11 20:29 UTC
Noticed the following:

If i did targeting using compound matchers and if the grain name has spaces in it's value then it would not match any minions:

```
[root@master ~]# salt -C 'G@osfullname:Oracle Linux Server' grains.get saltversion
No minions matched the target. No command was sent, no jid was assigned.
```

```
[root@master ~]# salt -C 'G@saltversion:2014.1.4 and G@osfullname:Oracle Linux Server' grains.get saltversion
No minions matched the target. No command was sent, no jid was assigned.
```

```
[root@cuimemiutl03 ~]# salt -C 'G@saltversion:2014.1.4 and G@osfullname:Oracle*' grains.get saltversion
minion1:
    2014.1.4
minion2:
    2014.1.4
minion3:
    2014.1.4
minion4:
    2014.1.4
```

It works if i use only Grain based targeting and not Compound matching:
```
[root@master ~]# salt -G 'osfullname:Oracle Linux Server' grains.get saltversionsaltversion
minion1:
    2014.1.4
minion2:
    2014.1.4
minion3:
    2014.1.4
minion4:
    2014.1.4
minion5:
    2014.1.4
minion6:
    2014.1.4
minion7:
    2014.1.4
```

Running the following salt-master version:
```
[root@master ~]# salt --versions-report
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

@cingeyedog and I noticed the bug

**Comment by jfindlay** [comment] 2015-03-11 21:04
This is a duplicate of #21260.  What do you think, @nmadhok?

**Comment by nmadhok** [comment] 2015-03-12 00:14
@jfindlay Didn't notice there's already an issue filed for that. Anyway here's some more detail about the issue. I'll try to fix this if time permits myself.

**Comment by jfindlay** [comment] 2015-03-12 00:43
@nmadhok, that would be awesome, thanks.  I'm going to close this one in favor of the other if that's fine with you.

**Closed by jfindlay** 2015-03-12 00:43 UTC
Labels: Duplicate
