### ISSUE TITLE
rest_cherrypy does not return responses from syndic-connected minions

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#43331] opened 2017-09-02 19:24 UTC
### Description of Issue/Question
I have a master-of-masters connected to 3 downstream syndics. On the salt CLI, If i run the simple query (for example) `salt -C 'G@os:*' test.ping`, I get responses from all minions whether they are connected directly to the master or to a syndic. But when making the same request via rest_cherrypy, I only receive responses from minions connected directly to the master-of-masters.

The same behavior is true for a `glob` target of `*`.

Is it expected behavior for rest_cherrypy to ignore minions connected via syndics? If so... why?

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by V3XATI0N** [comment] 2017-09-03 17:06
update: to be more clear -- the API returns "responses" from syndic minions, but test.ping returns "false" despite the fact that they do in fact reply, and any other function (grains.item, for example) returns empty and useless.

**Comment by gtmanfred** [comment] 2017-09-05 16:11
This will be fixed in 2017.7.2

https://github.com/saltstack/salt/pull/42710

Thanks,
Daniel

**Closed by gtmanfred** 2017-09-05 16:11 UTC

**Comment by V3XATI0N** [comment] 2017-09-05 18:12
Is #42710 all that is required? I patched that PR in locally and it has no effect on this issue. I already get a response for syndic-connected minions when they're disconnected ("false").  What I was hoping for was to get useful data when they _are_ connected, but even with that PR, they still just return "false".

**Comment by gtmanfred** [comment] 2017-09-05 19:16
did you restart the salt-master and salt-api processes after applying the patch?

With the little information provided, it sounds like this is a duplicate of this issue, https://github.com/saltstack/salt/issues/42668

Which i have re verified is fixed by the above patch, that it does return the information.

This was originally broken in https://github.com/saltstack/salt/pull/36318 because they used an XOR comparison, which checked for minions only listed in either the return or the list of minions connected to the master, so if they were not in the list of minions directly connected to the master, but were in the return data, they would have their output overwritten by `false`.

By changeing it to a minus sign, it just subtracts and will only report false for minions directly connected to the master, and not for minions the are returning and connected to a syndic.

**Comment by gtmanfred** [comment] 2017-09-05 19:29
```
[root@saltmaster /]# curl -Ssk https://localhost:8000/run \
>   -H 'Accept: application/x-yaml' \
>   -H 'Content-type: application/json' \
>   -d '[{
>   "client": "local",
>   "tgt": "*",
>   "fun": "test.version",
>   "username": "saltdev",
>   "password": "saltdev",
>   "eauth": "pam"}]'

return:
- e671ddf11038: false
  f7cfc145a2f3: false
  syndic1: 2017.7.1
  syndic2: 2017.7.1
[root@saltmaster /]# patch -Np1 -d /usr/lib/python2.7/site-packages/ < <(curl -Ls https://github.com/saltstack/salt/pull/42710.diff)
patching file salt/client/__init__.py
[root@saltmaster /]# curl -Ssk https://localhost:8000/run \
>   -H 'Accept: application/x-yaml' \
>   -H 'Content-type: application/json' \
>   -d '[{
>   "client": "local",
>   "tgt": "*",
>   "fun": "test.version",
>   "username": "saltdev",
>   "password": "saltdev",
>   "eauth": "pam"}]'

return:
- e671ddf11038: false
  f7cfc145a2f3: false
  syndic1: 2017.7.1
  syndic2: 2017.7.1
[root@saltmaster /]# systemctl restart salt-api salt-master
[root@saltmaster /]# sleep 10
[root@saltmaster /]# curl -Ssk https://localhost:8000/run \
>   -H 'Accept: application/x-yaml' \
>   -H 'Content-type: application/json' \
>   -d '[{
>   "client": "local",
>   "tgt": "*",
>   "fun": "test.version",
>   "username": "saltdev",
>   "password": "saltdev",
>   "eauth": "pam"}]'

return:
- e671ddf11038: 2017.7.1
  f7cfc145a2f3: 2017.7.1
  syndic1: 2017.7.1
  syndic2: 2017.7.1

```
