### ISSUE TITLE
[BUG] 3003.1 salt-run jobs.list_jobs has Target: unknown-target

### ISSUE THREAD

**Issue by oddfellow** [saltstack/salt#48734] opened 2018-07-24 13:05 UTC
### Description of Issue/Question

If I do a `salt "srv-kamptest1" test.version` from the master, wait for successful return and then try to find the job with `salt-run jobs.list_jobs search_function="test.version"` I get:

```
20180724124431069093:
    ----------
    Arguments:
    Function:
        test.version
    StartTime:
        2018, Jul 24 12:44:31.069093
    Target:
        unknown-target
    Target-type:
        list
    User:
        root
```

Here the Target is unknown-target and the Target-type is list which is not correct.
If I do a `salt-call test.version` from the minion, I get the correct job return fields with the jobs runner:

```
20180724125130189347:
    ----------
    Arguments:
    Function:
        test.version
    StartTime:
        2018, Jul 24 12:51:30.189347
    Target:
        srv-kamptest1
    Target-type:
        glob
    User:
        root
```

Without the correct Target field the default job cache is missing very important information because we cannot use `salt-run jobs.list_jobs search_function="test.version" search_target="srv-kamptest1"`

### Setup
Nothing specially configured (only the file_roots and pillar_roots, the dirs itself are empty), standard Debian install with repo.saltstack.com

### Steps to Reproduce Issue
Installed salt-saster 2018.3.2
Installed salt-minion 2018.3.2
configured file_roots and pillar_roots
accepted salt key
ran above commands

### Versions Report
Master:
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.5
         locale: UTF-8
        machine: x86_64
        release: 4.4.110-x86_64-jb1
         system: Linux
        version: debian 9.5
```

Minion: (but happens also with older Linux minions)
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500
64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```

**Comment by rallytime** [comment] 2018-08-03 16:35
This was caused by the changes in #43454.

**Comment by rallytime** [comment] 2018-10-31 16:14
Hi @oddfellow - This should be fixed now with #50328.

**Comment by oddfellow** [comment] 2018-11-01 12:16
Hi @rallytime I applied https://github.com/saltstack/salt/pull/50328/commits/c684c298ffbdcb846a16e32c7f94e44e32e6f81e to a 2018.3.3 master installation and can confirm salt-run now returns the correct values for the test case mentioned above. Thank you!

**Comment by rallytime** [comment] 2018-11-01 13:14
@oddfellow Excellent! Thank you for testing and confirming. :)

**Comment by major0** [comment] 2021-06-28 20:57
This is happening for me when using a non-local master_job_cache on Salt 3003.1

**Comment by sagetherage** [comment] 2021-06-28 21:07
Re-opening to fix this, again. Putting this in `Silicon` but have it unassigned ATM as a stretch goal for the `Silicon` release cycle, if I can find someone to take it I will assign it since it is a regression.

**Comment by waynew** [comment] 2022-03-04 21:12
@major0 I realize it's been a, uh, very long time since then. Do you know if this is still an issue?

**Comment by waynew** [comment] 2022-03-04 22:41
So.... I'm guessing that this is actually a broader problem with returners, and job lookup - similar to how the cache API did not have good high-level tests. I'm going to go ahead and close this issue in favor of a more broad issue, since I'll be fixing all kinds of bugs, including this one, when I get there.

**Closed by waynew** 2022-03-04 22:41 UTC
Labels: Bug, severity-medium, Regression
