### ISSUE TITLE
Installing SALT 3000.1 on CEL7 fails with a dependency to RHEL8 packages exists for CEL7

### ISSUE THREAD

**Issue by sarvi** [saltstack/salt#56588] opened 2020-04-08 21:37 UTC
### Description of Issue
Cannot install SALT 3000.1-1.el7 on a RHEL7 machine.

### Setup
RHEL7
```
-bash-4.2$ uname -a
Linux sjc-wwtl-flxcl2 3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

```

### Steps to Reproduce Issue

Follow instructions at https://repo.saltstack.com/#rhel
Redhat/CentOS 7 PY3
Pin to Latest Release
```
sudo yum install https://repo.saltstack.com/py3/redhat/salt-py3-repo-latest.el7.noarch.rpm
sudo yum clean expire-cache
sudo yum install salt-minion
-bash-4.2$ sudo yum install salt-minion                                                                                                                                                                 
Loaded plugins: fastestmirror, langpacks, merge-conf, priorities, product-id, search-disabled-repos, subscription-manager                                                                               
This system is not registered with an entitlement server. You can use subscription-manager to register.                                                                                                 
Loading mirror speeds from cached hostfile                                                                                                                                                              
Snapshot-nonreboot-Q3FY20                                                                                                                                                        | 2.1 kB  00:00:00     
Snapshot-reboot-Q3FY20                                                                                                                                                           | 2.1 kB  00:00:00     
eman_repo                                                                                                                                                                        | 2.1 kB  00:00:00     
redhat_base                                                                                                                                                                      | 2.1 kB  00:00:00     
redhat_extras                                                                                                                                                                    | 2.3 kB  00:00:00     
redhat_optional                                                                                                                                                                  | 2.4 kB  00:00:00     
redhat_supplementary                                                                                                                                                             | 2.3 kB  00:00:00     
salt-latest                                                                                                                                                                      | 2.9 kB  00:00:00     
salt-py3-3000                                                                                                                                                                    | 3.0 kB  00:00:00     
saltstack                                                                                                                                                                        | 2.9 kB  00:00:00     
13122 packages excluded due to repository priority protections                                                                                                                                          
Resolving Dependencies                                                                                                                                                                                  
--> Running transaction check                                                                                                                                                                           
---> Package salt-minion.noarch 0:2015.5.10-2.el7 will be updated                                                                                                                                       
---> Package salt-minion.noarch 0:3000.1-1.el8 will be an update                                                                                                                                        
--> Processing Dependency: salt = 3000.1-1.el8 for package: salt-minion-3000.1-1.el8.noarch                                                                                                             
--> Running transaction check                                                                                                                                                                           
---> Package salt.noarch 0:2015.5.10-2.el7 will be updated                                                                                                                                              
--> Processing Dependency: salt = 2015.5.10-2.el7 for package: salt-master-2015.5.10-2.el7.noarch                                                                                                       
---> Package salt.noarch 0:3000.1-1.el8 will be an update                                                                                                                                               
--> Processing Dependency: python3.6dist(msgpack) < 1.0.0 for package: salt-3000.1-1.el8.noarch                                                                                                         
--> Processing Dependency: python3-m2crypto >= 0.31.0 for package: salt-3000.1-1.el8.noarch                                                                                                             
--> Processing Dependency: python3-msgpack >= 0.4 for package: salt-3000.1-1.el8.noarch                                                                                                                 
--> Processing Dependency: python3.6dist(msgpack) >= 0.5 for package: salt-3000.1-1.el8.noarch                                                                                                          
--> Processing Dependency: python3.6dist(pyzmq) >= 2.2.0 for package: salt-3000.1-1.el8.noarch                                                                                                          
--> Processing Dependency: python3.6dist(requests) >= 1.0.0 for package: salt-3000.1-1.el8.noarch                                                                                                       
--> Processing Dependency: python3-distro for package: salt-3000.1-1.el8.noarch                                                                                                                         
--> Processing Dependency: python3-jinja2 for package: salt-3000.1-1.el8.noarch                                                                                                                         
--> Processing Dependency: python3-markupsafe for package: salt-3000.1-1.el8.noarch                                                                                                                     
--> Processing Dependency: python3-psutil for package: salt-3000.1-1.el8.noarch                                                                                                                         
--> Processing Dependency: python3-pycurl for package: salt-3000.1-1.el8.noarch                                                                                                                         
--> Processing Dependency: python3-pyyaml for package: salt-3000.1-1.el8.noarch                                                                                                                         
--> Processing Dependency: python3-requests for package: salt-3000.1-1.el8.noarch                                                                                                                       
--> Processing Dependency: python3-six for package: salt-3000.1-1.el8.noarch                                                                                                                            
--> Processing Dependency: python3-zmq for package: salt-3000.1-1.el8.noarch                                                                                                                            
--> Processing Dependency: python3.6dist(jinja2) for package: salt-3000.1-1.el8.noarch                                                                                                                  
--> Processing Dependency: python3.6dist(markupsafe) for package: salt-3000.1-1.el8.noarch                                                                                                              
--> Processing Dependency: python3.6dist(pyyaml) for package: salt-3000.1-1.el8.noarch                                                                                                                  
--> Running transaction check                                                                                                                                                                           
---> Package python3-distro.noarch 0:1.2.0-4.el8 will be installed                                                                                                                                      
---> Package python3-m2crypto.x86_64 0:0.33.0-1.el8 will be installed                                                                                                                                   
--> Processing Dependency: libcrypto.so.1.1(OPENSSL_1_1_0)(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                     
--> Processing Dependency: libcrypto.so.1.1(OPENSSL_1_1_1)(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                     
--> Processing Dependency: libssl.so.1.1(OPENSSL_1_1_0)(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                        
--> Processing Dependency: python3-typing for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                                             
--> Processing Dependency: libcrypto.so.1.1()(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                                  
--> Processing Dependency: libssl.so.1.1()(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                                     
---> Package python3-msgpack.x86_64 0:0.6.1-3.el8 will be installed                                                                                                                                     
---> Package python3-psutil.x86_64 0:5.4.3-8.el8 will be installed                                                                                                                                      
---> Package python3-zmq.x86_64 0:17.0.0-5.el8 will be installed                                                                                                                                        
---> Package salt.noarch 0:3000.1-1.el8 will be an update                                                                                                                                               
--> Processing Dependency: python3.6dist(requests) >= 1.0.0 for package: salt-3000.1-1.el8.noarch                                                                                                       
--> Processing Dependency: python3-jinja2 for package: salt-3000.1-1.el8.noarch                                                                                                                         
--> Processing Dependency: python3-markupsafe for package: salt-3000.1-1.el8.noarch                                                                                                                     
--> Processing Dependency: python3-pycurl for package: salt-3000.1-1.el8.noarch                                                                                                                         
--> Processing Dependency: python3-pyyaml for package: salt-3000.1-1.el8.noarch                                                                                                                         
--> Processing Dependency: python3-requests for package: salt-3000.1-1.el8.noarch                                                                                                                       
--> Processing Dependency: python3-six for package: salt-3000.1-1.el8.noarch                                                                                                                            
--> Processing Dependency: python3.6dist(jinja2) for package: salt-3000.1-1.el8.noarch                                                                                                                  
--> Processing Dependency: python3.6dist(markupsafe) for package: salt-3000.1-1.el8.noarch                                                                                                              
--> Processing Dependency: python3.6dist(pyyaml) for package: salt-3000.1-1.el8.noarch                                                                                                                  
---> Package salt-master.noarch 0:2015.5.10-2.el7 will be updated                                                                                                                                       
---> Package salt-master.noarch 0:3000.1-1.el8 will be an update                                                                                                                                        
--> Processing Dependency: python3-systemd for package: salt-master-3000.1-1.el8.noarch                                                                                                                 
--> Running transaction check                                                                                                                                                                           
---> Package python3-m2crypto.x86_64 0:0.33.0-1.el8 will be installed                                                                                                                                   
--> Processing Dependency: libcrypto.so.1.1(OPENSSL_1_1_0)(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                     
--> Processing Dependency: libcrypto.so.1.1(OPENSSL_1_1_1)(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                     
--> Processing Dependency: libssl.so.1.1(OPENSSL_1_1_0)(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                        
--> Processing Dependency: libcrypto.so.1.1()(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                                  
--> Processing Dependency: libssl.so.1.1()(64bit) for package: python3-m2crypto-0.33.0-1.el8.x86_64                                                                                                     
---> Package python3-typing.noarch 0:3.5.2.2-4.el8 will be installed                                                                                                                                    
---> Package salt.noarch 0:3000.1-1.el8 will be an update                                                                                                                                               
--> Processing Dependency: python3.6dist(requests) >= 1.0.0 for package: salt-3000.1-1.el8.noarch                                                                                                       
--> Processing Dependency: python3-jinja2 for package: salt-3000.1-1.el8.noarch                                                                                                                         
--> Processing Dependency: python3-markupsafe for package: salt-3000.1-1.el8.noarch                                                                                                                     
--> Processing Dependency: python3-pycurl for package: salt-3000.1-1.el8.noarch
--> Processing Dependency: python3-pyyaml for package: salt-3000.1-1.el8.noarch
--> Processing Dependency: python3-requests for package: salt-3000.1-1.el8.noarch
--> Processing Dependency: python3-six for package: salt-3000.1-1.el8.noarch
--> Processing Dependency: python3.6dist(jinja2) for package: salt-3000.1-1.el8.noarch
--> Processing Dependency: python3.6dist(markupsafe) for package: salt-3000.1-1.el8.noarch
--> Processing Dependency: python3.6dist(pyyaml) for package: salt-3000.1-1.el8.noarch
---> Package salt-master.noarch 0:3000.1-1.el8 will be an update
--> Processing Dependency: python3-systemd for package: salt-master-3000.1-1.el8.noarch
--> Finished Dependency Resolution
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3-six
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3-jinja2
Error: Package: python3-m2crypto-0.33.0-1.el8.x86_64 (salt-py3-3000)
           Requires: libssl.so.1.1()(64bit)
Error: Package: python3-m2crypto-0.33.0-1.el8.x86_64 (salt-py3-3000)
           Requires: libcrypto.so.1.1(OPENSSL_1_1_1)(64bit)
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3.6dist(markupsafe)
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3-markupsafe
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3.6dist(jinja2)
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3.6dist(requests) >= 1.0.0
Error: Package: python3-m2crypto-0.33.0-1.el8.x86_64 (salt-py3-3000)
           Requires: libssl.so.1.1(OPENSSL_1_1_0)(64bit)
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3.6dist(pyyaml)
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3-pycurl
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3-pyyaml
Error: Package: salt-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3-requests
Error: Package: salt-master-3000.1-1.el8.noarch (salt-py3-3000)
           Requires: python3-systemd
Error: Package: python3-m2crypto-0.33.0-1.el8.x86_64 (salt-py3-3000)
           Requires: libcrypto.so.1.1(OPENSSL_1_1_0)(64bit)
Error: Package: python3-m2crypto-0.33.0-1.el8.x86_64 (salt-py3-3000)
           Requires: libcrypto.so.1.1()(64bit)
 You could try using --skip-broken to work around the problem

```
(Include debug logs if possible and relevant.)

### Versions Report

Installing Latest SALT 3000.1

**Comment by nicholasmhughes** [comment] 2020-04-13 21:52
@sarvi , it looks like you have multiple Salt repos installed...
```
salt-latest
salt-py3-3000
saltstack
```
Can you disable any that might have conflicting packages and try again?

**Comment by dmurphy18** [comment] 2020-04-13 21:55
@sarvi Please report the listing of directory /etc/yum.repo.d/ and the contents of files starting with  saltxxxxx.repo.  It would appear as @nicholasmhughes has pointed out that you have too many active repositories for Salt and I suspect one of them is for Redhat 8.

**Comment by dmurphy18** [comment] 2021-04-13 16:20
@sarvi Information was requested a year ago on a listing of directory /etc/yum.repo.d/ and the contents of files starting with saltxxxxx.repo, but there has been no response.

If the issue is resolved, please close the issue, or provide requested information or any additional information which would help in resolving this issue.  Thanks in advance.

**Comment by dmurphy18** [comment] 2021-05-03 19:55
If the problem is unresolved, please provide the requested information and re-open the issue and assign it to @sagetherage or @dmurphy18

**Closed by dmurphy18** 2021-05-03 19:55 UTC
Labels: Bug, Packaging, dependency, info-needed, team-core
