### ISSUE TITLE
Salt-SSH file template can't import while SLS can

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#39722] opened 2017-02-28 15:01 UTC
### Description of Issue/Question
It seems Jinja2 Salt-SSH can render SLS files just fine, but is unable to import when it's 'just' rendering a `file.managed` template:

### Setup/Reproduce
Salt-SSH to a Yakkety VM w/Py3 & Py2 installed.

```shell
theloeki@lilarcore:~/project/salt/file_root$ tree
.
├── lib.jinja
├── service
│   ├── docker
│   │   ├── compose.sls
│   │   ├── engine
│   │   │   ├── bin
│   │   │   │   └── dhcpv6-docker-hook.sh.jinja
│   │   │   ├── conf
│   │   │   │   ├── docker_env.jinja
│   │   │   ├── init.sls
│   │   │   ├── map.jinja

```

Offending line:
```jinja2
{%- from 'service/docker/engine/map.jinja' import docker with context %}
```

Works in at least
* `service/docker/engine/init.sls`
* `service/docker/compose.sls`

Is broken in at least:
* `service/docker/engine/bin/dhcpv6-docker-hook.sh.jinja`
* `service/docker/engine/conf/docker_env.jinja`

```
----------
          ID: /etc/default/docker-default
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja error: service/docker/engine/map.jinja
              Traceback (most recent call last):
                File "/var/tmp/.root_d6c9f5_salt/py2/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/var/tmp/.root_d6c9f5_salt/py2/jinja2/environment.py", line 989, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/var/tmp/.root_d6c9f5_salt/py2/jinja2/environment.py", line 754, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 1, in top-level template code
                File "/var/tmp/.root_d6c9f5_salt/py2/salt/utils/jinja.py", line 135, in get_source
                  raise TemplateNotFound(template)
              TemplateNotFound: service/docker/engine/map.jinja
              
              ; line 1
              
              ---
              {%- from 'service/docker/engine/map.jinja' import docker with context %}    <======================
              ###
              ### Docker Environment file
              ###          
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.0               # Actually this is from the git branch
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.5
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12+ (default, Sep 17 2016, 12:08:02)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0
 
System Versions:
           dist: Ubuntu 16.10 yakkety
        machine: x86_64
        release: 4.8.0-39-generic
         system: Linux
        version: Ubuntu 16.10 yakkety
 
```

**Comment by gtmanfred** [comment] 2017-03-01 20:36
This appears to be a duplicate of https://github.com/saltstack/salt/issues/19564

Thanks,
Daniel

**Closed by gtmanfred** 2017-03-01 20:36 UTC
