### ISSUE TITLE
Reactor occasionally fails to run orchestration

### ISSUE THREAD

**Issue by johje349** [saltstack/salt#47608] opened 2018-05-11 09:04 UTC
### Description of Issue/Question
We have reactors configured for salt-cloud events created and destroyed which are used when we create/destroy new hosts during autoscale. They both execute orchestration state. Occasionally this fails, approx 10% of the time. This issue deals with minion-destroyed.sls.

### Setup
Master config:
```
reactor:
  - 'salt/minion/*/start':
    - '/srv/reactor/update-mine.sls'
  - 'salt/cloud/*/created':
    - '/srv/reactor/minion-created.sls'
  - 'salt/cloud/*/destroyed':
    - '/srv/reactor/minion-destroyed.sls'
  - 'salt/state/asx-bidder/deployed':
    - '/srv/reactor/bidder-deployed.sls'
  - 'salt/state/newrelic/finished':
    - '/srv/reactor/update-newrelic.sls'
  - 'salt/state/cassandra/finished':
    - '/srv/reactor/update-cassandra-topology.sls'
  - 'salt/beacon/*/load/':
    - '/srv/reactor/autoscale.sls'

#Set the TTL for the cache of the reactor configuration.
reactor_refresh_interval: 30

#Configure the number of workers for the runner/wheel in the reactor.
reactor_worker_threads: 50

#Define the queue size for workers in the reactor.
reactor_worker_hwm: 100000
```

minion-destroyed.sls
```
startup-orchestration:
  runner.state.orchestrate:
    - args:
        - mods: orchestration.minion-destroyed
        - pillar:
            id: {{ data['name'] }}
```
### Steps to Reproduce Issue
Destroy a VM with salt-cloud

Debug:
```
2018-05-11 10:26:07,110 [salt.loaded.int.fileserver.roots:35  ][TRACE   ][3468] roots: Processing /srv/salt/orchestration/minion-destroyed.sls
2018-05-11 10:26:07,110 [salt.template    :26  ][PROFILE ][3431] Time (in seconds) to render '/srv/pillar/notify.sls' using 'yaml' renderer: 0.00174403190613
2018-05-11 10:26:07,110 [salt.loaded.int.fileserver.roots:35  ][TRACE   ][3468] roots: /srv/salt/orchestration/minion-destroyed.sls is not a link
2018-05-11 10:26:07,111 [salt.loaded.int.fileserver.roots:35  ][TRACE   ][3468] roots: /srv/salt/orchestration/minion-destroyed.sls relative path is orchestration/minion-destroyed.sls
.
.
.
2018-05-11 10:28:26,210 [salt.utils.reactor:103 ][DEBUG   ][3370] Gathering reactors for tag salt/cloud/asx-u19/destroyed
2018-05-11 10:28:26,211 [salt.utils.reactor:203 ][DEBUG   ][3370] Compiling reactions for tag salt/cloud/asx-u19/destroyed
2018-05-11 10:28:26,211 [salt.template    :48  ][DEBUG   ][3370] compile template: /srv/reactor/minion-destroyed.sls
2018-05-11 10:28:26,211 [salt.utils.jinja :65  ][DEBUG   ][3370] Jinja search path: ['/var/cache/salt/master/files/base']
2018-05-11 10:28:26,215 [salt.transport.ipc:35  ][TRACE   ][3369] Client disconnected from IPC /var/run/salt/master/master_event_pull.ipc
2018-05-11 10:28:26,217 [salt.utils.event :35  ][TRACE   ][3370] _get_event() waited 0 seconds and received nothing
2018-05-11 10:28:26,225 [salt.utils.lazy  :97  ][DEBUG   ][3370] LazyLoaded roots.envs
2018-05-11 10:28:26,228 [salt.utils.lazy  :100 ][DEBUG   ][3370] Could not LazyLoad roots.init: 'roots.init' is not available.
2018-05-11 10:28:26,231 [salt.template    :26  ][PROFILE ][3370] Time (in seconds) to render '/srv/reactor/minion-destroyed.sls' using 'jinja' renderer: 0.0193800926208
2018-05-11 10:28:26,231 [salt.template    :115 ][DEBUG   ][3370] Rendered data from file: /srv/reactor/minion-destroyed.sls:
startup-orchestration:
  runner.state.orchestrate:
    - args:
        - mods: orchestration.minion-destroyed
        - pillar:
            id: asx-u19

2018-05-11 10:28:26,234 [salt.loaded.int.render.yaml:76  ][DEBUG   ][3370] Results of YAML rendering:
OrderedDict([('startup-orchestration', OrderedDict([('runner.state.orchestrate', [OrderedDict([('args', [OrderedDict([('mods', 'orchestration.minion-destroyed')]), OrderedDict([('pillar', OrderedDict([('id', 'asx-u19')]))])])])])]))])
2018-05-11 10:28:26,234 [salt.template    :26  ][PROFILE ][3370] Time (in seconds) to render '/srv/reactor/minion-destroyed.sls' using 'yaml' renderer: 0.00309205055237
2018-05-11 10:28:26,282 [salt.utils.process:259 ][DEBUG   ][3370] ThreadPool executing func: <bound method RunnerClient.low of <salt.runner.RunnerClient object at 0x7f58b9aa7210>> with args:('state.orchestrate', {'name': u'startup-orchestration', '__state__': 'runner', 'kwarg': {'pillar': OrderedDict([('id', 'asx-u19')]), 'mods': 'orchestration.minion-destroyed'}, '__id__': 'startup-orchestration', 'arg': (), '__sls__': '/srv/reactor/minion-destroyed.sls', 'order': 1, '__user__': 'Reactor'}) kwargs{}
2018-05-11 10:28:28,035 [salt.utils.event :729 ][DEBUG   ][3370] Sending event: tag = salt/run/20180511102828028497/new; data = {'fun': 'runner.state.orchestrate', 'fun_args': [{'pillar': OrderedDict([('id', 'asx-u19')]), 'mods': 'orchestration.minion-destroyed'}], 'jid': '20180511102828028497', 'user': 'Reactor', '_stamp': '2018-05-11T08:28:28.035585'}
2018-05-11 10:28:28,036 [salt.utils.event :35  ][TRACE   ][3370] _get_event() waited 0 seconds and received nothing
2018-05-11 10:28:28,037 [salt.config      :1960][DEBUG   ][3370] Reading configuration from /etc/salt/master
2018-05-11 10:28:28,037 [salt.utils.event :35  ][TRACE   ][3370] get_event() received = {'tag': 'salt/run/20180511102828028497/new', 'data': {'fun': 'runner.state.orchestrate', 'fun_args': [{'pillar': {'id': 'asx-u19'}, 'mods': 'orchestration.minion-destroyed'}], 'jid': '20180511102828028497', 'user': 'Reactor', '_stamp': '2018-05-11T08:28:28.035585'}}
2018-05-11 10:28:30,564 [salt.utils.lazy  :97  ][DEBUG   ][3370] LazyLoaded jinja.render
2018-05-11 10:28:30,564 [salt.utils.lazy  :97  ][DEBUG   ][3370] LazyLoaded yaml.render
2018-05-11 10:28:30,565 [salt.fileclient  :1070][DEBUG   ][3370] Could not find file 'salt://orchestration/minion-destroyed.sls' in saltenv 'base'
2018-05-11 10:28:30,566 [salt.fileclient  :1070][DEBUG   ][3370] Could not find file 'salt://orchestration/minion-destroyed/init.sls' in saltenv 'base'
2018-05-11 10:28:30,566 [salt.template    :48  ][DEBUG   ][3370] compile template: False
2018-05-11 10:28:30,566 [salt.template    :62  ][ERROR   ][3370] Template was specified incorrectly: False
2018-05-11 10:28:30,567 [salt.utils.lazy  :97  ][DEBUG   ][3370] LazyLoaded local_cache.prep_jid
2018-05-11 10:28:30,568 [salt.utils.event :729 ][DEBUG   ][3370] Sending event: tag = salt/run/20180511102828028497/ret; data = {'fun_args': [{'pillar': OrderedDict([('id', 'asx-u19')]), 'mods': 'orchestration.minion-destroyed'}], 'jid': '20180511102828028497', 'return': {'outputter': 'highstate', 'data': {'asx-salt_master': ["No matching sls found for 'orchestration.minion-destroyed' in env 'base'"]}, 'retcode': 1}, 'success': False, '_stamp': '2018-05-11T08:28:30.568558', 'user': 'Reactor', 'fun': 'runner.state.orchestrate'}
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-121-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

### Workround
Fire the event manually after it fails the first time:
`salt-run event.send salt/cloud/asx-u19/destroyed data='{"name":"asx-u19"}'`

This is not very feasible though as we autoscale 24/7.

Debug:
```
2018-05-11 10:57:24,173 [salt.utils.lazy  :97  ][DEBUG   ][3370] LazyLoaded jinja.render
2018-05-11 10:57:24,174 [salt.utils.lazy  :97  ][DEBUG   ][3370] LazyLoaded yaml.render
2018-05-11 10:57:24,175 [salt.fileclient  :1082][DEBUG   ][3370] In saltenv 'base', looking at rel_path 'orchestration/minion-destroyed.sls' to resolve 'salt://orchestration/minion-destroyed.sls'
2018-05-11 10:57:24,175 [salt.fileclient  :1090][DEBUG   ][3370] In saltenv 'base', ** considering ** path '/var/cache/salt/master/files/base/orchestration/minion-destroyed.sls' to resolve 'salt://orchestration/minion-destroyed.sls'
2018-05-11 10:57:24,176 [salt.template    :48  ][DEBUG   ][3370] compile template: /var/cache/salt/master/files/base/orchestration/minion-destroyed.sls
2018-05-11 10:57:24,176 [salt.utils.jinja :65  ][DEBUG   ][3370] Jinja search path: ['/var/cache/salt/master/files/base']
2018-05-11 10:57:24,188 [salt.utils.lazy  :97  ][DEBUG   ][3370] LazyLoaded roots.envs
2018-05-11 10:57:24,190 [salt.utils.lazy  :100 ][DEBUG   ][3370] Could not LazyLoad roots.init: 'roots.init' is not available.
2018-05-11 10:57:24,199 [salt.utils.lazy  :97  ][DEBUG   ][3370] LazyLoaded match.pcre
2018-05-11 10:57:24,199 [salt.template    :26  ][PROFILE ][3370] Time (in seconds) to render '/var/cache/salt/master/files/base/orchestration/minion-destroyed.sls' using 'jinja' renderer: 0.0228641033173
2018-05-11 10:57:24,199 [salt.template    :115 ][DEBUG   ][3370] Rendered data from file: /var/cache/salt/master/files/base/orchestration/minion-destroyed.sls:

notify-slack:
  salt.function:
    - name: notify.slack
    - tgt: 'asx-salt'
    - arg:
      - "[salt-cloud] Digitalocean droplet destroyed: asx-u19"

update-dns-server:
  salt.function:
    - name: cmd.script
    - tgt: 'asx-salt'
    - arg:
      - salt://scripts/remove_dns_record.sh
    - kwarg:
        args: asx-u19
        shell: /bin/bash

update-known_hosts:
  salt.function:
    - name: cmd.run
    - tgt: 'asx-salt'
    - arg:
      - ssh-keygen -f "/root/.ssh/known_hosts" -R asx-u19

update-hosts:
  salt.function:
    - name: cmd.script
    - tgt: 'not asx-autoscale and not asx-u19'
    - tgt_type: compound
    - arg:
      - salt://scripts/remove_hosts_entry.sh
    - kwarg:
        args: asx-u19
        shell: /bin/bash




update-usersync-haproxy:
  salt.state:
    - tgt: 'asx-lbu*'
    - sls: haproxy
    - queue: True


```

**Comment by johje349** [comment] 2018-05-14 08:35
It's very likely that multiple minions are using the reactor at the same time. Event salt/cloud/*/destroyed  is not sent simultaneously though, but event salt/beacon/*/load/ is sent from minions heavily.

**Comment by johje349** [comment] 2018-05-15 08:02
Do you think downgrade to 2017.7.4 is a workaround?

**Comment by Ch3LL** [comment] 2018-05-15 14:13
yes if the issue is the same as the other the user reported it was working in 7.4. Are you okay closing this issue and monitoring the issue int eh other issue? We have assigned the issue to one of our core engineers so you should be able to monitor it there.

**Comment by johje349** [comment] 2018-05-16 08:10
Yes we can close this one.

**Closed** 2018-05-16 08:10 UTC
Labels: Duplicate, Info Needed
