### ISSUE TITLE
Impossible to define a file.managed for use only as a template in "use" requisites

### ISSUE THREAD

**Issue by tweenk** [saltstack/salt#25423] opened 2015-07-14 21:11 UTC
In the past, I used something like this:
```yaml
root_private:
  file.absent:
    - name: /nonexistent
    - user: root
    - group: root
    - mode: 600
```
and similar states to group parameters which several file states have in common. These states are not intended to define any actual files, only to be used as 'templates' for other states via the `use` directive. This approach was taken from an older version of the Salt manual. It appears there is no way to do this cleanly now - I would need to define a state that creates an actual file somewhere on the filesystem just in order to use it as a template.

I was not able to find any documentation on what is the intended way to migrate this pattern.

**Comment by basepi** [comment] 2015-07-20 18:11
Interesting, this is not a pattern I'm familiar with, but I feel like it should probably still work, even though not many people use `use` these days. In what way is it broken these days?

**Comment by tweenk** [comment] 2015-07-20 21:05
Example:

    root_private:
      file.absent:
        - name: /nonexistent
        - user: root
        - group: root
        - file_mode: 600
        - dir_mode: 700

    /some/file:
      - source: salt://something
      - use:
        - root_private

    /some/other/file:
      - source: salt://other/something
      - use:
        - root_private

This way I don't need to specify the mode, group and owner for every file. It works for now, but warnings say it will cease to work in Salt Carbon, because `file.absent` will error out due to unknown keyword arguments.

Maybe I'm just missing something. Is there a way to define a `file.managed` state that does not actually create any file on the disk, and can be used just for inheritance via `use`? In that case this issue is only about documenting this better, because the current example of `use` does not show how to inherit from an "abstract" state that does not really make any changes in the system.

**Comment by basepi** [comment] 2015-07-23 22:50
Fascinating, now I know what the problem is.

@s0undt3ch this is an interesting use for non-supported keyword args in a state. Apparently we at some point recommended this use in the training manual. Any ideas on a workaround once Carbon comes around and we start hardfailing on non-supported keyword args?

I'm wondering if we can implement some sort of no-op state that accepts kwargs and is perhaps exempt from the non-supported keyword args rule so it can be used for `use` in this way?

**Comment by UtahDave** [comment] 2015-07-23 22:54
Shouldn't that be - file: root_private

?

**Comment by basepi** [comment] 2015-07-23 23:14
Yes, you're right. However, the problem would still remain. We're misusing `file.absent` with unsupported keyword args in order to provide fodder for the `use` requisite. This is scheduled to break in Carbon, when we enforce arg specs.

@s0undt3ch Functions which accept `**kwargs` will be exempt from the hardfail on unsupported kwargs, correct? If that's the case we could create the `no-op` state I mentioned before.

**Comment by tweenk** [comment] 2015-07-24 09:44
@UtahDave that's true, corrected. I was typing this from memory.

**Comment by s0undt3ch** [comment] 2015-07-24 11:16
`use` is marked as an internal keyword so it won't trigger the unsupported keyword arguments warning and won't break once we reach Carbon, and yes, functions which accept `**kwargs` are exempt from the hardfail because there's no way to check for bad usage(it's accepting **all** keyword arguments), but to support what's being asked above, yeah, we would need a `no-op` state which accepted `**kwargs` which could then be used by `use`.

**Comment by basepi** [comment] 2015-07-24 16:16
@s0undt3ch thanks, sir! This should be straightforward to implement, and will not be nearly as hacky as using a file.absent state in this way.

**Comment by whiteinge** [comment] 2015-09-17 22:57
As @basepi mentioned `use` isn't used too often nowadays. It's clunky for the reason you pointed out -- that it requires a template and there is no no-op states. I would be in favor of deprecating `use` (but that's another discussion).

You may prefer this syntax which was introduced in 2014.7:

```yaml
root_private:
  file.absent:
    - names:
      - /some/file:
        - source: salt://something
      - /some/other/file:
        - source: salt://other/something
    - user: root
    - group: root
    - file_mode: 600
    - dir_mode: 700
```

**Comment by basepi** [comment] 2015-09-17 23:25
Added a `test.nop` state in #27208. Between that and @whiteinge's recommendation above, I'm going to call this resolved.

**Closed by basepi** 2015-09-17 23:25 UTC
Labels: Core, Feature, Low-Hanging Fruit, P3
