### ISSUE TITLE
MULTILINE pattern cannot work in file.replace, fileinput always reads line by line.

### ISSUE THREAD

**Issue by regilero** [saltstack/salt#7999] opened 2013-10-21 16:32 UTC
The main problem comes from 
https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L962-964

<pre>
for line in fileinput.input(path,
            inplace=not dry_run, backup=False if dry_run else backup,
            bufsize=bufsize, mode='rb'):
</pre>

Using `salt.states.file.replace` with `flags:  ['DOTALL', 'MULTILINE']`, `bufsize: 'file'` and a pattern like `pattern: start.*end` it is impossible to match any multi-lines as `fileinput.input` is always reading the file line by line, even with bufsize set to the file size.

It seems that fileinput is made for that (http://docs.python.org/2/library/fileinput.html), a line by line read.

Documentation of `salt.modules.file.replace` states:
> Note: multiline searches must specify file as the bufsize argument below.

But this is not enough.

salt version: 0.17.0-1351-g9ba86c7
python version : Python 2.7.4

cc: @kiorky

**Comment by cr1st1p** [comment] 2015-01-25 07:37
Same problem here (2014.7.0). Spent a couple of days only to find out the issue is not with my regexp but with the bogus code when using MULTILINE.

I see the bug is >1 year old and several people mentioned it. Out of courtesy for the users I suggest to at least update the documentation and mention this issue with MULTILINE.

**Comment by alexhayes** [comment] 2015-02-03 00:49
Yep, this bit me also, any update on this?

**Comment by basepi** [comment] 2015-02-03 23:04
Bumped severity.

**Comment by lorengordon** [comment] 2015-03-05 00:32
Tomorrow, I'm planning to start reworking `file.replace` to use `salt.utils.fopen` instead of `fileinput`. Hoping the change will be merged into 2015.2. If anyone can post a good, simple test case for multiline regex, I'll see if I can get this working as well.

**Comment by lorengordon** [comment] 2015-03-05 20:01
I did some more research and testing on this and I believe the problem may be that salt is misinterpreting the meaning of `bufsize` in `fileinput`. The buffer seems to be how much of the file is held in memory at a time...it is *not* how much data is returned in each iteration of the `for` loop. Each `for` loop iteration *always* contains a single line. 

Same goes for the `buffering` parameter in `open()` and `io.open()`. Similarly, the size of the buffer has nothing to do with how much data is returned via the read(), readline(), or readlines() functions. The size of the buffer and the amount of data returned are entirely independent of each other.

This has implications for designing a function that supports both single-line and multi-line search/replace capabilities. I've tried `read()`, `readline()`, and `readlines()` and haven't yet figured out a common method to read a file that will support both options (at least, not with just the information currently passed to `file.replace`). So, it's easy if we create a new `multiline` boolean parameter for `file.replace` and write sub-functions (or `if` statements) to handle both cases. But for the moment, I'm going to hold off on that, as it sounds like something that would go into develop rather than 2015.2. 

If anyone knows otherwise and can explain what's going on, or has any bright ideas on how to provide the desired functionality, I'm all ears.

**Comment by basepi** [comment] 2015-03-10 22:25
@lorengordon did your pull requests over the last couple of weeks fix this issue?

**Comment by lorengordon** [comment] 2015-03-10 22:31
No, my last comment on this thread still applies. I'm not sure how to proceed with this particular issue... I don't know how others are using the `bufsize` parameter, so I may be misunderstanding it myself. But my instinct is to add a new a boolean parameter named `multiline`, and use that to modify how we read and write the file in a way that will support multiline regex.

**Comment by lorengordon** [comment] 2015-03-10 22:32
Alternatively, I suppose we could parse the flags parameter and check if 'MULTILINE' is present...

**Comment by whiteinge** [comment] 2015-03-11 00:02
@lorengordon sorry for the slow reply. You are very correct about the mistake on the `bufsize` parameter. That was my mistake, in fact. :flushed:

The only way to perform a general-purpose multiline search/replace is to read the whole file into memory.  The docs on that function specify "Note: multiline searches must specify file as the bufsize argument below." so the best way to tackle this and maintain backward-compat is to throw a [SaltInvocationError](http://docs.saltstack.com/en/latest/ref/internals/salt.exceptions.html#salt.exceptions.SaltInvocationError) when someone passes the multiline flag in the `flags` param and doesn't specify `file` for the bufsize argument. Then just read in the whole file before performing the search/replace. Ignore `bufsize` otherwise. (It doesn't work as stated and likely isn't being used by anyone because of that. Perhaps there is an optimization we can make sometime down the road with other values supplied to that function.)

**Comment by lorengordon** [comment] 2015-03-11 02:03
Ok, cool. I can maybe play with this next week, if no one else gets to it first.

**Comment by zerthimon** [comment] 2015-05-14 18:21
+1

**Comment by boltronics** [comment] 2015-10-20 07:09
+1 would have saved my afternoon.

**Comment by lorengordon** [comment] 2015-10-22 14:08
Well, it took me 7 months instead of a week to get around to this, but multiline support for file.replace was just merged in.

**Comment by whiteinge** [comment] 2015-10-22 16:07
:raised_hands: woot! @lorengordon thank you very much for fixing that.

**Comment by basepi** [comment] 2015-10-22 18:42
Woooo!

**Closed by basepi** 2015-10-22 18:42 UTC
Labels: Bug, Execution Module, High Severity, P2, Platform

**Comment by boltronics** [comment] 2015-10-22 23:19
:thumbsup: Nice one @lorengordon!

**Comment by zerthimon** [comment] 2015-10-23 10:33
Better late than never.
Thanks!
