### ISSUE TITLE
2015.5.8 GitFS failure on FreeBSD

### ISSUE THREAD

**Issue by sseekamp** [saltstack/salt#27151] opened 2015-09-15 21:50 UTC
Upgrading to 2015.5.8 with a local file:///git/repo backend fails. All dependent modules are installed and the correct versions.

2015-09-15 15:35:44,176 [salt.utils.gitfs                         ][ERROR   ][88389] The git command line utility is required by the Git fileserver backend when using the 'pygit2' provider.
2015-09-15 15:35:44,177 [salt.utils.gitfs                         ][CRITICAL][88389] No suitable gitfs provider module is installed.

**Comment by oogali** [comment] 2015-09-15 23:04
I have the same issue on FreeBSD 10.2.

It looks like the search path is using the default passed from /bin/sh. Not exactly Salt's fault.

My fix was to modify my ```/etc/rc.conf``` and ```/usr/local/etc/rc.d/salt_master``` files to pass a path along to Salt master, similar to how it's done for Salt minions.

**added this to my /etc/rc.conf**
```
salt_master_paths="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
```

**diff of my changes to /usr/local/etc/rc.d/salt_master**
```
# diff -U 1 /usr/local/etc/rc.d/salt_master.orig /usr/local/etc/rc.d/salt_master
--- /usr/local/etc/rc.d/salt_master.orig	2015-09-15 19:01:00.000000000 -0400
+++ /usr/local/etc/rc.d/salt_master	2015-09-15 19:00:05.000000000 -0400
@@ -23,2 +23,3 @@
 : ${salt_master_enable:="NO"}
+: ${salt_master_paths="$PATH"}

@@ -29,2 +30,4 @@

+export PATH="${salt_master_paths}"
+
 run_rc_command "$1"
```

**Comment by sseekamp** [comment] 2015-09-15 23:06
Thanks! I was suspecting something like that, but I couldn’t figure out where to verify or see. I might just add /usr/local/bin to the default path for the server if that’s the case!

Scott

**Comment by oogali** [comment] 2015-09-15 23:21
The root cause of this is the removal of some code that would manipulate the ```PATH``` environment variable if some sensible defaults weren't included.

Here's the code in question that I **do** see in my **2015.5.5** installation (salt/utils/__init__.py, in the ```which``` function):
```
        p = os.environ.get('PATH')
        if p is not None:
            pp = p.split(os.pathsep)
            if '/usr/local/bin' not in pp:
                pp.append('/usr/local/bin')
            if '/usr/local/sbin' not in pp:
                pp.append('/usr/local/sbin')
            os.environ['PATH'] = os.pathsep.join(pp)
```

But that code never existed in Salt, it was a user-submitted patch committed by a FreeBSD ports maintainer, specifically (https://svnweb.freebsd.org/ports/head/sysutils/py-salt/files/patch-salt__utils____init__.py?view=markup&pathrev=314999).

When the port was updated to Salt 2015.8.0, the new committer blew away that snippet of code (https://svnweb.freebsd.org/ports/head/sysutils/py-salt/files/patch-salt__utils____init__.py?r1=387241&r2=396791).

Personally, my opinion is that ports shouldn't be mucking about upstream code if it can be helped.

**Comment by sseekamp** [comment] 2015-09-16 00:06
Agreed!

Good catch. Worth opening a ports PR to notify them to at least out a notice in the install message?

Scott

**Comment by jfindlay** [comment] 2015-09-16 18:11
@sseekamp, @oogali, thanks for the report.

@DmitryKuzmenko, what do you think of the proposed patch above?

**Comment by sseekamp** [comment] 2015-09-19 02:02
@jfindlay I don't know how many other parts of Salt would be affected, but is there an equivalent to something like:

/usr/bin/env git

In Python? That wouldn't require customizing Salt just for FreeBSD's pathing differences?

**Comment by jfindlay** [comment] 2015-09-19 08:38
@sseekamp, right, I don't think we should hardcode paths into `salt.utils.which` except as a backup when no `$PATH` can be found.  It is also conventional that the environment will already provide a `$PATH` to search even without explicitly consulting a utility like `env`.  I would like to learn why FreeBSD is putting git into a path that is not included in the system `$PATH` available to salt.

**Comment by oogali** [comment] 2015-09-21 03:52
@jfindlay OS binaries are shipped in /bin, /usr/bin, /usr/sbin. 3rd-party packages are installed into /usr/local/{bin,sbin}.

FreeBSD ports already provide a method for explicitly passing in a custom PATH to the Salt master. The same method should be extended to the Salt minion service.

Adding @cedwards, the current recent committer of the FreeBSD py27-salt port.

**Comment by DmitryKuzmenko** [comment] 2015-09-21 10:00
@jfindlay sorry, don't kno, why I missed that I've been mentioned here.
I've removed those additional logic from salt.utils.which. It's because configuration of the environment is the task for the OS administrator. No one executable should search executable files outside the PATH specified in the environment where it's run. Another way is to specify binary to be executed with full path to it.

Thus, my answer is:
1. I agree with last @oogali comment, PATH should be configured either system-wide or in init script.
2. Not sure why it's a problem to do this and why environment miss a system binary path by default. For such rare cases when somebody don't want to add a path to program to the PATH, we could introduce a way to specify full PATH to commands in salt config, for instance we could modify salt.utils.which for each call for "program_name" (i.e. 'git') to first perform opts lookup for "program_name_path" (git_path = '/usr/local/bin/git') key. If there is a key, return this value, if not try to resolve via PATH environment.

About 2nd: it's no hard to implement if we **really** need it, but it's have to be approved by responsible core team engineer (@cachedout?)

**Comment by jfindlay** [comment] 2015-09-21 18:43
Thanks for the response here.  It seems that the best solution is to ensure all salt daemons on FreeBSD have the `PATH` modifications provided to the minion service as @oogali indicates.

Optionally we could add an optional option to salt.utils.which to dynamically replace/update `PATH` with a user-supplied value, but this may only encourage users to reinforce badly designed environments rather than fix problems in more formal, conventional ways.

**Comment by cedwards** [comment] 2015-09-21 19:11
I need to submit a patch to the ports tree to address another issue, so I can reinstate the fix to `salt/utils` as mentioned above and we can address it that way.

**Comment by cedwards** [comment] 2015-09-22 15:01
FYI - I'm submitting a patch this morning that allows defining salt minion and salt master paths in the `rc.conf`. This avoids patching upstream code (which I also prefer). I've also added a new RC script for proxy minions.

**Comment by cedwards** [comment] 2015-09-22 15:15
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203262

**Comment by oogali** [comment] 2015-10-14 21:35
I updated my systems, and this is fixed in FreeBSD ports/packages.

**Comment by sseekamp** [comment] 2015-10-14 21:52
Same here! Thanks all!

Scott

**Comment by rallytime** [comment] 2015-10-14 21:54
Awesome! Should we close this one up, @sseekamp?

**Comment by sseekamp** [comment] 2015-10-14 22:52
Yes indeed!

Scott

**Comment by rallytime** [comment] 2015-10-14 23:45
Awesome! Thanks!

**Closed by rallytime** 2015-10-14 23:45 UTC
Labels: Bug, High Severity, P3, Packaging, Platform
