### ISSUE TITLE
AttributeError: 'Minion' object has no attribute 'remove_periodic_callbback'

### ISSUE THREAD

**Issue by tyc1031** [saltstack/salt#54796] opened 2019-09-27 14:37 UTC
Hello,

I ran into this issue while deploying version 2019.2.1, it looks like a simple syntax error with the function call to `remove_periodic_callbback`, accidentally having an extra `b` in the name.

In order to reproduce the bug you need to have the `ping_interval` minion config option set.

The symptoms of the bug result in the minion continuously sending start events 
because it appears to be caught in loop.
```
2019-09-27 14:11:24,344 [salt.minion      :1049][CRITICAL][22765] Unexpected error while connecting to 192.168.1.10
Traceback (most recent call last):
  File "/tmp/tmpkxxemiux/pip3/salt/salt/minion.py", line 1027, in _connect_minion
    minion.tune_in(start=False)
  File "/tmp/tmpkxxemiux/pip3/salt/salt/minion.py", line 2733, in tune_in
    self.remove_periodic_callbback('ping', ping_master)
AttributeError: 'Minion' object has no attribute 'remove_periodic_callbback'
```

Here is a link to the line with the error:
https://github.com/saltstack/salt/blob/46bec3c9d9a8ad1e3ac1f1c4fd0cd5378a136e6f/salt/minion.py#L2733

```
Salt Version:
           Salt: 2019.2.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  9 2019, 16:44:18)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: centos 7.5.1804 Core
         locale: utf-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by dwoz** [comment] 2019-09-27 14:41
duplicate of #54776

**Comment by waynew** [comment] 2019-10-01 20:55
Closing this as it's a duplicate

**Closed by waynew** 2019-10-01 20:55 UTC
Labels: Duplicate
