### ISSUE TITLE
Modules synchronization fails if git backend is enabled with python3 and gitpython

### ISSUE THREAD

**Issue by dosercz** [saltstack/salt#47870] opened 2018-05-29 15:54 UTC
I'm testing salt with python 3 and I have a problem with our custom modules. It was working without any problem with python 2.7. Is there required any changes in config file or is it a bug in salt?

Modules are called e.g. in jinja templates via `salt['x.y'](args)` and salt returns error: `Unable to manage file: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'x.y'`

Sync failed too:
Run:
```
salt-run saltutil.sync_all
```
Output:
```
[ERROR   ] Failed to sync clouds module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync modules module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync states module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync grains module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync renderers module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync returners module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync output module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync proxy module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync runners module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync wheel module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync engines module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync thorium module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync queues module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync pillar module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync utils module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync sdb module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync cache module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync fileserver module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync tops module: string argument expected, got 'bytes'
[ERROR   ] Failed to sync tokens module: string argument expected, got 'bytes'
...

Salt master error log:
[ERROR   ] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1776, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 597, in wrapped
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 752, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python3/dist-packages/salt/fileserver/gitfs.py", line 185, in file_list
    return _gitfs().file_list(load)
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2909, in file_list
    return self._file_lists(load, 'files')
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2886, in _file_lists
    repo_files, repo_symlinks = repo.file_list(load['saltenv'])
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1286, in file_list
    file_blob.stream_data(stream)
  File "/usr/lib/python3/dist-packages/git/objects/base.py", line 119, in stream_data
    stream_copy(istream, ostream)
  File "/usr/lib/python3/dist-packages/git/util.py", line 127, in stream_copy
    destination.write(chunk)
```

### Setup
salt master config for modules:
```
extension_modules: /srv/modules/
```
`/srv/modules` and `/srv/modules/modules` are symlinks to dir with our modules (*.py files)

### Versions Report
Salt minion is on the same server as salt master and in the same version:
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 19 2017, 14:11:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

**Comment by garethgreenaway** [comment] 2018-05-29 16:12
@dosercz I haven't been able to reproduce this particular issue.  Can you provide a copy of your custom module that is seemingly causing the issue?  Another question, do you see the same errors if you don't have the custom module in place?

**Comment by dosercz** [comment] 2018-05-30 10:51
I have same results without any custom modules, so there is no problem in scripts.
I have upgraded salt-master/salt-minion from python2 repo to python3 by changing repo and runing apt-get upgrade + reboot. Are there required any other actions?
Whole salt master config:
```
file_roots:
  base:
    - /srv/salt/files

pillar_roots:
  base:
    - /srv/salt/pillar

fileserver_backend:
  - roots
  - git

gitfs_remotes:
  - https://github.com/xxx/users-formula.git

state_verbose: False

timeout: 600

extension_modules: /srv/modules/
```
/srv/modules/ dir contains empty dirs (cache, clouds, etc.) all owned by root with 700 rights

`salt-run saltutil.sync_modules` returns `[ERROR   ] Failed to sync modules module: string argument expected, got 'bytes'`

**Comment by bergmannf** [comment] 2018-08-27 14:11
I get a related problem it seems: even though for my the `saltutil.sync_modules` call does *not* produce errors but copies the files over:

```
Copying '/var/cache/salt/master/files/base/_modules/mymodule.py' to **'/var/cache/salt/master/extmods/modules/mymodule.py'**
```

However when running an `orchestration` the modules can not be used - even though they are available on the minions in `/var/cache/salt/minion/extmods/modules/`:

```
salt.exceptions.SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'mymodule'
```

I also verified that I can import the module in `python3` by running `import mymodule` and that produces no errors.

**Comment by dmurphy18** [comment] 2018-08-27 15:41
FYI there is a separate version of Salt built to run on Python 3.  Please check then you have the correct version of Salt installed since the dependencies for the version of Salt differ between Python 2.7 and Python 3, for Debian 9, Redhat 7 and Ubuntu 16.04 and 18.04.

@dosercz On the page http://repo.saltstack.com/#debian, the label 'Debian 9 (stretch) PY3' is the correct one to use.

**Comment by dosercz** [comment] 2018-08-27 15:43
@dmurphy18 I have used correct version for PY3

**Comment by dosercz** [comment] 2018-08-29 13:42
I can try it again with the newest version but I have no time to test it right now.

**Comment by bergmannf** [comment] 2018-08-29 13:49
I could fix the problem I had with `salt.exceptions.SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'mymodule'` - the problem was that I had imports between `_modules/*.py` files.

It seems with `python2` this still worked, but in `python3` I had to move the `_module/shared.py` file to `_utils/shared.py` and replace all imports and call-sites with `__utils__['shared.function'](*args, **kwargs)` instead.

For reference the [Utility modules](https://docs.saltstack.com/en/latest/topics/utils/index.html) docs.

**Comment by dosercz** [comment] 2019-03-22 18:48
@dmurphy18 tested with Salt 2019.2.0 on Debian 9.8 and it's still the same :(

**Comment by dosercz** [comment] 2019-03-22 19:16
Problem is caused by fil
``````

**Comment by dosercz** [comment] 2019-03-25 14:32
I have test it more and there is a problem with git backend (in my case gitpython). If git backend is disabled, sync works fine without any problem. I want to try pygit, but current version doesn't work with current salt version, so it's not possible now.
Current version report:
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8
```
Stack trace:
```
salt-master[14828]: TypeError: string argument expected, got 'bytes'
salt-master[14828]: [ERROR   ] Error in function _file_list:
salt-master[14828]: Traceback (most recent call last):
salt-master[14828]:   File "/usr/lib/python3/dist-packages/salt/master.py", line 1838, in run_func
salt-master[14828]:     ret = getattr(self, func)(load)
salt-master[14828]:   File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 666, in wrapped
salt-master[14828]:     return function(*args, **kwargs)
salt-master[14828]:   File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 789, in file_list
salt-master[14828]:     ret.update(self.servers[fstr](load))
salt-master[14828]:   File "/usr/lib/python3/dist-packages/salt/fileserver/gitfs.py", line 185, in file_list
salt-master[14828]:     return _gitfs().file_list(load)
salt-master[14828]:   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2943, in file_list
salt-master[14828]:     return self._file_lists(load, 'files')
salt-master[14828]:   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2920, in _file_lists
salt-master[14828]:     repo_files, repo_symlinks = repo.file_list(load['saltenv'])
salt-master[14828]:   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1311, in file_list
salt-master[14828]:     file_blob.stream_data(stream)
salt-master[14828]:   File "/usr/lib/python3/dist-packages/git/objects/base.py", line 119, in stream_data
salt-master[14828]:     stream_copy(istream, ostream)
salt-master[14828]:   File "/usr/lib/python3/dist-packages/git/util.py", line 127, in stream_copy
salt-master[14828]:     destination.write(chunk)
```
We are using git backend, so I have not found any workaround how to fix it now :(

**Comment by dmurphy18** [comment] 2019-04-01 21:45
Putting this out for others to work on since not an issue for packaging but python3 and gitpython and salt

**Comment by garethgreenaway** [comment] 2019-04-05 20:32
@dosercz I tested pointing a gitfs remote at a Github repository, with gitpython installed, and running sync_all results in the expected behavior.  Is there something in the Git remote that you're using that is perhaps causing the issue?

**Comment by dosercz** [comment] 2019-04-09 12:23
@garethgreenaway I could share there complete salt master config, we are using public repos, so you can try it.
``````

**Comment by dosercz** [comment] 2019-04-09 12:28
We have 2 "extension modules" - /srv/modules/modules/ and /srv/modules/pillar/ are both symlinks to same dir /srv/salt/files/_modules/

**Comment by dahrens** [comment] 2019-07-22 14:10
I encounter something similar when installing a fresh version of salt and gitpython (vagrant provisioning with passing `-x python3` to salt bootstrap) in a `debian/stretch64` box:

```
Passed invalid arguments: string argument expected, got 'bytes'.

Usage:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 1059, in highstate
    initial_pillar=_get_initial_pillar(opts))
  File "/usr/lib/python3/dist-packages/salt/state.py", line 4072, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2937, in __init__
    self.avail = self.__gather_avail()
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2947, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 350, in list_states
    for path in self.file_list(saltenv):
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 1243, in file_list
    else self.channel.send(load)
  File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 906, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 666, in wrapped
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 789, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python3/dist-packages/salt/fileserver/gitfs.py", line 185, in file_list
    return _gitfs().file_list(load)
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2943, in file_list
    return self._file_lists(load, 'files')
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2920, in _file_lists
    repo_files, repo_symlinks = repo.file_list(load['saltenv'])
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1311, in file_list
    file_blob.stream_data(stream)
  File "/usr/local/lib/python3.5/dist-packages/git/objects/base.py", line 119, in stream_data
    stream_copy(istream, ostream)
  File "/usr/local/lib/python3.5/dist-packages/git/util.py", line 124, in stream_copy
    destination.write(chunk)
TypeError: string argument expected, got 'bytes'
```

**Comment by xenadmin** [comment] 2019-08-09 15:05
I recently continued my Salt Master project I left of in January 2019. Debian 9 amd64 , `deb http://repo.saltstack.com/py3/debian/9/amd64/2018.3 stretch main`, python3-git installed, 
```
gitfs_provider: gitpython
fileserver_backend:
  - gitfs
  - roots
```
I did some changes to my public GitHub repo, salt-run fileserver.update and it fails, which it didn't the last time I was working on the project. 
```
root@salt:~# salt-run fileserver.update
Exception occurred in runner fileserver.update: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/runners/fileserver.py", line 352, in update
    fileserver.update(back=backend)
  File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 500, in update
    self.servers[fstr]()
  File "/usr/lib/python3/dist-packages/salt/fileserver/gitfs.py", line 133, in update
    _gitfs().update(remotes)
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2421, in update
    self.find_file
  File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 277, in reap_fileserver_cache_dir
    ret = find_func(filename, saltenv=saltenv)
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2764, in find_file
    blob, blob_hexsha, blob_mode = repo.find_file(repo_path, tgt_env)
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1341, in find_file
    file_blob.stream_data(stream)
  File "/usr/lib/python3/dist-packages/git/objects/base.py", line 119, in stream_data
    stream_copy(istream, ostream)
  File "/usr/lib/python3/dist-packages/git/util.py", line 127, in stream_copy
    destination.write(chunk)
TypeError: string argument expected, got 'bytes'
```
What must I do, to continue my Salt Master project with GitHub repos? I especially rely on the offical formulas. 
```
root@salt:~# salt --versions-report
Salt Version:
           Salt: 2018.3.4
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.9
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9
```

**Comment by dosercz** [comment] 2019-11-19 14:50
This problem is still locking us to python 2.7. I have test it again with salt 2019.2.2. 
I have tried to switch to pygit with python 3.5, but there is a problem, that it requires auth even for our public repos, see error:
```
[ERROR   ] gitfs remote 'https://github.com/w3w/hostsfile-formula.git' requires authentication, but no authentication configured
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1741, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib/python3/dist-packages/pygit2/remote.py", line 375, in fetch
    check_error(err)
  File "/usr/lib/python3/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: authentication required but no callback set
```
and I'm not able to make it working (setting user and password doesn't work too).

**Comment by dosercz** [comment] 2020-01-07 13:15
@garethgreenaway could we solve this issue?

**Comment by dosercz** [comment] 2020-02-06 17:48
@garethgreenaway could we solve this issue?

**Comment by dosercz** [comment] 2020-03-09 10:37
Still problem for us, but it looks like nobody wants to work on it...

**Comment by dosercz** [comment] 2020-04-09 09:10
Still problem for us, but it looks like nobody wants to work on it...

**Comment by dsanader** [comment] 2020-05-14 17:07
The small patch in PR https://github.com/saltstack/salt/pull/54900 fixed a similar issue for us.

**Comment by Ch3LL** [comment] 2023-08-30 19:18
Is this fixed for everyone else here?

**Comment by dosercz** [comment] 2023-08-30 21:07
@Ch3LL we are using newer versions of salt, OS, python... and we don't have this problem anymore. I'm not able to confirm fix at old versions, but IMO we could close that issue.

**Comment by twangboy** [comment] 2023-09-06 17:50
Closing this issue due as it seems to be resolved. Please create a new issue if the problem persists on 3006.2 or later. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!

**Closed by twangboy** 2023-09-06 17:50 UTC
Labels: info-needed, Pending-Discussion
