### ISSUE TITLE
Unable to run salt master on RHEL8 - pygit2 missing

### ISSUE THREAD

**Issue by infantvin** [saltstack/salt#55838] opened 2020-01-10 20:31 UTC
### Description of Issue
We are migrating a salt master from RHEL7 to RHEL8 (Setting up a new RHEL8 host and migrating the master configuration from RHEL7). During this we notice that pygit2 is not available anymore and hence salt-master fails to start.

We tried gitpython, but the pillar configuration absolutely requires pygit2. Hence we are stuck.

EPEL for RHEL8 does not contain pygit2 and neither does the salt repo we used to get the salt binaries. The OS repos dont seem to have these either.

How do we solve the pygit2 package dependency?

Are we supposed to ask Redhat support for this package? Please clarify

### Setup

Saltstack 2019.2.2 on RHEL8.1

### Steps to Reproduce Issue

Install base RHEL 8 OS with updates.
Install salt packages for master and salt-cloud on RHEL8

Try to search and install pygit2 with EPEL repo enabled. This package is nowhere to be found in the repos.

### Versions Report

This is for the salt master.

Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct 11 2019, 15:04:54)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.3.2

System Versions:
           dist: redhat 8.1 Ootpa
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-147.3.1.el8_1.x86_64
         system: Linux
        version: Red Hat Enterprise Linux 8.1 Ootpa

**Comment by Ch3LL** [comment] 2020-01-13 17:13
you should be able to pip install pygit2 for the time being. 


ping @dmurphy18 i believe there was a specific reason as to why we are not packaging pygit2 ourselves. is that correct?

If my understanding is correct you will need to work with redhat to ensure its packaged, but as stated before you can install pygit2 with pip.

**Comment by Anilkris07** [comment] 2020-01-14 06:51
Hi,

As we observe, both the packages are available within the system,
But libgit2 is installed at RPM level, where as the pygit2 is installed at pip level,
We suspect its a issue with integration of this modules.

[root@dehh-dev-salt ~]# yum list installed | grep libgit2
libgit2.x86_64                                     0.26.8-1.el8                                   @rhel-8-for-x86_64-appstream-rpms
[root@dehh-dev-salt ~]# pip3 install --user pygit2
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: pygit2 in /usr/local/lib64/python3.6/site-packages
Requirement already satisfied: cffi in /usr/lib64/python3.6/site-packages (from pygit2)
Requirement already satisfied: pycparser in /usr/lib/python3.6/site-packages (from cffi->pygit2)
[root@dehh-dev-salt ~]#

**Comment by infantvin** [comment] 2020-01-14 13:17
Hi @Ch3LL 

Like my colleague has commented,  we tried to install pygit2 using pip3 (in RHEL8) and it shows in the pip3 list as installed.

Output as shown below

# pip3 list|grep pygit2
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pygit2 (1.0.1)

Libgit2 is also installed as a rpm package 

# rpm -q libgit2
libgit2-0.26.8-1.el8.x86_64

We are not able to get the rpm package for pygit2 in RHEL8 (Not sure if it is available as I cannot find any documentation on that)

We suspect that salt is unable to use the pip installed pygit2 module as it shows the messages as below in the system log during startup and fails.

salt-master[32468]: [ERROR   ] git_pillar is configured but could not be loaded, are pygit2 and libgit2 installed?
salt-master[32468]: [ERROR   ] GitPython is installed, you may wish to set git_pillar_provider to 'gitpython' to use GitPython for git_pillar support.
salt-master[32468]: [CRITICAL] No suitable git_pillar provider module is installed.
salt-master[32468]: [CRITICAL] Failed to load git_pillar
salt-master[32468]: [CRITICAL] Master failed pre flight checks, exiting

Please let us know if you need any more information regarding this.

Thanks

**Comment by mcarlton00** [comment] 2020-02-05 21:16
Confirming, I'm also seeing this.

It seems to be a python path issue.  On CentOS 8, the salt master doesn't seem to be looking in `/usr/local/` for packages, which is where pip installs things to.  Also note that the salt master is using `/usr/libexec/platform-python`, not `/usr/bin/python3` like you might expect, but they're symlinked together so that's not a problem.

Salt Master 2019.2.3
```python
[vagrant@localhost init.d]$ sudo /usr/bin/salt-master
> /usr/lib/python3.6/site-packages/salt/__init__.py(12)<module>()
-> warnings.filterwarnings(
(Pdb) import sys
(Pdb) pp sys.path
['/usr/bin',
 '/usr/lib64/python36.zip',
 '/usr/lib64/python3.6',
 '/usr/lib64/python3.6/lib-dynload',
 '/usr/lib64/python3.6/site-packages',
 '/usr/lib/python3.6/site-packages']
```
```python
[vagrant@localhost salt]# /usr/libexec/platform-python
Python 3.6.8 (default, Oct  7 2019, 17:58:22)
[GCC 8.2.1 20180905 (Red Hat 8.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> from pprint import pprint
>>> pprint(sys.path)
['',
 '/usr/lib64/python36.zip',
 '/usr/lib64/python3.6',
 '/usr/lib64/python3.6/lib-dynload',
 '/usr/local/lib64/python3.6/site-packages',
 '/usr/local/lib/python3.6/site-packages',
 '/usr/lib64/python3.6/site-packages',
 '/usr/lib/python3.6/site-packages']
```

Root cause is the way python is being called from the executables themselves.  Both `/usr/bin/salt` and `/usr/bin/salt-master` are calling python with the `-s` argument.

```
[vagrant@localhost ~]$ head -n1 /usr/bin/salt
#!/usr/libexec/platform-python
```
```
[vagrant@localhost ~]$ /usr/libexec/platform-python -h
..................
-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE
..................
```

I'm not sure why this was done, but it's explicitly disallowing packages that have been pip installed.  @Ch3LL

**Comment by mcarlton00** [comment] 2020-02-05 21:36
It looks like this may have already been fixed here: https://github.com/saltstack/salt-pack-py3/pull/175 but hasn't been released yet

**Comment by Ch3LL** [comment] 2020-02-10 15:57
thanks for pointing to that @mcarlton00 

@dmurphy18 can you confirm what releases users can expect this new fix to be included in with the packages?

**Comment by mcarlton00** [comment] 2020-02-11 21:46
Looks like the `-s` has already been removed in current versions with Salt 3000.  Just tested and doing `/usr/libexec/platform-python -m pip install pygit2` does result in it showing up in `salt --versions` now.  I haven't had a chance to test full functionality yet

**Comment by Ch3LL** [comment] 2020-02-19 14:43
perfect thanks for confirming. i'll go ahead and close this, but let me know if needs to be re-opened

**Closed by Ch3LL** 2020-02-19 14:43 UTC
Labels: Pending Discussion
