### ISSUE TITLE
[TEST FAILURE] Ubuntu 18.04

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#60319] opened 2021-06-07 15:25 UTC
Please paste the link from the specific build where the failure first started:

https://jenkins.saltproject.io/job/pr-ubuntu-1804-amd64-py3-pytest-slow/job/master/224/

tests.pytests.functional.transport.zeromq.test_pub_server_channel.test_publish_to_pubserv_ipc

```
tests/pytests/functional/transport/zeromq/test_pub_server_channel.py:212: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <PubServerChannelProcess(PubServerChannelProcess-43, started)>

    def __enter__(self):
        self.start()
        self.collector.__enter__()
        attempts = 30
        while attempts > 0:
            self.publish({"tgt_type": "glob", "tgt": "*", "jid": -1, "start": True})
            if self.collector.running.wait(1) is True:
                break
            attempts -= 1
        else:
>           pytest.fail("Failed to confirm the collector has started")
E           Failed: Failed to confirm the collector has started

attempts   = 0
self       = <PubServerChannelProcess(PubServerChannelProcess-43, started)>

tests/pytests/functional/transport/zeromq/test_pub_server_channel.py:183:
```

This seems to be an intermittent failure. It seemed pretty stable up until these commits: 
e3c52e5fba7e2cbb1126ea784ce60f65fcb59254 : volumes on stopped pools in virt.vm_info
a8d72d06cedb14eaa5e41efbfa651c4a5a0931f9 : redis docs
4f49389e6d09d746221b02ba45a5acca0691fd4e : Fix problematic test on Windows (IPC) <============== Probably this one

**Comment by twangboy** [comment] 2021-06-07 17:03
I ran this test 50 times on my local VM and saw it fail one time.
```
nox -e 'pytest-zeromq-3(coverage=False)' -- -vvv --run-slow --run-destructive tests/pytests/functional/transport/zeromq/test_pub_server_channel.py
```

**Comment by nicholasmhughes** [comment] 2022-04-26 12:22
Looks like this unreproducible error was moved to Done on the board. Closing at this time.

**Closed by nicholasmhughes** 2022-04-26 12:22 UTC
Labels: Test-Failure
