### ISSUE TITLE
salt-run fileserver.update

### ISSUE THREAD

**Issue by steinliber** [saltstack/salt#39679] opened 2017-02-27 06:36 UTC
### Description of Issue/Question
When I run salt-run fileserver.update , return 

```
Exception occurred in runner fileserver.update: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 399, in _low
    if 'data' in data['return']:
TypeError: argument of type 'bool' is not iterable
```

I print the data and get the data  dict is 

`
{'fun_args': [], 'jid': '20170227143256493414', 'return': True, 'success': True, '_stamp': '2017-02-27T06:32:56.881725', 'user': 'root', 'fun': 'runner.fileserver.update'}
`

### Versions Report
Salt: 2016.11.2

**Comment by gtmanfred** [comment] 2017-02-27 16:27
this is a duplicate of https://github.com/saltstack/salt/issues/38638 and will be fixed in 2016.11.3

**Closed by gtmanfred** 2017-02-27 16:27 UTC
