### ISSUE TITLE
Run salt-call pkg.upgrade fromrepo=base failed

### ISSUE THREAD

**Issue by qiuchengxuan** [saltstack/salt#46457] opened 2018-03-09 07:35 UTC
### Description of Issue/Question
run salt-call pkg.upgrade fromrepo=base failed

In file yumpkg.py:1528, arguments are passed expanded:
```
repo_arg = _get_repo_options(**kwargs)
```
so in line 212, kwargs.pop won't affect caller kwargs
```
    # Get repo options from the kwargs
    fromrepo = kwargs.pop('fromrepo', '')
    repo = kwargs.pop('repo', '')
    disablerepo = kwargs.pop('disablerepo', '')
    enablerepo = kwargs.pop('enablerepo', '')
```
fromrepo are still passed as extra yum argument
```
extra_args = _get_extra_options(**kwargs)
```

### Setup
Just start salt-master and salt-minion

### Steps to Reproduce Issue
salt-call pkg.upgrade fromrepo=base

### Versions Report
Salt Version:
           Salt: 2016.11.9

**Comment by Ch3LL** [comment] 2018-03-09 16:26
Whats the error your seeing?

**Comment by ixs** [comment] 2018-03-09 22:27
Tried reproducing the problem. Succeeded. The code calls yum with a --fromrepo parameter which does not actually exist.

`# salt-call pkg.upgrade fromrepo=base
[ERROR   ] Command '['systemd-run', '--scope', 'yum', '--quiet', '-y', '--disablerepo=*', '--enablerepo=base', "--fromrepo='base'", 'upgrade']' failed with return code: 1
[ERROR   ] stdout: Usage: yum [options] COMMAND

List of Commands:

check          Check for problems in the rpmdb
check-update   Check for available package updates
clean          Remove cached data
deplist        List a package's dependencies
distribution-synchronization Synchronize installed packages to the latest available versions
downgrade      downgrade a package
erase          Remove a package or packages from your system
fs             Acts on the filesystem data of the host, mainly for removing docs/lanuages for minimal hosts.
fssnapshot     Creates filesystem snapshots, or lists/deletes current snapshots.
groups         Display, or use, the groups information
help           Display a helpful usage message
history        Display, or use, the transaction history
info           Display details about a package or group of packages
install        Install a package or packages on your system
list           List a package or groups of packages
load-transaction load a saved transaction from filename
makecache      Generate the metadata cache
provides       Find what package provides the given value
reinstall      reinstall a package
repo-pkgs      Treat a repo. as a group of packages, so we can install/remove all of them
repolist       Display the configured software repositories
search         Search package details for the given string
shell          Run an interactive yum shell
swap           Simple way to swap packages, instead of using shell
update         Update a package or packages on your system
update-minimal Works like upgrade, but goes to the 'newest' package match which fixes a problem that affects your system
updateinfo     Acts on repository update information
upgrade        Update packages taking obsoletes into account
version        Display a version for the machine and/or available repos.
[ERROR   ] stderr: Running scope as unit run-29938.scope.
Command line error: no such option: --fromrepo
[ERROR   ] retcode: 1
Error running 'pkg.upgrade': Problem encountered upgrading packages. Additional info follows:

changes:
    ----------
result:
    ----------
    pid:
        29938
    retcode:
        1
    stderr:
        Running scope as unit run-29938.scope.
        Command line error: no such option: --fromrepo
    stdout:
        Usage: yum [options] COMMAND

        List of Commands:

        check          Check for problems in the rpmdb
        check-update   Check for available package updates
        clean          Remove cached data
        deplist        List a package's dependencies
        distribution-synchronization Synchronize installed packages to the latest available versions
        downgrade      downgrade a package
        erase          Remove a package or packages from your system
        fs             Acts on the filesystem data of the host, mainly for removing docs/lanuages for minimal hosts.
        fssnapshot     Creates filesystem snapshots, or lists/deletes current snapshots.
        groups         Display, or use, the groups information
        help           Display a helpful usage message
        history        Display, or use, the transaction history
        info           Display details about a package or group of packages
        install        Install a package or packages on your system
        list           List a package or groups of packages
        load-transaction load a saved transaction from filename
        makecache      Generate the metadata cache
        provides       Find what package provides the given value
        reinstall      reinstall a package
        repo-pkgs      Treat a repo. as a group of packages, so we can install/remove all of them
        repolist       Display the configured software repositories
        search         Search package details for the given string
        shell          Run an interactive yum shell
        swap           Simple way to swap packages, instead of using shell
        update         Update a package or packages on your system
        update-minimal Works like upgrade, but goes to the 'newest' package match which fixes a problem that affects your system
        updateinfo     Acts on repository update information
        upgrade        Update packages taking obsoletes into account
        version        Display a version for the machine and/or available repos.`

The yum error is `Command line error: no such option: --fromrepo`.

**Comment by qiuchengxuan** [comment] 2018-03-10 09:09
Thanks for @ixs for reproducing, but I'm directly pointing out where this issue come from in code level, so how to fix this is straightforward.
one solution is replace
`repo_arg = _get_repo_options(**kwargs)`
with
`repo_arg = _get_repo_options(kwargs)`

**Comment by ixs** [comment] 2018-03-11 19:36
@qiuchengxuan once one sees the error, the problem becomes clear.
This was more for @Ch3LL to satisfy the NEEDINFO tag.

**Comment by Ch3LL** [comment] 2018-03-12 15:34
@qiuchengxuan seems you have a grasp for a solution, mind submitting a PR?

@ixs thanks for the additional information :)

**Comment by ixs** [comment] 2019-06-25 21:01
Issue probably still applicable.

**Comment by whytewolf** [comment] 2023-08-30 18:20
closing this, since the function mentioned doesn't exist anymore `_get_repo_options`. If the behavior is still happening in 3006.x please open a new ticket as we have to reevaluate what is happening.

**Closed by whytewolf** 2023-08-30 18:20 UTC
Labels: Bug, severity-medium
