### ISSUE TITLE
Add spawn-and-forget cmd module function for background tasks

### ISSUE THREAD

**Issue by quantum-x** [saltstack/salt#6691] opened 2013-08-14 11:00 UTC
Hey guys.
I have a command that eventually gets pushed into the background:

```
[simon@staging_www1 ~]$ /usr/bin/php /var/www/toyfoundry/app/console --env=prod bcc:resque:worker-start emailqueue
Starting worker nohup php  /var/www/toyfoundry/app/../vendor/chrisboulton/php-resque/resque.php > /var/www/toyfoundry/app/logs/resque.log 2>&1 & echo $!
Worker started staging_www1.toyfoundry.net:27985:emailqueue
```

When running via salt though:
```
salt staging_www1.toyfoundry.net cmd.retcode "/usr/bin/php /var/www/toyfoundry/app/console --env=prod bcc:resque:worker-start emailqueue"
```
It hangs - presumably because the thread dropped to the background.
cmd.retcode does the same thing.

How can I get salt to detatch?

**Comment by frvge** [comment] 2015-01-05 16:33
Can we also have this as a state?

**Comment by basepi** [comment] 2015-01-05 23:09
Adding a state on top should be super straightforward.

**Comment by frvge** [comment] 2015-01-19 18:20
I've "solved" my issue (calling a command via the cmd.run state where the command has an & in it), by creating a service and using the service state.

**Comment by lrhazi** [comment] 2015-07-23 03:19
this looks pretty simple, but not in current release yet, right? or am I misunderstanding?

**Comment by basepi** [comment] 2015-07-23 23:10
@lrhazi Correct, this is not yet implemented, the issue is still open.

**Comment by sastorsl** [comment] 2015-11-16 09:27
Any movement on this issue?
I would expect cmd.run to hang around and gather all feedback until the process drops to the background like you would for many servers when they start.

**Comment by basepi** [comment] 2015-11-16 23:50
No movement on this. Note that this should be fairly straightforward, so if someone wants to take a whack at it, I'm happy to provide guidance. We just haven't had time yet.

**Comment by The-Loeki** [comment] 2015-11-23 12:44
@basepi; you might've found your whacker here ;)

In essence I think the following should happen:
* add `wait=True` (or `async=False` or whatever) to the functions in `cmdmod`
* in order to non-block:
  - `['stdin', 'stdout', 'stderr', 'with_communicate'] all need to be `None` or `False`,
  - `salt.utils.timed_subprocess` shouldn't invoke `Popen`'s `wait()`

Those are the easy parts if you ask me.

The hairy parts from the top of my head:
* We're now calling upon `salt.utils.timed_subprocess` to `wait()` for a subprocess that's neither timed nor waiting...
* Any I/O would be out of the window; no way to catch retcode/exit status/stderr/stdin anymore that I can think of except for very hacky send events/job status or similar afterwards

Ideas? Or do we consider the above issues no issues in favour of the enhancement?

**Comment by basepi** [comment] 2015-11-25 00:15
I think when you fire and forget, you definitely have to sign off on never receiving the results of the job. If you need the results, you need to wait for them, right?

I would say ignore those issues for the moment and if they bite us further down we can address them then.

**Comment by jfindlay** [comment] 2016-03-08 21:59
This has implemented in #29964.  Can anyone confirm that this works as expected?

**Comment by The-Loeki** [comment] 2016-03-08 22:04
```
[root@salt01 ~]# salt-call cmd.run_bg 'sleep 180' 
[INFO    ] Determining pillar cache
[ERROR   ] Invalid output_loglevel 'None'. Valid levels are: quiet, critical, error, warning, info, profile, debug, trace, garbage, all. Falling back to 'info'.
[INFO    ] Executing command 'sleep 180' in directory '/root'
local:
    ----------
    pid:
        7801
[root@salt01 ~]# ps fuax |grep 7801
root      7974  0.0  0.0 112644   964 pts/2    S+   23:04   0:00      \_ grep --color=auto 7801
root      7801  0.0  0.0   4312   360 pts/2    S    23:03   0:00 sleep 180
```

I'm a bit confused though regarding the loglevel warning; wasn't there before

**Comment by cachedout** [comment] 2016-03-18 18:45
Given that we have this in, I'm going to go ahead and close this. If the log level issue is something that needs to be looked at further, please open another issue and we'll track it there. Thanks.

**Closed by cachedout** 2016-03-18 18:45 UTC
Labels: Feature, Fixed Pending Verification, Help Wanted, P1, Platform

**Comment by colegatron** [comment] 2017-11-24 14:20
I see it is closed, but maybe can help someone.
If the requirement is just run something in the background I accomplish it with the following command.

sudo salt "*" cmd.run 'echo "mycommand&" | at now + 1 minute'

Although of course you don't get return code for the command executed.

**Comment by taverentech** [comment] 2017-12-08 07:01
Its not really that complicated.  This example works just fine:
  cmd.run:
    - name: '/usr/bin/mongodb_exporter -log_dir {{ log_dir }} > {{ log_dir }}/exporter.log 2>&1 &'
    - unless: 'curl --silent http://localhost:9001/metrics'

nohup doesn't work, neither does specifying log.   you *MUST* redirect both STDOUT and STDERR to file and background and it will background and move on.... ie you have to add this to your cmd.run:
     > /logdir/logfile 2>&1 &

**Comment by The-Loeki** [comment] 2017-12-08 11:15
@colegatron & @taverentech I added the `cmd.run_bg` option in PR #29964:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run_bg

Solving both your use cases no?
