### ISSUE TITLE
Reactor triggered by cloud/*/created fails to execute on minion

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#29290] opened 2015-11-30 22:53 UTC
I've been chasing this for several days and am coming to the conclusion that it does not work.

I am trying to trigger the following state file from a <code>'salt/cloud/*/created'</code> event. 

On the master, I see the reactor properly rendered in the master logfile, I see the following state file rendered. 

On the minion, in a debug logfile I see no indication that the minion was contacted by this reactor.

In an IRC conversation, it has been suggested that this cannot dependably work and that there is no way to assure that the master can communicate with the minion when this event is triggered.

However, in the documentation, I see a nearly identical example of this goal with comments stating that the " a minion fires an event when it is able to receive commands". The doc here: https://docs.saltstack.com/en/latest/topics/cloud/reactor.html#example-reactor-based-highstate

So either I am doing something wrong in this state file or there is a bug, or the doc needs to be updated. Not sure which. I appreciate any help sorting this out.

Running on salt version 2015.8.1 on both master and minion with minion being a Windows instance on EC2.

```yaml
minion_sync_all:
  local.saltutil.sync_all:
    - tgt: {{ data['name'] }}
    - refresh: True

minion_mine_update:
  local.mine.update:
    - tgt: {{ data['name'] }}
    - require:
      - local: minion_sync_all

minion_refresh_pillar:
  local.saltutil.refresh_pillar:
    - tgt: {{ data['name'] }}
    - require:
      - local: minion_mine_update

refresh_pkg_db:
  cmd.pkg.refresh_db:
    - tgt: {{ data['name'] }}
    - require:
      - local: minion_refresh_pillar

install_required_windows_minion_software:
  cmd.state.sls:
    - name: common.windows
    - tgt: {{ data['name'] }}
    - require:
      - cmd: refresh_pkg_db

highstate_run:
  cmd.state.highstate:
    - tgt: {{ data['name'] }}
    - require:
      - cmd: install_required_windows_minion_software
```

**Comment by basepi** [comment] 2015-12-01 20:35
So in the master debug log, do you see the master pubbing the commands to the minions? You should see pubs for saltutil.sync_all, mine.update, etc. I just want to double check your good detective work to make sure it is in fact an issue of the minion not being ready to receive commands. But as far as I can tell you're completely right, this should work.

Oh, and also please add your reactor config for completeness.

**Comment by rterbush** [comment] 2015-12-01 21:57
@basepi 

Snippet from the minion logfile. I believe this shows the pubbing action you requested.
```
2015-12-01 14:27:33,088 [salt.utils.lazy  ][DEBUG   ][1644] LazyLoaded config.get
2015-12-01 14:27:33,088 [salt.loaded.int.render.yaml][DEBUG   ][1644] Results of YAML rendering: 
OrderedDict([('include', ['common.windows']), ('minion_sync_all', OrderedDict([('module.run', [OrderedDict([('name', 'saltutil.sync_all')]), OrderedDict([('refresh', True)])])])), ('minion_mine_update', OrderedDict([('module.run', [OrderedDict([('name', 'mine.update')])])])), ('minion_refresh_pillar', OrderedDict([('module.run', [OrderedDict([('name', 'saltutil.refresh_pillar')])])]))])
2015-12-01 14:27:33,094 [salt.fileclient  ][DEBUG   ][1644] Could not find file from saltenv 'base', u'salt://common/windows.sls'
2015-12-01 14:27:33,106 [salt.fileclient  ][DEBUG   ][1644] In saltenv 'base', looking at rel_path u'common/windows/init.sls' to resolve u'salt://common/windows/init.sls'
2015-12-01 14:27:33,107 [salt.fileclient  ][DEBUG   ][1644] In saltenv 'base', ** considering ** path u'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\common\\windows\\init.sls' to resolve u'salt://common/windows/init.sls'
2015-12-01 14:27:33,107 [salt.fileclient  ][INFO    ][1644] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://common/windows/init.sls'
2015-12-01 14:27:33,107 [salt.template    ][DEBUG   ][1644] compile template: c:\salt\var\cache\salt\minion\files\base\common\windows\init.sls
2015-12-01 14:27:33,108 [salt.utils.jinja ][DEBUG   ][1644] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
2015-12-01 14:27:33,139 [salt.template    ][DEBUG   ][1644] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\common\windows\init.sls:
install_windows_updates:
  win_update.installed:
    - categories:
      - 'Updates'
      - 'Critical Updates'
      - 'Security Updates'

--snip--
```

**Comment by basepi** [comment] 2015-12-01 22:35
It actually didn't. Could you gist a larger portion of the logs? The stuff I'm looking for will be after all of the rendering of the reactor SLS file.

**Comment by rterbush** [comment] 2015-12-02 03:24
I'll need to recreate this as I am not confident in the logfile I have in my possession. I'll get back to you on this over coming days as I am traveling for the next few. Tks

**Comment by rallytime** [comment] 2015-12-14 20:42
@rterbush I was just going through a bunch of these issues today and I think you're actually hitting a race condition here which is is a duplicate of #29249. As such, I am going to close this issue so we can track that bug in one place.

One thing that you could try in the mean time is to use the minion `start` event instead of the cloud `created` event. 

Use a jinja if statement to set a variable to switch the `data['id']` and `data['name']` values in your sls files to be able to use the start event seamlessly with salt cloud, as discussed at the end of #29290.

**Closed by rallytime** 2015-12-14 20:42 UTC
Labels: Bug, High Severity, P2, RIoT
