### ISSUE TITLE
service.running state does not respect package requirement

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#34171] opened 2016-06-21 14:01 UTC
### Description of Issue/Question

The following state can't be run in the test mode:

```
dbus:
  pkg:
    - installed
  service.running:
    - require:
        - pkg: dbus
```

It fails like this:

```
[ERROR   ] The named service dbus is not available
local:
----------
          ID: dbus
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: dbus
     Started: 13:53:27.894208
    Duration: 4293.316 ms
     Changes:
----------
          ID: dbus
    Function: service.running
      Result: False
     Comment: The named service dbus is not available
     Started: 13:53:32.188325
    Duration: 108.61 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    1
------------
Total states run:     2
```

Unsurprisingly, it works as expected when not in dry run mode.

I made a docker image to replicate this easily:

```
docker build -t salt --build-arg SALT_VERSION=2016.3 https://gist.githubusercontent.com/bobrik/a7972c4cc9d8232f6b1ba9a0dff3a2cc/raw/e05680118cc9cd1703e27faf2017a8291d599493/Dockerfile && docker run --rm -it salt salt-call --local state.sls test test=true
```

The issue here is that `service.running` checks for available services when the required package is not yet installed, which is the case for all packages that have service file in them.

If there is a way to test this nicely, it should be documented. If there is no way to do this (which is sad), it should also be noted in `service` state docs.

* https://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html

### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.1.19-boot2docker
         system: Linux
        version: debian 8.4
```

**Comment by lorengordon** [comment] 2016-06-21 14:43
related: https://github.com/saltstack/salt/issues/34019

**Comment by Ch3LL** [comment] 2016-06-21 17:57
@bobrik as @lorengordon stated I believe this might be a duplicate of the issue he posted. Essentially this is not working because that package is not installed yet so the test=True check fails. Are you okay to track improvement to test=True to that issue instead?

**Comment by bobrik** [comment] 2016-06-21 18:25
As long as the following is addressed, I'm fine with having one issue to track it:

> If there is a way to test this nicely, it should be documented. If there is no way to do this (which is sad), it should also be noted in service state docs.

I think my case is easier to understand (much simpler reproducible state). Feel free to merge these issues.

**Comment by Ch3LL** [comment] 2016-09-21 22:07
Thanks will close this one and comment on other issue pointing someone to this issue thanks

**Closed by Ch3LL** 2016-09-21 22:07 UTC
Labels: Core, Duplicate, Feature
