### ISSUE TITLE
[BUG] jobs.list_job returns all minions when using compound

### ISSUE THREAD

**Issue by tomadmiraal** [saltstack/salt#62588] opened 2022-08-31 09:22 UTC
**Description**
When I request a job by using match compound, it looks like the salt master is trageting all the minions.

for example

```
salt -C 'mgmt* or web*' test.ping
```

The minions that shouldn't be targeted will response with

```
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831090110814351
```

When I request the job details by using "salt-run jobs.list_job 20220831090110814351" it will return a list of ALL minions and not only the targeted once.

In version 3004.1 it was returning al list of targeted minions. 3004.2 and newer is returning all minions (tested both 3004.2 and 3005).

the request without match compound is working as expected
```
salt 'mgmt*' **test.ping**
```

also the jobs.list_job will return a list of targeted minions

**Setup**
salt --versions-report
```
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-125-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

**Steps to Reproduce the behavior**
for example:

```salt -C 'mgmt* or web*' test.ping```

will return all minions with errors on the non-targeted minions

```salt 'mgmt*' test.ping```

will return the targeted minions with correct response.

example with debug log:
```
salt -C 'mgmt* or web*' test.ping -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: han2
[DEBUG   ] Missing configuration file: /root/.saltrc
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: han2
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] compound resolution: original tgt: mgmt* or web*
[DEBUG   ] compound resolution: new_tgt: ['mgmt*', 'or', 'web*']
[DEBUG   ] Closing AsyncReqChannel instance
[DEBUG   ] The functions from module 'local_cache' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/38/0c8cdca2df78beb4dd3d54635265e3e2c625e135cb468a9913416c03762c22/.minions.p
[DEBUG   ] get_iter_returns for jid 20220831091745135871 sent to {'web02.mydomain.com', 'mgmt01.mydomain.com', 'db01.mydomain.com', 'db03.mydomain.com', 'runner01.mydomain.com', 'web01.mydomain.com', 'salt.mydomain.com', 'es03.mydomain.com', 'es02.mydomain.com', 'pve02.mydomain.com', 'es01.mydomain.com', 'dev04.mydomain.com', 'dev01.mydomain.com', 'dev02.mydomain.com', 'dev03.mydomain.com', 'db02.mydomain.com'} will timeout at 11:18:05.144000
[DEBUG   ] jid 20220831091745135871 return from web02.mydomain.com
[DEBUG   ] return event: {'web02.mydomain.com': {'ret': True, 'retcode': 0, 'jid': '20220831091745135871'}}
[DEBUG   ] The functions from module 'nested' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded nested.output
web02.mydomain.com:
    True
[DEBUG   ] jid 20220831091745135871 return from mgmt01.mydomain.com
[DEBUG   ] return event: {'mgmt01.mydomain.com': {'ret': True, 'retcode': 0, 'jid': '20220831091745135871'}}
[DEBUG   ] The functions from module 'nested' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded nested.output
mgmt01.mydomain.com:
    True
[DEBUG   ] jid 20220831091745135871 return from web01.mydomain.com
[DEBUG   ] return event: {'web01.mydomain.com': {'ret': True, 'retcode': 0, 'jid': '20220831091745135871'}}
[DEBUG   ] The functions from module 'nested' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded nested.output
web01.mydomain.com:
    True
[DEBUG   ] Checking whether jid 20220831091745135871 is still running
[DEBUG   ] Closing AsyncReqChannel instance
[DEBUG   ] retcode missing from client return
[DEBUG   ] return event: {'es03.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
es03.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'dev01.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
dev01.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'dev02.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
dev02.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'dev03.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
dev03.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'db01.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
db01.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'db03.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
db03.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'runner01.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
runner01.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'salt.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
salt.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'es02.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
es02.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'pve02.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
pve02.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'es01.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
es01.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'dev04.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
dev04.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] return event: {'db02.mydomain.com': {'failed': True}}
[DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded no_return.output
db02.mydomain.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20220831091745135871
[DEBUG   ] Closing IPCMessageSubscriber instance
ERROR: Minions returned with non-zero exit code
```

**Expected behavior**
return a list of targeted minions also in the jobs.list_job

**Versions Report**
see setup

**Comment by whytewolf** [comment] 2022-09-01 15:56
@tomadmiraal I'm not able to reproduce this. and you say this started after an update to 3004.2? You might want to try clearing your masters cache. to see if there might be a corrupted cache causing this.

**Comment by whytewolf** [comment] 2022-09-07 17:25
> @whytewolf Thanks for your reaction.
> 
> We debugged a little more and find out that the problem was solved by removing a setting
> 
> ```
> minion_data_cache: False
> ```
> 
> What is the default value of "minion_data_cache"?

the default for minion_data_cache is `True` setting it to False would mean you have no data cache for the master to know which minions would respond.

**Comment by whytewolf** [comment] 2022-10-07 16:24
I'm going to close this as without a data cache this would be the expected behavior.

**Closed by whytewolf** 2022-10-07 16:24 UTC
Labels: Bug, expected-behavior
