### ISSUE TITLE
pygit2: git submodules cause traceback in file_list

### ISSUE THREAD

**Issue by joshughes** [saltstack/salt#29631] opened 2015-12-11 17:34 UTC
We use the file recurse state and can not update to v2015.8.3 because in combination with gitfs, the state does not work. 

```
2015-12-11 17:28:20,418 [salt.master      ][ERROR   ][1255] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1379, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 607, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 180, in file_list
    return gitfs.file_list(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2308, in file_list
    return self._file_lists(load, 'files')
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2285, in _file_lists
    repo_files, repo_symlinks = repo.file_list(load['saltenv'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1017, in file_list
    _traverse(tree, blobs, self.root)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 994, in _traverse
    _traverse(obj, blobs, os.path.join(prefix, entry.name))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 994, in _traverse
    _traverse(obj, blobs, os.path.join(prefix, entry.name))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 994, in _traverse
    _traverse(obj, blobs, os.path.join(prefix, entry.name))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 986, in _traverse
    obj = self.repo[entry.oid]
  File "/usr/local/lib/python2.7/dist-packages/pygit2/repository.py", line 99, in __getitem__
    raise KeyError(key)
KeyError: f16c3f1b33223c7ab82744fb00e6bbc3f48ce61b
```

This error pops up every time any formula attempts to use the file.recurse state. The file.recurse state is marked as a failure with a message like. 

```
----------
          ID: salt-master
    Function: file.recurse
        Name: /etc/salt/master.d
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 17:28:19.378276
    Duration: 2082.209 ms
     Changes:
```

Below you will see I am trying to setup the config files in my master.d directory. I have tested and found this problem in my other formulas. I thought this was a good example since it was cloned at one point from. https://github.com/saltstack-formulas/salt-formula

```yaml
salt-master:
  file.recurse:
    - name: /etc/salt/master.d
    - template: jinja
    - source: salt://salt/files/master.d
    - clean: True
  service.running:
    - enable: True
    - name: salt-master
    - watch:
      - file: salt-master
      - file: /etc/salt/version_{{ salt.master.version }}_install
```

My version information is below.
```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: 1.1.2
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.22.1
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-49-generic
         system: Ubuntu 14.04 trusty
```

Gitfs configuration is as follows.

```yaml

fileserver_backend:

  - roots

  - git

gitfs_provider: pygit2

gitfs_pubkey: /root/.ssh/id.pub


gitfs_privkey: /root/.ssh/id


gitfs_user: git


gitfs_remotes:


    - ssh://git@foo.com/salt/apt-formula.git



    - ssh://git@foo.com/salt/artifactory-formula.git

```

**Comment by jfindlay** [comment] 2015-12-11 19:34
@joshughes, thanks for the report.

Ping, @terminalmage.

**Comment by terminalmage** [comment] 2015-12-11 19:40
What version of pygit2?

**Comment by terminalmage** [comment] 2015-12-11 19:40
Also, what version of libgit2?

**Comment by terminalmage** [comment] 2015-12-11 19:48
Oh, I did not realize that the pygit2 version was added to the versions_report.

Are the formulas you're using basically the same as the ones from Github?

**Comment by joshughes** [comment] 2015-12-11 20:11
Yes the state that is failing is exactly the same as this file... 

https://github.com/saltstack-formulas/salt-formula/blob/master/salt/master.sls

**Comment by joshughes** [comment] 2015-12-11 20:12
libgit2 

```
ii  libgit2-0:amd64                  0.19.0-2                         amd64        low-level Git library
ii  libgit2-dev:amd64                0.19.0-2                         amd64        low-level Git library (development files)
```

**Comment by terminalmage** [comment] 2015-12-11 20:22
The libgit2 version must be the same release cycle as pygit2 (this is explained in the "minimum requirements" note [here](https://docs.saltstack.com/en/latest/ref/file_server/all/salt.fileserver.gitfs.html)). There have been a number of changes between libgit2 0.19 and libgit2 0.22.

Please update libgit2 to a compatible release, and install a compatible pygit2 release, and try again.

**Comment by joshughes** [comment] 2015-12-11 21:22
Okay I will try updating. I have been down this road before and found it did not help at all.

**Comment by terminalmage** [comment] 2015-12-11 21:33
OK, well this isn't just coming from me, it's straight from the [pygit2 installation instructions](http://www.pygit2.org/install.html#version-numbers).

Once we can confirm that this isn't being caused by the interaction of conflicting versions of pygit2 and libgit2, we can be more confident that this is a bug in gitfs.

**Comment by joshughes** [comment] 2015-12-11 21:41
```
:~# dpkg -l | grep libgit
ii  libgit2-22:amd64                 0.22.1-0ubuntu3                  amd64        low-level Git library
ii  libgit2-dev:amd64                0.22.1-0ubuntu3                  amd64        low-level Git library (development files)

pygit2 (0.22.1)
```

Same error. Also just to note that 14.04 LTS ubuntu does not have the version of libgit that salt is requiring it defaults to 19. Also like I said this exact same configuration works on v2015.5.3... exactly. In the future I would hope that LTS versions of operating systems were taken into account for customers who depend on them. 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1379, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 607, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 180, in file_list
    return gitfs.file_list(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2308, in file_list
    return self._file_lists(load, 'files')
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2285, in _file_lists
    repo_files, repo_symlinks = repo.file_list(load['saltenv'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1017, in file_list
    _traverse(tree, blobs, self.root)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 994, in _traverse
    _traverse(obj, blobs, os.path.join(prefix, entry.name))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 994, in _traverse
    _traverse(obj, blobs, os.path.join(prefix, entry.name))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 994, in _traverse
    _traverse(obj, blobs, os.path.join(prefix, entry.name))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 986, in _traverse
    obj = self.repo[entry.oid]
  File "/usr/local/lib/python2.7/dist-packages/pygit2/repository.py", line 99, in __getitem__
    raise KeyError(key)
KeyError: f16c3f1b33223c7ab82744fb00e6bbc3f48ce61b
```

**Comment by terminalmage** [comment] 2015-12-11 21:49
We require pygit2 0.20.3 because it was the first version which supported authentication (auth support wasn't added to libgit2 until 0.20.0).

Unfortunately the libgit2, pygit2, and Ubuntu projects are not under our control, so we can't really do anything about the fact that Ubuntu doesn't have a compatible pygit2 version available out of the box.

**Comment by joshughes** [comment] 2015-12-11 21:50
```python
#!pydsl
import os
import salt.loader

from salt.fileclient import get_file_client
loaded_grains = salt.loader.grains(__opts__)

file_client = get_file_client(__opts__)
file_client.get_dir("salt://salt_test/servers", cache_path, environment)

environment = loaded_grains['env']
cache_path = '/var/cache/salt/minion/files/' + environment + '/salt_test/'
```

Using the PyDSL I can cause the error to throw by doing the above. Although files should be in the cache directory they are not there. In v2015.5.3 they are.

**Comment by joshughes** [comment] 2015-12-14 19:58
To add more to this issue. I have built a completely clean server installing everything by hand with the correct versions mentioned above. 

The initial cache population seems to work and my file recurse works and the above PYDSL works flawlessly. 

Any highstate after that first cache then proceeds to fail with the same error whenever trying to retrieve directories from the cache. 

```
2015-12-14 19:55:39,030 [salt.master      ][ERROR   ][3771] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1379, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 607, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 180, in file_list
    return gitfs.file_list(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2308, in file_list
    return self._file_lists(load, 'files')
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2285, in _file_lists
    repo_files, repo_symlinks = repo.file_list(load['saltenv'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1017, in file_list
    _traverse(tree, blobs, self.root)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 994, in _traverse
    _traverse(obj, blobs, os.path.join(prefix, entry.name))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 994, in _traverse
    _traverse(obj, blobs, os.path.join(prefix, entry.name))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 994, in _traverse
    _traverse(obj, blobs, os.path.join(prefix, entry.name))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 986, in _traverse
    obj = self.repo[entry.oid]
  File "/usr/local/lib/python2.7/dist-packages/pygit2/repository.py", line 99, in __getitem__
    raise KeyError(key)
KeyError: f16c3f1b33223c7ab82744fb00e6bbc3f48ce61b
```

**Comment by terminalmage** [comment] 2015-12-14 20:08
Thanks. This will be addressed either today or tomorrow.

**Comment by joshughes** [comment] 2015-12-15 16:31
So adding more. I think I finally got to the root cause of this. I removed one of my git repos that must have something that gitfs does not like. Once I removed the offending git repo gitfs started working correctly. It looks like at some point someone may have added a git submodule to the repo. That seems to be the only thing that I can see that could cause it to be different than my other git repos. 

So if your having trouble reproducing the error, that might be the root cause of all this.

**Comment by terminalmage** [comment] 2015-12-16 18:50
I'm in the process of trying to reproduce this, so the information about the submodule definitely helps. I'll add one and see if that helps.

**Comment by terminalmage** [comment] 2015-12-16 18:52
If it was indeed a submodule causing this, then the code we use to walk the file tree for pygit2 needs to be able to deal with it, so this is good info, thanks.

**Comment by joshughes** [comment] 2015-12-16 20:07
ya I am not sure how it happened but i had a file that referred to another project with the following content

```
Subproject commit f16c3f1b33223c7ab82744fb00e6bbc3f48ce61b
```

I am guessing that is a submodule reference... honestly I have only tried to use them once or twice. So it could be the fact that someone was trying to use a submodule at some point and then didn't remove it properly. 

I can say as soon as I removed the file with that content this issue went away.

**Comment by terminalmage** [comment] 2015-12-16 20:46
OK, I was finally able to reproduce this with a submodule.

As a little bit of background, the reason we have this ``_traverse()`` function which appears in the traceback you posted is because in pygit2 there is no function to iterate over all files in the repository. Files/symlinks are represented by ``pygit2.Blob`` objects, and directories are represented by ``pygit2.Tree`` objects. So, by recursing each time we reach a ``pygit2.Tree`` object (i.e. directory), we are able to build a list of what files are in the repo. This list of files is used by states like ``file.recurse`` to determine which files to pull down from the Salt fileserver to be placed on the minion.

So, going back to the line that raised that exception:

```
File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 986, in _traverse
    obj = self.repo[entry.oid]
  File "/usr/local/lib/python2.7/dist-packages/pygit2/repository.py", line 99, in __getitem__
    raise KeyError(key)
KeyError: f16c3f1b33223c7ab82744fb00e6bbc3f48ce61b
```

A ``pygit2.Repository`` object (``self.repo`` above) is indexable as if it were a dictionary, allowing for the blob or tree object to be easily referenced as we can see there in line 986 from the traceback.

So, what is happening here is that the submodule directory is not indexable in the same way that files and directories are. Pygit2 is pretty actively developed and does not guarantee that their API will change ([even in point releases](http://www.pygit2.org/install.html#version-numbers)), so this may be caused by changes in pygit2, or it might always have been broken. My guess is that the former is more likely than the latter, because I've used gitfs with repos containing submodules before without this sort of error occurring.

Thanks for the additional work spent investigating, it has been a HUGE help. I would not have thought to try a submodule.

**Comment by terminalmage** [comment] 2015-12-16 20:53
FYI, I've renamed this issue to more accurately describe what is going wrong. We use the titles of closed issues when generating changelogs for release notes, so this will make the release notes more accurate once a fix for this is merged.

It shouldn't take more than a few hours to nail down the versions under which this traceback appears, and figure out a way around it. I'm not sure if this will open up support to traverse down into submodule directories, I'll discover whether or not this is possible during my investigation.

**Comment by terminalmage** [comment] 2015-12-16 22:33
@joshughes Pygit2 does have submodule support in 0.22.1 and later, however I cannot at this time implement it for gitfs because it requires a branch to be checked out. For gitfs we don't checkout branches because we have to be able to support any branch or tag as a fileserver environment.

It may be possible to implement this for gitfs, but we'd need to checkout the branch/tag corresponding to the desired fileserver environment to do so, and this would make gitfs open to a race condition where one minion wants a file from branch ``master`` while another wants a file from branch ``foo``, and the master can only serve one of those requests at a time because it needs to checkout the branch first. This would be something I'd like to avoid.

A more reliable solution to using submodules in gitfs is to parse ``.gitmodules`` (actually, I'm pretty sure we can just do this with pygit2's native config file support since ``.gitmodules`` uses the same format), and fetch the submodule separately in its own cachedir.

With that in mind, for now I am skipping submodules (see #29772), which should prevent this traceback from occurring, and allow your ``file.recurse`` states to complete without resulting in a traceback.

**Comment by terminalmage** [comment] 2015-12-16 22:58
If you'd like to follow the progress of adding submodule support, you can subscribe to notifications for the already-open issue to add submodule support for gitfs: https://github.com/saltstack/salt/issues/13664

**Closed** 2015-12-22 15:05 UTC
Labels: Bug, Core, File Servers, High Severity, P3, Platform, TEAM Core
