### ISSUE TITLE
Dynamic nodegroup matching, not working in top.sls [BUG]

### ISSUE THREAD

**Issue by adamzero1** [saltstack/salt#58823] opened 2020-10-27 14:55 UTC
**Description**
I'm trying to use dynamic node groups (not sure if this is the correct term). So that I can add minions to a nodegroup without having to restart the salt master.
I have this working for targeting however pillar data doesn't seem to work.

**Setup**
`salt-master.conf`
```
nodegroups:
  foo:
    - 'I@is_in_foo:True'
```
`pillar/top.sls`
```
base:
  '*':
    - base
  foo:
    - match: nodegroup
   - foostuff
```

In `base` there is some logic that pulls in a file and updates the pillar so that 'is_in_foo' is `True`.
I can confirm this as:
`salt 'test' pillar.get is_in_foo` returns `True`
I can also see it is working for targeting as
`salt -N foo test.ping` pings the correct minions.
However, nothing in `foostuff` is in the pillar for the minion.

Just to make sure it wasn't some issue with cached nodegroups, I have restarted the salt master and can confirm I can still target the minion for commands, but not in the `top.sls`

If I swap `'I@is_in_foo:True'` within `salt-master.conf` for the minion id and restart, all works as expected.

Is this supposed to work?
Is there a better way to configure dynamic nodegroups that would work?

(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
I'm expecting to be able to target a nodegroup within a pillar file regardless of how the nodegroup is composed

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by Ch3LL** [comment] 2020-11-19 14:51
this is occurring because the top file is rendered before pillar data, so when it tries to match against pillar data there is no pillar data available yet. You could possibly target against grains, by either using grains already defined across all minions or a custom grain you set.

**Comment by Ch3LL** [comment] 2023-08-31 20:26
Closing as expected behavior.

**Closed by Ch3LL** 2023-08-31 20:26 UTC
Labels: expected-behavior, Question
