### ISSUE TITLE
[ubuntu-trusty] salt-common fails to install because python-tornado 4.2.1 is missing

### ISSUE THREAD

**Issue by vieira** [saltstack/salt#28106] opened 2015-10-19 18:13 UTC
I am using `deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/latest trusty main` on Ubuntu 14.04 and running apt-get install salt-common exits with error: `salt-common : Depends: python-tornado (>= 4.2.1) but 3.1.1-1ubuntu2 is to be installed`.

Any idea?

**Comment by jfindlay** [comment] 2015-10-20 15:51
@vieira, are you installing on a 32 bit system?

**Comment by vieira** [comment] 2015-10-21 13:12
@jfindlay Yes.
```
$ uname -p
i686
```

**Comment by jfindlay** [comment] 2015-10-27 20:04
@vieira, in that case, this is a duplicate of #27437.  Thanks for the report.

**Closed by jfindlay** 2015-10-27 20:04 UTC
Labels: Duplicate
