### ISSUE TITLE
libvirt.keys generates CA certificate with 1 year expiration date

### ISSUE THREAD

**Issue by moloney** [saltstack/salt#41667] opened 2017-06-09 00:32 UTC
### Description of Issue/Question
My libvirt hypervisors started to fail to communicate with each other mysteriously. After some digging I find that the SSL certificate generated by the `libvirt.keys` state has expired.  A default value of 1-year for these certificates is a bit silly.  There is no provision to update the certificates or change the expiration time.

### Setup
I am on 2015.8.13 but the relevant code doesn't appear to have changed since then.

### Steps to Reproduce Issue
Run the `libvirt.keys` state on at least one minion.  Look at the expiration data on the certificate at `/etc/salt/pki/master/libvirt/cacert.pem`.

### Versions Report
$ salt --versions-report
Salt Version:
           Salt: 2015.8.13
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment] 2017-06-09 16:47
@moloney Looking at the code and trying to replicate this issue, it doesn't appear that the `keys` function in the state module generates the keys.  It appears they're generated, stored in pillar and then retrieved by the `keys` function.

**Comment by moloney** [comment] 2017-06-09 21:01
Sorry, I should have mentioned the actual key generation happens in the external pillar.

**Comment by garethgreenaway** [comment] 2017-06-09 21:16
@moloney Ahh that makes more sense.  Is there a specific Salt module that you're using to generate them via external pillar?

**Comment by moloney** [comment] 2017-06-09 21:29
I am just making use of the `libvirt.keys` state, as mentioned above.

**Comment by garethgreenaway** [comment] 2017-06-09 21:35
@moloney All good now.  I needed to have certtool installed.

**Comment by rallytime** [comment] 2017-06-16 21:25
@moloney This should be fixed in #41722.

**Comment by garethgreenaway** [comment] 2017-07-21 15:51
This issue should be considered resolved and the fix is available on 2017.7.  If the issue is not considered resolved or persists, please feel free to re-open this issue.

**Closed by garethgreenaway** 2017-07-21 15:51 UTC
Labels: Feature, Fixed Pending Verification
