### ISSUE TITLE
Joyent API 6.5 support ending, salt-cloud needs updating

### ISSUE THREAD

**Issue by lawnoftrees** [saltstack/salt#18979] opened 2014-12-14 01:02 UTC
Hi,

salt-cloud currently uses version 6.5 of the Joyent API.
Joyent released version 7 on 2014-06-24.
They plan to discontinue support for 6.5 six months after that release, so on 2015-01-24.

Deprecation notice: https://apidocs.joyent.com/cloudapi/#appendix-f-sdc-65-support
Version 7 release announcement: https://www.joyent.com/company/press/joyent-smartdatacenter-7-delivers-production-ready-private-cloud-software-to-fill-growing-market-gap

**Comment by und1sk0** [comment] 2015-02-18 13:31
any updates?

**Comment by cachedout** [comment] 2015-02-18 15:08
@und1sk0 Forgive me for not being up-to-speed on salt-cloud but does the deprecation date passing now mean that salt-cloud no longer works with Joyent? We might need to bump the severity of this issue to get some eyes on it.

**Comment by und1sk0** [comment] 2015-02-19 03:00
Correct, you will want to get an SDC 7.0 version of the tools out asap. AFAIK SDC 6.5 is deprecated.

**Comment by rallytime** [comment] 2015-02-21 15:34
@lawnoftrees and @und1sk0 the Joyent driver has been updated to SDC 7.2 in the above pull request. The fix will be available in the upcoming release of 2015.2.0. Feel free to give the 2015.2 branch a try if you want to test it out!

**Comment by und1sk0** [comment] 2015-02-22 08:45
Thanks a million!

We'll definitely be testing it out in the next week.

**Comment by rallytime** [comment] 2015-02-24 04:18
I'm going to close this issue out for now as I have tested it pretty well and the new driver seems to be in good order. If anyone runs into any major problems, leave a comment here and we can re-open and re-asses. If there are specific or smaller issues that arise from this refactor, feel free to open a new issue with details to reproduce. Thanks all!

**Closed by rallytime** 2015-02-24 04:18 UTC
Labels: Bug, Fixed Pending Verification, High Severity, Salt-Cloud
