### ISSUE TITLE
Windows reg.present salt-call win_dacl.py 2019.2.0 'LookupAccountSid' Error

### ISSUE THREAD

**Issue by jeremylarose** [saltstack/salt#51868] opened 2019-02-27 14:36 UTC
### Description of Issue/Question
The reg.present states work, but presents an ugly error when running salt-call from a minion running version 2019.2.0... the error is not present with 2018.3.4 or if running the state from the master... only with a salt-call from the minion.

### Setup
example sls:
```
'HKLM\SOFTWARE\Policies\Microsoft\\Windows\TabletPC\PreventHandwritingDataSharing':
  reg.present:
    - name: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\TabletPC'
    - vname: PreventHandwritingDataSharing
    - vdata: 1
    - vtype: REG_DWORD
```
### Steps to Reproduce Issue
Run salt-call on multiple Windows 10 machines
```
[ERROR   ] Error resolving "S-1-1-1-1111-1111111111111-1111111111-11-111-111111-11111-1111-1111": No mapping between account names and security IDs was done.
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 1179, in get_name
    return win32security.LookupAccountSid(None, sid_obj)[0]
error: (1332, 'LookupAccountSid', 'No mapping between account names and security IDs was done.')
[ERROR   ] Error resolving "S-1-1-1-1111-1111111111111-1111111111-11-111-111111-11111-1111-1111": No mapping between account names and security IDs was done.
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 1179, in get_name
    return win32security.LookupAccountSid(None, sid_obj)[0]
error: (1332, 'LookupAccountSid', 'No mapping between account names and security IDs was done.')
```
... but the reg.present state runs and succeeds

### Versions Report

salt 2019.2.0 (Fluorine)
salt-call 2019.2.0 (Fluorine)... ERROR
salt-call 2018.3.4 (Oxygen)... no error

**Comment by twangboy** [comment] 2019-02-27 17:33
@jeremylarose Thanks for reporting. I'll take a look at this.
That GUID looks suspect though... I wonder where that came from...
That code is trying to match the GUID it received to an Account name.

**Comment by jeremylarose** [comment] 2019-02-27 17:36
Thanks, yes, i made up that id, it was a proper one

**Comment by twangboy** [comment] 2019-02-27 17:56
Oh, OK. That makes sense. I'll take a look at it.

**Comment by twangboy** [comment] 2019-02-27 23:15
@jeremylarose I'm having a hard time reproducing this. So, I have a few questions.

Is this the only thing in the state file you're applying? Are there any other states?
Are you setting `owner` or `perms` that you didn't have above?
What account are you running `salt-call` under? (Local Administrator?)
Is it a domain account?
Is the account a member of the Local Administrators group?

**Comment by jeremylarose** [comment] 2019-02-28 03:40
It occurs with other states.  But that is the only contents of this particular state that is run and produces the error.  No permissions are attempted to be modified.  Salt-call is run under a domain account with admin rights and through cmd or powershell run as administrator.  The thing is, it doesn't occur with previous versions of salt minion, ex: 2018.3.4 ... just 2019.2.0 using either py2 or py3.

**Comment by twangboy** [comment] 2019-02-28 17:22
Perhaps the `LookupAccountSID` function is failing because it can't find a name mapping for the Domain Account. Which is strange as you've assumably logged in with that account and are running the command under the same.
Does the same behavior occur with a local (non-domain) admin account?

**Comment by gdsjerry** [comment] 2019-03-29 13:58
Same problem happens to me. Vagrant running Windows 2019. Salt 2019.2.0 with python 3. Running as normal "vagrant" local user. Setting any value using reg.present seems to throw this error, for example:

```
ssh|set_bash_as_openssh_shell:
  reg.present:
    - name: 'HKLM\SOFTWARE\OpenSSH'
    - vname: 'DefaultShell'
    - vdata: 'C:\Program Files\Git\bin\bash.exe'
```

**Comment by twangboy** [comment] 2019-03-29 18:53
So, I thought that perhaps this was an issue where the owner of the key/file had been deleted from the machine. Windows leaves those entries in the DACL, but instead of resolving to a name, you'll see something like `Account Unknown` followed by the GUID.

![image](https://user-images.githubusercontent.com/9383935/55255878-41a15000-5221-11e9-8955-1e4576e1e6c7.png)

So, I tried the following:
1. Create a user on the machine
2. Make that user the owner of `HKLM\SOFTWARE\OpenSSH`
3. Delete that user from the machine
4. Apply the state

It still work generated the value properly. Maybe it's an issue if the missing owner is a domain user...

Would you mind looking at the key you're setting and see who the owner is? Does the account exist? Does it resolve to a name or is it `Account Unknown`? Is there anything there that looks strange?

![image](https://user-images.githubusercontent.com/9383935/55255987-980e8e80-5221-11e9-910f-3ef787a17f73.png)

**Comment by gdsjerry** [comment] 2019-03-30 17:31
The registry key does indeed have a "Account Unknown" next to other permission entries but so does even my own laptop with Windows 10 Pro. But the owner of the OpenSSH key itself is Administrators group, not this missing user. I cannot remove this user from entries because after clicking "remove" and then "apply" it magically reappears again... Also, strangely enough, every time I tinker with anything in that registry key there are more errors visible in the output of salt-apply. Initially there was just one error, now there is 4. 

![image](https://user-images.githubusercontent.com/4499197/55279517-a6d86c80-5319-11e9-8773-cb6f61fb338c.png)

![image](https://user-images.githubusercontent.com/4499197/55279538-c1124a80-5319-11e9-8ee4-bf1a2948c329.png)


I tried setting the following options on salt reg.present state but no difference (only more errors)

    - win_inheritance: false 
    - win_perms_reset: true

I tried creating any other key in any other location under HKLM and same problem occurs.

I'm using a vagrant image for windows 2019 with no modifications apart from changing a default hostname from `vagrant` to `vagrantpc` because that was causing a different set of issues https://app.vagrantup.com/StefanScherer/boxes/windows_2019

Any ideas how to resolve this?

**Comment by twangboy** [comment] 2019-03-31 03:47
Maybe the Unknown Account is being applied to a parent key. Try deleting it at the highest level that it's present.

**Comment by gdsjerry** [comment] 2019-03-31 11:14
When I try to remove Account Unknown from HKEY_LOCAL_MACHINE and click apply, it automatically reappears. So it seems its not possible on Windows Server 2019. But again - same situation is on my private Windows 10 Pro laptop. So i'm not sure this is a bad setup or behaviour

![image](https://user-images.githubusercontent.com/4499197/55288369-e7d28e80-53b6-11e9-84b2-83a857675381.png)

**Comment by twangboy** [comment] 2019-03-31 14:36
Well, doing some googling, that Account Unknown we're seeing may be a red herring. I found this link: https://social.technet.microsoft.com/Forums/en-US/3e7d85e3-d0e1-4e79-8141-0bbf8faf3644/windows-10-anniversary-update-the-case-of-the-mysterious-account-sid-causing-the-flood-of-dcom?forum=win10itprosetup
Looks like it's part of Microsoft Edge Sandboxing. The reg.present worked on my instance with the `Account Unknown` present. When I get back next week, I'll take a look using your vagrant image.

**Comment by rmustard** [comment] 2019-04-10 16:24
I had a similar issue.
With this state file the state reports a success but I see the same error above in the output.

Add-Reg:
  reg.present:
    - name: 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting\\LocalDumps\\exename'
    - vname: DumpType
    - vdata: '2'
    - vtype: 'REG_SZ'

Then I searched through the registry for that key and the key got added at:
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\Windows Error Reporting\LocalDumps\exename

**Comment by plaguardia** [comment] 2019-04-10 20:29
@gdsjerry Having these same issues. From my googling that local unknown SID user account on the registry permission seems to be a part of the base OS and cannot/should not be removed.

@twangboy in response to your most recent post, pushing the the state from the master works for me without an issue and doesn't return any errors. However, using the salt-call.bat (salt-call.bat salt.apply) from the minion returns the error. It appears to be applying the configuration successfully, but the error is making my orchestration layer tool bomb out because it sees the error response.

Anyone have any progress on this? It feels like a bug to me.

**Comment by timwsuqld** [comment] 2019-08-29 22:20
I'm having the same issue for a `file.managed` state.
Can we not just return the SID when an Account Name can't be found?
I assume in this case the SID is a local account that Salt is running as. And this occurs when we run the state from the salt master too.
```
          ID: C:\Zabbix
    Function: file.directory
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 1179, in get_name
                  return win32security.LookupAccountSid(None, sid_obj)[0]
              pywintypes.error: (1332, 'LookupAccountSid', 'No mapping between account names and security IDs was done.')
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1933, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 3295, in directory
                  win_perms_reset=win_perms_reset)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 792, in _check_directory_win
                  owner = salt.utils.win_dacl.get_owner(name)
                File "c:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 1270, in get_owner
                  return get_name(owner_sid)
                File "c:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 1186, in get_name
                  raise CommandExecutionError(message, exc)
. Additional info follows:ons.CommandExecutionError: Error resolving "PySID:S-1-5-21-54649834-1885742682-4122518233-1000": No mapping between account names and security IDs was done.
```

**Comment by timwsuqld** [comment] 2020-01-08 00:08
Not stale

**Comment by sagetherage** [comment] 2020-02-11 20:45
@Akm0d @xeacott looks like this needs some follow up, there may be other similar issues, please do your best and good luck!

**Comment by twangboy** [comment] 2020-02-13 20:31
A workaround would be to use the `win_lgpo` module to set the `Turn off handwriting personalization data sharing` policy

**Comment by sagetherage** [comment] 2020-05-18 23:45
closing as fixed will be released in Sodium

**Closed by sagetherage** 2020-05-18 23:45 UTC
Labels: Bug, Sodium, Windows
