### ISSUE TITLE
state.apply test=True returns inverted diff

### ISSUE THREAD

**Issue by NewEvolution** [saltstack/salt#47714] opened 2018-05-17 23:46 UTC
### Description of Issue/Question
When applying changes via `file.managed` in state with the `test=True` flag set, the diff shows the opposite of what changes will be made, i.e. the line to be removed is shown with a `+` and the line to be added is shown with a `-`

### Setup
Can be reproduced with arbitrary file content changes in `file.managed` managed files.

### Steps to Reproduce Issue
Apply a state: `salt --state-output=changes 'graylog.*' state.apply state/linux/graylog test=True`
Relevant output:
```
----------
          ID: /etc/graymongo/mongodb.conf
    Function: file.managed
      Result: None
     Comment: The file /etc/graymongo/mongodb.conf is set to be changed
     Started: 23:29:25.940514
    Duration: 36.212 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -8,7 +8,7 @@

                   # logappend=true

                  -bind_ip = 172.31.46.63
                  +bind_ip = [u'172.31.46.63
                   #port = 27017

                   # Enable journaling, http://www.mongodb.org/display/DOCS/Journaling
```
Run without test flag to make changes: `salt --state-output=changes 'graylog.*' state.apply state/linux/graylog`
Relevant output:
```
----------
          ID: /etc/graymongo/mongodb.conf
    Function: file.managed
      Result: True
     Comment: File /etc/graymongo/mongodb.conf updated
     Started: 23:33:42.907231
    Duration: 41.373 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -8,7 +8,7 @@

                   # logappend=true

                  -bind_ip = [u'172.31.46.63
                  +bind_ip = 172.31.46.63
                   #port = 27017

                   # Enable journaling, http://www.mongodb.org/display/DOCS/Journaling
```

### Versions Report
Master:
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-112-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minion:
```
Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: Ubuntu 16.04 xenial
             locale: ascii
            machine: x86_64
            release: 4.4.0-116-generic
             system: Linux
            version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment] 2018-05-18 12:49
duplicate of https://github.com/saltstack/salt/issues/46931 and will be fixed in 2018.3.1

**Closed by Ch3LL** 2018-05-18 12:49 UTC
