### ISSUE TITLE
Upgrade from 2017.7.1 to 2017.7.2 fails on Debian using pkg.upgrade

### ISSUE THREAD

**Issue by tkaehn** [saltstack/salt#44001] opened 2017-10-10 06:59 UTC
### Description of Issue/Question

Using `salt minion pkg.upgrade` or `salt minion pkg.upgrade dist_upgrade=True` for minions running Debian 8 or 9 results in connection loss due to a stopped minion and an inconsistent package state:

```
# apt-get upgrade
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
```

/var/log/salt/minion:
```
2017-10-10 08:29:58,282 [salt.utils.parsers][WARNING ][860] Minion received a SIGTERM. Exiting.
```

If I remember correctly the upgrades up to 2017.7.1 didn't fail like this.

### Setup
A single master with multiple minions.

### Steps to Reproduce Issue
Please see description.

### Versions Report
master:
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.9 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9 
```
minion (after manually upgrading the packages):
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.9 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9 
```

**Comment by mostynb** [comment] 2017-10-10 10:22
This problem occurs quite regularly for me, feels like a bug in the pkg.uptodate state and/or the .deb packages themselves: if salt-minion attempts to upgrade the packages, the salt .deb packaging scripts restart the minion and the connection is closed, leaving the minion disconnected and half-upgraded.

**Comment by githubcdr** [comment] 2017-10-10 14:15
confirmed

**Comment by gtmanfred** [comment] 2017-10-10 14:25
This is a duplicate of https://github.com/saltstack/salt/issues/43340

**Closed by gtmanfred** 2017-10-10 14:25 UTC
