### ISSUE TITLE
top.sls in master branch is not authorative

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#17261] opened 2014-11-07 09:13 UTC
top.sls in master branch looks:
```
base:
    '* and not I@environment:itg':
        - match: compound
        - httpd-stats
itg:
    'environment:itg':
        - match: pillar
        - httpd-stats
```
top.sls in itg branch looks:
```
base:
    '*':
        - httpd-stats
itg:
    'environment:itg':
        - match: pillar
        - httpd-stats
```
And the highstate result is:

    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is "httpd_stats" and is found in SLS "itg:httpd-stats" and SLS "base:httpd-stats"

After deleting top.sls from itg branch everything works as expected.

Documentation at http://docs.saltstack.com/en/latest/ref/states/top.html#how-top-files-are-compiled state that env defined in master branch (base env) is authorative.

Is it a bug or i misunderstood something ? Ma salt version is 2014.1.13

**Comment by alf** [comment] 2015-02-05 20:58
We just came across this problem. The reason things goes haywire is that [BaseHighState.get_envs](https://github.com/saltstack/salt/blob/v2014.1.13/salt/state.py#L1883) uses an unordered set.

The result from `get_envs` is used directly in [BaseHighState.get_tops](https://github.com/saltstack/salt/blob/v2014.1.13/salt/state.py#L1892) under the assumption that the base environment is first.

**Comment by cachedout** [comment] 2015-06-16 22:27
I believe this is a duplicate of #12483. I am about to push a fix for that and I would like to keep the conversation in one place. Therefore, I am going to close this issue in favor of that one. Please follow the discussion there. Thanks!

**Closed by cachedout** 2015-06-16 22:27 UTC
Labels: Bug, Core, High Severity, P2
