### ISSUE TITLE
salt-log-setup: AttributeError 'NoneType' object has no attribute 'flush'

### ISSUE THREAD

**Issue by asymetrixs** [saltstack/salt#46192] opened 2018-02-26 14:01 UTC
### Description of Issue/Question
Unfortunately I found this error in the log file and have no idea what exactly caused it. Perhaps others with the same error can add some more information.

### Error
```
[salt.log.setup] [EROR][16360] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'NoneType' has no attribute 'flush'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\salt\bin\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode= _main(fd)
  File "C:\salt\bin\lib\multiprocessing\spawn.py", line 119, in _main
    return self._bootstrap()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 268, in _bootstrap
    sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'Flush'
  
```

### Versions Report
Salt Version 2017.7.2 64-Bit on Windows 7, Python 3.5.3 64-Bit, Tornado 4.5.1 (default salt-minion installation, no detailed information due to airgap, hope this helps)

**Comment by Ch3LL** [comment] 2018-02-26 15:34
is there more context in the logs before or after this log? Also are you still seeing this?

**Comment by asymetrixs** [comment] 2018-02-26 16:19
Unfortunately there is nothing close to the time this incident took place. And also there was no job scheduled to run at that time. I really cannot offer more than that for now and only opened this incident so that perhaps others will find it and add information in case they experience the same issue.
It does not seem to cause any trouble for now. I will keep monitoring this.

**Comment by Ch3LL** [comment] 2018-02-27 16:00
Are you seeing this consistently?

**Comment by asymetrixs** [comment] 2018-02-28 07:45
I see this error popping up on all my Windows 7 machines that I just checked (did not check all). It happens occasionally and does not seem to be connected to an event (like a scheduled job or something) - the errors "just happen". Surprisingly, this error occurs in the morning and in the evening but most of the time between minute 44-48 (like 8:45:XX or 16:45:XX or 21:45:XX UTC, but I have also seen it at 14:10:XX)

Took the time to copy some details:
``

**Comment by Ch3LL** [comment] 2018-02-28 17:32
thanks for the follow up information

ping @saltstack/team-windows have any of you seen this?

**Comment by skizunov** [comment] 2018-02-28 18:34
@Ch3LL : Yes, I have seen this before. This is caused by PR #40686. By adding `AppNoConsole 1`, it has a side effect of causing stdin/stdout to be `None` in the Python environment, and hence you see this happen. I resolved this issue in my own branch of Salt by removing `AppNoConsole 1` and instead moving my version of `nssm.exe` to the "Featured pre-release" that has the Windows Creators Update fix, that may be found here:
https://nssm.cc/download
Initially, I was hesitant to use a pre-release version of `nssm`, but I couldn't find another way to adaquately address both the Windows Creator's Update issue and this issue. I have been using this pre-release of `nssm` for quite some time and haven't had any issues with it. `nssm` seems to be very slow to release new versions of its stuff. The featured pre-release is almost a year old and the last actual release is 3.5 years old.
I would recommend that you guys take the same approach.

**Comment by twangboy** [comment] 2018-03-01 01:31
We need to discuss moving to the pre-release nssm @UtahDave @dwoz

**Comment by dwoz** [comment] 2018-03-01 19:34
Based on how old it is, I think the pre-release version of nssm will be fine.

**Comment by twangboy** [comment] 2018-03-02 20:19
The `nssm` binary has been updated in the above PR and will be included in future releases of Salt.

**Closed by twangboy** 2018-03-02 20:19 UTC
Labels: Pending Discussion
