### ISSUE TITLE
Errors and Warnings in salt-master log and on CLI when using latest Oxygen

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#45353] opened 2018-01-09 17:27 UTC
Errors and Warnings in salt-master log and on CLI when using latest Oxygen

Steps:
1. Install latest Oxygen from head of branch. Include a master and minion in the installation.
2. View `/var/log/salt/master`. Warnings and Errors
3. Run a simple command from the CLI. Warnings printed to the screen.

**See attachment**
[Oxygen Warnings.txt](https://github.com/saltstack/salt/files/1616038/Oxygen.Warnings.txt)

```
[root@SSE ~]# salt --versions report
Salt Version:
           Salt: 2018.2.0-816-g227cdbd

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
```

**Comment by gtmanfred** [comment] 2018-01-09 20:32
The SSDP one is know, and it is already being fixed.

The other ones appear to be a duplicate of #45352

**Closed by gtmanfred** 2018-01-09 20:32 UTC
