### ISSUE TITLE
mirroring of repo.saltstack.com via rclone results in large amounts of duplicate files

### ISSUE THREAD

**Issue by survient** [saltstack/salt#57658] opened 2020-06-12 21:11 UTC
### Description of Issue
When mirroring saltstack via rclone as suggested by https://repo.saltstack.com/#mirror you wind up with a large number of duplicate files for a total capacity of 428.3GB. After running deduplication on our Netapp file server it was able to reduce this down to 42.96GB. Comparatively if you sync the content via rsync the total amount of content is ~64G. Is there something the instructions for rclone are missing to deduplicate the data locally? With rclone creating such a large amount of duplicated content it makes it difficult for most private and public mirrors to store the data if they don't have any storage solution of capable of deduplicating the content. From a client perspective with this one major flaw it makes rsync a much better experience than rclone.

### Setup
rclone and rsync commands installed

### Steps to Reproduce Issue
follow mirroring steps outlined in:
https://repo.saltstack.com/#mirror

### Versions Report
$ rsync --version
rsync  version 3.0.6  protocol version 30
$ rclone --version
rclone v1.51.0

**Comment by frogunder** [comment] 2020-06-12 22:02
@bryceml Can you take a look at this, maybe you have some info/tips?

Thanks.

**Comment by bryceml** [comment] 2020-06-22 18:36
s3 isn't aware of symlinks, the vast majority of the duplicate files are caused by the symlinks for centos like
```
7.0
7.1
7.2
7.3
7.4
etc.
```
you can add an `--exclude` flag on the rclone  something like `--exclude '**/7.*/**' --exclude '**/8.*/**'`

And that should get rid of the vast majority of the duplicates.

I didn't try those flags myself, but something like that should work.

Also we should be down to 90G now that we've moved most of the content to archive.repo.saltstack.com.

**Comment by bryceml** [comment] 2020-06-22 18:41
If you want to write up a good set of excludes that are at least somewhat future proof (have some good pattern matching), I would be fine publishing them to the instructions on https://repo.saltstack.com/#mirror

**Comment by bryceml** [comment] 2020-06-22 18:45
Long term I'd like to get rid of all of the centos symlinks.  They were put there because of an issue with scientific linux I think, @dmurphy18 knows more about that.  We need to make sure everywhere that it's documented to use `$releasever` in the centos repo file is changed to point to the correct one specifically, i.e. `7` or `8`.

We would also need to have a formal deprecation over a period of time of that and announce it.

**Comment by dmurphy18** [comment] 2020-06-22 21:13
Actually the symlinks are there because of the different versions that Redhat uses, in addition to Scientific Linux (majorver.minorver)., for example: 7Server, 7WorkStation and having to insure that paths using those names can be resolved.

**Comment by survient** [comment] 2020-06-22 21:39
I can confirm that the size has been significantly reduced after most of the content was moved to archive:

Logical Size Used by Active Filesystem: 86.72GB

deduplication brings the size down to 47.55GB

If s3 does not support symlinks then this will be a difficult "issue" to solve. That said if the overall size of the project not including archive doesn't expect to grow significantly in a short time period then this may not matter.

**Comment by sagetherage** [comment] 2020-08-19 21:11
closing for now, @survient let us know if you want it re-opened

**Closed by sagetherage** 2020-08-19 21:11 UTC
Labels: Pending Discussion
