### ISSUE TITLE
scheduler run job return data does not include retcode

### ISSUE THREAD

**Issue by golmaal** [saltstack/salt#46445] opened 2018-03-08 14:19 UTC
Event generated when salt-call test.ping is called - 
```
salt/job/20180308090940010139/ret/salt-master  {
    "_stamp": "2018-03-08T14:09:40.011277",
    "arg": [],
    "cmd": "_return",
    "fun": "test.ping",
    "fun_args": [],
    "id": "xoas",
    "jid": "20180308090940010139",
    "retcode": 0,
    "return": true,
    "tgt": "salt-master",
    "tgt_type": "glob"
}
```

Event generated when a test.ping is added to schedule and run by scheduler - 

Added schedule as following - 
```
salt-call schedule.add test_ping function='test.ping' seconds=10
```
Generated event - 
```
salt/job/20180308091048430549/ret/salt-master {
    "_stamp": "2018-03-08T14:10:48.431949",
    "arg": [],
    "cmd": "_return",
    "fun": "test.ping",
    "fun_args": [],
    "id": "xoas",
    "jid": "20180308091048430549",
    "pid": 3630,
    "return": true,
    "schedule": "test_ping",
    "success": true,
    "tgt": "salt-master",
    "tgt_type": "glob"
}
```

@gtmanfred thought this issue was reported already. I searched a combination of terms "job, schedule[r] and retcode" and didn't find this exact issue. 

### Versions Report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment] 2018-03-08 16:30
Duplicate of https://github.com/saltstack/salt/issues/36466

Looks like someone tried to fix it in that issue, can you provide include this information over there?

Thanks,
Daniel

**Closed by gtmanfred** 2018-03-08 16:30 UTC
