### ISSUE TITLE
file encoding is not working

### ISSUE THREAD

**Issue by robert8103** [saltstack/salt#48522] opened 2018-07-11 14:42 UTC
### state.file encoding issue
I use an utf8 encoded file with special chars like `ä,ü,ö,ß,Ä,Ü,Ö,...`

if i do a salt run  I'll get this error
```bash
minion1:
    Data failed to compile:
----------
    Rendering SLS 'base:my_users.husers' failed: Jinja error: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 389, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 18, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)

; line 18

---
[...]
    - template: jinja
    - encoding: UTF-8
    - context:
      firstName: {{ user.firstName }}
      lastName: {{ user.lastName }}
      userName: {{ name }}    <======================
    - source:
      - salt://my_users/files/user.json
{% endfor %}

Traceback (most recent call last):
[...]
---
```
### Setup
the file is qute simple it looks like this:
```yaml
users:
  hpueckel:
    firstName: Herbert
    lastName: Pückel
```
the command file gives me this:
```bash
root@saltmaster:~# file -b --mime /srv/pillar/my_users/hpueckel.sls
text/plain; charset=utf-8 
```
and the formula looks like this:
```jinja
# vim: sts=2 ts=2 sw=2 et ai
{% for name, user in pillar.get('users', {}).items()
        if user.absent is not defined or not user.absent %}
create_{{ name }}_json:
#  file.managed:
    - name: {{ "/opt/my_user/{}.json".format(name) }}
    - user: root
    - group: root
    - makedirs: True
    - mode: 600
    - template: jinja
    - encoding: UTF-8
    - context:
      firstName: {{ user.firstName }}
      lastName: {{ user.lastName }}
      userName: {{ name }}
    - source:
      - salt://my_users/files/user.json
{% endfor %}
```
a second try with: `file.serialize`
```jinja
# vim: sts=2 ts=2 sw=2 et ai
{% for name, user in pillar.get('users', {}).items()
        if user.absent is not defined or not user.absent %}
{%- set huser = {'firstName': user.firstName,
                  'lastName': user.lastName,
                  'adUsername': name} -%}
create_{{ name }}_json:
  file.serialize:
    - name: {{ "/opt/my_user/{}.json".format(name) }}
    - user: root
    - group: root
    - makedirs: True
    - mode: 600
    - formatter: json
    - encoding: utf8
    - dataset: {{ huser }}
{% endfor %}
```
a `# cat hpueckl.json` results in this:
```json 
{
  "adUsername": "hpueckl",
  "firstName": "Herbert",
  "lastName": "P\\xc3\\xbcckl"
}
```
### Steps to Reproduce Issue
implent the pillar and the formular

### Versions Report
```bash
root@saltmaster:~# salt 'minion1' test.versions_report
minion1:                                                           
    Salt Version:
               Salt: 2018.3.2
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.3
                ZMQ: 4.2.1
     
    System Versions:
               dist: debian 9.4 
             locale: UTF-8
            machine: x86_64
            release: 4.9.0-6-amd64
             system: Linux
            version: debian 9.4 
```

**Comment by noelmcloughlin** [comment] 2018-07-11 16:11
Might be related to #37906.  

I was getting same error on FreeBSD (Salt 2018.3.1) ..`'ascii' codec can't decode byte 0xe2 in position 2912: ordinal not in range(128)`. Fixed by setting lang to utf-8 in my unix environment like this.
```
cat i /usr/home/vagrant/.login_conf
me:\
        :charset=UTF-8:\
        :lang=en_US.UTF-8:\
        :setenv=LC_COLLATE=C:
```

**Comment by robert8103** [comment] 2018-07-12 12:30
@noelmcloughlin here are my env vars so it doesn't seem a problem with the language:
```
root@minion1:~# env
LC_PROMPT=fade
LANG=en_US.UTF-8
SUDO_GID=1000
USERNAME=root
SUDO_COMMAND=/bin/bash
SSH_AUTH_SOCK=/tmp/ssh-GGasPuxUyh/agent.989
USER=root
PWD=/root
HOME=/root
LC_CTYPE=de_AT.UTF-8
SUDO_USER=vagrant
SUDO_UID=1000
LESSSECURE=1
MAIL=/var/mail/root
SHELL=/bin/bash
TERM=screen
SHLVL=1
LOGNAME=root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```

**Comment by terminalmage** [comment] 2018-07-12 15:10
@robert8103 I can't reproduce this. If you could reproduce in something more portable, like a vagrant box, then I can take a closer look. It seems that you have a UTF-8 locale already, which is why this doesn't make a lot of sense.

**Comment by markuskramerIgitt** [comment] 2018-07-17 15:09
Why is ASCII the default codec, and not UTF8?

**Comment by terminalmage** [comment] 2018-07-18 16:45
Because that's just the way Python 2 is distributed: https://github.com/python/cpython/blob/2.7/Lib/site.py#L466-L483

**Comment by pruiz** [comment] 2018-08-13 03:31
I have the same issue and I can't seem to make it work. I have an sls file emitting output taken from pillar, and as long as it contains non-ascii chars, it goes havok.

From what I see, 2018.3.2 no longer takes 'yaml_utf8' into account. All references to 'yaml_utf8' have gone away at: https://github.com/saltstack/salt/commits/develop/salt/renderers/yaml.py

Is this yaml_utf8 removal on purpose?

**Comment by damon-atkins** [comment] 2018-08-17 18:26
yaml_utf8  it was removed with the effort to convert all of Salt PY2 and PY3 to support Unicode, and Unicode the internal string structure of salt.

**Comment by terminalmage** [comment] 2021-01-18 18:03
I think this issue can be closed as obsolete. With Python 2 support dropped, and Python 3 having UTF-8 as its default codec, there should be no need to use the `encoding` argument. Further, I tested this on Python 3.6 with unicode characters passed into the Jinja context, and the error does not occur.

**Comment by twangboy** [comment] 2023-09-06 21:46
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!

**Closed by twangboy** 2023-09-06 21:46 UTC
Labels: Bug, severity-medium
