### ISSUE TITLE
Better error message for "'pkg.installed' was not found in SLS ..."

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#35410] opened 2016-08-12 09:32 UTC
### Description of Issue/Question

If the linux distribution was not detected, then the following error message occurs:

```
State 'pkg.installed' was not found in SLS '...'
Reason: 'pkg' __virtual__ returned False
```

My favorite search engine returns several pages for this. The error seems to affect several people.

See https://www.google.de/search?q=State+%27pkg.installed%27+was+not+found+in+SLS

It would be very nice to get a better error message.

Maybe something like this:

_grains.get os_family returned "SuperLinux". This distribution is unknown. Please see ... how to support unknown distributions._

I tried to find the matching part in the source code, but failed.

BTW, here is the solution to support unknown distributions: https://github.com/saltstack/salt/issues/33475

**Comment by Ch3LL** [comment] 2016-08-15 17:00
@guettli this is a duplicate of #31678 The comment in that issue will explain further how we will be able to extend better messaging particularly for `pkg.installed`. I will close this issue so we can track the issue in 31678. Please feel free to comment on that issue. Thanks.

**Closed by Ch3LL** 2016-08-15 17:00 UTC

**Comment by guettli** [comment] 2016-08-16 07:31
@Ch3LL  thank you for keeping the bird eye view on all those tickets. I will follow the other issue.
