### ISSUE TITLE
route error

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#34298] opened 2016-06-27 07:04 UTC
### Description of Issue/Question

I cannot set a static route via salt module

salt state.apply gets stuck since network cannot come back up

I have to take the vmware console to "sudo ifup eth0"

(also the line route is note added to /etc/network/interfaces)

syslog:

```
Jun 27 08:55:05 dathomir networking[954]: Deconfiguring network interfaces...SIOCDELRT: No such process
Jun 27 08:55:05 dathomir networking[954]: run-parts: /etc/network/if-down.d/route-eth0 exited with return code 7
Jun 27 08:55:05 dathomir networking[954]: SIOCDELRT: No such process
Jun 27 08:55:05 dathomir networking[954]: run-parts: /etc/network/if-down.d/route-eth0 exited with return code 7
Jun 27 08:55:05 dathomir networking[954]: done.
Jun 27 08:55:07 dathomir networking[985]: Configuring network interfaces...SIOCADDRT: Network is unreachable
Jun 27 08:55:07 dathomir networking[985]: run-parts: /etc/network/if-up.d/route-eth0 exited with return code 7
Jun 27 08:55:07 dathomir networking[985]: ifup: post-up script failed.
```
### Setup

I create what should be the equivalent of  
sudo route add -net 192.168.2.0 netmask 255.255.255.0 gw 192.168.1.1
it should be added to /etc/network/interfaces and rans on the command line to work

```
  network.routes:
    - name: eth0
    - routes:
      - name: vpn_return
        ipaddr: 192.168.2.0       <----- this is actually a network, not an ip addr
        netmask: 255.255.255.0
        gateway: 192.168.1.1
```
### Steps to Reproduce Issue

on minion : 
sudo salt.call -l debug state.apply
### Versions Report

latest

**Comment by Ch3LL** [comment] 2016-06-27 17:51
@phil123456 is there any useful data in the salt-minion debug logs when this occurs? 
its seems from looking at your log that there is an issue with bringing up the route. What OS are you in because depending on the OS salt will add the routes to different files. For example if on a redhat/centos distro it will show up in `/etc/sysconfig/network-scripts/route-*`. Does the data in that file look appropriate for when adding a route? 

Also if you do restart network is it working? Is the only issue is that it needs to be restarted. I'm just trying to determine if the route is actually working. Thanks

**Comment by phil123456** [comment] 2016-06-28 12:18
I use debian and if I use the route command on the cli and/or add it in /etc/network/interfaces, it works

but the network.route module does not add that line to /etc/network/interfaces

and I did not find any info in the minion log file

**Comment by nilstoedtmann** [comment] 2016-09-15 19:10
We experienced a similar (same?) issue with salt 2016.3.1 with the Minion being Ubuntu 16.04 (_Xenial_). The problem is probably present anywhere the Minion uses systemd.

The cause is the `/etc/network/if-{up,down}.d/route-NETIF` scripts which _salt.states.network.routes_ drops - it's buggy. It runs each time _any_ interface is upped or downed. But if it's run for the 'wrong' interface, it has a non-zero exit code!

E.g. if you have a _salt.states.network.routes_ statement like this:

```
my_static_routes:
  network.routes:
    - name: eth2
    ...
```

That results in a `/etc/network/if-up.d/route-eth2` like this:

```
#!/bin/sh
route add [...] dev eth2
```

Which will be called and give a non-zero exit code e.g. on `ifup eth0` (either because eth2 is up and the route already exists, or because eth2 down and the route can't be added).

The init system of Ubuntu 14.04 and probably most other SysV-based init systems are pretty lenient with hooks having a non-zero exit code, which is probably why no one has complained yet.

But systemd is strict and considers `ifup eth0` failed if one of the hooks fails. This results in all sorts of side effects, e.g. systemd declaring `networking.service` as failed, which then leads to salt issues in turn.

**Comment by nilstoedtmann** [comment] 2016-09-15 21:45
The simplest way to fix `/etc/network/if-{up,down}.d/route-NETIF` would be to suffix the route command with something like ` || true`  or  `; exit 0`. 

The proper would be to observe the `$IFACE` var that `ifup` is passing to the hook. Something like this:

```
#!/bin/sh
[ "${IFACE}" = "eth2" ]   ||   exit 0
route add ...

```

**Comment by nilstoedtmann** [comment] 2016-09-15 22:06
Looks like this is a duplicate of https://github.com/saltstack/salt/issues/36208 which was fixed 5 days ago by https://github.com/saltstack/salt/commit/59e81bc877624ef782c954fd8d43cf53c988e5ab

**Comment by Ch3LL** [comment] 2016-09-16 16:35
@phil123456 mind giving that fix a try and we can close this as a duplicate?

**Comment by phil123456** [comment] 2016-09-19 06:28
ok

**Comment by rallytime** [comment] 2016-11-04 22:03
@phil123456 Were you able to give that fix a try as suggested above?

**Closed** 2016-11-06 23:39 UTC
Labels: Duplicate, Fixed Pending Verification, Info Needed

**Comment by phil123456** [comment] 2016-11-07 06:43
nop, never tried it again, I used append to add the line to the "interfaces" file
