### ISSUE TITLE
Salt-Cloud reactor highstate event failing after 2016.3.3 upgrade

### ISSUE THREAD

**Issue by sc250024** [saltstack/salt#36614] opened 2016-09-27 20:32 UTC
Salt-Cloud reactor highstate event failing after 2016.3.3 upgrade

### Description of Issue/Question

I'm running Salt Master in AWS, and using Salt-Cloud to provision machines. After upgrading to 2016.3.3 release of Salt, I've noticed that the `salt/cloud/*/created` reactor event is not working as expected anymore. In my `/etc/salt/master` config, I have the following:

```
reactor:
  - 'salt/minion/*/start':
    - /path/to/salt/reactor/sync_grains.sls
  - 'salt/cloud/*/created':
    - /path/to/salt/reactor/startup_highstate.sls
```

If I run a pre-built profile using the `salt-cloud -p some-profile new-machine.infra.company.com`, the machine is created, and the custom grains are synced, but the initial `state.highstate` never runs; I have to manually SSH into the machine, and run the command myself.

### Setup

All relevant files are below:

/etc/salt/cloud: https://gist.github.com/sc250024/575cbae238b012ece95fa03fb8456e2b
/etc/salt/cloud.providers.d/amazon-aws.conf: https://gist.github.com/sc250024/73d1afcf3e010a568f6068ecde69aa7c
/etc/salt/cloud.profiles.d/example-profile.conf: https://gist.github.com/sc250024/63530010776609bcea286801d4074f28
/path/to/salt/reactor/startup_highstate.sls: https://gist.github.com/sc250024/b15ce602ebc9c88be29666755ffd9998
/path/to/salt/scripts/provisioning.sh: https://gist.github.com/sc250024/515084dc0391172baa1c9206e479b2cd

Logs from minion that was just set up:

/var/log/salt/minion: https://gist.github.com/sc250024/0971141dc5e0aac77a29bcfd216e5554

### Steps to Reproduce Issue

1. Configure AWS provisioning using the example `/etc/salt/cloud.providers.d/amazon-aws.conf` above
2. Place the above snippet of the `salt/cloud/*/created` block into your Salt master config underneath the `reactor:` block
3. Use the base `salt-cloud` settings from the `/etc/salt/cloud` snippet above
4. Place the `startup_highstate.sls` into your configured `reactor` directory
5. Place the `provisioning.sh` script in a location that can be reference by the profile
6. Setup the example profile listed above as `/etc/salt/cloud.profiles.d/example-profile.conf`
7. Run `salt-cloud -p example-profile test-machine-name` to run the provisioner; note that the `state.highstate` command is not executed

### Versions Report

Salt Master versions report: https://gist.github.com/sc250024/03d2da9c234ee55d16b42721042c2fc0
Newly created Salt Minion versions report: https://gist.github.com/sc250024/9395f5e2051334daef5d9df6fa98b819

**Comment by rallytime** [comment] 2016-09-27 21:06
HI @sc250024 Thank you for filing this. This is a duplicate of #36055 and has been fixed by #35855. The fix for this issue will be available in the next release of 2016.3, which will be 2016.3.4. 

Since this is a duplicate and has already been fixed, is it alright if we close this ticket?

**Comment by sc250024** [comment] 2016-09-27 23:17
@rallytime Go ahead and close. Thank you very much for the prompt response!

**Comment by rallytime** [comment] 2016-09-27 23:38
@sc250024 Ok! Thank you for following up and filing this. :)

**Closed by rallytime** 2016-09-27 23:38 UTC
Labels: Bug, Duplicate, Fixed Pending Verification, High Severity, P1, RIoT, Salt-Cloud
