### ISSUE TITLE
Salt syndic architecture is slow

### ISSUE THREAD

**Issue by claudiupopescu** [saltstack/salt#19864] opened 2015-01-20 10:04 UTC
Hi,

I found something extremely close to what I have right now and the same problem: http://stackoverflow.com/questions/27925274/3-level-topology-with-saltstack-salt-syndic-performs-very-slowly

1. Salt master
2. Salt master + syndic + minion
3. Sal minion

When I run test.ping from 1 (which is master of master) it returns true for all hosts but before exiting it waits around 10 more seconds.

Is there any one else with this problem? If so is some bug or something not configured correctly?
For me this started happening since I enabled: order_masters on the master of master without having the lower level master connected.
I thought it will go away after I connect a lower level master but it did not.

**Comment by claudiupopescu** [comment] 2015-01-20 10:38
Update:
If the minion on syndic has as master localhost (itself) it is working properly.

**Comment by rallytime** [comment] 2015-01-20 22:09
@claudiupopescu Thanks for filing this report. This is a known issue internally, but I don't think we have any issues open for it. Basically what is happening here is we are not getting information back from the syndics on what minions we expect to come back the way we do on a regular master-minion setup. If the high-level master doesn't have any expectation of what minions to match on, the CLI exists immediately. So, instead of just immediately exiting from the CLI, we decided to hard-code the timeout in order for there to be time to post the output from the minions as it comes in. (Basically what was happening before we hard-coded this timeout was that the returns we coming in to the high master, but that data wasn't displaying on the CLI as it was exiting immediately.)

We definitely need to get this fixed up.

**Comment by andygrunwald** [comment] 2015-03-05 13:24
We can confirm this issue as well.
@rallytime Can you name the source (file / line) were you added that hardcoded timeout?
Do you got some more detailed information about this issue? That we got the chance to investigate?

**Comment by MakaHost** [comment] 2015-03-05 18:03
I went through the history and was able to identify the line that adds the timeout if the server is a syndic. You can find it here:
https://github.com/saltstack/salt/blob/43e69d2842c34cfb49b8997c7c3d5b378b43406a/salt/client/__init__.py#L945

**Comment by rallytime** [comment] 2015-03-05 18:09
@andygrunwald I don't think anyone has gotten a chance to look at this yet, but the change to the timeout was made in pull request #16962, specifically commit f997d24cfad5ec9e71a96079973c871fc4772696. A larger discussion about this change can be found in #16939.

**Comment by rallytime** [comment] 2015-03-12 22:40
I have been looking into this more, and it is definitely very slow. I have:
- 1 "Super Master" that also has a minion on it (nt-master)
- 1 syndic
- 2 minions below the syndic (nt-min1 and nt-min2)

I timed the execution of a simple test.ping, which clocked in at 15 seconds! o.O
```
time salt '*' test.ping
nt-master:
    True
nt-m2:
    True
nt-m1:
    True

real	0m15.473s
user	0m0.404s
sys	0m0.138s
```
This is at the current HEAD of the 2014.7 branch.

Essentially the behavior I am seeing is that all of the minions return with in the first 1-2 seconds, and then the CLI hangs for the remaining 15 seconds, as the majority of you have already reported. I am bumping the severity on this.

**Comment by andygrunwald** [comment] 2015-03-12 22:43
Thanks. We can confirm this issue.
If we can help (stack traces, profiling, testing, etc) please let us know.
We will do our best

Am Donnerstag, 12. März 2015 schrieb Nicole Thomas :

**Comment by rallytime** [comment] 2015-03-12 22:46
Thanks @andygrunwald! It's definitely a known issue...I just didn't realize HOW slow it was. We'll let ya know when we have something to test.

**Comment by claudiupopescu** [comment] 2015-03-13 07:59
@rallytime you should multiply those 15 seconds with an orchestration file calling ~30 different states and modules. Even small and fast actions are extremely slow when using this architecture.

**Comment by bechtoldt** [comment] 2015-03-13 08:07
The pseudo timeout on every salt CLI run definitely leads to a bad user experience.

**Comment by rallytime** [comment] 2015-03-13 14:24
@claudiupopescu Yes, in 2014.7.0 when this need for the CLI timeout was first introduced, the wait was only ~5 seconds. Which, while annoying, was not unreasonable assuming we fixed it. However, now it's clearly much longer than that and certainly unreasonable. 

In my testing, I have discovered that if, on your "Super Master(s)", you comment out the 2 lines under [this comment](https://github.com/saltstack/salt/blob/43e69d2842c34cfb49b8997c7c3d5b378b43406a/salt/client/__init__.py#L945), you can get the timeout down to 10 seconds instead of 15. *However!* Be advised that I have only tested this on simple commands like test.ping on my simple setup of master/syndic/minions noted above. I don't anticipate that this will cause many problems, but definitely try it on a testing environment first. This is only a bandaid for a deeper problem, but it may help alleviate some of the waiting here immediately until we can get this fixed properly.

@claudiupopescu Also, after re-reading your first reports(s) I wanted to clarify what you meant by "If the minion on syndic has as master localhost (itself) it is working properly." I have not tested this case yet, but basically are you saying that if you have a master, syndic, AND a minion on the same machine and you point the minion to `master: localhost` in the minion config file, the timeout goes away? Is that still correct? I also just realized that I never asked you what version of Salt you were seeing this on. Where are you testing this all (`salt --versions-report`)? Are you on a specific version or perhaps on the 2014.7 branch somewhere?

**Comment by claudiupopescu** [comment] 2015-03-13 15:01
Sorry about that one, I forgot to remove that message after figuring out what I was doing wrong :)
I had all the configs automatically generated (including master config for salt) and at a point in time when testing I made a mistake and removed order_masters: True
Reason for that second report which was wrong.

**Comment by rallytime** [comment] 2015-03-13 15:13
Ok perfect. I just wanted to make sure my assumptions were correct. My assumptions were "this problem resolves around setting `order_masters: True` which didn't jive with what you were saying about configuring the minion on the syndic. Thanks for clarifying!

**Comment by andygrunwald** [comment] 2015-03-13 16:01
@rallytime We got the same issue. Here is a `salt --versions-report`:

```
           Salt: 2014.7.2
         Python: 2.7.9 (default, Mar  4 2015, 14:41:42)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
Maybe this helps.

**Comment by cachedout** [comment] 2015-03-17 23:20
I have a fix for this but it's on a machine that doesn't have network access right now. (Long story.)

There were a number of issues causing this but the way it works is as follows:

1) Top-level master published command
2) Client begins gathering returns as they appear
3) Lower-level masters begin replying with lists of expected minion returns
4) Client waits the length of ```syndic_wait``` for those masters to reply. (There is no way to currently to retry if they do not reply, since the upper-level master does not know how many syndics are beneath it. This is a potential future enhancement but won't be included in this release.)
5) If all minions in the list(s) returned by lower-level master have returned, the client exits after 5s, which is the ```syndic_wait``` time (see step 4).
6) If all minions have not returned, the regular ```find_job`` logic kicks in.

I will submit the fix first thing tomorrow morning.

**Comment by rallytime** [comment] 2015-03-18 21:48
After testing the fixes above from @cachedout, we have determined that the syndic architecture is now much more stable. However, the "slow architecture" remains an issue. 

Basically what is happening is when the syndic does not have a minion installed on it (as the current docs say is possible, and indeed it is) the syndic (without the minion) acts as a minion to the master. The syndic ends up in the master's expected minions list, even though it won't return since it's not actually a minion, which causes the timeouts to extend until the limit is reached. According to @thatch45, this has been an issue with the syndic even since syndic was created.

The workaround for this is simply to install a minion along with the syndic. This will reduce the amount of CLI wait time back to the expected behavior of ~5 seconds as a default value. This can be further tuned, as stated by @cachedout above, in the `syndic_wait` value.

**Comment by rallytime** [comment] 2015-03-18 22:09
I have added some documentation to the syndic topology in the pull request above to reflect the discussion in this thread.

**Comment by andygrunwald** [comment] 2015-03-19 08:26
Thanks for the updates, works and merging!

Is there a plan to release v2014.07.3 and/or v2015.2.1 (with this fix included?).
We would love to test this :)

**Comment by rallytime** [comment] 2015-03-19 14:58
@andygrunwald Glad that is working better for you. And yes, there are plans for this fix to be in both a 2014.7.3 and a 2015.2.0 release.

**Comment by andygrunwald** [comment] 2015-03-19 14:59
@rallytime I saw that the fix is integrated in both versions, but my question was related to a (maybe) planned release date of this versions.

**Comment by rallytime** [comment] 2015-03-19 15:03
Oh, sorry I misunderstood. We don't have a fixed date for these releases yet, but we're trying to get them both out ASAP. There are a couple of blocking bugs (this was one of them) that we need to fix before the releases happen. As soon as we can resolve those, we'll be releasing each version.

**Closed** 2015-03-19 16:24 UTC
Labels: Bug, Fixed Pending Verification, High Severity

**Comment by Colstuwjx** [comment] 2015-06-24 09:10
sorry, @rallytime , I setup the syndic_wait option and setup the salt-minion daemon on syndic-master, but I still find out the MasterOfMaster is so slow to gather job data..

All Salt version is 2014.7.5.
It will be better if you update to doc:https://docs.saltstack.com/en/latest/topics/topology/syndic.html

thanks.
