### ISSUE TITLE
[loggers] sentry crashes on KeyError: 'grains.get' when configured (minion side)

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#28301] opened 2015-10-26 14:53 UTC
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 181, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 728, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 651, in setup_extended_logging
    handlers = get_handlers_func()
  File "/usr/lib/python2.7/dist-packages/salt/log/handlers/sentry_mod.py", line 195, in setup_handlers
    tag_value = __salt__['grains.get'](tag)
KeyError: 'grains.get'
```

```
~# salt-minion --versions-report
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.1.2
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 15.04 vivid
        machine: x86_64
        release: 3.19.0-31-generic
         system: Ubuntu 15.04 vivid
 
```

**Comment by Ch3LL** [comment] 2015-10-26 22:48
@arthurlogilab thanks for the report. Will you also post the relevant portions of your master or minion config.

**Comment by arthurlogilab** [comment] 2015-10-27 08:09
```
sentry_handler:
  servers:
    - https://sentry.example.org
  public_key: XXX
  secret_key: XXX
  project: 11
  timeout: 10
  context: #tags
    - os
    - master
    - saltversion
    - cpuarch
```

**Comment by Ch3LL** [comment] 2015-10-30 21:05
@arthurlogilab thanks for the additional information :)

**Comment by cachedout** [comment] 2015-11-05 23:00
When does this error happen? I'm able to paste that Senty config into a 2015.8.0 minion and it starts just fine.

**Comment by cachedout** [comment] 2016-05-17 20:57
@arthurlogilab did you just have a Meetup on Sentry not too long agao? I assume it was working for that. I'm closing this since I can't reproduce it. If it's still broken, let me know and we'll take another swing at it.

**Closed by cachedout** 2016-05-17 20:57 UTC
Labels: Bug, Core, High Severity, Loader, P4
