### ISSUE TITLE
docker-registries authentication seemingly failing when using dockerng.image_present 

### ISSUE THREAD

**Issue by cgiroua** [saltstack/salt#41581] opened 2017-06-05 16:16 UTC
### Description of Issue/Question
Using a private registry, and dockerng.image_present, the minion either seems to not be using the correct auth, or not using it at all, in order to connect to that private registry ... I hit the following issue(s):

- Pull fails for -any- new image with the following error (using a test image here):
     Comment: Encountered error pulling <my_registry>/busybox:latest: Pull failed for <my_registry>/busybox:latest. Error(s) follow:
              
              Error: image busybox:latest not found

- The pull also fails to find changes, when run against existing images (which have changed):
     Comment: Image '<my_registry></my/path/my_image>:latest' was pulled, but there were no changes

I am assuming (possibly incorrectly) they are both due to the same authentication issue, if that's the case then the second message is a bit misleading.

### Setup
From `pillar.items`:
```
    docker-registries:
        ----------
        <my_registry>:
            ----------
            email:
                <my_email>
            password:
                <my_password>
            username:
                <my_username>
```

<my_statefile>.sls:
```
test-image:
    dockerng.image_present:
        - name: '<my_registry>/busybox'
        - force: True
```

I have verified doing a manual `docker login` with the above credentials allows me to successfully pull the images mentioned above to the minion/host experiencing the issue.

I have also verified there is no issue using the above configuration with saltstack to pull busybox from the public dockerhub (it's only having issues with the private registry)

### Steps to Reproduce Issue
-Setup a private registry/configuration as above to access it
-Configure dockerng.image_present with an image in that registry
-Run the test-image state

The logs unfortunately just repeat the output from above, even on debug.

### Versions Report
2016.11.5 on both master/minion

I had seen this issue before when I had an older master/newer minion mismatch, and by upgrading the master/downgrading the issue went away.  However I needed some of the new fixes from this minion version, so I brought them both up to the current 'latest'.  The configurations were not touched in between the working version pair and the upgrade.

**Comment by Ch3LL** [comment] 2017-06-05 18:51
@cgiroua you state that this was working preivously. Which version was that?

**Comment by cgiroua** [comment] 2017-06-05 20:40
@Ch3LL I'm not 100% sure of my previous functioning versions (I've been playing around with a lot of combinations), but trying out what I have available ... both 2016.11.4 & 2016.11.5 masters appear to pull images fine with a 2015.8.8 minion.

**Comment by nfillot** [comment] 2017-06-14 13:28
Hello @Ch3LL @cgiroua 

I think the problem comes from the 2016.11.4 release.
The minion is able to pull the image (module dockerng.pull) with 2016.11.3 and not with 2016.11.4

In 2016.11.3, image_wrapper was handling the login for registries : 
https://github.com/saltstack/salt/blob/v2016.11.3/salt/modules/dockerng.py#L1007

In 2016.11.4, the logic changed and image_wrapper got replaced by client_wrapper but the login function never gets called by the pull function

https://github.com/saltstack/salt/blob/v2016.11.4/salt/modules/dockerng.py#L3937

**Comment by peterloron** [comment] 2017-09-07 23:20
Yes, we need a login (explicit or otherwise) in states.dockerng

**Comment by Ch3LL** [comment] 2017-09-26 17:01
@terminalmage if i remember correctly you were doing some work with local registries within docker. Do you know what version that was resolved in?

**Comment by terminalmage** [comment] 2017-09-26 19:41
>Yes, we need a login (explicit or otherwise) in states.dockerng
No, we don't. docker-py caches the login session, and can read from your ~/.docker/config.json (which is why a `dockerng.login` function was added).

**Comment by terminalmage** [comment] 2017-09-26 19:50
@cgiroua You've left out the most important information. What is the registry URL (the part before `/busybox`)? Where is the versions report?

My guess is that the code that we use to parse the registry URL and image name is not identifying the proper image name.

I can't reproduce failure to pull _any_ image, like you describe. If you can provide the info I requested above, it'll help me troubleshoot.

**Comment by terminalmage** [comment] 2017-11-22 06:34
The changes to image handling in https://github.com/saltstack/salt/pull/44638 fix this issue, as we now simply resolve the image down to an ID, and pull if that image ID is not present. This fix will be in the Oxygen release, due in January.

**Closed by terminalmage** 2017-11-22 06:34 UTC
Labels: Info Needed
