### ISSUE TITLE
[BUG] Salt masterless reactor_niceness key error

### ISSUE THREAD

**Issue by litnimax** [saltstack/salt#57701] opened 2020-06-17 19:03 UTC
**Description**
Works with 3000.3 and does not work with 3001.
I use minion reactor that now does not start due to KeyError.

```
19:00:50 - salt.utils.process:786 - ERROR - An un-handled exception from the multiprocessing process 'Reactor-1:2:1' was caught:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt/utils/process.py", line 777, in wrapped_run_func
    return run_func()
  File "/usr/local/lib/python3.6/dist-packages/salt/utils/reactor.py", line 240, in run
    if self.opts["reactor_niceness"] and not salt.utils.platform.is_windows():
KeyError: 'reactor_niceness'
19:00:50 - salt.engines:140 - CRITICAL - Engine 'reactor' could not be started!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt/engines/__init__.py", line 135, in run
    self.engine[self.fun](**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/engines/reactor.py", line 35, in start
    salt.utils.reactor.Reactor(__opts__).run()
  File "/usr/local/lib/python3.6/dist-packages/salt/utils/process.py", line 791, in wrapped_run_func
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/salt/utils/process.py", line 777, in wrapped_run_func
    return run_func()
  File "/usr/local/lib/python3.6/dist-packages/salt/utils/reactor.py", line 240, in run
    if self.opts["reactor_niceness"] and not salt.utils.platform.is_windows():
KeyError: 'reactor_niceness'
```

**Comment by max-arnold** [comment] 2020-06-18 06:43
Probably related to https://github.com/saltstack/salt/pull/57365

Cc: @mattp-

**Comment by xeacott** [comment] 2020-06-18 17:45
@litnimax Thanks for the issue here. @max-arnold it looks like that PR was merged and the code is there, however this is indicating that the `reactor_niceness` var is not present in his opts. Any suggestions here?

**Comment by mattp-** [comment] 2020-06-18 18:16
this seems odd. i just tried running from git on the v3001 tag and it was fine. how did you install salt / what packaging?

**Comment by mattp-** [comment] 2020-06-18 18:20
regardless of the actual issue, if you put reactor_niceness: 0 in your config it should work as before (unless something is _really_ wrong)

**Comment by litnimax** [comment] 2020-06-19 06:26
I installed with pip. So it did not create me the default configs.
Also I use masterless reactor. So this option should go to minion conf.
But anyway I think if ``self.opts.get("reactor_niceness", 9)`` will be better.

**Comment by mattp-** [comment] 2020-06-22 13:03
ah, didnt notice the title said masterless. i actually had no idea this was a thing, but if its instantiating a reactor with minion_opts it would explain the failure. your suggestion would work but really the default should be in config/__init__.py for minion opts if reactor can be used in this way.

**Comment by sagetherage** [comment] 2020-08-05 18:18
No default in the config - confirming the bug with help fr Gareth, moving to approved, can be picked up by the community or Core Team in Magnesium, but not committed unless a PR is opened, otherwise I will set it for consideration in Aluminium.

**Comment by sagetherage** [comment] 2020-08-05 18:20
I stand corrected -- this is a regression, moving to commit to work this in Magnesium release.

**Closed** 2021-02-19 19:55 UTC
Labels: Aluminium, Bug, Regression
