### ISSUE TITLE
Nova driver broken for 2015.8.[1-3]

### ISSUE THREAD

**Issue by tminn** [saltstack/salt#29666] opened 2015-12-14 14:17 UTC
I upgraded to 2015.8.1 today. My environment is using  centos 7 as OS. 
Using salt-cloud nova driver with Openstack (kilo) is broken . 

--snip--

```
[INFO    ] salt-cloud starting
[WARNING ] /usr/lib/python2.7/site-packages/salt/cloud/clouds/openstack.py:208: DeprecationWarning: This driver has been deprecated and will be removed in the Carbon release of Salt. Please use the nova driver instead.

ostack:
    ----------
    nova:
        ----------
        rundeck_c71:
            ----------
            id:
                6f5175c1-65b7-4344-98aa-508de901bc78
            image:
                73b3c7f8-ec5d-465b-bfbe-7c83adcacb45
            private_ips:
                - 172.16.200.198
                - 10.4.14.175
            public_ips:
            size:
                4
            state:
                ACTIVE
        smaster71:
            ----------
            id:
                fec4086b-37ff-4400-9ffc-711b633a5711
            image:
                73b3c7f8-ec5d-465b-bfbe-7c83adcacb45
            private_ips:
                - 172.16.200.131
                - 10.4.14.179
            public_ips:
            size:
                7
            state:
                ACTIVE
ostack_libcloud:
    ----------
    openstack:
        ----------
        rundeck_c71:
            ----------
            id:
                6f5175c1-65b7-4344-98aa-508de901bc78
            image:
                None
            name:
                rundeck_c71
            private_ips:
                - 172.16.200.198
            public_ips:
                - 10.4.14.175
            size:
                None
            state:
                RUNNING
        smaster71:
            ----------
            id:
                fec4086b-37ff-4400-9ffc-711b633a5711
            image:
                None
            name:
                smaster71
            private_ips:
                - 172.16.200.131
            public_ips:
                - 10.4.14.179
            size:
                None
            state:
                RUNNING
--snip--
```

with libcloud the listing of public and private ip is correct.
with nova driver it is wrong.

Also I'm unable to launch an instance with nova driver.  I get the following message

```
--snip--

 salt-cloud -p centos7_medium  t1
[INFO    ] salt-cloud starting
[INFO    ] Creating Cloud VM t1
[INFO    ] Salt interface set to: False
[INFO    ] Creating Cloud VM t2
[INFO    ] Salt interface set to: False
t1:
    ----------
    Error:
        A valid IP address was not found

--snip--

# My provider config

--snip--
ostack:
  ignore_cidr: 10.4.14.0/24
  minion:
    master: 172.16.200.131
  identity_url: 'http://10.4.13.61:5000/v2.0'
  compute_name: nova
  compute_region: RegionOne
  user: redacted
  tenant: osp
  password: redacted
  driver: nova
  securitygroup: base
  networks:
    - net-id: dc484f4b-65d4-4f28-9d2e-4b43b7990e57       
    - net-id: e4d002b3-9fec-4553-88d4-ab2ff4d5695f
ostack_libcloud:
  ignore_cidr: 10.4.14.0/24
  minion:
    master: 172.16.200.131
  identity_url: 'http://10.4.13.61:5000'
  compute_name: nova
  compute_region: RegionOne
  user: redacted
  tenant: osp
  password: redacted
  driver: openstack
  securitygroup: base
  networks:
    - fixed:
      - dc484f4b-65d4-4f28-9d2e-4b43b7990e57
    - floating:
      - e4d002b3-9fec-4553-88d4-ab2ff4d5695f

--snip--
```

I tested this with salt 2015.8.3 . The results are still the same.

**Comment by Ch3LL** [comment] 2015-12-14 18:05
@tminn thanks for the report.

**Comment by erchn** [comment] 2015-12-15 18:55
I believe this was already fixed by PR #28182

**Comment by rallytime** [comment] 2015-12-15 19:02
Thanks for pointing that out @erchn - that is really helpful.

@tminn The pull request that @erchn referenced above should be available in the 2015.8.3 version of salt. Can you give that a try and let us know if you're still seeing problems?

**Comment by tminn** [comment] 2015-12-18 14:30
I can confirm the issue persist on 2015.8.3

**Comment by rallytime** [comment] 2015-12-18 15:52
Thanks for checking @tminn.

@erchn If you've got some free cycles, it'd be swell if you could take a look at this one again, since you've been helping out on the Nova driver. If not, that's ok, too, and we can grab it later.

**Comment by erchn** [comment] 2015-12-18 18:28
Technically @tminn your provider config should be setting `ssh_interface: private_ips`, even though the 10 net IP is listed under private.  I believe that the openstack driver working is actually a bug.  I would try setting the ssh_interface configuration and try again, it should ignore the 10.4.x.x address as you'd expect, and choose the 172.16.x.x interface.

**Comment by erchn** [comment] 2015-12-18 18:47
I take it back, it's not a bug, but I believe it's due to the use of "floating IPs", which are assigned by default to the public_ips list, when found.  That functionality doesn't seem to exist in Nova, at least not in the Nova clouds wrapper.  But setting private_ips should solve the vm creation issue.

**Comment by tminn** [comment] 2015-12-21 07:33
I have set ssh_interface: private_ips in my profile conf. I will test if this option has an effect when done it is configured under provider.

--snip-- 
centos7_medium:
  driver: ostack
  size: m1.medium
  image: 86f60c96-447f-47ff-b686-35ac8ff4fa69
  ssh_interface: private_ips
  ignore_cidr: 10.4.14.0/24
  ssh_username: cclusr
  key_name: stack-rsa
  ssh_key_name: stack-rsa
  ssh_key_file: /home/salt/opstack/ssh/stack_rsa
  delete_sshkeys: True
  sync_after_install: all
  flush_mine_on_destroy: True
  script: /etc/salt/cloud.deploy.d/deploy.sh
--snip--

**Comment by tminn** [comment] 2015-12-29 15:38
I can confirm. The moving the config  "ssh_interface: private_ips" to provider has no effect.

**Comment by pass-by-value** [comment] 2016-01-11 20:46
Hi @tminn could you please run the salt cloud command in the debug mode and post the output? Something like `salt-cloud -p centos7_medium  t1 -l debug` would be great.

**Comment by tminn** [comment] 2016-01-19 13:35
Hi.

I switched to git branch and the status quo remains.
--snip--
(salt)[salt@smaster ~]$ salt-cloud --version 
salt-cloud 2015.8.3-5104-gdc95b28 (Beryllium)
--snip--
 

--snip--
 salt-cloud -p centos7_small    t1  -l debug
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad nova.optimize_providers
[DEBUG   ] The 'nova' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Generating minion keys for 't1'
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'centos7_small', 'event': 'starting create', '_stamp': '2016-01-19T13:10:01.773731', 'name': 't1', 'provider': 'ostack:nova'}
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[INFO    ] Creating Cloud VM t1
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-01-19T13:10:02.430101', 'event': 'requesting instance', 'kwargs': {'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984', 'name': 't1', 'size': u'3'}}
[DEBUG   ] Waiting for VM IP. Giving up in 00:10:00.
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Loaded node data for t1:
{'_uuid': None,
 'addresses': {},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'6e445e0e-44cc-4ee9-835c-1e7dc129dee6',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'BUILD'}
[DEBUG   ] Waiting for VM IP. Giving up in 00:09:50.
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Loaded node data for t1:
{'_uuid': None,
 'addresses': {},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'6e445e0e-44cc-4ee9-835c-1e7dc129dee6',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'ERROR'}
[DEBUG   ] Waiting for VM IP. Giving up in 00:09:40.
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Loaded node data for t1:
{'_uuid': None,
 'addresses': {},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'6e445e0e-44cc-4ee9-835c-1e7dc129dee6',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'ERROR'}
--snip--
Eventually I hav to wait for timeout. 
Salt-cloud returns 
--snip--
        t1:
            ----------
            id:
                6e445e0e-44cc-4ee9-835c-1e7dc129dee6
            image:
                67a9d8cf-75ca-482b-8213-16fcdc2f4984
            private_ips:
            public_ips:
            size:
                3
            state:
                ERROR
--snip--
If I comment the network options .. , I can launch VM  but it does not get a floating IP.

--snip--

--snip--

 --snip--
(salt)[salt@smaster ~]$ salt-cloud -p centos7_small    t1  -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Including configuration from '/etc/salt/cloud.conf.d/basic.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.conf.d/basic.conf
[DEBUG   ] Missing configuration file: /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/backend.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/backend.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/fileserver.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/fileserver.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/mine.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mine.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/useracl.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/useracl.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: smaster.novalocal
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/openstack.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/openstack.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos6_medium.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos6_medium.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos6_small.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos6_small.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos6_xlarge.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos6_xlarge.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos7_medium.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos7_medium.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos7_small.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos7_small.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/centos7_xlarge.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/centos7_xlarge.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/cirros_nano.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/cirros_nano.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/trusty_small.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/trusty_small.conf
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Including configuration from '/etc/salt/master.d/backend.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/backend.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/fileserver.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/fileserver.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/mine.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mine.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/useracl.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/useracl.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad nova.optimize_providers
[DEBUG   ] The 'nova' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Generating minion keys for 't1'
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'centos7_small', 'event': 'starting create', '_stamp': '2016-01-19T13:22:57.109229', 'name': 't1', 'provider': 'ostack:nova'}
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[INFO    ] Creating Cloud VM t1
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-01-19T13:22:57.791095', 'event': 'requesting instance', 'kwargs': {'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984', 'name': 't1', 'size': u'3'}}
[DEBUG   ] Waiting for VM IP. Giving up in 00:10:00.
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Loaded node data for t1:
{'_uuid': None,
 'addresses': {},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'a59d5a9c-f630-48f0-8ef7-cc04cfce6b9a',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'BUILD'}
[DEBUG   ] Waiting for VM IP. Giving up in 00:09:50.
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Loaded node data for t1:
{'_uuid': None,
 'addresses': {u'osp_5000': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:34:a8:c9',
                              u'OS-EXT-IPS:type': u'fixed',
                              u'addr': u'172.16.200.159',
                              u'version': 4}]},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'a59d5a9c-f630-48f0-8ef7-cc04cfce6b9a',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'ACTIVE'}
[DEBUG   ] Waiting for VM IP. Giving up in 00:09:40.
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Loaded node data for t1:
{'_uuid': None,
 'addresses': {u'osp_5000': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:34:a8:c9',
                              u'OS-EXT-IPS:type': u'fixed',
                              u'addr': u'172.16.200.159',
                              u'version': 4}]},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'a59d5a9c-f630-48f0-8ef7-cc04cfce6b9a',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'ACTIVE'}
[DEBUG   ] Waiting for VM IP. Giving up in 00:00:10.
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Loaded node data for t1:
{'_uuid': None,
 'addresses': {u'osp_5000': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:34:a8:c9',
                              u'OS-EXT-IPS:type': u'fixed',
                              u'addr': u'172.16.200.159',
                              u'version': 4}]},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'a59d5a9c-f630-48f0-8ef7-cc04cfce6b9a',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'ACTIVE'}
[DEBUG   ] Waiting for VM IP. Giving up in 00:00:00.
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Loaded node data for t1:
{'_uuid': None,
 'addresses': {u'osp_5000': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:34:a8:c9',
                              u'OS-EXT-IPS:type': u'fixed',
                              u'addr': u'172.16.200.159',
                              u'version': 4}]},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'a59d5a9c-f630-48f0-8ef7-cc04cfce6b9a',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'ACTIVE'}
[DEBUG   ] Waiting for VM IP. Giving up in 00:-1:50.
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[DEBUG   ] Loaded node data for t1:
{'_uuid': None,
 'addresses': {u'osp_5000': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:34:a8:c9',
                              u'OS-EXT-IPS:type': u'fixed',
                              u'addr': u'172.16.200.159',
                              u'version': 4}]},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'a59d5a9c-f630-48f0-8ef7-cc04cfce6b9a',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'ACTIVE'}
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-01-19T13:34:18.224235', 'name': 't1', 'event': 'destroying instance'}
Version 1.1 is deprecated, using alternative version 2 instead.
[WARNING ] Version 1.1 is deprecated, using alternative version 2 instead.
[INFO    ] Clearing Salt Mine: t1, False
[INFO    ] Destroying VM: t1
[INFO    ] Destroyed VM: t1
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-01-19T13:34:19.160726', 'name': 't1', 'event': 'destroyed instance'}
Error: There was a profile error: Unable to get IP for 00:10:00.
--snip--

hth

**Comment by gtmanfred** [comment] 2016-01-19 19:43
I am currently in the process of rewriting all of this to use the openstack-infra/shade library, so this should be fixed in the first 2016 release.  

https://github.com/saltstack/salt/pull/30335

It will be relying more heavily on upstream, and should have better support for the calls to make to openstack (it will also remove the constant querying of instance status by salt-cloud, and will handle all that with `wait=True`, and also handles the assignment of floating ips to the nodes during boot)

**Comment by tminn** [comment] 2016-01-20 07:07
Thanks gtmanfred, I will be willing to test it in 3 weeks . I'm offline from tommorrow.
Is there a reason for moving away from libcloud ? It was functional and in 2015.8 it is totally borked.

**Comment by pass-by-value** [comment] 2016-02-03 20:59
@tminn I'm concerned why the private and public ip's are `[]` (from your debug log above)

```shell
{'_uuid': None,
 'addresses': {u'osp_5000': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:34:a8:c9',
                              u'OS-EXT-IPS:type': u'fixed',
                              u'addr': u'172.16.200.159',
                              u'version': 4}]},
 'extra': {'access_ip': u'', 'metadata': {}},
 'id': u'a59d5a9c-f630-48f0-8ef7-cc04cfce6b9a',
 'image': u'67a9d8cf-75ca-482b-8213-16fcdc2f4984',
 'name': u't1',
 'private_ips': [],
 'public_ips': [],
 'size': u'3',
 'state': u'ACTIVE'}
```

Could you please check this instance in the dashboard to see if there's any error reported there?

I wasn't able to test the Nova driver with floating ips or `networks`.

I had better luck specifying networks using the Openstack driver instead. My testing env for this driver doesn't have floating ip support though.

**Comment by gtmanfred** [comment] 2016-02-11 06:19
there was a mistake in the NovaServer class that only put the networks named 'public' or 'private' in the public_ips and private_ips.

#31120 fixes that, and will sort the ips when making the server object, so this one should be fixed, because it can now just fall back to using the private_ips.

The other change was fixing letting ssh_interface specify which network to use the ip from, so you could specify 'osp_5000' if you had more than one interface attached.

**Comment by gtmanfred** [comment] 2016-02-12 17:17
Can you check if this pr fixes your problems https://github.com/saltstack/salt/pull/31120 ?

Thanks
Daniel

**Comment by tminn** [comment] 2016-02-18 09:39
Could you tell me this pr is in 2015.8.7 or should I test 2016.3 ?

**Comment by gtmanfred** [comment] 2016-02-18 12:01
It will vein 2015.8.8 and 2016.3.1

**Comment by rallytime** [comment] 2016-02-18 18:24
This change will be in 2015.8.8 as stated above, but I recently did a merge-forward to the 2016.3 branch in #31322, which includes this fix. So it will be available in 2016.3.0, too. :)

**Comment by tminn** [comment] 2016-02-19 14:03
Checked could not find tags/v2015.8.8 but works for 2016.3. Now I can deploy an instance without floating IP

--snip--
[salt@smaster salt(keystone_adm)]$ salt-cloud --version 
salt-cloud 2016.3.0rc1-1178-g64707d1 (Boron)
--snip--

The issue I'm running into is same as before. Please see output from Jan 19. What works for now is I can pass private network uuid in Network and It does work without floating-ip. Is there a different synatx for passing floating-ip ?

hth

**Comment by gtmanfred** [comment] 2016-02-19 15:04
For the nova driver, i don't know what the output of a floating ip looks like in the addresses dictionary.

But to attach a floating-ip, you should just have to follow the same format as attaching a private network, and then put in the stuff that you would pass to novaclient for that.

```
                 [--nic <net-id=net-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,port-id=port-uuid>]
--
  --nic <net-id=net-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,port-id=port-uuid>
                                Create a NIC on the server. Specify option
                                multiple times to create multiple NICs. net-
                                id: attach NIC to network with this UUID
                                (either port-id or net-id must be provided),
                                v4-fixed-ip: IPv4 fixed address for NIC
```

**Comment by tminn** [comment] 2016-02-22 10:07
I think, I know why this might be happening. We need a mechanism to specify that we need to associate floating ip.

This is what is happening on compute_node of Openstack

--snip--
2016-02-22 11:01:18.963 14649 WARNING nova.compute.resource_tracker [-] [instance: ed3f4495-8354-4595-b96c-998b736fba9e] Node field should not be set on the instance until resources have been claimed.
2016-02-22 11:01:18.964 14649 AUDIT nova.compute.claims [-] [instance: ed3f4495-8354-4595-b96c-998b736fba9e] Attempting claim: memory 1024 MB, disk 10 GB
2016-02-22 11:01:18.964 14649 AUDIT nova.compute.claims [-] [instance: ed3f4495-8354-4595-b96c-998b736fba9e] Total memory: 64158 MB, used: 12800.00 MB
2016-02-22 11:01:18.964 14649 AUDIT nova.compute.claims [-] [instance: ed3f4495-8354-4595-b96c-998b736fba9e] memory limit: 51326.40 MB, free: 38526.40 MB
2016-02-22 11:01:18.965 14649 AUDIT nova.compute.claims [-] [instance: ed3f4495-8354-4595-b96c-998b736fba9e] Total disk: 22345 GB, used: 210.00 GB
2016-02-22 11:01:18.965 14649 AUDIT nova.compute.claims [-] [instance: ed3f4495-8354-4595-b96c-998b736fba9e] disk limit not specified, defaulting to unlimited
2016-02-22 11:01:18.992 14649 AUDIT nova.compute.claims [-] [instance: ed3f4495-8354-4595-b96c-998b736fba9e] Claim successful
2016-02-22 11:01:19.311 14649 INFO nova.scheduler.client.report [-] Compute_service record updated for ('cn01.novalocal.de', 'cn01.novalocal.de')
2016-02-22 11:01:19.377 14649 INFO nova.scheduler.client.report [-] Compute_service record updated for ('cn01.novalocal.de', 'cn01.novalocal.de')
2016-02-22 11:01:19.401 14649 ERROR nova.compute.manager [-] Instance failed network setup after 1 attempt(s)
2016-02-22 11:01:19.401 14649 TRACE nova.compute.manager Traceback (most recent call last):
2016-02-22 11:01:19.401 14649 TRACE nova.compute.manager   File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1708, in _allocate_network_async
2016-02-22 11:01:19.401 14649 TRACE nova.compute.manager     dhcp_options=dhcp_options)
2016-02-22 11:01:19.401 14649 TRACE nova.compute.manager   File "/usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py", line 337, in allocate_for_instance
2016-02-22 11:01:19.401 14649 TRACE nova.compute.manager     self._check_external_network_attach(context, nets)
2016-02-22 11:01:19.401 14649 TRACE nova.compute.manager   File "/usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py", line 248, in _check_external_network_attach
2016-02-22 11:01:19.401 14649 TRACE nova.compute.manager     network_uuid=net['id'])
2016-02-22 11:01:19.401 14649 TRACE nova.compute.manager ExternalNetworkAttachForbidden: It is not allowed to create an interface on external network e4d002b3-9fec-4553-88d4-ab2ff4d5695f
2016-02-22 11:01:19.401 14649 TRACE nova.compute.manager 
2016-02-22 11:01:19.531 14649 INFO nova.virt.libvirt.driver [-] [instance: ed3f4495-8354-4595-b96c-998b736fba9e] Creating image
2016-02-22 11:01:19.853 14649 ERROR nova.compute.manager [-] [instance: ed3f4495-8354-4595-b96c-998b736fba9e] Instance failed to spawn
--snip--

hth

**Comment by gtmanfred** [comment] 2016-02-22 14:44
That will be coming in the rewrite with shade

**Comment by tminn** [comment] 2016-02-22 16:28
Thanks. I'm willing to test the shade rewrite. Is shade implementation planned for 2016.30? For now I'm sticking with 2015.5.x release as 2015.8.x is broken for my usecase.

**Comment by gtmanfred** [comment] 2016-02-22 17:40
It won't be in until the next major release, so the next 2016 release

**Comment by cachedout** [comment] 2016-06-03 17:07
@gtmanfred Could you please update this with information about what did and didn't make it into 2016.3 that might solve this issue?

**Comment by gtmanfred** [comment] 2016-06-03 17:26
fixes for public_ip and private_ip made it into 2016.3.

associating the floating_ip works in some cases but has a race condition sometimes if your cloud is fast enough that I am working on fixing in 2015.8 and 2016.3 soonish.

**Comment by gtmanfred** [comment] 2016-11-11 18:41
closing this because 2016.11 rc2 is out, please go test it.

**Closed by gtmanfred** 2016-11-11 18:41 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P3, RIoT, Salt-Cloud, TEAM RIoT
