### ISSUE TITLE
archive.extracted failing even though specified user exists

### ISSUE THREAD

**Issue by jsandas** [saltstack/salt#38175] opened 2016-12-08 23:30 UTC
I have been using several states using the archive.extracted module for several months with no problems, but recently I started getting an error saying "User root does not exist."  The user "root" obviously exists.  I did try looking through the source code and couldn't find anything that should be failing when it tries to get the uid for root in the file.user_to_uid function.  
Any help would be appreciated.

The following is one of the states in question:
nexus:
  archive.extracted:
    - name: /usr/
    - source: https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.1.0-04-unix.tar.gz
    - skip_verify: True
    - archive_format: tar
    - user: root
    - if_missing: /usr/nexus-3.1.0-04/
  file.symlink:
    - name: /usr/nexus
    - target: /usr/nexus-3.1.0-04

This is the output when running from the master:

          ID: nexus
    Function: archive.extracted
        Name: /usr/
      Result: False
     Comment: User root does not exist
     Started: 15:06:09.423586
    Duration: 1.008 ms
     Changes:

And this is the output if running using salt-call on the minion:

[INFO    ] Running state [/usr/] at time 16:27:09.759586
[INFO    ] Executing state archive.extracted for /usr/
[ERROR   ] User root does not exist
[INFO    ] Completed state [/usr/] at time 16:27:09.760435 duration_in_ms=0.849
[INFO    ] Running state [/usr/nexus] at time 16:27:09.760627
[INFO    ] Executing state file.symlink for /usr/nexus
[INFO    ] Symlink /usr/nexus is present and owned by root:root

          ID: nexus
    Function: archive.extracted
        Name: /usr/
      Result: False
     Comment: User root does not exist
     Started: 16:27:09.759586
    Duration: 0.849 ms
     Changes:

**Master Report:**
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Minion Report:**
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by jpohjolainen** [comment] 2016-12-09 09:05
I have same issue. it works after downgrading the minions to 2016.3.4 from 2016.11.0

**Comment by qianlnk** [comment] 2016-12-09 11:43
the same too, I have update salt-minion to 2016.11.0, but it can run at version 2015.8.8.

**Comment by gposton** [comment] 2016-12-09 15:46
yup, same for me version is 'salt-minion 2016.11.0 (Carbon)'

**Comment by jsandas** [comment] 2016-12-09 17:11
Downgrading is not a very appealing possibility for me.  This would seem like a normal procedure to have the owner of the extracted archive be root.

**Comment by Ch3LL** [comment] 2016-12-09 17:38
@jsandas this is a duplicate of #37969 and has been fixed in pr #38004

**Closed by Ch3LL** 2016-12-09 17:38 UTC
