### ISSUE TITLE
Integration testing for Salt-Cloud, Bootstrap-Salt and SaltStack 

### ISSUE THREAD

**Issue by mooperd** [saltstack/salt#25909] opened 2015-07-31 01:15 UTC
It might be sensible to have some kind of integration test to ensure the following sequence works as I'm often finding it broken with new releases. Ideally this should be tested with the stock AMIs / Images and an image with up to date packages.

a) bootstrap-salt bring up master
b) that master can bring up a minion using salt-cloud
c) the master can "state.highstate" the minion.

https://github.com/saltstack/salt/issues/25886

**Comment by thedrow** [comment] 2015-07-31 09:44
This is a duplicate of #20239 :)

**Comment by rallytime** [comment] 2015-07-31 14:20
It's also a duplicate of #8754. As such, I am going to close this issue since the other two have more work and comments being tracked there. If you'd like to add your suggestions to #20239, you're welcome to. Thanks!

**Closed by rallytime** 2015-07-31 14:20 UTC
Labels: Duplicate

**Comment by mooperd** [comment] 2015-08-02 13:51
It is not a duplicate of #8754

**Comment by rallytime** [comment] 2015-08-02 19:06
To clarify, we are already testing use cases (b) and (c) in both the nightly cloud tests as well as our regular integration test suite. Use case (a) is now on QA's list of manual tests for the the time being (until we can get to those automated). This will catch the problems that were caused by the `master_type: str` error noted in #25886.
