### ISSUE TITLE
[BUG] Can't remove pkg inside for loop

### ISSUE THREAD

**Issue by pesc** [saltstack/salt#57543] opened 2020-06-04 11:40 UTC
**Description**
salt3000.3 fails to remove pkg on FreeBSD while inside a for loop -> no problem while using pkg.installed or not deleting pkg's inside a loop

**Setup**
```
{% for i in range(3) %}
   salt3000_test_{{ i }}:
      pkg.removed:
        - pkgs:
          - php{{ i }}
{% endfor %}
```

**Steps to Reproduce the behavior**
```
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.3', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python3.7/site-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/state.py", line 1369, in sls
    _set_retcode(ret, high_)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/state.py", line 107, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
  File "/usr/local/lib/python3.7/site-packages/salt/utils/context.py", line 236, in __getitem__
    return self._dict()[key]
KeyError: 'state.check_result'

```
**Expected behavior (works in salt2019.2)**
```
local:
----------
          ID: salt3000_test_0
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 13:38:01.534142
    Duration: 80.558 ms
     Changes:   
----------
          ID: salt3000_test_1
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 13:38:01.630030
    Duration: 35.614 ms
     Changes:   
----------
          ID: salt3000_test_2
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 13:38:01.680598
    Duration: 35.292 ms
     Changes:   

Summary for local
------------
Succeeded: 3
Failed:    0

Summary for local

```

**Versions Report**
<details><summary>salt --versions-report</summary>
Minion: FreeBSD; Master - Ubuntu; Both 3000.3 

```
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.7 (default, Mar 19 2020, 10:35:02)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.3-RELEASE-p9
         system: FreeBSD
        version: Not Installed
```
</details>

**Comment by pesc** [comment] 2020-06-09 12:45
Some more bugs I think it's related to it:

If I use salt-call to run a single state there's no problem. If I use salt-call to run two independent states it fails: For example if I run the ntp and nginx state on it's own -> no problem. If I combining them there's an error. But if I combining two other states it works

`[root@test:~] 41s 1 # salt-call -l critical state.sls ntp test=true  --state-verbose=false --log-file-level=debug saltenv=salt3000
local:

Summary for local
-------------
Succeeded: 13
Failed:     0
-------------
Total states run:     13
Total run time:  768.352 ms
[root@test:~] 36s # salt-call -l critical state.sls nginx test=true  --state-verbose=false --log-file-level=debug saltenv=salt3000
local:

Summary for local
-------------
Succeeded: 16
Failed:     0
-------------
Total states run:     16
Total run time:  450.024 ms
[root@test:~] 35s # salt-call -l critical state.sls nginx,ntp test=true  --state-verbose=false --log-file-level=debug saltenv=salt3000
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.3', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python3.7/site-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/state.py", line 1369, in sls
    _set_retcode(ret, high_)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/state.py", line 107, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
  File "/usr/local/lib/python3.7/site-packages/salt/utils/context.py", line 236, in __getitem__
    return self._dict()[key]
KeyError: 'state.check_result'
[root@test:~] 42s 1 # salt-call -l critical state.sls ntp,openjdk test=true  --state-verbose=false --log-file-level=debug saltenv=salt3000
local:

Summary for local
-------------
Succeeded: 16
Failed:     0
-------------
Total states run:     16
Total run time:  833.512 ms` 


"Quick fix":
`-ntp_pkgs_deinstalled:
-  pkg.purged:
-    - name: {{ ntp.pkgremove }}
+#ntp_pkgs_deinstalled:
+#  pkg.purged:
+#    - name: {{ ntp.pkgremove }}`

so I guess it's about the same as pkg.removed from above...

**Comment by krionbsd** [comment] 2020-06-15 19:21
OK, let me test this on FreeBSD with pkg.removed, I didn't experience this failure before.

**Comment by pesc** [comment] 2020-06-17 11:04
> OK, let me test this on FreeBSD with pkg.removed, I didn't experience this failure before.

ok, let me know if you need some assistance or any further information

**Comment by krionbsd** [comment] 2020-06-17 14:08
Hmm, I can't reproduce it on 3000.3 + FreeBSD
```
local:
----------
          ID: salt3000_test_0
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 14:07:33.982207
    Duration: 54.891 ms
     Changes:   
----------
          ID: salt3000_test_1
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 14:07:34.053126
    Duration: 32.768 ms
     Changes:   
----------
          ID: salt3000_test_2
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 14:07:34.101775
    Duration: 32.558 ms
     Changes:   

Summary for local
------------
Succeeded: 3
Failed:    0
------------
Total states run:     3
```

**Comment by pesc** [comment] 2020-06-22 11:23
@krionbsd What version of FreeBSD are you using?
I've tested it on 11.3 and the new 11.4 with python 3.7.7 (as shown in version report)

`# salt --versions-report
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.7 (default, Jun 13 2020, 23:04:20)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: freebsd 11.4
         locale: UTF-8
        machine: amd64
        release: 11.4-RELEASE
         system: FreeBSD
        version: FreeBSD 11.4`

What kind of logs would be useful to get the reason of the problem?

**Comment by pesc** [comment] 2020-06-22 11:40
**Debug Log**
<details><summary>salt-call -l debug state.sls test4 test=true --state-verbose=true  saltenv=salt3000</summary>

```
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/salt3000/test4.sls:

   salt3000_test_0:
      pkg.removed:
        - pkgs:
          - test-0

   salt3000_test_1:
      pkg.removed:
        - pkgs:
          - test-1

   salt3000_test_2:
      pkg.removed:
        - pkgs:
          - test-2


[DEBUG   ] Results of YAML rendering:
OrderedDict([('salt3000_test_0', OrderedDict([('pkg.removed', [OrderedDict([('pkgs', ['test-0'])])])])), ('salt3000_test_1', OrderedDict([('pkg.removed', [OrderedDict([('pkgs', ['test-1'])])])])), ('salt3000_test_2', OrderedDict([('pkg.removed', [OrderedDict([('pkgs', ['test-2'])])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/salt3000/test4.sls' using 'yaml' renderer: 0.004225015640258789
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded pkg.removed
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /usr/local/etc/salt/minion_id: [[hostname]]
[DEBUG   ] Could not LazyLoad boto3.assign_funcs: 'boto3.assign_funcs' is not available.
[DEBUG   ] Error loading module.boto3_elasticsearch: __init__ failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 1752, in _load_module
    module_init(self.opts)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/boto3_elasticsearch.py", line 96, in __init__
    __utils__["boto3.assign_funcs"](__name__, "es")
  File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 1278, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/local/lib/python3.7/site-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'boto3.assign_funcs'
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init: 'pkg.ex_mod_init' is not available.
[INFO    ] Running state [salt3000_test_0] at time 13:34:38.771331
[INFO    ] Executing state pkg.removed for [salt3000_test_0]
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[DEBUG   ] LazyLoaded cmd.run_stdout
[INFO    ] Executing command ['pkg', 'info', '-ao'] in directory '/root'
[DEBUG   ] LazyLoaded pkg_resource.add_pkg
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[INFO    ] All specified packages are already absent
[INFO    ] Completed state [salt3000_test_0] at time 13:34:38.890110 (duration_in_ms=118.78)
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init: 'pkg.ex_mod_init' is not available.
[INFO    ] Running state [salt3000_test_1] at time 13:34:38.909839
[INFO    ] Executing state pkg.removed for [salt3000_test_1]
[DEBUG   ] Error loading module.boto3_elasticsearch: __init__ failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 1752, in _load_module
    module_init(self.opts)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/boto3_elasticsearch.py", line 96, in __init__
    __utils__["boto3.assign_funcs"](__name__, "es")
  File "/usr/local/lib/python3.7/site-packages/salt/utils/context.py", line 227, in __getitem__
    return self._dict()[key]
KeyError: 'boto3.assign_funcs'
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.chroot. Module will not be loaded: 'path.which'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 1981, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "/usr/local/lib/python3.7/site-packages/salt/modules/chroot.py", line 34, in __virtual__
    if __utils__["path.which"]("chroot") is not None:
  File "/usr/local/lib/python3.7/site-packages/salt/utils/context.py", line 227, in __getitem__
    return self._dict()[key]
KeyError: 'path.which'
[WARNING ] salt.loaded.int.module.chroot.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'chroot', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.network. Module will not be loaded: 'platform.is_windows'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 1981, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "/usr/local/lib/python3.7/site-packages/salt/modules/network.py", line 38, in __virtual__
    if __utils__["platform.is_windows"]():
  File "/usr/local/lib/python3.7/site-packages/salt/utils/context.py", line 227, in __getitem__
    return self._dict()[key]
KeyError: 'platform.is_windows'
[WARNING ] salt.loaded.int.module.network.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'network', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.rh_service. Module will not be loaded: 'systemd.booted'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 1981, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "/usr/local/lib/python3.7/site-packages/salt/modules/rh_service.py", line 58, in __virtual__
    if __utils__["systemd.booted"](__context__):
  File "/usr/local/lib/python3.7/site-packages/salt/utils/context.py", line 227, in __getitem__
    return self._dict()[key]
KeyError: 'systemd.booted'
[WARNING ] salt.loaded.int.module.rh_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_service', please fix this.
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_timezone. Module will not be loaded: 'platform.is_windows'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 1981, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "/usr/local/lib/python3.7/site-packages/salt/modules/win_timezone.py", line 196, in __virtual__
    if not __utils__["platform.is_windows"]():
  File "/usr/local/lib/python3.7/site-packages/salt/utils/context.py", line 227, in __getitem__
    return self._dict()[key]
KeyError: 'platform.is_windows'
[WARNING ] salt.loaded.int.module.win_timezone.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_timezone', please fix this.
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[INFO    ] All specified packages are already absent
[INFO    ] Completed state [salt3000_test_1] at time 13:34:40.255561 (duration_in_ms=1345.722)
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init: 'pkg.ex_mod_init' is not available.
[INFO    ] Running state [salt3000_test_2] at time 13:34:40.279497
[INFO    ] Executing state pkg.removed for [salt3000_test_2]
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[INFO    ] All specified packages are already absent
[INFO    ] Completed state [salt3000_test_2] at time 13:34:40.328981 (duration_in_ms=49.484)
[DEBUG   ] File /var/cache/salt/minion/accumulator/34683143632 does not exist, no need to cleanup
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'state.check_result'
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3001', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python3.7/site-packages/salt/scripts.py", line 472, in salt_call
    client.run()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/caller.py", line 121, in run
    ret = self.call()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/caller.py", line 229, in call
    self.opts, data, func, args, kwargs
  File "/usr/local/lib/python3.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/state.py", line 1416, in sls
    _set_retcode(ret, high_)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/state.py", line 111, in _set_retcode
    if not __utils__["state.check_result"](ret, highstate=highstate):
  File "/usr/local/lib/python3.7/site-packages/salt/utils/context.py", line 227, in __getitem__
    return self._dict()[key]
KeyError: 'state.check_result'
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3001', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python3.7/site-packages/salt/scripts.py", line 472, in salt_call
    client.run()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/caller.py", line 121, in run
    ret = self.call()
  File "/usr/local/lib/python3.7/site-packages/salt/cli/caller.py", line 229, in call
    self.opts, data, func, args, kwargs
  File "/usr/local/lib/python3.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/state.py", line 1416, in sls
    _set_retcode(ret, high_)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/state.py", line 111, in _set_retcode
    if not __utils__["state.check_result"](ret, highstate=highstate):
  File "/usr/local/lib/python3.7/site-packages/salt/utils/context.py", line 227, in __getitem__
    return self._dict()[key]
KeyError: 'state.check_result'
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
```
</details>

**Comment by krionbsd** [comment] 2020-06-22 15:05
Now I can reproduce it on FreeBSD 13 and Salt 3001
It seems every salt-call and state invocation has this flaw right now

**Comment by pesc** [comment] 2020-06-23 12:12
> Now I can reproduce it on FreeBSD 13 and Salt 3001
> It seems every salt-call and state invocation has this flaw right now

You're right. Not having problem when running it from one of the salt-masters

**Comment by sagetherage** [comment] 2020-10-08 18:47
Closing as fixed and will be released in Magnesium Oct 21, 2020

**Closed by sagetherage** 2020-10-08 18:47 UTC
Labels: Bug, FreeBSD, Magnesium, Regression, Severity: Critical, ZMQ, salt-call

**Comment by pesc** [comment] 2020-11-23 08:15
> Now I can reproduce it on FreeBSD 13 and Salt 3001
> It seems every salt-call and state invocation has this flaw right now

It happen again with 3002.2 - no problem with 3002.1
