### ISSUE TITLE
regression with 2015.5.0: archive.extracted loose executable permission from zip file

### ISSUE THREAD

**Issue by sebest** [saltstack/salt#24006] opened 2015-05-21 00:46 UTC
Hello,

It seems that 2015.5.x switch to the python version of zip instead of using the command line version and it introduces a regression: the executable bits is lost when extracting the file.

You can reproduce it like this:
```
# wget https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip
```

```
pxl|dev-hooky-00v3~# salt-call archive.unzip /root/0.5.0_linux_amd64.zip /root/
local:
    - consul

pxl|dev-hooky-00v3~# ls -la consul
-rw-r--r-- 1 root root 17734417 May 21 00:44 consul

pxl|dev-hooky-00v3~# rm consul

pxl|dev-hooky-00v3~# salt-call archive.cmd_unzip /root/0.5.0_linux_amd64.zip /root/
[INFO    ] Executing command ['unzip', '/root/0.5.0_linux_amd64.zip', '-d', '/root/'] in directory '/root'
local:
    - Archive:  /root/0.5.0_linux_amd64.zip
    -   inflating: /root/consul

pxl|dev-hooky-00v3~# ls -la consul
-rwxr-xr-x 1 root root 17734417 Feb 19 12:31 consul
```

**Comment by sebest** [comment] 2015-05-21 02:46
see https://bugs.python.org/issue15795

**Comment by jfindlay** [comment] 2015-05-21 03:57
@sebest, thanks for the report.  This is a duplicate of #23822.

**Closed by jfindlay** 2015-05-21 03:57 UTC
Labels: Duplicate
