### ISSUE TITLE
Infinite recursion with prereq and check_cmd

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [saltstack/salt#38879] opened 2017-01-23 15:05 UTC
Tried the following scenario (I use it in Ubuntu to prevent services autostart just after package install due to #33442):

```yaml
add-repo:
  cmd.run:
    - name: /bin/true
    - check_cmd:
      - /bin/false

disable-autostart:
  cmd.run:
    - name: /bin/true
    - prereq:
      - cmd: install-pkg

install-pkg:
  cmd.run:
    - name: /bin/true
    - require:
      - cmd: add-repo
```

and got an error:

```
master# salt-ssh server_id state.sls scenario test=true

[ERROR   ] JSON Render failed for: 
Traceback (most recent call last):
  File "/var/tmp/.root_b761f8_salt/salt-call", line 15, in <module>
    salt_call()
  File "/var/tmp/.root_b761f8_salt/py2/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/var/tmp/.root_b761f8_salt/py2/salt/cli/call.py", line 58, in run
    caller.run()
  File "/var/tmp/.root_b761f8_salt/py2/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/var/tmp/.root_b761f8_salt/py2/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/tmp/.root_b761f8_salt/py2/salt/modules/state.py", line 1553, in pkg
    ret = st_.call_chunks(lowstate)
  File "/var/tmp/.root_b761f8_salt/py2/salt/state.py", line 1810, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/var/tmp/.root_b761f8_salt/py2/salt/state.py", line 2095, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/var/tmp/.root_b761f8_salt/py2/salt/state.py", line 2095, in call_chunk
    running = self.call_chunk(low, running, chunks)

..... a lot of same lines .....

  File "/var/tmp/.root_b761f8_salt/py2/salt/state.py", line 2095, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/var/tmp/.root_b761f8_salt/py2/salt/state.py", line 1992, in call_chunk
    low = self._mod_aggregate(low, running, chunks)
  File "/var/tmp/.root_b761f8_salt/py2/salt/state.py", line 762, in _mod_aggregate
    agg_opt = self.functions['config.option']('state_aggregate')
  File "/var/tmp/.root_b761f8_salt/py2/salt/loader.py", line 1086, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/var/tmp/.root_b761f8_salt/py2/salt/utils/lazy.py", line 91, in __getitem__
    if self._missing(key):
RuntimeError: maximum recursion depth exceeded
[ERROR   ] No JSON object could be decoded
```

As you see I tried it in `test` mode and via salt-ssh, so don't know whether it works through salt minion. Seems problem is in interaction of `prereq` with `check_cmd`. If I comment `check_cmd` section or if check command returns `true` (replace `/bin/false` in `check_cmd` with `/bin/true`) recursion error disappears.

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment] 2017-01-23 15:07
Salt Version:
           Salt: 2016.11.1

**Comment by Ch3LL** [comment] 2017-01-24 15:39
@Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk looks to me that this is a duplicate of https://github.com/saltstack/salt/issues/20143   Would you agree?

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment] 2017-01-24 15:50
Yes, you are right, this issue slightly extends #20143 (with `check_cmd` and `test` mode).

**Comment by Ch3LL** [comment] 2017-01-24 22:21
Thanks closing now.

**Closed by Ch3LL** 2017-01-24 22:21 UTC
Labels: Duplicate, Info Needed
