### ISSUE TITLE
Restarting both master and minion delays ability to run a command

### ISSUE THREAD

**Issue by pete0emerson** [saltstack/salt#4084] opened 2013-03-13 17:43 UTC
version: dc2f0f3c1928b5ba9197355798a01e923c12f529

If I restart both the master and the minion and then immediately execute a command, the minion does not return:

```
[root@salt]# killall salt-master ; killall salt-minion ; /usr/bin/salt-master -d /usr/bin/salt-minion -d ; time salt -v salt cmd.run date
Executing job with jid 20130313171619907410
-------------------------------------------

salt:
    Minion did not return

real    0m23.188s
user    0m0.327s
sys     0m0.074s
```
Note that there is no output from the job, but it is in the job list:

```
[root@salt]# salt-run jobs.print_job 20130313171619907410
[root@salt]#
[root@salt]# salt-run jobs.list_jobs | grep -A6 "^'20130313171619907410':"
'20130313171619907410':
  Arguments:
  - date
  Function: cmd.run
  Start Time: 2013, Mar 13 17:16:19.907410
  Target: salt
  Target-type: glob
```

The command does *not* get run on the minion, either, based on my testing of

````
[root@salt] # salt -v salt cmd.run 'touch /tmp/test.txt'
[root@salt] # ls /tmp/test.txt
ls: /tmp/test.txt: No such file or directory
```

If I sleep for 30 seconds after starting up the minion, the command works as expected.
If I kill only the master or only the minion with no delay, the command works as expected.

I don't believe that the problem is in the daemonizing, as I can repeat the problem by firing up the master and minion in the foreground.

**Comment by arroyoc** [comment] 2016-01-04 23:03
@pete0emerson @basepi Is this ticket still in question? Looks like there has been a couple years of pause.

**Comment by basepi** [comment] 2016-01-06 00:02
These days, by default, the master will list minions which did not return in the output. So this may be resolved from that point of view.

The rest of the issue is summed up in the myriad other issues we have related to queueing a job until a minion comes up.

I'd be on board with closing this, unless @pete0emerson has concerns.

**Comment by basepi** [comment] 2016-01-06 20:14
(In fact, based on the age of this issue, I'm just going to close it, since it's easy enough to re-open later. :) )

**Closed by basepi** 2016-01-06 20:14 UTC
Labels: Question
