### ISSUE TITLE
Salt minion can't get the apt public key

### ISSUE THREAD

**Issue by colttt** [saltstack/salt#45061] opened 2017-12-18 11:28 UTC
### Description of Issue/Question
I've 2machines with this problem, they cant get  pub-file.
the log file contain the following:
```
2017-12-18 12:19:53,244 [salt.loaded.int.module.cmdmod][ERROR   ][1668] Command '['apt-key', 'add', '/var/cache/salt/minion/extrn_files/base/repo.saltstack.com/apt/debian/9/amd64/2017.7/SALTSTACK-GPG-KEY.pub']' failed with return code: 2
2017-12-18 12:19:53,245 [salt.loaded.int.module.cmdmod][ERROR   ][1668] stderr: Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
2017-12-18 12:19:53,245 [salt.loaded.int.module.cmdmod][ERROR   ][1668] retcode: 2
2017-12-18 12:19:53,246 [salt.state       ][ERROR   ][1668] Failed to configure repo 'deb http://repo.saltstack.com/apt/debian/9/amd64/2017.7 stretch main': Error: failed to add key from https://repo.saltstack.com/apt/debian/9/amd64/2017.7/SALTSTACK-GPG-KEY.pub
```

When I take a look into the file '/var/cache/salt/minion/extrn_files/base/repo.saltstack.com/apt/debian/9/amd64/2017.7/SALTSTACK-GPG-KEY.pub' its empty, I guess here is an error, the URL looks correct to me.

### Setup
```
{% if grains['os'] == 'Debian' %}
saltstack_repo:
  pkgrepo.managed:
    - name: deb http://repo.saltstack.com/apt/{{ salt['grains.get']('os')|lower }}/{{ salt['grains.get']('osmajorrelease')}}/amd64/2017.7 {{ salt['grains.get']('oscodename') }} main
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: https://repo.saltstack.com/apt/{{ salt['grains.get']('os')|lower }}/{{ salt['grains.get']('osmajorrelease')}}/amd64/2017.7/SALTSTACK-GPG-KEY.pub
    - dist: {{ grains['oscodename']|lower }}
    - failhard: true
```

### Steps to Reproduce Issue
Just try my setup above with a debian system..

### Versions Report
```
salt-minion --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.3 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.3 
```

**Comment by dynek** [comment] 2017-12-18 15:22
Interesting, I just created my state for saltstack and noticed the same thing. This issue is the only output I got on Google :-)

**Comment by gtmanfred** [comment] 2017-12-18 15:40
Duplicate of https://github.com/saltstack/salt/issues/44013

This is fixed by this https://github.com/saltstack/salt/pull/44016

**Closed by gtmanfred** 2017-12-18 15:40 UTC
