### ISSUE TITLE
Salt build for ubuntu is broken (TypeError: any() takes exactly one argument)

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#25287] opened 2015-07-09 10:31 UTC
This is an issue [filed against the salt-bootstrap script](https://github.com/saltstack/salt-bootstrap/issues/617). Bellow is the copy of it.

Latest ubuntu build from July 2 (2015.5.2) contains a bug:
```
An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
**cdata['kwargs'])
File "/usr/lib/python2.7/dist-packages/salt/states/rabbitmq_vhost.py", line 84, in present
if any(user, owner, conf, write, read):
TypeError: any() takes exactly one argument (5 given)

This is due to a bug in /usr/lib/python2.7/dist-packages/salt/states/rabbitmq_vhost.py which has already been fixed, but the deployment was created on a broken version (v2015.0.2).
```

**Comment by jfindlay** [comment] 2015-07-09 17:42
This is a duplicate of #24524, which has been fixed in 2015.8.3.

**Closed by jfindlay** 2015-07-09 17:42 UTC
Labels: Duplicate, Packaging
