### ISSUE TITLE
salt-cloud should delete static network interfaces when terminating instances

### ISSUE THREAD

**Issue by bengaywins** [saltstack/salt#34675] opened 2016-07-14 17:50 UTC
### Description of Issue/Question

When deploying an instance via salt-cloud in AWS and it fails (for whatever reason) and you have specified an IP for them, when it destroys the failed deploy instances, it does not destroy the created interfaces. Which then results in the following error:

`{'Error': {'Message': 'The specified address is already in use.', 'Code': 'InvalidIPAddress.InUse'}}`
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I could be wrong, but there doesn't seem to be anything relevant in this area.
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
1. Spin up an instance that will fail for any reason with a static IP in ec2.
2. Attempt to spin up same instance again.
3. You will get the error:
   `{'Error': {'Message': 'The specified address is already in use.', 'Code': 'InvalidIPAddress.InUse'}}`
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-28-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by rallytime** [comment] 2016-07-19 18:32
@gehzumteufel Ah, thanks for letting us know. We should get this cleaned up.

ping @techhat and @gtmanfred

**Comment by boltronics** [comment] 2016-10-21 03:56
Confirming I'm experiencing this too. You need to go to the Network Interfaces tab in the EC2 section of the web interface to delete the applicable IP address.

**Comment by rsuarezsoto** [comment] 2016-10-28 08:06
I've stumbled upon this just now. There were several network interfaces hanging around that were not in use, and I had to delete them by hand.

**Comment by dougofthemoment** [comment] 2017-03-23 19:50
I'm seeing this now as well in 2016.11.1

**Comment by gehzumteufel** [comment] 2017-03-23 20:02
When I filed this bug, yes it was in the network interface section of a profile. I don't currently have an example but I will see if I can craft one when I get a chance.

To be clear, this is _only_ a problem if the spin up of an instance fails to complete and it deletes the instance but not the static interface.

**Comment by gtmanfred** [comment] 2017-03-23 22:54
I have replicated this, will look at getting it fixed.

Sorry it took so long to respond.

Thanks,
Daniel

**Comment by gehzumteufel** [comment] 2018-09-25 01:01
I don't know that this has ever been fixed. If it hasn't, it should be left open.

**Comment by boltronics** [comment] 2020-01-10 01:40
I imagine this is still an issue, however I can't remember the last time I had an instance fail to deploy so am not certain.

**Comment by vlebo** [comment] 2020-11-18 21:43
This is still an issue in 3000.3.

 For example creation of an instance with static private IP fails with error `'Message': 'Network interfaces and an instance-level subnet ID may not be specified on the same request'`. On fixing the profile and rerunning it errors with `'Message': 'The specified address is already in use.`

After deleting interfaces it runs fine and creates the machines.

**Comment by sagetherage** [comment] 2021-02-17 22:39
The Core team won't be able to get to this in Aluminium, moving it back into planning for another release.

**Comment by bengaywins** [comment] 2021-02-17 22:55
At this rate it won't ever get fixed. Nothing is on fire enough for it.

**Comment by sagetherage** [comment] 2021-02-18 23:40
@bengaywins yes, true. I wish we had more resources and we will gladly review a PR from the community :)

**Comment by twangboy** [comment] 2023-08-30 22:18
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!

**Closed by twangboy** 2023-08-30 22:18 UTC
Labels: Bug, severity-medium, Salt-Cloud, RIoT

**Comment by bengaywins** [comment] 2023-09-01 19:11
@twangboy That's a pretty terrible result considering someone said it was still a problem in 3000.3 and you're saying that `if the problem persists` but yet nobody has talked about solving this issue in the 7 years its been opened and it seems to persist. Leave it closed or whatever, but imo, all that's happened here is neglect as opposed to anything else.
