### ISSUE TITLE
npm installed breaks when a module is missing

### ISSUE THREAD

**Issue by johtso** [saltstack/salt#18880] opened 2014-12-10 12:59 UTC
Salt version is `2014.7.0rc6` and no changes seem to have been made to the npm state module since.

`npm.list`:
```
    aglio:
        ----------
        missing:
            True
        required:
            *
```

State run:
```
          ID: api_aglio
    Function: npm.installed
        Name: aglio@1.16.2
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/npm.py", line 152, in installed
                  installed_pkgs[pkg_name]['version'])
              KeyError: 'version'
     Started: 12:52:13.735178
    Duration: 762.939 ms
     Changes:
```

**Comment by sbellem** [comment] 2015-03-16 12:17
Sorry, just wondering where I can follow up on this issue, e.g..: is a fix currently available in develop?

Or if I can help in resolving the issue, I'd be glad to help. 

Thanks.

**Comment by rallytime** [comment] 2015-03-16 15:06
@sbellem I don't think anyone has attempted a fix for this issue yet. If you'd like to give it a try, that would be most welcome. Since this bug occurs on the 2014.7 branch, please look at fixing it there, and make the pull request against that branch as well. (We have some useful documentation about that process in our [Contributing docs](http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch), for more info, or I am happy to answer any questions.)

**Comment by sbellem** [comment] 2015-03-16 23:03
@rallytime ok, cool, thanks! Will look into it then.

**Comment by rallytime** [comment] 2015-03-16 23:08
@sbellem Now that I think about it, there may have beens some changes recently to the npm modules and states since the "nothing has changed since 2014.7.0rc6" comment above, though, i can't remember which branch. Either way, it might be worth-while to take a look around at any recent activity surrounding those files on either 2014.7/2015.2/develop.

**Comment by chris-prince** [comment] 2015-05-02 03:04
I encountered this bug today, and I looked into the cause.  I think I see the solution.

In the `_pkg_is_installed()` function, at [`states/npm.py line 125`](../../salt/blob/develop/salt/states/npm.py#L125), it should check for `pkg_name in installed_pkgs` AND ALSO `'version' in installed_pkgs[pkg_name]`

BTW, you can also remove the `if pkg_name in installed_pkgs:` check at [`states/npm.py line 146`](../../salt/blob/develop/salt/states/npm.py#L146), and un-indent the block it was enclosing. That check is completely extraneous, because `_pkg_is_installed()` handles that case.

After making these changes in my local installation, things looked good.

More details:

`npm list` is returning something like this for packages that are required but missing:
```
    "sqlite3": {
      "required": "3.0.5",
      "missing": true
    },
```

Packages that are truly installed have a `version` property.  Missing packages do not.

(Another way to see that this is the right thing to do: the exception being thrown shows a non-existent 'version' property is being accessed:
```
installed_pkgs[pkg_name]['version'] --> KeyError: 'version'
```
The code must be written to never try to access a property that doesn't exist.)

**Comment by rallytime** [comment] 2015-05-02 15:50
That sounds great @chris-prince. Would you mind submitting a pull request with your changes? It would be much appreciated.

**Comment by chris-prince** [comment] 2015-05-02 18:30
Please ignore my 1st referenced commit, but the other three -- one per branch -- should be good to go.

**Closed** 2015-05-03 15:50 UTC
Labels: Bug, Medium Severity
