### ISSUE TITLE
Windows repo HTTP download seems broken in 2015.8

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#27869] opened 2015-10-12 16:00 UTC
On Windows Server 2012 R2 with Salt minion version 2015.8, I can't seem to install any software which requires an HTTP download where a redirect is involved.

For example:-

```
PS C:\salt\var\cache\salt\minion\extrn_files\base\downloads.sourceforge.net\project\winmerge\stable\2.14.0> rm .\WinMerg e-2.14.0-Setup.exe
PS C:\salt\var\cache\salt\minion\extrn_files\base\downloads.sourceforge.net\project\winmerge\stable\2.14.0> C:\salt\salt -call.bat -l debug pkg.install winmerge
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Motherboard info not available on this sytem
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'aws-dev-p-iis-5', 'tcp://192.168.101.7:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (10014)
[DEBUG   ] Setting zmq_reconnect_ivl to '10014ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'aws-dev-p-iis-5', 'tcp://192.168.
101.7:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'aws-dev-p-iis-5', 'tcp://192.168.101.7:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'aws-dev-p-iis-5', 'tcp://192.168.
101.7:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg_resource.parse_targets
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be locate
d
[DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.10 or later must be installed before this module can be used.
']
[DEBUG   ] Error loading module.victorops: No VictorOps api key found.
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'aws-dev-p-iis-5', 'tcp://192.168.
101.7:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'aws-dev-p-iis-5', 'tcp://192.168.101.7:4506')
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] file_roots is c:\salt\srv\salt
[DEBUG   ] file_roots is c:\salt\srv\spm\salt
[DEBUG   ] Requesting URL http://downloads.sourceforge.net/project/winmerge/stable/2.14.0/WinMerge-2.14.0-Setup.exe usin
g GET method
[INFO    ] Executing command ['c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\downloads.sourceforge.net\\project
\\winmerge\\stable\\2.14.0\\WinMerge-2.14.0-Setup.exe', '/SP-', '/verysilent', '/norestart'] in directory 'c:\\salt\\var
\\cache\\salt\\minion\\extrn_files\\base\\downloads.sourceforge.net\\project\\winmerge\\stable\\2.14.0'
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 654, in install
    result = __salt__['cmd.run_stdout'](cmd, cache_path, output_loglevel='trace', python_shell=False)
  File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 1186, in run_stdout
    use_vt=use_vt)
  File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 436, in _run
    .format(cmd, kwargs, exc)
CommandExecutionError: Unable to run command ['c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\downloads.sourcefo
rge.net\\project\\winmerge\\stable\\2.14.0\\WinMerge-2.14.0-Setup.exe', '/SP-', '/verysilent', '/norestart'] with the co
ntext {'with_communicate': True, 'shell': False, 'env': {'TMP': 'C:\\Users\\FMWEBR~1\\AppData\\Local\\Temp\\2', 'COMPUTE
RNAME': 'AWS-DEV-P-IIS-5', 'USERDOMAIN': 'AWS-DEV-P-IIS-5', 'PYTHON': 'C:\\salt\\bin\\python.exe', 'PSMODULEPATH': 'C:\\
Users\\fmwebroot\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\syste
m32\\WindowsPowerShell\\v1.0\\Modules\\;C:\\Program Files (x86)\\AWS Tools\\PowerShell\\', 'COMMONPROGRAMFILES': 'C:\\Pr
ogram Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 62 Stepping 4, GenuineIntel', 'PROGRAMFILES'
: 'C:\\Program Files', 'PROCESSOR_REVISION': '3e04', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Windows\\system32;C:\\Win
dows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Amazon\\cfn-bootstr
ap\\;C:\\ProgramData\\chocolatey\\bin;c:\\Program Files\\Microsoft\\Web Platform Installer\\;C:\\salt\\bin\\lib\\site-pa
ckages\\pywin32_system32', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'TEMP': 'C:\\Users\\FMWEBR~1\\AppData\\Local\
\Temp\\2', 'SCRIPT': 'C:\\salt\\bin\\Scripts\\salt-call', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Fi
les', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'CHOCOLATEYINSTALL': 'C:\\ProgramData\\chocolatey', 'ALLUSERSPROFILE': 'C:\\Pro
gramData', 'SALTDIR': 'C:\\salt', 'LOCALAPPDATA': 'C:\\Users\\fmwebroot\\AppData\\Local', 'HOMEPATH': '\\Users\\fmwebroo
t', 'USERDOMAIN_ROAMINGPROFILE': 'AWS-DEV-P-IIS-5', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'fmwebroot', 'LOGON
SERVER': '\\\\AWS-DEV-P-IIS-5', 'PROMPT': '$P$G', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\\Progr
amData', 'SESSIONNAME': 'RDP-Tcp#0', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL', 'CLIENTNAM
E': '3L8H95J', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'HOMEDRIVE': 'C:', 'APPDATA': 'C:\\Users\\fmwebroot\\A
ppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '4', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\P
rogram Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\fmwebroot'},
'stdout': -1, 'stdin': None, 'stderr': -1, 'cwd': 'c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\downloads.sour
ceforge.net\\project\\winmerge\\stable\\2.14.0'}, reason: [Error 216] This version of %1 is not compatible with the vers
ion of Windows you're running. Check your computer's system information and then contact the software publisher
Error running 'pkg.install': Unable to run command ['c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\downloads.so
urceforge.net\\project\\winmerge\\stable\\2.14.0\\WinMerge-2.14.0-Setup.exe', '/SP-', '/verysilent', '/norestart'] with
the context {'with_communicate': True, 'shell': False, 'env': {'TMP': 'C:\\Users\\FMWEBR~1\\AppData\\Local\\Temp\\2', 'C
OMPUTERNAME': 'AWS-DEV-P-IIS-5', 'USERDOMAIN': 'AWS-DEV-P-IIS-5', 'PYTHON': 'C:\\salt\\bin\\python.exe', 'PSMODULEPATH':
 'C:\\Users\\fmwebroot\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\
\system32\\WindowsPowerShell\\v1.0\\Modules\\;C:\\Program Files (x86)\\AWS Tools\\PowerShell\\', 'COMMONPROGRAMFILES': '
C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 62 Stepping 4, GenuineIntel', 'PROGRAM
FILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3e04', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Windows\\system32;C
:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Amazon\\cfn-b
ootstrap\\;C:\\ProgramData\\chocolatey\\bin;c:\\Program Files\\Microsoft\\Web Platform Installer\\;C:\\salt\\bin\\lib\\s
ite-packages\\pywin32_system32', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'TEMP': 'C:\\Users\\FMWEBR~1\\AppData\\
Local\\Temp\\2', 'SCRIPT': 'C:\\salt\\bin\\Scripts\\salt-call', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Com
mon Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'CHOCOLATEYINSTALL': 'C:\\ProgramData\\chocolatey', 'ALLUSERSPROFILE': 'C
:\\ProgramData', 'SALTDIR': 'C:\\salt', 'LOCALAPPDATA': 'C:\\Users\\fmwebroot\\AppData\\Local', 'HOMEPATH': '\\Users\\fm
webroot', 'USERDOMAIN_ROAMINGPROFILE': 'AWS-DEV-P-IIS-5', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'fmwebroot',
'LOGONSERVER': '\\\\AWS-DEV-P-IIS-5', 'PROMPT': '$P$G', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\
\ProgramData', 'SESSIONNAME': 'RDP-Tcp#0', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL', 'CLI
ENTNAME': '3L8H95J', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'HOMEDRIVE': 'C:', 'APPDATA': 'C:\\Users\\fmwebr
oot\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '4', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432':
'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\fmwebro
ot'}, 'stdout': -1, 'stdin': None, 'stderr': -1, 'cwd': 'c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\download
s.sourceforge.net\\project\\winmerge\\stable\\2.14.0'}, reason: [Error 216] This version of %1 is not compatible with th
e version of Windows you're running. Check your computer's system information and then contact the software publisher
```

I tried running the file directly from the cache, and it fails. I also noticed that the SHA1 hash of the downloaded file is wrong, and it seems to change on every run.

I transfered the file to a Linux box and used hexdump to view the data.

The first few lines of the file show the problem:-

```
00000000  33 30 32 20 46 6f 75 6e  64 0a 0a 54 68 65 20 72  |302 Found..The r|
00000010  65 73 6f 75 72 63 65 20  77 61 73 20 66 6f 75 6e  |esource was foun|
00000020  64 20 61 74 20 68 74 74  70 3a 2f 2f 6e 65 74 69  |d at http://neti|
00000030  78 2e 64 6c 2e 73 6f 75  72 63 65 66 6f 72 67 65  |x.dl.sourceforge|
00000040  2e 6e 65 74 2f 70 72 6f  6a 65 63 74 2f 77 69 6e  |.net/project/win|
00000050  6d 65 72 67 65 2f 73 74  61 62 6c 65 2f 32 2e 31  |merge/stable/2.1|
00000060  34 2e 30 2f 57 69 6e 4d  65 72 67 65 2d 32 2e 31  |4.0/WinMerge-2.1|
00000070  34 2e 30 2d 53 65 74 75  70 2e 65 78 65 3b 20 79  |4.0-Setup.exe; y|
00000080  6f 75 20 73 68 6f 75 6c  64 20 62 65 20 72 65 64  |ou should be red|
00000090  69 72 65 63 74 65 64 20  61 75 74 6f 6d 61 74 69  |irected automati|
000000a0  63 61 6c 6c 79 2e 20 20  4d 5a 50 00 02 00 00 00  |cally.  MZP.....|
000000b0  04 00 0f 00 ff ff 00 00  b8 00 00 00 00 00 00 00  |................|
000000c0  40 00 1a 00 00 00 00 00  00 00 00 00 00 00 00 00  |@...............|
000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000e0  00 00 00 00 00 01 00 00  ba 10 00 0e 1f b4 09 cd  |................|
000000f0  21 b8 01 4c cd 21 90 90  54 68 69 73 20 70 72 6f  |!..L.!..This pro|
00000100  67 72 61 6d 20 6d 75 73  74 20 62 65 20 72 75 6e  |gram must be run|
00000110  20 75 6e 64 65 72 20 57  69 6e 33 32 0d 0a 24 37  | under Win32..$7|
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001a0  00 00 00 00 00 00 00 00  50 45 00 00 4c 01 08 00  |........PE..L...|
000001b0  19 5e 42 2a 00 00 00 00  00 00 00 00 e0 00 8f 81  |.^B*............|
000001c0  0b 01 02 19 00 94 00 00  00 46 00 00 00 00 00 00  |.........F......|
000001d0  40 9c 00 00 00 10 00 00  00 b0 00 00 00 00 40 00  |@.............@.|
000001e0  00 10 00 00 00 02 00 00  01 00 00 00 06 00 00 00  |................|
000001f0  04 00 00 00 00 00 00 00  00 40 01 00 00 04 00 00  |.........@......|
00000200  00 00 00 00 02 00 00 80  00 00 10 00 00 40 00 00  |.............@..|
00000210  00 00 10 00 00 10 00 00  00 00 00 00 10 00 00 00  |................|
00000220  00 00 00 00 00 00 00 00  00 d0 00 00 50 09 00 00  |............P...|
00000230  00 10 01 00 00 2c 00 00  00 00 00 00 00 00 00 00  |.....,..........|
00000240  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000260  00 00 00 00 00 00 00 00  00 f0 00 00 18 00 00 00  |................|
00000270  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

You can see where this comes from:-
```
└──>>http "http://downloads.sourceforge.net/project/winmerge/stable/2.14.0/WinMerge-2.14.0-Setup.exe"
HTTP/1.1 302 Found
Connection: close
Content-Length: 357
Content-Type: text/html; charset=UTF-8
Date: Mon, 12 Oct 2015 15:57:44 GMT
Location: http://kent.dl.sourceforge.net/project/winmerge/stable/2.14.0/WinMerge-2.14.0-Setup.exe
Server: nginx
Set-Cookie: sf_mirror_attempt="winmerge:kent:stable/2.14.0/WinMerge-2.14.0-Setup.exe"; expires=120; Path=/
content-disposition: attachment; filename="WinMerge-2.14.0-Setup.exe"

<html>
 <head>
  <title>302 Found</title>
 </head>
 <body>
  <h1>302 Found</h1>
  The resource was found at <a href="http://kent.dl.sourceforge.net/project/winmerge/stable/2.14.0/WinMerge-2.14.0-Setup.exe">http://kent.dl.sourceforge.net/project/winmerge/stable/2.14.0/WinMerge-2.14.0-Setup.exe</a>;
you should be redirected automatically.


 </body>
</html>
```
It seems that the redirect text is getting prepended to the binary EXE file that is downloaded.

Since downloading software very frequently requires a redirect to a mirror, S3 or a CDN I'd consider this a critical problem.

**Comment by jfindlay** [comment] 2015-10-13 19:55
@johnccfm, thanks for the report.  This is a duplicate of #27093, which has been fixed in 2015.8.1.

**Closed by jfindlay** 2015-10-13 19:55 UTC
Labels: Duplicate
