### ISSUE TITLE
file.recurse doesn't support fallback directories

### ISSUE THREAD

**Issue by rsuarezsoto** [saltstack/salt#13758] opened 2014-06-26 11:52 UTC
Imagine a formula like this:

    /var/www/html/mysite.com:
       file.recurse:
        - source:
          - salt://web/mysite.com/html
          - salt://web/common/html

This should use the first directory as source if it exists, and if not, use the second one. Though a layout like this works for file.managed, it doesn't work for file.recurse. This error pops up:

    Comment: 'source' parameter must be a string

I don't recall seeing anything in the docs relative to this not working, but I haven't seen anything saying that it works either :-) Should this work? Is it in the works?

FWIW, I'm using salt 2014.1.4 on Red Hat 6.5. Thanks in advance.

**Comment by The-Loeki** [comment] 2015-08-04 11:43
Duplicate of #9304, and on 2015.5 it already exhibits this behaviour

**Comment by basepi** [comment] 2015-08-04 17:35
Thanks, @The-Loeki! Keep us posted if this isn't working like you want, @rsuarezsoto, but it appears that this feature is in 2015.5.2 and 2015.8.0.

**Closed by basepi** 2015-08-04 17:35 UTC
Labels: Feature
