### ISSUE TITLE
No notification if member of nodegroup doesn't exist

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#41326] opened 2017-05-18 17:13 UTC
### Description of Issue/Question
If a member of a nodegroup doesn't exist Salt doesn't give any notification of that fact.

For example, if I run a command against a non-existing minion directly I get a notification like this:
```
[me@me ~]$ sudo salt 'ghostminion' test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```
If I set up a nodegroup like this:
```
[me@me ~]$ cat /etc/salt/master.d/nodegroup_info.conf 
nodegroups:
  group1: 'L@dasalt,cent6test,ghostminion'
```
`dasalt` and `cent6test` are minions with their keys accepted by the master. The `ghostminion` doesn't exist at all.
```
[me@me ~]$ sudo salt-key -L
Accepted Keys:
cent6test
dasalt
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```
I shutdown `cent6test` then run a command against the nodegroup.
```
[me@me ~]$ sudo salt -N group1 test.ping
dasalt:
    True
cent6test:
    Minion did not return. [Not connected]
```

There is no mention of the `ghostminion` minion. There should be a notification stating the `ghostminion` is `[Not connected]` or doesn't exist somehow.

I've tested this on 2016.3.5 2016.11.4
```
[me@me ~]$ sudo salt --versions-report
Salt Version:
           Salt: 2016.3.5
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 6.0.1
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: 0.3.7
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-117-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

```
[me@me ~]$ sudo salt --versions-report
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: 0.3.7
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-117-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by UtahDave** [comment] 2017-05-18 17:13
ZD 1365

**Comment by gtmanfred** [comment] 2017-05-18 19:05
Is this a limitation on NodeGroups or on the List Matcher?

Thanks,
Daniel

**Comment by UtahDave** [comment] 2017-05-24 23:37
@gtmanfred honestly, I'm not sure. The example is from a user's nodegroup definition, which happened to use a list.

The behavior seems to be that the Salt Master isn't using the whole nodelist as part of the list of minions expected to return.  Mostly because the missing minion doesn't have an entry in `salt-key -L`.  

Does that help?

**Comment by garethgreenaway** [comment] 2017-06-02 15:18
I spent a bit of time working through this out.  The root of the issue is that the nodegroup matching uses the list matching under the hood and list matching looks for minions that already exist and discards those that don't, then runs the specified command(s) on just those ones that exist.  Sidelined for the moment due to other priorities but I was looking for a way to flag those minions as non-existent and report back as such.

**Comment by garethgreenaway** [comment] 2017-09-13 16:47
@UtahDave I'm going to close this out since the PR was merged.

**Closed by garethgreenaway** 2017-09-13 16:47 UTC
Labels: Bug, Core, High Severity, Oxygen, P3, ZD
