### ISSUE TITLE
2019.2.1 Salt-Minion connection via IPv6 impossible

### ISSUE THREAD

**Issue by piti01** [saltstack/salt#54763] opened 2019-09-26 10:45 UTC
### Description of Issue
Salt-Minion can not connect to master via IPv6 due to missing brackets. 

### Setup
Default Minion Config for Debian Buster without any adjustments.

/etc/hosts looks like:
`2a00:xx:xx:xx::xx    salt`

### Steps to Reproduce Issue

Output from salt-minion -l debug:
`[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'xxxx', 'tcp://2a00:xx:xx:xx::xx:4506', 'clear')`
`[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://2a00:xx:xx:xx::xx:4506`
`[DEBUG   ] Trying to connect to: tcp://2a00:xx:xx:xx::xx:4506`
`[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key`
`[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)
`

Minions who are still on 2019.2.0 do this:
`[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'xxxx', 'tcp://[2a00:xx:xx:xx::xx]:4506', 'clear')`
`[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://[2a00:xx:xx:xx::xx]:4506`
`[DEBUG   ] Trying to connect to: tcp:// [2a00:xx:xx:xx::xx]:4506
`

### Versions Report
```Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.1 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.1```

**Comment by kyentei** [comment] 2019-09-26 11:06
Duplicate of #54762

**Closed** 2019-09-26 19:09 UTC
