### ISSUE TITLE
Mapping git branch to env in ext_pillar throws errors

### ISSUE THREAD

**Issue by lloydoliver** [saltstack/salt#23644] opened 2015-05-13 10:05 UTC
Mapping a git branch to an environment in ext_pillar as mentioned in the docs (http://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html), although working, generates errors in the master log.

For example;
```
ext_pillar:
  - git: develop:base git:salt roots=pillar
```
which seems to be working when running `pillar.items`, however the master logs are showing;

```
2015-05-13 09:45:28,062 [root             ][ERROR   ][23386] Unable to checkout branch develop:base: 'git checkout origin/develop:base' returned exit status 1: error: pathspec 'origin/develop:base' did not match any file(s) known to git.
```

```
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
```

At this stage it doesn't appear to be a major issue, more of a general annoyance. Thought I would raise this in case there is an underlying issue that is not making itself apparent right now.

**Comment by jfindlay** [comment] 2015-05-14 15:18
@lloydoliver, thanks for the report.  I think this is a duplicate of #22681.  If you think it may be different then we can repoen this issue.

**Closed by jfindlay** 2015-05-14 15:18 UTC
Labels: Duplicate
