### ISSUE TITLE
[BUG] 3001 On Ubuntu 18.04, network.managed of bridge interface returns a RuntimeError

### ISSUE THREAD

**Issue by allyunion** [saltstack/salt#57721] opened 2020-06-18 18:14 UTC
**Description**
On Ubuntu 18.04, network.managed of bridge interface returns a RuntimeError

**Setup**

network.sls:
`ifupdown:
  pkg.installed:
    - pkgs:
      - ifupdown

eno1:
  network.managed:
    - enabled: True
    - type: eth
    - bridge: br0

br0:
  network.managed:
    - enabled: True
    - type: bridge
    - proto: dhcp
    - ports: eno1
    - use:
      - network: eno1
    - require:
      - network: eno1
      - pkg: ifupdown
`

**Steps to Reproduce the behavior**
Run salt-call or salt

Error:
`
----------
          ID: eno1
    Function: network.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python3.7/dist-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/local/lib/python3.7/dist-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.7/dist-packages/salt/states/network.py", line 398, in managed
                  old = __salt__["ip.get_interface"](name)
                File "/usr/local/lib/python3.7/dist-packages/salt/modules/debian_ip.py", line 1812, in get_interface
                  adapters = _parse_interfaces()
                File "/usr/local/lib/python3.7/dist-packages/salt/modules/debian_ip.py", line 696, in _parse_interfaces
                  for iface_name in adapters:
              RuntimeError: OrderedDict mutated during iteration
     Started: 18:08:45.817113
    Duration: 3.729 ms
     Changes:
----------
          ID: br0
    Function: network.managed
      Result: False
     Comment: One or more requisite failed: host.network.eno1
     Started: 18:08:45.821613
    Duration: 0.007 ms
     Changes:
`

**Expected behavior**
No errors

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
On the leader:

Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: 4.0.4
      gitpython: 3.1.1
         Jinja2: 2.11.2
        libgit2: 1.0.0
       M2Crypto: 0.35.2
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.6
      pycparser: 2.20
       pycrypto: 3.9.7
   pycryptodome: 3.9.7
         pygit2: 1.2.0
         Python: 3.7.5 (default, Nov  7 2019, 10:50:52)
   python-gnupg: 0.4.6
         PyYAML: 3.12
          PyZMQ: 19.0.0
          smmap: 3.0.2
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-106-generic
         system: Linux
        version: Ubuntu 18.04 bionic

On the follower:
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.5 (default, Nov  7 2019, 10:50:52)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-106-generic
         system: Linux
        version: Ubuntu 18.04 bionic

```
</details>

**Additional context**

**Comment by krionbsd** [comment] 2020-06-22 16:45
@allyunion thank you for reporting that. Could you provide mode details, did the state work for you prior to 3001 on Ubuntu 18?

**Comment by sagetherage** [comment] 2020-08-05 18:13
@allyunion putting this into blocked until we hear more from you - please mention me or krionbsd and we will move forward on this ticket.

**Comment by allyunion** [comment] 2020-08-05 18:43
Yes, it did work prior to 3001.

**Comment by sagetherage** [comment] 2020-08-06 15:12
@krionbsd looks like this might be a regression

**Comment by dmurphy18** [comment] 2022-01-14 01:12
Waiting on PR https://github.com/saltstack/salt/pull/60731 with fix to be merged / reviewed etc

**Closed** 2022-02-04 01:43 UTC
Labels: Bug, Regression, severity-high, Phosphorus v3005.0
