### ISSUE TITLE
salt-ssh:  Unable to import msgpack or msgpack_pure python modules

### ISSUE THREAD

**Issue by jcftang** [saltstack/salt#21226] opened 2015-03-02 17:40 UTC
This had previously worked in the tag v2014.7.1, I just checked out the tip of 2014.7 (as of the time of this post) and now running a "salt-ssh foo state.sls mystate" fails as such

```
# salt-ssh foo-host state.sls update
[ERROR   ] JSON Render failed for:
[CRITICAL] Unable to import msgpack or msgpack_pure python modules
Traceback (most recent call last):
  File "/tmp/.ubuntu_6a7d07__salt/salt-call", line 4, in <module>
    salt_call()
  File "/tmp/.ubuntu_6a7d07__salt/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/tmp/.ubuntu_6a7d07__salt/salt/cli/__init__.py", line 422, in run
    caller.run()
  File "/tmp/.ubuntu_6a7d07__salt/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/tmp/.ubuntu_6a7d07__salt/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/tmp/.ubuntu_6a7d07__salt/salt/modules/state.py", line 947, in pkg
    ret = st_.call_chunks(lowstate)
  File "/tmp/.ubuntu_6a7d07__salt/salt/state.py", line 1602, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/tmp/.ubuntu_6a7d07__salt/salt/state.py", line 1746, in call_chunk
    low = self._mod_aggregate(low, running, chunks)
  File "/tmp/.ubuntu_6a7d07__salt/salt/state.py", line 611, in _mod_aggregate
    agg_opt = self.functions['config.option']('state_aggregate')
KeyError: 'config.option'
[ERROR   ] No JSON object could be decoded
```

With these versions

```
salt-ssh --versions-report
           Salt: 2014.7.2-218-g6577a20
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.5
   msgpack-pure: 0.1.3
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by jfindlay** [comment] 2015-03-02 18:32
@jcftang, thanks for the report.

**Comment by jfindlay** [comment] 2015-03-02 18:35
@jcftang, is it possible for you to provide a state that triggers this?  I am having trouble reproducing the problem, thanks.

**Comment by jcftang** [comment] 2015-03-02 18:38
@jfindlay the state that I am executing is this

```
common_upd:
  pkg:
    - uptodate
    - refresh: True
```

It's a pretty simplistic state, there isn't anything else in it. Also the minions and master are all ubuntu 12.04 based machines. The odd thing is, this failure seems to only occur on my AWS based ubuntu machines. Hope the above helps.

**Comment by jfindlay** [comment] 2015-03-02 20:06
If you're only getting this error on a specific OS under a specific cloud, then it is likely a missing dependency.  How did you install salt?

**Comment by jcftang** [comment] 2015-03-02 20:14
Given that it's salt-ssh, I would not have expected many dependencies apart from python to be present on the targeted machine. Note that I am using salt-ssh from a virtualenv.

**Comment by jfindlay** [comment] 2015-03-02 20:27
Do you have the same problem when you remove `refresh: True`, or try another package?

**Comment by jcftang** [comment] 2015-03-02 20:38
Removing *refresh: True* makes no difference at all, it gives the same error as in the report above.

Running cmd.run update gives this

```
salt-ssh foo-host cmd.run uptime
foo-host:
    ----------
    retcode:
        1
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        Passed invalid arguments: argument of type 'NoneType' is not iterable
    stdout:
```

**Comment by jcftang** [comment] 2015-03-09 09:49
To further add, the tip of 2015.2 and develop has the same problem, however the v2014.7.2 tag works fine.

**Comment by basepi** [comment] 2015-03-13 17:33
@jcftang Can you please show me your roster entry for the machine which is failing, @jcftang? Are you using sudo and/or tty?

**Comment by basepi** [comment] 2015-03-13 17:39
For the record, I can reproduce this on 2014.7, with an Ubuntu 14.04 minion on Linode.

**Comment by basepi** [comment] 2015-03-13 18:15
Should be fixed in #21636. Thanks for the report.

**Comment by jcftang** [comment] 2015-03-13 22:33
@basepi cool, do you still need me to verify the fix or is this good to close?

**Comment by basepi** [comment] 2015-03-13 22:45
Either way. This will close as soon as it gets merged forward into develop.

**Comment by slav0nic** [comment] 2015-09-18 08:39
got 
```
stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'grains.cache_update' is not available.
```
```
salt-ssh  --versions-report
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.10 (default, Jul  1 2015, 10:54:53)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: 1.1.2
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 4.1.0-2-amd64
         system: debian stretch/sid 
```

**Comment by netroby** [comment] 2015-09-25 01:36
ds:
    ----------
    retcode:
        255
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'run.cmd' is not available.
    stdout:
m ~ # salt-ssh --version                  
salt-ssh 2015.8.0 (Beryllium)


still got trouble

**Comment by netroby** [comment] 2015-09-25 01:40
Why salt-ssh can not auto install python-msgpack for us? CentOS, Fedora, Ubuntu,debian both have this package.

**Comment by basepi** [comment] 2015-09-25 15:53
Salt-ssh is designed to run on the target system without any modification. It also is designed to not require msgpack, so I think the error you're getting is a bug we need to fix. Can you please post the error in its entirety? You may have to look at the minion debug logs to find the actual error.

**Comment by moebiuseye** [comment] 2015-11-14 15:00
I'm still experiencing this issue:

``̀`
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2 
```

More details later

**Comment by moebiuseye** [comment] 2015-11-14 15:03
salt-ssh -v '*' pkg.installed less

```
Executing job with jid 20151114160238344801
-------------------------------------------


lxc-snafu-ejabberd:
    ----------
    retcode:
        255
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'pkg.installed' is not available.
    stdout:
lxc-snafu-mpd:
    ----------
    retcode:
        255
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'pkg.installed' is not available.
    stdout:
lxc-snafu-nginx:
    ----------
    retcode:
        255
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'pkg.installed' is not available.
    stdout:
lxc-snafu-transmission:
    ----------
    retcode:
        255
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'pkg.installed' is not available.
    stdout:
lxc-snafu-wheezy-test:
    ----------
    retcode:
        255
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        'pkg.installed' is not available.
    stdout:
```

**Comment by jfindlay** [comment] 2015-11-14 16:10
@moebiuseye, are you able to get any salt-ssh commands to work successfully?  I suspect that this is a slightly different issue, and if so, I can confirm it.

**Comment by netroby** [comment] 2015-11-18 06:52
Long times goes, this bugs still there. affect us.

**Comment by netroby** [comment] 2015-11-18 06:59
```
sudo apt-get install python
sudo apt-get install python-msgpack  
```

This commend will install python and then install msgpack for us.

**Comment by netroby** [comment] 2015-11-18 07:04
First time run salt you may using following command to install python and msgpack module
```bash
salt-ssh hi -r 'sudo apt-get install python && sudo apt-get install python-msgpack'
```

**Comment by moebiuseye** [comment] 2015-11-18 12:07
@jfindlay Hi, I've installed python-msgpack because I didn't have time to wait for an answer. 
I'll reproduce this and post more info this week-end if I find the time. 
@netroby Of course that solves the problem, but to quote @basepi : «Salt-ssh is designed to run on the target system without any modification.»

**Comment by basepi** [comment] 2015-11-18 20:15
@moebiuseye Did installing msgpack resolve your `pkg.installed not available` errors? Looking back, I'm surprised those were related. I think that "critical" error is not actually critical in the case of salt-ssh, but if it was actually interfering with normal salt-ssh runs then I need to investigate more.

**Comment by basepi** [comment] 2015-11-18 22:42
I can reproduce this issue. I'm investigating now.

**Comment by basepi** [comment] 2015-11-19 22:45
Interestingly, installing python-msgpack did not fix pkg.installed for me.

**Comment by basepi** [comment] 2015-11-19 22:57
So I realized my problem. I was using pkg.installed (since that's what @moebiuseye was using in his post) instead of pkg.install, which is the actual remote execution command.

I cannot reproduce this issue. Whether python-msgpack is installed or not, pkg.install works for me. Same with cmd.run.

**Closed** 2015-11-24 01:05 UTC
Labels: Bug, Confirmed, Core, Fixed Pending Verification, High Severity, Regression, Salt-SSH, TEAM Core
