### ISSUE TITLE
Windows service.restart not restarting a process that is already stopped.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#49234] opened 2018-08-21 17:44 UTC
### Description of Issue/Question
On windows when you issue a `service.restart` of the process is already stopped it will throw an error.

Would be nice if that error wasn't fatal and allowed the start function to run effectively starting a stopped process.

### Setup
Setup a service and stop it. Then run service.restart on the service.

### Steps to Reproduce Issue
```
c:\salt\salt-call -l debug --local service.restart postgresql-x64-9.6
winion-0:
    [DEBUG   ] Reading configuration from c:\salt\conf\minion
    [DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
    [DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
    [DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: winion-0
    [DEBUG   ] Configuration file path: c:\salt\conf\minion
    [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
    [DEBUG   ] Grains refresh requested. Refreshing grains.
    [DEBUG   ] Reading configuration from c:\salt\conf\minion
    [DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
    [DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
    [DEBUG   ] Determining pillar cache
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] LazyLoaded service.restart
    [DEBUG   ] LazyLoaded cmd.run
    [INFO    ] Executing command ['net', 'stop', '/y', 'postgresql-x64-9.6'] in directory 'C:\Windows\system32\config\systemprofile'
    [ERROR   ] Command '['net', 'stop', '/y', 'postgresql-x64-9.6']' failed with return code: 2
    [ERROR   ] stdout: The postgresql-x64-9.6 service is not started.



    More help is available by typing NET HELPMSG 3521.
    [ERROR   ] retcode: 2
    [ERROR   ] Command '['net', 'stop', '/y', 'postgresql-x64-9.6']' failed with return code: 2
    [ERROR   ] output: The postgresql-x64-9.6 service is not started.



    More help is available by typing NET HELPMSG 3521.

    Passed invalid arguments: 'error' object does not support indexing.

    Usage:
    Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 449, in stop
        win32serviceutil.StopService(name)
      File "c:\salt\bin\lib\site-packages\win32\lib\win32serviceutil.py", line 409, in StopService
        return ControlService(serviceName, win32service.SERVICE_CONTROL_STOP, machine)
      File "c:\salt\bin\lib\site-packages\win32\lib\win32serviceutil.py", line 320, in ControlService
        status = win32service.ControlService(hs, code)
    pywintypes.error: (1062, 'ControlService', 'The service has not been started.')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 212, in call
        ret['return'] = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 488, in restart
        return stop(name) and start(name)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 451, in stop
        if exc[0] != 1062:
    TypeError: 'error' object does not support indexing

        Restart the named service. This issues a stop command followed by a start.

        Args:
            name: The name of the service to restart.

        .. note::
            If the name passed is ``salt-minion`` a scheduled task is created and
            executed to restart the salt-minion service.

        Returns:
            bool: ``True`` if successful, ``False`` otherwise

        CLI Example:

        .. code-block:: bash

            salt '*' service.restart <service name>
```

### Versions Report
```
winion-0:
    Salt Version:
               Salt: 2018.3.2

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by whytewolf** [comment] 2018-08-21 17:45
ZD-2789

**Comment by damon-atkins** [comment] 2018-08-22 02:34
Just needs to match Linux/Unix behaviour.

**Comment by garethgreenaway** [comment] 2018-08-22 17:34
Looks like this should be a relatively straightforward fix.  Just check if the process is running before attempting to stop it.  @dwoz @twangboy Thoughts?

**Comment by twangboy** [comment] 2018-08-23 22:32
Yeah. I'll add it to my list.

**Comment by twangboy** [comment] 2018-08-25 01:00
The issue is fixed in the above PR. I still need to write some tests for it.

**Closed by twangboy** 2018-08-25 01:00 UTC
Labels: 2018.3.4, Bug, High Severity, P2, Windows, ZD, team-windows
