### ISSUE TITLE
Salt mine does not refresh module output through proxy minion

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#32022] opened 2016-03-21 16:29 UTC
### Description of Issue/Question
It seems that in an environment using proxy minions, the salt mines do not refresh as specified in the pillars configuration file.

### Setup
I have a very simple code to setup a proxy minion (init, shutdown etc):

Filename dummy.py
```
# -*- coding: utf-8 -*-

"""
Dummy proxy
"""

from __future__ import absolute_import

import logging
log = logging.getLogger(__file__)

__proxyenabled__ = ['dummy']


def __virtual__():
    return True


def init(opts):

    return True


def ping(*args, **kw):

    return True


def shutdown(opts, *args, **kw):

    return True
```

This proxy is used in a module called test_mine.py:

```
# -*- coding: utf-8 -*-

from __future__ import absolute_import

import logging
log = logging.getLogger(__file__)

import time

__virtualname__  = 'testmine'
__proxyenabled__ = ['dummy']

def __virtual__():
    return True

def timestamp():

    return {'last_call': time.time()}
```

The configuration pillar is as follows (the proxy minion is called 'mine'):

```
mine_functions:
  testmine.timestamp: []
mine_interval: 1
proxy:
  proxytype: dummy
```

### Steps to Reproduce Issue
I can call testmine.timestamp properly:

```
(virtualenv)root@36netops3:/etc/salt/pillar# salt 'mine' testmine.timestamp
mine:
    ----------
    last_call:
        1458576466.12
```

I can udpate the mine:

```
(virtualenv)root@36netops3:/etc/salt/pillar# salt 'mine' mine.update
mine:
    True
```

I can get the mine content:

```
(virtualenv)root@36netops3:/etc/salt/pillar# salt 'mine' mine.get 'mine' testmine.timestamp
mine:
    ----------
    mine:
        ----------
        last_call:
            1458576511.46
```

But it does not refresh every minute as it should (every minute as specified in the pillar: ```mine_interval: 1```):

```
(virtualenv)root@36netops3:/etc/salt/pillar# date
Mon Mar 21 16:09:30 UTC 2016
(virtualenv)root@36netops3:/etc/salt/pillar# salt mine mine.get 'mine' testmine.timestamp
mine:
    ----------
    mine:
        ----------
        last_call:
            1458576539.17
(virtualenv)root@36netops3:/etc/salt/pillar# date
Mon Mar 21 16:15:44 UTC 2016
(virtualenv)root@36netops3:/etc/salt/pillar# salt mine mine.get 'mine' testmine.timestamp
mine:
    ----------
    mine:
        ----------
        last_call:
            1458576539.17
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.0-139-g2d732c9

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.8
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
         system: debian 8.2
```

**Comment by jfindlay** [comment] 2016-03-22 18:13
@mirceaulinic, thanks for the report.

**Comment by cachedout** [comment] 2016-03-25 21:56
@cro Is this something you could investigate? I'll assign it to you.

**Comment by cro** [comment] 2016-03-25 22:41
Will do

**Comment by cro** [comment] 2016-05-17 19:40
Do you have

``mine_enabled: True``

in your /etc/salt/proxy file?

**Comment by mirceaulinic** [comment] 2016-05-17 20:50
That's all I had in the proxy config file:

```yaml
master: localhost
pki_dir: /etc/salt/pki/proxy
cachedir: /var/cache/salt/proxy
multiprocessing: False
```

I will update it accordingly and I will let you know. Thank you!

**Comment by mirceaulinic** [comment] 2016-05-18 11:16
Yes, they are updating properly now. Many thanks, I was not aware of this config option.

```bash
(virtualenv)root@36netops3:/etc/salt# date
Wed May 18 11:03:23 UTC 2016
(virtualenv)root@36netops3:/etc/salt# salt 'mine' mine.get 'mine' testmine.timestamp
mine:
    ----------
    mine:
        ----------
        last_call:
            1463569375.01
(virtualenv)root@36netops3:/etc/salt# date
Wed May 18 11:10:12 UTC 2016
(virtualenv)root@36netops3:/etc/salt# salt 'mine' mine.get 'mine' testmine.timestamp
mine:
    ----------
    mine:
        ----------
        last_call:
            1463569795.01
```

Is there also an option to adjust the timeout? There are cases when the mines are not updated even from the CLI when trying to refresh big chunks of information:

```bash
root@36netops1:/etc/salt/pillar# salt edge01.sjc01 mine.update
edge01.sjc01:
    Minion did not return. [No response]
```

But when updating using ```-t``` feels better:

```bash
root@36netops1:/etc/salt/pillar# salt edge01.sjc01 mine.update -t 180
edge01.sjc01:
    True
```

Is there an equivalent such as ```mine_timeout``` or something similar that can be added in the config file(s)?

Thank you very much!

**Comment by mirceaulinic** [comment] 2016-05-18 13:34
Is it enough to set a different ```timeout``` value in ```/etc/salt/master``` config file or is there anything more specific?

**Comment by mirceaulinic** [comment] 2016-05-18 14:24
Was this fixed in ```2016.3``` by any chance? I tried the same configuration as above on two different platforms:

```bash
(virtualenv)root@36netops3:/etc/salt# salt --version
salt 2016.3.0-290-gd110115 (Boron)
```

Is the Salt instance that updated the mines (in my previous comment).

While, on a different machine running Beryllium:

```bash
root@36netops1:~# salt --version
salt 2015.8.3 (Beryllium)
```

It looks like the mines are not updated:

```bash
root@36netops1:~# date
Wed May 18 14:12:20 UTC 2016
root@36netops1:~# salt mine mine.get 'mine' testmine.timestamp
mine:
    ----------
    mine:
        ----------
        last_call:
            1463580725.74
root@36netops1:~# date
Wed May 18 14:18:59 UTC 2016
root@36netops1:~# salt mine mine.get 'mine' testmine.timestamp
mine:
    ----------
    mine:
        ----------
        last_call:
            1463580725.74
```

I have exactly the same config on both, except:

```mine_enabled: True``` in ```/etc/salt/proxy```, 
```timeout: 300``` in ```/etc/salt/master```.

**Comment by cro** [comment] 2016-05-18 14:54
Re: timeouts, the core issue there is probably `multiprocessing: False` since you are using ssh-based proxies, correct?  You can turn up the timeout in /etc/salt/master (https://docs.saltstack.com/en/latest/ref/configuration/master.html#timeout).

Note that the timeout only represents how long the CLI will wait for the minion to return.  The job is still running on the minion--it doesn't get terminated.  So your mines still get updated, they just take longer than the CLI is willing to wait.

re: mine_enable in 2016.3, yes this was a 2016.3 feature.  I backported it to 2015.8 last night but it won't make it into 2015.8.9 since we've already tagged.

**Comment by mirceaulinic** [comment] 2016-05-18 15:00
Understood, thank you very much @cro! 
Will upgrade all servers to ```2016.3``` as tested and confirmed to work. 
And yes, the ```multiprocessing``` is set to False because the proxies connect via SSH, as you pointed out.

**Comment by cro** [comment] 2016-05-18 15:05
You're welcome.  I will close this issue for now.  If the issue isn't resolved drop a comment here and I can reopen it.

**Closed by cro** 2016-05-18 15:05 UTC
Labels: Bug, High Severity, P3, Proxy Minion, RIoT, TEAM RIoT

**Comment by mirceaulinic** [comment] 2016-05-18 15:07
Absolutely, from my point of view this seems to be fixed. Will come back if any further issues. 👍
