### ISSUE TITLE
[BUG] virt.pool_running failling

### ISSUE THREAD

**Issue by cerberek** [saltstack/salt#57530] opened 2020-06-03 14:21 UTC
**Description**

State virt.pool_running should be in salt from  version 2019.2.0 i'm running 2019.2.5+ds-1 on minion and master

Definign pool with virt.pool_running fails. First run was OK

          ID: default
    Function: virt.pool_running
      Result: True
     Comment: Pool default defined and started
     Started: 14:11:23.789631
    Duration: 49.226 ms
     Changes:   
              ----------
              default:
                  Pool defined and started
Second run failed. 

          ID: default
    Function: virt.pool_running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/virt.py", line 764, in pool_running
                  if info['state'] == 'running':
              KeyError: 'state'
     Started: 14:16:23.447691
    Duration: 2.773 ms
     Changes:   
When I added option start: true it failled completely
Passed invalid arguments: 'start' is an invalid keyword argument for 'virt.pool_running'.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

default:
  virt.pool_running:
    - ptype: dir
    - target: /var/lib/libvirt/images
    - permissions:
        - mode: 0711
        - owner: 0
        - group: 0
    - autostart: True
#    - start: True

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

Everywhere is version 2019.2.5+ds-1

```
PASTE HERE
```
</details>

**Additional context**

**Comment by dmurphy18** [comment] 2020-06-04 18:10
@cerberek While everywhere is 2019.2.5+ds-1, the versions-report is also useful to know which OS platforms you are using.  Can you please supply the versions-report for both the master and minion, since there are 5 different Debian/Ubuntu platforms on which 2019.2.5+ds-1 can be installed.

**Comment by cerberek** [comment] 2020-08-14 09:38
Salt Version:
           Salt: 2019.2.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.0 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-5-amd64
         system: Linux
        version: debian 10.0 

Same OS is on minion. I did try this state again and still same error.

**Comment by cbosdo** [comment] 2020-09-03 12:54
Could you test with 3001? I feel confident this could have been fixed in the mean time

**Comment by dmurphy18** [comment] 2021-05-03 22:32
@cerberek Actually could you retest this with the latest version of Salt 3003, and close if it is no longer an issue. version 2019.2.5 has reached end-of-life.

If the issue is no longer reproducible, please consider closing this issue.

**Comment by sagetherage** [comment] 2021-06-21 18:50
Reviewed in Grooming 2021-JUN-21 please mention me if this issue is reproduced in a supported version of Salt, we are unable to reproduce it as well - closing.

**Closed by sagetherage** 2021-06-21 18:50 UTC
Labels: Bug, info-needed
