### ISSUE TITLE
salt-minion under python3 evaluates iteritems on pillar-derived object

### ISSUE THREAD

**Issue by rnickle** [saltstack/salt#47461] opened 2018-05-03 17:34 UTC
### Setup

I have this SLS in CUPS/init.sls.  In previous versions this worked, even for a minion that did not have cups_printers defined.
```
{% if salt['pillar.get']('cups_printers', {}) is defined %}
{% for printer, args in salt['pillar.get']('cups_printers', {}).iteritems() %}
CUPS_printer_{{printer}}:
  cmd.run:
    - name: lpadmin -p '{{printer}}' -v 'socket://{{args['ip']}}:{{args['port']}}' -m '{{args
['model']}}'  -L '{{args['comment']}}' -E 
    - unless: lpstat -p {{printer}} 2>/dev/null >/dev/null 
{% endfor %}
{# if cups_printers is defined #}
{% endif %}
```
When I upgraded to Ubuntu 18.04, which has Python3 for default python (salt-minion is started with /usr/bin/python3) I received:

Data failed to compile:
----------
    Rendering SLS 'test:CUPS' failed: Jinja variable 'dict object' has no attribute 'iteritems'

I thought perhaps it was because cups was not defined (despite the guard I put around it above, so I tried defining it for my test case with this pillar SLS):
```
cups_printers:
  swords:
    ip: 192.168.1.1
    port: 9100
    hosts: ['math']
    comment: lab
    model: drv:///hpcups.drv/hp-laserjet_p4015dn.ppd
    default: False
```
### Steps to Reproduce Issue

Minion log:

2018-05-03 13:26:36,793 [salt.utils.templates:180 ][ERROR   ][8915] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'iteritems'
2018-05-03 13:26:36,798 [salt.state       :3227][CRITICAL][8915] Rendering SLS 'test:CUPS' failed: Jinja variable 'dict object' has no attribute 'iteritems'

### Versions Report

```
Master versions report:

Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-96-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 ```
Minion version:

```
$ salt-minion --version
salt-minion 2017.7.4 (Nitrogen)
```

**Comment by garethgreenaway** [comment] 2018-05-04 18:59
@rnickle So far I am unable to reproduce this.  Can you provide the output from `salt <minion> pillar.get cups_printer`?  Thanks!

**Comment by rnickle** [comment] 2018-05-04 19:02
I didn't think to put it markdown when I posted above, I'll update it:

```
sudo salt 'ubbt3.*' pillar.items cups_printers saltenv=test
ubbt3.holycross.edu:
    ----------
    cups_printers:
        ----------
        swords:
            ----------
            comment:
                lab
            default:
                False
            hosts:
                - math
            ip:
                192.168.1.1
            model:
                drv:///hpcups.drv/hp-laserjet_p4015dn.ppd
            port:
                9100

```

**Comment by gtmanfred** [comment] 2018-05-04 19:10
iteritems is only in python2 thing, when using python3 you cannot use iteritems, you use just `items()` which returns a generator in python3, like iteritems did in python2.

**Comment by rnickle** [comment] 2018-05-04 20:00
I tried fooling around with a macro, but I don't think I can force the Jinja macro scope into a Jinja statement.

There's no way to do something like this?

```
{% macro iterator() -%}
{% if '3' in salt['grains.get']('pythonversion','')[0] %}
items()
{% else %}
iteritems()
{% endif %}
{%- endmacro %}
```

**Comment by gtmanfred** [comment] 2018-05-04 20:11
Yeah, macros do not work like that, they are for dumping other stuff, what you need is to be able to define a function.

You could write a custom utils module

```
from salt.utils.decorators.jinja import jinja_filter
import salt.ext.six as six

@jinja_filter()
def iterator(obj):
    return six.iteritems(obj)
```

Then put that in `salt://_utils/` and sync it over, then you could use it like

```
{%- for printer, args in salt['pillar.get']('cups_printers', {})|iterator %}
```

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

**Comment by rnickle** [comment] 2018-05-04 20:27
Thank you very much for closing that concern so elegantly!  That looks very useful.

Perhaps the other way I could do it would be to have .sls files conditionally included based on what version of Python my minion is running.

In the end, I don't think it is harmful for our implementation to just get lists with python2 and a generator with python3+, since we don't have any pillar with more than a few hundred items.

I'm not sure if there's anything actionable in my issue at this point.  Any recommendations on how it should be tagged?

**Comment by gtmanfred** [comment] 2018-05-04 20:30
Yup, done, and I will be closing :)

You should probably be fine just using `.items()` in both python2 and python3, i would be very surprised if it actually caused any problems.

**Closed by gtmanfred** 2018-05-04 20:30 UTC
Labels: Expected Behavior

**Comment by marek-obuchowicz** [comment] 2021-09-07 14:07
@gtmanfred I just updated to python3 and got the following issue with `.items()` (which worked with py27):
```
Jinja variable dict_items object has no element 0
```

The failing code is:
```
ENVIRONMENT="{{ salt['pillar.get']('environments', {}).items()[0][0] }}"
```

and pillar value:
```
salt-call pillar.get environments
local:
    ----------
    staging:
        ----------
        database:
            ----------
            hostname:
                some.host.xyz
```


Versions used:
```
Salt Version:
          Salt: 3003.3

Dependency Versions:
        Jinja2: 2.8
        Python: 3.5.3 (default, Apr  5 2021, 09:00:41)
        
```
