### ISSUE TITLE
Create state module for Win_Task module

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#40661] opened 2017-04-12 17:57 UTC
Create state module for Win_Task module.

Currently the Win_Task module needs to run under module.run if states are to be used.

ZD 1330
ZD 3389
https://github.com/saltstack/salt/issues/25249

**Comment by doesitblend** [comment] 2019-03-25 15:51
ZD-3389

**Comment by twangboy** [comment] 2019-03-25 15:51
Duplicate of #25249

**Closed by twangboy** 2019-03-25 15:51 UTC
Labels: Duplicate, Feature, Neon, ZD
