### ISSUE TITLE
saltutil.sync_modules can't sync myself module to minions if I use consul python package in the module

### ISSUE THREAD

**Issue by ShaolongTan** [saltstack/salt#34660] opened 2016-07-14 07:01 UTC
### Description of Issue/Question
I write a myself module with python. Because I need to use python consul package, I import consul in my python code. I used saltutil.sync_modules to sync the extended module. It shown saltutil sync the module, but actually I can't use the module function.
If remove the "import consul" code, the saltutil.sync_modules works.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
N/A

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
1. Add python code to /srv/salt/_modules/myconsul.py
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
import time
import consul

def get(host, port, prefix):
    """
    Get key from Consul
    """
    #c = consul.Consul(host=host, port=port)
    #try:
    #    ret = c.kv.get(prefix)[1]['Value']
    #except KeyError as err:
    #    log.debug("Can't find Key for %s. Error: %s" % (prefix, str(err)))
    #    raise err

    #return ret
    return "aa"

def date():
    return time.time()
```
2. sync the extended modules
```
tanr9@ubuntu1404:/srv/salt/_modules$ sudo salt "test-xxxx" saltutil.sync_modules -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /home/tanr9/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /home/tanr9/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ubuntu1404_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/ba/bb7d352540ed35516a89721329782e/.minions.p
[DEBUG   ] get_iter_returns for jid 20160714063824028526 sent to set(['test-xxxx']) will timeout at 06:38:29.042901
[DEBUG   ] jid 20160714063824028526 return from test-xxxx
[DEBUG   ] LazyLoaded nested.output
test-xxxx:
    - modules.myconsul
[DEBUG   ] jid 20160714063824028526 found all minions set(['test-xxxx'])
```
3. find that can't use the module.
```
tanr9@ubuntu1404:/srv/salt/_modules$ sudo salt "test-xxxx" myconsul.date
test-xxxx:
    'myconsul.date' is not available.
ERROR: Minions returned with non-zero exit code
```
4. If I JUST remove the "import consul". it is work after sync the module again.
```
tanr9@ubuntu1404:/srv/salt/_modules$ sudo salt "test-xxxx" myconsul.date
test-xxxx:
    1468479197.94
```
5.  I make sure I have installed python-consul package in salt-master and salt-minion.
  - for master:
```
tanr9@ubuntu1404:/srv/salt/_modules$ python -c "import consul"
tanr9@ubuntu1404:/srv/salt/_modules$ 
```
  - for minion:
```
tanr9@ubuntu1404:/srv/salt/_modules$ sudo salt "test-xxxx" cmd.run "python -c 'import consul'"
test-xxxx:
tanr9@ubuntu1404:/srv/salt/_modules$
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
  - for master:
```
tanr9@ubuntu1404:/srv/salt/_modules$ sudo salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-27-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
  - for minion:
```
tanr9@ubuntu1404:/srv/salt/_modules$ sudo salt "test-xxxx" test.versions_report
test-xxxx:
    Salt Version:
               Salt: 2015.8.0
     
    Dependency Versions:
             Jinja2: 2.8
           M2Crypto: 0.22
               Mako: 1.0.1
             PyYAML: 3.11
              PyZMQ: 14.4.1
             Python: 2.7.10 (default, Sep 24 2015, 13:11:49)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: 0.1.3
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: SuSE 11 x86_64
            machine: x86_64
            release: 3.0.101-0.46-default
             system: SUSE Linux Enterprise Server  11 x86_64
```

**Comment by Inveracity** [comment] 2016-07-14 14:53
Hey, on the master, have you run the following command:

```bash
salt "test-xxxx" saltutil.sync_modules
```
This ensures the module is transferred to the minion

**Comment by Inveracity** [comment] 2016-07-14 15:36
I noticed you've got a 2016.3.0 Master and a 2016.8.0 minion, I believe you're hitting one of the backwards incompatible changes as it's written [here](https://docs.saltstack.com/en/latest/topics/releases/2016.3.0.html#backwards-incompatible-changes)

> The default path for the extension_modules master config option has been changed. Prior to this release, the location was a directory named extmods in the Salt cachedir. On most platforms, this would put the extension_modules directory in /var/cache/salt/extmods. It has been moved one directory down, into the master cachedir. On most platforms, this is /var/cache/salt/master/extmods

:disappointed:

**Comment by ShaolongTan** [comment] 2016-07-15 02:57
Thanks for you quick response. My minion is 2015.8.0 and not 2016.8.0. :)
But why I can sync modules if I just remove "import consul"? If the reason is backwards incompatible, it always should not work. is it right? thanks.

**Comment by Inveracity** [comment] 2016-07-15 05:24
I apologise, I meant 2015.8.0 of course!
The reason I suggested it might have been the backwards incompatibility is because I tested it with a 2016.3.1 minion and master, and it worked fine when importing consul.
I realise now that I hadn't been paying proper attention, when you show that the execution module works fine without importing consul.

Try running the minion in debug mode and view what happens when you run the execution module and importing consul, You can also check the log `/var/log/salt/minion`, maybe that will show what goes wrong when it tries to load consul.

**Comment by ShaolongTan** [comment] 2016-07-18 05:59
In my salt-minion env, I can't run salt-minion with debug mode because I didn't install pyzmq. Currently, I can't resolve the issue because my network meet some issues and can't connect ourselves SUSE repository. Do you have any suggestion? Thanks a lot.

Please see the error message:
```
# salt-minion -l debug
Traceback (most recent call last):
  File "/usr/local/bin/salt-minion", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.6/site-packages/pkg_resources.py", line 2561, in <module>
    working_set.require(__requires__)
  File "/usr/lib64/python2.6/site-packages/pkg_resources.py", line 626, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.6/site-packages/pkg_resources.py", line 524, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: pyzmq>=2.2.0
```

**Comment by Inveracity** [comment] 2016-07-18 10:05
That is very odd 
Try putting the import into the function and wrap it in a try/except:

```python
def get():
    try:
        import consul
    except Exception as e:
        return e
```

I wonder if that will give you an indication of what goes wrong

**Comment by rallytime** [comment] 2016-07-18 21:06
@ShaolongTan I was able to reproduce your this error when I used your exact custom module that you pasted above and the consul package was missing from the minion. If the consul package was present on the minion, I didn't have any problems.

Here's the error:
```
root@rallytime:~# salt rally-arch saltutil.sync_modules
rally-arch:
    - modules.myconsul
root@rallytime:~# salt rally-arch myconsul.date
rally-arch:
    'myconsul.date' is not available.
```
And here is the output on a minion that can import consul successfully:
```
root@rallytime:~# salt rallytime saltutil.sync_modules
rallytime:
    - modules.myconsul
root@rallytime:~# salt rallytime myconsul.date
rallytime:
    1468875602.13
```
However, if I add the following to your module, I get a more helpful error saying the consul import couldn't be found:
```
try:
    import consul
    HAS_CONSUL = True
except ImportError:
    HAS_CONSUL = False

__virtualname__ = 'myconsul'


def __virtual__():
    if HAS_CONSUL:
        return __virtualname__
    else:
        return False, 'The consul module must be installed.'
```
Here's the error in practice:
```
root@rallytime:~# salt rally-arch myconsul.date
rally-arch:
    'myconsul' __virtual__ returned False: The consul module must be installed.
```
Then, after installing the consul module, it works as expected:
```
root@rallytime:~# salt rally-arch pip.install python-consul
rally-arch:
    ----------
    pid:
        12180
    retcode:
        0
    stderr:
    stdout:
        Collecting python-consul
          Downloading python-consul-0.6.1.tar.gz
        Requirement already satisfied (use --upgrade to upgrade): requests>=2.0 in /usr/lib/python2.7/site-packages (from python-consul)
        Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python2.7/site-packages (from python-consul)
        Installing collected packages: python-consul
          Running setup.py install for python-consul: started
            Running setup.py install for python-consul: finished with status 'done'
        Successfully installed python-consul-0.6.1
root@rallytime:~# salt rally-arch myconsul.date
rally-arch:
    1468875403.24
```
Adding the `__virtual__()` check, as well as the `__virtualname__` should help resolve this for you.

**Comment by ShaolongTan** [comment] 2016-07-19 02:32
Yes, I get the exception when I operate the function in the module. Below is the error message:
```
$ sudo salt 'test-xxxx' myconsul.get
test-xxxx:
    No module named consul
```
But I make sure I have installed the python package.  I can run the script in "test-xxxx" minion and not exception.
```
def get():
    try:
        import consul
    except Exception as e:
        return "%s" % str(e)

    print "yes"
    return "aa"

if __name__ == '__main__':
    get()
```
```
# python myconsul.py 
yes
```

**Comment by ShaolongTan** [comment] 2016-07-19 03:10
@rallytime, I can make sure I had installed package consul in minion but I get the exception yet that I move "imprt consul" to get() function. Below is the error message:
```
$ sudo salt 'test-xxxx' myconsul.get
test-xxxx:
    No module named consul
```

I can directly run the script in "test-xxxx" minion and not exception.
```
def get():
    try:
        import consul
    except Exception as e:
        print "no"
        return "%s" % str(e)

    print "yes"
    return "aa"

if __name__ == '__main__':
    get()
```
```
test-xxx:~ # python myconsul.py 
yes
```

**Comment by rallytime** [comment] 2016-07-19 15:54
@ShaolongTan Did you try the suggestion I posed above to include the `__virtual__()` function and `__virtualname__` definition? I suspect you might be hitting something going on with the loader.

**Comment by ShaolongTan** [comment] 2016-07-20 01:19
I add the __virtual__() function and __virtualname__ as you mentioned at above. The result is same as I guess. It meet exception while import consul. The below is the output:

```
sudo salt 'test-r1-is1-001' myconsul.date
tanr9@ubuntu1404:/srv/salt/_modules$ test-xxxx:
    'myconsul' __virtual__ returned False: The consul module must be installed.
ERROR: Minions returned with non-zero exit code
```

**Comment by ShaolongTan** [comment] 2016-07-20 02:14
Use cmd.exec_code to operate the python "import consul"  code. It is work fine.
```
tanr9@ubuntu1404:/srv/salt/_modules$ sudo salt 'test-xxxx' cmd.exec_code python 'import consul; help(consul)'
test-xxxx:
    Help on package consul:
    
    NAME
        consul
    
    FILE
        /usr/local/lib64/python2.6/site-packages/python_consul-0.6.0-py2.6.egg/consul/__init__.py
    
    PACKAGE CONTENTS
        aio
        base
        std
        tornado
    
    DATA
        __loader__ = <zipimporter object "/usr/local/lib64/python2.6/site-pack...
        __version__ = '0.6.0'
    
    VERSION
        0.6.0
```

**Comment by rallytime** [comment] 2016-07-21 20:00
@ShaolongTan Hm. I am out of ideas on this one. Perhaps @Ch3LL or @cachedout have an idea of why this wouldn't be working correctly, even though `import consul` works fine on the box.

**Comment by cachedout** [comment] 2016-07-21 20:06
This sounds like you have multiple versions of python installed.

**Comment by ShaolongTan** [comment] 2016-07-25 08:53
I have missed the test environment. If I can reproduce  issue again, I will check env whether or not there have multiple python versions. 
Thanks for your helps.

**Comment by rallytime** [comment] 2016-07-25 14:55
@ShaolongTan Sounds good. I'll close this for now, but certainly let us know if you bump into this one again.

**Closed by rallytime** 2016-07-25 14:55 UTC
Labels: Fixed Pending Verification, Question
