### ISSUE TITLE
Multi-master syndic is not documented in all examples hot-hot, multimaster and multi syndic w multimaster

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#18751] opened 2014-12-04 22:43 UTC
As the title says. I can't help but feel this is somehow @jacksontj's fault!  ;-)

**Comment by UtahDave** [comment] 2015-02-18 06:28
@whiteinge would you mind clarifying your clarification?

**Comment by whiteinge** [comment] 2015-02-18 07:24
@UtahDave A syndic cannot currently have a connection to multiple masters. This ticket is for the following scenario which provides more redundancy than just a master -> syndic-master connection but does not provide full HA.

Given Master A and Master B at main HQ, and syndic-masters a & b in one data center and syndic masters c & d in another data center:

* syndic-masters a & b are configured as multi-masters and minions e-k under them are connected to both as normal multi-master
* syndic-masters c & d are configured as multi-masters and minions l-r under them are connected to both as normal multi-master
* syndic-master a is connected to Master A; syndic-master c is connected to Master A.
* syndic-master b is connected to Master B; syndic-master d is connected to Master B.

If either Master A or Master B goes down, you still have a connection left to at least one syndic in each data center. But if the wrong syndic goes down at the same time as the wrong master, then you can still lose connection to a data center.

**Comment by jacksontj** [comment] 2015-02-18 15:55
To clarify more, since the addition of MultiSyndic you can put a list (instead of a single string) as the master list for a syndic-- and the syndic will connect to all of them-- similar to multiminion. The code is a bit messy, but it does work ;)

**Comment by cachedout** [comment] 2015-02-18 16:00
We need to completely overhaul the topology section of the docs to explain Salt's deployment options:

http://docs.saltstack.com/en/latest/topics/development/topology.html

**Comment by jacksontj** [comment] 2015-02-18 16:08
+1

**Comment by whiteinge** [comment] 2015-02-18 16:22
Holy cow, @jacksontj, that's awesome! I was previously told multi-connections had specifically not been added.

Definite +1 to getting MultiSyndic documented and also adding this to the topology doc.

**Comment by jacksontj** [comment] 2015-02-18 16:24
The only reason I haven't pushed it a lot is that some of the failure cases are a bit odd... I might just go back and thread it to work around them. Basically in a failure scenario (one master unavailable) you have to let zmq attempt to re-connect and we have to re-auth through it-- which means that the syndic will lock up for however long that connect timeout is. In general slow is better than unavailable-- but it can be worked around, I'll try to get back to that after our 2014.7 release internally

**Comment by whiteinge** [comment] 2015-02-18 16:33
Odd failure cases with ZeroMQ, you say? Hm.  ;-)

Thanks for mentioning that. I can think of one or two large sites just offhand that will be interested in getting this set up.

**Comment by jacksontj** [comment] 2015-02-18 17:15
We are one of them ;)

**Comment by Colstuwjx** [comment] 2015-07-08 23:52
Hi, @jacksontj, I setup 4 syndic-master that the one would connect to the other three, just like:

```
\#syndic 01 config:
syndic_master:
  -  [ syndic_02_ip ]
  -  [ syndic_03_ip ]
  -  [ syndic_04_ip ]
```

After all setup, I fired one job on syndic01, and I actually find out a duplicate of event loop problem, syndic 02\03\04 will duplicate to forward job and re-publish to its localmaster. so it will be:

```
\# on syndic_master 01
salt 'salt-test*' cmd.run 'echo 1TRY >> /tmp/run.log';

\# and all minions duplicate to add 1TRY to run.log
```

I checked out the MultiSyndic code, it seems that you only not forward event when the `master_id` match the origin one, but it didn't work in >2 syndics env.

After I check the 2014.7.5 & 2015.5.0 version, the setup cluster still doesn't work, still loop、loop and loop out...

Help~~~~~

**Comment by mimianddaniel** [comment] 2015-08-14 21:52
so multisyndic is not working as it suppose to?

**Comment by Colstuwjx** [comment] 2015-08-15 14:02
Yeah, Multi-Master with Multi-Syndic ( cluster mode ) didn't  work in my test case, but Multi-Syndic does.

**Comment by mimianddaniel** [comment] 2015-08-20 00:44
@jacksontj 
could you enlighten us? 

Multi-syndic setup has missing return issues from master of master for me. 
While runing multi-syndics on the syndic nodes, I see missing returns often against wildcard matches against (only 300 minions) from the master node. Without multisyndic, no issues with the returns from the master node. 

i have master_id set at the both master nodes and have a list of masters listed as syndic_master on the syndic nodes.  Am i missing anything??

**Comment by Joeskyyy** [comment] 2015-09-01 22:22
I'm having a super interesting issue with this set up actually.

I have the following servers:

```
master1.domain.com
master2.domain.com
syndic1.domain.com
syndic2.domain.com
minion1.domain.com
minion2.domain.com
```
When I run a test.ping on master1 I get the following:

```
[root@master1 ~]# salt '*' test.ping
syndic2.domain.com:
    Minion did not return. [No response]
syndic1.domain.com:
    Minion did not return. [No response]
```

Yet when I run the same on master2, I get the following:

```
[root@master2 ~]# salt '*' test.ping
minion1.domain.com:
    True
minion2.domain.com:
    True
syndic2.domain.com:
    Minion did not return. [No response]
```

You'll notice on master2, syndic2 isn't responding, despite the key being accepted and transferred correctly. The syndic logs keep having the same message repeating with regards to master1:

```
[INFO    ] Syndic still not connected to master1.domain.com
```

When I start the salt-syndics from scratch, keys are exchanged on both master1 and master2 however?

```
[root@master1 ~]# salt-key -L
Accepted Keys:
syndic1.domain.com
syndic2.domain.com
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

```
[root@master2 ~]# salt-key -L
Accepted Keys:
syndic1.saltysentinel.com
syndic2.saltysentinel.com
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```


Digging down, I found that when I started the minions, syndic1 has the keys sent to it, but syndic2 does not, despite the configuration being the same on both minions with regards to having the syndic pub keys on them, here's what my ```salt-keys -L``` looks like:

syndic1

```
[root@syndic1 ~]# salt-key -L
Accepted Keys:
minion1.domain.com
minion2.domain.com
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```
syndic2

```
[root@syndic2 ~]# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

Here's what i have for my config files on the syndics for the masters:

```
syndic_master:
  - master1.domain.com
  - master2.domain.com
```

And here's what I have on the minions for the syndics:

```
master:
   - syndic1.saltysentinel.com
   - syndic2.saltysentinel.com

master_type: failover

master_alive_interval: 30
```

====

Going a bit deeper, I can definitely confirm on the network level all instances should be able to talk each other:

Here's an example telnet from syndic2->master1

```
[root@syndic2 ~]# !telnet
telnet master1.domain.com 4506
Trying 10.1.4.231...
Connected to master1.domain.com.
Escape character is '^]'.
```

And for those counting at home master1->syndic2

```
[root@master1 ~]# telnet syndic1.domain.com 4506
Trying 10.10.2.217...
Connected to syndic1.domain.com.
Escape character is '^]'.
```

=======

I know it's a lot of information so I'm happy to confirm anything needed from above, but I REALLY need a setup like this to work with syndics and masters for HA if I'm going to further proceed with SaltStack.

**Comment by mimianddaniel** [comment] 2015-09-01 22:31
Make sure to have master_id set on the mom if you have not yet. With
multisyndic setup I see inconsistent showing of returns, returns arrived
properly but do not show up promptly at times.

**Comment by Joeskyyy** [comment] 2015-09-01 22:36
@mimianddaniel thanks for the suggestion, just gave that a go and still in the same spot. That was something I meant to have set anyways so at least I've got it covered now ;)

**Comment by Joeskyyy** [comment] 2015-10-05 20:08
Been over a month since any activity on this thread, just wondering if anyone from SaltStack has been able to plug at this.

**Comment by rallytime** [comment] 2015-10-05 20:28
Doesn't look like we've had time to get to documenting this yet. 

@jacobhammons Can you have a look here when you get a moment?

**Comment by jacobhammons** [comment] 2015-10-05 20:40
Multi-master syndic docs are at https://docs.saltstack.com/en/latest/topics/topology/syndic.html#configuring-the-syndic-with-multimaster

I think there is another issue going on here since @Joeskyyy's settings look correct.

**Comment by Joeskyyy** [comment] 2015-10-05 20:42
+1 Those are the docs I followed.

**Comment by jacobhammons** [comment] 2016-04-11 20:46
Hi @Joeskyyy, did you ever get this figured out?

**Comment by Joeskyyy** [comment] 2016-04-11 20:53
@jacobhammons I never did, no :\

**Comment by Oloremo** [comment] 2019-09-10 14:11
@Ch3LL Can you please re-open this?
This is a new(kinda) and very interesting part of salt configuration which is completely undocumented.

I found it in one of the salt conference videos - https://www.youtube.com/watch?v=qjFOY-QrW_k (starts from min 32) and really like to implement it in that way. almost 3 years passed and we don't have any docs.

**Comment by Oloremo** [comment] 2019-09-10 14:20
Just to clarify - I'm talking about a **multi-master & multi-syndic** configuration documentation.

**Comment by sagetherage** [comment] 2020-03-23 22:28
@saltstack/docs-working-group

**Comment by sagetherage** [comment] 2020-03-23 22:29
removing the `Core` label as to not confuse - this is work in the Core of Salt code, but not for the core team to do the documentation work as of now

**Comment by Oloremo** [comment] 2020-03-23 23:51
Really waiting for this one 🙏

**Comment by sagetherage** [comment] 2020-08-13 18:03
@saltstack/docs-working-group this is a feature that isn't documented something for the Docs Working Group could take on? @ScriptAutomate

**Comment by waynew** [comment] 2022-04-12 01:13
Had unexpected issues pop up, this one has to slip to the next release

**Comment by anilsil** [comment] 2023-08-18 21:45
Closing as Won't fix. Please follow Syndic deprecation work https://github.com/orgs/saltstack/projects/42 due for 3007.0

**Closed by anilsil** 2023-08-18 21:45 UTC
Labels: Documentation, Bug, severity-high, Salt-Syndic, doc-request, time-estimate-sprint

**Comment by Oloremo** [comment] 2023-08-19 12:13
@anilsil I get 404 for https://github.com/orgs/saltstack/projects/42
Any doc I can read about that?

**Comment by anilsil** [comment] 2023-08-21 19:34
Still in WIP but you can refer this https://github.com/saltstack/salt/issues/64941
