### ISSUE TITLE
debian/ubuntu release is outdated on ppa:saltstack/salt

### ISSUE THREAD

**Issue by onorua** [saltstack/salt#24697] opened 2015-06-16 02:56 UTC
I've figured out that current release is 2015.05.2, while latest available release, if installed in accordance to the following documentation:
http://docs.saltstack.com/en/latest/topics/installation/ubuntu.html
is 2015.5.0+ds-1utopic1
There are several bugs fixed which I really keen to see on my systems, but I have bunch of servers in "secure" area, where there is no internet at all except "deb" mirror. 
Could you please synchronise/automate deb packages creation?

**Comment by rallytime** [comment] 2015-06-16 03:14
Thanks for the report @onorua. This is a duplicate of #24563, so I am going to close this one in favor of that one. As stated in the other issue, we are currently working on getting a more synchronized and automated packaging system in place, but I don't know when that will be completed yet. Hopefully sooner rather than later. Thanks!

**Closed by rallytime** 2015-06-16 03:14 UTC
Labels: Duplicate
