### ISSUE TITLE
salt-ssh Not Syncing _grains Custom Grains with saltutil.sync_all

### ISSUE THREAD

**Issue by TheNewmanium** [saltstack/salt#39671] opened 2017-02-26 19:58 UTC
### Description of Issue/Question
When using salt-ssh, running the module saltutil.sync_all does not sync down custom grains from the <file_root>/_grains directory to minions. These grains are then missing in a salt-ssh <host> grains.items command and all states.

### Setup
Here is my simple setup for reproducing this issue. I have a single file_root in /srv/salt/states with a _grains directory under that:

```
root@myhost1:/srv/salt/states# ll
total 40
drwxr-xr-x 9 root root 4096 Feb 25 22:24 ./
drwxr-xr-x 5 root root 4096 Feb 26 12:47 ../
drwxr-xr-x 3 root root 4096 Jan 31 22:26 common/
drwxr-xr-x 2 root root 4096 Feb 26 12:40 _grains/
drwxr-xr-x 3 root root 4096 Dec  6 22:35 sshd/
-rw-r--r-- 1 root root  233 Feb 25 13:24 top.sls
drwxr-xr-x 2 root root 4096 Dec  2 20:37 vmware/
```
In _grains, I have a very simple test grain that returns the grain 'zzzz' with value of 'works':
```
#!/usr/bin/env python
import logging
log = logging.getLogger(__name__)

def testgrain():
  log.debug('computing my custom grain')
  grains = {}
  grains['zzzz'] = 'works'
  return grains
```

### Steps to Reproduce Issue
Running salt-ssh <remote minion> saltutil.sync_all followed by salt-ssh <remote minion> grains.item zzzz does not show the grain that was configured in _grains. Clearing out of all caches, deleting the remote thin dir, etc., has not produced a different result:

```
$ salt-ssh -l debug --roster=clustershell manwe saltutil.sync_all
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded clustershell.targets
[DEBUG   ] Matched minions: {'manwe': {'host': 'manwe', 'port': 22}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] In saltenv 'base', looking at rel_path '_grains/zzzz.py' to resolve 'salt://_grains/zzzz.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/master/files/base/_grains/zzzz.py' to resolve 'salt://_grains/zzzz.py'
[INFO    ] Fetching file from saltenv 'base', ** updated ** latest already in cache, 'salt://_grains/zzzz.py', mode updated from 0600 to 0755
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20170226134314494144: ['manwe']
[DEBUG   ] Could not LazyLoad saltutil.sync_all: 'saltutil.sync_all' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
saltutil.sync_all
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 24378  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE manwe: 11
[DEBUG   ] SHIM retcode(11) and command: deploy
[DEBUG   ] Executing command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=root  /var/cache/salt/master/thin/thin.tgz manwe:/var/tmp/.root_cc66fa_salt/salt-thin.tgz
[DEBUG   ] Child Forked! PID: 24391  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] Terminal Command: /bin/sh -c scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=root  /var/cache/salt/master/thin/thin.tgz manwe:/var/tmp/.root_cc66fa_salt/salt-thin.tgz
[DEBUG   ] Executing command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=root  /var/cache/salt/master/ext_mods.e81f2a9f9b68979e2c4fccaa42b479b42b685e08.tgz manwe:/var/tmp/.root_cc66fa_salt/salt-ext_mods.tgz
[DEBUG   ] Child Forked! PID: 24393  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] Terminal Command: /bin/sh -c scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=root  /var/cache/salt/master/ext_mods.e81f2a9f9b68979e2c4fccaa42b479b42b685e08.tgz manwe:/var/tmp/.root_cc66fa_salt/salt-ext_mods.tgz
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 24395  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] LazyLoaded nested.output
manwe:
    ----------
    beacons:
    engines:
    grains:
    log_handlers:
    modules:
    output:
    pillar:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    utils:
```

(and the following grains.item command)

```
$ salt-ssh -l debug --roster=clustershell manwe grains.item zzzz
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded clustershell.targets
[DEBUG   ] Matched minions: {'manwe': {'host': 'manwe', 'port': 22}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] In saltenv 'base', looking at rel_path '_grains/zzzz.py' to resolve 'salt://_grains/zzzz.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/master/files/base/_grains/zzzz.py' to resolve 'salt://_grains/zzzz.py'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://_grains/zzzz.py', mode up-to-date
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20170226134344547983: ['manwe']
[DEBUG   ] LazyLoaded grains.item
[DEBUG   ] Performing shimmed, blocking command as follows:
test.opts_pkg
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 24539  STDOUT_FD: 9  STDERR_FD: 11
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE manwe: 0
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /srv/pillar/top.sls
[DEBUG   ] Jinja search path: ['/srv/pillar', '/srv/spm/pillar']
[PROFILE ] Time (in seconds) to render '/srv/pillar/top.sls' using 'jinja' renderer: 0.00355005264282
[DEBUG   ] Rendered data from file: /srv/pillar/top.sls:
base:
 '*':
    test: stuff

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('base', OrderedDict([('*', OrderedDict([('test', 'stuff')]))]))])
[PROFILE ] Time (in seconds) to render '/srv/pillar/top.sls' using 'yaml' renderer: 0.00506901741028
[DEBUG   ] compound_match: manwe ? *
[DEBUG   ] compound_match manwe ? "*" => "True"
[DEBUG   ] compile template: /srv/pillar/test.sls
[DEBUG   ] Jinja search path: ['/srv/pillar', '/srv/spm/pillar']
[PROFILE ] Time (in seconds) to render '/srv/pillar/test.sls' using 'jinja' renderer: 0.000706911087036
[DEBUG   ] Rendered data from file: /srv/pillar/test.sls:
nothing: ignore

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('nothing', 'ignore')])
[PROFILE ] Time (in seconds) to render '/srv/pillar/test.sls' using 'yaml' renderer: 0.000538110733032
[DEBUG   ] LazyLoaded grains.item
[DEBUG   ] LazyLoaded nested.output
manwe:
    ----------
```

### Versions Report

```
$ salt --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-34-generic
         system: Linux
        version: Ubuntu 14.04 trusty```

**Comment by p6knewman** [comment] 2017-02-27 14:33
I think this is a dupe of https://github.com/saltstack/salt/issues/33629

**Comment by TheNewmanium** [comment] 2017-02-27 14:34
I think this is a dupe of https://github.com/saltstack/salt/issues/33629.

**Comment by gtmanfred** [comment] 2017-02-27 17:47
I am going to close this because it is a duplicate.

**Closed by gtmanfred** 2017-02-27 17:47 UTC
Labels: Duplicate
