### ISSUE TITLE
Fixed redis salt returner fails with TypeError

### ISSUE THREAD

**Issue by pcn** [saltstack/salt#30044] opened 2015-12-28 20:29 UTC
I want to use redis to fix a couple of issues I've had with getting jobs listed and reported etc. quickly via the netapi.  So I naturally ran across the bug with some returners returning a list, and others returning a dict.  I tried the fix at https://github.com/saltstack/salt/pull/28654 by changing the ```__virtual__``` to redis_fix, and updating my config.  For one highstate job, the fix seems to work, but once I ran a ```salt '* ' state.highstate``` the listing crashed.  

I posted details at https://github.com/saltstack/salt/pull/28654/files#r48502272 

```
ubuntu@peter.norton-saltmaster-vagrant:/srv/salt/states/_returners$ salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-52-generic
         system: Ubuntu 14.04 trusty
```

**Comment by cachedout** [comment] 2015-12-28 21:31
@DmitryKuzmenko Can you take a look here when you have a moment?

**Comment by DmitryKuzmenko** [comment] 2015-12-29 12:27
@pcn thank you for advanced log. It helped a lot!
The problem is in the None result. It looks like the data for some JID was cleared in the database but the jid still to be there. I think such results should be skipped by returner.

**Comment by cachedout** [comment] 2015-12-29 20:22
This should be fixed now. Closing.

**Closed by cachedout** 2015-12-29 20:22 UTC
Labels: Bug, Confirmed, Core, Fixed Pending Verification, High Severity, P2

**Comment by pcn** [comment] 2015-12-29 20:25
Thanks!
