### ISSUE TITLE
`__proxy__` dunder is not injected when invoking the `salt` variable in sls files

### ISSUE THREAD

**Issue by alexbleotu** [saltstack/salt#38753] opened 2017-01-16 16:24 UTC
### Description of Issue/Question

I tried to call execution functions in state files, because I was told grains may not be accurate when it comes to proxy minions. 

The issue is that the `__proxy__` dunder is not available when invoking execution functions from state files (both in the `2016.3` and in the `develop` branch). 

```
Running the execution function directly

$ salt cluster vsphere.get_cluster_vsan_data                                                                                                                             
cluster:
    ----------
    datastore_name:
        vsan:vsan8
    enabled:
        True
```

```
Invoking the same function in state files

$ salt cluster state.show_highstate
cluster:
    - Rendering SLS 'base:esxcluster' failed: Jinja error: 'esxcluster.get_details'
      Traceback (most recent call last):
        File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/utils/templates.py", line 368, in render_jinja_tmpl
          output = template.render(**decoded_context)
        File ".../jinja2/2.7.3-py27/lib/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 969, in render
          return self.environment.handle_exception(exc_info, True)
        File ".../jinja2/2.7.3-py27/lib/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 742, in handle_exception
          reraise(exc_type, exc_value, tb)
        File "<template>", line 29, in top-level template code
        File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/modules/vsphere.py", line 262, in __supports_proxies
          return fn(*args, **clean_kwargs(**kwargs))
        File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/modules/vsphere.py", line 295, in _gets_service_instance_via_proxy
          connection_details = _get_proxy_connection_details()
        File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/modules/vsphere.py", line 233, in _get_proxy_connection_details
          details = __salt__['esxcluster.get_details']()
        File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/modules/esxcluster.py", line 29, in get_details
          return __proxy__['esxcluster.get_details']()
        File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/utils/context.py", line 191, in __getitem__
          return self._dict()[key]
      KeyError: 'esxcluster.get_details'
      
      ; line 29
      
      ---
      [...]
          esxcluster.cluster_configured:
              - {{ cluster_config }}
      {%- endif %}
      
      {%- if esxcluster_states_enabled.get('cluster_vsan_datastore') %}
      {%- if pillar.get('vsan', {}).get('datastore_name') and     <======================
          **salt['vsphere.get_cluster_vsan_data']()**.get('datastore_name') %}
      cluster_vsan_datastore:
          esxcluster.vsan_datastore_configured:
              - datastore_name : {{ pillar['vsan']['datastore_name'] }}
      {%- endif %}
      [...]
      ---


```

**Comment by alexbleotu** [comment] 2017-01-16 16:24
@cro another `__proxy__` dunder issue

**Comment by mirceaulinic** [comment] 2017-01-16 17:23
I think it's just not injected. I have submitted https://github.com/saltstack/salt/pull/38755 - can you give it a whirl?
However, this is based on the develop branch and might fail as per https://github.com/saltstack/salt/issues/38557. If so, please let me know to port it in a different branch (e.g. `2016.11` does not have the https://github.com/saltstack/salt/issues/38557 bug).

**Comment by alexbleotu** [comment] 2017-01-16 17:25
Thanks Mircea, 

can you please port it to 2016 please. It's easier for me to test. Develop will be broken.

**Comment by mirceaulinic** [comment] 2017-01-16 17:33
Can you test this branch: https://github.com/cloudflare/salt/tree/try-38753-2016.11?

Looking closer to the output, this might be more related to this... looks like the `__proxy__` object does exist but your proxy functions are not available.

**Comment by mirceaulinic** [comment] 2017-01-16 17:43
Oh, I've got two questions:


From the trace:

```python
        File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/modules/esxcluster.py", line 29, in get_details
          return __proxy__['esxcluster.get_details']()
```

1. Can you do a test function to show all keys of `__proxy__`?

under `esxcluster.py`:

```python
def test():
  return __proxy__['esxcluster.get_details']()
```

2. Can you confirm `salt <target> esxcluster.test` works?

**Comment by alexbleotu** [comment] 2017-01-16 17:59
yep first one didn't fix it. 

So, it works fine when invoked via the CLI (`salt` command). The problem shows up when invoked via the state files, as in this works:

```
Running the execution function directly

$ salt cluster vsphere.get_cluster_vsan_data                                                                                                                             
cluster:
    ----------
    datastore_name:
        vsan:vsan8
    enabled:
        True
```

**Comment by alexbleotu** [comment] 2017-01-16 18:00
Do you want me to add a function that shows all keys of the `__proxy__` dunder?

**Comment by mirceaulinic** [comment] 2017-01-16 18:10
If you can do this inside the state and check if any of the proxy functions are there :D

**Comment by rickh563** [comment] 2017-01-17 15:41
ZD-1147

**Comment by cro** [comment] 2017-01-17 17:34
This is a regression, correct?  It used to work?

**Comment by alexbleotu** [comment] 2017-01-17 17:36
First time I try it - so don't think it's a regression considerring it's happening both in `develop` and `2016.3`

**Comment by cro** [comment] 2017-01-17 23:25
I spent quite a bit of time today tracking this one down as well as other dunder problems for proxies.  I hope to have a PR tomorrow to correct those issues.

**Comment by mirceaulinic** [comment] 2017-01-17 23:52
So you've been able to reproduce this @cro? I was very surprised when I've seen yesterday the title and I had to ask the questions above as I didn't notice any of them before although I've been running both 2016.3 and 2016.11. What was the problem?

**Comment by Ch3LL** [comment] 2017-03-13 15:02
@alexbleotu does the PR resolve this issue for you?

**Comment by Ch3LL** [comment] 2017-03-13 20:43
Closing this please let me know if you need to re-open

**Closed by Ch3LL** 2017-03-13 20:43 UTC
Labels: 2016.3.6, Bug, Fixed Pending Verification, High Severity, Nitrogen, P2, RIoT, TEAM RIoT, ZD
