### ISSUE TITLE
Loader for runner module invoked from reactor does not include code in _utils leading to exception

### ISSUE THREAD

**Issue by yannis666** [saltstack/salt#26348] opened 2015-08-15 21:54 UTC
We have a runner module that is invoked from a reactor
```saltstack
update_status: 
  runner.lcm_orchestrator_job.react_to_salt_job_event:
     - args:
       - {{ data['id']|default('None') }}
       - {{ data['jid'] }} 
      - {{ data['retcode']|default('None') }} 
      - {{ data['fun'] }} 
      - {{ data['return']|default('None') }} 
```
In the `lcm_orchestrator_job` module there are (lazy) imports on other modules which are in the `_utils` directory.
When however the module is accessed via the reactor, we see the following in the master log file
```
2015-08-15 21:30:37,957 [salt.utils.event                         ][DEBUG   ][1129] Sending event - data = {'_stamp': '2015-08-15T21:30:37.957409', 'tag': 'salt/run/20150815213037578147/ret', 'data': {'jid': '20150815213037578147', 'return': 'Exception occurred in runner lcm_orchestrator_job.react_to_salt_job_event: Traceback (most recent call last):\n  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 317, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/srv/salt/_runners/lcm_orchestrator_job.py", line 2236, in react_to_salt_job_event\n    lock_manager = _take_jobs_lock()\nFile "/srv/salt/_runners/lcm_orchestrator_job.py", line 1966, in _take_jobs_lock\n    schedules_dir = _get_local_path(JOBS_DIR)\n  File "/srv/salt/_runners lcm_orchestrator_job.py", line 2045, in _get_local_path\n    import lcm_file_util\nImportError: No module named lcm_file_util\n', 'success': False, '_stamp': '2015-08-15T21:30:37.639244', 'user': 'Reactor', 'fun': 'runner.lcm_orchestrator_job.react_to_salt_job_event'}}
```

Originally we were seeing the Trace early, on compilation. Moving to lazy imports delayed till the event.

The imports, modules in `_utils`, are resolved correctly when using `salt-run`.

We are using: salt 2015.5.3 (Lithium)

**Comment by jfindlay** [comment] 2015-08-17 18:15
@yannis666, thanks for the report.

**Comment by cachedout** [comment] 2015-08-27 21:10
Hi @yannis666 Can you provide us with a minimal test case to try and reproduce this issue?

**Comment by yannis666** [comment] 2015-11-20 21:21
Worked around it by master config:
runner_dirs:
  - /srv/salt/_runners
  - /srv/salt/_utils

**Comment by cachedout** [comment] 2016-05-24 19:41
Closing since I think this is an edge case and there's a reasonable workaround here.

**Closed by cachedout** 2016-05-24 19:41 UTC
Labels: Bug, Core, High Severity, P3
