### ISSUE TITLE
salt-cloud error with Softlayer (Bare Metal Instance): TypeError: 'bool' object is not iterable and with --list-locations: Failed to get the output of 'softlayer_hw.avail_locations()': 142776

### ISSUE THREAD

**Issue by s-iraheta** [saltstack/salt#27406] opened 2015-09-25 16:28 UTC
Hi.
When I try to create a Softlayer bare metal instance, salt-cloud failed and show me this error when I execute the command `sudo salt-cloud -p logs instance`:

```python
[ERROR   ] There was a profile error: 'bool' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 254, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1391, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/softlayer_hw.py", line 448, in create
    for product in optional_products:
TypeError: 'bool' object is not iterable
```
These are my config files:

```bash
$ sudo salt-cloud --version
salt-cloud 2015.5.3 (Lithium)
```
```bash
$ sudo cat cloud.providers.d/softlayer.provider.conf 
softlayer:
 minion:
  master: xx.yy.zz
 user: provision
 apikey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
 provider: softlayer

softlayerHw:
 minion:
  master: xx.yy.zz
 user: provision
 apikey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
 provider: softlayer_hw
```
```bash
$ cat cloud.profiles.d/profiles.conf 
logs:
 provider: softlayerHw
 image: 22251
 size: 2164
 hdd: 19
 domain: yy.zz
 location: 138124
```
There is another weird behavior: When I executed `sudo salt-cloud --list-locations softlayerHw` I received this error message:

```python
[ERROR   ] Failed to get the output of 'softlayer_hw.avail_locations()': 142776
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 798, in location_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/softlayer_hw.py", line 121, in avail_locations
    ret[location['locationId']]['available'] = True
KeyError: 142776
[DEBUG   ] LazyLoaded nested.output
```
The only way to know which ID have Dallas05 was execute `sudo salt-cloud --list-locations softlayer -l debug` and search into the XML output.

**Comment by rallytime** [comment] 2015-09-25 16:33
Thanks for this report @s-iraheta. I'll take a look.

**Comment by s-iraheta** [comment] 2015-09-25 16:35
Thank you very much @rallytime. I appreciate it so much.

**Comment by rallytime** [comment] 2015-09-25 16:37
@s-iraheta Are you in a position to upgrade to 2015.8.0? I was able to reproduce your bug on 2015.5.3 and 2015.5.5, but it appears to be fixed in 2015.8.0.

**Comment by rallytime** [comment] 2015-09-25 16:41
@s-iraheta Or, if not, the fix is simple if you feel comfortable. In the path to your salt install, in `salt/cloud/clouds/softlayer_hw.py` add the following lines to the `avail_locations` function (around line 121):
```
if location.get('isAvailable', 0) is 0:
    continue
```
So that the whole function looks like [this](https://github.com/saltstack/salt/blob/b72e0b113339a6addcdc2c5c4ea82f38c38a0104/salt/cloud/clouds/softlayer_hw.py#L117).

**Comment by s-iraheta** [comment] 2015-09-25 16:51
Great! I will try to this fix line. Let me do it and I will tell you what happened.

**Comment by s-iraheta** [comment] 2015-09-25 17:02
Cool! It's works! Now I can see the locations list. :ok_hand: 
To the first issue, Is it a little tricky to fix it into the 2105.5.3 version?

**Comment by rallytime** [comment] 2015-09-25 17:06
@s-iraheta Awesome!

What do you mean about fixing it into 2015.5.3 version? Once we tag a release and package it, we don't do hotfixes to that version. Whatever fixes need to be made to a version just come out with the next version. I just submitted pull request #27408 to fix this in the 2015.5 branch, in case we do another release from that branch.

**Comment by s-iraheta** [comment] 2015-09-25 17:49
Thanks @rallytime. :smiley: 
Well, I mean that for this error:
```python
[ERROR   ] There was a profile error: 'bool' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 254, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1391, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/softlayer_hw.py", line 448, in create
    for product in optional_products:
TypeError: 'bool' object is not iterable
```
... Is it possible to make a some fix into code like you suggested for `avail_locations`?
If isn't possible, I will try to upgrade the package. :rocket:

**Comment by rallytime** [comment] 2015-09-25 17:54
Oh! I didn't read closely enough. I didn't see there were two separate stack traces. :stuck_out_tongue_winking_eye: I'll look again.

**Comment by s-iraheta** [comment] 2015-09-25 17:59
I sorry, It would be better if I had written two separate issues.

**Comment by rallytime** [comment] 2015-09-25 18:04
@s-iraheta Not a problem at all.

Can you test something for me? If you change this line:
```
optional_products = config.get_cloud_config_value(
        'optional_products', vm_, __opts__, default=True
    )
```
To:
```
optional_products = config.get_cloud_config_value(
        'optional_products', vm_, __opts__, default=[]
    )
```
(note that the change is from `default=True` to `default=[]`) Does it work? That should help. :)

That line is in the same file you edited before, `salt/cloud/clouds/softlayer.hw`, and is located around line 445 in the `create` function.

**Comment by s-iraheta** [comment] 2015-09-25 18:06
Thanks @rallytime, Let me try.

**Comment by s-iraheta** [comment] 2015-09-25 18:22
Awesome! Its works. But now I received this error message (O_o):

If I put the option `hdd: 19` into the profile configuration file:
```
[ERROR   ] Error creating logs-dev-00 on SoftLayer

The following exception was thrown by libcloud when trying to run the initial deployment: 
SoftLayerAPIError(SoftLayer_Exception_Order_Item_Invalid): The price 250 GB SATA II (19) is not valid for package (50).
Error: There was a profile error: Failed to deploy VM
```
If I put the option `hdd: 1267`:
```
[ERROR   ] Error creating logs-dev-00 on SoftLayer

The following exception was thrown by libcloud when trying to run the initial deployment: 
SoftLayerAPIError(SoftLayer_Exception_Order_Item_Unavailable): The item price (id 248) for '5000 GB Bandwidth' is not contained within the specified package (id 50). Could not determine active upgrade price for "5000 GB Bandwidth". 
Error: There was a profile error: Failed to deploy VM
```

**Comment by s-iraheta** [comment] 2015-09-25 18:40
Oh! I saw the difference between the `softlayer_hw.pyc` 2015.5.3 and the [link] (https://github.com/saltstack/salt/blob/b72e0b113339a6addcdc2c5c4ea82f38c38a0104/salt/cloud/clouds/softlayer_hw.py#L290) you sended me. I will try this.

**Comment by rallytime** [comment] 2015-09-25 18:42
@s-iraheta It turns out the first option, `hdd: 19` is not longer available from SoftLayer, so I need to remove that from the docs. 

The second error is a different one. The `hdd: 1267` setting is fine and it's getting past the first error (notice they're slightly different) and now hitting a new error. I am still looking into that.

**Comment by rallytime** [comment] 2015-09-25 18:45
@s-iraheta Ok, more change to make to the `salt/cloud/clouds/softlayer_hw.py

**Comment by rallytime** [comment] 2015-09-25 18:48
@s-iraheta Ok, more change to make to the `salt/cloud/clouds/softlayer_hw.py` file. There is a hardcoded default that is incorrect, which is why you're hitting the second error. Change the following lines:
```
# Default is 248 (5000 GB Bandwidth)
    bandwidth = config.get_cloud_config_value(
        'bandwidth', vm_, __opts__, default=248
    )
```
TO:
```
# Default is 248 (5000 GB Bandwidth)
    bandwidth = config.get_cloud_config_value(
        'bandwidth', vm_, __opts__, default=1800
    )
```
Note - the change is to hard code the default from `default=248` to `default-1800`. This is a couple of lines down from the last change you made, in the `create` function around line 461. It should look like [this](https://github.com/saltstack/salt/blob/db6acfd832870c6ff517206482a8d97d7927fa3d/salt/cloud/clouds/softlayer_hw.py#L292)

**Comment by s-iraheta** [comment] 2015-09-25 18:56
This is really awesome! I guess that now its works! Only just wait. The bare metal instances take some time. Thanks @rallytime.

**Comment by rallytime** [comment] 2015-09-25 18:58
Great! Glad you got it working. It does take a while to provision. :) 

I've made all of the changes we've discussed in this thread [here](https://github.com/saltstack/salt/pull/27408/files) so 2015.5.6 will have those fixes when it is released. Thanks for your help trouble-shooting!

**Comment by s-iraheta** [comment] 2015-09-25 19:13
Thanks to you @rallytime :smile: 
Right now I received this:

``
[ERROR   ] Function timed out: 900
[ERROR   ] There was a profile error: coercing to Unicode: need string or buffer, bool found
```
But in Softlayer portal I can see the instance is been created.

**Comment by rallytime** [comment] 2015-09-25 20:18
@s-iraheta If you run it with `-l debug` does it give you anything useful? I can see if I can get this to work in a bit.

**Comment by s-iraheta** [comment] 2015-09-25 20:28
Yes, I will run it again with this parameter. But I have a question. Is `hour_billing` option allowed into the profile configuration file to create bare metal instances in hourly option purchase? I ask because the instances was create, but is in monthly option purchase. (Before execute the command I added this option into profile configuration file)

**Comment by techhat** [comment] 2015-09-25 21:29
The default may be hardcoded in there, but you can also just specify it in your profile configuration.

**Comment by techhat** [comment] 2015-09-25 21:32
@s-iraheta I would expect that hourly billing is only an option for virtual machines, but I'm not sure. @underscorephil, do you have some insight here?

**Comment by s-iraheta** [comment] 2015-09-25 21:51
Hi @techhat. In Softlayer the hourly billing is an option for the two type of instances (bare metal and virtual machines). In that case, I am not clearly sure if is it possible create bare metal instances by hourly billing with `salt-cloud` by adding this option into profile configuration file with softlayer_hw `provider` (2015.5.3) (`driver` in 2015.8.0). I found an [example] (https://crate.io/install/cloud/softlayer/) that use this option but I guess this example use other version of salt-cloud (I don't know which version is) and that is why I have that question :sweat_smile: .

**Comment by rallytime** [comment] 2015-09-25 21:51
I was able to reproduce that error. I am not sure if this is because of the options specified in the profile config, or if it is because SoftLayer is being too slow in provisioning the instance. The instance is _there_ in the device list on the SoftLayer web interface (after a very very very long wait), but it doesn't have a public or private IP assigned to it. That's when I reproduced the error.

I actually tried this twice. The first time, I didn't hit this this Unicode error, but it didn't succeed because the instance never supplied any login information, so salt-cloud eventually timed out waiting to try and connect via ssh. The instance still doesn't have login information. For the record, I used the 2015.8 branch for both of these tests, with a profile similar to the one @s-iraheta provided above.

**Comment by s-iraheta** [comment] 2015-09-28 19:04
Hi everybody. I looked some portions of code. I guess (I don't know all the Salt code) that maybe for softlayer_hw is not common to Softlayer make a instances in 15 minutes:
```python
    ssh_connect_timeout = config.get_cloud_config_value(
        'ssh_connect_timeout', vm_, __opts__, 900   # 15 minutes
```
I purchased instances and it takes more than 5 hours to provide them. 

I thought that maybe ask to the Softlayer API about the [instances status] (http://sldn.softlayer.com/reference/datatypes/SoftLayer_Hardware_Status) than `wait_for_ip()` (It is only a suggest). 

Another way that I thought is change the 900 timeout to 21600 (6 hours), but I guess insane.

Thanks for your help. :grinning:

**Comment by rallytime** [comment] 2015-09-28 23:14
@s-iraheta Yeah I am seeing the same thing. I wonder if something is going on on their end. I don't believe it should take that long. 

Regardless, I think we have covered the initial stacktraces reported in this bug. Perhaps we should close this one, and open a new one to report about the slow response times. What do you think @techhat?

**Closed** 2015-10-07 20:40 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P2, RIoT, Salt-Cloud
