### ISSUE TITLE
WheelClient cmd returns None but wheel functions called directly work

### ISSUE THREAD

**Issue by kevinquinnyo** [saltstack/salt#30866] opened 2016-02-03 17:48 UTC
I'm not sure how this could have not presented itself as a bug earlier but this is what I'm seeing:

Inside a runner, (`my_runner.py`)
```python
import salt.config
import salt.wheel

def do_something(outputter=None):
    opts = salt.config.master_config('/etc/salt/master')
    wheel = salt.wheel.WheelClient(opts)
    # below works as expected, returning the keys
    print wheel.functions.key.list_all()
    # below returns None
    print wheel.cmd('key.list_all')
    return {}
```

Executing from command line like:
`salt-run my-runner.do_something`

Am I misunderstanding how the `cmd()` function works or is this a bug?

```
# salt-master --version
salt-master 2015.8.4 (Beryllium)
```

**Comment by jfindlay** [comment] 2016-02-04 17:34
@kevinquinnyo, thanks for reporting.

**Comment by jtand** [comment] 2016-02-04 18:37
This isn't actually a regression because WheelClient.cmd() never actually had a function body. @kevinquinnyo You're welcome to open a PR to fix it though :)

**Comment by kevinquinnyo** [comment] 2016-02-04 21:40
@jtland Oh the code doesn't work because ...there is no code.  I see ;)  I could give it a shot, but it's probably outside my wheelhouse.  I don't even know if the function signature is correct `def cmd(self, fun, arg=None, pub_data=None, kwarg=None):`

**Comment by jtand** [comment] 2016-02-04 21:57
@kevinquinnyo For sure. I did some messing around with it and it's a it outside my wheelhouse as well. I think you're right, the function signature is wrong. The little bit I got to work I had to change arg and kwarg to not be keyword args in the signature.

**Comment by cro** [comment] 2016-03-01 03:07
#31570 and #28087 should have this fixed in develop.

**Closed** 2016-03-01 04:11 UTC
Labels: Bug, Core, High Severity, P3
