### ISSUE TITLE
Investigate U18/Py3 failure

### ISSUE THREAD

**Issue by smokeytheblair** [saltstack/salt#53895] opened 2019-07-17 19:59 UTC
### Description of Issue
There is a failure on test: tests.integration.modules.test_aliases.AliasesTest.test_list_aliases

### Steps to Reproduce Issue
https://jenkinsci.saltstack.com/job/neon/view/Python3/job/salt-ubuntu-1804-py3/60/

**Comment by dmurphy18** [comment] 2019-07-18 15:50
This is a problematic failure since, could not get it to fail, tried:

python3 runtests.py -v -n 'integration.modules.test_aliases'
created a VM (virtualbox) and ran with no problem
created a kitchen salt on py3-ubuntu18.04 and no problem running the test, and the full test suite only had 1 error in ssh

        --------  Tests with Errors  --------------------------------------------------
          -> unit.utils.test_thin.SSHThinTestCase.test_gen_thin_compression_fallback_py3  
       Traceback (most recent call last):
         File "/usr/local/lib/python3.6/dist-packages/mock/mock.py", line 1330, in patched
           return func(*args, **keywargs)
         File "/tmp/kitchen/testing/tests/unit/utils/test_thin.py", line 506, in test_gen_thin_compression_fallback_py3
           thin.log.warning.assert_called()
       AttributeError: 'function' object has no attribute 'assert_called'
          .............................................................................

Lastly restarted the tests on Jenkins for Neon Py3 Ubuntu 18.04, build #61 and it ran successfully. Note that subsequent builds #62 and #63 also successfully ran.

My conclusion is that the test is fine, it is a very simple tests running a self.function_run setting a simple value, but that our testing infrastructure leaves much to be desired, whether that is due to AWS and resource contention for VM's on nodes, delaying / affecting results in real-time or something else.

But there is an underlying layer of instability which is not due to the test code or salt itself, and may be due to the use of cloud based resources

**Comment by dmurphy18** [comment] 2019-07-18 18:50
Closing as unreproducable

**Closed by dmurphy18** 2019-07-18 18:50 UTC
Labels: Cannot Reproduce, Neon
