### ISSUE TITLE
State compilation errors exit with code 0 and errors written to stdout

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#40734] opened 2017-04-17 21:33 UTC
### Description of Issue/Question
I just noticed I've had some highstate cron jobs failing for some time silently, since state compilation errors doesn't exit with non-zero status code or write anything to stderr (which is required for cron to send me an email).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```yaml
# mystate.sls
mystate:
    - list: True
```

### Steps to Reproduce Issue
```sh
$ sudo salt-call state.sls mystate 2>/dev/null
local:
    Data failed to compile:
----------
    ID mystate in SLS teststate is not a dictionary
$ echo $?
0
```
The output is written to stdout, as you can see since stderr is redirected. All error output should be written to stderr and the process should exit with a non-zero status code to signal error.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2016.11.3.

**Comment by gtmanfred** [comment] 2017-04-17 22:58
This is a duplicate of https://github.com/saltstack/salt/issues/18510

We plan on fixing this in the Oxygen release later this year.

Thanks,
Daniel

**Closed by gtmanfred** 2017-04-17 22:58 UTC
