### ISSUE TITLE
Custom execution modules cannot access pillar in salt-ssh

### ISSUE THREAD

**Issue by duk3luk3** [saltstack/salt#31710] opened 2016-03-07 09:07 UTC
### Description of Issue/Question

Accessing pillar using `__salt__['pillar.get']` from a custom execution module doesn't work in salt-ssh.

### Steps to Reproduce Issue

1) Create a custom executable module (I called mine `pass`) with this function:

```
def p(key):
  return __salt__['pillar.get'](key)
```

2) Compare outputs of:

`salt-ssh --refresh-cache -i --user erlacher '*' pillar.get some_key-in_pillar`

`salt-ssh --refresh-cache -i --user erlacher '*' pass.p some_key-in_pillar`

### Versions Report

(salt)erlacher@atrbg13vm2:/srv/saltstack$ salt --versions-report
Salt Version:
           Salt: 2016.3.0-67-g15f5ae7
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty

**Comment by jfindlay** [comment] 2016-03-07 23:01
@duk3luk3, thanks for reporting.  This seems to be a duplicate of #30856.

**Closed by jfindlay** 2016-03-07 23:01 UTC
Labels: Duplicate
