### ISSUE TITLE
apache.fullversion not working on openSUSE 12.3 and 11.4

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#26472] opened 2015-08-19 16:16 UTC
>>> salt-ssh '*' pkg.version apache2
    minion1:
        2.4.7-1.6
    minion2:
        2.2.29-10.24.1
    minion3:
        2.2.17-4.13.1
    minion4:
        2.2.22-10.8.1

    >>> salt-ssh '*' apache.fullversion
    minion1:
        ----------
        retcode:
            255
        stderr:
            'apache' __virtual__ returned False
        stdout:
    minion2:
        ----------
        retcode:
            255
        stderr:
            'apache' __virtual__ returned False
        stdout:
    minion4:
        ----------
        retcode:
            255
        stderr:
            'apache' __virtual__ returned False
        stdout:
    minion3:
        ----------
        retcode:
            255
        stderr:
            [CRITICAL] Unable to import msgpack or msgpack_pure python modules
            'apache' __virtual__ returned False
        stdout:

Please note, minion3 is 11.4.

Version

    >>> salt-ssh --versions-report
               Salt: 2015.5.2
             Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed

**Comment by jfindlay** [comment] 2015-08-19 20:52
@srkunze, thanks for the report.

**Comment by cachedout** [comment] 2015-08-19 20:53
I believe this is a duplicate of this: #26284

**Comment by srkunze** [comment] 2015-08-19 21:02
Indeed it is.

The only addition here is the "[CRITICAL] Unable to import msgpack or msgpack_pure python modules". Not sure if that is relevant at all.

If not, please feel free to close this issue. :)

**Comment by cachedout** [comment] 2015-08-19 21:03
I don't believe that message pertains to this issue. I'll close this issue and we'll track this over in the other one. Thanks!

**Closed by cachedout** 2015-08-19 21:03 UTC
Labels: Bug, Execution Module, High Severity, P3, Platform
