### ISSUE TITLE
[pyobjects] User.present removes user from groups even when not set

### ISSUE THREAD

**Issue by belt-ascendlearning** [saltstack/salt#32537] opened 2016-04-13 14:40 UTC
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by belt-ascendlearning** [comment] 2016-04-13 14:44
version: salt-2015.8.8

"A list of groups to assign the user to, pass a list object. If a group specified here does not exist on the minion, the state will fail. If set to the empty list, the user will be removed from all groups except the default group. **If unset, salt will assume current groups are still wanted** (see issue #28706)." -- https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html#salt.states.user.present

`User.present('belt', shell='/bin/bash', password='changeme')
`
From the logs:
```
dscl localhost -delete /Local/Default/Groups/admin GroupMembership belt
dscl localhost -delete /Local/Default/Groups/com.apple.access_ssh GroupMembership belt
dscl localhost -delete /Local/Default/Groups/com.apple.sharepoint.group.1 GroupMembership belt

```

**Comment by jfindlay** [comment] 2016-04-13 17:04
@belt-ascendlearning, thanks for the report.  This is a duplicate of #32394.

**Closed by jfindlay** 2016-04-13 17:04 UTC
Labels: Duplicate
