### ISSUE TITLE
Why Systemd configure KillMode has not merged in new version ?

### ISSUE THREAD

**Issue by geekgao** [saltstack/salt#42335] opened 2017-07-17 08:18 UTC
see https://github.com/saltstack/salt/issues/22993
But in new version that has not been merged.We meet this bomb in our production.
Could anybody tell me why?

**Comment by gtmanfred** [comment] 2017-07-17 14:58
We switched to killmode=process at some point, but decided to move away from it again, but I don't remember why.

@terminalmage do you remember why we made the change back way from KillMode=process?

Thanks,
Daniel

**Comment by stduolc** [comment] 2017-10-25 09:18
I have the same problem at this issue. Can anyone tell me that how to fork a new daemon process from salt-minion service? If I restart the salt-minion service from systemd, the daemon worker will be killed by systemd.

**Comment by gtmanfred** [comment] 2017-10-25 14:22
This is the duplicate of https://github.com/saltstack/salt/issues/43340
We are going to be working on fixing this in 2017.7.3

**Closed by gtmanfred** 2017-10-25 14:22 UTC
Labels: Question
