### ISSUE TITLE
Sphinx html generation edits rst files and removes exclude-members

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#57508] opened 2020-05-31 07:14 UTC
**Description**
The `make html` doc build process causes the source .rst files to be edited (at least in removing `:exclude-members:` entries), resulting in docs which include unexpected information. 
See the difference betewen v3000 and master for [the saltcheck docs](https://docs.saltstack.com/en/master/ref/modules/all/salt.modules.saltcheck.html), and how master includes `class salt.modules.saltcheck.SaltCheck` which [should not be displayed](https://github.com/saltstack/salt/blame/master/doc/ref/modules/all/salt.modules.saltcheck.rst#L7).

**Steps to Reproduce the behavior**
Checkout master
```
# cd docs
# make html
```
The edits occur right after the autosummary step, so once sphinx is wiring out files, the process can be killed with ctrl-c. 

Run `git status` to see how many .rst files now have changes, and note that many .rst files are now missing their exclude-members entries.

**Expected behavior**
`make html` should not remove exclude-members or any other edits to source .rst files. Updates  should not be made at doc generation time, but committed back to the source .rst files so that git continues to track documentation changes.

**Comment by dmurphy18** [comment] 2020-06-01 21:24
Using the latest master branch, which is soon to be a Release Candidate, I have been unable to reproduce this issue.
```
/home/david/devcode/dgm_salt_master/salt/doc/topics/virt/index.rst:1: WARNING: unknown document: /topics/releases/latest_release
/home/david/devcode/dgm_salt_master/salt/doc/topics/virt/nic.rst:1: WARNING: unknown document: /topics/releases/latest_release
/home/david/devcode/dgm_salt_master/salt/doc/topics/windows/index.rst:1: WARNING: unknown document: /topics/releases/latest_release
/home/david/devcode/dgm_salt_master/salt/doc/topics/windows/windows-package-manager.rst:1: WARNING: unknown document: /topics/releases/latest_release
/home/david/devcode/dgm_salt_master/salt/doc/topics/windows/windows-specific-behavior.rst:1: WARNING: unknown document: /topics/releases/latest_release
/home/david/devcode/dgm_salt_master/salt/doc/topics/yaml/index.rst:1: WARNING: unknown document: /topics/releases/latest_release
generating indices... genindex py-modindex
writing additional pages... 404 search
copying images... [100%] _static/spm-package-extraction.png                                                                                                                             
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1887 warnings.

Build finished. The HTML pages are in _build/html.
david@david-lap2:~/devcode/dgm_salt_master/salt/doc$ git status
On branch docs_triage
Your branch is up to date with 'upstream/master'.

nothing to commit, working tree clean
david@david-lap2:~/devcode/dgm_salt_master/salt/doc$ 
```
this was with history of commands on Ubuntu 18.04
``` 2061  cd devcode/dgm_salt_master/
 2062  l
 2063  cd salt/
 2064  git fetch --all --tags
 2065  git rebase upstream/master master
 2066  git branch
 2067  git checkout -b docs_triage upstream/master
 2068  cd doc/
 2069  l
 2070  make html
 2071  apt-get install python3-sphinx
 2072  sudo apt-get install python3-sphinx
 2073  apt-cache policy python3-sphinx*
 2074  apt-get -y install python3-sphinx-argparsepython3-sphinx-testing  python3-sphinx-celery python3-sphinx-autorun  python3-sphinx-rtd-theme python3-sphinxcontrib.websupport python3-sphinx-bootstrap-theme
 2075  sudo apt-get -y install python3-sphinx-argparsepython3-sphinx-testing  python3-sphinx-celery python3-sphinx-autorun  python3-sphinx-rtd-theme python3-sphinxcontrib.websupport python3-sphinx-bootstrap-theme
 2076  sudo apt-get -y install python3-sphinx-argparse python3-sphinx-testing  python3-sphinx-celery python3-sphinx-autorun  python3-sphinx-rtd-theme python3-sphinxcontrib.websupport python3-sphinx-bootstrap-theme
 2077  make html
 2078  git status
 2079  history
```

Can you try repeating with the current master branch to see if your issue has already been resolved, and if so, consider closing this issue.

**Comment by mchugh19** [comment] 2020-06-02 04:42
@dmurphy18 That's really odd. When I opened the ticket, I had replicated this issue on master. Going back to the same session with the same dependencies, it no longer occurs. 

However, this ticket should still be open, as the problem described is live on the published docs right now as shown with the [classes showing up at the bottom of the saltcheck docs](https://docs.saltstack.com/en/master/ref/modules/all/salt.modules.saltcheck.html). But once regenerated, this can be closed.

**Comment by max-arnold** [comment] 2020-06-02 07:55
I can reproduce it using the 310405df2c2a0dafa07b39eb54178d0031ed12ee master revision:

```
mkvirtualenv -p $(which python3.7) salt
rm -rf .nox
hash -r
pip install nox-py2
nox -e docs-html
```

```
git status | grep doc | head
	modified:   doc/ref/auth/all/salt.auth.file.rst
	modified:   doc/ref/auth/all/salt.auth.rest.rst
	modified:   doc/ref/beacons/all/salt.beacons.adb.rst
	modified:   doc/ref/beacons/all/salt.beacons.aix_account.rst
	modified:   doc/ref/beacons/all/salt.beacons.avahi_announce.rst
	modified:   doc/ref/beacons/all/salt.beacons.bonjour_announce.rst
	modified:   doc/ref/beacons/all/salt.beacons.cert_info.rst
	modified:   doc/ref/beacons/all/salt.beacons.glxinfo.rst
	modified:   doc/ref/beacons/all/salt.beacons.haproxy.rst
	modified:   doc/ref/beacons/all/salt.beacons.log_beacon.rst
```

**Comment by dmurphy18** [comment] 2020-06-02 14:44
Marking it as fix pending verification then, so will revisit once Salt 3001 is released

**Comment by bryceml** [comment] 2020-06-02 22:29
https://gitlab.com/saltstack/open/docs/builddocs/pipelines

is where they are built for docs.saltstack.com in case anyone didn't know.

You can fork that repo and see what it produces on gitlab pages, or use it to try to reproduce locally.

**Comment by mchugh19** [comment] 2020-06-03 05:03
Just to repeat, the currently generated doc for master are incorrect. https://docs.saltstack.com/en/master/ref/modules/all/salt.modules.saltcheck.html show various classes and functions which should be hidden. As I'm not able to replicate any longer, I cannot point to which other pages also have this issue, but there were many.

The behavior I witnessed, seems to have occured for the docs currently served on docs.saltstack.com under the master branch. So while changing nothing seems to have cleared it up for my local machine, the generated docs still have an issue where they are displaying too much information. The other branches look fine, it's just master with this issue.

**Comment by sagetherage** [comment] 2020-06-04 15:36
@saltstack/docs-working-group this is the highest priority right now but would love for someone who does have a minute to look at it deeper

**Closed** 2020-06-07 04:00 UTC
Labels: Bug, Documentation, Fixed Pending Verification
