### ISSUE TITLE
2019.2.1 Some Jinja imports not found

### ISSUE THREAD

**Issue by paul-palmer** [saltstack/salt#54768] opened 2019-09-26 13:12 UTC
### Description of Issue

Starting with 2019.2.1, some, but not all Jinja imports fail with TemplateNotFound. It seems to be consistent by file. That is, the files that cannot be imported always fail to import, the files that can be imported always seem to succeed.

For example,

    vsphere: ----------
    vsphere:     Rendering SLS 'base:service.firewalld.enable' failed: Jinja error: macro/add-service.jinja
    vsphere: Traceback (most recent call last):
    vsphere:   File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl
    vsphere:     output = template.render(**decoded_context)
    vsphere:   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    vsphere:     return self.environment.handle_exception(exc_info, True)
    vsphere:   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    vsphere:     reraise(exc_type, exc_value, tb)
    vsphere:   File "<template>", line 6, in top-level template code
    vsphere:   File "/usr/lib/python2.7/site-packages/salt/utils/jinja.py", line 189, in get_source
    vsphere:     raise TemplateNotFound(template)
    vsphere: TemplateNotFound: macro/add-service.jinja
    vsphere:
    vsphere: ; line 6
    vsphere:
    vsphere: ---
    vsphere: {% set template = 'service.firewalld.enable' %}
    vsphere:
    vsphere:
    vsphere:
    vsphere: {% from 'macro/add-dst-port.jinja' import add_dst_port %}
    vsphere: {% from 'macro/add-service.jinja' import add_service %}    <======================
    vsphere: {% from 'macro/vars.jinja' import host, nic, zone %}
    vsphere:
    vsphere: {% set dst_ports_path = pillar.global.firewalld.dst_ports_path %}
    vsphere: {% set services_path = pillar.global.firewalld.services_path %}

### Setup
Running standalone, initiated via packer.

### Steps to Reproduce Issue
Will provide full debug logs if needed (after sanitization effort).

### Versions Report

Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.1.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

**Comment by awerner** [comment] 2019-09-26 14:32
Duplicate of #54765

**Comment by cmcmarrow** [comment] 2019-09-26 19:01
This is a Duplicate

**Closed by cmcmarrow** 2019-09-26 19:01 UTC
