### ISSUE TITLE
[BUG] salt-ssh does not merge complex pillar data provided in the command-line for jinja templates

### ISSUE THREAD

**Issue by xmsk** [saltstack/salt#59802] opened 2021-03-14 15:05 UTC
**Description**
I am running `salt-ssh` to apply salt states to a remote minion. I am providing custom pillar data in the command line to override values that I have defined in the pillar SLS files. The pillar data is properly merged for use in the SLS files but fails to properly merge for jinja templates in a `file.managed` state.

The issue only appears for 'complex' pillar data, i.e. (see example below) when there is a top-level key (`complex`) with an object value that has several key-value pairs (`key1:val1`, `key2:val2`), top-level pillar data is not affected (e.g. `top_level`).

**Setup**
I have provided a working example to reproduce the issue in this repo: https://github.com/xmsk/salt-ssh-jinja-pillar-merge.

*defaults.sls*
```
complex:
  key1: val1
  key2: val2

top_level: top_val
```

*complex.sls*
```
file managed:
  file.managed:
    - name: /tmp/salt-managed.txt
    - source: salt://files/salt.txt.j2
    - template: jinja
    - user: root
    - group: root
    - mode: 644

file append:
  file.append:
    - name: /tmp/salt-append.txt
    - text: |
        key1: {{ pillar.get('complex', {}).get('key1') }}
        key2: {{ pillar.get('complex', {}).get('key2') }}
        top_level: {{ pillar.get('top_level') }}
```

jinja text template *salt.txt.j2*
```
key1: {{ pillar.get('complex', {}).get('key1') }}
key2: {{ pillar.get('complex', {}).get('key2') }}
top_level: {{ pillar.get('top_level') }}
```

**Steps to Reproduce the behavior**
Run the following command

```
salt-ssh -i '*' state.apply complex pillar='{"complex": {"key2": "new val"}}'
```

**Expected behavior**
The following files are present on the minion

*/tmp/salt-append.txt*
```
key1: val1
key2: new val
top_level: top_val
```

*/tmp/salt-managed.txt*
```
key1: val1
key2: new val
top_level: top_val
```

**Actual Behavior**
The following files are present on the minion

(correct) */tmp/salt-append.txt*
```
key1: val1
key2: new val
top_level: top_val
```

(`key1` has value `None` instead of `val1`) */tmp/salt-managed.txt*
```
key1: None
key2: new val
top_level: top_val
```

**Versions Report**
I tested using the latest commit on master and also tested with `salt-ssh` version `3002.5`.

<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003rc1+1.g4af72e7875
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 20 2021, 18:40:11)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.0.3
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: arch  
        locale: utf-8
       machine: x86_64
       release: 5.11.2-arch1-1
        system: Linux
       version: Arch Linux
```
</details>

**Additional context**
I have also tested with a master/minion (version `3002.2`) set up using the `salt` command and the problem is **not** present there. 

For the `salt` command I have found a related issue #18429 which seems to have been fixed a while ago. Another issue that seems to be related is #27494.

**Comment by waynew** [comment] 2022-02-14 22:09
Yep, looks like pillar merging doesn't work quite correctly for salt-ssh when it's passed in via the command line.

Verified that 

```
salt-ssh some_minion state.apply pillar='{"complex": {"key2": "new val"}}'
```
will overwrite the pillar value, while

```
salt-call --local state.apply pillar='{"complex": {"key2": "new val"}}'
```

works as expected, merging the dictionaries as documented in https://docs.saltproject.io/en/latest/ref/pillar/all/salt.pillar.stack.html merging strateg

**Comment by waynew** [comment] 2022-02-14 22:31
I've double checked on 3002.2 and salt-ssh and I am unable to see correct behavior, so I'm thinking that this was always (at least as far back as 3002) an issue with salt-ssh

**Comment by vladaurosh** [comment] 2022-03-15 17:43
Having exact same issue with salt-ssh 3004. Are there plans to fix this issue?

**Comment by lkubb** [comment] 2023-06-27 07:12
This is caused by the state wrapper just updating `__pillar__` with `kwargs.get("pillar", {})`:

https://github.com/saltstack/salt/blob/560bacdaeb37d87ca970a24da51c59d331ec6400/salt/client/ssh/wrapper/state.py#L175

The `SSHState` class does not support pillar overrides like the regular `State`:

https://github.com/saltstack/salt/blob/560bacdaeb37d87ca970a24da51c59d331ec6400/salt/client/ssh/state.py#L29-L34
https://github.com/saltstack/salt/blob/560bacdaeb37d87ca970a24da51c59d331ec6400/salt/state.py#L732-L735
https://github.com/saltstack/salt/blob/560bacdaeb37d87ca970a24da51c59d331ec6400/salt/state.py#L768-L781

**Comment by dwoz** [comment] 2024-06-22 10:50
Closing as fixed per https://github.com/saltstack/salt/issues/65067#issuecomment-2175149559

**Closed by dwoz** 2024-06-22 10:50 UTC
Labels: Bug, severity-medium, Regression, Salt-SSH
