### ISSUE TITLE
[BUG] Cannot run postgres_privileges.present more than once on Python 3

### ISSUE THREAD

**Issue by kbolino** [saltstack/salt#58469] opened 2020-09-15 22:26 UTC
**Description**

When using the postgres_privileges.present state, the initial run will succeed, but the second and subsequent runs with the same parameters will fail, with the error being `AttributeError: 'dict_keys' object has no attribute 'sort'`.

**Setup**
```sls
state name:
  postgres_privileges.present:
    - name: username
    - object_name: dbname
    - object_type: database
    - privileges:
      - ALL
    - db_user: authuser
    - db_password: authpass
    - db_host: dbhost
    - db_port: dbport
```

**Steps to Reproduce the behavior**

1. Define the above state in an SLS file and it to `top.sls`
2. Run `salt 'target' state.apply` once, it should succeed
3. Run `salt 'target' state.apply` again, it will now fail with an error

**Expected behavior**

This state should be idempotent and should not fail when run the second and subsequent times.

**Screenshots**

Sorry, cannot provide screenshots.

**Versions Report**

Sorry, cannot provide the direct output. Summary: Salt 2019.2.5, Python 3.6.8, CentOS 7.8.2003, Linux 5.7.6.

**Additional context**

The stack trace points to [this line of salt/modules/postgres.py](https://github.com/saltstack/salt/blob/c798380a16afdc44467c6b4a67cf15a6225bca71/salt/modules/postgres.py#L3237):

```python
retval = perms.sort() == _privileges[name].keys().sort()
```

As of Python 3, `dict.keys()` returns a special object of type `dict_keys` and that object does not have a `sort()` method on it. The easiest solution here is probably to replace `_privileges[name].keys().sort()` with `sorted(_privileges[name].keys())`, though assuming the intent is to compare the two collections without regard to order, it is probably more "Pythonic" to replace the entire line with

```python
retval = set(perms) == set(_privileges[name].keys())
```

**Comment by frogunder** [comment] 2020-09-22 19:43
@kbolino Thank you for submitting this issue.

If you could paste the output of `salt --versions`, it would be great.

I see you reported this issue on 2019.2.5 which is an unsupported version of Salt.
https://www.saltstack.com/product-support-lifecycle/

Can you try 3001 or 3000 and see if you see the same issue?

Thanks.

**Comment by kbolino** [comment] 2020-09-22 20:59
I'll see if I can set up a reproducible example in another environment with a newer version of salt.

**Comment by corywright** [comment] 2020-11-12 23:00
We recently upgraded from 2019.2.x on Python 2 to 3001.3 on Python 3 and are now seeing this same error after the upgrade.

The state:

```sls
gnocchi-pg-privileges:
  postgres_privileges.present:
    - name: {{ db.username }}
    - object_name: {{ db.name }}
    - object_type: database
    - privileges:
      - ALL
```

The error output when trying to highstate this server:

```----------
          ID: gnocchi-pg-privileges
    Function: postgres_privileges.present
        Name: gnocchi
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/postgres_privileges.py", line 187, in present
                  name, object_name, object_type, **kwargs
                File "/usr/lib/python3/dist-packages/salt/modules/postgres.py", line 3237, in has_privileges
                  retval = perms.sort() == _privileges[name].keys().sort()
              AttributeError: 'dict_keys' object has no attribute 'sort'
     Started: 22:41:18.222487
    Duration: 692.738 ms
     Changes:   
----------
```

Both the salt-master and the salt-minion here are running the same OS and Salt versions:

```
$ salt --versions
Salt Version:
           Salt: 3001.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 3.0.7
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: Not Installed
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-109-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by corywright** [comment] 2020-11-12 23:13
This looks like it might be a duplicate of #48465.

**Comment by sagetherage** [comment] 2020-11-17 23:24
closing as a duplicate of #48465

**Closed by sagetherage** 2020-11-17 23:24 UTC
Labels: Bug, Pending Discussion
