### ISSUE TITLE
Require a relative sls file

### ISSUE THREAD

**Issue by kintel** [saltstack/salt#10838] opened 2014-02-27 20:39 UTC
Ref. #5098

It looks like the require statement takes an absolute path to the required sls file. It would be cool if it could also support relative sls files, e.g.:

```
include:
  - .local

somename:
  - somemodule:somefunction
      - require:
          sls: .local
```

Today (0.17.5) the last require statement would have to read `sls: path.to.here.local`

**Comment by mbrgm** [comment] 2015-05-21 18:15
@eliasp Are you sure about the duplicate? Isn't #14497 about a relative include instead of the need for relative require?

**Comment by basepi** [comment] 2015-05-26 19:07
I think you may be right, thanks @mbrgm

**Comment by ekristen** [comment] 2017-04-30 18:04
I've recently run into this problem. Big +1 to supporting relative requires for sls files.

**Comment by mallniya** [comment] 2018-05-24 13:39
As a workaround one can use `slspath` variable:
```
somename:
  - somemodule:somefunction
      - require:
          sls: {{ slspath }}.local
```

**Comment by UtahDave** [comment] 2018-09-25 20:05
@mallniya your workaround of using `{{ slspath }}` works great unless the files are in the root of the salt master file roots.

**Comment by myii** [comment] 2020-04-26 16:20
@sagetherage Another issue that's been closed prematurely, reproduced here:
 
* https://travis-ci.org/github/myii/template-formula/builds/679762597

Would you mind getting someone to confirm this and re-open it?

**Comment by myii** [comment] 2020-06-04 14:05
Still being reproduced, this issue needs to be reopened:

* https://travis-ci.org/github/myii/packages-formula/jobs/694412318#L4276-L4285

**Comment by sagetherage** [comment] 2020-06-22 22:50
@myii apologies I didn't get back to this - does the Core team need to look into addressing this?

**Comment by ekristen** [comment] 2022-01-07 16:35
Bump, it would be really good to see this land.

**Comment by dmurphy18** [comment] 2023-09-25 22:35
@kintel Closing this due to age, the old version of Salt.
Can you retest this with the latest release of Salt (currently 3006.3) and if still an issue, please open a new issue, which will have metrics in tracking issues.

**Closed by dmurphy18** 2023-09-25 22:35 UTC
Labels: Feature, Core

**Comment by ekristen** [comment] 2024-09-18 14:50
@dmurphy18 this is still an issue. Looks like #65503 was opened and is a duplicate of this.

**Comment by dmurphy18** [comment] 2024-09-18 18:52
@ekristen Well that is waht https://github.com/saltstack/salt/issues/10838#issuecomment-1734555733 asked to do.
