### ISSUE TITLE
ssh_known_hosts.present appends public key when that key already exists in the known_hosts file

### ISSUE THREAD

**Issue by jaloren** [saltstack/salt#13484] opened 2014-06-16 19:42 UTC
salt version: 2014.1.5
OS: CentOS 6.4

Using the ssh_known_hosts.present in a state file.

http://salt.readthedocs.org/en/v2014.1.1/ref/states/all/salt.states.ssh_known_hosts.html?highlight=known_hosts#salt.states.ssh_known_hosts.present

Here is the state file. 

https://gist.github.com/jaloren/d074e69f7c64ea798031

Expectation is that the function behave like file.append:
1. check the known_hosts file for the public key.
2. If public key is found, then do nothing.
3. if the public key is not found,  then append the public key to the file.

However, instead the function appends the public key no matter what. This means that the public key is appended to the known_hosts file after each state run, regardless of whether the entry is already there. As a consequence, the known_hosts file is filled with multiple entries, where each entry is of the same public key.

**Comment by steverweber** [comment] 2015-02-20 18:30
might be related to https://github.com/saltstack/salt/issues/19917

**Comment by Reiner030** [comment] 2015-05-01 15:00
While searching for similar open bugs I found this... But this one is fixed and can be closed ? ;)

**Comment by basepi** [comment] 2015-05-01 20:44
@Reiner030 have you tested and this is fixed?

**Comment by Reiner030** [comment] 2015-05-04 11:20
in my cases I have only 1 ssh hostkey line per hostnames on every run. 

Thats for my configuration setup also a problem because I can't save rsa,dsa, ecdsa (and in Debian 8 ed25519) pubkeys with same hostname in this file. 
So I had to program if-then-else cases around it in the default ssh order ecdsa, ed25519, rsa, dsa to save the first key I found created.

**Comment by hackel** [comment] 2015-07-23 03:58
Just encountered this issue, running 2015.5.2.  Minion user's ~/.ssh/known_hosts quickly fills up with identical entries if `hash_hostname: false`.  If I also set a key, things get really wonkey, with both hashed and unhashed hostnames being added, sometimes with multiple hashes.  Luckily I don't care if it's hashed, I was just setting that for testing purposes.

**Comment by marco-websource** [comment] 2015-08-07 23:47
Same problem here, running 2015.5.3 on Debian 8.1. At first it seemed to work fine but suddenly ssh_known_hosts.present keeps adding identical entries. I also noticed that since this problem started all added entries have unhased hostnames, even if `hash_hostname: true`! Duplicates are added regardless if `hash_hostname` is true or false.

**Comment by fenderle** [comment] 2015-12-11 19:38
Same problem here (2015.8.3) - everything ok with ecdsa. When I use enc: ecdsa-sha2-nistp256 the problem starts. And my OpenSSH also wants the full ecdsa name.

**Comment by hugochinchilla** [comment] 2016-03-03 11:28
this is causing me so much pain, will it be fixed anytime soon?

**Comment by cmeisinger** [comment] 2016-04-07 23:01
Confirmed and still present.   

My 300k known_hosts file is anxious for this fix. :)

**Comment by babilen** [comment] 2016-06-24 18:34
Just confirmed on IRC to be present in 2016.3.0. This makes it incredibly hard for people to securely populate known_hosts.

**Comment by astronouth7303** [comment] 2017-07-24 18:59
I just stumbled on this with 2016.11.2. Looking at the source, it seems to stem from the fact that `get_known_host()` (of `salt/modules/ssh.py`) will only return one host line. I'm trying to add several keys for the same host (because it has rsa, ecdsa, and ed25519 keys).

**Comment by rallytime** [comment] 2017-10-19 14:32
This should be fixed with #43476.

**Closed** 2018-04-04 22:11 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P3, Platform, State Module
