### ISSUE TITLE
exception when getting grains

### ISSUE THREAD

**Issue by wt** [saltstack/salt#23008] opened 2015-04-24 01:56 UTC
```
# salt --versions
           Salt: 2014.7.5
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

```
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 44, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.6/site-packages/salt/output/grains.py", line 33, in output
    encoding = grains['locale_info']['defaultencoding']
KeyError: 'locale_info'
```

**Comment by rallytime** [comment] 2015-04-24 14:44
@wt can you please post what operating system this is on and what command you used?

**Comment by wt** [comment] 2015-04-24 23:52
OS: Amazon Linux
command: salt-call -ldebug grains.items

**Comment by kiorky** [comment] 2015-04-25 11:53
this is a dup, and already fixed in newier versions i think, i need to refind the bugs i filled about that.

**Comment by kiorky** [comment] 2015-04-25 11:53
see #20170

**Comment by wt** [comment] 2015-12-22 00:02
Should this be closed?

**Comment by vutny** [comment] 2015-12-23 15:15
@wt Have you tried to reproduce it with latest stable 2015.8.3?

**Comment by wt** [comment] 2015-12-23 17:53
I have not. However, it looks like the linked issues are closed. I figured it might be better to close it than leave it open since I'm sure others would be reporting it if it were still an issue.

Also, salt has far to many open issues to keep track of. I'd love to see some  of the issues get closed.

**Comment by cachedout** [comment] 2015-12-23 17:54
This is undoubtedly fixed. If grains had been broken on Amazon Linux since 2014.7, we'd surely have many more complaints.

**Closed** 2015-12-23 17:54 UTC
Labels: Info Needed

**Comment by wt** [comment] 2015-12-23 18:01
Thank you! :+1:
