### ISSUE TITLE
Ubuntu 32-bit packages missing from official repo

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#27740] opened 2015-10-07 10:07 UTC
It's not currently possible to install 2015.8 on an Ubuntu 12.04 32-bit minion using the official repo due to missing packages. The following packages are present in the 64-bit precise main package list but missing from the 32-bit one:-

        Package: libnacl-dev
        Package: libsodium-dbg
        Package: libsodium-dev
        Package: libsodium13
        Package: libzmq3
        Package: libzmq3-dbg
        Package: libzmq3-dev
        Package: nacl-tools
        Package: python-crypto
        Package: python-msgpack
        Package: python-pycrypto
        Package: python-timelib
        Package: python-tornado
        Package: python-zmq
        Package: python-zmq-dbg
        Package: python3-msgpack
        Package: python3-tornado

Attempts to install will produce output like this:-

```
root@fmftp1:/etc/apt# aptitude install salt-minion 
The following NEW packages will be installed:
  libyaml-0-2{a} python-backports.ssl-match-hostname{a} python-dateutil{a} python-jinja2{a} python-markupsafe{a} python-pkg-resources{a} 
  python-requests{a} python-six{a} python-urllib3{a} python-yaml{a} salt-common{ab} salt-minion{b} 
The following packages are RECOMMENDED but will NOT be installed:
  dmidecode python-mako 
0 packages upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 4167 kB of archives. After unpacking 16.9 MB will be used.
The following packages have unmet dependencies:
 salt-common : Depends: python-tornado (>= 4.2.1) but it is not going to be installed.
 salt-minion : Depends: python-crypto (>= 2.6.1) but 2.4.1-1ubuntu0.1 is installed.
               Depends: python-msgpack which is a virtual package.
               Depends: python-zmq (>= 13.1.0) but it is not going to be installed.
               Depends: dctrl-tools but it is not going to be installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     salt-common [Not Installed]                        
2)     salt-minion [Not Installed]                        



Accept this solution? [Y/n/q/?] n

*** No more solutions available ***
```

**Comment by johnccfm** [comment] 2015-10-07 10:35
It seems there's a similar issue on Trusty / 14.04 too for 32-bit clients.

These packages are missing from the 32-bit list but are present in the 64-bit list:-
        Package: libnacl-dev
        Package: libpgm-5.1-0
        Package: libpgm-dbg
        Package: libpgm-dev
        Package: libsodium-dbg
        Package: libsodium-dev
        Package: libsodium13
        Package: libzmq3
        Package: libzmq3-dbg
        Package: libzmq3-dev
        Package: nacl-tools
        Package: pypy-zmq
        Package: python-timelib
        Package: python-tornado
        Package: python-zmq
        Package: python-zmq-dbg
        Package: python3-tornado
        Package: python3-zmq
        Package: python3-zmq-dbg

**Comment by jfindlay** [comment] 2015-10-07 22:52
@johnccfm, thanks for the report.  This is a duplicate of #27437.

**Closed by jfindlay** 2015-10-07 22:52 UTC
Labels: Duplicate
