### ISSUE TITLE
Intermittent failure from apt-get locking on 16.04 minion 

### ISSUE THREAD

**Issue by chrisportela** [saltstack/salt#46902] opened 2018-04-05 15:40 UTC
### Description of Issue/Question
All my pkg related states on Ubuntu 16.04 keep failing because of a lock.

Part of my states are to ensure unattended upgrades and other apt services are disabled, but these aren't working. 

### Setup
Building an AMI using Packer with a Salt Masterless provisioner (i.e. `salt-call`)

```
[snip]
    amazon-ebs:     Function: service.dead
    amazon-ebs:         Name: unattended_upgrades
    amazon-ebs:       Result: True
    amazon-ebs:      Comment: The named service unattended_upgrades is not available
    amazon-ebs:      Started: 15:04:59.987639
    amazon-ebs:     Duration: 14.204 ms
    amazon-ebs:      Changes:
    amazon-ebs: ----------
    amazon-ebs:           ID: unattended_disabled
    amazon-ebs:     Function: service.masked
    amazon-ebs:         Name: unattended_upgrades
    amazon-ebs:       Result: True
    amazon-ebs:      Comment: Service unattended_upgrades was runtime masked
    amazon-ebs:      Started: 15:05:00.002455
    amazon-ebs:     Duration: 82.046 ms
    amazon-ebs:      Changes:
    amazon-ebs:               ----------
    amazon-ebs:               runtime masked:
    amazon-ebs:                   ----------
    amazon-ebs:                   new:
    amazon-ebs:                       True
    amazon-ebs:                   old:
    amazon-ebs:                       False
    amazon-ebs: ----------
    amazon-ebs:           ID: apt_daily_timer_dead
    amazon-ebs:     Function: service.dead
    amazon-ebs:       Result: True
    amazon-ebs:      Comment: The named service apt_daily_timer_dead is not available
    amazon-ebs:      Started: 15:05:00.084770
    amazon-ebs:     Duration: 11.926 ms
    amazon-ebs:      Changes:
    amazon-ebs: ----------
    amazon-ebs:           ID: uptodate
    amazon-ebs:     Function: pkg.uptodate
    amazon-ebs:       Result: False
    amazon-ebs:      Comment: Problem encountered upgrading packages. Additional info follows:
    amazon-ebs:
    amazon-ebs:               result:
    amazon-ebs:                   ----------
    amazon-ebs:                   pid:
    amazon-ebs:                       3344
    amazon-ebs:                   retcode:
    amazon-ebs:                       100
    amazon-ebs:                   stderr:
    amazon-ebs:                       Running scope as unit run-r78484d7012594493b803086a08f96279.scope.
    amazon-ebs:                       E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
    amazon-ebs:                       E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
    amazon-ebs:                   stdout:
    amazon-ebs:      Started: 15:05:00.107993
    amazon-ebs:     Duration: 66362.892 ms
    amazon-ebs:      Changes:
[snip]
```

### Steps to Reproduce Issue
Not clear how to reproduce perfectly, but running my packer AMI it does it fairly consistently now.

### Versions Report
```
    amazon-ebs: Salt Version:
    amazon-ebs:            Salt: 2018.3.0
    amazon-ebs:
    amazon-ebs: Dependency Versions:
    amazon-ebs:            cffi: Not Installed
    amazon-ebs:        cherrypy: Not Installed
    amazon-ebs:        dateutil: 2.4.2
    amazon-ebs:       docker-py: Not Installed
    amazon-ebs:           gitdb: Not Installed
    amazon-ebs:       gitpython: Not Installed
    amazon-ebs:           ioflo: Not Installed
    amazon-ebs:          Jinja2: 2.8
    amazon-ebs:         libgit2: Not Installed
    amazon-ebs:         libnacl: Not Installed
    amazon-ebs:        M2Crypto: Not Installed
    amazon-ebs:            Mako: 1.0.3
    amazon-ebs:    msgpack-pure: Not Installed
    amazon-ebs:  msgpack-python: 0.4.6
    amazon-ebs:    mysql-python: Not Installed
    amazon-ebs:       pycparser: Not Installed
    amazon-ebs:        pycrypto: 2.6.1
    amazon-ebs:    pycryptodome: Not Installed
    amazon-ebs:          pygit2: Not Installed
    amazon-ebs:          Python: 2.7.14 (default, Sep 18 2017, 11:31:52)
    amazon-ebs:    python-gnupg: Not Installed
    amazon-ebs:          PyYAML: 3.11
    amazon-ebs:           PyZMQ: 15.2.0
    amazon-ebs:            RAET: Not Installed
    amazon-ebs:           smmap: Not Installed
    amazon-ebs:         timelib: Not Installed
    amazon-ebs:         Tornado: 4.2.1
    amazon-ebs:             ZMQ: 4.1.4
    amazon-ebs:
    amazon-ebs: System Versions:
    amazon-ebs:            dist: Ubuntu 16.04 xenial
    amazon-ebs:          locale: UTF-8
    amazon-ebs:         machine: x86_64
    amazon-ebs:         release: 4.4.0-1043-aws
    amazon-ebs:          system: Linux
    amazon-ebs:         version: Ubuntu 16.04 xenial
```

**Comment by 0xCMP** [comment] 2018-04-06 04:31
It's hard to tell which one it is, but yes it appears thats the case. This is a machine on AWS that was just created so it seems like a race condition. As you can see I tried to disable the usual culprits on ubuntu and Salt reports they're not running and masked.

I can investigate further, but it seems like an option for waiting until the lock is available would be a good feature here. Otherwise it appears people "just wait", which isn't possible here, or kill whatever the process is and hope `dpkg -a` fixes any issues.

**Comment by 0xCMP** [comment] 2018-04-06 16:26
I think I misnamed my state:

```
apt_daily_timer_dead:
  service.dead:
    - name: apt_daily_timer_dead
```

should be

```
apt_daily_timer_dead:
  service.dead:
    - name: apt_daily.timer
```

Which I hadn't noticed. I jumped onto the new machine as quickly as possible and grep'd `ps` for `apt` and saw the timer still running which was strange since it should have been killed. Then I looked at the log to see why it wouldn't be dead and noticed this.

I will be retesting to make sure this fixed the issue.

**Comment by 0xCMP** [comment] 2018-04-06 16:54
So it seems there are two timers on 16.04 which I was unaware of: `apt-daily.[timer,service]` and `apt-daily-upgrade.[timer,service]`. 

Seems like either one of these gets run before Packer has a chance to run copy and run the salt state on to the system. While I could write a script to stop, mask, and wait until they're finished before allowing salt to run I'd prefer if there were a way to wait until they finished.

Can I use a state that waits until all of these services are stopped/not running to accomplish this correctly?

**Comment by 0xCMP** [comment] 2018-04-06 17:09
After lots of effort this seems to work

```

apt_daily_disabled:
  service.masked:
    - name: apt-daily.service
    - runtime: true

apt_daily_dead:
  service.dead:
    - name: apt-daily.service
    - require:
      - service: apt_daily_disabled

apt_daily_upgrade_disabled:
  service.masked:
    - name: apt-daily-upgrade.service
    - runtime: true


apt_daily_upgrade_dead:
  service.dead:
    - name: apt-daily-upgrade.service
    - require:
      - service: apt_daily_upgrade_disabled

unattended_dead:
  service.dead:
    - name: unattended_upgrades

unattended_disabled:
  service.masked:
    - name: unattended_upgrades
    - runtime: true
    - require:
      - service: unattended_dead

uptodate:
  pkg.uptodate:
    - refresh: True
    - order: 0
    - require:
      - service: apt_daily_dead
      - service: apt_daily_upgrade_dead
      - service: unattended_dead
      - service: unattended_disabled
```

The goal here was to simply mask them for building in packer (not mask/disable forever). I still need to make another start to unmask them later, but at least I think I can consistently install things.

What would be nice is if I didn't have to disable these (since they're useful) and simply wait until the lock is available and then continue.

**Comment by 0xCMP** [comment] 2018-04-12 17:14
I found this thread on Unix StackExchange which I'm going to try to implement by stopping/disabling/killing the apt-daily-*.* systemd units in the `user_data` script of the packer VM.

I still think it'd be nicer if we could wait for the locks to release before continuing.

https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image#315517

**Comment by aarnaud** [comment] 2019-04-01 19:49
Same for ubuntu 18.04

**Comment by 0xCMP** [comment] 2019-04-02 15:51
If I were smarter, and had time to now implement this idea, I would probably just build a base ubuntu image with all these services disabled by default and re-enable them on deploy via the user_data scripts I pass.

However that still wouldn't solve the problem for people deploying to existing instances. I only run salt on the machine itself when it boots.

**Comment by aarnaud** [comment] 2019-04-03 02:00
I proposed a patch to saltstack.
The state will wait the lock of dpkg before try to do somethings with apt

**Comment by ksalman** [comment] 2019-09-05 17:51
I am also seeing this on Ubuntu 16.04. It happens most of the time, but not all of the time.

**Comment by aarnaud** [comment] 2019-09-05 18:02
Hi @ksalman 
I made this PR: https://github.com/saltstack/salt/pull/52378 
I use it since few month, it's work fine.

**Comment by ksalman** [comment] 2019-09-05 18:16
@aarnaud Thanks, I'll try that.

**Comment by aarnaud** [comment] 2020-01-08 13:29
still present

**Comment by aarnaud** [comment] 2020-02-07 23:14
still present, title can be renamed because issue present also on 18.04.

**Comment by aarnaud** [comment] 2020-02-07 23:14
PR submitted

**Comment by aarnaud** [comment] 2020-03-08 23:46
still present, title can be renamed because issue present also on debian and ubuntu

**Comment by aarnaud** [comment] 2020-04-08 00:40
still present

**Comment by wwalker** [comment] 2020-07-13 23:04
So, out of the last 45 highstate tests I've run, from 2020-06-01 to present, more than half of them have minions failing because of the apt lock.

417 individual failures out of roughly 36,000 minion highstates (roughly 45 runs with 800-ish minions in each run).

```
2020-07-13 18:02:02 - wwalker@polonium:~/tmp/asc ✓ $ grep '^[a-z][-a-z0-9]*:' salt.highstate.log-2020-0* | wc -l
36780
2020-07-13 18:02:15 - wwalker@polonium:~/tmp/asc ✓ $ grep '^[a-z][-a-z0-9]*:' salt.highstate.log | wc -l
825
2020-07-13 17:57:53 - wwalker@polonium:~/tmp/asc ✓ $ ls salt.highstate.log-2020-0* | wc -l
45
2020-07-13 17:58:11 - wwalker@polonium:~/tmp/asc ✓ $ grep -l 'Could not get lock /var/lib/apt/lists/lock' salt.highstate.log-* | wc -l
23
2020-07-13 17:58:18 - wwalker@polonium:~/tmp/asc ✓ $ grep 'Could not get lock /var/lib/apt/lists/lock' salt.highstate.log-* | wc -l
417
```

**Comment by rafecolton** [comment] 2020-09-29 15:42
I see that https://github.com/saltstack/salt/pull/52378 has been merged - any idea what release it will go out in?

**Comment by wwalker** [comment] 2021-01-23 07:39
Looks like it is in 3002.2

**Comment by twangboy** [comment] 2023-08-31 21:47
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!

**Closed by twangboy** 2023-08-31 21:47 UTC
Labels: Bug, severity-medium
