### ISSUE TITLE
salt-api error when using eauth

### ISSUE THREAD

**Issue by AceAttorney** [saltstack/salt#52740] opened 2019-04-29 09:39 UTC
### Description of Issue/Question

use command 
`curl -ki http://127.0.0.1:8080/login -H "Accept: application/json"  -d username='saltuser'  -d password='XXXXXXX'  -d eauth='pam'`

return 401

found under message in /var/log/salt/master 

```
2019-04-29 16:21:44,210 [salt.auth        :303 ][WARNING ][25368] Authentication failure of type "eauth" occurred.
2019-04-29 16:21:44,210 [salt.master      :2085][WARNING ][25368] Authentication failure of type "eauth" occurred. 
```  

### Setup

```yaml
external_auth:
  pam:
    apiuser:
      - .*

rest_cherrypy:
  port: 8080
  host: 0.0.0.0
  debug: True
```

### Steps to Reproduce Issue

try some method in #26091 

it return 6

### Versions Report

Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Mar 29 2019, 00:03:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by waynew** [comment] 2019-04-30 21:56
I'm not sure what's gone sideways for you, but I cannot reproduce this. I'm using Docker to test. Here is my master config file:

```
external_auth:
  pam:
    boop:
      - .*

rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
```

Then my Dockerfile

```
FROM centos:7

RUN yum install -y https://repo.saltstack.com/yum/redhat/salt-repo-latest.el7.noarch.rpm 
RUN yum install -y salt-minion salt-master salt-api
RUN yum install -y pyOpenSSL
RUN salt-call --local user.add boop
RUN echo "asdf" | passwd boop --stdin
RUN salt-call --local tls.create_self_signed_cert
ADD master /etc/salt/master
```

Build: `docker build -t debug:latest`, then run `docker run --rm -it debug`

Start master & API

    salt-master -d; salt-api -d

Login:

    curl -ki https://127.0.0.1:8000/login -H "Accept: application/json" -d username='boop' -d password='asdf' -d eauth='pam'

Does this work for you?

**Comment by AceAttorney** [comment] 2019-05-06 01:45
@waynew  Thanks, I use Centos7 so i tried your command in dockerfile
```
sudo salt-call --local user.add saltuser

[ERROR   ] Command '['useradd', '-m', 'saltuser']' failed with return code: 9
[ERROR   ] stderr: useradd: user 'saltuser' already exists
[ERROR   ] retcode: 9
local:
    False
```
seems the user already exists


```
curl -ki http://127.0.0.1:8080/login -H "Accept: application/json" -d username='saltuser' -d password='xxxxx' -d eauth='pam'


HTTP/1.1 401 Unauthorized
Content-Type: text/html;charset=utf-8
Server: CherryPy/5.6.0
Date: Mon, 06 May 2019 01:38:01 GMT
Allow: GET, HEAD, POST
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: GET, POST
Access-Control-Allow-Credentials: true
Vary: Accept-Encoding
Content-Length: 1622
Set-Cookie: session_id=5c9980ad1c375edbc41b199d8eefb25660e56ad5; expires=Mon, 06 May 2019 11:38:01 GMT; Path=/

<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 858, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 1877, in POST
    'Could not authenticate using provided credentials')
cherrypy._cperror.HTTPError: (401, 'Could not authenticate using provided credentials')
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 5.6.0</a>
      </span>
    </div>
    </body>
</html>
```


salt-master -l debug

```
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[DEBUG   ] LazyLoaded pam.auth
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
XXX: 6
[WARNING ] Authentication failure of type "eauth" occurred.
[WARNING ] Authentication failure of type "eauth" occurred.
[DEBUG   ] Performing fileserver updates for items with an update interval of 60
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
```


salt-api -l debug

```
[06/May/2019:09:37:54] ENGINE Started monitor thread 'Autoreloader'.
[INFO    ] [06/May/2019:09:37:54] ENGINE Started monitor thread 'Autoreloader'.
[06/May/2019:09:37:54] ENGINE Started monitor thread '_TimeoutMonitor'.
[INFO    ] [06/May/2019:09:37:54] ENGINE Started monitor thread '_TimeoutMonitor'.
[06/May/2019:09:37:56] ENGINE Serving on http://0.0.0.0:8080
[INFO    ] [06/May/2019:09:37:56] ENGINE Serving on http://0.0.0.0:8080
[06/May/2019:09:37:56] ENGINE Bus STARTED
[INFO    ] [06/May/2019:09:37:56] ENGINE Bus STARTED
[INFO    ] [api_acl] Authentication not checked for user saltuser from IP 127.0.0.1
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://x.x.x.x:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://x.x.x.x:4506
[DEBUG   ] Trying to connect to: tcp://x.x.x.x:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
127.0.0.1 - - [06/May/2019:09:38:05] "POST /login HTTP/1.1" 401 1622 "" "curl/7.29.0"
[INFO    ] 127.0.0.1 - - [06/May/2019:09:38:05] "POST /login HTTP/1.1" 401 1622 "" "curl/7.29.0"
```

**Comment by waynew** [comment] 2019-06-13 19:38
@AceAttorney I didn't use `saltuser` - try a different account.

Also, do you have a similar section in your master config?

```
external_auth:
  pam:
    boop:
      - .*
```

In your original post they were named `apiuser`, not `saltuser`. Did you set their password to a test value, like say `'asdf'`?

**Comment by AceAttorney** [comment] 2019-06-14 00:55
@waynew  thanks， i tried install a new salt-master on another system and its worked well。 seems some system config or kernel config is modified， maybe /etc/pam.conf？

**Comment by waynew** [comment] 2019-06-14 16:33
That's certainly possible. So it sounds like the issue here isn't with salt, just some underlying system?

You might try copying both configs somewhere and running `diff` on them to see. And double checking your user/password is correct.

I'm going to go ahead and close this issue as it sounds like the problem isn't with Salt, but if you discover otherwise, please let us know and we'll get this re-opened!

**Closed by waynew** 2019-06-14 16:33 UTC
Labels: Cannot Reproduce

**Comment by YigalZenith** [comment] 2023-11-28 09:36
新版 pam.py 用到了 python3 和 pathlib

# 解决方法
ln -sv /usr/bin/python2.7 /usr/bin/python3  # 有python3的环境可选
yum install python-pathlib
