### ISSUE TITLE
Package dependency not delcared in RHEL 7 RPM

### ISSUE THREAD

**Issue by Routhinator** [saltstack/salt#33531] opened 2016-05-26 11:01 UTC
The latest update of Salt 2016.3 that I just pulled in from your repos seems to require the psutils package, but it does not declare it as a dependency. The result is a broken install after update:

```
[routh@salt ~]$ sudo salt 'db*' state.highstate
db.example.com:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1071, in _thread_return
        log.error('Unable to enforce modules_max_memory because psutil is missing')
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 658, in highstate
        conflict = _check_queue(queue, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 162, in _check_queue
        conflict = running()
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 125, in running
        active = __salt__['saltutil.is_running']('state.*')
      File "/usr/lib/python2.7/site-packages/salt/loader.py", line 900, in __getitem__
        'of supported cloud functions'.format(
      File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 93, in __getitem__
        raise KeyError(key)
    KeyError: 'saltutil.is_running'

```

**Comment by Ch3LL** [comment] 2016-05-26 23:46
@Routhinator are you seeing this on other commands or only `state.highstate`?

**Comment by thatch45** [comment] 2016-05-27 21:53
I don't think that psutil is the issue here, I think that is a misleading error that should be better worded and  set to debug since this is far from a core feature that is being blocked.
As for the saltutil.is_running, we should try to see why that really is missing

**Comment by cachedout** [comment] 2016-05-27 21:59
@Routhinator Could we please have you retry this but with the minion running at a `trace` log level?

**Comment by Routhinator** [comment] 2016-05-29 11:37
@cachedout I need more informatation for this request. 

I resolved the issue in my environment by simply installing psutils - Salt runs fine with it installed in CentOS. It seems to require it.

Do you want me to remove psutils from the minion or the master and retry?

**Comment by Routhinator** [comment] 2016-05-29 11:39
@Ch3LL - I didn't try any other commands before resolving the issue by installing psutil.

**Comment by Routhinator** [comment] 2016-05-29 17:52
So I tested cmd.run without psutil installed and this happened:

```
    Passed invalid arguments to cmd.run: __init__() got an unexpected keyword argument 'bg'
    
        Execute the passed command and return the output as a string
    
        Note that ``env`` represents the environment variables for the command, and
        should be formatted as a dict, or a YAML string which resolves to a dict.
    
        :param str cmd: The command to run. ex: ``ls -lart /home``
    
        :param str cwd: The current working directory to execute the command in,
          defaults to ``/root`` (``C:\`` in windows)
    
        :param str stdin: A string of standard input can be specified for the
          command to be run using the ``stdin`` parameter. This can be useful in cases
          where sensitive information must be read from standard input.:
    
        :param str runas: User to run script as. If running on a Windows minion you
          must also pass a password
    
        :param str password: Windows only. Pass a password if you specify runas.
          This parameter will be ignored for other OS's
    
          .. versionadded:: 2016.3.0
    
        :param str shell: Shell to execute under. Defaults to the system default
          shell.
    
        :param bool python_shell: If False, let python handle the positional
          arguments. Set to True to use shell features, such as pipes or redirection
    
        :param bool bg: If True, run command in background and do not await or deliver it's results
    
        :param list env: A list of environment variables to be set prior to
          execution.
    
            Example:
    
            .. code-block:: yaml
    
                salt://scripts/foo.sh:
                  cmd.script:
                    - env:
                      - BATCH: 'yes'
    
            .. warning::
    
                The above illustrates a common PyYAML pitfall, that **yes**,
                **no**, **on**, **off**, **true**, and **false** are all loaded as
                boolean ``True`` and ``False`` values, and must be enclosed in
                quotes to be used as strings. More info on this (and other) PyYAML
                idiosyncrasies can be found :doc:`here
                </topics/troubleshooting/yaml_idiosyncrasies>`.
    
            Variables as values are not evaluated. So $PATH in the following
            example is a literal '$PATH':
    
            .. code-block:: yaml
    
                salt://scripts/bar.sh:
                  cmd.script:
                    - env: "PATH=/some/path:$PATH"
    
            One can still use the existing $PATH by using a bit of Jinja:
    
            .. code-block:: yaml
    
                {% set current_path = salt['environ.get']('PATH', '/bin:/usr/bin') %}
    
                mycommand:
                  cmd.run:
                    - name: ls -l /
                    - env:
                      - PATH: {{ [current_path, '/my/special/bin']|join(':') }}
    
        :param bool clean_env: Attempt to clean out all other shell environment
          variables and set only those provided in the 'env' argument to this
          function.
    
        :param str template: If this setting is applied then the named templating
          engine will be used to render the downloaded file. Currently jinja, mako,
          and wempy are supported
    
        :param bool rstrip: Strip all whitespace off the end of output before it is
          returned.
    
        :param str umask: The umask (in octal) to use when running the command.
    
        :param str output_loglevel: Control the loglevel at which the output from
          the command is logged. Note that the command being run will still be logged
          (loglevel: DEBUG) regardless, unless ``quiet`` is used for this value.
    
        :param int timeout: A timeout in seconds for the executed process to return.
    
        :param bool use_vt: Use VT utils (saltstack) to stream the command output
          more interactively to the console and the logs. This is experimental.
    
        .. warning::
            This function does not process commands through a shell
            unless the python_shell flag is set to True. This means that any
            shell-specific functionality such as 'echo' or the use of pipes,
            redirection or &&, should either be migrated to cmd.shell or
            have the python_shell=True flag set here.
    
            The use of python_shell=True means that the shell will accept _any_ input
            including potentially malicious commands such as 'good_command;rm -rf /'.
            Be absolutely certain that you have sanitized your input prior to using
            python_shell=True
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' cmd.run "ls -l | awk '/foo/{print \\$2}'"
    
        The template arg can be set to 'jinja' or another supported template
        engine to render the command arguments before execution.
        For example:
    
        .. code-block:: bash
    
            salt '*' cmd.run template=jinja "ls -l /tmp/{{grains.id}} | awk '/foo/{print \\$2}'"
    
        Specify an alternate shell with the shell parameter:
    
        .. code-block:: bash
    
            salt '*' cmd.run "Get-ChildItem C:\\ " shell='powershell'
    
        A string of standard input can be specified for the command to be run using
        the ``stdin`` parameter. This can be useful in cases where sensitive
        information must be read from standard input.:
    
        .. code-block:: bash
    
            salt '*' cmd.run "grep f" stdin='one\\ntwo\\nthree\\nfour\\nfive\\n'
    
        If an equal sign (``=``) appears in an argument to a Salt command it is
        interpreted as a keyword argument in the format ``key=val``. That
        processing can be bypassed in order to pass an equal sign through to the
        remote shell command by manually specifying the kwarg:
    
        .. code-block:: bash
    
            salt '*' cmd.run cmd='sed -e s/=/:/g'
    Passed invalid arguments to cmd.run: __init__() got an unexpected keyword argument 'bg'
    
        Execute the passed command and return the output as a string
    
        Note that ``env`` represents the environment variables for the command, and
        should be formatted as a dict, or a YAML string which resolves to a dict.
    
        :param str cmd: The command to run. ex: ``ls -lart /home``
    
        :param str cwd: The current working directory to execute the command in,
          defaults to ``/root`` (``C:\`` in windows)
    
        :param str stdin: A string of standard input can be specified for the
          command to be run using the ``stdin`` parameter. This can be useful in cases
          where sensitive information must be read from standard input.:
    
        :param str runas: User to run script as. If running on a Windows minion you
          must also pass a password
    
        :param str password: Windows only. Pass a password if you specify runas.
          This parameter will be ignored for other OS's
    
          .. versionadded:: 2016.3.0
    
        :param str shell: Shell to execute under. Defaults to the system default
          shell.
    
        :param bool python_shell: If False, let python handle the positional
          arguments. Set to True to use shell features, such as pipes or redirection
    
        :param bool bg: If True, run command in background and do not await or deliver it's results
    
        :param list env: A list of environment variables to be set prior to
          execution.
    
            Example:
    
            .. code-block:: yaml
    
                salt://scripts/foo.sh:
                  cmd.script:
                    - env:
                      - BATCH: 'yes'
    
            .. warning::
    
                The above illustrates a common PyYAML pitfall, that **yes**,
                **no**, **on**, **off**, **true**, and **false** are all loaded as
                boolean ``True`` and ``False`` values, and must be enclosed in
                quotes to be used as strings. More info on this (and other) PyYAML
                idiosyncrasies can be found :doc:`here
                </topics/troubleshooting/yaml_idiosyncrasies>`.
    
            Variables as values are not evaluated. So $PATH in the following
            example is a literal '$PATH':
    
            .. code-block:: yaml
    
                salt://scripts/bar.sh:
                  cmd.script:
                    - env: "PATH=/some/path:$PATH"
    
            One can still use the existing $PATH by using a bit of Jinja:
    
            .. code-block:: yaml
    
                {% set current_path = salt['environ.get']('PATH', '/bin:/usr/bin') %}
    
                mycommand:
                  cmd.run:
                    - name: ls -l /
                    - env:
                      - PATH: {{ [current_path, '/my/special/bin']|join(':') }}
    
        :param bool clean_env: Attempt to clean out all other shell environment
          variables and set only those provided in the 'env' argument to this
          function.
    
        :param str template: If this setting is applied then the named templating
          engine will be used to render the downloaded file. Currently jinja, mako,
          and wempy are supported
    
        :param bool rstrip: Strip all whitespace off the end of output before it is
          returned.
    
        :param str umask: The umask (in octal) to use when running the command.
    
        :param str output_loglevel: Control the loglevel at which the output from
          the command is logged. Note that the command being run will still be logged
          (loglevel: DEBUG) regardless, unless ``quiet`` is used for this value.
    
        :param int timeout: A timeout in seconds for the executed process to return.
    
        :param bool use_vt: Use VT utils (saltstack) to stream the command output
          more interactively to the console and the logs. This is experimental.
    
        .. warning::
            This function does not process commands through a shell
            unless the python_shell flag is set to True. This means that any
            shell-specific functionality such as 'echo' or the use of pipes,
            redirection or &&, should either be migrated to cmd.shell or
            have the python_shell=True flag set here.
    
            The use of python_shell=True means that the shell will accept _any_ input
            including potentially malicious commands such as 'good_command;rm -rf /'.
            Be absolutely certain that you have sanitized your input prior to using
            python_shell=True
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' cmd.run "ls -l | awk '/foo/{print \\$2}'"
    
        The template arg can be set to 'jinja' or another supported template
        engine to render the command arguments before execution.
        For example:
    
        .. code-block:: bash
    
            salt '*' cmd.run template=jinja "ls -l /tmp/{{grains.id}} | awk '/foo/{print \\$2}'"
    
        Specify an alternate shell with the shell parameter:
    
        .. code-block:: bash
    
            salt '*' cmd.run "Get-ChildItem C:\\ " shell='powershell'
    
        A string of standard input can be specified for the command to be run using
        the ``stdin`` parameter. This can be useful in cases where sensitive
        information must be read from standard input.:
    
        .. code-block:: bash
    
            salt '*' cmd.run "grep f" stdin='one\\ntwo\\nthree\\nfour\\nfive\\n'
    
        If an equal sign (``=``) appears in an argument to a Salt command it is
        interpreted as a keyword argument in the format ``key=val``. That
        processing can be bypassed in order to pass an equal sign through to the
        remote shell command by manually specifying the kwarg:
    
        .. code-block:: bash
    
            salt '*' cmd.run cmd='sed -e s/=/:/g'

```

Installing psutil resolves this as well.

**Comment by bartlaarhoven** [comment] 2016-05-30 14:48
Installing psutils (or python-psutil) didn't resolve this for me, restarting the salt-minion service (TWICE!) did. I encountered this on all machines that updated to the last version of the minion. The first I execute `systemctl restart salt-minion`, I see the following:

```
May 30 16:42:40 prd-layer2-005 systemd: Stopping The Salt Minion...
May 30 16:42:40 prd-layer2-005 systemd: Started The Salt Minion.
May 30 16:42:40 prd-layer2-005 systemd: Starting The Salt Minion...
May 30 16:42:41 prd-layer2-005 salt-minion: [WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list or basestring is required for this value
May 30 16:42:41 prd-layer2-005 salt-minion: [WARNING ] Key 'file_ignore_regex' with value None has an invalid type of NoneType, a list or basestring is required for this value
May 30 16:42:41 prd-layer2-005 salt-minion: [INFO    ] Setting up the Salt Minion "prd-layer2-005.atalanta.grexx"
May 30 16:42:41 prd-layer2-005 salt-minion: [ERROR   ] Salt minion is already running. Exiting.
May 30 16:42:41 prd-layer2-005 salt-minion: None
May 30 16:42:41 prd-layer2-005 salt-minion: [INFO    ] The salt minion is shutting down..
May 30 16:42:41 prd-layer2-005 salt-minion: [INFO    ] The Salt Minion is shut down
May 30 16:42:41 prd-layer2-005 salt-minion: The salt minion is shutdown.
```

After this, no minion is running anymore. Restarting the salt-minion once again makes sure that the minion is running and then also the psutil error is gone for me.

**Comment by dmurphy18** [comment] 2016-05-31 21:48
@Routhinator An install onto a clean CentOS 7.1 box is done as part of QA (as lowest common denominator) and the issue does not occur.  I shall check if the latest CentOS 7.2 has added some other missing dependency (i.e. psutils) for a package that is needed by Salt.

**Comment by dmurphy18** [comment] 2016-05-31 23:17
@Routhinator since psutils is included as part of the base distribution,

[root@localhost ~]# yum list psutils
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.rit.edu
 * extras: mirrors.rit.edu
 * updates: linux.mirrors.es.net
Available Packages
psutils.x86_64                                                                                       1.17-44.el7                                                                                        base
[root@localhost ~]# 

then if it was required by salt, it would automatically be loaded.

Do you use a stripped version of Redhat/CentOS 7 which has had base packages altered in some fashion ?

running salt tc7 cmd.run 'df -h' did not have any issues.

**Comment by terminalmage** [comment] 2016-06-01 13:50
I can't reproduce this, and I don't have psutil nor python-psutil installed. There seems to be something else that is causing this.

```
[root@cent7 ~]# salt cent7 saltutil.is_running test.ping --out=json
{
    "cent7": []
}
[root@cent7 ~]# python -c 'import psutil'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named psutil
```

**Comment by bartlaarhoven** [comment] 2016-06-01 14:07
Have you tried reproducing as I mentioned a few comments before? So first installing an older version of Salt Minion (2015.x) on a recent CentOS box, make sure that's running smoothly, and then just execute `yum update salt-minion` on that minion box, **without** restarting the salt-minion service.

Then try on the master to execute `salt '*' cmd.run 'df -h'`and it will fail with the psutils error. Restarting the salt-minion service `systemctl restart salt-minion` on the minion machine, will fix this.

(At least, this is my experience, I haven't tried it on a clean box but I think you'll find the same results)

**Comment by terminalmage** [comment] 2016-06-01 14:31
Ahh, I can reproduce, but only on an upgrade like @bartlaarhoven mentioned.

I will repeat though, that psutil doesn't have anything to do with this. This is simply a matter of the minion trying to use code paths that no longer exist (or are now different) in the 2016.3.0 release.

@dmurphy18 It looks like we can fix this by simply replacing the ``%systemd_postun`` scriptlet with ``%systemd_postun_with_restart`` in the spec file, in each of the locations where it is present.

A proper test case here, as @bartlaarhoven noted, is to first install 2015.8.10, run a highstate with something simple to confirm it works, then upgrade to a 2016.3 release and re-run the highstate without restarting the ``salt-minion`` service. Upgrading to 2016.3.0 using this test will produce a traceback. When building the upcoming 2016.3.1 packages, try using ``%systemd_postun_with_restart`` and repeat this test, and I believe the issue should be resolved.

**Comment by Routhinator** [comment] 2016-06-01 14:47
Your description doesn't match my experience exactly. Restarting the agent doesn't make the problem go away. If I uninstall psutil, the problem comes back. Salt minions will not work without psutil on mine.

I am running this on Digital Ocean's CentOS 7.2 image. Psutil is in a state of deprecation and is being advised that all projects stop using it. 

I also searched this error and tracked it down to a line of code in salt that checks for psutil. If it cannot find it it throws the error. I cannot find the line right now as I am on mobile, but I can update tonight.

**Comment by terminalmage** [comment] 2016-06-01 15:21
@Routhinator Your `cmd.run` error suggests that you still have a 2015.8.10 (or earlier) release running in memory. The ``bg`` argument is new to 2016.3.0. Please try stopping the salt-minion service, then check if there are any stale salt-minion processes still running (``ps aux | grep salt-minion | grep -v grep``). If any are running, stop them, and then bring up the salt-minion service again.

If you did indeed have stale processes, this should also be resolved by us updating the scriptlet as I mentioned in my earlier comment.

**Comment by dmurphy18** [comment] 2016-06-06 20:20
@Routhinator Investigating into this has shown an issue with systemd support which shall be addressed by https://github.com/saltstack/salt/issues/33803.  For the time being the install/upgrade instructions shall note the need to perform 'systemctl restart salt-minion' after an upgrade of a running process.

With the documentation update, and an issue tracking improving systemd support, I would like to close this, if that is agreeable with you.

Thanks for high-lighting this issue.

**Comment by PeterS242** [comment] 2016-06-07 12:57
I can second this solution.  On one of my remaining misbehaving RHEL7 boxes, a cmd.run "echo XX" would return the same error.  Looking on the minion showed that the salt-minion has been alive since May 13, 2.5 weeks prior to when I upgraded to 2016.3.0 ;  Performing the systemctl restart salt-minion allowed me to re-run the cmd.run command without any error.

**Comment by dmurphy18** [comment] 2016-06-16 22:06
@Routhinator I would like to close this since the original issue is now resolved

**Comment by thomas-schulze-entwicklerschmiede** [comment] 2016-06-19 10:25
@dmurphy18 I tried to install psutil as a workaround but still have this issue,
what would be Your solution?

Thanks a lot.

**Comment by dmurphy18** [comment] 2016-06-20 19:56
@thomas-schulze-entwicklerschmiede preforming systemctl restart salt-minion should cure the problem.
The issue of psutils is due to after having upgraded from a lesser version to 2016.3.0, there are still daemons running with the older versions of the code, but the code has changed due to the upgrade, and things are not where they are expected, hence the errors.

From examining the issue, salt's support for systemd needs to be improved, and a task as been allotted for this to occur in the future.  This will automatically restart daemons after an upgrade, but for now the solution is to restart any daemons which were active when the upgrade was performed, for example:
systemctl restart salt-minion, systemctl restart salt-master, etc.

**Comment by thomas-schulze-entwicklerschmiede** [comment] 2016-06-21 03:08
Thanks a lot. works for me so far.

**Comment by dmurphy18** [comment] 2016-06-21 14:54
Closing this since work-around solution working for now, and plans are in hand to better support restart after upgrade and systemd.

**Closed by dmurphy18** 2016-06-21 14:54 UTC
Labels: Platform, TEAM Platform
