### ISSUE TITLE
[BUG] Windows minion installer creates a folder blocking logging

### ISSUE THREAD

**Issue by bjoernf73** [saltstack/salt#61273] opened 2021-11-20 08:24 UTC
**Description**
The Windows minion installer creates the FOLDER: 
 - C:\ProgramData\Salt Project\Salt\var\log\salt\minion

However, when you enable minion logging, by default, the salt-minion service tries to log to a FILE:
 - C:\ProgramData\Salt Project\Salt\var\log\salt\minion

Since there is already a FOLDER occupying that FILE path, logging fails. Removing the leaf folder, the salt-minion is now able to create the log file automatically, and logging works.  

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (vSphere)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Fresh install of Windows minion creates the folder `C:\ProgramData\Salt Project\Salt\var\log\salt\minion`

**Expected behavior**
Install of Windows minion should only create the folder `C:\ProgramData\Salt Project\Salt\var\log\salt`

**Versions Report**
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: 3.1.18
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2022Server
        system: Windows
       version: 2022Server 10.0.20348 SP0 Multiprocessor Free

**Comment by OrangeDog** [comment] 2021-11-22 13:09
Duplicate of #61113?

**Comment by haodeon** [comment] 2021-11-23 06:22
Yes it is a duplicate of #61113 and I have an open PR #61144 which will fix it.

It's been approved but unsure what needs to happen for the PR to be merged. I admit there is a chicken egg problem with the test I have included. The test is failing because the test runners are using an older build and not a fresh build of the installer with my fix included.

**Closed** 2021-11-23 09:46 UTC
Labels: Bug, Duplicate
