### ISSUE TITLE
[BUG] 3002 salt-master memory leak 

### ISSUE THREAD

**Issue by ymasson** [saltstack/salt#58793] opened 2020-10-23 08:52 UTC
**Description**
Since 3002 upgrade, is there a memory leak. With 3001.1 version, the memory consumption was around 1.9Gb.

<img src="https://i.ibb.co/NTzP9x6/salt-master-memory.png" alt="salt-master-memory" border="0">

```
kernel: [43336.658962] Out of memory: Kill process 2091 (salt-master) score 267 or sacrifice child
```

**Setup**
Just start the salt-master and wait.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3002
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: devuan 3 beowulf
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-12-amd64
         system: Linux
        version: Devuan GNU/Linux 3 beowulf
```

</details>

Thanks

**Comment by whytewolf** [comment] 2020-10-23 14:23
this looks like a duplicate of https://github.com/saltstack/salt/issues/58785

**Comment by s0undt3ch** [comment] 2020-10-24 09:54
Closing as duplicate of https://github.com/saltstack/salt/issues/58785

**Closed by s0undt3ch** 2020-10-24 09:54 UTC
Labels: Bug, needs-triage
