### ISSUE TITLE
salt-cloud vmware issue

### ISSUE THREAD

**Issue by ilikeitsalty** [saltstack/salt#42216] opened 2017-07-07 20:42 UTC
### Description of Issue/Question

Hi everyone. I just updated my salt master/minion/cloud baselines and my salt-cloud server is not working anymore. This is the error I get now.
```

[root@saltmaster]# salt-cloud
Traceback (most recent call last):
  File "/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 439, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 46, in run
    self.parse_args()
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 3021, in parse_args
    from salt.cloud import libcloudfuncs
  File "/usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py", line 28, in <module>
    int(part) for part in libcloud.__version__.replace('-', '.').split('.')[:3]
ValueError: invalid literal for int() with base 10: '0rc2'

```

my environment:

```
[root@saltmaster]# salt --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core


```
```
[root@saltmaster]# rpm -qa | grep salt
salt-master-2016.11.6-1.el7.noarch
salt-repo-latest-2.el7.noarch
salt-2016.11.6-1.el7.noarch
salt-minion-2016.11.6-1.el7.noarch
salt-cloud-2016.11.6-1.el7.noarch
```
I'm kinda dead in the water right now. This was working fine before the updates.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment] 2017-07-07 20:54
This is a duplicate of https://github.com/saltstack/salt/issues/42115

https://github.com/saltstack/salt/pull/42163

and will be available in 2016.11.7.

**Closed by gtmanfred** 2017-07-07 20:54 UTC

**Comment by ilikeitsalty** [comment] 2017-07-07 21:13
@gtmanfred oh, ok - good to know. When is 2016.11.7 going to be released? thanks for the quick response.

**Comment by gtmanfred** [comment] 2017-07-07 21:18
I believe it is expected in september

**Comment by ilikeitsalty** [comment] 2017-07-07 21:34
@gtmanfred oh, thats a bit longer than we can wait. On the other ticket you referenced someone said the way to get around this is to downgrade libcloud. Do you know to what version?

**Comment by gtmanfred** [comment] 2017-07-07 21:40
We require at least version 0.2.1.

So any version after that.
