### ISSUE TITLE
salt-cloud has no reactor events anymore ???

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#36674] opened 2016-09-29 13:43 UTC
I have last months switched from default ```startup_states: highstate``` run to the much better salt-minion (re-)start independed version with reactor events and I find it very convenient this way.

... till latest update :( ...
```
root@salt-euc1-01:~# lsb_release -d
Description:    Debian GNU/Linux 8.6 (jessie)
root@salt-euc1-01:~# salt-cloud --version
salt-cloud 2016.3.3 (Boron)
root@salt-euc1-01:~# salt-minion --version
salt-minion 2016.3.3 (Boron)
root@salt-euc1-01:~# salt-master --version
salt-master 2016.3.3 (Boron)
```

The instance wasn't highstated and a check with:
```
root@salt-euc1-01:~# salt-run state.event pretty=True
```

shows the problem: There are no **salt/cloud/*** events thrown anymore ???
```
root@salt-euc1-01:~# grep ^salt salt-reactor-pretty-print.txt | grep -v /ret/
salt/auth       {
salt/minion/yz-euc1-07/start    {
salt/run/20160929131231218504/new       {
salt/run/20160929131231218504/ret       {
salt/run/20160929131231447638/new       {
salt/run/20160929131231447638/ret       {
salt/job/20160929131231601964/new       {
salt/auth       {
salt/minion/yz-euc1-07/start    {
salt/run/20160929131252969886/new       {
salt/run/20160929131252969886/ret       {
salt/run/20160929131254125822/new       {
salt/run/20160929131254125822/ret       {
salt/job/20160929131258189531/new       {
```
but they are still documented:
https://docs.saltstack.com/en/latest/topics/cloud/reactor.html#available-events

EDIT: to be sure to have all: I speak here about setup new instances with ec2 driver

**Comment by Ch3LL** [comment] 2016-09-29 20:24
@Reiner030 this is a duplicate of https://github.com/saltstack/salt/issues/36055 which has been fixed in https://github.com/saltstack/salt/pull/35855 and will be included in the 2016.3.4 release in october. Closing due to duplciate.

**Closed by Ch3LL** 2016-09-29 20:24 UTC
