### ISSUE TITLE
integration.cloud.clouds.test_vmware.VMWareTest.test_snapshot

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52825] opened 2019-05-02 22:22 UTC
2019.2.1 failed [salt-centos-7-py2-cloud](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-cloud/11/testReport/junit/integration.cloud.clouds.test_vmware/VMWareTest/test_snapshot), [salt-centos-7-py3-cloud](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py3-cloud/9/testReport/junit/integration.cloud.clouds.test_vmware/VMWareTest/test_snapshot)
---

'CLOUD-TEST-J400G3:' not found in []

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_vmware.py", line 122, in test_snapshot
    self.assertIn(ret_str, instance)
AssertionError: 'CLOUD-TEST-J400G3:' not found in []
		
```

**Comment by Ch3LL** [comment] 2019-05-03 13:51
duplicate of https://github.com/saltstack/salt/issues/52511

**Closed by Ch3LL** 2019-05-03 13:51 UTC
Labels: 2019.2.1, Test Failure
