### ISSUE TITLE
__virtual__ function raising multiple exceptions

### ISSUE THREAD

**Issue by aabognah** [saltstack/salt#40017] opened 2017-03-14 16:43 UTC
### Description of Issue/Question

I started seeing lots of these messages on the master after updating to 2016.11.3. This master is RHEL6. I have another Salt master running 2016.11.3 on RHEL7 that does not have this issue!

```
2017-03-14 12:03:11,959 [salt.loader                                          ][ERROR   ][15201] Exception raised when processing __virtual__ function for xapi. Module will not be loaded 'os'
2017-03-14 12:03:12,597 [salt.loader                                          ][ERROR   ][15201] Exception raised when processing __virtual__ function for grub_legacy. Module will not be loaded 'os_family'
2017-03-14 12:03:12,599 [salt.loader                                          ][ERROR   ][15201] Exception raised when processing __virtual__ function for deb_apache. Module will not be loaded 'os_family'
2017-03-14 12:03:12,608 [salt.loader                                          ][ERROR   ][15201] Exception raised when processing __virtual__ function for pw_user. Module will not be loaded 'kernel'
2017-03-14 12:03:12,708 [salt.loader                                          ][ERROR   ][15201] Exception raised when processing __virtual__ function for debconfmod. Module will not be loaded 'os_family'
2017-03-14 12:03:12,726 [salt.loader                                          ][ERROR   ][15201] Exception raised when processing __virtual__ function for kmod. Module will not be loaded 'kernel'
2017-03-14 12:03:12,745 [salt.loader                                          ][ERROR   ][15201] Exception raised when processing __virtual__ function for eix. Module will not be loaded 'os'
2017-03-14 12:03:12,753 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for debian_service. Module will not be loaded 'os'
2017-03-14 12:03:12,754 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for smf. Module will not be loaded 'os_family'
2017-03-14 12:03:12,979 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for pkgin. Module will not be loaded 'os'
2017-03-14 12:03:12,992 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for bridge. Module will not be loaded 'kernel'
2017-03-14 12:03:12,994 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for win_powercfg. Module will not be loaded 'os'
2017-03-14 12:03:13,061 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for debian_ip. Module will not be loaded 'os_family'
2017-03-14 12:03:13,065 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for dpkg. Module will not be loaded 'os_family'
2017-03-14 12:03:13,165 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for pw_group. Module will not be loaded 'kernel'
2017-03-14 12:03:13,173 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for pacman. Module will not be loaded 'os_family'
2017-03-14 12:03:13,177 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for netbsdservice. Module will not be loaded 'os'
2017-03-14 12:03:13,184 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for freebsdkmod. Module will not be loaded 'kernel'
2017-03-14 12:03:13,196 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for gentoo_service. Module will not be loaded 'os'
2017-03-14 12:03:13,220 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for solarispkg. Module will not be loaded 'os'
2017-03-14 12:03:13,248 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for apache. Module will not be loaded 'os_family'
2017-03-14 12:03:13,256 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for solaris_group. Module will not be loaded 'kernel'
2017-03-14 12:03:13,264 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for keyboard. Module will not be loaded 'os_family'
2017-03-14 12:03:13,276 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for openbsdservice. Module will not be loaded 'os'
2017-03-14 12:03:13,284 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for freebsdservice. Module will not be loaded 'os'
2017-03-14 12:03:13,287 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for gentoolkitmod. Module will not be loaded 'os'
2017-03-14 12:03:13,365 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for freebsdports. Module will not be loaded 'os'
2017-03-14 12:03:13,391 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for poudriere. Module will not be loaded 'os'
2017-03-14 12:03:13,422 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for upstart. Module will not be loaded 'os'
2017-03-14 12:03:13,441 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for pkgng. Module will not be loaded 'kernel'
2017-03-14 12:03:13,622 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for mdadm. Module will not be loaded 'kernel'
2017-03-14 12:03:13,624 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for rh_ip. Module will not be loaded 'os_family'
2017-03-14 12:03:13,631 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for service. Module will not be loaded 'kernel'
2017-03-14 12:03:13,688 [salt.loader                                                   ][ERROR   ][15201] Exception raised when processing __virtual__ function for layman. Module will not be loaded 'os'
2017-03-14 12:03:13,866 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for solaris_user. Module will not be loaded 'kernel'
2017-03-14 12:03:13,986 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for nspawn. Module will not be loaded 'kernel'
2017-03-14 12:03:14,008 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for linux_sysctl. Module will not be loaded 'kernel'
2017-03-14 12:03:14,009 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for freebsdjail. Module will not be loaded 'os'
2017-03-14 12:03:14,029 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for logadm. Module will not be loaded 'os_family'
2017-03-14 12:03:14,033 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for eselect. Module will not be loaded 'os'
2017-03-14 12:03:14,060 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for mac_sysctl. Module will not be loaded 'os'
2017-03-14 12:03:14,065 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for freebsd_sysctl. Module will not be loaded 'os'
2017-03-14 12:03:14,074 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for makeconf. Module will not be loaded 'os'
2017-03-14 12:03:14,102 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for rh_service. Module will not be loaded 'os'
2017-03-14 12:03:14,157 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for useradd. Module will not be loaded 'kernel'
2017-03-14 12:03:14,172 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for openbsdpkg. Module will not be loaded 'os'
2017-03-14 12:03:14,181 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for xbpspkg. Module will not be loaded 'os'
2017-03-14 12:03:14,272 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for systemd. Module will not be loaded 'kernel'
2017-03-14 12:03:14,294 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for openbsdrcctl. Module will not be loaded 'os'
2017-03-14 12:03:14,321 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for mac_xattr. Module will not be loaded 'os'
2017-03-14 12:03:14,353 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for zfs. Module will not be loaded 'kernel'
2017-03-14 12:03:14,378 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for linux_ip. Module will not be loaded 'os_family'
2017-03-14 12:03:14,390 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for pkgutil. Module will not be loaded 'os'
2017-03-14 12:03:14,419 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for freebsdpkg. Module will not be loaded 'os'
2017-03-14 12:03:14,457 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for solarisips. Module will not be loaded 'os'
2017-03-14 12:03:14,467 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for groupadd. Module will not be loaded 'kernel'
2017-03-14 12:03:14,468 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for openbsd_sysctl. Module will not be loaded 'os'
2017-03-14 12:03:14,479 [salt.loader                                                    ][ERROR   ][15201] Exception raised when processing __virtual__ function for netbsd_sysctl. Module will not be loaded 'os'

```
The above is a grep a not a full log.

### Setup
standard master/minions setup with gitfs and git pillars. 
### Versions Report
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.6.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago
```

**Comment by aabognah** [comment] 2017-03-14 16:46
here is a longer version of the log:

```
2017-03-14 12:44:53,643 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.freebsdjail.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsdjail', please fix this.
2017-03-14 12:44:53,647 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for logadm. Module will not be loaded 'os_family'
2017-03-14 12:44:53,647 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.logadm.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'logadm', please fix this.
2017-03-14 12:44:53,649 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for eselect. Module will not be loaded 'os'
2017-03-14 12:44:53,649 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.eselect.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'eselect', please fix this.
2017-03-14 12:44:53,658 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for mac_sysctl. Module will not be loaded 'os'
2017-03-14 12:44:53,658 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.mac_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'mac_sysctl', please fix this.
2017-03-14 12:44:53,658 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for freebsd_sysctl. Module will not be loaded 'os'
2017-03-14 12:44:53,658 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.freebsd_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsd_sysctl', please fix this.
2017-03-14 12:44:53,662 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for makeconf. Module will not be loaded 'os'
2017-03-14 12:44:53,662 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.makeconf.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'makeconf', please fix this.
2017-03-14 12:44:53,671 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for rh_service. Module will not be loaded 'os'
2017-03-14 12:44:53,671 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.rh_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_service', please fix this.
2017-03-14 12:44:53,688 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for useradd. Module will not be loaded 'kernel'
2017-03-14 12:44:53,688 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.useradd.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'useradd', please fix this.
2017-03-14 12:44:53,691 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for openbsdpkg. Module will not be loaded 'os'
2017-03-14 12:44:53,691 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.openbsdpkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openbsdpkg', please fix this.
2017-03-14 12:44:53,694 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for xbpspkg. Module will not be loaded 'os'
2017-03-14 12:44:53,694 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.xbpspkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'xbpspkg', please fix this.
2017-03-14 12:44:53,718 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for systemd. Module will not be loaded 'kernel'
2017-03-14 12:44:53,719 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.systemd.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'systemd', please fix this.
2017-03-14 12:44:53,726 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for openbsdrcctl. Module will not be loaded 'os'
2017-03-14 12:44:53,726 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.openbsdrcctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openbsdrcctl', please fix this.
2017-03-14 12:44:53,733 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for mac_xattr. Module will not be loaded 'os'
2017-03-14 12:44:53,733 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.mac_xattr.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'mac_xattr', please fix this.
2017-03-14 12:44:53,743 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for zfs. Module will not be loaded 'kernel'
2017-03-14 12:44:53,743 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.zfs.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'zfs', please fix this.
2017-03-14 12:44:53,750 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for linux_ip. Module will not be loaded 'os_family'
2017-03-14 12:44:53,750 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.linux_ip.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'linux_ip', please fix this.
2017-03-14 12:44:53,752 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for pkgutil. Module will not be loaded 'os'
2017-03-14 12:44:53,752 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.pkgutil.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pkgutil', please fix this.
2017-03-14 12:44:53,758 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for freebsdpkg. Module will not be loaded 'os'
2017-03-14 12:44:53,758 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.freebsdpkg.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'freebsdpkg', please fix this.
2017-03-14 12:44:53,766 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for solarisips. Module will not be loaded 'os'
2017-03-14 12:44:53,766 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.solarisips.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'solarisips', please fix this.
2017-03-14 12:44:53,766 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for groupadd. Module will not be loaded 'kernel'
2017-03-14 12:44:53,767 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.groupadd.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'groupadd', please fix this.
2017-03-14 12:44:53,768 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for openbsd_sysctl. Module will not be loaded 'os'
2017-03-14 12:44:53,768 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.openbsd_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openbsd_sysctl', please fix this.
2017-03-14 12:44:53,770 [salt.loader                                                    ][ERROR   ][20955] Exception raised when processing __virtual__ function for netbsd_sysctl. Module will not be loaded 'os'
2017-03-14 12:44:53,770 [salt.loader                                                    ][WARNING ][20955] salt.loaded.int.module.netbsd_sysctl.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'netbsd_sysctl', please fix this.
```

**Comment by ninja-** [comment] 2017-03-14 16:47
This is actually expected behaviour(for now) due to some hard-to-refactor loader limitations...Whether or not you get these messages depends on randomness of module loading order.

**Comment by gtmanfred** [comment] 2017-03-15 14:55
Thanks for reporting this,

We will get it fixed.
Daniel

**Comment by thatch45** [comment] 2017-03-15 15:18
Can you give us your master configs (all the the files under master.d too)?

**Comment by aabognah** [comment] 2017-03-17 15:28
below are all the salt master configs

I think the one thats causing the problem is the orchestrate configuration. when I remove that I don't see the error messages any more.


```
# Add any additional locations to look for master runners:
runner_dirs: ['/srv/salt/_runners',]
gitfs_provider: gitpython

fileserver_backend:
  - git

gitfs_remotes:
  - [git repository url]:
    - root: base
    - base: master

top_file_merging_strategy: same

schedule:
  orchestrate_highstate:
    function: state.orchestrate
    minutes: 10
    args:
      - orc.ordered_highstate.sls
state_verbose: False
#git_pillar_provider: gitpython

ext_pillar:
  - git:
    - master [git repository url]:
      - root: pillar/base
      - env: base
      - privkey: /root/.ssh/id_rsa
      - pubkey: /root/.ssh/id_rsa.pub

pillar_top_file_merging_strategy: same

#ext_pillar_first: True
reactor:
  - 'salt/netapi/hook/fileserver/gitfs/update':
    - /srv/salt/reactor/update_fileserver.sls
    - /srv/salt/reactor/build_iptables.sls

  - 'salt/job/*/ret/*':
    - /srv/salt/reactor/email-on-fail.sls
rest_cherrypy:
  port: 8080
  host: [salt master name]
  ssl_crt: /etc/ssl/private/cert.pem
  ssl_key: /etc/ssl/private/key.pem
  webhook_disable_auth: True
  webhook_url: /hook
schedule:
  update_environments:
    function: update_environments.update_env
    minutes: 30
    splay: 100

# debuggin slow respones from some minison
state_events: False

gathar_job_timeout: 200
```

**Comment by thatch45** [comment] 2017-03-17 16:41
Hmm, we have seen this happen when there are some bad configs....

**Comment by aabognah** [comment] 2017-04-03 13:43
I just want to report that I am still seeing these messages after removing the orchestrate configuration.

**Comment by terminalmage** [comment] 2017-04-06 01:24
These errors are happening because the ``__grains__`` dictionary is missing important items like ``os``, and ``kernel`` that are part of the core grains and expected to be there.

**Comment by terminalmage** [comment] 2017-04-06 01:56
I cannot reproduce this:

```
[root@c1c0f8fd8bc0 /]# cat /etc/redhat-release
CentOS release 6.8 (Final)
[root@c1c0f8fd8bc0 /]# salt test grains.item os
test:
    ----------
    os:
        CentOS
[root@c1c0f8fd8bc0 /]# fgrep __virtual__ /var/log/salt/*
```

You said this was happening on a master, but didn't say if those log messages were in the master log, or if you're running a minion on the master and these log messages are in the minion log.

Can you please provide your full configuration, as requested a few weeks ago?

**Comment by terminalmage** [comment] 2017-04-10 18:23
@aabognah Can you follow up on my questions from last week, please?

**Comment by aabognah** [comment] 2017-04-11 18:59
Hi,

sorry for the late response.

I am seeing those messages in /var/log/salt/master on the master.

Here is all configs under /etc/salt/master.d/ (nothing in the /etc/salt/master):

```
runner_dirs:
  - /srv/salt/_runners
gitfs_provider: gitpython

fileserver_backend:
  - git

gitfs_remotes:
  - [our git server]/salt-root.git:
    - root: base
    - base: master
  - [our git server]/salt-iptables.git:
    - base: master

top_file_merging_strategy: same

state_verbose: False

ext_pillar:
  - git:
    - master [git server]/salt-root.git:
      - root: pillar/base
      - env: base
      - privkey: /root/.ssh/id_rsa
      - pubkey: /root/.ssh/id_rsa.pub

pillar_top_file_merging_strategy: same

#ext_pillar_first: True
reactor:
  - 'salt/netapi/hook/fileserver/gitfs/update':
    - /srv/salt/reactor/update_fileserver.sls
    - /srv/salt/reactor/build_iptables.sls

  - 'salt/job/*/ret/*':
    - /srv/salt/reactor/email-on-fail.sls

rest_cherrypy:
  port: 8080
  host: localhost
  ssl_crt: /etc/ssl/private/cert.pem
  ssl_key: /etc/ssl/private/key.pem
  webhook_disable_auth: True
  webhook_url: /hook

schedule:
  update_environments:
    function: update_environments.update_env
    minutes: 30
    splay: 100

# debuggin slow respones from some minison
state_events: False

gathar_job_timeout: 200
```

**Comment by terminalmage** [comment] 2017-04-11 20:21
1. Do these messages still show up in your master log?
2. Do any of your git_pillar SLS files call functions using jinja? (e.g. ``{{ salt['module.function']('argument') }}``)
3. If so, do the log messages go away if you comment out your ext_pillar configuration?

**Comment by aabognah** [comment] 2017-04-12 16:24
Hi,

1- yes I am still seeing these messages every time the master is restarted.

2- I am not using any functions in jinja templates. however I have the following schedule pillar:

```
schedule:

  # update roles grain from the roles_file.
  update_roles_grain:
    function: saltutil.sync_grains
    seconds: 900
    splay:
      start: 60
      end: 90


  # get the latest pillars from the maser every 10 minutes, but wait 60-80 seconds for fileserver to update
  refresh_pillars:
    function: saltutil.refresh_pillar
    seconds: 1800
    splay:
      start: 90
      end: 120

  # Execute highstate every 10 minutes but wait 90-120 seconds so the above two steps get a chance to complete
  highstate:
    function: state.apply
    seconds: 3600
    return_job: True
    splay:
      start: 120
      end: 180

  # restart ntpd every two weeks to offset clock drifts
  restart_ntpd:
    function: cmd.run
    days: 15
    when: 'Saturday 3:00am'
    args:
      - 'service ntpd restart'
    kwargs:
      stateful: False
      shell: /bin/bash
```

3- If I disable the ext_pillar and restart the master I still see the same messages

**Comment by terminalmage** [comment] 2017-04-13 01:46
OK. Can you comment out sections of your master config, then uncomment them one at a time and restart the ``salt-master`` service, so we can tell what triggers this?

**Comment by cachedout** [comment] 2017-04-20 17:46
@aabognah Did you see the above request for more info? If we don't hear back, we'll need to close this issue until we do get a response. Thanks!

**Comment by cachedout** [comment] 2017-04-27 10:51
Closed for lack of response.

**Closed by cachedout** 2017-04-27 10:51 UTC
Labels: Bug, Cannot Reproduce, Core, Critical, P1, TEAM Core
