### ISSUE TITLE
JSON array structure incorrectly rendered

### ISSUE THREAD

**Issue by sdodsley** [saltstack/salt#39986] opened 2017-03-13 15:24 UTC
### Description of Issue/Question
The JSON standard for an array is that it starts with a [ (left bracket) and ends with a ] (right bracket), with values between these being separated by a comma (http://www.json.org/index.html).

When using the salt runner module the array structure is being incorrectly formatted with whole array being wrapped in quotation marks("), including the left and right brackets, which makes the JSON structure incorrect.

### Steps to Reproduce Issue
I am running the following salt-run command against a Pure Storage FlashArray's RestAPI service:
```
# salt-run http.query https://10.234.112.107/api/1.8/host/salt-host method=POST data='{"wwnlist": ["0011223344556677","1122334455667788"]}' persist_session=True verify_ssl=false
error:
    HTTP 400: BAD REQUEST
status:
    400
```

Log file from storage array receiving incorrectly formed JSON structure:

```
2017-03-13 11:19:26.095 [INFO] 10.234.112.46 >> POST http://10.234.112.107/api/1.8/host/salt-host
{
  "wwnlist":"['0011223344556677', '1122334455667788']"
}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pure/rest/controller/util.py", line 97, in execute
    (command, args) = get_args(command_list, version, params)
  File "/usr/lib/python2.7/dist-packages/pure/rest/controller/util.py", line 392, in get_args
    raise RestException("Value of argument {} needs to be one of {}.".format(key, arg.arg_type), Code.BAD_REQUEST)
RestException: Value of argument wwnlist needs to be one of ['list'].
2017-03-13 11:19:26.101 [WARNING] << 400 BAD REQUEST
{
  "msg":"Value of argument wwnlist needs to be one of ['list']."
}
```
The Pure Storage RestAPI works with Ansible URI module calls as well as Puppet and Python calls. Only Salt causes this error.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment] 2017-03-13 16:28
Can you please provide the debug log of the command so that hopefully we can see where this errored at?

Thanks,
Daniel

**Comment by sdodsley** [comment] 2017-03-13 23:45
Here's the debug output you requested...
```
# salt-run -l debug http.query https://10.234.112.107/api/1.8/host/salt-host method=POST data='{"wwnlist": ["0011223344556677","1122334455667788"]}' persist_session=True verify_ssl=false
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded http.query
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20170313194317225101/new; data = {'fun': 'runner.http.query', 'fun_args': ['https://10.234.112.107/api/1.8/host/salt-host', {'__pub_master_job_cache': 'local_cache', '__pub_ipc_mode': 'ipc', '__pub_gitfs_privkey': '', '__pub_gather_job_timeout': 10, '__pub_ssh_list_nodegroups': {}, '__pub_file_roots': {'base': ['/salt/states']}, '__pub_minionfs_mountpoint': '', '__pub_raet_port': 4506, '__pub_gitfs_global_lock': True, '__pub_log_granular_levels': {}, '__pub_ssh_timeout': 60, '__pub_cli_summary': False, 'verify_ssl': False, '__pub_state_verbose': True, '__pub_gitfs_saltenv': [], '__pub_gitfs_user': '', '__pub_git_pillar_branch': 'master', '__pub_hgfs_branch_method': 'branches', '__pub_reactor_refresh_interval': 60, '__pub_git_pillar_passphrase': '', '__pub_mktoken': False, '__pub_queue_dirs': [], '__pub_nodegroups': {}, '__pub_ssh_port': '22', '__pub_regen_thin': False, '__pub_engines': [], '__pub_gitfs_base': 'master', '__pub_minionfs_env': 'base', '__pub_syndic_log_file': '/var/log/salt/syndic', '__pub_tcp_master_pull_port': 4513, '__pub_fileserver_backend': ['roots'], '__pub_event_return': '', '__pub_cache': 'localfs', '__pub_winrepo_dir_ng': '/srv/salt/win/repo-ng', '__pub_winrepo_pubkey': '', '__pub_eauth': '', '__pub_ssh_scan_ports': '22', '__pub_show_timeout': True, '__pub_pub_hwm': 1000, '__pub_interface': '127.0.0.1', '__pub_master_use_pubkey_signature': False, '__pub_django_auth_path': '', '__pub_git_pillar_global_lock': True, '__pub_preserve_minion_cache': False, '__pub_publisher_acl': {}, '__pub_jinja_trim_blocks': False, '__pub_auth_mode': 1, '__pub_range_server': 'range:80', '__pub_gitfs_remotes': [], '__pub_doc': False, '__pub_winrepo_remotes_ng': ['https://github.com/saltstack/salt-winrepo-ng.git'], '__pub_pillar_version': 2, '__pub_ping_on_rotate': False, '__pub_on_demand_ext_pillar': ['libvirt', 'virtkey'], '__pub_hard_crash': False, '__pub_winrepo_password': '', '__pub_ssh_sudo_user': '', '__pub_ssl': None, '__pub_zmq_filtering': False, '__pub_ioflo_verbose': 0, '__pub_ssh_sudo': False, '__pub_transport': 'zeromq', '__pub_state_top_saltenv': None, '__pub_show_jid': False, '__pub_con_cache': False, '__pub_args_stdin': False, '__pub_loop_interval': 60, '__pub_id': 'salt-master_master', '__pub_hgfs_remotes': [], '__pub_fileserver_ignoresymlinks': False, '__pub_winrepo_dir': '/srv/salt/win/repo', '__pub_ssh_scan_timeout': 0.01, '__pub_ioflo_period': 0.01, '__pub_syndic_jid_forward_cache_hwm': 100, '__pub_minion_data_cache': True, '__pub_log_datefmt_logfile': '%Y-%m-%d %H:%M:%S', '__pub_gitfs_mountpoint': '', '__pub_event_return_queue': 0, '__pub_django_auth_settings': '', '__pub_extension_modules': '/var/cache/salt/master/extmods', '__pub_master_pubkey_signature': 'master_pubkey_signature', '__pub_syndic_wait': 5, '__pub_max_minions': 0, '__pub_publish_session': 86400, '__pub_default_top': 'base', '__pub_state_events': False, '__pub_http_request_timeout': 3600.0, '__pub_master_floscript': '/usr/lib/python2.7/dist-packages/salt/daemons/flo/master.flo', '__pub_verify_env': True, '__pub_syndic_pidfile': '/var/run/salt-syndic.pid', '__pub_rotate_aes_key': True, '__pub_token_expire': 43200, '__pub_selected_output_option': 'output_indent', '__pub_ssh_identities_only': False, '__pub_thin_extra_mods': '', '__pub_cluster_masters': [], '__pub_top_file_merging_strategy': 'merge', '__pub_svnfs_tags': 'tags', '__pub_event_match_type': 'startswith', '__pub_keep_jobs': 24, '__pub_file_recv_max_size': 100, 'method': 'POST', '__pub_fileserver_limit_traversal': False, '__pub_ssh_use_home_key': False, '__pub_state_top': 'top.sls', '__pub_master_uri': 'tcp://127.0.0.1:4506', '__pub_master_sign_key_name': 'master_sign', '__pub_event_return_whitelist': [], '__pub_ipv6': False, '__pub_order_masters': False, '__pub_tcp_keepalive_cnt': -1, '__pub_log_level': 'debug', '__pub_log_level_logfile': 'warning', '__pub_gitfs_env_blacklist': [], '__pub_state_aggregate': False, '__pub_enforce_mine_cache': False, '__pub_gitfs_root': '', '__pub_http_max_body': 107374182400, '__pub_ioflo_realtime': True, '__pub_env_order': [], '__pub_profiling_enabled': False, '__pub_config_dir': '/etc/salt', '__pub_outputter_dirs': [], '__pub_tcp_keepalive_idle': 300, '__pub_client_acl_verify': True, '__pub_cython_enable': False, '__pub_runner_dirs': [], '__pub_gitfs_env_whitelist': [], '__pub_conf_file': '/etc/salt/master', '__pub_cachedir': '/var/cache/salt/master', '__pub_archive_jobs': False, '__pub_ssh_passwd': '', '__pub_tcp_master_publish_pull': 4514, '__pub_git_pillar_env': '', '__pub_raet_alt_port': 4511, '__pub_runner_returns': True, 'persist_session': True, '__pub_fileserver_followsymlinks': True, '__pub_tcp_keepalive': True, '__pub_file_recv': False, '__pub_file_buffer_size': 1048576, '__pub_state_auto_order': True, '__pub_renderer': 'yaml_jinja', '__pub_pillar_cache': False, '__pub_raet_clear_remotes': False, '__pub_log_fmt_console': '[%(levelname)-8s] %(message)s', '__pub_hgfs_base': 'default', '__pub_pillar_cache_backend': 'disk', '__pub_timeout': 5, '__pub_quiet': False, '__pub_tcp_master_pub_port': 4512, '__pub_maintenance_floscript': '/usr/lib/python2.7/dist-packages/salt/daemons/flo/maint.flo', '__pub_keysize': 2048, '__pub_gitfs_pubkey': '', '__pub_key_cache': '', '__pub_python2_bin': 'python2', '__pub_root_dir': '/', '__pub_raet_mutable': False, '__pub_reactor_worker_hwm': 10000, '__pub_thorium_roots': {'base': ['/srv/thorium']}, '__pub_file_ignore_regex': [], '__pub_git_pillar_pubkey': '', '__pub_sign_pub_messages': False, '__pub_job_cache': True, '__pub_sqlite_queue_dir': '/var/cache/salt/master/queues', '__pub_python3_bin': 'python3', '__pub_worker_threads': 5, '__pub_ipc_write_buffer': 0, '__pub_tcp_master_workers': 4515, '__pub_ext_pillar': [], '__pub_log_file': '/var/log/salt/master', '__pub_cache_sreqs': True, '__pub_svnfs_trunk': 'trunk', '__pub___role': 'master', '__pub_tcp_keepalive_intvl': -1, '__pub_no_color': False, '__pub_sudo_acl': False, '__pub_auto_accept': False, '__pub_log_datefmt': '%H:%M:%S', '__pub_syndic_dir': '/var/cache/salt/master/syndics', '__pub_client_acl': {}, '__pub_winrepo_branch': 'master', '__pub_client_acl_blacklist': {}, '__pub_log_datefmt_console': '%H:%M:%S', '__pub_hgfs_env_blacklist': [], '__pub_dummy_pub': False, '__pub_publish_port': 4505, '__pub_serial': 'msgpack', '__pub_gitfs_passphrase': '', '__pub_svnfs_root': '', '__pub_master_tops': {}, '__pub_arg': ['https://10.234.112.107/api/1.8/host/salt-host', 'method=POST', 'data={"wwnlist": ["0011223344556677","1122334455667788"]}', 'persist_session=True', 'verify_ssl=false'], '__pub_reactor': [], '__pub_winrepo_insecure_auth': False, '__pub_git_pillar_root': '', '__pub_force_color': False, '__pub_open_mode': False, '__pub_raet_lane_bufcnt': 100, '__pub_git_pillar_password': '', '__pub_ret_port': 4506, '__pub_syndic_master': 'masterofmasters', '__pub_master_sign_pubkey': False, '__pub_pillar_safe_render_error': True, '__pub_renderer_blacklist': [], '__pub_max_event_size': 1048576, '__pub_hgfs_root': '', '__pub_svnfs_remotes': [], '__pub_profiling_path': '/tmp/stats', '__pub_git_pillar_base': 'master', '__pub_worker_floscript': '/usr/lib/python2.7/dist-packages/salt/daemons/flo/worker.flo', '__pub_token_expire_user_override': False, '__pub_key_logfile': '/var/log/salt/key', '__pub_environment': None, '__pub_pillar_cache_ttl': 3600, '__pub_failhard': False, '__pub_log_fmt_logfile': '%(asctime)s,%(msecs)03d [%(name)-17s][%(levelname)-8s][%(process)d] %(message)s', '__pub_async': False, '__pub_pillar_roots': {'base': ['/srv/pillar', '/srv/spm/pillar']}, '__pub_fun': 'http.query', '__pub_winrepo_user': '', '__pub_pillar_source_merging_strategy': 'smart', '__pub_zmq_monitor': False, '__pub_git_pillar_privkey': '', '__pub_hash_type': 'sha256', '__pub_minionfs_whitelist': [], '__pub_jinja_lstrip_blocks': False, '__pub_permissive_pki_access': False, '__pub_peer': {}, '__pub_state_output': 'full', '__pub_winrepo_passphrase': '', '__pub_state_output_diff': False, '__pub_git_pillar_user': '', '__pub_raet_clear_remote_masters': True, '__pub_gitfs_insecure_auth': False, '__pub_git_pillar_ssl_verify': True, '__pub_gitfs_ssl_verify': True, '__pub_svnfs_branches': 'branches', '__pub_master_roots': {'base': ['/srv/salt-master']}, '__pub_file_ignore_glob': [], '__pub_thorium_interval': 0.5, '__pub_reactor_worker_threads': 10, '__pub_test': False, '__pub_winrepo_privkey': '', '__pub_pidfile': '/var/run/salt-master.pid', '__pub_user': 'root', '__pub_pki_dir': '/etc/salt/pki/master', '__pub_search': '', '__pub_winrepo_ssl_verify': True, '__pub_ssh_user': 'root', '__pub_winrepo_cachefile': 'winrepo.p', '__pub_max_open_files': 100000, '__pub_ioflo_console_logdir': '', '__pub_token_file': '/root/salt_token', '__pub_publisher_acl_blacklist': {}, '__pub_renderer_whitelist': [], '__pub_ext_job_cache': '', '__pub_enable_gpu_grains': False, '__pub_token_dir': '/var/cache/salt/master/tokens', '__pub_search_index_interval': 3600, '__pub_raet_main': True, '__pub_pillar_opts': False, '__pub_file_client': 'local', 'data': {'wwnlist': ['0011223344556677', '1122334455667788']}, '__pub_svnfs_mountpoint': '', '__pub_syndic_failover': 'random', '__pub_winrepo_remotes': ['https://github.com/saltstack/salt-winrepo.git'], '__pub_hgfs_env_whitelist': [], '__pub_event_return_blacklist': [], '__pub_cluster_mode': False, '__pub_minionfs_blacklist': [], '__pub_external_auth': {}, '__pub_raet_road_bufcnt': 2, '__pub_svnfs_env_blacklist': [], '__pub_gitfs_password': '', '__pub_svnfs_env_whitelist': [], '__pub_exit_on_config_errors': False, '__pub_pillar_merge_lists': False, '__pub_git_pillar_insecure_auth': False, '__pub_syndic_event_forward_timeout': 0.5, '__pub_zmq_backlog': 1000, '__pub_hgfs_mountpoint': '', '__pub_sock_dir': '/var/run/salt/master', '__pub_output_file_append': False, '__pub_ssh_log_file': '/var/log/salt/ssh', '__pub_default_include': 'master.d/*.conf', '__pub_job_cache_store_endtime': False}], 'jid': '20170313194317225101', 'user': 'sudo_pureuser', '_stamp': '2017-03-13T23:43:27.569866'}
[DEBUG   ] Requesting URL https://10.234.112.107/api/1.8/host/salt-host using POST method
[DEBUG   ] Sending event: tag = salt/run/20170313194317225101/ret; data = {'fun_args': ['https://10.234.112.107/api/1.8/host/salt-host', {'__pub_master_job_cache': 'local_cache', '__pub_ipc_mode': 'ipc', '__pub_gitfs_privkey': '', '__pub_gather_job_timeout': 10, '__pub_ssh_list_nodegroups': {}, '__pub_file_roots': {'base': ['/salt/states']}, '__pub_minionfs_mountpoint': '', '__pub_raet_port': 4506, '__pub_gitfs_global_lock': True, '__pub_log_granular_levels': {}, '__pub_ssh_timeout': 60, '__pub_cli_summary': False, 'verify_ssl': False, '__pub_state_verbose': True, '__pub_gitfs_saltenv': [], '__pub_gitfs_user': '', '__pub_git_pillar_branch': 'master', '__pub_hgfs_branch_method': 'branches', '__pub_reactor_refresh_interval': 60, '__pub_git_pillar_passphrase': '', '__pub_mktoken': False, '__pub_queue_dirs': [], '__pub_nodegroups': {}, '__pub_ssh_port': '22', '__pub_regen_thin': False, '__pub_engines': [], '__pub_gitfs_base': 'master', '__pub_minionfs_env': 'base', '__pub_syndic_log_file': '/var/log/salt/syndic', '__pub_tcp_master_pull_port': 4513, '__pub_fileserver_backend': ['roots'], '__pub_event_return': '', '__pub_cache': 'localfs', '__pub_winrepo_dir_ng': '/srv/salt/win/repo-ng', '__pub_winrepo_pubkey': '', '__pub_eauth': '', '__pub_ssh_scan_ports': '22', '__pub_show_timeout': True, '__pub_pub_hwm': 1000, '__pub_interface': '127.0.0.1', '__pub_master_use_pubkey_signature': False, '__pub_django_auth_path': '', '__pub_git_pillar_global_lock': True, '__pub_preserve_minion_cache': False, '__pub_publisher_acl': {}, '__pub_jinja_trim_blocks': False, '__pub_auth_mode': 1, '__pub_range_server': 'range:80', '__pub_gitfs_remotes': [], '__pub_doc': False, '__pub_winrepo_remotes_ng': ['https://github.com/saltstack/salt-winrepo-ng.git'], '__pub_pillar_version': 2, '__pub_ping_on_rotate': False, '__pub_on_demand_ext_pillar': ['libvirt', 'virtkey'], '__pub_hard_crash': False, '__pub_winrepo_password': '', '__pub_ssh_sudo_user': '', '__pub_ssl': None, '__pub_zmq_filtering': False, '__pub_ioflo_verbose': 0, '__pub_ssh_sudo': False, '__pub_transport': 'zeromq', '__pub_state_top_saltenv': None, '__pub_show_jid': False, '__pub_con_cache': False, '__pub_args_stdin': False, '__pub_loop_interval': 60, '__pub_id': 'salt-master_master', '__pub_hgfs_remotes': [], '__pub_fileserver_ignoresymlinks': False, '__pub_winrepo_dir': '/srv/salt/win/repo', '__pub_ssh_scan_timeout': 0.01, '__pub_ioflo_period': 0.01, '__pub_syndic_jid_forward_cache_hwm': 100, '__pub_minion_data_cache': True, '__pub_log_datefmt_logfile': '%Y-%m-%d %H:%M:%S', '__pub_gitfs_mountpoint': '', '__pub_event_return_queue': 0, '__pub_django_auth_settings': '', '__pub_extension_modules': '/var/cache/salt/master/extmods', '__pub_master_pubkey_signature': 'master_pubkey_signature', '__pub_syndic_wait': 5, '__pub_max_minions': 0, '__pub_publish_session': 86400, '__pub_default_top': 'base', '__pub_state_events': False, '__pub_http_request_timeout': 3600.0, '__pub_master_floscript': '/usr/lib/python2.7/dist-packages/salt/daemons/flo/master.flo', '__pub_verify_env': True, '__pub_syndic_pidfile': '/var/run/salt-syndic.pid', '__pub_rotate_aes_key': True, '__pub_token_expire': 43200, '__pub_selected_output_option': 'output_indent', '__pub_ssh_identities_only': False, '__pub_thin_extra_mods': '', '__pub_cluster_masters': [], '__pub_top_file_merging_strategy': 'merge', '__pub_svnfs_tags': 'tags', '__pub_event_match_type': 'startswith', '__pub_keep_jobs': 24, '__pub_file_recv_max_size': 100, 'method': 'POST', '__pub_fileserver_limit_traversal': False, '__pub_ssh_use_home_key': False, '__pub_state_top': 'top.sls', '__pub_master_uri': 'tcp://127.0.0.1:4506', '__pub_master_sign_key_name': 'master_sign', '__pub_event_return_whitelist': [], '__pub_ipv6': False, '__pub_order_masters': False, '__pub_tcp_keepalive_cnt': -1, '__pub_log_level': 'debug', '__pub_log_level_logfile': 'warning', '__pub_gitfs_env_blacklist': [], '__pub_state_aggregate': False, '__pub_enforce_mine_cache': False, '__pub_gitfs_root': '', '__pub_http_max_body': 107374182400, '__pub_ioflo_realtime': True, '__pub_env_order': [], '__pub_profiling_enabled': False, '__pub_config_dir': '/etc/salt', '__pub_outputter_dirs': [], '__pub_tcp_keepalive_idle': 300, '__pub_client_acl_verify': True, '__pub_cython_enable': False, '__pub_runner_dirs': [], '__pub_gitfs_env_whitelist': [], '__pub_conf_file': '/etc/salt/master', '__pub_cachedir': '/var/cache/salt/master', '__pub_archive_jobs': False, '__pub_ssh_passwd': '', '__pub_tcp_master_publish_pull': 4514, '__pub_git_pillar_env': '', '__pub_raet_alt_port': 4511, '__pub_runner_returns': True, 'persist_session': True, '__pub_fileserver_followsymlinks': True, '__pub_tcp_keepalive': True, '__pub_file_recv': False, '__pub_file_buffer_size': 1048576, '__pub_state_auto_order': True, '__pub_renderer': 'yaml_jinja', '__pub_pillar_cache': False, '__pub_raet_clear_remotes': False, '__pub_log_fmt_console': '[%(levelname)-8s] %(message)s', '__pub_hgfs_base': 'default', '__pub_pillar_cache_backend': 'disk', '__pub_timeout': 5, '__pub_quiet': False, '__pub_tcp_master_pub_port': 4512, '__pub_maintenance_floscript': '/usr/lib/python2.7/dist-packages/salt/daemons/flo/maint.flo', '__pub_keysize': 2048, '__pub_gitfs_pubkey': '', '__pub_key_cache': '', '__pub_python2_bin': 'python2', '__pub_root_dir': '/', '__pub_raet_mutable': False, '__pub_reactor_worker_hwm': 10000, '__pub_thorium_roots': {'base': ['/srv/thorium']}, '__pub_file_ignore_regex': [], '__pub_git_pillar_pubkey': '', '__pub_sign_pub_messages': False, '__pub_job_cache': True, '__pub_sqlite_queue_dir': '/var/cache/salt/master/queues', '__pub_python3_bin': 'python3', '__pub_worker_threads': 5, '__pub_ipc_write_buffer': 0, '__pub_tcp_master_workers': 4515, '__pub_ext_pillar': [], '__pub_log_file': '/var/log/salt/master', '__pub_cache_sreqs': True, '__pub_svnfs_trunk': 'trunk', '__pub___role': 'master', '__pub_tcp_keepalive_intvl': -1, '__pub_no_color': False, '__pub_sudo_acl': False, '__pub_auto_accept': False, '__pub_log_datefmt': '%H:%M:%S', '__pub_syndic_dir': '/var/cache/salt/master/syndics', '__pub_client_acl': {}, '__pub_winrepo_branch': 'master', '__pub_client_acl_blacklist': {}, '__pub_log_datefmt_console': '%H:%M:%S', '__pub_hgfs_env_blacklist': [], '__pub_dummy_pub': False, '__pub_publish_port': 4505, '__pub_serial': 'msgpack', '__pub_gitfs_passphrase': '', '__pub_svnfs_root': '', '__pub_master_tops': {}, '__pub_arg': ['https://10.234.112.107/api/1.8/host/salt-host', 'method=POST', 'data={"wwnlist": ["0011223344556677","1122334455667788"]}', 'persist_session=True', 'verify_ssl=false'], '__pub_reactor': [], '__pub_winrepo_insecure_auth': False, '__pub_git_pillar_root': '', '__pub_force_color': False, '__pub_open_mode': False, '__pub_raet_lane_bufcnt': 100, '__pub_git_pillar_password': '', '__pub_ret_port': 4506, '__pub_syndic_master': 'masterofmasters', '__pub_master_sign_pubkey': False, '__pub_pillar_safe_render_error': True, '__pub_renderer_blacklist': [], '__pub_max_event_size': 1048576, '__pub_hgfs_root': '', '__pub_svnfs_remotes': [], '__pub_profiling_path': '/tmp/stats', '__pub_git_pillar_base': 'master', '__pub_worker_floscript': '/usr/lib/python2.7/dist-packages/salt/daemons/flo/worker.flo', '__pub_token_expire_user_override': False, '__pub_key_logfile': '/var/log/salt/key', '__pub_environment': None, '__pub_pillar_cache_ttl': 3600, '__pub_failhard': False, '__pub_log_fmt_logfile': '%(asctime)s,%(msecs)03d [%(name)-17s][%(levelname)-8s][%(process)d] %(message)s', '__pub_async': False, '__pub_pillar_roots': {'base': ['/srv/pillar', '/srv/spm/pillar']}, '__pub_fun': 'http.query', '__pub_winrepo_user': '', '__pub_pillar_source_merging_strategy': 'smart', '__pub_zmq_monitor': False, '__pub_git_pillar_privkey': '', '__pub_hash_type': 'sha256', '__pub_minionfs_whitelist': [], '__pub_jinja_lstrip_blocks': False, '__pub_permissive_pki_access': False, '__pub_peer': {}, '__pub_state_output': 'full', '__pub_winrepo_passphrase': '', '__pub_state_output_diff': False, '__pub_git_pillar_user': '', '__pub_raet_clear_remote_masters': True, '__pub_gitfs_insecure_auth': False, '__pub_git_pillar_ssl_verify': True, '__pub_gitfs_ssl_verify': True, '__pub_svnfs_branches': 'branches', '__pub_master_roots': {'base': ['/srv/salt-master']}, '__pub_file_ignore_glob': [], '__pub_thorium_interval': 0.5, '__pub_reactor_worker_threads': 10, '__pub_test': False, '__pub_winrepo_privkey': '', '__pub_pidfile': '/var/run/salt-master.pid', '__pub_user': 'root', '__pub_pki_dir': '/etc/salt/pki/master', '__pub_search': '', '__pub_winrepo_ssl_verify': True, '__pub_ssh_user': 'root', '__pub_winrepo_cachefile': 'winrepo.p', '__pub_max_open_files': 100000, '__pub_ioflo_console_logdir': '', '__pub_token_file': '/root/salt_token', '__pub_publisher_acl_blacklist': {}, '__pub_renderer_whitelist': [], '__pub_ext_job_cache': '', '__pub_enable_gpu_grains': False, '__pub_token_dir': '/var/cache/salt/master/tokens', '__pub_search_index_interval': 3600, '__pub_raet_main': True, '__pub_pillar_opts': False, '__pub_file_client': 'local', 'data': {'wwnlist': ['0011223344556677', '1122334455667788']}, '__pub_svnfs_mountpoint': '', '__pub_syndic_failover': 'random', '__pub_winrepo_remotes': ['https://github.com/saltstack/salt-winrepo.git'], '__pub_hgfs_env_whitelist': [], '__pub_event_return_blacklist': [], '__pub_cluster_mode': False, '__pub_minionfs_blacklist': [], '__pub_external_auth': {}, '__pub_raet_road_bufcnt': 2, '__pub_svnfs_env_blacklist': [], '__pub_gitfs_password': '', '__pub_svnfs_env_whitelist': [], '__pub_exit_on_config_errors': False, '__pub_pillar_merge_lists': False, '__pub_git_pillar_insecure_auth': False, '__pub_syndic_event_forward_timeout': 0.5, '__pub_zmq_backlog': 1000, '__pub_hgfs_mountpoint': '', '__pub_sock_dir': '/var/run/salt/master', '__pub_output_file_append': False, '__pub_ssh_log_file': '/var/log/salt/ssh', '__pub_default_include': 'master.d/*.conf', '__pub_job_cache_store_endtime': False}], 'jid': '20170313194317225101', 'return': {'status': 400, 'error': 'HTTP 400: BAD REQUEST'}, 'success': True, '_stamp': '2017-03-13T23:43:27.600416', 'user': 'sudo_pureuser', 'fun': 'runner.http.query'}
[DEBUG   ] LazyLoaded nested.output
error:
    HTTP 400: BAD REQUEST
status:
    400
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20170313194317225101
[DEBUG   ] Runner return: {'status': 400, 'error': 'HTTP 400: BAD REQUEST'}

```

**Comment by gtmanfred** [comment] 2017-04-12 17:20
@techhat when you get a minute could you look into this?

I don't see any thing in here that would indicate why it is sending the list as a string.

Thanks,
Daniel

**Comment by techhat** [comment] 2017-04-12 17:47
Hi @sdodsley. The problem is that the Salt CLI automagically converts JSON/YAML to Python data structures (using `yaml.safe_load()`) so that they can be used with functions that expect things like `dict`s and `list`s as arguments. By the time `http.query()` gets ahold of your string it's already a dict, so it just URL encodes it so that it will `POST`.

The trick would be to trick Salt into not converting your data structure. It looks like prefacing the `data` string in your command with a space (`data=' {"wwnlist": ["0011223344556677","1122334455667788"]}'`) will accomplish that. The question is whether your API will treat a string starting with a space as proper JSON. http://jsonparseronline.com/ didn't have a problem with it, so I have high hopes.

**Comment by sdodsley** [comment] 2017-04-12 18:25
Hi @techhat. Unfortunately, that did not solve the problem.
Issuing 
```
# http.query https://10.234.112.107/api/1.8/host/salt-host method=POST data=' {"wwnlist":
 ["0011223344556677","1122334455667788"]}' persist_session=True verify_ssl=false
```
still fails with 400 and our internal logfile is saying:
```
2017-04-12 14:21:33.305 [INFO] 10.234.112.46 >> POST http://10.234.112.107/api/1.8/host/salt-host
{
  " {\"wwnlist\": [\"0011223344556677\",\"1122334455667788\"]}":""
}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pure/rest/controller/util.py", line 97, in execute
    (command, args) = get_args(command_list, version, params)
  File "/usr/lib/python2.7/dist-packages/pure/rest/controller/util.py", line 408, in get_args
    raise RestException(exception_msg, Code.BAD_REQUEST)
RestException: ['Argument  {"wwnlist": ["0011223344556677","1122334455667788"]} is not a valid parameter name.']
2017-04-12 14:21:33.306 [WARNING] << 400 BAD REQUEST
{
  "msg":[
    "Argument  {\"wwnlist\": [\"0011223344556677\",\"1122334455667788\"]} is not a valid parameter name."
  ]
}
```

**Comment by sdodsley** [comment] 2017-05-13 16:57
@techhat any other ideas about how to resolve this? can you confirm this a bug on your side?

**Comment by techhat** [comment] 2017-05-16 16:11
@sdodsley I can confirm the behavior, but this is getting out of my league. @terminalmage and/or @cachedout would you mind taking a look?

**Comment by terminalmage** [comment] 2017-05-18 15:32
As @techhat has noted, we pass arguments through PyYAML so that numeric values are loaded as ints/floats, and also allowing for complex data structures to be passed in on the CLI. The issue here though is that JSON loads as a Python dictionary when loaded my PyYAML.

I spent some time last night investigating a means of allowing for a mapping of functions to a list of arguments for which YAML loading should be skipped, similar to ``__func_alias__`` allows for the name of functions to be overidden. However, while this works well for runners, this method has the disadvantage of not working in remote execution (both in a traditional master/minion configuration, and via salt-ssh) because the YAML parsing happens before the command is published to the minion.

I'm investigating a potential method where we can add a CLI argument to the parser mixins which will allow a user to disable parsing for a given CLI argument. So, for example, it would be possible to do this:

```
salt-run http.query https://10.234.112.107/api/1.8/host/salt-host method=POST data='<JSON STRING>' --no-parse=data
```

**Comment by terminalmage** [comment] 2017-05-24 22:32
I've opened https://github.com/saltstack/salt/pull/41419 to implement a ``--no-parse`` argument to suppress PyYAML loading of individual CLI arguments.

**Comment by cachedout** [comment] 2017-05-31 22:39
This has been merged so it looks like this is ready to be closed.

**Closed by cachedout** 2017-05-31 22:39 UTC
Labels: Bug, Core, Nitrogen, TEAM Core
