### ISSUE TITLE
docker.running state fails with TypeError: create_host_config() got an unexpected keyword argument 'mem_limit'

### ISSUE THREAD

**Issue by allanliu** [saltstack/salt#28057] opened 2015-10-17 15:32 UTC
salt-minion version: salt-minion 2015.8.1-104-gd7263d2 (Beryllium)
salt-master version: salt-master 2015.5.0 (Lithium)
docker version: Docker version 1.7.1, build 786b29d

```
ID: mysql
    Function: docker.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/root/src/salt/salt/state.py", line 1592, in call
                  **cdata['kwargs'])
                File "/root/src/salt/salt/loader.py", line 1490, in wrapper
                  return f(*args, **kwargs)
                File "/root/src/salt/salt/states/dockerio.py", line 1233, in running
                  out = create(image_name, **kwargs)
                File "/root/src/salt/salt/modules/dockerio.py", line 714, in create_container
                  raise e
              TypeError: create_host_config() got an unexpected keyword argument 'mem_limit'
     Started: 15:28:57.179234
    Duration: 18.094 ms
     Changes:
```

state.sls block:
```
mysql:
  docker.running:
    - name: mysql
    - image: mysql
    - volumes:
      - /var/lib/mysql: /var/lib/mysql
    - environment:
      - MYSQL_ROOT_PASSWORD: superawesomepassword
    - ports:
      - 3306: 3306
    - require:
      - docker: wordpress_image
```

**Comment by jfindlay** [comment] 2015-10-19 16:47
@allanliu, thanks for the report.  This is a duplicate of https://github.com/saltstack/salt/issues/25492#issuecomment-138735071.

**Closed by jfindlay** 2015-10-19 16:47 UTC
Labels: Duplicate
