### ISSUE TITLE
[BUG] Error from pillar: TypeError: can not serialize 'CompletedProcess' object

### ISSUE THREAD

**Issue by brd** [saltstack/salt#58874] opened 2020-11-04 03:43 UTC
**Description**
I was experimenting with ext_pillar and I ended up with a master and minion that do not work reliably. In an effort to remove any lingering ext_pillar issues I have shut down both the master and minion and `rm -rf /var/cache/salt` and restarted both.  Then when I run various pillar functions (`salt '*' pillar.items`, `salt '*' pillar.get`, `salt '*' pillar.raw`) they work fine until I run `salt '*' state.highstate` fails, then `salt '*' pillar.items` starts failing, but `salt '*' pillar.raw` still works.

I think there must be some other cache that I need to remove, but I am unsure where else it could be.

**Setup**

<details><summary>master config file:</summary>

Comments and blank lines removed:
```
file_roots:
  prod:
    - /usr/local/etc/salt/prod
pillar_roots:
  prod:
    - /usr/local/etc/salt/pillar
log_level_logfile: debug
```
</details>

<details><summary>pillar roots:</summary>

```
root@ops1:/usr/local/etc/salt/pillar # cat top.sls 
prod:
  '*':
    - schedule

root@ops1:/usr/local/etc/salt/pillar # cat schedule.sls
schedule:
  highstate:
    function: state.highstate
    minutes: 30
```
</details>

<details><summary>file roots top and simple state to apply</summary>

```
root@ops1:/usr/local/etc/salt/prod # cat top.sls 
prod:
  '*':
    - tweaks
root@ops1:/usr/local/etc/salt/prod # cat tweaks.sls 
{% if grains['os'] == 'FreeBSD' %}
/usr/local/etc/newsyslog.conf.d:
  file.directory:
    - user: root
    - group: wheel

/usr/local/etc/newsyslog.conf.d/salt_minion:
  file:
    - managed
    - user: root
    - group: wheel
    - mode: 644
    - contents:
      - /var/log/salt/minion   640  7   *   @T00   JC
{% endif %}
```
</details>

**Steps to Reproduce the behavior**
I cannot reproduce this problem on another setup :/

**Expected behavior**
I expect pillar to work reliably and maybe a better error message.

**Versions Report**
<details><summary>salt --versions-report</summary>

Both master and minion are the same:
```
Salt Version:
           Salt: 3002
 
Dependency Versions:
           cffi: 1.14.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.7.9 (default, Nov  3 2020, 02:13:18)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: freebsd 12.1 
         locale: UTF-8
        machine: amd64
        release: 12.1-STABLE
         system: FreeBSD
        version: FreeBSD 12.1 
```
</details>

**Additional context**
<details><summary>Log from the minion at log level of trace, from running `salt '*' pillar.items`:</summary>

```
2020-11-04 00:48:49,163 [salt.transport.mixins.auth                                 :40  ][TRACE   ][48539] Decoding payload: {'enc': 'aes', 'load': b"\xd9\x86:\xb5.\xc4\xcad\xe3\xbf\x03\xe8\xc0h\t>\x9d\x8e\xd8j;E\xe93\x1c\xfayk\xc4\xa82\x85\x80\x98\xd3\x8e2\x9d\x8c\xc9\x94\x10sp\xe1D\xc9\xb7\xcdN\xee@\x0ci\xeb\x10\xe4l\n\xfa?\xb5\xfa\x9a\xea4\xb5)\x8cq\x00\xc7\xb8'\xea\xc8\xd9V\xdb\xf3\x87\xe7{b\x8bc\xb2\xc8\x96\xe1\x0bLu\xd7\x0f\xe3VD\x8dZ\xec6\xefJ\xa3\xb5\x12!\x16\xf0\xb9\x0b\x8e>\xf39\x88\xf2)U1\x01:69&S\x87\xd9!\xbd\xa7\x8d{\xe5\x81\t;\xe5\xd2kd[\xa0oib\xf4\xcf\x1b\xf7\xc2\xfc\x85\nY\x07\x16w\xc3", 'sig': b'F\xb3\x07\x87*\xad\xc2\xe4\xfc\xfe$kk\xcb\xf0\xc8\xe2\xc5>L.\xce\xd3\x1a\xbb\x90=\x8a\xe8\x166\x81\xef\x11\xf9\xf1\x80C=\xe2\xa4\x11\xb1,d\xa8=!\xb8\xb9\xcesT\xd5\xdb\x81S\xf9\x16\xea\x0f\x95\xb8\x05\x14\xd2\xbbD\x82 \xf2\x0b\x05Oz\x90\x92]L\x7fbhx\xd8\xbc(\x16\xf5\xd4\xb3(P\xd8\x0f\xa7\xbb#k9\xe3C\x90\x8aa\xd0\x96\x9c\xd7c\x16\x93\xb7\xbd\xfd\xe1s\x15\x07\xac\xce\xcd\xb1\x06o\xdc\xcb\xd3\x87\xce\\?\xd6/\xd3\x11\x87\xcf\x07\x04\x1dyz\x8cM\xf4A\xe0\xd4\xee6\xdc\rS\xfe\x91{\x81\x08\xe4(f\x84a\x12\xeb\xa7Z\xbeVq\x8d\xbe8\xf2?\xec\xdd\xb2\xab>\r>\xe0\xfd\xad\xee\x03Rc\xf7\xd4Xn\xba\x05aQ\xc6tY\xc1\x80\xdd\xd6\xf7g8\x06\x8a4#\x80\x92\xc1\x90\x9b\xe6N;\xe2\xd8\xad{\x9d\xb1\xd1dVK%\xdc\x81\x97G\xde8+\xb2\xc5\x17\xef\x95r\x90\xc1h\xd1_7m#d\xa0\x9fd\xf4'}
2020-11-04 00:48:49,164 [salt.minion                                                :1670][INFO    ][48539] User sudo_brd Executing command pillar.items with jid 20201104004849111700
2020-11-04 00:48:49,165 [salt.minion                                                :1674][DEBUG   ][48539] Command details {'fun': 'pillar.items', 'arg': [], 'tgt': 'ops2*', 'jid': '20201104004849111700', 'ret': '', 'tgt_type': 'glob', 'user': 'sudo_brd'}
2020-11-04 00:48:49,165 [salt.minion                                                :40  ][TRACE   ][48539] Started JIDs: ['20201104000232112461', '20201104000244636274', '20201104000256854637', '20201104000301949914', '20201104000457379796', '20201104000505964150', '20201104000516387874', '20201104000521961692', '20201104002935362527', '20201104002944435588', '20201104002949460733', '20201104003001837616', '20201104004344387602', '20201104004607547197', '20201104004617348018', '20201104004633253182', '20201104004727553424']
2020-11-04 00:48:49,173 [salt.utils.process                                         :1044][DEBUG   ][48539] Subprocess ProcessPayload-Job-20201104004849111700 added
2020-11-04 00:48:49,370 [salt.utils.lazy                                            :102 ][DEBUG   ][63490] LazyLoaded jinja.render
2020-11-04 00:48:49,373 [salt.utils.lazy                                            :102 ][DEBUG   ][63490] LazyLoaded yaml.render
2020-11-04 00:48:49,380 [salt.minion                                                :1866][INFO    ][63490] Starting a new job 20201104004849111700 with PID 63490
2020-11-04 00:48:49,382 [salt.loader                                                :40  ][TRACE   ][63490] Error loading executor.docker: Docker executor is only meant to be used with Docker Proxy Minions
2020-11-04 00:48:49,386 [salt.utils.lazy                                            :106 ][DEBUG   ][63490] Could not LazyLoad direct_call.allow_missing_func: 'direct_call.allow_missing_func' is not available.
2020-11-04 00:48:49,388 [salt.utils.lazy                                            :102 ][DEBUG   ][63490] LazyLoaded pillar.items
2020-11-04 00:48:49,390 [salt.minion                                                :40  ][TRACE   ][63490] Executors list ['direct_call']
2020-11-04 00:48:49,390 [salt.pillar                                                :77  ][DEBUG   ][63490] Determining pillar cache
2020-11-04 00:48:49,391 [salt.transport.zeromq                                      :165 ][DEBUG   ][63490] Initializing new AsyncZeroMQReqChannel for ('/usr/local/etc/salt/pki/minion', 'ops2.example.com', 'tcp://10.0.0.254:4506', 'aes')
2020-11-04 00:48:49,392 [salt.crypt                                                 :495 ][DEBUG   ][63490] Initializing new AsyncAuth for ('/usr/local/etc/salt/pki/minion', 'ops2.example.com', 'tcp://10.0.0.254:4506')
2020-11-04 00:48:49,392 [salt.transport.zeromq                                      :264 ][DEBUG   ][63490] Connecting the Minion to the Master URI (for the return server): tcp://10.0.0.254:4506
2020-11-04 00:48:49,394 [salt.transport.zeromq                                      :1308][DEBUG   ][63490] Trying to connect to: tcp://10.0.0.254:4506
2020-11-04 00:48:49,395 [salt.transport.zeromq                                      :40  ][TRACE   ][63490] Inserted key into loop_instance_map id 34463888080 for key ('/usr/local/etc/salt/pki/minion', 'ops2.example.com', 'tcp://10.0.0.254:4506', 'aes') and process 63490
2020-11-04 00:48:49,395 [salt.pillar                                                :40  ][TRACE   ][63490] ext_pillar_extra_data = {}
2020-11-04 00:48:49,399 [salt.minion                                                :1963][WARNING ][63490] Passed invalid arguments to pillar.items: can not serialize 'CompletedProcess' object

    Calls the master for a fresh pillar and generates the pillar data on the
    fly

    Contrast with :py:func:`raw` which returns the pillar data that is
    currently loaded into the minion.

    pillar
        If specified, allows for a dictionary of pillar data to be made
        available to pillar and ext_pillar rendering. these pillar variables
        will also override any variables of the same name in pillar or
        ext_pillar.

        .. versionadded:: 2015.5.0

    pillar_enc
        If specified, the data passed in the ``pillar`` argument will be passed
        through this renderer to decrypt it.

        .. note::
            This will decrypt on the minion side, so the specified renderer
            must be set up on the minion for this to work. Alternatively,
            pillar data can be decrypted master-side. For more information, see
            the :ref:`Pillar Encryption <pillar-encryption>` documentation.
            Pillar data that is decrypted master-side, is not decrypted until
            the end of pillar compilation though, so minion-side decryption
            will be necessary if the encrypted pillar data must be made
            available in an decrypted state pillar/ext_pillar rendering.

        .. versionadded:: 2017.7.0

    pillarenv
        Pass a specific pillar environment from which to compile pillar data.
        If not specified, then the minion's :conf_minion:`pillarenv` option is
        not used, and if that also is not specified then all configured pillar
        environments will be merged into a single pillar dictionary and
        returned.

        .. versionadded:: 2016.11.2

    saltenv
        Included only for compatibility with
        :conf_minion:`pillarenv_from_saltenv`, and is otherwise ignored.

    CLI Example:

    .. code-block:: bash

        salt '*' pillar.items
    
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/minion.py", line 1889, in _thread_return
    function_name, function_args, executors, opts, data
  File "/usr/local/lib/python3.7/site-packages/salt/minion.py", line 1845, in _execute_job_function
    return_data = self.executors[fname](opts, data, func, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/modules/pillar.py", line 279, in items
    return pillar.compile_pillar()
  File "/usr/local/lib/python3.7/site-packages/salt/pillar/__init__.py", line 335, in compile_pillar
    load, dictkey="pillar",
  File "/usr/local/lib/python3.7/site-packages/salt/utils/asynchronous.py", line 126, in wrap
    six.reraise(*results[1])
  File "/usr/local/lib/python3.7/site-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/salt/utils/asynchronous.py", line 132, in _target
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/site-packages/salt/transport/zeromq.py", line 356, in crypted_transfer_decode_dictentry
    self._package_load(self.auth.crypticle.dumps(load)),
  File "/usr/local/lib/python3.7/site-packages/salt/crypt.py", line 1535, in dumps
    return self.encrypt(self.PICKLE_PAD + self.serial.dumps(obj))
  File "/usr/local/lib/python3.7/site-packages/salt/payload.py", line 201, in dumps
    msg, default=ext_type_encoder, use_bin_type=use_bin_type
  File "/usr/local/lib/python3.7/site-packages/salt/utils/msgpack.py", line 133, in packb
    return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))
  File "/usr/local/lib/python3.7/site-packages/msgpack/__init__.py", line 46, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 284, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 234, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 245, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 281, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'CompletedProcess' object
2020-11-04 00:48:49,410 [salt.minion                                                :896 ][DEBUG   ][63490] Minion return retry timer set to 5 seconds (randomized)
2020-11-04 00:48:49,411 [salt.minion                                                :2152][INFO    ][63490] Returning information for job: 20201104004849111700
2020-11-04 00:48:49,411 [salt.minion                                                :40  ][TRACE   ][63490] Return data: {'success': False, 'return': "Passed invalid arguments to pillar.items: can not serialize 'CompletedProcess' object\n\n    Calls the master for a fresh pillar and generates the pillar data on the\n    fly\n\n    Contrast with :py:func:`raw` which returns the pillar data that is\n    currently loaded into the minion.\n\n    pillar\n        If specified, allows for a dictionary of pillar data to be made\n        available to pillar and ext_pillar rendering. these pillar variables\n        will also override any variables of the same name in pillar or\n        ext_pillar.\n\n        .. versionadded:: 2015.5.0\n\n    pillar_enc\n        If specified, the data passed in the ``pillar`` argument will be passed\n        through this renderer to decrypt it.\n\n        .. note::\n            This will decrypt on the minion side, so the specified renderer\n            must be set up on the minion for this to work. Alternatively,\n            pillar data can be decrypted master-side. For more information, see\n            the :ref:`Pillar Encryption <pillar-encryption>` documentation.\n            Pillar data that is decrypted master-side, is not decrypted until\n            the end of pillar compilation though, so minion-side decryption\n            will be necessary if the encrypted pillar data must be made\n            available in an decrypted state pillar/ext_pillar rendering.\n\n        .. versionadded:: 2017.7.0\n\n    pillarenv\n        Pass a specific pillar environment from which to compile pillar data.\n        If not specified, then the minion's :conf_minion:`pillarenv` option is\n        not used, and if that also is not specified then all configured pillar\n        environments will be merged into a single pillar dictionary and\n        returned.\n\n        .. versionadded:: 2016.11.2\n\n    saltenv\n        Included only for compatibility with\n        :conf_minion:`pillarenv_from_saltenv`, and is otherwise ignored.\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' pillar.items\n    ", 'out': 'nested', 'retcode': 1, 'jid': '20201104004849111700', 'fun': 'pillar.items', 'fun_args': []}
2020-11-04 00:48:49,412 [salt.transport.zeromq                                      :165 ][DEBUG   ][63490] Initializing new AsyncZeroMQReqChannel for ('/usr/local/etc/salt/pki/minion', 'ops2.example.com', 'tcp://10.0.0.254:4506', 'aes')
2020-11-04 00:48:49,412 [salt.crypt                                                 :495 ][DEBUG   ][63490] Initializing new AsyncAuth for ('/usr/local/etc/salt/pki/minion', 'ops2.example.com', 'tcp://10.0.0.254:4506')
2020-11-04 00:48:49,413 [salt.transport.zeromq                                      :264 ][DEBUG   ][63490] Connecting the Minion to the Master URI (for the return server): tcp://10.0.0.254:4506
2020-11-04 00:48:49,414 [salt.transport.zeromq                                      :1308][DEBUG   ][63490] Trying to connect to: tcp://10.0.0.254:4506
2020-11-04 00:48:49,415 [salt.transport.zeromq                                      :40  ][TRACE   ][63490] Inserted key into loop_instance_map id 34465962128 for key ('/usr/local/etc/salt/pki/minion', 'ops2.example.com', 'tcp://10.0.0.254:4506', 'aes') and process 63490
2020-11-04 00:48:49,528 [salt.utils.schedule                                        :40  ][TRACE   ][48539] ==== evaluating schedule now None =====
2020-11-04 00:48:49,729 [salt.transport.zeromq                                      :291 ][DEBUG   ][63490] Closing AsyncZeroMQReqChannel instance
2020-11-04 00:48:49,731 [salt.minion                                                :40  ][TRACE   ][63490] ret_val = None
2020-11-04 00:48:49,732 [salt.minion                                                :2019][DEBUG   ][63490] minion return: {'success': False, 'return': "Passed invalid arguments to pillar.items: can not serialize 'CompletedProcess' object\n\n    Calls the master for a fresh pillar and generates the pillar data on the\n    fly\n\n    Contrast with :py:func:`raw` which returns the pillar data that is\n    currently loaded into the minion.\n\n    pillar\n        If specified, allows for a dictionary of pillar data to be made\n        available to pillar and ext_pillar rendering. these pillar variables\n        will also override any variables of the same name in pillar or\n        ext_pillar.\n\n        .. versionadded:: 2015.5.0\n\n    pillar_enc\n        If specified, the data passed in the ``pillar`` argument will be passed\n        through this renderer to decrypt it.\n\n        .. note::\n            This will decrypt on the minion side, so the specified renderer\n            must be set up on the minion for this to work. Alternatively,\n            pillar data can be decrypted master-side. For more information, see\n            the :ref:`Pillar Encryption <pillar-encryption>` documentation.\n            Pillar data that is decrypted master-side, is not decrypted until\n            the end of pillar compilation though, so minion-side decryption\n            will be necessary if the encrypted pillar data must be made\n            available in an decrypted state pillar/ext_pillar rendering.\n\n        .. versionadded:: 2017.7.0\n\n    pillarenv\n        Pass a specific pillar environment from which to compile pillar data.\n        If not specified, then the minion's :conf_minion:`pillarenv` option is\n        not used, and if that also is not specified then all configured pillar\n        environments will be merged into a single pillar dictionary and\n        returned.\n\n        .. versionadded:: 2016.11.2\n\n    saltenv\n        Included only for compatibility with\n        :conf_minion:`pillarenv_from_saltenv`, and is otherwise ignored.\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' pillar.items\n    ", 'out': 'nested', 'retcode': 1, 'jid': '20201104004849111700', 'fun': 'pillar.items', 'fun_args': []}
2020-11-04 00:48:50,536 [salt.utils.schedule                                        :40  ][TRACE   ][48539] ==== evaluating schedule now None =====
2020-11-04 00:48:50,537 [salt.utils.process                                         :1055][DEBUG   ][48539] Subprocess ProcessPayload-Job-20201104004849111700 cleaned up
```
</details>

**Comment by brd** [comment] 2020-11-04 18:40
I found the problem.. I had a custom grain that would extract the ssh hostkeys via `ssh-keygen -r`

From `/usr/local/etc/salt/prod/_grains/ssh_hostkeys.py`:

```python
#!/usr/bin/env python

import socket
import subprocess
import sys


def get_host_key():
  hostname = socket.gethostname()
  grains = { }
  if sys.version_info[0] == 3:
    sshkeygen = subprocess.run(['ssh-keygen', '-r', hostname], capture_output=True, text=True)
    if sshkeygen.returncode != 0:
      print('error calling ssh-keygen: ', sshkeygen.stdout)
    else:
      grains['sshfp_records'] = sshkeygen
  # Py 2 support for old linux
  else:
    sshkeygen = subprocess.check_output(['ssh-keygen', '-r', hostname])
    grains['sshfp_records'] = sshkeygen

  return grains

if __name__ == "__main__":
  print(get_host_key())
```

On line 9 where I set sshfp_records, `sshkeygen` should be `sshkeygen.stdout`.

Strange that it showed up as a pillar issue..

**Comment by s0undt3ch** [comment] 2020-11-06 08:08
Based on the last comment, I'm closing as invalid since it's not a bug on the salt side.
Please let us know if you still think this is a salt issue.

**Closed by s0undt3ch** 2020-11-06 08:08 UTC
Labels: Bug, needs-triage

**Comment by brd** [comment] 2020-11-06 14:26
I think maybe Salt should check the dict returned by an ext_pillar is healthy.. but I am not sure how one would go about doing that?
