### ISSUE TITLE
state.orchestrate for salt masterless mode?

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#33356] opened 2016-05-19 12:01 UTC
Is there a way to run `state.orchestrate` using salt-call? I don't see it as a function in the execution module, only in the runner.

**Comment by babilen** [comment] 2016-05-19 13:09
As orchestration requires the ability to connect to multiple minions, I don't think that this can be achieved, as of now, when called locally on a minion.

How would you expect this to work? How would your minion know about other minions and talk to them? How would that differ from that minion being a master?

**Comment by lorengordon** [comment] 2016-05-19 13:18
I don't want to talk to multiple minions, just the local one. I just want to run states, re-initializing the loader and renderer in between. That way I can have a state that does something, then run another state that can render (via Jinja or whatever) objects set by the prior state.

**Comment by Ch3LL** [comment] 2016-05-20 04:12
babilen is correct currently this is not possible, because runners are master side only. You could possibly use the publish.runner from the minion but would still need a master to connect back to. Although I think this would be a great feature request to setup the ability for minions to be able to orchestrate running state files without the runner.

**Comment by lorengordon** [comment] 2016-05-20 09:21
@Ch3LL, maybe take a look at how the winrepo runner is imported into the winrepo execution module? Would that approach work here?

**Comment by whiteinge** [comment] 2016-05-20 15:33
@lorengordon take a look at #33390 when you have a moment. It is describing something very similar.

I like the idea of a "sub-state run". Both for Orchestrate (which is simply a master-side state run) as well as regular minion-side state runs. One obvious hurdle is by default Salt performs a check to prevent concurrent state runs on the same machine. (I'm surprised the workflow in the issue above works at all.) Maybe the calling state run pauses until the child is done then resumes, or maybe the parent is replaced by the child. In either case (or both), this would be a nice addition.

If you agree the issue linked above describes the same scenario you are describing, I'd like to close this one as a dupe of that one. Thoughts?

**Comment by lorengordon** [comment] 2016-05-20 15:51
@whiteinge, I just checked the `saltutil.runner` function and it says it must be run on the master. While the issues do appear related, it seems to me that they are addressing different use cases. Are you saying that to resolve the other issue, the `saltutil.runner` function would be made to work on a minion in masterless mode, as well? If so, sure, close as a duplicate. Though my preference would really be for a `state.orchestrate` execution module rather than layering it through the `saltutil` module.

**Comment by whiteinge** [comment] 2016-05-20 16:39
> Are you saying that to resolve the other issue, the saltutil.runner function would be made to work on a minion

No, this will decidedly be a feature addition for this issue and that issue because in both cases Salt needs to start a state run from a state run on a single machine. (Orchestrate is simply a master-side state run. The only thing different about it is since it's running on a master it can call more functions.)

You can execute runners on a masterless system if you install the salt-master package (no need to start the daemon). But you'll still have the problem described above.

Perhaps something like this. Could be called from any state run (Orchestrate, minion-side, or masterless):

```
# /srv/salt/proceedure_one.sls
run_proceedure_two:
  salt.sub_state:    # terrible name ;-)
    - sls: proceedure_two
```

**Comment by lorengordon** [comment] 2016-06-07 01:46
@whiteinge, perhaps keep it simple and consistent, name it the `state.apply` function... ;)

**Comment by lorengordon** [comment] 2016-06-07 13:09
Meh, figured I'd attempt to import the orchestrate runner into an execution module, as I proposed [above](https://github.com/saltstack/salt/issues/33356#issuecomment-220557669), but I'm not really getting anywhere fast.

The function runs, but first fails because `/var/cache/salt/master` does not exist. Create that directory, and it fails cuz `salt/client/__init__.py` cannot contact the master. Well, duh. Looking deeper to see how that works...

The imported runner function does run normal sls states just fine, actually...it's the orchestration-formatted states with targeting (e.g. `salt.state` and `salt.function`) that fail.

**Comment by lorengordon** [comment] 2016-06-07 14:39
Hmm, the fact that normal sls states ran fine gave me the idea of just using `module.run` with `state.sls` in masterless mode as a kind of poor man's orchestrate. Works like a champ, rendering happens as desired, no need to use the imported orchestrate function at all.

**Comment by lorengordon** [comment] 2016-06-07 14:46
For the sake of consistency, it would be nice if the same orchestration states worked, obviously with caveats/limitations. Perhaps the `states/saltmod.py` functions could be modified to detect masterless mode and just execute `module.run`?

**Comment by lorengordon** [comment] 2016-06-07 18:13
So, looks like this might be a good test for masterless mode: `__opts__['__role'] == 'minion' and __opts__['file_client'] == 'local'`?

**Comment by lorengordon** [comment] 2016-06-07 21:38
So, got a working patch for the `state.orchestrate` execution function and the `salt.state` state function. I tried a similar approach for the `salt.function` state, but I'm getting stuck.

```diff
diff --git a/salt/modules/state.py b/salt/modules/state.py
index f414839..11695b9 100644
--- a/salt/modules/state.py
+++ b/salt/modules/state.py
@@ -33,6 +33,14 @@ import salt.utils.jid
 import salt.utils.url
 from salt.exceptions import SaltInvocationError

+# The "unused" imports here are needed for the imported orchestrate runner
+# code
+# pylint: disable=unused-import
+from salt.runners.state import (
+    orchestrate as _orchestrate
+)
+# pylint: enable=unused-import
+
 # Import 3rd-party libs
 import salt.ext.six as six

@@ -58,6 +66,17 @@ __func_alias__ = {
 }
 log = logging.getLogger(__name__)

+# Define the module's virtual name
+__virtualname__ = 'state'
+
+def __virtual__():
+    '''
+    Set the virtualname
+    '''
+    global _orchestrate
+    _orchestrate = salt.utils.namespaced_function(_orchestrate, globals())
+    return __virtualname__
+

 def _filter_running(runnings):
     '''
@@ -107,6 +126,23 @@ def _wait(jid):
         states = _prior_running_states(jid)


+def orchestrate(mods,
+                saltenv='base',
+                test=None,
+                exclude=None,
+                pillar=None,
+                pillarenv=None):
+    '''
+    Execute the orchestrate runner
+    '''
+    return _orchestrate(mods=mods,
+                        saltenv=saltenv,
+                        test=test,
+                        exclude=exclude,
+                        pillar=pillar,
+                        pillarenv=pillarenv)
+
+
 def running(concurrent=False):
     '''
     Return a list of strings that contain state return data if a state function
diff --git a/salt/states/saltmod.py b/salt/states/saltmod.py
index da166d2..221557d 100644
--- a/salt/states/saltmod.py
+++ b/salt/states/saltmod.py
@@ -216,7 +216,21 @@ def state(
     if batch is not None:
         cmd_kw['batch'] = str(batch)

-    cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)
+    masterless = __opts__['__role'] == 'minion' and \
+                 __opts__['file_client'] == 'local'
+    if not masterless:
+        cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)
+    else:
+        if top:
+            cmd_kw['topfn'] = ''.join(cmd_kw.pop('arg'))
+        elif sls:
+            cmd_kw['mods'] = cmd_kw.pop('arg')
+        tmp_ret = __salt__[fun](**cmd_kw)
+        cmd_ret = { __opts__['id']: {
+            'ret': tmp_ret,
+            'out': tmp_ret.get('out', 'highstate') \
+                if isinstance(tmp_ret, dict) else 'highstate'
+        }}

     changes = {}
     fail = set()
```

**Closed** 2016-06-16 17:16 UTC
Labels: Core, Feature, Runners
