### ISSUE TITLE
Module keys appear to be checked prior to execution

### ISSUE THREAD

**Issue by vr-jack** [saltstack/salt#26438] opened 2015-08-18 17:26 UTC
If an sls has a pkg install as well as a module state that requires the package being installed, it will fail with a key error.

Workarounds appear to be to have a primary sls that includes 2 sls files. The first with the pkg installs and the second with the module states that depended on the pkg installs.

Example is installing mysql and using the mysql_database module. The modules can't load until their virtual definition meets it's requirements (usually a command that the pkg installs). While the pkg state should reload modules, it appears we hit an error in initial processing instead of letting each state run prior to key checks of future states.

This was hard to search on, so hopefully not a duplicate. We have a lot of documentation that uses pkg.installed followed by a configuration module. Require is not enough to stop the key error.

**Comment by jfindlay** [comment] 2015-08-19 17:28
@vr-jack, is it possible for you to provide a more specific example, or at least the specific error and debug logs you are seeing?  Also, what is the output of `salt --versions-report`?  Thanks.

**Comment by vr-jack** [comment] 2015-08-19 17:34
@jfindlay See https://github.com/saltstack-formulas/rabbitmq-formula/issues/20 and my fix.

**Comment by jfindlay** [comment] 2015-08-19 19:35
Thanks, @vr-jack.

**Comment by rallytime** [comment] 2016-01-26 20:28
@vr-jack Were you by change using salt version `2015.5.3` when you saw the errors you're describing? We had a regression in the state compiler that sounds exactly like the error you're describing here, which has since been fixed with newer versions of 2015.5.x and all 2015.8.x releases.

**Comment by vr-jack** [comment] 2016-01-26 21:36
@rallytime It's been forever. I should have been running 2015.5.3-613-g8e1b5da that I custom built.

There were multiple people complaining about it, but I'm not sure what versions they were running at the time. The rabbitmq problem is easy to duplicate and verify. Unfortunately, I'm not active in salt right now. Feel free to close if you believe it fixed.

**Comment by rallytime** [comment] 2016-01-26 22:08
@vr-jack Thanks for the response. There were many problems caused by that regression and we had a lot of filed issues revolving around it, all of which have been fixed. I'm going to close this, but if you come back and still have problems on newer releases, we would be more than happy to reopen.

**Closed by rallytime** 2016-01-26 22:08 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P3
