### ISSUE TITLE
syndic is not added to startup rhX

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#39880] opened 2017-03-08 09:53 UTC
### Description of Issue/Question
salt-syndic is not added to start automatically on boot.
it was removed from #32308. 
ping @terminalmage 
I also don't understand why the restart is commented out ( although it would need to have a condrestart in the init script )

### Steps to Reproduce Issue
install latest salt-syndic in a rh os and check with chkconfig if its added to startup.

### Versions Report
2016.11.x
haven't checked other versions.

**Comment by Ch3LL** [comment] 2017-03-08 16:16
@terminalmage or @dmurphy18 do you know why this behavior was added and if it was intended?

**Comment by terminalmage** [comment] 2017-03-08 16:52
Sorry, but I don't have any idea what you mean by "the restart is commented out", and I don't know what you think changed in that PR. Can you elaborate?

I don't think that any of the daemons are set to automatically start on boot, and that is the intended behavior I believe.

**Comment by tsaridas** [comment] 2017-03-08 17:15
at the spec file for rhX

https://github.com/saltstack/salt/blob/develop/pkg/rpm/salt.spec#L342
adds master to automatically start on boot and below you can find minion but not the syndic.

%postun restarts master and minion but not syndic.
https://github.com/saltstack/salt/blob/develop/pkg/rpm/salt.spec#L353

**Comment by terminalmage** [comment] 2017-03-08 17:20
@dmurphy18 Please see the above two links.

**Comment by dmurphy18** [comment] 2017-03-08 18:12
@tsaridas The spec file to generate Redhat packages exists in salt-pack, https://github.com/saltstack/salt-pack/blob/develop/file_roots/pkg/salt/2016_11_3/rhel7/spec/salt.spec, however the section of commented out code exists there too.  Can you verify which versions of Redhat this is occurring on, given use of chkconfig, I am presuming Redhat 6 since on Redhat 7 I would expect systemd commands to be used.

**Comment by dmurphy18** [comment] 2017-03-08 18:16
This shall be fix in the next releases, see https://github.com/saltstack/salt-pack/issues/221

**Comment by tsaridas** [comment] 2017-03-09 14:14
I'm using rh6 but I don't see any systemctl enable on rh7 either so I'm guessing its not added to startup there either.

I can confirm minion is not added to rh7 in startup but it is for rh5-6

**Comment by dmurphy18** [comment] 2017-03-20 16:11
Moving forward with the minor releases, salt-minion and salt-master will remain auto enabling on startup when they are installed on Redhat 6 & 5 since this functionality has been present since 8 Jan 2012.
Current functionality of Redhat 7 where they are not auto enabled on install shall be preserved.

In the next major release of Salt for Redhat 6 & 5, the auto enabling of salt-minion and salt-master shall be removed.

**Comment by dmurphy18** [comment] 2017-03-28 19:30
Fixed in Salt 2016.3.6

**Closed by dmurphy18** 2017-03-28 19:30 UTC
Labels: Packaging, Pending Discussion, Platform, TEAM Platform

**Comment by tsaridas** [comment] 2017-03-28 19:51
but I'm using 2016.11.3 :)

**Comment by dmurphy18** [comment] 2017-03-28 20:29
@tsaridas it will appear in 2016.11.4 when it is released, already in the code on the nightly builds for the 2016.11 branch.  Sorry have to wait for the next point release on the 2016.11 branch.

The Salt 2016.3.6 branch just went live an hour ago, announcement should be made soon if not already

**Comment by dmurphy18** [comment] 2017-03-28 20:31
@tsaridas If you so desire, you can re-open this and I'll move it to the blocked state, waiting for the next point release 2016.11.4.

**Comment by tsaridas** [comment] 2017-03-28 20:45
no, personally I don't really mind as long as you say its going to the next minor of 2016.11.

would you be able to point to a pr though so I can check the code ? :)

thanks

**Comment by dmurphy18** [comment] 2017-03-29 16:16
@tsaridas Please see https://github.com/saltstack/salt-pack/blob/develop/file_roots/pkg/salt/2016_11/rhel7/spec/salt.spec
 and review the history, March 16th and 20th

Same spec file is used for all Redhat builds
