### ISSUE TITLE
[Question] Git FS is not fetching files from run time tag.

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#58992] opened 2020-11-20 09:41 UTC
Git FS is not fetching files form tag. Have mentioned base and ref_type in the conf file, still file is not listing in the server

Is there any other way to handle this?  can I give tag name in Run time?

##master conf
```
fileserver_backend:
 - roots
 - gitfs

gitfs_provider: GitPython

gitfs_remotes:
  - git@github.###.com:sooraj/app.git:
    - name: config_repo
    - root: config/dev
    - mountpoint: salt://config/dev
    - ref_types:
      - tag
    - base: devops-salt-poc
```
Salt --version
3000.3

**Comment by sooraj2589** [comment] 2020-12-09 06:59
@sagetherage can you please update on this?

**Comment by sagetherage** [comment] 2020-12-15 00:37
We are terribly behind on triaging issues, i have reassigned and will look to get this triaged.

**Comment by garethgreenaway** [comment] 2021-01-11 22:11
@sooraj2589 apologies for the delay in responding to this one.  Unfortunately I wasn't able to reproduce the issue.  Just to clarify a few things in your gitfs remote configuration:
```
gitfs_remotes:
  - git@github.###.com:sooraj/app.git:
    - name: config_repo
    - root: config/dev
    - mountpoint: salt://config/dev
    - ref_types:
      - tag
    - base: devops-salt-poc
```
The remote tag that you're expected states are is `devops-salt-poc`, when you attempt to use the state in a call such as state.apply you're prefacing the name of the state with `config.dev`, and in your GIT repository there is a subdirectory called `config/dev` that contains the states you're expecting to see.  Also, any error messages that you're seeing when attempting to run the states.  Thanks!

**Comment by garethgreenaway** [comment] 2023-09-08 21:40
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!

**Closed by garethgreenaway** 2023-09-08 21:40 UTC
Labels: info-needed
