### ISSUE TITLE
archive.extracted and modified files not detected

### ISSUE THREAD

**Issue by gigi206** [saltstack/salt#50294] opened 2018-10-29 21:08 UTC
### Question

Is there a way for archive.extracted to detect modified files? Indeed, this function seems to detect only if a file is missing and not if a file has been modified.

**Comment by dwoz** [comment] 2018-10-30 17:01
@gigi206 Thanks for reporting the issue. Can you provide us with an example state?

**Comment by sathieu** [comment] 2020-01-09 16:14
Not stale.

**Comment by sathieu** [comment] 2020-02-08 16:47
Still not stale...

**Comment by sathieu** [comment] 2020-03-09 20:01
Not stable.

**Comment by gigi206** [comment] 2020-04-09 19:22
Not stale

**Comment by garethgreenaway** [comment] 2021-06-11 01:49
@gigi206 We discussed this one during our Triage meeting last week and wondered whether this particular is actually by design.  When looking at an archive it's easy and fairly quick to see the contents of the archive, eg. an list of what files and directories exist inside.  It's not easy however to see details about the files, eg. their sizes or MD5 sums to compare whether the file that exists in the archive is the same file that exists in the extracted location.  Depending on the size of the archive and size of the files contained inside, this could be a very costly action.  As an alternative, one suggestion from the Triage meeting was to utilize Salt beacons and reactors to monitor the extracted location for any changes that occur and then re-run the original state that extracted the archive into the desired location.

**Comment by garethgreenaway** [comment] 2023-08-28 18:18
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.

**Closed by garethgreenaway** 2023-08-28 18:18 UTC
Labels: Pending-Discussion
