### ISSUE TITLE
How to forbid the module when salt api use the cmd.run?

### ISSUE THREAD

**Issue by zhulh200868** [saltstack/salt#38192] opened 2016-12-11 05:19 UTC
change the app.py ?

**Comment by gtmanfred** [comment] 2016-12-12 16:26
You could just not allow the user who is making calls to have access to cmd.run, and only specify the modules that they can run in the eauth settings.

https://docs.saltstack.com/en/latest/topics/eauth/index.html

**Comment by whiteinge** [comment] 2016-12-14 07:53
See also the `modules` section under the [publisher_acl_blacklist](https://docs.saltstack.com/en/latest/ref/configuration/master.html#publisher-acl-blacklist) setting which works alongside eauth.

**Comment by zhulh200868** [comment] 2016-12-31 01:12
Oh,I am sorry.My question is about the salt api,and you say the salt master.
I want the salt master can use the modules but the salt api not use the modules.

**Comment by gtmanfred** [comment] 2016-12-31 01:14
Sorry, but you cannot do that.  The salt-api just shims off to the python Client that is used in the same way that the command line arguments are used.

The api runs through the master, it isn't separate.

**Comment by zhulh200868** [comment] 2017-01-01 03:05
@gtmanfred Your mean don't change the salt-api?Oh,I just want to change the salt-api's codes,and if one post request then salt-api judges the request,if the command is not allowed,back to 400.

**Comment by whiteinge** [comment] 2017-01-01 03:27
Salt's eauth and acl subsystems perform those kinds of checks. You're
welcome to edit the code for that netapi module for your use, of course,
but that isn't a change we're likely to accept in upstream because salt-api
does not perform any authentication or authorization by design -- all that
is handled by Salt.

If you want the check in salt-api for your own reasons then making your own
copy of that module is a fine way to go, but if you're going this route
because there's a deficiency in either eauth or acl we'd love to hear about
it.


On Dec 31, 2016 20:05, "zhulh200868" <notifications@github.com> wrote:

@gtmanfred <https://github.com/gtmanfred> Your mean don't change the
salt-api?Oh,I just want to change the salt-api's codes,and if one post
request then salt-api judges the request,if the command is not allowed,back
to 400.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/saltstack/salt/issues/38192#issuecomment-269890597>,
or mute
the thread

**Comment by zhulh200868** [comment] 2017-01-02 02:16
@whiteinge thank you very much!I just edit the netapi module ,but I don't know if edit the netapi module will effect the salt performance.

**Comment by whiteinge** [comment] 2017-01-02 05:05
It might affect salt-api's performance but changes to a netapi module are unlikely to affect Salt. Either way, I would suggest doing before/after benchmarks for whatever changes you make.

Good luck with your changes. I'm going to close this out now. Please feel free to reopen if your question wasn't fully addressed.

**Closed by whiteinge** 2017-01-02 05:05 UTC
Labels: Info Needed
