### ISSUE TITLE
Salt Master under some load bubbles ZMQ exceptions when sent SIGTERM

### ISSUE THREAD

**Issue by holmboe** [saltstack/salt#8432] opened 2013-11-12 09:25 UTC
This is a 0.17.1 master running on SLES 11 SP1 64 bit.

The exceptions below were displayed during some 10:s of seconds, but after a little longer the Salt Master processes eventually died.

```
sea2920spx1:~ # /etc/init.d/salt-master stop
sea2920spx1:~ # ps auxwww | grep salt-master
root      2768 24.3  0.7 276348 30456 ?        Sl   09:57   1:00 /usr/bin/python /usr/bin/salt-master -d
root      2771 24.3  0.7 276440 30444 ?        Sl   09:57   1:00 /usr/bin/python /usr/bin/salt-master -d
root      2774 24.3  0.7 276344 30428 ?        Sl   09:57   1:00 /usr/bin/python /usr/bin/salt-master -d
root      2775 24.3  0.7 276340 30448 ?        Sl   09:57   1:00 /usr/bin/python /usr/bin/salt-master -d
root      3083  0.0  0.0   5520   804 pts/3    R+   10:01   0:00 grep salt-master
sea2920spx1:~ # pkill -TERM salt-master
Exception salt.exceptions.MasterExit: MasterExit() in <built-in method __del__ of Context object at 0x1075050> ignored
Exception salt.exceptions.MasterExit: MasterExit() in <built-in method __del__ of Context object at 0x1075050> ignored
Exception salt.exceptions.MasterExit: MasterExit() in <built-in method __del__ of Context object at 0x1075050> ignored
Exception salt.exceptions.MasterExit: MasterExit() in <built-in method __del__ of Context object at 0x1075050> ignored
sea2920spx1:~ # ps auxwww | grep salt-master
root      2768 24.4  0.7 276348 30468 ?        Sl   09:57   1:09 /usr/bin/python /usr/bin/salt-master -d
root      2771 24.4  0.7 276440 30456 ?        Sl   09:57   1:09 /usr/bin/python /usr/bin/salt-master -d
root      2774 24.4  0.7 276344 30440 ?        Sl   09:57   1:09 /usr/bin/python /usr/bin/salt-master -d
root      2775 24.4  0.7 276340 30460 ?        Sl   09:57   1:09 /usr/bin/python /usr/bin/salt-master -d
root      3086  0.0  0.0   5520   804 pts/3    R+   10:02   0:00 grep salt-master
sea2920spx1:~ # pkill -TERM salt-master
Exception salt.exceptions.MasterExit: MasterExit() in <zmq.sugar.context.Context object at 0x1075050> ignored
Exception salt.exceptions.MasterExit: MasterExit() in <zmq.sugar.context.Context object at 0x1075050> ignored
Exception salt.exceptions.MasterExit: MasterExit() in <zmq.sugar.context.Context object at 0x1075050> ignored
Exception salt.exceptions.MasterExit: MasterExit() in <zmq.sugar.context.Context object at 0x1075050> ignored
sea2920spx1:~ # 
```

**Comment by rallytime** [comment] 2015-08-11 20:23
@holmboe I am making my way some old issues. I suspect this has been fixed when upgrading to newer versions of salt, as well as newer versions of ZMQ. Can you still reproduce this?

**Comment by rallytime** [comment] 2015-09-09 18:13
Closing since we didn't hear back. Let us know if this remains and issue and we can re-open. Thanks!

**Closed by rallytime** 2015-09-09 18:13 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P3
