### ISSUE TITLE
file.managed ignoring require of user

### ISSUE THREAD

**Issue by rsuarezsoto** [saltstack/salt#38303] opened 2016-12-16 09:47 UTC
I'm trying to create a file and make it belong to an user that I create in the same SLS. I use `require` to ensure that the user is created first, and then the file, but Saltstack seems to be ignoring it when I use `test=True`.

Here's the code sample:

```
test_user:
  user.present: 
    - shell: /bin/bash
        
/tmp/test_user.txt:
  file.managed:
    - user: test_user
    - require:
      - user: test_user
```

When running this with salt-call with `test=True`, this is what I get:

```
local:
----------
          ID: test_user
    Function: user.present
      Result: None
     Comment: User test_user set to be added
     Started: 10:31:23.205541
    Duration: 3.009 ms
     Changes:   
----------
          ID: /tmp/test_user.txt
    Function: file.managed
      Result: False
     Comment: User test_user is not available
     Started: 10:31:23.210603
    Duration: 4.968 ms
     Changes:   

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    1
------------
Total states run:     2
Total run time:   7.977 ms

```

But when running it without `test=True`, it works flawlessly:

```
local:
----------
          ID: test_user
    Function: user.present
      Result: True
     Comment: New user test_user created
     Started: 10:35:28.325257
    Duration: 172.329 ms
     Changes:   
              ----------
              fullname:
              gid:
                  1013
              groups:
                  - test_user
              home:
                  /home/test_user
              homephone:
              name:
                  test_user
              passwd:
                  x
              roomnumber:
              shell:
                  /bin/bash
              uid:
                  1010
              workphone:
----------
          ID: /tmp/test_user.txt
    Function: file.managed
      Result: True
     Comment: Empty file
     Started: 10:35:28.500421
    Duration: 6.563 ms
     Changes:   
              ----------
              new:
                  file /tmp/test_user.txt created
              user:
                  test_user

Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time: 178.892 ms

```

Am I doing anything wrong? Why does this not work when using `test=True`? I understand that what matters is that it works when not testing, but it's not funny having to execute a state for real without knowing if it'll work.

I'm running Saltstack 2016.3.3+ds-1 under Ubuntu 14.04. Thanks in advance!

**Comment by Ch3LL** [comment] 2016-12-16 21:29
@rsuarezsoto this happens because the user does not yet exist on the system. So when you run the `test=True` check it sees if the user exists and since it does not it exits. I would label this as expected behavior. 

I'm not sure how we would actually solve this. ping @cachedout or @rallytime do either of you see a way forward to improve this behavior? Want to make sure i get either of your opinions on the matter in case before I close as expected behavior. Thanks

**Comment by wolfpackmars2** [comment] 2016-12-24 05:15
There's not much documentation about state testing at present.  This is what I found:
https://docs.saltstack.com/en/latest/ref/states/testing.html

Through experience, I've learned that state testing is fairly limited, for reasons such as this.

In the short term, maybe some information about the limitations of state testing in the docs.  In the long term, I can think of two possible ways to fix this.

1) Modify state testing to actually apply a state to the system, then roll back any changes when complete. Truthfully, this is how I used to think it worked.  however, I seriously doubt this would be desirable for a whole host of reasons, not least of which it risks placing minions in an indeterminate state.

2) Modify state testing to look for instances such as this and "assume" that the user has been created. In other words, change the results of the test from "fail" with "assumed to pass".  I also don't think this is ideal.

**Comment by Ch3LL** [comment] 2017-01-25 16:54
@rsuarezsoto I think this is actually a duplciate of https://github.com/saltstack/salt/issues/34019 . This issue is opened to add better reporting when using test=True when one state is depended on another. This issue would address printing out a more useful error if for example the user did not exist but was going to be created. Going to close this issue and we can track there, unless anyone makes any convincing arguments thanks :)

**Closed by Ch3LL** 2017-01-25 16:54 UTC
Labels: Expected Behavior, Pending Discussion
