### ISSUE TITLE
[BUG]  Schedules not failing over properly when using master failover

### ISSUE THREAD

**Issue by saladman13** [saltstack/salt#62026] opened 2022-05-05 00:52 UTC
**Description**
Schedules not failing over after master failover

**Setup**
- multi master setup (2)
- minion running in failover mode 
-
master:
  - 10.x.x.1
  - 10.x.x.2

master_alive_interval: 60

master_failback: True
master_failback_interval: 30

Minion is running a schedule that  does "rpm -qa" every 15 seconds

After stopping the primary master, we see the minion correctly detect first master is dead, and change the master IP to second one in the list.

At this point, we expect the schedule to continue running every 15 seconds.  However, it takes 4 1/2 minutes before the schedule picks up again on the minion.  All the while, we see this in minion logs:

2022-05-05 00:22:23,824 [salt.utils.schedule:250 ][DEBUG   ][17557] schedule.handle_func: Checking job against fun state.sls: {'id': 'ip-10-231-35-164.ec2.internal', 'fun': 'state.sls', 'fun_args': ['test_loop'], 'schedule': 'test failover script schedule', 'jid': '20220505001852825603', 'pid': 18125}
2022-05-05 00:22:23,825 [salt.utils.schedule:260 ][DEBUG   ][17557] schedule.handle_func: Incrementing jobcount, now 1, maxrunning is 1
**2022-05-05 00:22:23,825 [salt.utils.schedule:267 ][DEBUG   ][17557] schedule.handle_func: The scheduled job test failover script schedule was not started, 1 already running**
2022-05-05 00:22:24,823 [salt.beacons     :107 ][INFO    ][17557] Closing beacon inotify. State run in progress.
2022-05-05 00:22:25,823 [salt.beacons     :107 ][INFO    ][17557] Closing beacon inotify. State run in progress.
2022-05-05 00:22:26,823 [salt.beacons     :107 ][INFO    ][17557] Closing beacon inotify. State run in progress.

As soon as the original master dies, this goes on for about about 4 minutes until we see:

022-05-05 00:22:53,125 [salt.transport.zeromq:1233][DEBUG   ][18125] Trying to connect to: tcp://10.231.35.189:4506
2022-05-05 00:22:53,126 [salt.utils.schedule:875 ][ERROR   ][18125] Unhandled exception running state.sls
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/schedule.py", line 842, in handle_func
    ret["return"] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)

Finally, after about 4 1/2 minutes, the schedule starts up again on the minion.

We expect the schedule to resume as soon as the minion detects the first master is down and fail over to the second master in the list.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [X ] VM running on a cloud service, please be explicit and add details
   AWS EC2 on rhel 8
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

- configure multi master (2)
- configure minion for failover mode
- schedule a job on minion with high frequency (every 15s)
- stop first master
- at this point, we expect to see the schedule keep running, but it does not happen for 4 1/2 minutes, even though logs indicate the minion has successfully failed over to the second master.

**Expected behavior**
Scheduled job should continue running as soon as minion detects first master is down.

**Screenshots**
See attached - job success at 19:18:39, failure not detected until 4 1/2 minutes later

**Versions Report**
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.1.0
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 1.6.0
        Python: 3.6.8 (default, Sep  9 2021, 07:49:02)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 8.5 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.23.1.el8_5.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.5 Ootpa

```yaml
PASTE HERE
<img width="960" alt="alcali" src="https://user-images.githubusercontent.com/104951153/166849409-869d74a8-78f4-4d97-9a6d-2d1125085d9d.png">

```
</details>

**Additional context**

**Comment by saladman13** [comment] 2022-05-05 01:01
Just wanted to add - schedule failback is immediate.  When the dead master comes back online, minion detects it and the schedule picks up immmediately.

**Comment by garethgreenaway** [comment] 2022-05-13 23:09
@saladman13 Thanks for the report.  I was unable to reproduce this in the latest master branch, which means it should be fixed in the 3005 release.  I was able to bring up a single minion with two masters, add a job to the scheulder, then shutdown one of the masters, and still see the scheduled job running.  I'll see if I can reproduce it with 3004.1.

**Comment by garethgreenaway** [comment] 2023-08-21 18:50
Closing this one out due to lack of activity.  If the issue persists please open a new issue.  Thanks!

**Closed by garethgreenaway** 2023-08-21 18:50 UTC
Labels: Bug, needs-triage
