### ISSUE TITLE
Simple way to avoid conflicts between "key accept" reactors and "on start" reactors

### ISSUE THREAD

**Issue by moloney** [saltstack/salt#30462] opened 2016-01-19 23:39 UTC
It is a common need to do something slightly different on the first boot of a minion and subsequent reboots.  We can write reactors for when a minion key is first accepted (our first boot) but when we write a reactor for minion starts there is no way to tell it only run on subsequent reboots.  Perhaps we can provide something like a boolean `is_first_boot` in the minion startup events?

**Comment by jfindlay** [comment] 2016-01-21 17:12
@moloney, thanks for reporting.  There is not a duplicate of this issue that I know of.

**Comment by moloney** [comment] 2016-05-27 20:26
This is solvable with a persistent master side data store (like sdb). Just add the minion to a list that have gone through the first boot preparations. I ended up always using the minion startup event and ignoring the event for the key being accepted since it looks like the key is accepted before the minion is fully prepared to start applying states.

I think this issue can be closed, but I will leave that to your discretion.

**Comment by jfindlay** [comment] 2016-05-27 21:05
@moloney, I'm glad you were able to figure this out.  Let's close this unless somebody else can also make a case beyond what is handled by your solution.

**Closed by jfindlay** 2016-05-27 21:05 UTC
Labels: Core, Feature
