### ISSUE TITLE
Shadow documentation missing

### ISSUE THREAD

**Issue by MTecknology** [saltstack/salt#51153] opened 2019-01-12 00:52 UTC
### Description of Issue/Question

The documentation produced for `salt.modules.shadow` [1] mentions that `shadow` [2] is the resource that provides `shadow` support for Linux.

Unfortunately, these names conflict and it's not possible to get to documentation for the linux/shadow module [2].

I suspect this is an easy fix (rename the module), but I don't have the time to provide a patch... just the complaint.

[1] https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.shadow.html
[2] https://github.com/saltstack/salt/blob/develop/salt/modules/shadow.py

**Comment by max-arnold** [comment] 2019-01-13 05:39
Duplicate of #49335

**Comment by racooper** [comment] 2019-11-20 22:16
This is still an ongoing issue.  Web docs for the shadow module are not available.  Clicking on "shadow" for linux on https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.shadow.html#module-salt.modules.shadow just returns to the same page.

**Comment by MTecknology** [comment] 2020-01-07 12:20
Can someone add that label that prevents marking this as stale?

**Comment by johnnybubonic** [comment] 2020-02-07 04:35
not stale; pending merge of https://github.com/saltstack/salt/pull/55914

**Comment by johnnybubonic** [comment] 2020-03-08 04:38
keep open; this problem still exists.

**Comment by johnnybubonic** [comment] 2020-04-07 13:49
issue still exists.

**Closed** 2020-05-23 17:41 UTC
Labels: Duplicate
