### ISSUE TITLE
requiring sls file containing only includes fail

### ISSUE THREAD

**Issue by kintel** [saltstack/salt#10852] opened 2014-02-28 05:32 UTC
I have the following file structure:

```
includetest/init.sls
includetest/subtestfile.sls
includetest/testfile.sls
```

init.sls:

```
include:
  - includetest.testfile

/home/deploy/testfile2.txt:
  file.managed:
    - contents: Hello
    - require:
      - sls: includetest.testfile
```

testfile.sls:

```
include:
  - .subtestfile
```

subtestfile.sls:

```
/home/deploy/subtestfile.txt:
  file.managed:
    - contents: Hello
```

When running `salt-call state.sls includetest`, I get:

```
    State: - file
    Name:      /home/deploy/testfile2.txt
    Function:  managed
        Result:    False
        Comment:   The following requisites were not found:
                   require:
                       sls: includetest.testfile
```

Playing around a bit, it appears that this is caused by requiring a file containing _only_ includes. A workaround is to modify testfile.sls to do some arbitrary work.

Is this a bug or by design?
My use-case is to have a file including a bunch of states and requiring that file from various places.
(Tested on 0.17.5)

**Comment by spareslant** [comment] 2015-02-11 22:47
@whiteinge and @kintel  thanks for suggesting an alternative solution. This was much needed.

**Comment by eliasp** [comment] 2015-09-24 12:51
Just wasted ~3h on this bug too until I realized what I was dealing with :)
Using now a simple `test.configurable_test_state` as workaround which could also be replaced with `test.nop` (available since `2015.5.6`) - depending on the used Salt version.

**Comment by boltronics** [comment] 2015-09-24 13:32
@eliasp Join the club. :) It's generally not obvious what the problem is when you hit it. This drove me nuts last year until it was burned into my mind to always watch out for this.

I'm very glad to see this bumped up from Low to High severity at least.

**Comment by JaseFace** [comment] 2016-09-23 20:03
It appears for understandable reasons there is same behavior when you include an 'empty' file, say for example you include a file wrapped in conditionals that don't trigger.  So more appropriately this bug triggers when you simply include an sls without any states.

**Comment by DanyC97** [comment] 2017-02-03 13:52
shame this hasn't been fixed even after 3 y (spent ages to find why i got this issue)

**Comment by sean-bennett112** [comment] 2017-02-24 20:19
I also recently ran into this, and it took quite awhile to find this issue and the underlying reason it's failing. Has there been any movement on this? Or at the very least, could the documentation be updated to point out that requiring an empty sls, or an sls that only has include statements, currently fails?

**Comment by whiteinge** [comment] 2017-02-24 23:27
This isn't currently being worked on. Two ideas that have been floated is to have Salt's YAML parser automatically add a `test.nop` state to empty files or to figure out a change to Salt's state compiler that can detect this condition another way.

In the meantime, a docs addition is a great idea. [This doc](https://github.com/saltstack/salt/blob/develop/doc/ref/states/include.rst) is a good first place to add a warning. @sean-bennett112 are you interested in adding that? You can edit that file directly from GitHub's web UI if you'd like.

**Comment by sean-bennett112** [comment] 2017-02-27 19:39
@whiteinge sorry for the late reply. I'd be happy to add a warning to the docs. However, is that the best place to add one? I'd think a better location would be [here](https://github.com/saltstack/salt/blob/develop/doc/ref/states/requisites.rst#require-an-entire-sls-file), given that page tends to be the first or second result in Google when I'm trying to debug a requisites issue.

**Comment by whiteinge** [comment] 2017-02-27 23:54
@sean-bennett112 good call! A warning in both wouldn't be too much, IMO.

**Comment by Reiner030** [comment] 2017-04-20 08:00
Belated happy 3rd birthday to this bug ;) Is there sometimes a fix to be in sight?
Since on other usages this multilevel references are unproblematic (pillar, grains, sls references for includes) it shouldn't be too problematic / difficult to get here also a solution?

The above mentioned workaround could /has to be used then but I was just trying to avoid single state reference and use a whole sls as required_in because saltstack likes to play dice with state ordering already also in the referenced sls

**Comment by hgfischer** [comment] 2017-11-30 15:52
Just hit the nail with this bug now. I guess that's the price to pay for trying to write organized formulas. :(

**Comment by kiemlicz** [comment] 2019-03-26 09:52
I think it is still an issue

**Comment by MalloZup** [comment] 2019-07-26 08:26
update on this?

**Comment by MalloZup** [comment] 2019-07-26 08:26
it is a stale issue but still an issue, the bot algorithm need improvements there.

**Comment by kiemlicz** [comment] 2020-01-08 10:41
I guess not stale

**Comment by wayne-weibel** [comment] 2020-04-24 12:08
just hit this same bug, again

**Comment by sagetherage** [comment] 2021-02-17 22:44
The Core team won't be able to get to this in Aluminium, moving it back into planning for another release.

**Comment by dmurphy18** [comment] 2023-08-28 15:47
@kintel Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.

**Comment by baby-gnu** [comment] 2023-08-29 09:28
> Closing this due to age, the old version of Salt and Python 2. Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.

I still have this issue on `3006.2`, I opened #65080 as you requested.

**Comment by OrangeDog** [comment] 2023-08-29 09:39
> will have metrics in tracking issues

What does this mean? Pretending that you haven't been saying you'll fix it for nearly a decade?

**Comment by dmurphy18** [comment] 2023-08-29 16:24
@OrangeDog Understand what you say about Python, but bit of difference between 2 and 3. 
Secondly getting originator's to test with latest, since the Core Team doesn't have the bandwidth to go through all of these old issues originated in 2014/2015 in our backlog.  Yeah, it has been updated this decade, but a number of them have not.
With the new GitHub Actions based PR testing etc., able to get through a lot more, than in the past, hence the desire to clean up backlog, and only work on those still relevant.

Hence close, have the originator retest and fill out new issue (with the template filled out) on current code.
@baby-gnu Thanks for checking and am assigning myself to the new issue.

**Comment by twangboy** [comment] 2023-08-30 19:38
Closing. New issue being tracked here: https://github.com/saltstack/salt/issues/65080

**Closed by twangboy** 2023-08-30 19:38 UTC
Labels: Bug, severity-medium, Core, State-Compiler
