### ISSUE TITLE
"Failed to load function" errors on 2018.3.3 master

### ISSUE THREAD

**Issue by clallen** [saltstack/salt#50781] opened 2018-12-07 01:51 UTC
### Description of Issue/Question
I'm in the process of upgrading to 2018.3.3, and see these errors in the master log:
```
2018-12-06 18:31:33,825 [salt.loader      :1698][ERROR   ][21774] Failed to load function {'cmd': '_file_envs'}.envs because its module ({'cmd': '_file_envs'}) is not in the whitelist: [u'gitfs', u'roots']
2018-12-06 18:31:33,825 [salt.loader      :1698][ERROR   ][21774] Failed to load function {'cmd': '_file_envs.envs because its module ({'cmd': '_file_envs) is not in the whitelist: [u'gitfs', u'roots']
```
I am unsure if this is causing any actual problems, because everything seems to work.

### Steps to Reproduce Issue
Any state.sls call will trigger the errors, even with a very simple SLS, such as:
```
Simple test:
  test.nop
```

### Versions Report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Dec  6 2018, 16:19:54)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 4.1.12-124.15.2.el7uek.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo

**Comment by Ch3LL** [comment] 2018-12-07 16:01
looks like its coming from here: https://github.com/saltstack/salt/blob/v2018.3.3/salt/loader.py#L1695-L1699

are you using any sort of whitelisting?

**Comment by clallen** [comment] 2018-12-07 16:15
I don't have any configured.  Is there a way to look at the "effective" options at runtime?

**Comment by clallen** [comment] 2018-12-10 16:42
Thanks @Ch3LL !

**Comment by terminalmage** [comment] 2018-12-10 20:55
I can't reproduce this. Please provide a reproducible test case.

**Comment by kzorba** [comment] 2018-12-11 11:46
In a small lab environment I created to test network automation with salt using docker containers, I can reproduce the issue in 2018.3 branch. Using 2017.7 no error messages appear in the master.
My repo is here:

https://github.com/kzorba/net-automation-lab

**Comment by terminalmage** [comment] 2018-12-11 16:45
The master failed to build for me.

**Comment by terminalmage** [comment] 2018-12-11 16:45
Can you just provide a set of configs and steps to reproduce?

**Comment by kzorba** [comment] 2018-12-11 17:11
Stupid mistake from my part, I had a typo error, fixed. Out of the box it builds salt 2017.7 branch containers (no issue there). Comment/uncomment the relevant parts in Dockerfile.master, Dockerfile.proxy and docker-compose.yml and build the 2018.3 where the problem appears when you issue "make start" (problem will appear in salt-master console). Let me know if you succeed or you have any other question.

**Comment by terminalmage** [comment] 2018-12-11 17:36
I already commented out 2017.7 and used 2018.3 before I commented.

**Comment by kzorba** [comment] 2018-12-11 18:11
My typo was in docker-compose.yml. Did you comment/uncomment the relevant `image` lines there as well? You need to do it in the Dockerfiles and docker-compose.yml. I just build everything from scratch in my environment and it works. Can you tell me what is the error you get?

**Comment by terminalmage** [comment] 2018-12-11 18:49
This issue appears to have been fixed after we branched for the 2018.3.3 release. @Ch3LL tested against the head of the 2018.3 branch (which will become 2018.3.4) and was unable to reproduce, but was able to reproduce on 2018.3.3. I hadn't tested against 2018.3.3, which is why I could not reproduce.

**Comment by Deshke** [comment] 2018-12-12 08:39
jep, currently facing the issue, what is the workaround for this ?

**Comment by terminalmage** [comment] 2018-12-12 16:04
This isn't causing any actual problems, aside from adding noise to the log. It was fixed by https://github.com/saltstack/salt/pull/49526.

The only way to suppress these messages in 2018.3.3 is to set `log_level_logfile` to something more severe than `error` (for example, `critical`). However this means that you will lose all log messages logged at the `error` loglevel.

**Comment by terminalmage** [comment] 2018-12-12 16:04
As this is known to be fixed, I'm closing this.

**Closed by terminalmage** 2018-12-12 16:04 UTC
Labels: Bug, High Severity, P1, team-core
