### ISSUE TITLE
Can't use Subnet/IP Address Matching

### ISSUE THREAD

**Issue by techcook** [saltstack/salt#30169] opened 2016-01-06 02:48 UTC
version: 2015.8
Descriptions: salt can't use Subnet/IP address matching.
![qq 20160106121830](https://cloud.githubusercontent.com/assets/10361796/12134941/bab8e4a6-b46f-11e5-838d-8e68f215a69e.png)

**Comment by techcook** [comment] 2016-01-06 04:20
add pic

**Comment by ssgward** [comment] 2016-01-06 16:26
@techcook - did you try ``S@10.10.10.100`` to see if that was successful, as opposed to ``-S...``?

**Comment by techcook** [comment] 2016-01-07 09:14
@ssgward  yes, I have try do it . but have same  problem:

**Comment by ssgward** [comment] 2016-01-07 15:46
OK. Sounds like a bug.

**Comment by whytewolf** [comment] 2016-01-19 17:40
+1 also having this bug. and finding that it goes a little deeper than just the ip not matching. even some subnets that should match are not. 

for an ip of 10.40.0.2 I can test upto 10.40.0.0/25 

but a submask of /26 or higher does not match. even though that ip should be within range till at least /30 also a subnet mask of /32 for an ip never matches. even though it is technically a valid subnet mask for a single ip.

```
salt --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.4
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-41-generic
         system: Ubuntu 14.04 trusty
```

also this is affecting mine.get

```
salt 'ctrl*' mine.get 'I@roles:ntp-server and not S@10.40.0.3' mgmt_network compound
ctrl01.wolfcloud.bad4.us:
    ----------
    ctrl01.wolfcloud.bad4.us:
        - 10.40.0.2
    ctrl02.wolfcloud.bad4.us:
        - 10.40.0.3
    ctrl03.wolfcloud.bad4.us:
        - 10.40.0.4
ctrl03.wolfcloud.bad4.us:
    ----------
    ctrl01.wolfcloud.bad4.us:
        - 10.40.0.2
    ctrl02.wolfcloud.bad4.us:
        - 10.40.0.3
    ctrl03.wolfcloud.bad4.us:
        - 10.40.0.4
ctrl02.wolfcloud.bad4.us:
    ----------
    ctrl01.wolfcloud.bad4.us:
        - 10.40.0.2
    ctrl02.wolfcloud.bad4.us:
        - 10.40.0.3
    ctrl03.wolfcloud.bad4.us:
        - 10.40.0.4
```

however modules.match.ipcidr does not seem to be affected.

**Comment by whytewolf** [comment] 2016-01-22 22:01
this looks like a dupe of #29188

**Comment by hgfischer** [comment] 2016-01-28 15:40
I'm being affected by the same problem here.

**Comment by hgfischer** [comment] 2016-01-28 16:28
Clearing the minion cache and syncing partially solved the problem: 

```
salt '*' cmd.run 'rm -rm /var/cache/salt/minion/files/base/*'
salt '*' saltutil.sync_all
```

Now I have lots of 'True' responses for the following command but also lots of `Minion did not return` errors.

But then I restarted all Minions and the problem is back. Sometimes it works, sometimes not.

**Comment by rallytime** [comment] 2016-02-12 23:10
Hi everyone! This is a duplicate of #29188, as @whytewolf suggested. (Thanks for the find!)

Since the other issue is older, I am going to close this in favor of that one so we can track the issue all in one issue.

**Closed by rallytime** 2016-02-12 23:10 UTC
Labels: Bug, Core, Duplicate, Grains, High Severity, P2
