### ISSUE TITLE
unit.test_auth.MasterACLTestCase.test_master_publish_name

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#53786] opened 2019-07-09 23:30 UTC
Neon fails on `salt-fedora-29-py2, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py3-tcp`
Error:
```
'NoneType' object is not subscriptable
```

**Comment by Akm0d** [comment] 2019-07-09 23:47
Duplicate of https://github.com/saltstack/salt/issues/53788

**Closed by Akm0d** 2019-07-09 23:47 UTC
Labels: Neon, Test Failure
