### ISSUE TITLE
Key format change from 2017.7 to Oxygen

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#45833] opened 2018-02-02 00:13 UTC
### Description of Issue/Question
Something has changed with the minion keys between 2017.7 and Oxygen. When upgrading from 2017.7 to Oxygen, the minion will no longer start because it's key is being denied. When you run `salt-key` on the master, you get something similar to the following:
```
master:/srv/salt# salt-key
Accepted Keys:
slee_winsrv2016_tests
Denied Keys:
slee_winsrv2016_tests
Unaccepted Keys:
Rejected Keys:
```
Here are the contents of the keys:
/etc/salt/pki/master/minions/<current key>
```
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAnuBrZNE2R2NgwdeJe6/8
dszO2VAkOdlWUQyT3Aop2/1AOJDzx1ssLqSZ3IMxknNQLUsMfJLpKH8olg4jHTcy
DBijrColavJ9spTKgPOdorb/SxvsX5tsh2IsPQiesdLoLYrOSEoEzCNTkgQ+Dvl6
isdADig19E2ebHEQ/8MWKBEhrEFAAxxeJ/ShS6aUxvf4ya4WXrS9gbUAUpiaJwsw
qx4zHJ728Ykc8ZyQNX6+DOH2j6hX2KF8k4TSCL5CKYdMCR49G6mok/jhfOgJUnmI
7/4N1CCLZ3IOe1zLdsGLp9sDsk474mzP2gAYjC8cqSGLXpgCJmvyxVTfrVi0qauy
4laE3gKhgH5k9BCEadYxl3MMzYimINosEKA4UUS2EQdkJx2piSafz/wET2s3+pfU
Jw1Cluo/6gKoCfFdhieRvGZOKUMtNpZ5xfMW+MWXcj72o8LPCWEc/0UFeMomqo2P
DrvGsopGc0etuF1nAup3iMv/WC1aCrvwd0X2Pg2hdS73pK1IjbityOt1E7fQTf8C
wjnkHhPunYatbvNzYAVZIy/JEYKCNhGnfkI7jxW5XBAqtaTH/4gSl98Bd497Tmrs
pOcLU6jLdHTkbXTtoFB653gGquE3wM/G30MLt+d5y56I1Vy3hM+WL3fCo+rDeEoy
oShJ4MG9QF0fhTZZxjJH5X8CAwEAAQ==
-----END PUBLIC KEY-----
```
/etc/salt/pki/master/minions_denied/<denied key>
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvQcfBpsvu533OB/A43Wi
PSKasp+4AgBJwXCJOM1a97oSDJeM6l4q3lLRfpkluy0PwFkufyrz0qCoqSY0mhvW
ya/pv0flT5JD4aN3pMfKGvlgVvYVW2RjkvDWKZJk46Gr4M5YLxgipglRJMMk8Zce
Np+v57Qm7o7wA5ARO3Yn1iAoLY7hy23UDdmAGg/EazfZQd67XKu3+Dsz5YKbxTVR
s9VxJl0WVboVKCrXz+83gJ6cSQHM7csKALtyS/CXK/0UfP3RdOXWY2xSO61/bSz/
SCYoG3D2XzRuyE7JOj+egfva0ihUPgv44g0QdHwc1wivodaR++wSFqCZ7vnbrpwj
NQIDAQAB
-----END PUBLIC KEY-----
```

### Steps to Reproduce Issue
Install 2017.7 minion (any version)
Start the minion (`salt-minion -l debug`)
Accept the key on the master
perform test.ping
minion starts successfully

Install Oxygen minion
Start the minion (`salt-minion -l debug`)
The minion will fail to start
The following will be displayed
```
[DEBUG   ] Initializing new AsyncAuth for ('/conf/pki/minion', 'slee_winsrv2016_tests', u'tcp://104.236.251.190:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8384)
[DEBUG   ] Setting zmq_reconnect_ivl to '8384ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/conf/pki/minion', 'slee_winsrv2016_tests', u'tcp://104.236.251.190:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://104.236.251.190:4506
[DEBUG   ] Trying to connect to: tcp://104.236.251.190:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
```
salt-key on the master will show the following:
```
master:/srv/salt# salt-key
Accepted Keys:
slee_winsrv2016_tests
Denied Keys:
slee_winsrv2016_tests
Unaccepted Keys:
Rejected Keys:
```

### Versions Report
Oxygen Master
2017.7 minion
Oxygen minion

**Comment by rallytime** [comment] 2018-02-02 14:37
I am interested to know if this is happening on Linux as well as Windows. And is it possible to bisect this?

**Comment by rallytime** [comment] 2018-02-05 18:25
I spoke with @twangboy about this offline. He's only able to reproduce this on windows and linux was OK. But he wasn't able to do a git bisect successfully to help narrow it down.

**Comment by twangboy** [comment] 2018-02-07 17:30
After updating to the latest Oxygen (1bd38fb3b7), I now get a stacktrace... repeatedly...:
```
[CRITICAL] Unexpected error while connecting to 104.236.251.190
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\minion.py", line 1006, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\minion.py", line 1205, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe, failed)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\salt-dev\salt\salt\minion.py", line 703, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "c:\salt-dev\salt\salt\transport\client.py", line 161, in factory
    import salt.transport.zeromq
  File "c:\salt-dev\salt\salt\transport\zeromq.py", line 32, in <module>
    import salt.transport.mixins.auth
  File "c:\salt-dev\salt\salt\transport\mixins\auth.py", line 16, in <module>
    import salt.master
  File "c:\salt-dev\salt\salt\master.py", line 56, in <module>
    import salt.key
  File "c:\salt-dev\salt\salt\key.py", line 21, in <module>
    import salt.daemons.masterapi
  File "c:\salt-dev\salt\salt\daemons\masterapi.py", line 36, in <module>
    import salt.utils.gitfs
  File "c:\salt-dev\salt\salt\utils\gitfs.py", line 91, in <module>
    import git
  File "c:\python27\lib\site-packages\git\__init__.py", line 82, in <module>
    refresh()
  File "c:\python27\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "c:\python27\lib\site-packages\git\cmd.py", line 230, in refresh
    cls().version()
  File "c:\python27\lib\site-packages\git\cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "c:\python27\lib\site-packages\git\cmd.py", line 1010, in _call_process
    return self.execute(call, **exec_kwargs)
  File "c:\python27\lib\site-packages\git\cmd.py", line 732, in execute
    **subprocess_kwargs
  File "c:\python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

**Comment by DmitryKuzmenko** [comment] 2018-02-07 18:01
I've seen all these problems. I've already done the corresponding changes and will have a PR tomorrow, I expect.

**Comment by DmitryKuzmenko** [comment] 2018-02-09 09:20
I've found no normal case that can produce the described behavior. The only idea I have is: because of some other errors minion got an error during the key load procedure and decided to generate a new keypair. Or the old keypair was removed by user or a script. Thus minion generated a new key pair that was denied by master.

I've thought something wrong with M2Crypto migration but I've tested all combinations of (2017.7, oxygen + pyCrypto, oxygen + M2Crypto) * (master, minion) and found no related issues.

#45918 fixes some windows issues and it's already merged to `oxygen.rc1`.

@twangboy could you please try to reproduce this issue against the current `oxygen.rc1` branch?
I mean take the old keypair, run and accept `2017.7` minion and then update minion to `oxygen.rc1` and run again. This case works fine for me.

**Comment by twangboy** [comment] 2018-02-10 00:03
@DmitryKuzmenko 
@rallytime 

OK... I think I'm on to something here...

The config file had the following setting:
```
pki_dir: /conf/pki/minion
```

The setting is coming from `salt-cloud`. The entire config file created by `salt-cloud` looks like this:
```
hash_type: sha256
id: <aws instance id>
ipc_mode: tcp
log_level: info
master: <ip address>
multiprocessing: false
pki_dir: /conf/pki/minion
root_dir: c:\salt
```

If you run `config.get pki_dir` on a 2017.7 minion with that setting the return is:
```
c:\salt\conf\pki\minion
```
and the keys are created in that directory

When I launched the oxygen minion, the keys were created in:
```
c:\conf\pki\minion
```
And since it's a new key, it does not match what the master has.

Once I accept the key on the master, the results of `config.get pki_dir` are:
```
/conf/pki/minion
```

So, it leads me to believe that oxygen isn't prepending `root_dir` to `pki_dir` in the same way that the 2017.7 minion does.

According to the docs (https://docs.saltstack.com/en/latest/ref/configuration/minion.html#root-dir) The root_dir is supposed to be prepended to the values for `pki_dir`, `cachedir`, `log_file`, `sock_dir`, and `pidfile`.

So, I checked `cachedir`, `log_file`, `sock_dir`, and `pidfile` and they look correct. But, when I specifically defined those values to their defaults in the minion config, then they behaved in the same way as `pki_dir`. The problem only occurs if the values are specifically configured in the minion config.

So, it's a different issue than I originally thought.

**Comment by DmitryKuzmenko** [comment] 2018-02-10 06:31
Awesome finding @twangboy !

**Comment by DmitryKuzmenko** [comment] 2018-02-12 10:51
Ok. The behavior change is introduced by PR #41281.
The sensible change is a fix for the logic case that prevents prepending of the root dir to absolute paths set in config. There was a bug in that logic where check for an absolute path was done against the key (i.e. `pki_dir`) instead of the value (`/conf/pki/minion`).

Buggy line is here: 
https://github.com/saltstack/salt/pull/41281/files#diff-0ddbe12a41fee1a8e552b35086f918ddL2082
Fixed line is here:
https://github.com/saltstack/salt/pull/41281/files#diff-0ddbe12a41fee1a8e552b35086f918ddR2099

So now it works as expected: if you set up `pki_dir` as `/conf/pki/minion` you'll get exactly this dir in the root of the current drive on windows: `C:\conf\pki\minion`
If you want to set that dir up inside of the salt `root_dir` your have to set `pki_dir` to a relative value `conf/pki/minion`. In this case you'll get `C:\salt\conf\pki\minion`

**Comment by rallytime** [comment] 2018-02-12 21:01
@DmitryKuzmenko This was reopened because after some investigation, we need to config gate the behavior change. Just wanted to let you know why this was opened and the the assignees were changed.

**Comment by DmitryKuzmenko** [comment] 2018-02-13 10:49
@rallytime Got it. Thank you!

**Closed** 2018-02-13 14:00 UTC
Labels: Bug, Fixed Pending Verification, High Severity, P1, Windows, oxygen.rc1
