### ISSUE TITLE
[state.dockerio] docker.run TypeError: run() argument after ** must be a mapping, not str

### ISSUE THREAD

**Issue by MarkusMuellerAU** [saltstack/salt#12003] opened 2014-04-15 13:10 UTC
Getting the following error running state.highstate
```
----------
          ID: /reload.sh
    Function: docker.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1371, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerio.py", line 548, in run
                  return drun(**cmd_kwargs)
              TypeError: run() argument after ** must be a mapping, not str
     Changes:
```
I am trying to run a command inside a container the following way:

```
/reload.sh:
    docker.run:
        - cid: f56154a814f1ecd6961b6314c589a5765e15ed8e85567be399982d1b3efa324c
        - watch:
          - file: /config.cfg
```

The documentation http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html suggest doing it the following way:
```
/finish-install.sh:
    docker.run:
        - container: mysuperdocker
        - unless: grep -q something /var/log/foo
        - docker_unless: grep -q done /install_log
```
Whereas the syntax at http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html#salt.states.dockerio.run only mentions a cid, not a container argument.

**Comment by munhitsu** [comment] 2015-02-25 17:42
@rallytime problem is back

salt 2014.7.2
docker-py 1.0.0
docker 1.4.1

Currently run should have been implemented using docker exec


Plus webpage documentation is misleading saying that one should go for:
```yaml
/finish-install.sh:
  docker.run:
    - container: mysuperdocker
```

while is should have been (cid)
```yaml
/finish-install.sh:
  docker.run:
    - cid: mysuperdocker
```

**Comment by rallytime** [comment] 2015-02-25 17:52
Thanks for letting us know. I've re-opened the issue. Thanks!

**Comment by tkent-xetus** [comment] 2015-04-21 15:38
+1 I'm also running into the `NotImplementedError` with 2014.7.4. In case anybody else happens across this issue, a fairly straightforward alternative is something like:

```
mypostsetupcmd:
  require:
    - docker: some-docker-running-state
  cmd.wait:
    - name: >
      docker exec {{ container_name }}
      your commands here…

    - watch: 
      - docker: some-docker-installed-state 
```

**Comment by terminalmage** [comment] 2015-04-21 16:18
Looking at dockerio.py, the only way that an ``ExecutionDriver`` of "native-0.2" would not be supported is if ``nsenter`` is not installed on the minion. ``nsenter`` is usually included with the "util-linux" package. Can you run ``salt <minion_id> cmd.run_all 'which nsenter'`` (replacing **<minion_id>** with the minion ID of the affected host)? If there is no stdout in the return, and the retcode is not 0, you don't have nsenter installed and that is why the failure is happening. In that case, installing util-linux (or whatever provides ``nsenter`` on your platform) should be all you need to do to get this working.

For what it's worth, in my full rewrite of Salt's docker support (see [here](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerng.html#executing-commands-within-a-running-container)), docker-exec is used for Docker 1.3 and later.

**Comment by terminalmage** [comment] 2015-04-21 16:28
I've submitted https://github.com/saltstack/salt/pull/22898 to improve the error message when nsenter is not available.

**Comment by rallytime** [comment] 2015-04-21 17:22
I have cleaned up the example in the documentation to use the correct `cid` kwarg (instead of `container`) for the `docker.run` state example.

With the helpful nsenter check from @terminalmage in his pull request, as well as with this documentation clean up, I think this one is now resolved again. Thoughts from @munhitsu or @tkent-xetus?

**Comment by tkent-xetus** [comment] 2015-04-21 20:52
@terminalmage 

Thank you very much for that quick reply! I didn't even think I could missing be a dependency, sorry for not checking first. Our OS (Ubuntu 14.04) doesn't happen to include `nsenter` with util-linux, but I went ahead and installed it manually.

@rallytime 

Thanks for patching up the docs, and sorry for missing your earlier comment around `nsenter`! I can confirm that docker.run works in my case. Here's the relevant parts of our setup if anybody ever needs to reference it:

 - ubuntu 14.04 (w/nsenter manually installed) 
 - salt 2014.7.4
 - docker 1.5.0

However, I still can't use it without still throwing in a little `docker exec` statement due to #17088

**Comment by rallytime** [comment] 2015-04-21 20:55
@tkent-xetus Awesome! Thanks for verifying everything. Since this particular issue has had all of it's pieces patched up and there is already another bug open for the `docker exec` part, can we close this issue up again?

**Comment by tkent-xetus** [comment] 2015-04-21 20:59
@rallytime I would say so!

**Comment by rallytime** [comment] 2015-04-21 20:59
Awesome! Thanks!

**Closed by rallytime** 2015-04-21 20:59 UTC
Labels: Bug, Documentation, Fixed Pending Verification, High Severity, P4, State Module
