### ISSUE TITLE
salt-minion can't restart itself

### ISSUE THREAD

**Issue by ozgurakan** [saltstack/salt#5721] opened 2013-06-25 16:53 UTC
Hi,

When I use salt service module or a watch statement on minon configuration file to restart salt-minion service, it ends up running two instances which breaks the communication between master and minion. (I recognized that PID is different after restart command)

This is required in order to be able to do mass changes on minions like editing mine configuration.

Below you can see how it behaves;

```
[root@mar-pre-ord-web-03 marconi]# ps -fe|grep salt
root     21507     1  7 16:43 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion -d

root@salt01:# salt mar-pre-ord-web-03 service.restart salt-minion

[root@mar-pre-ord-web-03 marconi]# ps -fe|grep salt
root     21583     1  1 16:44 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion -d
root     21601     1 25 16:44 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion -d
```

This was the sls formula, which also doesn't work.

```
salt-minion:
  pkg:
    - installed
    - name: salt-minion
  file:
    - managed
    - name: /etc/salt/minion
    - template: jinja
    - source: salt://common/files/minion.jinja
    - require:
      - pkg: salt-minion
  service:
    - running
    - enable: True
    - require:
      - pkg: salt-minion
    - watch:
      - file: salt-minion
```

test with salt-call

```
[root@mar-pre-ord-web-03 marconi]# ps -fe|grep salt
root     22690     1  2 16:59 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion -d
root     22755  2229  0 17:00 pts/0    00:00:00 grep salt
[root@mar-pre-ord-web-03 marconi]# salt-call  service.restart salt-minion
[INFO    ] Configuration file path: /etc/salt/minion
[INFO    ] Executing command '/sbin/runlevel' in directory '/root'
[INFO    ] Executing command '/sbin/chkconfig --list' in directory '/root'
[INFO    ] Executing command '/sbin/service salt-minion restart' in directory '/root'

^C (hangs here)
Exiting gracefully on Ctrl-c
[root@mar-pre-ord-web-03 marconi]# ps -fe|grep salt
root     22788     1 19 17:00 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion -d
root     22821  2229  0 17:00 pts/0    00:00:00 grep salt
```

If I restart salt-minion on the server it works fine.

```
[root@mar-pre-ord-web-03 marconi]# ps -fe|grep salt
root     22253     1 18 16:56 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion -d

[root@mar-pre-ord-web-03 marconi]# service salt-minion restart
Stopping salt-minion daemon:                               [  OK  ]
Starting salt-minion daemon:                               [  OK  ]

[root@mar-pre-ord-web-03 marconi]# ps -fe|grep salt
root     22302     1 38 16:56 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion -d
```

**Comment by I3olle** [comment] 2015-02-24 10:31
I know this topic is from 2013 but the bug still doesn't seem to be fixed? Because my minions won't restart either when being told so by the master.

master
```
[root@master]# salt-call --versions-report
           Salt: 2015.2.0rc1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

minion
```
[root@minion]# salt-call --versions-report
           Salt: 2014.1.10
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 14.3.1
            ZMQ: 3.2.4
```

As you can see the masters and minions ZMQ are both 3+. I just get the message
```
    Minion did not return. [No response]
```

**Comment by basepi** [comment] 2015-02-25 19:10
@I3olle What command did you run to restart the minion?

**Comment by I3olle** [comment] 2015-02-26 09:55
I ran
``` 
salt 'minion_id' cmd.run "service salt-minion restart"
```
Is there a better, by salt implemented, method?

**Comment by thedrow** [comment] 2015-02-26 11:17
You can use the [service module](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.service.html#salt.modules.service.restart)

**Comment by I3olle** [comment] 2015-02-26 12:34
Thank you @thedrow. I ran 
```
root@master_id ~ $ salt 'minion_id' service.restart salt-minion
minion_id:
    Minion did not return. [No response]
```

It doesn't seem to change the outcome though

**Comment by bean5** [comment] 2015-12-18 16:55
@I3olle using salt to restart a minion's salt-minion service is probably not returning because, well, it restarted the salt-minion, so it dropped the connections. I heard that this can make minions stop connecting to the master.

So better to do something like `for i in $(sudo salt-key | grep -); do echo ${i}; sudo salt ${i} cmd.run "sudo service salt-minion restart";  done`.

**Comment by dr4Ke** [comment] 2015-12-24 09:14
I'm hitting this "bug" too. So I have some thoughts on this.

What's is the current expected behavior?

What about adding a specific state/module to trigger a salt-minion restart after the entire job execution?
It would just output a "changes: salt-minion will be restarted after this job execution", continue the job execution, returns the job status to the master, and only then, the minion restart itself.

Or, salt-minion could work as `sshd` do: a new process is created to execute the current job, and it kills itself only at the end of the job. A salt-minion restart would not touch existing job processes and not break minion-master communication. I think it's more difficult to do, but more elegant.

**Comment by vutny** [comment] 2015-12-24 10:18
@dr4Ke I found that doing like this:
```
salt '*' at.at 'now + 1 minute' 'service salt-minion restart' tag=salt-restart
```

is the most reliable way to restart minions. But only when you have (or want to have) `atd` installed everywhere.

**Comment by Vye** [comment] 2015-12-25 01:59
I had success using a supervisor like systemd or [supervisord](http://supervisord.org/).

**Comment by dragon788** [comment] 2016-02-18 02:42
Using atd or anacron or a sleep 300 is a good way to do it on Linux, and on Windows using a scheduled task works pretty well. I also like somebody's suggestion of using salt-call --local service.restart salt-minion as that uses salt but salt-call doesn't require the service or communication with the master.

**Comment by vutny** [comment] 2016-02-22 15:04
This is a long living issue, but it's also some kind of well-known limitation of Salt.
We got it covered in documentation: https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-daemon-using-salt
@ozgurakan @basepi I believe this issue could be closed.

**Comment by basepi** [comment] 2016-02-22 19:14
The reason that we have never closed this is because it would be useful if we could harden the restart routines such that a minion could restart itself without `at` or similar.

**Comment by vutny** [comment] 2016-02-23 07:45
@basepi I see that we have at least couple of duplicates for this issue: #18835 #7997.
Maybe it would be nice to keep just a single issue relevant for the topic?

**Comment by basepi** [comment] 2016-02-24 04:49
@vutny #18835 has a different underlying issue. The restart is just a workaround. I commented on #7997 to see if anyone thinks it should remain open.

**Comment by sjmh** [comment] 2016-04-15 18:37
This should be be doable easily enough now with cmd.run-bg from #6691.

Tested this on CentOS 6 and worked fine:

```
salt myminion cmd.run-bg 'sleep 10; service salt-minion restart'
```

**Comment by cachedout** [comment] 2016-04-15 18:38
Take a look at something we just merged a few minutes ago: https://github.com/saltstack/salt/pull/32593

**Comment by sjmh** [comment] 2016-04-15 18:41
@cachedout - nice! Will that make it in time for Boron or is that going to have to wait for a point release?

**Comment by cachedout** [comment] 2016-04-15 18:50
That's in develop right now, so it's scheduled for Cabon. I'd be willing to consider a backport. Is it something important for you?

**Comment by sjmh** [comment] 2016-04-15 18:53
@cachedout - With the workaround via cmd_bg which is in Boron, we won't need a backport.

**Comment by cachedout** [comment] 2016-04-15 18:53
@sjmh Sounds good. Thanks.

**Comment by oliver-dungey** [comment] 2016-08-19 16:02
@ozgurakan have you experimented with the minion config parameter `master_tries`? If you set it to -`1` it should retry connecting infinitely rather than giving up on first attempt and becoming a dead minion (if I've understood the documentation properly).

**Comment by Trouble123** [comment] 2016-08-27 23:51
Hi, i had been trying to restart a windows minion for ages, and finally worked out a way to get it to work everytime:

salt '*' cmd.run_bg 'Restart-Service salt-minion' shell=powershell

**Comment by wu0407** [comment] 2016-09-18 10:37
@Trouble123 but not work for linux,it return
Minion did not return. [Not connected]

**Comment by vutny** [comment] 2016-09-29 07:51
There is a universal recipe for all platforms supported by Salt:
```
salt '*' cmd.run_bg 'salt-call --local service.restart salt-minion'
```

It should work on Windows too even without `shell=powershell` parameter, as I figured out from the docs.
Could somebody confirm?

**Comment by cachedout** [comment] 2016-09-29 07:52
If that does work, we should definitely wrap it up into its own exec module function.

**Comment by vutny** [comment] 2016-09-29 08:13
@cachedout What about the changes in PR #32593? I think its possible to specify `salt-call --local service.restart salt-minion` as the `minion_restart_command` command and make it default. But again, not sure if that will work on Windows.

At least, for now we can update the [FAQ](https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-daemon-using-salt) for `2016.3` with better recipe.

**Comment by smarsching** [comment] 2017-03-05 18:19
@vutny I can confirm that your solution works fine on Ubuntu 16.04 LTS and on Windows Server 2012 R2 with one small exception: On Windows, the complete path to `salt-call` has to be specified. This is strange because `C:\salt` is in the `path` grain, but maybe `cmd.run_bg` does not inherit this path.

Anyway, I think that the solution proposed by @vutny is the one which works best on most platforms and thus the FAQ should be updated accordingly.

I use the following logic for triggering a restart from an SLS file:
```
minion_config:
  # The logic for updating the minion's configuration goes here...

minion_restart:
  module.run:
    - name: cmd.run_bg
{% if grains['os'] == 'Windows' %}
    - cmd: 'C:\salt\salt-call.bat --local service.restart salt-minion'
{% else %}
    - cmd: 'salt-call --local service.restart salt-minion'
{% endif %}
    - onchanges:
      - file: minion_config
```

**Comment by vutny** [comment] 2017-03-10 08:56
@smarsching Thanks for the feedback! This is valuable information.
Just to be more precise, could you please tell with which exact Salt version you have tested your SLS?

In the meanwhile I will try to come up with PR to update FAQ according to your comment.

**Comment by smarsching** [comment] 2017-03-10 08:59
@vutny Sure, I tested it with version 2016.11.3.

**Comment by vutny** [comment] 2017-03-10 11:07
@smarsching Thanks, one more question: maybe do you use some `sleep` command before actually restarting a Minion? Because on Linux sometimes Salt performs to fast (:smile:) and restarts the service before the Minion is to be able to report back to the Master. That's why I put `sleep 10; ` before doing `salt-call ...`. I wonder how to put something like this to the Windows command.

**Comment by smarsching** [comment] 2017-03-10 14:42
@vutny I did not have to add a sleep command (it simply worked correctly without it), but if you want to do some thing similar to `sleep 10; salt-call --local service.restart salt-minion` on Linux, the closest thing on Windows is `ping -c 10 127.0.0.1 >nul: & C:\salt\salt-call.bat --local service.restart salt-minion`.

**Comment by vutny** [comment] 2017-03-10 14:42
Ah, never mind, I figured out that we don't need any kind of "sleep" or "timeout". It appears that on some systems (I've tested on CentOS7) wrapping `cmd.run_bg` with `module.run` doesn't work in way we want.
Instead, I've used `cmd.run` *state* function with `bg` argument. That works like a charm.

All the tricks have been assembled in PR #39952. But it would be great to have a single function which just hide all the complexities between systems, SaltStack is good at this :smile: 

I will try this later on:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.minion.html#salt.modules.minion.restart
It should support custom installations, virtualenvs and looks system-agnostic.

@smarsching If you could evaluate it on Win platform, that would be much appreciated.

**Comment by smarsching** [comment] 2017-03-13 09:18
@vutny Sure, if you provide an updated version of `minion.restart`, I can certainly give it a try on Windows.

**Comment by vutny** [comment] 2018-03-21 16:01
I have tested Salt Minion "self-restarting" with `2016.11.8` and it works quite nice even without ``--local`` option:
```bash
$ sudo salt-call -l debug service.restart salt-minion
...
[DEBUG   ] LazyLoaded service.restart
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command ['systemctl', 'status', 'salt-minion.service', '-n', '0'] in directory '/root'
[DEBUG   ] stdout: * salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-01-23 09:08:19 UTC; 1 months 26 days ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 31 (salt-minion)
   CGroup: /docker/7661046ac38e9413cb86a6d0c1292c9f6e58e00bfc6c7bdaf9e5b084676547db/system.slice/salt-minion.service
           |-  31 /usr/bin/python /usr/bin/salt-minion
           |-1441 /usr/bin/python /usr/bin/salt-minion
           `-1543 /usr/bin/python /usr/bin/salt-minion
[INFO    ] Executing command ['systemctl', 'is-enabled', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: enabled
[DEBUG   ] Service 'salt-minion' is not masked
[INFO    ] Executing command ['systemd-run', '--scope', 'systemctl', 'restart', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: Running scope as unit run-7123.scope.
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'c7-minion', 'tcp://172.20.0.2:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'c7-minion', 'tcp://172.20.0.2:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    True
```

This SLS always give success:
```
test:
  test.succeed_with_changes

salt-minion:
  cmd.run:
    - name: salt-call service.restart salt-minion
    - bg: True
    - onchanges:
      - test: test
```

The `minion.restart` function seems does slightly different job and does not applicable for system init service definitions which come from SaltStack's packages.

**Comment by vutny** [comment] 2018-03-22 08:18
As well, `salt-minion` is able to restart the `salt-master` the same way!

**Comment by rallytime** [comment] 2018-03-27 14:38
With the most recent doc changes explaining the conversation above, I think this is finally resolved. I'll close this. Thanks all!

**Closed by rallytime** 2018-03-27 14:38 UTC
Labels: Bug, Execution Module, High Severity, P1, Platform
