### ISSUE TITLE
Error in yumpkg salt-2016.11

### ISSUE THREAD

**Issue by owengo** [saltstack/salt#44271] opened 2017-10-25 08:06 UTC
### Description of Issue/Question
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1765, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1705, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/states/pkg.py", line 1440, in installed
    **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/yumpkg.py", line 1233, in install
    if re.match('kernel(-.+)?', name):
  File "/usr/lib64/python2.6/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

THE FIX:
=> /usr/lib/python2.6/site-packages/salt/modules/yumpkg.py line 1233:

                 else:
                        if re.match('kernel(-.+)?', name):
=>
                 else:
                        if re.match('kernel(-.+)?', pkgname):

### Setup
centos6/7, salt 2016.11

### Steps to Reproduce Issue
state which forces yum package versions for kernel

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.8

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

minion is centos 6

THE FIX:
=> /usr/lib/python2.6/site-packages/salt/modules/yumpkg.py line 1233:

                 else:
                        if re.match('kernel(-.+)?', name):
=>
                 else:
                        if re.match('kernel(-.+)?', pkgname):

**Comment by owengo** [comment] 2017-10-25 08:11
the source file is in:
https://github.com/saltstack/salt/blob/develop/salt/modules/yumpkg.py

sorry I do not make a PR

**Comment by rossengeorgiev** [comment] 2017-10-25 09:46
This is duplicate of #44150

**Comment by owengo** [comment] 2017-10-25 10:06
ok sorry I did not spot the duplicate

**Closed** 2017-10-25 10:06 UTC
