### ISSUE TITLE
Mine.send does not work for alias functions

### ISSUE THREAD

**Issue by enver** [saltstack/salt#34581] opened 2016-07-11 12:13 UTC
### Description of Issue/Question

Mine.send does not work for alias functions. It always returns false.
### Setup

```
mine_functions:
  grains.items: []
  alias.test:
    - mine_function: grains.items
```

After restarting minion (deploy) I can get values from mine with:
`# salt deploy mine.get deploy grains.items`
`# salt deploy mine.get deploy alias.test`

yet executing mine.send function always fails on alias function:

```
# salt deploy mine.send grains.items
deploy:
    True
```

```
# salt deploy mine.send alias.test
deploy:
    False
```
### Steps to Reproduce Issue

Add 2 mine functions: 

```
mine_functions:
  grains.items: []
  alias.test:
    - mine_function: grains.items
```

Restart minion `# service salt-minion restart`
Run mine.send on booth functions: `# salt deploy mine.send grains.items` and `# salt deploy mine.send alias.test`
Result: mine.send fails on alias function.

Could not find anything useful in debug logs.
### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.20.0
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

Master and minion running on same machine and same version of salt.

**Comment by Ch3LL** [comment] 2016-07-11 20:26
@enver looks like i'm able to replicate this issue back to 2015.5 branch. Looks like we need to get this fixed up. Thanks

**Comment by bitskri3g** [comment] 2018-10-13 21:54
Just want to comment that this is still broken on 2018.3.2

```
{% set hostname = data['path'].split('/') %}

testing reactor:
  local.mine.send:
    - tgt: 'pxe'
    - arg:
      - file.read
      - /var/www/html/pending_hosts/{{ hostname[5] }}
```

works

```
{% set hostname = data['path'].split('/') %}

testing reactor:
  local.mine.send:
    - tgt: 'pxe'
    - arg:
      - get_pending_host_{{ hostname[5] }}
      - mine_function: file.read
      - /var/www/html/pending_hosts/{{ hostname[5] }}
```

Does not.  No errors are printed in debug mode, but the mine is never updated in the latter case.

**Comment by aplanas** [comment] 2019-05-14 13:50
Confirmed in develop branch too

**Comment by samilaine** [comment] 2019-06-28 13:13
If I am not mistaken, the current behaviour is consistent with [the documentation](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mine.html#salt.modules.mine.send).

Saying "Send a specific function to the mine." doesn't, I think, means that an alternative name for the entry in the mine should be read from the pillar instead of using the function name as the key or taking the alternative name as a command line parameter.

However, the documentation seems to show that the alternative name can, and should, be given as a command line parameter. For the second example in the documentation, `salt '*' mine.send eth0_ip_addrs mine_function=network.ip_addrs eth0`, shows how to define an alias on the command line.

For example, running `salt '*' mine.send fun_alias mine_function: grains.get id` produces an identical entry in the mine than would results when with the pillar below is used together with 'mine.update':

```
mine_functions:
  fun_alias:
    - mine_function: grains.get
    - id
```

Now the obvious question is: Is the documentation correct?

If the documentation is correct, then I think there isn't any need to change `salt/modules/mine.py`.

Should the documentation be in error, then the first step to take would be to write tests which correctly fail with function aliases defined in pillars with the current code (of `salt/modules/mine.py`). 

After a quick glimpse over the source code, writing tests to cover this use case appears quite a bit easier than coming up with a non-ugly solution in `salt/modules/mine.py` to pass those tests. That's not an argument against a correction, but an argument for double checking that a correction is actually needed.

**Comment by github-abcde** [comment] 2020-07-17 15:23
I believe this issue can be closed.
The function aliasing feature is there to define a more user-friendly alias to store the results from a salt function with, rather than potentially complex and long function names. It is no more than a label for the data stored in the mine for easy retrieval.
It is not meant as a persistent alias for a specific salt function.
Besides that, `mine.send` does not look at the current `mine_functions`-configuration at all (and I feel it should not need to) in order to send new data into the mine. 
On the other hand, `mine.update`, which updates information already in the salt mine *does* work with the alias.

**Comment by bitskri3g** [comment] 2020-07-17 17:35
It's sort of implied from the earlier comments that this used to work though, and I can see plenty of use-cases where not having to statically/permanently define mine function aliases can be extremely useful, particularly during orchestration.  Being able to ```mine.send``` ephemeral bits of data to the mine for use during orchestration runs lets you synchronize minions in a lightweight manner without having to globally configure ```mine_functions```, which can get onerous, particularly if your ```mine_functions``` config would need to be dynamic and change based on other goings-on in your environment.

If this was never intended to work, it should be added as a feature request.  If it was intended to work and now doesn't this should stay open IMHO.

**Comment by github-abcde** [comment] 2020-07-18 10:06
@bitskri3g Thank you for your response :)

The implication that it used to work made me go through the code history of `salt/modules/mine.py` and look at the `send`-function. Ch3ll mentions that she can replicate the problem back to 2015.5. However, looking back at the version right before that (2014.7) shows that the ability to define aliases does not exist in 2014.7 and was only introduced in 2015.5. This leads me to conclude that the implication that it used to work like this at one time is false. From the moment on aliasing was possible, it never worked like this.

As for the use-case you describe where the freedom to define aliases as you go is greatly appreciated: Isn't this already the case? You can define an alias for mine data using `mine.send` (together with the mine_function and the required args/kwargs for that mine_function). If you do this at the start of an orchestration, later calls to `mine.update` will automatically pick up on this.
It is only when you want to use `mine.update` to update one specific alias that this functionality seems to be absent. However, if you somehow manage to store the dynamically created instance of `mine_functions` somewhere (perhaps even in the salt mine itself), you can pass this to `mine.update` and it will update exactly that.
Another thing that comes to mind: the function alias needs to be defined somewhere, and this is only done in the `mine_functions`-definition. The details on which function and which arguments are linked to an alias is not stored in the salt mine itself, so without providing the details of the desired function, `mine.send` would not be able to ascertain what to do.

**Comment by MKLeb** [comment] 2023-08-29 16:44
Closing due to age and there seems to be some agreement that this is expected behavior.  If there is still worry that this is not expected behavior, please open a new issue.

**Closed by MKLeb** 2023-08-29 16:44 UTC
Labels: Execution-Module, Bug, severity-medium, Confirmed, Platform
