### ISSUE TITLE
Stacktrace with salt-cloud on AWS

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#45646] opened 2018-01-23 20:14 UTC
### Description of Issue/Question
When creating an instance on AWS using salt-cloud, the following error is produced. I assume this is related to the transition to `unicode_literals`.
```
[ERROR   ] There was a profile error: descriptor 'lower' requires a 'str' object but received a 'unicode'
Traceback (most recent call last):
  File "/root/salt/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/root/salt/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/root/salt/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/ec2.py", line 2597, in create
    data, vm_ = request_instance(vm_, location)
  File "/root/salt/salt/cloud/clouds/ec2.py", line 2015, in request_instance
    sigver='4')
  File "/root/salt/salt/utils/aws.py", line 435, in query
    method, endpoint, params, prov_dict, aws_api_version, location, product, requesturl=requesturl
  File "/root/salt/salt/utils/aws.py", line 259, in sig4
    for header in sorted(new_headers.keys(), key=str.lower):
TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'
```
### Setup
Given a cloud profile named `aws_win_2012r2` that defines a 2012r2 ami on Amazon... I believe this will probably fail with any profile... but it was discovered while trying to create a Windows VM.

### Steps to Reproduce Issue
Create an amazon image Windows image with the following command:
```
salt-cloud -l debug -p aws_win_2012r2 slee_winsrv2012r2_test
```
Observe the error

### Versions Report
Head of Oxygen branch
Ubuntu 14 master

**Comment by gtmanfred** [comment] 2018-01-23 20:21
This is a duplicate of #45550

**Closed by gtmanfred** 2018-01-23 20:21 UTC
