### ISSUE TITLE
Inconsistent Pillar Data Behavior and Availability

### ISSUE THREAD

**Issue by praveenkulkarni22** [saltstack/salt#55487] opened 2019-12-02 13:45 UTC
### Description of Issue
The Pillar Data availability reacts differently when i try to access them in different states using `include` and `module.run` salt commands. 

### Setup
**setup.sls**
```
include:
  - pkg_install.sls

```
**pkg_install.sls**
```
{% set pdata = salt['pillar.get']('db_pgs') %}
chk_pkgi:
  file.managed:
    - name: /tmp/chk_pkgi.txt
    - contents: |
        {{pdata|tojson}}
```
In this Scenario, there are no issues. I am able to access the pillar data and it gets loaded to the pdata variable. However, this is not the case when i change my `setup.sls` to `module.run `as below:

**setup.sls**
```
{% set pdata = salt['pillar.get']('db_pgs') %}
s_pgs_pkgs_install:
  module.run:
    - state.sls:
      - pkg_install
      - pillar: {{pdata|tojson}}
```

In pkg_install the `pdata` is empty. It does not load though I am passing it as a argument to the state file using `pillar: {{pdata|tojson}}`. The pillar data should be available through out the run irrespective of how the states are called.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.12.14-95.24-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by sagetherage** [comment] 2020-01-22 19:31
@garethgreenaway can you triage this today or tmr, please?

**Comment by praveenkulkarni22** [comment] 2020-01-23 14:46
Any updates or specifc reasons on this pecilur behaviour of Pillars

**Comment by sagetherage** [comment] 2020-02-24 15:50
@garethgreenaway can you answer @praveenkulkarni22 question, here?

**Comment by garethgreenaway** [comment] 2020-03-10 16:20
@praveenkulkarni22 Apologies for the delay.  I wasn't able to reproduce this one.  Can you provide an example of what the pillar data looks like?  Also are you able to upgrade to one of the later version of 2019.2 or the 3000 release to see if either of those resolves the issue for you?  Thanks!

**Comment by praveenkulkarni22** [comment] 2020-03-14 12:01
@garethgreenaway no problem on the delay. But, the issue still persists and I have not found a solution yet. The Pillar is passed as command line argument to the state file and they behave differently when I use `include` and `module.run`. Please find a example below:

Here is the salt call from Master with pillar passed as command line argument:

`salt '*' state.apply setup pillar='{"db_type": "postgresql"}'`

If I use include in my `setup.sls` as detailed below

```
include:
  - pkg_install.sls
```

and I am able to get the details of the pillar when I try to access the pillar in the `pkg_install.sls` as below: 

```
{% set pdata = salt['pillar.get']('db_type') %}
chk_pkgi:
  file.managed:
    - name: /tmp/chk_pkgi.txt
    - contents: |
        {{pdata|tojson}}
```
In this Scenario, there are no issues. I am able to access the pillar data and it gets loaded to the pdata variable and the details are written to `/tmp/chk_pkgi.txt` file. However, this is not the case when i change my `setup.sls` to `module.run` as below:

```
{% set pdata = salt['pillar.get']('db_type') %}
s_pgs_pkgs_install:
  module.run:
    - state.sls:
      - pkg_install
      - pillar: {{pdata|tojson}}
```

In `pkg_install` the pdata is empty and the details are not written to `/tmp/chk_pkgi.txt`. It does not load though I am passing it as a argument to the state file using `pillar: {{pdata|tojson}}`. The pillar data should be available through out the run irrespective of how the states are called. Why is this inconsistent behaviour between `include` and `module.run`

**Comment by garethgreenaway** [comment] 2023-08-28 18:26
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.

**Closed by garethgreenaway** 2023-08-28 18:26 UTC
Labels: Pending-Discussion
