### ISSUE TITLE
salt-call state.show_states gives error on 2019.2.1-1

### ISSUE THREAD

**Issue by verhage** [saltstack/salt#54758] opened 2019-09-26 07:48 UTC
### Description of Issue
I just updated my salt-minion on CentOS 7 to version 2019.2.1-1.el7. Now when I run `salt-call state.show_states`, I get the following error;

```
Passed invalid arguments: string indices must be integers.

Usage:

    Returns the list of states that will be applied on highstate.

    CLI Example:

    .. code-block:: bash

        salt '*' state.show_states

    .. versionadded:: 2019.2.0
```

On a minion still running the previous version (2019.2.0-1.el7) everything works fine.

### Setup
salt-master and minion both running on CentOS 7 7.6.1810, salt version 2019.2.1-1.el7

### Steps to Reproduce Issue

Update minion to latest version and call state.show_states:

```
yum update
salt-call state.show_states
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.27.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by waynew** [comment] 2019-09-26 16:52
Hi @verhage thanks for the report - I'm trying to reproduce this, and it's not failing for me yet.

Question: do you have any Jinja in your states?

**Comment by verhage** [comment] 2019-09-26 17:27
Yes, we use Jinja templates in almost every state. I'll try and see if I can reproduce this in Vagrant.

**Comment by Ch3LL** [comment] 2019-09-26 17:32
im able to replicate this @waynew working on bisecting it now

**Comment by Ch3LL** [comment] 2019-09-26 17:38
looks like this is also failing on 2019.2.0. and `state.show_states` was added in 2.0

**Comment by Ch3LL** [comment] 2019-09-26 17:46
I found the reason mine is failing is I have an sls defined in my `top.sls` file that does not exist. Looking into a fix to handle this.

**Comment by verhage** [comment] 2019-09-26 17:52
I just figured it out too, there was a typo in one of the states in top.sls

**Comment by Ch3LL** [comment] 2019-09-27 14:11
re-run full all

**Comment by Ch3LL** [comment] 2019-09-27 14:11
Fixed in https://github.com/saltstack/salt/pull/54785

**Closed** 2019-10-21 16:13 UTC
Labels: Bug, Confirmed, Fixed Pending Verification, Medium Severity, P4
