### ISSUE TITLE
run multiple salt-api instances using salt-api command.

### ISSUE THREAD

**Issue by kstreee** [saltstack/salt#31194] opened 2016-02-13 02:25 UTC
I installed the develop branch version of saltstack using setup.py in github repository.
Then try to run several salt-api using following ```master``` configuration file.

```
worker_threads: 10
timeout: 120
auto_accept: True

a:
  port: 30001
  disable_ssl: True

b:
  port: 31001
  disable_ssl: True

rest_cherrypy:
  port: 32001
  disable_ssl: True
```

To test it, I copied ```rest_cherrypy``` directory to ```a``` and ```b``` in salt/netapi, then install saltstack it using setup.py.
But when we run the command ```salt-api``` after run ```salt-master```, only one instance among the ```a```, ```b```, and ```rest_cherrypy``` are run.
In my case, the ```b``` is only instance which is run by the command ```salt-api```.
Thus I run  ```salt-api -c /PATH/FOR/EACH/API/PRIVATE/DIRECTORY``` three times to run ```a```, ```b```, and ```rest_cherrypy``` with separated configuration directory for the each salt-api instance.

**Comment by whiteinge** [comment] 2016-02-13 09:06
Interesting. I think I can safely say you're the first person to try this. I'm curious what your use-case is.

I can't think of a reason this wouldn't work. Was there any errors or interesting log messages for the copies that did not start up?

**Comment by kstreee** [comment] 2016-02-13 21:49
No there is no error while executing the ```salt-api``` command like this way, but the salt-api command does not recognize multiple salt-api configurations. The command just run a single salt-api instance.

In our case, We use a salt stack as a low level framework to deploy and run commands for other systems.
Thus we want to separate salt-api based on purposes of api calls.
For example, one salt-api instance is used in deployment system, and another salt-api instance is used in command-running system to inspect server's status and others.
Thus we want to separate several salt-api based on it's purposes and jobs, even the jobs and works of a couple of salt-api are almost same.
running multiple salt-master based on the purpose and jobs is clear, but running multiple salt-master for same server farm  needs too much running cost for us.

If your team thinks that running multiple salt-api instances with a single ```master``` configuration file is useful, I want to try to fix the code to support invoking multiple salt-api instances in a single ```master``` configuration file when executing the ```salt-api``` command.

**Comment by whiteinge** [comment] 2016-02-14 01:12
Thanks for the explanation; that is interesting. I should rephrase: you're the first person I've heard of to run multiple rest_cherrypy instances. salt-api is definitely written to be able to start multiple netapi modules at once.

Try this:

* In your `a` and `b` copies of rest_cherrypy, edit [this line](https://github.com/saltstack/salt/blob/afdcc81/salt/netapi/rest_cherrypy/__init__.py#L39) to return a string with a unique name for each copy. E.g., `return 'rest_cherrypy_a'`.

Then in your master config make sure each configuration matches each returned string. E.g.:

```yaml
rest_cherrypy_a:
  port: 30001
  disable_ssl: True
```

Hopefully that will get multiple rest_cherrypy instances working under a single salt-api instance.

**Comment by kstreee** [comment] 2016-02-14 22:41
It works well what you advised!
Following configuration for rest_cherrypy instances works well.
```
a:
    port: 30001
    disable_ssl: True
b:
    port: 31001
    disable_ssl: True
rest_cherrypy:
    port: 32001
    disable_ssl: True
```
I think, the name of salt-api instance doesn't need to have a ```rest_cherrypy``` as a prefix.

How about change [the line](https://github.com/saltstack/salt/blob/afdcc81/salt/netapi/rest_cherrypy/__init__.py#L39) returns ```short_name```. E.g., ```return short_name```.
I know it is quite tricky and this change is not necessary to run a single salt-api instance, but it will useful to person who wants to run multiple salt-api using the ```salt-api``` command.
On the other hand, I wonder that changing the return statement to ```return short_name``` bring some side-effects.

**Comment by kstreee** [comment] 2016-02-14 22:50
It works well what you advised ( update the return statement into return NAME_OF_CHERRYPY for each copies of cherrypy instances )!
Following configuration for rest_cherrypy instances worked well.

a:
    port: 30001
    disable_ssl: True
b:
    port: 31001
    disable_ssl: True
rest_cherrypy:
    port: 32001
    disable_ssl: True
I think, the name of salt-api instance doesn't need to have a rest_cherrypy as a prefix.
However, there are some warning of it, and the warning messages are following.
```
[WARNING ] salt.loaded.int.netapi.rest_cherrypy.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the
 module 'rest_cherrypy', please fix this.
```

How about change the line returns short_name. E.g., return short_name.
I know it is quite tricky and this change is not necessary to run a single salt-api instance, but it will useful to person who wants to run multiple salt-api using the salt-api command.
On the other hand, I wonder that changing the return statement to return short_name bring some side-effects.

**Comment by kstreee** [comment] 2016-02-16 06:52
Also I found a typo at [this line](https://github.com/saltstack/salt/blob/develop/salt/netapi/rest_cherrypy/app.py#L1727). It could be ```orig_session```.

**Comment by whiteinge** [comment] 2016-02-16 17:57
> How about change the line returns short_name (E.g., return short_name).

This module is a tad out of date by Salt standards. That line should officially return the `__virtualname__` 
variable near the top of the file. Something that may be a middle ground is something like:

```python
try:
    with open('virtualname.json', 'rb') as f:
        __virtualname__ = json.load(f)['virtualname']
except:
    __virtualname__ = 'rest_cherrypy'
```

Then you could add a `virtualname.json` to each copy:

```json
{"virtualname": "othermodulename"}
```

> Also I found a typo at this line. I think that It could be orig_session.

You're right about that. At least it's a consistent typo. (^_^) It should be fixed.

**Comment by kstreee** [comment] 2016-02-17 12:53
I think, this code is appropriate way to set \_\_virtualname\_\_ for rest_cherrypy instances,
```
try :
    __virtualname__ = os.path.abspath(__file__).rsplit('/')[-2]
except:
    __virtualname__ = 'rest_cherrypy'
```

Because directory name of salt-api and salt-api instance name in ```master``` configuration file must be same to run salt-api instance.
For example, If user set salt-api instance name as ```abc``` in ```master``` configuration file, then the target salt-api instance must be located in ```.../salt/netapi/abc/``` to run it.
Thus, the \_\_init\_\_.py file what we try to fix in rest_cherrypy must be located in ```.../salt/netapi/[instance name]/__init__.py```, so the result of ```os.path.abspath(__file__).rsplit('/')[-2]``` is always ```[instance name]```.

Because of the relationship between ```master``` configuration file and location of rest_cherrypy, the above code make sense to set \_\_virtualname\_\_.

Also the rest_tornado has a [same issue to set \_\_virtualname\_\_](https://github.com/saltstack/salt/blob/develop/salt/netapi/rest_tornado/__init__.py#L8), and the above code can be used for it too. 

If you think the above code will work well for this cases, I will send a pull request for it.

**Comment by kstreee** [comment] 2016-02-17 12:54
Oh I am sorry, I had a click miss.

**Comment by whiteinge** [comment] 2016-02-18 14:35
Relabeling. Not a bug since Salt modules are not normally intended to have multiple instances.

**Comment by whiteinge** [comment] 2016-02-18 14:38
@kstreee this approach is not as explicit as the JSON file approach. But that's ok. I'll leave additional comments in your pull req.

**Closed** 2016-02-24 04:22 UTC
Labels: Core, Feature, Salt-API
