### ISSUE TITLE
Develop branch stack traces on startup on Windows

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#30486] opened 2016-01-20 23:00 UTC
On start up the following stack trace occurs:
```
[ERROR   ] Unhandled exception running mine.update
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\utils\schedule.py", line 740, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
  File "c:\salt-dev\salt\salt\utils\context.py", line 187, in __getitem__
    return self._dict()[key]
KeyError: 'retcode'
[DEBUG   ] Process manager iteration
```
The minion continues to start and seems to function correctly after the error.
This is working off the head of the develop branch:

`2015.8.0-1263-g7b88d72`

**Comment by jfindlay** [comment] 2016-01-21 19:01
This may be a duplicate of #30472.

**Closed** 2016-05-06 22:35 UTC
Labels: Bug, Core, Medium Severity, P1
