### ISSUE TITLE
Cannot match minions when using restful-api and set expr_form=nodegroup

### ISSUE THREAD

**Issue by qiangshui** [saltstack/salt#40447] opened 2017-03-31 09:50 UTC
Cannot match minions when using restful-api and set expr_form to nodegroup, but when i set expr_from to list or none,everything works fine.

Here is my nodegroups configuration:
  [root@salt salt]# vim /etc/salt/master
     
![Uploading image.png…]()

Here is a part of my python scripts:
![Uploading image.png…]()

 

  if the expr_from be set to list, minions is pass by value "g108,jenkins", it could work, but when the expr_from be set to nodegroup,minions is pass by value "group2", arise an error.
 
And when i execute "salt -N group2 state.highstate" , it can work, the nodegroup "group2" could be recongnized.

I try this way:
`curl -k http://192.168.12.16:9876 -H "Accept: application/json" -H "X-Auth-Token:cd37ab1d1e93d03bd4a0ccb5a19ccce14694533c" -d client="local" -d tgt="g108" -d expr_form="list" -d fun="state.highstate"  | python -mjson.tool,`

it works fine,but when i change expr_from to "nodegroup" and tgt to "group2",retnrn this :
{
    "return": "An unexpected error occurred", 
    "status": 500
}

Here is the logs:

2017-03-31 14:11:26,232 [salt.utils.minions][ERROR   ][30419] Failed matching available minions with noegroup pattern: group2
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/minions.py", line 649, in check_minions
    minions = check_func(expr, greedy)
TypeError: 'NoneType' object is not callable
2017-03-31 14:11:36,554 [salt.utils.minions][ERROR   ][30418] Failed matching available minions with sadf pattern: group2
Traceback (most recent call last):
 File "/usr/lib/python2.6/site-packages/salt/utils/minions.py", line 649, in check_minions
    minions = check_func(expr, greedy)
TypeError: 'NoneType' object is not callable
2017-03-31 14:11:54,008 [salt.utils.minions][ERROR   ][30419] Failed matching available minions with nodegroups pattern: group2

[root@salt saltdeploy]# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

My english is  terrible, please forgive me
@rallytime @cachedout

**Comment by qiangshui** [comment] 2017-03-31 10:15
#37742

**Comment by gtmanfred** [comment] 2017-03-31 15:19
Hrm, 

I am not seeing this error.

```
[daniel@salt ~]$  curl -sSk https://localhost:8000/ -H 'Accept: application/x-yaml' -H "X-Auth-Token: $token" -d client=local -d tgt='group1' -d expr_form='nodegroup' -d fun='test.ping'
return:
- salt.c.gtmanfred-1263.internal: true
```

```
[daniel@salt ~]$ salt-call --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

Did you restart your `salt-api` and `salt-master` after you added the nodegroup?

This should have never been a problem in 2016.11 https://github.com/saltstack/salt/pull/37763

Can you provide me with any more information?

Thanks,
Daniel

**Comment by gtmanfred** [comment] 2017-03-31 15:22
I think this is a duplicate of https://github.com/saltstack/salt/issues/37742 and should be fixed in 2016.11.3, so once you restate, if you could close this if it works.

Thanks,
Daniel

**Closed** 2017-04-07 06:40 UTC
Labels: Duplicate, Fixed Pending Verification

**Comment by qiangshui** [comment] 2017-04-07 06:46
@gtmanfred Thank you very much,I didn't restart salt-api,when I restart salt-api,nodegroup could work.Sorry for the delay of your precious time!

**Comment by gtmanfred** [comment] 2017-04-10 14:25
No worries, thanks for closing!
