### ISSUE TITLE
[2016.11.2] salt-ssh overrides mysql.user

### ISSUE THREAD

**Issue by alxwr** [saltstack/salt#39520] opened 2017-02-21 10:04 UTC
### Description of Issue/Question

`salt` uses the configured username. `salt-ssh` uses the username of the currently logged in user (`whoami`).

### Setup

```
# master.d/mysql-ext_job_cache.conf
master_job_cache: mysql
event_return: mysql

mysql.host: '192.168.1.1'
mysql.user: 'salt'
mysql.pass: 'myPassword'
mysql.db: 'salt'
mysql.port: 3306
```

### Steps to Reproduce Issue

```
% salt-ssh 'node1.*' state.highstate
[ERROR   ] MySQL returner could not connect to database: (1045, "Access denied for user 'salt-ma
ster'@'192.168.1.2' (using password: YES)")
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 606, in run
    self.returners['{0}.save_load'.format(self.opts['master_job_cache'])](jid, job_load)
  File "/usr/local/lib/python2.7/site-packages/salt/returners/mysql.py", line 314, in save_load
    with _get_serv(commit=True) as cur:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/salt/returners/mysql.py", line 251, in _get_serv
    raise salt.exceptions.SaltMasterError('MySQL returner could not connect to database: {exc}'.
format(exc=exc))
SaltMasterError: MySQL returner could not connect to database: (1045, "Access denied for user 's
alt-master'@'192.168.1.2' (using password: YES)")
[ERROR   ] Could not save load with returner mysql: MySQL returner could not connect to database
: (1045, "Access denied for user 'salt-master'@'192.168.1.2' (using password: YES)")
[WARNING ] Ignoring pillar stack template "domain-sz9i.net.yaml": can't find from root dir "/usr
/local/etc/salt/pillarstack"
[WARNING ] Ignoring pillar stack template "domain-sz9i.net.yaml": can't find from root dir "/usr
/local/etc/salt/pillarstack"
[CRITICAL] MySQL returner could not connect to database: (1045, "Access denied for user 'salt-ma
ster'@'192.168.1.2' (using password: YES)")
[CRITICAL] Could not store return with MySQL returner. MySQL server unavailable.
```

If the following line is inserted at `salt/returners/mysql.py` line 251, `_options` contains all the configured values, but a wrong username.

```
raise salt.exceptions.SaltMasterError(str(_options))
```

```
% salt-ssh 'node1.*' state.highstate
[ERROR   ] {'ssl_key': None, 'ssl_cert': None, 'db': 'salt', 'ssl_ca': None, 'host': '192.168.1.1', 'user': 'salt-master', 'pass': 'myPassword', 'port': 3306}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 606, in run
    self.returners['{0}.save_load'.format(self.opts['master_job_cache'])](jid, job_load)
  File "/usr/local/lib/python2.7/site-packages/salt/returners/mysql.py", line 315, in save_load
    with _get_serv(commit=True) as cur:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/salt/returners/mysql.py", line 251, in _get_serv
    raise salt.exceptions.SaltMasterError(str(_options))
[…]
```

**Workaround**: Set MySQL username to OS's username.

### Versions Report

```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan  3 2017, 01:35:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 10.3-RELEASE-p11
         system: FreeBSD
        version: Not Installed
```

**Comment by Ch3LL** [comment] 2017-02-22 18:57
@alxwr seems this is a duplicate of https://github.com/saltstack/salt/issues/32567. I will close this here and we can track this issue there. Thanks

**Closed by Ch3LL** 2017-02-22 18:57 UTC
