### ISSUE TITLE
salt-ssh with tty and sudo fails due to stderr output going to stdout

### ISSUE THREAD

**Issue by dr4Ke** [saltstack/salt#29667] opened 2015-12-14 14:18 UTC
Hi,
I'm using saltstack on CentOS 6. Versions:
```
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.11.2.el6.x86_64
         system: CentOS 6.5 Final
```

The `test` module is working but a lot of others don't. Even with the core `grains.get`.

The error happens when executing `test.opts_pkg`. The output is not json, and the command ends with the error `Failed to return clean data`, the output shows:
```
_edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
{
    "local": {
        "fun_args": [], 
        "jid": "20151214150601918508", 
        "return": {
[...]
```

The issue is that there is this magic string `RSTR` from `salt/client/ssh/__init__.py` left in stdout.

Now, I've done some debugging and it seems that the stderr from the virtual terminal is redirected into stdout. Thus we have the `RSTR` string twice, and it is removed only once.

It seems to be in the `saltutil.vt` code that the `stderr` is received from the `term` inside the `stdout` stream. I'll try to understand why but I'm not familiar with that.

So a quick and dirty fix would be to ignore all stdout until the last `RSTR` string found.

**Comment by jfindlay** [comment] 2015-12-15 17:42
@dr4Ke, thanks for your work on this.

**Comment by basepi** [comment] 2015-12-15 18:39
Thanks for fixing this @dr4Ke, I'm going to go ahead and close this.

**Closed by basepi** 2015-12-15 18:39 UTC
Labels: Bug, Core, Fixed Pending Verification, High Severity, P2, Salt-SSH

**Comment by dr4Ke** [comment] 2015-12-16 11:46
Thank you for merging. I'm just worry about this scenario:
The executed command outputs some lines in `stdout`, then some in `stderr`. If the outputs all go to `stdout`, we would have this in the output:
```
RSTR
stdout lines
RSTR
stderr lines
```

Then the parsing would only give the `stderr` lines, ignoring the `stdout` lines. I think we have to understand why the `stderr` is going to `stdout`. Does anyone else experience this?

To check that `stderr` was going to `stdout`, I did this change:
```
diff --git a/salt/client/ssh/ssh_py_shim.py b/salt/client/ssh/ssh_py_shim.py
index d5f5b3c..d061479 100644
--- a/salt/client/ssh/ssh_py_shim.py
+++ b/salt/client/ssh/ssh_py_shim.py
@@ -212,8 +212,10 @@ def main(argv):  # pylint: disable=W0613
 
     # Only emit the delimiter on *both* stdout and stderr when completely successful.
     # Yes, the flush() is necessary.
+    sys.stdout.write('STDOUT: ' + OPTIONS.delimiter + '\n')
     sys.stdout.write(OPTIONS.delimiter + '\n')
     sys.stdout.flush()
+    sys.stderr.write('STDERR: ' + OPTIONS.delimiter + '\n')
     sys.stderr.write(OPTIONS.delimiter + '\n')
     sys.stderr.flush()
     old_umask = os.umask(0o077)
```
Then I execute:
```
$ salt-ssh -l trace 'node' grains.get os 2>&1 | less -N
[...]
   1043 [TRACE   ] STDOUT lnxjy114.atac.local
   1044 + SUDO=
   1045 + '[' -n sudo ']'
   1046 + SUDO='sudo '
   1047 + EX_PYTHON_INVALID=10
[...]
   1207 SALT_ARGV: ['/usr/bin/python26', '/tmp/.salt_23460e_salt/salt-call', '--local', '--metadata', '--out', 'json', '-l', 'quiet', '-c',    1207 '/tmp/.salt_23460e_salt', '--', 'test.opts_pkg']
   1208 STDOUT: _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
   1209 _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
   1210 STDERR: _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
   1211 _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
   1212 {
   1213     "local": {
[...]
```

It's clear, in this output, that the `ssh_py_shim.py` writing to `stderr` is going to `stdout` in the end. I don't understand why. I think the issue is in the `saltutil.vt` code.

Maybe this case can't happen, but I don't see why it couldn't. For me, the issue is solved with my workaround, but I'm afraid others will hit this issue, or it would trigger in some other scenario.

What do you think?

**Comment by basepi** [comment] 2015-12-16 18:59
I think the problem is that the vt system can't differentiate between the two types of output, since it's creating a virtual terminal and just outputting everything from that virtual terminal. I don't know the details on the implementation, I haven't had time to explore vt. Maybe @s0undt3ch can help shed some light on why we combine the two?

**Comment by s0undt3ch** [comment] 2015-12-16 19:13
Vt differentiates stderr and stdout if told to do it. I'd need time to investigate why this is happening...

**Comment by basepi** [comment] 2015-12-16 19:24
It's certainly possible that we are misusing vt. I guess I should revisit this at some point.
