### ISSUE TITLE
branches/environments from via GitFS are only added/deleted on salt-master restart

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#20785] opened 2015-02-18 06:26 UTC
**OS:** Ubuntu 14.04.1 amd64
**Salt Master:**
```
               Salt: 2014.7.1
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.0.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: 0.9.1
```

The `gitpython` GitFS backend (others possibly too, haven't tested the `pygit` and `dulwich` backends) doesn't delete branches which have been removed from the remote in the master's cache.

```
salt-run cache.clear_all
salt-run fileserver.update
salt-run fileserver.envs sources=True
```
… still shows old branches/environments which have been deleted long ago from the remote.
This has caused quite some trouble here because I unexpectedly ran into topfile collisions etc and couldn't make sense of it, as my local clone and the remote were both clean of any collisions until I realized it's GitFS not cleaning up.

IMHO, GitFS should always have a clone which 100% reflects the state of the remote.

**Comment by terminalmage** [comment] 2015-02-18 20:24
We do have a mechanism for detecting stale refs, which is supposed to exclude them. It is probably just malfunctioning. I'll have a look, thanks!

**Comment by terminalmage** [comment] 2015-02-18 21:26
@eliasp We also cache environments for 30 seconds because the available envs are requested often, and calculating them every time they are requested was a major CPU bottleneck. Also, note that the ``cache.clear_all`` runner does not clear the fileserver cache. Can you make sure that you wait at least 30 seconds after you delete the remote branch before running the ``fileserver.envs`` runner?

**Comment by eliasp** [comment] 2015-02-19 01:31
Ok, so the problem is actually a bit different one.
Environments based on git branches are only updated when restarting the master service.

This doesn't only apply to deleting environments, but also to adding new environments.
IMHO, environment changes done by adding/deleting git branches shouldn't require a restart of the master - would you agree on this statement?

**Comment by terminalmage** [comment] 2015-02-19 01:34
I totally agree, in fact I designed it to work just the way you think it should. If it is indeed behaving in the way you are describing, then this is a regression.

**Comment by terminalmage** [comment] 2015-02-19 01:37
Can you post your git-related master config file options? Please obfuscate anything personally private, such as the URLs of the remotes. Also, please let me know which version of python you are using. For example:

```
% python -c 'import git; print(git.__version__)'
0.3.2.1
```

**Comment by terminalmage** [comment] 2015-02-19 01:48
Another question: Did you actually test a file.managed state using the new environment, or are you just basing this issue on the return data from the ``fileserver.envs`` runner? It's possible that this may just be an issue with the runner.

**Comment by eliasp** [comment] 2015-02-19 01:59
My relevant master config options:
```YAML
fileserver_backend:
  - roots
  - git
file_roots:
  base:
    - /media/volumes/salt/master/fileserver/
gitfs_remotes:
  - git@scm.institution.tld:salt-states.git
  - git@scm.institution.tld:salt-minions.git
  - git@scm.institution.tld:salt-formulas.git
  - git@scm.institution.tld:salt-localmods.git
```

GitPython version is `0.3.2 RC1` as shipped by Ubuntu 14.0.4.1

I base this not only on the output of the `fileserver.envs` runner, but started to investigate because I ran into unexpected topfile collisions (from environments/branches which I deleted quite some time ago) when applying highstates to Minions and ended up with the findings reported above.

**Comment by terminalmage** [comment] 2015-02-19 08:58
@eliasp https://github.com/terminalmage/salt/commit/0487d3aedde038ea4bf4b5aba9fcbbe0e9c3a7ef fixes this for GitPython. I'll take a look at pygit2 in the morning. Due to the way dulwich handles refs, I don't think it would be affected, but I'll be sure to test with it as well.

**Comment by eliasp** [comment] 2015-02-19 12:11
@terminalmage Thanks a lot for fixing it that quickly - works as expected!
In case you're still in the mood to do git-stuff - I also just filed a related issue (#20824) for the win_repo git support :)

**Comment by terminalmage** [comment] 2015-02-20 10:45
@eliasp A better fix for this (and for pygit2) has been submitted in https://github.com/saltstack/salt/pull/20854. This fix will be in Salt 2015.2.0.

I also added a runner to clear the fileserver cache.

**Comment by eliasp** [comment] 2015-02-20 10:51
Awesome! Thanks a lot!

**Comment by terminalmage** [comment] 2015-02-20 10:53
No prob, thanks for reporting! I'm relieved to see this fixed.

**Comment by eliasp** [comment] 2015-02-20 12:02
Although your PR is against `2015.2` I applied it here on a `2014.7.1` master.
`fileserver.update` ended up with this:
```
[ERROR   ] Git fileserver backend is enabled in master config file, but could not be loaded, are pygit2 and libgit2 installed?
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/gitfs/645f5b4f4850735183ee66ec61a4b697/update.lk'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 145, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 463, in run
    runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 234, in run
    self.opts['fun'], self.opts['arg'], self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 123, in cmd
    return self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/fileserver.py", line 104, in update
    fileserver.update(back=backend)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 330, in update
    self.servers[fstr]()
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 1091, in update
    exc_info_on_loglevel=logging.DEBUG
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 962, in _acquire_update_lock_for_repo
    yield
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 978, in wait_for_write_lock
    os.remove(filename)
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/gitfs/645f5b4f4850735183ee66ec61a4b697/update.lk'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 145, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 463, in run
    runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 234, in run
    self.opts['fun'], self.opts['arg'], self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 123, in cmd
    return self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/fileserver.py", line 104, in update
    fileserver.update(back=backend)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 330, in update
    self.servers[fstr]()
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 1091, in update
    exc_info_on_loglevel=logging.DEBUG
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 962, in _acquire_update_lock_for_repo
    yield
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 978, in wait_for_write_lock
    os.remove(filename)
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/gitfs/645f5b4f4850735183ee66ec61a4b697/update.lk'
```
The directory `/var/cache/salt/master/gitfs/645f5b4f4850735183ee66ec61a4b697/` was there, but completely empty.
Only after a `fileserver.clear_cache`, it worked again.

I wonder whether this is something others might run into when upgrading.

**Comment by terminalmage** [comment] 2015-02-20 16:51
Yes, I noticed this as well on a ``fileserver.update``. This is being caused by a recent bugfix and appears to be unrelated to my pull request, I will look into fixing it though in my pull request.

**Comment by terminalmage** [comment] 2015-02-26 05:37
Fixed in https://github.com/saltstack/salt/pull/20854.

**Closed by terminalmage** 2015-02-26 05:37 UTC
Labels: Bug, Medium Severity
