### ISSUE TITLE
[BUG] salt-api can't handle large volumes of data with msgpack > 0.5.6

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#57026] opened 2020-04-30 21:20 UTC
**Description**
After upgrading python-msgpack, salt was unable to transfer large volumes of information via salt-api due to msgpack's new max_str_length value. As far as I know there's no workaround available in Salt. I had to downgrade msgpack for my api-connected tools to continue working.

**Setup**
Salt 2019.2.4 or 3000.2 with python-msgpack > 0.5.6

**Steps to Reproduce the behavior**
Attempt to retrieve a lot of information (for example a full copy of the minion data cache) from rest_cherrypy. If you tail the Master log, you'll see the data is generated and retrieved, but cannot be passed to salt-api because it is larger than msgpack's max_str_length value.

**Expected behavior**
salt-api gives you the information you ask for

**Comment by twangboy** [comment] 2020-04-30 23:30
@V3XATI0N We need more information to be able to test the issue you're seeing. What commands exactly are you running? Minion config? Versions report? What is the exact message you're seeing in the master log? Exactly what version of msgpack did you try? Anything else that would be helpful in replicating this issue?

**Comment by V3XATI0N** [comment] 2020-05-01 00:24
the commands i sent:
`salt-run cache.grains tgt=\*` (this works fine)

via the API:
```json
{
  client: "runner"
  tgt: "*"
  fun: "cache.grains"
}
```
this fails with the error:
```
2020-04-30 13:42:29,036 [salt.transport.ipc:198 ][ERROR   ][12971] Exception occurred while handling stream: 1310589 exceeds max_str_len(1048576)
```

version report (same on master and minion, though the minion is irrelevant for this issue):
```
Salt Version:
           Salt: 3000.2
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.9.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.25.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.25.1
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1032-gcp
         system: Linux
        version: Ubuntu 18.04 bionic
```
The issue is currently resolved, but I downgraded python-msgpack to `0.5.6`.

Also note you need to have a substantial amount of data in the minion data cache to trigger this error. You won't run into it if you just spin up a few minions I have about 450 minions and quite a bit of pillar data on the instance that encounters the problem. A separate master that controls only 100-120 minions and only minimal pillar data doesn't have the issue.

The problem isn't with the minion data cache itself - on the master CLI, that works fine. It only breaks when trying to pass the data through salt-api to an HTTP client (and maybe/probably in other areas too that I just didn't run into in my use case).

**Comment by lukasraska** [comment] 2020-05-01 12:41
The same problem affects minions as well. This is because msgpack changed max_str_length to 1MB in 0.6.0 (https://github.com/msgpack/msgpack-python/issues/295), then promptly increased the limit to 100MB in 1.0.0 (https://github.com/msgpack/msgpack-python/pull/391), however there are repos where msgpack is between 0.6.0 and 1.0.0 (for example RHEL 8, or Ubuntu 18.04 in this case).

Quick&dirty fix is to add `kwargs["max_buffer_size"] = 100*1024*1024` into https://github.com/saltstack/salt/blob/v3000.2/salt/utils/msgpack.py#L56 , but I will try to create PR with tests in upcoming days if nobody from Salt Core team handles that first.

**Comment by V3XATI0N** [comment] 2020-05-01 16:13
thanks for the insight, @lukasraska

**Comment by oeuftete** [comment] 2020-05-02 14:01
I believe this is a duplicate of https://github.com/saltstack/salt/issues/54884.

**Comment by jothibasu-kamaraj** [comment] 2020-05-11 13:31
> The same problem affects minions as well. This is because msgpack changed max_str_length to 1MB in 0.6.0 ([msgpack/msgpack-python#295](https://github.com/msgpack/msgpack-python/issues/295)), then promptly increased the limit to 100MB in 1.0.0 ([msgpack/msgpack-python#391](https://github.com/msgpack/msgpack-python/pull/391)), however there are repos where msgpack is between 0.6.0 and 1.0.0 (for example RHEL 8, or Ubuntu 18.04 in this case).
> 
> Quick&dirty fix is to add `kwargs["max_buffer_size"] = 100*1024*1024` into https://github.com/saltstack/salt/blob/v3000.2/salt/utils/msgpack.py#L56 , but I will try to create PR with tests in upcoming days if nobody from Salt Core team handles that first.

Any update on When we are going to get the fix for this ?

**Closed** 2020-10-08 14:23 UTC
Labels: Bug, Info Needed
