### ISSUE TITLE
file.makedirs loops if path is not absolute

### ISSUE THREAD

**Issue by sastorsl** [saltstack/salt#36149] opened 2016-09-08 14:25 UTC
### Description of Issue/Question
Salt module function file.makedirs loops if the path given is not absolute. More specifically the `directories_to_create` list is not populated.

### Setup
Try to use file.makedirs on a relative path.

### Steps to Reproduce Issue
In an execution module:

    result = __salt__['file.makedirs']('tmp/directory')

At the command line:

    salt-call file.makedirs tmp/directory

### Versions Report
Seems like this bug has been around since 2015.5 or even longer back.
It's the same code in `develop`

    Salt Version:
               Salt: 2016.3.3

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Apr  9 2015, 11:03:32)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.3.1
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 3.2.5

    System Versions:
               dist: redhat 7.1 Maipo
            machine: x86_64
            release: 3.10.0-229.14.1.el7.x86_64
             system: Linux
            version: Red Hat Enterprise Linux Server 7.1 Maipo

**Comment by sastorsl** [comment] 2016-09-08 14:31
I'm working on a PR for this now.

**Comment by sastorsl** [comment] 2016-09-08 15:01
Seems like this might be similar to or a duplicate of https://github.com/saltstack/salt/issues/34478
At least the commited fix.

I propose rather a test at the top

    path = os.path.expanduser(path)

    if not os.path.isabs(path):
        msg = 'Failed: The path \'{0}\' must be an absolute path'.format(path)
        raise SaltInvocationError(msg)

**Comment by Ch3LL** [comment] 2016-09-09 17:00
yes this seems like it is a duplicate of #34478. Does the current fix work for you? If you want to propose a different fix feel free to submit as a PR and it can be given more of an expert review by @cachedout  whether its the better solution.  Are you okay closing this and tracking the issue on 34478 though?

**Comment by Ch3LL** [comment] 2016-09-21 22:00
@sastorsl want to make sure you were taken care of on this issue? Looks like it is resolved but you had some concerns about a different approach to the fix. Were you able to submit as a PR for further review? Any questions?

**Comment by sastorsl** [comment] 2016-10-06 13:54
Have not been able to address this in a PR, so if the duplicate takes care of it please close my issue as fixed.

**Comment by Ch3LL** [comment] 2016-10-11 21:01
Im going to verify with the user on the other user just to make sure it resolves the issue in his case as well and then i'll close both these up. Thanks

**Comment by Ch3LL** [comment] 2016-10-12 21:53
Closing user verified it fixed their issue. Thanks

**Closed by Ch3LL** 2016-10-12 21:53 UTC
Labels: Duplicate
