### ISSUE TITLE
[2018.3.1] salt.loaded.int.utils.boto3.__virtual__() is wrongly returning `None`

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#48121] opened 2018-06-14 05:51 UTC
### Description of Issue/Question
Running a highstate results in seeing the following error and warning:
```
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.utils.boto3. Module will not be loaded: 'module' object has no attribute '__version__'
[WARNING ] salt.loaded.int.utils.boto3.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto3', please fix this.
```

This particular machine does not have any boto package installed:
```
root@web01:~# dpkg -l | grep -i boto
root@web01:~# 
```

```
root@web01:~# pip list --format=columns | grep -i boto
root@web01:~# 
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-12-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by gtmanfred** [comment] 2018-06-14 13:48
This is fixed in https://github.com/saltstack/salt/pull/47726

And will be added in 2018.3.3, unless we sneak it into the quick bugfix for 2018.3.2... let me ask.

**Comment by gtmanfred** [comment] 2018-06-14 13:53
Looks like this will have to wait for 2018.3.3

**Comment by gtmanfred** [comment] 2018-06-14 13:53
Duplicate of #47694

**Closed by gtmanfred** 2018-06-14 13:53 UTC
Labels: 2018.3.3, Fixed Pending Verification

**Comment by billscheidel** [comment] 2018-06-25 04:35
Is there a work around to this issue in the meantime? I'm on Ubuntu 16.04 and currently can't run any salt commands, the minions are always not responding.
